_inc/client/components/module-settings/module-settings-form.jsx, _inc/client/traffic/style.scss, _inc/client/traffic/verification-services/google.jsx
Fixes #
* Builds on https://github.com/Automattic/jetpack/pull/10248
* If no token but local config on page load, enter "manual" UI
* Add cancel button to go from manual UI to chooser
Desktop
Mobile
* When site has config but no token in WPCOM, should show "manual" UI
* When editing manually then Cancel should go to chooser
=> Site verify cancel button and tweak status

json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Fixes #10071
* Add an isset check to avoid PHP notice
=> Add an isset check to avoid PHP notice

modules/photon-cdn.php
This handles cases where the url looks like `/wp-admin/admin-ajax.php?action=get_my_whatever_css` -- which ends in `css`
I'm having a hard time thinking of things we'd want to rewrite that wouldn't end in `css` or `.js` and would include a `?` in the path.  Open to ideas though.
- Add a filter to your site that would enqueue an URL that looks like CSS but is actually not:
```
add_action( 'init', function() {
wp_enqueue_style( 'blablablab', '/wp-admin/admin-ajax.php?action=get_my_whatever_css' );
});
```
- See that CDN will rewrite that request to serve it from the CDN.
- Use this PR, see that the request does not get rewritten to be served from CDN, but instead goes to your site directly.
- You will see request errors in both cases, the only difference is the URL.
Fixed Jetpack CDN …
=> Add additional checks to CDN to avoid rewriting too many paths.

docs/guides/gutenberg-blocks.md
This is essentially a Markdown version of @simison's Google Doc, so all props to him :star: 
- View in [visual mode](https://github.com/Automattic/jetpack/blob/d86c752bfd4f7b68fe35a8613596e71a9ee5ccec/docs/guides/gutenberg-blocks.md), verify that layout is fine
- Follow instructions, verify that they work
=> Docs: Add Gutenberg SDK doc

class.jetpack.php, tools/builder/frontend-css.js
Follow up for #10153
The files were not enqueued anymore as of the PR above, but the CSS
did not get added to the jetpack.css file that is enqueued instead of the singular files.
2. run `gulp frontendcss`
3. Check that `css/jetpack.css` was updated and includes the necessary CSS.
4. Add the 2 widgets to a site where `WP_DEBUG` is set to `false`.
5. Make sure the widgets look good.
* Widgets: fix missing CSS for the Authors and the Social Icons Widgets.
=> Widgets: concatenate author and Social Icons widget CSS

modules/sitemaps.php, modules/sitemaps/sitemap-state.php, modules/sitemaps/sitemaps.php
* Don't try to call up sitemaps with a passed object through a cron job.
* New JN site.
* Activate sitemaps and immediately check it.
* Within a couple of minutes, is the sitemap present?
* Improve initial sitemap creation process.
=> Sitemaps: Ensures sitemap creation immediately upon activation

class.jetpack.php
Expose a global variable identifying the dynamic URL base for Gutenberg SDK-built assets. This allows for splitting.
See companion PR: https://github.com/Automattic/wp-calypso/pull/27274
`gutenpack-jn` (Add `&calypsobranch=update/conditional-module-load`)
=> Gutenberg: Add global JETPACK_BLOCK_ASSETS_BASE_URL

docker/README.md, docs/development-environment.md
Having the `https` based URL may be confusing for folks onboarding.
* Updates `docker/README.md` to have the `git` based version of the URL for the Jetpack repo.
* Updates `docs/development-environment.md` to have the `git` based version of the URL for the Jetpack repo.
* Check the rendered version of the docs, confirm the URL looks fine.
* [docker/README.md](https://github.com/Automattic/jetpack/blob/fix/docker-docks-git-path/docker/README.md#to-get-started).
* [docs/development-environment.md](https://github.com/Automattic/jetpack/blob/fix/docker-docks-git-path/docs/development-environment.md#a-note-on-node-versions-used-for-the-build-tasks).
=> Docs: Update repo URL from https to git based

_inc/client/traffic/verification-services/google.jsx
Fixes #10296
* Change jetpack_site_verification_google_verify_error property name
1. Point Jetpack to your sandbox
2. Add `return new WP_Error( "artificial-error", "Artificial Error for Documenting" );` to line 206 of `google-site-verification-client.php` ( the `verify_site` method ) or introduce and error into the verify site process somewhere else
3. Attempt to Auto-Verify the Site
4. Confirm that you eventually receive the ""Artificial Error for Documenting" Error
5. Navigate to Track live view and look for event `jetpack_site_verification_google_verify_error`
Confirm that your event eventually appears
6. Confirm that the event has the `error_message` property with the value "Artificial Error for Documenting"
* Change jetpack_site_verification_google_verify_error property name
=> Rename jetpack_site_verification_google_verify_error prop

modules/theme-tools/featured-content.php
Fixes #7996
* Returns early if it is a REST or XMLRPC request, in addition to admin.
* Setup a site with a featured-content using theme (I tried with Axon from WP.com's theme directory).
* Add a post with the tag "featured"
* Via Customizer, visit Featured Content, set tag as `featured`, and check the option to hide tag.
* Visit the front end and see the tag not present on the permalink page of the post.
* Visit the WP.com Editor for the post, see the tag is also missing.
* Apply patch.
* Revisit front end, confirm tag is still hidden.
* Revisit WP.com Editor, not see the tag is present.
* Featured Content: No longer hides the "featured" tag from the WordPress.com Editor or the mobile apps.
=> Featured Content: Prevent tag hiding from REST API interactions

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes #10254
* Strip Meta Tags from Verification Values when checking changes
1. Navigate to Jetpack -> Settings -> Traffic -> Site verification
2. Set a value in the Bing, Pinterest, or Yandex Fields
3. Save the value by pressing enter or clicking "SAVE SETTINGS"
4. Temporarily modify the value, then revert your changes so that the "SAVE SETTINGS" Button is a clickable blue
5. Save the value by pressing enter or clicking "SAVE SETTINGS"
6. Confirm that the a "green check" notification with the test "Updated Settings" appears
* Strip Meta Tags from Verification Values when checking changes
=> Fix Error on Verification Settings No Change

modules/sitemaps/sitemap-builder.php
Fixes #10033
* Decode HTML entities on site name before adding it to the news sitemap to prevent double encoding issues.  These are encoded by WordPress core and stored encoded in the database, so it's not as easy as just removing a filter.
* Set up or change a site to have the site name (`blog_name`) contain an ampersand (`&`).
* Enable Jetpack Sitemaps
* Post a new post to generate a new news sitemap.
* Visit `/news-sitemap.xml` and view double encoded ampersands in the `<news:name>` tag.
* Apply Patch
* Post a new post to generate a new news sitemap.
* Visit `/news-sitemap.xml` and view single encoded ampersands in the `<news:name>` tag.
Sitemaps: Remove double encoding of site name in news sitemap.
=> Sitemaps: Remove double encoding of site name

modules/sitemaps.php, modules/sitemaps/sitemap-buffer-fallback.php, modules/sitemaps/sitemap-buffer-image-fallback.php, modules/sitemaps/sitemap-buffer-master-fallback.php, modules/sitemaps/sitemap-buffer-news-fallback.php, modules/sitemaps/sitemap-buffer-page-fallback.php, modules/sitemaps/sitemap-buffer-video-fallback.php, modules/sitemaps/sitemap-buffer.php, modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-librarian.php, modules/sitemaps/sitemap-logger.php, modules/sitemaps/sitemap-state.php, modules/sitemaps/sitemaps.php
After digging in to figure out the initial creation issue ( #10274 ), I made a pass at the other pending issues.
Fixes #7992 #8549 #9159 #9363
* Updates a concatenated string to a single string.
* Checks if the home_url is a static page and if so, do not include it in the sitemap (as it would already be included when pages are added to the sitemap)
* Modifies the "no sitemap" error when visiting sitemap.xml for logged-in admins to display the next cron run time.
* When the sitemap data is reset following a Jetpack upgrade, schedule a new generation task one minute in the future. Before, it would wait until the next scheduled attempt, which could be up to 12 hours under default settings.
* Site with Sitemaps already active.
* Set the home page as a static page.
* Bump the version within JP …
=> Sitemaps: Various improvements

modules/protect/math-fallback.php
Adds a single space before each line break in the jetpack_protect_num input tag in order to allow a space to be maintained between the tag name and the attributes when output is buffered. This would maintain compatibility with front end login plugins that need to buffer the output and collect it in ob_get_contents() so it can be displayed in a widget or main content.
Fixes #
* Add a single space before each line break in the jetpack_protect_num input tag, most importantly between "<input" and "type="
* The problem does not present itself when Protect is used somewhere like wp-login.php.  However, when used with a front end login plugin that needs to buffer output (such as WP-Members), line breaks are lost.  So testing with WP-Members would show the issue.
* Added white space before line …
=> Protect: update math_form() method input tag

_inc/client/traffic/style.scss
Missing commit from https://github.com/Automattic/jetpack/pull/10263#pullrequestreview-162257922
@joanrho said:
> It could use the same consistent margin below the "Edit" button just above the jp-form-setting-explanation on mobile views. Setting .jp-form-input-with-prefix-bottom-message as -1.25rem instead of -1.5rem seemed to achieve the same visual result if you want to do it that way.
The difference is very subtle:
Before:
After:
=> Narrower bottom border on site verify description

bin/pre-commit-hook.js, composer.json, docs/development-environment.md, package.json
These scripts, defined in `package.json` and `composer.json` actually check for compatibility among a few versions of PHP and not just 5.2. 
* Updates every reference reading `php:5.2-compatibility` to `php:compatibility`.
* Standing on the Jetpack source directory.
* Run `yarn php:compatibility .`  Confirm everytning runs ok although a few warnings are shown.
* Run `composer php:compatibility` and expect the same results.
* Check the [rendered version of development-environment.md](https://github.com/Automattic/jetpack/blob/update/rename-php-5.2-compatibility/docs/development-environment.md#checking-jetpacks-php-for-compatibility-with-different-versions-of-php-since-52).
cc @jeherve @brbrr makes sense? 
Shouldn't make it into the changelog probably
=> Proposal: Update npm/yarn and composer commands php:5.2-compatibility to just php:compatibility

docs/partners/plan-provisioning-direct-api.md
This functionality was only intended to be used by VIP Go and internal "partners". After being initially added, we have now removed the functionality. I removed final traces of `wpcom_user_email` in D19364 so now no mention of `wpcom_user_email` is found in the API.
This functionality is planned to become more widely available to hosting partners in the near future with automated account creation and connection, which won't use this `wpcom_user_email` parameter either. 
* Remove mention of `wpcom_user_email` in Jetpack partners documentation.
* Check that all mention of `wpcom_user_email` removed from `docs/partners` directory.
Removes mention of `wpcom_user_email` from partner documentation.
=> Docs: JPS: Remove mention of wpcom_user_email

class.jetpack.php, tools/builder/frontend-css.js
Follow-up from #10280
One list is for the files being dequeued.
The other list is for the content of those files to be concatenated into jetpack.css.
The 2 lists should match, but that was not the case. I updated them.
Noting that I also removed The IDC file since it is meant to be used in wp-admin only.
Ensure that the CSS file used to style Quizzes (shortcode) is not inserted when adding a quiz to your site like so:
https://en.support.wordpress.com/quiz-shortcode/
The quiz should still be styled properly thanks to CSS added to `jetpack.css`.
Noting that `WP_DEBUG` should be set to `false` on your site while testing.
CSS Concatenation: make sure all concatenated CSS is up to date.
=> CSS concatenation: fix differences between what the 2 lists.

class.jetpack-gutenberg.php
The `@wordpress/edit-post` dependency is needed for the Publicize Gutenberg extension to work.
* Add `@wordpress/edit-post` dependency to our Gutenberg block assets.
* Do a fresh `yarn distclean && yarn build`.
* Verify build still works well.
* Verify `edit-post` assets are included while in the Gutenberg editor.
=> Gutenberg: Add @wordpress/edit-post dependency

json-endpoints/class.wpcom-json-api-get-comments-tree-endpoint.php, json-endpoints/class.wpcom-json-api-update-comment-endpoint.php, modules/carousel/jetpack-carousel.php, modules/sitemaps/sitemap-librarian.php, packages/sync/src/modules/class-comments.php, tests/php/sync/server/class.jetpack-sync-test-object-factory.php, tests/php/sync/test_class.jetpack-sync-comments.php, tests/php/sync/test_class.jetpack-sync-woocommerce.php
This is to bring us in line with recent core changes:
https://core.trac.wordpress.org/changeset/47597
https://core.trac.wordpress.org/ticket/49236
> Use `comment` instead of an empty string for the `comment_type` DB field value in comments table.
* Can you post comments on a Carousel modal? Are they saved in the db properly?
* Comments: update how comment types are stored to be fully compatible with upcoming WordPress Core changes.
=> Comments: update default comment type

modules/shortcodes/recipe.php, tests/php/modules/shortcodes/test-class.recipe.php
* For the [Recipe shortcode](https://wordpress.com/support/recipes/) in AMP, changes the 'Print' link to 'Print page,' and it now prints the entire page 
* No intended change to non-AMP
* In AMP, it's not possible to only print only the recipe, like on non-AMP
* Printing only the recipe is [done with a jQuery plugin](https://href.li/?https://github.com/Automattic/jetpack/blob/feeadafa22309b7cf0d77077c0354d9df1f74eda/modules/shortcodes/js/recipes-printthis.js).
* Even `<amp-script>` doesn't look possible here, as it [doesn't allow](https://amp.dev/documentation/components/amp-script/#creating-amp-elements) creating an `<iframe>`
* This enhances an existing feature
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here:
pbIAo1-1m-p2
1. Ensure the …
=> Recipe shortcode: on AMP, change the Print link

extensions/blocks/podcast-player/templates/podcast-header.php
* Moves the `podcast-header-title` template rendering outside of the `$show_cover_art` `if` statement so that the title will show even if no cover art is available.
| before  | after |
|<img width="781" alt="Screen Shot 2020-04-21 at 8 58 52 AM" src="https://user-images.githubusercontent.com/967608/79875192-e6537a00-83ae-11ea-89b1-33fcd6657338.png">| <img width="777" alt="Screen Shot 2020-04-21 at 8 58 35 AM" src="https://user-images.githubusercontent.com/967608/79875199-e9e70100-83ae-11ea-8257-1f75647fc30f.png">|
* Create a podcast player block and set the Show Cover Art option to false.
* Publish
* Go to the front-end.
* Turn off JavaScript so you only see the PHP server-side rendered template
* You should see the podcast player titles, but no image. …
=> Podcast Player: Show header template even if no cover art is available

class.jetpack-network-sites-list-table.php
* For the Sites list table in Network Admin when Jetpack (beta version via the beta plugin) is network-activated, show all sites where either Jetpack stock or Jetpack beta is active.
* n/a
* Multisite with multiple subsites
* Network activate Jetpack
* Before PR, unable to manage subsites (see screeshot)
* After PR, able to manage subsites.
* Beta: When using a beta version of Jetpack via the Jetpack Beta Plugin, allow subsite connections to be managed in Network Admin.
=> Multisite: Check for the Beta Plugin managed version

tests/e2e/bin/push-allure-artifacts.sh
It seems that the script is failing now due to too much logging. I removed unneeded logging since it's work fine right now. 
* Check E2E build log. make sure the `after_script` section is finished successfully
* n/a
=> Travis CI: Remove unneeded logging in push artifacts script

extensions/blocks/podcast-player/style.scss
Fixes https://github.com/Automattic/jetpack/issues/15469
Fixes https://github.com/Automattic/jetpack/issues/15478
Except for:
- Twenty Thirteen editor mejs background. Front-end is fine.
- Twenty Fourteen mejs player which includes a lot of customizations to the mejs player. We'd have to bump the specificity a bit and add quite a few overrides. Maybe it's best not to touch that one unless there's strong data to suggest fixing it.
We've decided not to fix the Twenty Thirteen or Twenty Fourteen mejs player issues: https://github.com/Automattic/jetpack/issues/15478#issuecomment-617384963
**Global Styles in action**
**Twenty Fifteen (and others) that used `text-decoration` or `box-shadow` or `border-bottom` styles on links**
| before  | after |
| <img …
=> Podcast Player: Improve themes compatibility

json-endpoints/class.wpcom-json-api-update-comment-endpoint.php
This is a follow-up on #15494.
Let's not create "comment" type comments that are then displayed in areas handled by themes just yet. A lot of themes are not yet ready to handle comments that have a comment type other than an empty string.
We can apply this change once WordPress 5.5. ships, since there will then be a dev note published helping theme authors update their theme to take this into account.
Until then, let's only support the new comment type when pulling comments, and let's use the comment type in comments that are displayed via Jetpack, such as in the Carousel.
Internal reference: p2EDhh-14W-p2
There shouldn't be a lot to test, we're going back to the previous behaviour where comments created via the API (such as when replying to a comment via the Notifications panel or the …
=> Comments: do not create comments with the comment type just yet

bin/phpcs-whitelist.js, dangerfile.js
When adding a new PHP file, we ask folks add it to the bin/phpcs-whitelist.js file, but don't make that as clear as we could.
* Improve messaging.
* n/a
* Add a new PHP file to this branch and push a new PR to see the error.
* n/a
=> Build: Improve Danger's whitelist message

tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/plan-helper.js, tests/e2e/lib/setup-env.js, tests/e2e/specs/connection.test.js, tests/e2e/specs/free-blocks.test.js, tests/e2e/specs/pro-blocks.test.js
Before this PR, for every test suite, we would create a new site (actually reset the existing one, and generate new URL). This is quite time-consuming. In this PR I tried to reuse created site, and tweak its state by messing around with plan data and  `jetpack_private_options` option. Seems like it saves us around 80 sec comparing to `master` build. 
Thanks @dereksmart for the suggestion!
* No functional changes were made. 
* Travis tests should be green
* n/a
=> E2E Tests: Add Connection mocking

extensions/blocks/podcast-player/components/header.js, extensions/blocks/podcast-player/components/track-error.js, extensions/blocks/podcast-player/components/track.js, extensions/blocks/podcast-player/style.scss, extensions/blocks/podcast-player/templates/playlist-track.php, extensions/blocks/podcast-player/templates/podcast-header.php, extensions/blocks/podcast-player/templates/podcast-title.php
Built on top of #15504 as a part of completing the remaining Podcast Player improvements. My main goal was to go through styles.scss and clean it up a bit to minimize technical debt. On the way, I found a few small bugs and decided not to create separate issues for them as they kind of fixed themselves while cleaning up the code :)
Maintenance:
- Removed duplicated SCSS variables,
- Renamed some SCSS variables for clarity,
- Used available SCSS variables for hardcoded values where possible,
- Unified gutter and some paddings into simple `$gutter-s/m/l` vars,
- Cleaned up and made colors styles more consistent and easy to follow,
- Cleaned up a few misplaced comments.
Bugfixes:
- Made links styling consistent (Podcast title, Track title, Error message)
Links have the Secondary color …
=> Podcast Player: Clean-up styles & fix few remaining issues

_inc/client/at-a-glance/backups.jsx, _inc/client/components/footer/index.jsx
Fixes #15455 
External URLs should be created using the jp-redirect library. Use the jp-redirect library to create:
* The `https://dashboard.vaultpress.com` URL in the AAG backups card.
* The `https://jetpack.com` URL in the dashboard footer.
* Jetpack must be activated and connected.
* VaultPress must be activated.
1. Run `yarn build` to build the new front-end files.
2. Navigate to the Jetpack dashboard. In the footer, check the **Jetpack version** link. It should be a redirect link: `https://jetpack.com/redirect/?source=jetpack`. Click the link and confirm that you’re directed to `jetpack.com`
3. While still on the Jetpack dashboard, check the **View backup details** link in the Backup card. It should be a redirect link: …
=> Admin Page: update a few URLs to use jp-redirect

packages/redirect/src/class-redirect.php, packages/redirect/tests/php/bootstrap.php, packages/redirect/tests/php/test_Redirect.php
After D42161-code, our redirect service also accetps a `url` parameter that will redirect the visitor to this URL without the need of registering this url in our backend beforehand. This will only work for a few Automattic domains.
This PR adds the possibility of creating such links using the `Redirects` package.
* Run the package unit tests:
```
cd packages/redirects
composer run phpunit
```
* Create some output to test links:
```PHP
use Automattic\Jetpack\Redirect;
// ...
?>
Check if this links creates an URL pointing to jetpack.com/redirect?url=https%3A%2F%2Fwordpress.com%2Fsupport
Click on it and see if it works.
<a href="<?php echo Redirect::get_url( 'https://wordpress.com/support' ); ?>">Link</a>
```
```PHP
use Automattic\Jetpack\Redirect;
// ...
?>
Check if this links creates an …
```
=> add support to direct url to Redirects::get_url

tests/php/modules/shortcodes/test-class.recipe.php
This is a follow-up from #15477. It updates the tests to match the markup.
I am not exactly sure how the tests were okay for that last PR. But this should fix tests failing in `master` from now on.
* N/A
=> Recipes: update tests after markup update

_inc/lib/plans.php
Differential Revision: D41787-code
This commit syncs r206104-wpcom.
This makes updates to the methods in Store_Product_List that were previously setting different attributes on the Store_Product to generate responses for the API endpoints.
Instead, this is now generating generic objects to be used as DTO's for the purpose of the API.
This did require updating some methods outside of the Store_Product_List to make sure they were using the methods that returned Store_Products[] vs the DTO's where necessary.
Built in tests.
I also applied D41723-code, which can be used to generate JSON output from the API endpoints that use the Store_Product_List and can be compared before and after applying this patch.
* N/A
=> Store Product List: Stop setting attributes on the Store_Product class object to fill in data for the API responses

modules/shortcodes/crowdsignal.php, tests/php/modules/shortcodes/test-class.crowdsignal.php
This commit syncs r206118-wpcom. Crowdsignal survey iframes are always loaded, and fallback to a plain link if the load didn't succeed. I removed the `AMP` specific test since the change now outputs the same link with or without `AMP` running.
**Testing instructions:**
* You'll need a Crowdsignal shortcode to add to a post or two. Here's one `[crowdsignal type="iframe" survey="D29C2F3267E6A603" height="auto" domain="7iger" id="a-phone-number-test"]`
* Add the shortcode to a post, and view it in the main posts page for a site. The survey should be visible: 
* View the `/amp` version of the post, it should show a simple `Take Our Survey` link:
* Enable infinite scroll for a theme that supports it. Depending on how the theme processes shortcodes for asynchronously loaded posts, it will …
=> Crowsignal shortcode: Always attempt to embed survey iframe. Refs D42082

modules/wordads/wordads.php
The "Standard" mode for the Google AMP plugin is AMP first. This means that when this mode is enabled, a user will see the AMP version of the website, regardless of device, the site being served from an AMP Cache or being viewed using a specific AMP endpoint. 
We should thus, render a larger Word Ads size when an AMP version of the website is being viewed on a desktop browser.
Fixes #15400
* This enhances and existing feature
* P2 shortlink: https://wp.me/pbIAo1-17
1. Ensure the AMP plugin is active
2. In AMP > Settings, select Standard mode
3. Enable Word Ads in Jetpack > Settings > Traffic > Ads
4. Visit a post on the front end on a desktop browser with ?amp appended to the URL, and make sure a 300*250 ad is showing above post content.
5. Visit a post on a mobile device with ?amp …
=> WordAds - AMP Compatibility

extensions/shared/styles/gutenberg-base-styles.scss
Fixes #14524
* Sets width of vertically aligned columns to properly constrain child blocks such as Slideshow in older versions of WordPress and Gutenberg.
_Without specifying the width, nested blocks such as slideshow, overflow the column. Setting the width to 100% constrains them as expected._
1. Start up version 5.3 of WP with this fix.
2. Edit a blog post or page with block editor.
3. Add a column block (2 columns of 50%)
4. In the first column add a slideshow block and add some images to it.
5. Add a paragraph of text into the second column.
6. Select the first column and set the vertical alignment to top.
7. Slideshow block should still be bound by the column it is in.
_You can see the original behaviour by inspecting the column via dev tools and toggling off the width CSS property …
=> Block Editor: Set width for vertically aligned column

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, sal/class.json-api-site-base.php
Differential Revision: D42191-code
This commit syncs r206374-wpcom.
This patch saves the value of the `site_creation_flow` option as a site option.
We're doing this so we know which onboarding flow the user completed to create a particular site.
More specifically, we'd like to identify sites created in the Gutenboarding signup flow so we can customize the editor UI.
https://github.com/Automattic/wp-calypso/issues/41300#issuecomment-617065342
Run https://github.com/Automattic/wp-calypso/pull/41349
Create a site via `/new`.
When you finally land in the editor, filter the XHR network requests in your browser's console by `me/sites`
Check that the option is set.
* N/A
=> Onboarding: saving the site creation flow as a site option

packages/autoloader/src/class-plugins-handler.php, packages/autoloader/tests/php/bootstrap.php, packages/autoloader/tests/php/test_plugins_handler.php
This branch is based on the `feature/update_autoloader` branch.
* Refactor `Plugins_Handler` by adding a few methods. This change will make the class easier to test. The new methods are:
* `get_multisite_plugins()`
* `get_active_plugins()`
* Add unit tests for `Plugins_Handler`.
* This branch includes a small refactor, so make sure that Jetpack still works without errors.
* n/a
=> Autoloader: refactor Plugins_Handler and add unit tests

_inc/client/lib/jp-redirect/index.js
After D42161-code, our redirect service also accetps a `url` parameter that will redirect the visitor to this URL without the need of registering this url in our backend beforehand. This will only work for a few Automattic domains.
This PR adds the possibility of creating such links using the `Redirects` package.
This is the JS relative of https://github.com/Automattic/jetpack/pull/15525
Note: This lib is being moved to its own npm package. There are tests there, so these changes should be fine: https://github.com/Automattic/wp-calypso/pull/41497
* Create some test links:
```
import getRedirectUrl from 'lib/jp-redirect';
const url = getRedirectUrl( 'https://wordpress.com/support' );
```
Check if this links creates an URL pointing to …
=> adds support for direct URL to getRedirectUrl lib

3rd-party/class-jetpack-bbpress-rest-api.php, _inc/lib/class.jetpack-password-checker.php, _inc/lib/class.jetpack-photon-image.php, class.jetpack-network.php, class.jetpack-post-images.php, class.jetpack.php, class.photon.php, modules/sitemaps/sitemap-buffer-fallback.php, modules/subscriptions.php, packages/compat/legacy/class-jetpack-client.php, packages/compat/legacy/class-jetpack-sync-actions.php, packages/connection/legacy/class-jetpack-xmlrpc-server.php, packages/connection/src/class-client.php, packages/connection/src/class-manager.php, packages/sync/src/modules/class-full-sync-immediately.php, src/class-tracking.php, tests/php/test_class.jetpack_photon.php
Change inline documentation types of `Array` to `array`. The current version is confusing to some IDEs.
* Updated inline PHP documentation to correctly indicate the `array` type.
=> Correct inline documentation "Array" type

extensions/blocks/podcast-player/style.scss
* Fix the last line of the description text being cut off a few pixels from the bottom:
| | Before  | After |
| - | ------------- | ------------- |
| `line-clamp` (modern browsers) | <img width="796" alt="Screenshot 2020-04-27 13 23 14" src="https://user-images.githubusercontent.com/1451471/80372092-422c7000-8893-11ea-8e89-7aeb70df088d.png"> | <img width="797" alt="Screenshot 2020-04-27 14 27 26" src="https://user-images.githubusercontent.com/1451471/80372123-4d7f9b80-8893-11ea-91ca-5c880b30c88b.png"> |
| `max-height` (IE11) | <img width="779" alt="Screenshot 2020-04-27 14 46 03" src="https://user-images.githubusercontent.com/1451471/80374192-938a2e80-8896-11ea-8ab1-6b17517951b5.png"> | <img width="799" alt="Screenshot 2020-04-27 14 38 05" …
=> Podcast Player: Fix cropped description text & title wrapping

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php, bin/phpcs-whitelist.js, extensions/blocks/instagram-gallery/edit.js, extensions/blocks/instagram-gallery/use-connect-instagram.js
* Update the `WPCOM_REST_API_V2_Endpoint_Instagram` endpoint to `WPCOM_REST_API_V2_Endpoint_Instagram_Gallery` as the former already exists on WPCOM.
Note: this needs to be synced in D42516-code
* Smoke test the Instagram Gallery block.
* Does the "connect to Instagram" flow work?
* Does it load the gallery?
* Does the "disconnect" flow work?
* N/A (unreleased block)
=> Instagram Gallery Block: Rename Instagram endpoint to Instagram_Gallery

packages/autoloader/tests/php/test-version-selector.php, packages/autoloader/tests/php/test_Autoloader.php, packages/autoloader/tests/php/test_file_loader.php
This branch is based on the `feature/update_autoloader` branch.
* Add unit tests for the `Version_Selector` class
* Confirm that the tests didn't fail.
* n/a
=> Autoloader: add unit tests for the Version_Selector class

bin/update-package.sh
* Some of our packages, compat and options, do not have a src directory. That should not stop us from updating those packages.
* Not much should change. In future PRs that modify the packages above, the action should be triggered and the packages should be updated.
* N/A
=> Actions: do not bail when a package does not have a src dir

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php, extensions/blocks/instagram-gallery/edit.js, extensions/blocks/instagram-gallery/use-connect-instagram.js
Part of #15276
~Requires D42457-code~
* When the Instagram Gallery block is inserted, checks if the user has already an Instagram access token stored, and use it automatically instead of asking them to connect to Instagram every time.
Note: this needs to be synced in D42516-code
* ~Apply D42457-code and sandbox the API.~
* On a site connected to WPCOM, open the editor and insert an Instagram Gallery block.
* If your user has already an Instagram token stored, the block should (eventually) directly embed the gallery.
* Otherwise, it should show a "Connect to Instagram" button.
* When the block is connected to Instagram, open its sidebar and click on "Disconnect your account".
* Make sure the block is reverted to placeholder state.
Note: this doesn't work across different blocks.
* N/A
=> Instagram Gallery Block: Reuse the Instagram token if already stored

modules/subscriptions/views.php, modules/theme-tools/compat/twentytwenty.css
On WordPress.com (and only on wpcom), Subscription widget titles are wrapped in label tags.
This is problematic with the Twenty Twenty theme, since that theme has custom label styles that overwrite the default widget title style. Let's fix that.
**Before**
**After**
This was originally reported by @kathrynwp here:
https://core.trac.wordpress.org/ticket/49137
* Nothing should change if you use the widget with the Twenty Twenty theme on a Jetpack site; the look of the widget title should match the other titles before and after this patch was applied.
* On WordPress.com (see D42586-code), you should see the changes in the screenshot above.
* N/A
=> Subscriptions Widget: ensure titles are displayed nicely in 2020

modules/comments/comments.php
Spotted a small typo. Quick fix.
=> Fix a small typo in the comments of comment_form_before

class.jetpack-twitter-cards.php
Before this PR we only looked at a feature image in determining if a Twitter card should be `summary` or `summary_large_image`.
Since, of as #15527, we will start deferring to Twitter cards over attached media for Twitter when 8.5 ships, it was reported there is a gap when a site is not using featured images. On the WP.com side, we would look for additional images to send to Twitter. This PR would close that gap by looking for other sources within the post (no fallback to gravatars or site icons).
Fixes p8oabR-uL-p2 item 4160.
* Use additional media beyond featured image.
* Update and enforce Twitter size requirements per their documentation.
* n/a
* Jetpack connected + Publicize or Sharing enabled.
* Write a post with a reasonably large image (over 300x157 at the very least) in the …
=> Twitter Cards: Use additional images.

packages/jitm/src/class-jitm.php
I'm not sure why this is explicitly disabled. It seems to work just fine in my testing.
Testing:
- connect your jp site to a wp.com sandbox
- modify jitm-engine to remove the message_path() call for one of the existing messages (maybe also remove a few other checks so that it shows everywhere for you)
- Go to the old stats page in the wp-admin dashboard and verify that the message is shown.
=> JITM: Allow JITM on stats pages

extensions/blocks/podcast-player/podcast-player.php
* Suppress all block errors to public visitors, as other blocks do too (eventbrite, google cal, instagram gallery to name a few I found)
* what we do extra here compared to other blocks is that we show the error message to users with capability to edit the post. This can be helpful with their debugging.
enhancement of the podcast player, based on the feedback p7DVsv-8oS-p2#comment-28483
* Insert Podcast Player that will error on the frontend:
- for example by just inserting it, not filling anything and hitting preview
- inserting faulty URL (probably only doable through editing post source, because our UI prevents such situations)
* publish the post and check it on the frontend as:
- admin: you should see error
- logged-out visitor (anonymous mode): no error
* Remove visitor-facing fatal …
=> Podcast Player: Only display frontend errors to users capable of editing

extensions/blocks/button/button.php, extensions/blocks/button/edit.js
Fixes #15578
* If the Button block is set to output as `a` or `button`, make sure the inner HTML is rendered.
* If the Button block is set to output as `input`, prevent inserting newlines and strip any HTML tags.
* Insert a Revue block, and add a Revue username (or some random text).
* Smoke test the block CSS classes and styles: set custom colors, change the border radius. Make sure they are rendered as expected in the front end.
* Try inserting a newline in the button text.
* Make sure the newline appears in the front end, and there is no unparsed HTML content.
Now modify the [Revue inner block definition](https://github.com/Automattic/jetpack/blob/a483211b27167830f0adee2c6d31c4062c0dfdb7/extensions/blocks/revue/index.js#L19).
* Change the element into an `a`, and add an `url` attribute …
=> Button Block: Properly render inner HTML if context-appropriate

tests/php/json-api/test-class.json-api-jetpack-endpoints.php
In #11771, we added a check for `JETPACK__PLUGIN_DIR` before adding a file. This constant is defined on WP.com but the file we are including is not.
Adding a wpcom check so we can finish up some fusion work for 11771.
* Add a WP.com conditional.
* n/a
* Unit tests pass.
* n/a
=> Unit Tests: Add WPcom check

sal/class.json-api-post-base.php
Fixes #p2EDhh-zj-p2
Syncs r186840-wpcom with changes staged in D42763-code
When encountering a SimpleXMLElement object in post meta, an exception can be thrown. The core maybe_unserialize() function does not yet handle this scenario.
This patch adds a temporary fix to SAL_Post so that exceptions are handled.
=> SAL Post Base: Capture exception when seralizing

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
This is unused in Jetpack but keeps our files in sync with WP.com
Differential Revision: D42135-code
This commit syncs r206116-wpcom
=> API: Add Earth Day Live API endpoint

tests/php/core-api/wpcom-fields/test-class.subscribers-endpoint.php
There is not reason the core base testcase should not call the parent tearDown method, like all other testcases do.
Core's cache flush is simplified, and the redundant calls compared to the base isolation testcase are removed.
This makes the environment slightly incompatible with the alloptions tests, and reveals a test that should be failing, but reduces the testcase maintenance burden. Fixes are provided for the tests
Test Plan: TC
Differential Revision: D38799-code
This commit syncs r202837-wpcom
=> Unit Tests: share more code with the isolated base testcase

modules/subscriptions.php
Vulnerability scanners often attempt to inject invalid data into any form fields on a website, and when such a scanner does this to a site with the Jetpack Subscription widget on it, it's common to pass an array to the subscription fields.
Ultimately, this causes a PHP Warning to be generated similar to the following:
> E_WARNING: wp-includes/formatting.php:3413 - strlen() expects parameter 1 to be string, array given
That's caused by passing an array to the `is_email()` function, which only accepts strings.
and a PHP Notice similar to:
> E_NOTICE: wp-content/plugins/jetpack/modules/subscriptions.php:688 - Array to string conversion
which is caused by attempting to use `$redirect_fragment` in the redirect later in the function.
* An extra input check to validate that the arguments are …
=> Protect against invalid form input

modules/theme-tools/social-menu.php
Use `restapi_theme_init` -- props @michaeldcain 
This commit syncs r129550-wpcom from too long ago.
=> Social Menu: Make sure Menu is being displayed via Rest API

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
Easy come, easy go.
Summary:
This removes the necessary settings to display banner for Earth Day Live up to and including April 22nd.
Reverses: D42135
Test Plan: Manual testing.
Reviewers: cojennin
Reviewed By: cojennin
Differential Revision: D42822-code
=> Remove Earth Day Live plugin and API endpoint

packages/analyzer/src/Declarations.php, packages/analyzer/src/Declarations/Class_Method.php, packages/analyzer/src/Declarations/Function_.php, packages/analyzer/src/Declarations/Visitor.php, packages/analyzer/src/Differences.php, packages/analyzer/src/Differences/Class_Method_Deprecated.php, packages/analyzer/src/Differences/Function_Deprecated.php, packages/analyzer/src/Utils.php
We currently use the Jetpack Analyzer to scan for changes within WooCommerce versions. One of the things we are looking to improve is the possibility to find any usage of deprecated functions.
This PR provides some changes to the Analyzer classes which allow for detecting deprecated functions and finding invocations of these deprecated functions. In WooCommerce a function is marked as deprecated by adding `@deprecated` to the DocBlock and also a call to `wc_deprecated_function` is used (similar to the WordPress function `_deprecated_function`).
Outline of the changes:
- Visitor class: scan for functions and methods which have the deprecated docblock or a call to a function called `_deprecated_function`
- Utils class: add a helper function for finding a text string within a docblock, add a …
=> Add support for detecting deprecated functions in the Analyzer

modules/widgets/internet-defense-league.php
Related to D42942-code for WP.com backend change.
* Force HTTPS when looading the IDL script
* Use www in IDL URLs to avoid 301 redirects
See docs at https://github.com/fightforthefuture/idl-members/blob/master/docs/embed.md for the updated JavaScript embed code.
* Widgets: enable Internet Defense League
* On front-end of site, confirm no HTTPS mixed content errors
* Widgets: update Internet Defense League for full HTTPS support
=> Widgets: update Internet Defense League for full HTTPS support

_inc/client/at-a-glance/scan.jsx
This PR will make it possible to redirect users to jetpack cloud scanner section. 
By separating the activity log from the scanner section. 
Related D42869-code
* Go to At a Glance. Section. 
* When Jetpack Scan is set up as expected the link to view scanner should still take you to the activity log for now. But in the future we will be sending the user to the scanner section. 
* Nothing to add to the change log this is part of the work that adds jetpack cloud.
=> Scanner: Update the link to take the user to calypso-scanner

packages/sync/src/class-queue.php
It is possible for a buffer to be removed before sync actions are finished processing by WP.com. WHen this happens we end up leaving the items in the queue and they get resent to WP.com for processing causing duplicate actions.
This update ensures that we always delete items from the queue even if the buffer is no longer checked out. 
* Always delete processed sync actions even if buffer is not valid.
* Existing functionality, optimization
* Enqueue large amounts of Sync Actions on your test site
* Perform a `wp jetpack-sync pull --blog-id=XX --queue=sync`
* When `buffer not checked out warnings are displayed the actions will still be removed from the queue.
* N/A - internal optimization to send less duplicate actions. Won't be visible to end users.
=> Jetpack Sync - Queue Cleanup

_inc/client/at-a-glance/connections.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php
Alternative solution to #15647.
Fixes #15646 
Rely on the local user's Gravatar when in development mode, instead of trying to use the connecter WordPress.com user data, which we don't have.
To do that, I repurposed `gravatar` in the initial state we pass alongside the React bundle. We were not using it anymore.
Another approach to solve that problem could be to use a generic icon instead, as suggested in #15647.
To do:
* Start with a brand new site, not connected to WordPress.com yet.
* Add the following to your site's `wp-config.php` file: `define( 'JETPACK_DEV_DEBUG', true );`
* Head to Jetpack > Dashboard
* Check the image at the bottom of the dashboard. It was previously broken, now it shows your local user's Gravatar.
* Admin Page: avoid broken Profile image in the Jetpack …
=> Admin Page: display local user's Gravatar when in dev mode

package.json, yarn.lock
Closes #15413
Investigating `acorn`, which Renovate tagged for an update. We added it as part of #15305 to force use an updated version of `acorn`. Checking the `yarn audit` and dep treee, this resolution is no longer needed, confirming what @brbrr thought.
* Removes resolutions.
* n/a
* Verify Travis. Run `yarn audit` before and after patch.
* n/a
=> Build: Remove unused resolutions

class.jetpack-gutenberg.php
In #14953 I removed the availability check before registering a block. I can't remember why I did this, but now looking at the way we deal with this logic I wonder if we should make this proposed change.
At the moment we make the assumption that if a block is registered it is available, which makes it hard to disable blocks once they have been registered. Here I am proposing that we check that blocks are both registered and available before we show them.
The alternative is to simply add the `is_available` check back to these blocks.
* Apply this patch to your WPCOM sandbox and sandbox a site
* Open the post editor on a free site
* Add an OpenTable and Calendly block
* Check that you still see the upgrade notice in the block editor
* no changelog
=> Fix the availability check logic

modules/shortcodes/crowdsignal.php, tests/php/modules/shortcodes/test-class.crowdsignal.php
This commit syncs r206937-wpcom.
* Fixes `unfurling` of survey.fm links on themes such as P2 that load posts asyncronously so that they get transformed into a proper crowdsignal shortcode and rendered on the front-end.
* Removed inline `display-block` style to get the embed rendering properly within its container.
* Switch your site to the P2 theme.
* Add a new post in the block editor.
* Type `/crowdsignal` to add a new Crowdsignal embed block.
* Paste a survey.fm link into the block, here's one you can use: `https://7iger.survey.fm/test-embed`. 
* The survey should embed into the block editor.
* Publish the post, and view it on the front-end of the site. The embed should also render here.
* Try switching to a different theme. The embeds should still render appropriately.
* Ensure poll …
=> Crowdsignal shortcode: Convert survey.fm links to shortcodes.

extensions/blocks/instagram-gallery/edit.js
* Stop showing the `There are currently only %s posts in your Instagram account` notice in the sidebar while the block is embedding (the image count is zero at that point, but that's about to change shortly).
* Add a variation for when the Instagram account contains zero posts. "There are currently only 0 posts" sounded very awkward.
* Add periods to all variations.
* Remove an accidental double translation:
```diff
- __( sprintf( _n( ... ) ) )
+ sprintf( _n( ... ) )
```
* Insert an Instagram Gallery block, and display its sidebar.
* Connect it to Instagram, and observe the sidebar.
* Make sure the "there are only 0 posts" notice doesn't show up.
* N/A (unreleased block)
=> Instagram Gallery Block: Improve the "not many posts" Notice

modules/shortcodes/ted.php, tests/php/modules/shortcodes/test-class.ted.php
* In the TED shortcode, allow clicking external links — the TED logo — on AMP requests.
* This adds functionality to the current shortcode.
1. Ensure the AMP plugin is enabled;
1. In AMP Settings, select 'Transitional' mode;
1. In Jetpack > Settings, ensure 'Compose using shortcodes' is toggled on:
1. Add a Shortcode block with:
`[ted id="210"]`
1. Preview the AMP front-end by clicking the AMP icon:
1. Click an external link, like the TED logo;
1. Expected: it opens a new tab or window:
Before, clicking an external link did nothing.
Worthy of mention, this approach also makes the default oembed compatible with AMP.
* Improve TED shortcode AMP compatibility.
=> Make TED shortcode AMP compatible

package.json
* Sometimes you need to check for linting errors in a single file in the codebase. We currently do not have that option, unless you have your editor set up and can view linting errors there. This simple task should give us that option.
* Try `yarn lint-file _inc/client/admin.js`
* Add code that will triggered a linting error to that file.
* Run the above again.
* You should get something like this:
* N/A
=> Tasks: add task to lint a single js file

modules/masterbar/masterbar.php, modules/masterbar/tracks-events.js
Remove Recommendations from master bar
Fixes #15222
* The Master Bar still displays a link under "Reader" that points to wordpress.com/recommendations, but this page was retired. See p5PDj3-3ka-p2#comment-4520
* This fixes a bug, removing a broken link from the master bar
* Activate the Master Bar module
* Click on Reader
* See that there is a link to "Recommendations" 
* checkout this branch and see that the "Recommendations" link is gone.
* Remove retired "Recommendations" link from Masterbar
=> Remove Recommendations from master bar #15222

extensions/blocks/image-compare/index.js
Fixes #15744 
* Adds keywords to block to improve search
* Keywords added: juxtapose, photos, pictures, side by side, slider
* Confirm Image Compare block works as expected
* Confirm search terms in block inspector work
=> Image Compare: Add keywords to block

extensions/blocks/image-compare/editor.scss
Fixes #15737.
This PR massages the margins, and the nested placeholders, to make it look good in WordPress environments both that have, and don't have the Gutenberg plugin installed.
Before:
After:
After, with the plugin:
- Test this PR on a WordPress 5.4 install without the Gutenberg plugin enabled, and verify that the placeholder/setup state of the Image Compare block looks good.
=> Image Compare: Fix placeholders for non-plugin environments

extensions/shared/stripe-connection-notification.js
See <https://github.com/Automattic/wp-calypso/issues/41586> for additional context/information.
Changes 1 string.
No
* None
* No
* Sign up for a new site, purchase a plan (on WordPress.com)
* Create a page/post with a premium content block.
* Follow the prompts to add a Stripe connection.
* After the connection is created you should see a notice: "Congrats! Your site is now connected to Stripe. You can now start making money!"
* No changelog entry needed
=> Change post stripe connection messaging: 

extensions/blocks/opentable/attributes.js, extensions/blocks/opentable/edit.js, extensions/blocks/opentable/editor.scss, extensions/blocks/opentable/index.js, extensions/blocks/opentable/opentable.php, extensions/blocks/opentable/view.scss
Fixes #15267
* The OpenTable button is within an iframe and has default padding. A new optional CSS class has been added to apply a negative margin to the container matching the default padding.
_Note: When this is merged, [documentation](https://wordpress.com/support/wordpress-editor/blocks/opentable-block/#advanced) will need to be updated. Docs need info about the "load in iframe" setting as well._
1. Edit a post using the block editor
2. Add a paragraph block of text for visual alignment check
3. Add an OpenTable block using the button style
4. You should see that there is padding within the OpenTable block indenting it
5. Select the OpenTable block and expand it's Advanced settings panel
6. Toggle on the new "Remove button padding" setting
6. Block should appear visually aligned now …
=> OpenTable Block: CSS Class to counter button padding

_inc/social-logos.php, bin/phpcs-whitelist.js
This PR introduces a few changes to Social Logos:
- Switch to using Jetpack version for versioning.
- Switch to using existing filter for minified versions.
- Introduce new constants that we'll rely on for AMP to differentiate Jetpack and wpcom platforms. See https://github.com/Automattic/jetpack/pull/15497#discussion_r421652259
In parallel, I created D43318-code so we can bring those files in sync and use those constants on WordPress.com as well.
- Go to Settings > Sharing
- Icons should be displayed on that page.
- The sharing icons should be displayed on the frontend as well.
* N/A
=> Social Logos: update library to prepare for Fusion

packages/sync/src/class-actions.php, packages/sync/src/class-listener.php, tests/php/sync/test_class.jetpack-sync-integration.php
Jetpack Sync has various settings/filters that determine whether data should be sent on shutdown. Unfortunately this logic wasn't being applied consistently within the listener when data was queued.
This change simply re-uses the should_initialize_sender function to ensure that we don't send data when we are not supposed to.
* consistently use `should_initialize_sender` to determine if the Sender should be initialized
* Bug Fix
* Apply https://github.com/Automattic/jetpack/pull/15726 
* Run the unit tests 
* WP_Test_Jetpack_Sync_Integration::test_do_not_load_sender_if_is_cron_and_cron_sync_disabled will fail
* Runt the unit tests
* WP_Test_Jetpack_Sync_Integration::test_do_not_load_sender_if_is_cron_and_cron_sync_disabled will pass
* Jetpack Sync :: Bug fix to ensure …
=> Sender needs to load consistently utilizing  logic

functions.photon.php
Fixes #15772
Wikimedia uses a specific image URL format, such as this one:
https://commons.wikimedia.org/wiki/File:Dapper_Gentleman.jpg
Although the url uses .jpg, the image is wrapped and displayed within Wikipedia's UI. We consequently should not try to serve such html pages from our CDN.
* Start on a site where the Site Accelerator feature is active.
* In a new post, add an image block, with just about any image.
* After adding the image, add a link to `https://commons.wikimedia.org/wiki/File:Dapper_Gentleman.jpg` to the image like so:
* Publish your post.
* Check the published post. The image should link to `https://commons.wikimedia.org/wiki/File:Dapper_Gentleman.jpg`, not `https://i0.wp.com/commons.wikimedia.org/wiki/File:Dapper_Gentleman.jpg`
* Site Accelerator: avoid breaking …
=> Photon: exclude Wikimedia images from Photon

class.jetpack.php
Currently there's no easy way to distinguish in Tracks between a regular "disconnect" and a disconnect that has happened via plugin deactivation. 
This PR adds a specific tracks even to fire on `plugin_deactivation_hook`. 
Moar tracks
- Connect Jetpack 
- While Jetpack is still connected, go to plugins page
- Deactivate Jetpack from plugins page
- Wait in the "live" view of tracks. Search for events matching `jetpack_deactivate_plugin`. 
- Make sure deactivation works when Jetpack is not connected
N/A
=> Tracks: Send event when plugin is deactivated. 

extensions/blocks/image-compare/edit.js, extensions/blocks/image-compare/index.js, extensions/blocks/image-compare/save.js
Due to changes for AMP support in #15753 we are changing the attributes to not be pulled from source. This allows switching the images to objects and simplifies the code.
Additionally, adds width/height attributes and uses the `photonizeImageProps` utility to set a photon URL.
Fixes: #15741
* Switch attributes to remove source
* Switch image attributes to be objects
* Add width/height attributes to images
* Use photonizeImageProps to set src 
* Due to refactoring attributes, any old Image Compare blocks will invalidate
* Create a new Image Compare block
* Confirm block works as expected on edit/view/re-edit
Note: after this change goes in, the AMP part will need to be updated to include width/height that will also fix the aspect ratio issue.
* For this PR, not necessary because the …
=> Refactor block attributes

extensions/blocks/instagram-gallery/attributes.js, extensions/blocks/instagram-gallery/edit.js, extensions/blocks/instagram-gallery/editor.scss, extensions/blocks/instagram-gallery/instagram-gallery.php
Fixes issue reported on p58i-8Zc-p2.
> Mobile Layout – No responsive settings
* Add a "Stack on mobile" setting, similar to the one used for the Core Media & Text block.
| Large screens | Small screens |
| - | - |
| <img width="1065" alt="Screenshot 2020-05-13 at 11 10 17" src="https://user-images.githubusercontent.com/2070010/81800242-7007ea80-950a-11ea-85f0-b9021ada25ec.png"> | <img width="382" alt="Screenshot 2020-05-13 at 11 10 31" src="https://user-images.githubusercontent.com/2070010/81800251-71d1ae00-950a-11ea-8a63-aa4ed1f4a81b.png"> |
* Insert an Instagram Gallery block and connect it to an account with more than 1 image.
* Make sure there is a "Stack on mobile" setting in the block sidebar, and it's on by default.
* Resize the browser to a mobile width, and make sure the gallery …
=> Instagram Gallery Block: Add a "Stack on mobile" setting

extensions/blocks/image-compare/image-compare.php, extensions/blocks/image-compare/index.js
Fixes #15653 
* Add AMP support for Image Compare using [amp-image-slider component](https://amp.dev/documentation/examples/components/amp-image-slider/).
* This only applies to render in AMP, no changes to non-AMP enviornments
* Install AMP plugin: https://wordpress.org/plugins/amp/
* Activate and Enable Standard AMP so all pages are rendered as AMP pages (this makes testing easier)
* Create a new post (or view existing) with an Image Compare block
* You should see a side-by-side image comparison, it should be the AMP component that looks a bit different than the non-AMP version but should work.
**Note:** the side-by-side and above-below settings will not alter the viewing (it will always be side-by-side) when viewed in AMP context. The AMP component needs to add the additional …
=> Image Compare block: add AMP support using amp-image-slider

modules/widgets/gravatar-profile.php, modules/widgets/twitter-timeline.php
This code is only fires on WP.com.
Bypassed pre-commit hooks since I haven't added the redirect line to WP.com yet, so want to keep this PR clean wrt bringing it back in line with WP.com.
* Remove code that doesn't fire in Jetpack.
* n/a
* n/a
*
* None needed.
=> Widgets: Remove redirect

extensions/index.json
Moves the Image Compare block from a beta block to a production block. 🚀
It is considered ready for a v1 launch, see master issue for list of known issues and improvements for a v2 update. https://github.com/Automattic/jetpack/issues/15742
* Update block from beta array to production array
* See internal announcement post: https://wp.me/p1HpG7-8NH
* Create a new Image Compare block
* View on front-end normal view, AMP view
* Edit the block, confirm it doesn't invalidate
* Adds new Image Compare block
=> Image Compare: Promote from beta to production 🎓

modules/shortcodes/hulu.php, modules/shortcodes/spotify.php, modules/shortcodes/youtube.php
Follow-up to #4281
`embed_autourls` was deprecated a long time ago, no need to use it anymore.
We can also remove its use in the `jetpack_comments_allow_oembed` filter.
* Start on a site where the Shortcodes module is enabled.
* We'll be testing 4 shortcodes:
- In a new comment, add the following link: `http://www.hulu.com/watch/369061` (in my tests it did not always work, the Hulu service seems spotty, I would receive "Service unavailable" responses; maybe that's because I'm outside of the US)
- In a new post, add the following text on its own line: `spotify:track:4bz7uB4edifWKJXSDxwHcs`
- In a new comment, add the following link: `https://www.youtube.com/watch?v=Slp7N6NK0CE`
* Embeds should keep working.
* Embeds: stop using deprecated WordPress option.
=> Embeds: consolidate use of embed_autourls and filters

.travis.yml
Suddenly, ngrok setup, which is used in CI E2E tests stoped working. This PR will move E2E tests to "Allowed failures" section thus unblock the PRs
* move E2E tests CI job to "allowed failures"
* Make sure the E2E tests job is not blocking the PR
*
* n/a
=> Travis: Unblock PRs by allowing falures for E2E tests

modules/shortcodes/spotify.php, tests/php/modules/shortcodes/test-class.spotify.php
Fixes #15800 
* Check if `spotify:` exists anywhere in the `$element` string instead of just the first 8 characters of the string.
* Create a new post in the classic editor or using a classic block.
* If using the classic editor, open the `Text` view.
* Add some arbitrary text (not wrapped in an HTML tag).
* Add spotify:track:4bz7uB4edifWKJXSDxwHcs on its own line below the other text.
* View post and verify that the embed is rendered properly.
* Embeds: ensure that all valid Spotify embeds are being rendered.
=> Shortcodes - Spotify: Fix embed when text not preceded by HTML tag.

packages/connection/src/class-manager.php
* We're seeing occasional timeouts on the token request during user authorization. Let's try increasing the timeout from the default 5s to 30s.
The test site must have Jetpack activated and disconnected.
1. Verify that the you can successfully connect to WPCOM.
* n/a
=> Connection: increase timeout on the token request

_inc/lib/admin-pages/class.jetpack-react-page.php
* Non-admins are not allowed to activate / deactivate modules, they consequently do not need to see the setup wizard.
* Add a new user to your site, and give it the Editor role.
* Check it this branch
* Add the following filter to a functionality plugin:
`add_filter( 'jetpack_show_setup_wizard', '__return_true' );`
* Make sure your admin user sees the "Set Up" menu item in the admin menu.
* Make sure your editor user does not.
* N/A
=> Dashboard Setup page: do not add menu for non-admins

_inc/lib/debugger/debug-functions.php
In #14901, an early return was added for test results that are marked to hide from Site Health.
This is problematic because site health keeps the test item present, but now with an empty result, which causes Core to JS fatal as described in https://github.com/Automattic/jetpack/issues/15709#issuecomment-625496903.
This is a bit of a pickle since for Core, we're just passing the knowledge of a test and the callable used to run the test itself. In our test, Jetpack was changing the value of `show_in_site_health` based on the test results, so the test is still existing in the test array.
I was able to "fix" this by, in the scope of our filter adding the tests, to run each test and if the result returned was a known value to indicate it should be skipped, unset it from the array, but that …
=> Debugger: Remove return for hiding in site health.

bin/post-merge-checkout-hook.sh, package.json
* First attempt at throwing a notice when a package file has changed to encourage building new.
I'm having some trouble testing this reliably, so might be something we need to commit to test. All of the individual parts work.
* n/a
* Switching to this branch will run the hook, but there aren't any changes to impacted files.
* n/a
=> Git Hooks: First pass at notices for changing lock or package files

class.jetpack-gutenberg.php
* Add a new utility we can rely on to display messages instead / alongside blocks on the frontend.
* Try adding something like this to the render function of a block:
`echo Jetpack_Gutenberg::notice( 'a test', 'success' );`
* Ensure that things get displayed properly on the frontend.
* N/A
=> Blocks: add utility to display messages in blocks

modules/widgets/contact-info.php
* As part of syncing things to WP.com, need to handle an URL that we don't want to pass to Jetpack.com.
Improvements to the package are coming to not need these conditionals, but adding this for now to unblock fusion.
* n/a
* n/a
* n/a
=> Redirect: Handle WP.com

_inc/lib/class.core-rest-api-endpoints.php
* In #15470, we made some changes to build_connect_url and added one $request parameter. However, not all calls to build_connect_url currently provide that parameter. Let's consequently provide a default.
* Start from a Jetpack site connected to WordPress.com.
* Update the site URL (like [so](https://wordpress.org/support/article/editing-wp-config-php/#wp_siteurl) for example).
* After a little while, you should see a prompt at the top of the Jetpack dashboard to either fix the connection issue by reconnecting, or putting the site in safe mode.
* Click to reconnect the site, and monitor your logs to ensure that no fatals happen.
* N/A
=> IDC fix: avoid fatals when calling build_connect_url without params

extensions/blocks/podcast-player/attributes.js, extensions/blocks/podcast-player/edit.js, extensions/blocks/podcast-player/index.js
This adds the ability to show static example data, without fetching a remote podcast feed.
Any better ideas for the example episode titles?
Fixes #15707
- Adds a new attribute `exampleFeedData`
- Updates `example` of the block to use the new attribute
* Update to existing block
* `yarn run build-extensions`
* In the inserter, hover "Podcast Player" block and see the new block preview:
* Add an example usage of Podcast Player
=> Podcast Player: Add example

modules/infinite-scroll/infinity.js
Fixes #15837
* Make the IS AJAX request with `X-Requested-With` header to set `DOING_AJAX` in WordPress and ensure backwards compatibility.
* Fixes an issue in the Infinite Scroll module.
* It's a regression fix, can only be tested in code by observing the value of `DOING_AJAX` when the infinite scroll page request is made.
* Fixes issues with the Infinite Scroll AJAX request not being recognized as AJAX request by WordPress.
=> Infinite Scroll: Provide the 'X-Requested-With' header

extensions/shared/components/block-nudge/style.scss
Fixes https://github.com/Automattic/wp-calypso/issues/42021
* Add a bottom margin to the block warning message to avoid instances where the theme button has no top margin and the button and block run together.
Before
After
* Switch to this branch on a test site with a WordPress.com site on the free plan
* Sandbox the test site and apply D43611-code
* Add a page/post, and add a Recurring Payments block
* Note the spacing changes around the upgrade notice and the button below it
* Fix lack of spacing after block warning message
=> Recurring Payments: Add 12px bottom margin to block warning

docker/README.md, docker/docker-compose.yml, package.json
Introduce usage of the published image [automattic/jetpack-wordpress-dev](https://hub.docker.com/r/automattic/jetpack-wordpress-dev) which is built from the Dockerfile contained in this repo: See [docker/Dockerfile](https://github.com/Automattic/jetpack/blob/master/docker/Dockerfile)
The current approach to getting the environment running implies bulding of a docker image which consumes much battery and bandwidth. On top of that one needs to install node packages and such, thus adding to the consumption of battery and bandwidth. **Less than ideal for meetup situations**.
Usage of a pre-built image should decrease significantly the time from cloning Jetpack to having the docker environment running locally, **by a factor 7** approximately. (That is if the whole setup currently takes 3 mins, …
=> Use docker image automattic/jetpack-wordpress-dev instead of local build for the docker environment

extensions/blocks/image-compare/editor.scss, extensions/blocks/image-compare/view.scss
Some of the CSS for the Image Compare block caused display issues in the editor. Specifically, the backface visibility caused rounding errors with the width of the focus rectangle.
This PR addresses that, and also positions the block in the editor to not crop the focus.
Before:
_Note how the focus is 2px on the right and 1px below_
After:
Testing instructions:
- Insert an Image Compare block with two images.
- Unselect it, then select it again so it has a blue focus rectangle.
- Observe that the border has the same width all the way around.
- Also observe that it otherwise works as intended.
Proposed changelog entry: 
- Fixed inconsistent focus border when the block was selected in the editor.
=> Image Compare: Polish focus rectangle.

_inc/client/components/jetpack-termination-dialog/features.jsx, _inc/client/components/jetpack-termination-dialog/style.scss
Make Active plugins relying on Connection more prominent on the Disconnect modal
After some discussion in p1HpG7-8VJ-p2 we decided to change the labels and add Warning icons to the list of active plugins relying on the connection.
* `yarn build-client`
* Add a plugin with the following content:
```
/** Plugin Name: Jetpack Connection Test Plugin (1) */
( new Automattic\Jetpack\Config() )->ensure( 'connection', array( 'slug' => 'jetpack-connection-test-1', 'name' => 'Jetpack Connection Test Plugin (1)' ) );
}, 1 );
```
* Activate it
* Go to the Jetpack Dashboard
* Click on "Manage site Connection":
* Check the modal window and confirm there's a red icon by the plugin name:
No need, there's already a merged PR that added this …
=> Adjust labels in the modal and add warning icons

class.jetpack-admin.php, modules/calypsoify/class.jetpack-calypsoify.php, modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
* When the WP.com classic editor is deprecated the Switch to Classic Editor link needs to go to the WP admin classic editor. 
* This will also activate the classic editor plugin and reset its options as needed to ensure user ends up on the classic editor. This will happen on Atomic sites, but also on Jetpack sites if the classic editor is installed but not activated.
**Important note**
In production the "The Switch To Classic Editor" link will only be shown when:
* Loading an Atomic or Jetpack site in WPcom Calypso and using the iFramed block editor 
* The `editor/after-deprecation` query string param is present (Temporary feature flag).
* The classic editor plugin is installed but not active.
* User has permission to activate plugins e.g. admins.
However, because it is impossible to get …
=> Editor: Update switch to classic editor link

extensions/shared/external-media/sources/pexels.js
The input for searching for images in Pexels uses `type="text"`, but it should be `type="search"`. It doesn't need a `<label>`, as the input is `search` and the button says `search`.
Fixes https://github.com/Automattic/jetpack/issues/15827
* Uses `type="search"` for the search field so it's more semantic
* Adds `aria-label="Search"`
I was originally going to use a visually-hidden `<label>`, but using `TextControl` and needing to repeat the `.screen-reader-text` CSS seemed like a worse solution. The downside with using `aria-label` is that `aria-label` isn't exposed to browser translations. I'm 100% open to doing a visually hidden label instead if people have a recommended clean way of doing it (or not doing it cleanly because it is arguably better 😊)
* Open the editor and insert an image …
=> External Media: Fix Pexels search markup

extensions/blocks/instagram-gallery/edit.js
* Convert the sidebar notice from HOC to simple component.
While working with the block errors handling, I've noticed (pun intended) that we are using the `withNotices` HOC in two different locations (placeholder and sidebar) to display two different kinds of notices.
The sidebar notice informs if the selected Instagram account has less images than requested; the placeholder notice will keep track of all kinds of server and connection errors.
Since the sidebar is not rendered when the block is a placeholder, we thought it was ok to "overload" `withNotices` this way.
Though, it can happen (and it has happened to me while testing) that notices intended for the sidebar might end up being displayed in the placeholder too, where they would make no sense.
Instead of unnecessarily complicating …
=> Latest Instagram Posts Block: Convert the sidebar notice from HOC to simple component

extensions/shared/external-media/media-browser/index.js, extensions/shared/external-media/media-browser/media-item.js
The media item in the external media modal did not contain valid markup for the images, and diverged from what the core media library used. In order to be more similar to the core media library, I changed the markup of the media items to this structure:
```
<ul>
<li role="checkbox" aria-checked... >
...
```
Fixes https://github.com/Automattic/jetpack/issues/15829
* Uses `<ul>` for the media items wrapper
* Each `MediaItem` is an `<li>` with `role="checkbox" tabindex="0"` and an `aria-checked` attribute (either `true` or `false`)
* Adds `onKeydown` listener to each `MediaItem` to catch `enter` and `space` presses
* Open the editor and insert an image block.
* Click the Select Image button and choose Pexels
* Use the keyboard to change the selected image with space or enter
* Inspect the …
=> External Media: Media Item Markup

extensions/shared/external-media/media-button/media-menu.js
~~The popover dropdown should be a `DropdownMenu` component instead of a `Dropdown` so it's consistent with other similar dropdowns in Gutenberg.~~ 
The included `@wordpress/components` package version doesn't have the functionality we need. I've recreated it using the minimum states and functionality we need: aria states and arrow key navigation on the menu.
* Wraps the dropdown in `<NavigableContainer>` to trap focus and allow arrow keys to navigate the menu
* Adds an `aria-label` to the dropdown 
* Adds `aria-expanded` and `aria-haspopup=true` to the toggle button
* Add an image block to a post
* Click the Select Image button
* Use the arrow keys and tab to move around the menu
* Focus …
=> External Media: Arrow keys interactions and aria on Select Image Dropdown

_inc/client/my-plan/my-plan-header/index.js, class.jetpack.php
Simple change from Jetpack Scan to Jetpack Scan Daily. 
We will be using jetpack scan realtime in the future. So it good to be more specific now. 
Related: PR 
After:
* Go to the plans page. Do you see the expected "Daily Scan" as the selection?
* Once you buy Jetpack Scan Daily. Do you notice the new Jetpack Scan `Daily` as the product that you purchased. 
nothing roll them up to the jepack scan product.
=> Jetpack Scan: Update Scan to Daily Scan.

extensions/blocks/image-compare/save.js
I've noticed a couple of block invalidations depending on how orientation is set, this fill force the orientation to horizontal if empty, which is the default behavior.
* Adds a default horizontal of orientation is not set.
* Add the Image Compare block, only test against new posts with new block - existing posts might have the same problem. The block hasn't been published so this should effective any real customers, only previous testing.
* Publish block without changing orientation, re-edit block and confirm in JavaScript console that there are no validation errors
* Try a combination of changing orientations (side-by-side and above/below) publishing and re-editing and confirm there continues no validation errors.
* ( This is covered in new block changelog )
=> Image Compare: Force a default orientation of horizontal in save

bin/phpcs-whitelist.js, modules/theme-tools/site-breadcrumbs.php
Fixes #10062 
* Adds the position itemprop to resolve schema error.
* n/a
* Jetpack + Edin theme (https://wordpress.com/theme/edin) (or another that supports JP breadcrumbs.
* Via Customizer, Theme Options and activate Breadcrumbs option.
* With various pages (a page by itself, a page that itself is a child to another page), run the URLs through the Google testing tool ( https://search.google.com/structured-data/testing-tool/ )
* Ensure the Breadcrumbs are compliant.
Before:
After:
* Theme Tools: Add correct schema.org value for Jetpack Breadcrumbs.
=> Breadcrumbs: Support position itemprop

modules/related-posts/jetpack-related-posts.php
* Prevent embedded posts from wastedly trying to get the related posts API 
When embeded the post with oEmbed, the request will failed because sandbox of iframe. And, the response will not used.
* Activate Jetpack and Related posts module
* embed some post to another post
* Open "another" post in Google Chrome
* Before: Error like net::ERR_FAILED is shown in console
* or, You can see flying request to API like `/post/embed/?relatedposts=1`
* After: There are no one and There is no change in the appearance of the embedding
* parent page still shows related posts
* Related posts: prevent embedded posts from wastedly trying to get the related posts API
=> Related Posts: Don't enque scripts in embed view

extensions/blocks/instagram-gallery/editor.scss, extensions/blocks/instagram-gallery/image-transition.js, extensions/blocks/instagram-gallery/view.scss
Fixes #15767
* On modern browsers, crop the Latest Instagram Posts images to be square.
| - | - |
| <img width="628" alt="Screenshot 2020-05-21 at 17 33 10" src="https://user-images.githubusercontent.com/2070010/82582046-5b21fb80-9b89-11ea-872c-266945c282da.png"> | <img width="628" alt="Screenshot 2020-05-21 at 17 32 03" src="https://user-images.githubusercontent.com/2070010/82582092-6bd27180-9b89-11ea-84b2-486f8c39666b.png"> |
I've chosen the simple way of using the new-ish `object-fit` rule, which is [supported in all modern browsers except IE11](https://caniuse.com/#search=object-fit).
Older browsers will display the images in their original ratio.
I've also moved one last piece of `view.scss` affecting only the editor into `editor.scss`, and moved most of the …
=> Latest Instagram Posts Block: Crop images to square

packages/jitm/src/class-jitm.php, packages/jitm/src/class-post-connection-jitm.php
Fixes #15884
* Remove the `Automattic\Jetpack\Connection` use statements from `class-jitm.php`. The `Manager` and `Client` classes aren't used in this file.
* Add the `Automattic\Jetpack\Connection\Manager` use statement to the `class-post-connection-jitm.php` file. The `Manager` class is used in the `delete_user_update_connection_owner_notice()` method.
* This fixes an existing part of Jetpack.
* Must have Jetpack activated and connected.
* Must have JITMs to display (that is, the JITMs have not been dismissed).
* Must have at least two admin users.
* Debug logging should be enabled.
1. Navigate to the Jetpack dashboard and confirm that a JITM displays.
2. Navigate to wp-admin -> Users. Attempt to delete a user. If the user is not the connection's master user, you should see the normal …
=> JITM: fix use statements

extensions/blocks/image-compare/edit.js, extensions/blocks/image-compare/index.js
Adds a help panel in the inspector to guide the user to use two images of the same size.
@jasmussen let me know what you think
* Adds help panel
* No functional change, confirm help panel shows on right
* New block, changelog already addressed
=> Image Compare: Add help panel

_inc/client/at-a-glance/scan.jsx, _inc/client/components/dash-item/style.scss, _inc/client/pro-status/index.jsx, _inc/lib/class.core-rest-api-endpoints.php, bin/phpcs-whitelist.js, class.jetpack.php, modules/masterbar/masterbar.php, modules/masterbar/overrides.css, modules/module-extras.php, modules/scan/admin-bar-notice.js, modules/scan/class-admin-bar-notice.php, modules/scan/scan.php, modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php, packages/assets/README.md, packages/assets/src/class-assets.php, packages/assets/tests/php/test_Assets.php, tools/builder/react.js
Fixes 1151678672052943-as-1173872646945049.
* This implements threat notifications from Jetpack Scan in two places, the admin bar, and the Jetpack dashboard.
* Part of Scan release.
The new admin bar with the notice. 
* Create a site with Jetpack Scan.
* Create a threat.
* Look at admin and Jetpack dashboard.
* N/A, part of Scan changelog.
=> Add Jetpack Scan threat notifications

_inc/client/state/site/reducer.js
The `getSitePurchases` selector is not checking explicitly for the state object `purchase` that many other selectors rely on. When it's not there, it causes a fatal JS error and the dashboard is blank. 
Ideally, we'd be handling errors when `JETPACK_SITE_PURCHASES_FETCH_FAIL` is fired. Instead, everything is set up to just fall back to a blank default via this reducer. But I understand that this is just following a bad pattern set by othes a while ago. We'll get back around to this, but in the meantime this PR should resolve bricking the Dashboard in any case. 
Updates getSitePurchases to check for more contextual default. 
Bugfix
Before applying this patch, you can get your dashboard to the broken state by: 
- Connect Jetpack 
- Point to your sandbox
- Apply this patch D43509-code (this …
=> getSitePurchases: Fix blank Dashboard on API errors 

modules/contact-form/grunion-contact-form.php
* Avoids PHP Notices and warnings on invalid contact form inputs.
* This is mostly achieved by returning early and checking submitted field types prior to performing string operations on them.
* Each change is it's own commit with an example of the warning/notice and any reasoning why it seems safe.
* Bugfix only.
* Insert a form into a post/widget/area and view the form.
* Manipulate the front-end of the form to change the field types to arrays (ie. `name="g90-youremail"` to `name="g90-youremail[]"`
* Submit the junk input, watch logs for PHP Notices and Warnings.
Please note: This needs careful code review, I believe these changes are safe, but I haven't fully tested every format of contact form.
* No changelog needed.
=> Avoid PHP Notices/warnings on invalid form input

packages/redirect/src/class-redirect.php, packages/redirect/tests/php/bootstrap.php
Adds a filter to `get_url` method so it can be modified on the wpcom side.
* It adds a filter to an existing feature
Nothing to test here, just evaluate if it looks good.
For testing, see D43528-code
=> add filter to Redirect::get_url

modules/contact-form/grunion-contact-form.php
* Add a new action, `grunion_after_feedback_post_inserted`, which fires after the
feedback post has been inserted. The `do_action()` call for this hook should take the
following parameters:
- The post id.
- An array of `Grunion_Contact_Form_Field` objects.
- The spam status.
- The `entry_values` data.
* tbd
* tbd
=> Contact Form: add a new action after the feedback post is inserted

_inc/lib/admin-pages/class.jetpack-react-page.php, class.jetpack.php, tests/php/general/test_class.jetpack.php
Fixes #15600
The issue above describes a problem with how the update modal displays. Currently, it only displays when the user visits the Jetpack dashboard immediately after updating Jetpack. This PR fixes that. The update modal should display on the Jetpack dashboard after updating Jetpack, regardless of whether the user visits the Jetpack dashboard immediately or visits other pages first. Also, the update modal should display only once.
* Add a new Jetpack state index, `display_update_modal`. This index will be used to determine whether the update modal should be displayed.
* In `Jetpack_React_Page::get_initial_state()`, use `Jetpack::state('display_update_modal')` to
determine whether to collect the release post content and send it to the Jetpack dashboard.
* Move the update modal …
=> Admin Page: display update modal correctly

extensions/blocks/recurring-payments/edit.jsx, extensions/blocks/recurring-payments/editor.scss
Fixes #15607
* Updates the button type from standard to secondary for the Recurring Payments list of available options. This adds a border for each button to clean up the UI a bit.
* Also tidies the spacing between buttons and text to even things out.
**Before**
**After**
* Spin up a test site with this branch: https://jurassic.ninja/create?jetpack-beta&branch=update/recurring-payments-styles
* Connect to WP.com and make sure you're on the Jetpack Premium plan
* Add a new post and add a Recurring Payments block to the post
* Connect to Stripe
* Add a couple instances of Recurring Payments buttons
* Note the style changes
* Fix Recurring Payments button styles.
=> Recurring Payments: Use a secondary-styled buttons for payment options

_inc/client/setup-wizard/income-question/index.jsx
This updates the subheader on the Setup Wizard income page to use a `h2` tag instead of a `p` tag based on [this feedback](https://github.com/Automattic/jetpack/pull/15637#issuecomment-630486812) from @jeffgolenski.
No
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/income`.
3. Inspect the HTML and verify that the "Check all that apply" subheader is in a `h2` tag instead of a `p` tag.
* None needed, should be one entry for the whole wizard.
=> Jetpack Setup Wizard: Update Subheader Tag on Income Question Page

modules/google-analytics/classes/wp-google-analytics-legacy.php, modules/google-analytics/classes/wp-google-analytics-universal.php, modules/google-analytics/wp-google-analytics.php, phpunit.xml.dist, tests/php/modules/google-analytics/test-class.google-analytics.php
The current implementation of Google Analytics is not compatible with AMP requests.
* For AMP requests, the PR leverages `amp_analytics_entries` filter from AMP plugin to append the Jetpack Google Analytics Tracking ID. This affects both Jetpack flows for GA Legacy and Universal.
* This functionality is dependant of the [AMP](https://wordpress.org/plugins/amp/) plugin
* This adds Google Analytics on AMP requests;
1. Ensure the [AMP](https://wordpress.org/plugins/amp/) plugin is enabled;
1. Under Jetpack Settings > Traffic > Google Analytics, click `Configure your Google Analytics settings`. This should take you to your wordpress.com dashboard;
1. On `Marketing and Integrations` page, scroll down to Google Analytics section and set the Google Analytics Tracking ID and enable the tracking …
=> Leverage AMP plugin to output the AMP Google Analytics tag

.github/PULL_REQUEST_TEMPLATE.md
* Recommend the use of the new label when a privacy update is necessary.
Alongside this change, I've added 2 labels:
- [Status] Needs Privacy Updates
- [Status] Has Privacy Updates
* Internal reference: p1HpG7-97O-p2
* Check the PR template for typos.
* N/A
=> Privacy Updates: add new section to PR template

dangerfile.js
* When the new privacy section added in #15897 is deleted, Danger will issue a warning to let you know you should answer the question.
* Internal reference: p1HpG7-97O-p2
* Since this PR does not include the new section, you should see a warning in the Danger output below.
* N/A
=> Privacy Updates: add warning when the section is deleted

bin/phpcs-whitelist.js, modules/widgets/eu-cookie-law.php, modules/widgets/eu-cookie-law/style.css, modules/widgets/eu-cookie-law/widget-amp.php
Adds an `amp-consent` component when the AMP site is being viewed based on the Cookies and Consent widget settings.
Fixes #14398 (EU Cookie Law Widget)
* This enhances an existing feature.
* Ensure the [AMP plugin](https://wordpress.org/plugins/amp/) is active
* In AMP > Settings, select Transitional mode
* Enable the extra widgets in Jetpack > Settings > Writing > Widgets
* Add the Cookies & Consents Banner (Jetpack) widget to a sidebar on your theme
* Customise the widget options as desired
* Go to the AMP frontend by adding `?amp` to the end of your site url and ensure the consent banner shows up and is customised as per the options selected on the widget.
I was able to apply most of the settings from the widget to the AMP version of the widget, however the the AMP Consent tag does now …
=> AMP Support for Cookies and Consent

extensions/blocks/contact-form/components/jetpack-field-checkbox.js, extensions/blocks/contact-form/components/jetpack-field-controls.js, extensions/blocks/contact-form/components/jetpack-field-multiple.js, extensions/blocks/contact-form/components/jetpack-field-textarea.js, extensions/blocks/contact-form/components/jetpack-field-width.js, extensions/blocks/contact-form/components/jetpack-field.js, extensions/blocks/contact-form/editor.scss, extensions/blocks/contact-form/index.js, modules/contact-form/css/grunion.css, modules/contact-form/grunion-contact-form.php
Replaces #15674
Update the contact form block to allow field widths to be set. This allows more complex layouts to be achieved:
* Add a Contact Form block
* Add a number of different types of fields
* Change the width setting of these fields and confirm they adjust as expected.
* Publish/update the post and confirm these settings and the layout are retained correctly.
* Confirm the same flex layout is rendered on the front end of the site.
* Added greater support for flexible layouts using the Contact Form block.
=> Contact Form Block: Support flex field widths from master

_inc/client/state/site/reducer.js
Reverts Automattic/jetpack#15807.
The prior pull request broke state as the `sitePurchases` key is an array of purchase objects, so `purchase` cannot be queried there.
To verify, on a site with a product purchased:
1. View My Plan page.
2. View Plans page.
In both, the UI acts as if there are no products bought as it cannot query the purchases for the site.
=> Revert "getSitePurchases: Fix blank Dashboard on API errors "

_inc/client/traffic/sitemaps.jsx, _inc/client/traffic/style.scss
This PR seeks to ease the process of copying the sitemap and news sitemap URLs to paste them in the sitemap input fields from Google Search Console for example. I recently had to setup GSC for two websites, and found not optimal to have to select the text to copy the sitemap URLs and enter them in the GSC input fields. It's much faster to have this button to quickly copy them to the clipboard.
* The text links to each sitemap have been replaced with controls to copy the link to the clipboard. This offers a better UX since user doesn't need to highlight the link to copy and it's faster. Links to each sitemap are preserved next to the control to copy the links.
* Go to Settings > Traffic
* Scroll down to the Sitemaps card. If it's disabled, enable it
* You should see the controls to copy …
=> Settings - Sitemaps: replace text links with control to copy them to the clipboard

packages/sync/src/class-replicastore.php
When doing a reset of the WP.com Cache site we are not clearing the comment cache. This PR doesn't impact any Jetpack Functionality but aligns it with updates being made on the WP.com side.
Fixes #
* Fully utilize clean_comment_cache as outlined in https://wp.me/p94tqY-mg
* Regression Testing as beyond tests modified functions are not utilized.
* On master get the results for /sites/%s/data-check  
or by wp shell call `$store = new Replicastore(); return $store->checksum_all();`
* Switch to fix/comment_cache branch and make the same call
* Verify no warnings/errors and the results are the same.
* N/A
=> Update ReplicaStore to utilize clean_comment_cache

packages/jitm/README.md, packages/jitm/composer.json, packages/jitm/tests/php/test_JITM.php
Fixes #15802
This is a follow-up from #15718. 
* add missing dependencies to `composer.json` so the package can properly be used by others.
* expand a bit on the initial docs so one can quickly see we now have 2 types of JITM.
* add a basic test to ensure we don't show the pre-connection messages to everyone by mistake.
* This does not make changes to privacy.
* N/A
=> JITM: expand docs and tests to account for pre-connection messages

_inc/client/setup-wizard/feature-toggle/index.jsx, _inc/client/setup-wizard/feature-toggle/map-feature-to-props.js, _inc/client/setup-wizard/income-question/index.jsx, _inc/client/setup-wizard/intro-page/index.jsx, _inc/client/setup-wizard/recommended-features/index.jsx, _inc/client/setup-wizard/updates-question/index.jsx
This PR adds Tracks events to the Setup Wizard.
Project: p1HpG7-8BF-p2
Design: pbtFPC-ol-p2
2. Visit `/wp-admin/admin.php?page=jetpack#/setup`.
3. Advance through the flow, verifying that each possible action sends an appropriate Tracks event. The easiest way to check this is to search for `t.gif` in the Network tools.
* None needed, should be one entry for entire Setup Wizard.
=> Jetpack Setup Wizard: Add Tracks events

.phpcs.xml.dist
* Including a "fixable" sniff if a translation function is included without a textdomain. Previously, this would error without an option to auto-fix, but let's be opinionated.
Open question -- Did we ever make a decision about what to do with packages that will require translatable strings on how we'd handle the textdomain?
* n/a
n/a
* On this branch, make a change to a php file to add a line with a translating function without a textdomain, e.g. `$something = __( 'something' );` (it is helpful to do to a file that is otherwise error-free, like 3rd-party/3rd-party.php.
* Run `vendor/bin/phpcs path-to-that-file`
* Should see two errors, both reporting that the text domain is missing. One of them is autofixable.
* Run `vendor/bin/phpcbf path-to-file.
* See the line now is `$something = __( …
=> PHPCS: Allow auto-fixing of translation functions with no text domain to 'jetpack'

extensions/blocks/recurring-payments/edit.jsx
#13175 ## Changes proposed in this Pull Request:
* We're making an effort to sentence-case all calls to action across WP.com. This does so for the Recurring Payments upgrade nudge.
Before
After
* Switch to this PR on a site with the Jetpack Free plan
* Add a Recurring Payments block to a page or post
* Note the upsell; the call to action should be sentence case
* Update Recurring Payments CTA to sentence case
=> Recurring Payments: Sentence case call-to-action upgrade button

_inc/client/setup-wizard/income-question/index.jsx
This PR adds support for a `use` parameter on the income page to enable a URL to provide an answer to the first question of the setup wizard. 
This will enable the Setup Wizard banner to be a part of the questionnaire flow, as the user's choice of personal or business can be "passed" in to React by using the URL query parameters.
No
No
2. Visit `/wp-admin/index.php`.
3. The top banner should be the first question of the setup wizard. Select Personal or Business and verify that you are taken to the income page, and that the `use` question has been answered. The easiest way to check this is to search for a POST to `/jetpack/v4/setup/questionnaire` in the network dev tools.
* None …
=> Jetpack Setup Wizard: Add handling for query param in income page

modules/contact-form/admin.php
The Akismet API docs request that when content is rechecked (or checked at any time other than the time of creation), a `recheck_reason` parameter is included. This change satisfies that request. (API docs at https://akismet.com/development/api/#comment-check)
Testing Instructions:
Enable and configure Akismet, if not already done.
Enable these wp-config.php settings:
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'AKISMET_DEBUG', true );
```
Click "Check for Spam" on a feedback queue that contains an item newer than 15 days. Observe in `wp-content/debug.log` that the requests to Akismet do not contain a `recheck_reason` parameter. (The request string is in the akismet_debug->http_args->body array entry.)
Apply the patch. Click "Check for Spam" again, and after it …
=> Include a recheck_reason for contact form spam rechecks

extensions/blocks/recurring-payments/edit.jsx
Fixes #15603
* Format currency for the text input value rather than displaying it as a raw decimal point
Before
After
* Switch to this branch on a new Jetpack test site with a Premium or greater subscription.
* Add a Recurring Payments block to a post or page
* Check that the default currency is correctly displayed with two decimal points rather than one
* Show Recurring Payments suggested price to two decimal points
=> Recurring Payments: Make sure default values are formatted like currency

class-jetpack-wizard-banner.php
The Setup Wizard banner was intended to show only on the Dashboard and Plugins pages in wp-admin, but it is showing on every wp-admin page.
This PR changes that so that it only shows on the Dashboard and Plugins pages.
2. Visit the Dashboard and Plugins pages in wp-admin and verify that the banner shows.
3. Visit other pages in wp-admin and verify that the banner does not show.
* None needed, only one entry needed for the whole Setup Wizard.
=> Jetpack Setup Wizard: Show Setup Wizard banner only on dashboard and plugins screens

_inc/lib/class.core-rest-api-endpoints.php, modules/scan/class-admin-sidebar-link.php, modules/scan/scan.php
Fixes 1169345694087188-as-1164157450632310.
* Adds a new class that inserts an external link to the sidebar under the Jetpack category.
* Class checks cache for Scan and Backup state, refreshing via cron if either cache is empty.
* Part of Backup & Scan features.
* It tracks users going to their backups dashboard.
* Visit admin on a site with a valid product (see below) as an admin.
* View link to Backup and Scan.
* Click the link.
* Backup
* Scan
* Personal with Rewind enabled (just backups)
* Premium or Pro with Rewind enabled (backup & scan)
* Backup & Scan: Adds a link to access your backups easily from the admin.
=> Adds link to Backup & Scan into sidebar

_inc/jetpack-wizard-banner.js, class-jetpack-wizard-banner.php
* This PR adds dedicated Tracks events to the Jetpack Setup Wizard banner so that we can analyze how it is used.
No
No
2. Visit the Dashboard and choose any option from the Jetpack Setup banner.
3. Visit the tracks live tool in mc and verify that the event shows.
*
=> Jetpack Setup Wizard: Add Tracks events to the Setup Wizard banner

_inc/client/pro-status/index.jsx
This change was introduced in #15795, and while it works well on its own it introduces a small issue whenever we want to gather translations from the Dashboard to send them to translate.wordpress.org.
If it were PHP, the string would use WordPress' `_nx` function, as we're dealing with a string with a singular/plural variant, and some added context. Unfortunately, the tool we use to extract strings from React to PHP does not support `_nx` at the moment.
I would be tempted to fix our tool to support this, but since we'll be moving away from this approach to translate the React dashboard soon (we'll be relying on `@wordpress/i18n` package instead, and we'll let WordPress do the work of extracting translations), I think it's best if we just avoid relying on `_nx` for now; I don't think it's …
=> Dashboard: remove context from plural string

packages/jitm/src/class-post-connection-jitm.php
Fixes #15965 
The bug was introduced in the 8.6 cycle, so I've added this PR to the 8.6 milestone.
* Add a use statement for `Automattic\Jetpack\Redirect`
* Remove the duplicate instantiation of `Connection\Manager`. (See line 149.)
This changes an existing part of Jetpack.
No.
- Must have Jetpack active.
- Must have at least two connected admins.
1. Log in as a secondary admin (not the master user).
2. Navigate to wp-admin -> Users.
3. Attempt to delete the master user.
4. You should see a notice that provides instructions for changing the master user. Confirm that no errors have been generated.
5. Change the master user.
* tbd
=> JITM: add Redirect use statement

_inc/client/setup-wizard/feature-toggle/map-feature-to-props.js
Fixes #15947
This PR changes the copy of the recommended features page to use "block editor" in favor of "Gutenberg".
No
No
1. Visually check that the copy has been changed appropriately.
None
=> Jetpack Setup Wizard: Substitute "block editor" for "Gutenberg"

class-jetpack-wizard-banner.php, scss/jetpack-wizard-banner.scss
Fixes #15916
The dismiss button of the Setup Wizard banner would stay in one place on the screen even as the screen scrolled. This is because it had a fixed position.
This PR fixes that by removing the fixed position CSS and giving the `jp-wizard-banner` a relative position so that the dismiss button will be positioned correctly by its `notice-dismiss` class.
No
No
```
```
2. Visit `/wp-admin/index.php` on a site that has yet to begin the setup wizard and verify that you can see the Setup Wizard banner.
3. Scroll down and verify that the dismiss button of the banner is positioned as it should be.
None
=> Jetpack Setup Wizard: Fix positioning of Setup Wizard banner dismiss button

_inc/client/setup-wizard/feature-toggle/style.scss
Fixes #15942
This PR increases the font size of recommended feature toggles on large screens.
No
No
```
```
2. Visit /wp-admin/admin.php?page=jetpack#/setup/features.
3. Check that the font size is larger on large screens
None
=> Jetpack Setup Wizard: Increase font size of feature toggle content on large screens

class-jetpack-wizard-banner.php
Fixes #15944
The Setup Wizard banner currently hides whenever the current status is not `not-started`. When the user visits `/setup` for the first time and is redirected to `/setup/intro` the status is considered `intro-page` and so the banner would hide even though the user had not answered the question.
This PR changes this so that the Setup Wizard banner continues to display while the user is on the first question, and hides only after it has been answered.
No
No
```
```
2. Visit the `/wp-admin/index.php` and verify that the setup wizard prompt banner shows.
3. Visit `/wp-admin/admin.php?page=jetpack#/setup` and …
=> Jetpack Setup Wizard: Make the setup wizard banner show when the first step has been started

_inc/client/setup-wizard/feature-toggle/map-feature-to-props.js, _inc/client/state/site/reducer.js
Fixes #15943
The Backup and Scan feature toggles were prompting upgrades in the case where the site had single product purchases of Backup and Scan. This was happening because they only considered the site's plan, which is still Jetpack Free when single products have been purchased.
They now look at current active purchases of Backup and Scan in addition to the site plan to determine when to prompt an upgrade.
No
No
```
```
2. On a free site, visit `/wp-admin/admin.php?page=jetpack#/setup/features` and verify that both Backup and Scan prompt an upgrade.
3. Purchase Back and Scan single products and then visit …
=> Jetpack Setup Wizard: Fix upgrade states of backup and scan feature toggles

_inc/client/setup-wizard/index.jsx
Fixes #15936
When a user visits `/wp-admin/admin.php?page=jetpack` and the state of the plugin is such that it redirects to `/wp-admin/admin.php?page=jetpack#/setup` there was an infinite loop causing React to crash and the page to be blank.
This was happening because the `useRouteMatch()` hook in `SetupWizardComponent` was returning `/*` for this case, even after the URL had been changed to `#/setup`.
To fix this I have just hardcoded `/setup`, as there is no real need to dynamically get the URL here since these routes are not expected to change dynamically.
```
add_filter( …
```
=> Jetpack Setup Wizard: Fix setup page being blank after connection

_inc/jetpack-deactivate-dialog.js, class.jetpack.php, scss/jetpack-deactivate-dialog.scss
Track stats from the Deactivation Modal actions
* Adds tracking to actions in the Deactivation modal (open the dialog, cancel and confirm)
* This is part of the "Handle disconnections gracefully" project - p1HpG7-8VJ-p2
Yes, we are now tracking:
* When the user clicks "Disconnect and Deactivate", in order to deactivate the plugin (This only shows up if there's at least one other plugin relying on the Jetpack connection
* When the user confirms the deactivation
* When the user cancels the deactivation
* Are these the best event names? I'm using the same events used in the termination dialog in the Jetpack Dashboard. It already has these `location` and `purpose` that were meant to be used to differentiate when we reused this modal in the deactivation context (which we didn't do. We created …
=> Track stats from the Deactivation Modal

extensions/shared/external-media/media-browser/index.js, extensions/shared/external-media/media-browser/media-item.js, extensions/shared/external-media/sources/google-photos/google-photos-media.js, extensions/shared/external-media/sources/pexels.js
Fixes #15830
- Make the first input element focus on modal open:
- For Pexels, search input is focused and the text is selected,
- For Google Photos, the `View` select is focused.
- Move focus to the first appended image on the "Load More" button click.
1. Add `Image` block,
2. Click `Select Image` button and select Pexels,
3. When the modal opens, the search input should be focused and its text selected.
4. Click on "Load More" button,
5. The first newly appended image should be focused on.
- External Media: Focus modal elements for a11y improvement
=> External Media: Focus modal elements for a11y improvement

scss/jetpack-wizard-banner.scss
* As per @jeffgolenski's recommendation, limit the width of the wizard banner.
-- p8oabR-vj-p2#comment-4314
* No
* On a connected site, add
```php
```
* Check the banner at the top of the main dashboard, its contents should never go too large.
* N/A
=> Jetpack Setup Wizard: limit the width of the banner

packages/jitm/src/class-pre-connection-jitm.php
Fixes #15971
This PR updates the pre-connection JITMs to use the connect-in-place flow instead of the wordpress.com flow.
No
No
1. On a brand new site, before connecting to WordPress.com, add the following:
```php
```
2. Go to the Posts screen
3. Click on Setup Jetpack at the top of the page in the notice
4. Verify that you are taken to `/wp-admin/admin.php?page=jetpack#/setup` and that you see the connect-in-place flow.
None
=> Pre-connection JITMS: Link to connect-in-place flow

_inc/client/setup-wizard/feature-toggle/style.scss
Fixes #15949
The borders of the features page were rounded in the mobile view, creating a bad aesthetic effect:
Now the borders are no longer rounded in the mobile view:
```
```
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/features`.
3. Resize the window to be narrow.
4. Verify that the rounded borders are no longer present.
None
=> Jetpack Setup Wizard: Adjust borders of recommended features page in mobile view

_inc/client/setup-wizard/feature-toggle-group/style.scss, _inc/client/setup-wizard/recommended-features/index.jsx, _inc/client/setup-wizard/recommended-features/style.scss
Fixes #15974
This PR adds margins between the groups of feature toggles in the Setup Wizard.
Before:
After:
No
No
```
```
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/features`.
3. Verify that there is appropriate space between each feature group.
None
=> Jetpack Setup Wizard: Add margin between feature toggle groups

_inc/client/setup-wizard/feature-toggle/style.scss
Fixes #15972
This PR adjust the layout of the feature toggle to avoid a layout conflict between the configure button and the text below it.
Before:
After:
No
No
1. On a brand new site, before to connect to WordPress.com, add the following:
```php
```
2. Connect your site to WordPress.com and pick a Professional plan.
3. Head back to wp-admin.
4. Click on setup.
5. Pick Business and the Advertising option in the flow.
6. On the recommended features find the Ads card and verify that it has no visual issues.
None
=> Jetpack Setup Wizard: Fix the configure button alignment

packages/jitm/src/class-pre-connection-jitm.php
Fixes #15968
Pre-connection JITMs were showing to all users. This PR makes it so that they only show to admins.
No
No
```
```
2. On a pre-connection Jetpack on an admin account visit `/wp-admin/upload.php` and verify that you see a pre-connection JITM.
3. On a pre-connection Jetpack on an author account visit `/wp-admin/upload.php` and verify that you do not see a pre-connection JITM.
*
=> Jetpack Setup Wizard: Do not show pre-connection JITMs to non admins

_inc/client/main.jsx, class.jetpack-admin.php
Fixes #15970
The Setup Wizard was originally made the default page when clicking into the plugin. This PR changes it so that the dashboard is the default page when clicking into the plugin. 
No
No
```
```
2. Starting at the dashboard with a connected Jetpack, click the "Jetpack" nav item on the left sidebar. Verify that you are taken to `/wp-admin/admin.php?page=jetpack#/dashboard`
3. Go to `/wp-admin/admin.php?page=jetpack`. Verify that you are taken to `/wp-admin/admin.php?page=jetpack#/dashboard`.
*
=> Jetpack Setup Wizard: Make #/dashboard the default page

class.jetpack-cli.php, packages/sync/src/class-sender.php, tests/php/sync/test_class.jetpack-sync-sender.php
As of Jetpack 8.3 the `jetpack sync start` cli command would initiate a Full Sync but would not continually send data. This update adds appropriate logic so that the command will run until the full sync has completed.
* Adds a check for the Full Sync Module in use to properly send data until the Full Sync is complete when using `jetpack sync start`
Resolves an issue introduced in 8.3
No
* execute `jetpack sync start` from the remote site's cli
* Verify that the command runs until complete "Success: Finished syncing to WordPress.com"
* Trigger a Full Sync from the jetpack Debugger
* Perform admin actions on the jetpack site (viewing pages is sufficient)
* Verify in the Debugger that the Full Sync processes until complete.
* Jetpack CLI :: fix issue where `jetpack sync start` was triggering …
=> Fix `jetpack sync start` CLI command

_inc/client/setup-wizard/feature-toggle-group/style.scss, _inc/client/setup-wizard/recommended-features/style.scss
#15993 added margins between the feature groups by giving them a `margin-bottom`, and attempted to set the bottom margin of the last child to 0 but failed at doing so in the mobile view. This PR fixes that.
Before:
After:
```
```
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/features` and make the window width below 660px to see the mobile view.
3. Check the margins and verify that they look good.
None
=> Jetpack Setup Wizard: Fix last-child margin of recommended features

packages/connection/src/class-manager.php
See pbtFPC-wo-p2 for context. 
In summary, when we moved to using the connection package for registering, we broke a partner-provisioning flow for setting SSH credentials that was added in #12788. The issue is that the register flow in the connection package does not send the ABSPATH value as part of the register process. 
* Begins syncing ABSPATH when connecting via the connection package. This was previously begin sent when connecting via the Jetpack class.
pbtFPC-wo-p2
For a new site:
- Create JN site with beta
- Checkout this PR
- Click "Set Up Jetpack" button to start connection... but do not approve connection
- On WP.com side, ensure that the `jetpack_constant_ABSPATH` value is synced …
=> Connection: Fix issue where ABSPATH not included with register

extensions/blocks/image-compare/edit.js, extensions/blocks/image-compare/image-compare.php
Fixes #16001
* Pick image's width and height attributes from the sizes made available by the upload. In some cases it may come from `img` (when you select an existing image in the media libray) but in others it may come from `img.media_details` (when uploading a new image).
* Do not set any width or height attributes to the AMP slider when sizes are not available.
* No.
* Install the AMP plugin on your site.
* Go to Posts > Add New and add a new Image Compare block.
* Upload one image, and set one from an existing image in your media library to test both scenarios.
* View that post in an AMP view, and in a regular view; the block should be displayed nicely.
* Back in the editor, switch to the code editor in the editor sidebar. Check the block's attributes for width and height attributes …
=> Image Compare: set width and height attributes for block's images

packages/jitm/src/class-pre-connection-jitm.php
Fixes #15945
This PR changes the "edit post" preconnection JITM so that it only shows when there are 5 or more published posts.
No
No
1. On a brand new site before connecting and before adding any posts, add the following to your wp-config.php:
```
```
2. Visit `/wp-admin/edit.php?post_type=post`. Verify that no pre-connection JITM shows.
3. Add posts until there are 5 or more.
4. Visit `/wp-admin/edit.php?post_type=post`. Verify that there is a pre-connection JITM.
None
=> Hide pre-connection JITM on the posts page when few posts are published

modules/contact-form/admin.php, modules/contact-form/css/grunion.css, modules/contact-form/js/grunion-admin.js
This is modeled after how the "Check for Spam" button in Akismet (and also the Jetpack Contact Form admin page) functions.
Fixes #15661
* This changes the "Empty Spam" button from performing a simple POST request that deletes all spam feedbacks to a button that initiates a series of AJAX requests to delete spam in batches of 25.
This improves an existing part of Jetpack.
1. Amass a thousand spam feedbacks
2. Go to /wp-admin/edit.php?post_status=spam&post_type=feedback
3. Click "Empty Spam"
4. Wait
5. The page will likely time out or lead to an error page.
Apply the patch.
1. Amass a thousand spam feedbacks
2. Go to /wp-admin/edit.php?post_status=spam&post_type=feedback
3. Click "Empty Spam"
4. Observe that the button changes to say "Emptying Spam (0%)" along with a loading indicator.
5. …
=> Change the Contact Form "Empty Spam" button to empty the spam in batches so the page doesn't time out when there's a lot of spam.

extensions/shared/components/stripe-nudge/index.jsx
This PR fixes the Tracks event handling for the Strip nudge in the Recurring Payments block.
* See D44119-code.
* It fixes a button click tracking we already thought we were doing.
* no entry needed
=> Block Extensions: Fix Stripe nudge Tracks event.

class.jetpack-twitter-cards.php
* Follow-up from #15608 
* In some scenarios, we may not have enough info from the image. Let's avoid notices like the ones that follow when that happens:
```
PHP Notice:  Undefined index: src_height in wp-content/plugins/jetpack-dev/class.jetpack-twitter-cards.php on line 96
PHP Notice:  Undefined index: src_width in wp-content/plugins/jetpack-dev/class.jetpack-twitter-cards.php on line 98
```
* No
* No
* Not much testing to do here.
* Sharing: avoid PHP notices when we do not have enough information about an image.
=> Twitter Cards: avoid PHP notices when no image width / height info

class.jetpack-cli.php, packages/sync/src/class-sender.php, tests/php/sync/test_class.jetpack-sync-sender.php
Revert #16010
The additional get_raw_option call is resuliting in an infinite loop in some situations.
*
* Go to '..'
*
*
=> Revert #16010

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, modules/seo-tools/jetpack-seo-utils.php
In examining language use with Jetpack, the term 'grandfathering' has historical origins that are not proper.
This PR renames usage of the term.
* Changes 'grandfather' to 'legacy'/
* pb6Nl-duS-p2
No.
* None.
*
* Remove use of the term 'grandfathering' for a more precise 'legacy'.
=> SEO Tools: Re-term 'grandfather' to 'legacy'

extensions/blocks/image-compare/view.scss
Increases the specificity of CSS for image compare blocks tags `img` and `figcaption` to avoid conflicts with themes.
Fixes #16036
* Modify CSS for image compare block to avoid theme conflicts
* Add image compare block with images
* Toggle between side-by-side and above/below 
* Try with different themes
* Fix Image Compare CSS to avoid potential theme conflict.
=> Image Compare: Increase CSS specificity to avoid theme conflict

extensions/shared/external-media/sources/google-photos/google-photos-auth.js, extensions/shared/external-media/sources/google-photos/index.js, extensions/shared/external-media/sources/with-media.js
Fixes a bug where the first query after authenticating with Google would show Albums instead of the most recent photos.
See https://github.com/Automattic/jetpack/pull/15717#pullrequestreview-418201700
* Swaps authentication variable to make state clearer.
* Passes a authentication state update function to original components.
* Authentication component updates auth state now instead of populating the modal.
No.
* Go through the Google Photos authentication flow
* Make sure the flow fires when there is no connection
* Make sure it doesn't as for authentication when Google Photos is already authenticated
* Check that after authenticating the initial results are recent photos
None needed.
=> External Media: Render Media after authentication

extensions/shared/external-media/editor.scss
Fixes a bug where buttons were running into each other in the featured image panel.
* Extends CSS rule for button margin to Featured Image.
No.
* Open the Editor
* Set a featured image, if the post/page doesn't already have one.
* Make sure there is a sufficient margin between those buttons.
| Before  | After |
| ![Screen Shot 2020-06-03 at 2 48 58 PM](https://user-images.githubusercontent.com/1398304/83693256-9b7e7200-a5aa-11ea-8fec-07033c5a8b5b.png) | ![Screen Shot 2020-06-03 at 2 43 20 PM](https://user-images.githubusercontent.com/1398304/83693273-a46f4380-a5aa-11ea-9f5f-fd712dce3914.png) |
Not needed.
=> External MediaExtend button margin to featured image

modules/shortcodes/css/gravatar-amp.css, modules/shortcodes/css/gravatar.css, modules/shortcodes/gravatar.php
This adds AMP support for the `[gravatar_profile]` shortcode.
*  This change enqueues the necessary CSS file for the `[gravatar_profile]` shortcode, as opposed to adding the `<style>` tag via JS.
This enhances an existing feature.
No.
* Ensure the AMP plugin is active
* In AMP > Settings, select Transitional mode
* In a post, add a shortcode block and input `[gravatar_profile who="ashicus@gmail.com"]`
* View the post with ?amp appended to the end URL
* Expected: The Gravatar profile looks the same in AMP and non-AMP pages
* Adds AMP support for [gavatar_profile] shortcode
=> AMP support for [gravatar-profile] shortcode

modules/shortcodes/twitchtv.php
* In the `[twitchtv]` and `[twitch]` shortcodes, adds a `sandbox` attribute which allows opening links in a new window and fixes a console error on page load.
* This enhances an existing feature.
* Ensure the AMP plugin is active
* In AMP Settings, select 'Transitional' mode
* In Jetpack > Settings > Writing, ensure 'Compose using shortcodes' option is toggled on
* Add a shortcode block with: `[twitchtv url="https://www.twitch.tv/xaryu" height='378' width='620']` or `[twitch url="https://www.twitch.tv/xaryu" height='378' width='620']`
* View the page with `?amp` in the query string
* Click a link inside the Twitch TV embed
* Expected: Link opens up in a new window/tab, and does not throw a console error
* Improved Twitch TV shortcode AMP compatibility
=> Improve AMP compatibility for the TwitchTV shortcodes.

class.jetpack-error.php, class.jetpack.php, modules/subscriptions.php
Continues on #16058
* `Jetpack_Error` is extending `WP_Error` with zero changes. Let's use `WP_Error` instead.
* n/a
No.
* There's no functional change.
*
* Removes Jetpack_Error to use WP_Error directly.
=> Remove usage of Jetpack_Error

extensions/shared/external-media/media-button/media-menu.js
Alternates dropdown button text based on whether the current block accepts media types other than `image`.
Fixes #16064.
* Display "Select Media" if the amount of accepted media types are more than one. (We only ever get this far if the block accepts at least `image`.
* Moves up `mediaProps.value` check to return quicker.
No
* Check out this PR and run `yarn run build-extensions`
* In the editor, insert a media block (Cover, Media & Text, Image, Gallery)
* Check that the dropdown button shows the expected button text.
* Note that it says "Select Image" in the featured image pane.
**After** 
* Not needed.
=> External Media: Better reflect accepted media types

class.jetpack.php, modules/seo-tools.php
This PR adds the Rank Math plugin as conflicting for some Jetpack modules:
- SEO tools 
- verification tools
- sitemaps
Activate Rank Math and ensure SEO elements otherwise output by Jetpack are not longer output, like OG tags or Twitter cards.
* Jetpack will now stop outputting SEO content if Rank Math plugin is active
=> Conflicting plugins: add Rank Math to the list

sal/class.json-api-post-base.php
* Noticed in my logs, it seems this can happen with some incomplete media. Let's check before we rely on `$metadata['length']`, just like we do a few lines below.
* No
* No
* N/A
=> SAL: avoid notice with incomplete media items

modules/related-posts/related-posts.js
Fixes #12811
This PR improves the screen reader accessibility of the related posts feature. It does this by:
* Removing excerpts from link titles - they are long and verbose
* Using the actual image alt text if there is one assigned to the image. This stops the post title being read out again and again and again. 
We could consider removing the `title` attribute from the links completely, however this announces an empty link on the image.
It modifies the related posts feature to improve navigation via screen reader. It doesn't go as far as implementing all recommendations in the original issue. For now we have not:
* Used a single link element for the title, image and meta - changing the markup/layout of the feature in this way risks breaking existing themes/css
* Changed headings from …
=> Fix accessibility of verbose related posts

extensions/blocks/podcast-player/components/header.js, extensions/blocks/podcast-player/components/playlist.js, extensions/blocks/podcast-player/components/podcast-player.js, extensions/blocks/podcast-player/icons/link.js, extensions/blocks/podcast-player/podcast-player.php, extensions/blocks/podcast-player/style.scss, extensions/blocks/podcast-player/templates/playlist-track.php, extensions/blocks/podcast-player/templates/podcast-header-title.php
1. Add an external link to the main episode title
2. Hide the track list if there is only one episode 
3. Fix an issue in the original no-js implementation where the links in the track list would be empty if `link` was not set. It now falls back to `src` in that case.
Fixes https://github.com/Automattic/jetpack/issues/15803
| Before  | After |
| <img width="803" alt="Screenshot 2020-06-03 at 19 37 46" src="https://user-images.githubusercontent.com/1562646/83669469-ebbcfa80-a5d1-11ea-895a-7103ea50cab0.png"> | <img width="812" alt="Screenshot 2020-06-03 at 19 36 51" src="https://user-images.githubusercontent.com/1562646/83669425-de077500-a5d1-11ea-91e8-65c4d6db08f7.png"> |
For all:
* Create a new post and add the `Podcast Player` block.
* Add a Podcast URL …
=> Podcast Player: add episode link and hide single episode track lists

extensions/shared/external-media/media-button/media-menu.js
Adds dropdown button text alternative based on whether the current block accepts multiple entities.
See https://github.com/Automattic/jetpack/pull/16071#issuecomment-639367271
* Displays "Select Images" when the block accepts multiple entities and only one media type.
* Display "Select Media" if the amount of accepted media types are more than one, regardless of how many entities the block accepts. Media is already plural.
No
* Check out this PR and run `yarn run build-extensions`
* In the editor, insert a media block (Cover, Media & Text, Image, Gallery)
* Check that the dropdown button shows the expected button text.
**After** 
* Not needed.
=> External Media: Account for multiple images

modules/shortcodes/slideshare.php
Fixes #
- Remove AMP errors
* Remove the `marginwidth` and `marginheight` attributes to the `iframe` in the shortcode output for AMP requests.
* This modifies the output of the Slideshare shortcode
* Make sure you have AMP Plugin installed and activated.
* Create a new post/page or edit a existing post/page
* Add the Slideshare shortcode:
* Check the shortcode output:
* Check the shortcode output for AMP:
* Go to AMP Validated URL pages (WP Dashborad > AMP > Validated URLs), on the list click the URL of the post/page the shortcode was added in.
* Press the `Recheck` button
* Make sure that there is no AMP errors in the Errors table.
Note: Please try different parameter combinations in the shortcode.
* Improve AMP compatibility for Slideshare shortcode.
=> Make Slideshare shortcode to be compatible with AMP

extensions/shared/external-media/sources/with-media.js
Fixes: https://github.com/Automattic/jetpack/issues/15855
When the External Media modal is open, pressing any arrow key causes it to close immediately. 
To address this issue, I figured that a good thing to start with would be to handle the open/close toggle via the editor state (rather than re-rendering the whole thing every time content source changes). I've used other core implementations as an example - i.e.[ KeboardShortcutHelpModal](https://github.com/WordPress/gutenberg/blob/dbcaf38e886781d0bf5101db8cd04b5360ce2685/packages/edit-post/src/components/keyboard-shortcut-help-modal/index.js) or [OptionsModal](https://github.com/WordPress/gutenberg/blob/34ed2a6042d42fa18a5dcd0853d59bdff6a068d9/packages/edit-post/src/components/options-modal/index.js). I was hoping it would fix the issue, …
=> External Media: Fix Modal focus loss on arrow keypress

modules/shortcodes/dailymotion.php
* In the `[dailymotion-channel]` shortcode, adds a `sandbox` attribute which allows opening links in a new window and fixes a console error on page load.
* This enhances an existing feature.
* Ensure the AMP plugin is active
* In AMP Settings, select 'Transitional' mode
* In Jetpack > Settings > Writing, ensure 'Compose using shortcodes' option is toggled on
* Add a shortcode block with: `[dailymotion-channel user=PAworldnews type=grid]` or `[dailymotion-channel user=PAworldnews type=carousel]`
* View the page with `?amp` in the query string
* Click a link inside the Dailymotion embed
* Expected: Link opens up in a new window/tab, and does not throw a console error
* Improved dailymotion-channel shortcode AMP compatibility
=> AMP support for [dailymotion-channel] shortcode

class.jetpack-cli.php, class.jetpack-gutenberg.php, class.jetpack.php, functions.photon.php
Supports #16099
* Update Jetpack CLI, Gutenberg class, and the main Jetpack class to remove most references to whitelist/blacklist.
* pb6Nl-duS-p2
* No.
* Test `jetpack protect allow` function. It should function the same as the pre-existing `whitelist` function. `whitelist` will still work in case there are partners who have scripted this CLI command in their systems, but not advertised.
* Removed instances of "whitelist" and "blacklist" from the Jetpack codebase.
=> Remove whitelist/blacklist from files in the Jetpack root directory

modules/sitemaps.php, modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-librarian.php, modules/sitemaps/sitemap-state.php, modules/sitemaps/sitemaps.php
In syncing files with WP.com, a commit failed as we prohibit relative include paths (e.g. `include 'sitemaps/sitemaps.php`).
Updating to use `__DIR__` in that instance plus updating Sitemaps to `__DIR__` over `dirname(__FILE__)` since we're no longer in need to support PHP 5.2.
* Use absolute paths in the Sitemaps module since `__DIR__`.
* n/a
n/a
* Confirm Sitemaps loads as usual.
*
* None really needed, but can say something akin to "Sitemaps: Modernize code".
=> Sitemaps: Do not use relative include.

extensions/shared/external-media/editor.scss, extensions/shared/external-media/media-browser/index.js, extensions/shared/external-media/media-browser/media-item.js, extensions/shared/external-media/sources/google-photos/filter-view.js, extensions/shared/external-media/sources/google-photos/google-photos-media.js, extensions/shared/external-media/sources/pexels.js
* This PR is addressing some feedback from #16081 
- Insert image using the External Media modal and observe the loading state:
- you cannot interact with the image selection, buttons or filters
- all images are visually faded-out
- selected images (eg: those being copied) have a spinner on top of them, as well as "Inserting image…" label
- none
=> External Media: Loading and disabled states for the copying state

modules/contact-form/css/grunion.css
Fixes #3228
From the original issue:
> The color contrast ratio between for the text (#aaaaaa) and its background (#F8F8F8 for Twenty Fifteen) is not at least 4.5 to 1.
* To fix these we can use font-size and weight rather than color to differentiate between label and required label on Jetpack forms. This should increase theme compatibility for these labels.
* A11y fix for Jetpack forms
No
* Pull this PR
* Insert a Jetpack form with required fields
* Check the contrast ratio on the "required" label next to form fields
**Before:**
**After:**
Tested on Twenty Fifteen.
* N/A
=> Fix color contrast ratio accessibility issue with "required" text on forms

extensions/blocks/videopress/edit.js
This fix makes use of the "overlay" method used in Core embeds, as well as several Jetpack embed blocks, to make the video playable in the block editor.
The block has an invisible overlay when it isn't selected, which allows it to be clicked on and selected without playing the video. When it is selected, that layer is removed, and clicking the video again will play it.
* VideoPress Block: Add support for playing the video in the block editor.
* Enhancement to existing feature.
No changes.
* Use a Jetpack site with VideoPress support (ie, has the Jetpack Premium plan or above).
* Create a new post.
* Upload a video.
* Once the video is uploaded, confirm that you can play the video from within the block editor.
* VideoPress Block: Add support for playing the video in the block editor.
=> VideoPress Block: Add support for playing the video in the block editor.

extensions/shared/external-media/editor.scss, extensions/shared/external-media/media-button/media-menu.js
Fixes #15828
Fixes issue where after closing the External Media modal the focus is not restored to the selected media option.
- Add the ExternalMedia block,
- Click `Select Media` button and select any option,
- Close the modal,
- The focus should be restored to the selected media menu option,
- Repeat for each media option.
* no changelog entry needed
=> External Media: Restore focus on modal close

extensions/blocks/button/attributes.js, extensions/blocks/button/edit.js, extensions/blocks/button/use-passthrough-attributes.js
* Add a `passthroughAttributes` attribute to the Button block, to map parent attribute values to child (Button) attributes.
In some cases, we might want the Button block to use a parent attribute.
For example, the parent block might have a link that we want to use for the button as well.
Inner blocks templates don't update after mount, so we need another way to keep them in sync.
The `passthroughAttributes` is an object that indicates which parent attributes we want to sync to which child attributes.
E.g. `{ childAttribute: 'parentAttribute' }`
The `usePassthroughAttributes` hook retrieves the parent attributes values and sets them to the Button attributes, effectively keeping them in sync.
See also: https://github.com/Automattic/jetpack/pull/15370#issuecomment-614071023
- This is a …
=> Button Block: Add parent-child syncing mechanism

.github/workflows/needs-review.yml
This reverts commit d52a15c0eb66d8346fcc7b8a166adc19dc73ec99.
Reverts #16121
Should not be merged until Monday morning.
* Crew is back so stop announcing we're away.
* n/a
n/a
* n/a
*
* n/a
=> Actions: revert warning about Crew being away again

tests/php/modules/shortcodes/test-class.hulu.php
Differential Revision: D44828-code
This commit syncs r208905-wpcom.
* Marks a flakey test as skipped
* Run the unit tests, see they now pass reliably and this test is skipped
* None needed
=> Jetpack Unit Tests: Skip test_shortcodes_hulu_id_via_oembed_http_reqUest as the test is super flakey

modules/scan/class-admin-bar-notice.php
I noticed some bizzare issues with the admin bar in how some inline style rules added to the `admin-bar` would fail to apply. The issue turns out to be a missing closing curly brace for a `@media` at-rule added by Jetpack. 
Fixes regression introduced in #15795.
* Fix CSS syntax error due to missing curly brace in media at-rule.
No
No
* Copy contents of the `style#admin-bar-inline-css`  element and verify no CSS syntax errors are present.
* Fix CSS syntax error due to missing curly brace in media at-rule.
=> Add missing closing curly brace for media at-rule

extensions/shared/submit-button.js
Removes the border reset from the Recurring Payments button so the any border defined by themes is preserved.
Note that this was affecting only the editor view. Border was not being reset in the saved content.
View | Before | After
--- | --- | ---
Editor | <img width="288" alt="Screen Shot 2020-06-12 at 14 59 20" src="https://user-images.githubusercontent.com/1233880/84505627-5b13a800-acbe-11ea-9aa4-b85b8143d32e.png"> | <img width="293" alt="Screen Shot 2020-06-12 at 15 01 54" src="https://user-images.githubusercontent.com/1233880/84505649-61098900-acbe-11ea-9b95-4d57571a0081.png">
Published | <img width="287" alt="Screen Shot 2020-06-12 at 15 00 04" src="https://user-images.githubusercontent.com/1233880/84505667-69fa5a80-acbe-11ea-9427-4cef4e905d07.png"> | <img width="287" alt="Screen …
=> Recurring Payments: Remove border on editor

extensions/blocks/recurring-payments/edit.jsx
Ensures any custom text entered in a Recurring Payments button is preserved when plan changes.
Before | After
--- | ---
Recurring Payments is an existing feature of Jetpack.
No.
* Insert a Recurring Payments block.
* Select a plan.
* Makes sure the button label changes to `<Plan Amount> Contribution`.
* Change the plan.
* Makes sure the button label changes to `<New Plan Amount> Contribution`.
* Change the button label to a custom text such as "Subscribe".
* Change the plan.
* Makes sure the custom text previously entered is preserved.
Recurring Payments: Keep custom text on plan change
=> Recurring Payments: Keep custom text on plan change

extensions/blocks/recurring-payments/edit.jsx, yarn.lock
Fixes the ability to set a custom text color for a Recurring Payments button.
Before | After
--- | ---
Recurring Payments is an existing part of Jetpack.
No.
* Insert a Recurring Payments block.
* Try changing the text color on the right sidebar to a custom color (one that is not part of the pre-defined palette).
* Make sure the selected color is applied.
Recurring Payments: Allow setting a custom text color
=> Recurring Payments: Allow setting a custom text color

extensions/editor.js, extensions/shared/blocks/cover/cover-media-placeholder.js, extensions/shared/blocks/cover/editor.scss, extensions/shared/blocks/cover/index.js, extensions/shared/blocks/cover/utils.js, extensions/shared/components/block-nudge/index.jsx, extensions/shared/components/upgrade-nudge/index.jsx, modules/contact-form/css/grunion.css
This PR extends the MediaPlaceholder component for the `core/cover` block, to improve the messages to the users when try to upload different files, depending on the current site plan.
* not simple site: **no changes**
* paid plan: **no changes**
* simple site: free plan
- The user tries to upload an image: **no changes**
- The user tries to upload a no video file: **no changes**. It shows the regular error message
- The user tries to upload a video: changes!!! It shows the upgrade nudge.
For the last condition, it worths mentioning it works either dropping the file as well as by clicking on the upload button.
* It adds a new (controversial) `/blocks` folder in `/share`. After testing I decided to put it there because it isn't a Jetpack block but is a core one. And also, it modifies the …
=> Cover: Handling site plan and its errors

modules/custom-post-types/portfolios.php, modules/custom-post-types/testimonial.php
Fixes #15872
* Introduce a conditional check before loading the CSS styles required for the `[portfolio]` shortcode, this allows theme and plugin authors to register their own version of the styles like so:
```
wp_enqueue_style( 'jetpack-portfolio-style', get_template_directory_uri() . '/portfolio.css', array(), '1.0' );
```
Small improvement to custom content types shortcodes.
N/A
* Enable custom post type support
* Create some posts and use the `[portfolio]` or `[testimonial]` shortcode
* See styled output of shortcode
* Add example snippet above to your theme at the correct hook for styles/scripts
* See custom styles applied to shortcode
* N/A
=> Allow custom CSS to override [portfolio] shortcode styles

_inc/client/lib/jp-redirect/index.js, composer.lock, packages/redirect/README.md, packages/redirect/composer.json, packages/redirect/src/class-redirect.php, packages/redirect/tests/php/test_Redirect.php
`https://jetpack.com/redirect` just redirects requests to `https://jetpack.com/redirect/`. Adding the trailing `/` means that redirect links avoid an extra round trip just for that redirect.
For me, this PR saves 300ms per redirect, which (assuming an average of 10 redirect URLs visited a day), will pay back the hour it took to investigate and write this fix in just 3 years!
I also updated the comments which referred to the URL without the trailing `/`, as that may have contributed to the bug getting in originally.
* Update `Redirect::get_url()` to return a redirect URL with a trailing `/`.
* Bug fix.
No.
* Open dev tools in your browser, go the Network tab, and ensure it's set to keep logs between page loads.
* Visit https://jetpack.com/redirect?url=https://wordpress.com/support, and …
=> Add a trailing / to jetpack.com/redirect URLs.

modules/theme-tools/compat/twentytwenty.css
Fixes #14573
* Fix breakage with .com toolbar and the TwentyTwenty theme, the issues covers the problem in detail. Props @edequalsawesome for the proposed fixes. 
* Compatibility fix for 2020 and the .com toolbar
N/A
* Enable the TwentyTwenty theme
* Turn on the WordPress.com toolbar in Jetpack settings
* Ensure that the notifications panel, and overflow theme menu behave as expected
* Test with the WordPress.com toolbar turned off too - both scenarios should be covered
N/A
=> TwentyTwenty specific fixes for the .com toolbar

json-endpoints/class.wpcom-json-api-list-roles-endpoint.php
Adds a filter for roles returned by the `/sites/<blog-id>/roles` endpoint. 
No.
Partial fix for 462-gh-p2 
* D44865-code adds a filter for roles returned by `/sites/<blog-id>/roles`
* No. 
No.
* Changes here should not affect non-P2 (wpforteams) sites.
* Using the WP.COM dev api console (v1 GET), verify that `sites/<P2-SITE-ID>/roles` does not return the contributor role.
* Using the WP.COM dev api console (v1 GET), verify that `sites/<NON-P2-SITE-ID>/roles` returns the contributor role.
* Adds filter for roles returned by sites/$blog-id/roles api endpoint.
=> API: Add filter to /sites/$blog-id/roles

extensions/blocks/contact-form/components/jetpack-field-checkbox.js
Fixes https://github.com/Automattic/jetpack/issues/16152
* Add required field option to the checkbox field
* Add a form block to a post or page
* Add a new "Checkbox" field
* Confirm you can toggle the field as required or not required
* Form Block: Added missing checkbox field required setting.
=> Form Block: Add required option to the checkbox field

.github/PULL_REQUEST_TEMPLATE.md
Updates the PR template to include a more clear section on Jetpack product discussion.
The background here is: It's important to make sure that any change to the Jetpack as a product must have a related internal discussion so we know all the stakeholders are aware of the change.
Before this PR, the question was:
```
Is this a new feature or does it add/remove features to an existing part of Jetpack?
```
So it looked like the main concern there was to know whether the PR was something new or changed anything. But what we really want is to know if this was properly discussed and a link to the discussion.
This PR proposes to put this in the format of a topic, and not a question:
```
```
=> updates jetpack product topic on pr template

modules/gravatar-hovercards.php, modules/gravatar/gravatar-hovercards-amp.css
This adds AMP support for Gravatar Hovercards in comment sections
* Replaces Gravatar JS implementation with an AMP lightbox
* This enhances an existing feature
* Ensure AMP plugin is active
* In AMP > Settings, select Transitional mode
* Add some comments to a post
* View the post in non-AMP mode as well as AMP mode (`?amp`)
* Expected: 
* Both AMP and non-AMP mode render the comments themselves the same way
* In AMP mode, when clicking/tapping on an avatar, user is shown a lightbox with the commenter's profile information
* Added AMP support for Gravatar Hovercards
=> AMP support for Gravatar Hovercards

modules/custom-post-types/comics.php
The comic CPT doesn't validate on AMP because of the `jetpack-comics` script that gets enqueued. This change conditionally loads it for non-AMP only. 
* Don't load `jetpack-comics` on AMP pages
No.
No changes.
* Install AMP plugin if necessary
* In the AMP plugin settings, select Transitional mode
* In your theme, add `add_theme_support( 'jetpack-comic' );` to `after_setup_theme`
* In wp-admin, create a comic (/wp-admin/post-new.php?post_type=jetpack-comic)
* View the post in AMP mode and non-AMP mode
* If the post returns a 404, switch to a different theme, and then back to the previous theme
* Confirm that the post renders correctly and that there are no validation errors
* AMP support for comic CPT
=> Make Comics CPT validate for AMP

modules/shortcodes/twitchtv.php
On June 10th, Twitch deployed some changes that required the parent query arg be added to all iframe embeds. The value of the parent query param is supposed to be the the domain that the player is embedded on. See https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956
This patch has already been shipped to WPCOM in r208936-wpcom.
* Fixes broken embeds after a change on Twitch's side that began being enforced on June 10
No changes
* Checkout PR
* Create new post with a shortcode block
* Inside the shortcode block, use something like this: `[twitchtv url="https://www.twitch.tv/thinnd" width="1080" height="720" autoplay="false" muted="true"]` (feel free to substitute your …
=> Shortcodes: Twitch: Add required parent query param to embed

modules/sso.php
At the moment, the type for the `$user` parameter passed to the `jetpack_sso_handle_login` action is listed as `array`. The parameter actually never is of this type - it is initialized as `null` and later set to either `WP_User` or `false` by calls to `get_user_by()`.
* Updated the DocBlock for the `jetpack_sso_handle_login` action.
* No, just a DocBlock update.
No.
None.
No changelog entry is needed.
=> SSO: Update types in `jetpack_sso_handle_login` action DocBlock

extensions/blocks/image-compare/view.js
Due to the way React `useLayoutEffect` works, the `scanPage` function is called multiple times, with the component in various states of ready. The load and execution order of the scripts change based on different environments, for example due to `concat_js` behavior on WPCOM.
This ends up causing problems if one of the states is not rendered how the script expects. This PR adds a couple of additional checks to make sure it is in a valid state to avoid errors.
~Additionally, the initial `scanPage` call at the end is no longer needed and was removed.~
Updated: scanPage function is required for front-end rendering.
Fixes #16117
* Add check for `this.wrapper` and bail if not defined.
* Add check for two images in element and bail if not found.
* ~Remove initial `scanPage` call, not needed …
=> Image Compare: fix issue with editing two blocks in a post

extensions/blocks/instagram-gallery/edit.js, extensions/blocks/instagram-gallery/use-connect-instagram.js
* Don't try to reuse an Instagram connection if it doesn't exist anymore.
When permanently deleting an Instagram connection from Calypso, existing blocks won't be immediately aware of it.
After disconnecting the block (which now doesn't permanently delete the connection anymore), the block will try to automagically pre-select the old connection, with the reasoning that it hasn't been permanently deleted, so it still exists.
Though, the connection was deleted in Calypso.
When trying to re-connect the block, the block will use the pre-selected connection (instead of creating a new one), which will fail, because it doesn't exist.
No.
* Insert a Latest Instagram Posts block, and connect it to an Instagram account.
* In another tab, open Calypso -> Marketing -> Connections. Locate the …
=> Latest Instagram Posts: Don't try to reuse a connection if it doesn't exist anymore

tools/jetpack-live-branches/jetpack-live-branches.user.js
This PR fixes a bug in the Jetpack Live Branches userscript related to the script's unexpected behaviour on DOM re-rendering, for example when the script coexists with the Github Highlighter script which does exactly that.
In more detail, before these changes, the way the script was attaching the onchange event on the corresponding checkboxes resulted in the event not being fired when the corresponding DOM nodes where re-rendered ( caused by the Github Highlighter ).
No
**Prerequisites**: 
- Tampermonkey with `Jetpack Live Branches` and `Github Highlighter` scripts active
**Testing:**
- Try viewing a Jetpack PR with both the `Jetpack Live Branches` and `Github Highlighter` scripts active in Tampermonkey
- Verify the "Before" behaviour as seen in the screencast below, aka checking on a …
=> Jetpack Live Branches: Fix Jurassic Ninja link update on DOM re-render

tools/revert-release.sh
This adds a new script that does one thing only, which is to roll back the stable tag of the Jetpack plugin in the wp.org repo. It is only meant to be used in case of extreme emergency situations. 
We have discussed in depth internally about this. 
Internal janitorial feature I guess? 
no
**PLEASE BE CAREFUL WHEN TESTING**
There are a couple of confirmations along the way, and I suspect you still will need to input your svn creds in order for the commit to go through. But I have not dared to go beyond the last confirmation myself. 
I would like feedback on the following: 
- Whether we need more or less confirmations during the script
- The verbiage used
- If we should add more context in the description/text on when to use this
N/A
=> New script that will revert the stable tag for Jetpack in wp.org svn. 

modules/sitemaps.php
Supports #15388
WordPress 5.5 adds a new default sitemap feature. While a future PR will investigate expanding upon that feature when 5.5 is our supported minimum, in the short term, we should short-circuit the Core sitemap to prevent duplicative sitemaps from loading.
This PR would disable the Core sitemap whenever the Jetpack sitemap modules is enabled. Since it is only adding a filter, this can land without version checks.
* Disables the Core's sitemaps added via https://core.trac.wordpress.org/changeset/48072
p9dueE-1eG-p2
No.
* On WordPress nightly.
* Connected Jetpack with default modules.
* Visit example.com/wp-sitemap.xml and see Core's sitemap.
* visit example.com/robots.txt and see wp-sitemap.xml noted.
* Visit example.com/sitemap.xml and see the redirect to wp-sitemap.xml.
* …
=> Sitemaps: Disable Core's sitemap

_inc/lib/core-api/class.jetpack-core-api-site-endpoints.php
Fixes #16067
* Return an error code if the API response is not 200.
n/a
No.
* Connect Jetpack.
* On WP.com, set the `blog_public` option to `-1` for the cache site.
* Attempt to load the Jetpack dashboard.
Before the patch, WSOD. After, the dashboard loads.
This is due to #16068 which should be separately fixed where we'd assumed the response would be an array if it was returned successfully. This fixes the reason the response was not an array, but we should still tackle 16068 to future-proof this more.
* REST API: Minor fix to ensure an accurate fix for the site purchase endpoint.
cc: @nickdaugherty
=> Site Purchases: Return an error if the response from the API is not 200

modules/plugin-search.php
We've never needed to use this remote switch, and I can't think of a reason today where we'd need to turn them off. Removes unnecessary requests, as the transient time was set pretty short. 
I added a new filter which specifically will disable this feature all together. This can also be disabled via the `jetpack_show_promotions` filter that already exists. 
Brought up here: 
p9dueE-1xX-p2
no
- Head to `/wp-admin/plugin-install.php` and search for the term `photon` or some other Jetpack feature.
- Set the filter to `false`, make sure plugin search hints do not display
New filter for disabling Plugin Search Hints feature.
=> Plugin Search Hints: Remove status request to wp.com.

extensions/blocks/podcast-player/podcast-player.php, extensions/blocks/podcast-player/view.js
* Fix initialization of podcast player on infinite scroll load so that the audio player controls are created and the block does not unnecessarily default to static markup.
* No.
* No changes.
* Activate theme that has infinite scroll
* Visit Settings > Reading and set max posts to 2 and check infinite scroll behaviour option
* Set homepage to display latest posts instead of static page if needed
* Create three posts each containing a podcast player block
* Visit homepage and confirm initial two posts podcast players are initialized ok 
* Scroll down until infinite scroll is triggered. 
* Confirm new post's podcast player is initialized and no errors in console
* Bug Fix: Ensure podcast players are initialized correctly when loaded via infinite scroll.
=> Podcast Player: Fix initialization of podcast player on infinite scroll load

extensions/blocks/button/README.md
* Add documentation for the Button block.
This already includes changes introduced in #15918 and #15931.
* Button block: Add documentation
=> Button Block: Add documentation

extensions/blocks/eventbrite/editor.scss, extensions/blocks/eventbrite/style.scss
Fixes #15761
* When the Eventbrite block is center aligned, make sure the inner button is center aligned as well.
| - | - |
| <img width="628" alt="Screenshot 2020-06-22 at 12 09 43" src="https://user-images.githubusercontent.com/2070010/85281089-5058d000-b481-11ea-99f9-290a7e22627f.png"> | <img width="626" alt="Screenshot 2020-06-22 at 12 09 07" src="https://user-images.githubusercontent.com/2070010/85281094-5484ed80-b481-11ea-80d8-a86ed3de5930.png"> |
| <img width="620" alt="Screenshot 2020-06-22 at 12 09 32" src="https://user-images.githubusercontent.com/2070010/85281112-5c449200-b481-11ea-9cd3-d22fa6bc9134.png"> | <img width="643" alt="Screenshot 2020-06-22 at 12 09 15" src="https://user-images.githubusercontent.com/2070010/85281117-5f3f8280-b481-11ea-99d0-ba2452d1d1 …
=> Eventbrite Block: Center the button when the parent block is center aligned

tests/php/sync/test_class.jetpack-sync-sender.php
See p1HpG7-9pe-p2 for context. In short, we release an 8.6.1 release after we found a looping issue in 8.6.0. We were able to replicate the issue when:
- A full sync was being processed via CLI
- Another full sync was triggered via cron
After debugging this, the issue seems to be that #16010 had changed the behavior of #16010 such that it always returned true if we hadn't completed a full sync. Before #16010, would've returned a `WP_Error` instance if there was an existing lock. 
* Adds a test to ensure that `do_full_sync` returns an instance of WP_Error if there is an existing lock.
p1HpG7-9pe-p2
No changes.
* Checkout patch
* Run `yarn docker:phpunit --filter=test_do_full_sync_returns_error_if_lock` and ensure tests pass
* Checkout 8.6 tag
* Run `yarn docker:phpunit …
=> Sync: Add test to verify do_full_sync returns error when existing lock

class.jetpack.php, packages/connection/docs/register-site.md, packages/connection/src/class-manager.php, packages/connection/src/class-plugin-storage.php, packages/connection/src/class-plugin.php, packages/connection/tests/php/test-class-plugin.php, packages/connection/tests/php/test_Manager.php, packages/options/legacy/class-jetpack-options.php
* access tokens no longer get removed if there are other plugins using them (unless explicitly requested);
* public API to mark the plugin as "disconnected by user", and remove that mark;
* Jetpack disconnection always initiate the "hard disconnect", removing the tokens.
* `p1HpG7-8VJ-p2`
1. Install the `client-example` plugin from the branch `add/soft-disconnect`: https://github.com/Automattic/client-example/tree/add/soft-disconnect
2. Call `composer install` over the `client-example` directory to update the dependencies.
3. Create a file `wp-content/plugins/jetpack-connection-test-1.php` with following content:
```
<?php
/** Plugin Name: Jetpack Connection Test Plugin (1) */
( new Automattic\Jetpack\Config() )->ensure( 'connection', array( …
```
=> Connection Package: Soft Disconnects

modules/widgets/blog-stats.php
Fixes #16182
* Replace the Hits text field in Blog Stats Widget from "12,345" to "Pageview Description"
No
- Ensure Site Stats module is active
- Navigate to Customize > Widgets > WIDGET LOCATION
- Click on "Add a Widget"
- Select the Blog Stats widget to add
- Confirm the Hits text field's label is now "Pageview Description"
Blog Stats Widget: Update Label on Hits Text Field
=> Blog Stats Widget: Update Label on Hits Text Field

_inc/lib/core-api/wpcom-endpoints/memberships.php
To support one-time donations through the Recurring Payments system, we need to be able to filter different types of membership products. Adding a `GET` argument will permit the type of product returned to be specified.
* Add a `type` argument to the `memberships/status` endpoint to allow specifying only products of type `donation` should be returned in the response's `products` array.
* pbMlHh-kg-p2
* no
* TBD
* `/wp-json/wpcom/v2/memberships/status`
* The `memberships/status` endpoint can now return only donation products.
=> Memberships: Add a donations argument to the status endpoint.

modules/calypsoify/class.jetpack-calypsoify.php, modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
Adds a check for cookies to enable breaking out of iframe if 3rd party cookies blocked
Part of fixe for: https://github.com/Automattic/wp-calypso/issues/43068
* If a redirect to login from calypso iframe is detected a check is done to make sure cookies can be set, if not code exits with an `X-Frame-Options: DENY` header. This prevents an endless auth loop between wpcom and jetpack and makes the editor break out of the iframe. 
* Adds functionality to an existing feature.
No
- Add Jetpack Beta to an Atomic site and install this branch
- Go direct to the atomic site wp-admin and login
- Load WP.com and switch to the same Atomic site in safari with `Prevent Cross Site Tracking` enabled, and load editor
- It should do a redirect to wpadmin and return to editor with authWpAdmin=true param set …
=> Calypsoify: Add check for cookies to enable breaking out of iframe if 3rd party cookies blocked

packages/connection/src/class-manager.php
Move the `add_filter( 'jetpack_constant_default_value'` call so that it precedes the `Manager::setup_xmlrpc_handlers()` call.
* The `jetpack_constant_default_filter` sets default values of Jetpack API constants if they haven't already been set.
* The `JETPACK__API_VERSION` constant is used in `Manager:: internal_verify_xml_rpc_signature()`, which is called in the arguments for
`Manager::setup_xmlrpc_handlers()`. So, the hook should be added before `Manager::setup_xmlrpc_handlers()` is called.
This bug and the changes in this PR should not affect the Jetpack plugin. Jetpack sets the value of the API constants. So, the default values are only needed when the Connection package is used by another plugin and Jetpack is not activated.
* No.
* This …
=> Connection: add the api_constant filter before setup_xmlrpc_handlers called

docker/mu-plugins/.gitignore, docker/mu-plugins/avoid-plugin-deletion.php, docker/mu-plugins/jetpack-debug-helper-loader.php, docker/mu-plugins/jetpack-debug-helper/class-broken-token.php, docker/mu-plugins/jetpack-debug-helper/css/style.css, docker/mu-plugins/jetpack-debug-helper/inc/class-broken-token-xmlrpc.php, docker/mu-plugins/jetpack-debug-helper/plugin.php
Per our team call today, bringing over @dereksmart's broken token testing tool.
Changed from the original source:
* Various coding standard improvements, including output sanitation and all that.
* Built into a more general helper plugin to give us a framework to add more.
* Adds a helper mu-plugin to our Docker instance to assist with connection testing.
n/a
n/a
* Via our Docker container, kick off Jetpack.
* Notice new mu-plugin that adds a "Broken Token" menu to the Jetpack nav menu of WP.
* Play with it.
* Not sure we need one.
=> Dev Tools: Broken Token Helper

packages/connection/src/class-manager.php
Fixes #16056
* Check blog token when computing $manager->is_registered()
* Register, but do not activate a site
* `(new Connection_Manager())->is_registered()` should return true
* `(new Connection_Manager())->is_active()` should return false
=> Check blog token when computing is_registered

packages/autoloader/src/class-autoloader-handler.php, packages/autoloader/src/class-classes-handler.php, packages/autoloader/src/class-files-handler.php
This is a temporary fix to a site with Jetpack installed in the mu-plugins folder.
- n/a
No
* Test on a site with Jetpack installed in the mu-plugins folder.
* n/a
=> Autoloader: use JETPACK__PLUGIN_DIR when looking for the jetpack plugin directory

packages/autoloader/src/class-autoloader-handler.php, packages/autoloader/src/class-classes-handler.php, packages/autoloader/src/class-files-handler.php
(hopefully) Fixes broken autoloader when loading from mu-plugins in VIP Go environments. 
Discussion here p1592963888441800-slack-jetpack-crew
This will be cleaned up as part of https://github.com/Automattic/jetpack/issues/16252
Checks mu-plugins if it's not found in regular plugin path. This will be cleaned up tomorrow. See 
- Make Jetpack an mu-plugin
- change the directory name to something like `jetpacks`
- This PR should load everything properly. 
*
=> Autoloader: add fallback check for plugin path in mu-plugins

_inc/lib/core-api/wpcom-endpoints/memberships.php
#16180 introduced a product `type` query arg to the memberships status endpoint. This PR expands the accepted values to include `all`, for returning all products regardless of their type.
* pbMlHh-kg-p2
* no
* Apply D45314-code to a WP.com sandbox and sandbox the API.
* Make a `GET` request to `/sites/:site/memberships/status?type=all`.
* Verify the response does not include a `rest_invalid_param` error.
* none, not applicable
=> Memberships: Allow an `all` value for product type when querying membership status.

extensions/blocks/mailchimp/deprecated/v1/index.js, extensions/blocks/mailchimp/edit.js, extensions/blocks/mailchimp/index.js, extensions/blocks/mailchimp/mailchimp.php, extensions/blocks/mailchimp/view.scss
Fixes #15712
* Replace the SubmitButton in the Mailchimp block with new shared Button block.
* No.
* No.
* Mailchimp account
* Site with Mailchimp connection setup
* Post with Mailchimp block created prior to applying this PR's changes
1. Apply this PR
2. On the frontend, visit the post containing the previous version of Mailchimp block
3. Confirm that the block displays and functions as it did before
4. Edit the post
5. Confirm Mailchimp block displays and has correct settings
6. Update the Mailchimp block's button using new settings controls provided by button block
7. Save the post
8. Re-visit the post on the frontend and confirm display and function of block.
* Update Mailchimp block to use new shared Button block.
=> Mailchimp Block: Replace submit button with inner button block

extensions/shared/blocks/cover/components.js, extensions/shared/blocks/cover/cover-media-placeholder.js, extensions/shared/blocks/cover/edit.js, extensions/shared/blocks/cover/editor.scss, extensions/shared/blocks/cover/index.js, extensions/shared/blocks/cover/utils.js, extensions/shared/get-allowed-mime-types.js
As part of the "Next Steps" of https://github.com/Automattic/jetpack/pull/16107, this PR refactorizes the code of the shared/blocks/cover block to:
1) Stop using a constant for the allowed files. Instead of this, replace it with the `allowedMimeTypes` object defined in the Jetpack initial state. It's handled by the `isVideoFile` helper function.
2) Add the `isUpgradable()` helper to make the code more readable and reusable.
3) Handle data propagation between CoverEditBlock and the media placeholder through of a new context.
* Connect with context. Add `isVideoFile()` and `isUPgradable()` helper functions.
* Apply D44997-code
* get sandboxed
* Confirm that when trying to upload a video for a cover block using the MediaPlaceholder will show the Upgrade Nudge, only for Simple sites with a …
=> Cover: Use context to show Upgrade Nudge.

extensions/shared/blocks/cover/cover-media-placeholder.js, extensions/shared/blocks/cover/index.js, extensions/shared/blocks/cover/utils.js
Suggestion to fix the `useBlockEditContext` regression for WordPress 5.3.
This emulates the way the VideoPress block is using `useBlockEditContext`, hidden behind an `isSimpleSite` and plan check.
Fixes #16233.
* Moves environment checks into `index.js` to only filter the media placeholder when necessary.
No
* Set up a test environment that runs WordPress 5.3.4 with Jetpack master
* Open the editor and try inserting an Image Compare block 
* Make sure the block displays without error
* Not needed.
=> Cover: Only add filter if needed

packages/autoloader/src/class-plugins-handler.php, packages/autoloader/src/functions.php
Fix the fatal that occurs during plugin update. The fatal occurs because, during a plugin update, a function in the just-installed version of `autoload_functions.php` is called. However, that file had already been loaded, so the just-installed version of  the file isn't available.
Fixes #16273
* Move the `upgrader_post_install` callback function, `reset_maps_after_update`, to the `autoload_functions.php` file.
* In `reset_maps_after_update`, call `set_up_autoloader` to reset the autoloader after a plugin update.
* n/a
* n/a
1. Install the Jetpack beta plugin.
2. Install and activate the master branch.
3. Delete the existing `jetpack` folder and rename the `jetpack-dev` folder to `jetpack`.
4. Decrease the plugin version in the plugin header of the `jetpack.php` file to < 8.6.1.
5. Connect …
=> Autoloader: fix the fatal that occurs during plugin update

extensions/blocks/slideshow/slideshow.js, extensions/blocks/slideshow/slideshow.php
This PR resolves #15273, where adding a slideshow block, without selecting any image, results to obsolete markup in the frontend. Especially, in the case of AMP rendering there was an extra **visible** markup.
* Return null when images array is empty so that no obsolete markup is rendered both for normal and AMP rendering
No
* Setup local jetpack env with ngrok tunneling as per [instructions](https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md) 
* Install the AMP plugin By AMP Project Contributors here /wp-admin/plugin-install.php?s=amp&tab=search&type=term
* Go to /wp-admin/post-new.php
* Add a slideshow block AND do not select any image
* Save and visit the above post
* Visit the the same post by appending `/amp` to the URL to inspect how AMP renders …
=> Slideshow: do not render markup when user doesn't select any images

extensions/shared/blocks/cover/cover-replace-control-button.js, extensions/shared/blocks/cover/index.js
~IMPORTANT~
~PR branched off from https://github.com/Automattic/jetpack/pull/16271~
This PR extends the media to replace flow in order to deal with paid plans. Basically, the UI allows the user to upload a video when it's a simple site even with a free plan. This PR shows an upgrade nudge when the user tries to upload a video to the `cover` block.
* Handle upgrade nudge when uploading video for cover block.
No
1) Test with _Gutenberg v8.4.0_ (it uses the editor.MediaReplaceFlow filter, added [here](https://github.com/WordPress/gutenberg/pull/22995))
2) Apply these changes (D45422-code)
3) Create a cover block in a simple site with a free plan
4) Set the background (color or image)
5) Try to replace the background uploading a video.
6) Confirm that you get the upgrade nudge.
7) Confirm …
=> Cover: Handle upgrade nudge when replace background

_inc/lib/core-api/wpcom-endpoints/memberships.php, extensions/blocks/recurring-payments/index.js
Part of adding support for the Donations block will be automatically generating default plan products for the three tabbed options: one-time, monthly, and yearly. This PR adds a route to the memberships endpoint for `POST`ing that a certain type of product have its defaults generated (and returned). The only type to be immediately supported will be the `donation` type.
* This PR adds a `create_posts` callback for a new `memberships/products` route which, server-side on WP.com, will generate default products for a given product type via the `Memberships_Product` library.
* pbMlHh-kg-p2
* No
_WordPress.com_
* On a WP.com sandbox, apply D45327-code, D45328-code, and sandbox the API and store.
* Use the [WP.com developer console](https://developer.wordpress.com/docs/api/console/) to `POST` to …
=> Memberships: Add a route for generating products.

extensions/blocks/contact-form/components/jetpack-field-checkbox.js
Fixes #16169
* Make sure that a single checkbox field remains checked when the option "checked by default" is selected. 
* Add a form block
* Add a single checkbox field
* Select "checked by default" option for the field
* Save post and refresh editor
* Confirm that the checkbox is checked.
* Confirm that the checkbox is checked on the front end **logged out**
* Form Block: Fixed issued with checkbox fields not being checked by default when the option is selected.
=> Form Block: Fix checked option on checkbox not persisting.

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php, extensions/shared/external-media/editor.scss, extensions/shared/external-media/index.js, extensions/shared/external-media/media-browser/index.js, extensions/shared/external-media/media-browser/media-item.js, extensions/shared/external-media/media-button/media-menu.js, extensions/shared/external-media/sources/google-photos/filter-view.js, extensions/shared/external-media/sources/google-photos/google-photos-auth.js, extensions/shared/external-media/sources/google-photos/google-photos-media.js, extensions/shared/external-media/sources/google-photos/index.js, extensions/shared/external-media/sources/pexels.js, extensions/shared/external-media/sources/with-media.js, tests/php/core-api/wpcom-endpoints/test_class-wpcom-rest-api-v2-endpoint-external-media.php
Changes in this PR:
* Handle 401 responses #16041
* Extend button margin to featured image #16059
* Render Media after authentication #16044
* Better reflect accepted media types #16071
* Account for multiple images #16077
* Fix Modal focus loss on arrow keypress #16055
* Add API unit tests #15988
* Improve Insert Flow #16081
* Restore focus on modal close #16102
* Disable for existing galleries #16176
* Improve upload permission check #16185
* Adds a handler for 401 responses of the list endpoint.
* Adds margins for "Select Image" button in placeholders and the featured image panel
* Re-renders Google media modal after authentication instead of trying to fill it with a new query
* Updates button test to better reflect accepted media types
* Handles focus updates from arrow key presses
* …
=> External Media: Updates for 8.7

3rd-party/class.jetpack-amp-support.php
If the sharing module is not active, the `WP_SHARING_PLUGIN_DIR` constant is not set. Only try load sharing styles for AMP Reader Mode if the constant is set and thus the module active.
Fixes #16259 
- Enable AMP Reader Mode using the AMP WordPress plugin
- Make sure Sharing is disabled
- Go to a WordPress post on the front end
- Make sure the following warning is not thrown in the error logs:
`PHP Warning:  Use of undefined constant WP_SHARING_PLUGIN_DIR - assumed 'WP_SHARING_PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /wp-content/plugins/jetpack/3rd-party/class.jetpack-amp-support.php on line 435`
=> Fix AMP Reader Mode sharing warning

extensions/blocks/tiled-gallery/deprecated/index.js, extensions/blocks/tiled-gallery/deprecated/v2/constants.js, extensions/blocks/tiled-gallery/deprecated/v2/gallery-image/save.js, extensions/blocks/tiled-gallery/deprecated/v2/index.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/column.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/gallery.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/index.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/mosaic/index.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/mosaic/ratios.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/row.js, extensions/blocks/tiled-gallery/deprecated/v2/layout/square.js, extensions/blocks/tiled-gallery/deprecated/v2/save.js, extensions/blocks/tiled-gallery/deprecated/v2/utils/index.js, extensions/blocks/tiled-gallery/edit.js, extensions/blocks/tiled-gallery/gallery-image/save.js, extensions/blocks/tiled-gallery/index.js, extensions/blocks/tiled-gallery/layout/column.js, extensions/blocks/tiled-gallery/layout/index.js, extensions/blocks/tiled-gallery/layout/mosaic/index.js, extensions/blocks/tiled-gallery/layout/mosaic/resize.js, extensions/blocks/tiled-gallery/save.js, extensions/blocks/tiled-gallery/view.scss
* Fix the output of the Mosaic and Columns styles of Tiled Galleries on AMP pages when they are generated using Gutenberg.
* This modifies the output of the Tiled Gallery block
1. Ensure AMP plugin is activated
2. On AMP General settings page, set 'Transitional' or 'Reader' as the Template Mode
3. Ensure that Gutenberg is the default editor.
4. Create a new Post
5. Add a new `Tiled Gallery` block
6. Select the images for the gallery (by uploading from your pc or selecting them from the `Media Library`)
7. Click on the AMP logo close to the `Preview` button (See the red arrow on the image above)
8. On the preview page you should see the output for the gallery:
9. Compare the output for the AMP pages with the normal pages, go back to the edit page and click on the `Preview` button:
10. Go …
=> Fix Mosaic and Columns styles for Tiled Gallery block on AMP pages.

class.jetpack.php, tests/php/general/test_class.jetpack.php
Fixes #16254
* This essentially reverts #5464. We don't need that killswitch anymore.
* N/A
Not much to test imo. Let's just make sure IDCs still work
* Start from a site currently experiencing an IDC. See below for a quick and dirty way to force your site into an IDC.
* Open the dashboard while logged in as an admin, view the notice.
```php
// Opt in to IDC mitigation.
add_filter( 'jetpack_sync_idc_optin', '__return_true' );
/**
* Trigger an update of IDC options from URL parameters in wp-admin
*/
function developing_jetapck_idc_query_strings() {
if ( isset( $_GET['trigger-idc'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification
Jetpack_Options::update_option(
'sync_error_idc',
array_merge(
Jetpack::get_sync_error_idc_option(),
array(
'home'    => 'fakehome.com',
'siteurl' => …
```
=> IDC: remove remote killswitch

modules/sharedaddy/sharing-sources.php
* Jetpack's Sharing feature does not rely on jQuery, and not all sites load jQuery via their theme or other plugins so we cannot expect it to be available.
* No
* Start with a site that uses the Twenty Twenty theme, and no other plugin. This will ensure that jQuery is not loaded on the frontend of your site by default.
* Activate and connect Jetpack to WordPress.com.
* Go to Jetpack > Settings > Sharing and enable the sharing buttons.
* Go to Settings > Sharing and switch to the official sharing buttons. Also ensure the button is loaded on the home page as well.
* View a post. You'll notice that the Facebook official button does not load. You'll see a JavaScript error in the console instead.
* Switch to this branch.
* The button should now load.
* Make sure it loads when viewing single …
=> Facebook: avoid relying on jQuery for the official button

packages/connection/src/class-plugin-storage.php
Fixes #16299
Typecast values fetched from the database to avoid warnings.
No 
Just run phpunit tests
* No need
=> Connection package: Don't throw warnings if the database is corrupted somehow

_inc/client/components/jetpack-notices/index.jsx, _inc/client/components/jetpack-notices/notice-action-disconnect.jsx, _inc/client/components/notice/notice-action-disconnect.jsx
* React component `ErrorNoticeCycleConnection` to be used for displaying connection errors.
* React component `NoticeActionDisconnect` - a button to disconnect Jetpack within an error notice.
No
* Open file `_inc/client/components/jetpack-notices/index.jsx`
* Find the component `JetpackNotices` and put following code inside the `render()` method: `<ErrorNoticeCycleConnection text={ 'Something went wrong' } />`
* Rebuild Jetpack, open the dashboard and confirm that the notice shows up:
* Click "Reconnect" and confirm that Jetpack has been disconnected, the page should reload, "Set Up Jetpack" button should appear.
* The error notice will still show up after you're disconnected, that's fine.
n/a
=> Dashboard: Reconnect Notice

class.jetpack.php, packages/connection/composer.json, packages/connection/src/class-manager.php, packages/connection/tests/php/test_Manager.php
We'd like to[ move the connection owner deletion notice](https://github.com/Automattic/jetpack/issues/15568) to the Connection package. This will allow the notice to be displayed when the Connection package is used by a plugin and Jetpack is not installed. The notice uses the `jetpack_disconnect` capability. This PR moves the `jetpack_disconnect` capability, along with a few other connection-related capabilities, to the Connection package.
* Move the connection-related custom capabilities to the Connection package.
This will allow the custom capabilities to be used when the package is used by
another plugin and Jetpack isn't installed.
* Add unit tests for the new `Manager::jetpack_connection_custom_caps` method.
* Add a new parameter, `$namespace`, to the `ManagerTest::mock_function` …
=> Connection: move connection custom caps to the Connection package

_inc/client/components/jetpack-notices/index.jsx, _inc/client/components/jetpack-notices/jetpack-connection-errors.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php
- New filter`react_connection_errors_initial_state` is used to push connection errors into React Initial State.
- New `JetpackConnectionErrors` component that read the Initial State errors and displays them using `ErrorNoticeCycleConnection`.
- Existing `ErrorNoticeCycleConnection` component is moved alongside `JetpackConnectionErrors`, as it makes more sense being stored there.
1. Create a plugin `jetpack-connection-test.php` with following code:
```php
<?php
/** Plugin Name: Jetpack Connection Message Plugin */
add_filter( 'react_connection_errors_initial_state', function( $errors ) {
$errors[] = array(
'message' => __('message'),
'action' => 'reconnect'
);
$errors[] = array(
'code' => 'invlaid_blog_token',
'action' => 'reconnect'
);
$errors[] = array(
'code' => …
```
=> React Connection Errors component.

packages/connection/legacy/class-jetpack-ixr-client.php, packages/connection/legacy/class-jetpack-ixr-clientmulticall.php
In https://core.trac.wordpress.org/changeset/48204, Core has adopted the spread operator. As we're overloading the XMLRPC class, we need to match the parent methods.
* Use the spread operator instead of `func_get_args` for the xmlrpc class implementations.
No.
No.
* No functional change, though it is a very slight performance bump.
* Tests pass.
We may need to get creative with the older versions until our minimum is 5.5.
* WordPress 5.5 compatibility
=> Connection: Update XMLRPC overload

packages/autoloader/composer.json, packages/autoloader/src/CustomAutoloaderPlugin.php
Fixes #15793
Composer v2.0 will be released soon, and the autoloader needs to be updated to add support for v2.0.
**NOTE:** One of Jetpack's [dependencies](https://github.com/Automattic/jetpack/blob/master/composer.json#L35), `dealerdirect/phpcodesniffer-composer-installer` v0.6.2, requires `composer-plugin-api` v^1.0 so it's not compatible with Composer 2.0. Adding support for Composer v2.0 is in progress [here](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/pull/111).
* Allow version **^2.0** of the `composer-plugin-api` package.
* Implement the `CustomAutoloaderPlugin::deactivate()` and `CustomAutoloaderPlug::uninstall()` methods which have been added to `PluginInterface`.
* This updates an existing part of Jetpack.
* No.
`CustomAutoloaderPlugin` must work with both …
=> Autoloader: Support Composer v2.0

packages/sync/src/class-defaults.php
Flamingo (https://wordpress.org/plugins/flamingo/) plugin stores email messages as post types. To minimize Search records and also reduce sync/backup requests we are adding them to the post_type blocklist.
Fixes #
[jpop-5477]
* Adds flamingo_contact, flamingo_inbound and flamingo_outbound to post blaoklist
* https://wp.me/p1HpG7-9x6
* No
* Ensure your test site is connected to WordPress.com
* Install and Activate the contact-form-7 and flamingo plugins to your site
* Add a contact-form-7 form to your site
* Submit the contact-form-7 form
* Verify a inbound/contact record is shown in your WP-Admin (Grab the post_id of the record)
* On your WP.com sandbox
* wp shell --url={SITE_DOMAIN}
* get_post( POST_ID)
Verify the post is not found on the sandbox (e.g. did not sync)
* N/A …
=> Block Flamingo Plugin post types in Jetpack Sync

extensions/index.json
* Let's move this block to production since it will go out with Jetpack 8.7
Related PR: #15050 
N/A
No
* With Jetpack Beta blocks disabled, go to Posts > Add New and search for the Send a Message block.
* Do you see it? 🎉 
* N/A
=> Blocks: Switch new Whatsapp block to production

extensions/blocks/recurring-payments/edit.jsx
Add a new filter for determining if the Recurring Payments block controls should be shown in the inspector. This will allow to hide them in cases where they are useless (such as when nested in a WP.com Premium Content block).
Controls enabled | Controls disabled
--- | ---
https://github.com/Automattic/wp-calypso/issues/43450#issuecomment-649535418
No.
* Insert a Recurring Payments block (known as just Payments in dev).
* Make sure the Payment plan and management block controls are shown by default (as long as there are Recurring Payments plan created).
* Type `wp.hooks.addFilter( 'jetpack.RecurringPayments.showControls', 'jetpack/test', () => false );` in the browser console.
* Confirm the block controls are no longer shown (unselect and select again the previously inserted block to make …
=> Recurring Payments: Add filter for hiding block controls

_inc/lib/debugger/class-jetpack-cxn-tests.php
The commit adds verification that `blog_token` exists, and fixes an error that prevented it from being validated.
* Make sure the `blog_token` exists before running the connection test
* If blog token is incorrect, and `display_errors` is enabled, displayed "warning" made the Debugger mark the whole "local testing suite" as "skipped". This PR fixes that issue, so if the blog token is invalid, the error will show up in the debugger.
* Using the "Broken Token" plugin, clear the `blog_token`, but leave the other tokens in place.
* Run Jetpack Debugger, you should see an error: `error: test local testing suite`, `message: Blog token is missing.`.
* Using the "Broken Token" plugin, set an invalid `blog_token`.
* Run Jetpack Debugger again. You should see another error: `error: …
=> Jetpack Debugger: Verifying the blog_token.

bin/phpcs-requirelist.js, class.photon.php, tests/php/test_class.jetpack_photon.php
Fixes #16035 
Previously, we added filters to the REST API before and after the callback is executed to not filter using Photon when the context is set to edit.
In #16035, this behavior regressed when uploading images because the image block does not explicitly set the context to edit when submitting the upload request.
The REST API sets the context, but only within the callback, so our existing filter logic had already fired—and determined it was okay to filter the URLs.
This PR adds a filter specifically for the media endpoint when POSTing a new image using the same overall logic, but at a point after the context is set to `edit`.
* Filters specifically when the rest API creates an attachment.
* Creates a corresponding test.
n/a
No.
* Jetpack connected + Image CDN active.
* Upload an …
=> Photon: Do not filter URLs returned when uploading via REST API.

_inc/client/components/jetpack-notices/index.jsx, _inc/client/components/jetpack-notices/jetpack-connection-errors.jsx, _inc/client/state/site/reducer.js, _inc/lib/class.core-rest-api-endpoints.php
Add user feedback then the request to the `jetpack/v4/site` endpoint returns an error.
Up until https://github.com/Automattic/jetpack/pull/16184, if the `site` endpoint returned an error, the whole React dashboard would break. 
Now that we fixed that, we can display a helpful error message to the user. One of the reasons this endpoint return an error is because of a broken connection, so we are displaying a "Connection Error" message with a CTA to Reconnect jetpack.
p1HpG7-9q9-p2
No
* Start with a connected Jetpack site
* Use the "Broken token" plugin to break your connection (this is available in the `mu-plugins` folder and activated on your docker environment)
* Go to Jetpack > Broken tokens
* Now choose "Set invalid blog token"and break the connection. 
* Visit the Jetpack Dashboard
* …
=> Adds error message for broken REST API calls to jetpack/v4/site

_inc/client/components/jetpack-notices/index.jsx
In #16304 and #16320 we added a new React notice when we see signs the connection is broken, with a CTA to reconnect the site. 
We should only be showing this notice to users that have the capability to reconnect. 
p1HpG7-9q9-p2
No
- Connect Jetpack as an admin
- Trigger the error by breaking the blog token. `Invalidate blog token` button in the Broken Token UI will do the trick. 
- Verify you see the notice in the Jetpack dashboard
- Create/log in as a secondary user that has an `editor` role, or any role lower than admin
- Navigate to the /settings tab as the user, and you should NOT see the notice anymore. 
N/A
=> Do not show connection error notice to non-admins

packages/connection/legacy/class-jetpack-xmlrpc-server.php, tests/php/general/test_class.jetpack.php
Fixes #16060
* The `jetpack.json_api` and `jetpack.testConnection` endpoints should only be available when the Jetpack plugin is active. Check whether the Jetpack class exists before setting up these endpoints.
* n/a
* No.
1. Install, active, and connect Jetpack.
2. Confirm that  the `jetpack.json_api` and `jetpack.testConnection` endpoints are available by making requests to these endpoints. For example, use the Jetpack debugger or access Calypso.
1. Deactivate Jetpack and activate the client-example plugin.
2. Copy the changes in this branch to the connection package in client-example.
3. Follow the test instructions in Issue #16060, and confirm that no errors or warnings are generated.
* tbd
=> Jetpack_XMLRPC_Server: set up jsonAPI and testConnection endpoint when Jetpack is active

tests/php/modules/geo-location/test_class.jetpack-geo-location.php
In https://core.trac.wordpress.org/changeset/48224, Core checks for `$post->post_type` anytime that the `$post` global is not empty.
In the Geolocation test, we make a very simple mock of `$post` with just the ID, so let's add `post_type` too to keep our testing flowing.
Requesting Core check for a WP_Post object in https://core.trac.wordpress.org/ticket/49927 to add a little defense for this if other people are doing something like we are.
=> Unit Tests: Improve the Geolocation Test.

_inc/client/components/jetpack-notices/jetpack-connection-errors.jsx, _inc/client/components/jetpack-notices/notice-action-disconnect.jsx
When an admin clicks "Reconnect" on the "Connection Error" notice bar, we track the event. This commit adds the error code to the tracking information.
Yes, adds a new prop to existing event.
1. Create the file `wp-content/plugins/jetpack-connection-message.php` with following content:
```
<?php
/** Plugin Name: Jetpack Connection Message Plugin */
add_filter( 'react_connection_errors_initial_state', function( $errors ) {
$errors[] = array(
'code' => 'invlaid_blog_token',
'action' => 'reconnect',
'message' => 'Connection Error'
);
return $errors;
} );
```
2. Load the Jetpack Dashboard, you should see the "Connection Error" notice.
3. Open the "Network" tab in your dev tools, enable "Persist Logs", and click on the "Reconnect" button.
4. An HTTP request should be sent to …
=> React Reconnect Notice: Tracking the error code.

docker/mu-plugins/jetpack-debug-helper/class-admin.php, docker/mu-plugins/jetpack-debug-helper/modules/class-jetpack-sync-debug-helper.php, docker/mu-plugins/jetpack-debug-helper/plugin.php
Adds the sync helper module that used to live in the jetpack-debug-helper repository
adds a simple UI to activate modules
=> new module and UI to activate modules

packages/connection/src/error-handlers/class-invalid-blog-token.php
This is a small fix to the XML-RPC error handling PR merged yesterday to only display the admin notice errors to users with permission to make connections.
* Only display connection error notices to users with permission to connect Jetpack to WordPress.com
* Same testing instructions as #16194 
* At the end, log in as a non-admin user and make sure the error message doesn't show up.
=> only display connection errors to allowed users

_inc/client/README.md
Fixes #15694
We currently rely on React in 2 different areas of Jetpack: extensions (aka blocks) and the admin interface). Let's try to follow the same coding guidelines in both environments.
The React dashboard was built a few years back, when React Hooks weren’t a thing yet. As a result, 95% of it relies on classes.
Blocks are still being built, and you’ll find 2 different styles, depending on when the blocks were first built: some use classes, some rely on React Hooks.
As we iterate on the dashboard, let's now encourage the use of function components instead of classes.
The paragraph added in this PR is shamefully stolen from the Gutenberg docs. Kudos @aduth
https://github.com/WordPress/gutenberg/blob/cee8193ca015857d9f9f5e70205588c1a4e6b0a4/docs/contributors/coding-guidelines.md#wordpr …
=> React Dash docs: encourage moving to function components

packages/connection/tests/php/test_Manager.php
Fixes #16250
* Add unit tests for `Manager::is_registered()`
* n/a
* no
* These changes only affect unit tests, so confirm that the tests pass.
* n/a
=> Connection: add unit tests for is_registered

tests/php/general/test_class.jetpack.php
* The `test_classic_xmlrpc_*` unit tests are brittle because `assertArraySubset` returns true only when the subset array being evaluated is in the same order as the input array. The order of the xmlrpc methods arrays doesn't matter, so Improve the tests by using `array_diff()` instead.
* Also clean up the phpcs errors in the `test_classic_xmlrpc_*` tests.
* n/a
* no
* These changes affect only the unit tests, so verify that the unit tests passed.
* n/a
=> Tests: improve the test_classic_xmlrpc_* tests

docker/mu-plugins/jetpack-debug-helper/modules/class-broken-token.php
A few small updates to clean up the user token tests:
* Update the text to 'user tokens' because these tests affect all user tokens
* Add a default value of an empty array to the `Jetpack_Options::get_option( 'user_tokens')` call. This will prevent warnings that occur when there are no user tokens to change.
* n/a
* no
1. Enable the broken token testing tool.
2. Clear the user tokens using the "Clear user tokens" button. There should be no user tokens in the current stored options.
3. Attempt to set invalid user tokens using the "Invalid user tokens" button. Confirm that no warnings have been generated in the debug log.
* n/a
=> Broken Tokens tool: clean up user token tests

packages/autoloader/tests/php/test_plugins_handler.php
Fixes `Notice: Use of undefined constant WP_PLUGIN_DIR - assumed 'WP_PLUGIN_DIR' in /home/travis/build/Automattic/jetpack/packages/autoloader/tests/php/test_plugins_handler.php on line 10`
* use string in the `define`
n/a
no
* Confirm the notice above does not appear on Travis runs that tests the package tests.
*
* n/a
=> Autoloader: Tests: Use a string with define

_inc/lib/class.core-rest-api-endpoints.php
* `Jetpack_Core_Json_Api_Endpoints::rest_authorization_required_code()` is no longer needed since
`rest_authorization_required_code()` has been [added to core](https://developer.wordpress.org/reference/functions/rest_authorization_required_code/). Deprecate it and use core's function.
* n/a
* no
1. Make a request to an endpoint without the required capability, and confirm that the status code in the response is correct (403 for a logged in user, 401 otherwise).
* n/a
=> REST Endpoints: deprecate Jetpack_Core_Json_Api_Endpoints::rest_authorization_required_code

.github/actions/assign-issues/action.yml, .github/actions/assign-issues/package.json, .github/actions/assign-issues/src/index.js, .github/workflows/assign-issues.yml
Fixes #16358
When a PR is created to fix a specific issue, let's:
1. Assign the issue to the PR author
2. Mark the issue as In progress.
This commit adds the new action as well as a new dir (.github/actions) where we can add more similar actions in the future. I'd like to work on assigning milestones to PRs once this makes it in.
This work is based off something similar being done in the Gutenberg repo:
https://github.com/WordPress/gutenberg/tree/master/packages/project-management-automation
N/A
No
* Go check #16358
* Has an action updated the assignee to me and added the "in progress" label to the issue?
* See the action's output here: https://github.com/Automattic/jetpack/pull/16359/checks?check_run_id=827587282
* N/A
=> Repo Gardening: add new action to mark issues being worked on

docker/mu-plugins/jetpack-debug-helper/class-admin.php
Fixes this issue: 
This is what I was seeing when trying to `save` after unchecking the boxes.
- Ensuring we are only trying to update the option if the value is set
- Defaulting to array everywhere we rely on it
- Moves the nonce up in the method to pass phpcs checks. 
- Go to `/wp-admin/admin.php?page=debug-tools`
- Check one of the boxes. Click save. 
- Uncheck the box, click save. 
- Try saving with no values at all. 
- You should see no notices. 
N/A
=> Debug tools: Fix warnings and notices on save of empty checkboxes. 

extensions/blocks/gathering-tweetstorms/editor.js, extensions/blocks/gathering-tweetstorms/editor.scss
This PR shows a spinner over the "Unroll" button after it's clicked, while the twitter thread is loading.
* Add a loading spinner to the twitter thread loader.
p58i-98G-p2#comment-46742
No changes.
* Embed a tweet in a post.
* Click the "Unroll" button.
* None needed.
=> Gathering Tweetstorms: Show a spinner while the thread is loading.

docs/development-environment.md
* Fix the links to the build instruction docs for extensions and the search modules. They were inverted: the one for the search was being linked in the extensions line and vice-versa.
* Fix the links to the build instruction docs for extensions and the search modules
=> Fix the links for the build instructions for extensions and the search module

modules/infinite-scroll/infinity.css, modules/infinite-scroll/infinity.js, modules/infinite-scroll/infinity.php
Fixes #11217
* Add a new `aria-live` span to the footer to announce loading and loaded states for infinite scroll
* Add `aria-labels` to each new page load
* Correctly focus on the newly loaded page data (only for screen readers, not visually)
* Improves infinite scroll
It should remain the same.
* Go into the infinite scroll settings and use either "button" or "auto" mode
* Use a screenreader to visit the front end of your site
* Interact with the infinite scroll page and ensure everything works as expected
* All modes of infinite scroll should work (except for theme, which relies on the them)
* Improve a11y of infinite scroll
=> Improve a11y of infinite scroll. Add aria-live updates for screen readers

_inc/connect-button.js, class.jetpack-connection-banner.php, docs/testing/regression-checklist/regression-checklist.md, docs/testing/regression-checklist/test-suites/packages/connection.md, tests/e2e/bin/install-wordpress.sh, tests/e2e/bin/setup-e2e-travis.sh, tests/e2e/specs/connection.test.js
This PR removes the A/B testing flow from the existing connection flow. Given this, the `in-place` connection flow becomes the default flow.
Furthermore, up to now we were using the `JETPACK_SHOULD_USE_CONNECTION_IFRAME` constant to force the `in-place` connection flow. Given that this is now the default flow and aiming to preserve a corresponding constant for testing purposes we replace the `JETPACK_SHOULD_USE_CONNECTION_IFRAME` constant with `JETPACK_SHOULD_NOT_USE_CONNECTION_IFRAME` which when set to `true` will force the original (aka authorization via redirection flow).
To summarize, this PR:
* Removes A/B testing logic for our 2 different connection flows
* Replaces the `JETPACK_SHOULD_USE_CONNECTION_IFRAME` with `JETPACK_SHOULD_NOT_USE_CONNECTION_IFRAME`  constant
* Updates the …
=> In-place connection flow: Remove ab tests

_inc/lib/core-api/wpcom-endpoints/service-api-keys.php, tests/php/test_deprecation.php
This came up because of 2 changes made in Core this weekend:
- https://core.trac.wordpress.org/ticket/50300
- https://core.trac.wordpress.org/changeset/48327/
They caused our tests to start failing, because:
1. we were not using a valid schema type.
2. We were not expecting the right replacement for deprecated files anymore.
* N/A
* N/A
* Can you still add a Mapbox API key to a brand new Map block?
* N/A
=> Unit Tests: valid JSON schema type / file deprecation changes

extensions/shared/external-media/editor.scss
Previously: #16144
* Let's ensure that the External Media styles do not impact other elements in the block editor.
**Before**
**After**
* N/A 
* N/A 
* In the block editor sidebar, select Tools > Welcome Guide
* Also check that the External Media modal (appearing when adding an image block and selecting an external media source) still looks good.
* N/A
=> External Media: avoid styles bleeding out to Gut welcome modal

packages/debug-helper/plugin.php
* Added missing "Plugin Version" constant.
No
* Go to the Debug Tools plugin.
* Make sure the error notice no longer shows up.
* Confirm that the plugin is still working.
n/a
=> Debug Tools: Added missing Plugin Version constant.

_inc/lib/class.core-rest-api-endpoints.php, packages/connection/src/class-error-handler.php
Kind of a proposal to hook into the /sites request to wpcom, and clear our errors if it's successful. 
Currently, the errors are only cleared if the site was re-registered (on registration hook), or after 24 hrs. I believe this is not ideal. We should not be showing a notice at any time when the connection is working properly. 
I understand the /sites error is not necessarily reflective of the same errors that pop up via XMLRPC, so I'm open to discussion on how we can better catch these in a more appropriate place. 
- New action hook that fires on successful request to wpcom's /site endpoint. 
- Clears Errors on success. 
N/A
No
- Connect Jetpack 
- Break the token with "broken token" by malforming the user token
- Run the site through the Jetpack.com debugger 
- See the error notice
- …
=> Connection Errors: Clear when there's a successful request to /sites

_inc/lib/debugger/class-jetpack-debugger.php
See #14901
The in-plugin debugger did not get the new variable names introduced for failed tests.
* Debugger: Display error message on the in-plugin debug page.
n/a
no
* Create a failed testing state (add another admin, demote the initial admin without disconnecting Jetpack)
* Review the in-plugin debugger. Look for PHP notices.
*
* Bug Fix: Display error on the Jetpack Debuging Page.
=> Debugger: Update vars after #14901

_inc/lib/class-jetpack-tweetstorm-helper.php, _inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-gather.php
Private sites are currently unable to unroll twitter threads, getting the fairly obscure “User cannot access this private blog.” error. This is due to use connecting to the WPCOM API as the blog, rather than the current user.
* Allow private sites to unroll twitter threads.
p58i-98G-p2#comment-46743
No.
Note that this fix _only_ applies to Atomic sites, since these are the only sites that can be officially set to private.
* Create a private Atomic site.
* Apply D45966-code to your sandbox, and set `JETPACK__SANDBOX_DOMAIN` to your sandbox domain on your Atomic site.
* Paste a Tweet URL.
* Click the Unroll button.
Before this change, it would fail. After, it works.
* None needed.
=> Gathering Tweetstorms: Allow private sites to unroll threads.

json-endpoints/class.wpcom-json-api-update-comment-endpoint.php
This reverts commit 99ec0afb51d8b2e5e439e4e3451225d183b37abf.
Follow-up from #15494 and #15530
Internal reference: 94tqY-p2
* Comments created in Calypso or in Notifications should use the `comment` `comment_type`.
* N/A
=> Comments: change default comment type of comments created via API

class.jetpack-user-agent.php, tests/php/general/test_class.jetpack-user-agent.php
Jetpack 8.7 moved UA detection to a new package. There are some themes that, improperly, accessed the legacy methods statically.
In 8.7, the refactor would result in fatals for sites doing this.
* Restore backcompat for themes calling methods statically. (Pre-existing notices would still fire.)
No.
No.
* Install pub/p2-breathe theme.
* Backwards Compatibility: Prevent fatals on themes calling a method statically.
=> User Agent: Restore back-compat

docs/coding-guidelines.md, docs/release-management.md
* Let's be more clear on code deprecation in the plugin, to avoid breaking things on update, or leave things around forever.
cc'ing @dereksmart on this, since you've often been our champion for removing deprecated code. Previous art on the topic:
- https://github.com/Automattic/jetpack/pull/13389
- https://github.com/Automattic/jetpack/pull/13374
- https://github.com/Automattic/jetpack/pull/13375
**Note**: I also took the opportunity to update wording in another document, moving from Master issue to Primary issue (see #16099).
* N/A
* N/A 
* N/A
=> Docs: add recommendations on how to deprecate code

extensions/blocks/gathering-tweetstorms/editor.js
The Twitter thread importer uses a fallback UI for WordPress 5.3. #16369 implemented a loading spinner on newer versions of WordPress, but didn't include it for WordPress 5.3.
* Add the functionality implemented in #16369 to WordPress 5.3.
58i-98G-p2#comment-46754
No change.
* Ensure you're testing on WordPress 5.3.x.
* Embed a tweet in a post.
* Click the Unroll button.
* Gathering Tweetstorms: Show a loading spinner when unrolling Twitter threads on WordPress 5.3.
=> Gathering Tweetstorms: Show the loading spinner in WP 5.3.

extensions/blocks/tiled-gallery/tiled-gallery.php
Fixes #16426
The Tiled Gallery block relies on Jetpack's Image CDN to resize the images on the fly, and consequently cannot be used on a site that's not publicly accessible, where the CDN cannot fetch the images.
With this change, the block will not appear when your site is not connected to WordPress.com.
* N/A
* N/A
* Launch a new JN site with this branch.
* Under Settings > Jetpack Constants, enable Dev mode
* Go to Posts > Add New: the Tiled Gallery block should not be available.
* Disable Dev mode
* Connect your site to WordPress.com.
* The block should become available
* Blocks: do not load the Tiled Gallery block when your site is not connected to WordPress.com.
=> Tiled Gallery Block: only available when Jetpack is connected

packages/autoloader/src/class-plugins-handler.php, packages/autoloader/tests/php/test_plugins_handler.php
Autoloader: Avoid a PHP warning when an empty string is passed to `is_directory_plugin()`.
Example Warning: `strpos(): Offset not contained in string`.
* Avoids a PHP warning when an empty string is passed to `is_directory_plugin()`.
No.
I'm not really sure how this has happened, but on WordPress.org `get_option( 'active_plugins' )` returns `''` (an empty string) on some sites. I don't know if that's expected or not, but I suspect it only happens on sites that have never had a plugin activated on it directly, only through Network-activated plugins.
It causes `get_active_plugin_paths()` https://github.com/Automattic/jetpack/blob/master/packages/autoloader/src/class-plugins-handler.php#L48-L52 to have `array( '' )` as it's `$plugin_slugs` value, which seems like it might be expected due to …
=> Autoloader: Avoid a PHP warning when an empty string is passed to `is_directory_plugin()`.

functions.global.php, tests/php/general/test_class.functions.global.php
In #16433, we determined that we would remove deprecated files and functions 6 months after they've been deprecated.
Let's communicate this to site owners as well, by outputting additional details in the error logs when a deprecation notice is issued. 
* N/A
* N/A
* Add the following into a plugin on your site:
```php
function jeherve_test_deprecated_things() {
require_once JETPACK__PLUGIN_DIR . 'modules/minileven.php';
$deprecated_function = jetpack_check_mobile();
}
add_action( 'init', 'jeherve_test_deprecated_things' );
```
* Load your site
* Check your error log: you should see the following:
```
[09-Jul-2020 08:19:37 UTC] The minileven.php file will be removed from the Jetpack plugin in version 8.9.
[09-Jul-2020 08:19:37 UTC] PHP Deprecated:  minileven.php is …
```
=> Deprecation notices: add details about file/function removals

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php, json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-list-posts-v1-2-endpoint.php, modules/sharedaddy/sharing-service.php
Fixes two warnings:
Warning: Illegal offset type in isset or empty in /srv/public/wp-content/plugins/jetpack/modules/sharedaddy/sharing-service.php on line 307
E_WARNING: /home/public_html/wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php:137 - Invalid argument supplied for foreach()
* Validation of variable type before use.
n/a
* For the Sharing one, connected JP, activate Sharing and hit an URL like https://continuing-sacred.jurassic.ninja/2020/07/09/hello-world/?share[0]=twitter&share[1]=facebook&nb=1
(notice the `share[0]` and `share[1]` values.
* Bug Fix: Prevent PHP warnings in two instances.
=> Various: Fix PHP warnings

bin/partner-provision.sh
* Update the partner provision script to accept FTP credentials (previously only SSH credentials were allowed).
See pbuNQi-gM-p2.
In order to test this you will need a hosting partner partner ID and partner secret. Feel free to ping the folks at `#jetpack-infinity` in Slack for some testing credentials. You will also need a test site with Jetpack installed, activated, and with working FTP credentials for your server.
SSH to the site and go to the jetpack plugin's bin dir. In there execute the following, replacing whatever is between `<>` with the appropriate values:
```bash
bash partner-provision.sh \
--partner_id=<PARTNER ID> \
--partner_secret=<PARTNER SECRET> \
--user=<SITE USER> \
--plan=professional \
--wpcom_user_id=<YOUR WPCOM USER ID> \
--url=<SITEURL> \
--ftp-host=<FT HOST> \ …
```
=> Add FTP support to partner provision script

_inc/lib/admin-pages/class.jetpack-react-page.php, _inc/lib/class.core-rest-api-endpoints.php
Required for Automattic/wp-calypso#43788
* Adds the Jetpack connection owner's username to the API response
See Automattic/wp-calypso#25812 
I don't think so, but this data isn't accessible in Calypso currently.
* Go to `/settings/manage-connection/site` in Calypso
* Inspect the call to `?http_envelope=1&path=%2Fjetpack%2Fv4%2Fconnection%2Fdata%2F&locale=en-gb`
* Verify the response includes the connection owner's name
* Probably not needed since this is a change in Calypso
=> API: Add Connection Owner Name to Endpoint

extensions/blocks/instagram-gallery/instagram-gallery.php
Fixes #
- Fix the images style layout of the Latest Instagram Posts block on AMPpages.
* Apply object-fit CSS rule to images of the block
* Make sure AMP plugin is activated
* Create or edit a new post and add a `Latest Instagram Posts` block:
* Connect the block with your Instagram account. If you already connected the block with instagram, then choose a account:
* You should see a grid with the posts from your instagram account:
* Save the post and check the output on normal pages and then on AMP pages:
Normal Pages:
AMP Pages:
Before:
* Fix image layout for Latest Instagram Posts block
=> Fix Latest Instagram Posts Images on AMP pages

packages/debug-helper/modules/class-broken-token.php
Consider the user ID when creating an invalid user token, this better simulates a token where the "hash" part is broken while still assigned to the user.
In order to test, you have to have a primary user whose ID is not 1.
. Without this patch: an invalid user token would look like a completely disconnected site. No access to dashboard
. With this patch: user still has access to the Dashboard
=> Broken token plugin: fixes invalid user token method

extensions/blocks/opentable/deprecated/v1/index.js, extensions/blocks/opentable/index.js
Fixes #15639
Update OpenTable block so additional CSS classes are maintained between edits. 
Previously, reloading the editor after saving an additional CSS class under the block's Advanced settings, loses the CSS class from that field. Saving the post again causes the CSS class to be removed from the block's saved content as the Additional CSS Classes field is blank.
_I haven't been able to find a means of getting the `className` value for the OpenTable block at the time of migrating a deprecated block. This means that I can't prevent the issue this PR addresses until the block has been migrated and the custom CSS class re-added._
_Open to suggestions on how to tackle this, if anyone has any? I believe the use of this block is rather low as well, so it might not be worth the time …
=> OpenTable Block: Allow for custom css classes

modules/contact-form/grunion-contact-form.php
Fixes:
```
E_WARNING
stripslashes() expects parameter 1 to be string, array given
Page
/news/page/2/?_wpnonce0=exp&_wpnonce1=1&contact-form-hash=91a34bc4135cf099b48a4c5b916250db4fe47f3a&contact-form-id=4&contact-form-sent=2599&subscribe=many_pending_subs
File
/home/public_html/wp-content/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2004
```
* Ensures the hash is a string.
n/a
n/a
* On an archive page with a contact form and a subscription form, submit the contact form and then submit the subscription form.
* Covered in an earlier warning bug fix changelog item.
=> Contact Form: Ensure hash is expected type.

functions.opengraph.php, tests/php/test_class.functions.opengraph.php
Fixes #16459
As described on the issue:
> The refactoring changed the order of some calls, namely removing URLs and stripping HTML tags. It now removes URLs first, which invalidates the img tag by removing the last " of the src attribute. Stripping HTML tags next removes the img tag and everything after instead of just the img tag itself. If the description is empty it uses the fallback text.
This fixes that by going back to a proper order for cleaning up the description.
* N/A
* N/A
* On a site with the sharing module active, create a new post.
* That post should start with an image, and then include some text.
* View source after publishing the post; the `og:description` tag should include the beginning of the text you wrote.
* Sharing: create proper Open Graph …
=> Open Graph: description for posts that start with an image

_inc/client/writing/composing.jsx, modules/module-info.php
The support doc used to be https://jetpack.com/support/copy-post-2/
It now uses `support/copy-post` like it should have from the start. :)
See p1594628241203200-slack-jpop-quill
N/A 
N/A 
* Go to Jetpack > Settings
* Search for "Copy"
* Make sure the link to the support doc is correct.
* N/A
=> Copy Post: update support link

extensions/blocks/subscriptions/subscriptions.php
I noticed unnecessary queries to `jetpack_tokens` and `jetpack_tokens_mu` on a fresh WPCOM site.
=> Check `IS_WPCOM` constant first

modules/photon-cdn.php, tests/php/modules/photon/test_class.jetpack-photon-static-asset-cdn.php
Fixes #15995
* Check the value of `$file` before setting the local path for translation files. `$file` [can be false](https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/l10n.php#L1086), and in that case, we should not return the local path.
* Add unit tests for `Jetpack_Photon_Static_Assets_CDN::fix_local_script_translation_path`. The "File is false" test data should fail with the current implementation of `Jetpack_Photon_Static_Assets_CDN::fix_local_script_translation_path`. The test should pass with the changes in this PR.
* n/a
* no
1. Install the latest stable version of Jetpack. Activate and connect Jetpack.
2. Enable debug logging.
3. Navigate to Jetpack -> Settings -> Performance and turn on the toggle for Enable Site Accelerator. Both the image and static file load …
=> Asset CDN: don't fix local script translation path when $file is false

webpack.config.search.js
We are increasing the bundle size limit for Jetpack Instant Search due to WPCOM's bundle exceeding the 130 KiB limit (currently, the bundle is 115 KiB in Jetpack and 134 KiB in WPCOM).
* Increases Jetpack Instant Search bundle limit to 150 [KiB](https://en.wikipedia.org/wiki/Kibibyte).
No.
* Run `yarn build-production`. Ensure that it completes without an error code.
* None.
=> Search: Increase instant search bundle limit to 150 KiB

extensions/blocks/recurring-payments/deprecated/v1/index.js, extensions/blocks/recurring-payments/edit.jsx, extensions/blocks/recurring-payments/index.js, extensions/blocks/recurring-payments/view.scss, modules/memberships/class-jetpack-memberships.php
Fixes #15713
* Replace the SubmitButton in the Recurring Payments block with new shared Button block.
No.
* Sandboxed `public-api.wordpress.com` and `subscribe.wordpress.com`. See instructions for sandboxing for Recurring Payments in the Field Guide.
* Site connected to Stripe and a plan created.
* A post with a Recurring Payment block added prior to checking out this PR branch.
1. On the frontend, visit post containing previous version of Recurring Payments block.
2. Confirm the blocks display and function as they did when you set them up. 
_Button should still be contained within div with `.wp-block-button` class._
3. Edit the post.
4. Confirm the Recurring Payment block still appears correctly and its settings are correct.
5. Update the Recurring Payment button using the new settings …
=> Recurring Payments: Replace submit button

extensions/blocks/gathering-tweetstorms/editor.js
The Unroll button is clickable (though it does nothing) when a URL hasn't been embedded in the Twitter embed block. This can be slightly confusing if the author pastes a URL into the block, and then clicks Unroll: the URL isn't available as an attribute until after the Embed button has been clicked.
This PR fixes that by setting it to be disabled when there's no URL available.
* Disable the Gathering Tweetstorms Unroll button when there's no URL entered.
N/A
No.
* Use the block inserter to add a Twitter embed.
* Note that the Unroll button is disabled.
* Enter a Tweet URL, and click Embed.
* Note that the Unroll button is enabled.
* Gathering Tweetstorms: Don't enable the Unroll button until after a Twitter URL has been entered and verified.
=> Tweetstorms: Disable the Unroll button when there's no url.

modules/likes/jetpack-likes-settings.php
Resolves:
```
E_NOTICE: /home/public_html/wp-content/plugins/jetpack/modules/likes/jetpack-likes-settings.php:308 - Trying to get property 'post_type' of non-object
```
`is_single` will return `true` if the post object is null, so it's possible to get to this point on a null post. This will check for the type of var of `$post` before assuming it is a `WP_Post`.
* Checks if the output of `get_post` is a WP_Post object before assuming so.
n/a
n/a
* Unsure how to actually duplicate it; fixing based on the logs.
*
* Likes: Fixed a potential PHP notice.
=> Likes: Resolve warning for a non-post object

_inc/lib/class.media-extractor.php, _inc/lib/class.media-summary.php, bin/phpcs-requirelist.js, class.jetpack-twitter-cards.php
Fixes #16499 
Fixes #16500 
Fixes #16501 
PHPCS impacted files.
* Defensive coding to ensure that `$post` is a `WP_Post` object before use.
n/a
n/a
* A simple test would be to intentionally override the global `$post` via a filter on `jetpack_open_graph_tags` at a priority <10 so that the Twitter Card functionality would have a non-object global $post.
* Twitter Cards: Resolve potential PHP notice.
* Media Tools: Resolve potential PHP notice.
=> Media & Twitter Cards: Verify WP_Post object before attempted use.

extensions/blocks/button/button.php, extensions/blocks/button/view.js, extensions/blocks/button/view.scss
Fixes #15697
* Set a default text color for Jetpack button block in AMP mode (without Gutenberg plugin)
This change only addresses the lack of a default text color for Jetpack buttons that is visible against the default button background color when in an AMP view. Given updating the AMP styles from theme color schemes will be much more involved, this simple fix could be shipped in the meantime.
*Note:*
* Custom colors for the background and text get applied as inline styles which in turn get imported to the AMP custom CSS
* Default options from color schemes apply CSS classes which come from themes and so aren't imported to the AMP CSS
e.g. `.has-accent-background-color`
* Gradient colors are imported into the resulting AMP CSS
No.
1. Install and activate the AMP plugin, deactivate …
=> Button Block: Set missing text color in AMP mode 

modules/contact-form/css/grunion.css
Fixes #16128
* Improve alignment of radio and checkbox items within contact forms
**Notes:** 
* These CSS tweaks use `inline-flex`. Despite IE11 not supporting all flex has to offer it works well in IE11 for me.
* Tested across Firefox, Safari, Chrome, Edge, and IE11, using the 2020, 2019 and 2017 themes; 
No changes.
1. Create post adding Jetpack form and some radio buttons and checkboxes
2. Save post and view on the frontend to confirm misalignment of radios and checkboxes
3. Checkout this branch and build client files
4. Refresh the post page on the frontend and confirm field alignments
* Fix alignment of radio and checkbox items within contact forms
=> Contact Form: fix radio and checkbox alignment on frontend

modules/wordads/class-wordads.php, modules/wordads/php/class-wordads-sidebar-widget.php
Our partners at IPW have developed a more dynamic ad loader that allows us to more generally describe the space the ad is in and find the best unit available. This code replaces the standard units (header/belowpost/sidebar) with the dynamic ads. Units added through AMP or Gutenberg will retain their original loaders as there's more work required to make them compliant.
* Updates __ATA ad inits to utilize the dynamic version.
* Units added through Gutenberg or AMP will retain their original calls.
* No
* Notify @dbspringer of the site you plan on testing so he can make sure the dynamic ads are enabled for your site in the backend.
* Enable the Ads module in Jetpack Settings -> Traffic on a Jetpack test site with Premium+ plan.
* Enable all the ad units, some widgets, and create a post with …
=> WordAds: Swap ad calls to dynamic

_inc/client/components/apps-card/index.jsx, _inc/client/components/chart/index.jsx, _inc/client/components/connect-button/index.jsx, _inc/client/components/dash-item/index.jsx, _inc/client/components/footer/index.jsx, _inc/client/components/forms/index.jsx, _inc/client/components/jetpack-dialogue-modern/index.jsx, _inc/client/components/jetpack-dialogue/index.jsx, _inc/client/components/jetpack-notices/feedback-dash-request.jsx, _inc/client/components/jetpack-notices/index.jsx, _inc/client/components/jetpack-notices/jetpack-connection-errors.jsx, _inc/client/components/jetpack-notices/plan-conflict-warning.jsx, _inc/client/components/jetpack-notices/state-notices.jsx, _inc/client/components/jetpack-termination-dialog/dialog.jsx, _inc/client/components/jetpack-termination-dialog/features.jsx, _inc/client/components/jetpack-termination-dialog/survey.jsx, _inc/client/components/masthead/index.jsx, _inc/client/components/mobile-magic-link/index.jsx, _inc/client/components/module-overridden-banner/index.jsx, _inc/client/components/module-settings/connect-module-options.jsx, _inc/client/components/module-settings/index.jsx, _inc/client/components/module-toggle/index.jsx, _inc/client/components/navigation-settings/index.jsx, _inc/client/components/navigation/index.jsx, _inc/client/components/plans/plan-price/index.jsx, _inc/client/components/product-expiration/index.jsx, _inc/client/components/settings-card/index.jsx, _inc/client/components/support-card/index.jsx, _inc/client/components/support-info/index.jsx, _inc/client/components/upgrade-notice-content/index.jsx
This is part 2, follow-up of #13527. We're moving away from `translate` and using the `@wordpress/i18n` package instead.
This PR focusses on updating all components used throughout the dashboard.
**Note: this PR is open against the branch used for part 1 in #13527 for now, hence the "Do not merge" label. Once the other PR is merged I'll update the base branch for this PR.**
* p1HpG7-99c-p2
* N/A
Nothing should change at first sight.
* Everything should look good in the admin dashboard.
* Try activating and deactivating modules, changing settings, connecting / disconnecting
* Try using filters to trigger alternate views; something like #8934 for example.
* Try enabling development mode in different ways: `add_filter( 'jetpack_development_mode', '__return_true' );`, …
=> Admin Page: Move to Core translation functions -- PART 2

_inc/client/discussion/comments.jsx, _inc/client/discussion/index.jsx, _inc/client/discussion/subscriptions.jsx, _inc/client/my-plan/my-plan-body.jsx, _inc/client/my-plan/my-plan-header/checklist-cta.js, _inc/client/my-plan/my-plan-header/checklist-progress-card/index.js, _inc/client/my-plan/my-plan-header/index.js, _inc/client/notices/validation-error-list.jsx, _inc/client/performance/index.jsx, _inc/client/performance/media.jsx, _inc/client/performance/search.jsx, _inc/client/performance/speed-up-site.jsx, _inc/client/plans-prompt/index.jsx, _inc/client/plans/constants.js, _inc/client/plans/duration-switcher.js, _inc/client/plans/plan-grid.jsx, _inc/client/plans/product-selector.jsx, _inc/client/plans/single-product-components/plan-radio-button.jsx, _inc/client/plans/single-product-components/product-options-label.js, _inc/client/plans/single-product-components/product-savings.jsx, _inc/client/plans/single-product-components/promo-nudge.jsx, _inc/client/plans/single-product-components/purchased-product-card.jsx, _inc/client/plans/single-product-components/upgrade-button.jsx, _inc/client/plans/single-product-search/index.jsx, _inc/client/plans/single-product/index.js
This is part 3, follow-up of #13527. We're moving away from `translate` and using the `@wordpress/i18n` package instead.
This PR focusses on updating 3 parts of the dashboard:
- The My Plan and Plans pages
- The Discussion settings
- The Performance settings
**Note: this PR is open against the branch used for part 1 in #13527 for now, hence the "Do not merge" label. Once the other PR is merged I'll update the base branch for this PR.**
* p1HpG7-99c-p2
* N/A
Nothing should change at first sight.
* Check the modified pages (My Plan, Plans, Discussion, Performance) for any changes; you shouldn't see anything odd.
* TBD
=> Admin Page: Move to Core translation functions -- PART 3

_inc/client/privacy/index.jsx, _inc/client/pro-status/index.jsx, _inc/client/searchable-modules/index.jsx, _inc/client/security/antispam.jsx, _inc/client/security/backups-scan.jsx, _inc/client/security/index.jsx, _inc/client/security/jetpack-backup.jsx, _inc/client/security/manage-plugins.jsx, _inc/client/security/monitor.jsx, _inc/client/security/protect.jsx, _inc/client/security/sso.jsx, _inc/client/settings/index.jsx
This is part 4, follow-up of #13527. We're moving away from `translate` and using the `@wordpress/i18n` package instead.
This PR focusses on updating 3 more parts of the dashboard:
- The Security settings
- The Privacy settings (see link in the footer)
- The search functionality
**Note: this PR is open against the branch used for part 1 in #13527 for now, hence the "Do not merge" label. Once the other PR is merged I'll update the base branch for this PR.**
* p1HpG7-99c-p2
* N/A
Nothing should change at first sight.
* Check the modified pages for any changes; you shouldn't see anything odd.
* TBD
=> Admin Page: Move to Core translation functions -- PART 4

_inc/client/setup-wizard/feature-toggle-group/index.jsx, _inc/client/setup-wizard/feature-toggle/index.jsx, _inc/client/setup-wizard/feature-toggle/map-feature-to-props.js, _inc/client/setup-wizard/income-question/index.jsx, _inc/client/setup-wizard/intro-page/index.jsx, _inc/client/setup-wizard/recommended-features/index.jsx, _inc/client/setup-wizard/updates-question/index.jsx
This is part 5, follow-up of #13527. We're moving away from `translate` and using the `@wordpress/i18n` package instead.
This PR focusses on updating one more parts of the dashboard, the Setup wizard.
**Note: this PR is open against the branch used for part 1 in #13527 for now, hence the "Do not merge" label. Once the other PR is merged I'll update the base branch for this PR.**
* p1HpG7-99c-p2
* N/A
Nothing should change at first sight.
* On a brand new site, before you connect, add the following filter:
`add_filter( 'jetpack_show_setup_wizard', '__return_true' );`
* Connect your site to WordPress.com, and once the connection is successful you'll be prompted to start setup.
* Follow the steps; you shouldn't see anything odd.
* TBD
=> Admin Page: Move to Core translation functions -- PART 5

extensions/blocks/button/index.js, extensions/blocks/image-compare/index.js, extensions/blocks/markdown/index.js, extensions/blocks/rating-star/index.js, extensions/blocks/slideshow/index.js, extensions/blocks/tiled-gallery/index.js, extensions/shared/get-category-with-fallbacks.js, extensions/shared/test/get-category-with-fallbacks.js
- Update the category names for relevant Jetpack blocks. More details [here](https://github.com/Automattic/wp-calypso/issues/43198) (**first** task listed in the issue). There's an equivalent [PR](https://github.com/Automattic/wp-calypso/pull/43670) for `wp-calypso`. 
-  Adds a helper function that is used to safely update category names while still supporting old environments
* FSE blocks (wp-calypso): https://github.com/Automattic/wp-calypso/pull/43670
* wpcom-blocks: https://github.com/Automattic/wpcom-blocks/pull/178
* block-experiments: https://github.com/Automattic/block-experiments/pull/110
No.
* `yarn test-extensions`
1. Follow the instructions here to set up your local Jurassic Ninja instance
2. Activate Jetpack
3. To test that old category still work in old environments where …
=> Update blocks categories

extensions/README.md, extensions/shared/create-interpolate-element.js
* While we are not yet clear to use `createInterpolateElement` (it will only be available in WordPress 5.5), we can now rely on `__experimentalCreateInterpolateElement` as Jetpack now requires WordPress 5.4+.
References:
- WordPress 5.5 Compatibility: #15388 
- Jetpack now requires WordPress 5.4+ as of #16445
- `__experimentalCreateInterpolateElement` was introduced in https://github.com/WordPress/gutenberg/pull/17376
* N/A 
* N/A 
* Is my example the best and clearer way to show what can be done?
* N/A
=> Extensions: update documentation: React in strings is now possible

packages/sync/src/class-actions.php
Jetpack Sync utilizes the owner's User Token to send sync actions to WP.com. This PR updates the send process to use the blog token that is user agnostic. This will ensure that Sync actions still are sent and processed even if the user token is removed or modified.
* Update the IXRClient to use generic blog token vs user token.
[p9dueE-1DD]
No change.
This change requires a full regression test of down stream services powered by the WP.com Cache Site. (Publicize, Search, Activity Log, Backups, etc)
* Add a new Post/Page via the WP-Admin
* Access Calypso editor and verify the post/page is available and has same content you just created.
* Enable Publicize and connect to Twitter or Facebook
* Add a new Post and publish
* Verify post is published to social media.
Automattic colleagues, again …
=> Utilize the blog token vs master user token to send sync actions.

modules/sharedaddy/sharing-service.php, modules/sharedaddy/sharing.css
Fixes 116-gh-dotcom-manage
* This PR adds a link under the "Share This" buttons on post pages (for users with sufficient permissions) to the customization screen for those buttons, to make it easier for users to realize that they are indeed customizable.
N/A
No
* Enable share buttons on Jetpack-enabled site by navigating to WP Admin -> Jetpack -> Settings -> Sharing and enabling the "Add sharing buttons to your posts and pages" toggle.
* Navigate to a post on the site, both while logged in as a user with admin permissions (`manage_options`, specifically) and while not.
* Verify that while logged in with permissions, a "Customize buttons" link is displayed under the sharing buttons which links the user to the customization options in Calypso.
* Verify that this option does not exist if the …
=> Sharing - add link to customize share button settings

extensions/shared/register-jetpack-block.js, extensions/shared/register-jetpack-block.native.js, extensions/shared/register-jetpack-plugin.js
- Fixes 22 eslint warnings.
- All changes are within comments, so there are no functional changes.
- These fixes were made by `eslint --fix`, which automatically fixes errors.
- Exception: for jsdoc/no-undefined-types, the "false" type was changed
to "boolean".  See https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-no-undefined-types
```
These warnings were present before this commit:
/home/matta8c/h20/dev/jetpack/extensions/shared/register-jetpack-block.js
26:0  warning  There must be a hyphen before @param description                jsdoc/require-hyphen-before-param-description
27:0  warning  Invalid JSDoc @param "details" type "Object"; prefer: "object"  jsdoc/check-types
27:0  warning  There must be a hyphen before @param description …
```
=> JSDoc Comments: Fix eslint warnings

extensions/blocks/subscriptions/deprecated/index.js, extensions/blocks/subscriptions/deprecated/v3/attributes.js, extensions/blocks/subscriptions/deprecated/v3/get-subscriptions-shortcode.js, extensions/blocks/subscriptions/deprecated/v3/index.js, extensions/blocks/subscriptions/deprecated/v3/save.js, extensions/blocks/subscriptions/deprecated/v4/index.js
Fixes #15776
* Stop saving localized attributes defaults in the Subscriptions block content.
The Subscriptions block has two attributes with localized default values which are saved in the block content as shortcode attributes. Changing the site language will break the block validation, because the strings are saved in the previous language, while the validator expects them to be in the new language.
In this PR we stop adding those attributes to the shortcode if they are the same as the default (haven't been changed by the user).
The shortcode will take care of those missing attributes by using [its own defined defaults](https://github.com/Automattic/jetpack/blob/020effc64833fa2f378d1b8a9a18ff0b8a118672/modules/subscriptions/views.php#L625-L653).
There have been two deprecated versions …
=> Subscriptions Block: Stop saving localized attributes defaults in the block content

_inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/wpcom-endpoints/business-hours.php, _inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php, _inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-mailchimp.php, _inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-gather.php, _inc/lib/core-api/wpcom-endpoints/hello.php, _inc/lib/core-api/wpcom-endpoints/service-api-keys.php, packages/connection/src/class-error-handler.php, packages/connection/src/class-rest-connector.php
See #16539
I consider this an incomplete fix to silence the errors and so our unit testing isn't blocked. But, the ones that I added, we should review to ensure it is intentional.
* Adds a permission_callback for all endpoints that lacked one.
n/a
n/a
* Run a connected Jetpack on WP trunk.
* Any notices?
* n/a would make a part of a general WP 5.5 compat line.
=> REST API: Add permission callback to all that lack one.

_inc/lib/class.core-rest-api-endpoints.php, packages/connection/src/class-manager.php, packages/connection/src/class-rest-connector.php, packages/connection/tests/php/test-rest-endpoints.php, packages/connection/tests/php/test_Manager.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
Some of the endpoints can function without Jetpack, especially the ones that return status of the connection, and manage it.
This is the first effort to split the REST endpoints between Jetpack and `jetpack-connection`.
* Moved following REST endpoints into `jetpack-connection` package:
- `jetpack/v4/remote_authorize`
- `jetpack/v4/connection`
- `jetpack/v4/connection/plugins`.
* Unit tests for these endpoints.
`p9dueE-1qA-p2`
1. Go to "Jetpack -> Debug Tools" and enable "REST API Tester".
2. Go to "Jetpack -> REST API Tester" and send the POST request:
* Endpoint: `remote_authorize`
* Body (replace `[user_id]` with the primary user ID: `{ "state": [user_id], "secret": "12345", "redirect_uri": "http://jetpack.com", "code": "54321" }`
* If the site is already connected, you …
=> REST API: Move some endpoints to `jetpack-connection` package.

modules/widgets/social-icons.php, tests/php/modules/widgets/test_social-icons-widget.php
Fixes #16484
* Add the `rel="noopener noreferrer"` attribute to links in the Social Icons widget that have a `target="_blank"` attribute.
* Add a small unit test that covers the change in this PR.
* n/a
* no
1. The test site must have Jetpack active and connected.
2. The test site must have extra sidebar widgets enabled.
3. Navigate to wp-admin -> Appearance -> Widgets.
4. Add a Jetpack Social Icons widget to your test site and add a few URLs to the widget. Check the `Open link in a new tab` checkbox and save.
5. While still on the Widgets page, open your browser's inspector, and confirm that the `View available icons` link includes  the `target="_blank"` and `rel="noopener noreferrer"` attributes and that the link is properly formatted.
6. Click the `View available icons` link and …
=> Social Icons Widget: add rel attribute to links

.github/actions/repo-gardening/src/tasks/assign-issues/index.js
Fixes https://github.com/Automattic/jetpack/issues/16532
This avoids assigning unrelated issues to folks who use number in their PRs.
* N/A
* N/A
* The associated issue (#16532) does not have a Progress label right now.
* In a minute, I'll add a comment on the issue to mark the time.
* I will then edit this PR to add `Fixes #theissuenumber` 
* The issue should be triggered and the label will be added.
* N/A
=> Repo Gardening: only assign issues when necessary

modules/contact-form/grunion-contact-form.php
* Contact Form: avoid deprecated notices when submitting a form
See https://make.wordpress.org/core/2020/07/23/codebase-language-improvements-in-5-5/
Primary issue: #15388 
* N/A
* N/A
From 2 sites, both running this branch, one running WP 5.4.2 and another WP 5.5:
* Activate contact form feature.
* Add a form to a post
* Under Settings > Discussion, add the word "jeremy" to the comment disallowed list.
* View the post with your form, and submit a form with that word.
* The form should be submitted successfully, with no notices in your log, and you should see the form submission in the Spam category in the Feedback menu in wp-admin.
* Contact Form: updates based on language improvements in WordPress 5.5.
=> Contact Form: avoid deprecation notice in WP 5.5

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
* WordPress.com REST API: query the right option depending on WordPress version.
* See https://core.trac.wordpress.org/changeset/48575
Primary issues: #15388 and #16099 
* Note: indenting is off in some of those files. In a separate PR I'll aim to fix all indenting in these big arrays.
* N/A
* N/A
From 2 sites, both running this branch, one running WP 5.4.2 and another WP 5.5:
* Go to https://developer.wordpress.com/docs/api/console/
* Query the `/sites/%s/settings` endpoint for your site.
* You should see the 4 fields concerned by this PR return the right values, and no notices on your site.
* WordPress.com REST API: adjust API response based on language improvements in WordPress 5.5.
=> WordPress.com API: take new option names into account

modules/carousel/jetpack-carousel.php
Fixes #16550
In 0507aa58fae1eca84e6115217da90d84cb1a0c93, we removed another dependency that itself depended on jQuery.
Since the Carousel script relies on jQuery, let's add it as a dependency.
**Note**: in the future we should be able to get rid of this dependency for good as we keep working on #16420.
* N/A 
* N/A 
Start with a site with no other plugin, no other Jetpack feature active, and the Twenty Twenty theme.
1. Enable Carousel.
2. Publish a post with a gallery.
3. It works when logged in.
4. Log out
5. Carousel should still work. You should see no errors in the console.
* Carousel: ensure jQuery is loaded when using the Carousel feature.
=> Carousel: add jQuery script dependency

package.json, yarn.lock
It should help us avoid having to skip the wpcalypso/import-docblock rule like here:
https://github.com/Automattic/jetpack/pull/16545#discussion_r459287221
More info about the update:
https://github.com/Automattic/wp-calypso/pull/44388
* N/A
* N/A
* N/A
=> Linting: update to latest version of eslint-plugin-wpcalypso

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, json-endpoints/class.wpcom-json-api-get-site-v1-2-endpoint.php, sal/class.json-api-site-jetpack.php
Differential Revision: D46165-code
This commit syncs r210825-wpcom.
Since we've decided to stop and roll back the Expert Guidance upsell experiment as described here: pbxNRc-gv-p2#comment-485,
this patch aims to roll back the changes introduced in r208548-wpcom (in Jetpack in #16089).
It is made by as the following:
1. Create a direct revert by running the command
1. There are simple merge conflicts in public.api/rest/json-endpoints/class.wpcom-json-api-get-site-endpoint.php and public.api/rest/json-endpoints/class.wpcom-json-api-get-site-v1-2-endpoint.php. Resolving them by keeping the current trunk version while removing `is_white_glove` references.
* N/A
* N/A
1. Review and confirm it's just a direct revert of r208548-wpcom, plus removing `is_white_glove` from …
=> Revert the backend changes for the Expert Guidance experiment.

modules/calypsoify/class.jetpack-calypsoify.php
Fixes Automattic/wp-calypso#41858
As reported in Automattic/wp-calypso#41858, the back link is still using the stats
page as the home page in Calypso. This change swaps that to `/home/` and
updates the 'My Sites' link also.
If the site can't view the Customer Home, then it will be redirected back to the stats page.
* On a Jetpack/Atomic test site load a wp-admin page with the `calypsoify` query parameter, such as `/wp-admin/plugins.php?calypsoify=1`
* With the Calypsoified view, click on the backlink in the top of the sidebar, and ensure that it takes you back to Customer Home or the stats page, as appropriate
* Similarly check the My Sites link in the master bar. 
No, this doesn't make any changes to data.
I don't think one is needed, as this is a bug fix that's probably not of interest …
=> Calypsoify: Change the default link to Customer Home

packages/connection/src/class-manager.php
Adds error messages to some common XML-RPC connection errors.
These error messages will be displayed in the Jetpack Debugger.
p9dueE-1Ce-p2
No
* Start with a fresh Jetpack site, connected and authorized
* Install / activate the Debug Helper plugin (already available on docker env) - https://wp.me/p9dueE-1Ce
* Go to Jetpack >Dev tools and activate the Broken Token module
* set the `JETPACK_DEV_DEBUG` constant to `true`
* Go to Jetpack > Broken token
* Click "Store these options"
* Click "Set invalid blog token"
* Visit the Jetpack debugger
* Back to your dashboard, go to Jetpack > XML-RPC Errors
* Confirm there's an error with error code `no_valid_token` and message `Invalid blog token`.
* Clear all errors
* go back to Jetpack > broken token and click "Restore from stored options"
* Click …
=> add messages for some common connection errors

sal/class.json-api-site-base.php
Required for Automattic/wp-calypso#43520
This capability does already exist under `activate_wordads`.
https://github.com/Automattic/jetpack/blob/2e190a1ffe33df32f19a0632d5e6f34589e79035/sal/class.json-api-site-base.php#L424
However, it also needs to be used in a wider context outside WordAds, and it was agreed that it'd be better to introduce a new check rather than relying on a feature which could change in the future. 
From https://github.com/Automattic/wp-calypso/pull/43520#issuecomment-647788436:
> It feels a bit fragile. If WordAds was changed or withdrawn for any reason, the feature may not work as expected. Let's try and find another way to identify that the current user is not the site owner.
No.
I've primarily made this change based on looking at examples for adding different …
=> API: Add owns_site Capability to Sites Endpoint

modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
Fixes `Notice: Undefined index: calypsoify_cookie_check in /srv/users/user7272d637/apps/user7272d637/public/wp-content/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php on line 98`
Introduced in https://github.com/Automattic/jetpack/pull/16167
* Check the var before use.
n/a
n/a
* Open the desktop app
* Select Jetpack site (with SSO enabled)
* Open Gutenberg
* Wait ~1 min.
* Error without the patch.
See p1595360260179800-slack-jetpack-plugin for the initial report.
* Fix: PHP notice emitted when using the WordPress.com Desktop App.
=> WPCOM Block Editor: Check for the _GET var before use

extensions/blocks/donations/attributes.js, extensions/blocks/donations/context.js, extensions/blocks/donations/controls.js, extensions/blocks/donations/fetch-default-products.js, extensions/blocks/donations/fetch-status.js, extensions/blocks/donations/loading-error.js, extensions/blocks/donations/loading-status.js
Follows up #16545.
Remove the eslint exceptions disabling the `wpcalypso/import-docblock` from the donations block now that `eslint-plugin-wpcalypso` has been updated in #16566.
N/A
N/A
Make sure CI builds pass.
N/A
=> Donations block: Remove "import-docblock" rule exceptions

composer.json, composer.lock
This PR adds the new MC Stats package as a dependency to Jetpack. It does not use it anywhere.
p9dueE-1tz-p2
No
Nothing to test, just run `composer install` and checks if the new `Mc_A8c_Stats` class is available.
* Adds new MC Stats package as a dependency for jetpack
=> Adds MC Stats package as a dependency for Jetpack

_inc/client/components/jetpack-notices/index.jsx, class.jetpack.php, packages/connection/src/class-rest-connector.php, packages/status/src/class-status.php, packages/status/tests/php/test-status.php
This PR builts on top of #16338. **It is open against that branch**.
It does 3 things:
- It expands our list of known staging sites to detect more hosting providers. @Automattic/jetpack-infinity I'm adding you as reviewers for this PR so you can review and maybe warn hosting providers if necessary?
- It adds a new method to the Status package, allowing us to better detect local sites, as discussed here:
https://github.com/Automattic/jetpack/issues/11798#issuecomment-651514631
- It uses that new method in the Admin dashboard and in Site Health checks.
**Before**
**After**
* N/A
* N/A
* On a local site, go to Tools > Site Health and Jetpack > Dashboard, and check the messages as per the screenshots above.
* Connnection Tools: improve local development environment detection.
=> Status: add new method to check for a local development site, and expand list of staging sites.

packages/autoloader/src/class-autoloader-handler.php, packages/autoloader/src/class-plugins-handler.php, packages/autoloader/src/functions.php
* On Windows, the directory separator is a `\`. Normalize the plugin paths by converting `\` separators to `/`.
* N/A
* No
1. Install and activate Jetpack using WP-CLI.
2. Observe the fatal error.
If possible, test in both Linux and Windows environments.
1. Install Jetpack.
2. Activate Jetpack using wp-admin and confirm that no errors occur.
3. Deactivate Jetpack.
4. Activate Jetpack using WP-CLI and confirm that no errors occur.
* Autoloader: normalize file paths so the autoloader will work properly in Windows environments.
=> Autoloader: convert '\' directory separators to '/' in plugin paths

packages/debug-helper/modules/class-broken-token.php
1. Adding a button to break the token for current user only, and leave the rest intact.
2. Currently if there are more than one user tokens, only last token gets "broken", the rest are removed. This commit fixes the issue, allowing "breaking" of all existing tokens instead of deleting them.
No.
This is a minor change in the internal debugging tool, no testing is necessary.
1. Login as a separate user (non-master), doesn't matter if it's connected to WordPress.com or not.
2. Go to "Jetpack -> Broken Token". Click on the button `Set invalid user token (current user)`.
3. Take a look at the user tokens dump, make sure that your user token has been broken (even if it didn't exist before).
4. Make sure that other tokens remain intact.
n/a
=> Broken Token: Breaking user tokens improvement

class.jetpack-gutenberg.php, extensions/editor.js, extensions/shared/plan-utils.js, extensions/shared/premium-blocks/index.js
This PR adds the `jetpack-enable-upgrade-nudge` CSS class to the document body when the site has enabled the Upgrade Nudge feature.
This class will be used in the next PRs to deal with some visual adjustments needed to implement the new Banner upgrade design. You'd like to take a look at [this commit](https://github.com/Automattic/jetpack/pull/16495/commits/15233684e431a8fd195f490049fd7ea936f80644) to see how it's used to add custom icons to the premium blocks.
This PR is referenced to the `feature/premium-blocks ` feature branch.
* Add CSS class to body when upgrade-nudge is enabled.
no
* Apply this changes in your sandbox (D47020-code)
* Test in a _Simple site_ with a _Free Plan_
* ✔️ Confirm the `enable_upgrade_nudge` is true in the global Jetpack object in …
=> Premium Blocks: add CSS class to body when Upgrade Nudge is enabled

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php, class.photon.php, extensions/shared/external-media/sources/with-media.js, tests/php/test_class.jetpack_photon.php
See #16425 
This is very similar to an issue that @kraftbj recently fixed in #16287 
* Do not process images with Photon when inserting from external services like Pexels or Google Photos
* Properly attach the photo to the post when copying
This came from a request from Galactica via Slack.
No 
- Connect site
- Add post and insert an image from Pexels or Google Photos
- Go to Media library and select new image
- Ensure that image is properly attached to post
* Fixes issue where images from Pexels or Google Photos weren't attached to posts
=> External Media: Fix image not attaching or being recognized as "used" in a post

class.jetpack.php
This PR avoids conflicts in the public Edit Post link if other plugins are filtering it.
The problem occurs when the `jetpack_edit_links_calypso_redirect` option is set to `true` and Jetpack changes all the "Edit" links to calypso instead of wp-admin.
Since our filter returns an escaped url, filters that run later might end up breaking it. This was reported and was happening with the Classic Editor plugin.
There are 2 ways of fixing this:
1. Change the filter priority, and let it run later after any other filters. For some reason, the priority of this filter is 1.
2. Remove the `esc_url` call at the end of the function.
Looking at the alternatives, I decided to go with option 2. It makes sense not to escape the URL at this point, since the original …
=> avoid conflict with other plugins filtering edit url

extensions/shared/components/upgrade-nudge/index.jsx, extensions/shared/plan-utils.js, extensions/shared/premium-blocks/edit.js, extensions/shared/premium-blocks/editor.scss, extensions/shared/premium-blocks/index.js, extensions/shared/premium-blocks/upgrade-plan-banner.jsx, extensions/shared/register-jetpack-block.js
**This PR depends on https://github.com/Automattic/jetpack/pull/16602 so review it before starting with this.**
This PR adds the Upgrade Plan Banner in the block inspector.
Fixes https://github.com/Automattic/wp-calypso/issues/44057
* Add Upgrade Plan Banner to Block inspector.
no
* Apply these changes in your sandbox ( D47027-code )
* Test in a Simple site with a Free Plan
* Add a Premium block to the editor.
* Confirm that you see the Upgrade button Block Inspector.
* Confirm that clicking on the Upgrade button it leads to user to the checkout page.
This PR also handles saving post when the user clicks on the Upgrade button. Check that:
* If the post doesn't have changes, clicking on the Upgrade button leads to the checkout page immediately.
* If there are …
=> Premium Blocks: Add upgrade banner to block inspector

extensions/blocks/donations/icon.js
This PR sets premium icons for donations block in jetpack
This PR is referenced to the [`feature/premium-blocks ` feature branch](https://github.com/Automattic/jetpack/pull/16611).
Fixes #16628
* Set icon for Donations Block in Jetpack.
no
* Apply these changes in your sandbox
* Test in a Simple site with a Free Plan
* Check that the donations block show a little red circle indicating it is premium.
* Set premium icon indicator for Jetpack Donations Block.
=> Premium Blocks: Add premium indicator to donations block icon

class.jetpack-cli.php, packages/sync/src/class-actions.php, packages/sync/src/class-sender.php, tests/php/sync/test_class.jetpack-sync-actions.php, tests/php/sync/test_class.jetpack-sync-sender.php
As of Jetpack 8.3 the jetpack sync start cli command would initiate a Full Sync but would not continually send data. This update adds appropriate logic so that the command will run until the full sync has completed. This is re-applying the logic in https://github.com/Automattic/jetpack/pull/16010 that got reverted in 8.6.1 due to not having proper checks for cron behavior. (p1HpG7-9pe-p2)
Adds a check for the Full Sync Module in use to properly send data until the Full Sync is complete when using `jetpack sync start` cli
Resolves an issue introduced in 8.3
No
TEST CLI Command
1) execute `wp jetpack sync start` from the remote site's cli
2) Verify that the command runs until complete "Success: Finished syncing to WordPress.com"
Test Standard Full Sync Flow
3) Trigger a Full Sync from the …
=> Rework Sender to properly return state during do_full_sync

extensions/shared/premium-blocks/index.js
This PR populates the blocks keywords with the`premium` word when they are premium blocks.
* Populate block keywords with `premium` when the block is premium.
no
* Apply these changes in your sandbox
* Test in a Simple site with a Free Plan
* Confirm that typing `premium` word the blocks inserter shows all premium blocks
**before** | **after**
-----------|----------
*
=> Premium Blocks: populate blocks keywords with Premium

packages/debug-helper/README.md, packages/debug-helper/class-admin.php, packages/debug-helper/modules/class-broken-token.php, packages/debug-helper/modules/class-rest-api-tester.php, packages/debug-helper/modules/inc/class-broken-token-xmlrpc.php
Jetpack debug helper is a plugin that brings some Debug tools to help you test things in Jetpack.
One of its main uses right now is to test the connection package, allowing us to break the tokens in many ways, inspect XML-RPC errors, and test local REST API endpoints.
Since we often want to make sure all the packages' features will work seamlessly when used by other plugins, without Jetpack, it makes sense for these debug tools to be available even when the Jetpack plugin is not active.
This PR moves all the Debug tools to its own top-level admin menu and makes sure that everything will work without Jetpack.
no
* First go to you admin Dashboard and visit "Jetpack Debug" menu
* Test activating and deactivating modules
* Test the features and make sure it works as before
* Deactivate …
=> Make jetpack debug plugin work without Jetpack

_inc/client/components/jetpack-notices/notice-action-reconnect.jsx
* Adds tracking to the when the "Reconnect" dialog is displayed to the user
Yes, it tracks when the "Reconnect Jetpack" error dialog is displayed to the user
* Set up a connected jetpack site
* Use the Jetpack debug helper plugin
* Go to Broken Token and clik "Set invalid blog token"
* Visit the Jetpack Dashboard
* Open the console and type `localStorage.setItem('debug', 'dops:analytics');`
* Refresh the window
* Confirm you see the error dialog (like the image below)
* Confirm you see the tracking debug in the console: `dops:analytics Record event "jetpack_termination_error_notice_view"  ... `
* Confirm this debug message appears only once.
* Tracks the number of times the "Reconnect" dialog is displayed
=> Tracks the Reconnect dialog display

extensions/blocks/story/edit.js, extensions/blocks/story/player/index.js, extensions/blocks/story/player/lib/shadow-root.js
This fixes the Story block on sites which replace the default CSS asset for the story block. This currently happens on WPCOM which groups the CSS of all blocks present on the page into one. This "optimization" prevents the Story block from finding the CSS/link element in the page and injecting it into each shadow dom so stories end up broken, without CSS.
Example of broken post containing a story on WPCOM: https://alexforcierbetablocks.wordpress.com/2020/07/24/story-post/
- Make the CSS selector more flexible by matching on the href property as well
- Prevent using shadow DOM if no styles are found
- Apply patch to a Jetpack site
- Make sure Story block are still functioning on the frontend and backend
No changelog if merged before the release
No change
=> Story Block: fallback to no shadow DOM if we cannot find the block styles in the page

_inc/client/at-a-glance/style.scss
The `width: 70%` rule in the Account connection panel causes the email address to wrap when it's longer than the line above. Removing the width allows the email address to scale the entire width of the panel, and then `word-wrap` if necessary.
Fixes #16641 
* Removes one line of CSS for the At a Glance dashboard to fix wrapping email addresses when they don't need to wrap
No
* Go to **Dashboard > At a Glance** on a connected Jetpack site
* Scroll down to the Account connection panel
* Note the screenshots below:
**Before:**
**After:**
**Edge Case (really long email address):**
* No changelog entry needed
=> Remove CSS width on Account connection panel text

class.jetpack-plan.php, extensions/blocks/social-previews/editor.js, extensions/blocks/social-previews/editor.scss, extensions/blocks/social-previews/index.js, extensions/blocks/social-previews/social-previews.php, extensions/index.json, package.json, yarn.lock
Fixes #16594
TODO:
* adds very basic scaffolding and place where we'll later put our code
no
For working on this feature, set constants in wp-config:
```
define( 'WP_DEBUG', true );
define( 'JETPACK_BETA_BLOCKS', true );
define( 'JETPACK_DEV_DEBUG', true );
define( 'SCRIPT_DEBUG', true );
define( 'GUTENBERG_DEVELOPMENT_MODE', true );
```
* Load the block editor and lookup `window.Jetpack_Editor_Initial_State.available_blocks['social-previews']`
* it should return `{ available: true }`
No other UI is expected at this point, we have them as separate tasks.
* none yet
=> Social Preview: Add scaffolding for the feature

_inc/client/traffic/ads.jsx
Fixes #16647
* Hide Ads.txt section completely for subdir sites
n/a
n/a
* Use subdir site
* Enable WordAds on your site
* Go to `/wp-admin/admin.php?page=jetpack#/traffic`
* Make sure that Ads.txt section **is not** present, and there are no placeholders is present.
* Use singlesite site (🤦 )
* Enable WordAds on your site
* Go to `/wp-admin/admin.php?page=jetpack#/traffic`
* Make sure that Ads.txt section **is** present, and there are no placeholders is present.
**Before:**
**After:**
* Hide Ads.txt settings section for subdirectory sites
=> Settings: check for subdirectory site before rendering Ads.txt section

modules/scan/admin-bar-notice.js
In testing the new onboarding wizard screen for the AMP plugin (coming in v2.0), I noticed that Jetpack is throwing a JS error the Admin Bar is not printed on the screen.
1. Activate the latest 2.0 beta of the AMP plugin.
2. Access the new onboarding wizard.
3. See error in the console.
* Avoid JS error when Admin Bar not present and Site Scan's `update_threats_link()` is called.
=> Site Scan: Short-circuit update_threats_link() if Admin Bar is not present

_inc/client/components/global-notices/style.scss, _inc/client/components/notice/index.jsx
The notice content should not contain HTML. If it happens to have any, we clear out the tags before displaying the error.
* Removing HTML tags from the error text.
* Limiting the maximum width of the notice.
No.
1. Open your theme's `functions.php` and add following code to display the connection error notice:
```php
add_filter( 'react_connection_errors_initial_state', function( $errors ) {
$errors[] = array(
'message' => __('Connection Error'),
'action' => 'reconnect',
'code' => 'invalid_blog_token',
);
return $errors;
} );
```
2. Open file `packages/connection/src/class-rest-connector.php` and add this line into the beginning of the `connection_reconnect()` method:
```php
return rest_ensure_response( new WP_Error( 'some_error', str_repeat( ' something something <strong>HTML</strong> …
```
=> Error Notice: removing HTML code, adjusting maximum width.

extensions/blocks/recurring-payments/edit.jsx
When a page that uses the recurring payments block is reopened in block editor, the plan is disconnected from the payments block.
This issue does not always happen but can be consistently reproduced on the site mentioned in p2EDhh-13q-p2.
See before & after video in: p2EDhh-13q-p2#comment-6488
The recurring payment's block attribute schema says that `planId` should contain an integer. However, the `planId` that was set by `setMembershipAmount()` function is a string.
When the page is reopened for editing in block editor, the `planId` value is then invalidated, what used to contain the value of the planId becomes `undefined` when the block goes through Gutenberg's `getBlockAttributes()` function, causing the block to be disconnected from the plan.
More information about this can be seen …
=> Fix recurring payments block disconnected from plan when page is reopened in block editor.

_inc/client/components/dash-item/index.jsx
Follow-up from #16497
I missed this string when moving away from `i18n-calypso`. This should fix that.
* N/A
* N/A
* Go to Jetpack > Dashboard on a site with a plugin that needs updating
* This notice should look good:
* N/A
=> Admin Page: update string still using old i18n format

_inc/client/components/notice/index.jsx
* Follow-up of #16690
The contents of the dashboard notices is not always a string. It can be a React element.
When that's the case, let's avoid any errors by not using the replace method which is only available for strings.
* N/A
* N/A
* Activate [Jetpack's Offline mode](https://jetpack.com/support/development-mode/) on your site, to trigger this notice in your dashboard:
https://github.com/Automattic/jetpack/blob/4392a22d643eaf812f42c37739bf675ea3ef7f34/_inc/client/components/jetpack-notices/index.jsx#L155
* Visit Jetpack > Settings
* Notice a blank dashboard with the following error: `react-dom.min.js?ver=16.9.0:103 TypeError: e.replace is not a function`
* Switch to this branch.
* The dashboard should now load.
* Deactivate Offline mode and try the instructions in #16690; they should …
=> Admin Page: avoid blank dashboard when notice is not a string

3rd-party/woocommerce-services.php
* Since Jetpack comes with its own lib to install and activate plugins, let's use that instead of duplicating code.
* N/A
* N/A
This is a bit of a tricky one.
Start with a site:
- With this branch
- Connected to WordPress.com
- With Woo active and configured
- With at least one order
- Without the WooCommerce Services plugin installed.
- With the following code snippet (we want to force JITMs to show, they're hidden at the moment):
```php
function jeherve_show_woo_jitm() {
?>
<style>
.woocommerce-layout__notice-list-hide {
display: block !important;
}
</style>
<?php
}
add_action( 'admin_head', 'jeherve_show_woo_jitm' );
```
* Then go to WooCommerce > Orders
* You should see the JITM inviting you to install the Woo Services plugin
* Click to install
* Verify that the installation went …
=> Woo Services: update to use existing Jetpack plugin install tools

.wp-env.json, tests/e2e/lib/pages/wpcom/pick-a-plan.js
Since personal plan is removed, we need to update a locator to address that change
n/a
n/a
* Travis should be green again
*
* n/a
=> E2E Tests: Fix locator for classic connection flow

packages/connection/README.md, packages/connection/docs/xmlrpc-async-calls.md, packages/connection/src/class-xmlrpc-async-call.php, packages/connection/tests/php/test_XMLPC_Async_Call.php
Introduces a new class to handle async XML-RPC requests and replace `Jetpack::xmlrpc_async_call()`
Currently, `Jetpack::xmlrpc_async_call()` is used to enqueue few XML-RPC requests that are sent all at once, as a MultiCall request, at shutdown. This method forces the requests to use the "Master user" token.
As we are moving to give preference to the blog token everywhere we can, and the current user token where we are performing a user action, we needed a more flexible method that allowed us to choose which token we wanted to use.
To modify this method while keeping backward compatibility would result in a not very elegant solution, polluting the Jetpack class even more and adding complexity to an untested method. So I decided to create a new class to handle this, removing the …
=> New class to handle async XML-RPC requests

package.json, yarn.lock
After #16461, we started seeing some extremely increased build times and node-module sizes. We tracked this down to lodash, so reverting back for now.
=> Lodash: Revert to previous version

extensions/blocks/social-previews/editor.js, extensions/blocks/social-previews/index.js, extensions/blocks/social-previews/panel.js
Builds on https://github.com/Automattic/jetpack/pull/16633 to address the need to make Social Previews a paid feature on WordPress.com.
This PR will address the frontend aspect of this by creating a new "Gutenberg Plugin" `social-previews-upgrade-nudge` (note this is _not_ a WordPress Plugin in the traditional sense - [see here](https://github.com/WordPress/gutenberg/tree/65258a077e4899ee4933c79077108f56f8b5ce6d/packages/plugins)) which will be registered _only_ when the `social-previews` feature is not available on the current plan. 
It will show the exact same UI as the main `social-previews` Plugin but include an upgrade prompt instead of a link to display the "Preview" modal.
Note: the reason this is required is because `registerJetpackPlugin` checks whether the `social-previews` …
=> Make Social Previews a gated feature on WPCom

packages/connection/src/class-error-handler.php
This PR adds tracking of sites that have a orphan user token key for a deleted user who is still marked as the connection owner. This helps us understand what sites could be affected if we deleted these old tokens that trigger the `unknown_user` error from the wpcom's database.
p9dueE-1GB-p2
Not significantly. It just tracks a boolean indicating whether the site still has a valid token from a deleted user which is still being used to make requests to wpcom
* Start with a connected jetpack site
* Create a secondary admin user
* Log in as the secondary admin user
* Move your master user away. Directly in your database: `UPDATE wp_users SET ID = 99 WHERE ID = 1` (Replace Ids as needed)
* Go to Jetpack Debug > XML-RPC Errors
* Click the link and visit the Jetpack debugger. Wait until it …
=> add tracking for deleted but active master users

class.jetpack.php, modules/seo-tools.php
This PR adds [Slim SEO](https://wordpress.org/plugins/slim-seo/) to the list of supported SEO plugins to avoid conflict/duplication of outputting meta tags and sitemaps.
=> Add Slim SEO to list of SEO plugins

class.jetpack-plan.php
Remove the donations feature from Jetpack Personal since we're removing that plan. Donations now require a Jetpack Premium plan.
p1HpG7-9NV-p2
No.
* With a WordPress instance of your choice, install Jetpack Beta and activate this branch. Or visit https://jurassic.ninja/create/?jetpack-beta&branch=update/donations-required-plan.
* Connect Jetpack to WordPress.com with a free plan.
* Make sure Jetpack beta blocks are visible by going to /wp-admin/options-general.php?page=companion_settings and activating `JETPACK_BETA_BLOCKS`. 
* Note that if folks are using the sandbox store method (PCYsg-lW4-p2) to also set the `JETPACK__SANDBOX_DOMAIN` value.
* Go to Posts > New
* Make sure the Donations block doesn't show up in the inserter.
* Upgrade to Jetpack Premium (ideally we should test that the …
=> Donations: Remove feature from Personal plans

docker/mu-plugins/avoid-plugin-deletion.php
Removes Warning that happens sometimes when using `wp cli` in our docker env.
```
[07-Aug-2020 18:16:21 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-content/mu-plugins/avoid-plugin-deletion.php on line 68
```
do not apply
No
I didn't dig to find the reasons and a way to reproduce this warning. I can tell that for me, right now, if I
* check out https://github.com/Automattic/jetpack/pull/16758
* `wp option get jetpack_protect_key`
I get this Warning on the error log. But I'm not sure what are the conditions to trigger this. Anyway I think this is a safe fix.
* No need
=> avoid warning on wp cli

tests/e2e/lib/reporters/slack.js
* CC myself only on failures on master
* Add Travis job URL into slack messages
n/a
n/a
* Nothing to test here, really.  
*
* n/a
=> E2E Tests: Updates to slack reporter

tests/e2e/lib/pages/wp-admin/login.js
.org login sometimes fails due to puppeteer failing to type in the credentials correctly. It's kinda hard to figure out why this is happening, so I added a retry attempt to the login method.
* add retry to .org login method
n/a
n/a
* Travis tests still should be green
*
* n/a
=> E2E tests: Add retry to .org login method

extensions/blocks/donations/amount.js, extensions/blocks/donations/common.scss, extensions/blocks/donations/editor.scss, extensions/blocks/donations/save.js, extensions/blocks/donations/tab.js, extensions/blocks/donations/tabs.js, extensions/blocks/donations/view.js, extensions/blocks/donations/view.scss
Some sites such as any WP.com simple site might have a more restricted KSES logic that doesn't allow `<button>` elements in a post content. 
To work around that, this PR modifies the output of the Donations block so all `<button>` elements are replaced with semantically equivalent `<div role="button">` elements, which are allowed in WP.com. We still need to allow the `data-*` attributes in WP.com KSES, but that will be handled in separate WP.com patch. The `contenteditable` attribute has been also removed from the post content and it's set not dynamically with JS so it doesn't need to be allowed by KSES.
It also simplifies the general markup by removing all `wp-block-buttons` and `wp-block-button` classes, so we need to override less styles.
p1HpG7-9NV-p2
No.
- On a WP.com sandbox, apply …
=> Donations: Avoid using buttons elements in block output

_inc/client/security/backups-scan.jsx, _inc/client/security/jetpack-backup.jsx
The wording for the **Backups and security scanning** card in **Settings** has caused some confusion in the past (see links in "Jetpack product discussion"), so this PR attempts to fix that. Overall, the goal is to reduce the implication that successful backups exist while still explaining that backup functionality is enabled/active.
Fixes `1164141197617539-as-1156835636217697`.
* Change copy on the Security settings page for Jetpack Backup and VaultPress customers, so that we don't imply backups have been made.
Original report: p6TEKc-2ZM-p2
Conversation on what copy to use: p1596726897175800-slack-C0D96691V
* Test with sites that meet the following criteria:
* Scan and Backup with VaultPress
* Scan and Backup with Rewind
* Backup only with VaultPress
* Backup only with Rewind (unchanged …
=> Settings: Change copy to not imply backups have been successful

class.jetpack.php, packages/connection/src/class-manager.php, tests/php/_inc/lib/test_class.rest-api-authentication.php, tests/php/modules/post-by-email/test-class.post-by-email-api.php
Fixes #16488
See #15388
* Removes last mentions of `HTTP_RAW_POST_DATA`.
* class.jetpack.php -- Removes a usage that could be replaced with `php://input`. It was used for pre-PHP5.6 that couldn't read the input multiple times.
* connection package -- removes a trim for mozblog. We never specifically used this, it was part of a copy/paste from Core's xmlrpc.php that was added into our alt xmlrpc endpoint.
* Tests -- remove references that were there to reset after a test.
n/a
n/a
* verify unit tests pass.
*
* Cleaner Code: removes reference to pre-PHP 5.6 code.
=> Remove usages of removed HTTP_RAW_POST_DATA

class.jetpack-gutenberg.php, extensions/blocks/social-previews/editor.js, extensions/blocks/social-previews/editor.scss, extensions/blocks/social-previews/upgrade.js, extensions/shared/urls.js, images/social-previews.svg
Fixes #16729
* implements the nudge design from #16729 
—
no
- follow setup steps from #16615 
- this PR currently shows both paid and unpaid versions of the sidebar. Click the one with "Learn More" button and it opens up this upgrade nudge
none
=> Social Previews: Upgrade Nudge in Modal

modules/subscriptions.php
This PR changes the token used to dispatch requests to subscribe to comments.
* Use the blog token to submit subscription to comments
p9dueE-1Dv-p2
No
* Set up a connected Jetpack
* Activate the Subscription module
* Visit your site as an anonymous user
* Leave a comment on a post, enter a valid email and check the "Notify me of follow-up comments by email" box.
* verify the subscription worked. See 25ebc-pb/#plain
* Subscribe to comments now uses the blog token
=> Use blog token to add new comment subscriber

modules/sharedaddy/sharing-sources.php, tests/php/3rd-party/test_class.jetpack-amp-support.php
Fix at Jetpack side: ampproject/amphtml#29563 and Automattic/newspack-theme#1014
When a button doesn't have an accessible name, screen readers announce it as "button", making it unusable for users who rely on screen readers.
I think this should be fixed when writing amp-social-share tag on HTML template.
* Add `aria-label` and `title` using a translated string to `$attrs` on `get_amp_display` method 
No
When you hover over a share button, it will display a tooltip
* Improve accessibility (a11y) of amp-social-share buttons
=> Improve a11y of amp-social-share

_inc/client/security/antispam.jsx
Fixes #8226.
* Add a check in the Antispam component to look for indications of a globally-set WPCOM_API_KEY for Akismet.
* If a globally-set API key is detected, inform the user and disable input.
See #8226.
No.
How to globally define an Akismet API key:
* In the **Jetpack > Akismet Anti-spam** menu, if an API key is already set, disconnect or remove it.
* In your site's `wp-config.php` file, add the following line: `define( 'WPCOM_API_KEY', 'your api key' );` where `your api key` is your desired API key.
To test changes in this PR:
* Globally define a **valid** Akismet API key for your site (see instructions above).
* Verify that in **Jetpack > Settings > Security**, the **Anti-spam** card shows *"Your site is protected from spam."* and the text input is disabled, like in the below …
=> Settings: Recognize valid Akismet keys from wp-config and restrict input

modules/infinite-scroll/infinity.js
Conditional check for wrapper before giving focus to new page.
Fixes #16807
* Bug fix, add small conditional
N/A
N/A
* Make sure Jetpack 8.8 or Jetpack 8.8.1 is installed and activated
* Activate a Theme with Support for Infinite Scroll with the following settings: `'type' => 'click', 'wrapper' => false,`
* Go to the Dashboard > Jetpack > Settings > Writing
* Scroll down to 'Theme enhancements' > 'Infinite Scroll'
* Check 'Load more posts in page with a button' and click 'Save settings'
* Switch to the front end of the site and go to the blog page
* Scroll down to and click the 'Load more' button ( Make sure the site has enough posts for the Infinite Scroll button to be visible )
* Check for JS errors and that the load more button continues to work
* N/A
=> Infinite Scroll: Fix bug condition where no wrapper is present

class.jetpack-gutenberg.php, extensions/blocks/social-previews/editor.js
Certain blocks and extensions in Jetpack are gated by plan. Depending on where the code is being run (ie: in the Plugin or on WordPress.com) the plan being checked against might be either:
- Jetpack plan
- WordPress.com plan
https://github.com/Automattic/jetpack/blob/11f81f14bb3df0b8c561981574106a1c2646206a/class.jetpack-gutenberg.php#L1088-L1096
Currently when registering a Jetpack extension/block using [`jetpack_register_block`](https://github.com/Automattic/jetpack/blob/11f81f14bb3df0b8c561981574106a1c2646206a/class.jetpack-gutenberg.php#L24) you can use the `plan_check` arg in the settings array to choose to check if the feature should be enabled on the current plan. If it isn't the the block/extension won't be registered.
However, `jetpack_register_block` currently requires the …
=> Extensions: make `render_callback` optional when checking block registration against plan

extensions/shared/external-media/sources/with-media.js
The `speak` message is currently announced on insertion of the image. I have removed this `speak` message and did not replace it, as focus is moved to the top of the modal on insert, and it's best to not make an announcement while moving focus as one of the messages will get lost anyways. It's best to let the focus move handle the announcement.
Fixes https://github.com/Automattic/jetpack/issues/16695
* Removes `speak` announcement when image is being inserted into the editor.
* Go to the block editor
* Insert an image block
* Turn on a screen reader
* Click Select Media > Pexels Free Photos 
* Select a photo
* Insert the photo
* There should be no "Inserting: [alt text]" announcement
I don't think a changelog entry is necessary here, as it's a minor change.
=> External Media: Fix `speak` announcements

extensions/shared/external-media/index.js
Fixes #16668
* Let's change the priority at which we hook our External Media implementation into the existing media library. That will avoid conflicts with other plugins that do the same.
* N/A
* No
* Add an image block
* Select Google Photos or Pexels in the options to pick an existing image
* It should still work
* Block Editor: ensure our External Media option is compatible with other plugins that also make changes to the Media Library options in the block editor.
=> Increase the `editor.MediaUpload` hook priority

modules/theme-tools/social-menu.php
Fixes https://wordpress.org/support/topic/php-7-4-errors/
* Ensure that the value used is an array with the applicable offset before use.
n/a
n/a
* n/a
*
* Theme Tools: Resolve a PHP notice in PHP 7.4.
=> Theme Tools: Resolve PHP 7.4 array offset notice.

_inc/connect-button.js, class.jetpack-connection-banner.php
In #16643, we updated the design of the connection panel and added a new heading at the bottom of the page.
Let's ensure that heading disappears with the rest of the content when you start the connection process.
* N/A
* N/A
* On a brand new site running this branch, go to Jetpack > Dashboard
* Click on the button to setup Jetpack.
* The images, their descriptions, the ToS text, and the new heading at the bottom of the page ("More than 5 million..." should fade out. Only the connection iFrame and the main heading should remain.
* N/A
=> Connect-in-place: hide new heading during connection process

packages/sync/src/modules/class-themes.php
This was ported from D47418-code.
There is currently a mistake in the edit theme jetpack sync functionality that is preventing theme edited events from reaching the Activity Log.
The nonce field is being created like this in the theme editor:
`wp_nonce_field( 'edit-theme_' . $stylesheet . '_' . $relative_file, 'nonce'  );`
* N/A
* N/A
* Apply this patch, edit a theme and check that there is a theme modified event in the Activity Log.
* Activity Log: ensure that theme changes are mentioned in the Activity Log.
=> Sync: Fix nonce action string in theme edit sync

modules/subscriptions/views.php
Changes the call to fetchSubscriberToken to use the blog token instead of primary user token, as it is not needed
p9dueE-1Dv-p2#comment-2838
No
Test it first on the master branch:
* Set up a connected site
* Activate Subscriptions module
* Make sure you have at least one subscriber
* Add the "Blog Subscriptions (Jetpack)" widget to your site
* Visit the site and check the number of subscribers being displayed. "Join XX other subscribers"
Now checkout this branch
* clear the cache: `wp transient delete wpcom_subscribers_total`
* Visit the site again and confirm that you see the same number of subscribers
* Call to fetchSubscriberToken now uses the blog token
=> Use blog token to make the request to fetchSubscriberCount

_inc/lib/class.core-rest-api-endpoints.php, extensions/shared/plugin-management.js
This PR is built on top of #16821. It may be best to wait to merge it, and change the base branch once #16821 and #16713 are merged.
This PR adds tools to install and activate plugins right from the block editor.
* Internal reference: p1HpG7-9NB-p2
* N/A
* This is not easy to tests on its own, but you could run the `apiFetch` calls in your browser console in the editor and see what comes up. It's going to be easier to test with something actually using it. You can switch to #16825 to be able to test those new functions with the Jetpack CRM integration.
* N/A
=> Blocks: add plugin management tools

3rd-party/creative-mail.php
Built on top of #16818, do not merge for now. We can change the base branch once the other PR has been merged.
* When installing the plugin via Jetpack, automatically configure some plugin options.
**Note**
I was originally hoping to use the `activated_plugin` action provided by Core, but it then wouldn't be possible to pass a source that we can use in the option. I consequently ended up creating a new hook (I added the docblock in #16821), that we can also use when activating the plugin via the plugins endpoints introduced in #16713. 
* Internal reference: pbtFPC-H5-p2
* No
* Similar setup as in #16818
* Upon plugin activation, run `wp option get CE4WP_REFERRED_BY`
* You should see the following data being returned:
```
array (
'plugin' => 'jetpack',
'version' => '8.9-alpha',
'time' => …
```
=> Creative Mail: configure some options when activating plugin

modules/theme-tools/social-menu.php
Fixes https://github.com/Automattic/themes/issues/2353 (regression added in #16795 ).
* If no options are set, it should use genericons, not null.
See pNEWy-8RI-p2
n/a
* Apply the dotcom diff and see https://nikaudemo.wordpress.com/
* Menu icons should appear on the right-hand side.
* n/a fixes unreleased regession
=> Theme Tools: Use `genericons` if no option are set.

extensions/shared/external-media/media-browser/index.js, extensions/shared/external-media/media-browser/media-item.js, extensions/shared/external-media/media-button/index.js, extensions/shared/external-media/sources/with-media.js
Adds arrow key navigation on media items in the external media browser modal. This brings it to have parity with the core Media Library image grid navigation.
* Adds a `onKeyDown` prop to `MediaItem`
* Adds a `columns` ref and window resize listener to count and store the number of grid image columns. This is used to know where to send focus to when the up/down arrow keys are pressed.
* Go to a post and add an Image or Gallery block
* **Arrow key presses _should not close the modal_**. Focus different elements (search input, search button, etc) and press the arrow keys. It should never close the modal. Arrow keys should operate normally inside inputs (like the search input).
* **Media Grid image items should be able to navigate with arrow key presses**
* **Resize the browser to less than …
=> External Media: Arrow keys navigation

.gitignore, packages/autoloader/src/AutoloadGenerator.php, packages/autoloader/src/autoload.php, packages/autoloader/src/functions.php
During a plugin update, an error can be caused by opcache holding the old version of the `autoload_packages.php` file when `find_latest_autoloader()` tries to load the newly installed autoloader. To prevent this, don't try to find the latest autoloader version; just continue using the current autoloader.
Also, change the path of the the `autoload_functions.php` file to `jetpack-autoloader/autoloader_functions.php`. This will help prevent errors caused by the previous versions of the autoloader that have already been released. This path matches the path being used in PR #16819, which is in-progress.
See p9dueE-1IA-p2 for more info about the errors and for a discussion about removing the `reset_maps_after_udpate` method. The method has not been removed in this PR, but it can be if we decide …
=> Autoloader: don't reset the autoloader version during plugin update

packages/assets/.gitattributes, packages/connection/.gitattributes, packages/jitm/.gitattributes, packages/partner/.gitattributes, packages/redirect/.gitattributes
Our testing now uses `phpunit.xml.dist` which was not updated in package's `.gitattributes` files.
Fixes issue introduced in #16810
* n/a
n/a
n/a
* Done pre-release. After a new version of a package has this update, should be able to do `composer install --no-dev` on a project with one of these packages and not see `phpunit.xml.dist` in the distributed copy.
* n/a
=> Packages: Update filenames after #16810

_inc/client/state/connection/actions.js, packages/connection/composer.json, packages/connection/src/class-client.php, packages/connection/src/class-manager.php, packages/connection/src/class-rest-connector.php, packages/connection/tests/php/test-rest-endpoints.php, packages/connection/tests/php/test_Manager.php
~Requires `D46648-code` and `D47087-code`  patches to be applied.~ Patches deployed.
- Blog and user tokens get validated via the `jetpack-token-health` WP.com endpoint.
- If the user token is invalid, it gets refreshed.
- If the blog token is invalid, it gets refreshed via the  `jetpack-refresh-blog-token` WP.com endpoint.
`p9dueE-1CV-p2`
Yes.
It adds three new events for the "Restore Connection" process:
- `restore_connection_reconnect` (full reconnect started)
- `restore_connection_refresh_blog_token` (blog token refresh initiated)
- `restore_connection_refresh_user_token` (user token refresh initiated)
Any of these events can only be triggered after Jetpack has already been connected, therefore TOS have been accepted.
Additionally, there's [TOS …
=> Reconnect Process: Partial Reconnect

extensions/blocks/calendly/edit.js, extensions/blocks/calendly/editor.scss
Fixes #15357
* Adds an Edit button to the Calendly block toolbar
* Fixes width of form field in Calendly block's placeholder form
No changes.
* Edit a post adding a Calendly block
* Confirm existing Calendly block functions as expected and toolbar has new Edit button
* Add a new Calendly block and then edit that block's Calendly URL or embed code
* Ensure block updates appropriately
* Calendly Block: Add edit button to toolbar
=> Calendly Block: Add edit button to block toolbar

extensions/shared/blocks/cover/editor.scss
Fixes #16157
* Forces visible text color for component notices within cover blocks
NOTE: This PR would just be to fix the issue in the short term prior to a change being merged into core.
* Edit a post, adding a cover block and selecting a background color for it
* Insert OpenTable block within the cover block
* Select the "wide" style for the OpenTable block, then align that block to the center
* You should see a notice displayed above the OpenTable block within the cover block but the text's color will match the notice background.
* Save post
* The notice text should clearly be visible
* Improved visibility of notice text when displayed within cover block
=> Cover Block: Force notice text color so it is visible

extensions/blocks/slideshow/style.scss
Fixes #16719
* Hide duplicate slideshow control arrows introduced via Swiper dependency update
Note: This just applies the CSS fix suggested in the [linked issue](https://github.com/Automattic/jetpack/issues/16719). Any issues with build artifacts can be addressed in a separate PR. This just aims to get this fixed visually as quickly as possible for users.
No changes.
* Apply this PR branch
* Edit a post adding a Slideshow block with images
* There should be no duplicate arrows within the slideshow next/prev buttons
* Save post and confirm the frontend displays correctly as well
* Slideshow Block: Fix duplicate control arrows.
=> Slideshow Block: Hide Swiper next and previous button arrows

3rd-party/3rd-party.php, 3rd-party/creative-mail.php, bin/phpcs-requirelist.js, packages/jitm/src/class-post-connection-jitm.php
This should facilitate the installation and the configuration of the plugin.
The installation tools in there are to be used in tandem with a JITM, introduced in D48025-code.
* Internal references:
* pbtFPC-GX-p2
* pbtFPC-HO-p2
* No 
* Apply D48025-code on your WordPress.com sandbox.
* Start on a Jetpack site with this branch checked out.
* The Jetpack site should point to your WordPress.com sandbox, with the `JETPACK__SANDBOX_DOMAIN` constant.
* I would recommend disabling the cache for JITM messages, with `add_filter( 'jetpack_just_in_time_msg_cache', '__return_false' );`
* The site must be connected to WordPress.com, and the Contact Form module must be active.
* The Creative Mail plugin should not be active on your site.
* You can test this diff with both the plugin installed but not …
=> Compat: add new Creative Mail compat file

modules/widgets/class-jetpack-instagram-widget.php
I noticed this when trying to get the widget working on WPCOM (D46749-code).
* The CSS needs to be enqueued so that we get a preview of the widget in the customizer.
No
* Open the customizer
* Add an Instagram widget
* Check that you see a preview of the widget in the customizer like this:
* no changelog
=> Instagram Widget: Enqueue CSS in Customizer

extensions/blocks/social-previews/upgrade.js, extensions/shared/components/upgrade-nudge/constants.js, extensions/shared/plan-utils.js, extensions/shared/use-upgrade-flow/README.md, extensions/shared/use-upgrade-flow/index.js
Takes inspiration from `UpgradeNudge` and `BlockNudge` to save the post and redirect to the checkout flow of the Business plan.
Reuses the following event:`jetpack_editor_block_upgrade_click`. We'll do a follow up PR for view event tracking.
Fixes #16781.
* Adds tracking for upgrade modal view and Upgrade link click
* Autosaves current post and redirects to plan checkout flow for a business plan. 
Similar to `UpgradeNudge` tracking.
* follow setup steps from #16615.
* ~When testing on dotcom, make sure D48017-code is applied.~ No longer required as now in Production.
* ~this PR currently shows both paid and unpaid versions of the sidebar. Click the one with~ If tested on local Jetpack Plugin, you will need to comment out [`social-previews` …
=> Social Previews: Add upgrade path

modules/sharedaddy/sharing.css
Fixes #16619
* Update sharing CSS to move the bottom margin on the sharing buttons; `ul` to the outer wrapper, `.sd-sharing`. This prevents the "Customize buttons" link from running up against the content beneath it.
**Before**
**After**
Logged-in admin on WP.com site
Not logged in on WP.com
Local Jetpack, logged in
* Spin up a new site with this branch
* Go to Jetpack -> Settings -> Sharing to activate the sharing buttons on posts/pages
* View a single post on the front end of your site; note spacing around "Customize buttons" link
* Check different themes to make sure front-end changes have not caused visual regressions or bugs
* Update spacing around sharing buttons
=> Sharing: Add bottom margin to sharing buttons section

modules/stats.php
This PR changes the token used by the Stats module to make requests to `stats.wordpress.com/csv.php`.
Soon
No
First of all, you will need a connected site that has some Stats.
Let's first test it before checking out this branch, so we can compare the results
* In the master branch, go to the admin Dashboard (WP Dashboard, not Jetpack Dashboard)
* Look for the Stats widget and take note of the information under "Top posts" and "Top searches" (these two pieces of info are the ones affected by this change)
* Check out this branch
* Apply D47584-code
* Sandbox `stats.wordpress.com`
* Clear the cache with `wp option delete stats_cache` (you will need to do this every time you run a test to make sure a new request is performed)
* Go back to the Dashboard and confirm you see the same values
* …
=> Requests to Stats CSV use the blog token

extensions/blocks/donations/amount.js, extensions/blocks/donations/donations.php, extensions/blocks/donations/view.js, extensions/index.json, extensions/shared/currencies.js
- Add `thickbox` as dependency when loading the view assets (Thickbox is required for the payments dialog).
- Add `donations` to the `no-post-editor` list of blocks (TBH, not sure what `no-post-editor` does, but I see `recurring-payments` is there, so we likely need the donations block there too given they both share the same architecture.
- Move the `parseAmount` function to a file that does not import anything from `@wordpress/block-editor`. That way, the `wp-block-editor` dep is not added to the `view.asset.php` file, which was causing the issue noted in p58i-9k2-p2#comment-47338.
p58i-9k2-p2
No
- Sandbox the API, `s0.wp.com` and `austineatworld.wordpress.com`.
- Add the code below to your `0-sandbox.php` file:
```
define( 'FORCE_CONCAT', TRUE );
add_filter( …
```
=> Donations: Fix dependencies

_inc/client/at-a-glance/backups.jsx
Fixes the missing Backups card in the main dashboard when waiting for the response of the /rewind endpoint, as well as when that endpoint returns an error. 
The way this card works is quite confusing, since it needs to handle both VaultPress and Rewind statuses. 
Currently, this card relies on the /rewind endpoint to return one of a specific key before displaying any information. Unfortunately, there is no case for when the API errors. In this case, the value of `this.props.rewindStatus` is empty, therefore not falling back to the `getVPContent()` content that is used to show the loading/upgrade prompts. 
IMO this entire component could use a re-write. But for an immediate fix, this should at least solve the problem of the missing card in any case. 
Before: 
After: 
N/A
No
- Connect …
=> AAG: Display Backups card when Rewind API is loading or has error

modules/stats.php
This PR drops the use of the `JETPACK_MASTER_USER` token and replaces it with the use of Blog token.
~PLEASE do not merge it before D47631-code is verified and deployed.~ deployed
p9dueE-1Dv-p2
No
* Start with a Jetpack connected site with some stats
* ~Apply D47631-code~
* ~Sandbox `dashboard.wordpress.com`~
* Visit WordPress admin dashboard and confirm the Stats widget loads the graph properly (admin home, not the Jetpack dashboard)
* Visit Jetpack > Site Stats and confirm the page and the graphs load properly
*
=> Make Stats module use the blog token

extensions/blocks/social-previews/modal.js
* Similar to [its backend counterpart](https://github.com/Automattic/jetpack/blob/f9b5cdb92ffc1b8753db7f99b1697090bd886aa4/functions.opengraph.php#L137), the preview text can fall back to the post content if the perex is not present. In this case, we should respect the "more" block (represented as HTML comment) and only show content before it.
* I have also added support for the advanced seo that you can fill on wpcom in JP sidebar as well as the static text fallback
no
* follow setup steps from #16615
* go to the block editor
* check the social preview right away and you should see a static fallback there "Visit the post for more."
* now, don't write any excerpt but write some content into the post.
* use the "more" block and write some more text after it. feel free to edit the text of …
=> Social Previews: improve preview description handling

extensions/blocks/story/edit.js, extensions/blocks/story/icon.js, extensions/blocks/story/index.js, extensions/blocks/story/player/components/background.js, extensions/blocks/story/player/components/calypso-spinner.js, extensions/blocks/story/player/components/controls.js, extensions/blocks/story/player/components/index.js, extensions/blocks/story/player/components/media.js, extensions/blocks/story/player/components/overlay.js, extensions/blocks/story/player/index.js, extensions/blocks/story/player/lib/wait-media-ready.js, extensions/blocks/story/player/player.js, extensions/blocks/story/player/slide.js, extensions/blocks/story/player/style.scss, extensions/blocks/story/story.php, extensions/blocks/story/view.js
Addresses part of https://github.com/Automattic/jetpack/issues/16591:
- Show a progress indicator when uploading media from the block editor, prevent story playback while its uploading
- Improve loading of media files
- Better fit media on the player, use heuristics to crop some part of the image to make it fit a user screen (for instance allow 10% cropping max, after which margins can be displayed)
- Refine UX
- Scale down story embeds (make it 50% smaller?)
With this change we stop rendering all the slides dynamically from the server. Instead we only render the first one and serialize the media into the markup so the client can retrieve it and load slides dynamically. Slides are rendered as the story is played, with a preload of the next slide.
It also applies the latest changes in …
=> Improve Story block media loading

modules/stats.php
This PR changes the token used by the stats module to make a request to the `updateBlog` XMLRPC endpoint. It drops the use of the "Master user" token and uses the blog token instead.
p9dueE-1Dv-p2#comment-2838
No
* Open `modules/stats.php` file
* At line 25 change the `STATS_VERSION`value to a higher number, for example:
`define( 'STATS_VERSION', '10' );`
* This will force a call to the `updateBlog` endpoint
* Browse the admin panel. Just viewing a page is enough
* Check the `stats_options` option on the cache site and confirm the value for the `version` option key was updated :) 
* Now revert the change.
* Undo the change to the constant value in the `stats.php` file.
* On your local environment:
```
wp shell
$options = get_option( 'stats_options' );
unset($options['version']); …
```
=> Use blog token to request the jetpack.updateBlog XMLRPC endpoint

packages/connection/tests/php/test-rest-endpoints.php
Rebuilding the connection package unit test `Test_REST_Endpoints::test_remote_authorize()`.
The existing test only verifies the existence of the endpoint, and turned out to be unreliable.
The test has been rewritten to actually test the authorization process. Some existing tests were also refactored.
No.
Run unit tests for the `jetpack-connection` package.
Make sure that all tests pass.
n/a
=> Connection REST API: Unit test for the `remote_authorize` request.

packages/compat/legacy/class-jetpack-sync-actions.php
Fixes the declaration of a class method to match parent class and avoid PHP Warnings and Fatals
* Verify all tests are passing, including PHP Nightly
=> Compat Package: Fix method declaration compatibility

class.jetpack.php
This endpoint does not require a user token and we should use the blog token instead.
Help needed: how to test it?
* changes the token used by Jetpack::get_cloud_site_options to the blog token
p9dueE-1Dv-p2#comment-2838
No
TBD - need help
* Jetpack::get_cloud_site_options to the blog token uses the blog token to make the request to fetchSiteOptions
=> Use the blog token to make the request for fetchSiteOptions

packages/connection/docs/error-handling.md, packages/connection/src/class-error-handler.php
XML-RPC errors displayed outside the context of the Jetpack Dashboard are still a bit confusing:
* We need to add the context that this is related to Jetpack and a CTA to fix it
* We can't assure the error is still present in the moment the error. message is being displayed.
The purpose of displaying the error in the WP Dashboard is for them to be displayed by plugins using the connection package without the Jetpack plugin. However, there's still more work to do to better display these errors, so we are disabling it by default while leaving room for plugins to activate them if they want.
* Disable XML-RPC errors in the WordPress admin
p1597856985219100-slack-CBG1CP4EN
No
* Start with a healthy jetpack site and the Debug Helper plugin
* Go to Broken token and break your connection
* Go to …
=> Disable xmlrpc errors out of JP dashboard

extensions/blocks/donations/icon.js, extensions/blocks/donations/index.js
Fixes https://github.com/Automattic/wp-calypso/issues/44796
* This PR updates the icon displayed when selecting a donations block in the block editor, setting it to be a Gridicons outline heart.
N/A
No.
* Create a JN site running this branch.
* Go to /wp-admin/options-general.php?page=companion_settings.
* Activate JETPACK_BETA_BLOCKS.
* Set JETPACK__SANDBOX_DOMAIN with your sandbox address (make sure you enter the short URL e.g. mysandbox.wordpress.com to avoid issues with the SSL certificate).
* Sandbox the API, the store and subscribe.wordpress.com (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Go to Posts > New and add a donation block.
* Verify that the block icon is a heart outline. …
=> Update donations block icon to heart gridicon

_inc/client/components/auth-iframe/index.jsx
Fixes #16906
* Fixes an issue where the connection iFrame didn't correctly load for secondary users.
N/A
No
1. On Jetpack site set `add_filter( 'jetpack_use_iframe_authorization_flow', '__return_true' );`
2. Connect Jetpack site with user A
3. Login to site as user B
4. Go to Jetpack dashboard
5. Click "Link to WordPress.com" button
6. Observe that iFrame loads properly
* Fixes an issue where the connection screen would not load for secondary users.
=> Connection: Fix broken connection for secondary users

packages/connection/src/class-error-handler.php
In https://github.com/Automattic/jetpack/pull/16750 we introduced a check to find out sites that had features relying on a deleted user token. This allowed us to do some cleaning of old unused tokens in WPCOM.
For 8.9 we got rid of all the usage of the `JETPACK_MASTER_USER` constant, so this is not a problem anymore. This check is no longer necessary.
* Removes check for deleted but active master user tokens
p9dueE-1J8-p2
No
If you really want to test it
* Start with a connected jetpack site
* Create a secondary admin user
* Log in as the secondary admin user
* Move your master user away. Directly in your database: `UPDATE wp_users SET ID = 99 WHERE ID = 1` (Replace Ids as needed)
* Go to Jetpack Debug > XML-RPC Errors
* Click the link and visit the Jetpack debugger. Wait until it …
=> remove no longer needed check

packages/connection/src/class-error-handler.php, packages/debug-helper/modules/inc/class-broken-token-xmlrpc.php
Adds two new features to the XML-RPC errors page in the Debug helper plugin
* create fake errors - help creating errors in the database without the need to actually breaking the site
* Clear all errors (both verified and unverified)
It also does a small fix in the error reporting, where all blog token errors (user id = 0) were being logged as "invalid_user" intead of user 0 (zero)
* Go to Debug helper -> XMLRPC errors
* Play with the Create Fake Errors form
*
=> add new features to debug helper

modules/shortcodes/flickr.php
* In some cases Flickr may not return the expected response, thus causing the following error:
```
Fatal error .../shortcodes/flickr.php:194 - Uncaught Error: Cannot use object of type WP_Error as array in .../shortcodes/flickr.php:194
```
This avoids that.
* N/A
* N/A
* Try using a shortcode like `[flickr video=49931239842 autoplay="yes" controls="no"]` 
* It should still work.
* Shortcodes: avoid Fatal errors when receiving unexpected response from Flickr.
=> Flickr: avoid Fatal errors when receiving unexpected response

modules/scan/class-admin-sidebar-link.php
Fixes #16905.
* Ensure the Jetpack sidebar menu link still points to the dashboard for non-admin users, by way of guaranteeing an integer return value from `get_link_offset()`.
N/A
No.
* See #16905 for instructions to reproduce the issue. Verify the issue still occurs.
* Apply this PR's version of the Jetpack plugin on your site (e.g, by using the Jetpack Beta plugin).
* Try again to reproduce the issue. Verify the issue no longer occurs.
* Regression testing: verify that sidebar links still work for admin users, and for sites without a Jetpack plan or product.
* Fix the Jetpack sidebar menu link for non-administrators on sites with Jetpack Backup and/or Scan.
=> Sidebar: Point Jetpack sidebar link to the dashboard instead of WordPress.com

modules/protect/blocked-login-page.php
* In 3010b47431d784ba4771188ca1da2637bb922d97 we started escaping the "Get Help" message, thus escaping the help icon HTML markup as well.
* I took the opportunity to add a textdomain that was missing from another string.
**Before**
**After**
* N/A
* N/A
* Add the following constant to your site: `define( 'JETPACK_ALWAYS_PROTECT_LOGIN', true );`
* Connect your site to WordPress.com; Protect should be automatically enabled.
* Log out
* Try to log back in.
* See the new blocked login page.
* Protect: avoid displaying HTML markup on blocked login screen.
=> Protect: avoid HTML markup displayed on Locked login page

_inc/client/security/index.jsx
Fixes https://github.com/Automattic/dotcom-manage/issues/128
* Only show the auto-updates module if the site is NOT an Atomic site
Non-Atomic Sites | Atomic Sites
--- | ---
Atomic discussion: p9F6qB-5uo-p2
No changes.
1. Go to /wp-admin/admin.php?page=jetpack#/settings on an Atomic site
2. Go to /wp-admin/admin.php?page=jetpack#/settings on a self-hosted site
* Hide the auto-updates module for Atomic sites
=> Settings: Hide auto-update plugins module for Atomic sites

extensions/blocks/donations/tab.js
Fixes https://github.com/Automattic/jetpack/issues/16887
Prevent users from setting a link to the donate button, so it doesn't collide with the link we set for showing the payments dialog.
Before | After
--- | --- 
p58i-9k2-p2
N/A
* [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=update/donations-prevent-set-link). 
* Activate `JETPACK_BETA_BLOCKS`. 
* Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address (make sure you enter the short URL e.g. mysandbox.wordpress.com to avoid issues with the SSL certificate).
* Sandbox the API, the store and `subscribe.wordpress.com` (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Set up Jetpack and purchase a …
=> Donations: Avoid setting a link in the donate button

extensions/blocks/donations/view.js
Fixes https://github.com/Automattic/jetpack/issues/16908
Ensures the frontend logic of the Donations block runs on all blocks.
p58i-9k2-p2
No.
* [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=fix/donations-multiple-blocks). 
* Activate `JETPACK_BETA_BLOCKS`. 
* Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address (make sure you enter the short URL e.g. mysandbox.wordpress.com to avoid issues with the SSL certificate).
* Sandbox the API, the store and `subscribe.wordpress.com` (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Go to Posts > New and insert a new Donations block.
* Set …
=> Donations: Handle multiple blocks in frontend

modules/widgets/eu-cookie-law/style.css
Fixes Automattic/wp-calypso#44126
* Repositions the edit button that is added to the widget within the Customizer so it is more obvious the widget is editable and the button isn't partially hidden behind the Customizer sidebar.
No changes.
1. Ensure you have a theme selected that can add widgets via the Customizer
2. If you haven't already, turn on the extra widgets in Jetpack settings
3. Navigate to the Customizer and add the "Cookies & Consent" widget
4. Notice how the injected edit button for the widget is partially obscured
5. Apply this PR branch
6. Reload the Customizer and ensure the injected edit button now overlays the top left corner of the widget
* Customizer: Make Cookies & Consent widget edit button more obvious.
=> Customizer: Tweak cookie widget edit button position

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
* Check for the `jetpack_protect_save_whitelist` function before calling it in `Jetpack_Core_API_Module_Toggle_Endpoint::update_data`. If it doesn't exist, require the file that contains it.
The endpoint is currently returning a 500 error and generating a fatal. For context, see p1597673240279600-slack-CDLH4C1UZ
* N/A
* No
1. Install, activate, and connect Jetpack on your test site.
2. Using the developer console, send a post request to `/jetpack-blogs/$blog_id/rest-api` with:
path: `/jetpack/v4/settings`
body: 
`{ "jetpack_protect_global_whitelist":"", "protect":false}`
3. The request should return a 500 error. This PHP error should be in your debug.log:
`PHP Fatal error:  Uncaught Error: Call to undefined function jetpack_protect_save_whitelist() in …
=> Protect: check for jetpack_protect_save_whitelist function before using it

extensions/blocks/contact-form/editor.scss, extensions/blocks/donations/common.scss, extensions/blocks/donations/view.scss, extensions/blocks/gif/editor.scss, extensions/blocks/gif/style.scss, extensions/blocks/map/add-point/style.scss, extensions/blocks/map/style.scss, extensions/blocks/markdown/editor.scss, extensions/blocks/podcast-player/style.scss, extensions/blocks/publicize/editor.scss, extensions/blocks/rating-star/style.scss, extensions/blocks/recurring-payments/editor.scss, extensions/blocks/seo/editor.scss, extensions/blocks/slideshow/editor.scss, extensions/blocks/social-previews/modal.scss, extensions/blocks/story/editor.scss, extensions/blocks/tiled-gallery/editor.scss, extensions/blocks/wordads/editor.scss, extensions/shared/components/style.scss, extensions/shared/external-media/editor.scss, package.json, yarn.lock
* This PR is a split from #15157. Here, I updated the `@wordpress/base-styles` package and updated all blocks where we leveraged core colors according to recent changes in Core:
- WordPress/gutenberg#23454
- WordPress/gutenberg#23648
- WordPress/gutenberg#23048
This updates quite a few blocks to use those new colors. Here are some examples:
* N/A
* N/A
* Add and play with blocks, and see if you notice any weirdness.
* Blocks: update to use latest colors defined by WordPress.
=> Blocks: update base-styles dependency

extensions/blocks/social-previews/modal.scss
This PR aims to fix an issue where we were cutting off some of the content in social previews in some device widths. 
Fixes p7DVsv-97x-p2#comment-30410
Before | After
-------|------
-
-
* apply `arc patch D48491` in your **clean** sandbox OR `yarn build-extensions` and sync to your sandbox 
* sandbox a **business** site
* navigate to the edit page of a post / page
* click the Jetpack Icon in Bar
* click `Preview` in Social Previews section of the sidebar
* try resizing the window
* Fixes social previews overflowing in some device widths
=> Social Previews: fix previews overflowing (Responsive Updates)

extensions/blocks/opentable/attributes.js, extensions/blocks/opentable/deprecated/v2/index.js, extensions/blocks/opentable/edit.js, extensions/blocks/opentable/editor.scss, extensions/blocks/opentable/index.js, extensions/blocks/opentable/opentable.php, extensions/blocks/opentable/restaurant-picker.js, extensions/blocks/opentable/use-previous.js, extensions/blocks/opentable/utils.js, extensions/blocks/opentable/view.scss
Fixes #15064
* Update implementation of block styles in the OpenTable block to be consistent with other blocks
* Improve form field and button alignments in OpenTable placeholder embed form
* Fix minor bugs causing console errors (isLarge and missing keys)
* Fix filtering of duplicate restaurants from suggestions
No changes.
1. Create new post
2. Add OpenTable blocks for each block style (standard, tall, wide & button)
3. Add new OpenTable block and add two restaurant IDs via placeholder form, then try and add the second again.
(note that it is not filtered from suggestions)
4. Save post and view on frontend for reference
5. Checkout this PR branch
6. Refresh frontend page and confirm each block has new styles e.g. `is-style-tall`
7. Open post in the editor and confirm blocks are still …
=> OpenTable: Implement block styles natively

packages/connection/composer.json, packages/connection/src/class-manager.php, packages/heartbeat/src/class-heartbeat.php, tests/php/general/test_class.jetpack.php
This PR adds information of active plugins using connection to the heartbeat, except jetpack itself.
If plugins are active alongside Jetpack, their slugs will be added to the `combined-connection` group. 
If Jetpack is not present, they will be added to the `standalone-connection` group.
~This PR depends on the new Heartbeat package -> #16285~
* 1146297891914257-as-1146297891914257
Yes, it tracks if there are any other active plugin using the Jetpack connection
* Connect jetpack
* Install the Client Example plugin
* run `wp jetpack-heartbeat`
* Check that there is an entry of `combined-connection -> client-example`
Note, you might need to copy the contents of the connection package inside the `vendor/automattic` folder of the client example plugin if you want to test the `standalone` …
=> Connection: use heartbeat to send connected plugins info

extensions/blocks/social-previews/modal.js, extensions/blocks/social-previews/utils.js
We've had reports of image size being too small and I have confirmed that when running on wpcom. The image size provided was 150px big, which is not enough for bigger previews that might be generated. 
* Switch the logic to look for the `large` named image size and use the full one as a fallback. 
no
* same setup as #16615
* set a featured image and try getting a preview. they should look good, not blurry
*
=> Social Previews: Simplify featured image media size logic

class.jetpack.php, packages/connection/src/class-rest-authentication.php, packages/connection/tests/php/test_Rest_Authentication.php, tests/php/_inc/lib/test_class.rest-api-authentication.php, tests/php/modules/post-by-email/test-class.post-by-email-api.php, tests/php/sync/test_class.jetpack-sync-callables.php
Fixes #16747
* Move the rest authentication methods to the connection package so that they're
available to consuming plugins.
* The "wp_rest_authenticate' method hooks to the `determine_current_user` filter which is fired in `wp_get_current_user`. It looks like the expectation is that hooks will be set as the plugins are loaded that plugins can call `wp_get_current_user` during the `plugins_loaded` action, at any priority. Therefore, the consuming plugin needs to set up the filter hooks when it loads:
```
use Automattic\Jetpack\Connection\Rest_Authentication as Connection_Rest_Authentication;
// Set up the Jetpack REST authentication hooks.
Connection_Rest_Authentication::init();
```
* n/a
* no
* Make authenticated requests to the Jetpack REST API, for example by loading Calypso. The …
=> Connection: move the rest authentication methods to the connection package

_inc/lib/core-api/wpcom-endpoints/memberships.php, extensions/blocks/donations/fetch-status.js
Ensure users are redirected back to the WordPress.com block editor if they connect to Stripe from a Donations block inserted in the WordPress.com block editor.
p58i-9k2-p2
No.
* [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=fix/stripe-conection-redirect). 
* Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address.
* Sandbox the API and the store (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Apply D48460-code to your sandbox.
* Go to `wordpress.com/block-editor/post` and select the test site you created above.
* Insert a Donations block.
* The Stripe nudge should show up.
* Click on …
=> Donations block: Redirect users back to Calypso after connecting to Stripe

modules/contact-form/grunion-contact-form.php
Fixes #16513
* If the contact form submission matches the user's disallowed list, put the feedback post in the Trash section.
* n/a
* no
1. Install, activate, and connect Jetpack.
2. Create a post with a contact form.
3. Navigate to the contact form and submit it.
4. Navigate to wp-admin -> Feedback and confirm that the feedback post for the form submission is in the `All` section.
5. Navigate to the contact form and submit something that will be caught as spam. For example, use `akismet-guaranteed-spam@example.com` for the email address.
6.  Navigate to wp-admin -> Feedback and confirm that the feedback post for the form submission is in the `Spam` section.
7. Navigate to wp-admin -> Settings -> Discussion and add something to the Comment Blocklist.
8. Navigate to the contact form and …
=> Contact Form: put feedback that matches the disallowed list in trash

_inc/client/setup-wizard/feature-toggle/map-feature-to-props.js
Currently the Upgrade Links in the Setup Wizard are hard-coded. This patch updates these variables to use the Jetpack Redirect Engine instead to allow for proper redirect handling and query args inclusion. The handlers have already been added in the Redirect Manager (all prefixed with `jetpack-setup-wizard-`).
pbtFPC-GX-p2
No
1. On your Jetpack site add the following to then end of the wp-config.php file in order to make the Setup Wizard show:
```
```
2. On your Jetpack site visit /wp-admin/admin.php?page=jetpack#/setup/features
3. Test that all Upgrade Links use the Jetpack Redirects engine with a pattern of …
=> Changing Setup Wizard upgradeLinks to use Redirect slugs instead of hardcoding

_inc/client/rest-api/index.js, _inc/client/setup-wizard/feature-toggle/index.jsx, _inc/client/setup-wizard/feature-toggle/map-feature-to-props.js, _inc/client/setup-wizard/feature-toggle/style.scss, _inc/client/setup-wizard/index.jsx, _inc/client/state/setup-wizard/feature-recommendations.js
This PR adds a recommendation to the Setup Wizard for Creative Mail.
When Creative Mail is not installed:
pbtFPC-Hb-p2
No
1. On your Jetpack site add the following to then end of the wp-config.php file in order to make the Setup Wizard show:
```
```
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/features` and scroll to the Marketing section.
3. Verify that the Creative Mail recommendation shows with a disabled toggle and an install button.
4. Click "Install Now" and verify that the Creative Mail plugin gets installed and activated.
5. Click "Configure" and verify that you are taken to the Creative Mail setup flow.
6. Click the "Learn more" link and verify …
=> Setup Wizard: Add Creative Mail Recommendation

package.json, postcss.config.js, yarn.lock
* It was removed in #16312, but caused issues discussed in #16733.
* N/A
* N/A
* Connect your site to WordPress.com.
* Under Jetpack > Settings, enable Publicize
* See that the Jetpack logo looks good in the plugin sidebar.
* Insert a Mailchimp block, connect it to your Mailchimp account.
* Modify one of the Mailchimp processsing messages and ensure that the colors are applied:
* N/A
=> Blocks: add Calypso Color Schemes back

docker/README.md, docs/development-environment.md
To ease how many places to update, let's only mention things once in the docs and reference the technical requirement location.
* Updating docs.
n/a
n/a
n/a
n/a
=> Docs: Reference one location for minimum version of Yarn needed

class.jetpack.php
This method was replaced with a more complete class in https://github.com/Automattic/jetpack/pull/16674
Its usage was replaced in
* https://github.com/Automattic/jetpack/pull/16692
* https://github.com/Automattic/jetpack/pull/16698
* https://github.com/Automattic/jetpack/pull/16710
Now it's no longer used and should be deprecated, especially because we don't want to use `JETPACK_MASTER_USER` token anymore.
* Deprecates Jetpack::xmlrpc_async_call which is no longer used
n/a
No
* Nothing specific to test, just make sure there are no warnings or notices anywhere
* Any thoughts of external plugins/blocks that could be using it?
* Deprecates Jetpack::xmlrpc_async_call
=> Depreacate xmlrpc async call

tools/get-version.sh, tools/includes/normalize-version.sh, tools/version-update.sh
Fixes https://github.com/Automattic/jetpack-beta/issues/100
We can cherry-pick to that branch to prevent the same type of issue having there. 8.9-beta < 8.9.0-beta, so it should be an improvement to that branch specifically.
Other branches wouldn't be impacted negatively, I don't believe, since they branch off master, which has `alpha` usually.
* See https://github.com/Automattic/jetpack-beta/issues/100 for details.
* This will ensure that beta versions have a X.Y.Z version number to ensure that X.Y-### wouldn't appear greater than X.Y.Z-###.
p1HpG7-a13-p2
No.
* Run `./tools/get-version.sh` from the command line before and after patch to see in action.
* n/a
=> Beta Building: Normalize version number.

packages/tracking/src/class-tracking.php
This is required now because the connection status check has been removed from the ToS package in #16967 . This is a minimal change, but we should also take a look at how we are passing the Connection Manager object to the constructor of this class and remove the optional direct instantiation.
**Update:** The change between `is_active` and `is_user_connected` requires some explanation. I have made this change first because in my testing I have seen that `is_active` can return true when a user is not connected, but a master user token check returns true anyway. So
- the use of `is_active` is not working as expected in case of Tracking - we need to actually check whether the active user is connected;
- the `is_active` method is going to be deprecated soon, and we might just as well start …
=> Tracking: Add the connection check.

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php, json-endpoints/jetpack/class.wpcom-json-api-get-option-endpoint.php
Jetpack Sync Manager (WP.com) utilizes the User Token to send sync actions to a remote Jetpack site. This PR updates the sync related endpoints to allow usage of the blog token that is user agnostic.
* Remove any user related capabilities from sync endpoints
p9dueE-1KW-p2
No
- See D48304-code
* N/A :: non functional change, hardening of Jetpack Connection and Sync.
=> Sync - Allow blog token usage in sync related endpoints

class.jetpack.php
This is required now because the connection status check has been removed from the ToS package in #16967 .
Instead of adding the extra check for the current user's connection when checking if the user has agreed to the ToS, it completely removes the deprecated function where this check occurred.
Part of #16973
* Removes the `jetpack_tos_agreed` deprecated since 7.9.0 method 
N/A
No
N/A
N/A
=> Remove deprecated jetpack_tos_agreed

packages/config/composer.json, packages/config/src/class-config.php
This is required now because the connection status check has been removed from the ToS package in #16967 . 
It adds the extra check for the current user's connection when checking whether to enable the tracking feature.
Update: See #16979 for explanation on why we are now using `is_user_connected` instead of `is_active` 
Part of #16973
Changes proposed in this Pull Request:
* Adds a method call that checks for the current user's connection in the Config conditional to enable the tracking feature.
* Instantiates the Tracking class by passing a Connection/Manager object as argument.
N/A
* This pull request does not add, but may remove some instances of data, because is_user_connected may be more restrictive than is_active that we were using before.
* Make sure that the tracking feature is …
=> Config: Add connection status check

packages/config/composer.json
Reverts adding composer dependencies to the Config package.
The change was part of [this PR](https://github.com/Automattic/jetpack/pull/16987).
Seems we shouldn't declare any composer dependencies in the Config package because consumer plugins use Config to configure whichever packages they want. 
Config checks that the package classes are available by calling ensure_class().
N/A
No
N/A
N/A
=> Config: Remove composer dependencies

_inc/client/security/backups-scan.jsx, _inc/client/security/jetpack-backup.jsx
This is a follow-up from #16751.
Fixes `4257-gh-jpop-issues`.
Support issues are still cropping up due to confusion over copy on the Settings page for Jetpack Backup and Scan. This PR seeks to make things clearer by saying explicitly that these services are _connected_, and not that any backups or scans have taken place.
* Alter copy in Settings to explicitly say that Jetpack Backup/Scan or VaultPress are connected, to avoid confusing implications that any backups or scans may have taken place.
See `4257-gh-jpop-issues` for more information.
No.
Follow the same instructions as in #16751 (copied here for easy access):
* Test with sites that meet the following criteria:
* Backup only with VaultPress
* Backup only with Rewind
* Scan and Backup with VaultPress
* Scan and Backup with Rewind
* …
=> Admin Page: Change settings copy for VaultPress/Rewind to only say they're connected

extensions/extended-blocks/paid-blocks/editor.scss, extensions/extended-blocks/paid-blocks/upgrade-plan-banner.jsx
This PR improves the banner alignment defined indirectly when the block changes the alignment. The banner component is not part of the block component rather a sibling of it. 
Fixes #16912
* Improve Upgrade banner alignment.
* Get sandboxed
* Apply **D48425-code**
* Start to edit a post
* Test with a premium block that allows changing its alignment, for instance, `opentable`
* Change all alignments. Confirm that the banner is shown as expected:
_Left alignment._
* Improve Upgrade banner alignment.
=> Upgrade Banner: Improve alignment.

docker/README.md, docs/development-environment.md, modules/widgets/class-jetpack-instagram-widget.php, tests/package-runner.sh
Before installing a package's deps for testing, clean out the vendor and the non-VCS'd composer.lock.
*
n/a
n/a
* `yarn docker:phpunit:package connection` on master, make manual changes to composer.json
* Run again, see no change with master.
* Switch to this version and run. See that vendor and composre.lock are fixed.
* n/a
=> Docker: Clean out vendor and composer.lock before installing package deps

packages/config/README.md, packages/config/src/class-config.php
Fixes #16993
* The Config package is unusual because it uses multiple package classes but does not require the composer packages. Add info about this to the readme and the Config class.
* n/a
* no
* Read the documentation changes and make suggestions if anything is unclear.
* n/a
=> Config: add info about the package dependencies to the package docs

extensions/blocks/donations/view.js
The logic that runs in the frontend view of a Donations block was assuming that the block will always show a tabbed interface, but this is not true when the monthly and annual donations options are disabled.
That was causing the block to get stuck in a loading state. This PR modifies the frontend view logic so it can handle correctly the lack of tabs.
Before | After
--- | ---
p58i-9k2-p2#comment-47426.
No.
* [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=fix/donations-frontend-one-time-only). 
* Go to WP Admin > Settings > Jetpack Constants.
* Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address.
* Sandbox the API and the store (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Set up Jetpack and purchase any …
=> Donations block: Handle lack of tabs

packages/sync/src/class-defaults.php, packages/sync/src/class-functions.php, packages/sync/src/modules/class-callables.php, packages/sync/src/modules/class-themes.php, tests/php/sync/test_class.jetpack-sync-callables.php, tests/php/sync/test_class.jetpack-sync-themes.php
Currently we are experiencing problems syncing theme features. 
The main problem is when theme switch occurs we don't actually have the theme features on the global variable yet. 
So they can't be accessed and synced in order to fix this, this PR provides a way to unlock callables and lets them be synced on the next tick. (Page load) 
The solution remove the locking transient so that on the next tick (page load we are able to send the data to .com as expected.) 
related D48095-code
* This PR provides a way to reset the callabled transient so that the more accurate data can be send on the next request.
No it just tried to sync more accurate data. 
Apply this branch. 
Build it. 
Notice that when you switch theme you are seeing the correct data on .com side of things. 
The data should be …
=> Sync: Improve theme support syncing

_inc/client/state/setup-wizard/reducer.js
Per request from @jessefriedman this PR switches the order of the performance and marketing categories in Jetpack.
N/A
No
1. On your Jetpack site add the following to then end of the wp-config.php file in order to make the Setup Wizard show:
```
```
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/features`.
3. Verify that the order of the sections is security, marketing, performance, and design.
* None needed
=> Setup Wizard: Switch order of performance and marketing categories

_inc/lib/debugger/class-jetpack-debug-data.php
Fixes #17007
* Removes the e-mail address from the Site Health Debug Data area for the primary/master user and the current user.
* Marks the server variable fields as private.
While this information isn't typically a security concern, it is still personally-identifible information that is usually not requested within the w.org forums. Since fields not marked as private are easily copied to the clipboard via Core's copy button, they are often included
in forum posts where that information isn't actually helpful.
The server variables that are included are from a specific list of ones that matter for either the Jetpack connection or Protect. By marking them as private, Happiness will need to tweak their instructions (will p2 to them post-merge).
n/a
n/a
* Go to Tools->Site Health->Info
* See …
=> Debug Data: Mark sensitive information as private

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php
When a site admin checks installed plugins on a site that's part of a Multisite network,
they should see similar results in the WordPress.com plugins interface and in the Plugins menu (if activated by the super admin) in wp-admin.
Reference: p8oabR-xs-p2#comment-4502
* N/A
* N/A
* See p8oabR-xs-p2#comment-4502
* N/A
=> Plugins: avoid including network-activated plugins in responses

class.jetpack.php
* Updates comment to state the default value is `true` not false. All sites are by default opted in to IDC mitigation.
N/A
No
N/A verify comment text makes sense.
N/A
=> Update optin comment to say default is true

modules/scan/class-admin-bar-notice.php
Since the Site Scan feature launched, I've very frequently seen the AMP menu item in the admin bar show validation errors:
The validation errors are coming from Jetpack:
Specifically they are coming from the Site Scan feature:
The issue can be fixed simply be flagging the scripts as being part of [AMP Dev Mode](https://weston.ruter.net/2019/09/24/integrating-with-amp-dev-mode-in-wordpress/).
This can be done for the `jetpack-scan-show-notice` script simply by making it dependent on the `admin-bar` script, which is itself already part of AMP Dev Mode by default. The only thing left is to ensure that the inline script (added via `wp_localize_script()`) to also be flagged for AMP Dev Mode via the `amp_dev_mode_element_xpaths` filter, which itself may be unnecessary after …
=> Site Scan & AMP: Include toolbar scripts for Site Scan have data-ampdevmode on AMP requests

extensions/blocks/donations/controls.js, extensions/blocks/donations/edit.js, extensions/blocks/recurring-payments/edit.jsx
Fixes https://github.com/Automattic/jetpack/issues/17033
The `site_slug` property returned in the response of the `wpcom/v2/memberships/status` API endpoint has a wrong value when [WordPress is installed in subdirectory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/).
However, as noted by @jeherve in https://github.com/Automattic/jetpack/issues/17033#issue-689341871, we can actually rely on the shared `getSiteFragment` utility that is used across all blocks for building links to Calypso.
pbMlHh-dW-p2
No.
* Spin up a JN sub-directory multisite by including the Beta plugin on this branch and clicking "Launch Multisite on subdirs".
* Network-activate both Jetpack and the Jetpack Beta plugin.
* Create a new sub-directory site in the Network Admin.
* Set up Jetpack …
=> Donations / Payments: Use getSiteFragment for building Calypso links

_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-parser.php
In D48544-code, we added a new method `get_lang_field_suffix()` to `Jetpack_WPES_Search_Query_Parser`. This PR syncs the change back to Jetpack.
Differential Revision: D48544-code
This commit syncs r213167-wpcom.
Jetpack_WPES_Search_Query_Parser normalizes the languages handed to it with the `norm_langs()` method, which is called from the constructor. However, there is no way to retrieve the normalized language back from the parser. This PR adds a new method `get_lang_field_suffix()` to retrieve the first normalized language from the parser.
No.
* Request the WP.com endpoint https://public-api.wordpress.com/wpcom/v2/read/tags/cards?tags=dogs&_locale=fr&_envelope=1. It should return 'lang: fr' in the response. This has been obtained from …
=> Jetpack_WPES_Search_Query_Parser: add method to retrieve lang suffix

extensions/blocks/opentable/editor.scss, extensions/blocks/opentable/opentable.php, extensions/blocks/opentable/view.scss
Fixes #16156
* When the page is being loaded via mobile and the current style is `wide`, the embed URL is switched to the standard theme and an `is-style-mobile` CSS class added. This results in widget more easily being fit on smaller viewports. 
* The choice to switch the widget entirely was made to avoid duplicating markup and scripts for the block. The trade-off being this approach will not help desktop users who resize their browser window smaller than the `wide` style.
No changes.
1. Apply this PR branch
2. Create a post and add an OpenTable block to it
3. Select the wide style for the block and save the post
4. Visit the post on the frontend.
5. Spoof the user agent in your browser to some kind of mobile device and reload the page. 
6. Ensure that the standard theme widget is …
=> OpenTable Block: Add mobile fallback when using wide style

extensions/blocks/pinterest/pinterest.php
See #14395.
This PR adds AMP compatibility for the Pinterest block.
Given this block content:
```html
<div class="wp-block-jetpack-pinterest"><a data-pin-do="embedPin" href="https://www.pinterest.com/pin/140948663310535715/"></a></div>
<div class="wp-block-jetpack-pinterest"><a data-pin-do="embedPin" href="https://www.pinterest.com/pin/834784480905384404/"></a></div>
<div class="wp-block-jetpack-pinterest"><a data-pin-do="embedPin" href="https://www.pinterest.com/pin/1759287342038719/"></a></div>
```
The before/after results are as follows:
Non-AMP | AMP before _or_ non-AMP without JS 👎 | AMP after 👍  | AMP after without JS 👍 
----------|----------------------------|---------------|----------------
The behavior is even improved over the non-AMP version in that it also renders fallback …
=> Add AMP compatibility for Pinterest block

modules/shortcodes/others.php, tests/php/modules/shortcodes/test-class.others.php
Replaces #14998 
* This PR updates the song.link oEmbed provider to support more formats.
* I extended the existing test to test for more potential formats, but did not use the full list provided [here](https://github.com/Automattic/jetpack/pull/14998#issuecomment-600367587) to avoid slowing down our tests too much. I picked one domain for each variation instead.
* Internal reference: D49210-code
* N/A
* Try to add some of the links provided [here](https://github.com/Automattic/jetpack/pull/14998#issuecomment-600367587) and see that they get displayed properly.
* Embeds: update song.link oEmbed to support more formats.
=> Embeds: update song.link oEmbed to support more formats.

extensions/blocks/pinterest/pinterest.php
* Follow-up from #17086. In some environments (on WordPress.com for example), `Jetpack_AMP_Support` is not always available by the time we load the block.
* N/A
* N/A
* Apply WordPress.com patch.
* Notice no Fatals.
* N/A
=> Pinterest: avoid errors when Jetpack_AMP_Support isn't available

extensions/blocks/contact-form/variations.js
Related: #17051
On WordPress.com Simple sites, it is not yet possible to easily take advantage of the new form variation, as you cannot install plugins to integrate form submissions with a newsletter solution.
Let's consequently remove that variation for now, to avoid confusion.
* p93VbO-gZ-p2
* p1599066361020000-slack-C0160HSMDQV
* No
* On a Jetpack site, when adding a form to a new post, the "Newsletter sign-up" option should still available.
* On WordPress.com Simple sites (when applying D49020-code), you should not see that option.
* N/A
=> Form Block: remove newsletter variation on wpcom simple sites

modules/sso.php
* The `sso_discover` JITM cannot be dismissed properly and is no longer needed, so this PR removes the JITM-related methods from `Jetpack_SSO`.
p1HpG7-8V8-p2
No
* Checkout this branch on a fresh Jetpack test site
* I recommend disabling the JITM cache with: `add_filter( 'jetpack_just_in_time_msg_cache', '__return_false' );`
* Enable Single Sign On in Jetpack Settings
* Log in to the site using SSO
* Ensure no SSO JITM appears on Dashboard > Home upon login.
* SSO / JITM: Removes Single Sign On discovery JITM
=> Remove SSO JITM from Jetpack_SSO

packages/tracking/composer.json, packages/tracking/phpunit.xml.dist, packages/tracking/src/class-tracking.php, packages/tracking/tests/php/bootstrap.php, packages/tracking/tests/php/test-tracking.php
* Add a new method, `Tracking::should_enable_tracking()`, which replicates the original logic in the `Terms_Of_Service::has_agreed()` method [before the changes](https://github.com/Automattic/jetpack/pull/16967/files#diff-70716275c6e734611a8a24650646c4fbL62) in PR #16967.
* Add unit tests for the new `Tracking::should_enable_tracking()` method.
* n/a
* No.
1. Install and activate Jetpack.
2. In your `wp-config.php` file, set the `JETPACK_SHOULD_NOT_USE_CONNECTION_IFRAME` constant to true. This will force the Calypso connection process to be used.
3. On the Jetpack dashboard, click the `Set up Jetpack` button.
4. Go to the Tracks live view and verify that the `jetpack_jpc_register_success` event was recorded.
* tbd
=> Tracking: add a should_enable_tracking() method

_inc/lib/debugger/class-jetpack-cxn-tests.php
Jetpack Debugger: Add new test for testing blog and current user's token against WP.com's check-token-health endpoint
* Adds a new `test__token_health` method in `Jetpack_Cxn_Tests` for checking both the blog and current user's token by making a REST API call to WP.com's `check-token-health` endpoint
* If for any reason the remote request fails, the test is marked as `skipped`.
**Note:** Since the local debugger is meant to be used by our end users, we are not displaying specific error codes or detailed info for any token related errors.
p9dueE-1NT-p2
No
* Go to your site's local debugger page (`/admin.php?page=jetpack-debugger`)
* Make sure all tests pass
* Using the "Broken Token" plugin (available via Jetpack Debug) invalidate the blog token. Also make sure to store your current …
=> Debugger: Add token health check test

packages/sync/src/modules/class-woocommerce.php
Fixes the [issue 554](https://github.com/Automattic/wc-calypso-bridge/issues/554)
This PR adds the options `woocommerce_task_list_hidden` and `woocommerce_onboarding_profile` to sync wc whitelist.
No.
* Verify that the values of `woocommerce_task_list_hidden` and `woocommerce_onboarding_profile` are synchronized.
* Added the options `woocommerce_task_list_hidden` and `woocommerce_onboarding_profile` to sync wc whitelist.
=> Added 2 options to sync wc whitelist

modules/copy-post.php
Fixes 5862-gh-jpop-issues
Copy post uses `$post->post_category` property to fetch the post categories. However, this property is fetched using a magic getter, since it does not exist on the database. If the blog is running on a [very old DB schema](https://href.li/?5903-core), in which the `post_category` column is still present, this method will fail.
This PR changes this approach to avoid this error.
Note, this was already deployed in WPCOM D49220-code
pMz3w-bWE-p2
No
See D49220-code
* Fix error when using Copy a post on DBs on old schemas
=> fixes copy post not copying categories in old dbs

packages/sync/src/class-defaults.php
Checking for edit_comment can only be used to check for the cap for one specific comment, which does not match our needs here.
More dicussion: p1599656662345700-slack-jetpack-crew
This did not come up in the past, and was triggered by a core change (r48961-core) that revealed the problem.
**Note**: in a future PR, we should consider making `Automattic\Jetpack\Sync\Modules\Users::get_real_user_capabilities()` more future-proof by ensuring it does not include caps that are not relevant or require extra arguments.
* N/A
* No
* N/A
=> Sync: stop trying to check for edit_comment capability

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, json-endpoints/class.wpcom-json-api-update-site-homepage-endpoint.php, sal/class.json-api-site-base.php
Summary:
Allows getting and setting `wpcom_public_coming_soon_page_id` via the api, as will be use by calypso on the *pages* page 
See D45700-code for more details
This commit syncs r213352-wpcom.
* Add support for public coming soon page redesign
=> Coming soon: add coming soon page id to homepage and sites APIs

extensions/blocks/story/player/style.scss, extensions/blocks/story/story.php
Updates the permalink used when JS is not present to load the story in fullscreen.
@Tug this seems to generally work but doesn't trigger fullscreen mode on Android Chrome. It seems like the two params aren't enough to trigger that?
* Auto-fullscreen permalink when JS isn't loaded
* Add bottom margin to story container (affects posts with multiple blocks and the Android Reader)
No change
Style change:
* Create a post with a story and a paragraph block right underneath.
* Observe the story is a bit too close to the paragraph (might be theme-dependent). (This is also a problem on the WPAndroid Reader.)
* Apply this change and confirm the spacing is better.
Permalink change:
* Apply this change to a Jetpack site, and follow that site in the Reader
* Apply the corresponding Calypso patch …
=> Story block: Improve static fallback

modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-universal.php
Fixes #17071
* Uses `WC_Order_Item_Product::get_product_id()` to get product ID for `woocommerceanalytics_product_purchase` event. 
Previously was using `$order->get_product_from_item` which is [deprecated](https://github.com/woocommerce/woocommerce/blob/master/includes/legacy/abstract-wc-legacy-order.php#L319) in WooCommerce 4.4+.
`WC_Order_Item_Product::get_product_id()` is [available in WooCommerce 3.0+](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order-item-product.php#L237); WooCommerce Analytics is [gated for 3.0+ and newer](https://github.com/Automattic/jetpack/blob/master/modules/woocommerce-analytics/class-jetpack-woocommerce-analytics.php#L62).
Not a product change - just a bug fix 👍 
No changes to tracking, just fixes a bug affecting an existing …
=> use current (not deprecated) API for getting product id for prop on purchase event

_inc/client/components/jetpack-notices/jetpack-connection-errors.jsx, _inc/client/components/jetpack-notices/notice-action-reconnect.jsx, _inc/client/rest-api/index.js, _inc/client/state/connection/actions.js, packages/connection/src/class-rest-connector.php, packages/connection/tests/php/test-rest-endpoints.php
This PR mainly cleans up the `action` parameter, used in the `reconnect` endpoint.
This parameter was introduced based on the assumption that the client will be aware of the type of reconnect we need to trigger, eg full or partial and send it along with the `reconnect` request.
Based on the current implementation, this logic is handled backend and the client is not aware of it, therefore we are cleaning up any references to the specific `action` we were meaning to send on the client side.
* Removes the required `action` param from the `reconnect` endpoint and updates the corresponding unit tests
* Removes the `action` param from the client rest-api request implementation
* Removes the `action` redundant references from the client notices component
* Removes the `action` argument from the …
=> Partial reconnect: Cleanup redundant actions

_inc/lib/debugger/class-jetpack-cxn-tests.php
The token check was introduced in the PR #17028.
Unfortunately, it's breaking the Jetpack Debugger (the one on `tools.jetpack.com`) because there is no user logged into WP when it runs.
This commit fixes the problem by checking the connection owner's token by default.
`p9dueE-1NT-p2`
No.
1. Go to https://tools.jetpack.com/debug/ and debug your site. All tests should pass.
2. Go to the Debugging Center (`/wp-admin/admin.php?page=jetpack-debugger`) and confirm that there are no errors.
3. Go break the user token via the Broken Token plugin.
4. Go back to https://tools.jetpack.com/debug/ and debug your site. You should see an error: `server error. requested method jetpack.testConnection does not exist`. This is fine for now, we'll need to make it validate the user token separately.
5. Go …
=> Jetpack Debugger: Fixing the user token health check.

modules/stats.php
Stats Module shouldn't render if the site is in Staging Mode.
Fixes #17052
* Update Stats Module so it doesn't track visits if the site is in Staging Mode.
No
1. On your testing site confirm that your site sends visits information by confirming that the following script gets loaded:
```
<script type='text/javascript' src='https://stats.wp.com/e-202036.js' async='async' defer='defer'></script>
<script type='text/javascript'>
_stq = window._stq || [];
_stq.push([ 'view', {v:'ext',j:'1:9.0-alpha',blog:'YOURBLOGID',post:'POSTID',tz:'3',srv:'YOURDOMAIN'} ]);
_stq.push([ 'clickTrackerInit', 'YOURBLOGID', 'POSTID' ]);
</script>
```
This script is for tracking a blog, a page view can be different. Keep in mind that stats are not sent for logged in administrators by default.
2. Add a constant to …
=> Don't render stats tracking code if in Staging Mode

class.jetpack.php, packages/config/src/class-config.php
We should consider removing the TOS and Tracking features from the Config package for three reasons:
* These features depend on the `Automattic\Jetpack\Plugin\Tracking` class, which is [located in the Jetpack plugin](https://github.com/Automattic/jetpack/blob/master/src/class-tracking.php#L23). Therefore, it's not possible for other consumer plugins to enable these features using the Config package.
* The Config package does not have any package dependencies, so we need to be extremely careful when making changes to this package. There's no way to guarantee which version of other packages will be installed. Therefore, I think we need to keep this package as small and stable as possible.
* I can't think of a need to configure the Tracking and TOS packages in the Config class. Consumer …
=> Config: remove tos and tracking features

tests/e2e/lib/page-helper.js, tests/e2e/lib/pages/wp-admin/login.js
Sometimes, WPORG login fails due (probably) invalid login/password typed in. I guess it might happen because the puppeteer logs in too fast
-
-
* This issue is hard to test since it happens quite rarely. 
* Looking through code should be enough
* n/a
=> E2E Tests: Fix WPORG login failures

.github/workflows/build-artifacts.yml, tools/build-jetpack.sh
In #14274 we introduced `nvm use` call into the `build-jetpack` script, which apparently wasn't working properly from the beginning. For some reason, `nvm` is not available in script context, which seems odd, but I guess this is how github action environment is set up 🤷 
* explicitly export `nvm` binary and run `nvm install` to pull `nvmrc`-defined node version
n/a 
n/a
* Check Beta builder action. it should be green
*
*
=> Build Artifacts: fix `nvm` not found issue

packages/sync/src/modules/class-comments.php
'review' comment_type added as a default Comment Type. This is used by Woo and other plugins and already is being sent to WP.com.
* Updating the default jetpack_sync_whitelisted_comment_types values to include review.
No
* Apply PR to your test site
* Insert comment with type "review" that is unapproved
* Approve comment
* Verify via kibana that a comment_approved_review sync action was sent for the site.
* Jetpack Sync - review comment_type now trigger the comment_approved_* comment_unapproved_* actions.
=> Adding 'review' to whitelisted comment types

packages/connection/src/class-client.php, packages/connection/src/class-manager.php, packages/connection/src/class-rest-authentication.php, packages/connection/src/class-utils.php
When Jetpack plugin is not installed, REST Authentication requires defaults constants to function. In particular, `JETPACK__API_VERSION` is empty, making the WP Proxy request signature verification fail.
- Extract the default constants initialization code into `Utils::init_default_constants()`.
- Replace the existing initialization with the new function call.
- Add a new initialization call for `Rest_Authentication` class so WP proxy requests signature could be properly verified.
`p1599852544000900-slack-CPBTESZMG`
No.
1. Install and connect Jetpack.
2. Open file `jetpack.php` and comment out two constants: `JETPACK__API_VERSION`, `JETPACK__API_BASE`.
3. Load the Dashboard, make sure it still works.
4. Go to the WordPress.com API Console and run an API request:
`WP.COM API`, `v1.1`, …
=> Connection: Initializing default constants for the REST authorization.

_inc/lib/debugger/class-jetpack-cxn-tests.php
Skips a test if the site is not connected.
* Skips a test if the site is not connected.
n/a
No
* Before patch, set `JETPACK_DEV_DEBUG` to true.
* Load Site Health and see a critical error related to the blog token.
* Apply patch, repeat, see no error.
* Site Health: Skip a test when in offline mode that assumed a connected site.
=> Local Testing Suite: Skip the blog token test if site is not connected

_inc/lib/class.media-extractor.php, _inc/lib/class.media-summary.php
Follow-up from #16506 
Fixes a problem with early return when still in another blog context.
* Adds a statement to switch back to the original blog before returning.
Barry: "Summary: We can't call switch_to_blog() and then return without also calling restore_current_blog(). One of these seems very old and the other one seems relatively new in class.media-extractor.php. It seems like we should be able to do some static or dynamic analysis to detect these cases and prevent new ones from being committed." Props @bazza  for the fix.
This commit syncs r213537-wpcom.
* N/A
* No
* TBA
* N/A
=> Fix early returns in Jetpack.

_inc/client/components/jetpack-notices/index.jsx, _inc/client/main.jsx, _inc/client/state/connection/actions.js
This PR adds support for a direct reconnect link that automatically triggers the partial reconnection process.
Up to now, this was only triggered by clicking the "Restore Connection" button, found in the corresponding alert when connection (token related) errors occured. 
* Adds a new `reconnect` dashboard route
* Triggers partial reconnection upon visiting the `reconnect` route seamlessly, while maintaining the same UX flow with clicking the "Restore connection" button, found in the corresponding alert when connection (token related) errors occur. 
* Hides the connection error and link-account notices while reconnecting
p9dueE-1NT-p2
No
**Broken blog token:**
- Invalidate the blog token using the Broken Token plugin
- Visit `admin.php?page=jetpack#/reconnect`
- The partial reconnect flow …
=> Client admin page: Add reconnect route

modules/custom-css/csstidy/data.inc.php
Fixes #17106 
* Adds support for the `clip-path` CSS property to the Customizer.
Raised as an issue here: [CSS Tidy: add clip-path · Issue #17106 · Automattic/jetpack](https://github.com/Automattic/jetpack/issues/17106) after initially suggesting Custom CSS to a user in 3294186-zen.
Not as far as I'm aware, no.
* Go to "My Sites → Design → Customize → Additional CSS"
* Create a CSS statement using the `clip-path` property, for example:
```
/* Add different circle crop to a larger images on the page */
.post-111 .wp-image-1020 {
clip-path: circle(25%);
}
```
* Adds support for the `clip-path` CSS property for use in Additional CSS in the Customizer.
=> Adding clip-path property to supported CSS properties

packages/blocks/src/class-blocks.php, packages/blocks/tests/php/bootstrap.php, packages/blocks/tests/php/test-blocks.php
* This PR starts adding methods to the new Blocks package we'll use for all Jetpack blocks from now on.
This just adds the method, we'll then start using them in blocks in #17101. 
* Internal reference: p9dueE-1BH-p2
* Primary issue: #17099 
* N/A
* Not much to test yet, those methods aren't in use just yet.
* N/A
=> Blocks: add new methods to new package

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, sal/class.json-api-site-base.php
Summary:
This patch is part of [[ 45148-gh-wp-calypso | #45148 ]]
This patch saves the `selected_features` as a site option.
We're looking to use this data during the Site setup flow (in editor) to recommend a plan based on the selected features.
The option will be available only for sites created using `site_creation_flow: 'gutenboarding'`.
Note: this change is a very similar to D42191-code
Test Plan: Follow testing instructions in [[ 45148-gh-wp-calypso | #45148 ]]
Reviewers: simison, mciampini, tomjcafferkey
Reviewed By: mciampini, tomjcafferkey
Differential Revision: D49420-code
This commit syncs r213657-wpcom.
* We now save the user selection made during Features step in Gutenboarding (wordpress.com/new/features).
* Go to …
=> Gutenboarding: save selected features as a site option

packages/autoloader/src/class-autoloader-handler.php, packages/autoloader/src/functions.php, packages/autoloader/tests/php/tests/test_autoloader_handler.php
In https://github.com/woocommerce/woocommerce/issues/27608 it became apparent that plugins can filter `active_plugins` in a way that prevents some plugins from being detected by the autoloader. This PR addressed the issue by caching the list in `should_autoloader_reset()` as an additional means to evaluating whether or not manifests should be processed again.
N/A
No
* Add this `autoloader-testing.php` file to `mu-plugin`. It sets up autoloader globals in a way that pretends the autoloader has been successfully loaded. Without this PR this will result in the entire site becoming inaccessible due to class loading errors, but with this PR, it will work as-expected.
```php
<?php
/**
* Plugin Name: Autoloader Testing
* Description: This plugin helps.
* Version: 1.0
*/
defined( 'ABSPATH' ) || …
```
=> Autoloader: Detect filtering of active_plugins

functions.photon.php
The following PR: https://github.com/Automattic/jetpack/pull/15774 has introduced a ban/filter in the Photon API for Wikimedia.org domain as images have a very specific URL.
Unfortunately, some Wikimedia.org subdomains are hosted on WordPress VIP and need to be able to use the Photon API.
Fixes #
* I have modified the  wikimedia.org pattern in the `jetpack_photon_banned_domains()` function to only ban subdomains starting with `commons` and `upload`. To my knowledge, only those 2 subdomains are meant to be skipped in the Photon API. Multiple Wikimedia subdomains like `diff`, `techblog`, `policy`, ... need to use the Photon API.
115353-zd-wordpressvip
No
The following blog post: https://diff.wikimedia.org/2019/10/23/my-life-as-a-strategy-liaison-for-the-french-language/  
has a …
=> Filter only specific Wikimedia subdomains in Photon API

packages/connection/legacy/class-jetpack-ixr-clientmulticall.php, packages/connection/tests/php/test_Jetpack_IXR_ClientMulticall.php
Fixes #17008
* Fix a `usort()` bug that will affect `add/license-support` once its merged.
N/A
No.
Running unit tests is sufficient. Since this PR introduces a method signature change you can use this variation of the unit test introduced in this PR to run on `master` in order to reproduce the issue:
https://gist.github.com/atanas-dev/ba31849fc39517df9deda659e8632953
The difference being:
```diff
diff --git a/packages/connection/tests/php/test_Jetpack_IXR_ClientMulticall.php b/packages/connection/tests/php/test_Jetpack_IXR_ClientMulticall.php
index aaf742da1..60051d5fb 100644
--- a/packages/connection/tests/php/test_Jetpack_IXR_ClientMulticall.php
+++ b/packages/connection/tests/php/test_Jetpack_IXR_ClientMulticall.php
@@ -177,6 +177,8 @@ class Jetpack_IXR_ClientMulticall_Test extends …
```
=> Jetpack_IXR_ClientMulticall: Fix sort_calls() producing undefined relative order between equal items

modules/shortcodes/crowdsignal.php
Crowdsignal: Don't call mktime() in a deprecated manner.
This has been deprecated since PHP 5.1 and removed in PHP 8.0.
This is untested, but the behaviour of `mktime()` is to simply return the same value as `time()` for such calls.
This was detected via PHP Code Sniffer:
```
FILE: jetpack/modules/shortcodes/crowdsignal.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
391 | ERROR | The "hour" parameter for function mktime() is missing.
|       | Passing this parameter is no longer optional. The
|       | optional nature of the parameter is deprecated since
|       | PHP 5.1 and removed since PHP 8.0
|       | …
```
=> Crowdsignal: Don't call mktime() in a deprecated manner.

_inc/lib/debugger/class-jetpack-cxn-tests.php
Up to now, the Jetpack debugger (and correspondingly the Site Health tool) used to:
1. Report connection failing tests in a non-consistent format, aka sometimes an intro text about what a connection is, other times only the error that occurred and different recommendations to resolve the issue.
2. Provide links for resolving the connection issues either to the admin dashboard or to the Jetpack support page on reinstalling / reconnecting Jetpack
This PR aims to provide consistent handling of connection related failing tests while most importantly utilize the reconnect flow by providing direct links to the end users in order to reconnect Jetpack in one-click. 
* Adds a `connection_failing_test` public static method in `Jetpack_Cxn_Tests` in order to return consistent responses for a …
=> Jetpack Debugger: Handle connection failing tests consistently

sal/class.json-api-links.php
* Defined `__wakeup()` as public, added a `die()` for safety.
All PHP Magic methods should be public, as of PHP8 __wakeup() causes a PHP Warning if it's defined as non-public.
Technically, `__clone()` and `__construct()` should also be public, but PHP doesn't yet trigger warnings for those methods, so I'm submitting the bare minimal PR.
This is untested, but shouldn't cause an issue.
This was detected via PHP 8 Lint checking:
```
php -l jetpack/sal/class.json-api-links.php
PHP Warning:  The magic method WPCOM_JSON_API_Links::__wakeup() must have public visibility in jetpack/sal/class.json-api-links.php on line 25
```
* Primary issue: #17166 
* No
* Start with a site runnning this branch
* Connect the site to WordPress.com
* Upload some media
* Go to …
=> PHP Warning: All PHP Magic methods should be public, as of PHP8 __wakeup() causes a warning

modules/custom-css/custom-css/preprocessors/lessc.inc.php, modules/custom-css/custom-css/preprocessors/scss.inc.php
Fixes #17190
* Add `rebeccapurple` to our 2 CSS preprocessors. 
* See https://www.w3.org/TR/css-color-4/#valdef-color-rebeccapurple
* No
* No
* Go to Jetpack > Settings and enable the Custom CSS feature.
* Go to Appearance > Customize > Additional CSS.
* Add the following:
```scss
a:hover { 
background: lighten(rebeccapurple, 40%);
}
```
* Pick the SCSS preprocessor
* Save
* Visit your site's frontend
* View source
* Ensure the SCSS was compiled into:
```css
a:hover {
background: #ccb3e6;
}
```
Custom CSS: add rebeccapurple color to the list of colors that can be processed by the SCSS and LESS preprocessors.
=> Custom CSS: add rebeccapurple color

tests/php/modules/shortcodes/test-class.slideshow.php, tests/php/sync/test_class.jetpack-sync-full-immediately.php, tests/php/sync/test_class.jetpack-sync-full.php
Fixes https://wp.me/p9dueE-1Ry
* Update Unit Tests so that restore_current_blog is called after each swtich_to_blog statement.
N/A
No
Verify Unit Tests are still fully functional
* N/A Unit Test update
=> Update Unit Tests to call restore_current_blog after switch_to_blog usage

_inc/lib/class.media-summary.php, class.jetpack-network.php, modules/carousel/jetpack-carousel.php
Fixes https://wp.me/p9dueE-1Ry
* Ensure restore_current_blog is called for all switch_to_blog usages.
N/A
No
Verify all Unit Tests Pass
1. Setup a Multi-site and connect several blogs with Jetpack.
2. perform a network wide deactivation -> ensure all blogs are disconnected
* Bug - ensure restore_current_blog is called for all switch_to_blog usages.
=> Update code paths to always call restore_current_blog if switch_to_blog was used.

extensions/blocks/gathering-tweetstorms/editor.js, extensions/blocks/gathering-tweetstorms/test/editor.js, extensions/blocks/gathering-tweetstorms/test/match-media.mock
Gutenberg 8.8 changed how the Twitter embed block is registered (WordPress/gutenberg#24090), which caused our checks before adding the "Unroll" button to fail.
This PR adds support for GB 8.8+, and maintains back compat with the older method.
Fixes #17201.
* Add support for Gutenberg 8.8+ to the Twitter thread unroller.
N/A
No Change.
Run through these tests with the Gutenberg plugin enabled and disabled.
* Paste a Twitter link in the block editor.
* Confirm that the Unroll button appears, and works as expected.
* Twitter Threads: Add support for unrolling threads when Gutenberg 8.8+ is activated.
=> Gathering Tweetstorms: Add support for Gutenberg 8.8+

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-gather.php
Related to changes allowing backups to be made accessed for coming soon sites.
Differential Revision: D47231-code
This commit syncs r212027-wpcom.
=> Rename `allow_blog_token_when_site_is_private` on tweetstorm endpoint 

_inc/client/components/jetpack-notices/state-notices.jsx, class.jetpack.php, packages/connection/src/class-rest-connector.php
This PR adds a success message when a partial reconnection has been completed.
Note that this currently only happens when we don't need the user to re-authorize their WP.com account, eg in cases where we are restoring a connection with unhealthy blog token.
* Adds a new hook in Connection's `REST_Connector` `connection_reconnect` endpoint, named `jetpack_reconnection_completed` when the response from connection restore is `completed`.
* Adds a new action in `Jetpack` that logs a re-connection success message to state cookie for later display in Admin.
p9dueE-1SB-p2#comment-3254
No
* Setup Jetpack in your testing site
* Invalidate the **blog** token using the Broken Token plugin
* Visit `admin.php?page=jetpack#/reconnect` 
* Verify that after successful reconnection you see the following …
=> Connection: Add success message on completed partial reconnection

class.jetpack-gutenberg.php, composer.json, composer.lock, extensions/blocks/button/button.php, extensions/blocks/calendly/calendly.php, extensions/blocks/eventbrite/eventbrite.php, extensions/blocks/gif/gif.php, extensions/blocks/google-calendar/google-calendar.php, extensions/blocks/image-compare/image-compare.php, extensions/blocks/instagram-gallery/instagram-gallery.php, extensions/blocks/mailchimp/mailchimp.php, extensions/blocks/map/map.php, extensions/blocks/opentable/opentable.php, extensions/blocks/pinterest/pinterest.php, extensions/blocks/podcast-player/podcast-player.php, extensions/blocks/repeat-visitor/repeat-visitor.php, extensions/blocks/revue/revue.php, extensions/blocks/slideshow/slideshow.php, extensions/blocks/story/story.php
* This PR starts adding methods to the new Blocks package we'll use for all Jetpack blocks from now on.
* Internal reference: p9dueE-1BH-p2
* Primary issue: #17099 
* N/A
* Install the AMP Plugin on your site.
* Connect Jetpack to WordPress.com, and try to add all the blocks added as labels to this PR.
* View them in AMP views as well.
* Ensure all blocks are displayed properly.
* Ensure that blocks that include a `view.js` file (such as the Map block) still load it on non-AMP views.
* N/A
=> Blocks: add AMP and CSS Classes methods to the new package

packages/README.md, packages/autoloader/README.md, packages/autoloader/src/AutoloadGenerator.php, packages/autoloader/src/AutoloadProcessor.php
* Add PSR-0 support to the autoloader. PR #16699 needs to use a composer package that uses the PSR-0 autoloading standard.
* n/a
* no
2. Add a package that uses PSR-0 to the list of required packages in the `composer.json` file. For example, add `"nojimage/twitter-text-php": "3.1.0"`.
3. Run `composer update`.
4. Open the `vendor/composer/jetpack_autoload_classmap.php` file and confirm that it includes the file paths for the `Twitter\\Text` classes: `EmojiRegex`, `Validator`, etc.
5. Run `composer update -o`.
6. Repeat step 4.
* Autoloader: add PSR-0 support.
=> Autoloader: add PSR-0 support

_inc/client/admin.js, _inc/client/components/reconnect-modal/README.md, _inc/client/components/reconnect-modal/index.jsx, _inc/client/components/reconnect-modal/style.scss, _inc/client/components/reconnect-modal/test/component.js, _inc/client/main.jsx
This PR adds a confirmation dialog so that the user can confirm their intention before triggering the reconnect process by url.
* Adds a new `ReconnectModal` with corresponding unit tests and usage instructions
* Handles `reconnect` routing using a more declarative approach, per React guidelines, by adding it to Routes in `admin.js`
* Displays the reconnect confirmation modal on `reconnect` route and redirects to `dashboard` upon dismissal or when reconnection is triggered in `main.js`.
* Upon reconnect modal confirmation the `confirm_reconnect_modal` click action is tracked.
p9dueE-1NT-p2
**Unit tests**
* Run `yarn test-client && yarn test-gui` and verify all tests pass
**Reconnect flow with confirmation modal**
* Setup Jetpack in your testing site
* Visit …
=> Admin: Request user confirmation before triggering reconnect by url

3rd-party/class.jetpack-modules-overrides.php
Correctly spell "apply" in the `Jetpack_Modules_Overrides` class.
=> fix spelling error in docblock

packages/autoloader/src/class-plugins-handler.php, packages/sync/src/modules/class-module.php
* Fix some PHPCS warnings that stop us from updating packages on WordPress.com
* N/A
* N/A
* N/A
=> Packages: avoid PHPCS warnings

class.jetpack-modules-list-table.php
Fixes #17229
The existing `jetpack_modules_list_table_items` filter ended up
not being very useful until now. It was only filtering the items
displayed, not the whole list of items available on the page.
The filter consequently could not be used to stop a specific item
from being displayed.
With this change, one can now filter an item out entirely.
I also took the opportunity to apply the filter to the views as well,
so when you filter an item out, the total count of items is updated.
It's worth noting that the filter is not currently being used in any theme or plugin in the plugin directory.
* N/A
* N/A
Before to apply this branch, add the following snippet to your site:
```php
/**
* Remove Masterbar from the old Module list.
*
* @param array $items Array of Jetpack modules.
*/
function …
```
=> Module List: filter all items using existing filter

extensions/blocks/image-compare/image-compare.php
Fixes #16858
See #14395
The Image Compare block on AMP pages was not including not only the caption but also the containing `figure.wp-block-jetpack-image-compare` wrapper element. This PR fixes that problem by just replacing the `div.juxtapose` element inside the block `$content` with the `amp-image-slider` element, rather than just rendering just the `amp-image-slider` alone.
AMP markup for block:
```html
<amp-image-slider layout="responsive" width="1536" height="2048">
<amp-img id="4175" src="https://wordpressdev.lndo.site/content/uploads/2020/09/fire-before.jpg" alt="" layout="fill"></amp-img>
<amp-img id="4176" src="https://wordpressdev.lndo.site/content/uploads/2020/09/fire-after.jpg" alt="" layout="fill"></amp-img>
</amp-image-slider>
```
AMP markup for block:
```html
<figure …
```
=> Preserve block wrapper and caption for Image Compare block in AMP

extensions/blocks/image-compare/image-compare.php
Fixes #16093
See #14395
All elements in AMP need to have dimensions defined up-front so that the page will have static layout to avoid [CLS](https://web.dev/cls/) (Cumulative Layout Shift). When no `width` or `height` is available for the Image Compare block, instead of omitting the `width`/`height` for the `amp-image-slider` component, the correct AMP fallback is to provide fallback dimensions. Since we don't know what the image dimension is, providing an aspect ratio of 1:1 seems to make sense.
* Ensure fallback dimensions are provided to Image Compare block when image size is not available
Add an Image Compare block to a post and view that post on an AMP page.
I'm not sure entirely why the `width` or `height` weren't available when calling `render_amp()`, so the only way I know to test …
=> Fix Image Compare block in AMP when width/height are not available

extensions/blocks/eventbrite/eventbrite.php, extensions/blocks/eventbrite/style.scss
See #14395.
This PR adds AMP compatibility for the Eventbrite block.
Given a post with this content:
```html
<h2>In-Page Embed</h2>
<a class="wp-block-jetpack-eventbrite eventbrite__direct-link" href="https://www.eventbrite.com/e/wordpress-diverse-speaker-workshops-october-2020-tickets-118559108485">https://www.eventbrite.com/e/wordpress-diverse-speaker-workshops-october-2020-tickets-118559108485</a>
<h2>Button and Modal</h2>
<div class="wp-block-jetpack-eventbrite"></div>
```
State |  Non-AMP | JS Disabled Before 👎 | AMP Before 👎  | AMP After 👍 | JS Disabled After 👍 
------|-----------|-------------|-----------|--------------|-------------
Initial | ![image](https://user-images.githubusercontent.com/134745/93173267-1f371700-f6e1-11ea-8457-19a7fe9652fc.png) | …
=> Add AMP compatibility for Eventbrite block

modules/contact-form/grunion-contact-form.php
Fixes #15981
See #14395
Fixes styling of Contact Forms on the legacy AMP post template in Reader mode. This is only an issue in legacy Reader mode because the old post templates do not have The Loop, and thus `loop_start` does not fire.
Before | After
-------|------
* Fix styling of Contact Forms in legacy AMP Reader mode post templates.
1. Add a contact form to a post.
2. Activate the AMP plugin.
3. Switch to Reader mode and select the "AMP Legacy" Reader theme.
4. View the post as AMP.
* Fix styling of Contact Forms in legacy AMP Reader mode post templates.
=> Fix styling of Contact Forms on the legacy AMP post template in Reader mode

extensions/blocks/contact-form/components/jetpack-newsletter-integration-settings-plugin-state.js
https://github.com/Automattic/jetpack/pull/16964#pullrequestreview-494478771
* Support WordPress instances installed in a subdirectory
* show the correct Activating vs Installing caption.
N/A
N/A
No
* Search for ‘Newsletter Sign-up’.
* Select the form block in the Gutenberg editor.
* Collapse the "Newsletter Integration" on the right side
* Click install plugin creative mail plugin
* Click open creative mail, this should open the creative mail plugin in a new tab.
* Make sure that the Creative Mail plugin is *installed but deactivated*
* Search for ‘Newsletter Sign-up’.
* Select the form block in the Gutenberg editor.
* Collapse the "Newsletter Integration" on the right side
* Click active plugin
* Click open creative mail, this should open …
=> Contact From: Newsletter integration error handling fix

extensions/blocks/google-calendar/google-calendar.php, extensions/blocks/google-calendar/view.scss
See #14395
Given this `post_content`:
```html
<hr class="wp-block-separator"/>
<a href="https://calendar.google.com/calendar/embed?src=askenergy%40oregon.gov&amp;ctz=America/Los_Angeles" class="wp-block-jetpack-google-calendar">https://calendar.google.com/calendar/embed?src=askenergy%40oregon.gov&amp;ctz=America/Los_Angeles</a>
<hr class="wp-block-separator"/>
```
Google Calendar is currently not rendering at all on an AMP page. This is because it is getting removed due to not having a `width` defined on the `amp-iframe`:
> ![image](https://user-images.githubusercontent.com/134745/94099028-cd784600-fdde-11ea-87e7-9e40b38b2f85.png)
This PR fixes that issue by supplying the proper `layout` of `fixed-height` rather than `responsive`, since the width is intended to be `100%`. (This appears to …
=> Fix AMP compatibility for Google Calendar block

packages/debug-helper/modules/class-jetpack-sync-debug-helper.php
In case of an error that contains object data, like in case of a disconnection, on shutdown this filter receives a WP_Error. This additional condition helps avoid a fatal error when trying to resolve an object as an array.
* Added a condition that checks for a WP_Error in the last Sync error filter.
N/A
N/A
* Enable the debug helper by clicking all checkboxes in the "Jetpack Debug" menu.
* Disconnect Jetpack by using the Dashboard disconnect link near the bottom of the page.
* See the fatal error in the log because of an attempt to access an array index on an object.
* N/A
=> Debug Helper: Added WP Error object handling.

modules/infinite-scroll/infinity.js
Summary:
Reported in 1014-gh-p2
Current code clears the spinner when the infinity xhr call responds with an error, or when the request succeeds and the payload is processed completely.
When two xhr calls are made in quick succession, and one of the calls returns first with the final payload batch, the second call will also succeed but with a payload of `{"type":"empty"}`, which can result in the infinity spinner never being cleared.
In this changeset, we cover the case described above.
Test Plan:
1. Test on a P2020 site with only a few posts -- i.e. not enough posts to fill the screen when in compact view.
2. Scroll your browser to the very bottom, and reload.
3. After the very last post (oldest) is loaded, the spinner should clear.
4. Test on Default/Expanded view, and also on non-P2 …
=> infinity: remove spinner when request completes but response is empty

_inc/client/components/settings-card/index.jsx, _inc/client/performance/search.jsx
* Do not display Upgrade banners in Offline mode, where folks will not be able to purchase a plan or product for their site.
This PR removes those banners: 
* N/A
* N/A
* Start with a site [in Offline mode](https://jetpack.com/support/development-mode/) (in JN, you can go to Settings > Jetpack Constants and enable that option)
* Go to Jetpack > Dashboard and Jetpack > Settings
* You should not see banners inviting you to upgrade. The Anti-Spam banner should be the only one remaining (since Akismet can still be used).
* Dashboard: do not display option to purchase a plan when in Offline mode.
=> Admin Page: do not display upgrade banners when in Offline mode

packages/blocks/src/class-blocks.php, packages/blocks/tests/php/test-blocks.php
* This PR adds methods used to register a block.
* This just adds the methods, we'll then start using them in blocks in a future PR.
* Internal reference: p9dueE-1BH-p2
* Primary issue: #17099 
* N/A
* Not much to test yet, those methods aren't in use just yet.
* N/A
=> Blocks: add block registration to package

.travis.yml, bin/pre-commit-hook.js, phpunit.xml.dist, tests/php/test-composer-lint.php
If composer.lock has a monorepo package as version "dev-master", this can easily confuse Composer into switching the package from the monorepo to the versions in the Packagist repository, which in turn will break Travis testing.
We avoid this in a few ways:
* A git pre-commit hook will attempt to switch them from "dev-master" to "dev-monorepo", and will fail the commit if it can't.
* A CI test has been added to avoid such changes being merged if they somehow get past the above.
* Our Travis setup has been adjusted to pretend to Composer that the monorepo version is "dev-master" instead of the default based on the commit ID, which should hopefully prevent it from getting confused.
none, but see https://github.com/Automattic/jetpack/pull/17030#issuecomment-697804890
No
Reset all changes …
=> Avoid version "dev-master" for monorepo packages in composer.lock

_inc/client/setup-wizard/feature-toggle/index.jsx, _inc/client/setup-wizard/feature-toggle/map-feature-to-props.js
This PR adds a Tracks event to the Creative Mail install button in the setup wizard.
N/A
No
1. On a Jetpack site without Creative Mail installed add the following to then end of the wp-config.php file in order to make the Setup Wizard show:
```
```
2. Visit `/wp-admin/admin.php?page=jetpack#/setup/features`.
3. Open the network tab in your browser's dev tools and filter for `t.gif`.
4. Click "Install now" on the Creative Mail recommendation. 
5. Verify that a request for `t.gif` is made with `feature=creative-mail` and `_en=jetpack_wizard_feature_install`.
6. Wait 5 minutes and then verify in Tracks Live View that the `jetpack_wizard_feature_install` event …
=> Jetpack Setup Wizard: Add Tracks event to Creative Mail install

packages/autoloader/README.md
* The v2.x version of the autoloader allows package classes to be loaded before the `plugins_loaded` action has fired. Remove the bullet point that states that package classes should be loaded only after all plugins have loaded.
* n/a
* n/a
* n/a. This is documentation change.
* n/a
=> Autoloader: remove the plugins_loaded bullet point from the README

class.jetpack-connection-banner.php, scss/organisms/_banners.scss
* Display a variation of the connection banner when the site has stored license keys.
pbtFPC-Ms-p2
No.
Case 1:
- Make sure Jetpack is active but not connected.
- Go to WordPress' Dashboard page.
- You should see the normal connection banner.
Case 2:
- Make sure Jetpack is active but not connected.
- Run the following: `yarn docker:wp option update jetpack_licenses '["lorem_ipsum"]' --format=json`
- Go to WordPress' Dashboard page. 
- You should see an updated connection banner that matches Option B in pbtFPC-Ms-p2
No changelog entry necessary.
=> Licensing: Add a license-aware version of the connection banner

extensions/blocks/publicize/twitter/options.js, extensions/blocks/publicize/twitter/tweet-divider.js, package.json, yarn.lock
After #16699, there appears to be a race condition when loading `wp-annotations`, which can cause it blocks to throw JavaScript errors.
While the `@wordpress/annotations` package doesn't actually export anything, adding `import '@wordpress/annotations'` is a signal to `@wordpress/dependency-extraction-webpack-plugin` that `wp-annotations` is a dependency, and needs to be added to the `editor*asset.php` files.
* Fixes a sporadic JavaScript error that can occur in the post editor.
N/A
No.
This is tricky to reproduce. It appears to occur most consistently in a fresh `wp-env` based setup, before connecting Jetpack to a WPCOM account.
* None needed.
=> Publicize: Fix race condition when loading wp-annotations

extensions/blocks/opentable/opentable.php, extensions/blocks/opentable/view.scss
See #14395
This fixes AMP compatibility for the OpenTable block by rendering an `amp-iframe` as opposed to the embed `script` on AMP pages. Note that the block edit function similarly constructs and iframe for preview purposes, so manually constructing the iframe is not unprecedented.
~👉  Note this is currently blocked by an AMP bug which has been fixed upstream but is not yet in production. See https://github.com/ampproject/amphtml/issues/29398. In order to test this PR, you need to first opt-in to to the `beta-channel` on the [AMP Experiments](https://cdn.ampproject.org/experiments.html) page. The fix should be rolled out to AMP's production channel by September 22nd.~  _The fix is now live._
Given this HTML content:
```html
<div class="wp-block-jetpack-opentable"><a …
```
=> Add AMP compatibility for OpenTable block

packages/licensing/src/class-licensing.php, packages/licensing/tests/php/class-test-licensing.php
* This is a minor change, just ensuring we use [Oxford commas](https://en.wikipedia.org/wiki/Serial_comma) when possible.
**Before**
**After**
* N/A
* No
* On a brand new site, add an invalid license: `yarn docker:wp option update jetpack_licenses '["lorem_ipsum"]' --format=json`
* Connect your site to WordPress.com
* When back in the dashboard, notice the notice.
* N/A
=> Licensing: use Oxford comma in error message

composer.json, composer.lock
The `nojimage/twitter-text-php` package requires `ext-intl` to be available. Unfortunately, the default PHP build on MacOS doesn't include `ext-intl`.
Since we're not making any use of the parts of `nojimage/twitter-text-php` that use `ext-intl`, we can override this requirement.
* Add a platform override for `ext-intl` to `composer.json`.
p9dueE-1WN-p2
No.
* Check that the PHP version you're using doesn't have `ext-intl` enabled. (`php -m`)
* Run `composer install`, and confirm that it finishes without errors.
* None needed.
=> Composer: Ignore the ext-intl requirement of nojimage/twitter-text-php

_inc/client/components/product-expiration/index.jsx, _inc/client/my-plan/my-plan-header/index.js, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php, package.json, yarn.lock
* In Jetpack > My Plan, switch from `moment` to `@wordpress/date` to display expiration dates for the current plan.
* Related issues: #16481, #16397 
* No
* Connect your site to your WordPress.com account and purchase a plan.
* Head back to Jetpack > My Plan in wp-admin.
* The displayed expiration date should be correct.
* Try changing the date format in Settings > General, as well as the site language; the date should remain correct.
* Admin Page: improve the display of dates in the Jetpack Plan screen.
=> Admin Page: switch to @wordpress/date in My plan page

_inc/client/my-plan/my-plan-body.jsx
* See https://github.com/Automattic/wp-calypso/issues/45288#issuecomment-701184609
After connecting a brand new site to your WordPress.com account, you are directed to Jetpack > My Plan when you want to go back to wp-admin. There, we offer a number of Jetpack features you can start using. One of those is Publicize. We suggest you "start sharing" by clicking a button that leads you to Publicize settings in Calypso. However, at that point Publicize is most likely not active yet; that Publicize settings screen is consequently not available yet.
In this PR, when the module is not active, instead of linking to Publicize settings we offer a button to activate the feature. If the feature is active, we then link to Publicize settings.
In addition to this change, I've also made sure we do not show …
=> Admin Page: activate Publicize before to link to its settings

.phpcs.xml.dist, bin/PHPCSSniffs/Sniffs/MasterUserConstantSniff.php, bin/PHPCSSniffs/ruleset.xml, bin/phpcs-requirelist.js, class.jetpack.php, jetpack.php, packages/connection/src/class-manager.php, tests/php/general/test_class.jetpack-data.php
Deprecates the JETPACK_MASTER_USER constant and add a linter rule to avoi it from being used again
p9dueE-1Gw-p2
No
* Nothing to test - just need general feedback, especially on the linter error message
* deprecate JETPACK_MASTER_USER constant
=> deprecates JETPACK_MASTER_USER and adds linter

_inc/lib/class-jetpack-instagram-gallery-helper.php
Prevents the following PHP warning when there's an error from the Instagram API
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .../_inc/lib/class-jetpack-instagram-gallery-helper.php on line 75
```
p1601478331363400-slack-CKZHG0QCR
No.
* Add the Latest Instagram Posts block to a page while tailing your site's PHP error logs
* You should not see the `count(): Parameter must be an array or an object` error when there's an error retrieving images.
* There's happens to be an [outage with the Instagram API](https://developers.facebook.com/status/issues/370520597643291/) if you test this soon, otherwise you can simulate this by sandboxing the wpcom API and returning `'ERROR'` for the `images`  property in …
=> Latest Instagram Posts: fix PHP warning when checking cached gallery

extensions/blocks/podcast-player/attributes.js, extensions/blocks/podcast-player/components/header.js, extensions/blocks/podcast-player/components/podcast-player.js, extensions/blocks/podcast-player/edit.js, extensions/blocks/podcast-player/podcast-player.php, extensions/blocks/podcast-player/templates/podcast-header.php
At present the block allows you to hide the episode description and cover art. This allows you to also hide the episode title.
* Add an attribute to toggle the visibility of the episode title.
No
* Create a post with a podcast player
* Add a podcast RSS feed
* Toggle the episode title off
* Load the post in the front end
* Confirm that the episode title doesn't show
* Podcast player: Make it possible to hide the episode title.
=> Podcast player: Make it possible to hide the episode title

_inc/connect-button.js
Fixes #17344
This change adds some logic that will manually carry over the `from` parameter from the original request, for cases such as #17344 where the flow starts in the wp-admin dashboard or plugins screen banner. 
One side effect of this approach is that the query parameter remains in the URL after the redirect happens `/wp-admin/admin.php?page=jetpack#/setup&from=connect-banner-72-dashboard`. 
pbtFPC-PY-p2
Yes, we should be properly tracking the `from` if it's set in any connection flow. 
- From `/wp-admin/index.php`, click the "Set Up Jetpack" button in the banner at the top
- You should be redirected to the Jetpack dashboard as normal
- The registration step should still be done automatically
- You should end up landing on the user auth step
- When in the auth …
=> Connect button: Carry the "from" param when redirecting.

_inc/lib/class-jetpack-instagram-gallery-helper.php
In D50630-code I simplified this library to remove WPCOM specific code. This PR just syncs the files again.
To test, just make sure the Instagram Latest Posts block still works I guess.
=> Update Instagram helper from WPCOM

modules/theme-tools/content-options/featured-images.php
Fixes #17345
Fixes #13107 
This will give plugin and theme authors more control over Jetpack's content options settings and how they impact CPTs.
* N/A
* N/A
* On a site with the Jetpack plugin installed and active, activate the "Rebalance" theme.
* Go to Jetpack > Settings > Writing, and activate Jetpack's Portfolios. 
* Go to Portfolio > Add New, and publish a portfolio item, with Featured image
* View that Portfolio item, you should see the Featured Image at the top of the page.
* Go to Appearance > Customize > Content Options, and disable featured images for single projects.
* Refresh the page; the featured image should be gone.
* Content Options: add new filter to allow theme and plugin authors to disable featured image removal for their Custom Post Types.
=> Content Options: filter to disable featured image removal for CPT

extensions/blocks/publicize/store/selectors.js
* Let's avoid block editor errors when Publicize isn't available for a Custom Post Type.
* N/A
* No
* Start with a site that's connected to WordPress.com, and where Publicize is disabled.
* Go to Jetpack > Settings > Writing, and activate Jetpack's Portfolios.
* Go to Portfolio > Add New
* Start typing 
* You'll notice that you cannot add any blocks; you'll get an error instead.
* Switch to this branch
* Go back to the editor.
* See no errors when typing.
* N/A
=> Publicize: avoid errors when Publicize isn't available

class.photon.php, tests/php/test_class.jetpack_photon.php
Fixes #9833
* Removes the attempted support for HTML4 percentage width/height in the Photon code. It has never conformed to HTML4 semantics, and since 2016 it hasn't even correctly implemented the "percentage of the image's native width/height" semantics.
See #9833 
No
* Enable Photon, if necessary.
* Using the code editor, attempt to add an `<img>` tag with percentage values for width and/or height.
* The resulting HTML should ignore the supplied percentage width/height, acting the same as if you had omitted the attribute entirely.
* Perhaps something like "Jetpack's image accelerator (Photon) will now ignore attempts to specify percentages for width or height in an `<img>` tag. This hasn't worked correctly since 2016, and even before that did not follow HTML4 semantics."?
=> Photon: Remove broken support for HTML4 img percentage width/height

modules/theme-tools/compat/twentytwenty.css
When using the Twenty Twenty theme and inserting Facebook videos inside a classic block, videos used to be breaking out of the layout:
This fixes that:
Reported here:
p8oabR-y3-p2/#comment-4678
* No
* Start with a site using the Twenty Twenty theme.
* Add some content.
* Insert a Classic block
* Inside that block, paste this on its own line: `https://www.facebook.com/WhiteHouse/videos/10153398464269238/`
* Publish your post
* Ensure it is displayed properly.
* Embeds: ensure Facebook videos are centered properly with the Twenty Twenty theme.
=> Twenty Twenty: ensure Facebook videos are centered properly

_inc/client/at-a-glance/index.jsx, _inc/client/at-a-glance/scan.jsx, _inc/client/rest-api/index.js
Fixes #17220.
* Significantly refactor the `DashScan` component to make the VaultPress/Rewind switching logic more straightforward
* Add copy and handling to the Scan card for states where VaultPress is active but not registered/connected
* Use Rewind status to determine whether the site uses VaultPress or Rewind, instead of checking VaultPress data directly (doesn't appear to be as reliable?)
* Hide the At-A-Glance Scan card entirely for multi-sites that don't use VaultPress, since Rewind doesn't currently support multi-site networks
N/A
Nope 👍 
Monitor the **Network** panel in your browser's developer console. Verify that outgoing requests eventually stop once the page is fully loaded; or, to rephrase, ensure that network calls to get VaultPress/Rewind status don't infinitely repeat. …
=> At-A-Glance: Only show the Scan card for multisites if they're connected to VaultPress

class.json-api-endpoints.php, class.json-api.php, json-endpoints/jetpack/class.jetpack-json-api-endpoint.php, tests/php/json-api/test-class.json-api-jetpack-endpoints.php
This PR updates the functionality of Jetpack JSON API endpoints by allowing them to support both site based authentication and also define needed capabilities that will only be checked if user based authentication is provided.
In short, if an endpoint allows site based authentication ( `allow_jetpack_site_auth` is `true` ) and the current authentication includes a blog token (no logged in user), then any needed capabilities defined by an endpoint will not be checked.
If though, the aforementioned endpoint is accessed with a user token, then the capabilities will be checked, same as before.
It's important to note that we will no longer need to set `$needed_capabilities = array()` in a Jetpack JSON API endpoint in order to support the blog token like we used to. 
We can have both the …
=> REST API: Site based authentication migration

tests/php/json-api/test-class.json-api-jetpack-endpoints.php
Not much, just moves the `parent::setUp` call to the top of `WP_Test_Jetpack_Json_Api_Endpoints` `setUp` method
n/a
no
n/a
n/a No functional changes
=> REST API tests: Minor update in setUp method

modules/publicize/publicize-jetpack.php, modules/stats.php, packages/connection/legacy/class-jetpack-xmlrpc-server.php, packages/heartbeat/src/class-heartbeat.php, packages/sync/src/class-sender.php, tests/php/general/test_class.jetpack.php
This PR opens the possibility make request to some XMLRPC methods using the Blog Token as well as the user token.
p9dueE-1VI-p2
No
See 26a46-pb/#php
*
=> Make XMLRPC methods available for blog token

_inc/client/lib/jp-redirect/index.js, _inc/lib/admin-pages/class.jetpack-react-page.php
Automatically append the current site in every link generated by the `getRedirectUrl` method of the `jp-redirects`lib.
* Adds a new global javascript variable to inform the jp-redirects lib about the current site url
* Changes the lib to 
p1601493560050900-slack-CDLH4C1UZ
No
* `yarn docker build-client`
* Visit Jetpack Dashboard
* Confirm that the link to Support how includes a `site` parameter with the current site URL
* Automatically append the current site in every link generated by the `getRedirectUrl`
=> Automatically adds current site url in getRedirectUrl

_inc/lib/class.media-extractor.php
Fixes `E_NOTICE: /home/public_html/wp-content/plugins/jetpack/_inc/lib/class.media-extractor.php:267 - Trying to access array offset on value of type bool` (discovered in w.org logs)
* Simple isset for URL parts.
* Unsure, but likely setting an image URL that's relative directly into the post.
*
* Media Extractor: Prevent PHP notice for some URLs.
=> Media Extractor: Ensure URL parts are present

packages/autoloader/tests/php/tests/test-version-selector.php, packages/autoloader/tests/php/tests/test_manifest_handler.php
* A few of the unit tests require that the `JETPACK_AUTOLOAD_DEV` constant be set to true. Currently, we're checking whether the constant is defined before setting it. If the constant is already defined, we can't guarantee that the constant is set to true, making the tests less reliable. Let's remove the `defined()` checks. If the constant is already defined when the unit tests are executed, an error should be generated.
* n/a
* no
* These changes affect the tests. Verify that the autoloader packages tests have passed.
* n/a
=> Autoloader: remove the defined('JETPACK_AUTOLOAD_DEV') checks from the tests

modules/shortcodes/instagram.php
See D50894-code. Note, this is already merged to WP.com
* Because we have rate limiting for our Facebook access token, we need good logging/stats in place. This action makes it convenient to hook in any time an embed request is made to handle logging/stats.
See D50894-code and p7H4VZ-2DU-p2
It does not change what logging that we have in the Jetpack core plugin. It does, however, allow us to better log requests with a standard retention rate on WordPress.com
See D50894-code
* Add jetpack_instagram_embed_request action to allow for logging and stats since the Facebook embed API is rate limited.
=> Jetpack: API: Add jetpack_instagram_embed_request action

modules/shortcodes/instagram.php
Fixes #17424
Differential Revision: D50902-code
This commit syncs r214945-wpcom.
* The graph.facebook.com endpoint for Instagram embeds does not like query params and seemingly always returns errors. This patch will clean the query params by only using the path from the URL.
* Only using the path from the URL also allows us to simplify some other validation logic.
See D50902-code
No
- Checkout patch
- Create JN site and connect
- Create post and add Instagram embed.
- `https://www.instagram.com/p/CGAWEzXnD-O/?utm_source=ig_web_copy_link` should work just as well as `https://www.instagram.com/p/CGAWEzXnD-O/` or `https://instagr.am/p/CGAWEzXnD-O/`
* Instagram Embeds: ensure that Instagram URLs with additional URL parameters can be embedded as well
=> Jetpack: Clean query params and force URL and protocol

packages/connection/src/class-client.php, packages/connection/src/class-manager.php, packages/connection/src/class-rest-authentication.php
A fatal error can occur under these conditions:
- Jetpack is updated from <=8.9.1 to >=9.0.
- The Dashboard -> Updates tool is used to update Jetpack.
The generated error is `Fatal error: Uncaught Error: Call to undefined method Automattic\Jetpack\Connection\Utils::init_default_constants()`
This PR prevents the fatal from occurring.
Thanks to @sergeymitr for suggesting this fix.
* Call `add_filter( 'jetpack_constant_default_value'...)` directly rather than calling `Utils::init_default_constants()`.
* n/a
* no
1. Install, activate, and connect Jetpack 8.9.1.
2. Using the Dashboard -> Updates tool, update Jetpack to 9.0.1.
3. Observe the error.
1. Install, activate, and connect Jetpack 8.9.1.
2. Set up a snippet to force an update to this branch. See p9dueE-1AG-p2 for instructions. The …
=> Connection: add the constant filter hooks directly

_inc/lib/class-jetpack-tweetstorm-helper.php, tests/php/_inc/lib/test-class.jetpack-tweetstorm-helper.php
This PR fixes two errors in URL handling, that can cause invalid tweets to be generated:
- The `href` of a link tag should only be inserted into the text when it's a URL that Twitter considers to be valid. (For example, `mailto:foo@bar.com`. and `ftp://foo.com` are valid `href` values, but Twitter doesn't auto-link them, so they shouldn't be treated as URLs.)
- Before the URL from an embed block is appended to the tweet, it should check that the tweet has enough space for it.
Additionally, this PR extends handling of when link text is the same as the link `href`: it previously only checked if they were identical, but it now checks if the text is a shortened version of the `href`. (For example, having a `href` of `https://wordpress.org/` and a link text of `wordpress.org` will no longer …
=> Publicize: URLs are sometimes counted incorrectly in Twitter threads.

extensions/blocks/publicize/twitter/options.js
Fixes https://github.com/Automattic/wp-calypso/issues/46279
* When we have no connections available (like in the page editor, where Publicize isn't available), we shouldn't need to load Publicize Twitter settings.
Related:
- https://github.com/Automattic/wp-calypso/issues/46278
- https://github.com/Automattic/wp-calypso/issues/46279
* p2EDhh-1aA-p2
* No
* Go to Pages > Add New
* See no editor errors
* See Publicize Twitter options
* Publicize: avoid block editor errors when no Publicize connections are available.
=> Publicize: avoid loading Twitter settings when not necessary

extensions/blocks/publicize/twitter/editor.scss, extensions/blocks/publicize/twitter/options.js, extensions/blocks/publicize/twitter/test/options.js
This PR includes a couple of tweaks to the Twitter options panel, making it more usable.
- The style and copy has been tweaked to more closely match the post visibility radio options in Core.
- The panel is now hidden when there are no Twitter accounts selected.
* Tweaks to the Publicize Twitter options panel.
p58i-9vv-p2#comment-47632
No.
* Open the Publicize panel in a post.
* Ensure that the options look correct.
* Ensure that the options are only visible when one or more Twitter accounts is enabled.
* Publicize: Improve the usability of the Twitter thread options.
=> Publicize: Improve the text/usability of Twitter thread options

.travis.yml
* Adds automated slack notifications for failed master builds into #jetpack-r2d2
n/a 
n/a
* Not much to test here. 
* once merged, look for Travis failures for the master build, then check #jetpack-r2d2
* n/a
=> Travis: Add slack notifications for failed master builds

_inc/client/at-a-glance/stats/dash-stats-bottom.jsx, _inc/client/at-a-glance/stats/index.jsx
Follow-up to #17321
* This should allow for better translations and date formatting in i18n languages for all date labels in the Stats graph of the Jetpack dashboard.
**Before (note the untranslated dates and months)**
**After**
* Related issues: #16481, #16397
* No
You'll need an active site with some stats to be able to test things.
* Go to Jetpack > Dashboard
* Check the different views of the Stats graph (day / week / month)
* Check the dates in all labels and axis; they should be formatted properly.
* Check the "Best day" item at the bottom of the stats graph; that day should be formatted according to the settings under Settings > General.
* If you switch to a different language, that date should change to use the new language.
* Dashboard: improve the display of dates in the Stats …
=> Admin Page: switch to @wordpress/date in Stats dashboard

modules/subscriptions/views.php
* Adds a missing label for screen readers in Subscriptions form (wpcom)
5911-gh-jpop-issues
No
- Apply D51011-code to your sandbox
- Add a subscription form in your Wordpress.com sandboxed site
- Make sure a corresponding label for the `email` input exists but is not visible, with class `screen-reader-text`
* N/A :: These changes do not affect the Jetpack plugin
=> Subscription module: Add missing email input label

modules/comments/comments.php
See #9730.
When validating an post permalink that has comments enabled and the Jetpack Comments module active, two validation errors are raised:
Invalid `name` attribute on iframe | Invalid `script` output by `watch_comment_parent`
----------------------------------|-----------------------------------------------------
This PR removes the invalid `name` attribute on the `iframe`. It also uses AMP's built-in `layout=fixed-height` rather than using inline styles.
Additionally, I noticed that when I enter a long comment that is higher than 400px, the iframe begins to scroll when it should resize itself:
> ![image](https://user-images.githubusercontent.com/134745/94521104-52e66680-01e2-11eb-9ca0-95f3cd856117.png)
In order for an iframe to resize itself in AMP, it needs to be marked as …
=> Improve Comments module's AMP compatibility

extensions/blocks/calendly/calendly.php
Fixes #15935 
* If jQuery and o2 are available, bind the `ready.o2` [event](https://backbonejs.org/#Events-on) to the body element and initialize the Calendly widget in the callback. This loads the Calendly widget _after_ the o2 plugin has replaced main#content.
See 426-gh-p2tenberg
No changes.
Only a12s can test this fix.
* Apply D49317 to your sandbox with a premium plan.
* Activate the P2020 theme with wp cli: `wp theme activate pub/p2020 --url=[siteurl]`
* Enable Calendly blocks by commenting out wp-content/plugins/p2tenberg-wpcom/p2tenberg-wpcom.php line 159 (`'jetpack/calendly',`)
* Create a post and insert the Calendly block, and add a Calendly link.
* The block should embed a Calendly widget in the editor.
* Save the post and preview/view it in the front end.
* Check that the …
=> Calendly Block: Fixes Widget Not Loading on P2 Front End

extensions/shared/external-media/index.js
Enables External Media feature for the Cover block.
* Adds `core/cover` to the list of blocks External Media is available to.
No
* In the Editor, insert a Cover block and chose an External Media provider to insert a background image.
* Replace the image with a different one.
* Makes External Media available to the Cover block.
=> External Media: Enable for Cover block

extensions/shared/external-media/media-button/media-menu.js, extensions/shared/external-media/sources/index.js, extensions/shared/icons.js, package.json, yarn.lock
Fixes #17472 
Updates external media provider icons to be properly aligned in the latest Gutenberg version (without breaking existing versions). Also updates Media Library icon.
* Adds html class for icons to be properly aligned
* Adds `@wordpress/icon` library to replace old media library Icon
* Updates `yarn.lock`, not sure if that's desired.
No.
* Go to the Editor
* Click to add a Featured Image in the right sidebar and make sure (1) the Icons are aligned to the right (or left, depending on Gutenberg version) and (2) the media library icon is updated (an SVG rather than dashicon)
* Insert a media & text block and add an image to the media part.
* Click on "Replace" and make sure the icons are aligned properly
* External Media: updated iconography and better forward compatibility. …
=> External Media: Update source icons

modules/custom-post-types/portfolios.php
Fixes #17322
* The Portfolio Post Type needs to support custom fields so post meta can be saved by Publicize when the post is saved.
* N/A
* N/A
* Go to Jetpack > Settings > Writing and enable Portfolios.
* Go to Jetpack > Settings > Sharing and enable automatic sharing, then configure it (connect a test Twitter account)
* Go to Portfolio > Add New
* You should see the Publicize options in the Jetpack plugin sidebar.
* When making changes there (such as entering a custom message), and then saving as draft, your changes should remain.
* When publishing your portfolio, the custom message you've entered should get used on your Twitter message.
* Publicize: ensure that custom messages can be saved when using the Portfolio Custom Post Type.
=> Publicize: ensure that post meta can be saved for Portfolio CPT

extensions/blocks/videopress/constants.js, extensions/blocks/videopress/edit.js, extensions/blocks/videopress/utils.js
Relates to https://github.com/Automattic/jetpack/issues/17465
In Video Block (`core/video`):
- adds utils to determine aspect ratio
- adds aspect ratio classes to preview
Code is pull from Gutenberg embed block which handles it correctly 
https://github.com/WordPress/gutenberg/blob/e4b6d70f129a745a0cc7dc556d41a44bdab7b0ca/packages/block-library/src/embed/util.js#L177
* apply D51012-code
* Open the sandboxed site
* Edit a page / post
* Add a 30/30/30 columns block
* Add a video to 1 column
* Video should get full width of the current column
* Height should be adjusted according to the aspect ratio of the original video
Before | After
-------|------
* Fix video block to respect video aspect-ratio in editor
=> Fix video (videopress) aspect-ratio in editor

tests/e2e/README.md, tests/e2e/lib/pages/wpcom/pick-a-plan.js, tests/e2e/lib/setup-env.js, tests/e2e/specs/connection.test.js, tests/e2e/specs/plugin-updater.test.js, tests/e2e/specs/pre-connection.test.js
* Don't pre-connect Jetpack when it is not needed
This PR saves around 1 minute for E2E tests run time.
n/a
n/a
* Travis should be green
* E2E build time should be lower
*n/a
=> E2E Tests: Don't pre-connect for suites where it is not needed

extensions/blocks/story/edit.native.js
This PR builds on top of https://github.com/Automattic/jetpack/pull/17222
This PR changes the `StoryUpdateProgress` component to the more generic abstraction `BlockMediaUpdateProgress` - this is mostly a renaming refactor
Related PRs:
Gutenberg: https://github.com/WordPress/gutenberg/pull/26005
Gutenberg mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2706
WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13101
=> Mobile Stories block (part 3): rename using BlockMediaUpdateProgress

modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
With the Calypso editor deprecated and the code to switch editors
removed from WPCOM, the code to trigger the inclusion of the 'Switch to
Classic' option is redundant. This change removes that code.
Testing is difficult in that there is no way to get the 'Switch to Classic' option to appear anymore. As this change affects the WPCOM Block Editor code, editing a post within the Gutenframe on a Jetpack site will mean that the code is run. Checking for errors in the browser dev tools, and on the server side is probably the best testing we can do. 
N/A
=> Editor Deprecation: Remove the Switch to Classic option

tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/setup-env.js, tests/e2e/specs/plugin-updater.test.js
It is a follow-up to #17470 which did not properly disable pre-connect step.
The problem with the above PR is that it uses env var that was set in the build time, it would not reflect any runtime changes.
n/a
n/a
* Make sure the tests are green :D 
*
* n/a
=> E2E Tests: Disable pre-connection in some tests V2

modules/contact-form/grunion-contact-form.php, tests/php/modules/contact-form/test-class.grunion-contact-form.php
Fixes #7633
* Add more HTML entity-encoding when converting Gutenblock input to shortcode text, to avoid a few problems:
* Commas in "options" and "values" were conflicting with the use of commas as an array element separator.
* Brackets broke shortcode parsing entirely.
* Backslashes would get mangled too.
* A bit of incidental improvement to the tests.
No discussion, but see #7633
No
* Create a page with a contact form.
* Attempt to create radio buttons with commas in the labels.
* Save or preview, and see that your radio buttons are as intended rather than being broken on commas as in #7633.
* Do the same with brackets (`[` and `]`) and backslashes anywhere in the form.
* Perhaps "Contact Form: Selection widgets, radio buttons, and checkboxes can now have commas in the labels and …
=> Contact Form: Allow for commas and such in field labels, options, and values

_inc/client/traffic/site-stats.jsx
Removes the hide smiley stats toggle.
Before:
After:
The api endpoint in has been left for now: https://github.com/Automattic/jetpack/blob/fix/17304-hide-smile-ui/_inc/lib/class.core-rest-api-endpoints.php#L2610
Fixes #17304
* Remove UI control for stats smiley (hidden by default)
N/A
N/A
* Go to `wp-admin/admin.php?page=jetpack#/settings?term=site%20stats`
* Verify that the stats toggle has been removed from the UI
* N/A
=> Remove smile stats toggle

modules/shortcodes/facebook.php
WIth the turning down of Facebook oEmbed support, Jetpack's internal oEmbed handler is now being used embedding Facebook posts. The way this is implemented, however, does not work with the AMP plugin's conversion of Facebook post embeds to `<amp-facebook>` components.
Given this `post_content`:
```html
<figure class="wp-block-embed-facebook wp-block-embed is-type-rich is-provider-facebook">
<div class="wp-block-embed__wrapper">
https://www.facebook.com/aljazeera/posts/10159392848398690
</div>
</figure>
```
This is resulting in the following markup added to the non-AMP page:
```html
<figure class="wp-block-embed-facebook wp-block-embed is-type-rich is-provider-facebook">
<div class="wp-block-embed__wrapper">
<fb:post href="https://www.facebook.com/aljazeera/posts/10159392848398690" …
```
=> AMP: Use div.fb-post instead of fb:post to modernize and fix Facebook post embeds on AMP pages

class.jetpack-plan.php, tests/php/general/test_class.jetpack-plan.php
* There's no need to update the `jetpack_active_plan` option if the plan hasn't changed. Compare the plan from the WPCOM response to the current plan and bail early if they're the same.
* Add two new data provider elements for the unit test:
- The site starts with a free plan and WPCOM returns the free plan. In this case, the `jetpack_active_plan` option should not be updated.
- The site starts with a personal plan and WPCOM returns the personal plan with an additional available feature. In this case, the `jetpack_active_plan` option needs to be updated.
* n/a
* no
1. Install and activate this branch.
2. Connect Jetpack and select the Free plan.
3. Check that the free plan is in the `jetpack_active_plan` option:
`wp option get jetpack_active_plan`
4. Upgrade the Jetpack plan. For example, …
=> Jetpack_Plan: don't update the option if the plan hasn't changed

package.json, yarn.lock
Fixes #16397
Following the work we've done in #16481, we should not be needing this dependency anymore.
**Note**: the library is still loaded, as it's required as a dependency of `@automattic/format-currency`
* #16481
* No
* Nothing should change, you should be to load the Jetpack dashboard pages with no errors.
* N/A
=> Admin Page: remove i18n-calypso dependency

.gitignore, .phpcs.xml.dist, bin/phpcs-requirelist-commands.js, bin/phpcs-requirelist.js, composer.json, package.json, yarn.lock
* As we eye adding PHPCS rules and whenever we update PHPCS versions, our "clean" files can be out of date. This adds a processor to run through the list to PHPCBF them all and run PHPCS.
* Adds chalk as a direct dev dep.
A first attempt of something to run whenever sniffs are updated—either our in-repo or upstream diffs.
n/a
* `composer php:requirelist`
* n/a
=> Dev: Add processor for lists on the require list for PHPCS

.phpcs.xml.dist, bin/PHPCSStandards/Jetpack/ruleset.xml, bin/phpcs-requirelist.js, composer.json, composer.lock, packages/codesniffer/.gitattributes, packages/codesniffer/.gitignore, packages/codesniffer/Jetpack/Sniffs/Constants/MasterUserConstantSniff.php, packages/codesniffer/Jetpack/ruleset.xml, packages/codesniffer/README.md, packages/codesniffer/composer.json, packages/codesniffer/phpunit.xml.dist, packages/codesniffer/tests/php/bootstrap.php, packages/codesniffer/tests/php/tests/files/master-user-constant.php.report, packages/codesniffer/tests/php/tests/files/master-user-constant.php.tolint, packages/codesniffer/tests/php/tests/test-jetpackstandard.php
This moves the code for custom Jetpack phpcs sniffs into a new package in the monorepo, which will make it easier in the future to import additional sniffs and add tests. It'll also make it easy to reuse the coding standard in any other code repo we might wind up with.
This also adds some tests, and has the WordPress sniffs be pulled in via the Jetpack standard instead of being pulled in on their own.
None directly, but see p9dueE-1Y9-p2 for the proposal this cleanup is motivated by.
No.
* Verify that this doesn't change any sniffs reported by `composer php:lint` or the like. You might do that by
* Check out a clean copy of master. Run `composer install && composer php:lint -- --report-file=/tmp/report.old`
* Pull in this PR. Run `composer install && composer php:lint -- …
=> Add a package to hold our coding standard

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php, json-endpoints/jetpack/class.wpcom-json-api-get-option-endpoint.php, json-endpoints/jetpack/json-api-jetpack-endpoints.php
This PR is part of our work towards migrating endpoints to allow blog tokens described in #17379 and covers the two sub-tasks under the Technical Debt section.
In more detail, in order to allow blog token usage in the past we had removed the Sync related endpoint capabilities in #16893 
With #17331 though, we can now both have needed capabilities defined for endpoints (if a user token is used) AND allow blog token usage, as long as the endpoint has the `allow_jetpack_site_auth` flag set.
So in this PR, we are adding again the needed capabilities we had removed from Sync related endpoints.
* Sets the `allow_jetpack_site_auth` flag for Sync related endpoints (covers Options related endpoints as well as they are used by Sync).
* Re-adds the previously removed needed permissions in Sync …
=> REST API: Add sync related endpoint capabilities

extensions/shared/use-upgrade-flow/index.js
When block editor is running under Calypso, clicking on Upgrade Plan button should call the parent Calypso and display the checkout modal overlay.
This improves the user experience of the checkout flow by avoiding the need to exit block editor and redirect to the checkout page.
See related PRs and issues at https://github.com/Automattic/wp-calypso/milestone/322
Fixes: https://github.com/Automattic/wp-calypso/issues/46389
- On a FREE site, open up calypso block editor behind the feature flag `post-editor/checkout-overlay`, for example: https://wp_dot_com/block-editor/page/your_site_here.wordpress.com?flags=post-editor/checkout-overlay
- Add any jetpack premium blocks.
- Click on "Upgrade Plan" button.
- It should show checkout modal instead of redirecting.
* No changelog entry needed …
=> Add checkout overlay action to upgrade flow

modules/infinite-scroll/infinity.php
#9120 made a change to Infinite Scroll which changed the behaviour for the "click" option.
This reinstates only behaviour in Infinite Sroll thus:
If infinite scroll is set to `click` and the user has a `posts_per_page` setting which is different from the default (10) then use that instead of the theme value.
cc @mikejolley
Fixes #16471
No
* Choose a theme that supports infinite scroll (e.g. Pictorico)
* Turn on Infinite Scroll with this setting: "Load more posts in page with a button"
* Change the posts per page setting on wp-admin/options-reading.php to a number that isn't 10
* Check that this number of posts loads on the frontend.
* Load the user's setting for posts per page in Infinite Scroll if it's not the default
=> Infinite Scroll: Set the number of posts for the 'click' option to the global setting

_inc/lib/class-jetpack-tweetstorm-helper.php, extensions/blocks/publicize/twitter/editor.scss, extensions/blocks/publicize/twitter/options.js, extensions/blocks/publicize/twitter/tweet-divider.js, tests/php/_inc/lib/test-class.jetpack-tweetstorm-helper.php
There are two relatively common use cases where Latin-based sentence punctuation won't be used:
- Informal writing, particularly text messaging, where punctuation and capitalisation are read as being overly formal.
- Non-Latin languages, which only sometimes use Latin punctuation.
In both of these cases, we can treat line breaks as being the equivalent of sentence breaks. When we need to split up a chunk of content into multiple tweets, line breaks are a good indicator that it's a reasonable place in the content to split.
Chrome and Firefox render the line break split indicator slightly differently, I was unable to determine why.
* The Twitter thread generator can now choose to split content at line breaks, when it needs to.
N/A
No.
* Create a new post, and change to Twitter thread mode. …
=> Publicize: Allow splitting Twitter thread text at line breaks

_inc/lib/class-jetpack-tweetstorm-helper.php, tests/php/_inc/lib/test-class.jetpack-tweetstorm-helper.php
By inserting a block that only contains non-breaking spaces, it's possible for a tweet consisting only of whitespace to be generated. This tweet will be rejected by Twitter's API, causing the thread to fail. This behaviour can be confirmed by trying to tweet only whitespace on twitter.com.
To prevent this from happening, this change expands the final thread checks to trim all whitespace, not just the whitespace characters that `trim()` catches.
* Ensures the Twitter thread generator checks for tweets that only contain whitespace.
N/A
No change.
* Create a new post.
* Add some text.
* Add a final heading consisting of non-breaking spaces (on MacOS, type Option+Space).
* Check that the heading doesn't show in the parse REST API response, or in the thread preview.
* Publicize: Ensure that …
=> Publicize: Remove tweets from threads that are only whitespace

extensions/blocks/story/index.js, extensions/index.json
This PR makes the Story block available to everyone in production, it keeps the block hidden in the block picker though.
Currently a beta block, this PR simply moves the definition of "jetpack/story" from the "beta" section to the "production" section,
pbD5rk-m7-p2
- Apply this patch
- Disable beta and experimental blocks on your jetpack config
- Ensure the Story block is not available in the picker when you search for it
- Ensure you can edit story blocks created from the mobile app or when pasting a template
* Add support for the Story block
=> Make the story block available in production

docker/bin/run.sh
This adds a symlink into the Docker environment like #17570 did for
Travis.
None.
No.
To see the failure this is fixing,
* Run `yarn docker:update-core-unit-tests`
* Run `yarn docker:phpunit --filter=test_plugin_action_links_get_synced`, the test should fail.
To test the fix,
* Run `yarn docker:build-image`
* Stop (`yarn docker:stop`) and restart (`yarn docker:up`) the Docker dev environment.
* Run `yarn docker:update-core-unit-tests`, if necessary.
* Run `yarn docker:phpunit --filter=test_plugin_action_links_get_synced`, the test should pass now.
* Probably none.
=> Docker: Add symlink for WordPress test environment change

docker/bin/run.sh, tests/php/sync/test_class.jetpack-sync-callables.php, tests/php/sync/test_class.jetpack-sync-plugins-updates.php, tests/php/sync/test_class.jetpack-sync-plugins.php, tests/setup-travis.sh
WordPress upstream has changed the test environment to define
WP_PLUGIN_DIR (see WordPress/wordpress-develop@9e83d04). Which made our
Travis tests fail when they were expecting that Jetpack would be listed
by `get_plugins()`.
For the time being, at least, let's copy Jetpack into both the old
and new locations so `get_plugins()` will find it.
None, but several threads in Slack.
No.
* See if tests are green.
* None needed.
=> Fix tests for upstream test environment change

modules/sharedaddy/recaptcha.php
This commit was generated from D50774-code.
The original wpcom diff (D50774-code) attempts to provide AMP compatibility to the VIP Contact Form.
This adds a filter to allows us to add extra valid hostnames with which to compare the hostname from the recaptcha token. This is needed because the [amp-recaptcha-input](https://amp.dev/documentation/components/amp-recaptcha-input/) component returns a different hostname than `get_home_url()`
More info: pau2Xa-23c-p2
No.
Instructions can be found in the original diff D50774-code.
Alternatively, a simpler set of instructions would to check if the VIP Contact Form still works.
* Go to https://wordpress.com/pricing/
* Scroll down to the VIP CTA section and click on `Learn more`
* Fill in the VIP Contact Form and Submit
* The submit should be …
=> reCaptcha: add filter to verify against multiple hostnames

extensions/blocks/podcast-player/api.js, extensions/blocks/podcast-player/edit.js
Fixes #17496
* Surface errors from the Podcast Player API - they contain useful context of the exact error.
* Only use the generic error as a fallback
—
no
* Test for example with an empty feed
* or force the API error like I did:
* at the top of the method `get_player_data` in `_inc/lib/class-jetpack-podcast-helper.php`,
* `return new WP_Error( 'err_code', __( 'Custom error message', 'jetpack' ) );`
* More helpful error messages in the Podcast Player block
=> Podcast Player: Show error from API

extensions/blocks/google-calendar/editor.scss
Updates the Google Calender block UI to be more consistent with other blocks. 
Before:
After:
with comparison to Calendly
Fixes #17326 
* Style only
N/A
N/A
* Pull this PR
* Create a new Google Calendar block and check the UI 
* Compare it with the Calendly UI 
* N/A
=> Update size of input on Google Cal block

modules/sharedaddy/sharing-service.php
* Opening this to replace #9767, since Travis does not report test results in that PR and since I do not have the permissions to push to that forked repo to rebase the branch and trigger Travis again.
In some hosting environments (VIP Go), the use of `get_blog_lang_code` (a function defined on WordPress.com and VIP Go) can trigger a deprecation warning:
`get_blog_lang_code is deprecated since version 2.0.0 with no alternative available.`
-- https://github.com/Automattic/vip-go-mu-plugins-built/blob/ed65a52b9b27554efa92b301e31124df1e1e244a/vip-helpers/vip-deprecated.php#L786
This solves this issue.
See discussion in #9767 for more background on this.
* N/A
* N/A
* Not much to test here, `get_bloginfo( 'language' )` is supported in all environments.
* On VIP Go, the deprecation warning …
=> Sharing: remove get_blog_lang_code() call

class.json-api-endpoints.php
Summary: This patch switches the site visibility to public for all sites created from WPAndroid. It does so by updating the type expected by the sites/new endpoint to also accept a string and it that case checks if it's equal to the parameter name itsef. So `public: "PUBLIC"` gets transformed to `public: 1` while `public: "PRIVATE"` gets transformed to `public: 0` (because (int) "PRIVATE" is 0)
Test Plan: Try creating a site from WPAndroid while sandboxing [private link], the new site should be public
Differential Revision: D51492-code
This commit syncs r215520-wpcom.
This PR add a new API type definition that is currently used in the /sites/new endpoint. 
* Add a new API type definition that is currently used in the /sites/new endpoint. 
This PR doesn't currently effect Jetpack. 
- Do …
=> : Patch site creation to fix all requests coming from WPAndroid

modules/stats.php
It's completely unclear what might be happening in #15582 or how it
might be reproduced. But some static analysis (see the issue) seems to
indicate that Stats wants a WP_Post object and not anything else, so
perhaps we can cut the spaghetti knot and just check for that class
directly in Stats.
Also, since phpcs is making me touch the surrounding lines anyway for
alignment of `=`, remove some extraneous parens and throw in some
try-finally logic to make it a little more robust.
Fixes #15582
None I'm aware of.
It stops incorrectly reporting a term ID as a post ID in some existing tracking. Instead "0" will be used, as for other cases where no post ID is available.
* Check that normal posts still have the post ID in the Stats footer as they did before.
* If you can figure out how to …
=> Stats: Insist on a WP_Post when trying to fetch a post ID

packages/jitm/src/class-jitm.php
* The JITM package shouldn't depend on methods from the Jetpack plugin, so let's use the `Manager::is_active` method instead of `Jetpack::is_active`.
* n/a
* no
1. Install and activate Jetpack.
2. Set up the `jetpack_pre_connection_prompt_helpers` filter, which allows the pre-connection JITMs to be displayed:  
`add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );`
3. Verify that the pre-connection JITMs are displayed. For example, navigate to wp-admin -> Appearance -> Widgets. The "Looking for event more widgets?" JITM should be displayed.
4. Connect Jetpack.
5. Verify that the post-connection JITMs are displayed. For example, naviage to wp-admin -> Jetpack -> Dashboard -> At a Glance. The "Give your site a speed boost" JITM should be displayed, assuming that you …
=> JITM: use is_active from the connection package

webpack.config.search.js
* We moved from using Webpack performance settings to `size-limit` for checking bundle sizes in #17507. Unfortunately, #17495 restored the Webpack performance settings due to git shenanigans.
* This PR removes the Webpack performance settings.
* Run `yarn build-search`. Ensure it works as expected.
* Run `yarn test-search`. Ensure it works as expected.
* None.
=> Instant Search: Remove accidentally restored Webpack settings

class.json-api-endpoints.php, json-endpoints/class.wpcom-json-api-render-endpoint.php
Based on the D50016, but now with a hotfix for embed rendering endpoint to prevent all the PHP warnings :)
See p7H4VZ-2F7-p2#comment-8953
Test Plan: manual
Reviewers: scruffian
Differential Revision: D51494-code
This commit syncs r215583-wpcom
* N/A
* N/A
See p7H4VZ-2F7-p2#comment-8953
* N/A
=> REST API: postpone the call to `wp_templating_constants();` until we are on a correct blog

extensions/shared/components/block-nudge/index.jsx, extensions/shared/components/stripe-nudge/index.jsx, extensions/shared/components/stripe-nudge/style.scss
Fixes Automattic/wp-calypso#46010
* Vertically center content in Stripe banner connection warning.
**Before**
**After**
* Switch to this branch
* Add a premium block to a page or post on a site that does not have an established Stripe connection
* You should see the above banner and its contents should be vertically aligned to the center.
* Fix visual bug with Stripe connection banner.
=> Fix visual bugs in Stripe warning nudge

modules/widget-visibility/widget-conditions.php
The Widget Visibility feature requires a lot of data in order to provide a very flexible visibility settings for the widgets. For instance, it lists all the pages on a site in a dropdown, which may be an issue for sites with a huge amount of pages, or sites with very large pages, so they don't fit into a single memcache key=>value pair.
In order to preserve the current behaviour (listing all the pages), but optimize the loading times, this patch is introducing a custom direct SQL query for fetching only necessary data of all pages (ID, post_parent, and post_title). The direct SQL query is being cached under plugin's own group, and is taking advantage of the `wp_cache_get_last_changed( 'posts' )` value, which is being flushed whenever a new page is being added, so the listing should be …
=> Fix memory and performance issues of the Widget Visibility module

modules/widget-visibility/widget-conditions.php
This PR adds a couple filters for modifying the number of tags or categories fetched by the widget visibility settings. There isn't currently a good way of modifying that limit, and Newspack has a number of sites with more than 1000 tags. On those sites, some tags will be missing from the widget visibility list. 
An alternate approach could be to just do `number => 0` which would get all of the terms, but that may take so long that the request times out on sites with a lot of tags and poor infrastructure. I think a filter is the way to go because it doesn't affect the behavior unless something is hooked into the filter.
n/a - this doesn't modify the product in any way.
n/a - this doesn't affect any of that.
1. Go to Jetpack settings and enable widget visibility:
2. Go to Appearance > …
=> Add filters for modifying the max number of tags/categories fetched in widget visibility

packages/sync/src/class-defaults.php, packages/sync/src/class-functions.php, packages/sync/src/class-replicastore.php, packages/sync/src/interface-replicastore.php, packages/sync/src/modules/class-themes.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/server/class.jetpack-sync-test-replicastore.php, tests/php/sync/test_class.jetpack-sync-full-immediately.php, tests/php/sync/test_class.jetpack-sync-full.php, tests/php/sync/test_class.jetpack-sync-themes.php, tests/php/sync/test_interface.jetpack-sync-replicastore.php
In https://github.com/Automattic/jetpack/pull/16827
We introduces a new way of syncing the theme supports data while doing that we missed adding additional theme date that is currently registered. 
This PR also seperates the theme data and theme supports information. 
So that theme data ( name, version, slug and uri) doesn't contain any theme support data. Since this info should be stored different places on .com side.
This PR also adds additional theme supports data so that we would be able to provide the same data as the /themes?status=active endpoint. 
We sync more theme related data. 
* Switch the theme. Make sure that this works as expected. Apply the D50465-code to your .com sandbox. 
Does the data appear to be as you would expect it to be? 
* Improved syncing of the theme related …
=> Sync: Seperate theme data ( name, version, slug and uri) from theme support data 

packages/jitm/src/class-pre-connection-jitm.php
* Currently, the `Pre_Connection_JITM` class uses `Jetpack::admin_url()` to generate the Jetpack admin url. The JITM package shouldn't depend on the Jetpack plugin, so let's add a new method that generates an admin url in the `Pre_Connection_JITM` class.
* n/a
* no
1. Install and activate Jetpack (don't connect).
2. Set up the `jetpack_pre_connection_prompt_helpers` filter, which allows the pre-connection JITMs to be displayed:
`add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );`
3. Navigate to wp-admin -> Posts. A pre-connection JITM should be displayed. Verify that the `SET UP JETPACK` button link contains `?page=jetpack&#/setup`.
4. Navigate to wp-admin -> Media. A pre-connection JITM should be displayed. Verify that the button link contains …
=> JITM: add a Pre_Connection_JITM::generate_admin_url method

packages/sync/src/modules/class-callables.php
Verify that $action_links is still an array after filters before calling array_filter on it.
Fixes #17550
* Resolve PHP Warning when $action_links has been filtered to not be an array.
No
1. Add a filter to plugin_action_links that returns null
`add_filter( 'plugin_action_links', '__return_true' );`
2. delete_option( 'jetpack_callables_sync_checksum' );
3. delete_transient( 'jetpack_sync_callables_await' );
4. modify a post -> triggers sync
**Before PR**
Warning will be visible in error logs.
**After PR**
No Warning is generated.
* Jetpack Sync - Resolve array_filter warning that can be triggered by filters returning unexpected data.
=> Resolve PHP Warning with array_filter usage in sync of action_links.

extensions/shared/register-jetpack-block.js
~This PR improves the way to define the block example when registering the jetpack block. In short, it won't add the `example` key to the block settings, instead of adding it with an `undefined` value.~
This PR enables showing the block examples for all blocks, removing the conditional about if it requires a paid plan or not. For instance, `pay with paypal`:
Indirectly, it fixes the following issue in Calendly block:
When the block is inserted in the editor canvas, the preview breaks the block settings (sidebar) and block toolbar. Setting the preview for the `link` style explicitly fixes the issue.
Fixes #
* Improve setting block example process
No
* Apply these changes to your dev end. Use D51652-code for Simple sites.
* Go to create/edit a post
* Add a Calendly Block. You can use this …
=> RegisterJetpackBlock: improve settings block example

modules/comment-likes.php, modules/likes.php
* The postmessage.js script register and enqueue indicate that jquery is a dependency.   However, postmessage.js itself - https://github.com/Automattic/jetpack/blob/master/_inc/postmessage.js - indicates that jquery is optional.  That being the case, it shouldn't be asking for jquery to be loaded.
* Primary issue: #16409 
* No
* Not much to test here. Try Liking posts and comments, and make sure that still works.
* Likes: remove jQuery dependency where possible.
=> Remove jquery dependency from postmessage.js

.travis.yml
In some scenarios, composer is set in `$HOME/.config/composer/` instead of `$HOME/.composer/
Internal discussion: p1603706416114500-slack-CBG1CP4EN
* N/A
* N/A
* Do all the tests pass?
* N/A
=> Unit Tests: look for global PHPUnit installation in 2  places

_inc/lib/core-api/class.jetpack-core-api-site-endpoints.php
* The `stats_get_from_restapi()` function [can return](https://github.com/Automattic/jetpack/blob/master/modules/stats.php#L1632) a `WP_Error` object. When that happens, a PHP notice will be generated when we try to access the stats property of the `$stats` variable in `Jetpack_Core_API_Site_Endpoint::get_benefits`. So, let's check whether the `$stats` variable is a `WP_Error` object before trying to access its properties.
* n/a
* no
1. Install, activate, and connect Jetpack.
2. Visit your site in an incognito window to generate visitor stats.
3. Navigate to wp-admin -> Jetpack -> Dashboard. Scroll down to the `Site connection` card and click the `Manage site connection` link. You should see the disconnection modal, which includes stats for the connection benefits. 
4. Edit the …
=> Core_API_Site_Endpoint: check whether a WP_Error was returned in get_benefits

extensions/blocks/story/player/index.js, extensions/blocks/story/player/player.js, extensions/blocks/story/player/slide.js, extensions/blocks/story/story.php
This PR fixes the latest bugs and UI feedback on the Story block:
- Media not cropped in fullscreen in iOS Safari
- Fix icon pixelated
- Create a story, with its first image being a bit thinner than 9:16
- Load the post on Safari iOS (not the homepage)
- Don't scroll
- Use your first interaction with the page to tap on the story
- Make sure the image does not have black margins on the side
- Load a story in fullscreen
- Check that the site icon is not pixelated
- Inspect the image url loaded, make sure it ends with `?w=40`
=> Story block: minor UI fixes and improvements

extensions/blocks/slideshow/swiper-callbacks.js
Fixes #16127
* Lazy loading is set up before the slideshow's duplicate first and last images are generated. This leads to missing images when the slideshow loops when lazy image loading is enabled. To fix this, dispatch the `jetpack-lazy-images-load` event in `swiperInit`.
* n/a
* no
1. Install, activate, and connect Jetpack.
2. Navigate to wp-admin -> Jetpack -> Settings -> Performance and enable lazy loading for images.
3. Create a post that includes some content, including a slideshow block with multiple photos. The slideshow block should be at the bottom of the post so that lazy image loading will be used for the slideshow's images.
4. View the post while logged out or in an incognito window.
5. Click the slideshow arrow buttons to display the slide show images. When the slideshow …
=> Slideshow: dispatch the jetpack-lazy-images-load event in swiperInit

.github/workflows/e2e-tests.yml, .travis.yml, tests/e2e/bin/includes.sh, tests/e2e/bin/push-allure-artifacts.sh, tests/e2e/lib/page-helper.js, tests/e2e/lib/reporters/slack.js
Move E2E tests from Travis into GH actions
With GH Actions, we could customize our runs, run different suites on different events (e.g. on new tags, merges to master, etc)
n/a 
n/a 
* Take a look at "Checks" section
* Make sure the tests have passed.
* n/a
=> E2E Tests: Migrate to github actions

extensions/shared/components/block-styles-selector/index.js
This PR fixes an issue adding the block-styles buttons to the toolbar. We are using the wrong component. Instead of [Toolbar](https://developer.wordpress.org/block-editor/components/toolbar/), we should use [ToolbarGroup](https://developer.wordpress.org/block-editor/components/toolbar-group/).
before | after
-------|-----
Fixes #
* Restore block styles buttons in the block toolbar
No
* Apply these changes (use D51527-code for Simple sites)
* Go to create/edit a post
* Add, for instance, en Eventbrite embed block
* I picked up https://www.eventbrite.com.ar/e/a-feminists-guide-to-botany-online-botanical-painting-session-tickets-121982903147
**before**
* Confirm you don't see the block style buttons in the toolbar
**after**
* Confirm you see the block style buttons right there
* Restore …
=> Block Styles Selector: fix toolbar buttons

class.jetpack-post-images.php, functions.opengraph.php, tests/php/media/test-class.jetpack-post-images.php
Adds support for the Story block to `Jetpack_PostImages`, allowing the Open Graph image tags (`og:image` and `twitter:image`) to be set for posts containing the story block. This also enables themes that support it (e.g. Cubic) to have a preview image for story posts in the post gallery, without requiring a featured image.
~I'm also proposing a tweak to the open graph image selection logic, so it selects the first 'good' image in a post instead of the last (the Twitter card tag logic already does this).~ Extracted that part to #17598.
The image tags can be inspected by viewing the source of a post page, they look like this:
```html
<meta property="og:type" content="article" />
<meta property="og:title" content="A story post" />
<meta property="og:url" …
```
=> Story block: Post Images support

_inc/client/state/initial-state/reducer.js
It's not clear that a user_id needs to be added to the redirect parameter in order for it to be tracked. 
- Adds a default for the selector `getUpgradeUrl` that will fall back to whatever is set in the getUserId() state. Also updated the `getUserId` to default to an empty string, to match the pattern of what it's replacing. 
Yes, see panfyZ-48-p2
Yes, it will ensure that any usage of `getUpgradeUrl` within the react dashboard will carry a user_id along, and will get tracked on wpcom side unless they've opted out. 
- Connect
- Hover over this button:
- You should see the redirect URL with the `u=` parameter defined. 
- If you click it, you should also see your tracks even get logged in the live feed. 
N/A
=> Upgrade URL: Set default to add current user to the redirect URL in the state selector.

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, bin/phpcs-requirelist.js, packages/redirect/tests/php/bootstrap.php, tests/php/core-api/wpcom-endpoints/test_class-wpcom-rest-api-v2-endpoint-admin-menu.php
First step towards enhancing the Masterbar module with nav-unification for Calypso.
This change has no dependencies and doesn't change the way Masterbar works. It introduces the admin menu API endpoint that Calypso will use to import a site's menu. The PR includes unit tests for all endpoint methods as well.
* Add Admin Menu API endpoint.
* Add unit tests for API endpoint
* Update phpcs require list to include the two new files.
* Update `wp_parse_url()` function signature that caused an error in my editor.
pbAPfg-VL-p2#comment-1904
No
To run unit tests:
* Follow [setup guidelines](https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md#unit-testing) if you don't have unit tests set up yet.
* Run `phpunit --filter WP_Test_WPCOM_REST_API_V2_Endpoint_Admin_Menu`
* …
=> Masterbar: Add Admin Menu endpoint

class.json-api-endpoints.php, json-endpoints/class.wpcom-json-api-get-comment-endpoint.php, json-endpoints/class.wpcom-json-api-get-post-endpoint.php, json-endpoints/class.wpcom-json-api-get-post-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-get-site-endpoint.php, json-endpoints/class.wpcom-json-api-get-site-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-get-taxonomies-endpoint.php, json-endpoints/class.wpcom-json-api-get-taxonomy-endpoint.php, json-endpoints/class.wpcom-json-api-get-term-endpoint.php, json-endpoints/class.wpcom-json-api-list-comments-endpoint.php, json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php, json-endpoints/class.wpcom-json-api-list-posts-endpoint.php, json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-list-posts-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-list-terms-endpoint.php, json-endpoints/class.wpcom-json-api-update-comment-endpoint.php
This commit syncs r215949-wpcom.
* Add a new endpoint property, `allow_fallback_to_jetpack_blog_token`, whether this endpoint allows falling back to a blog token for making requests to remote Jetpack sites.
* Update existing endpoints that should allow falling back to Jetpack blog token
p9dueE-1Yq-p2
No
n/a
* n/a :: Hardening WPCOM REST API v1
=> REST API: Add endpoint property for allowing fallback to blog token

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
Addresses changes brought up in https://github.com/Automattic/wp-calypso/issues/46664
* Internal reference: D51890-code. 
* Go to '..'
*
*
=> REST API: Add support for GA4 measurement IDs

bin/version-packages.sh, composer.json
The jetpack-codesniffer package is our first that is `require-dev` in Composer and our script to version packages for release branches assumed that all pacakges were going to be `require`.
This PR fixes by using Composer 2's new `composer show --no-dev` flag to only display `require` packages. Since this flag is not available in <2.0, this also adds a check for that.
Additionally, this PR sets our repo in composer.json as "non-canonical". In Composer 2.0, all repos are now consider canonical by default. Previously, it was reversed.
A "canonical repo" is one where, once a package is found in that repo, no other repos after that are checked. In our case, that meant our local file path was the *only* place Composer would look for versions of any our monorepo packages. Only if we didn't have …
=> Build: Prevent dev packages from being versioned / Composer 2 compat

extensions/blocks/button/button.php, extensions/blocks/contact-info/contact-info.php, extensions/blocks/map/map.php, extensions/blocks/podcast-player/podcast-player.php, extensions/blocks/send-a-message/send-a-message.php, extensions/blocks/send-a-message/whatsapp-button/whatsapp-button.php, extensions/blocks/slideshow/slideshow.php, extensions/blocks/story/story.php, extensions/extended-blocks/core-audio/core-audio.php, extensions/extended-blocks/core-cover/core-cover.php, extensions/extended-blocks/core-video/core-video.php, extensions/extended-blocks/premium-content-container/premium-content-container.php
After #17406, updated the "requiredlist" files to match new PHPCS rules for blocks.
* PHPCS
n/a
n/a
n/a
* n/a
=> Updated PHPCS: Blocks

packages/connection/legacy/class-jetpack-ixr-client.php
Brings over a change made in r215538-wpcom . We aren't setting the Content-Type on these requests.
n/a
n/a
* Tests pass.
* Connect a new site to Jetpack. Interact with it via WordPress.com (Calypso or the developer.wordpress.com/console).
* Any obvious errors in the browser dev console/networking tab? Specifically wanting to ensure setting the Content-Type doesn't break normal interactions with a Jetpack site.
* Connection Package: Declare Content-Type.
=> Connection Package: Ensure a text/xml header is set

packages/connection/src/class-manager.php, packages/connection/src/class-plugin.php
When a plugin (e.g. Jetpack or WCPay) initiates a connection, we don't know the name of the plugin.
The slug of the plugin is now passed to WP.com during site registration.
We pass additional parameter into the registration API request - name of the plugin initiating the connection.
1. Disconnect your site, make sure that `blog_id` is clean.
2. Apply D51955-code and switch your site to the sandbox.
3. Connect Jetpack.
4. Check the Tracks Live to confirm that events `wpcom_jpc_register_begin` and `wpcom_jpc_register_success` have the `connect_plugin: jetpack` property.
5. Disconnect Jetpack, install WCPay.
6. Connect WCPay.
7. Confirm that the same events contain the property `connect_plugin: woocommerce-payments`.
n/a
=> Connection: Plugin Tracking

extensions/editor.js, extensions/shared/styles/slideshow-fix.scss
Fixes #17616. Carried over from https://github.com/WordPress/gutenberg/pull/26552 so we have a short-term fix while waiting for that PR to land.
Set `max-width` of `.interface-interface-skeleton__editor` to 100%, so that blocks cannot 
> exceed the editor boundaries and, when set to full width, gain a width of literally millions of pixels, making the editor unusable.
For more details, see https://github.com/WordPress/gutenberg/pull/26552.
N/A
No.
Verify that #17616 is fixed.
Set `max-width` of `.interface-interface-skeleton__editor` to 100% to fix wide/full alignment of Slideshow Block.
=> Slideshow Block: Fix Wide/Full Alignment

modules/contact-form/css/editor-ui.css, modules/contact-form/grunion-contact-form.php, scss/jetpack-icons.scss
Introduced in #10670.
* Reverts feedback menu icon to dashicon
No.
Before | After
-------|------
* Apply the diff and make sure the Feedback menu item in wp-admin's sidebar menu has changed to a dashicon
* None needed.
=> Feedback: Allow Calypso to change menu icon color

packages/sync/src/class-replicastore.php
Alignment of ReplicaStore with WP.com implementation. A Replica Store can be hosted on another server that does not have access to the same themes/plugins. Therefore it is needed to call ensure_taxonomies so that the Taxonomy is registered before attempting to update object terms.
* N/A - Cleanup of technical debt.
* NO
* N/A - local testing will always early return with ensure_taxonomy 
=> Update update_object_terms to utilize ensure_taxonomy so that the Taxonomy is registered.

packages/sync/src/class-replicastore.php
Call ensure_taxonomy before delete to make sure Taxonomy has been initialized.
* N/A - Cleanup of technical debt.
- NO
* Create a new Term
* On Master run the following commands in shell
* `$store = new \Automattic\Jetpack\Sync\Replicastore();`
* `$store->delete_term( $term_id, $taxonomy );
* Verify the term has been removed
* Apply this PR / checkout branch
* Repeat the above steps
=> Alignment of delete_term with implementations.

packages/sync/src/class-replicastore.php
Addition of post-trashed status and cleanup of cases.
* N/A - Cleanup of technical debt.
- NO
* On Master run the following commands in shell
* `$store = new \Automattic\Jetpack\Sync\Replicastore();`
* `$store->comment_count( 'approve' );
* record this return value.
* Apply this PR / checkout branch
* Run the same commands in shell
* Verify the return is consistent.
* Add a new Post
* Add several comments to the new Post
* Trash the new Post
* Execute $store->comment_count( 'post-trashed' );
* Verify it returns count of posts with 'post-trashed' status
=> Alignment of comment_status_to_approval_value function. 

packages/sync/src/class-replicastore.php
Addition dev note on the explicit return of null instead of false when constant not found.
* Documentation
No
N/A
=> Additional documentation on get_constant return value

dangerfile.js
We currently automatically set the code freeze date displayed in Danger Bot messages, 7 days prior to the milestone's due date.
This holds true for most of the year, but in some scenarios we deviate from this one-week beta period standard.
When that's the case, we can define a code freeze date in the milestone description (using ISO 8601), and we'll now try to pick this up with Danger.
If no date has been provided there, we'll fallback to the previous behaviour.
* p1603982867285900-slack-CBG1CP4EN?thread_ts=1603977448.274600&cid=CBG1CP4EN
* No
* I've added the 9.1 milestone to this PR, so when Danger comes around, the code freeze should be set to October 26 instead of the default November 3.
* N/A
=> Danger Bot: use code freeze date provided in milestone description

packages/autoloader/src/CustomAutoloaderPlugin.php
* The autoloader will now try to reuse the random suffix, instead of trying to generate a new one each time. This may help avoid issues when deploying new code.
* In order, it will prefer an autoloader suffix configured in composer.json, an existing Jetpack Autoloader suffix, or an existing Composer autoloader suffix. See commit message on 49c8fce for additional context.
p1601923798428600-slack-CBG1CP4EN
No.
Test 1:
1. You probably have an existing vendor directory with `vendor/autoload_packages.php` already existing (if not, `composer install` should create one; ideally do this on master before checking out this patch). Make note of the suffix on the namespace line.
2. Run `composer install`.
3. Check that `vendor/autoload_packages.php` has not changed.
Test 2:
1. Remove …
=> Autoloader: Reuse an existing autoloader suffix if available

packages/sync/src/class-replicastore.php
Alignment of ReplicaStore with WP.com implementation. A Replica Store can be hosted on another server that does not have access to the same themes/plugins. Therefore it is needed to call ensure_taxonomies so that the Taxonomy is registered before attempting to retrieve terms.
N/A - Cleanup of technical debt.
NO
* $store = new \Automattic\Jetpack\Sync\Replicastore();
* $store->get_terms( $taxonomy_slug );
* Verify terms are returned.
=> Update get_terms to utilize ensure_taxonomy so that the Taxonomy is registered.

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-resolve-redirect.php, extensions/shared/test-embed-url.js
While testing on a local dev site I noticed that the resolve-redirect
API call was being 301 redirected and would then fail as the `//` in the
URL parameter was being switched to a single `/`.
After a lot of debugging, I discovered that it was Cloudflare that was
seeing a URL like
`https://test.com/wp-json/wpcom/v2/resolve-redirect/https://calendly.com`
as invalid, and redirecting to a sanitised version.
The solution was to make the URL parameter in the path optional, so that
it could be passed as a query parameter.
This change implements that so the old style of calling the endpoint will still work, but also we can swap to using a more
conventional URL format.
N/A
* If testing on WPCOM, sandbox the API
* Insert a calendly block
* Add a URL like https://calendly.com/paul-bunkham
* Click …
=> Test Embed API: Update resolve-redirect route

packages/sync/src/class-replicastore.php, packages/sync/src/interface-replicastore.php
During a Full Sync the taxonomy is not available and causes ensure_taxonomy to fail. This update makes a call to get_term_by when term_taxonomy_id is provided during Full Syncs.
* N/A - Cleanup of technical debt.
* NO
* Obtain the term_taxonomy_id for a term on your site
* $store = new \Automattic\Jetpack\Sync\Replicastore();
* `$store->get_term( null, $term_taxonomy_id, "term_taxonomy_id" );
* Verify term is returned.
=> Update get_term Replicastore function to handle term_taxonomy_id option

tests/e2e/lib/pages/wpcom/pick-a-plan.js
Fixes https://github.com/Automattic/wp-calypso/pull/47015
cc @monsieur-z 
* update locators for a Calypso pricing page
n/a
n/a
* Make sure the E2E tests in GH actions are green now
*
* n/a
=> E2E Tests: Fix calypso plans page locators
