Automattic/jetpack

class.jetpack-options.php
class.json-api-endpoints.php
json-endpoints.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php
json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php
modules/custom-css/custom-css.php
modules/sharedaddy/sharing.js

I have tested the changes, and everything seems to be in order, except I have added one fallback to the old code to avoid a fatal error.
@lancewillett @justinshreve @blowery @enejb @jkudish @aduth can you please see if all the code here is as intended? Thanks!

Merges changes from SVN as of 19th of December, 2014

---

modules/custom-post-types/nova.php
modules/custom-post-types/portfolios.php
modules/custom-post-types/testimonial.php

Fixes #1449
Before we were only including the "Comics" CPT to Omnisearch.  This adds the rest. (Portfolio, Nova, and Testimonials)

Add all Custom Post Types to Omnisearch 

---

functions.gallery.php
modules/widgets/gallery.php
modules/widgets/gallery/js/admin.js

fixes #1440 
the Gallery admin.js script needed to be enqueued where the customizer can read it

Gallery Widget - Upload images from the customizer

---

modules/publicize/ui.php

See http://www.wpbeginner.com/opinion/is-jetpack-misusing-your-brand-to-promote-wordpress-com/#comment-1772809108

Publicize: update connection confirmation message

---

locales.php

Merges the latest version of both classes from the Glotpress repository.
Adds a couple of locales and locale attributes, removes undefined and empty locale attributes, corrects capitalisation.

Update GP_Locales and GP_Locale classes

---

modules/contact-form/admin.php

Contact Form: Use the predefined $title variable in the anchor tag in the button on admin

---

modules/infinite-scroll/infinity.css
modules/infinite-scroll/infinity.js

This will allow to focus on the "Older posts" button and trigger it with the keyboard, for example. Fixes #1205

Adds a `button` wrapper for the infinity handle.

---

class.media-summary.php
modules/likes.php
modules/sharedaddy/sharing.css
modules/shortcodes/flickr.php
modules/shortcodes/soundcloud.php
modules/shortcodes/vimeo.php
modules/tiled-gallery/tiled-gallery.php
modules/widgets/gallery.php

Wpcom merge 21jan2015

---

modules/carousel/jetpack-carousel.css
modules/carousel/rtl/jetpack-carousel-rtl.css

Fixes #1537 
This fixes the font weight values for Carousel comments

Fix font weights in Carousel comments

---

modules/videopress.php

VideoPress: DNS prefetch for the VideoPress domain

---

modules/subscriptions.php

Fix some overlying issues from the recently merged subscriptions subscribers shortcode and remove a parameter from and old version of the plugin.

Subscription fixes

---

modules/sharedaddy/sharing-sources.php
modules/sharedaddy/sharing.js

Sharing: add sharing count to pinterest unofficial buttons

---

class.jetpack-user-agent.php

Taking a stab at fixing #1515 with this, not sure if this is all the rule that's required.

Add Galaxy Tablet as tablet device instead of mobile

---

modules/sharedaddy/sharing-service.php

Hide sharing buttons for private posts

---

modules/theme-tools/site-breadcrumbs.php

Site Breadcrumbs: add from Dotcom

---

modules/sharedaddy/sharing-service.php

Reverts Automattic/jetpack#1540

Revert "Add trailing slash to share URL (for counting purposes only)"

---

modules/custom-css/custom-css.php

Custom CSS: Maybe inline css if it's short?

---

modules/theme-tools/site-logo/inc/functions.php

Adding itemprops for site logo to support Organization schema. Related to #1608

Adding itemprops to support logo schema.

---

modules/protect.php

Per a conversation with @georgestephanis - we'll whitelist successful logins and add a comment to their entry
https://jetpackp2.wordpress.com/2015/02/16/calypso-pr-ready-for-some-testing/#comment-13873

Protect Module: add successful logins to the IP Address whitelist

---

class.jetpack-post-images.php

Add support for site icon to be used in place of blavatar

---

class.jetpack.php
tests/test_class.jetpack.php

Deprecate Jetpack::options methods.

---

modules/related-posts/jetpack-related-posts.php

Props francogilio and expandedfronts.
See:
https://wordpress.org/support/topic/related-posts-php-notice-undefined-index

Related Posts: Add more strict checking to prevent PHP Notices

---

modules/contact-form/grunion-omnisearch.php
modules/omnisearch/omnisearch-posts.php

Omnisearch: Add post_type_obj to array of compatible fields for WP_List_Table

---

modules/manage.php

Sync: Jeptack Options when Manage module is active

---

class.jetpack.php

Updates to the banner so that they work with the new Manage Module.

Manage Banner: Updated to work with the new manage module.

---

modules/shortcodes/vimeo.php

Adds inline documentation for all hooks in vimeo.php. Also serving as a demonstration PR for an upcoming project by the Jetpack Happiness crew. :smile:

Shortcodes: Add inline docs for hooks in vimeo.php

---

class.jetpack-sync.php
modules/manage.php

- Added syncing of constant 'EMPTY_TRASH_DAYS'
- Added syncing of whether the the site is a single user site.

Jetpack Manage: Sync more mock options and constants.

---

modules/shortcodes/youtube.php

Width and Height filters.
Props Aurora.

Shortcodes: Add inline documentation for YouTube player

---

modules/shortcodes.php

Document the jetpack_shortcodes_to_include filter.

Shortcodes: Add filter documentation to shortcodes.php

---

_inc/lib/admin-pages/class.jetpack-admin-page.php
_inc/lib/admin-pages/class.jetpack-landing-page.php
_inc/lib/admin-pages/class.jetpack-settings-page.php
class.jetpack.php

* Documents all hooks in _inc/lib/admin-pages/*
* Documents `jetpack_admin_menu` generally.

Adds inline documentation to hooks in _inc/lib/admin-pages/*

---

modules/shortcodes/slideshow.php

`jetpack_slideshow_slide_caption`
`jetpack_js_slideshow_settings`

Shortcodes: add inline docs to Slideshows

---

modules/after-the-deadline/proxy.php

Add inline docs for the 4 hooks in proxy.php to set the timeout, change service domain, and act when an HTTP error is encountered.

Document hooks in modules/after-the-deadline/proxy.php

---

modules/after-the-deadline.php

Document hook to load AtD scripts.

After the Deadline: Add docs to hook atd_load_scripts

---

modules/protect.php

Document `jpp_log_failed_attempt` action
Document `jpp_kill_login` action

Protect: Add documentation for actions

---

modules/widgets.php

Document `jetpack_widgets_to_include` filter

Extra Sidebar Widgets: Add documenation for hooks

---

modules/custom-post-types/nova.php

Document the hook to enable Nova CPT

Add inline docs to Nova CPT

---

modules/shortcodes/instagram.php

`instagram_cache_oembed_api_response_body` filter

Shortcodes: add inline docs for Instagram shortcode

---

modules/custom-post-types/comics.php
modules/custom-post-types/portfolios.php
modules/custom-post-types/testimonial.php

Documented all of the hooks in Comics, Portfolios, and Testimonials CPTs

Document the hooks in CPTs

---

modules/comments/base.php
modules/comments/comments.php

Document `comment_cookie_lifetime` filter
Document `jetpack_comments_loaded` action
Document `jetpack_must_log_in_to_comment` filter
Document `jetpack_comment_form_prompt_reply` filter

Jetpack Comments: Add Inline Documentation

---

class.jetpack.php

is_single_user_site should be returning false if there is more then 1 user and true if there is only one.

Bug fix: is_single_user_site returned the wrong value.

---

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php

Add POST /sites/%s/sync endpoint. Schedules a full sync. cc @enejb

JSON API: Add Sync Endpoint

---

class.jetpack-sync.php
class.jetpack.php
modules/manage.php

Manage: Always Sync Jetpack_Options

---

class.photon.php

Support Rocket Lazy Load

---

modules/contact-form/grunion-contact-form.php

Meant to replace #1626 in providing some sort of notification for bad emails.  
Will alert() a user on post save, update, or publish if they have an invalid email as a recipient of the contact form.  
enhances #1619 for issue #1610

Contact Form: Alert for bad emails on post save, update, or publish 

---

class.jetpack-sync.php

just before calling the sync function we make sure we capture all the options that are supposed to be synced.

Plugin Sync: By adding all the options to be synced

---

modules/widgets/rsslinks-widget.php

See https://github.com/Automattic/jetpack/pull/1634#discussion_r26302551

Remove unnecessary has_filter check

---

class.jetpack.php

Typo - We should have been calling update_option.
There error reported was created by passing in a string instead of an array.
Fixed #1772.

Bug fix: We are calling the wrong function.

---

modules/contact-form.php

Sync 'feedback' CPT when "Contact Form" is active.

Contact Form: Sync `feedback` CPT

---

class.jetpack.php
modules/stats.php

Enqueue "underscore" script

---

views/admin/admin-page.php

Adds another conditional to hide jump start if in dev mode.

Jump Start: Hide jump start completely in dev mode

---

class.jetpack.php

Make sure to only try to activate Jetpack Manage module on init or after. So that we don't get the fetal error.

Bug Fix: Only activate Jetpack manage after init.

---

views/admin/admin-page.php

Hardcoded module number FTL.  Find the difference of recommended and available instead.
Related: #1787

Landing Page: Don't hardcode numbers

---

class.jetpack-network.php

If we are in dev mode, just show the notice and bail

---

modules/protect.php

Protect: Import BruteProtect's blocked login number immediately on activation of Protect module

---

modules/custom-css/custom-css.php

Custom-css: Add missing isset call for restore css revision action

---

modules/custom-css/custom-css.php

Add warning below CSS support noting theme changes reset CSS

---

modules/protect/math-fallback.php

Fixes #1856
Seems like a super edge case, but this should take care of the notices anyway.  cc @samhotchkiss

Protect: Resolve PHP unindexed notices for Math Fallback

---

modules/site-icon/jetpack-site-icon.php

fixes: #1858
Use the correct function to get the RSS blog url from within a printed string.

Site Icon: Don't break RSS feed

---

modules/widgets/contact-info.php

Copy of #1814 after rebasing against 3.4.1. Fixes #1813

Contact Info Widget: Change class name to prevent conflict

---

modules/infinite-scroll/infinity.php
tests/modules/infinite-scroll/test_class.infinite-scroll.php

Fix body class when Infinite Scroll type is set to 'click'

---

modules/widgets/gallery.php
modules/widgets/gallery/js/admin.js

- parse defaults into `widget` method to fix undefined index notices.
- trigger change when adding gallery to reload customizer. fixes #1970

Gallery Widget:

---

modules/protect.php

Always allow logins from private IPs

---

class.json-api-endpoints.php
json-endpoints/class.wpcom-json-api-update-comment-endpoint.php

@scruffian, @stephanethomas, @dmsnell could you be so kind and review the changes from your commits and see if they are OK?

WPCOM Merge: This merges wpcom changes as of 16th of April, 2015

---

class.jetpack.php
tests/test_class.jetpack.php

Fix: Don't enqueue frontend styles until connected

---

class.jetpack.php

Remove error if domain is period-free.  This PR replaces #1993 and fixes #1918

Account for localhost as domain

---

modules/widgets/rsslinks-widget.php

Fixes #1757
Set the defaults for the widget fields.  Added `default()` method that returns values.  
Aslo adds a bunch of whitespace.  
For easy review, just look at 5d1c984

Fix: RSS Links widget PHP notices

---

json-endpoints/class.wpcom-json-api-list-media-v1-1-endpoint.php
modules/protect.php

Add checks for list media endpoint callback arguments

---

modules/custom-post-types/css/testimonial-shortcode.css
modules/custom-post-types/testimonial.php

Brings the testimonials file in sync with wpcom.  
Created in it's own branch so that we can easily test with themes 
Note: No new functionality was introduced 
cc @michaeldcain

Merge wpcom testimonials 5/5/15

---

_inc/lib/icalendar-reader.php
json-api-config.php
json-endpoints.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php
json-endpoints/class.wpcom-json-api-list-comments-endpoint.php
json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
locales.php
modules/carousel/rtl/jetpack-carousel-rtl.css
modules/custom-post-types/testimonial.php
modules/infinite-scroll/infinity.js
modules/publicize/publicize.php
modules/shortcodes/dailymotion.php
modules/shortcodes/facebook.php
modules/shortcodes/instagram.php
modules/shortcodes/js/slideshow-shortcode.js
modules/widgets/gallery/js/admin.js
modules/widgets/top-posts.php

Clean up unnecessary REST API tests
Update GlotPress - more languages 
New Dailymotion shortcode

Merge wpcom/11may2015

---

modules/shortcodes/mesh.php

Create Mesh oembed for Jetpack.
From r117966-wpcom

Add Mesh oembed to Jetpack

---

locales.php

Added Facbook language support for English Australian and English Canadian 
fixes #2089

Fix for missing Facebook button certain languages

---

modules/publicize/publicize.php
modules/sharedaddy/sharing-service.php
modules/sharedaddy/sharing-sources.php
modules/sharedaddy/sharing.js

This branch will let us sync the code from Jetpack back to wpcom when this is merged to `master`.

Sharing: completes one of two needed code merges to bring the code in sync with wpcom.

---

class.json-api-endpoints.php
functions.opengraph.php
modules/custom-post-types/css/nova-font.css
modules/custom-post-types/nova.php
modules/shortcodes/js/facebook.js

REST API: fixes a bug which prevented pages from being queried via the REST API as an unauthenticated user.
Open Graph: Fix a bug where facebook was showing old blavatar image
Facebook Embeds: Fix async initialization after SDK loaded
Nova Content Type: fix minor glitches with icons and dashboard links.

Merge wpcom/18may2015

---

modules/protect/config-ui.php

Changed the text near the whitelist form to help users understand a bit more about how IP addresses work and that removing the IP from the list does remove it from being whitelisted
fixes #2030

updated the whitelist configuration content

---

modules/omnisearch/omnisearch-posts.php

https://wordpress.org/support/topic/omnisearch-add-custom-post-types?replies=14&view=all#post-6865563

Omnisearch: add a link to edit to post title on the results page

---

modules/custom-post-types/nova.php

Some locales (like Russian) will use the singular form for numbers that are not 1.
props zinigor
Merges r118303-wpcom.

Nova: Use a placeholder for the singular form in_n().

---

readme.txt

Readme: reduce the number of tags displayed on the plugin page.

---

modules/protect.php
modules/protect/shared-functions.php

I'm trying to check if an IP has already been whitelisted in the Jetpack CLI #2168.  This will allow us to use the method to check if the IP is already within a range.  
cc @roccotripaldi

Protect: make ip_address_is_in_range() a shared function

---

modules/sso.php

SSO: Update URL to WP.com 2fa

---

_inc/jp.js

Don't hide/timeout error notices.

---

Gruntfile.js
modules/theme-tools/compat/twentyfifteen-rtl.css
modules/theme-tools/compat/twentyfifteen.css
modules/theme-tools/responsive-videos.php
modules/theme-tools/responsive-videos/responsive-videos.css

Fixes #2185
Also removes CSS from Twenty Fifteen's compat file

Responsive Videos: add CSS to ensure compatibility with all themes

---

_inc/lib/admin-pages/class.jetpack-landing-page.php
class.jetpack-modules-list-table.php

Possible solution for #2189 
This adds filters to the `js_templates` callback values, to allow other developers to override them.

Add filters to the `js_templates` callback values

---

Gruntfile.js
modules/module-info.php
modules/widgets/social-media-icons.php
modules/widgets/social-media-icons/style.css

Initial commit to Jetpack, Ported over from wpcom.
(plus an additional commit to another file to add it to our module description, which is not synced)
Fixes #2019
Will replace PR #2129

Widgets: Add Social Media Icons Widget

---

class.jetpack.php

The wp_style_add_data wasn't being used correctly creating a improperly built css file name
fixes #2125

fix a bug where the a non existing RTL css file was being referenced

---

modules/minileven/theme/pub/minileven/footer.php

https://github.com/Automattic/jetpack/issues/2105

Minileven: add hook before footer

---

class.jetpack-heartbeat.php
class.jetpack.php

Start collecting data about single user sites.

Add Is Single User Site to hearbeat

---

modules/shortcodes/js/slideshow-shortcode.js
modules/shortcodes/slideshow.php

Replay of #2198
> Add autostart="false"` to [gallery] tag to pause on start.
>
> In opposite to #558 @lancewillett's statement, in my opinion it is MUST HAVE. For me, this slideshow without it is just useless.

Slideshow: Autostart control

---

modules/stats.php

We should have inline documentation for functions.

Document stats_get_csv function

---

modules/shortcodes/mixcloud.php

Mixcloud: handle accented characters in URLs

---

modules/custom-css/custom-css/preprocessors/lessc.inc.php

Updates LESS to current latest. Redo of #1775 with LESS code copied from https://raw.githubusercontent.com/leafo/lessphp/0f5a7f5545d2bcf4e9fad9a228c8ad89cc9aa283/lessc.inc.php (tagged 0.5.0 commit)

Custom CSS: Update LESS to 0.5.0

---

class.jetpack.php

This filter allows overriding any info about Jetpack modules.

Add in a filter to let folks modify module info on the fly.

---

class.jetpack-twitter-cards.php

Set a Twitter card image URL using `twitter:image` instead of the `twitter:image:src` structured property.

use twitter:image instead of twitter:image:src

---

modules/protect.php
modules/protect/shared-functions.php

Locally, so that we're caching blocks properly

Learn trusted headers

---

modules/widgets/top-posts.php

Another attempt at fixing #54 and #943
I would appreciate a review of my changes, especially the data validation part, as I've struggled a bit with it.
Thanks!

Top Posts Widget: add a new option to choose what Post Types to display

---

modules/widgets/wordpress-post-widget.php

Display WordPress Posts Widget: Add new option to open links in a new tab

---

class.jetpack-client-server.php
tests/test_class.jetpack-client-server.php

Here's a proposal for modifying the Jetpack_Client_Server class so that it can be unit tested. Does this seem reasonable?

Modify Jetpack_Client_Server to support unit testing, add some tests.

---

modules/protect.php
modules/protect/math-fallback.php
to-test.txt

Instead of the hard block.  Thoroughly tested, should be good to merge

When status is "blocked," use a captcha

---

tools/deploy-to-svn.sh
tools/export-translations.php

But delete them when moving to SVN.

Keep the PO files in Git

---

class.jetpack-cli.php

Makes it easier on the translators

Jetpack CLI: make translated strings more readable for translators

---

_inc/lib/markdown/extra.php
_inc/lib/markdown/gfm.php
class.jetpack-ixr-client.php
class.jetpack-signature.php
class.jetpack-user-agent.php
class.jetpack.php
modules/custom-css/custom-css.php
modules/notes.php
modules/sharedaddy/sharing-service.php
modules/subscriptions.php
modules/widgets/gallery.php
modules/widgets/rsslinks-widget.php

Change from old php4 style constructor.

---

modules/carousel/jetpack-carousel.php

Carousel: update bail wording to use module instead of plugin.

---

class.jetpack.php

Some languages translate these differently based on who the message is targeted to
See <a href="https://a8c.slack.com/archives/i18n/p1436287414000631">this slack convo</a> for more info

Create two distinct strings as the success message (changing primary)

---

modules/widgets/gallery.php

Also the slideshow will now autoplay by default again.
PR #2201 did not account for the param when using the widget slideshow

Fixes warning when using gallery widget in slideshow mode

---

class.jetpack.php

And a link to submit feedback. 
Looks like this: 
https://cloudup.com/cegNxyLFtd8
Kinda boring, but thought I'd start up the discussion on how we want to do this here.

Development Version: throw notice when using dev version

---

modules/protect/math-fallback.php

Protect: return a 401 error code when failing the math fallback

---

readme.txt

Featured images first, to match the release post.  
Up for discussion.

Better organized 3.6 changelog 

---

_inc/footer.php

Show "Debug" link in footer to admins only

---

_inc/jetpack-modules.js

Admin: Stop scrolling to top when closing module description modal

---

modules/module-info.php

Originally reported by @jenial

Protect: update wording for module description

---

modules/notes.php

Notes: Load v1.1 notifications client

---

functions.opengraph.php

filter og:title and og:description so they get smart punctuation

---

class.jetpack-sync.php

Attempt to reduce SQL queries.  I don't fully understand the flow here so have tried to keep this as simple as possible.

Don't fire clean_post_cache on the same post multiple times

---

class.json-api-endpoints.php

Fix 2356 : Check height width in json before adding it to response

---

functions.gallery.php
modules/videopress/videopress.php

Added do_action info for modules/videopress/videopress.php

Added Inline Docs for Videopress.php

---

class.jetpack-user-agent.php

Was reviewing some old issues related to Jetpack troubleshooting an issue. I came across issue #1402
While its great the filter was added, I thought it would still be good to update the list, so I thought I would submit a pull request for it, since it never got added.

Updated Bot List

---

modules/sharedaddy/sharing-sources.php

Fixes #2481. Param was found here: https://www.reddit.com/static/button/button-embed.js

Open official Reddit button link in new tab

---

modules/widgets/social-media-icons.php

These 2 actions would make it a lot easier for folks wanting to add support for custom services, like in #2366.

Social Media Widget: add actions before and after the list

---

functions.opengraph.php
modules/theme-tools/site-logo/inc/functions.php

Part 2 of #2291
See #2283 for more discussion about this
Fixes #2104

Open Graph: add image:width and image:height tags to fallback images

---

modules/shortcodes/youtube.php

`autohide` accepts 3 parameters: `2` is the default, `0` and `1` are 2 other accepted values:
https://developers.google.com/youtube/player_parameters?hl=en#autohide
https://wordpress.org/support/topic/youtube-shortcode-autohide-player-controls

Shortcodes: Add autohide parameter to the YouTube shortcode.

---

modules/protect/transient-cleanup.php

No reason to hang on to expired transients for a week...

Change time limit for protect transient cleanup

---

modules/infinite-scroll/infinity.php

Infinite Scroll: add translation function to credit line.

---

json-endpoints.php
json-endpoints/class.wpcom-json-api-site-user-endpoint.php

Add endpoint to GET and UPDATE a user from a site.
GET/POST /sites/%s/users/%d

REST API: Add site user endpoint

---

modules/likes.php

Likes: Delete the Email notification option when Likes get deactivated.

---

modules/shortcodes/soundcloud.php

Update to soundcloud.php to accept percent for dimensions (#2445)

Fix soundcloud.php to accept percent for dimensions (#2445)

---

class.json-api-endpoints.php
json-endpoints.php
json-endpoints/class.wpcom-json-api-autosave-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-get-post-counts-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php
json-endpoints/class.wpcom-json-api-list-invites-endpoint.php
json-endpoints/class.wpcom-json-api-list-media-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-list-roles-endpoint.php
json-endpoints/class.wpcom-json-api-list-users-endpoint.php
json-endpoints/class.wpcom-json-api-post-endpoint.php
json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
json-endpoints/class.wpcom-json-api-update-media-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php

Could you review your changes?
Please check your name if they are good to go on 3.7 :)

Merge wpcom API changes

---

class.jetpack.php
scss/organisms/_banners.scss

Updating the display of ID crisis cta banners. I’ve added some new css,
as well as some simple markup to make styling these banners easier.

CTA Banner Styles

---

modules/module-info.php

Manage: Add Themes and Menus to module info

---

views/admin/my-jetpack-page.php

Translate Confirm Disconnect button

---

class.jetpack.php

There are some network settings that would are useful for us to know in
order to prevent some common user errors and provide a better UI when
managing sites that are part of a network.
Data gets synced every time network settings get updated and daily. 
In order for the network settings to get synced on update the user has to to have the main network site jetpack connected or have Jetpack network activated. 
Data that we are syncing.
network name, network_allow_new_registrations, add_new_users (bool), site_upload_space, upload_filetypes, fileupload_maxk and menu_items.

Sync Network Data

---

to-test.txt

Not to merge until everything before the beta gets in and accounted for.

3.7 testing list

---

modules/related-posts/jetpack-related-posts.php

You should be able to use the filter when using the raw class as well.
cc @xyu

Related Posts: apply jetpack_relatedposts_filter_hits to raw class

---

class.media-summary.php

Fix 1302 Sharing: Added dailymotion screenshots to Open Graph meta tags

---

json-endpoints/class.wpcom-json-api-update-post-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php

Improves on #2393.
cc @dereksmart

JSON API: set default for each input variable to avoid notices

---

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
modules/after-the-deadline.php
modules/custom-post-types/testimonial.php
modules/publicize.php

General: avoid Fatal Errors when bump_stats_extras doesn't exist

---

to-test.txt

@samhotchkiss @zinigor Let's do it!

3.7 Beta: Update to-test.txt pre-beta 3

---

class.jetpack.php

This way we're respecting multisite's sub-site-override option as well.  
related #2643

IDC notice - respect multisite settings

---

class.jetpack-cli.php
modules/module-info.php

This to address [Jenia's comments regarding Jetpack 3.7](https://i18n.wordpress.com/2015/08/21/jetpack-3-7-is-ready-for/#comment-9760).

Improve translatable strings

---

class.jetpack.php
modules/shortcodes/recipe.php

In certain places numbered placeholders were used without a dollar sign, this PR fixes those omissions.

I18n: fixes numbered placeholders

---

class.jetpack.php
modules/module-info.php

I18n: fixes numbered placeholders, take 2

---

class.jetpack.php

Enable the IDC notice regardless of dev version or not.

IDC: remove check for dev version 

---

modules/custom-post-types/nova.php
modules/custom-post-types/portfolios.php
modules/custom-post-types/testimonial.php
modules/theme-tools/site-logo.php

This avoids errors with Plugin Language Packs.

i18n: remove extra text domains

---

class.jetpack.php

IDC: Correct placeholder

---

class.jetpack.php

Fix potential fatal error syncing form frontend

---

modules/likes.php

Likes: Show label in screen hides for hiding Likes column in list tables

---

modules/subscriptions.php

Introduce subscription success message to the joys of closing punctuation.

Subscription Success Punctuation

---

class.jetpack-network.php

Check for dev mode, return early if true

---

modules/module-headings.php
modules/module-info.php
modules/verification-tools.php
modules/verification-tools/blog-verification-tools.php

Replace mentions of Google Webmaster Tools with Google Search Console

---

json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php

```
[27-Sep-2015 15:09:44 UTC] PHP Notice:  Undefined index: status in wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php on line 90
[27-Sep-2015 15:09:44 UTC] PHP Notice:  Undefined index: status in wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php on line 94
```

JSON API: fix errors when publishing a post from the wpcom editor.

---

class.jetpack-client-server.php
class.jetpack-debugger.php
class.jetpack-ixr-client.php
class.jetpack-post-images.php
class.jetpack-sync.php
class.jetpack-user-agent.php
class.jetpack-xmlrpc-server.php
class.jetpack.php
class.json-api-endpoints.php
modules/stats.php
modules/theme-tools/infinite-scroll.php
modules/tiled-gallery/tiled-gallery.php
require-lib.php

I started reviewing files and removing unused code here and there in the plugin. I'll continue to do so over the next few weeks, but I thought I'd already submitted what I have done so far, to avoid having only one huge Pull Request, that would be harder to review.

Remove unused code, round 1

---

class.jetpack.php

Include domain name in IDC messaging to make it more clear

---

modules/custom-css/custom-css.php
modules/sharedaddy/sharing-service.php

+ add missing param for an existing filter in modules/sharedaddy/sharing-service.php

Custom CSS: add inline docs.

---

modules/contact-form/grunion-contact-form.php

POST takes precedence over GET variables, and both methods over user data in the case the user is logged in. For #2554

Contact Form: allow pre-filling form fields with URL parameters

---

modules/carousel/jetpack-carousel.js

For #2703. I've made some test and seems like with this patch, the functionality of browser buttons is normal interacting with the galleries.

Carousel: fix browser back/forward button behavior.

---

modules/shortcodes/vimeo.php
modules/shortcodes/youtube.php

Prefer HTTPS for video embeds to avoid mixed content warnings

---

modules/contact-form/grunion-contact-form.php
modules/contact-form/grunion-form-view.php
modules/contact-form/js/grunion.js

This is an updated and locally-branched version of @iandunn's #602
I added the functionality to allow field values to be arrays, which was the only real hurdle in getting this up to date.  
I think this is a great addition to the contact forms.  
replaces #602

Contact Form: Introduce checkbox-multiple field type.

---

_inc/jetpack-modules.js
_inc/jp.js

I thought we had already fixed this, but alas...

Prevent scrolling of body when module modals are opened

---

class.jetpack-jitm.php

@richardmuscat and I want to test if a new message will increase activations of Photon from the just-in-time-message.

Updated the Photon JITM message to test for better results

---

modules/shortcodes/twitchtv.php

Add twitch.tv shortcode from wpcom

---

class.jetpack-autoupdate.php

Tracking sucessful autoupdates will give us a more complete data set.
Testing instructions to follow.

Autoupdates: also track sucessful autoupdates

---

modules/sharedaddy/sharedaddy.php

Sharing: Add filter to choose if sharing meta box should be shown.

---

to-test.txt

Update to-test for 3.8 beta-1

---

class.jetpack.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php

Syncing a max_upload_size option and exposing it on the /sites/$site endpoint.
cc: @enejb @lezama

JSON API: max_upload_size option

---

modules/manage/activate-admin.php
modules/manage/confirm-admin.php

Currently the links don't take you where you think they are going to take you. 
this PR fixes that.

Manage: fix links on manage confirm page

---

_inc/jetpack-jitm.js
class.jetpack-jitm.php
scss/jetpack-admin-jitm.scss

The button wasn’t being tracked in MC previously, it is now
Also the button would disappear after being clicked, this has been fixed

Added tracking and fixed a bug on the WP.com tools button

---

class.photon.php

Photon: Update filter after r35419-core

---

modules/custom-post-types/testimonial.php
modules/manage/activate-admin.php
modules/manage/confirm-admin.php

Aside from a couple of fixed typos, I have done one small refactoring, reducing the assigment of the same string 6x to once.

Fix typos introduced in 3.8b2

---

modules/custom-post-types/portfolios.php
modules/custom-post-types/testimonial.php

Don't use `the_{content/excerpt}()` inside another `echo`.

---

modules/subscriptions.php

Subscription Widget: remove extra PHP closing tag

---

modules/protect.php

Don't show the learn more link over XMLRPC

---

modules/shortcodes/polldaddy.php

Fixes #2874
I was able to reproduce the issue using type "slider" attribute on the shortcode.

Fix undefined notice on polldaddy shortcut.

---

readme.txt

Readme: update contributor list

---

modules/wpgroho.js

Check if Gravatar js object is available.

---

class.jetpack.php

Fixes #2274 
I think they only need to be removed, right? No manipulation there.

Remove unneeded translation functions.

---

modules/markdown/easy-markdown.php

This commit resolves issue #636.

Fix Markdown Quick Edit Bug

---

readme.txt

Let us not live in the past. Merging right away, PRing it for the sake of notifications and transparency.

Update readme.txt to stable 3.8

---

class.jetpack-autoupdate.php
json-endpoints/jetpack/class.jetpack-json-api-maybe-auto-update-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php

Add a new Maybe Auto Update API Endpoint that will allows us to trigger any autoupdates right away. 
As opposed to wait for the scheduled time at which they are happening.

JSON API: Add maybe auto-update-api-endpoint

---

json-endpoints/jetpack/class.jetpack-json-api-plugins-install-endpoint.php

Allows us to capture the that the site doesn’t have proper file system access.
Another note: I also tried to capture the settings link here but it didn't work as expected. 
To test:
1. test that the install works as expected. 
2. Put your site into mode where the site needs would request the FPT form ( You need to add `define( 'FS_METHOD', 'ssh2' )` to your wp-config.php for example. 
The expected result of the API is now install_error_fs_unavailable
3. Test that the site returns 'install_error_package_not_available' for a plugin that is not in .org
4. Test that the site return 'install_error_folder_exists' if you are trying to install a plugin that has the the same fodler as a private plugin
5. Test that the site returns 'install_error_filesystem_full' if site doesn't have enough space …

Plugins API: improved errors

---

class.jetpack.php

Fix undefined function error when parsing plugin data

---

class.jetpack-heartbeat.php

Would be interesting data to see overtime.

Heartbeat: Add return for if a site is_ssl or not.

---

modules/theme-tools/compat/twentysixteen-rtl.css
modules/theme-tools/compat/twentysixteen.css
modules/theme-tools/compat/twentysixteen.php

In this change, I refined some styles (mainly Related Posts and Sharing) and fixed some visual bugs I didn't catch in the first PR.
Also I've added a missing space pointed in https://github.com/Automattic/jetpack/pull/2970#discussion_r44786325.

Visual Refinements for Twenty Sixteen

---

modules/widget-visibility/widget-conditions.php

Please check if this is really a taxonomy name that would be replaced here.

Improve translator comment about a taxonomy name

---

modules/contact-form/admin.php

Contact Form: Fix Notices thrown on `admin_init` hook.

---

class.jetpack.php

oEmbeds: Add support for gfycat.com.

---

_inc/jetpack-jitm.js
class.jetpack-jitm.php
class.jetpack.php
scss/jetpack-admin-jitm.scss

JITM for Plugins screen is only displayed after a plugin is activated.
JITM for Add New screen is only displayed for posts and pages.

JITMs for Plugins and Add New screens

---

json-endpoints/jetpack/class.wpcom-json-api-get-option-endpoint.php
json-endpoints/jetpack/class.wpcom-json-api-update-option-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php

Alternative to https://github.com/Automattic/jetpack/pull/2901

JSON API: Update option endpoint jetpack only

---

_inc/lib/markdown/gfm.php

Props George Stephanis <george@stephanis.info>
https://github.com/Automattic/jetpack/commit/6dbf288
Merges r125033-wpcom.

Pinking Shears.

---

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php

Merges r127710-wpcom.
Actual changes were already committed in #3099

REST API: removing whitespace

---

class.json-api-endpoints.php
json-endpoints/class.wpcom-json-api-get-media-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-list-media-v1-1-endpoint.php

Merges r124933-wpcom and additonal checks added in r127583-wpcom.

REST API: Media: add new filter allowing us to include thumbnail details for WPCOM sites

---

modules/widgets/gravatar-profile.php

Merges r127839-wpcom.
This shouldn't change anything for Jetpack users.

Gravatar Profile: when using Calypso, link to /me for editing your profile rather than linking to wp-admin.

---

modules/custom-post-types/nova.php

Custom Post Types / Menus: do not register CPT and tax if they already exist

---

modules/carousel/jetpack-carousel.php
modules/carousel/rtl/jetpack-carousel-rtl.css

- It shouldn't appear on WordPress.com.
- It should be displayed properly on sites using an rtl language.

Carousel: Update carousel bail message for Jetpack

---

json-endpoints.php

Document endpoints, and update existing documentation

REST API: Users endpoint updates

---

class.json-api-endpoints.php
modules/infinite-scroll/infinity.php
modules/publicize/ui.php
modules/sharedaddy/sharing-service.php
modules/shortcodes/gist.php
modules/shortcodes/slideshow.php
modules/site-icon/jetpack-site-icon.php
modules/stats.php

As reported by @garyjones during translation editing.

Correct Javascript to JavaScript

---

tests/php/test_class.jetpack-heartbeat.php

Some initial tests for the heartbeat class.

Add tests for Jetpack_Heartbeat

---

modules/contact-form/grunion-contact-form.php

Add filter to customize the required field text.

---

tests/qunit/index.html
tests/qunit/modules/shortcodes/slideshow-shortcode.js

Shows how to structure test files when writing tests for modules.
Includes test to verify that after initialization we have a jQuery object and to verify that loading image was append and remove.

Adds QUnit test for slideshow shortcode

---

class.jetpack.php

oEmbeds: add Wistia

---

modules/contact-form/grunion-contact-form.php

Contact Form: check if checkbox-multiple has at least one selection, fixes #3131

---

_inc/jetpack-jitm.js
class.jetpack-jitm.php
class.jetpack.php
scss/jetpack-admin-jitm.scss

- After user publishes a post, a JITM will be displayed:
* if user doesn't have Stats enabled, it will prompt to activate it. Once it's done, it will prompt user to go to WordPress.com
* if user has Stats enabled, it will prompt user to go to WordPress.com
- After user starts uploading an image, a JITM will be displayed:
* if user doesn't have Photon enabled, it will prompt to activate it.

Add JITMs after user publishes a post and when user uploads an image

---

class.json-api-endpoints.php
json-endpoints/jetpack/class.wpcom-json-api-update-option-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php

Handle writing an object as an array.

Options Endpoint: update array values 

---

modules/after-the-deadline/atd.core.js

After The Deadline: Exclude pre tags from spellchecking.

---

modules/after-the-deadline/atd-nonvis-editor-plugin.js

Fixes #3220
Merges r129710-wpcom

After the Deadline: fix replacing emoji with images in the text editor in Chrome

---

class.jetpack-debugger.php

Debug emails: add "BETA" to subject line when running dev version.

---

_inc/lib/tracks/class.tracks-client.php
_inc/lib/tracks/class.tracks-event.php
_inc/lib/tracks/client.php
class.jetpack-tracks.php

Tracks: prefix all functions with jetpack_

---

_inc/lib/tracks/class.tracks-client.php
_inc/lib/tracks/class.tracks-event.php
_inc/lib/tracks/client.php

Tracks: namespace classes to avoid conflicts

---

modules/module-info.php

Fix typo ("accesible" to "accessible")

---

modules/shortcodes/vimeo.php

Mostly proper escaping and pinking shears 
cc @lancewillett

Merge/vimeo-shortcode 

---

modules/videopress/videopress.php

cc @jeherve @kraftbj @eliorivero please review and merge ASAP.

VideoPress: fixed an incorrectly named method.

---

modules/shortcodes/archives.php
modules/shortcodes/flickr.php
modules/shortcodes/instagram.php
modules/shortcodes/presentations.php
modules/shortcodes/scribd.php
modules/shortcodes/slideshare.php
modules/shortcodes/soundcloud.php
modules/shortcodes/ted.php
modules/shortcodes/twitter-timeline.php
modules/shortcodes/upcoming-events.php
modules/shortcodes/wufoo.php
modules/shortcodes/youtube.php

This will bring us up to date with wpcom's files for all shortcodes. 
cc @lancewillett

Dotcom Merge: All Shortcode files

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.svnignore

@see https://github.com/blog/2111-issue-and-pull-request-templates
- Move all templates in `/github` folder
- Add `.github` folder to .svnignore

Contributing guide: add new issue and PR templates

---

modules/shortcodes/instagram.php

Also updates the format of the core provider that is first removed before adding our own.
fixes #3384

Embed handler registered for Instagram now allows www subdomain in URLs

---

class.jetpack.php

Extend `show_development_mode_notice` to show note about staging site.

Staging: Add notice to admin

---

class.json-api-endpoints.php
class.json-api.php
json-endpoints.php
json-endpoints/class.wpcom-json-api-delete-media-endpoint.php
json-endpoints/class.wpcom-json-api-delete-media-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php
json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php
json-endpoints/class.wpcom-json-api-post-endpoint.php
json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-sharing-buttons-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php

This will bring us up to date with all the json-api file changes from dotcom

Merge JSON API all files

---

modules/contact-form/grunion-contact-form.php

- Do not save private site credentials in post meta
- Cleanup existing post metadata on a daily basis

Contact Form: avoid saving private site credentials in post meta

---

readme.txt

* Release date and post link
* Information about 2 security PRs, #3455 and #3456
* Mention of the new Top Posts shortcode added in #3418

Readme: add info about upcoming release

---

json-endpoints/class.wpcom-json-api-get-site-endpoint.php

brings file up to date with wpcom

Merge: API: updates to sites/xxx

---

modules/shortcodes/houzz.php

Shortcodes: add Houzz

---

modules/shortcodes/vimeo.php

This way we don't need to do two regex checks, and dramatically simplifies the callback function.

Vimeo: Simplify the regex checks for embedding vimeos in comments

---

modules/widgets/top-posts.php

Fix @since version in hooks

---

modules/widgets/top-posts.php

See #3477
- Update hook titles to specify the element being used.
- Update parameters to be more specific.

Top Posts Widget: update inline documentation for 2 hooks.

---

modules/carousel/jetpack-carousel.js
modules/shortcodes/js/slideshow-shortcode.js
modules/shortcodes/slideshow.php
modules/tiled-gallery/tiled-gallery/templates/carousel-container.php
modules/tiled-gallery/tiled-gallery/templates/partials/item.php

This PR adds basic schema support to Tiled Galleries and the Carousel
Modules.
Fixes #1750

Schema for Galleries & Carousel

---

modules/subscriptions/subscriptions.css

Fixes #3340  .
- Removed #subscribe-email input padding.

Subscriptions: remove #subscribe-email input padding

---

_inc/lib/tracks/client.php

Finalizes #3446, cc @dereksmart @richardmuscat

General: finalize AJAX tracks by removing debug output.

---

modules/sitemaps/sitemap-xsl.php
modules/sitemaps/sitemaps.php

Sitemaps: use Jetpack_PostImages::get_image to get any image in entry, closes #3333

---

modules/comments/comments.php

This re-PRs #3475 which seems to never have applied, even though it was merged? I'm not sure what happened, but trying again.
Going to merge it myself since the branch was already reviewed and should have been merged. ( cc @zinigor for 3.9.3 inclusion ).

Comments: Always use https for jetpack.wordpress.com

---

class.json-api.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php
sal/class.json-api-site-jetpack.php

Merge from wpcom
Add SAL, Site Abstraction Layer
cc @gravityrail

REST API: Get site endpoint with SAL

---

modules/infinite-scroll/infinity.php

The first part was already merged in #3492, but because it was a rebase and a forced push, it didn't actually make it to `master`.
The second commit is more recent.

Infinite Scroll: Merge from WordPress.com

---

_inc/lib/class.color.php

in accordance with latest WCAG 2.0 standards.
Merges r128444-wpcom.

Custom Colors: update luminance and contrast formulae

---

_inc/jetpack-jitm.js
class.jetpack-jitm.php

JITMs prompting to enable backup are displayed in Updates screen and Post screen after publishing. One prompting to enable spam protection is displayed in Comments screen.

New JITMs prompting user to enable backups and spam protection

---

class.jetpack.php
views/admin/admin-page.php

Adding a `from` parameter to the connection buttons within the plugin helps us identify which "connect" buttons are used the most.

Better tracking of connection buttons

---

modules/contact-form/grunion-contact-form.php

This would break IPv6 addresses, and Akismet can do any necessary sanitization itself.

Don't sanitize REMOTE_ADDR

---

modules/theme-tools/site-breadcrumbs.php

Added schema to Breadcrumbs

---

modules/shortcodes/vimeo.php

Fixes #3615
- change regex so it doesn't attempt to replace numbers in comment with a Vimeo video.
**Convert these cases**
```
Shortcode, ID only
[vimeo 001234]
Shortcode, https URL
[vimeo https://vimeo.com/001234]
Shortcode, http URL
[vimeo http://vimeo.com/001234]
Plain URL
https://vimeo.com/123456
Plain URL, no scheme
vimeo.com/1234
Plain URL, only forward slashes
//vimeo.com/1234
```
**Do NOT convert these**
```
This is a 734 comment, leave the number unchanged
"vimeo.com/1234" don't convert the URL between quotes
Link enclosing text
A <a href="https://vimeo.com/123456" rel="nofollow">Vimeo video link</a>
Link enclosing URL
Another link <a href="https://vimeo.com/123456" rel="nofollow">https://vimeo.com/123456</a>
```

Vimeo: only replace videos in comments if they're a shortcode or a URL

---

modules/widget-visibility/widget-conditions.php

fixes for #80 and #750
replaces #1599

Widget Visibility: support custom post type archive pages #80

---

modules/module-info.php

This module information modal hadn't been updated since we added those modules.

Widgets: add Google+, Contact Info, and Goodreads to the desc modal.

---

class.jetpack-ixr-client.php

See #3056 
While we need to go through and audit everything, if there are multiple people reporting this particular file is being attempted directly, let's shut that down sooner rather than later.

IXR Client: Prevent direct access

---

modules/contact-form/grunion-contact-form.php

See [#](https://github.com/Automattic/jetpack/commit/c96f5aefc7b82d4b1294dfffdfbcd4f466ed5899#commitcomment-16734523)
props: cfinke

Fix contact form cleanup SQL

---

class.jetpack-xmlrpc-server.php

XMLRPC 'verifyAction' method does not need to check for state if the action is
'publicize'. We only need to check for state for 'register' and 'authorize'.
cc @eliorivero

XMLRPC Server

---

scss/templates/_connection-landing.scss
views/admin/admin-page.php

fixed: changed srcsrc values in order to proper render the appropriate images on the right screen sizes. fixed a flex box issues on smaller screens and some padding as well.

Bug: fixing srcset on landing page

---

readme.txt

Merging these early changelogs for now, @jessefriedman will review them before the final version.

Update changelogs for 4.0.0 release

---

modules/videopress/js/editor-view.js
modules/videopress/shortcode.php
modules/videopress/videopress-editor-style.css

Related discussion p1HpG7-37u-p2

Hide the checkboxes for Flash Player and Open Source codecs

---

class.jetpack.php

This is temporary.
Do NOT merge until @jessefriedman confirms it.

Disable all JITMs.

---

readme.txt

Improved changelogs for readability and understanding

---

class.jetpack.php
jetpack.php

Fixes #3697. Work in progress.

Jetpack: move jetpack_require_lib_dir outside of the Jetpack class

---

modules/sso.php

Alternative, and improved, solution to #3731 after some user input in  #2631891-t. Fixes an issue where a user will receive an `-10520: Jetpack: [missing_token]`if the SSO module is turned on and then all Jetpack connections are removed
Because users could, and are, extending SSO for their own uses, we shouldn't automatically die in `Jetpack_SSO::request_initial_nonce` when that method fails.
This refactor should not change any existing functionality, but should make it easier for developers to customize SSO functionality.
Test existence of bug:
- On a site with Jetpack enabled and connected to WP.com, enable SSO.
- Disconnect all Jetpack connections
- Logout
- Go to `/wp-admin`
- Click "Log in with WordPress.com"
- Do you get a `missing_token` error?
Test fix:
- Checkout …

SSO: Refactors functionality to build SSO URL

---

modules/sso.php

Automatically redirect user to connect flow after SSO login if user is not already connected. This PR is one small piece of a larger puzzle that includes the new Calypso connect flow as well as some work on the WPCOM side of SSO.
After thinking about it, and looking at the Calypso side, I think we should handle the auto authorize on the Calypso side. The key here is that we want to make sure the user has taken an action (such as approving SSO) before we auto authorize. If we were to trigger auto authorize by redirecting to Calypso with a query parameter, then we aren't 100% sure of the user's intent.
To test:
- Checkout `update/sso-redirect-to-auth` branch
- Go to `$site/wp-admin` (where `$site` has SSO enabled)
- Click "Log in with WordPress.com" button
- If you haven't previously logged …

SSO: Automatically redirect user to connect flow after SSO if not connected

---

class.jetpack-debugger.php

Fixes #3711 .
- When a user submits a debug request, the form now POSTs to the http**s** version of the site.

Debugger: Secure form submission

---

_inc/client/at-a-glance/protect.jsx

Adds a missing space in the Protect AAG prompt.
Fixes some jslint errors while I'm there.

AAG: Fix Protect link/spacing when module is disabled

---

_inc/jquery.jetpack-resize.js
modules/after-the-deadline/atd-nonvis-editor-plugin.js
modules/after-the-deadline/atd.core.js
modules/after-the-deadline/jquery.atd.js
modules/after-the-deadline/tinymce/editor_plugin.js
modules/likes/queuehandler.js
modules/videopress/js/videopress-admin.js

Introduces small adjustments to JS files so the new, and more strict jshint can better understand the files without throwing warnings.

Tweak JS files so they doesn't show jshint warnings

---

readme.md

Update readme with dev recommended environment and known issues

---

_inc/client/at-a-glance/stats.jsx

Fixes _hopefully_ module resolution in environments where webpack is case sensitive.
- Replaces usage of `'lodash/foreach'` for `'lodash/forEach'`

At A Glance: Update case in lodash/forEach import

---

_inc/client/engagement/index.jsx
_inc/client/more/index.jsx
_inc/client/security/index.jsx
_inc/client/site-health/index.jsx

Fixes warnings in console `Each child in an array or iterator should have a unique "key" prop`. 
- Adds unique key attribute to engagemente, more, site health, and security `<FoldableCards>`s
- Adds unique key attribute to more sections' H1s

Add key attributes with unique values to module FoldableCards

---

_inc/client/main.jsx

Fixes warnings in console about `shouldComponentUpdate` returning undefined
- Adds a `return false` statement for default cases in `Main` component's `shouldComponentUpdate` method

Make Main.shouldComponenUpdate return false by default

---

_inc/client/components/masthead/index.jsx
_inc/client/components/masthead/style.scss

Adding new classes, modding styles, cleaning code spacing. 
Only visual changes: padding adjustments since the "feedback" link was running into the scrollbar on the right side on screens smaller than 1200px

Enhancement: Masthead component styling improvements

---

_inc/client/components/jetpack-connect/index.jsx
_inc/client/components/jetpack-connect/style.scss

Removing srcset size attr cuz they ain't working as intended and I iz mad.

Connection Landing: Adjusting the markup for srcset images

---

.gitignore

Update .gitignore to add _inc/jetpack-strings.php and separated out the things we will need in release branches.

.gitignore: _inc/jetpack-strings.php 

---

_inc/lib/class.core-rest-api-endpoints.php

This allows to create, regenerate or delete the Post by Email address without depending on the methods in the Post by Email class that are suitable for ajax requests.

REST API - Post by Email: new method for endpoint to call WPCOM through authenticated request

---

_inc/client/components/connect-button/index.jsx

Prepares the connect button component for internationalization.
To test:
- Checkout `update/i18n-for-connect-button` branch
- Run `npm run build`
- Run `npm run build-i18n`
- Check `_inc/jetpack-strings.php` to make sure that the strings in the connect button were found.
cc @dereksmart or @beaulebens for review.

Admin Page: Prepare connect button for internationalization

---

_inc/client/components/support-card/style.scss

Fixes: https://github.com/Automattic/jetpack/issues/3954
Before: 
After:

SupportCard: fixing content overrun in IE10

---

.svnignore

Add some files to .svnignore not needed in production 

---

modules/sso.php

Previously, even though we disabled the default login form, it was possible to post a username and password to the login form anyways. This PR fixes that.
To test:
- Checkout `update/sso-disable-login-form-by-post` branch
- Make sure SSO is enabled
- In a compat plugin, `add_filter( 'jetpack_remove_login_form', '__return_true' );`
- Go to `$site/wp-admin`
- You should notice a blue notice with the same wording as in the screenshot below
- Open inspector, and remove the `jetpack-sso-body` class. This should show the default login form.
- Fill out and submit the form
- You should be redirected to the login page and see an error like this:
Note: You may or may not see the gravatar and user name. That would depend on whether you have previously connected your user from the remote site to …

SSO: Disable ability to submit default login form

---

_inc/lib/admin-pages/class.jetpack-react-page.php
views/admin/admin-page.php

Support: update our list of Happiness Engineers

---

modules/widgets/rsslinks-widget.php
views/admin/network-settings.php

This should clarify the use of these words for translators
https://wordpress.org/support/topic/global-keyword-translation?replies=2&view=all

i18n: add context to 2 translations

---

class.jetpack.php

Twitter Cards: ensure tags are only ignored when filter is true

---

changelog.txt
jetpack.php
package.json
readme.txt
to-test.md

Beta Release: prepare for upcoming 4.0.4 Beta

---

changelog.txt
readme.txt
to-test.md

Changes were merged into `branch-4.0` in #4098

4.0.4 Beta: Merge Release Notes to Master as well

---

modules/widgets/contact-info.php

`extract()` usage is deprecated and considered bad practice, according to the Coding Standards - https://make.wordpress.org/core/handbook/coding-standards/php/#dont-extract .
Its usage has been removed from the widget and the code has been updated to work properly with `$args`.

Contact Info Widget: Remove extract() usage.

---

modules/likes/queuehandler.js

Uses DOM object manipulation methods instead of string concatenation to properly generate avatar wrapper elements. cc @jeherve

Fixes gravatar wrapper element generation

---

sync/class.jetpack-sync-actions.php
sync/class.jetpack-sync-client.php
tests/php/sync/test_class.jetpack-sync-client.php

Fixes a few minor issues:
- sync as jetpack master user to avoid issue with post authors being 0
- move expensive check for dev/staging to init
cc @lezama

Fix remaining TODO items for Sync

---

modules/publicize/publicize-jetpack.php

@see https://github.com/Automattic/jetpack/commit/b2d3b7878a0020cfb12d9fe4fb44b4901e038b0b#commitcomment-17578042

Publicize: add missing parameter in filter documentation.

---

functions.global.php
jetpack.php

- This file is meant to be the future home for any generic functions that can be reused and accessible whenever Jetpack is active.

Add new file functions.global.php

---

3rd-party/bitly.php

Fixes #4155
- Add a method_exists() check for og_tags

Add fallback code for Bitly class when og_tags does not exist

---

tests/php/sync/test_class.jetpack-sync-options.php

@see https://core.trac.wordpress.org/changeset/37747
Fixes failing Unit Tests like https://travis-ci.org/Automattic/jetpack/jobs/138933530
cc @kraftbj

Unit Tests: provide a valid Permalink structure tag

---

modules/likes/queuehandler.js

Apply #4160 to `master` as well.

Likes: added schema checks for gravatar profile URLs.

---

readme.txt

Improved the changelog for better understanding and readability

---

changelog.txt

Already cherry-picked to `branch-4.0`

Release Notes: copy release notes to changelog.txt too.

---

readme.txt

Already committed to `branch-4.0`

Update tested to WP version

---

modules/custom-css/csstidy/data-wp.inc.php

Custom CSS: Allow multiple `display` properties to be used

---

class.jetpack.php

@see #3816 and #4169
cc @gravityrail

HTTPS Connection Check: fix placeholder values.

---

modules/contact-form/grunion-contact-form.php

The PR at introduces 3 new tokens that can be used to customize the subject of emails sent by contact forms: `entry_title`, `entry_permalink` and `feedback_id`.
User can use these tokens in the subject parameter of the contact form shortcode:
```
[contact-form subject='Sent from {entry_title} at {entry_permalink} #{feedback_id}'][contact-field label='Name' type='name' required='1'/][contact-field label='Comment' type='textarea' required='1'/][/contact-form]
```
which will render the following subject:
```
Sent from Sample Page at http://example.com/sample-page #1ab2cd3ef4gh5ij6kl7mn8op9qr0st1u
```
The `feedback_id` is the same `post_name` used when `wp_insert_post` is called to insert the feedback, an `md5`of the combination of the feedback author and the current mysql time.
closes #3392 …

Contact Forms: new tokens for title and permalink of entry where form is and unique ID

---

_inc/jetpack.js
modules/after-the-deadline/atd-nonvis-editor-plugin.js
modules/gravatar-hovercards.php
modules/likes.php
modules/publicize/ui.php
modules/related-posts/jetpack-related-posts.php
modules/sharedaddy/sharing.js

Replace deprecated jQuery.size() calls

---

jetpack.php
package.json
readme.txt
to-test.md

4.1 Release: prepare for 4.1 Beta1 release

---

.github/ISSUE_TEMPLATE.md

- in this way, it's more natural to describe what you were doing, what did you expect to happen next and what happened instead.

Issue template: changed the order of the headings

---

modules/shortcodes/videopress.php
modules/videopress.php
modules/videopress/utility-functions.php

VideoPress: do not set constant if it is already set.

---

modules/videopress/utility-functions.php

Addresses concern by @enejb https://github.com/Automattic/jetpack/pull/4215#issuecomment-228739561
Thanks for the feedback.

VideoPress: check that constant hasn't been defined before, even if now there's only one place where it is defined

---

package.json

Update the package.json in attempt to fix npm parsing of package.json

Update to package.json ver

---

class.jetpack.php

Jetpack: Check that locales file is available before using it

---

modules/carousel/jetpack-carousel.js

See #3791.
Needs testing.
Original patch by Joseph Scott via https://github.com/Automattic/jetpack/issues/3791#issuecomment-219463561

Provide smaller images in the Carousel when the full-size is very large

---

modules/widgets/image-widget.php

Fixes #4218
- move the code that downloads the image and gets its dimensions to the WP_Widget::update so it's done and saved.
- it will do this only if there's an image URL, and width and height fields are empty. If file download fails, 0 will be saved. So unlike before, the image download will only be done once. Previously, every time the Widgets screen was accessed, the image was downloaded.
- if user enters dimensions, they will be respected.

Image Widget: fetch image and correctly get and save dimensions

---

modules/sharedaddy/sharing.php

PR https://github.com/Automattic/jetpack/pull/4246 done on the master.

Sharing: Fix rtl support in sharing admin

---

sync/class.jetpack-sync-module-protect.php
sync/class.jetpack-sync-modules.php
tests/php/sync/test_class.jetpack-sync-modules-protect.php

Adds bruteprotect to new sync logged actions

Synchronize bruteprotect login attempts

---

modules/widgets/twitter-timeline.php

```
PHP Notice:  Undefined index: widget-id in wp-content/plugins/jetpack/modules/widgets/twitter-timeline.php on line 120
PHP Notice:  Undefined index: title in wp-content/plugins/jetpack/modules/widgets/twitter-timeline.php on line 83
```

Twitter Widget: avoid PHP notices when setting up the widget.

---

modules/monitor.php
modules/sso.php

Updates the version number on a number of inline docs, trims some whitespace that snuck in, and addresses lack of full docs in https://github.com/Automattic/jetpack/pull/4073/files#r65800739
cc: @jeherve

Inline Docs: 4.1->4.1.0

---

modules/widgets/contact-info.php

See #4240 
The smallest delta to keep functionality up. #4242 is still valid and the home to a more long-term intermediate fix :)

Contact Info Widget: Add a filter for a Google API Key

---

class.jetpack.php

Applying #4269 to `master` as well.
Testing instructions can be found in the other PR.

Set Jetpack Version after running upgrade routine.

---

modules/sso.php

Unless I misread the code, we had the wrong association in the docs.
cc: @ebinnion

Inline Docs: Correct SSO docs

---

Gruntfile.js

Related: 5cc909083b4985506ccc905d15234fa09295ecf5

SSO: Add SSO styles to Grunt build process

---

.codeclimate.yml
.svnignore
readme.md

Fixes #4168
Adds a CodeClimate config file and a badge to the readme file.

Add CodeClimate config & badge

---

class.jetpack.php

Fixes comment on https://github.com/Automattic/jetpack/pull/4281#discussion_r69609749

Fix deprecation notice on security report function

---

sync/class.jetpack-sync-wp-replicastore.php
tests/php/sync/server/class.jetpack-sync-test-replicastore.php
tests/php/sync/test_interface.jetpack-sync-replicastore.php

Add checksum for options to `options_checksum`
cc @gravityrail

Sync: Add checksum for options

---

sync/class.jetpack-sync-defaults.php
sync/class.jetpack-sync-module-meta.php

- Make sure we sync post meta that is needed by publicize and other
Jetpack Modules.
- Also 2 fixes publicize by making sure we sync post meta related to them. 
Skip publicize for some accounts `_wpas_skip_*`
Publicize as well as custom message. `_wpas_mess`
cc @gravityrail, @lezama

Fixes: Publicize

---

sync/class.jetpack-sync-module-users.php
tests/php/sync/test_class.jetpack-sync-users.php

Sanitizes user data and make it constant across the login and logged actions.
- Added tests to show that the data across login and logout action is the same. 
- Added tests that show that that the user data is sanitised.

Sync: Sanitizes user data and make it constant across the login and logged actions.

---

modules/likes.php
modules/widgets/top-posts/style.css

A few minor changes, syncing recent fixes from WP.com version.
Note: don't merge until after 4.5 is ready in core, since this removes compat code.
The CSS change is minor, but fixes invalid selector.

Sync likes.php module file from WP.com, minor fixes to CSS

---

class.jetpack.php

@see #4294
cc @enejb Could you take a look and review? Thanks!

Sync: add deprecated hooks to deprecated list.

---

modules/carousel/jetpack-carousel.js
modules/carousel/jetpack-carousel.php

Fixes #3356
First pass at tracking images in full-screen mode

Track individual image hits in Carousel for full-screen images

---

modules/protect.php

Version against master of #4271

Jetpack Performance: move Protect hooks from init to login init

---

class.jetpack-debugger.php

Debugger: add Debug Info to email sent to support.

---

gulpfile.js
package.json

This will let us specify the environment that we need when building Jetpack instead of always using `production`.

Removed hardcoded environment and cleaned up eslint warnings.

---

_inc/client/components/module-settings/index.jsx
_inc/lib/class.core-rest-api-endpoints.php

Fixes #4380 by making minileven use strings rather than numbers for settings.

Admin Page: Fixes minileven settings

---

modules/carousel/jetpack-carousel.php

Fixes spelling error in docblock.

Fix spelling error in function docblock

---

.github/PULL_REQUEST_TEMPLATE.md

Contributing templates: add testing instructions to PR template.

---

_inc/lib/class.core-rest-api-endpoints.php

Fixes #4384
- Allows to set and get options for Stats module:
```
'admin_bar'    => boolean
'roles'        => array of [ 'administrator', 'editor', 'author', 'contributor', 'subscriber' ]
'count_roles'  => array of [ 'administrator', 'editor', 'author', 'contributor', 'subscriber' ]
'blog_id'      => boolean
'do_not_track' => boolean
'hide_smile'   => boolean
'version'      => integer
```
- This commit also modifies d6984ca2d3edcf1ae86e73bbcf9133430fc3d35b since otherwise the existent $user_permissions_error_msg and the newly introduced $stats_roles aren't initialized. Modifying the same commit, it's not necessary to check for WP 4.4. since if the `rest_api_init` action hook doesn't exist, nothing will be called.
cc @oskosk so he can review and integrate with JS.

Endpoints - Module Options: allow to set and get Stats options.

---

modules/custom-post-types/portfolios.php

- Testimonials and comics are already whitelisted in Jetpack.
- Requested here: https://twitter.com/BinaryMoon/status/753539417986441216

Custom Content Types: add Portfolios to REST API whitelist.

---

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php
sync/class.jetpack-sync-defaults.php
sync/class.jetpack-sync-wp-replicastore.php
tests/php/sync/server/class.jetpack-sync-test-replicastore.php
tests/php/sync/test_interface.jetpack-sync-replicastore.php

Allows us to remotely checksum any set of columns for posts or comments.
cc @lezama

Allow selecting columns in histogram API

---

modules/shortcodes/youtube.php

Youtube: use $content_width when available instead of embed_size_w

---

class.jetpack.php
tests/php/sync/test_class.jetpack-sync-base.php

Docs: add missing docblocks

---

tools/deploy-to-master-stable-branch.sh

Build script: make sure dependencies are updated as well.

---

_inc/client/components/dash-item/style.scss

Fixes cloud alignment in IE11.
* some fancy positioning changes to "simplify it
* fixed positioning of containers a bit
- open `_inc/client/at-a-glance/protect.jsx` and modify the count number in line 29 from 0 to whatever your site happens to have
- rebuild
- open in IE11
- try not to notice other visual bugs
Before:
After:
CC @jeffgolenski for testing and review

At a Glance: fixes clouds in IE11

---

sync/class.jetpack-sync-actions.php

Previously we exited the cron job which sends data if it had been running longer than a minute, however after reading more about how wp-cron works I no longer think this is necessary. I had been worried about it holding up other cron jobs, but by default if another cron tries to run after `WP_CRON_LOCK_TIMEOUT` (60s) then it acquires the lock automatically. Therefore no matter what we do we _can't_ hold up other jobs longer than 60s.
In addition, I see a lot of example code for crontabs where wp-cron is scheduled only once every 15 minutes. Assuming this is a standard configuration, we'd be foregoing 14 minutes of processing time by exiting early.
This PR just removes the check for how long the sync has been running.
cc @lezama @enejb

Don’t limit how long we can run when using cron

---

_inc/client/components/masthead/index.jsx

Fixes #4360
Updates version number using current Jetpack version.

Admin Page: update version reference in link to survey

---

class.jetpack-xmlrpc-server.php

Props @sarciszewski for the catch.

Hardening against timing attacks.

---

_inc/client/components/jetpack-notices/index.jsx
_inc/client/components/support-card/index.jsx
_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx

Admin Page: remove extra space before comma.

---

_inc/client/dashboard-widget/style.scss
modules/after-the-deadline/atd.css
modules/protect/protect-dashboard-widget.css
modules/publicize/assets/publicize.css
scss/atoms/_buttons.scss
scss/atoms/typography/_variables.scss
scss/templates/_connection-landing.scss
scss/templates/_main.scss

Fixes #4508
* removes all references to unused font families in favor of the native fonts already in place

Removed unused references to unused fonts

---

sync/class.jetpack-sync-wp-replicastore.php

Fixes slowness with checksum histograms by avoiding OFFSET

Faster checksum histogram query

---

changelog.txt
modules/widgets/top-posts.php

Update en.wordpress.com urls to https.

en.wordpress.com to https

---

modules/shortcodes/googlemaps.php
modules/widgets/contact-info.php

Update Google Map urls to HTTPS by default.

google maps to https

---

modules/carousel/jetpack-carousel.js
modules/shortcodes/js/slideshow-shortcode.js
modules/shortcodes/recipe.php
modules/shortcodes/slideshow.php
modules/theme-tools/site-breadcrumbs.php

Update Schema.org urls to https.

schema.org urls to HTTPS

---

_inc/client/components/footer/index.jsx
modules/carousel/jetpack-carousel.php
modules/site-icon/jetpack-site-icon.php
modules/theme-tools/site-breadcrumbs.php
package.json
readme.txt
views/admin/network-admin-footer.php

Updated all wordpress.com urls to https.

wordpress.com to https

---

_inc/client/at-a-glance/akismet.jsx
_inc/client/at-a-glance/protect.jsx
_inc/client/at-a-glance/scan.jsx

Fixes #4479.
- introduces Calypso's `numberFormat` to format and display long numbers
- go to admin and make sure numbers are properly displayed.

Admin Page - AAG: use numberFormat for large numbers

---

class.json-api-endpoints.php
json-endpoints.php
modules/module-info.php
modules/widgets/gravatar-profile.css
modules/widgets/gravatar-profile.php

I decided to break up my original pull request into smaller bite size requests. Sets all gravatar urls/resources to always be https.

gravatar urls to https

---

_inc/client/plans/plan-body.jsx

Admin Page: link View your security dashboard to VaultPress dashboard

---

json-endpoints/jetpack/json-api-jetpack-endpoints.php

Re add missing attribute to json api.
cc: @lezama

Json API: Re add is_scheduled to sync/status endpoint

---

_inc/lib/tracks/class.tracks-client.php
class.jetpack.php
modules/likes.php

Sets all pixel.wp.com urls/resources to always be https.

Update pixel.wp.com to HTTPS

---

_inc/client/apps/index.jsx

- fixes issues with Apps landing
- make sure Apps looks ok

Admin - Apps: fix layout issues

---

class.json-api.php
json-endpoints/class.wpcom-json-api-get-site-endpoint.php
sal/class.json-api-site-base.php

On Multisite the wrong blog id gets passes to the `is_user_member_of_blog` member of blog function. 
This PR tries to fix that by setting the right blog_id in that function.

JSON API: Fix the response.

---

changelog.txt
readme.txt

The last few changelogs were only committed to the release branches. This brings the master changelog up to date with the latest releases.

Changelog: update changelog with changes from release branches

---

sync/class.jetpack-sync-defaults.php

This will help us identify sites running on Pressable.

Sync IS_PRESSABLE constant

---

sync/class.jetpack-sync-defaults.php
sync/class.jetpack-sync-module-posts.php

Addressing feedback on #4711

---

sync/class.jetpack-sync-actions.php

Remove do_sync call on shutdown from cron

---

class.jetpack.php

Removes unused code from class.jetpack.php.  Notably: 
- old admin_ajax callbacks used in the legacy admin
- ID crisis resolves

Clean class.jetpack.php

---

sync/class.jetpack-sync-sender.php

Add wp_suspend_cache_addition on full sync. 
cc: @lezama @kovshenin

Add wp_suspend_cache_addition on full sync

---

tests/php/sync/test_class.jetpack-sync-full.php

Small fixes to address feedback on merged PRs

---

_inc/client/main.jsx
_inc/client/state/jumpstart/actions.js
_inc/client/state/jumpstart/reducer.js
class.jetpack.php

- display Jumpstart after resetting options
- highlight Dashboard menu item after activating recommended features
- activate Jumpstart, make sure the Dashboard menu item is highlighted
- click Reset options at the footer, make sure Jumpstart is displayed

Admin: fix Jumpstart issues

---

_inc/client/components/forms/styles.scss
_inc/client/components/module-settings/index.jsx
_inc/client/state/modules/actions.js

Fixes #4720 .
Relies on https://github.com/Automattic/jetpack/pull/4717 being merged. Sorry.
* uses FormField and FormButton now
* Make sure you're on `dops-components` `add/input-text` branch
* go to Writing > Post by email
Before:
After:

Post by email settings: fixed layout by using FormLegend and FormButton

---

.gitignore

Example: a5cd27ad1923ff3052ebd90956c68827584f1523

.gitignore: Do not commit Unison temp files

---

modules/sharedaddy/sharing-sources.php

See #4665
While relative protocol should work fine, we can make things more secure by always using https.

Sharing: Use https when possible

---

class.jetpack.php
sync/class.jetpack-sync-actions.php
sync/class.jetpack-sync-module-users.php

Select values directly from usermeta when enqueuing users to avoid expensive IN query against users table.

Fix poor performing user enqueue query

---

_inc/client/components/forms/styles.scss
_inc/client/components/module-settings/index.jsx

* implements new Textarea component
* rearranging of explanation
* updated copy
* Requires https://github.com/Automattic/dops-components/pull/51 to be merged or to be on `dops-components` branch `add/textarea`
* Go to Settings > Security > Protect
Before:
After:

Protect settings: updates layout and implments new Textarea component

---

_inc/client/at-a-glance/akismet.jsx
_inc/client/at-a-glance/plugins.jsx

- Reword text in Akismet and Update cards to avoid orphans
Before:
After:
- Go to Jetpack Admin > Dashboard

Admin: fix orphans in Akismet and Update cards in AAG

---

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php
sync/class.jetpack-sync-actions.php
sync/class.jetpack-sync-module-full-sync.php
sync/class.jetpack-sync-module-users.php
tests/php/sync/test_class.jetpack-sync-base.php
tests/php/sync/test_class.jetpack-sync-full.php

Don’t calculate author IDs during initial sync

---

_inc/client/appearance/index.jsx
_inc/client/engagement/index.jsx

Fixes #4748
- Change `accesible` into `accessible`

Admin: spell accessible correctly

---

sync/class.jetpack-sync-actions.php
sync/class.jetpack-sync-module-full-sync.php
sync/class.jetpack-sync-module-users.php
tests/php/sync/test_class.jetpack-sync-full.php

Move user lookup code into users sync module

Initial sync user id cleanups

---

jetpack.php
readme.txt

Bring over readme changes from `branch-4.2` into `master`, and add a changelog for 4.2.1

Changelog: update and get ready for 4.2.1

---

_inc/client/at-a-glance/stats.jsx
_inc/client/at-a-glance/stats/dash-stats-bottom.jsx
_inc/client/at-a-glance/stats/index.jsx
_inc/client/rest-api/index.js
_inc/client/state/at-a-glance/actions.js
_inc/client/state/at-a-glance/reducer.js
_inc/client/state/initial-state/reducer.js

As an Admin and with the React Dev tools open:
1. Get to the dashboard.
1. Check that the `DashStats` component is receiving at least these props:
* statsData
* siteRawUrl

Admin Page: Remove direct access to Initial State in Admin Page Stats component

---

_inc/client/general-settings/index.jsx

Fixes #4762
cc @MichaelArestad

Settings: wrap the Notificaion && JSON API descriptions in this class

---

_inc/client/components/module-settings/style.scss

Quick fix. Changes background color of gravatar. It's only seen during loading.

Connection Settings: fixed gravatar background color

---

_inc/lib/admin-pages/class.jetpack-react-page.php

- don't load tracking js in dev mode
- add version to cache it
- load in footer.
cc @dereksmart for review

Admin: tweaks to tracking js load

---

changelog.txt
readme.txt

- update stable version to current stable, 4.2.1
- Update changelog

Readme: update master with recent changes for 4.2.1

---

_inc/client/components/connect-button/index.jsx
_inc/client/components/footer/index.jsx
_inc/client/components/jetpack-connect/index.jsx
_inc/client/components/jetpack-notices/index.jsx
_inc/client/components/jetpack-notices/state-notices.jsx
_inc/client/components/jetpack-notices/static-warning.jsx
_inc/client/components/loading-placeholder/index.jsx
_inc/client/components/masthead/index.jsx
_inc/client/components/module-settings/form-components.jsx
_inc/client/components/module-settings/index.jsx
_inc/client/components/module-settings/module-settings-form.jsx
_inc/client/components/module-settings/modules-per-tab-page.jsx

Makes some fixes to files  under the `_inc/client/components` directory for complying with eslint rules
1. These changes add spaces to some lines, replace doblequotes for single quotes in other lines and changes the way `ModuleSettingsForm` is imported to be start with a lowercased name

Admin Page: Make a few linting fixes in components found under the _inc/client/components directory

---

_inc/client/at-a-glance/akismet.jsx
_inc/client/at-a-glance/backups.jsx
_inc/client/at-a-glance/index.jsx
_inc/client/at-a-glance/monitor.jsx
_inc/client/at-a-glance/photon.jsx
_inc/client/at-a-glance/plugins.jsx
_inc/client/at-a-glance/protect.jsx
_inc/client/at-a-glance/scan.jsx
_inc/client/at-a-glance/site-verification.jsx

Makes some fixes to files  under the `_inc/client/at-a-glance` directory for complying with eslint rules
1. These changes add only spaces to some lines. Just reviewing the file sources will do

Admin Page: Make a few linting fixes in at-a-glance (dashboard) related components

---

changelog.txt
readme.txt

Bring changes from `branch-4.2` to `master`

Update version numbers / changelog

---

sync/class.jetpack-sync-defaults.php

Some more meta keys which are rapidly updated.

Add more blacklisted meta

---

_inc/client/admin.js
_inc/client/main.jsx
_inc/client/state/initial-state/reducer.js

As an Admin and with the React Dev tools open, check that the `Main.jsx` component is receiving at least this props and that it has a non undefined value.
* `tracksUserData`

Admin Page: Reduce direct access to window.Initial_State from admin.js file

---

jetpack.php
package.json
to-test.md

@dereksmart @csonnek I'd be happy to get your feedback on this. Let me know if everything is clear, and if I forgot something!
Thank you!

Testing List: update for 4.3

---

class.jetpack-xmlrpc-server.php

I'd love to get this in the next release, if possible.
This PR merely improves error messages we use internally to track connection errors.
cc: @dereksmart

XMLRPC: improved error messaging

---

_inc/client/apps/index.jsx

> At the bottom the copy writing feels odd to me. Having pocket and desktop capitalized with your being lowercase made me squint.

Admin Page / Apps: Capitalize Your.

---

scss/templates/_main.scss

Removed background on noJS view and now looks "way better"

---

readme.md

Fixes #4403 .
- Adds 2 new sections to the readme: Development build, Production build and Development build with changes monitoring.

Admin Page: readme.md - Add reference to development and production builds

---

_inc/client/components/module-settings/index.jsx

Stats: add smiley explanation back to Admin page.

---

_inc/client/state/jumpstart/actions.js
_inc/client/state/modules/actions.js

Fixes #5002 .
- Made all placeholders use proper format to avoid i18n exceptions.

Fixed incorrectly named placeholders.

---

_inc/client/at-a-glance/stats/dash-stats-bottom.jsx
_inc/client/at-a-glance/stats/index.jsx

Fixes #5007 
To test: 
- Make sure the button works
- Make sure it looks nice

AAG Stats: add "view old stats" button

---

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php

Previously the endpoint was returning untranslated module names and descriptions.

Added properly translated module names and descriptions.

---

sync/class.jetpack-sync-actions.php

Fixes #4977 by loading the sync listener and sender for cron jobs.
Marking as in progress while I test.

Sync: Load listener and sender for cron jobs

---

_inc/lib/class.core-rest-api-endpoints.php

REST API: fix typo

---

_inc/lib/class.core-rest-api-endpoints.php
_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php

- introduces fixed placeholders in strings that missed them
- added message for translators explaining placeholders
- added inline docs.

Endpoints: update translatable strings with fixed placeholders

---

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php

Fixes a comment for the sync object endpoint.
cc @gravityrail

Sync: Fix comment for sync object endpoint

---

sync/class.jetpack-sync-listener.php
tests/php/sync/test_class.jetpack-sync-base.php

Sync `updating_jetpack_version` event! why not?

Sync: Sync `updating_jetpack_version` event

---

class.photon.php

Photon: apply jetpack_photon_skip_image to srcset images too.

---

jetpack.php
package.json
readme.txt

Also update plugin version to 4.3.1 alpha version

Readme: update stable version, as well as initial 4.3.1 changelog

---

sync/class.jetpack-sync-defaults.php
sync/class.jetpack-sync-functions.php
tests/php/sync/test_class.jetpack-sync-callables.php

This helps a lot with support, as some hosting providers have known peculiarities.

Sync hosting provider

---

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php

Sync: Add next_sync_time to sync status endpoint

---

modules/shortcodes/blip.php
modules/shortcodes/dailymotion.php
modules/shortcodes/flickr.php
modules/shortcodes/googlemaps.php
modules/shortcodes/instagram.php
modules/shortcodes/polldaddy.php
modules/shortcodes/presentations.php
modules/shortcodes/soundcloud.php
modules/shortcodes/vimeo.php
modules/shortcodes/youtube.php
tests/php/modules/shortcodes/test_shortcode_defense.php

Fixes #4795 .
<del>Currently a WIP, showing example of one shortcode in this commit.</del>

Shortcodes: Return early if not passed a string.

---

_inc/client/components/module-settings/index.jsx
_inc/client/components/module-settings/modules-per-tab-page.jsx
_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php

Fixes #4986 .
* remove duplicate settings
Before:
After:
@dereksmart or @oskosk I only made the visual changes.  It doesn't actually work I don't think. Could one of you fix this up?

Gravatar Hovercard Settings: removed extra form visually

---

tests/php/sync/test_class.jetpack-sync-posts.php

Fixes a failing test due to missing class.
cc @lezama @samhotchkiss

Fix test failing due to missing contact form require

---

class.jetpack-xmlrpc-server.php

Corrects some of the doc blocks in the `Jetpack_XMLRPC_Server` class.

General: Audit doc blocks in XMLRPC server file

---

sync/class.jetpack-sync-defaults.php

Sync: Add DISABLE_WP_CRON to $default_constants_whitelist

---

_inc/client/at-a-glance/index.jsx
_inc/client/components/masthead/index.jsx

Replaces #5232
Fixes #5231 
**Before:**
**After:**

Admin Page: remove prompt for feedback.

---

class.jetpack-heartbeat.php
tests/php/test_class.jetpack-heartbeat.php

Removes unnecessary checksum information from heartbeat data

Remove checksum from heartbeat

---

modules/tiled-gallery/tiled-gallery/tiled-gallery-layout.php

Allow others to override the default Tiled Gallery template files.

Tiled gallery templates

---

jetpack.php
package.json
readme.txt

This PR starts a new release cycle for 4.4.

Bumped stable tag and version.

---

class.jetpack.php

This PR simply fixes a whitespace formatting issue that has been bothering me. There should be no functionality changes.

General: Whitespace fix in build_connect_url() method

---

modules/widgets/social-media-icons.php

Updated code based on PHP Coding Standards. Mostly PHP Doc Blocks.

Social Media Icons Widget: Coding standards updates.

---

class.jetpack.php

**Improved Compatibility:**
* Open Graph: add SEO by Squirrly TM to the list of conflicting plugins.

Conflicting plugins: add SEO by Squirrly to the list.

---

sync/class.jetpack-sync-defaults.php

Sync: blacklist `bwg_album` and `bwg_gallery` post types

---

modules/widgets/social-media-icons.php

Patches for #3774
Removing the title attribute from social media icons.

removing title attribute on social media icon

---

class.photon.php

Updates to use the identical (===) operator, tagged as Bug Risk in CodeClimate.

Photon: Update operators in class.photon.php

---

modules/theme-tools/compat/twentyfifteen.php
modules/theme-tools/compat/twentyfourteen.php
modules/theme-tools/compat/twentysixteen.php

This is a rebase to allow automated tests to run and the like.
Fixes #4865 
Fixes #3679

Theme Tools: do not load compat files in the dashboard.

---

modules/subscriptions.php
modules/widgets/contact-info.php
modules/widgets/facebook-likebox.php
modules/widgets/gallery.php
modules/widgets/goodreads.php
modules/widgets/google-translate.php
modules/widgets/googleplus-badge.php
modules/widgets/gravatar-profile.php
modules/widgets/image-widget.php
modules/widgets/my-community.php
modules/widgets/rsslinks-widget.php
modules/widgets/social-media-icons.php
modules/widgets/top-posts.php
modules/widgets/twitter-timeline.php
modules/widgets/upcoming-events.php
modules/widgets/wordpress-post-widget.php

Janitorial naming fix, minor.
The stat name changed on the WP.com side, and this reflects that — it's more specific.
Previously #5478 improved after feedback from @jeherve

Stats: improve pageview counts for widget views

---

_inc/idc-notice.js
_inc/lib/class.core-rest-api-endpoints.php
class.jetpack-idc.php
class.jetpack-options.php
sync/class.jetpack-sync-actions.php

Closes #5446 
Testing instructions TBD.

Identity Crisis: Handle 'Migrate Stats & Subscribers' action

---

modules/custom-post-types/nova.php

Allowing filtering element's opening and closing markup and item's class.

Nova Menu CPT: Improved control over output markup

---

modules/protect/shared-functions.php
modules/protect/transient-cleanup.php

Code Cleanup based on WordPress PHP Coding Standards.

Protect: Coding Standards updates.

---

modules/carousel/jetpack-carousel.php

Fixed the majority of the reported issues by CodeClimate and PHP Coding Standards. Lots of Doc Block Additions.

Jetpack Carousel Cleanup

---

class.jetpack.php
gulpfile.js

1. Bring back changes accidentally removed during Merge. 9b81998 undid the changes that were made in f2fd051
2. Add community widget style to concat styles (see #3358).

CSS Concatenation: update rules to include new CSS files

---

modules/custom-post-types/nova.php

Fixes #5542
Filters added in #1542
cc @zinigor

Nova Menus: add docblocks for new filters.

---

json-endpoints/jetpack/class.jetpack-json-api-plugin-new-endpoint.php
json-endpoints/jetpack/class.jetpack-json-api-plugins-new-endpoint.php
json-endpoints/jetpack/json-api-jetpack-endpoints.php

This api endpoint allows us to install a plugin via by uploading a zip file.
For a description how to test this PR 
Follow the instructions here D3262-code

Json api: Add new plugin/new api endpoint

---

.svnignore
LICENSE.txt

Allows display of licensing on GitHub: https://github.com/blog/2252-license-now-displayed-on-repository-overview

License: add license file to repository.

---

modules/widget-visibility/widget-conditions.php

Widget Visibility: move filter so it can be accessed by the parser

---

_inc/client/admin.js
_inc/client/appearance/index.jsx
_inc/client/components/module-settings/index.jsx
_inc/client/components/navigation-settings/index.jsx
_inc/client/components/non-admin-view/index.jsx
_inc/client/engagement/index.jsx
_inc/client/main.jsx
_inc/client/security/index.jsx
_inc/client/writing/index.jsx

Backs out of the changes that are going to be a part of the next release.

Revert "Updates module settings positions and renames tabs."

---

sync/class.jetpack-sync-module-callables.php
tests/php/sync/test_class.jetpack-sync-callables.php

The callable checksums work great. Maybe even too well. 😄 
For IDC's purposes, we can get in a weird state when dealing with cloned sites. For example, imagine this scenario.
- You have two sites, "A" and "B"
- "B" is a clone of "A"
- Shortly after being cloned, site "B" attempts to sync it's new `home_url` and `site_url` values, which we then deny on WP.com, and then we put the site into IDC mode
- Site "B" can decide to force the sync (although we present this as migrating the subscriptions and stats from Site "A" to Site "B").
- When this happens, we set an option, `migrate_for_idc`, that gets sent with each sync request and acts as an override to allow the sync
- But, here's the catch. When we initially sent the callable for Site "B", in the sync request that put the site in safe …

Sync: IDC: Ensure that we send URL callables while migrating for sync

---

_inc/client/components/module-settings/README.md
_inc/client/components/module-settings/module-settings-form.jsx

- Adds a `README.md` file, inline docs and cleans up deprecated methods
1. Take a look at `components/module-settings/README.md` and check if it's fine.

Admin Page: Feature Settings Add better docs for feature settings-related components

---

_inc/lib/markdown/gfm.php

Fixes #367
Replaces #4894
Props @lkraav

Markdown: allow filtering $preserve_shortcodes

---

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php
json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
json-endpoints/jetpack/class.jetpack-json-api-themes-install-endpoint.php
modules/videopress/class.videopress-cli.php
modules/videopress/class.videopress-edit-attachment.php

Fixes some i18n problems. cc @dbtlr because I have added context to some VideoPress strings, can you please see if I got it right and test the interface again?

Added missing textdomains, added context, fixed minor braces and typos.

---

class.jetpack-autoupdate.php
class.jetpack-options.php
json-endpoints/jetpack/class.jetpack-json-api-themes-endpoint.php
json-endpoints/jetpack/class.jetpack-json-api-themes-modify-endpoint.php
sync/class.jetpack-sync-defaults.php
tests/php/sync/test_class.jetpack-sync-options.php

JSON API: Add `auto_update_translations` feature

---

modules/widgets/my-community.php

@jeffgolenski  What do you think?

My Community: improve wording.

---

_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx

Support for Personal Plan and VideoPress

---

_inc/lib/admin-pages/class.jetpack-admin-page.php

Might fix an issue with flash of unstyled content (FOUC). cc @jeherve 
Earlier today, @jeherve reported an issue with FOUC. This issue can be difficult to reproduce. From what I gathered, the issue was occurring due to when we enqueued the styles, specifically since we were enqueueing when adding the admin pages instead of enqueueing in the `wp_enqueue_scripts` hook.
This PR fixes that by always calling `additional_styles` from the `wp_enqueue_scripts` hook and then conditionally bailing from that method if we previously decided to not render the page.
To test:
- Checkout `update/admin-page-refactor-styles-enqueue` branch
- Go to Jetpack admin page and ensure the page loads properly
- Go to old Jetpack admin page and ensure it loads properly (`/wp-admin/admin.php?page=jetpack_modules`)
- …

Admin Page: Refactor additional styles loading

---

readme.txt

Adds changelog entry for #5636 
cc @jeherve

Adds changelog for #5636

---

readme.txt

This is a copy of #5654 for the `master` branch.

Added changelog for #5636, copy of #5654 for the master branch.

---

modules/videopress/class.jetpack-videopress.php

WordPress has 2 media uploaders, the one embedded in the Media Library and an older one inside the `wp-admin/media-new.php`. This replaces the submenu item and adds in a method to have the uploader opened up when the standard media library is loaded.
1) Click: Media -> Add New
2) You should be directed to `wp-admin/upload.php?action=add-new`
3) This will open the media library with the Add New media item box open

Make sure when the user clicks on the Media -> Add New menubar item VideoPress works

---

_inc/client/components/module-settings/modules-per-tab-page.jsx
modules/module-headings.php
modules/module-info.php
modules/seo-tools.php

Changes to SEO Tools text

---

class.jetpack-connection-banner.php

Content updates for connection banner

---

_inc/client/plans/plan-header.jsx

Removes price

---

_inc/client/plans/plan-body.jsx

Fix SEO tools section on plans page, and lose VideoPress

---

_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx

Admin Page: remove VideoPress from Plans page.

---

modules/widgets/my-community.php
modules/widgets/top-posts.php

Widgets: update traffic link to support doc on jetpack.com.

---

jetpack.php
package.json

Bumped version to 4.5.0-alpha

---

_inc/client/engagement/test/component.js
modules/module-info.php

Update the support doc link to use the new Jetpack support doc.

SEO Tools: update support doc link.

---

package.json
yarn.lock

In the beginning of the new release cycle let's try to update the dependencies to the available new versions.

Ran yarn upgrade to use available new versions of software.

---

modules/theme-tools/featured-content.php

Fixes #5292. cc @georgestephanis 
* Moves the term check out of the filter to avoid infinite loops.
* Install superhero theme.
* In the customizer enable hiding of the featured tag in tag lists.
* Load the client part of the site, observe an infinite loop error (or a WSOD if you don't have debug enabled).
* Use this PR, observe no more WSODs.

Moved get_term_by call out of the filter to avoid infinite loops.

---

modules/custom-css/custom-css-4.7.php
modules/custom-css/custom-css/css/customizer-control.css
modules/custom-css/custom-css/js/core-customizer-css.js
modules/custom-css/migrate-to-core.php

Would be nice for 4.4.2, but 4.5 is probably fine.

Some CSS fixes and enhancements.

---

modules/widgets/milestone.php
modules/widgets/milestone/milestone.js
modules/widgets/milestone/milestone.php
modules/widgets/milestone/style-admin.css

This PR adds the milestone widget from WPCOM. 
My only concern is that the `Milestone_Widget` class is too generic.  I would like to change it but if we change it on wpcom (to keep it in sync) then any widget already registered would be de-registered.  I've at least namespaced the `Milestone` class name.  
Please also test the wpcom diff, as I had to make some changes in order to make this widget syncable with wpcom.  D3593

Milestone Widget: add from wpcom 

---

_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx
_inc/client/search/index.jsx
_inc/client/writing/index.jsx
class.jetpack.php

Fixes VideoPress logic and merges some things in from 4.4

Fix VideoPress Logic

---

class.jetpack.php

Reverts Automattic/jetpack#3635
We will reintroduce it soon, or a modified version that does the same, but right now we need to move on.

Revert "Make is_development_mode() value "static""

---

json-endpoints.php
modules/sharedaddy/sharing-sources.php
modules/sharedaddy/sharing.php

Ysupr add/sharing variables

---

_inc/client/components/module-settings/index.jsx
_inc/client/components/module-settings/modules-per-tab-page.jsx
_inc/client/engagement/index.jsx
_inc/client/pro-status/index.jsx
_inc/lib/class.core-rest-api-endpoints.php
class.jetpack.php
gulpfile.js
modules/module-headings.php
modules/module-info.php
modules/wordads.php
modules/wordads/css/style.css
modules/wordads/php/admin.php
modules/wordads/php/api.php
modules/wordads/php/cron.php
modules/wordads/php/networks/amazon.php
modules/wordads/php/params.php
modules/wordads/php/widgets.php
modules/wordads/wordads.php

PR for adding WordAds as a Jetpack module.
Details in https://github.com/Automattic/jetpack/issues/5465

Module: WordAds

---

modules/wordads/php/widgets.php
modules/wordads/wordads.php

This should make our parser happier.

WordAds: add details to WordAds filter docblocks.

---

_inc/client/components/dash-section-header/index.jsx
_inc/client/components/dash-section-header/test/component.js

GUI Testing: add more tests

---

modules/module-headings.php
modules/wordads.php

Missed updating the header info.
Re-ran via `gulp php:module-headings`

Ads Header: Updated Copy

---

modules/widgets/google-translate.php

- Improve wording for Widget Description.
- Add default title.
p2JiWH-1tm-p2

Google Translate Widget: improvements to wording

---

to-test.md

Testing file for the beta plugin

To Test: 4.5

---

_inc/client/components/dash-section-header/index.jsx

cc @dereksmart 
Export DashSectionHeader as default export.
* build, make sure everything is ok

Admin: export DashSectionHeader component correctly

---

jetpack.php
package.json

Bump version

---

_inc/client/at-a-glance/backups.jsx
_inc/client/at-a-glance/scan.jsx
_inc/client/plans/index.jsx
_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx
_inc/client/pro-status/index.jsx
_inc/client/search/index.jsx
_inc/client/writing/index.jsx
class.jetpack-jitm.php

Changes links from plugin to wp.com/plans to a page on jetpack.com
which will redirect to the appropriate page based on the “source” param

Change to plan URLs

---

modules/shortcodes/unavailable.php

With its first shortcode to override -- blip.tv!
See: #5853

Add Shortcode Unavailable class.

---

.travis.yml

The previous PR incorrectly added notifications, this one does it properly.

Actually adding webhook notifications.

---

_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx

- adds mentions about Ads
- adds Ads card in premium and pro page
- updates to free plan page body include CTA at the bottom

Changes to /plans to include new features

---

changelog.txt
readme.txt
to-test.md

- Changelog entry added for each PR.
- I made very few changes to the testing list, it was already pretty good.
- I updated the version numbers in readme to avoid issues when updating to the beta.

4.5 Release: update changelog, testing list, and bump version numbers in readme.

---

_inc/client/writing/index.jsx

- don't import ProStatus since it's never used.
* build and make sure everything in Writing tab looks right

Admin: remove import of unused ProStatus component

---

modules/stats.php

The HTTP will 301 to HTTPS. Let's fix that.

Update CSV call to https

---

modules/widgets/contact-info.php

To improve findability in widget list.
Merges r148062-wpcom
* Open widgets, add Contact Info -- ensure title and description are updated.

Extra Sidebar Widgets: Contact Info: add map to title and description

---

modules/wordads/php/widgets.php

Default to MREC in case we somehow create a widget without setting the values.

Ads: Set Default Values for Widget

---

_inc/client/components/dash-item/style.scss

Fixes: https://github.com/Automattic/jetpack/issues/6032
Before:
After:

Dash: Inactive card SectionHeader color change

---

_inc/client/at-a-glance/scan.jsx

Updating “Malware Scanning” to “Security Scanning” on the dashboard, for better language
consistency
Fixes https://github.com/Automattic/jetpack/issues/6042
Before:
After:

Dash: Updating Scanning Verbiage

---

class.json-api-endpoints.php
json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php

cc @aduth @jeherve @mtias 
This PR aims to accomplish https://github.com/Automattic/jetpack/pull/5487#issuecomment-270512025

JSON API: Update `allowed_post_types`

---

_inc/lib/icalendar-reader.php
modules/shortcodes/upcoming-events.php
modules/widgets/upcoming-events.php

Syncs up files regarding the Upcoming Events widget and shortcode from WPCOM including some changes by @sirbrillig regarding timezones.
As this is only now finally shipping, shouldn't need a changelog entry.

Upcoming Events file sync with WPCOM.

---

_inc/client/plans/plan-body.jsx
modules/wordads.php

WordAds: better description verbiage

---

modules/videopress.php

VideoPress: update description (added period)

---

_inc/client/plans/plan-body.jsx
_inc/client/plans/plan-header.jsx
class.jetpack-connection-banner.php

- Remove mention from feature tour
- Remove mention from upsell pitch
- Remove card on Pro plan body

Remove obvious PollDaddy mentions

---

readme.txt

Bump to 4.5 now that the release is out.

Readme: update stable version.

---

modules/wordads/php/widgets.php
modules/wordads/wordads.php

Updated the WordAds notice from About these ads to Advertisements per
https://support.google.com/adsense/answer/4533986?hl=en.

Ads: Updated ad notice

---

.travis.yml
modules/contact-form/grunion-contact-form.php
tests/php/sync/test_class.jetpack-sync-plugins.php
tests/php/sync/test_interface.jetpack-sync-replicastore.php
tests/php/test_class.jetpack-client-server.php
tests/php/test_class.jetpack-post-images.php
tests/prepare-wordpress.sh
tests/run-travis.sh

Adds PHP 7.1 released December 1st and unit tested by Core. Fixes #5959

Add PHP 7.1 testing

---

_inc/client/writing/theme-enhancements.jsx

* adds missing class
* Go to Writing > Theme enhancements

Adds missing class that fixes styles in Theme Enhancements group

---

_inc/client/components/connect-button/test/component.js
_inc/client/components/navigation-settings/test/component.js

- update tests for ConnectButton and NavigationSettings

GUI Tests: update tests for ConnectButton and NavigationSettings

---

_inc/client/components/settings-card/README.md
_inc/client/components/settings-card/index.jsx
_inc/client/components/settings-card/test/component.js
_inc/client/components/settings-group/README.md
_inc/client/components/settings-group/index.jsx
_inc/client/components/settings-group/test/component.js
_inc/client/discussion/comments.jsx
_inc/client/discussion/subscriptions.jsx
_inc/client/security/antispam.jsx
_inc/client/security/backups-scan.jsx
_inc/client/security/protect.jsx
_inc/client/security/sso.jsx
_inc/client/traffic/related-posts.jsx
_inc/client/traffic/seo.jsx
_inc/client/traffic/site-stats.jsx
_inc/client/traffic/verification-services.jsx
_inc/client/writing/composing.jsx
_inc/client/writing/custom-content-types.jsx
_inc/client/writing/media.jsx
_inc/client/writing/post-by-email.jsx
_inc/client/writing/theme-enhancements.jsx

Needed for upcoming dev mode implementation. It's merely a refactor with no functionality added or changed.
- refactor SettingsGroup to a new file
- update gui tests to pass
- update how SettingsGroup and SettingsCard are imported
- removed unnecessary imports in SettingsCard and SettingsGroup
- edit Readme file of SettingsCard

Admin: refactor SettingsGroup to a new file. Adapt gui tests.

---

modules/google-analytics.php

@richardmuscat gave this 👍 in slack

Update google analytics description

---

class.jetpack.php

Minor whitespace cleanups

---

_inc/client/traffic/verification-services.jsx
modules/module-info.php

Fixes #6212 
- update support link for Verification Services
* make sure the link in Verification Services goes to the right location.

Settings UI: update Verification Tools support link

---

changelog.txt
readme.txt
to-test.md

- List all changes made in the release.
- Create testing list for all relevant items

Changelog and Testing list for Jetpack 4.6

---

modules/infinite-scroll/infinity.js
modules/infinite-scroll/infinity.php

Update Jetpack with any relevant changes to wpcom on Infinite Scroll.
Fortunately, there seem to be few.  Some chaff that will get cleared out when squashed.

WPCOM MERGE Infinite Scroll

---

_inc/client/security/sso.jsx

Removes redundant setting explanation.

Removed redundant setting explanation

---

_inc/client/security/protect.jsx

* removed redundant explanation text
* made IP a label
* embiggened `Add to whitelist` button
* switch to branch
* take a good look at the Brute force protection group in Security settings

Updated design of brute force protection settings group

---

_inc/client/components/module-settings/modules-per-tab-page.jsx

Fixes #6289
Updates description to match calypso's when inactive.

GA: Update inactive description to match calypso

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.svnignore
CODE-OF-CONDUCT.md
docs/code-reviews.md
docs/coding-guidelines.md
docs/development-environment.md
docs/git-workflow.md
docs/guides/get-started-with-git.md
docs/guides/report-bugs.md
docs/guides/submit-patch.md
docs/pull-request.md
docs/release-management.md
docs/translations.md
readme.md

- Make contributing less frightening and easier for all potential contributors.
- Make our guidelines and requirements clearer.
- Surface all data in our contributing guide.
- Offer options to contribute to everyone, even if it's not via code.
- Outline our release management process, and approach to code reviews and Pull Requests.
- Documentation: refresh our contributing guide.

Documentation: reorganize current docs and create new ones.

---

class.jetpack-cli.php
class.jetpack-debugger.php
class.jetpack-twitter-cards.php
modules/contact-form/grunion-contact-form.php
modules/custom-css/custom-css-4.7.php
modules/custom-css/custom-css.php
modules/custom-post-types/portfolios.php
modules/custom-post-types/testimonial.php
modules/infinite-scroll/infinity.php
modules/likes.php
modules/publicize/publicize-jetpack.php
modules/videopress/class.videopress-cli.php
sync/class.jetpack-sync-actions.php

In this PR I collect plural strings that should have been using `_n()` but weren't.

Improve translatability of plurals and texts with variables
