functions.opengraph.php, tests/php/test_class.functions.opengraph.php
This is a tweak to the open graph image selection logic, making it select the first 'good' image in a post instead of the last (the Twitter card tag logic already does this).
The image tags can be inspected by viewing the source of a post page, they look like this:
```html
<meta property="og:type" content="article" />
<meta property="og:title" content="A story post" />
<meta property="og:url" content="https://example.com/2020/10/20/a-story-post/" />
<meta property="og:description" content="Visit the post for more." />
<meta property="article:published_time" content="2020-10-20T06:39:37+00:00" />
<meta property="article:modified_time" content="2020-10-20T06:39:37+00:00" />
<meta property="og:site_name" content="alexforcier" />
<meta property="og:image" …
```
=> Use the first good image for the open graph tag

extensions/blocks/story/index.js
With this PR https://github.com/Automattic/jetpack/pull/17536/files the story block was hidden from the inserter altogether but we want it to be available on mobile behind a feature flag as per https://github.com/wordpress-mobile/gutenberg-mobile/pull/2762
This PR fixes that (which otherwise would make the Story block not available in the inserter for _all_  platforms), by making the `supports.inserter` flag `false` for the web, and `true` for native platforms.
=> Story block set inserter support to false for web, but keep it for native

packages/sync/src/class-replicastore.php
comment_status_to_approval_value is currently marked as private, it should be protected to allow overwriting if needed.
* Update private to protected 
NO
* N/A
=> Update access of comment_status_to_approval_value to allow extension.

packages/connection/src/class-client.php
To support the new VideoPress endpoint in D52124-code we need to pass the body through to the connection client when making a request to wp.com via `wpcom_json_api_request_as_blog()`.
* Passes through the `$body` object `WPCOM_API_Direct::do_request`. The body is safely checked if it exists in that function.
pxWta-Tk-p2
No
* Apply PR and verify existing calls to wp.com are still functioning as expected. I tested the latest Instagram posts block.
* See D52124-code for testing instructions that utilize a POST request.
* No changes.
=> Pass HTTP POST when making a wp.com api request

.github/workflows/e2e-tests.yml, tests/e2e/lib/global-teardown.js, tests/e2e/lib/page-helper.js, tests/e2e/lib/pages/wpcom/authorize.js, tests/e2e/lib/pages/wpcom/pick-a-plan.js, tests/e2e/lib/reporters/slack.js, tests/e2e/lib/setup-env.js
After recent changes, local test runs were failing due to slack reporter error. 
This PR resolves the error by refactoring the slack reporter functions into a class. Also, it adds a run type line to the slack messages that would help distinguish build types
n/a
n/a
* Run tests locally:
```
$ ./tests/e2e/bin/env.sh start
$ yarn test-e2e --testPathIgnorePatterns=updater
```
* Check if the tests are passing in CI.
* Check slack report. Does it make sense? (link incoming)
* n/a
=> E2E tests: Fix e2e slack reporter

bin/pre-commit-hook.js, bin/prepare-commit-msg.js
Improvements:
* We can more reliably detect whether the hook was run by storing the
tree hash that's going to be committed rather than a timestamp.
* If the commit is already flagged as not verified, there's no point in
adding the flag again ("[not verified] [not verified]").
* If the commit is flagged as not verified but it was just verified, we
can remove the flag.
There seems to be no way to do the right thing (i.e. verify) on a cherry
pick or rebase. But this does still improve the situation for those too.
For a cherry pick you can `git commit --amend` immediately after, which
will verify and will now remove the flag. For a rebase, you can do it
with --interactive and change "pick" to "reword" on all lines, which
will for some reason also verify each one.
None, although #16985 is …
=> Git hooks: Improve "not verified" flagging

.phpcs.xml.dist, packages/codesniffer/Jetpack/ruleset.xml, packages/codesniffer/tests/php/tests/test-jetpackstandard.php
We generate code coverage using phpdbg. If you pass it `-qrr` it works to execute command-line scripts, but it's not really command-line compatible with the standard PHP executable.
None the less, it still sets `PHP_BINARY` to point to itself, and without the `-qrr`. This will break anything that tries to use `PHP_BINARY` to shell out to PHP, and in particular breaks the Generic.PHP.Syntax sniff's attempt to shell out to `php -l`.
So when we try to generate code coverage for the codesniffer package, and it executes the sniffs to test them, the Generic.PHP.Syntax sniff hangs.
There are a few ways we might work around this:
1. Exclude Generic.PHP.Syntax from the Jetpack standard. Linting can be done more efficiently with php-parallel-lint.
2. Exclude Generic.PHP.Syntax when running tests, …
=> Codesniffer: Fix code coverage generation hang due to Generic.PHP.Syntax sniff

extensions/shared/external-media/index.js
Fixes #17476.
* Very rudimentarily checks if the media button render function contains the `coblocks` textdomain and doesn't append external media links if it does.
No
Before | After
--- | ---
* Go to the Editor
* Insert an image block and select an image.
* Click on "Replace" in the block toolbar and make sure External Media is still available there.
* Check the sidebar and make sure External Media links are no longer there.
* External Media: Fixed a conflict with CoBlock's image replace feature.
=> External Media: Don't append to Coblocks replace button

bin/prepare-commit-msg.js
In #17728 we added some code to remove the "not verified" tag when
verification passed, on the assumption that the pre-commit hook was
verifying the whole commit on an --amend.
It turns out that it only verifies the changes being made, rather than
the commit as a whole. So removing the tag is not the correct thing to
do unless we can figure out a way to detect --amend and reverify the
whole commit.
None.
No.
* Create a commit with --no-verify. See that it gets flagged with [not verified].
* Amend the commit with --no-verify. See that the [not verified] remains, but is not doubled.
* Amend the commit without --no-verify. See that the [not verified] remains, but is not doubled.
* Amend the commit with --no-verify. See that the [not verified] remains, but is not doubled.
* Developer only, …
=> Git hooks: Revert code removing the "not verified" tag

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, json-endpoints/class.wpcom-json-api-update-site-homepage-endpoint.php, sal/class.json-api-site-base.php
This commit:
- syncs changes from D52434-code (r216472-wpcom) and D52433-code (r216472-wpcom)  (which rolled back the corresponding code in WPCOM)
- effectively rolls back https://github.com/Automattic/jetpack/pull/17105 
This PR makes no changes to data or privacy.
* Remove support for public coming soon page redesign, which we've decided not to release at all
=> Coming soon: synching roll back changes on WPCOM 

modules/infinite-scroll/class-jetpack-amp-infinite-scroll-sanitizer.php, modules/theme-tools/compat/twentynineteen.php, modules/theme-tools/compat/twentytwenty.php
@westonruter,
I'm assigning this PR to extend #17497 and provide support for elements that are supposed to be hidden on initial load, in case Infinite Scroll is enabled — like the pagination bar.
=> AMP infinite scroll add hidden

packages/connection/src/class-manager.php
When the `wp_options` table is not writeable, connecting Jetpack will result in the error `Verification secrets not found`.
This PR clarifies the error, informing the user that they need to confirm the options table is writable.
No.
1. Disconnect Jetpack (if connected).
2. Remove `AUTO_INCREMENT` from the `wp_options` table:
```sql
ALTER TABLE wp_options CHANGE option_id option_id bigint(20) unsigned NOT NULL;
```
3. Try to connect Jetpack.
4. The "Set up Jetpack" page should be reloaded, the error message "Could not save secrets. Please confirm that the options table is writable." should show up.
**Before:**
**After:**
* Displaying a clarified error message when the options table is not writable.
=> Clarified error message for non-writable options table.

extensions/blocks/story/edit.js, extensions/blocks/story/icon.js, extensions/blocks/story/player/components/bullet.js, extensions/blocks/story/player/components/button.js, extensions/blocks/story/player/components/media.js, extensions/blocks/story/player/components/overlay.js, extensions/blocks/story/player/index.js, extensions/blocks/story/player/player.js, extensions/blocks/story/player/progress-bar.js, extensions/blocks/story/player/style.scss, extensions/blocks/story/story.php
Improvements to the Story block
- Improve progress indicator in story preview when there are many frames.
- Add title attribute to image and videos
- Block editor: Minor copy fix: added a comma after “upload new ones”
- Block editor: Remove the fullscreen icon from the story block preview. Replaced with a slide count
- Block editor: Fix CSS regressions on new versions of wordpress: left and right arrow too small, stopped using the Button component from `@wordpress/components`
- Minor update to the story icon, updated to match the other G2 style icons in the web block picker
Make sure there is no regression after this patch is applied and all the items in the list are addressed.
* Minor visual improvements to the Story block
=> Story block improvements

modules/stats.php
In this PR, we add support for Web stories plugin that does has a custom render and does not use `wp_footer`
Fixes https://github.com/google/web-stories-wp/issues/5016
*
* Go to '..'
*
*
=> Add support for stats in Web Stories.

.travis.yml
* Composer 2.0.7 is incompatible with the Jetpack autoloader, which causes the Travis tests to fail. To fix the failing tests, use Composer 2.0.6 in the the Travis tests.
* n/a
* no
* Verify that the Travis tests pass.
* n/a
=> Tests: Use Composer 2.0.6 in Travis tests

packages/connection/src/class-manager.php, packages/status/src/class-status.php
Adds the possibility for developers to run Jetpack in a "No user" mode
* adds a check for the `no_user_test_mode`
* If this mode is active, Jetpack will be considered `active` if it has the blog token and will disconsider the user tokens. Those will be ignored and never returned from the database.
p1HpG7-a4a-p2
No
* New site
* Add `define( 'JETPACK_NO_USER_TEST_MODE', true );` to your `wp-config.php`
* You will be asked to connect a user, as usual. Connect
* The screen will freeze in the last step "Finalizing". Refresh the window
* Check that you see the Jetpack Dashboard
* Check you see dialogs suggesting you to connect your user to WPCOM (as if you were not connected)
* remove the defined constant and add: `add_filter( 'jetpack_no_user_testing_mode', '__return_true' …
=> Add the no_user_testing mode

extensions/blocks/tiled-gallery/view.scss
Adding these styles will improve rendering of the Tiled Gallery block in WordPress.com subscriber emails.
Fixes 196-gh-Automattic/dotcom-manage
Before | After
--- | ---
*
None.
No.
* Apply this patch to your WP.com sandbox using the Fusion-generated diff.
* On a WordPress.com test site, publish a post with a Jetpack Tiled Gallery block.
* Send a test email for this post (see PCYsg-tvN-p2).
* Verify the results look good. It doesn't have to be an exact layout match, the images should just make some visual sense and not be crowded.
No changelog needed.
=> Tiled Gallery Block: Update styles for WP.com emails.

tools/jetpack-live-branches/jetpack-live-branches.user.js
JN now supports the Debug Helper plugin, so let's add it as an option to our userscript.
* Adds a "Jetpack Debug Helper" checkbox to the userscript.
p9dueE-277-p2
n/a
* Install the userscript in tools/jetpack-live-branches/jetpack-live-branches.user.js (click Raw on the GH editor view for that page).
* Go to a PR, see the live branch info following the PR description. Check the Debug Helper box and spin up a JN. Confirm the Debug Helper menu appears on the JN site that is provisioned.
* n/a, does not ship.
=> Testing Tools: Add Jetpack Debug Helper to live branches script

bin/phpcs-requirelist.js, modules/widgets/milestone.php, modules/widgets/milestone/class-milestone-widget.php, modules/widgets/milestone/milestone.php
As part of WordPress.com's work to remove/reduce jQuery deps, we discovered that the Milestone widget was not being actively fusioned with WP.com and did not get the update to remove jQuery that Jetpack committed a few months back.
* PHPCS Compliance in order to pass current WP.com linting.
* Update the version number of assets to be common to today on both platforms.
* Adds a class_exists before using the `Jetpack_AMP_Support` class since it is not presently available on WP.com.
None, but supports webperf's jQuery work.
No.
* Ensure Widgets are enabled on the Jetpack test site.
* Visit the Appearance->Widgets wp-admin page to ensure no errors. Use/edit the widget.
* View the front end of a site with a milestone widget. No errors in the console or PHP?
* Can be included as part of a …
=> Widgets: PHPCS + Fusion Milestone widget

modules/widgets/social-icons.php
[Status] Needs Review
Fixes #15162
* Fix a bug where multiple icons were shown in the Social Icons widget when the URL matched both a service domain (like wordpress.com) and the Feed URL match (like /feed/)
No
* Add Social Icons widget to widget area
* Enter URL "https://twitter.com/feed/"
* Observe that both Twitter and Feed icons are displayed
(reproduction steps also documented in #15162)
* Fixed bug causing multiple icons to display for some links in Social Icons widget
=> social-icons: only return a single icon per link

modules/widgets/milestone.php, modules/widgets/milestone/class-milestone-widget.php, modules/widgets/milestone/milestone.php
See #17802
In 17802, to comply with PHP, the file was renamed to match the role as a class definition file. Widgets are, generally, all old before PHPCS cared about such things, so most widgets follow the convention of inclusion code with the class definition in the same file.
As we progress forward with the code base, we should update the structure to match modern standards.
* Moves code around a bit to maintain separation of class definition from executing code.
n/a
n/a
* Enable Widgets for Jetpack.
* Ensure the milestone widget is available under Appearance->Widgets once done without PHP error/notice.
* n/a
=> Milestone Widget: Remove non-class code from class definition file. 

bin/pre-commit-hook.js
PR #17726 accidentally changed the behavior of the hook to only run
phpcs-changed when at least one file in phpcs-required was changed. It
should be run if any PHP file is changed.
None.
No.
* Make changes to a non-required file that will fail the linter.
* Run `node bin/pre-commit-hook.js` and see whether they're reported.
* Developer only, none needed.
=> Pre-commit: Run phpcs-changed even if no required files are changed

modules/shortcodes/instagram.php, tests/php/modules/shortcodes/test-class.instagram.php
This will allow us to provide a set of parameters that are supported by Facebook's Graph API, while everything else will get stripped away.
It also cleans up the URL that we pass to Facebook's API so only supported parameters are sent.
* Internal discussion: p1604395525052300-slack-C03AP0WBV
* Internal reference: p7H4VZ-2DU-p2
* No
Worth noting that tests will be impacted by [this Facebook bug](https://developers.facebook.com/support/bugs/730016047927322/); the `hidecaption` parameter does not result into the caption getting hidden at the moment.
* On a site connected to WordPress.com, try to embed different types of Instagram posts. I tried with those:
- `https://www.instagram.com/p/BnMOk_FFsxg/`
- `https://www.instagram.com/p/BnMOk_FFsxg/?utm_source=ig_web_copy_link`
- …
=> Instagram: introduce new function to clean up URL and params

.github/workflows/phpcompatibility-dev.yml
Github Actions [does not work well](https://github.community/t/feature-request-conditional-required-checks/16761/) when a required action uses `paths` to
skip workflow execution. But it's fine if you skip job execution with
`if`.
So switch phpcompatibility-dev to have the job check for modified files
manually rather than using Github's `paths`.
p1605116547182500-slack-CBG1CP4EN
No
* See that this PR has the "dev branch for PHP 8.0" job running.
* See that #17786 shows the job skipped, and still shows as being mergeable despite that job being required.
* Developer only, none needed.
=> Github Actions: Always run (but sometimes skip) phpcompatibility-dev

bin/version-packages.sh, composer.json
Composer 2.x sets all repositories as canonical by default. We added the `"canonical": false` setting to our local path repo in `composer.json` so that stable versions would be used when the release version of Jetpack is built. However, this causes stable versions to also be used in the development environment, which is undesirable. During development, the development versions of the packages from the current branch should be symlinked to the vendor directory.
* Remove the `"canonical": false` setting from the local path repo in `composer.json`.
*  In `version-packages.sh`, remove the local repo from `composer.json`. This will prevent development versions from being used when the release version of Jetpack is built.
(If there's a better way to do this, let me know. I'm not very familiar …
=> Build: use symlinked dev versions of packages in dev environment

.travis.yml, packages/autoloader/src/AutoloadGenerator.php, packages/autoloader/src/CustomAutoloaderPlugin.php
A few method signatures in Composer's `AutoloadGenerator` class were changed in Composer 2.0.7, making the Jetpack autoloader's `AutoloadGenerator` class incompatible with 2.0.7.
To fix this incompatibility, refactor the `Automattic\Jetpack\Autoloader\AutoloadGenerator` class so that it is no longer a subclass of `Composer\Autoload\AutoloadGenerator`.
* Remove the `composer self-update 2.0.6` command from the .travis.yml file. The changes in this PR allow the latest version of composer to be used.
* Add a `composer self-update` commend to the "Build dashboard & extensions" Travis test. The build currently uses Composer 1.5.2, which is not compatible with the changes in this PR. Since 1.5.2 was released in 2017, I don't think it's necessary to support it.
* The …
=> Autoloader: AutoloadGenerator no longer extends Composer's AutoloadGenerator class

json-endpoints/class.wpcom-json-api-update-post-endpoint.php, json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php, tests/php/json-api/test-class.json-api-update-post-endpoints.php
Summary:
Currently when you untrash a post (Set to Draft from the trash) using mobile apps. The posts comments get lots.
The apps uses the update post endpoint in order for that to happen. This process doesn't take the post though the 'untrash flow'. So we end up with missing comments.
See https://github.com/wordpress-mobile/WordPress-Android/issues/11026.
This PR tries to address this issue by update the post endpoint and setting running the wp_untrash_post() function if the post status goes from trashed to something else.
Test Plan:
- Sandbox and proxy the api. Use the iOS simulator to create a post. leave a comment on that post
- Trash the post. Restore the post using the UI in the simulator on iOS and Android.
- Notice that the comments appear as expected again.
- Notice that the post …
=> Edit Post API: Restores the post comments when untrashing a post.

packages/status/src/class-status.php, packages/status/tests/php/test-status.php
@georgestephanis asked me about if the existing regex for `is_staging_site` would pick up an URL that included a directory or an ending slash.
In #17758, I added a couple of tests to make sure that those cases were covered. But, I felt unsettled about it all.
In running the Status suite PHPUnit tests in a random order, I realized that the additions I made were actually failing because the testing environment was polluted by other tests not cleaning up after itself.
* Use `wp_parse_url` to pull out just the host to use for detection.
n/a
n/a
* `yarn docker:phpunit:package status` for automated testing.
*  Manual testing would be to setup an URL on a staging server with a directory.
* Status: improve detection of staging servers.
=> Status: Improve the staging site detection

packages/status/tests/php/test-status.php
PRs #17794 and #17820 both added mocking of WP core's
wp_get_environment_type to setUp(), but did so in slightly different
ways in different places within the method.
17794 also changed tests to depend on its specific way, but since
17820's came later it took precedence once both were merged and caused
tests to fail. Resolve the problem by removing 17820's attempt.
Also, while I'm poking at it, swap assertEquals for assertSame and have
the custom message actually print "true"/"false" rather than "1"/"".
None.
No.
* See if tests pass now.
* None needed.
=> Status: Fix test failure

packages/sync/src/modules/class-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
WP 5.6 introduces the new `wp_after_insert_post` function and action that is triggered after a post and its terms, meta have been saved. We are migrating the `jetpack_published_post` sync event to this new hook to ensure that Publicize, Subscriptions and Elastic based functionality has the complete data available to it when they are triggered.
Fixes #14629
See: https://core.trac.wordpress.org/changeset/49172
See: https://make.wordpress.org/core/2020/11/20/new-action-wp_after_insert_post-in-wordpress-5-6/
* Migrate `jetpack_published_post` sync event to trigger on `wp_after_insert_post` instead of `wp_insert_post`.
Historically WP.com dependent Jetpack functionality has run into issues with race conditions or chunked sync event processing that has lead to Publicize, Subscription Emails, …
=> Migrate jetpack_published_post to wp_after_insert_post hook

packages/connection/legacy/class-jetpack-signature.php, packages/connection/tests/php/bootstrap.php, packages/connection/tests/php/test_Signature.php
Related to this JPOP issue 6089-gh-jpop-issues
We are not handling situations where PHP variable `$_SERVER['SERVER_PORT']` is not set. We assume it is always there, but according to the PHP documentation](https://www.php.net/manual/en/reserved.variables.server.php):
```
Note: Under the Apache 2, you must set UseCanonicalName = On, as well as UseCanonicalPhysicalPort = On in order to get the physical (real) port, otherwise, this value can be spoofed and it may or may not return the physical port value. It is not safe to rely on this value in security-dependent contexts. 
```
When this value is not set, we cast it to integer and it ends up as `0` -> https://github.com/Automattic/jetpack/blob/master/packages/connection/legacy/class-jetpack-signature.php#L78
Then, when we check it further, …
=> Handle empty SERVER_PORT information on signature checks

_inc/client/at-a-glance/backups.jsx, _inc/client/at-a-glance/scan.jsx, _inc/client/security/backups-scan.jsx, _inc/client/security/jetpack-backup.jsx
Fixes 1164141197617539-as-1199174045949517
1. Fix broken redirects. Currently, all of these redirects that we are changing in this PR take users to `wordpress.com/settings/security` instead of to `wordpress.com/settings/jetpack`.
2. Have unique redirects. We are using the same redirect for multiple purposes. In some cases we want to send users to `/settings/security` but in others, we don't want that. Thus, to have more control, we decided that having unique redirects for each piece of the UI would work better.
* Fix redirects that are meant to take users to the server credentials form that are currently taking users to the Security section.
* Use a unique redirect for each place in which we want to redirect users to the server credentials form.
P2: p6TEKc-4bd-p2#comment-8702.
Ticket: …
=> Fix incorrect links to Jetpack credentials form

extensions/blocks/story/story.php
Fixes blank previews for the Story block in Calypso/the notifications panel.
It seems that at some point the notifications code is converting the line break between `<img>` and `</figure>` in the slide output into a `<br>`. This made it into the `note` structure sent by the notifications API, which for some reason made the front-end ignore the image tag and only include the `<br>` tag as a child of `<figure>` in the displayed notification, causing it to look blank as in the screenshot.
I'm not familiar enough with the notifications code to understand why this would be the case - but since merely removing the line break solves the issue and I don't see a good reason not to inline the `figure` wrapping the `img` tag, I haven't dug in any further.
No.
* Apply this patch to a Jetpack site and …
=> Remove spacing inside figure tag for Story block

extensions/shared/external-media/constants.js
Fixes #17850
The 'year' and 'month' args were passed wrapped in a single array argument to the `Date` constructor. This overload fails on Firefox. 
This started happening after Gutenberg 9.4 migrated to `dateFns` from `moment`. We still don't know why it worked before, but I have a hunch that `moment` (or other package in its dependency tree) monkeypatched/polyfilled the Data object in order to allow it to accept an array (?).
No
Run a WP instance (com or org) with Jetpack and Gutenberg 9.4.1, start a new post and watch the console for the exception. You'll also noticed JP blocks haven't loaded.
1. Apply this patch to your Jetpack instance;
1. Start a new post, be sure to have the JS console open and look for errors. A "RangeError" should not happen;
1. JP blocks should be present, test …
=> Fix Date constructor RangeError exception on Firefox when running alongside Gutenberg 9.4.1

extensions/blocks/contact-form/attributes.js, extensions/blocks/contact-form/edit.js
Fixes #17534
The form block currently displays the following default values:
* The site's admin email address as the default form submission email address.
* The phrase "A new message from your website" as the default form submission email subject.
The backend uses a different set of defaults:
* The post author's email address.
* "[_site title_] _post title_". as the email subject.
This results in confusing behavior for users. The form submissions are not sent to the expected email address, and the email's subject is not the expected subject. 
To fix this, change the email address and subject default values on the front end. The default email address should be the post author's email address, and the default subject should be "[_site title_] _post title_".
**NOTE:** The default subject is …
=> Contact Form: Use the same default email and subject as the form block

3rd-party/3rd-party.php, 3rd-party/web-stories.php, bin/phpcs-requirelist.js
The web stories plugin, outputs it's own open graph tags. In this PR, with a filter, we disable them if jetpack's open graph tags are enabled. This PR relays on [this](https://github.com/google/web-stories-wp/pull/5312 ) to merged first.
Related:  https://github.com/google/web-stories-wp/pull/5312 
Fixes https://github.com/google/web-stories-wp/issues/4913
*
* Go to '..'
*
*
=> Disable web stories open graph tags.

extensions/blocks/story/story.php
Updates the static fallback for video slides when the slide is a VideoPress video on WordPress.com, so that the poster image for the video is located and used instead of a `<video>` tag.
This already worked for Jetpack, but VideoPress data is stored differently on WP.com and requires a different method than Jetpack (I did the same treatment for post images in a preview PR, see #17198).
This change mostly affects the Reader, which relies on the static fallback for image previews in the feed list.
I also added width and height attributes to the image tag for VideoPress poster images in Stories, since the mobile Readers look for that to determine whether an image is large enough to display in the Reader list.
~Note: Targeting #17708 since there are some related changes there I want to make …
=> Story block: Fix static preview for VideoPress videos on WP.com

docs/development-environment.md
* Add the minimum supported version of composer to the development environment doc. The minimum version is 1.9.0.
* n/a
* no
This is just a documentation update. If you'd like, you can verify that Composer 1.9.0 works:
1. Install Composer 1.9.0: `composer self-update 1.9.0`
2. Remove the vendor folder and lock file: `rm -rf vendor && rm composer.lock`
3. Run `composer update` and verify that no errors are generated.
5. Update to the latest version of composer: `composer self-update`
* n/a
=> Docs: Add minimum composer version to dev env doc

bin/phpcs-requirelist.js, modules/theme-tools.php, modules/theme-tools/compat/twentytwentyone.css, modules/theme-tools/compat/twentytwentyone.php, tools/builder/frontend-css.js
See #17248 
* Ensure that no features look too out of place in the new default theme. 
**It doesn't do much, I consider this the strict minimum. We can iterate in future PRs and future releases to add support for more Jetpack features such as Content Options or Infinite Scroll**. Jetpack widgets and features don't actually look too bad out of the box imo. Only Related Posts were not aligned properly.
* pNEWy-did-p2
* No
* Start from a site running WP 5.6 Beta, either via the WordPress Beta plugin, or via `yarn docker:wp core update --version=trunk` locally.
* Go to Appearance > Themes and activate the theme.
* Go to Jetpack > Settings and activate Jetpack features that are displayed on the frontend: sharing, likes, ads, related posts
* Ensure that those features look good in all browsers. …
=> Theme Tools: add Twenty Twenty One compatibility files

extensions/blocks/podcast-player/podcast-player.php
* Our code started generating notices like this in WP 5.5.0:
> Notice: rest_validate_value_from_schema was called incorrectly. The “type” schema keyword for can only be one of the built-in types: array, object, string, number, integer, boolean, and null. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /srv/users/…/apps/…/public/wp-includes/functions.php on line 5229
The fix is to change the type to string. `url` type probably wasn't ever a thing and we had it wrong.
p8oabR-Av-p2#comment-4805
no
* In WP 5.5.0, try this branch and observe the block rendered on the frontend. Compared to the default branch, the notice should be gone.
—
=> Change URL attribute type to string

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, sal/class.json-api-site-base.php, sal/class.json-api-site-jetpack.php
This PR exposes the new `anchor_podcast` blog option introduced in D53245-code in the response of the site endpoints. This option identifies the Anchor podcast ID used in podcasting sites set up as part of the partnership between WP.com and Anchor.
By exposing this option, we allow API consumers like Calypso to perform actions based on its value (e.g. https://github.com/Automattic/wp-calypso/pull/47747).
pbAPfg-PF-p2
No.
- Apply D53313-code to your WP.com sandbox.
- Modify your `/etc/hosts` file and point `public-api.wordpress.com` to the IP of your WP.com sandbox.
- Go to the [WP.com API console](https://developer.wordpress.com/docs/api/console/).
- Make a `GET` request to `/rest/v1.1/site/:site?fields=options&options=anchor_podcast` for a site where the `anchor_podcast` option is still …
=> API: Expose `anchor_podcast` option in the site endpoint

tests/php/modules/masterbar/test-class-admin-color-schemes.php
Makes Admin Color Scheme unit tests compatible with wpcom. See D53264-code.
* Remove unneeded file import.
* Instantiates `Admin_Color_Schemes` once for all tests.
* Uses `wp_rest_request()` for wpcom compat.
* Sets user where needed.
No.
* Travis tests not failing should be enough.
None needed.
=> Masterbar: Make tests WPCOM-patible

tools/build-release-branch.sh
On my laptop, `yarn run build-production` takes about 4 minutes of wall
time, while `yarn run build-production-concurrently` takes about 2.5.
None.
No.
* Does the script still work?
* None needed.
=> Tools: Use build-production-concurrently in tools/build-release-branch.sh

extensions/blocks/slideshow/style.scss
This adds extra CSS to the Slideshow block captions to ensure they are visible in all themes.
Fixes #17911
Fixes https://github.com/Automattic/themes/issues/2835
This extra CSS will make the block larger, but it's important for the block to prevent themes overriding its styles. Another solution could be to use a different class name.
No
See https://github.com/Automattic/themes/issues/2835
* Slideshow Block: show captions in all themes.
=> Slideshow block: Force captions to have opacity

3rd-party/class.jetpack-amp-support.php
Fixes #16836.
* Added NPE check prior to updating metadata for post, in case the post data was unavailable.
At the top level, the associated filter that triggers this error is found at `3rd-party/class.jetpack-amp-support.php`:
```php
// Add post template metadata for legacy AMP.
add_filter( 'amp_post_template_metadata', array( 'Jetpack_AMP_Support', 'amp_post_template_metadata' ), 10, 2 );
```
which references the static method `amp_post_template_metadata` from file `3rd-party/class.jetpack-amp-support.php`, which is a deprecated method:
```php
/**
* Add publisher and image metadata to legacy AMP post.
*
* @since 6.2.0
*
* @param array   $metadata Metadata array.
* @param WP_Post $post     Post.
* @return array Modified metadata array.
*/
public static function …
```
=> Closes 16836 - Added NPE check for post when updating image metadata

_inc/client/components/modal/index.jsx, docs/git-workflow.md, phpunit.xml.dist, tests/php/modules/calypsoify/test-class.jetpack-calypsoify.php
See #17939
Adds an unit test to call the `mock_masterbar_activation` function to ensure it doesn't error.
As it stands, this PR will fail. Coupled with 17939, it should pass.
* Adds unit test.
n/a
No
* Unit tests should fail. You can test directly under `yarn docker:phpunit --testsuite=calyposify`
* Merged into 17939 or into `master` after that's merged, it should pass.
* n/a
=> Calypsoify: Add test to fail under 9.2

_inc/lib/class-jetpack-podcast-helper.php, tests/php/_inc/lib/mocks/class-mock-jetpack-podcast-helper.php, tests/php/_inc/lib/mocks/class-mock-simplepie-item.php, tests/php/_inc/lib/mocks/class-mock-simplepie.php, tests/php/_inc/lib/test-class-jetpack-podcast-helper.php
* this adds a new method to the helper class which allows us to find the track info for a specific podcast episode (by guid)
—
no
* `Jetpack_Podcast_Helper::get_track_data( $feed, $guid )` — this method accepts the feed URL and episode GUID
* the result is cached for an hour, per episode
* none, this is an internal helper class
=> Podcast Helpers: Add method to find specific track

modules/calypsoify/class.jetpack-calypsoify.php, phpunit.xml.dist, tests/php/modules/calypsoify/test-class.jetpack-calypsoify.php
* In #17762 and #17783 we've refactored the Masterbar, but forgot to update references to it in the Calypsoify feature, thus causing Fatal errors.
* p1606836053244800-slack-C02C4GXMY
* No
* Start from a fresh Jetpack site running this branch.
* Go to Jetpack > Settings and enable SSO.
* Go to `https://wordpress.com/posts/yoursite.com`
* Click on the button to start writing a new post.
* You should not see any Fatal errors
* WordPress.com Toolbar: avoid Fatal errors when the feature is not active.
=> Calypsoify: fix Masterbar reference after its refactor

modules/theme-tools/compat/twentytwentyone.php
This adds Content Options to TwentyTwentyOne.
Part of https://github.com/Automattic/jetpack/issues/17248
* I removed the lines for comment link, author bio and tags, as these don't appear in the excerpt.
No
* Switch to TT1
* Open the Customizer
* Open the Content Options panel
* Try changing the settings and making sure that the post content updates accordingly
* Add Content Options to TwentyTwentyOne
=> TwentyTwentyOne: Add Content Options

_inc/lib/functions.wp-notify.php, class.jetpack.php
This PR removes the necessity to check `Jetpack::is_active()` too early which can lead to Fatal errors.
`functions.wp-notify.php` is [included](https://github.com/Automattic/jetpack/blob/update%2Fremove_early_call/class.jetpack.php#L731) if the `edit_links_calypso_redirect` is present.
This file will override two WP core pluggable functions that send email notifications. Since it has to declare the function before Core does, it has to be included super early in the load.
The problem is that `functions.wp-notify.php` has a call to `Jetpack::is_active()`, which calls `Connection\Manager::is_active()` before the whole environment is loaded. For example, when this file is loaded, functions such as `get_userdata()` do not exist yet.
There's no UI for the user to set the …
=> Replace pluggable function with filter callbacks

extensions/blocks/story/icon.js
This PR updates the Story block icon as recently added to [gridicons](https://github.com/Automattic/gridicons/pull/309) repo.
Related Gutenberg-mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/2861
Related WPAndroid PR https://github.com/wordpress-mobile/WordPress-Android/pull/13534
1. use WPAndroid PR https://github.com/wordpress-mobile/WordPress-Android/pull/13534
2. create a new Post with the mobile Gutenberg editor
3. tap on + to display the block picker
4. observe the Story block shows as follows and is correctly displayed both in Android light and dark modes
**BEFORE:**
Observe the color is incorrectly set:
**AFTER:**
Observe the icon shows itself uniformly as per the rest of the block icons:
* no changelog entry needed
=> Story block: update icon

_inc/connect-button.js, class.jetpack-connection-banner.php, scss/organisms/_banners.scss
Adds a link to skip user authentication to make it easier to test the user-less connection experience.
* Adds a link to skip user authentication when no_user_testing_mode is on
p9dueE-2bJ-p2#comment-3787
No
* Start with a disconnected Jetpack
* add `define( 'JETPACK_NO_USER_TEST_MODE', true );` to your `wp-config.php`
* (option to Jurassica ninja coming soon -> https://github.com/Automattic/companion/pull/43)
* Make sure to `yarn build-client`
* Go to the Jetpack Dashboard
* Confirm the screen looks normal, with no "skip user authentication" link showing up
* Click "Set up"
* When you're prompted to authenticate the user, there should be a link to skip this step
* Click the "Skip user authentication" button
* Confirm you land in the Jetpack Dashboard
* No user testing mode: Add link to …
=> Add a link to skip user auth when on "no user testing mode"

_inc/lib/debugger/class-jetpack-cxn-test-base.php
Fixes " Warning: /home/runner/work/jetpack/jetpack/_inc/lib/debugger/class-jetpack-cxn-test-base.php:539:3: warning - Function openssl_free_key() is deprecated since PHP 8.0 (PHPCompatibility.FunctionUse.RemovedFunctions.openssl_free_keyDeprecated)" as seen in https://github.com/Automattic/jetpack/pull/17974/checks?check_run_id=1501094595
* Add conditional for PHP 8
n/a
n/a
* Confirm no warning on the PHP 8 compat check.
*
* Various: PHP 8 compatibility improvements.
=> Debugger: Do not release key on 8.0+ No longer needed.

packages/sync/src/class-defaults.php
The AMP plugin creates an amp_validated_url to store validation errors. This is not content and should not be Synced to the Cache Site.
* Disallow amp_validated_url from Jetpack Sync.
Yes, it excludes amp_validated_url content from Jetpack Sync
N/A - The blacklist have unit tests. If desired you can create a post with the blacklisted post_type and then verify the post is not on the cache site.
* Jetpack Sync - Exclude amp_validated_url content
=> Disallow amp_validated_url as it is not site content

packages/assets/src/class-assets.php
Related to #17974
* `async defer` causes browsers to use `async`, losing the benefit of `defer`.
p1607034688079500-slack-C4GAQ900
P
n/a
* tba
* Assets: Use modern JavaScript best practices for loading scripts.
=> Assets: Use defer for script tags

modules/stats.php
Fixes https://twitter.com/rick_viscomi/status/1331735748060524551
* Drop obsolete use of `type`.
* Use only `defer`.
* Skip PHPCS validation since the script should be enqueued, but that's going to be the beginning of a deep rabbit hole given how old a lot of this code is. :)
Discussed with perfops in p1607034688079500-slack-C4GAQ900P
n/a
* Logged out on a site connected to Jetpack, ensure no JS errors and that the stats were counted.
* Should not be via AMP.
* Stats: Update JavaScript loading to meet modern best practices.
=> Stats: Use only defer for script tag

class.json-api-endpoints.php
The [`wpcom_is_vip()` function](https://github.com/Automattic/vip-go-mu-plugins/blob/dfc36174ce2274def920a9ed4bf88e7d50303b35/vip-helpers/vip-deprecated.php#L1096-L1110) is marked a deprecated for VIP Go sites, and the `WPCOM_IS_VIP_ENV` constant should be used instead.
Since all of the VIP sites should be off of WPCOM by the end of the this month, it may be that the `wpcom_is_vip()` function could be removed completely.
=> Check for VIP constant before deprecated function

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
This PR emerged based on additional testing of admin menu endpoint on a site with WooCommerce enabled, after [this comment by Jeremy](https://github.com/Automattic/jetpack/pull/17629/#discussion_r532790440).
The way WP Admin generates these menu item URLs is quite intricate and replicating it for the endpoint has come with a steep learning curve. These updates get us closer to how `wp-admin/menu-header.php` generates those URLs and fixes a bunch of WooCommerce admin menu URLs as a result.
* Fixes passthrough of absolute URLs
* Generation of Core admin URLs works now like in `wp-admin/menu-header.php`.
* Fixes a bug where custom menu slugs didn't receive the correct filename prefix.
* Removes an abstraction layer in tests that led to false positives for Core admin URLs.
No.
No manual tests …
=> Admin Menu: Improve menu item url generator

modules/masterbar/masterbar/class-masterbar.php
Fixes #17989 
In #17762 and #17783 we've refactored the Masterbar, but forgot to update the reference to the script that got moved along with this.
* N/A
* No
* Go to Jetpack > Settings > Writing
* Enable the WordPress.com toolbar
* On page reload, check your browser network tools; you should see `_inc/build/masterbar/masterbar/tracks-events.min.js` load properly.
* WordPress.com Toolbar: update resources' path.
=> Masterbar: update path to tracks resource

3rd-party/class.jetpack-amp-support.php, class.jetpack.php, load-jetpack.php, packages/assets/src/class-assets.php, packages/assets/tests/php/test-assets.php
The `Jetpack` class already has a `staticize_subdomain` method one can use all across the Jetpack plugin. Let's move this to a package to keep moving things out of `class.jetpack.php`.
**Note**: I skipped the pre-commit check for my commit modifying `class.jetpack.php`, as it was triggering errors even for lines I hadn't touched.
* N/A
* No
* Install the AMP plugin on your site.
* Publish a new post without any image.
* Visit the AMP view of that post and view source: you should see the OG Image meta tag using a `https://s*.wp.com/i/blank.jpg` image.
* N/A
=> Assets: introduce new method to process static resources

packages/connection/src/class-manager.php
The user-less testing mode, at first, aimed to make a connected site behave like it had no users.
However, with this approach, we are unable to test the whole flow, especially how a user will connect to WPCOM after the site is connected only at a site level.
* No User testing mode no longer discards the user tokens
N/A
No
* Not necessary
* Not necessary
=> Userless testing mode: do not discard user tokens

docs/development-environment.md
* It shouldn't be necessary to install the WordPress Coding Standard, so remove the WPCS installation instructions.
* Add information about the Jetpack custom ruleset path to the development docs.
* n/a
* no
This is just a documentation change, so no testing is necessary. Just verify that the documentation changes are correct.
* n/a
=> Docs: Add the path to Jetpack's ruleset in the development docs

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Fixes #17977.
* Adds a second try for top-level menu items when they have submenu items available.
* Adds unit tests to make sure that a top-level item exists when there are submenu items that the user has caps for.
* Adds unit tests to make sure that top-level and the first submenu item have the same menu slug.
No.
* Run unit tests and make sure there are no failures for the admin menu tests: `$phpunit --testsuite core-api`.
* None needed. Feature not in use yet.
=> Admin Menu: Account for top-level item capabilities

modules/related-posts/jetpack-related-posts.php, modules/related-posts/related-posts.css, modules/related-posts/related-posts.js
* Uses `<time>` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time - to ensure that the dates are semantic.
* N/A
No
* Start from a connected site with Related Posts enabled and displayed on a post.
* Add `define( 'SCRIPT_DEBUG', true );` to your site's `wp-config.php` file
* Apply this branch
* Refresh post
* Ensure that related posts look the same as they do on the stable version of Jetpack.
* Related Posts: use the semantic time element when displaying dates.
=> Related Posts: Add semantic dates

_inc/lib/class-jetpack-podcast-helper.php
Part of the itunes mark-up in podcast RSS feeds, allows an image to be set per episode. This change includes these image URLs in the track data that is retrieved and sent in the API request made by the podcast player block.
* With this PR insert a podcast block
* Give it an RSS feed with images for each episode e.g. https://anchor.fm/s/22b6608/podcast/rss
* Check the network response of the API request to `/wp-json/wpcom/v2/podcast-player` it should include the `image` key for each element of the tracks array:
N/A
=> Podcast Player: Add the episode image URL to the API response.

modules/masterbar/admin-menu/admin-menu.js, modules/masterbar/admin-menu/class-admin-menu.php, modules/masterbar/masterbar/class-masterbar.php
Builds on https://github.com/Automattic/jetpack/pull/17629
Fixes https://github.com/Automattic/jetpack/pull/17629#issuecomment-725510025
* Do not load masterbar.js for sites that have nav-unification enabled. 
No
* Follow the same steps as in https://github.com/Automattic/jetpack/pull/17629
* Make sure that clicking on My Sites for desktop breakpoints does nothing
* Switch to a mobile breakpoint, clicking My Sites should open / close the mobile menu
Before | After
-------|------
* Displays a unified mobile menu
=> Ensure that masterbar.js is not loaded when nav-unification is enabled.

extensions/blocks/anchor-fm/anchor-fm.php, extensions/blocks/anchor-fm/editor.js
Fixes 313-gh-Automattic/dotcom-manage
This PR displays an outbound link in the block editor's post-publish panel that sends users to the Anchor.fm <> WP.com entry page.
pbAPfg-PF-p2
No
- Activate the beta blocks:
- If testing on a JN site, go to Settings > Jetpack Constants and turn on the `JETPACK_BETA_BLOCKS` option.
- If testing locally, add a new plugin to docker/mu-plugins with `define( 'JETPACK_BETA_BLOCKS', true );`.
- Start writing a new post and publish it.
- Make sure the post-publish panel displays a link prompting users to convert the post into a podcast episode. The link should open `anchor.fm/wordpress` in the same tab (note that Anchor has still not implemented the landing page, so the URL currently links to a podcast, see …
=> Anchor: Show outbound link after publishing a post

class.jetpack-modules-list-table.php
* For reference:
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters
cc @mzakariya 
* Primary issue: #17166 
* No
* On a site running PHP 8, go to `https://mysite.com/w/wp-admin/admin.php?page=jetpack_modules`
* The page should load without any fatals, with a list of modules.
* Dashboard: avoid errors on sites using PHP 8.
=> Module list: avoid fatals in PHP 8

modules/masterbar/admin-color-schemes/colors/_admin.scss, modules/masterbar/admin-color-schemes/colors/_gutenberg.scss
The general support for admin color schemes is being added in #17828. This specific PR extends it so the color schemes also apply to the block editor, just as core color schemes. 
* uses Sass variables to generate CSS vars the block editor uses to adjust its colors
—
No
* Follow instructions from #17828 and activate yourself some of the new color schemes
* Open the block editor and check if your color scheme has a desired effect on the editor UI. The editor doesn't change a lot but you can see those colors for example in the toolbar buttons (block inserter and publish) or form elements in the sidebar. 
A few examples of the green color propagating from the Sakura scheme:
Compared to the Sunset scheme:
—
Fixes https://github.com/Automattic/jetpack/issues/18016
=> Admin Color Schemes: Block Editor Support

bin/phpcs-excludelist.json, modules/calypsoify/class-jetpack-calypsoify.php, modules/calypsoify/class.jetpack-calypsoify.php, modules/module-extras.php, tests/php/modules/calypsoify/test-class.jetpack-calypsoify.php
Follow-up to #17939 and requires it before landing in `master`.
This PR slightly modifies the `mock_masterbar_activation` function to return the instance of the Masterbar. Functionally, this doesn't do anything, but for the sake of testing, we can confirm that the instance matches what we expect.
While in the file, PHPCS'd everything.
* Return instance for testing.
* PHPCS.
n/a
n/a
* Load up Calypsoify (see 17939 for instructions) and confirm it loads without notice/warning/error.
* Calypsoify: improve code quality.
=> Calypsoify: update mock and PHPCS

extensions/blocks/anchor-fm/editor.js, extensions/blocks/anchor-fm/editor.scss
Follows up https://github.com/Automattic/jetpack/pull/17996.
Fixes the styles of the external icon displayed in the post-publish Anchor outbound link for sites using WordPress 5.6 where the `components-external-link__icon` is missing (it has been migrated to CSS-in-JS: https://github.com/WordPress/gutenberg/pull/25751).
Before | After
--- | ---
N/A.
No.
- Activate the beta blocks:
- If testing on a JN site, go to Settings > Jetpack Constants and turn on the `JETPACK_BETA_BLOCKS` option.
- If testing locally, add a new plugin to docker/mu-plugins with `define( 'JETPACK_BETA_BLOCKS', true );`.
- Make sure your testing site is updated to WordPress 5.6.
- Make sure your testing site does NOT use the Gutenberg plugin.
- Start writing a new post and publish it.
- Make sure the external icon …
=> Anchor: Add styles for external icon displayed on the post-publish panel

.github/workflows/e2e-tests.yml, .github/workflows/php-linting.yml, .github/workflows/phpcompatibility-dev.yml
GitHub seems to have added PHP 8.0 as the default version on their job
runners, while our composer.json specifies packages that haven't been
updated for 8.0 yet.
So specifically choose 7.4 for all tests that execute composer and
aren't already specifying a version.
p1608061178463100-slack-CBG1CP4EN
No.
* Are tests green?
* None needed
=> CI: Specify PHP version for all jobs using composer

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
While it might be a good idea for `menu-header.php` to format entities, it is not for this endpoint.
This PR removes the calls to `wptexturize()` to make sure it sends out plain text characters as expected by Calypso.
Fixes #18087
*
No
Run php unit tests and make sure they pass:
`$ phpunit --testsuite core-api`
* None needed.
=> Admin Menu API: Send out plain text characters

modules/masterbar/admin-color-schemes/colors/_overrides.scss, package.json, tools/builder/sass.js
* Reintroduce the TC build for wpcom after Compass build led to issues in production
* Add color schemes overrides for nav unification (for details see https://github.com/Automattic/jetpack/issues/18092)
**For Jetpack:**
- In the Jetpack settings ensure that in the `Writing` section the `WordPress.com toolbar` option is active
- Navigate to your user profile in `/wp-admin/profile.php`
- Check if all Calypso color schemes are present
- Compare new color schemes to their Calypso counterparts
- Everything should still look as in https://github.com/Automattic/jetpack/pull/17828
**For WoA:**
- Use Jetpack Beta and activate this branch
- Everything should still look as in https://github.com/Automattic/jetpack/pull/17828
**For Simple:**
- Apply D54346-code (diff for this PR) to your sandbox
- …
=> Admin Color Schemes: reintroduce TC build and add overrides for nav unification

tools/builder/sass.js
This PR adds a new comment into the built CSS of color schemes to prevent autortl script from running on it during wpcom commits. Color scheme CSS files are universal and don't need the RTL version generated.
—
no
- checkout this branch
- `yarn build-client`
- open one of color scheme build artifacts and confirm it contains the new code comment
example file to check `_inc/build/masterbar/admin-color-schemes/colors/aquatic/colors.css`
none needed
=> Color Schemes: Prevent RTL versions of built files

sal/class.json-api-post-base.php
Summary:
A fatal error was discovered when testing an internal only page - here is the relevant part of the stacktrace:
```
Fatal error: Uncaught Error: Call to undefined function has_meta() in /home/wpcom/public_html/public.api/rest/sal/class.json-api-post-base.php:123 Stack trace: #0 /home/wpcom/public_html/public.api/rest/json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php(264): SAL_Post->get_metadata() #1 /home/wpcom/public_html/public.api/rest/json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php(130): 
```
Searching around, it seems that the `has_meta` function is defined not in `wp-includes/post.php` but rather in `wp-admin/includes/post.php`
Differential Revision: D53904-code
This commit syncs r218377-wpcom.
Fixes #
* Fixes a potential bug in the posts API endpoint, in …
=> Site Abstraction Layer - fix get_metadata function

modules/masterbar/admin-menu/class-admin-menu.php
Making the decision where to point menu item URLs filterable will allow us to ship the feature to atomic without having to wait for 9.4.
This is in preparation of https://github.com/Automattic/wp-calypso/issues/47043.
* Adds a filter to the decision point on whether menu URLs should point to Calypso or WP Admin.
No
Automated tests are probably fine? It's a noop and just shouldn't fatal.
* None
=> Admin Menu: Make link destination decision filterable

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Core updates are displayed in a submenu item to `index.php`. This PR adds compatibility for that.
So far we've only accounted for update badges in top-level menu items like "Plugins" and "Themes". But WordPress also has a submenu item with an update count called "Updates", which is visible under "Dashboard" when there are updates. This PR now correctly parses these submenu items.
/cc @getdave as this will change the response schema.
* Separate out update count parsing into its own method.
* Update item scheme to account for a `count` attribute for submenu items.
* Update unit tests for submenu items to include a case with update count.
* Add unit tests for new method.
Manual testing should not be necessary, unit tests will have it covered.
If you do want to manually test, make sure you …
=> Admin Menu: Account for update count in submenu items

modules/masterbar.php, modules/masterbar/admin-menu/class-admin-menu.php, tests/php/modules/masterbar/test-class-admin-menu.php
This PR tries to fix as many of the things @jeherve pointed out in the original PR as possible.
See https://github.com/Automattic/jetpack/pull/17629#pullrequestreview-544243248
Fixes #17973
* Updates version numbers to reflect the version this will ship in.
* Removes Scan & Backup submenu items to let Jetpack Scan handle them.
* Accounts for missing grofiles plugin on WoA sites. Falls back to `profile.php` again.
* Adds conditions for menu items that are wpcom-only.
https://github.com/Automattic/jetpack/pull/17629#pullrequestreview-544243248
No
* On your Jetpack test site, make sure you have the Masterbar module active
* Check that the Jetpack menu item doesn't contain "Scan" and "Backup" menu items anymore.
* Check that the Settings > Domains and Settings > Hosting Configuration menu …
=> Admin Menu: Follow-up tasks from initial commit

extensions/blocks/anchor-fm/anchor-fm.php, extensions/blocks/anchor-fm/editor.js
This PR applies a small refactor to the Anchor integration in order to make easier for the extension to support multiple actions at once (e.g. set the episode title as the post title and insert the Spotify badge). 
N/A.
No.
- [Spin up a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=update/anchor-disable-jp).
- Set up Jetpack (choose the Jetpack Free plan).
- Back in WP Admin, go to Settings > Jetpack constants and enable the beta blocks.
- Go to Posts > Add new.
- In the browser JS console, make sure `Jetpack_AnchorFm.actions` is an array.
- Publish the post, and make sure the post-publish panel includes a link prompting users to create a podcast episode.
- Go to `/post-new.php?anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spot …
=> Anchor: Support multiple actions

tests/php/modules/shortcodes/test-class.vimeo.php
Core introduced lazy-loading of iframes in [this changeset](https://core.trac.wordpress.org/changeset/49808). Let's take this into account in Jetpack's tests.
* N/A
* No
* N/A
=> Vimeo: account for new lazy-loading option for iFrames

modules/masterbar/admin-menu/class-admin-menu.php, tests/php/modules/masterbar/test-class-admin-menu.php
This renames "Purchases" to "Upgrades" in the new unified admin menu. It also adds the "Plans" and "Purchases" submenu items, along with moving "Domains" from "Settings" to "Upgrades".
See: https://github.com/Automattic/wp-calypso/issues/48322
Calypso changes: https://github.com/Automattic/wp-calypso/pull/47465/commits/8d37ca1c32d9ade9a6a46b66a0dfc261dd3d6f83
* Rename "Purchases" to "Upgrades"
* Add the following sub-pages:
* "Plans" (/plans/{site_slug})
* "Domains" (/domains/manage/{site_slug})
* "Purchases" (/purchases/subscriptions/{site_slug})
* Remove "Domains" from under "Settings"
pbOQVh-KN-p2
No
* `phpunit --testsuite=masterbar`
To test a simple site:
* Sync these changes with your WordPress.com sandbox and sandbox `public-api.wordpress.com`
* Follow the instructions to test the …
=> Admin Menu: update Purchases to Upgrades and add submenu

_inc/lib/class-jetpack-tweetstorm-helper.php, tests/php/_inc/lib/test-class.jetpack-tweetstorm-helper.php
When generating Twitter Cards, we need to ensure that URLs are well formed before passing them to `Requests`.
Also, the return data previously used the `Requests`-formatted URL as the result key, which could cause the card to not be shown in the preview, if the URL was typed differently.
Fixes #18103.
* Improve the URL validation and handling in `Jetpack_Tweetstorm_Helper::generate_cards()`.
N/A
No.
* Create a new Twitter thread post.
* Type some weirdly formatted URLs in the post (eg, missing protocol, capitalisation).
* Check that there are no PHP errors in your error log.
* Check that the card shows correctly in the thread preview.
I've also added unit tests for this: `yarn docker:phpunit --filter twitter_card --group external-http`
* Twitter Threads: Improve how Twitter Cards are …
=> Twitter Threads: Handle incorrectly formatted URLs when generating Twitter Cards

modules/masterbar/admin-menu/admin-menu.css, modules/masterbar/admin-menu/class-admin-menu.php
Fixes https://github.com/Automattic/jetpack/issues/18092
* Creates color-schemes specific rules for wp-admin color schemes (calypso ones will be addressed in another PR)
I will create a separate file `colors.css` on a follow up PR, I kept the changes in place for reviewing.
1) Enable nav-unification experiment
2) Apply the patch  D54314-code  
3) Change color-scheme from `https://wordpress.com/me/account`
1) Select this branch on jetpack on an Atomic site
2) Install nav-unification enabler
[nav-unification.zip](https://github.com/Automattic/jetpack/files/5703566/nav-unification.zip)
3) Change color-scheme from `/wp-admin/profile.php`
**Check the following color-schemes:**
- default
- light
-  Modern
-  Blue
-  Coffee
-  Ectoplasm
-  Midnight
-  Ocean
-  Sunrise
Known Issue: On Atomic …
=> Fix nav-unification with color-schemes implications (wp-admin color schemes)

modules/masterbar/admin-menu/class-admin-menu.php
This is a regression, when we moved the masterbar styles inside `admin-menu.css` some rules didn't apply correctly due to 
`masterbar-overrides/masterbar.css` being loaded last.
Builds on: https://github.com/Automattic/jetpack/issues/18092
Fixes https://github.com/Automattic/jetpack/issues/18083
* Adds `masterbar-overrides/masterbar.css` (loaded from wpcom) to the dependencies of `admin-menu.css` so that the latter is loaded last
* Apply D54314 to your sandbox
* Apply this patch (D54443) to your sandbox
* Enable nav-unification
* Go to /wp-admin
* Switch to mobile view
Before | After
-------|------
* Fixes styles loading order
=> Make sure that admin-menu.css is loaded last so that it takes priority in styles.

tests/php/bootstrap.php
We have a bunch of logic to try to find a copy of WordPress or
wordpress-develop. But if that fails, we wind up producing fairly
unhelpful output.
Instead, if auto-detection fails, we should output a useful message to
the user to tell them that and suggest how they might resolve the
matter.
None.
No.
* Try running `phpunit` in a setup where WP isn't in one of the auto-detected locations.
* None needed.
=> CI: Better handle failure to determine $test_root

packages/sync/src/class-replicastore.php, packages/sync/src/replicastore/class-table-checksum.php
This PR adds some improvements to the newly introduced functionality in #17567
* Properly return an empty array when the range specified with `min_id` and `max_id` is empty. Previously it returned the checksums of the WHOLE dataset.
* Add a prefix to the key fields when doing detailed checksum query as they can clash with sub-tables (i.e. `comment_id` in `comments` and `commentmeta` tables).
* Add a hardcoded `LIMIT` to return more results when doing the detailed meta checksums. In some cases there's a default limit when not specifying `LIMIT` in the query explicitly.
* As #17567
* As #17567
=> Sync: Table Checksum - improvements

packages/README.md
* Add info about textdomains to the package documentation.
We've been investigating providing a way for consumer plugins to change the textdomains in the packages. I found a couple of PRs from last year: #12525 and #12471. From the conversations in those PRs, in looks like the final decision was to let consumer plugins provide their own solution for updating textdomains in the packages.
I think this is the best approach. Consumer plugins should choose the tool and process that works best for that plugin, and there's no need for Jetpack to provide a tool for this. Instead, we should update the documentation so that consumer plugins understand that updating the textdomain is their responsibility. We can also provide links to a few tools that may be helpful, which I've done in this PR.
* no …
=> Docs: add info about textdomains to the package documentation

modules/widgets/eu-cookie-law/eu-cookie-law.js
Fixes #17560. 
There are cases when the cookie banner JS is loaded but the banner not present in the DOM (I had an example on a checkout page). Introduced in #16927, we try to access a method on `null`. When combined with JS concattenation this can cause a cascade of missing JS, causing other random failures.
1. Ensure you have extra widgets turned on in Jetpack settings.
2. Add the "Cookies & Consent" widget to your site into a widget area that's not available on all pages.
3. Accept the Cookie warning somewhere on the site.
4. Go to a page without the EU cookie in the widget area.
5. Observe that no JS error warning appears.
* Widgets: avoid JavaScript errors when displaying the Cookies & Consent Widget.
No implications.
=> EU Cookie Widget: Ensure the widget exists before trying to call a method on it

packages/autoloader/src/class-autoloader.php, packages/autoloader/src/class-plugin-locator.php, packages/autoloader/src/class-plugins-handler.php, packages/autoloader/tests/php/tests/integration/test-autoloader-scenarios.php, packages/autoloader/tests/php/tests/unit/test-plugin-locator.php, packages/autoloader/tests/php/tests/unit/test-plugins-handler.php
In #17667 we added a cache containing all of the active plugins on shutdown to prevent unnecessary autoloader resets. A consequence of this change is that deactivated plugins will be present in the autoloader cache for the first request following their deactivation. This is generally harmless since we're only populating the autoloader with their class manifests, but in some cases, it might lead to undesirable behavior. 
With WooCommerce and its autoloaded feature plugins we have the following scenario (I'll note that the impact of this is harmless but I don't see a reason we shouldn't be more defensive.):
* WooCommerce with embedded Blocks 1.1
* WooCommerce Blocks 1.2
* When the Blocks plugin is deactivated the embedded Blocks will think it is version 1.2 in the first request following …
=> Autoloader: Don't cache deactivating plugins

modules/sharedaddy/recaptcha.php
`recaptcha` script loading now defaults to `defer` instead of `async`.
Deferred scripts have better performance characteristics for our use case, since they will not block the document parser.
Previously, rendering could be blocked by the recaptcha API request, or even the full-on 140KB (gzipped) recaptcha JS request, since that's scheduled async by the recaptcha API.
* Add `script_defer` config option to sharing recaptcha
* Make `script_defer` `true` by default
* Make `script_async` `false` by default
* Modify script logic to add `defer` or `async` as configured
None.
No.
* Enable sharing and the email sharing option
* Visit any page where sharing functionality is enabled
* Look at the page HTML and find a script tag starting with `<script src="https://www.google.com/recaptcha/api.js`
* …
=> Default to `defer` instead of `async` recaptcha

json-endpoints/jetpack/json-api-jetpack-endpoints.php
The sync/settings endpoint allows remote update of sync settings to optimize sync behavior. This update allows for the enabling/disabling of checksums.
* 9.3 includes the addition of a checksum_disable option that can toggle if a site allows checksum validation. This exposes it to the sync/settings API for management.
N/A
No
Require D54844 and D54845 for testing
Verify that you can toggle the "Disable Checksums" option in Jetpack Debugger and it persists on save.
* N/A - this change is under the umbrella of Sync Checksums.
=> Add checksum_disable as a valid param of sync/settings endpoint

class.json-api.php
* REST API: properly trap wp_die in WPCOM_JSON_API_Update_Comment_Endpoint::new_comment
- Differential Revision: D53694-code
- This commit syncs r217961-wpcom.
After https://build.trac.wordpress.org/changeset/49090/ the `application/json; charset=utf-8` content-type is being recognized as json request, thus the `wp_die_json_handler` filter is being used instead of `wp_die`.
This patch covers all possible wp_die filters based on the conditional checks similar to those used inside the `wp_die` function. See https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L3351
* N/A
* No
manual
```
curl -k -H 'Host: [private link]' -H 'authorization: Bearer <Bearer>' -H 'content-type: application/json; charset=utf-8' --data-binary '{"content":"This is a unique comment"}' …
```
=> REST API: properly trap wp_die  when updating comments

modules/contact-form/admin.php
In the `grunion_ajax_spam()` method, we call `wp_insert_post()` then call `wp_transition_post_status()`. `wp_transition_post_status()` is also [called in `wp_insert_post`](https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/post.php#L4209), causing the [actions](https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/post.php#L4892) in `wp_transition_post_status()` to be fired twice.
Let's fix this by removing the `wp_transition_post_status()` calls from `grunion_ajax_spam()`.
* n/a
* no
To test this change, we’ll add a hook on the `transition_post_status` action, which is [fired](https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/post.php#L4902) in `wp_transition_post_status`. We'll use that hook to verify that the action is fired only once when a …
=> Contact Form: remove unnecessary calls to wp_transition_post_status

tests/php/modules/shortcodes/test-class.slideshow.php
In merging D49499-code, linting on WP.com failed due to the lack of `parent::tearDown()`
* Calls the parent teardown.
n/a
n/a
*
* n/a
=> Slideshow Unit Test: Parent teardown is required

modules/masterbar/admin-menu/class-admin-menu.php, tests/php/modules/masterbar/test-class-admin-menu.php
This was updated in the tracking spreadsheet but I didn't catch it until now.
Fixes #18206
* Rearranges the submenu link order between Themes and Customize menu items.
* Updates the parent slug for submenu pages
* Updates unit tests to reflect the change.
No
Jetpack:
* On your Jetpack site, enable the admin menu with `add_filter( 'jetpack_load_admin_menu_class', '__return_true' );`
* Make sure the "Appearance" menu item links to wordpress.com/themes/site_name
* Verify that "Themes" is the first submenu item and "Customize" the second.
Atomic:
* On an Atomic site, enable Jetpack beta and switch to this branch
* Enable the admin menu with `add_filter( 'jetpack_load_admin_menu_class', '__return_true' );`
* Make sure the "Appearance" menu item links to wordpress.com/themes/site_name
* Verify …
=> Admin Menu: Switch Customizer and Theme links

.github/renovate.json, packages/codesniffer/composer.json
For libraries, it's better to use ranges so as to not send your users to
dependency hell.
Also, reconfigure renovate to not pin them again. It seems that by
default it looks at the 'type' in composer.json to decide whether it
should pin or maintain ranges, and it doesn't recognize
"phpcodesniffer-standard" as a kind it should do ranges for.
None linkable.
No.
* Nothing should change. Post-merge we should make sure renovate doesn't try to re-pin the dependencies here.
* None needed.
=> Codesniffer: Unpin composer deps

extensions/blocks/anchor-fm/anchor-fm.php, extensions/blocks/anchor-fm/editor.js, extensions/blocks/anchor-fm/templates/index.js
~**IMPORTANT**: it branches off from https://github.com/Automattic/jetpack/pull/18033 https://github.com/Automattic/jetpack/pull/18064, so let's hold on.~
This PR adds a basic templating system for the episode blog post. Depending on the action name, it will render a basic template or the Spotify badge.
The basic template adds the current podcast player block, but let's keep in mind we'd like to switch to the player single podcast version once it's ready (https://github.com/Automattic/jetpack/issues/18008)
Anchor.fm: implement a basic layout for episode blog post.
361-gh-Automattic/dotcom-manage
p1607567538046400-slack-
No
* Create a new post, but passing podcast data in the query string. You can use the following URL, changing the `hostname` if  it's the case: …
=> Anchor.fm: implement a basic template for podcast blog post

extensions/blocks/conversation/edit.js, extensions/blocks/conversation/save.js, extensions/blocks/dialogue/dialogue.php, extensions/blocks/dialogue/edit.js, extensions/blocks/dialogue/style.scss
_This PR is part of the [follow-up tasks](https://github.com/Automattic/jetpack/issues/18123) after merging `conversation`/`dialogue` blocks._
This PR removes the `entry-content` class from the conversation block markup. We don't want to apply all styles defined for this class in the conversation block. ~In case we want to polish the styles, we can do it in the block itself.~
Also, it applies block properties using the `useBlockProps()` hook, and tweak a little bit some styles.
Fixes #
* Conversation: remove unneeded `entry-content` CSS class.
No
Test editing a conversation block. You shouldn't see big changes there, no bugs either.
=> Conversation: remove unneeded `entry-content` CSS class

.github/workflows/linting.yml, docs/development-environment.md, jetpack.php, projects/plugins/jetpack/LICENSE.txt, projects/plugins/jetpack/readme.md, projects/plugins/jetpack/readme.txt, readme.md, tools/check-copied-files.sh, tools/pre-commit-hook.js
People used to the old way of doing things may try to check out the monorepo directly in their WordPress `wp-content/plugins` folder, or they may already be doing so. That will no longer work to install Jetpack.
To make the failure case a little more user-friendly, we add a dummy `jetpack.php` to the monorepo root so WordPress will find a plugin. All this plugin does is display an admin notice telling the user they're doing it wrong and pointing them to relevant documentation on how to do it right.
Said documentation needs to exist. So this PR also moves the existing Jetpack readme.md to the Jetpack plugin, and creates a new readme.md for the monorepo in the monorepo root. Once we get to the point of creating the built "Automattic/jetpack-production" mirror repo, the Jetpack-specific …
=> Reorg: Add a dummy "jetpack.php" to the monorepo, and update docs

extensions/blocks/anchor-fm/templates/index.js
~IMPORTANT~
=========
~This PR was branched off https://github.com/Automattic/jetpack/pull/18046, so let's hold on until #18046 merges.~
This PR adds is part of the anchor.fm -> WordPress.com flow, adding a `conversation` block when a new site episode post is created.
Fixes #
* Anchor.fm: add conversation block to simple template
No
* Create a new post, but passing podcast data in the query string. You can use the following URL, changing the hostname if it's the case:
http://localhost:8888/wp-admin/post-new.php?action=edit&anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spotify_show_url=https%3A%2F%2Fopen.spotify.com%2Fshow%2F6HTZdaDHjqXKDE4acYffoD%3Fsi%3DEVfDYETjQCu7pasVG5D73Q
* Among some blocks, you should see the `conversation` block, with the …
=> Anchor.fm: add conversation block to simple template

extensions/blocks/conversation/edit.js, extensions/blocks/dialogue/edit.js
_This PR is part of the [follow-up tasks](https://github.com/Automattic/jetpack/issues/18123) after merging `conversation`/`dialogue` blocks._
This PR improves the UX when creating new `dialogue block.
Fixes #
* Dialogue: improve UX when creating new blocks.
No
* Create a new `conversation` block
* Edit the participant names in order to make the testing easier to understand
* Confirm that it creates a new dialogue block when pressing ENTER, where
* it picks up the next participant from the conversation block. If it's the last one, it will pick the first in the list.
* If it breaks the block in the middle, the text os properly applied to both blocks 
* It copies the timestamp of the selected block
* It behaves similarly when the new diaogue block is inserted and the previous block is a …
=> Dialogue: improve UX when creating new blocks

modules/masterbar/admin-menu/class-admin-menu.php, tests/php/modules/masterbar/test-class-admin-menu.php, tests/php/modules/masterbar/test-class-atomic-admin-menu.php, tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes #18216
As [this spreadsheet](https://docs.google.com/spreadsheets/d/1i640dQt4vs2XYgqRA4YEH69ssR9UNcFJx49HUss0-q0/edit#gid=0) suggests, Settings should redirect to Calypso.
* Changes link direction of Setting menu to Calypso rather than wp-admin
* Enable nav-unification (paYJgx-1af-p2)
**Simple**
* Apply D54949-code in your sandbox
**Atomic**
* Use Jetpack Beta and select the current branch
**Result:**
* Inspect the Settings submenu, nothing should have changed except from the fact that Settings redirects to calypso now
run `yarn docker:phpunit --filter Admin_Menu`
* Settings menu now redirects to Calypso Settings when Dashboard Customizations are enabled.
=> Redirect Settings menu to calypso

extensions/blocks/conversation/edit.js
This PR sets the `hasBoldStyle` attribute as default when a new participant is added.
Fixes #18222
* Conversation: set bold format for new participant
* Create/edit a new conversation block
* Add a new participant
* Add a new dialogue block, setting the participant with the new one
* Confirm that it is bold as default.
before | after
-------|-----
Take a look [at this video](https://github.com/Automattic/jetpack/pull/18176#issuecomment-755414890) to see the issue.
n/a
=> Conversation: set bold format for new participant

extensions/blocks/dialogue/edit.js
This PR implements an auto-focus behavior to the dialogue block. It will happen when:
1) block is mounted
2) block is selected
3) block is not empty
Fixes https://github.com/Automattic/jetpack/issues/18228
* Dialogue: focus on content when it's convenient
https://github.com/Automattic/jetpack/pull/18176#issuecomment-755746402
No
* Try to test the experience described [here](https://github.com/Automattic/jetpack/pull/18176#issuecomment-755746402). Confirm that now, every time that dialogue block is created, it makes focus on the block content component.
n/a
=> Dialogue: focus on rich text component when created

modules/sharedaddy/sharing-service.php
Follow-up to #17864
In 17864, the JS was refactored to no longer depend on jQuery; however, we missed removing the dependency from the enqueue.
See D55030-code for the discovery while getting everything back in sync with WP.com.
* Remove jQuery dep.
n/a
n/a
* Same as #17864
* none, to be handled via 17864.
=> Sharing: JS is no longer dependent on jQuery

extensions/blocks/story/player/style.scss
During Story playback, limits the post title displayed at the top to two lines to prevent overflowing text for long titles:
No.
* Create or edit a story and give the post an extremely long title
*Play the story and verify that 
* Check a few other browsers (I've checked Mac Chrome, Firefox, and Safari, Android Chrome, iOS Safari, and Edge).
No changelog needed.
=> Story block: Limit title length during playback

modules/shortcodes/crowdsignal.php
When embedding a Crowdsignal survey in the block editor it doesn't use the shortcode to fetch the embed code, but when the post is saved the shortcode is run. The survey link was incorrect because it was expecting a URL in a different, older format we don't use any more. This patch supports calling the shortcode normally, and by the block editor REST API.
Ref: p1609789666043200-slack-C01CSBEN0QZ
No
In modules/shortcodes/crowdsignal.php go to the end of the crowdsignal_shortcode function and just above "return $this->get_async_code" add error_log( "survey_url: $survey_url" );
Create a post and paste a Crowdsignal survey URL (Try http://donncha.survey.fm/test-test-3 if you don't have a CS account) into a block.
Click "Save draft" and you should see the broken survey URL in your error log. …
=> Crowdsignal: update shortcode survey URL in using block editor

.github/actions/update-project/update-project.sh, .github/workflows/update-project.yml
In this branch, we take the monorepo and spit out a built version of jetpack to the https://github.com/automattic/jetpack-production mirror repo.
This is a not-DRY modification and duplication of the package->mirror script that is already used in production with some changes.
- For anything with a `package.json` file, it will run `yarn build-production-concurrently` so if we need JS build steps for a package before being available for clients outside of the monorepo, this could handle that as long as the package as that script defined. This is a bit hacky since if there is a package.json and it doesn't have that script, it'll break. I think we need a datastore for each project's canonical best development and production build scripts. I'd like to tackle that outside of this though.
- It …
=> Reorg: Write to jetpack-production

modules/masterbar/admin-menu/class-wpcom-admin-menu.php
Stat chart seems to be tied to site URL and not the publicly domain.
See https://lobby.vip.wordpress.com/wordpress-com-documentation/home_url-vs-site_url/
Props @RealCarFax.
Fixes #18299.
* Use `site_url` rather than `home_url`. 
Before | After
------------ | -------------
No
* Apply the phab diff to your sandbox and sandbox a site with a custom domain and without a custom domain
* With Nav Unification active, make sure that both sites have the stats graph show up correctly.
* None needed.
=> Masterbar: Use site_url for stats chart

modules/sharedaddy/recaptcha.php, modules/sharedaddy/sharedaddy.php, modules/sharedaddy/sharing.js, tests/php/modules/sharedaddy/test-class.recaptcha.php
When an email sharing button is present, reCAPTCHA currently gets loaded unconditionally on page load. This can be problematic, since it uses a large amount of JS, which needlessly competes for resources during the critical page load time.
This PR instead delays reCAPTCHA loading until a user actually clicks to open the email sharing dialog, ensuring that only this tiny percentage of users pays the JS cost, and at a much less critical time.
* Add lazy loading option in `recaptcha.php`.
* Use lazy loading option in email sharing
* Add test for lazy loading option
Note: the lazy loading option is not enabled by default in `recaptcha.php`, so that it doesn't affect some files that make use of `recaptcha.php` and live outside of Jetpack. It's instead explicitly enabled it in `sharedaddy.php`. …
=> Lazily load reCAPTCHA for email sharing

bin/pre-commit-hook.js
ESLint likes to whine if you pass it a file that's in .eslintignore, and
doesn't provide any way to override this behavior (unlike every other
linting rule).
Fortunately it uses a library called 'ignore' to process .eslintignore,
and our pre-commit check uses JS too so we can just use that library to
filter out ignored files.
p1610428080226800-slack-CBG1CP4EN
No.
* Make a change to a file listed in .eslintignore
* `git add` the file
* Try to commit, or run `node bin/pre-commit-hook.js` manually. It should succeed, and either shouldn't even run eslint or run it while only passing other files you might have modified. It's ok if it runs eslint-changed, that tool will ignore the bogus warning.
* None needed.
=> Pre-commit: Don't run eslint on ignored files

modules/seo-tools/jetpack-seo.php
Fixes a notice seen on w.org:
```
E_NOTICE: Trying to get property 'taxonomy' of non-object in /home/public_html/wp-content/plugins/jetpack/modules/seo-tools/jetpack-seo.php:138
```
* Verify that the variable in an object and has the expected properties.
n/a
no
* Haven't duplicated it yet.
* SEO Tools: prevent a PHP notice in some situations involving taxonomy or author pages.
=> SEO Tools: Defensive coding to prevent notices

tools/cleanup-excludelists.sh
The cleanup tool uses `mktemp` which has different accepted args on Linux vs OS X. On OS X, there is no `tmpdir` arg, so the `cleanup-excludelist.sh` script fails.
* Removes the args, which works on OS X.
n/a
No.
* On OS X, run `./tools/cleanup-excludelist.sh`.
* On Linux, run `./tools/cleanup-excludelist.sh`.
I haven't tested this on Linux.
* n/a
=> Allow cleanup tool to run on OSX

3rd-party/class-domain-mapping.php
Follow-up from #18061
Our changes in namespacing caused this issue, since we're relying on an external class here.
* N/A
* No
This requires a bit of a setup, since you'd need to be using [this plugin](https://github.com/wpmudev/domain-mapping) on a Multisite instance.
Once you've set that up, you shouldn't see any Fatals on your site.
* Multisite: avoid Fatals on sites using WPMUDEV domain mapping
=> Multisite: avoid Fatals on sites using WPMUDEV domain mapping

.github/workflows/update-project.yml
If two PRs get merged at about the same time, GitHub will happily run
the workflows in parallel and the two might wind up stepping on each
other.
Avoid this by including an action that waits for earlier instances of
the workflow to finish before proceeding.
None.
No.
* Merge this.
* Merge two other PRs at the same time.
* See if the second one's run stops at the "Wait for prior instances of the workflow to finish" step until the first finishes.
* None needed.
=> Mirror repos: Avoid concurrent workflow runs

_inc/client/.eslintrc.js, _inc/client/at-a-glance/stats/dash-stats-bottom.jsx, _inc/client/components/footer/index.jsx, _inc/client/components/jetpack-notices/state-notices.jsx, _inc/client/security/backups-scan.jsx, _inc/client/setup-wizard/updates-question/index.jsx
Now that we're using core WordPress translation functions, let's add linting to ensure that we use those functions properly.
* N/A
* N/A
* Does the linting test pass?
* N/A
=> Admin Page: lint all files for @wordpress/i18n errors

.github/workflows/update-project.yml
During the reorg work, we had Github push to a branch of the mirror repos. We no longer need this.
* Removes temporary code.
n/a
n/a
* None
*
* n/a
=> Reorg: Remove temp branch from executing action

.github/workflows/build-artifacts.yml
* Removes the step to build to `master-built`. We deprecate that and push everyone to https://github.com/automattic/jetpack-production
* Set the retention time for the artifact to 1d. The beta server grabs the zip and saves it there, so we don't need it for any length of time.
n/a
n/a
* Check the action log.
*
* n/a
=> Actions: Improve build-artifacts

package.json
We shouldn't have two projects named the same.
* Some build tools will balk at two projects with the same name. The renames the monorepo.
p1610704784177500-slack-CBG1CP4EN
n/a
* n/a
*
* n/a
=> Reorg: Rename root-level project

projects/plugins/jetpack/_inc/client/.eslintrc.js, projects/plugins/jetpack/_inc/client/traffic/site-stats.jsx, projects/plugins/jetpack/extensions/.eslintrc.js, projects/plugins/jetpack/extensions/blocks/contact-form/index.js, projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/mailchimp/edit.js, projects/plugins/jetpack/extensions/blocks/pinterest/edit.js, projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx, projects/plugins/jetpack/extensions/blocks/story/edit.native.js, projects/plugins/jetpack/extensions/blocks/subscriptions/edit.js, projects/plugins/jetpack/extensions/blocks/videopress/edit.js
Now that we've added an eslint plugin to monitor for i18n issues in our js files (see #16455 and #16516), let's start enforcing a rule: translatable strings should always include the jetpack textdomain.
This PR adds the rule to both the React dashboard and the extensions, and fixes instances where we had wrong strings until now.
* N/A
* No
* Check the different blocks impacted by the change; the strings should remain correct.
* N/A
=> i18n: enforce the use of the jetpack textdomain

projects/plugins/debug-helper/composer.json
A miscommunication on #18317 led to the file not being included, but
then thinking it had been #18355 removed the ability to mirror without a
composer.json.
We're all agreed we want a composer.json here, so let's add it now. We
can always edit it again after p9dueE-2l9-p2 reaches a decision.
#18317
No.
* Check the build artifacts, see that Automattic/jetpack-debug-helper is included and has expected contents.
* None needed.
=> Debug-Helper: Add composer.json so it will be mirrored

projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php, projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php
This PR fixes a PHP notice when trying to fetch user connection data while a connection owner does not exist (user-less).
* Updates the `get_user_connection_data` method in `Jetpack_Core_Json_Api_Endpoints` to properly handle cases where the connection owner does not exist.
* Adds a corresponding unit test 
No
**Before applying this fix:** 
* Start with a fresh Jetpack site
* Enable user-less connection mode by setting `JETPACK_NO_USER_TEST_MODE` ( in `wp-config.php` or via Settings -> Jetpack Constants)
* Set up Jetpack in user-less mode (aka skip user authentication)
* Go to Jetpack Dashboard and notice the following notice when fetching: `jetpack/v4/connection/data`:
The notice will be visible either in `debug.log` or in your browser console, Network tab -> XHR -> `GET …
=> REST API: Fix user connection data without owner

projects/plugins/jetpack/extensions/shared/components/audio-player/index.jsx
It was seen that if you click around on the timeline of the audio
player, that from time to time, the click will be ignored and the audio
will jump back to the previous position.
This change updates the options passed to `throttle` as the problem
seemed to be caused by the prop changing every second and a click
happening within the second, this led to two calls to the throttled
function, on the leading and trailing edge of the time period.
It's probably not strictly necessary, but it also cancels the throttled
function in the unmount callback of the `useEffect`.
* Insert a podcast block and set it up with an RSS feed.
* Set an episode playing and click around on the timeline.
* From time to time you should see that the time change event on the timeline gets ignored and it jumps back to …
=> Audio Player: Fix the firing of multiple conflicting time changes

.github/workflows/build.yml
GitHub's artifact mechanism does not preserve file permissions (or case,
but presumably if that were a problem we'd have known about it before
now).
The [official workaround](https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files) is to use `tar` to collect your files and
upload that archive file as the artifact. So let's do that. As a bonus,
it might speed up the artifact upload and download.
None.
No.
* Look at the "jetpack-build" artifact in the Build workflow. Yes, unfortunately it'll download the .tar.xz inside a zip. [There's no way around that](https://github.com/actions/upload-artifact#zipped-artifact-downloads).
* Post-merge, see if the mirroring made https://github.com/Automattic/jetpack-codesniffer/blob/master/tests/php/ci-can-run.sh …
=> Mirroring: Preserve file permissions by uploading a .tar.xz as the build artifact

projects/packages/tracking/legacy/class-jetpack-tracks-client.php
The `Jetpack_Tracks_Client::get_connected_user_tracks_identity` method currently calls `Jetpack::get_connected_user_data`. This prevents the Tracking package from being used without Jetpack. If a consumer plugin called this method without Jetpack installed on the site, a fatal would occur.
The Connection package provides the `Manager::get_connected_user_data` method. The two `get_connected_user_data` methods are the same, so use Manager's method instead.
* n/a
* no
1. Install this branch, activate Jetpack, and connect.
2. The `Jetpack_Tracks_Client::get_connected_user_tracks_identity` method [is used](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php#L322) in 
`Jetpack_React_Page::get_initial_state`. Navigate to …
=> Tracking: get connected user data from the Connection package

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
When syncing #18305 to dotcom, phabricator rightfully complained about `$menu` being undefined. I lifted the code from Core's `wp-admin/menu.php` where it is defined earlier, but the `isset()` check surrounding it prevents the missing variable to be noticed.
The fix was committed to dotcom in r219509-wpcom, so this PR just syncs it back to Jetpack.
* Updates `$menu` to reference the `$GLOBALS` global.
No.
* Not really needed I think.
None needed.
=> Masterbar: Fix undefined variable

projects/plugins/jetpack/extensions/blocks/story/player/progress-bar.js, projects/plugins/jetpack/extensions/blocks/story/player/style.scss
A few fixes to playback for the Story block:
* There is an intermittent issue on some browsers (mostly Chrome it seems) where the background scrim flickers when playing a story. The background has two layers: a blank, black background and the current slide magnified and blurred. We found that simply hiding the blurred slide and just keeping the blank background seems to resolve the issue, so going with that for now.
* The ellipsis behavior during playback for long stories introduced in #17708 was incorrectly being applied in some cases to shorter stories, causing odd behavior. Here's a demonstration for a three-slide story:
This looks to have been a calculation error, and was only happening for odd-numbered stories below the max bullet limit. Should be resolved by this PR.
No.
* The …
=> Story block: Playback fixes

.github/workflows/build.yml, .github/workflows/code-coverage.yml, .github/workflows/codeql-analysis.yml, .github/workflows/composer.yml, .github/workflows/dangerci.yml, .github/workflows/e2e-tests.yml, .github/workflows/gardening.yml, .github/workflows/js-tests.yml, .github/workflows/linting.yml, .github/workflows/phpcompatibility-dev.yml, .github/workflows/phpunit.yml, .github/workflows/required-review.yml
I started by looking at the last few successful runs of each job to get
an idea of how long they tend to take, then added some extra based on
gut feeling so most of the numbers wound up rather arbitrary.
Feel free to change them if something seems off. Hopefully this doesn't wind up being a major source of test flakiness in the future.
Team meeting 2021-01-18. 1138708815542418-as-1199606265177798
No.
* Do tests run, and seem to have enough headroom on the timeouts?
* None needed.
=> CI: Add timeouts for all jobs

projects/plugins/jetpack/extensions/blocks/dialogue/dialogue.php
replace `wp_kses` with `wp_kses_post`.
Fixes #18298
* Dialogue: replace wp_kses with wp_kses_post.
No
* Check the dialogue content is parsed properly by the server-side, confirming that the block content looks good ni the front-end.
n/a
=> Dialogue: replace wp_kses with wp_kses_post

projects/plugins/jetpack/extensions/blocks/publicize/form-unwrapped.js, projects/plugins/jetpack/extensions/blocks/publicize/form.js, projects/plugins/jetpack/extensions/blocks/publicize/store/selectors.js
When a post has a title added, the Publicize "Customize your message" input will autofill with that post title if a custom sharing message has not already been set.
Currently, if a post has a title added, and users select and then try to delete (not type over) all of the text in the custom sharing message input, it will immediately fill with the post title text.
This change will track if the custom message input has been edited, and if it has, allows a user to select and delete all text, even when the post has a title added to it.
* Allow fully clearing the Publicize custom message even if a post title has been set. Not being able to delete all selected text can be confusing to users.
* None, open to discussion
* No
* After pulling down proposed changes, make sure to rebuild Jetpack (e.g. …
=> Publicize: Allow clearing Publicize custom message if a post title has been set

projects/plugins/jetpack/modules/infinite-scroll/infinity.php
* Busts cache to stay in sync with WP.com.
The JS has some major differences, so this is just to keep the PHP in sync until the JS can be tackled.
See D54641-code
No
* None
* n/a
=> Infinite Scroll: Bust cache

projects/plugins/jetpack/extensions/blocks/dialogue/style.scss
Fixes #18277 
* Wrap the participant names in a fixed-width column.
Before | After
------- | ----
https://github.com/Automattic/jetpack/pull/18348
N/A
* Connect a test site to Jetpack and enable beta blocks.
* Add a Conversation Block to a post.
* Select one of the Dialogue Blocks in the Conversation Block
* In the Block settings sidebar, select the "Column" style.
* Check the alignment with "Show conversation timestamps" both enabled and disabled:
* Check that the "Row" style is aligned and unaffected.
* No changelog entry needed; this is an update to the Conversation & Dialogue blocks that are in beta.
=> Dialogue block: Fix dialogue column alignment

projects/packages/connection/legacy/class-jetpack-xmlrpc-server.php, projects/plugins/jetpack/tests/php/general/test_class.jetpack.php
This PR adds the possibility to make an XMLRPC request to `jetpack.disconnectBlog` using a blog token. User token is still supported.
* Moves the `jetpack.disconnectBlog` outside of the login logic in `Jetpack_XMLRPC_Server`
p9dueE-1VI-p2
No
**Manual**
27e39-pb/ (OneBin)
**Automated**
```
phpunit --filter=test_classic_xmlrpc_when_active_and_signed_with_no_user
```
* No changelog entry needed: The `jetpack.disconnectBlog` method now is also accessible with a blog token (WPCOM)
=> Connection: Accept blog token on 'jetpack.disconnectBlog'

tools/docker/mu-plugins/.gitignore, tools/docker/mu-plugins/fix-monorepo-plugins-url.php
Since our Docker environment will probably have the monorepo packages
symlinked, WordPress's `plugins_url()` can't find the plugin their paths
belong to and so winds up including the full path in the URL.
This adds a mu-plugin that filters `plugins_url()` for this case,
adjusting the passed `$plugin` to go through the symlink in Jetpack's
vendor directory.
p9dueE-2ms-p2
No.
* Using the Docker dev environment, open the Jetpack Dashboard, look for the `<link rel='stylesheet' id='jetpack-jitm-css-css'`, and make sure it points to a correct URL.
* Try the same in other environments, e.g. Jurassic Ninja.
* None needed.
=> Docker: Add a mu-plugin to fix monorepo package URLs

projects/plugins/jetpack/extensions/blocks/conversation/edit.js
Fixes #18431
* Remove useBlockProps to fix WordPress 5.5 compatibility issue
https://github.com/Automattic/jetpack/pull/18247#issuecomment-759651672
N/A
* Connect a site to Jetpack and enable beta blocks.
* Use the Jetpack Live Branches WP Downgrade option or the [WP Downgrade plugin](https://wordpress.org/plugins/wp-downgrade/) or `yarn docker:wp core update —version=5.5 —force` to downgrade to WordPress 5.5
* Add a Conversation block to a post.
* Inspect the block div and check that it has this class: `wp-block-jetpack-conversation`
* Check that the block is functional and has the same class in WordPress 5.6
For reference, this is what the div looked like before:
* No changelog entry needed; this is an update to a beta block.
=> Conversation: Fix Block Doesn't Load When Running WordPress 5.5

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
With the changes in this PR, the app will check if the `jetpack/conversation` block is available before building the episode template. In case the block is not available, it will create a fallback composition based on core blocks.
Fixes #
* anchor.fm: check conversation block availability
No
* Try to recreate a scenario where anchor.fm extension is available but conversation block is not. 
* Use a similar link to the following to create a new episode post:
`http://localhost/wp-admin/post-new.php?action=edit&anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spotify_show_url=https%3A%2F%2Fopen.spotify.com%2Fshow%2F6HTZdaDHjqXKDE4acYffoD%3Fsi%3DEVfDYETjQCu7pasVG5D73Q`
* You should see the basic template rendered, but the _Transcription _ section will be composed of …
=> anchor.fm: check conversation block availability

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php
This fixes a bug on dotcom, where submenu items didn't get the correct parent prefix associated with their page hook. That resulted in menu URLs being computed incorrectly, essentially just returning their menu slug.
I _think_ the bug was introduced with https://github.com/Automattic/jetpack/pull/18376, but I can't say for sure. Reverting it locally didn't seem to change anything. I'm also not sure which globals really need declaring ahead of generating the menu, so far we've opted for a more conservative approach where we add globals as needed to fix bugs or maintain parity with wp-admin's output.
* Imports `$admin_page_hooks` global before generating the admin menu.
No
* Apply D55665-code on your wpcom sandbox and sandbox public-api
* With nav unification activated, load your test site …
=> Admin Menu: Declare admin_page_hooks global

projects/plugins/jetpack/_inc/client/components/jetpack-termination-dialog/features.jsx
Fixes #18391
* Let's ensure that we display the right string regardless of the language and the number of connected plugins.
* N/A
* No
* Start from a site connected to WordPress.com and running this branch.
* Add and activate a test plugin like this one:
```php
<?php
/** Plugin Name: Jetpack Connection Test Plugin (1) */
( new Automattic\Jetpack\Config() )->ensure(
'connection',
array(
'slug' => 'jetpack-connection-test-1',
'name' => 'Jetpack Connection Test Plugin (1)'
)
);
}, 1 );
```
* Go to Jetpack > Dashboard, and click on the Manage connection link towards the end of the page.
* You should see this:
* Now add and activate a second plugin:
```php
<?php
/** Plugin Name: Jetpack Connection Test Plugin (2) */
add_action( 'plugins_loaded', …
```
=> Admin Page: better handle i18n for disconnection warnings

projects/plugins/jetpack/modules/carousel/jetpack-carousel.js, projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
* The refactor of the Gallery block changes the block structure so this PR adds additional selectors so the block will be compatible with the slideshow block if and when it lands
No
- Check the [Gallery refactor PR](https://github.com/WordPress/gutenberg/pull/25940) to a local Jetpack dev env
- Switch on the option to `Display images in a full-screen carousel gallery` in Jetpack Settings -> Writing
- Add a gallery with images and view in front end and notice that clicking on an image does not open the carousel
- Check out this PR and reload the gallery front end and the carousel should now launch and the first image shown should be the one that was clicked on
- Also check that Images that have a custom link added link through to the custom link instead of opening the carousel
- Change the …
=> Add additional selectors to allow slideshow to work with Gallery block refactor

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-feed-locator.php, projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php, projects/plugins/jetpack/tests/php/_inc/lib/mocks/class-simplepie-file.php, projects/plugins/jetpack/tests/php/_inc/lib/mocks/class-simplepie-locator.php, projects/plugins/jetpack/tests/php/_inc/lib/test-class-jetpack-podcast-feed-locator.php
Currently, we use `SimplePie`'s default feed locator when a URL that isn't an RSS feed is used in the podcast player block. This means that it can pick up an RSS feed for comments, a category of posts, or something else that isn't the feed of podcast episodes.
This PR implements a custom locator class which checks for either the use of the itunes.com namespace in the feeds found, or `enclosure`s with an `audio/` mimetype.
No
* Insert a podcast block
* Provide a URL to a podcast site which has more than one feed. An [example is this site](https://www.tested.com/podcasts/adam-savage-project/amber-ruffin-the-adam-savage-project-11-17-20/), which on the episode pages only has the podcast feed as the `href` of the 'Subscribe' buttons.
* Without this PR the block is converted to a WordPress …
=> Podcasts: Add extra checks to the feed detection

projects/plugins/jetpack/extensions/blocks/dialogue/attributes.js, projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
This PR introduces some changes in order to enhance the block participants edition.  Most releat changes:
* Remove participants dropdown from the editor canvas
The participants dropdown has been removed from the editor canvas, in the Dialogue context.
* Add participants dropdown in the block toolbar.
* Remove custom participant from `Dialogue` block:
All participants belong to the conversation block, which means are edited globally in that context. From the `Dialogue` context, the user just can pick up from the block toolbar.
**Screenshot**
Fixes https://github.com/Automattic/jetpack/issues/18283
* Conversation/Dialogue: handling participants enhancements 
No
* Create a conversation block with some dialogue blocks there
* Confirm the changes introduced by this PR
Before | After …
=> Conversation/Dialogue: handling participants enhancements 

projects/plugins/jetpack/extensions/blocks/dialogue/components/timestamp-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/editor.scss, projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js, projects/plugins/jetpack/extensions/shared/components/audio-player/index.jsx, projects/plugins/jetpack/extensions/shared/components/media-player-control/index.js, projects/plugins/jetpack/extensions/shared/components/media-player-control/style.scss, projects/plugins/jetpack/extensions/shared/icons.js, projects/plugins/jetpack/extensions/store/media-source/storeDefinition.js
Integrate with the Dialogue block with podcast player. Add MediaPlayerControl.
Fixes https://github.com/Automattic/jetpack/issues/18344
* Dialogue: media control player integration
No
* Create/edit a post from the block editor.
* Add a podcast player.
* Add a transcription block.
* Confirm you see the media player control in the block toolbar
* Confirm play/pause work as expected.
* Confirm jump back/skip forward buttons work as expected (five seconds), changing the audio player time.
* Confirm player display is consistent with the podcast player
* Confirm the `Keep in-sync` mode works as expected:
- When it's activated, the `timestamp` value changes according to the current time of the player
- When it's activated, the TimestampControl gets disabled in order to avoid _out of sync_ and/or …
=> Dialogue: media control player integration

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
This PR set the podcast player vertically aligned in the middle with respect to the column when the episode is created.
Fixes #18469
* Anchor.fm: align podcast vertical int the middle
No
* Start to create a new episode from anchor.fm
* Confirm that the podcast player is vertically aligned in the middle of the column
Aligment toolbar button | Middle is activated
n/a
=> Anchor.fm: align podcast vertical int the middle

projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php
The way user meta data is saved was recently changed on Atomic (590-gh-Automattic/wpcomsh). This PR updates the atomic-admin-menu class to obtain the information it needs from the new sources.
* Replaces uses of `Connection_Manager::get_connected_user_data()` with a new user option.
* Updates unit tests to use the new user option.
No.
* Use the Jetpack Beta plugin on an Atomic site and switch to this branch.
* Verify that the "Browse Sites" link still shows up when you have more than one site.
* Verify that the "Add new site" link still shows up when you don't have more than one site.
Not needed.
=> Masterbar: Use user_option rather than Connection_Manager

projects/packages/sync/src/replicastore/class-table-checksum.php
The previous way where we select a single row from the table and then check the returned fields, doesn't work very well in two cases:
1. When there is no data in the table, which will result in an empty response and the validation will fail
2. When there is too much data in the table and the DB will reply with `The SELECT would examine more than MAX_JOIN_SIZE rows;`
This way we only fetch the columns from the table and it isn't prone to the cases above.
* Fetch field/column names by using `SHOW COLUMNS FROM <table>` and validate against it
N/a
N/a
* Apply diff to your WPCOM sandbox and Jetpack site
* Make sure that the checksum process works correctly
* Jetpack Sync: Better field name validation when calculating checksums on tables.
=> Jetpack Sync: Checksums: Use a better way to fetch and validate fields against table

projects/plugins/jetpack/extensions/blocks/dialogue/style.scss
This PR fixes an issue about the color of the participant and timestamp label of the Dialogue component, in the editor canvas context.
Fixes https://github.com/Automattic/jetpack/issues/18488
Dialogue: fix participant and timestamp color issue
No
* Install and activate the Spearhead theme
* create/edit a conversation block.
* Confirm now you see the participant and timestamp there
before | after
------|-------
*
=> Dialogue: fix participant and timestamp color issue

projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php, projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
Fixes #18477
This change passes the cover art URL and the feed URL to the front end so that they can be used when populating the podcast episode template. 
This is a bug fix.
No
As explained in #18477:
* Go to ` /wp-admin/post-new.php?anchor_episode=89113006-542a-11eb-b4f3-c3757114ae55&anchor_podcast=5243218` on a development site with beta extensions enabled.
* Notice that the cover image block and the podcast player are both displayed as placeholders
* Apply this change and go to the above URL again. The new post should have blocks set up correctly.
Not needed as this is a bug with a feature that's not yet launched.
=> Anchor.FM: Pass the cover art and feed URL to the episode template

projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php
* Avoid a PHP notice when trying to display plan information about a site without a plan.
* N/A
* No
* Create a new Ephemeral site with the Jetpack Beta plugin, running `master`
* Enable nav-unification on that site with:
```php
add_filter( 'jetpack_load_admin_menu_class', '__return_true' );
// no calypso links though
add_filter( 'jetpack_admin_menu_use_calypso_links', '__return_false' );
```
* Connect the site to WordPress.com, but do not pick a plan.
* Go to Jetpack > Settings > Writing, enable the WordPress.com toolbar.
* Notice the PHP notice when viewing the dashboard.
* Switch to this branch, the notices should disappear.
* N/A
=> Masterbar: avoid notices when no plan is available on site.

projects/plugins/jetpack/extensions/blocks/podcast-player/api.js, projects/plugins/jetpack/extensions/blocks/podcast-player/edit.js
This is a follow up to #18380. It does two things:
* Changes the parameters to the `fetchFeed` callback so that it accepts one object, [as suggested here](https://github.com/Automattic/jetpack/pull/18380#discussion_r561793341).
* [Removes the control to set the number of episodes to display](https://github.com/Automattic/jetpack/pull/18380#pullrequestreview-573619358) when the `selectedEpisodes` attribute is defined
This is part of the Anchor FM work, but also a general improvement to an existing feature.
No
The same as #18380:
* Paste a link to create a new post that includes anchor_podcast and anchor_episode query parameters
For example: http://localhost:8000/wp-admin/post-new.php?anchor_episode=547d02ae-abde-462d-92af-3de55ed5bcd2&anchor_podcast=22b6608
* You should see a single player …
=> Podcast Player: Selected Episode Changes

projects/plugins/jetpack/extensions/blocks/conversation/edit.js
It adds the `Timestamps` button to the block toolbar.
Fixes #
* Conversation: add Timestamps button to the toolbar
NO
* Add/edit a Conversation block
* Once selected, confirm you see the `Timestamps` button
* Confirm it works as expected.
N/A
=> Conversation: add Timestamps button to toolbar

tools/docker/mu-plugins/fix-monorepo-plugins-url.php
This is a minor fix that allows the mu-plugin "Fix monorepo plugins_url" to function with Jetpack plugin deactivated.
See #18432
No.
1. Pull the branch and go to Jetpack Dashboard. Verify that the file `jetpack-admin-jitm.min.css` is loaded correctly.
2. Disable the Jetpack plugin. The site should not fatal 🙂 
n/a
=> Docker: Fix the monorepo package URLs fix.

projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php
This PR checks the Spotify URL before inserting the badge in order to prevent an invalid URL.
Fixes #
* Anchor.fm: checks Spotify badge URL
p1611176029052500-slack-
No
* Created an episode post from an URL, but changing the host. 
* Confirm that the badge is not inserted when the host doesn't match what's expected.
* Confirm it works as expected with the proper host.
n/a
=> Anchor.fm: checks Spotify badge URL

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php, projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
Fixes #18470 
Builds on #18474
* Adds a `description_html` to /podcast-player endpoint, filtering the episode description with `wp_kses_post`
* Uses that description for the episode summary when creating a single episode post for anchor.fm podcasts
pbAPfg-PF-p2
No.
* Create a new episode post, using a link like `http://localhost:8000/wp-admin/post-new.php?anchor_episode=547d02ae-abde-462d-92af-3de55ed5bcd2&anchor_podcast=22b6608`
* See that the summary in the post contains links and line breaks
* Turn on the episode description in the podcast player block, and confirm it still uses the 
* Publish the post, and confirm the same on the front-end
**before** | **after**
---------|----------
* Anchor.fm block: allow safe html in episode summary
=> Anchor.fm: show episode summary with post_content safe html

projects/packages/connection/src/class-manager.php
Fixes #17917 
I started noticing a notice of `Undefined index: HTTP_RAW_POST_DATA` today. This should make sure these notices are not generated.
* Add an `isset` guard over `$GLOBALS['HTTP_RAW_POST_DATA']`
N/a
No
* Checkout branch
* Enable `WP_DEBUG` in `wp-config.php`
* Start a Full sync from WPCOM 
* Watch the error log on your local site
* Fix a possible notice of undefined variable when making XMLRPC requests.
=> Connection package: Guard against reading a `$GLOBALS` variable that might not exist.

projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
Differential revision: D55521-code
This commit syncs r219912-wpcom.
Fixes #
* This PR updates the site settings JSON endpoint to allow storing of a Cloudflare Analytics tracking ID; it is a sync from a WPCOM revision.
N/A
No
I'm actually not sure what the exact process is for testing changes to API endpoints within Jetpack compared to testing the API on a WPCOM site. But you should be able to make a request to the site settings endpoint containing the body
```
{cloudflare_analytics: {code: "715d4d275266427cb78934b7919e73e6"}}
```
You should then be able to test that the site in question has a `cloudflare_analytics` site option set with this information.
See D55521-code for context/instructions there.
* Added cloudflare_analytics as a valid field for site settings API POST request.
=> WPCOM sync - adding cloudflare_analytics as valid site settings field

package.json, projects/packages/lazy-images/package.json, projects/plugins/jetpack/package.json
`yarn check` is buggy and deprecated. See https://classic.yarnpkg.com/en/docs/cli/check/#toc-yarn-check
`yarn install --check-files`, which we already have in the script, is the successor.
* Remove deprecated yarn command.
n/a
n/a
* `yarn build`
* Does it still work after the initial step (calling `install-if-deps-outdated`).
* n/a
=> Build: Remove yarn check check

projects/plugins/jetpack/extensions/blocks/dialogue/dialogue.php
* Refactor frontend display to escape as late as possible.
* N/A
* No
* Follow the instructions in #18450 
* The dialogue bits should be displayed just like with the `update/connect-podcast-player-with-dialogue-front-end` branch.
* N/A
=> Dialogue: refactor frontend display to escape as late as possible

projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
Fixes https://github.com/ampproject/amp-wp/issues/5803. 
When forms are submitted on AMP pages, the `amp-form` component issues an XHR request and is expecting a JSON response, as AMP prefers that success messages be displayed via Ajax if not performing a redirect. The XHR form submission request from AMP pages is resulting in the form not being successfully parsed as `jetpack_is_frontend()` returns `false` due to `wp_is_json_request()` returning `true`. The end result is that, while the form submission succeeds, the computed `contact-form-hash` is different and the success message is not displayed on the redirected AMP page.
Non-AMP Success Page | AMP Success Page
-------------------------|--------------------
`contact-form-id=2153`, `contact-form-sent=2218`, …
=> Ensure success page is displayed for Contact Form submissions from AMP pages

projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css, projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php
Fixes https://github.com/Automattic/wp-calypso/issues/49122
- Set the same admin bar link destinations that we use for Simple sites. These new links are ignored when the Nav Unification is disabled (since we display a custom menu when clicking on any menu item), but are used when enabled, effectively fixing the issues described in https://github.com/Automattic/wp-calypso/issues/49122 and p7DVsv-ago-p2#comment-33901 that was preventing users from managing their site, their reader subscriptions and their account.
- Display the same menu items on small viewports that we display on Simple sites when the Nav Unification is enabled.
- Small CSS fix so larger site icons don't exceed the max width allowed.
N/A.
No.
_Atomic_
* Use the Jetpack Beta plugin on an Atomic site and switch to this …
=> Masterbar: Improve menu items when Nav Unification is enabled

tools/docker/mu-plugins/fix-monorepo-plugins-url.php
The monorepo path is hard-coded as /usr/local/src/jetpack-monorepo/ in a
few places in the Docker config. Let's just hard-code it here too
instead of adding dependencies trying to be fancy.
Fixes #18513
#18513
No.
* Same as #18499.
* None needed.
=> Docker: Don't try to be so fancy in the monorepo plugins_url fix

projects/plugins/jetpack/modules/sso.php, projects/plugins/jetpack/modules/sso/class.jetpack-sso-helpers.php, projects/plugins/jetpack/tests/php/modules/sso/test_class.jetpack-sso-helpers.php
If the login page URL has been changed from `wp-login.php` to a custom one, WP.com redirects users back to `wp-login.php`, which throws "error 404". Therefore, Jetpack SSO will not work.
This PR and D55722-code fix the issue by sending along the custom login URL (if there's one). Then WP.com will redirect users not to `wp-login.php`, but to that custom path.
Fixes #17782
* Detect custom login page URL
* Pass it to WP.com along with other SSO data
* WP.com will use it to redirect the user back to the Jetpack site
No.
1. Connect Jetpack, enable SSO (Jetpack -> Settings -> Security -> WordPress.com login -> Allow users to log in...)
2. Install the [WPS Hide Login](https://wordpress.org/plugins/wps-hide-login/) plugin, set a custom login page URL (Settings -> WPS Hide Login).
3. Logout from …
=> SSO: fixing authentication with custom login page URL's.

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/47043
* Switches from Calypso poistive to wp-admin positive to determine link destination.
* Updates unit tests to account for this ^ switch.
* Introduces a user_option for Jetpack and Atomic sites to determine link destination.
* Uses existing `calypsoPreference` setting on dotcom to determine link destination.
No
Atomic:
* [Install & activate the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/). Switch to this branch.
* Reload wp-admin and double-check that menu items still link to Calypso.
* Using `_cli`, add the user option: `$ wp user meta update USER_ID jetpack_admin_menu_link_destination 1`
* Reload wp-admin and double-check that menu items now link to wp-admin screens.
None needed.
=> Masterbar: Account for link destination setting

projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css
This fixes a bug where legacy site icons can overflow their container, if no smaller sizes are available.
* Limits site icons to their container size, 32px.
No
Atomic:
1. Apply this diff 
2. Set a site icon on your test site, if you haven't yet.
3. In dev-tools, change the image url to use a `150x150` or `300x300` size.
4. Make sure the visible image stays at 32px.
None needed,
=> Masterbar: Limit site icon to 32px

projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/conversation/example.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
This PR implements a few enhancements to the `Conversation` and `Dialogue` blocks:
* **Conversation: use row style for example.** https://github.com/Automattic/jetpack/commit/196a22670c6622bad86a11965b06110a652c8b58
This is a quick fix for 425-gh-Automattic/dotcom-manage
The idea is simply to switch the block style to `row` in the example. We can iterate with a better solution soon.
* **Dialogue: remove focusing always the block content.** https://github.com/Automattic/jetpack/commit/f2627e0e450c1df31f312b705137ffbd1ec152e0
I've removed this improvement because I considered it not necessary. Basically, the idea was to make focus always on the block content when the block was selected, independently of the component/area where the event happened.
I think it's better to leave the choice to …
=> Conversation/Dialogue: new enhancements round

projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
This PR fixes an issue in FF. The participant style is not detected when clicking on the participant component, but just in focus. This PR allows selecting it by clicking on it.
Fixes #
* Dialogue: select participant by clicking on the component.
No
* In FF, create a dialogue component
* Select the participant component by clicking on it
* Confirm you see, and also can apply formats to the participant, from the toolbar
* n/a
=> Dialogue: select participant by clicking on the component.

projects/plugins/jetpack/extensions/blocks/dialogue/dialogue.php
Fixes #18295
Outputs the custom css classes added to dialog block settings only on the block container, not the inner elements.
No
* Insert a conversation block
* Set a custom class on one of the dialog blocks
* Verify the class is output only on the container div, and not on other `<div>`s in the block, when the block is rendered on the front-end
- Dialog block: fix how custom css classes are output
=> Dialog block: output custom css classes only on container

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
We've noticed that several Anchor.fm podcast descriptions contain multiple paragraph tags, and thus using a single paragraph block for the entire summary causes block invalidation errors, since https://github.com/Automattic/jetpack/pull/18481.
This change uses the `pasteHandler` from `@wordpress/blocks` to parse the episode description into multiple blocks, when appropriate.
No
* Create a new podcast episode post where the description has multiple `<p>` tags within it (for example `/wp-admin/post-new.php?anchor_episode=2dded3cd-b9ef-4e9e-8721-d0c1773a57a3&anchor_podcast=ffd7ec4`)
* Save the draft post
* Refresh the editor page in your browser
* See that no block validation errors are triggered, and that the episode description is parsed into multiple paragraph blocks
n/a since the …
=> Anchor.fm: parse podcast summary into blocks

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php, projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php, projects/plugins/jetpack/tests/php/_inc/lib/test-class-jetpack-podcast-helper.php
Fixes #18514
This makes the `anchor_episode` parameter optional. When it's not supplied we'll create the episode post using the most recent episode of the podcast. 
This is part of the Anchor.FM integration project.
No.
* Go to `/wp-admin/post-new.php?anchor_podcast=5243218` on your development site, ensuring that you have the beta/experimental features enabled.
* You'll be presented with a blank post.
* With this branch, do the same thing,  and you should see a new post in the editor, populated with the latest episode of the podcast.
Not required, as this is a change to the Anchor.FM integration, which is launched.
=> Anchor.FM: Get most recent episode when no GUID is passed.

projects/plugins/beta/composer.json
Allows the GitHub actions for the monorepo to function as expected.
=> Beta Plugin: Add composer.json for the beta plugin

projects/plugins/jetpack/_inc/lib/class-jetpack-recommendations.php
* We do not need to show those recommendations to folks that are not connected to WordPress.com.
* N/A
* No
* On a site, set up offline mode (https://jetpack.com/support/development-mode/)
* Visit Jetpack > Dashboard
* You should not see the Recommadations tab.
* N/A
=> Recommendations: shortcircuit early when in Offline Mode

projects/plugins/jetpack/composer.json
By default composer generates a new random suffix for its autoloader
classes if there isn't already a vendor/autoload.php file to read one
from.
This causes every commit to our Automattic/jetpack-production mirror
repo to change these files with a new suffix, cluttering the git
history.
We can avoid that by configuring a static suffix in composer.json. We
still use a long arbitrary string that it's unlikely anyone else will
choose by accident. The main risk is that someone might copy our
composer.json for their own plugin and not change it (despite the fact
that it contains the word "jetpack").
The "f11009ded9fc4592b6a05b61ce272b3c" isn't entirely arbitrary. It's
the MD5 hash of "Automattic/jetpack".
None.
No.
* Run `composer install` locally in project/plugins/jetpack/, and see that …
=> Jetpack: Set composer autoloader-suffix

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49292
Register again the `editcss` submenu page in the new Admin menu so it is available when the Nav Unification is enabled.
N/A.
No.
- Apply D56069-code to your WP.com sandbox.
- Sandbox a Premium site.
- Go to Appearance > Customizer.
- Open "Additional CSS" panel. _If this is your first time adding CSS here you will need to add some, save and refresh to enable the "CSS Revisions"._
- Click "CSS Revisions" above the CSS editor.
- Make sure the "CSS Stylesheet Editor" from WP Admin is opened.
N/A.
=> Re-register Edit CSS sub page menu item

projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/_overrides.scss
* Add a border between the sidebar and the content in the Contrast color scheme
This PR is related to a similar change in Calypso https://github.com/Automattic/wp-calypso/pull/49408
The related issue is https://github.com/Automattic/wp-calypso/issues/48009
|Before|After|
|-|-|
|<img width="404" alt="Screenshot 2021-01-28 at 15 08 05" src="https://user-images.githubusercontent.com/1562646/106149539-abbb1100-617a-11eb-8d4e-a845a72c4efc.png">|<img width="414" alt="Screenshot 2021-01-28 at 15 07 34" src="https://user-images.githubusercontent.com/1562646/106149545-ad84d480-617a-11eb-9a60-8195b48becfb.png">|
- activate WPCOM toolbar in Settings>Writing
- select the Contrast color scheme in profile.php
- confirm there is now a visual divider between the sidebar and the content
=> Admin Color Schemes: add border to Contrast color scheme

projects/plugins/jetpack/extensions/blocks/anchor-fm/editor.js
* The link is currently not correct, it points to an existing Anchor.fm podcast. Let's fix that.
(note: the new link isn't working yet, that's going to be fixed in the next few weeks)
* See 451-gh-dotcom-manage
* No
* Start from a site connected to WordPress.com where Beta blocks are enabled (`add_filter( 'jetpack_load_beta_blocks', '__return_true' );`)
* Go to Posts > Add New, and write a post.
* Publish it.
* Notice the post-publish prompt in the sidebar.
* Click on the link.
* N/A
=> Anchor.fm: update Anchor.fm destination link

projects/plugins/jetpack/functions.photon.php, projects/plugins/jetpack/modules/videopress/class.videopress-xmlrpc.php, projects/plugins/jetpack/modules/videopress/utility-functions.php, projects/plugins/jetpack/tests/php/test_functions.photon.php
This PR re-enables image resize parameters for VideoPress poster URLs.
This was previously disabled in https://github.com/Automattic/jetpack/pull/12764, because resize parameters sent to videos.files.wordpress.com didn't use to work (and resulted in a 404 error). This has since been fixed server-side (see D49897-code and pxWta-Rs-p2), so this PR undoes the now-unneeded exclusion so that poster URLs can be resized once again.
I also undid some related behavior that applied the `ssl=1` parameter to VideoPress poster URLs. I believe this is a holdover from when Photon was used for resizing the URLs (before the wpcom-images project - p3topS-mu-p2). All WP.com URLs are always SSL-enabled, so the parameter should not be needed - it's not applied to other *.files.wordpress.com URLs and we should …
=> Photon: Enable resize parameters for VideoPress poster images

projects/plugins/jetpack/extensions/blocks/conversation/index.js, projects/plugins/jetpack/extensions/blocks/dialogue/style.scss
Fixes #18567 and #18569
- Stacks column style conversations on smaller screens
- Ensures participant names are right aligned for column style in the editor
- Add top/bottom margin to dialogue entries on the front-end
- Adds `dialogue` search term to conversation block, since the conversation block is what's available in the inserter
| **Before** | **After** |
| --- | --- |
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/106225046-f6a04d00-61a9-11eb-9bec-218caea4bf8b.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/106225188-4121c980-61aa-11eb-9252-1101171594ce.png"> |
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/106225053-fa33d400-61a9-11eb-84ca-b3fd6c77c74f.png"> | …
=> Conversation/dialogue blocks: tweaks to styles and search terms

package.json
Fixes p1611862320013700-slack-CDLH4C1UZ
* For the `yarn docker:build` command, use the node version from `.nvmrc` instead of `node:latest`.
n/a
n/a
* Run `yarn docker:build` before after this patch.
* n/a
=> Build: Use Node 12 instead of Node latest

projects/plugins/jetpack/extensions/shared/components/upgrade-nudge/style.scss
* See discussion here:
See https://github.com/Automattic/jetpack/pull/18239#discussion_r562751038
* N/A
* No
* Apply D55864-code to your sandbox.
* Sandbox a free WordPress.com site.
* Open the editor and insert a Premium Content block.
* You should see an upgrade nudge with all its colors.
* No
=> Editor nudges: use colors from Color Studio

projects/plugins/jetpack/_inc/lib/functions.wp-notify.php
This is a tricky one. This filter is called in two places in Core. One is just to pass if a comment is being held for moderation. See https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/comment.php#L2296
So we can't just assume that a true value here is what we need. The second time the filter is called, it checks the option -- which is what we expected here. See https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/pluggable.php#L1737
It's possible another plugin would be filtering this value to true despite the option setting; however, since we're running at priority 1, they can still do that. They'll just get the Core flow instead of this one.
Fixes p9F6qB-6q6-p2
* More defensive check before sending comment notification.
n/a
No.
* With Jetpack activated, …
=> Calypso: Check moderation option before comment notification

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/jetpack/issues/18596
* Support changing the customizer link ($customize_slug) through a parameter in the `add_appearance_menu` so that simple / atomic class can set the correct link.
**On an atomic site**
* Load this branch with Jetpack Beta
* Check that customizer URLs point to WPAdmin links and work
**On a jetpack site**
* Load this branch
* Enable `nav-unification` by adding `add_filter( 'jetpack_load_admin_menu_class', '__return_true' );` in a mu-plugin
**On a simple site**
* apply D56179 patch
* Check that customizer URLs point to WordPress.com links and work
* Avoid redirects for customizer links
=> Changes the customize_slug depending on simple / atomic.

projects/github-actions/push-to-mirrors/push-to-mirrors.sh
If the mirror repo is created with no branches, the script should still be able to push to it.
p1612201209477300/1612199331.464600-slack-CBG1CP4EN
No.
* None needed.
=> push-to-mirrors: Fix mirroring to an empty repo

.github/files/build-all-projects.sh, tools/cli/commands/build.js
Uses the `jetpack build` logic to determine to run production vs development build commands instead of assuming `build-production` will always be present.
Also, removes a check for the `build-production` script. We'd want to lock in the composer packages either way, no?
The jetpack cli intentionally exits with `0` if there is no composer.json or build steps are present. It'll return `1` if a build step actually fails.
I realized this when reviewing https://github.com/Automattic/jetpack/pull/18303 that `build-development` wouldn't have actually built the plugin.
* See above.
n/a
n/a
* Can try to run the commands locally.
* n/a
=> Build: Use the CLI for build step to avoid duplicating logic

projects/plugins/jetpack/extensions/blocks/story/story.php
This fixes an issue with Story playback on WP.com, where images would sometimes be pixelated or blurry (Jetpack sites were not affected).
The reason this was happening was that the base image size [supplied to `wp_calculate_image_srcset`](https://github.com/Automattic/jetpack/blob/6cc6ec6b0243bb92767efd30a1214cf55e0cc2cb/projects/plugins/jetpack/extensions/blocks/story/story.php#L66) was small, and WP.com has added filtering that removes the full size image from the srcset sources if it's more than twice the base size of the image (see `filter_image_srcset()` in `wpcom-media.php`). This resulted in a too-small image being upscaled to fit the display and looking blurry.
Here's an example of the issue (Jetpack on the right is correctly loading the full-size image):
This PR changes the …
=> Story block: Fix srcset tag values on WP.com

tools/docker/bin/install.sh
wp-crontrol is an extremely handy plugin for debugging cron issues on sites and is my first install anytime cron comes up.
To aid others in faster access and discoverability of this debugging tool, let's add it to our default docker install.
* Add wp-crontrol as a default debugging plugin.
n/a
n/a
* `yarn docker:install`
* Confirm wp-crontrol was installed (should be in the CLI output 
* n/a
=> Docker: Add wp-control as a default debugging plugin

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
Fixes p1YhhO-Md-p2
* Uses `rest_request_before_callbacks` as a filter rather than an action. 
**On Simple**
- apply the patch to your sandbox
- visit `http://wordpress.com/` and select your sandboxed site
- make sure that you don't get duplicate menu items like 
**On Atomic**
- Use Jetpack Beta and switch to this branch
- visit `http://wordpress.com/` and select your atomic site
- make sure that you don't get duplicate menu items like 
Please also follow p1YhhO-Md-p2#comment-6349 for the jetpack-licensing issue
* Fixes jetpack-licensing endpoint
=> Use rest_request_before_callbacks as a filter.

docs/monorepo.md
In #18617, the logic was changed to use the `jetpack build` commands, which uses build-production OR build-development depending on internal logic.
This updates the documentation to include reference to `build-development` and that one of the `build-*` scripts are required if a build step is needed.
* Updates docs.
n/a
n/a
* n/a
*
*
=> Docs: Add reference to build-development for monorepo docs

projects/plugins/jetpack/modules/widgets/eu-cookie-law/eu-cookie-law-admin.js, projects/plugins/jetpack/modules/widgets/eu-cookie-law/eu-cookie-law.js
Gutenberg 8.9.0 introduced a block-based widget editing screen, and
these changes fix two JS errors that were occuring due to:
1. `eu-cookie-law-admin.js` referencing an id value which when editing
the widget from the block-based screen is no longer present - there is
a legacy widget block wrapper.
2. `eu-cookie-law.js` may not always find the right DOM elements from
the block-based widget screen as the block is rendered or rerendered.
A separate issue has been opened for the `Preview` option not working as expected: #18664
Fixes #18565
No.
* Refer to reproduction steps outlined in #18565
* After pulling/building proposed changes, test that you are able to add & edit a `Jetpack Cookies & Consents Banner` widget from the Gutenberg block-based widgets screen. Refresh the page and make sure …
=> Fix JS errors for eu-widget in block widget editor

.github/workflows/linting.yml, tools/eslint-changed.js
In #18627, we updated to the latest version of phpcs-changed which updated from `--git-branch` to `--git-base`.
To mirror them, let's update the arg the same. The same happy accident with phpcs-changed where it worked with any base, not just branches, already, should be the same for us as well.
* eslint-changed now uses `--git-base` instead of `--git-branch`
n/a
n/a
* Make changes in JS and run `yarn lint-changed --git-base [base]` with a different branch.
*
* n/a
=> Tools: Update eslint-changed to match phpcs-changed

projects/packages/autoloader/src/class-plugin-locator.php, projects/packages/autoloader/src/class-plugins-handler.php, projects/packages/autoloader/tests/php/tests/unit/test-plugin-locator.php, projects/packages/autoloader/tests/php/tests/unit/test-plugins-handler.php
As an alternative to #18673 this PR adds stricter type checking around WordPress functions. It's possible that filters may cause these to return unexpected data and we should add resiliency to avoid fatals in those cases.
N/A
No.
The circumstances where this can be tested on a live site are difficult but I've included tests that verify the bug is fixed.
* Autoloader: stricter type-checking on WP functions
=> Autoloader: stricter type-checking on WP functions

projects/plugins/jetpack/.wp-env.json, projects/plugins/jetpack/tests/e2e/.eslintrc.js, projects/plugins/jetpack/tests/e2e/lib/flows/jetpack-connect.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/block-editor.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/jetpack.js, projects/plugins/jetpack/tests/e2e/lib/setup-env.js, projects/plugins/jetpack/tests/e2e/specs/connection.test.js, projects/plugins/jetpack/tests/e2e/specs/plugin-updater.test.js, tools/eslint-excludelist.json
* fixes a bug related to missed packages folder in wp-env environment
* switches the connection variation switch from PHP constant for a JS approach
* rename `connectThroughWPAdminIfNeeded` to reflect actual implementation
* Attempt to address flakiness related to unexpected "Saved" state in block editor
n/a
n/a
* Make sure tests are green in CI
* Re-run it few times, to make sure there no intermittent failures
* Run `./tests/e2e/bin/env.sh start`. Make sure script can activate `jetpack-dev` plugin
* n/a
=> E2E Tests: use JS to force connect variation

projects/packages/sync/src/modules/class-posts.php
To make Sync a standalone package we need to remove references to Jetpack functions and constants. This update replaces the usage of `wp_startswith` with `0 === strpos` to check the meta_key.
* Removal of dependency functions.
NO
* This update is covered under existing unit tests "test_syncs_wpas_skip_meta"
* To manually test you can add the _wpas_meta_ meta value to a post and verify it is synced to the Cache DB.
* add_post_meta( POST_ID, '_wpas_skip_1234', '1' );
* Sync - Packaging : removal of Jetpack dependent functions.
=> Remove Sync's usage of wp_startswith

projects/plugins/jetpack/class.json-api-endpoints.php
This is a follow-up from #18637.
On WordPress.com, file operations are handled a bit differently and calling filesize() can consequently cause warnings.
We now avoid calling it on WordPress.com, and instead rely on the filesize metadata field when it is available (it is not for all images).
* See D56399-code
* No
* Go to https://developer.wordpress.com/docs/api/console/
* Query the media endpoint for a site where you've applied this patch.
* You should see the media size in the response
* N/A
=> WPCOM API / Media: handle WordPress.com file operation differences

projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
Rely on core's `WP_Automatic_Updater` class to check if any of the `update_plugins` items `should_update()`.
See #18562
No
* With this change pulled down, connect Jetpack to WordPress.com
* Install a plugin for testing such as Hello Dolly, and `Enable auto-updates` for the plugin from WP Admin
* Add `define( 'AUTOMATIC_UPDATER_DISABLED', true );` to your site's `wp-config.php` file
* Rollback the version of the plugin you enabled auto-updates for using something like the WP Rollback plugin. Refresh WP Admin to make sure you see that a new version is available for that plugin.
* Visit `https://wordpress.com/plugins/manage/__YOUR_SITE__` where you should see some toast messages telling you the plugin is being updated.
* If you refresh WP Admin however, you should see that the plugin was …
=> Update plugin modify endpoint to use should_update

projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
Reverts Automattic/jetpack#18697
`should_update` expects an object for the $plugin item update offer, this change was throwing some PHP notices and I'd like to test it a bit more.
=> Revert "Update plugin modify endpoint to use should_update"

projects/plugins/jetpack/class.jetpack.php, projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php, projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php, projects/plugins/jetpack/tests/php/general/test_class.jetpack.php
Part of https://github.com/Automattic/wp-calypso/issues/47043
Follows up https://github.com/Automattic/jetpack/pull/18238
Read the value of the new link destination setting that has been exposed in the `wpcom.getUser` XMLRPC response in D56006-code, and store it as the user option used by the new admin menu.
N/A.
No.
- On an Atomic site, [install & activate the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/). Switch to this branch.
- Go to wordpress.com and switch to that Atomic site.
- Make sure that the sidebar menu items link to Calypso.
- Go to `/me/account` and enable the toggle that says "Replace all pages with WP Admin equivalents".
- Go to My Sites.
- Check the sidebar menu and make sure that all pages with WP Admin equivalents link to WP Admin.
- Go again to …
=> Masterbar: Update link destination setting

projects/packages/sync/src/class-functions.php, projects/packages/sync/src/class-json-deflate-array-codec.php, projects/packages/sync/src/modules/class-module.php, projects/plugins/jetpack/functions.global.php
jetpack_json_wrap is used for encoding sync events to ensure we can consistently decode them. This function is only being used by the Sync Package as such we are migrating it into the Sync/Functions class as a static method json_wrap.
* Migration of jetpack_json_wrap function to Sync/Functions::json_wrap
No
* Verify all Sync Unit Tests pass. This action is called in sending of data so an error will cause the full test suite to fail.
* On a Jetpack connected site perform edit actions and verify they are sent to WP.com. I suggest using Instant Search, Publicize or similar feature and confirm the post publicizes or is available in search results.
* Sync :: deprecation of jetpack_json_wrap with replacement by Sync/Functions::json_wrap
=> Deprecate jetpack_json_wrap

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php, projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php, projects/plugins/jetpack/extensions/blocks/anchor-fm/editor.js
Fixes #18541
* Adds editor notice for when Anchor episode is not available
* Adds `force_refresh` param to to helper `get_track_data` method to clear the podcast helper and SimplePie caches when needed
https://github.com/Automattic/jetpack/issues/18541
N/A
_Caching_
* Create a podcast on Anchor.fm, add an episode, and copy the RSS feed URL from the distribution settings.
* Add a podcast player block to a post with the RSS feed URL.
* Publish a new podcast episode.
* Go to the RSS feed URL and copy the GUID of the new episode (might take a couple of minutes to show up because of Anchor.fm caching).
* Go to 'wp-admin/post-new.php?anchor_podcast={podcast-id}&anchor_episode={episode-id}' and verify that no error message appears and the episode info populates the post as expected.
_Error …
=> Add error message for when episode is not available

projects/packages/connection/src/class-client.php, projects/plugins/jetpack/class.jetpack.php
Fixes p9dueE-2l1-p2
* Prevents needless calls to the WP.com Test API endpoint.
p9dueE-2l1-p2
n/a
* `add_filter( 'jetpack_client_verify_ssl_certs', '__return_true' )`;
* `wp jetpack options update fallback_no_verify_ssl_certs false`
* Monitor outbound traffic from your server. See that on every wp-admin request, a call is made to the test api endpoint.
* Apply patch, add the filter and reset the option, then confirm no requests or at least no more than one. :)
* Admin: fix issue of excessive test API calls.
=> Connection: Prevent pointless calls to the test API

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
* Removes the image next to the podcast player block in the Anchor block, and centers the podcast player
p1612562996197700-slack-C01FD4FGD7X
N/A
* Go to 'wp-admin/post-new.php?anchor_podcast=22b6608&anchor_episode=547d02ae-abde-462d-92af-3de55ed5bcd2&spotify_url=https://open.spotify.com/show/6HTZdaDHjqXKDE4acYffoD?si=EVfDYETjQCu7pasVG5D73Q'
* Check that the player is centered and there is no cover image next to it.
N/A
=> Anchor: Remove image next to podcast player block

projects/plugins/jetpack/modules/custom-post-types/portfolios.php, projects/plugins/jetpack/modules/custom-post-types/testimonial.php
Fixes #18741
- Allow Newspack's Blog Posts block to display Testimonial and Portfolio posts.
* N/A
* No
* On an Atomic site, go to Jetpack > Settings > Writing
* Enable both Custom Content Types
* Create posts for both content types, and publish them.
* Add a new Blog Posts Block: https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/
* You should be able to pull the Custom Posts you've just created in the "Post Types" sidbar panel.
* Custom Content Types: allow Newspack's Blog Posts block to display Testimonial and Portfolio posts.
=> Custom Content Types: add support for Newspack's Blog Posts block

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php, projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php, projects/plugins/jetpack/_inc/lib/functions.wp-notify.php, projects/plugins/jetpack/class.jetpack-gutenberg.php, projects/plugins/jetpack/class.jetpack.php, projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-user-connect-endpoint.php, projects/plugins/jetpack/modules/monitor.php, projects/plugins/jetpack/modules/notes.php, projects/plugins/jetpack/modules/sharedaddy.php, projects/plugins/jetpack/modules/sso.php, projects/plugins/jetpack/modules/stats.php, projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php, projects/plugins/jetpack/tests/php/general/test_class.jetpack.php
Fixes https://github.com/Automattic/jetpack/issues/18727
In #18548 we deprecated `Jetpack::is_user_connected` and `Jetpack::get_connected_user_data`. This PR migrate all the deprecations so the functions from the connection manager package are used instead.
N/A
No.
Many files have changed. Unit tests should cover us. Alternatively check the modified files and manually test the relevant UI. 
No.
=> Connection: Migrate deprecations

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js, projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/conversation/example.js, projects/plugins/jetpack/extensions/blocks/conversation/index.js, projects/plugins/jetpack/extensions/blocks/conversation/participants.json, projects/plugins/jetpack/extensions/blocks/conversation/utils.js, projects/plugins/jetpack/extensions/blocks/dialogue/attributes.js, projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/editor.scss, projects/plugins/jetpack/extensions/blocks/dialogue/index.js, projects/plugins/jetpack/extensions/blocks/dialogue/save.js, projects/plugins/jetpack/extensions/shared/icons.js
This PR implements a new component used to edit the participants in a conversation structure.
https://user-images.githubusercontent.com/77539/106919456-ec6dd980-66e8-11eb-96a3-92f5f520cc12.mov
* Dialogue: edit participant from canvas
NO
* Create a new conversation block. Check you can get it by `conversation`, `transcription`, `dialogue`, `dialog`, and `speaker` keywords.
* When you start a new component from scratch, there is not any participant defined in the conversation context, thus you need to start to type the participant name in some of the dialogue blocks.
* The new participant will be added once press `ENTER` key or when on focus outside
* When editing a new Dialogue participant, you should get the participant suggestions.
* To add a new participant, you need to clean the …
=> Dialogue: edit participant from canvas

projects/plugins/jetpack/extensions/blocks/conversation/components/participants-controls.js, projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/conversation/editor.scss, projects/plugins/jetpack/extensions/blocks/dialogue/style.scss
**IMPORTANT**: PR branched off from update/dialogue-participant-canvas-edition
This PR cleans and updates the `timestamp` and `participants` controls from the toolbar and the block settings (sidebar).
Issue tasks:
* Remove timestamp and speaker management from the Conversation block,
* and place those controls in the child blocks. 
* Toggling on timestamps in a child block will still affect other child blocks, 
* and will remove the need to move between the parent and child block to make updates.
Fixes https://github.com/Automattic/jetpack/issues/18671
* Conversation: re-organize timestamp and participants controls
No
* Create a new Conversation/Dialogue block
* Add some participants there.
* Confirm either participants and timestamps controls have been removed from the toolbar
before | …
=> Conversation: re-organize timestamp and participants controls

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Counterpart of https://github.com/Automattic/wp-calypso/pull/49718
Needed by 577-gh-Automattic/wpcomsh
Further reading: p9o2xV-1fe-p2
Sanitize the URLs returned in the `admin-menu` endpoint response to ensure that only internal links are used.
N/A.
No.
* Spin up a Jetpack site running this branch.
* Add a mu-plugin with the code below:
```php
add_action( 'admin_menu', function() {
global $menu, $submenu;
$menu[0] = [ 'Click here', 'read', 'javascript:alert("hello")' ];
$submenu['javascript:alert("hello")'] = [ [ 'Or here', 'read', 'http://example.com' ] ];
} );
```
* Go the [WP.com API console](https://developer.wordpress.com/docs/api/console/).
* Select "WP REST API" and "wpcom/v2".
* Make a `GET` request to `/sites/:site/admin-menu`.
* Make sure the first item of the response and its …
=> Admin Menu: Sanitize URLs in endpoint response

projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
This PR adds a fallback for the `useDebounce` hook. It isn't available in WordPress version 5.5. This hook was introduced in this PR https://github.com/Automattic/jetpack/pull/18646
* Dialogue: add fallback for useDebounce()
p1612871290001800?thread_ts=1612868861.488300&cid=CKZHG0QCR-slack-
* Switch to WordPress core 5.5
If you use Jetpack env dev, you can run `yarn docker:wp core update --version=5.5 --force`
* Confirm that, without the changes suggested by this PR, the editor app breaks when a new Dialogue/Conversation block is created
* Confirm that, with these changes, the app works as expected.
* Try to create a conversation with many Dialogue blocks
* Set the same speaker for some of them.
* Edit a speaker label, and confirm the label is propagated to all sibling dialogue blocks.
*
=> Dialogue: add fallback for useDebounce

projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js, projects/plugins/jetpack/extensions/shared/components/audio-player/README.md, projects/plugins/jetpack/extensions/shared/components/audio-player/index.jsx
Fixes #
* Audio Player: support load file when ready feature
p1612872457005400?thread_ts=1612868861.488300&cid=CKZHG0QCR-slack-
No
With these changes, the media file will be initially loaded when a podcast block is added, so
* Create/edit a post
* Open the redux tool
* Add a podcast block
* set a valid RSS feed
* check that the duration is already populated in the media source
* Confirm that changing the episode, the duration also updated to the new file.
*
=> Audio Player: add `loadWhenReady` and `preload` properties

projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php
The `WP_Test_Jetpack_REST_API_endpoints::test_change_owner` test started failing today with the message "Failed asserting that 500 matches expected 200".
It looks like the [jetpack.switchBlogOwner request](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php#L1824) is returning an error. We haven’t identified the root cause of the failure, but manual testing has not revealed any issues with changing the blog owner.
To fix the test failure, we can intercept the http request and provide the mocked http response using the `pre_http_request` filter in the `WP_Test_Jetpack_REST_API_endpoints::test_change_owner` method. 
n/a
no
* Verify that the tests pass.
* n/a
=> API Endpoints: filter the switchBlogOwner http response before the request.

projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/components/timestamp-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/editor.scss, projects/plugins/jetpack/extensions/blocks/dialogue/save.js, projects/plugins/jetpack/extensions/blocks/dialogue/style.scss, projects/plugins/jetpack/extensions/blocks/dialogue/view.js
Fixes https://github.com/Automattic/jetpack/issues/18675
* Dialogue: new approach to edit timestamp
No
* Create/edit a post
* Add a podcast block with a valid RSS feed. You can use this one: `https://distributed.blog/2020/07/24/lara-hogan-management-secrets/`
* Add a Conversation/Dialogue blocks composition
* you should be able to see the media player control in the Dialogue toolbar, as well as the `Add timestamp` link in the Dialogue block.
* 
* From here, you can add and remove the timestamp
* Confirm it gets the timestamp value from the current time in the player. If the player is in the `10:00` position, the timestamp should get this value by clicking on the `Add timestamp` link.
* Open the block settings.
* You should see the Range control. Confirm you can change the timestamp using …
=> Dialogue: new approach to edit timestamp

projects/plugins/jetpack/extensions/blocks/dialogue/edit.js, projects/plugins/jetpack/extensions/shared/components/media-player-control/index.js
This PR renders the timestamp in the block toolbar with a Button component, which provides a way to set the Dialogue timestamp by clicking on it.
Fixes #
* Dialogue: set Dialogue timestamp from the toolbar button
p1612991089094400-slack-
No
* Create/edit a post
* Add a podcast block with a valid RSS feed. You can use this one: https://distributed.blog/2020/07/24/lara-hogan-management-secrets/
* Add a Conversation/Dialogue blocks composition
* Confirm that is possible to set the Dialogue timestamp value by clicking on the timestamp button, rendered in the block toolbar.
*
=> Dialogue: set Dialogue timestamp from the toolbar button

projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php
New tabs were sometimes opened instead of (or in addition to) the expected popup when clicking a sharing button.
Fixes #18760.
* Handle both the situation where the button itself is clicked, and where an element inside of it is
No.
Follow the testing instructions on #18760 on a page with this patch applied.
* Sharing buttons should now correctly open a single popup.
=> Fix sharing button popups

.github/actions/repo-gardening/src/index.js, .github/actions/repo-gardening/src/tasks/add-labels/index.js, .github/actions/repo-gardening/src/tasks/add-labels/readme.md, .github/labeler.yml, .github/workflows/gardening.yml
* This is a more automated approach to our existing implementation, an alternative to #18467.
**Note**: this automated approach has its inconvenients. There are some use cases where our label names are different from the way the features are organized:
- For example, we use the "Shortcodes / Embeds" label instead of a "Shortcodes" label that would match our folder structure (`modules/shortcodes`). We can see the problem in this test PR: #18725  
- In some cases, we'd rather not surface the old code name of the feature: we use the "Sharing" label to group all issues related to the feature living in `modules/sharedaddy`.
* N/A
* No
* I'll be creating PRs against this branch to test things out. This PR touches an action, so should also trigger a label change. Also see #18766 for some …
=> Actions: add labels to all PRs, based on list of modified files

.github/files/required-review.yaml
We want Jetpack Approvers to be able to approve any PR in the repo.
* See p1613000059385100-slack-CBG1CP4EN
* No
* Default to the Jetpack Approvers team for folks who can approve all PRs in the repo.
* N/A
=> Required Review Action: update so Approvers are the default group

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49238
* Adds a WordPress.org theme install menu item for WoA sites only so users have the chance to install a theme from the WordPress.org repository
* Select this branch in Jetpack Beta
* Make sure that a Appearance -> WordPress.org Themes exists under Themes 
* The above menu redirects to `/wp-admin/theme-install.php`
* Run `yarn docker:phpunit --filter Test_Atomic_Admin_Menu` and confirm there are no failures
Before | After
-------|------
* Adds a WordPress.org theme install menu item for Atomic sites.
=> Adds a WordPress.org theme install menu item.

projects/plugins/jetpack/extensions/shared/components/audio-player/index.jsx
When the AudioPlayer component was used there were occasions when both the mount and unmount parts of the `useEffect` hook would run in a single render. `MediaElement` has a responsive mode that uses `setTimeout( ..., 0)` to wait for the audio player to be rendered before checking and updating its size. The problem here is that the audio element was being cleaned up as part of the `useEffect` before the sizing function had a chance to run. It would then run and assuming the audio element was still part of the DOM, would attempt to read properties about its `parentNode`. This would cause an error as `parentNode` was undefined.
This should probably be patched in MediaElement itself, but it is an edge case, and I think something specific to do with how this operates with `useEffect`. But …
=> Audio Player: Fix the error thrown from MediaElement of parentNode being undefined

projects/plugins/jetpack/extensions/blocks/conversation/components/participants-controls.js, projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/conversation/utils.js, projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js
This PR handles setting the speaker label in order to prevent adding format styles, and also allowing special characters.
Fixes #
* Conversation/Dialogue: render render speaker label properly.
p1612970062065000-slack-
No
It's preferable testing in SImple sites  (D56853-code)
* Create a new conversation block.
* Paste the speaker name copying text with format styles: **Joey**, _Kerry_.
* Confirm that, although initially, the component shows the label with styles (like the screenshot below), once the speaker is added the styles are removed from there.
before to add | once added
-----|-------
* Confirm that the speaker label is properly printed in the block settings (sidebar)
Dialogue sidebar |  Conversation sidebar
--------|--------
* Save the post
* hard refresh
* Confirm it doesn't get …
=> Conversation/Dialogue: render render speaker label properly

projects/packages/sync/src/class-actions.php, projects/packages/sync/src/class-main.php, projects/packages/sync/src/class-users.php, projects/plugins/jetpack/class.jetpack-cli.php, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-integration.php
This PR updates the Sync logic that triggers an initial sync on `jetpack_user_authorized`, to do so on `jetpack_site_registered ` instead.
The main reason is that on user-less Jetpack connections, aka when no user has connected their WP.com account, the initial sync would never get triggered.
Besides from that, given that Sync now relies only on the site connection (blog token), there's nothing preventing us to trigger the initial sync when the site is connected.
* Updates the hook that triggers the initial sync on `Sync\Main` class's `configure` method from `jetpack_user_authorized` to `jetpack_site_registered`
* Replaces the `is_active` check in `Sync\Actions` class's `get_debug_details` method, with `is_connected`. `is_active` looks for an existing user connection, while `is_connected` …
=> Sync: Trigger initial sync on jetpack_site_registered

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php
This change will allow for plugins menu order callbacks to work on admin menu API requests.
* Defined the `$menu_order`  global before including `/wp-admin/menu.php`.
* Removed menu order filter.
No.
* Install & activate Jetpack Beta on a WoA site with an eCommerce plan and switch to this branch.
* Access the WoA site via SFTP and add a new mu-plugin with the content of 577-gh-wpcomsh.
* Load the site in Calypso and make sure WooCommerce menu items show up in the correct order.
None needed.
=> Admin Menu API: Account for menu order callbacks

projects/plugins/jetpack/extensions/blocks/dialogue/attributes.js, projects/plugins/jetpack/extensions/blocks/dialogue/save.js
* Uses an `html` source for the label attribute, so it doesn't need to be duplicated in the html comment and the block markup
* Uses `<RIchText.Content>` in the save function for the label, now that it's generated using the RichText component.
| **Before** | **After** |
| - | - |
| <img width="821" alt="Screen Shot 2021-02-11 at 14 43 15" src="https://user-images.githubusercontent.com/1699996/107696821-09ba1f00-6c78-11eb-8c19-1734b6eb3144.png"> | <img width="829" alt="Screen Shot 2021-02-11 at 14 43 52" src="https://user-images.githubusercontent.com/1699996/107696855-13dc1d80-6c78-11eb-8753-4877399090de.png"> |
No
1. Insert a conversation block and add speaker entries
1. Use the code editor to verify the label attribute is no longer duplicated in the HTML comment
1. Load an existing …
=> Dialogue block: use HTML for label attribute

projects/packages/sync/src/class-defaults.php, projects/plugins/jetpack/class.jetpack.php
jetpack_sync_callable_whitelist filter exists to allow extending of Sync callables. To ensure the Sync Package is isolated this PR removes Jetpack functions from the default definitions and adds them using the filter during Jetpack initialization.
* No functional changes, simply shifting addition of Jetpack callables into Jetpack.
* No
These changes are covered under the existing test test_sync_callable_whitelist
Manual Test
* $cm = Automattic\Jetpack\Sync\Modules::get_module( 'functions' );
* $cm->get_all_callables();
* verify that the callable list includes:
single_user_site
updates
active_modules
available_jetpack_blocks
sso_is_two_step_required
sso_should_hide_login_form
sso_match_by_email
sso_new_user_override
sso_bypass_default_login_form
* N/A - no functional changes simply …
=> Refactor Jetpack callables into the plugin

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50039
Fixes https://github.com/Automattic/wp-calypso/issues/49978
Since 577-gh-Automattic/wpcomsh, menu items registered by third-party plugin show up in the Calypso/WP Admin menu when the nav unification is enabled.
"Jetpack > Backups & Scan" is one of these menu items, which is registered by Jetpack. However, it is redundant, since we already include separate links for the "Backup" and "Scan" pages, so this PR removes the redundant "Backups & Scan" menu entry.
Also noted that the "Backups & Scan" menu links to a `jetpack.com` URL which was no longer an allowed URL since https://github.com/Automattic/jetpack/pull/18759. Although I've not found any other menu that links to a `jetpack.com` URL, this PR also adds the `jetpack.com` URL …
=> Admin Menu: Remove "Backups & Scan" menu

projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
This PR fixes some issues when removing speakers from the Conversation block, as well as how they can be restored.
Fixes #
* Conversation: handling removed/restored speakers
p1613141900276100-slack-
No
* Start testing with a new post
* Create a new Conversation/Dialogue blocks composition.
* Create two speakers, and add some Dialogue blocks there:
Description | Screenshot
-------|---------
Like this blocks composition | ![image](https://user-images.githubusercontent.com/77539/107808413-4c4b2c80-6d48-11eb-8840-c412a778d507.png)
From the outline | ![image](https://user-images.githubusercontent.com/77539/107808546-8ddbd780-6d48-11eb-932b-c9bae71b85bb.png)
Two speakers, from the Conversation block | ![image](https://user-images.githubusercontent.com/77539/107808583-9b915d00-6d48-11eb-881c-d632 …
=> Conversation: handling removed/restored speakers

projects/plugins/jetpack/modules/markdown/easy-markdown.php
This PR fixes the error on WPCOM.
```
WordPress database error Table 'wpmu_6cb.wp_1234567_options' doesn't exist for query INSERT INTO `wp_1234567_options` (`option_name`, `option_value`, `autoload`) VALUES ('wpcom_publish_comments_with_markdown', '', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`) made by add_option from <wp server address here> public-api.wordpress.com/rest/v1.1/sites/new?http_envelope=1
```
The markdown plugin listens to the `switch_blog` action and executes `maybe_load_actions_and_filters()`.
However, the `switch_blog` action is also called when a new site is created (site entry exists) but not yet initialized (site db tables not exists).
The fix is to prevent …
=> Markdown: Fix db error missing options table when WP site is being installed.

projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
Updates the "Participant" labels in the sidebar to "Speaker" to be consistent with the DIalogue block placeholder.
| Conversation sidebar | Dialogue sidebar | Dialogue placeholder |
| - | - | - |
| <img width="274" alt="Screen Shot 2021-02-15 at 12 15 49" src="https://user-images.githubusercontent.com/1699996/107984710-257e3780-6f8e-11eb-8d45-f675d51e3fb0.png"> | <img width="273" alt="Screen Shot 2021-02-15 at 12 16 08" src="https://user-images.githubusercontent.com/1699996/107984712-2616ce00-6f8e-11eb-8be9-2cc4076b7ba4.png"> | <img width="381" alt="Screen Shot 2021-02-15 at 12 19 28" src="https://user-images.githubusercontent.com/1699996/107984713-2616ce00-6f8e-11eb-9799-e3c0469c2c13.png">
No
* Insert a conversation block
* See that "Speaker" is used in the sidebar of both the …
=> Conversation/dialogue blocks: use "Speaker" for participant label

projects/plugins/jetpack/extensions/blocks/dialogue/edit.js, projects/plugins/jetpack/extensions/blocks/dialogue/editor.scss, projects/plugins/jetpack/extensions/shared/components/media-player-control/index.js, projects/plugins/jetpack/extensions/shared/components/media-player-control/style.scss
This PR tweaks the speaker input size to try to improve the UX when selecting and in general interacting with the editor.
Fixes #
* Dialogue: Tweak speaker input size
p7DVsv-atS-p2#comment-34465
* Edit/create an empty post
Step | Screenshot
-----|------
Add a Conversation Block | ![image](https://user-images.githubusercontent.com/77539/107993814-2200a580-6fba-11eb-973e-79c7ee872b07.png)
Confirm the speaker input stretches to the whole width. It allows start to edit the speaker by clicking on any place of the input. | ![image](https://user-images.githubusercontent.com/77539/107993876-4197ce00-6fba-11eb-8d99-f2c7a8c5d416.png)
Confirm it's still easily selectable when the speaker has only one character, for instance, a dot `.`. | ![image](https://user-images.githubusercontent.com/77539/107994 …
=> Dialogue: Tweak speaker input size

projects/plugins/jetpack/extensions/blocks/conversation/index.js
This PR uses the function with fallback to creating blocks from a template, since `createBlocksFromInnerBlocksTemplate()` is not available for some WordPress versions.
Fixes #
* Conversation: use fallback for createBlocksBlocksTemplate
No
* Create/edit a post
* Paste a bunch of paragraphs
* transform them to Conversation/Dialogue composition
* *everything should be ok
* Test in WordPress 5.5
*
=> Conversation: use function with fallback to creating blocks from a template.

projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css, projects/plugins/jetpack/modules/masterbar/masterbar/overrides.css
Fixes https://github.com/Automattic/wp-calypso/issues/49793
* Add specificity to admin menu CSS so that they get applied on Atomic sites.
* Additional specificity will display masterbar icons on mobile
No
* Create an Atomic site on your A8C account so that nav unification is enabled.
* Install Jetpack Beta
* Checkout this branch via Jetpack Beta plugin
* Reduce viewport to mobile view and observe changes below
Repeat steps on a non-A8C account to ensure this works as expected for non-nav unified users.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/8639742/107649323-446e8800-6c75-11eb-9884-677ad8088e62.png" /></td>
<td><img src="https://user-images.githubusercontent.com/8639742/107649373-4f291d00-6c75-11eb-8ec5-6812384a2e5e.pn …
=> Override masterbar to show quick links on Atomic sites

.github/workflows/e2e-tests.yml, projects/plugins/jetpack/tests/e2e/jest-playwright.config.js, projects/plugins/jetpack/tests/e2e/package.json
* Used Playwright's video recording capability. Currently there is no option to specify a video file naming pattern. If needed we can address this in the future and find a way to somehow rename the files.
* 800x600 resolution is currently needed to workaround a Playwright issue that is scheduled to be fixed in version 1.9.0
n/a
n/a
* E2E tests should pass and video recordings should be saved in `output/videos`
n/a
=> E2E tests: Add record video option

projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php, projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php
Starting in PHP 8, method_exists() now throws a TypeError when not using an object or a string. Let's avoid any fatals by checking for a valid object first.
Primary issue: #17166
No
* Start on a site running PHP 8.
* Enable the Widget visibility module.
* Go to Appearance > Widgets
* Add a new widget, and add some visibility settings.
* As you attempt to save those settings, you'll notice the Fatal error in your logs.
* Apply the patch.
* You should now be able to save your visibility settings with no errors.
* Anchor.fm / Widget Visibility: avoid fatal errors when using PHP 8
=> Anchor.fm / Widget Visibility: avoid fatal errors when using PHP 8

projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
This PR handles properly the block attributes for the block when they are created by splitting its content.
Fixes #
* Dialogue: handling attributes for split blocks.
p1613477977476200-slack-
No
* Create / Edit a new Conversation/Dialogue blocks composition. Set an speaker value and fill the content.
* Split the content by pressing the ENTER key in the start, middle, and end of the Dialogue content.
**BEFORE**
It doesn't matter how the content was split, the speaker is always propagated to the new block
**AFTER**
The speaker is propagated as long as the new block gets content.
**before** | **after**
------|------
*
=> Dialogue: handling attributes for split blocks

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php
This PR adds a filter to allow a variable number of tracks to be returned when getting a track list. The default remains at ten.
See: 474-gh-Automattic/dotcom-manage
pbAPfg-PF-p2
No.
* TBD
* A filter is now available to modify the number of tracks returned by a Podcast Helper track list.
=> Podcast Helper: Allow filtering the number of tracks returned by get_track_list.

projects/plugins/jetpack/modules/sso.php
When a site has set the `jetpack_use_iframe_authorization_flow` filter to return true, it's possible for a user to be redirected to the in-place connection after approving an SSO connection, when that user is not already connected to the site. This is an issue since the in-place connection is designed in such a way to be embedded in an iframe. Instead, we always want the user to be redirected to the legacy connection flow.
To handle that behavior, this PR removes any previous filters on `jetpack_use_iframe_authorization_flow` and then adds a new filter to return true, to be extra defensive in case we default to passing the filter `true` in the future.
N/A
No
- Spin up JN site
- Connect site
- Enable SSO
- Ensure that setting to allow finding users by email address is on
- Add a filter for …
=> SSO: Disregard filters to use in-place connection when redirecting after SSO

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-jetpack-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49830
We were previously always linking to the Customizer for managing widgets and menus since that's what the existing Calypso nav does. However there are better WP Admin screens for doing that when the user has the "Replace all dashboard pages with WP Admin equivalents when possible." setting enabled or when the WP Admin Customizer is forced on Jetpack/Atomic sites.
This PR adjusts the link destination of Customize, Widgets and Menus according to the table below:
Site | Customize | Widgets | Menus
--- | --- | --- | ---
Simple | `wordpress.com/customize` or `/wp-admin/customize.php`, depends on the link destination setting toggle. | `wordpress.com/customize` or `/wp-admin/widgets.php`, depends on the link destination setting toggle. | …
=> Admin Menu: Fix link destination for Widgets and Menus

projects/plugins/jetpack/modules/shortcodes/instagram.php, projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.instagram.php
Fixes #18389
When one uses the Instagram shortcode to embed an Instagram post, one can provide additional shortcode attributes such as hidecaption. Those attributes are the same options you can add as query strings of the instagram URL when you simply paste an Instagram URL on its own line in the editor and let oEmbed do the work.
Until now, however, although we did pass those shortcode attributes to `WP_Embed::shortcode()`, we did not actually use them when we built the final oEmbed fetch URL.
**Note**: I originally thought to add tests for this, but we already had tests for `jetpack_instagram_oembed_fetch_url`; I just made them a bit easier to parse. 
* N/A
* No
* Go to '..'
*
Shortcodes: use arguments provided by shortcode attributes for the Instagram embeds.
=> Instagram: use arguments provided by shortcode attributes

projects/plugins/jetpack/extensions/shared/icons.js
The `TranscriptIcon` was using an attribute of `stroke-width` which is invalid JSX. This causes an error to be thrown as the icon is used by the inserter, selecting the block etc.
This change makes the attribute `strokeWidth` which fixes the issue.
This is a bug fix to an existing feature.
No.
* Open the developer console. 
* Open the block inserter with `/` or in some other way cause a conversation block to render its icon.
* Without this PR you should see an error saying `Warning: Invalid DOM property `stroke-width`. Did you mean 'strokeWidth'?`
* With this PR, there shouldn't be any error.
N/A This is a minor bug fix
=> Conversation Block: Correct the strokeWidth attribute in the icon

projects/plugins/jetpack/modules/videopress/utility-functions.php
In some scenarios, the following notice happens:
```
PHP Notice:  Undefined property: stdClass::$rating in /home/holden/apps/jeherve_com/w/wp-content/plugins/jetpack-dev/_inc/lib/core-api/wpcom-fields/class-wpcom-rest-api-v2-attachment-videopress-data.php on line 97
```
Let's make sure we always have at least a default rating.
* N/A
* No
Testing instructions are similar to the ones in #17659. 
* Start with a site with a paid plan, and where you've activated VideoPress under Jetpack > Settings > Performance.
* In a post, add a /video block and upload a new video
* Once the video has uploaded, change the value for Rating in the sidebar. It will save automatically.
Open the Media Library, find your video and open it
* The rating in the media library should match the rating you selected on …
=> VideoPress: avoid warning when no rating is set

.github/actions/repo-gardening/src/tasks/check-description/index.js
Follow-up from #18558.
When we do not have any plugin info, let's not try to add anything to the comment.
You can see the bug in action here:
https://github.com/Automattic/jetpack/pull/18877#issuecomment-781887430
* N/A
* No
* Check the comment below.
* N/A
=> Actions: do not add milestone info to comment when undefined

.github/actions/repo-gardening/src/if-not-closed.js, .github/actions/repo-gardening/src/index.js
Follow-up to #18558.
We do not have to keep editing labels or comments on PRs that are closed.
Here is an example: #18881 Since I removed status labels from that PR, the action ran, the comment was updated, and a label was added:
* N/A
* No
* See that the comment was properly added below, and that no "needs author reply" was added back to that closed PR: #18883 
* N/A
=> Actions: do not run label and comment automations on closed PRs

projects/plugins/jetpack/modules/wordads/php/class-wordads-api.php
This is a possible solution for https://github.com/Automattic/jetpack/issues/10063
The wordads module has code in it that converts settings from booleans to a string representation of a boolean prior to saving them via update_option(). True to '1'. False to '0'. The phpdocs for the functions specifically state that booleans should be returned.
There are 4 option values affected. All of them are directly related to the wordads module. wordads_approved, wordads_active, wordads_house, and wordads_unsafe
This conversion from true booleans to a string representation does not appear to be harmful but it is unnecessary. It can also make the function documentation appear to be wrong and undermining trust in the docs appears unwise. "The docs say it returns a boolean but it clearly returns a …
=> Avoid unnecessary converting of booleans to strings in the WordAds module

projects/plugins/jetpack/_inc/lib/class.jetpack-keyring-service-helper.php, projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/publicize-services.php
Alternative approach to #13799, so the Keyring services can use the Sharing page without the need of being explicitly registered as an empty menu item.
Before | After
--- | ---
N/A.
No.
- With this patch on, go to Jetpack > Settings > Sharing and disable all modules.
- Check the Settings menu, and make sure there isn't any empty submenu item linking to `options-general.php?page=sharing`.
- Go to Jetpack > Settings > Traffic
- Try to automatically verify your site with Google.
- The pop up that opens should lead you to Google.
- Go to Jetpack > Settings > Sharing and enable at least one module.
- Check the Settings menu, and make sure there is a Sharing submenu item linking to `options-general.php?page=sharing`.
- Go to Jetpack > Settings > Traffic
- Try to automatically verify your site …
=> Keyring: Register Sharing page without menu

projects/packages/sync/src/class-settings.php, projects/packages/sync/src/replicastore/class-table-checksum.php
The Checksum process rolled out in Jetpack 9.3 did not limit taxonomies based on existing blacklists. This update overhauls the table configuration and supporting functionality so that we don't identify content as missing that is not supposed to be Synced to the cache site.
* Updates taxonomy checksums to exclude blacklisted taxonomies.
* No
* Perform a checksum of all tables.
```$rs = new Automattic\Jetpack\Sync\Replicastore();```
* Verify that no errors are returned and we have a checksum for all 7 tables 
* Note the checksum values for terms, term_taxonomy and term_relationships
* Add a new taxonomy of "ancestors", "comments_number", "the_categories" and "usermeta"
* Add terms to each of the new categories
* Add terms to existing posts
* Perform a new checksum of all tables.
* Verify …
=> Update Checksums to support blacklisted taxonomies.

.github/ISSUE_TEMPLATE/plugin_jetpack-beta.md
* The Beta plugin label is now just "Beta".
* N/A
* No
* Not much to test here; just look at the label name here ->
* N/A
=> Issues templates: update label name for Beta plugin

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php
As part of the Anchor.FM integration we'd like to set the publish date of the generated posts to the publish date of the podcast episode. This information could also be of use in other contexts.
This change adds the UTC publish date to the track information, formatted for use as the post's `post_date_gmt`.
N/A this is an enhancement to an existing feature.
No.
* Insert a podcast block
* Open the developer console and select the network requests tab
* Set a valid podcast feed - e.g. https://www.spreaker.com/show/3314543/episodes/feed
* Check the next requests for the `podcast-player` request. 
* You should see the `publish_date` included for each of the episodes in the response
Added the publish date to the track details of the podcast player API endpoint.
=> Podcast API Endpoint: Add the publish date to the track information.

projects/plugins/jetpack/_inc/lib/debugger/class-jetpack-cxn-tests.php
Adapts the Connection healthy checks to skip Master User tests when running userless mode
* Skip some connection tests when in userlessmode
N/A
no
* Start with a new not connected site
* Define the `JETPACK_NO_USER_TEST_MODE`
* Go to Tools > Site Health
* Go under passed tests and look for "Master User Exists On Site" and "Master User Can Manage Options" tests
* Confirm they were skipped with a message saying Jetpack is not connected 
* Connect Jetpack only at a site level
* Visit `/wp-admin/admin.php?page=jetpack-debugger` and make sure `Your Jetpack setup looks a-okay!`
* Go to Tools > Site Health
* Go under passed tests and look for "Master User Exists On Site" and "Master User Can Manage Options" tests
* Confirm they were skipped with a message saying Jetpack is in user-less mode
* …
=> Skip master user tests when in userless mode

projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php, projects/plugins/jetpack/modules/related-posts/related-posts.js
This PR removes `jQuery` as a dependency to the Related Posts script, by reimplementing the latter in IE 11-compatible ES5.
* Remove `jQuery` dependency from Related Posts
None.
No.
* In your test blog, make sure you enable the Related Posts Jetpack feature.
* Create several classic content blog posts (not Gutenberg). In my testing, I created 4 posts using the same tag and with similar short content.
* Open one of the blog posts and ensure that Related Posts are shown. They should be loaded dynamically via JS, so you'll see them pop in shortly after the page is first rendered.
* Apply this PR.
* Ensure that Related Posts are still shown, in the exact same way.
* Ensure that the admin pages for the feature still work correctly.
* Ensure that the customizer for the feature still works …
=> Remove jQuery from Related Posts

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/publicize-services.php
Fixes a regression introduced by https://github.com/Automattic/jetpack/pull/18861 since the `Jetpack_Keyring_Service_Helper` class is not available in WP.com.
N/A.
No.
* Apply D57190-code to your WP.com sandbox.
* Sandbox the API.
* Go to the [WP.com API console](https://developer.wordpress.com/docs/api/console/).
* Make an `GET` request to `wpcom/v2/sites/:site/publicize/services` for a Simple site.
* Make sure it returns a 200 response.
N/A.
=> Fix Publicize Services endpoint on WP.com

projects/plugins/jetpack/modules/widgets/class-jetpack-instagram-widget.php
The Instagram widget requires a User connected to Jetpack in order to work. 
With the upcoming User-less connection, it's nice that we display a proper message when a disconnected user attempts to use the widget, otherwise they would see a "Instagram is having connectivity issues" which is not true.
By the way, this is what happens today when secondary disconnected users try to use the widget, so this PR also fixes it.
* Adds a proper message in the Instagram widget form for disconnected users
N/A
no
* Create a Jetpack site and define the `JETPACK_NO_USER_TEST_MODE` constant.
* Connect the site only at a site level
* Go to Appearance > Widgets, and add the Instagram widget
* Confirm you see a message telling that you have to connect your user to Jetpack
* Click the link and confirm you …
=> Adds message to Instagram widget form for disconnected users

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49211
Add a new menu item to the new unified menu on WoA sites that links to the WP Admin user lists screen, so users can continue editing users from there as they have been doing with the old menu (currently enabled in production to all non-a8c users). This is especially useful for WooCommerce sites with the Product Vendor extension installed.
This PR also includes a small refactoring of the `add_users_menu` function, to make the code a bit more maintainable.
paYJgx-1lp-p2#comment-1661
No
- Install Jetpack Beta on a WoA site and activate the branch of this PR.
- Go to https://wordpress.com and switch to that WoA site.
- Make sure there is a new "Users > Advanced Users Management" menu entry that links to `/wp-admin/users.php`.
- Go to …
=> Admin Menu: Add "Advanced Users Management" menu on WoA sites

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50249
[Some plugins like WooCommerce make use of WP CSS class `hide-if-js` to avoid showing menu items that shouldn't be there](https://github.com/woocommerce/woocommerce-admin/blob/07d26b12847647b273db2c285315b7dfa8f550ec/src/Features/Navigation/CoreMenu.php#L292-L299), but not remove them completely so their routes remain available.
To mimic that behavior, this PR excludes any menu and submenu item that contains the `hide-if-js` class from the `wpcom/v2/admin-menu` API response.
N/A.
No.
- Try to replicate first the issue on a Jetpack site running the `master` branch by adding the code below to a mu-plugin:
```
add_filter( 'jetpack_load_admin_menu_class', '__return_true' );
add_action( 'admin_menu', function () {
add_menu_page( 'My …
```
=> Admin Menu: Exclude hidden items from API response

projects/plugins/jetpack/_inc/client/components/settings-card/index.jsx
Sites that are enrolled in WordAds should still be able to update their ads settings, even if the site no longer meets the plan eligibility. This PR fixes the check that was preventing site admins from accessing their Ads settings.
No
* Setup a test site with an eligible plan enrolled in WordAds
* Remove the plan
* Verify the Ads settings at Jetpack > Settings > Traffic are displayed, and able to be modified
* N/A
=> Ads: Fixes check for displaying the Ads module settings

projects/plugins/jetpack/modules/protect/blocked-login-page.php
`wp_robots_no_robots()` replaces `wp_no_robots()` in WP 5.7:
https://core.trac.wordpress.org/ticket/51511#comment:13
Primary issue: #18842 
* No
* Add the following constant to your site: `define( 'JETPACK_ALWAYS_PROTECT_LOGIN', true );`
* Connect your site to WordPress.com; Protect should be automatically enabled.
* Log out
* Try to log back in.
* See the new blocked login page.
* Whether you use WordPress 5.6 or WP 5.7 (via the WordPress Beta Tester plugin for example), you should see a `<meta name='robots' content` meta tag in the page's `head`.
* Protect: use new Robots API introduced in WordPress 5.7 when displaying a blocked login page.
=> Protect: introduce new wp_robots_no_robots when available

projects/plugins/jetpack/modules/comments/comments.php, projects/plugins/jetpack/modules/publicize/publicize-jetpack.php
* This follows-up #18812, and should avoid fatals when trying to use one of the 2 features.
* N/A
* No
* Go to Jetpack > Settings and enable the Comments and Publicize modules
* You shouldn't get any fatal errors on your site. 
* N/A
=> Comments / Publicize: add missing Tokens imports

composer.json, composer.lock
That release fixes a bug that can cause files changed in both the
current branch and in the base branch since the branchpoint to show
warnings from unchanged lines.
p1612859631270800-slack-CBG1CP4EN
No.
* `composer install` and see that phpcs-changed 2.7.1 is now used. You might also try to reproduce [the bug](https://github.com/sirbrillig/phpcs-changed/issues/42) that that release fixes if you want.
* None needed.
=> Use phpcs-changed 2.7.1

projects/packages/autoloader/phpunit.xml.dist
The coverage test isn't actually running, PHPUnit complains
Warning: Incorrect filter configuration, code coverage will not be processed
This turns out to be due to the attempt to exclude a "views" directory
that does not exist.
Fixing this reveals another bug: bootstrap.php sets up a symlink from
tests/php/tmp/wp-content/plugins/current/vendor/automattic/jetpack-autoloader
back to the root directory, and PHPUnit is apparently not smart enough
to handle that when trying to find the files to cover
(sebastianbergmann/php-code-coverage#849). Work around that by adding
`src` specifically instead of adding `.` then trying to exclude `tests`.
None.
No.
* Does the Code Coverage job generate coverage for automattic/jetpack-autoloader?
* None needed.
=> Autoloader: Fix coverage test

projects/plugins/jetpack/_inc/client/security/monitor.jsx
* Removes target property so that downtime monitoring notification settings opens in same tab
- Automattic/wp-calypso#50225
- p1HpG7-bcl-p2
No
* Checkout patch
* On a connected Jetpack site, go to Security tab
* Click "Configure your notification settings" card  and verify that the settings tab does not open in new page
* Opens downtime monitoring notification settings in same tab
=> Monitor: Do not open monitor notification preferences in new tab

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
Removes the group block from the Anchor.fm podcast episode post template to work around an issue where content in the group block doesn't display in the post excerpt.
https://github.com/WordPress/gutenberg/issues/26706
| **Before** | **After** |
| - | - |
| <img width="622" alt="Screen Shot 2021-02-22 at 15 36 22" src="https://user-images.githubusercontent.com/1699996/108773342-cbe4b280-7523-11eb-8dfa-7f49d4119724.png"> | <img width="622" alt="Screen Shot 2021-02-22 at 15 35 34" src="https://user-images.githubusercontent.com/1699996/108773356-d4d58400-7523-11eb-8ffb-847863b7d148.png"> |
No
1. Visit a url that creates a podcast start post, with the necessary Anchor information in the query parameters, (e.g. `/wp-admin/post-new.php?anchor_episode=fb1dcaa4-bf8c-43dc-92e1-7b46b7a77a2b&anchor_p …
=> Anchor.fm: Remove group block to prevent blank excerpt

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-jetpack-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/jetpack/issues/18831
- Add back the submenus of the Plugins menu when they link to WP Admin (only Atomic sites).
- Force the Plugins menu to link to Calypso on Simple and Jetpack sites (to mimic the behavior of the existing/old navigation).
N/A.
No.
_Simple_
* Go to https://wordpress.com/me/account and disable the "Replace all dashboard pages with WP Admin equivalents when possible." setting.
* Apply D57572-code to your WP.com sandbox.
* Sandbox the API and a Simple site.
* Go to https://wordpress.com and switch to that site.
* Make sure that the Plugins menu links to Calypso.
* Enable now the "Replace all dashboard pages with WP Admin equivalents when possible." setting.
* Make sure that Plugins still links to Calypso.
_Jetpack_
* Go to …
=> Admin Menu: Keep Plugins submenus when they link to WP Admin

projects/plugins/jetpack/extensions/blocks/contact-form/editor.scss
Fixes #18930
This PR adds a minimum width to the form block settings so each field can be easily edited.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/426388/109128030-5a894780-774f-11eb-9fc1-f692f7173745.png" /></td>
<td><img src="https://user-images.githubusercontent.com/426388/109128079-6a089080-774f-11eb-9bd6-3a0ff506d27f.png" /></td>
</tr>
</table>
* N/A
* No
This is worth testing in different environments:
- On a site running WP 5.6
- On a site running WP 5.7
- On a site running WP 5.7 + the Gutenberg plugin
* On all sites, enable the contact form module (that's done for you when you connect a site to WordPress.com) and add a form block to a post. 
* After adding the form, select the main form block (not one of the …
=> Form: ensure that the form settings look good in WP 5.7+

projects/plugins/jetpack/tests/e2e/.gitignore, projects/plugins/jetpack/tests/e2e/lib/flows/jetpack-connect.js, projects/plugins/jetpack/tests/e2e/lib/logger.js, projects/plugins/jetpack/tests/e2e/lib/pages/wpcom/login.js, projects/plugins/jetpack/tests/e2e/lib/setup-env.js
After WPCOM login save the browser storage in a file and pass it the next time the browser context is reset. This way we don't need to login on each test.
n/a
n/a
* Login to WPcom is done only once at the beginning. For each subsequent test the user should be already logged in.
* All E2E tests should pass.
n/a
=> E2E tests: Save browser storage and reuse the wpcom session

projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php
Adds back the Theme Editor submenu to the new unified menu on Atomic sites, so users don't lose access to this feature (which was already available in the existing navigation).
No.
N/A.
* Install Jetpack Beta on a WoA site and activate the branch of this PR.
* Make sure there is a "Theme Editor" submenu under "Appearance" that links to `/wp-admin/theme-editor.php`.
N/A.
=> Admin Menu: Add Theme Editor submenu on Atomic sites

projects/plugins/jetpack/modules/widgets/class-jetpack-instagram-widget.php
This is a possible fix for https://github.com/Automattic/jetpack/issues/17801
When first dragging the instagram widget into a widget area some PHP errors occur (visible with Query Monitor). The errors are the result of accessing undefined array indexes.
Fixes #17801 
I have added some simple isset() checks. $instance contains all the default values. It is updated with supplied values if the relevant array index is defined. 
No change in behaviour is expected (apart from not producing errors)
I am not an Automattician.
No
* Enable extra sidebar widgets https://jetpack.com/support/extra-sidebar-widgets/
* Install and enable Query Monitor
* Go to /wp-admin/widgets.php and drag the "Instagram (Jetpack)" widget into a widget area. No php errors should result.
If the Instagram widget doesn't …
=> Avoid accessing undefined indexes in Instagram widget

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50373
* Removes markup of counter while keeping the counter
* Removes unexpected markup while keeping the markup
Counter cases:
- `<span class="update-plugins count-[NUMBER]"><span class="update-count">[NUMBER]</span></span>` for Updates
- `<span class="update-plugins count-[NUMBER]"><span class="plugin-count">[NUMBER]</span></span>` for Plugins
- `<span class="awaiting-mod count-[NUMBER]"><span class="pending-count" aria-hidden="true">[NUMBER]</span><span class="comments-in-moderation-text screen-reader-text">[NUMBER] Comments in moderation</span></span>` for Comments
Markup cases:
- `<font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Site editor </font></font><span class="awaiting-mod"><font …
=> Parses count and removes the counter markup from title of admin_menu api response.

projects/plugins/jetpack/_inc/lib/markdown/gfm.php, projects/plugins/jetpack/tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php, tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php
Fixes #10595
Closes #17761
* This is an alternative approach to #17761, trying to solve the issue for all types of links that may include underscores, whether we use the Shortcodes feature or not.
* N/A
* No 
* Go to Jetpack > Settings > Writing, and enable the Markdown feature.
* Go to Plugins > Add New, install and activate the Classic editor plugin.
* Go to Posts > Add New, and start writing a new post. 
* Try testing with different types of Markdown content; you can find some examples [here](https://daringfireball.net/projects/markdown/syntax).
* You can also focus on links in Markdown, in different formats, with or without underscores:
- `https://twitter.com/_sagesharp_/status/1323662905716273152` on its own line.
- `[A link with underscore in URL](https://jetpack.com/_features_/)`
- …
=> Markdown: avoid processing URLs that may include Markdown syntax

tools/eslint-changed.js
We're using `git diff gitBase...HEAD` to get a diff for line number
correction, which uses the merge-base of gitBase and HEAD as the left
side of the diff rather than gitBase itself.
But when we run eslint, we run it against the file versions from gitBase
itself rather than from the merge-base commit.
This can break the line number correction and result in unchanged issues
being reported as changed.
p1612859631270800-slack-CBG1CP4EN
No.
* Make a branch A.
* Make a branch B from A that touches a file with eslint warnings, preferably without actually adding or removing any lines or affecting any of the warnings.
* Add a commit to A inserting or removing lines early in the file. Do not merge this into B.
* On branch B, execute `tools/eslint-changed.js --git --git-base=A the-file.js`.
* None …
=> eslint-changed: Use merge-base to fetch old file versions

projects/plugins/jetpack/extensions/blocks/premium-content/logged-out-view/logged-out-view.php
Relative path includes are not allowed on wpcom.
* N/A
* No
* Start from a site with a Paid plan, and with the Beta blocks enabled.
* Create a new post with a Premium Content block, connected to Stripe, and with a paid plan.
* Add some content for logged out users.
* Publish post
* View the page while logged out, the "Log In" button should be displayed.
* N/A
=> Premium Content: update require for logged out view button

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50059
This PR updates the `admin-menu` endpoint in order to mimic the behavior done by Core in which it always uses the URL of the first submenu in the parent menu, so they both link to the same page: https://core.trac.wordpress.org/browser/trunk/src/wp-admin/menu-header.php?rev=49193#L152
N/A.
No.
* Spin up a Jetpack site running the `master` branch.
* Add the code below to a mu-plugin.
```
add_action( 'admin_menu', function () {
add_menu_page( 'My Plugin', 'My Plugin', 'read', 'index.php?page=my-plugin', '', '', 0 );
add_submenu_page( 'index.php?page=my-plugin', '1st submenu', '1st submenu', 'read', 'index.php?page=my-plugin-1', null, 0 );
}, 100000 );
```
* In the WP.com API console, make a `GET` request to the …
=> Admin Menu: Use first submenu URL as parent menu URL

projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php, projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
* Rely on core's `WP_Automatic_Updater` class to check if any of the `update_plugins` items `should_update()`.
* Rely on core's `WP_Automatic_Updater` class to pass on an accurate `autoupdate` value for plugin items, as that value is currently [used](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/plugins/installed/actions.js#L520) in Calypso plugin management screens to fire update requests.
See #18562
No
* With this change pulled down, connect Jetpack to WordPress.com
* Install a plugin for testing such as Hello Dolly, and `Enable auto-updates` for the plugin from WP Admin
* Add `add_filter( 'auto_update_plugin', '__return_false' );` to a mu-plugin for testing.
* Rollback the version of the plugin you enabled auto-updates for using something like the WP Rollback plugin. …
=> Update plugin API endpoints to use should_update

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php
Relates to https://github.com/Automattic/wp-calypso/issues/49568
This is the WP Admin version of https://github.com/Automattic/wp-calypso/pull/50586/files
- For simple sites that haven't selected "Replace all dashboard pages with WP Admin equivalents when possible." we always load customizer in `https://wordpress.com/customize/' . $this->domain`;
- In other cases where customizer will open in WP Admin, if the request is not coming from the API (calypso) we add as a `return` param the current url.
**In your sandbox simple site**
- Apply this patch
- Turn on "Replace all dashboard pages with WP Admin equivalents when possible."
- Go to WP Admin
- Go to Appearance -> Customizer
- Click exit
- You should return to your initial page
**API**
- Go to …
=> Adds return url param for customizer link.

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50498
Fixes https://github.com/Automattic/wp-calypso/issues/50501
I'm not sure why, but it seems that unregistering the Dashboard menu and registering it again with the same slug causes some side effects to their submenus like the issue noted in https://github.com/Automattic/wp-calypso/issues/50498.
To work around that, this PR makes sure that the "Dashboard" > "My Home" replacement happens by directly updating the `$menu` global instead of unregistering/registering the menu.
N/A.
No.
_Simple_
- Apply D57840-code to your WP.com sandbox.
- Sandbox a Simple site.
- Go to https://wordpress.com/me/account and enable the "Replace all dashboard pages with WP Admin equivalents when possible" setting.
- Go to …
=> Admin menu: Update "Dashboard" menu instead of removing/adding it

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50550
Follows up https://github.com/Automattic/jetpack/pull/18898
This PR ensures that submenus are not included as children of hidden menus in the `admin-menu` API endpoint, in order to replicate the behavior in WP Core.
N/A.
No.
- Try to replicate first the issue on a Jetpack site running the `master` branch by adding the code below to a mu-plugin:
```
add_filter( 'jetpack_load_admin_menu_class', '__return_true' );
add_action( 'admin_menu', function () {
add_menu_page( 'My Plugin', 'My Plugin', 'read', 'my-plugin', '', '', 0 );
add_submenu_page( 'my-plugin', 'Submenu', 'Submenu', 'read', 'my-submenu' );
global $menu;
$menu[0][4] .= ' hide-if-js';
}, 1000000 );
```
- Load WP Admin and note how the menu and submenu are not visible: …
=> Admin Menu: Remove submenus from hidden menus

projects/packages/connection-ui/.gitattributes
* We do not need the `.github` directory in the production package of the Connection UI.
N/A
No
* N/A
=> Connection UI: remove .github directory from production package

projects/plugins/jetpack/class.jetpack.php
Fixes the silence if this deprecated method is used. Without it, theres no way for someone to know without reading the code. 
This was the only instance I found, searching for the comment string `* @deprecated since` in .php files, and manually looking through. Can anyone find more? 
Throws a deprecation notice if used. 
N/a
no
- Spelling
- Version 
- Is the suggestion for new method correct?
N/A
=> Deprecated Method: Throw deprecation notice if used

tools/cli/commands/generate.js
Adds a default prefix (action- or jetpack-) for a project slug.
* See above.
n/a
n/a
* Run `jetpack generate` and start a new project. Confirm that the composer.json in the new project is automattic/{prefix}-{name}.
*
* n/a
=> CLI: Add a prefix for the name of a generated project.

projects/plugins/jetpack/functions.opengraph.php
This PR reverts  #18654 which was conflicting with Newspack blocks.
Fixes https://github.com/Automattic/wp-calypso/issues/50672
The issue:
Newspack blocks have a logic to prevent posts from being displayed more than once on the page, even by different blocks.
When we called `do_blocks` it was as if we were rendering a first version of the block. Then, when the actual block was being rendered, it would exclude all the posts that were returned in the first (fake) render.
* Revert #18654
* p1614716941027400-slack-C02FMH4G8
No
* Check the slack thread
* Revert improvements to the `og:description` meta tag since it was conflicting with Newspack blocks
=> Fixes conflict with Newspack blocks

projects/plugins/jetpack/modules/latex.php
Removing the title tag from the generated image.  
Fixes #18954
* This is a change to remove the title tag from the image this module generates.  
This was first noted here 3777668-zen
No
Add sample LaTex code to a page/post.  Look at the HTML of the generated image.  The title attribute should be removed. 
Remove title attribute from Beautiful Math generated LaTex image. 
This is my first pull request so please let me know how better I can test this out!
=> Beautiful Math - Remove title attribute from module generated image

projects/plugins/jetpack/extensions/blocks/anchor-fm/editor.js
Related to 515-gh-Automattic/dotcom-manage
* Anchor post publish link: Change to primary button
No
_(How I test jetpack code; you may have a better way)_
* `cd projects/plugins/jetpack`
* `yarn build-extensions --watch`
* Rsync or copy  `./_inc` to `mu-plugins/jetpack/_inc` on sandbox
* Visit sandboxed site
_(These specific changes)_
* Publish the post
* Check the post publish sidebar on the right side
* The anchor related link ("Create a podcast episode") is now a primary button instead of a text link
* Anchor post publish link: Change to button
=> Anchor post publish link: Change to primary button

projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
~This PR fixes a bug when the user selects multiple blocks. It changes the speakers of some Dialogue blocks because the app detects that the block is selected, and consequently updates the speaker.~
This PR handles the propagation of the speaker-name changes among all Dialogue sibling blocks closely.
It checks if whether the participant label and the current block label are different before applying the changes, also checks if there is a multi-blocks-selection, and finally it removes the debouncing when setting attributes.
Fixes #
* Conversation: Handle closely speaker-name changes propagation
p7DVsv-atS-p2#comment-34479
No
* Create Conversation/Dialogue composition
* Defines some speakers for them
**before**
In the following video, the speaker changes from `James` to `Jimmy` just because …
=> Conversation: Handle closely speaker-name changes propagation

projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/editor.scss
This PR improves the way of handling the speaker's autocompleter.
Fixes #
* Dialogue: improve speakers autocomplete handling
> When the suggestion text is the same as the label I’ve already entered, and there’s just one suggestion, I wouldn’t expect to see suggestions at all:
> <img src="https://user-images.githubusercontent.com/77539/108090614-93436580-7059-11eb-9e54-5a57729e1f87.png" width="300px" />
p7DVsv-atS-p2#comment-34461
No
Test the whole implementation gets a little bit tricky. The best way to do it is by paying attention to the CSS class defined in the participant element:
State | Canvas | Element Inspector
-----|------|-----
Create a new block ( **ready** - initial state) | ![image](https://user-images.githubusercontent.com/77539/108091128-254b6e00-705a-11eb-8084-cc6eff1cfc8a.p …
=> Dialogue: improve speakers autocomplete handling

projects/plugins/jetpack/extensions/blocks/podcast-player/edit.js
A bug with a refactor of `withNotices` in Gutenberg WordPress/gutenberg#28676 causes the Podcast Player block to get stuck in an infinite loop. This was fixed in Gutenberg WordPress/gutenberg#29491 but the problem is still present for anyone with Jetpack and Gutenberg 10.1 active - which is currently the case on WordPress.com 😱 
* Remove the `noticeOperations` dependencies from the `useEffect` in the podcast player block.
Primary issue: #19038 
No
* Have both Jetpack and Gutenberg 10.1.0 active on a site
* Insert a podcast player block
* Set the RSS URL
* Notice it gets stuck in a loop
* With this patch the problem should be fixed
I'm not sure if it needs one but
* Fixed an infinite loop when loading the podcast player block
=> Podcast Player: Remove the noticeOperation dependencies from the API callback

projects/plugins/jetpack/extensions/blocks/instagram-gallery/use-instagram-gallery.js
* Removes notices dependency as this is causing an infinite rerender issue https://github.com/WordPress/gutenberg/pull/29491. This gutenberg patch doesn't fix the issue for the Instagram block, as it used noticeOperations instead of createErrorNotice as a dependency.
Primary issue: #19038 
No
* Add instagram latest posts block along with latest gutenberg plugin release and make sure block operates as normal
* Removes the notices dependency in the customhook useEffect as changes in the notices dependency shouldn't cause the api calls to rerun.
=> Fix instagram infinite loop bug

projects/plugins/jetpack/extensions/blocks/opentable/edit.js
* Like #19034, this fixes the same issue with the Opentable block. Having `noticeOperations` in the dependency array causes the editor to hang as it gets into a render loop.
Primary issue: #19038
No
* Add an Opentable block with Gutenberg 10.1.0 active
* The editor will hang
* With this PR, it should work as expected
* Check that you still receive a notice when the block is not wide or full aligned and the wide style is selected
* Remove the noticeOperations dependency from the useEffect in the OpenTable block to prevent a loop caused from a change in Gutenberg 10.1.0
=> Opentable: Remove noticeOperations from the useEffect dependencies

projects/plugins/jetpack/_inc/client/main.jsx
When navigating the different pages of the Jetpack dashboard, we aim to display a footer with useful links. Let's display that footer when on Recommendations pages as well.
* N/A
* No
* Go to Jetpack > Dashboard. You should see a footer with links.
* Navigate to Jetpack > Recommendations: you should see the footer there as well.
* N/A
=> Recommendations: display footer.

.github/workflows/linting.yml
PR #18504 increased the limit for one job that was consistently hitting
the old 5-minute timeout, but not the other two. Lately I've been
noticing that one of those other two has been barely hitting the timeout
too on occasion, and I see the other is at ~4:30 too, so let's bump them
too.
None.
No.
* Does CI still work?
* None needed.
=> linting: Increase time limits for eslint jobs

projects/packages/connection/src/class-manager.php, projects/plugins/jetpack/class.jetpack.php
It seems that checking for offline mode takes a few milliseconds, and
those milliseconds quickly add up when done on every capability check.
p1614972521076300-slack-CBG1CP4EN
No.
* Is Jetpack's multisite test completing significantly faster than before?
* Something about performance, maybe.
=> Jetpack, connection: Only check offline mode when needed in map_meta_cap filters

projects/plugins/jetpack/modules/gravatar-hovercards.php
Fixes #19052
* Prevent attempting to do Gravatar Hovercards for non-comment comments (e.g. Pingbacks and Trackbacks).
1. Activate the AMP plugin.
2. Enable Standard template mode or Transitional template mode.
3. Navigate to the AMP version of a post that has comments including pingbacks.
4. Verify the pingback URL goes to the expected location and not `#!`.
* Fix AMP compatibility with Gravatar Hovercards for Pingbacks and Trackbacks
=> Prevent attempting to do Gravatar Hovercards for Pingbacks and Trackbacks

projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
Note: this bug is fixed on Atomic via 628-gh-Automattic/wpcomsh but we need this follow up in JP 9.6 to sort things correctly.
Prior to application of 628-gh-Automattic/wpcomsh on a Jetpack site (in Atomic) going to /wp-admin/admin.php?page=jetpack#/dashboard will cause the **Plugins** menu item to be highlighted. This is because we have a bug in `add_plugins_menu` which uses an incorrect slug: 
```diff
diff --git a/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
index 0231813e7..891c13b4e 100644
--- a/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
+++ b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
@@ -512,7 +512,7 @@ class …
```
=> Fix Jetpack slug for Nav Unification

projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css
Fixes https://github.com/Automattic/wp-calypso/issues/50695
I scanned the codebase for `160px` which is the core sidebar width and found the following
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/_inc/client/components/global-notices/style.scss#L30
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/_inc/client/components/jetpack-dialogue-modern/style.scss#L16
which are changed to `272px` for nav-unification in this PR
- I haven't found how to invoke this components
Before | 
-------|
*  Fixes wrong navbar width in jetpack modal / notices
=> Fixes sidebar width in dialogue and notices components.

projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
WordPress.com merge.
- r221604-wpcom
- D57570-code
The `media_errors` value in this endpoint response is inconcistent
It can sometimes be an array, and sometimes an object.
This happens because we set the errors array key to the uploaded media id.
And php’s `json_encode` just does this:
```
$> return json_encode( [ 0 => 'Element Zero', 1 => 'Element One' ], JSON_PRETTY_PRINT )
'[
"Element Zero",
"Element One"
]'
$> return json_encode( [ 0 => 'Element Zero', 2 => 'Element Two' ], JSON_PRETTY_PRINT )
'{
"0": "Element Zero",
"2": "Element Two"
}'
```
This is documented behavior - see https://www.php.net/manual/en/function.json-encode.php#example-3967
With this change, we will always return an array.
Note that the [endpoint documentation](P2gHKz-g-p2.2/post/sites/%24site/posts/new/) does not …
=> rest-api: update the new/update post endpoints to always return media errors as an array

projects/packages/changelogger/bin/changelogger, projects/packages/changelogger/changelog/add-changelogs-for-everything.2
It only really worked right in the monorepo when changelogger had been
installed. It broke if it was symlinked in from the built copy or if
pulled in from packagist.
Split this out from #19031.
None.
No.
* Run `bin/changelogger` from within `projects/packages/changelogger`, after running `composer install`.
* Delete `projects/packages/changelogger/vendor`, then try the following:
* Go to `projects/plugins/jetpack`, run `composer install`, then try `vendor/bin/changelogger` and `vendor/automattic/jetpack-changelogger/bin/changelogger`.
* Create a new "project" in `/tmp` or somewhere with a composer.json like
```json
{
"require-dev": {
"automattic/jetpack-changelogger": "@dev"
},
"repositories": [ {
"type": "path",
"url": "/path/to/projects/packages/changelogger",
"options": {
"symlink": …
```
=> changelogger: Fix autoload.php finding logic

.github/files/setup-wordpress-env.sh
We started running `composer install || composer update` because we can
no longer have one composer.lock that works for all versions. But it
turns out that GH sees the error messages output by `composer install`
and creates (huge) annotations about them even though they didn't make
the test actually fail.
Let's try avoiding that by using `composer check-platform-reqs` to see
whether we need to run `composer update` or `composer install`.
None.
No.
* Are there spurious annotations from the PHP 5.6 and 6.0 jobs in the "Tests" workflow output?
=> CI: Avoid spurious GH annotations when setting up test env

projects/packages/autoloader/src/class-autoloader.php, projects/packages/autoloader/src/class-container.php, projects/packages/autoloader/src/class-shutdown-handler.php, projects/packages/autoloader/tests/php/tests/unit/ShutdownHandlerTest.php
Fixes #18996
When `Plugin_Locator::find_current_plugin()` is unable to find the plugin containing the autoloader it throws an exception. Normally this should never happen but during uninstallation a plugin might be deleted in the same request it is deactivated. When this happens it won't be able to locate the plugin with the autoloader and will throw the exception. This PR takes the safest approach and clears the autoloader cache so that the next request can rebuild it (if necessary).
N/A
No.
Just noting here that I've added a test case covering the bug.
* Install Jetpack `wp plugin install jetpack --activate`
* Uninstall Jetpack `wp plugin delete jetpack`
* Verify no error is present in console.
* Autoloader: Fix uninstallation fatal.
=> Autoloader: Fix Uninstallation Fatal

projects/plugins/jetpack/tests/e2e/README.md, projects/plugins/jetpack/tests/e2e/lib/blocks/word-ads.js, projects/plugins/jetpack/tests/e2e/lib/env/global-setup.js, projects/plugins/jetpack/tests/e2e/lib/logger.js, projects/plugins/jetpack/tests/e2e/lib/pages/page.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/block-editor.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/jetpack.js, projects/plugins/jetpack/tests/e2e/package.json, projects/plugins/jetpack/tests/e2e/specs/free-blocks.test.js, projects/plugins/jetpack/tests/e2e/specs/pro-blocks.test.js, projects/plugins/jetpack/tests/e2e/yarn.lock
* Move away from wordpress/e2e-test-utils. There were 2 simple actions in block editor used from this library: search for block and click on block toolbar
* Propose a Page class design in BlockEditorPage, with getters for elements selectors, so we don't spread selectors all over. It should help keep things more maintainable.
n/a
n/a
* All E2E tests should pass
n/a
=> E2E tests: Remove e2e-test-utils

tools/cli/cliRouter.js
Fixes #19077
* Adds details about -v flag to cli auto-generated help.
n/a
n/a
* `jetpack --help` -- does it mention -v / --verbose?
* `jetpack build --help` -- does it mention -v / --verbose?
* `jetpack install --help` -- does it mention -v / --verbose?
=> CLI: Add v/verbose to help text

.github/actions/repo-gardening/src/index.js, .github/actions/repo-gardening/src/tasks/wpcom-commit-reminder/index.js, .github/actions/repo-gardening/src/tasks/wpcom-commit-reminder/readme.md
﻿As an a12n, once you merge a PR in Jetpack, it's nice to follow-up and also commit any matching WordPress.com diff that was created for you.
This commit adds a new task that will run every time a push to master happens, will look for the matching merged PR, and will add a reminder comment if that PR also included a previous comment from matticbot.
* Internal discussion: p1615302799197900-slack-CBG1CP4EN
* No
I'm not quite sure how to best test this, since this is only triggered on merges to `master`.
=> Actions: remind authors to commit their wpcom diffs with comment.

.github/actions/repo-gardening/src/get-labels.js, .github/actions/repo-gardening/src/tasks/add-milestone/index.js, .github/actions/repo-gardening/src/tasks/check-description/index.js
﻿Milestone assignment was no longer automatically happening when merging PRs without a milestone, since #18558.
I cleaned things up a bit and made the difference between owner (the object) and owner.login (the owner's login name, what we actually need when interacting with the API) a bit clearer.
* N/A
* No
* Do the existing Gardening tasks complete without failure?
* When we merge this PR, even though there is no milestone assigned to it, a milestone should get added by the action afterwards.
=> Actions: fix milestone assignment and clean up owner references

.github/actions/repo-gardening/src/index.js
﻿Follow-up from #19092.
- We cannot use `ifNotFork` to check for a fork on push event, since we do not have info about the fork at that point, we only know about the merge commit.
- We do not need to check for a fork, since Matticbot will not comment on PRs that are opened by external contributors in the first place; diffs cannot be created from forks.
* N/A
* No
* This aims to fix errors that happen on an action that run on merge to `master`, so... We can merge this PR and see the resulting action? :)
=> Actions: do not check for fork on push event

projects/packages/changelogger/changelog/fix-project-version-exit-code, projects/packages/changelogger/src/Application.php, tools/project-version.sh
Piping to the while doesn't work, as it results in the while being
executed in a subshell and so the main shell doesn't get EXIT=1. Use
process substitution instead.
Then apply a version bump to changelogger that should have been in
#19102 but was missed because this error made it not fail CI.
None.
No.
* Undo the change in 364f2c6, run `tools/project-version.sh -v -u 1.0.1-alpha packages/changelogger` or `tools/changelogger-validate-all.sh`, and see that the exit code is not 0.
=> tools: Fix exit code in project-version.sh

projects/plugins/jetpack/extensions/blocks/conversation/attributes.js, projects/plugins/jetpack/extensions/blocks/conversation/edit.js, projects/plugins/jetpack/extensions/blocks/conversation/editor.scss, projects/plugins/jetpack/extensions/blocks/conversation/utils.js
This PR implements a way to create a Conversation/Dialogue blocks composition by providing a transcript file.
Here, the Conversation block initially shows a placeholder that allows uploading a transcript video, or create a conversation from scratch.
The whole process can be split up into three parts.
* **UPLOADING**: The initial step. The user is able to upload the transcript file. Here, we try to validate the file by type and extension, check its size (100KB is the max size).
* **PARSING**: When the content format is detected early, this process applies the proper parser in order to data. It happens with the .srt files. It's a known format that makes the parsing process easier to do and less erratic.
When the file is simply a text file, the app tries to detect some patterns. We try to …
=> Conversation: Support uploading/parsing/composing transcript

docs/monorepo.md, docs/writing-a-good-changelog-entry.md
* Add changelogger info to `monorepo.md`
* Update `writing-a-good-changelog-entry.md` with changelogger info; removing info about the previously used `Needs Changelog` labeling/template.
* Internal: p1HpG7-bqa-p2
* No.
* Proofread updated documents.
=> Docs: Add changelogger info to monorepo.md

projects/plugins/jetpack/_inc/client/my-plan/my-plan-body.jsx, projects/plugins/jetpack/changelog/Enhancement-fixing-capitalization-issue
Changing the "Instant Search and Filtering" title on the my plans page from camel case to sentence case for consistency with all of the other cards.
Before:
After:
* No
* Go to Jetpack > My Plan
* Check the different card titles
#Hackweek
=> My plan body: Changing title to sentence case for consistency

projects/plugins/jetpack/_inc/client/at-a-glance/monitor.jsx, projects/plugins/jetpack/_inc/client/components/connect-user-bar/index.jsx, projects/plugins/jetpack/_inc/client/components/connect-user-bar/style.scss, projects/plugins/jetpack/_inc/client/components/connect-user-frame/index.jsx, projects/plugins/jetpack/_inc/client/discussion/subscriptions.jsx, projects/plugins/jetpack/_inc/client/searchable-modules/index.jsx, projects/plugins/jetpack/_inc/client/security/monitor.jsx, projects/plugins/jetpack/_inc/client/security/sso.jsx, projects/plugins/jetpack/_inc/client/sharing/likes.jsx, projects/plugins/jetpack/_inc/client/sharing/publicize.jsx, projects/plugins/jetpack/_inc/client/sharing/share-buttons.jsx, projects/plugins/jetpack/_inc/client/traffic/seo.jsx, projects/plugins/jetpack/_inc/client/writing/masterbar.jsx, projects/plugins/jetpack/_inc/client/writing/post-by-email.jsx, projects/plugins/jetpack/changelog/userless-editorial, projects/plugins/jetpack/class.jetpack-connection-banner.php, projects/plugins/jetpack/scss/jetpack-connect.scss
- updated copy for the userless connection components (see #18837)
- removed the connection iframe border in "userful" mode
p2JRYi-5fn-p2
No.
0. Go through the changed copy and check for typos 🙂 
1. Define the JETPACK_NO_USER_TEST_MODE, disconnect Jetpack and connect again in the userless mode.
2. Go to "Jetpack -> Settings" and use the "This feature is provided by the WordPress.com cloud..." connection bar to connect the user.
3. Complete the connection process, the greyed out modules should get available.
=> Userless Connection: editorial

projects/plugins/jetpack/changelog/19070-wpcomapi-update-prevent-duplicate-creation, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Differential Revision: D58079-code
This commit syncs r222267-wpcom (and r222314-wpcom).
Summary:
There's no duplicate post creation prevention in the WPCOM rest API.
Sending multiple identical requests will create a new post for each request.
Ahead of the [[ https://[private link] | Facebook DTP project ]], we'd like to make sure repeated attempts by FB users to export their posts to WP.com don't create duplicate posts.
This revision updates (only) the 1.2 version of this endpoint to prevent this, by using core's `post_exists()` function
* N/A
* No
This is covered by tests on WordPress.com. For more details, see D58079-code
Manual testing:
- sandbox [private link]
- use the developer console at https://[private link] to post to /sites/[YOURSITE]/posts/new
- Set the date, title, and …
=> rest-api: prevent duplicate post creation

projects/plugins/jetpack/changelog/fix-admin-menu-migrate-submenu-hooks, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/data/admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-jetpack-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/50950
Fixes https://github.com/Automattic/wp-calypso/issues/50945
Fixes https://github.com/Automattic/wp-calypso/issues/51018
Fixes https://github.com/Automattic/wp-calypso/issues/51024
Fixes https://github.com/Automattic/wp-calypso/issues/50939
Fixes https://github.com/Automattic/wp-calypso/issues/49915
Turns out that changing the menu slugs introduces a lot of side effects, mainly because the page hooks are still attached to the previous slugs:
- https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin.php#L1469
- https://core.trac.wordpress.org/browser/trunk/src/wp-admin/menu-header.php#L245
- https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin.php#L1331
To work around that, this PR explores …
=> Admin Menu: Do not alter menu slugs

projects/plugins/jetpack/changelog/fix-e2e-wp-env-failure, projects/plugins/jetpack/tests/e2e/.wp-env.json, projects/plugins/jetpack/tests/e2e/bin/env.sh, projects/plugins/jetpack/tests/e2e/bin/wp-setup.sh, projects/plugins/jetpack/tests/e2e/package.json, projects/plugins/jetpack/tests/e2e/yarn.lock
This is a temp solution for wp env database connection issue
* Use latest wp-env from trunk. Solution found here: 84-gh-Automattic/a8c-wp-env
* Temporary solution until https://github.com/WordPress/gutenberg/pull/29800 gets released to npm
n/a
n/a
```
yarn install
yarn wp-env destroy
yarn wp-env start
```
WP env should start successfully.
=> Temporary fix for wp-env database issue

projects/plugins/jetpack/changelog/fix-empty_blog_name, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49355
* Uses domain in Site Card when blogname is empty.
* Go to `/wp-admin/options-general.php`.
* Submit an empty `Site Title` .
* You should be seeing the Domain name twice.
* Please reinstate your `Site Title` and make sure it correctly appears.
Before | After
-------|------
=> Replace Blog Name when it is empty with domain name 

.github/actions/repo-gardening/src/tasks/check-description/index.js
Fixes #19127
When things are missing from a PR, we now mark it as missing in a comment on the PR. This PR adds inline recommendations in that comment, so that when something is missing, we also offer help so the PR author can easily fix what's missing.
I've also taken the opportunity to update the PR description length requirement to require more text (at least the length of the contents of the PR template).
* N/A
* No
* See comment below, and in this PR (where all things will be missing): #19150
=> Gardening: add inline recommendations to PR check comment

projects/packages/jitm/README.md, projects/packages/jitm/changelog/update-jitm_pre_connection_filter, projects/packages/jitm/src/class-pre-connection-jitm.php, projects/packages/jitm/tests/php/test_JITM.php, projects/packages/jitm/tests/php/test_pre_connection_jitm.php, projects/plugins/jetpack/changelog/update-jitm_pre_connection_filter, projects/plugins/jetpack/class-jetpack-pre-connection-jitms.php, projects/plugins/jetpack/class.jetpack.php, projects/plugins/jetpack/tests/php/general/test-class-jetpack-pre-connection-jitms.php
* The pre-connection JITMs should be shown only on sites that have Jetpack active. Move these JITMs from the JITM package to Jetpack.
* Add a filter, `jetpack_pre_connection_jitms`, which Jetpack will use to add its pre-connection JITMs. Other plugins can also use this filter to add pre-connection JITMs.
These changes help make the JITM package independent of Jetpack.
* n/a
* no
1. Install and activate this branch. Do not connect Jetpack.
2. Enable pre-connection settings using the `jetpack_pre_connection_prompt_helpers` filter:
`add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );`
3. In wp-admin, navigate to `Media`. You should see a JITM: `Do you want lightning-fast images?`.
4. In wp-admin, navigate to `Appearance -> Widgets`. You should see a JITM: `Looking for …
=> JITM: move pre-connection JITMs to Jetpack

projects/plugins/jetpack/changelog/fix-e2e-wp-env-bump, projects/plugins/jetpack/tests/e2e/.wp-env.json, projects/plugins/jetpack/tests/e2e/package.json, projects/plugins/jetpack/tests/e2e/yarn.lock
* Bumps wordpress/env version to 4.0.0. This should fix the env database connection issue.
n/a
n/a
```
yarn install
yarn wp-env destroy
yarn wp-env start
```
WP env should start successfully.
=> E2E tests: Bump wordpress/env to 4.0.0

projects/packages/sync/changelog/fusion-sync-yoavf-r222889-wpcom-1615978885, projects/packages/sync/src/class-functions.php, projects/plugins/jetpack/changelog/fusion-sync-yoavf-r222889-wpcom-1615978885, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Differential Revision: D58776-code
This commit syncs r222889-wpcom.
* If the `_dtp_fb` metadata is present, add a filter for allowed post metadata on create/save post API endpoint.
No
See D58776-code
=> rest-api: Handle FB DTP metadata

.github/files/build-all-projects.sh, .github/files/gh-autotagger/workflows/autotagger.yml, docs/monorepo.md
The optional auto-tagger workflow will add a tag in the mirror repo when
a CHANGELOG.md is pushed with a non-prerelease version.
This PR doesn't actually enable it anywhere.
Mentioned somewhere. Can't remember where.
No.
* Check that the build output doesn't have the new workflow file.
* Set `.extra.autotagger` to true and build. See that the new workflow file is copied into that mirror's tree.
* Copy the workflow into a testing repo and try it out. Or look [here](https://github.com/anomiex/testing/actions/workflows/autotagger.yml) where I did that.
=> mirrors: Add an auto-tagger

projects/packages/licensing/changelog/fix-licenses-not-attached-on-option-creation, projects/packages/licensing/src/class-licensing.php
* Fix stored licenses not being attached on option creation. Licensing was only hooking into update_option_jetpack_licenses where it should've hooked into add_option_jetpack_licenses as well.
No.
1. Checkout `master` and build Jetpack. The examples below are using WP CLI via docker.
3. `yarn docker:wp option delete jetpack_licenses`
4. `yarn docker:wp option update jetpack_licenses '["SOME_VALID_LICENSE_KEY"'] --format=json`
5. Refresh the My Plan tab in your browser - the product for the license in the previous step will be missing.
7. Checkout this PR.
8. Repeat steps 3 (CRUCIAL), 4 and 5 - the product should now show up under My Plan.
=> Licensing: Fix stored licenses not being attached on option creation

projects/plugins/jetpack/changelog/remove-double-init-call, projects/plugins/jetpack/load-jetpack.php
Already executed in line number 86.
Fixes #19166
Fixes #5684 
All is explained in the above issue.
* No
* Try using different parts of Jetpack depending on `init`.
* Try updating from the stable version of Jetpack to a new version with this patch, and ensure that the upgrade routine works well.
=> Execute Jetpack::init only once

tools/find-project-deps.php
Two errors:
* It was cutting off the last character of the slug.
* It was counting directories that aren't actually projects (i.e. no
composer.json) as dependencies if they had a package.json, which
confused other tooling.
Also did some other cleanup while I was looking at it.
p1616015585089400-slack-CBG1CP4EN
No.
* Try cherry picking this into https://github.com/Automattic/jetpack/pull/19134/commits/3293dd0857de15b5c9ca2b6eb6129dfbd04b6496, run it and see what happens.
* Same with the current version of #19134.
=> tools: Fix js-package handling in find-project-deps.php

tools/includes/plugin-functions.sh
Scripts that take a "plugin" currently accept the plugin directory name,
a full directory path, or a full path to the WP plugin file.
To avoid confusion with scripts that take a project slug, also accept
the "plugins/name" style slug.
https://github.com/Automattic/jetpack/pull/19183#pullrequestreview-615497553
No.
* Try `tools/plugin-version.sh plugins/jetpack`
=> tools: Accept slugs to plugin scripts

.github/files/check-composer-locks.sh, .github/files/check-excludelist-diff.js, .github/files/generate-ci-matrix.php, .github/files/require-change-file-for-touched-projects.php, tools/project-version.sh
GitHub's highlighting in the logs replaces the `%0A` with a newline, but
doesn't color the subsequent lines in red like it does the first to tie
them together. Add `---` before and after multiline messages to better
set them off for human readers looking at the logs.
p1616087631140300-slack-CBG1CP4EN
No.
* Make a PR introducing errors that trigger these messages, and then look at the logs.
=> actions: Bracket multiline messages for better visibility in GH's logs

projects/packages/sync/changelog/sync-memcache-delete-lock, projects/packages/sync/src/class-lock.php, projects/packages/sync/src/class-sender.php, projects/packages/sync/src/modules/class-full-sync-immediately.php
delete_option leaves options vulnerable to memcache inconsistencies (race conditions).  The [early return](https://core.trac.wordpress.org/browser/tags/5.7/src/wp-includes/option.php#L653) of delete_option will cause an out of date memcache value to remain persisted  if called when the option was successfully deleted from the database previously.  By switching to update_option( name, false ); we instead will trigger the db and memcache update if the memcache value is different than the db value due to update_options check for equality based on the get_option value which will return the memcache value if it exists.
* Update Sync locks to use update_option.
* NO
* Sync behavior is covered in unit (integration) tests.
* In addition you can verify the following scenarios
Sync Lock clears
* …
=> Update Sync lock and retry-after options to use update_option

projects/plugins/jetpack/changelog/update-gutenberg-menus, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/data/admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
This PR provides the previously WPCom Simple-only changes to FSE menu item positioning introduced in #18800 to Atomic sites.
Fixes Automattic/wp-calypso#50894
* Atomic and Jetpack sites now also reposition the FSE menu
* Gutenberg plugin menu removed on WPCom Simple and Jetpack
* Keep the Customizer removed when it's been removed by FSE
Unifying behaviour is the whole Nav Unification deal right?
No
For WPCom Simple and Atomic, you should see:
**Site Editor with no (beta) label, underneath Appearance**
* Apply D58831-code  to your sandbox
* Sandbox a site created through the [Horizon FSE flow](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor)
* Sandbox `public-api.wordpress.com`
* Visit your test site's `wp-admin`
* Verify that both wp-admin and Caplyso should show the …
=> FSE: FSE menu item platform parity

tools/docker/README.md
When using the new Docker RC for M1 Mac/Apple Silicon, you need to add a snippet to your compose-extras.yml in order to get MySQL to build. @jeherve shared this with me, and I'm sure others will run into it, so I thought it'd be good to add it to the docs.
No.
Read the docs changes.
=> Docker docs: add Mac M1/Apple Silicon Docker workaround

projects/packages/connection/changelog/update-userless-connection-reconnect, projects/packages/connection/src/class-manager.php, projects/packages/connection/tests/php/test-rest-endpoints.php, projects/packages/connection/tests/php/test_Manager_integration.php
When a Jetpack site is experiencing token related errors, the user is asked to reconnect Jetpack.
Upon reconnection we decide if a partial of full reconnect is needed.
In cases of a full reconnection or a user token partial reconnection we also ask the user to reconnect their WPCOM account.
Under the user-less context, upon fixing connection errors (aka reconnecting) we should not ask the user to connect their WPCOM account, as this is definitely not part of the solution.
* Connection : Introduce `is_userless` method in `Manager`
* Connection: Update `restore` method in `Manager` to take "userless" into account.
No
* Enable userless Jetpack mode (`define( 'JETPACK_NO_USER_TEST_MODE', true );`)
* Connect Jetpack only at a site level (skip user auth)
* Using the Jetpack Debug->Broken Token …
=> Connection: Handle reconnecting a userless connection

projects/plugins/jetpack/changelog/fix-sso_atomic_users, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51232
This PR aims to make the Calypso Users menu available at all cases so that Atomic administrators have a chance to add an SSO user.
- Turn on advanced wp-admin pages under /me/account
- Go to an atomic site's dashboard
- "Users" -> should redirect to Calypso Users management screen
- "Add new" -> should redirect to Calypso Users management screen
- "Advanced Users Management" -> should redirect to WP Admin
- Now, turn off advanced wp-admin pages under /me/account
- Try the menus again, the results should be identical
=> Always adds Calypso Users menu.

projects/packages/blocks/changelog/add-enable-package-autotagger-to-test, projects/packages/blocks/composer.json, projects/packages/changelogger/changelog/add-enable-package-autotagger-to-test, projects/packages/changelogger/composer.json, projects/plugins/beta/changelog/add-enable-package-autotagger-to-test, projects/plugins/beta/composer.lock, projects/plugins/debug-helper/changelog/add-enable-package-autotagger-to-test, projects/plugins/debug-helper/composer.lock, projects/plugins/jetpack/changelog/add-enable-package-autotagger-to-test, projects/plugins/jetpack/composer.lock
When we next do a release with tools/changelogger-release.sh and merge
the resulting PR, the new versions of these packages should be
automatically tagged in the mirror repos.
p1616427747259300-slack-CBG1CP4EN
No.
* Check the output of the Build workflow, the new action should be present for these projects (but not any others).
* Once this is merged, check that the mirror repos did not auto-tag (because this isn't a release).
* When we do do a release, check that the mirror repos get correctly tagged.
=> blocks, changelogger: Enable auto-tagger

.github/actions/repo-gardening/src/tasks/check-description/index.js
﻿When we recommend adding a changelog entry for a given project, let's use the full project path (e.g. projects/plugins/jetpack) instead of the partial one (plugins/jetpack), so one can copy the path and cd into it straight from their terminal.
* Internal reference: p1616432372272500-slack-jetpack-crew
* No
* Check the comment on this PR for an example: #19245
=> Gardening: use full project path for displayed recommendation

projects/plugins/jetpack/changelog/update-story-playback-improvements, projects/plugins/jetpack/extensions/blocks/story/player/components/header.js, projects/plugins/jetpack/extensions/blocks/story/player/components/media.js, projects/plugins/jetpack/extensions/blocks/story/player/lib/wait-media-ready.js, projects/plugins/jetpack/extensions/blocks/story/story.php
Resolves a few issues with Stories playback:
https://github.com/Automattic/story-block/issues/11
https://github.com/Automattic/story-block/issues/12
This should improve the issue mentioned above, where sometimes the loading animation would show indefinitely (I believe this may be due to a race condition issue when the video was already cached and load was completed before the listener to hide the loading indicator was registered, but I'm not sure). It should also be a load time optimization in general.
This also improves the preview on some mobile browsers/webviews (see https://github.com/wordpress-mobile/WordPress-Android/issues/13809), where videos are not predownloaded for bandwidth reasons - the poster image will still be downloaded in those situations.
No changes.
On a Jetpack site …
=> Story block: Playback improvements

projects/plugins/jetpack/changelog/try-force-atomic-posts-pages-to-wpadmin, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php
It was requested that for Atomic both Posts and Pages default to WPAdmin and ignore the setting that allows toggling between Calypso and WPAdmin.
Fixes https://github.com/Automattic/wp-calypso/issues/51283
See also hotfix in 648-gh-Automattic/wpcomsh
* Force both Posts and Pages menus to link to WPAdmin on Atomic sites.
Nope
* Activate this branch via JP Beta on Atomic site.
* Check that `Posts` and `Pages` menu items _always_ link to WPAdmin.
* Toggle the toggle under https://wordpress.com/me/account.
* Check both menu items _still_ continue to link to WPAdmin.
Once done testing please revert back to Jetpack Beta `master` branch and then test the hotfix 648-gh-Automattic/wpcomsh
=> Force Posts and Pages to WPAdmin for Atomic

.github/actions/repo-gardening/src/tasks/check-description/index.js
As its name implies, `Object.assign()` assigns to the object. Which
breaks when the same object is used again later in the method.
Better to just create a new object with spread syntax.
None
No.
* Did it comment correctly on this PR?
* Do something that makes it both remove "[Status] Needs Review" and add "[Status] Needs Author Reply". Did that work correctly?
=> repo-gardening: Remove broken use of Object.assign()

projects/packages/jitm/changelog/update-jitm-replace-connection-is-active, projects/packages/jitm/composer.json, projects/packages/jitm/src/class-jitm.php
Replace Connection's `is_active` check with `is_connected`.
With user-less in mind we will be slowly deprecating the `is_active` method in the `Manager` class.
**Changes proposed in this Pull Request:**
`is_active` was audited and replaced by `is_connected`, which indicates an established **site-level** connection.
**Jetpack product discussion**
1191179647901802-as-1200087466875449
Does this pull request change what data or activity we track or use?
No
**Testing instructions:**
Basically look at the code to validate the logic.
=> JITM: Replace connection is_active check

.github/renovate.json
Fixes #18465
Follow-up from #17842. Reviewers list should be an array.
* N/A
* No
* Renovate shouldn't reopen that issue when we merge this.
=> Renovate: reviewer list should be an array

projects/packages/licensing/changelog/update-licenses-replace-connection-is-active, projects/packages/licensing/src/class-licensing.php, projects/packages/licensing/tests/php/class-test-licensing.php
Replace Connection's `is_active` check with `has_connected_owner`.
With user-less in mind we will be slowly deprecating the is_active method in the Manager class.
Changes proposed in this Pull Request:
`is_active` was audited and replaced by `has_connected_owner`, which indicates an established user-level connection.
Jetpack product discussion
1191179647901802-as-1200087466875449
Does this pull request change what data or activity we track or use?
No
Testing instructions:
Basically look at the code to validate the logic.
=> Licensing: Replace connection is_active

projects/plugins/jetpack/changelog/fusion-sync-yoavf-r223277-wpcom-1616596994, projects/plugins/jetpack/sal/class.json-api-post-base.php
The documentation for the post metadata field specifies it is an array.
However, when there is no metadata, the return value will be
- `false` for wpcom sites
- `[ false ]` for Jetpack sites
This change makes sure we always return an array.
Differential Revision: D59107-code
This commit syncs r223277-wpcom.
* wpcom-api: make sure post metadata is always an array as documented.
NO
See D59107-code
=> wpcom-api: make sure post metadata is always an array 

projects/plugins/jetpack/changelog/fix-display-fallback-when-video-404s, projects/plugins/jetpack/extensions/blocks/videopress/edit.js
Fixes https://github.com/Automattic/wp-calypso/issues/51151
When a user deletes a video from their Media Library, any Video blocks that are linked to that file will break because the GUID remains saved in the block attributes. When the block attempts to fetch the video with that GUID, it will 404. In the editor, it gets stuck in a loading spinner and the user cannot access block controls in order to fix/remove the block.
This PR catches the error and displays the fallback in the editor, allowing the user to replace the video or delete the block if desired. It does not change the behavior on the frontend.
Test on a wpcom simple site with a premium plan.
1. Create a post and insert a Video block.
2. Upload a new video or use an existing video from your media library.
3. Publish the post.
4. …
=> Video Block: fix/display fallback when video 404s

.github/files/renovate-close-old-PRs.sh, .github/workflows/renovate-cleanup.yml
Renovate loses track of its own PRs when they're beyond the latest 1000
in the repo. See [renovate issue #​4803](https://git.io/JYt4a).
This adds a workflow that will check for such PRs and close them.
Renovate will re-create them later on, despite recreateClosed being
false, because of that same bug.
p1616624425493000-slack-CBG1CP4EN
No
* Ran it manually to produce https://github.com/Automattic/jetpack/pull/11978#issuecomment-807470473
* Otherwise, merge then see if it worked.
=> renovate: Close old PRs

projects/packages/connection/changelog/add-test_blog_token_health, projects/packages/connection/src/class-tokens.php, projects/plugins/jetpack/_inc/lib/debugger/class-jetpack-cxn-tests.php, projects/plugins/jetpack/changelog/add-test_blog_token_health
Adapts the local suite tests to work with user-less.
If the test is called in a context without a logged in user and without a connection owner, it will skip the check for the user token health.
If there is a connected logged in user, or if the site has a connected owner, it will also check for the user token health
* Adapt local test suite for user-less connections
N/A
* Connect your site only at a site level (if not using the docker env, you need to activate user-less testing mode)
* Visit the Jetpack Debugger no WP Admin
* Visit the Jetpack Debugger on jptools.wordpress.com . 
* Make sure tests pass
* Connect the user and run the tests again
Invalidate the Blog token and see that the test fails
=> add Blog token health check

.github/files/renovate-close-old-PRs.sh, .github/workflows/renovate-cleanup.yml
We need to pass the token in explicitly, GH doesn't do that
automatically.
Also, may as well pass matticbot's token rather than GH Action's so the
comment and close show up as being from our own bot.
None
No
* Merge, then check tomorrow whether it worked.
=> renovate: Fix "close old PRs" script

projects/packages/connection/changelog/update-is_active_deprecation, projects/packages/connection/src/class-manager.php, projects/packages/connection/tests/php/test-rest-endpoints.php, projects/plugins/jetpack/changelog/update-is_active_deprecation, projects/plugins/jetpack/class-jetpack-connection-status.php, projects/plugins/jetpack/class.jetpack.php, projects/plugins/jetpack/load-jetpack.php
This is a follow-up PR after the changes in Licensing package: https://github.com/Automattic/jetpack/pull/19283, JITM package: https://github.com/Automattic/jetpack/pull/19280 Jetpack: https://github.com/Automattic/jetpack/pull/19276  and Connection package: https://github.com/Automattic/jetpack/pull/19259
The `is_active` method is deprecated. The default response of the Connection Status API endpoint will still return the value of the deprecated method, for now, but is going to be filtered by the Jetpack plugin. This will allow us to enable the Jetpack UI for user-less connection when we want.
Since these methods are widely used, we decided not to throw any deprecation notices for now, and only inform it in the doc blocks. 
* Adds a deprecation note to the doc block of Jetpack::is_active …
=> Deprecate is_active and filter connection status

projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php, projects/plugins/jetpack/changelog/fix-jetpack-recommendations-on-userless
This PR fixes the Jetpack Recommendations feature for User-less Jetpack Connections and secondary users without a connected WPCOM account.
- Checks if the current user is connected and hides the upsell card if yes.
1191179647901802-as-1199661507903018/f
**Before**:
- Connect Jetpack in User-less mode, aka by skipping user authentication after setting up Jetpack. (In JN, check `JETPACK_NO_USER_TEST_MODE` in Settings->Jetpack Constants )
- Run the Recommendations wizard
- Notice in the final step `admin.php?page=jetpack#/recommendations/summary` will be blank and the following error in your browser console: `react-dom.min.js:125 TypeError: Cannot read property 'symbol' of null`
**After**:
- Notice in the final step `admin.php?page=jetpack#/recommendations/summary` everything works as …
=> Jetpack Recommendations: Fix fetching upsell on userless

projects/plugins/jetpack/_inc/client/components/connect-user-bar/index.jsx, projects/plugins/jetpack/_inc/client/discussion/subscriptions.jsx, projects/plugins/jetpack/_inc/client/security/monitor.jsx, projects/plugins/jetpack/_inc/client/security/protect.jsx, projects/plugins/jetpack/_inc/client/security/sso.jsx, projects/plugins/jetpack/_inc/client/sharing/publicize.jsx, projects/plugins/jetpack/_inc/client/sharing/share-buttons.jsx, projects/plugins/jetpack/_inc/client/traffic/seo.jsx, projects/plugins/jetpack/changelog/fix-userless-connect-bar-offline-mode, projects/plugins/jetpack/modules/seo-tools.php
﻿
This PR is a follow-up of #18837 and #19300.
It introduces the following changes:
**The connect bar main message should be translatable.**
**The SEO module now works in userless mode.**
**The Protect card should still be a bit readable when in offline mode.**
In bc422ac3f771e80a36ef47ef73d7681878411979, we wrapped the foldable card into a SettingsGroup component that already handles the display of the group when in offline mode. We consequently do not need to handle it again in the foldable card.
**Before**
**After**
**Let's not show the connect bar when in offline mode, since folks will not be able to connect their site to WordPress.com anyway.
**Before**
**After**
**Note**: a potential alternative would be to add the Offline check within the connect bar component itself. …
=> Connection: do not display Connect Bar when in Offline mode, and make SEO userless

projects/plugins/jetpack/changelog/fix-userless-get-available-modules, projects/plugins/jetpack/class.jetpack-admin.php
This PR fixes the list of available modules taking into account their user connection constraints.
* Jetpack Admin: Updates the `get_available_modules` method to return `false` if the module requires a user connection and the site has no connected owner.
* Jetpack Admin: Updates the `get_available_modules` method to return `false` if the module requires a user connection and the site is in offline mode.
1191179647901802-as-1200123916753249/f
No
**Before**
- Start with a brand new JN site running master.
- In the Jetpack constants page, enable Userless mode.
- Connect the site ONLY at a site level (skip user auth)
- Go to `wp-admin/admin.php?page=jetpack_modules`
- The modules below (requiring user connection) will be displayed as available while they shouldn't:
1. Monitor
2. Notifications …
=> Jetpack Admin: Fix fetching available modules on user-less mode

projects/plugins/jetpack/_inc/client/at-a-glance/monitor.jsx, projects/plugins/jetpack/_inc/client/at-a-glance/protect.jsx, projects/plugins/jetpack/_inc/client/components/dash-item/README.md, projects/plugins/jetpack/_inc/client/components/dash-item/index.jsx, projects/plugins/jetpack/changelog/fix-userless-monitor-protect
- hide the "toggle" buttons for Monitor and Protect cards in userless mode
- disable Monitor card in Offline mode when the module is enabled
1191179647901802-as-1200123916753257
No.
1. Connect Jetpack in Userless Mode.
2. Go to Jetpack Dashboard and confirm that cards "Protect" and "Downtime monitoring" are asking you to connect the user.
3. Confirm that the enable/disable toggles do not show up on these cards.
4. Connect the user, confirm that the toggles do show up, try switching then on/off.
5. Activate both "Downtime monitoring" and "Protect".
6. Switch into the Offline mode (`define( 'JETPACK_DEV_DEBUG', true );`) and reload the Jetpack Dashboard.
7. Confirm that both of those cards say "Unavailable in Offline Mode."
=> Connection: fully disable Monitor and Protect on userless Dashboard

projects/plugins/jetpack/_inc/client/at-a-glance/protect.jsx, projects/plugins/jetpack/changelog/fix-userless-dashboard-copy
* Fixing typo in the Dashboard "Protect" card in Userless mode.
No.
1. Connect your site in Userless mode.
2. Go to Jetpack Dashboard and find the "Protect" card.
3. Confirm that it displays "Connect your WordPress.com **account** to keep..." instead of "Connect your WordPress.com to keep..."
=> Connection: fixing typo in the userless Protect card

projects/plugins/jetpack/changelog/fix-admin-menu-rtl-styles, projects/plugins/jetpack/modules/masterbar/admin-color-schemes/class-admin-color-schemes.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php, projects/plugins/jetpack/tools/builder/admin-css.js
Fixes https://github.com/Automattic/wp-calypso/issues/49779
- Add the admin menu styles to the build process that generates the RTL CSS files.
- Load the appropriate RTL admin menu styles when the language is a RTL language.
N/A.
No.
Try to reproduce first the issue:
* Go to https://wordpress.com/me/account.
* Change your language to a RTL language like Arabic or Hebrew. Save the settings.
* Toggle the "Show advanced pages" setting or change the color scheme and save. (This is to flush the cache on your Atomic sites).
* On an Atomic site, load `wp-admin/options-general.php` and change the site language to the same language you've set for your account.
* Open the responsiveness dev tools in your browser and switch to a mobile viewport.
* Note how the content is misplaced to the right:
Now …
=> Admin Menu: Handle RTL styles

projects/plugins/jetpack/_inc/client/state/recommendations/reducer.js, projects/plugins/jetpack/changelog/fix-recommendations-hide-monitor-on-userless
Jetpack Assistant (Recommendations) allows users to enable the Monitoring setting, however on user-less mode (no connected users) this setting is disabled and we only allow users to enable it after connecting their WPCOM account.
This PR fixes the above by hiding the Monitoring setup step on User-less mode.
The following fixes to the recommendations' state are introduced:
- `isStepEligibleToShow`: Adds an extra check whether the site has a connected owned in order to hide it if not.
- `isFeatureEligibleToShowInSummary`: Adds an extra check whether the site has a connected owned in order to hide it if not.
p9dueE-2EA-p2
No
**Before**
* Set up a new JN site running the master branch.
* Enable user-less mode ( `Settings->Jetpack Constants` )
* Setup Jetpack without connecting your WPCOM …
=> Recommendations: Hide Monitoring setting on User-less mode

.github/files/pr-update-to.sh, .github/workflows/pr-is-up-to-date.yml, projects/github-actions/pr-is-up-to-date/.gitattributes, projects/github-actions/pr-is-up-to-date/.gitignore, projects/github-actions/pr-is-up-to-date/CHANGELOG.md, projects/github-actions/pr-is-up-to-date/README.md, projects/github-actions/pr-is-up-to-date/action.yml, projects/github-actions/pr-is-up-to-date/changelog/add-pr-up-to-date-check, projects/github-actions/pr-is-up-to-date/composer.json, projects/github-actions/pr-is-up-to-date/license.txt, projects/github-actions/pr-is-up-to-date/run.sh
GitHub's built-in "Require branches to be up to date before merging"
seems a bit too strict, as every time someone merges anything it'll
require a master merge and therefore a re-run of all the CI checks.
On the other hand, it would be advantageous to have a check that
requires branches be up to date to the most recent time we did a release
to avoid the need for PRs like #19266.
So what we do here is define a tag indicating the master commit that PRs
need to be up to date with respect to. A push to master runs a job that
might update this tag, and any push to the tag will check all open PRs
and set a status check to "failed" for any that aren't up to date.
I'm not at all attached to the tag name proposed in this PR. Feel free to suggest
something better.
None
No
* I suppose you might copy …
=> Add a "PR is up-to-date" check

tools/cli/helpers/tasks/installProjectTask.js
Yarn's install versus upgrade is weird:
- If there's no lock file, upgrade fails.
- If there is a lock file but it's outdated with respect to
package.json, upgrade fails while install updates it.
- If there is a lock file that is up to date, install uses it while
upgrade updates it.
The best thing for the CLI to do seems to be to just use `yarn install`
always, deleting any non-checked-in lockfile first to avoid the second
case.
Pretty sure that's what was going on in p1617037783160300-slack-CBG1CP4EN
No.
* First, `git checkout 19abfd97^` then do `yarn install --ignore-engines` in `projects/packages/lazy-images/` to get an outdated yarn.lock created there. Then check out this and do `jetpack install packages/lazy-images`.
=> cli: Avoid yarn upgrade, always do yarn install

projects/plugins/jetpack/changelog/update-twitter-text-php-213, projects/plugins/jetpack/composer.json, projects/plugins/jetpack/composer.lock
The lib was updated to update a PHP 8 fix for a part of the lib we do not use in Jetpack.
I do not think it hurts to update in any case.
Related PR: https://github.com/nojimage/twitter-text-php/pull/39
* N/A
* No
* Not much to test here. You could try to use Publicize, with a linked Twitter account, set your Publicize options to "Twitter Thread" in the block editor, and see if your post still gets split into multiple tweets.
=> Publicize: update Twitter text processing library

projects/plugins/jetpack/changelog/update-videopress-221526-223544, projects/plugins/jetpack/modules/videopress/class.videopress-gutenberg.php, tools/phpcs-excludelist.json
This PR brings the file in sync with WordPress.com: it includes r221526-wpcom and r223544-wpcom.
I've also taken the opportunity to fix phpcs errors.
Internal references: 
- D57013-code
- D59423-code
* No
* Not much to test here, the changes should not impact Jetpack customers.
* You can try, on a site with a paid plan and the Video option added under Jetpack > Settings > Performance, to use the Video block in a new post.
* Make sure you can still upload videos and see the modified video block that allows you to upload and view Jetpack videos.
=> VideoPress: bring in sync with WordPress.com

projects/plugins/jetpack/changelog/update-changelog-link, projects/plugins/jetpack/readme.txt
We've now switched to a markdown file, so we can display the file with its Mardkdown preview instead of linking to a non-existing file.
I've opted to link to the Changelog anchor, so folks do not get to see the GitHub UI as much.
* N/A
* No
* Check if the link works.
=> Readme: update link to changelog

.github/workflows/gardening.yml, projects/github-actions/repo-gardening/README.md, projects/github-actions/repo-gardening/action.yml, projects/github-actions/repo-gardening/changelog/add-gardening-editorial-task, projects/github-actions/repo-gardening/changelog/expand-gardening-clean-labels, projects/github-actions/repo-gardening/changelog/update-gardening-required-parameters, projects/github-actions/repo-gardening/src/index.js, projects/github-actions/repo-gardening/src/tasks/clean-labels/index.js, projects/github-actions/repo-gardening/src/tasks/notify-editorial/index.js, projects/github-actions/repo-gardening/src/tasks/notify-editorial/readme.md
This PR adds in a few changes:
- Add a new Editorial task
Just like the Needs Design task, we'll listen for labels and notify the
Editorial team accordingly.
This is a feature that's already implemented in the Calypso repo. Let's standardize it.
- Expand list of labels to clean up after a PR has been merged
It was missing the design and editorial review labels.
- Mark some parameters as optional
Since they're not used in all tasks, they are only required when you use one of the tasks that relies on them. In this case, and if you miss the parameter, the action will fail.
* N/A
* No
* See that the comment below from the action still works.
* See that the labels added to this PR will be removed when we merge it.
* Check this message for an example of the task in use: …
=> Gardening Action: add Notify Editorial task

.github/files/gh-autotagger/workflows/autotagger.yml, docs/monorepo.md, projects/github-actions/pr-is-up-to-date/changelog/update-autotagger-for-actions, projects/github-actions/pr-is-up-to-date/composer.json, projects/github-actions/push-to-mirrors/changelog/update-autotagger-for-actions, projects/github-actions/push-to-mirrors/composer.json, projects/github-actions/repo-gardening/changelog/update-autotagger-for-actions, projects/github-actions/repo-gardening/composer.json, projects/github-actions/required-review/changelog/update-autotagger-for-actions, projects/github-actions/required-review/composer.json
And make the autotagger able to maintain the major version tag that's
described at https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management
None
No
* Check the Build step to see that the autotagger workflow is being added to the actions.
* Merge, then verify that when this is pushed to the mirrors that no tags are created (as this is not a release).
* Release an action (plus changelogger). See that the action gets both its "vX.Y.Z" and "vX" tags created/updated, while changelogger only gets "v1.1.2" (no "v1" tag).
=> github-actions: Enable autotagger for all actions repos

projects/plugins/jetpack/changelog/fusion-sync-yoavf-r223672-wpcom-1617271820, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Syncs r223672-wpcom 
Minor change to post format for posts created through the wpcom-api under certain conditions.
No
Not really needed, but see D59622-code.
=> wpcom-api: set post format to aside for dtp

projects/plugins/jetpack/CHANGELOG.md, projects/plugins/jetpack/changelog/update-changelog, projects/plugins/jetpack/readme.txt
This faeture isn't ready for launch just yet, so let's not mention it in the changelog to avoid confusion.
﻿Related:
- #19378
- #19279
- #19233
* N/A
* No
* Does everything look okay?
=> Changelog: remove entries for feature that's not ready for launch

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php, projects/plugins/jetpack/changelog/remove-jsonp-check
We don't use JSONP so no need to care about if it is enabled on a site or not.
* See above.
p3btAN-1o6-p2
No
* Add `add_filter( 'rest_jsonp_enabled', '__return_false' );` to a test site.
* See the wp-admin Jetpack dashboard not work.
* Apply this patch.
* See it work.
=> Admin Page: Remove check for JSONP

projects/plugins/jetpack/changelog/fix-admin-menu-check-position, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-base-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51510
When manipulating the global `$menu` for the unified menu, our logic was not checking whether certain menu positions were already used by other menu items, causing them to be replaced (and thus to be missing in the unified menu).
On this PR we're ensuring that the menu positions are not already populated, and if so, we automatically place the new menu items in a different position.
N/A.
No.
* Spin up a local Jetpack site running the `master` branch.
* Add the `wpcomsh` plugin to your local Jetpack site:
- `cd tools/docker/mu-plugins/`
- `git clone --single-branch --branch master git@github.com:Automattic/wpcomsh.git`
- `cd wpcomsh`
- `git submodule update --init --recursive`
- `composer install`
- `cd ..`
- `ln -s …
=> Admin Menu: Check position before setting menu item

tools/cli/helpers/projectHelpers.js, tools/cli/helpers/promptForProject.js
Ensures the type list is in alphabetical order.
* Updates the projectTypes array to alphabetical.
* Adds a `.sort()` to the promptForType function. Only adding it there since usually we don't care and avoid the time to sort.
n/a
No
* Run `jetpack install` before and after this PR. See `js-packages` out of order before, and not after.
=> CLI: Alpha sort project types during type prompt

projects/plugins/jetpack/changelog/fusion-sync-yoavf-D59714-code-1617527, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Syncs D59714-code / r223768-wpcom
Minor change to allowed metadata keys for DTP posts.
No
See D59714 for integration tests.
=> wpcom-api: update DTP allowed metadata 

.github/workflows/e2e-tests.yml, projects/plugins/jetpack/changelog/e2e-ci-build-jetpack-using-cli
Use Jetpack CLI to build Jetpack in E2E tests Github actions workflow
n/a
no
* CI happy
=> E2E tests: Build Jetpack plugin using Jetpack CLI

projects/plugins/jetpack/_inc/client/traffic/seo.jsx, projects/plugins/jetpack/_inc/client/traffic/style.scss, projects/plugins/jetpack/changelog/update-seo-tools-save-buttons
In WP Admin the custom SEO card can get long vertically when the
different sections get expanded. Adding additional save buttons to the
other two sections will make it so the user doesn't have to scroll far
back to the top of the SEO card to save.
Fixes: #19403
Internal: p8oabR-DS-p2#comment-5199
* No
* With changes pulled down, in WP Admin head to `/wp-admin/admin.php?page=jetpack#/traffic`
* Make sure the additional save buttons under the custom title structures and custom meta description work.
=> SEO: add additional save buttons to card section

projects/plugins/jetpack/changelog/update-show-links-manager-with-invisible-links, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51745
When we are retrieving links to see if the user has added any themselves to determine whether the Links Manager is in use (So we can hide it if it isn't). We are only retrieving visible links so if the user has added lots of invisible links we are incorrectly hiding the Links menu item.
* Return both invisible and visible links.
* Limit the query to the latest item only rather than 10, as we are only checking that.
**Simple**
* Apply this patch
* Remove all existing links from `/wp-admin/link-manager.php` and add a new link
* Link menu item should be visible.
* Edit your recently added link and make it private (Checkbox above the "Update Link" button).
* Link menu item should still be visible.
* Delete your recently added link.
* …
=> Retrieve invisible links when checking bookmarks

projects/github-actions/repo-gardening/changelog/update-gardening-check-progress-label, projects/github-actions/repo-gardening/package.json, projects/github-actions/repo-gardening/src/tasks/check-description/index.js
If you are still working on your PR, you may make more changes that will appease the action that checks your PR description. It's consequently not useful to add the Needs Author Reply label if you're still not done with your work.
No
* See p1617721097468900-slack-CBG1CP4EN
* See the labels added by the action under this PR. I will purposefully leave the "Privacy" information out of my PR description, so the action will detect that something is failing. But I'll also add the "In Progress" label. It should not add a "Needs Author Reply" label in response.
* I'll then edit things and mark the PR as ready for review.
=> Gardening Action: do not add the "Needs Author Reply" label if a PR is actively being worked on

projects/plugins/jetpack/changelog/fusion-sync-yoavf-D59840-code-1617790596, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Syncs D59840-code / r223880-wpcom
Improvements to post depublication in the API endpoint that will also work for posts with gallery shortcodes
No
See D59840 for integration tests.
The payload from that test can be used to test manually as well.
=> wpcom-api: improve post deduplication

projects/packages/connection/changelog/fix-rest-authentication-infinite-loop, projects/packages/connection/src/class-rest-authentication.php
Fixes a very specific situation where the `determine_current_user` filter added by the connection package can produce an infinite loop. See p9o2xV-1kz-p2#comment-4415
* Avoid determine_current_user filter to enter an infinite loop
p9o2xV-1kz-p2#comment-4415
No
* Set up an ephemeral site with wpcomsh/Jetpack and jetpack-beta
* Break the Jetpack user token (see p9o2xV-1kz-p2#comment-4415 or use the [Debug helper plugin](https://github.com/Automattic/jetpack/tree/master/projects/plugins/debug-helper))
* Use the developer console to request WP REST API | wpcom/v2 | GET | /sites/$your-site-id/admin-menu.
* `tail -f /tmp/php-errors` on the ephemeral site should output an OOM error. The rest API response code should be 500
* Using jetpack beta, switch to this branch
* Make the …
=> Avoid determine_current_user filter to enter an infinite loop

.github/files/renovate-helper.sh, projects/github-actions/push-to-mirrors/changelog/fix-gh-actions-git-auth, projects/github-actions/push-to-mirrors/push-to-mirrors.sh
Apparently GitHub sets up a generic auth token by default, and what we
were doing wasn't actually valid so it was falling back to that. This
should be the correct way to set it up.
This mostly doesn't matter, since either token is allowing access in
our current use cases. But it does prevent cancel-dups.yml from being
triggered from renovate-helper.sh and might break push-to-mirrors if
someone were to try using it to push to a private repo.
None
No
* Merge this. Then
* Make sure the push-to-mirrors job still runs successfully.
* Trigger renovate to rebase a PR that touches a project, and see if matticbot's push to add change files triggers jobs from cancel-dups.yml.
=> actions: Correctly supply git auth token

projects/plugins/jetpack/changelog/fix-cover-block-paid-block-media-placeholder-flex-child, projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/editor.scss
Related to #19488
* Add a CSS rule to "remove" the `paid-block-media-placeholder` element from the flexbox layout in the cover block, when the cover block has a background set
Initial report: p1617898513140100-slack-CBTN58FTJ
No
1. Apply D59965-code to your sandbox
2. Open the block editor on a site that is added to your sandbox
3. Add a cover block
4. Pick a background color or select a background image/video from the gallery
5. Add a paragraph into the cover block and play with the cover block settings to change the position of its content
6. With the cover block selected, drag a new image over the block
**Before**
https://user-images.githubusercontent.com/1083581/114181127-6452bd00-9941-11eb-8797-3e544ffadc31.mp4
**After**
https://user-images.githubusercontent.com/1083581/114181138-67e6 …
=> Cover block: fix paid-block-media-placeholder interference with flex positioning

projects/plugins/jetpack/3rd-party/class.jetpack-amp-support.php, projects/plugins/jetpack/changelog/fix-amp-legacy-reader-social-logos-css-import
Originally reported at https://github.com/ampproject/amp-wp/issues/5693. Users of the AMP plugin were getting access logs saying things like:
```
2021/04/12 06:30:26 [error] 9853#9853: *348118 open() "/var/www/sample/amp/social-logos.eot" failed (2: No such file or directory), client: 221.103.224.207, server: s01, request: "GET /sample/amp/social-logos.eot?5d3b4da4f6c2460dd842dbf9e0992ea6 HTTP/2.0", host: "example.org", referrer: "https://example.org/sample/amp/"
```
This issue wouldn't show up for modern browsers which support `data:` URLs, but for browsers that only support EOT or TTF font formats, the issue is that the CSS file uses a relative path for these font files:
https://github.com/Automattic/jetpack/blob/99ea6be4a3d54af93483c4373f6080192c9f05d1/projects/plugins/jetpack/_inc/soci …
=> Sharing: avoid broken sharing icons when using IE11 and legacy AMP theme

.github/workflows/e2e-tests.yml
Publish E2E tests results to Testspace: https://automattic.testspace.com/projects/66340
p9dueE-2ID-p2
no
* After E2E tests complete in CI the results should be published in Testspace
=> E2E tests: Publish test results to Testspace

projects/packages/sync/changelog/add-woocommerce-currency-to-sync, projects/packages/sync/src/class-defaults.php, projects/plugins/jetpack/changelog/add-woocommerce-currency-to-sync, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
The blog option `woocommerce_currency` is required in the Jetpack cache blog. We use it during Elasticsearch indexing to select the currency correctly for the Jetpack Search API. 
Related: https://github.com/Automattic/jetpack/issues/19500.
No.
Make sure the sync options tests pass.
=> Search: add woocommerce_currency to sync

projects/packages/sync/changelog/add-woocommerce-currency-to-sync, projects/packages/sync/src/class-defaults.php, projects/plugins/jetpack/changelog/add-woocommerce-currency-to-sync, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
Reverts Automattic/jetpack#19501.
@westi advised in https://github.com/Automattic/jetpack/pull/19501/#issuecomment-818401640 that the `woocommerce_currency` option is already synced. 
It goes into the "no_autoload" options table rather than the main options table, and therefore needs to be retrieved in a slightly different way.
We no longer need to add `woocommerce_currency` to the main sync allow list.
No.
Make sure the sync options tests pass.
=> Revert "Search: add woocommerce_currency to sync"

projects/plugins/jetpack/changelog/fix-mailchimp-block-secondary-user, projects/plugins/jetpack/extensions/blocks/instagram-gallery/edit.js, projects/plugins/jetpack/extensions/blocks/instagram-gallery/use-connect-instagram.js, projects/plugins/jetpack/extensions/blocks/mailchimp/edit.js, projects/plugins/jetpack/extensions/blocks/mailchimp/test/edit.js
This PR fixes the Mailchimp block UX for non-connected users, aka users that have not connected their WPCOM account.
* Redirects the user to connect their WPCOM account when setting up the Mailchimp block
* Updates the Mailchimp block's UI to represent the above
* (Bonus) Fixes an error in the Instagram Gallery block (500 status code) when trying to fetch the instagram connections for a user that has not connected their WPCOM account.
* (Bonus) Fixes the UI in the Instagram Gallery block account connection button
1191179647901802-as-1200141581897648/f
No
**Before**
* Add a secondary user but don't connect them to WPCOM
* Make sure you are logged in to WPCOM
* As the above user try to add the Mailchimp block in a post
* When clicking on the "Setup Mailchimp form" button …
=> Mailchimp Block: Fix UX for non-connected users.

projects/packages/connection/changelog/fix-nonce-cleanup-zero, projects/packages/connection/src/class-nonce-handler.php, projects/packages/connection/tests/php/test-class-nonce-handler.php
If the options table has `AUTO_INCREMENT` broken and all option ID's are `0`, the nonce cleanup component will remove all options.
This PR adds additional checks to prevent this from happening.
* Add safeguard against accidental option removal
p1617989003132300-slack-CBG1CP4EN
p1618002840155900-slack-CBG1CP4EN
3892136-zen
3901396-zen
No.
1. Setup a new JN site with Jetpack Beta and Jetpack Debug plugin. Install and active the "WP Crontrol" plugin.
2. Activate "Mocker" in the Jetpack Debug and create a bunch of nonces.
3. Go to the database and see how many options you have now: `select count(*) from wp_options;`
4. Go to "Tools -> Cron Events", find event `jetpack_clean_nonces` and run it.
5. Run the count query again and make sure that the nonces got removed: `select count(*) from …
=> Connection: avoid accidental options removal in nonce cleanup

projects/plugins/jetpack/changelog/update-inline-css-site-icon, projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51893
* Add inline styles to dashboard header for site icon when nav unification is enabled
* Unable to use `wp_add_inline_style` because non-core handles get removed by third-party plugins (Gravity forms)
* Go to https://github.com/Automattic/wp-calypso/issues/51893 and follow the steps to replicate the issue
* For Atomic: Install Jetpack Beta and activate this branch. Attempt to replicate again
* For Simple: Apply patch `D60088` to your Sandbox and ensure you've sandboxed your site. Attempt to replicate again
=> Define site icon CSS height and width inline

projects/plugins/jetpack/changelog/fix-refactor-submenu-replace, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-jetpack-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51459
Fixes https://github.com/Automattic/wp-calypso/issues/51381
Instead of removing submenu items in order to not display them in the navigation, we can add ~~the `hide-if-no-js` and~~ `hide-if-js` CSS classes on the items we want to exclude from the navigation. 
- In wp-admin that would mean that html elements will still be present in the nav however, they'll not be displayed.
- On Calypso, since the submenu items are filtered on the back-end side, there shouldn't be any behaviour changes.
This was needed in order to keep compatibility with third-party plugins that depend on core submenu items to register hidden pages; one example of this is All in one SEO plugin, where in order to register a hidden page, a submenu item is added and …
=> Nav unification - hide submenu items instead of removing them

projects/plugins/jetpack/changelog/Sync sidebar collapsed state with wpcom, projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/46645
The way that WP Admin works makes it difficult to retrieve the **updated** sidebar state.
**How it currently works?**
1. User visits `/wp-admin`
2. User clicks "Collapse Menu"
3. A cookie is added / updated `wp-settings-USERID`
4. User refreshes the page, `wp_user_settings()` runs and saves the cookie values to DB
In order to update the value in real time, I added an `eventListener` to the `Collapse menu` button. The first idea was to make a direct request to `https://public-api.wordpress.com/rest/v1.1/me/preferences` and update the `sidebarCollapsed` key of `calypso_preferences`. This wasn't fruitful, especially from Atomic sites due to authorization issues. In this pull request I am doing a `admin-ajax.php` request to the …
=> Saves sidebar expanded state from WP Admin to WPCOM calypso_preferences in real-time.

.github/workflows/e2e-tests.yml, projects/plugins/jetpack/changelog/fix-testspace-publish-if-failure
If the previous steps in actions failed the Testspace setup step was skipped leading to test failures not being published. This PR fixes that.
n/a
no
* CI happy
* Test results published to Testspace (even on failure - see [this run](https://github.com/Automattic/jetpack/pull/19534/checks?check_run_id=2343954746) )
=> Publish to Testspace even if previous steps failed

projects/plugins/jetpack/changelog/fix-photon-size-comparison, projects/plugins/jetpack/class.photon.php
WordPress is not particularly type-safe. In 3908038-zen I ran into a
situation where a site had the width and height metadata in 'sizes'
stored as strings rather than integers. WP was passing those strings
through in the srcset data, and since #16588 made a bunch of comparisons
strict Photon wasn't matching them anymore.
So add some casts to fix that.
None
No
* Have an image attachment on a post that has the `width` and `height` values in `sizes` as strings rather than integers.
* I don't know how you might do this normally, I just did an UPDATE on the row in wp_postmeta to reproduce it.
* Activate Photon.
* Look at the `srcset` attribute on the `<img>` tag. The Photonized URLs should be like `resize=300%2C200`, not `w=300`.
=> Photon: Cast dimensions to int when comparing

.github/workflows/gardening.yml
﻿
Follow-up from #19382.
We need to allow the action to run from forks for pull_request_target events, so we can add labels to PRs created by external contributors.
* N/A
* No
* See how the action was skipped in #19553: https://github.com/Automattic/jetpack/actions/runs/754757429
* For my next test PR (once this is merged), it should run.
=> Gardening: also run from forks for pull_request_target event

projects/plugins/jetpack/changelog/remove-sharing-submenu, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49689
This diff updates the Calypso wpcom Settings submenu to not include "Sharing" as an option, since this links to a page which is actually under the Tools menu (Tools->Marketing->Sharing Buttons).
(This fix was originally submitted as a wpcom diff at D59878-code, and it doesn't seem to relate directly to Jetpack behavior as standalone Jetpack sites don't seem to have this menu item anyway, but since the file exists as a Jetpack file as well, it seems like this is something that should be processed by Fusion. Please let me know if this is not the case and I can return to the original diff!)
N/A
No
* Check out wpcom Fusion-generated diff to your sandbox and make sure you have the API sandboxed.
* Open Calypso admin for a simple site. …
=> Remove Sharing submenu option from settings menu

projects/plugins/jetpack/changelog/update-carousel-improvement-batch-1, projects/plugins/jetpack/modules/carousel/jetpack-carousel.css, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js, projects/plugins/jetpack/modules/carousel/jetpack-carousel.php, projects/plugins/jetpack/modules/carousel/rtl/jetpack-carousel-rtl.css, tools/eslint-excludelist.json
This patch is the first of a series of changes that aim to improve the Carousel and ultimately remove its `jQuery` dependency, while keeping it IE11-compatible.
I'm trying to keep the changes relatively small and self-contained so that they can be incrementally tested (and debugged, if needed), instead of dropping a gigantic change that rewrites the world.
This PR syncs Jetpack to D56414-code, and applies some extra lint fixes, since the rules appear to be different. The change was started on wpcom instead of Jetpack due to legacy reasons. The next batch of improvements works on making that unnecessary.
This PR is a manual sync, since the automated tool appears to fail due to the mismatch in directory structure for the RTL CSS.
* Move carousel skeleton HTML generation to the server. It …
=> First batch of improvements to Carousel

projects/plugins/jetpack/changelog/2021-04-20-16-14-30-697350, projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
* The `for` attribute of a `label` element should contain the id of the labeled element. (More info [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label).)
* The incorrect `for` attributes in the carousel comments cause accessibility errors in the [WAVE tool](https://wave.webaim.org/).
* Fix this by setting the `for` attributes in the carousel comment fields to the labeled elements' ids.
* n/a
* no
1. Install, activate, and connect the master branch of Jetpack.
2. Navigate to Jetpack -> Settings -> Writing. Enable the `Display images in a full-screen carousel gallery` and `Show comments area in carousel` settings.
3. Create a post with an image gallery.
4. Navigate to the post and confirm that the carousel displays properly.
5. Test your site using the WAVE tool: …
=> Carousel: use element ids in the for attributes of the label elements

.github/workflows/tests.yml
It's not even passing a token, it's passing the literal string
"secrets.API_TOKEN_GITHUB" due to incorrect syntax.
If it were passing a token, whatever tests were trying to use it would
probably fail on forked PRs. If we do wind up needing a token for tests,
we should try to use GH's own `secrets.GITHUB_TOKEN` (which will always
exist, but with read-only access for forked PRs) instead of matticbot's.
I see this was added during #18851, but it's not clear it was even being used there.
None
No
* Is CI happy?
=> tests: Stop setting GITHUB_TOKEN when running tests

projects/plugins/jetpack/changelog/fix-plugin-search-error, projects/plugins/jetpack/modules/plugin-search.php
Fixes #19576
When we filter the list of plugins returned by the .org API, we assume a regular format (an object with arrays of information about each plugin).
However, other plugins and themes can also use the same `plugins_api_result` filter, with a lower priority, to change the response before we attempt to filter it.
Let's account for that and try to handle the different formats that may be offered to us.
* N/A
* No
I could not reproduce the exact error on my end, but we can check if the existing feature still works.
* On a site that's connected to WordPress.com, go to Plugins > Add New
* Search for Photon
* See that the Photon feature is highlighted as the first result, while the Jetpack plugin is not on the result list.
=> Feature hints: handle multiple plugin response formats.

tools/docker/Dockerfile, tools/docker/README.md, tools/docker/config/php.ini, tools/docker/docker-compose.yml
This PR fixes remote debugging using Xdebug from the docker container and addresses https://github.com/Automattic/jetpack/issues/19427
The command `apt-get install php-xdebug` in `Dockerfile` was installing an xdebug version for php 8, apache is using php 7.4 so xdebug was not available for remote debugging the wordpress install.
Switching to the `php7.4-xdebug` package fixes it.
Before (php cli has the same config as apache):
```
⋊> docker exec -it jetpack_wordpress bash
root@a84e9975cdba:/var/www/html# php -v
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
```
After:
```
⋊> docker exec -it jetpack_wordpress bash …
```
=> Fix using xdebug from docker container

projects/plugins/jetpack/changelog/fix-nav-unification-array-filter-warnings, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
Fixes the array_filter warnings we are receiving when the $submenu[ $slug ] is not set. 
Adding isset() checks on $submenu[ $slug ] array making sure it exists.
No
- Sandbox your wordpress.com environment
- Login with an Editor account on wordpress.com
- Make sure that no warnings are triggered on your sandbox by using `tail -f /tmp/php-errors`
=> Fixed array_filter warnings when the $submenu[ $slug ] is not set.

tools/docker/.dockerignore
Ignores the JT installation directory.
Otherwise if JT is installed, Docker complains about unreadable files
there when doing `jetpack docker build-image` or the like.
None.
No.
* Download the JT installer and run it per PCYsg-snO-p2. You don't need to actually sign up for JT.
* Try `yarn docker:build-image` or `jetpack docker build-image`.
=> docker: Add bin/jt to dockerignore

projects/plugins/jetpack/_inc/client/at-a-glance/scan.jsx, projects/plugins/jetpack/changelog/fix-at-a-glance-link-to-scan-atomic-sites
Fixes https://github.com/Automattic/wp-calypso/issues/48178
* Hide link to Scan's section from Atomic sites. The Scan panel located at the `At a Glance` section contains a link to `wordpress.com/scan/:site` which leads users to a section that is not available to Atomic sites.
Read https://github.com/Automattic/wp-calypso/issues/48178 and 1164141197617539-as-1200221780317813.
This PR does not change what data or activity we track or use.
**Atomic site**
* Get an Atomic site.
* Activate the Jetpack Beta Tester plugin on the site.
* On the Jetpack Beta Tester plugin, activate this branch.
* Visit the site's wp-admin dashboard.
* Visit the At a glance section of the Jetpack plugin.
* Make sure that the Scan panel doesn't show any link to `wordpress.com/scan/:site` or any other link.
**Jetpack …
=> At a glance: hide link to Scan from Atomic sites

projects/plugins/jetpack/changelog/add-recommendations-e2e-improvements, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/recommendations.js, projects/plugins/jetpack/tests/e2e/specs/recommendations.test.js
Follow-up of #19460.
* Target input elements by their ID and remove `:nth-child` from selectors.
* Simplify assertion statements.
This doesn't bring changes to the product, it only enhances the Recommendations module's e2e test.
No. It doesn't change what data or activity we track or use.
* Code review: make sure the changes improve readability and robustness.
* `cd` into `jetpack/projects/plugins/jetpack/tests/e2e`.
* Run `yarn test-e2e ./specs/recommendations.test.js` to run the test in headless mode or `HEADLESS=false yarn test-e2e ./specs/recommendations.test.js` if you want to see it in action.
* Make sure the test pass. You should see an output like this:
```
2021-04-07 17:36:03 info: TEST PASSED: Jetpack Recommendations - Steps
PASS  specs/recommendations.test.js (104.614 s) …
```
=> Recommendations (Jetpack Assistant): make element selectors more robust

.github/workflows/build.yml
Better for the beta builder to not accept download requests for any
arbitrary PR.
None, but similar to p3btAN-1nR-p2
No
Merge this and deploy the corresponding PR for the beta builder, then
* Master-merge some other PR and see that the builder returns success (and that the zip gets downloaded too).
* Try curling betadownload.jetpack.me manually (without the secret, of course) and see that you get a 403 response.
=> build: Use a shared secret when informing the beta builder

projects/plugins/jetpack/changelog/2021-04-20-19-12-55-295671, projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
* Add a label element for the carousel comment form textarea.
* n/a
* no
1. Install, activate, and connect the master branch of Jetpack.
2. Navigate to Jetpack -> Settings -> Writing. Enable the `Display images in a full-screen carousel gallery` and `Show comments area in carousel` settings.
3. Create a post with an image gallery.
4. Navigate to the post and confirm that the carousel displays properly.
5. Test your site using the WAVE tool: https://wave.webaim.org/
6. In the WAVE tool, turn off styles and scroll down to the bottom of the page to see the carousel comments. You'll see an error related to form label for the carousel comment textarea element.
7. Apply this branch.
8. Navigate to the post with the gallery and confirm that the carousel displays properly.
9. Retest your site …
=> Carousel: add label to carousel comment form textarea

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/changelog/Show current plan in sidebar, projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.css, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49660
To Do
* Adds the plan name in Upgrades menu title
* Supports passing inline text via the `admin-menu` api
* Defaults to `my-plan` for Plans submenu.
Please follow the instructions here https://github.com/Automattic/wp-calypso/pull/52111
=> Adds the current plan inline with Upgrades menu.

projects/plugins/jetpack/changelog/fix-e2e-fix-pinterest-spec, projects/plugins/jetpack/tests/e2e/config/default.js, projects/plugins/jetpack/tests/e2e/specs/free-blocks.test.js
Fix for a failing Pinterest test. The pin used for testing no longer exists so I changed it. I also moved the pinId into config file for easier management.
n/a
no
* CI happy
=> E2E tests: fix failing Pinterest test

projects/plugins/jetpack/changelog/fix-add-new-theme-menu-highlighting, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51349
* When going to the page `/wp-admin/theme-install.php` it will correctly highlight the menu item "Add New Theme" on Atomic sites.
* Install Jetpack Beta and activate this branch on an Atomic site
* Go to Appearance > Add New Theme in the menu.
* Observe the menu item correctly highlighted as the current menu item you're on.
=> Fix "Add New Theme" menu item highlighted

projects/plugins/jetpack/changelog/add-rest-api-v12-list-modules-endpoint, projects/plugins/jetpack/json-endpoints/jetpack/class-jetpack-json-api-modules-list-v1-2-endpoint.php, projects/plugins/jetpack/json-endpoints/jetpack/json-api-jetpack-endpoints.php, projects/plugins/jetpack/tests/php/json-api/test-class.json-api-jetpack-modules-endpoints.php
Introduces a new v1.2 endpoint for listing modules.
* Updates the min. max versions in the existing v1 modules list endpoint
* Adds a new v1.2 endpoint for listing modules that returns additional module info (same as `v4` endpoint excluding the `options` field)
p9dueE-2Lm-p2
No
D60475-code
=> REST API: Add list modules v1.2 endpoint

projects/plugins/jetpack/changelog/fix-e2e-event-name-logging, projects/plugins/jetpack/tests/e2e/lib/env/playwright-environment.js
Fix for a logging issue.
When hooks that are part of a test suite end their name is incorrectly logged using test's name, instead of hook's name.
n/a
no
* CI happy
* Check log files info level for hooks start and end events are properly logged and their name match. 
Example:
``` 
2021-04-22 18:38:54 info: START: beforeAll - Jetpack pre-connection
2021-04-22 18:38:59 info: SUCCESS: beforeAll - Jetpack pre-connection
```
=> E2E tests: fixed incorrect event name logged for hook end

tools/jetpack-live-branches/jetpack-live-branches.user.js
* Nests the live branch JN site options under a `<details>` ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)) element to reduce noise when viewing PRs.
* Browser compat looks good: https://caniuse.com/details
N/A
No.
* Install this updated userscript version in your userscript browser extension.
* Raw install URL: https://github.com/Automattic/jetpack/raw/0d97153c47e8d15808bed843285f735458f9f6cc/tools/jetpack-live-branches/jetpack-live-branches.user.js
* Open a PR and observe that the live branch site options are nested under an accordion-like toggle.
=> Live Branches: show JN site options in details element

tools/cli/commands/changelog.js
This PR refactors the `jetpack changelog` tool to make things significantly cleaner and make further development easier. 
Refactored using the "Sami method" which worked for the "Write" command: https://github.com/Automattic/jetpack/pull/19444
This PR makes "add", "write" and "validate" work the same way.
No
* Run `jetpack changelog`
* Make sure all the commands continue to work properly.
* Passthroughs should work correctly as well, e.g:
* `jetpack changelog add plugins/jetpack -s "patch" -t "bugfix" -e "testing changelog" -f "test"`
* `jetpack changelog validate packages/abtest --no-verify`
* `jetpack changelog write packages/abtest` 
* Error handling should largely be handled by the changelogger now, so incorrect or invalid commands should fail.
=> CLI: Refactor `jetpack changelog` tool

projects/plugins/jetpack/changelog/update-taxonomy-nav-links, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
See Automattic/wp-calypso#50568
* Categories and Tags menu items (under Posts) should link to Calypso screens when the Dashboard appearance toggle is **off** under Me -> Account Settings, and to `/wp-admin` when the toggle is on.
* The same menu items should link to `/wp-admin` screens when the Dashboard appearance toggle is **on** under Me -> Account Settings
No
* Apply D60379-code to your sandbox and sandbox the API
* Make sure the **Show advanced dashboard pages.** toggle is **off** under `/me/account`
* View your site's dashboard and click on Categories or Tags under Posts in the main navigation. You should be brought to `/settings/taxonomies/category/[site]` or `/settings/taxonomies/post_tag/[site]`
* Turn the **Show advanced dashboard pages.** setting **on** under `/me/account`
* …
=> Nav Unification: Link to Calypso screens for Categories and Tags

projects/plugins/jetpack/changelog/Always use WP Admin for comments in Atomic sites., projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51429
* Always use WP Admin for comments in Atomic sites by not altering the Comments menu at all.
* With `Show advanced dashboard pages.` off
* Load this branch in Jetpack Beta
* Click "Comments"
* You should be redirected to WP Admin
* Repeat with `Show advanced dashboard pages.` on (sanity check)
=> Always use WP Admin for comments in Atomic sites.

projects/plugins/jetpack/changelog/2021-04-23-01-04-14-716130, projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php
Fixes #19616
This seems odd, as the filter completely ignores the provided `$content` from the filter normally, so not sure if this is correct or not.. it seems that Jetpack should be using `$content` instead of `$post->post_excerpt` below in the if-else instead.
* Returns early when no context is provided
No
No
*  See Issue
=> Theme Tools: Return early when there's no post context in jetpack_blog_display_custom_excerpt()

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/changelog/update-admin-menu-api-special-characters-url, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/49309
* Update `prepare_menu_item_url` method in admin menu API to replace special characters in URLs with their HTML entities such as ampersand (e.g. convert `&amp;` to `&`).
no
**Simple sites**
* Apply patch to Sandbox.
* Sandbox the public API.
* Enable the "Portfolio" menu item by going to Settings > General > Writing and toggling this on.
* Click Projects > Project Types and view the correct sub-menu being open.
* Try other menu items to check for regressions.
**Atomic sites**
* Install Jetpack Beta and activate this branch
* Enable the "Portfolio" menu item by going to Settings > General > Writing and toggling this on.
* Click Projects > Project Types and view the correct sub-menu being open.
* Try other menu items to check for …
=> Decode special chars in URLs for admin menu responses

projects/plugins/jetpack/_inc/connect-button.js, projects/plugins/jetpack/changelog/update-registration-copy, projects/plugins/jetpack/class.jetpack-connection-banner.php, projects/plugins/jetpack/scss/organisms/_banners.scss
NOTE: This PR assumes user-less connections are active for all users and should only be merged if and when we decide we are shipping it.
With user-less, when the users click on "Set up Jetpack" and see the in-place connection UI to authorize a user, the connection is already established.
This PR makes the title of this step more clear, to inform the user that Jetpack has been activated.
In our testings, some people reported confusion after bailing the connection flow and realizing Jetpack was connected even though they didn't make it to the end.
* Changes the title of the in-place connection page after Jetpack is connected on a site level
No
* Launch a new site with user-less testing mode
* Click "Set up Jetpack" either in the WP-admin dashboard or from the Jetpack Dashboard
* Make sure …
=> Changes copy upon jetpack activation

projects/plugins/jetpack/changelog/update-add_unavailable_reason_in_modules_list, projects/plugins/jetpack/class.jetpack-admin.php, projects/plugins/jetpack/class.jetpack-modules-list-table.php, projects/plugins/jetpack/scss/templates/_settings.scss, projects/plugins/jetpack/tests/php/test-get-modules.php
Display the reason a module is listed as unavailable in the modules list.
- Jetpack_Admin: Introduces a `get_module_unavailable_reason` static method in `Jetpack_Admin`
- Jetpack_Admin: Updates the existing `get_modules` method by adding a `unavailable_reason` entry in each module array. If the module is available, this will be an empty value.
- 
**Notes**: Also affects the modules core `v4` [endpoint](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L195) that depends on the `get_modules` method but I think this is useful info to be included in our corresponding API response as well.
1191179647901802-as-1200216211144043/f
No
* Connect your site only at a site level (default in local env or by checking …
=> Jetpack Modules: Add explanation when a module is unavailable

tools/cli/commands/changelog.js
* This PR adds the `version` command to the `jetpack changelog` tool.
p9dueE-2A1-p2
* Run the `jetpack changelog` command and try the `version` command
* Passthroughs should work, ie, `jetpack changelog version plugins/jetpack next`
* Error handling should be handled by changelogger itself
* Make sure the existing commands, specifically add, continue to work normally.
=> CLI: Add `version` to `jetpack changelog`

projects/packages/jitm/changelog/update-jitm-redirect-unlinked, projects/packages/jitm/src/class-post-connection-jitm.php
The upsell JITMs redirect the users to landing pages from where they can select a product and immediately proceed to checkout.
Up to now, these JITMs where only displayed to connected users, but with user-less in mind we are going to show them to non-connected users as well.
This PR handles non-connected users being redirected by JITM CTAs by adding an `unlinked` query arg to the redirect url.
On the Calypso checkout page when the `unlinked` query arg is detected, users will be asked to connect their account first before proceeding to checkout, ensuring a non-breaking UX.
* `Post_Connection_JITM` class: Checks if the current user has connected their WordPress.com account and adds the `unlinked` query arg in the redirect url if not.
1191179647901802-as-1200216211144035/f
No
D60580-code
=> JITM: Add unlinked in redirect url to indicate not-connected user

projects/plugins/jetpack/changelog/fix-import-export-inconsistency, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51533
Here is a summary of import/export links in Calypso, depending on the "Show advanced dashboard pages" setting on wordpress.com/me/account
```
simple | Advanced Dashboard OFF = 
Import https://wordpress.com/import/simplesite
Export https://wordpress.com/export/simplesite
simple | Advanced Dashboard ON = 
Import https://simplesite/wp-admin/import.php?return=https%3A%2F%2Fwordpress.com%2Fhome%2Fsimplesite
* Export https://wordpress.com/export/simplesite
atomic | Advanced Dashboard OFF =
Import https://wordpress.com/import/atomicsite
† Export https://atomicsite/wp-admin/export.php?return=https%3A%2F%2Fwordpress.com%2Fhome%2Fatomicsite
atomic | Advanced Dashboard ON =
Import https://atomicsite/wp-admin/import.php?return=https%3A%2F%2Fw …
```
=> Simple site's export menu now follows the should_link_to_wp_admin() setting

projects/packages/jitm/changelog/update-pre-connection-jitms, projects/packages/jitm/changelog/update-pre-connection-jitms-2, projects/packages/jitm/src/class-pre-connection-jitm.php, projects/packages/jitm/src/css/jetpack-admin-jitm.scss, projects/packages/jitm/tests/php/test_pre_connection_jitm.php, projects/plugins/jetpack/changelog/update-pre-connection-jitms, projects/plugins/jetpack/class-jetpack-pre-connection-jitms.php, projects/plugins/jetpack/functions.global.php, projects/plugins/jetpack/tests/php/general/test-class-jetpack-pre-connection-jitms.php
This PR updates our pre-connection JITMs so they can be launched to all Jetpack sites. Until now, they were only available when setting a filter on your site
This PR:
﻿- removes that dependency to a filter to display the pre-connection messages.
- ~~updates the existing function used to display the ToS blurb, so that blurb can be used without echo'ing it right away.~~ Reverted that, we'll use custom ToS blurbs in those messages. See p1HpG7-bPy-p2#comment-46028
- updates the connection links in all pre-connection messages.
~~A by-product of this change is that clicking on the set-up button in those messages launches the old Calypso flow instead of the in-place flow.~~ I fixed that in 33b944bc71ff085e45f83f0590bb9288afe1e32a
* Internal reference: p1HpG7-bPy-p2
* It does add a from parameter …
=> JITMs: update pre-connection messages for launch

projects/plugins/jetpack/changelog/update-jetpack-button-block-to-enqueue-core-button-style, projects/plugins/jetpack/extensions/blocks/button/button.php, projects/plugins/jetpack/extensions/blocks/button/editor.scss, projects/plugins/jetpack/extensions/blocks/button/view.scss
As tracked in https://github.com/Automattic/jetpack/issues/19464 the Jetpack Button block depends on styles from the core Button block (via the class name `.wp-block-button__link`. In an FSE theme like TT1-blocks, no styles are provided to override the button block styling, so it becomes apparent that when no core Button block is inserted into a template part, then the Jetpack button block appears unstyled.
To address this, we can ensure that the core Button block styles are always enqueued when a Jetpack Button block is rendered on the server.
Possible fix for #19464 and related to https://github.com/Automattic/jetpack/issues/19504
* Always ensure the core Button Block styles are enqueued when rendering a Jetpack Button block
* Provide a default for the Button border (`inherit`), to …
=> Jetpack Button Block: Ensure block enqueues core Button block styles as a dependency

projects/plugins/jetpack/changelog/fix-invalid-menu-id, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
Some menu items are pointing to full URLs. It turns out these have a
number of invalid characters that aren't getting stripped out by the
core WordPress functions. This meant that invalid ID attributes were
being set and that in turn broke the SVG styling introduced in #19364.
Fixes #19625
This PR fixes the ID, by filtering out invalid characters, allowing the icon to be properly displayed.
N/A
No.
* Using an Atomic site install Woocommerce
* Run the current master branch using the Jetpack Beta plugin
* Without Woocommerce activated, note that the icon is not displayed in the menu
* Swap to this branch and the icon should be displayed correctly.
=> Admin Menu: Fix invalid menu item ID attributes

projects/packages/connection/changelog/add-track-unique-registrations, projects/packages/connection/composer.json, projects/packages/heartbeat/changelog/add-track-unique-registrations, projects/packages/heartbeat/composer.json, projects/packages/jitm/changelog/add-track-unique-registrations, projects/packages/jitm/composer.json, projects/packages/licensing/changelog/add-track-unique-registrations, projects/packages/licensing/composer.json, projects/packages/options/changelog/add-unique_registrations_stat, projects/packages/options/composer.json, projects/packages/options/legacy/class-jetpack-options.php, projects/packages/sync/changelog/add-track-unique-registrations, projects/packages/sync/composer.json, projects/packages/terms-of-service/changelog/add-track-unique-registrations, projects/packages/terms-of-service/composer.json, projects/packages/tracking/changelog/add-track-unique-registrations, projects/packages/tracking/composer.json, projects/plugins/jetpack/changelog/add-track-unique-registrations, projects/plugins/jetpack/changelog/add-unique_registrations_stat, projects/plugins/jetpack/class.jetpack.php, projects/plugins/jetpack/composer.json, projects/plugins/jetpack/composer.lock
-- New rebased version of https://github.com/Automattic/jetpack/pull/19213 --
Under the `jetpack-connections` MC Stat there's an entry for `unique-connection`, that is bumped everytime a site connects for the first time.
This is triggered only after the user authorization. 
This PR adds a new similar metric for `unique-registrations` that is triggered upon site registration and will therefore count sites with a user-less connection.
* Adds unique-registrations MC Stats
1191179647901802-as-1199552431277341
Yes, we now anonymously track the first time a site was registered under `jetpack-connections/unique-registrations` MC Stat
* Visit MC Stat `jetpack-connections/unique-registrations` and look at the count
* Make sure this option does not exist: `wp jetpack options …
=> Record stat of the first time the site is registered

projects/plugins/jetpack/_inc/client/components/jetpack-dialogue-modern/style.scss, projects/plugins/jetpack/changelog/2021-04-23-21-16-10-453129, projects/plugins/jetpack/class.jetpack.php
Fixes #18966
* The update modal content could be generated using WordPress blocks, such as the Button block. Let's enqueue the `wp-block-library` style when the Jetpack version is bumped so that the modal can include properly styled blocks.
* n/a
* no
1. Install and activate this branch.
3. Cause a version update. The update modal for version 8.4 includes a button, so update from 8.3 to 8.4:
a. In the `jetpack.php` file, change the `JETPACK__VERSION` value to 8.3.
b. Reload the site.
c. In the `jetpack.php` file, change the `JETPACK__VERSION` value to 8.4.
4. Navigate to the Jetpack dashboard. You should see the 8.4 update modal, and a button should be displayed correctly at the bottom of the modal.
5. Repeat from step 3, this time navigating to other admin pages …
=> Update Modal: use the wp-block-library styles

projects/packages/password-checker/.gitignore, projects/packages/password-checker/changelog/update-password-checker-gitignore
When releasing Jetpack 9.7 Beta earlier today, the Password Checker directory in my checked out copy of jetpack-production/branch-9.7 included the whole vendor directory for the password-checker package. We do not need it since those are only dev dependencies.
* N/A
* No
* I'm not sure how to best test this.
=> Password checker: avoid checking in vendor directory

projects/packages/jitm/changelog/update-jitm_jetpack_is_mobile, projects/packages/jitm/composer.json, projects/packages/jitm/src/class-jitm.php, projects/packages/jitm/src/class-post-connection-jitm.php, projects/plugins/jetpack/changelog/update-jitm_jetpack_is_mobile, projects/plugins/jetpack/composer.json, projects/plugins/jetpack/composer.lock, projects/plugins/jetpack/jetpack.php, projects/plugins/jetpack/package.json
* The JITM package needs to be independent of the Jetpack plugin. Replace the `jetpack_is_mobile()` function call with `Device_Detection::is_smartphone()`. Also add the `jetpack-device-detection` package to the JITM package's requirements.
* n/a
* no
Verify that JITMs are still displayed:
1. Install this branch. Activate Jetpack and connect.
2. Navigate to the Jetpack dashboard. A JITM should display (assuming that you haven't previously dismissed the JITMs that display on the JP dashboard.).
=> JITM: Use the Device_Detection package to determine if the device is mobile

.github/files/build-all-projects.sh
We used `composer update --root-reqs` to try to update references to
monorepo packages to point to the built versions instead of the monorepo
versions.
But that fails to update any monorepo packages that are depended on
indirectly, like how plugins/jetpack depends on packages/sync which
depends on packages/password-checker but does not itself depend on
packages/password-checker.
This probably doesn't matter much, except for the case where we're
bundling the packages in the plugin. In that case we might get files
that aren't supposed to be included, or omit files that are.
So instead, explicitly update just the packages built from the monorepo.
#19666
No
* Revert #19666 and run a build. Does `vendor/automattic/jetpack-password-checker/vendor` still not exist in the Jetpack plugin?
=> build: Fix package ref updating

projects/plugins/jetpack/changelog/fix-page-optimize-conflict, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
Fixes #19340 
Added `rtl` extra data for `colors` and `jetpack-admin-menu` CSS handles. This in turn will make Page Optimize to ignore the stylesheets since the current implementation does not support RTL. 
No
_Simple_
- Apply D60626-code to your WP.com sandbox.
- Sandbox the API and a simple site.
_Atomic_
- Install Jetpack Beta on a Atomic site and switch to the branch of this PR.
- Go to https://wordpress.com and switch to the WoA site.
_Jetpack_
- Spin up a local environment and switch to this PR branch
To test this fix, on all environments, you'll need to:
- Have page optimize installed (except for Simple sites)
- Go to https://wordpress.com/me/account and change your language to an RTL language.
- Enable an RTL language on your site (Settings > General)
- Make sure that Page …
=> Fixed Page Optimize plugin conflict for RTL stylesheets

projects/plugins/jetpack/_inc/client/at-a-glance/connections.jsx, projects/plugins/jetpack/_inc/client/at-a-glance/stats/dash-stats-bottom.jsx, projects/plugins/jetpack/_inc/client/components/connect-button/index.jsx, projects/plugins/jetpack/_inc/client/components/connect-user-bar/index.jsx, projects/plugins/jetpack/_inc/client/components/connect-user-bar/style.scss, projects/plugins/jetpack/_inc/client/discussion/subscriptions.jsx, projects/plugins/jetpack/_inc/client/searchable-modules/index.jsx, projects/plugins/jetpack/_inc/client/security/monitor.jsx, projects/plugins/jetpack/_inc/client/security/protect.jsx, projects/plugins/jetpack/_inc/client/security/sso.jsx, projects/plugins/jetpack/_inc/client/sharing/publicize.jsx, projects/plugins/jetpack/_inc/client/writing/masterbar.jsx, projects/plugins/jetpack/_inc/client/writing/post-by-email.jsx, projects/plugins/jetpack/changelog/update-standardize-user-connection-text
Fixes inconsistent messaging to authenticate the user with WordPress.com
Updates all copy to use the same messaging for connecting/authenticating the user with WordPress.com.
Before - Dashboard: 
After - Dashboard: 
Before - Stats dashboard button:
After - Stats dashboard button:
Before - Settings card bar:
(This is just one - there are many settings bars that change in the PR, please look at the code changes)
After - Settings card bar: 
p1HpG7-bRQ-p2#comment-46172
No
Set up Jetpack in site-only connection mode, and view the respective areas. Check for:
- Spacing
- Typos
- Wording
=> Standardize text prompting to connect/authenticate the user to wordpress.com

projects/plugins/jetpack/changelog/e2e-fix-mailchimp-test, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/blocks/mailchimp.js
Fix for cases when Mailchimp is already set up and the Mailchimp block test fails because it's expecting the setup button, but instead the join button is displayed.
This happens when running the Mailchimp test multiple times using the same site url.
n/a
no
* CI green
* Locally, start with a clean setup, then run the Mailchimp test multiple times without cleaning the env in between.
=> E2E: Check Mailchimp connection status 

projects/packages/jitm/changelog/update-jitm_filters, projects/packages/jitm/src/class-jitm.php, projects/packages/jitm/src/class-post-connection-jitm.php, projects/packages/jitm/tests/php/test_JITM.php, projects/plugins/jetpack/changelog/update-jitm_filters, projects/plugins/jetpack/class.jetpack.php
The `jetpack_just_in_time_msgs` filter is used to enable and disable the display of the JITMs. Let's set the default value to true. Currently, the plugin has to set the filter to true in order to display JITMs If a plugin has configured the JITM message package, it's safe to assume that the JITMs should be displayed.
Also, the `jetpack_just_in_time_msg_cache` filter is used to enable and disable the JITM cache. Let's set the default value to true.
These changes will make the JITM package easier to consume. Consumer plugins will no longer need to set these filters in order to display and cache JITMs.
* n/a
* no
Verify that JITMs are still displayed:
1. Install this branch. Activate Jetpack and connect.
2. Navigate to the Jetpack dashboard. A JITM should display (assuming that you haven't …
=> JITM: set the JITM and cache filter defaults to true

projects/plugins/jetpack/_inc/client/components/navigation/index.jsx, projects/plugins/jetpack/_inc/client/components/navigation/test/component.js, projects/plugins/jetpack/changelog/update-reactivate-plans
* Enables the Plans tab in Jetpack navigation menu for unliked users
p9dueE-2EQ-p2#comment-4986
No
* Checkout this branch and make sure to run `jetpack build plugins/jetpack`
* Connect your site only at a site level
* Visit the Jetpack Dashboard
* Make sure the "Plans" tab is visible
* Click the "Plans" tab
* choose a plan and click to buy it
* If logged out, log in
* Once you reach the checkout page, you can go back to your wp-admin
* Visit the Jetpack Dashboard and make sure your WPCOM user is linked to your site:
Test the above flow in different conditions:
* already logged in to WPCOM in the same window
* Not logged in to WPCOM
* Also test the normal flow in a fully connected site
=> enable Plans tab to unliked users

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-transient.php, projects/plugins/jetpack/changelog/add-wpcom-v2-delete-transient-endpoint, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-transient.php
* Part of a fix for https://github.com/Automattic/wp-calypso/issues/50312
* Adds an endpoint to delete a transient on a Jetpack site, so that we can clear `jetpack_connected_user_data_$user_id` when a user makes an account change (e.g. to color scheme or language) on WP.com
p1618495635435200/1618329458.321800-slack-CKZHG0QCR
p3hLNG-18q-p2
Nope.
* Apply D60544-code and D60594-code and sandbox the API.
* Send a DELETE request to a Jetpack site via [the console](https://developer.wordpress.com/docs/api/console/): `https://public-api.wordpress.com/wpcom/v2/sites/{site slug or id}/transients/jetpack_connected_user_data_1`
* The response should be `success: true` or `success: false`
=> API: Add delete transient wpcom/v2 endpoint

projects/plugins/jetpack/changelog/e2e-connect-btn-timeout, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/in-place-authorize.js
Change the timeout to wait for loading animation in connection frame, before the approve button is displayed. 
p1619699921405800/1619682720.387300-slack-CBG1CP4EN
no
* All E2E tests should pass
=> E2E tests: Connection wait for loading timeout to 35 sec

tools/docker/mu-plugins/01-monorepo.php, tools/docker/mu-plugins/avoid-plugin-deletion.php, tools/docker/mu-plugins/fix-monorepo-plugins-url.php
Within our Docker setup, we load from the monorepo our plugins. We do not want WP to upgrade or delete these plugins else it overrides our local copies. This extends the existing prevention of that happening to Jetpack to the other monorepo plugins.
I'm not sure the best way to automate this to always cover all monorepo plugins, short of using how WP searches for plugins from the monorepo plugin directory and add those to the array. But, this at least prevents anyone from wrecking their local setup in the meantime.
* Adds to the hardcoded list of monorepo plugins Backups, Beta, Debug Helper
n/a
No
* Before and after this PR, run Docker off master. See the upgrade prompt for Backups without patch.
*
=> Docker: Do not allow update/delete of Backups, Beta, etc

.github/renovate.json
Eslint and its plugins seem pretty easy to validate, if CI is happy then
we're probably good.
So let's group them all together in one PR instead of spreading them out
over several.
None
No
* Merge, then trigger renovate to run and see if it grouped them.
=> renovate: Group eslint and its plugins together

projects/plugins/jetpack/_inc/client/sharing/publicize.jsx, projects/plugins/jetpack/changelog/fix-duplicate-publicize-connect-banner
Fixes an issue when we were showing two banners to connect the user in the Publicize settings card, as shown here: 
Removes the legacy connection banner from the Publicize settings card. 
Slack 
No 
1. Connect site-only mode
2. Enable Publicize from `/wp-admin/admin.php?page=jetpack_modules`
3. Navigate to `/wp-admin/admin.php?page=jetpack#/sharing`
4. Look at the Publicize card
5. It should only have one prompt to connect the user
6. Connect a user 
7. Make sure the existing prompt to "Connect your social media accounts" is still present, and works.
=> Fix duplicate Publicize connection banner

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/changelog/fix-paid-upgrades-and-jetpack-menu-item, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-jetpack-admin-menu.php
Fixes #19598 
- In case of `Upgrades` menu, we are safe to remove the default `paid-upgrades.php` submenu item that's generated by core.
- In case of Jetpack menu, for non-administrator roles, the first submenu item (and therefore the default slug of the menu) is the generated by the core's menu behaviour. In this case, when clicking on the menu item, the user will be redirected to a broken page. Just as in the case of `Upgrades`, the core submenu item can be removed.
- The Settings menu item will not appear for Editor roles because the only item displayed in there was `Sharing` which it should be hidden. As in the case of the other pages mentioned above, we are safe to remove this page since it does not contain additional functionality.
No
_Simple_
- Apply D60482-code to your WP.com …
=> Nav Unification: Fix Upgrades, Jetpack and Settings default menu slugs in WP-Admin

projects/plugins/jetpack/_inc/client/at-a-glance/index.jsx, projects/plugins/jetpack/changelog/fix-protect-for-non-admins
Fixes p9dueE-2EQ-p2#comment-5000
* do not display the Protect card for non-admin users while there is not a connected owner - and thus Protect can not be activated
p9dueE-2EQ-p2#comment-5000
No
* Open 2 windows of the site. One logged in as admin and another as an editor
* With the admin, connect only at a site level
* As an editor, visit the Dashboard and confirm Protect is not there
* As an admin, connect your user - make sure Protect is enabled
* As an editor, confirm Protect is present
* As an admin, deactivate Protect
* As an editor, confirm Protect is not present
* As an admin, re-activate Protect
* As an admin, Disconnect Jetpack and connect again only at a site level (protect will be kept marked as active)
* As an editor, confirm Protect is not there
=> Hide protect card for non-admins in site-only connection

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php, projects/plugins/jetpack/changelog/update-hide-settings-site-level-non-admin
When the site is at a site-only connection, non administrators are not able to link their accounts to WordPress.com to enable features that require a user connection.
Editors, for example, can access the Settings page only to see Post By Email and Publicize, however they will not be able to link their accounts until and admin has done this before and enabled those features.
This PR hides the Settings page for non-admin while the site doesn't have a full connection
* Hides the Settings menu for non admin while in site-only connection
p1619720622439100-slack-CBG1CP4EN?thread_ts=1619718679.433500&cid=CBG1CP4EN
No
* Connect at a site level only
* Check the Settings menu is available and working for admins
* Login as an editor and check the Settings menu is not available
* Complete the …
=> Hide settings in site-only conn for non admin

projects/plugins/jetpack/_inc/client/components/auth-iframe/index.jsx, projects/plugins/jetpack/_inc/client/components/auth-iframe/test/component.js, projects/plugins/jetpack/changelog/fix-iframe-heigh-on-dashboard
Fixes the layout of the connection iframe when the user is connecting via one of the buttons in the Jetpack Dashboard.
What really changed here is that we're now displaying the TOS agreement on this context, and we didn't before.
I'd love a confirmation if the fix is to really adjust the height or to remove the TOS.
Before (see the scrollbar):
After:
* Fix the height of the In-place Connection dialog on the Dashboard
p1619722373443900-slack-CBG1CP4EN
No
* Test the iframe connection in every possible situation:
* Regular in-place connection flow while logged in to WPCOM
* Regular in-place connection flow while not logged in to WPCOM (option to skip user auth)
* Set up a site-only connection. Go to the Jetpack Dashboard and click in one of the "Connect your WordPress.com account" links -> …
=> fix default iframe heigh

projects/packages/jitm/changelog/update-jitm_use_connection_auth_url, projects/packages/jitm/src/class-post-connection-jitm.php
Fixes #19701
* The user deletion notice currently uses the `Jetpack::build_connect_url` method to obtain the user authorization url. Let's use the `Manager::get_authorization_url` method instead, so that the JITM package doesn't depend on a Jetpack method.
* n/a
* no
1. On Jetpack master, start with a site that's connected to WordPress.com account A with Admin A.
2. Create a new user, Admin B.
3. Log out of the site, and of WordPress.com Admin A.
4. Log in with WordPress.com account B and Admin B local user.
5. Go to the Users menu
6. Click on the delete action next to the Admin A user.
7. You'll be offered an option to connect your account to WordPress.com, and become the new connection owner.
8. Click on that button.
9. You should be able to successfully connect your account to …
=> JITM: Use the connection package instead of Jetpack to get auth URL.

projects/plugins/jetpack/changelog/fix-protect-notice, projects/plugins/jetpack/modules/protect.php
Fixes "Undefined variable: output in plugins/jetpack/modules/protect.php:411"
Pretty straight forward. If none of the headers are present, $output is never set. We need to set it to ensure it is there to return.
*
no
no
* Load JP in a setup without any of those headers, probably like PHP CLI or soemthing.
*
=> Protect: Resolve PHP notice for unknown var

projects/packages/jitm/changelog/update-move_jitm_sync_hook, projects/packages/jitm/src/class-jitm.php, projects/plugins/jetpack/changelog/update-move_jitm_sync_hook, projects/plugins/jetpack/class.jetpack.php
The `jetpack_last_plugin_sync` transient value is used to determine if the JITM cache should be used. This transient is updated when the `jetpack_sync_before_send_updated_option` filter fires. Move the `jetpack_sync_before_send_updated_option` hook and the `jetpack_track_last_sync_callback` method from the Jetpack class to the JITM package. This will allow the JITM package to update the `jetpack_last_plugin_sync` transient value when the Jetpack plugin is not active.
* n/a
* no
1. Install and activate this branch. Connect Jetpack.
2. Check the value of the `jetpack_last_plugin_sync` transient:
`wp transient get jetpack_last_pluging_sync`
3. Activate a plugin.
4. Verify that the value of the `jetpack_last_plugin_sync` transient has changed.
=> JITM: move the last sync callback hook to the JITM package

projects/plugins/jetpack/changelog/fix-remove-replace-button, projects/plugins/jetpack/extensions/shared/external-media/editor.scss, projects/plugins/jetpack/extensions/shared/external-media/index.js, projects/plugins/jetpack/extensions/shared/external-media/media-button/index.js, projects/plugins/jetpack/extensions/shared/external-media/media-button/media-menu.js, projects/plugins/jetpack/extensions/shared/external-media/media-button/media-sources.js
Previously, our "Select Image" button would still show alongside Core's "Replace Image" button. Now, Cores' button is not shown, and our button shows as "Replace Image" when an image has been selected.
Fixes #19555
* Post Thumbnail UI should no longer show duplicate buttons, and buttons shown are appropriate
* n/a
no
* apply soon-to-be-generated Diff to your WPCom sandbox
* Open an existing post (or create a new one)
* Open the "Featured Image" section in the Post sidebar
* No featured image selected should look like: 
* With a selected featured image: 
Note that we use the Media Button in several locations throughout Gutenberg. These modifications should be isolated to featured image usage, but smoke testing other image-based blocks/settings since I can't find any tests for this.
=> External Media: don't show duplicate buttons for post thumbnails

projects/packages/sync/changelog/fix-sync-early-return-full-sync, projects/packages/sync/src/class-sender.php
When Sync is enabled on a site we add 2 hooks to the shutdown action to perform incremental sync and full sync processes. The do_full_sync hook was currently not checking if a Full Sync was running before updating options used to ensure a single process is running. As these hooks run for front end view we were adding unnecessary write operations. 
This updates the process to check the status and if no Full Sync is in progress we return instead of updating options.
Fixes #jpop-6590
* Increase performance by minimizing option writes from Full Sync.
N/A
No
There are several flows that should be tested manually and already have unit/integration tests.
1) Verify that incremental sync is not impacted. By performing site edits and verifying they synced (Debug Tool can give you sync queue info) …
=> If no Full Sync in process early return to minimize option writes

projects/plugins/jetpack/changelog/fix-legacy-seo-meta, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, projects/plugins/jetpack/modules/seo-tools/jetpack-seo-utils.php
* In Automattic/jetpack/pull/17309 the way the `LEGACY_META_OPTION` was handled got changed. However, there are simple WPcom sites (non Biz/eCom plans) that still have the legacy usage and need this option preserved.
* Internal report: p2EDhh-1hp-p2
* No.
* Will require a sandbox, test with no paid plan on WPcom simple site.
* Set the following option: `wp option add seo_meta_description 'Testing legacy front page meta description.' --url=__sandbox_url__`
* This will allow the UI to show up for editing the front page meta at: `https://wordpress.com/marketing/traffic/__site_url__`
* With the diff applied to your sandbox, should be able to update the front page meta.
* And for a Jetpack site (free or paid), updating the front mage meta should remain functional.
=> SEO: Fix LEGACY_META_OPTION handling for WPcom simple sites

package.json, projects/plugins/jetpack/changelog/add-wordpress-components-dep, yarn.lock
https://github.com/Automattic/jetpack/pull/19422 added the `@wordpress/components` dependency to the connection JS package, but seems to be causing the JS tests to fail ([example](https://github.com/Automattic/jetpack/pull/19745/checks?check_run_id=2516520038)):
```
[test-adminpage] Error: Cannot find module '@wordpress/components'
```
Apparently, the dependency needs to be also declared in the root `package.json` since the JS tests don't install the specific dependencies needed by the JS packages.
N/A.
No.
Check that all CI checks pass.
=> Add `@wordpress/components` dependency

projects/plugins/jetpack/changelog/add-advanced-general-menu-item, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51189
* When the advanced dashboard toggle is enabled we need to add an "Advanced General" menu item so that Calypso settings are still accessible.
No
**Simple Sites**
* Apply the WPCOM patch D61023-code to your Sandbox
* Check that Settings > Advanced General exists regardless of whether the "Advanced Dashboard" toggle is enabled or not and that it goes to WP Admin
* Check that Settings > General exists and goes to Calypso settings
**Atomic Sites**
* Install Jetpack Beta and activate this branch.
* Check that Settings > Advanced General exists regardless of whether the "Advanced Dashboard" toggle is enabled or not and that it goes to WP Admin
* Check that Settings > General exists and goes to Calypso settings
=> Add Advanced General menu item

projects/plugins/jetpack/changelog/fix-legacy-seo-calypso-error, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
* Follow up to Automattic/jetpack/pull/19753
* For users that are able to update the `LEGACY_META_OPTION` option, this change will avoid trying to update `TITLE_FORMATS_OPTION` which would display a 403 in Calypso.
* N/A
* No.
* Will require a sandbox with these changes pulled down.
* On a sandboxed site with no paid plan, set the following option: `wp option add seo_meta_description 'Testing legacy front page meta description.' --url=__sandbox_url__`.
* This will allow the UI to show up for editing the front page meta at: `https://wordpress.com/marketing/traffic/__site_url__`
* You should now be able to update that description without seeing any errors in Calypso or your sandbox.
* Next, add a Business plan to the sandboxed site. And again update the front page description. This should …
=> SEO: fix Calypso error when updating `seo_meta_description` option

projects/plugins/jetpack/changelog/fix-top-posts-widget, projects/plugins/jetpack/modules/stats.php
Fixes 6571-gh-jpop-issues
Since this subject is often confusing, also for myself, I thought it was a good idea to write down the "whys" here as I have it fresh in my mind.
This line was recently changed in [this commit](https://github.com/Automattic/jetpack/pull/19310/files#diff-074ea7354745baca91015b568ed3398387def033002ec1304e16c2f2578c86feR1261). But the truth is that the bug was not introduced there, the code was already buggy before.
First let's understand why we avoid the use of `date` and favor `gmdate`.
Both functions do the same thing. The difference is that, under Linux/Apache servers, `date` takes the local timezone into account, while it does not under Windows servers. This could make our code have different result in different servers, and that's why we favor `gmdate` …
=> Fix date used in Top Posts dashboar widget

projects/plugins/jetpack/changelog/changelog.md, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
See D61035-code
*   This PR brings the changes from .com over to Jetpack and fixes the issue for Jetpack sites.
* Apply this PR to a jetpack site. 
* Change the date or time format setting in the mobile app to use a slash (for example j \d\e F, Y ) ( a character you want to escape) not that the slashes are not escaped but remain. Which produced the expected result. 
No
=> WPCOM API: update settings endpoint to store unslashed values for date/time

projects/packages/connection/changelog/update-remove_post_authorization_from_package, projects/packages/connection/legacy/class-jetpack-xmlrpc-server.php, projects/packages/connection/tests/php/test_jetpack_xmlrpc_server.php, projects/plugins/jetpack/changelog/update-remove_post_authorization_from_package, projects/plugins/jetpack/class-jetpack-xmlrpc-methods.php, projects/plugins/jetpack/tests/php/general/test_class.jetpack-xmlrpc-server.php
Part of the Package Independence effort, removes the routine that runs after `remote_connect` from the Connection package and use a hook in the plugin to do it instead
* Removes the routine that runs after `remote_connect` from the Connection package and use a hook in the plugin to do it instead
1199702491434901-as-1199702491434919
No
* Look at the code
* Tests are passing?
* Not sure how to test the real thing. Do you think that's enough?
* Do you think we should deprecate `do_post_authorization` method instead of deleting it? Nobody should be using it...
=> Remove post authorization from package

projects/plugins/jetpack/changelog/story-block-fix-chrome-1px-border-on-preview, projects/plugins/jetpack/extensions/blocks/story/player/style.scss
Fixes a minor esthetic bug when displaying story previews on chrome.
Sometimes (usually when the image width is not divisible by 180px (the story preview width)), a story would display with a 1px black column on the right side of the image (can also happen at the bottom).
This PR attempts to fix it.
no
* Try creating a story with a rather small image, the issue is also visible on video caption.
You can try this block story template which reproduces the bugs pretty consistently:
```
<div class="wp-block-jetpack-story wp-story"></div>
```
* Test on chrome, try at different width, hover on the story etc, there should be not black lines on the side.
* Make sure there is no regression on mobile
=> Story Block: Use CSS scale3d() instead of scale()

.github/files/check-lock-files.sh, tools/check-composer-deps.sh, tools/composer-update-monorepo.sh
In tools/check-composer-deps.sh and the CI lockfile check, we were using
`composer update --root-reqs` to try to update monorepo packages in
composer.lock.
But that fails to update monorepo packages that are depended on
indirectly. What we need to do is pass the list of all monorepo packages
(and the root reqs) to `composer update` so it can update those and only
those.
Since the code to properly determine that list is somewhat complicated,
let's wrap it in a script.
p1620666192013600-slack-CBG1CP4EN
No
* Create a shallow clone of this PR: `git clone --branch=fix/composer-update-root-reqs --depth=1 git@github.com:Automattic/jetpack.git /tmp/jetpack`
* Change to the clone directory: `cd /tmp/jetpack`
* Bump the version number of packages/status: `composer config …
=> tools: Avoid `composer update --root-reqs` in more places

projects/plugins/jetpack/changelog/update-ensure-correct-mime-type-on-videopress-updates, projects/plugins/jetpack/modules/videopress/class.videopress-xmlrpc.php
This change fixes a case in the Atomic flow where attachments uploaded to a site before it goes atomic would be missing the VideoPress options in the media library video item. This is caused because the `post_mime_type` in wpcom is set to `video/quicktime` instead of `video/videopress` and that metadata is copied over as-is when the site is made Atomic. Other metadata is missing as well in this process, and calling the `jetpack.updateVideoPressMediaItem` xmlrpc function back-fills all of the required metadata except for the mime type, which is what this PR adds. Once this change is released it will allow the fix in D60437-code to set the values correctly on Atomic transfer and back-fill attachments for sites affected by this issue.
* When video meta is updated by a wpcom xmlrpc call, …
=> Ensure VideoPress mime-type is set when updating meta

projects/packages/blocks/CHANGELOG.md, projects/packages/blocks/changelog/add-is-fse-theme-method, projects/packages/blocks/changelog/add-support-hiding-nested-nudges, projects/packages/blocks/changelog/fix-changelogger-in-subdir, projects/packages/changelogger/CHANGELOG.md, projects/packages/changelogger/changelog/add-changelogger-filename-dups, projects/packages/changelogger/changelog/fix-changelogger-in-subdir, projects/packages/changelogger/changelog/fix-changelogger-in-subdir-2, projects/packages/changelogger/src/Application.php
Let's release a new version of the Blocks package so we can benefit from changes that will be needed on WordPress.com.
* N/A
* No
=> Packages: release a new version of Blocks and Changelogger

projects/plugins/jetpack/changelog/update-nav-unification-redirect-flag, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
Fixes Automattic/wp-calypso#51530
* The `is_redirected_domain()` check is too broad for Site Redirect's purposes. We've introduced a new function to check specifically for Site Redirects in D60809-code, and this PR updates the check for the "Redirect" flag in the sidebar on the /wp-admin side.
No
* Apply D60809-code and D61140-code to your sandbox
* Sandbox a test site with a custom domain mapped
* Go to your test site's `/wp-admin`; there should be no "Redirect" flag in the sidebar, as shown above
* Sandbox another site that uses a simple Site Redirect (set up at `/domains/add/site-redirect`)
* Ensure the "Redirect" flag is present in the sidebar as expected
=> Nav Unification: Update site redirect flag function

projects/plugins/jetpack/_inc/client/components/masthead/header-nav.jsx, projects/plugins/jetpack/_inc/client/components/masthead/index.jsx, projects/plugins/jetpack/_inc/client/state/modules/reducer.js, projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php, projects/plugins/jetpack/changelog/fix-settings-access-offline-mode
Fixes #19814
This is a follow-up from #19714.
This PR does 3 things:
1. It refactors / extracts the access check used to add the Settings submenu, so it's more readable now that we have multiple conditions.
2. It adds that submenu when folks use Offline mode.
3. It applies a similar logic (and refactors into its own component to help readability) to the navigation menu that is shown in the Jetpack dashboard pages.
**Note**: there are a number of conditions here, I think I caught them all but would really appreciate if y'all could tell me if things are more readable / easier to understand with this new implementation. If that's only more readable for me, then that's not very useful :) 
* N/A
* No
1. Start with a fresh Jetpack site, not connected to WordPress.com.
1. You should not see the …
=> Admin: ensure Jetpack settings can be accessed in Offline mode.

.github/workflows/e2e-tests.yml
Apparently, scheduled runs weren't working at all. Pobably, GH Actions does not like when matrix defined in runtime is prettified: 
```
Error when evaluating 'strategy' for job 'e2e-tests'. (Line: 41, Col: 18): Error reading JArray from JsonReader. Path '', line 1, position 1.,(Line: 41, Col: 18): Unexpected value ''
```
https://github.com/Automattic/jetpack/actions/runs/838790992 
n/a
n/a
* Impossible to test. Just merge and wait for 12 hours :D  
*
=> E2E Tests: Unprettify `jq` output

projects/packages/connection/changelog/update-filter_remote_register_redirect_uri, projects/packages/connection/legacy/class-jetpack-xmlrpc-server.php, projects/plugins/jetpack/changelog/update-filter_remote_register_redirect_uri, projects/plugins/jetpack/class-jetpack-xmlrpc-methods.php, projects/plugins/jetpack/tests/php/general/test_class.jetpack-xmlrpc-server.php
Part of the Connection Independece efforts.
* Adds a filter to the Remote URI returned by the remote_register XMLRPC method, and move the Jetpack specific modification into the plugin
1199702491434901-as-1199702491434919
No
* Look at the code
* Check the tests are working as expected
=> Add and use filter to remote_register redirect uri

projects/plugins/jetpack/changelog/story-block-fix-video-partial-content-ios, projects/plugins/jetpack/extensions/blocks/story/player/lib/wait-media-ready.js
The [recent work on video loading](https://github.com/Automattic/jetpack/pull/17342) for the story block actually caused a regression on iOS. It seems videos sometimes do not load. In those cases, partial requests are failing and they're  not tried again (it's not clear why as it seems the server is configured correctly for handling partial requests and it's not a cross-origin issue either).
As a result the story appears to be constantly loading:
This change makes sure a failed media is retried.
no
* Apply this patch on a public site
* Publish a story starting with a video
* Access it with an iOS device with either Safari or Chrome
* (Optional: try it on both an iphone and an ipad as safari doesn't have the same permission on each, for instance the fullscreen api is only enabled on ipad) …
=> Story Block: Fix video not loading on safari and Chrome iOS

projects/plugins/jetpack/changelog/update-unify-carousel-js, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js
This updates the Jetpack carousel JS to make it possible to have a single, unmodified JS codebase for the plugin. It shouldn't result in any user-visible changes for Jetpack or wpcom users.
Once Fusion generates a sync diff, I will commandeer it and update it to add the wpcom-specific code that enables this. A draft of that is available at D61295-code.
* Unify carousel JS between Jetpack and wpcom
None.
No.
Smoke-test the carousel and ensure that everything continues to work normally.
=> Unify carousel JS between Jetpack and wpcom

projects/plugins/jetpack/_inc/client/components/navigation-settings/index.jsx, projects/plugins/jetpack/_inc/client/components/navigation-settings/test/component.js, projects/plugins/jetpack/_inc/client/settings/index.jsx, projects/plugins/jetpack/changelog/update-settings-default-non-admin, tools/eslint-excludelist.json
This is a bit of a follow-up to #19815. This PR changes the behaviour of the Settings screen for connected non-admins.
Non-admins currently need access to the Settings screen for 2 reasons:
- Publicize (Sharing tab)
- Post By Email (Writing tab)
Until now, we always defaulted to the Writing tab for connected non-admins. This has 2 problems:
1 - We did not check if the Post By Email module was actually enabled, so when the module was disabled editors loading the settings page would only see a Writing tab and its title, but no content.
2 - Publicize is more popular than Post By Email today, so it's more likely that editors will be interested in the Publicize settings first, even if both PBE and Publicize are enabled.
This PR changes that default behaviour, and introduces checks for the …
=> Admin Page: display Sharing as new default tab for non-admins

projects/github-actions/repo-gardening/changelog/add-cache-repo-gardening-api-calls, projects/github-actions/repo-gardening/src/get-files.js, projects/github-actions/repo-gardening/src/get-labels.js
The Gardening action runs pretty frequently, and each run might check
the list of files twice and the list of labels 12 times. We can reduce
our API calls by caching the lists so subsequent calls to getFiles or
getLabels don't re-fetch them.
Related to p1620322922356800/1620320214.350000-slack-CBG1CP4EN
No.
* Check the runs for the Gardening workflow on this PR. Does it report using the caches?
=> repo-gardening: Cache label and files API calls

projects/packages/connection-ui/changelog/update-connection-ui-hook-docblock, projects/packages/connection-ui/src/class-admin.php
* Quick follow up to https://github.com/Automattic/jetpack/pull/19820 to add a DocBlock for the `jetpack_on_connection_ui_init` hook.
* No.
* Proofread the change.
=> DocBlock for `jetpack_on_connection_ui_init` hook

projects/plugins/jetpack/changelog/fix-jetpack-admin-menu-customize, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-jetpack-admin-menu.php
This PR fixes a minor bug in the admin menu class used for Jetpack sites which prevented the Appearance submenu from being registered correctly. 
With this bug fixed, we'll finally be able to use the new sidebar component in Calypso for Jetpack sites, avoiding the current UI inconsistency when switching from a WP.com site to a Jetpack and vice versa. See https://github.com/Automattic/wp-calypso/pull/52871.
N/A.
No.
- Go to the [WP.com API console](https://developer.wordpress.com/docs/api/console/).
- Select `WP REST API` and `wpcom/v2`.
- Make a `GET` request to `/sites/:site/admin-menu`.
- Make sure there are 2 submenu items under the Appearance menu item.
Before | After
--- | ---
=> Admin Menu: Fix Appearance submenus on Jetpack sites

projects/plugins/jetpack/changelog/e2e-fix-slack-notification-for-scheduled-jobs, projects/plugins/jetpack/tests/e2e/bin/slack.js
Fixes failing Slack notification for scheduled jobs. 
In case of scheduled jobs the event.json file doesn't provide an html_url property for repository making the slack script fail.
1156386383419466-as-1200337431330111/f
no
* Hard to test until the next scheduled Gutenberg job will run.
=> E2E tests: Slack notification missing html_url for scheduled jobs

projects/plugins/jetpack/changelog/fix-related-posts-customizer, projects/plugins/jetpack/modules/related-posts.php
Internal reference: 6646-gh-jpop-issues
In some specific edge-cases (most likely triggered by specific plugins), WP_Customize_Manager may be loaded, but not the accompanying WP_Customize_Control. Let's avoid fatals by only loading our Customizer-related classes when the classes already exist.
* Internal reference: 6646-gh-jpop-issues
* No
I'm still unclear on how to reproduce the issue, but we should be able to check that this doesn't break the feature.
* Go to Jetpack > Settings and enable Related Posts
* Go to site's home page
* Click on Customize link in the admin bar.
* Click on the Related Posts tab and see the invitation to visit a single post.
* Click on a single post and see the Related Posts option.
=> Related Posts: avoid fatals when class is missing

projects/plugins/jetpack/changelog/try-add-height-related-posts, projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php, projects/plugins/jetpack/modules/related-posts/related-posts.js
Fixes #19840
We already know the image height since we define it ourselves and resize the images with Photon. Let's add the height attribute to the image tags for each set of related posts (whether at the bottom of a post or within a block).
* N/A
* No
* Start on a connected site where Related posts are active and where you've already got some related posts displayed and working well.
* Apply branch.
* All images should be displayed nicely without being distorted.
=> Related Posts: add height attribute to post images

projects/packages/jitm/changelog/update-remove_constants, projects/packages/jitm/composer.json, projects/plugins/jetpack/changelog/update-remove_constants, projects/plugins/jetpack/composer.lock
* The JITM package doesn't depend on the `jetpack-constants` package so remove it from JITM's `composer.json` file.
* Put the dependencies in alphabetical order.
* n/a
* no
* No testing required.
* Review the JITM package and verify that the jetpack-constants package is not used.
* Note that the `jetpack-constants` package is required by other packages that JITM depends on, so the `jetpack-constants` package will still be installed in JITM's vendor directory if `composer install` is run on the JITM package.
=> JITM: remove the jetpack-constants dependency from composer.json

tools/cli/commands/changelog.js
* Ensures that composer.json has an extra section before reading it.
n/a
no
* Modify files in js-packages/connection
* Run `jetpack changelog add`
* Before patch, see error. After patch, see it work.
The js-packages/connection does not (yet) have an extra section since the mirror repo does not yet exist.
=> CLI: Ensure extras section of composer exists for Changelog

projects/packages/jitm/changelog/update-use_action_in_jitm, projects/packages/jitm/src/class-jitm.php, projects/packages/jitm/tests/php/test_JITM.php, projects/plugins/jetpack/changelog/update-use_action_in_jitm, projects/plugins/jetpack/composer.lock
* We're currently using a class property to prevent JITMs from being registered multiple times. Let's use an action instead, similar to the approach used in #19820 .
* n/a
* no
1. Install and activate the this branch of Jetpack.
3. Add this code in a snippet (you can use something like the Code Snippets plugin if you'd like):
`( new \Automattic\Jetpack\JITMS\JITM() )->configure();`
4. Open your browsers inspector.
5. Navigate to an admin page and search the network requests for jitm. You should see one request to the `wp-json/jetpack/v4/jitm endpoint`.
=> JITM: use an action to prevent JITMs from being registered multiple times

projects/plugins/jetpack/_inc/client/components/non-admin-view/index.jsx, projects/plugins/jetpack/changelog/fix-redirect-non-admins-dashboard
﻿This was brought up and explained by @sdixon194 here:
https://github.com/Automattic/jetpack/pull/19838#pullrequestreview-660018127
When an admin enters a non-existing route in the Jetpack dashboard, we show them the At A Glance component and update the URL accordingly.
We did not update the URL for non-admins. This commit should fix that.
* N/A
* No
* Start with a site that's connected to WordPress.com, and 2 users connected to WordPress.com; an admin and an editor.
* Log in as the editor.
* Go to Jetpack > Dashboard, or Jetpack > Settings if you have access to it (Post By Email or Publicize are active)
* Manually update the URL to `admin.php?page=jetpack#/foobar` for example, or to `admin.php?page=jetpack#/admin.php?page=jetpack#/security`.
* You should see the At A Glance UI appear in …
=> Dashboard: redirect non-admins to dashboard hash when needed

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php, projects/plugins/jetpack/changelog/fix-site-only-connection-owner
If user token is not present, but the connection owner option is set to the current user, Jetpack Dashboard will occasionally handle the current user as connection owner.
This PR will only set the `isMaster` initial state value to `true` if the user is connected.
* Correctly display connection owner information if user token is missing, but connection owner option is set.
No.
1. Fully connect Jetpack.
2. Use the "Broken Token" tool to remove user tokens. Make sure to keep the "Primary User" value intact.
3. Go to Jetpack Dashboard, scroll down to the "Connections" cards, and confirm that the connection owner information is displayed correctly.
**Before:**
**After:**
=> Site-only Connection: Fix the connection owner info card

projects/plugins/jetpack/changelog/fix-undefined-upgrade-nudge-attribute, projects/plugins/jetpack/class.jetpack-gutenberg.php
Related #19407
* Checks whether the `shoudlDisplayFrontendBanner` attribute is set before checking value to avoid php errors.
* Testing instructions in #19407 
* Insert a paid block on a site with a free plan and observe the upgrade nudge. Open the post in the frontend and you should see the frontend nudge. Inspect error logs for errors.
=> Upgrade Nudge: Check for undefined attribute

projects/plugins/jetpack/changelog/update-simple-and-atomic-plan-parity, projects/plugins/jetpack/class.jetpack-gutenberg.php, projects/plugins/jetpack/extensions/shared/plan-utils.js, projects/plugins/jetpack/jetpack.php
Fixes https://github.com/Automattic/jetpack/issues/19498
This PR adds the features availability logic according to the site plan for Atomic sites.
No
* Apply the patch
* Get sandboxed
* Start to edit a post
* Nothing should change here. For sites with a `free` plan and paid blocks, you should see the upgrade banner:
block | Free plan | Paid plan
------|------|------
Donations | ![image](https://user-images.githubusercontent.com/77539/117493917-00c0ad00-af4a-11eb-97cf-f72ebfd4d467.png) | ![image](https://user-images.githubusercontent.com/77539/117492769-74fa5100-af48-11eb-8e14-1aaa0a0e401b.png)
Payments | ![image](https://user-images.githubusercontent.com/77539/117494013-1df57b80-af4a-11eb-90df-ac3d2fc3b8ce.png) | ![image](https://user-images.githubusercontent.com/77539/117492928-aa9f3a00-a …
=> Enable upgrade banner for WoA sites

projects/packages/sync/changelog/fix-notice-sync-queue-buffer, projects/packages/sync/src/class-queue-buffer.php, projects/packages/sync/src/class-sender.php
﻿
`array_combine()` can return false if the number of elements for each array isn't equal.
Let's take that into account to avoid PHP notices like this:
* File
/home/wordcamp/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-sender.php:422
* Stack Trace
shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Sync\Sender->do_sync, Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays, Automattic\Jetpack\Sync\Sender->do_sync_for_queue, Automattic\Jetpack\Sync\Sender->get_items_to_send, WordCamp\Error_Handling\handle_error, WordCamp\Error_Handling\send_error_to_slack
* N/A
* No
* Not much to test here, tests should still pass.
=> Sync: avoid PHP notices in some edge-cases

projects/plugins/jetpack/changelog/remove-feedback-export-csv-submenu, projects/plugins/jetpack/modules/contact-form/admin.php, projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-p2-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/52661
Removes the "Feedback > Export CSV" submenu entry. The export functionality is still available in "Feedback > Form responses". This aligns the behavior with WordPress.com Simple sites, which currently don't register this submenu.
N/A.
No.
- Make sure the "Feedback" menu does not contain the "Export CSV" submenu.
- Go to "Feedback > Form responses".
- Make sure the "Export CSV" functionality appears when there are form responses.
- To submit a form response, follow the steps below:
- Go to Posts > Add new.
- Insert a Form block and publish the post.
- Visit the published post.
- Fill the form and submit the data.
- Make sure the "Form responses" submenu displays the count of unread form responses.
=> Feedback: Remove "Export CSV" submenu

projects/plugins/jetpack/changelog/update-priority-for-unified-nav-styles, projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-base-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Fixes alignment issues noted here p58i-axR-p2#comment-50605
* Fixes Gutenberg widget styles loading after the nav unification override styles by increasing the priority
Firstly enable the Widgets Editor by following the instructions here p58i-axR-p2
**Simple sites**
* Apply diff to your Sandbox and ensure Sandboxing is enabled.
* Follow the steps in the P2 above to enable the feature
* Go to Appearance > Widgets or `/wp-admin/themes.php?page=gutenberg-widgets`
**Atomic sites**
* Install Jetpack Beta and activate this branch
* Follow the steps in the P2 above to enable the feature
* Go to Appearance > Widgets or `/wp-admin/themes.php?page=gutenberg-widgets`
<table>
<tr>
<td>**Before**</td>
<td>**After**</td>
</tr>
<tr>
<td><img width="1791" alt="Screenshot 2021-05-19 at 13 37 08" …
=> Update Nav Unification styles priority

projects/plugins/jetpack/changelog/story-block-fix-css-button-outline, projects/plugins/jetpack/extensions/blocks/story/player/style.scss
This is a very minor fix that prevents CSS conflicts with some themes used on WPCOM such as [Libretto](https://wordpress.com/theme/libretto).
WPCOM currently doesn't support shadow DOM as we bundle all our scripts and CSS together. As such we have some CSS conflicts on some themes. This is an attempt to fix one type of CSS conflict.
A more general approach should be taken to bring back shadow dom to WPCOM by excluding the story block styles and JS from the bundling logic (see D48402-code).
An even more general approach would be to serve stories from iframes. This is a much larger project and will be tackled at some point in the future.
CSS rule added in story css file
no
* Create a story on a site that uses the Libretto theme
* Make sure the button outline is not visible
=> Story Block: prevent CSS conflicts by making sure buttons don't have outlines

projects/packages/connection/changelog/fix-disconnect-user-wpcom, projects/packages/connection/src/class-manager.php, projects/packages/connection/tests/php/test_Manager_integration.php, projects/packages/connection/tests/php/test_Manager_unit.php, projects/plugins/jetpack/changelog/fix-disconnect-user-wpcom, projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php
Fixes #19857
* With this PR, we now attempt to make the request to disconnect the user from WordPress.com before we delete the connected data locally. This should fix the problem outlined in #19857.
* N/A
* No
1. Start with a site connected to WordPress.com, with 2 connected users: an admin (primary user for the connection) and an extra user.
2. At this point, when looking at your `user_tokens` Jetpack option, you'll see the 2 entries, one for each user id.
3. While logged in as the primary admin, go to Users in wp-admin
4. Delete the other user.
5. Find the cache site in Network admin.
6. Ensure the wpcom user linked to the local user you just deleted got removed from Network admin.
=> Connection: disconnect user from wpcom before to do so locally

projects/github-actions/repo-gardening/CHANGELOG.md, projects/github-actions/repo-gardening/changelog/add-cache-repo-gardening-api-calls, projects/github-actions/repo-gardening/changelog/add-sync-package.json-engines, projects/github-actions/repo-gardening/changelog/fix-changelogger-in-subdir, projects/github-actions/repo-gardening/changelog/renovate-actions-core-1.x, projects/github-actions/repo-gardening/changelog/renovate-vercel-ncc-0.x, projects/github-actions/repo-gardening/changelog/renovate-vercel-ncc-0.x#2, projects/github-actions/repo-gardening/changelog/update-docs-changelogger-in-monorepo, projects/github-actions/repo-gardening/changelog/update-repo-gardening-labels-boost, projects/github-actions/repo-gardening/package.json
* release a new version of the action for use by third-parties.
* I am especially interested in getting #19891 to be available for the Jetpack Boost repo.
N/A
No
Check for typos
=> Repo gardening: release new version of the action

projects/plugins/jetpack/changelog/Update masterbar write button URL, projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php
Fixes https://github.com/Automattic/wp-calypso/issues/51639
* Always use WP Admin block editor for Atomic or Jetpack Users.
* Load `update/masterbar-write-button-destination` in your Jetpack Beta Atomic site.
* Load `/wp-admin`
* Click "Write" in the masterbar
* You should land in WP Admin Block Editor
=> Update masterbar write button URL

projects/github-actions/repo-gardening/changelog/fix-boost-module-name, projects/github-actions/repo-gardening/package.json, projects/github-actions/repo-gardening/src/tasks/add-labels/index.js
Follow-up from #19891.
We do not need a [Block] prefix for Boost labels.
* No
* No
* Not much to test here, just fixing a mistake I did yesterday.
=> Repo Gardening: remove Block prefix for Boost labels

projects/plugins/jetpack/changelog/fix-help-icons-overlap, projects/plugins/jetpack/modules/masterbar/inline-help/class-inline-help.php
Fixes 73-gh-Automattic/wordpress-seo-premium
* Hide the FAB icon on Yoast admin pages to avoid overlap with the Yoast help icon
73-gh-Automattic/wordpress-seo-premium
Nope.
* Go to a free Atomic site with the Yoast plugin installed and activated.
* Go to /wp-admin/admin.php?page=wpseo_dashboard
* Without this change, the two icons overlap:
* With this change, only the Yoast icon is visible.
=> WP.com Toolbar: Hide the FAB icon on Yoast admin pages

tools/check-composer-deps.sh
When running `tools/check-composer-deps.sh -u`, it errors with "Directory plugins/beta not found".
This appears to be due to the `check_dir` that is being ran within the `tools/composer-update-monorepo.sh` not passing the full slug over.
Not fully tested, but wanted to open it up for testing and discussion.
* Pass the full dir
Slack: p1621617579169200-slack-CBG1CP4EN
No.
* ./tools/check-composr-deps.sh -uv
*
=> Tools: Pass full dir in check-composer-deps

projects/plugins/jetpack/changelog/update-p2-hide-email-plan-link, projects/plugins/jetpack/modules/masterbar/admin-menu/class-p2-admin-menu.php
For P2 sites, hide the admin bar link to email plans.
See 2674-gh-Automattic/p2
* Hides the admin bar link to the paid upgrade for emails.
no
* On a P2 hub, verify that the admin menu does not have a submenu item under "Upgrades".
=> Hide admin menu link to plans email for P2s

projects/plugins/jetpack/changelog/add-disable-edit-and-delete-on-posts-page, projects/plugins/jetpack/modules/masterbar.php, projects/plugins/jetpack/modules/masterbar/wp-posts-list/bootstrap.php, projects/plugins/jetpack/modules/masterbar/wp-posts-list/class-posts-list-page-notification.php, projects/plugins/jetpack/modules/masterbar/wp-posts-list/wp-posts-list.css, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-posts-list-page-notification.php
Disables editing and deleting capabilities in WP-Admin Post list for the page that is configured as a Posts Page in WP-Admin.
Fixes https://github.com/Automattic/wp-calypso/issues/52692
* Removed the edit_post and delete_post capabilities for all users for the page is configured as a Posts page in WP-Admin. 
* Added an info icon for informing the user why the page cannot be edited or deleted.
No
* Install Jetpack Beta plugin and switch to the current branch.
* Make sure that you have a Posts Page configured for your site (Configurable in Settings > Reading section). 
* Go to WP-Admin > Pages section
* Make sure that the page configured in the second step cannot be edited and deleted
* Make sure that the page has an info icon with a `title` informing why the page cannot be edited or …
=> Disabled editing and deleting capabilities in WP-Admin Post list for Posts Page

projects/plugins/jetpack/changelog/update-carousel-improvement-batch-2, projects/plugins/jetpack/modules/carousel/jetpack-carousel.css, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js
This is the second batch of improvements to carousel, building upon #18858 and more recent changes such as #19843.
This batch of improvements focuses on reorganising the codebase and preparing for future work that removes the dependency on `jQuery`.
- Stop implementing the carousel as a `jQuery` extension.
Beyond locking us into `jQuery`, this was unnecessary and confusing, given that there is only ever one instance of a carousel on the page.
- Reimplement all jQuery extension functionality as plain old functions.
- Reimplement touchwipe as a plain function
- Rename functions to follow proper naming conventions and be more descriptive of their behaviour.
- Use a flag to enable and disable keyboard bindings instead of binding and unbinding the listeners all the time.
- Standardise …
=> Second batch of improvements to Carousel

projects/plugins/jetpack/changelog/update-videopress-use-block-props, projects/plugins/jetpack/extensions/blocks/videopress/edit.js, projects/plugins/jetpack/extensions/blocks/videopress/save.js
Fixes #18864 
* extracts the video player portion of the rendered component into a function component so the `useBlockProps` hook can be called
* Ensure you have a Jetpack site with VideoPress enabled
* Prior to pulling PR, create a post and add a video block (it may be unclickable and very wide, this PR will fix that)
* Apply the PR
* Refresh the post and the videoblock should still work
* Add a new video block, it should render as expected
* Ensure all video block interactions continue to work as expected
=> Update VideoPress block for `useBlockProps`

projects/packages/sync/changelog/fix-sync-endpoints-get-sync-object-return-multiple-meta-values, projects/packages/sync/src/modules/class-meta.php, projects/plugins/jetpack/changelog/fix-sync-endpoints-get-sync-object-return-multiple-meta-values, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-meta.php
When we built the endpoint, we worked under the assumption that we'll be fetching only single meta entry per object/key pair. We now need to fetch all the entries under the object/key pair.
* Return multiple Meta entries per object/key pair.
This is a continued effort in bringing improved alignment between the Jetpack site and the WordPress.com cache.
Doesn't add any additional data or activity we track or use.
* Apply PR
* Apply D61787-code
* Run a checksum and fix for `postmeta` for your test site
* Add additional entries for meta for a `post` with the same key, e.g. `_wp_attached_file`
* Run checksum and fix again
* Make sure all the entries were synchronized over
=> Jetpack Sync: Fix: Get Sync Objects endpoint - Meta - return multiple meta values

projects/plugins/jetpack/changelog/fix-posts-page-icon, projects/plugins/jetpack/modules/masterbar/wp-posts-list/bootstrap.php, projects/plugins/jetpack/modules/masterbar/wp-posts-list/class-posts-list-page-notification.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-posts-list-page-notification.php
Fixes https://github.com/Automattic/wp-calypso/issues/53167
* Removed the restriction from post.php page, in order to reduce the impact.
* Handled a scenario where the posts page and the home page can point to the same page id - even though on WP-Admin interface from options-reading.php the posts page dropdown is reset when the home page dropdown contains the same page.
* Disabled the feature when "Your homepage displays" option is configured with "Your latest posts"
No
* Apply the patch D61984-code on your sandbox
* Go to wp-admin/options-reading.php, set "Your homepage displays" to "a static page" and select the same page in "Homepage" and "Posts Page" dropdowns.
* Click save and you'll notice that the "Posts page" dropdown is empty again. Internally the site option was set.
* Go to …
=> Fixed regression introduced in posts page icon notification in WP-Admin edit.php page

projects/plugins/jetpack/changelog/update-p2-admin-menu-items-hide, projects/plugins/jetpack/modules/masterbar/admin-menu/class-p2-admin-menu.php
1. On **P2 hubs**, we are hiding admin menu items that would be confusing or don't apply.
- Posts
- Pages
- Media
- Comments
- Statistics
- Jetpack
- Appearance
- Tools
- P2Editor
2. On P2 **workspace sites** we are hiding a few menu items:
- Jetpack -> Backup
- All under “Appearance” except “Customise”.
Note that this only hides the items in Calypso in most cases. See `2887-gh-Automattic/p2` and `2888-gh-Automattic/p2`.
* Hiding the menu items.
* Hubs and spaces now have distinct functions that hide menu items for them.
* Added slugs as class variables so they can be shared between functions.
No.
* Go to a P2 hub and verify that the menu items in the first list above are hidden.
* Go to a P2 workspace site and verify that the menu items in the second list above are hidden.
=> Conditionally hide admin menu items for P2 hubs/spaces

projects/plugins/jetpack/changelog/fix-9.8-story-block-notice-message, projects/plugins/jetpack/extensions/blocks/story/story.php
Fixes https://github.com/Automattic/jetpack/issues/19947
This PR fixes a notice message showing up in `story.php`.
no
* Create a story block on a local site (not connected to WPCOM)
* Render the post
* Check the logs in wp-content, there should be no notice message
=> Story Block: Fix Notice: Undefined variable: poster_url

projects/plugins/jetpack/changelog/fix-unneeded-phpcs-ignore, projects/plugins/jetpack/class.jetpack.php
A comment on another PR where someone almost added an unnecessary
`phpcs:ignore MediaWiki.Classes.UnusedUseStatement.UnusedUse` made me
wonder if we had done that anywhere else.
I found only one, and removed it. I also cleaned up the unused variable
so the other sniff no longer needs ignoring on that line either.
None
No
* I guess make sure the code still works. I can't see how it wouldn't though.
=> Remove an unneeded phpcs:ignore

projects/plugins/jetpack/changelog/story-block-fix-muted, projects/plugins/jetpack/extensions/blocks/story/player/store/constants.js, projects/plugins/jetpack/extensions/blocks/story/player/store/effects.js
Fixes https://github.com/Automattic/jetpack/issues/19948
This PR fixes the mute button which was not working when playing a story
no
* Play a story containing a video
* Toggle the mute button several times
* Make sure it mutes and unmutes the video as expected each time.
=> Story Block: Fix syncing muted state

projects/plugins/backup/changelog/update-backup-plugin-rna-connection, projects/plugins/backup/composer.lock, projects/plugins/backup/src/js/actions/connection-status.js, projects/plugins/backup/src/js/actions/index.js, projects/plugins/backup/src/js/hooks/useConnection.js, projects/plugins/backup/src/js/reducers/connection-data.js, projects/plugins/backup/src/js/reducers/connection-status.js, projects/plugins/backup/src/js/selectors/connection-data.js, projects/plugins/backup/src/php/class-initial-state.php
* Update RNA Connection usage based on the changes made in: Automattic/jetpack/pull/19837
* N/A
* No.
*   Check out these changes to your local monorepo dev environment.
*   You can build the Backup plugin with the Jetpack CLI: `jetpack build`
*   Deactivate the Jetpack plugin (we don't want a connection to start with) and make sure the Jetpack Backup plugin is activated.
*   Check to make sure you see the `Connection Manager` as a submenu under Tools (but don't connect there).
*   Go to the Backup plugin admin page: `/wp-admin/admin.php?page=jetpack-backup`
*   Click on the Connect button, after a moment the site connection will be made and an iframe shown with an Approve button for making the user connection. Once both connections are made you should see `Site and User Connected` at the …
=> Backup Plugin: update RNA Connection usage

projects/packages/connection/changelog/fix-use-santized-variable, projects/packages/connection/src/class-manager.php
In #19833 we added a new check on the registration flow that expects a new key in the register response sent by WPCOM.
We made sure to check if the new key is present to avoid errors, but we forgot to use the variable a few lines later! This PR fixes it.
* Fixes a variable usage
N/A
No
* Nothing really, but you can check if the registration process works.
=> Uses the sanitized variable

.github/workflows/e2e-tests.yml, projects/plugins/jetpack/changelog/fix-e2e-tunnel-logs-pnpm-run, projects/plugins/jetpack/tests/e2e/package.json
The command that writes tunnel logs to file in e2e tests workflow got broken with the migration from yarn to pnpm.
n/a
no
* CI green, no errors reported in E2E tests workflow. `e2e/output/logs/tunnel.log` gets created and is not empty.
=> E2E tests: Fix for tunnel logs not being written to file

projects/plugins/jetpack/changelog/update-fix-carousel-info-pos, projects/plugins/jetpack/modules/carousel/jetpack-carousel.css, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js
Fixes carousel info position, so that more of it is visible without scrolling down.
Fixes #19969.
* Fix carousel info position
None.
No.
See the instructions in #19969.
=> Carousel: fix photo info position

projects/plugins/jetpack/changelog/update-client-lock-autoupdates, projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php, projects/plugins/jetpack/tests/php/json-api/test-class.json-api-plugins-endpoints.php
It is possible for Core and Jetpack update processes to run in parallel. This update has Jetpack obtain the auto-updater lock before attempting to perform updates.
* Obtain lock before attempting to perform updates.
See https://wp.me/p9o2xV-1s0
* NO
Unit Test added to show behavior. 
Manual Testing can be done by openning wp shell on your test site and running
```
include_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
WP_Upgrader::create_lock( 'auto_updater' );
```
to obtain a lock. Afterwards trigger the plugin update and confirm a WP_Error is returned.
=> Client Side lock to ensure Jetpack and Core autoupdate don't run simultaneously

tools/docker/mu-plugins/01-monorepo.php
Error only occured on a logged-in view while visiting the **frontend** of
the local Docker site exposed via JT. Error did not happen on logged out
views, or if visiting the site at localhost (not using JT).
```
Fatal error: Uncaught Error: Call to undefined function
Jetpack\Docker\MuPlugin\get_plugin_data() in
/var/www/html/wp-content/mu-plugins/01-monorepo.php on line 128
```
Requiring `wp-admin/includes/plugin.php` as a quick fix.
* Internal: p1622833970293800-slack-CBG1CP4EN
* No.
* Before pulling down changes, see if you can reproduce the fatal by visiting your local Docker site exposed via JT.
* After pulling down these changes, I was no longer seeing the fatal error.
=> Docker: fix frontend fatal when using JT

projects/plugins/jetpack/changelog/fusion-sync-fullofcaffeine-r226957-wpcom-1623188698, projects/plugins/jetpack/modules/theme-tools/site-logo/inc/functions.php
Summary:
Resolves 53517-gh-wp-calypso and supports #19654
Implementation by @creativecoder.
Code recently added to Gutenberg syncs site_logo options and custom_logo theme mod. This causes a conflict with the legacy Jetpack site logo functionality.
This is an initial fix--we'll need to follow up to reconcile the new site_logo option and Jetpacks legacy logo functionality.
Related convo: p1623174912090300-slack-CBTN58FTJ.
Test Plan:
- Sandbox a Simple Site
- Activate a theme that uses `jetpack_the_site_logo` to display a logo, such as premium/soho (`wp theme activate premium/soho --url=[private link]`)
- Navigate to the customizer, set a logo, and save the changes
- Without this change, the logo does not display
- With this change, the logo should display
Reviewers: paulbunkham, kraftbj, …
=> Jetpack Site Logo: add integer check for custom_logo

.github/files/setup-wordpress-env.sh, .phpcs.config.xml, projects/plugins/backup/changelog/bump-to-5.7, projects/plugins/backup/readme.txt, projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php, projects/plugins/jetpack/changelog/bump-to-5.7, projects/plugins/jetpack/jetpack.php, projects/plugins/jetpack/modules/shortcodes/instagram.php, projects/plugins/jetpack/readme.txt, tools/cli/commands/generate.js
- Bump minimum supported/tested version to 5.7/5.8
- Remove Instagram oembed removal. Ref #19736
See #19654
* Bump versions.
* Remove Instagram code
* More coming.
See 19654
n/a
* Running WP 5.7 or 5.8, test an Instagram embed.
*
=> General: Basic updates to prepare for WP 5.8

.github/workflows/e2e-tests.yml, projects/plugins/jetpack/changelog/e2e-e2e-test-report-send-pr-info
Send more information about the tested PR in request to test reporter. 
- added PR title
- use PR title as event name
1156386383419466-as-1200453732403160/f
no
* CI green. Test report workflow is triggered with correct information in `automattic/jetpack-e2e-reports`
=> E2E test reports: send more information about pr to test report

tools/docker/Dockerfile
Our Dockerfile was set to use `xenial`, 16.04 LTS, which is now EOL. Updating to the latest LTS release.
Funny part is I even RT'd this from the maintainer of the PHP packages we use, yet was still wondering why the docker build failed for me...
https://twitter.com/oerdnj/status/1401670677376159745
* Update to Ubuntu 20.04 LTS.
n/a
No
* Run various docker commands and confirm that we're still in business.
*
=> Docker: Bump Ubuntu to 20.04 LTS

projects/plugins/jetpack/changelog/fusion-sync-scruffian-r227092-wpcom-1623406878, projects/plugins/jetpack/modules/shortcodes/inline-pdfs.php, projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.inline-pdf.php
Summary: Some themes set a height for object elements, but we always want these ones to be 800px high.
Test Plan: See 1919-gh-themes
Reviewers: #themes_team, lance, jeffikus
Reviewed By: #themes_team, jeffikus
Subscribers: jeffikus
Differential Revision: D62535-code
This commit syncs r227092-wpcom.
Fixes #
Some themes set a height for object elements, but we always want these ones to be 800px high.
No
See https://github.com/Automattic/themes/issues/1919
=> Inline PDFs: Fix height to overcome theme specific CSS.

projects/plugins/jetpack/changelog/fix-activecampaign-js-error, projects/plugins/jetpack/tools/webpack.config.extensions.js
Fixes #17289
- Adds a custom setting for `output.jsonpFunction` to the webpack configuration for building extensions
- This prevents conflicts in the default `webpackJsonp` JavaScript global when other WordPress plugins also load JavaScript built with webpack
See https://v4.webpack.js.org/configuration/output/#outputjsonpfunction for more information about the webpack configuration.
N/A
No.
I've only been able to replicate #17289 with the release build of Jetpack, not in development environments, so I'm not sure how to test that this definitely fixes the issue.
But more generally, you can test by
1. Build Jetpack extensions with `jetpack build plugin` and select `jetpack`.
1. Load a post or page in the editor with your local Jetpack development site. Look at the output JS for extensions …
=> Extensions: update webpack configuration to prevent plugin conflicts

projects/packages/connection/changelog/update-move-connection-owner-endpoint, projects/packages/connection/src/class-manager.php, projects/packages/connection/src/class-rest-connector.php, projects/packages/connection/tests/php/test-rest-endpoints.php, projects/packages/connection/tests/php/test_Manager_unit.php, projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php, projects/plugins/jetpack/changelog/update-move-connection-owner-endpoint, projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php
This PR moves the `connection/owner` endpoint from the Jetpack plugin to the Connection package.
* Moves the `connection/owner` endpoint for updating the connection owner to the Connection package
* Introduces the `update_connection_owner` method in `Manager` as this is considered business logic, keeping the endpoint callback thiner.
* Updates the existing logic by only refreshing the `master_user` option when the corresponding remote call to WPCOM is successful. This will ensure consistency between the local and remote connection owner.
1191179647901802-as-1200454472172402/f
No
The easiest way to test this would be via the newly "Connected Admins" functionality introduced in the Jetpack Debugger:
- Spin up a new JN site
- Connect 2 admin users
- Go to the Debugger and click the "Make …
=> Connection: Move 'connection/owner' endpoint to Connection

projects/plugins/jetpack/changelog/add-yt-t-arg, projects/plugins/jetpack/modules/shortcodes/youtube.php, projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.youtube.php
Note: This merges into the embed double-quote branch to prevent merge conflict.
Fixes situation where an URL like https://youtu.be/o-IvKy3322k?t=10683 does not render as an embed that starts at the expected timestamp.
* Handles t values whether it is in seconds or "mixed" (`2m30`).
p1623433589233700-slack-C029LRAU2
No.
* Unit Tests
* Connected Jetpack, enable the Shortcodes module so Jetpack takes over YouTube oembed from Core.
* Insert https://youtu.be/o-IvKy3322k?t=10683 to a post. Before this patch, it'll start at 0:00. After, it'll start at the proper time.
=> Shortcodes: YouTube: Correctly handle t value as seconds

.github/files/build-all-projects.sh, .github/files/check-lock-files.sh, .github/files/check-monorepo-package-repos.sh, .github/files/list-changed-projects.php, .github/files/renovate-helper.sh, .github/files/require-change-file-for-touched-projects.php, tools/check-composer-deps.sh, tools/check-copied-files.sh, tools/cli/commands/clean.js, tools/git-hooks/post-merge-checkout-hook.sh, tools/git-hooks/pre-commit-hook.js
Otherwise git will quote and escape filenames that include Unicode,
which generally isn't what our scripts are expecting.
See https://github.com/Automattic/jetpack/pull/20085/checks?check_run_id=2834404562#step:9:27 for an example of what this fixes.
None
No
* Is CI happy?
* Do the scripts work if you arrange for them to work on files with Unicode in their names?
=> tools: Set `-c core.quotepath=off` to various git diff, ls-files, and check-attr

projects/packages/sync/changelog/add-constants-get-objects-by-id, projects/packages/sync/src/modules/class-constants.php, projects/plugins/jetpack/changelog/add-constants-get-objects-by-id, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-constants.php
This update allows us to expand the checksum process so that we ensure constants are always in sync. It implements get_objects_by_ids and get_object_by_id for the Constants module that allows for us to retrieve the current value on demand. Pulled constants are limited to the allowed Sync constants.
Expand sync/object endpoint to include retrieval of constants.
No constants are already retrievable via a Full Sync this simply exposes a new endpoint to request the data.
1) Access shell on your WP.com sandbox
2) $jsm = new Jetpack_Sync_Manager( get_current_blog_id() );
3) $jsm->get_sync_objects( 'constants', 'constant', array( 'all' ) );
4) Verify that constants are retrieved
5) $jsm->get_sync_objects( 'constants', 'constant', array( 'blue-bird' ) );
6) Verify that empty array is returned
7) …
=> Allow for constants to be retrieved by the sync/object endpoint

projects/packages/sync/changelog/add-themes-get-objects-by-id, projects/packages/sync/src/modules/class-themes.php, projects/plugins/jetpack/changelog/add-themes-get-objects-by-id, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-themes.php
This update allows us to expand the checksum process so that we ensure theme-info is always in sync. It implements get_objects_by_ids for the Themes module that allows for us to retrieve the current value on demand.
Expand sync/object endpoint to include retrieval of theme-info.
No
1) Access shell on your WP.com sandbox
2) $jsm = new Jetpack_Sync_Manager( get_current_blog_id() );
3) $jsm->get_sync_objects( 'themes', 'theme-info', array( ) );
4) Verify that theme-info is retrieved
```
array(1) {
[0]=>
array(4) {
["name"]=>
string(17) "Twenty Twenty-One"
["version"]=>
string(3) "1.3"
["slug"]=>
string(15) "twentytwentyone"
["uri"]=>
string(45) "https://wordpress.org/themes/twentytwentyone/"
}
}
```
=> Allow for theme-info to be retrieved by the sync/object endpoint

projects/packages/sync/changelog/add-updates-get-objects-by-id, projects/packages/sync/src/modules/class-updates.php, projects/plugins/jetpack/changelog/add-updates-get-objects-by-id, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-updates.php
This implements get_objects_by_ids and get_object_by_id for the Updates module that allows for us to retrieve the current value on demand.
Expand sync/object endpoint to include retrieval of updates.
No 
1) Access shell on your WP.com sandbox
2) $jsm = new Jetpack_Sync_Manager( get_current_blog_id() );
3) $jsm->get_sync_objects( 'updates', 'update', array( 'all' ) );
4) Verify that updates are retrieved
5) $jsm->get_sync_objects( 'updates', 'update', array( 'blue-bird' ) );
6) Verify that empty array is returned
7) Specify 'plugins', 'core', 'themes'  for ids and verify they are returned.
=> Allow for updates to be retrieved by the sync/object endpoint

projects/plugins/jetpack/changelog/kraftbj-patch-2-autoupdate, projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
Fixes p9dueE-340-p2
* Only check autoupdate requirements if it is an autoupdate attempt.
p1623790405112000-slack-CBG1CP4EN
No.
* Try upgrading a plugin via the mobile app ( see p9dueE-340-p2 )
* Separately, mark a plugin as autoupdatable, and ensure there is a new version (manually lower the version if needed). Does it still autoupdate correctly?
=> Plugin API: Only use should_update if we are trying to autoupdate

projects/plugins/beta/changelog/update-beta-no-jetpack-dev, projects/plugins/beta/class-jetpack-beta-admin.php
If the Jetpack plugin is active (in the 'jetpack' directory) and there is not a beta version yet downloaded (thus the `jetpack-dev` directory does not exist), the Beta plugin will fatal due to the inability to include the markdown directory.
We'll need to soon probably package Markdown processing within the beta plugin itself to make it usable for non-Jetpack plugins, so this is a shim to prevent the fatal before the deeper dive.
* Load markdown from either a beta or stable version of Jetpack.
* If neither, return the content.
n/a
No.
* Within our Docker setup, have Jetpack and the Beta plugin active.
* Ensure in `tools/docker/wordpress/wp-content/plugins` there is no `jetpack-dev dir.
* Load the Jetpack beta page. Scroll to the bottom. Without patch, see "critical error" message. With …
=> Beta: Soft-require Markdown

.github/workflows/gardening.yml
This might help reduce our API call usage from turnstyle, by cancelling
extraneous jobs in cases where we get multiple "pull_request labeled"
events in quick succession or something like that.
Just generic discussion about hitting the GH API rate limits.
No
* Try triggering multiple events in quick succession, e.g. changing labels multiple times. See whether some of the resulting Gardening jobs get cancelled.
=> actions: Set concurrency for gardening workflow

projects/plugins/jetpack/changelog/remove-nav-unification-jetpack-submenus-atomic, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/51342
The _Jetpack_ menu currently contains a _Settings_ submenu which are redundant for WP.com sites, since the options that can be managed from that page can be already managed from other WP.com pages:
Jetpack page | WP.com page
--- | ---
Jetpack > Settings > Security | Settings > General > Security
Jetpack > Settings > Performance | Settings > General > Performance
Jetpack > Settings > Writing | Settings > General > Writing (as of https://github.com/Automattic/wp-calypso/pull/53656)
Jetpack > Settings > Sharing > Publicize | Tools > Marketing > Connections (as of https://github.com/Automattic/wp-calypso/pull/53630)
Jetpack > Settings > Sharing > Sharing | Tools > Marketing > Sharing buttons (as of …
=> Nav Unification: Remove "Jetpack > Settings" submenu

projects/plugins/jetpack/changelog/e2e-report-url-in-slack-notif, projects/plugins/jetpack/tests/e2e/bin/slack.js
Include the test report url in Slack notification.
1156386383419466-as-1200408419584760/f
n/a
* Check Slack notification for this PR. It should include a new button for report which links to the test report.
=> E2E: include test report url in Slack notification

projects/github-actions/repo-gardening/changelog/e2e-gardening-add-e2e-report-url, projects/github-actions/repo-gardening/package.json, projects/github-actions/repo-gardening/src/tasks/check-description/index.js
Add a new section in PR bot comment with link to e2e tests report.
1156386383419466-as-1200466130024533/f
no
* Check bot comment of this PR. It should include a section with a link to e2e test report.
=> Add e2e report url in pr bot comment

projects/plugins/jetpack/changelog/fix-increase-touch-zone-for-carousel-close, projects/plugins/jetpack/modules/carousel/jetpack-carousel.css
Fixes 278-gh-Automattic/view-design
* On mobile devices it can be difficult to press the close button for the carousel; if you don't press close enough, it instead flips through to the next image. This PR just increases the size of the touch zone to improve accessibility (see screenshots).
* Create a new post and insert the Gallery block. Add multiple photos and publish the post.
* View the published post in a mobile view.
* On the frontend, click an image within the gallery to view the image in the carousel.
* Try clicking on/near the button and verify that the carousel closes.
| --- | --- |
| <img width="423" alt="Screen Shot 2021-06-16 at 3 11 35 PM" src="https://user-images.githubusercontent.com/63313398/122301973-5166e680-ceb6-11eb-86e1-5a70ad310815.png"> | <img …
=> [Carousel]: Increase the size of the touch zone for the close button

projects/plugins/backup/changelog/update-backup-plugin-with-backup-pkg, projects/plugins/backup/composer.json, projects/plugins/backup/composer.lock, projects/plugins/backup/src/php/class-jetpack-backup.php
This PR updates the Backup plugin to utilize the `jetpack/v4` core API endpoints defined in the backup package.
* Update Backup Plugin dependencies by adding `automattic/jetpack-backup` in `composer.json`
* Resolve Jetpack REST auth issue by early initializing the Connection's `Rest_Authentication` class in the `Jetpack_Backup` class's constructor.
1199658893173824-as-1200402244140846
No
- Make sure JP is deactivated and site/user connection established via the Backup plugin
-  Follow the instructions here: 29958-pb/#php
=> Jetpack Backup: Utilize endpoints from backup package

projects/plugins/jetpack/changelog/update-carousel-missing-attribute-resilience-part-2, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js
The carousel now uses the thumbnail dimensions when image sizes are missing in the markup.
Ffixes #11191. Hopefully once and for all 🙂
* Uses the thumbnail dimensions when image sizes are missing.
None, but see #11191.
No.
This test requires a gallery with missing size information, such as the one pointed to in https://github.com/Automattic/jetpack/issues/11191#issuecomment-866067231.
If you're testing on that particular page, do note that it appears to load the Carousel twice, both in a concatenated JS file, and as a separately loaded resource.
=> Carousel: yet more resilience to missing data

projects/plugins/jetpack/changelog/update-admin-menu-calypso-settings-submenus, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-admin-menu.php
Part of https://github.com/Automattic/wp-calypso/issues/53774.
In order to accommodate changes that seek to remove the settings navigation bar from Calypso (https://github.com/Automattic/wp-calypso/issues/53774), this PR registers the different Calypso settings pages as independent submenus of the Settings menu.
Site | Before | After
--- | --- | ---
Simple | <img width="279" alt="Screen Shot 2021-06-17 at 17 12 52" src="https://user-images.githubusercontent.com/1233880/122424785-492eaa00-cf8f-11eb-825d-4e130b68ab0b.png"> | <img width="289" alt="Screen Shot 2021-06-17 at 17 11 55" src="https://user-images.githubusercontent.com/1233880/122424825-4fbd2180-cf8f-11eb-9830-3e88f71dd3ee.png">
Atomic | <img width="277" alt="Screen Shot 2021-06-17 at 17 52 21" …
=> Admin menu: Register Calypso settings pages as independent submenus

projects/plugins/jetpack/changelog/add-share-and-embed-fields, projects/plugins/jetpack/class.json-api-endpoints.php, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-media-v1-1-endpoint.php, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-media-v1-2-endpoint.php, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-media-v1-1-endpoint.php, projects/plugins/jetpack/modules/videopress.php, projects/plugins/jetpack/modules/videopress/class-videopress-attachment-metadata.php, projects/plugins/jetpack/modules/videopress/class.videopress-edit-attachment.php
Add the `Share` and `Rating` configuration options in Calypso Media Edit modal for WPCOM and Jetpack sites (including atomic).
Fixes https://github.com/Automattic/wp-calypso/issues/51040
* I've extracted and refactored the implementation from class.videopress-edit-attachment.php save_fields method in order to be able to use it in WP-Admin and in the API.
* The API rest endpoints for listing and updating the media which we are currently using in Calypso contains two new properties to for rating and share.
* In the WPCOM patch there's also a fix in VideoMeta that fixes `Duplicated entry` SQL errors triggered when un-checking and checking the Sharing checkbox.
No
Atomic and Jetpack:
* Use Jetpack Beta to switch to this branch.
Simple sites:
* Sandbox your environment and apply the patch …
=> Add/share and embed fields in Calypso media edit modal

.github/workflows/build.yml
The Beta Download webhook has been updated to use the new plugins
artifact.
This should shave about 80 seconds off the time it takes for a build to
be available in the Beta plugin, as creating that jetpack-dev was
relatively slow.
p9dueE-362-p2
No.
* See that the "Build / Create artifact for Jetpack Beta plugin" job completed successfully on this PR.
* See that entries for this PR show up in both https://betadownload.jetpack.me/jetpack-branches.json and https://betadownload.jetpack.me/vaultpress-branches.json.
=> build: Stop creating legacy jetpack-dev artifact

projects/plugins/jetpack/changelog/fix-admin-menu-jetpack-item, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php
* Added the missing `null` parameter for add_submenu_page for Settings > Jetpack menu on Atomic sites.
No
* Switch to this branch with Jetpack Beta on your Atomic site
* Go to Settings > Jetpack
* Make sure that you are redirected to wordpress.com/settings/jetpack/your-site
=> Added missing `null` parameter to the add_submenu_page function call

projects/plugins/jetpack/changelog/update-removes-dashboard-switcher-from-index, projects/plugins/jetpack/modules/masterbar/admin-menu/menu-mappings.php, projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php
Fixes https://github.com/Automattic/jetpack/issues/20197
As discussed here pd2C0z-3q-p2#comment-146 we are not going to show a dashboard switcher in `/wp-admin/index.php` and instead we are adding a submenu item. This PR removes the switcher from `/wp-admin/index.php` .
* Go to `/wp-admin/index.php` 
* Click screen options
* You shouldn't be presented with the dashboard switcher.
* Go to `/wp-admin/edit.php`
* Make sure you are still seeing the dashboard switcher and no regressions are introduced.
Before | After
-------|------
=> Dashboard Switcher: do not show it on index.php

projects/plugins/jetpack/changelog/update-remove_mobile_push_file, projects/plugins/jetpack/modules/mobile-push.php, tools/phpcs-excludelist.json
* Delete the `modules/mobile-push.php` file. This module appears to have been deprecated 8 years ago.
* n/a
* no
I don't think any testing is necessary.
=> Delete the modules/mobile-push.php file

projects/plugins/jetpack/_inc/client/at-a-glance/connections.jsx, projects/plugins/jetpack/_inc/client/components/connect-button/index.jsx, projects/plugins/jetpack/_inc/client/main.jsx, projects/plugins/jetpack/changelog/add-disconnect-route
* New `#/disconnect` route for the Jetpack plugin.
* The route shows the Jetpack Dashboard, and opens the "Disconnect" modal.
p1HpG7-chE-p2
No.
1. Connect Jetpack if not connected.
2. Open the URL `/wp-admin/admin.php?page=jetpack#/disconnect`.
3. Confirm that you get redirected to `/wp-admin/admin.php?page=jetpack#/dashboard`, and Jetpack Dashboard loads.
1. Connect Jetpack if not connected.
2. Rebuild Jetpack if needed.
3. Open the URL `/wp-admin/admin.php?page=jetpack#/disconnect`.
4. Confirm that Jetpack Dashboard loads, and the "Disconnect" modal opens automatically.
5. Disconnect Jetpack, confirm that it went fine.
6. Reconnect Jetpack and load the URL `/wp-admin/admin.php?page=jetpack#/dashboard`.
7. Confirm that Jetpack Dashboard loads, but the "Disconnect" modal does not open …
=> Connection: route for the "Disconnect" modal

projects/github-actions/repo-gardening/changelog/add-gardening-e2e-tests-label, projects/github-actions/repo-gardening/src/tasks/add-labels/index.js, projects/plugins/jetpack/tests/e2e/playwright.config.js
Automatically add label `E2E Tests` if PR changes e2e tests files.
1156386383419466-as-1200408419584765/f
no
* CI green.
* If e2e tests files are changed E2E Tests label should be added by `Gardening / Manage labels and assignees` check.
* Tested with [81535a1](https://github.com/Automattic/jetpack/pull/20213/commits/81535a11a0ea174e557735f63161c4cc73712e85), see PR history.
=> Gardening: add E2E Tests label

.github/files/lint-project-structure.sh, tools/check-copied-files.sh
Remove the package.json engines check from the pre-commit hook.
It's slow, and package.json files aren't edited all that often.
Put the check into .github/files/lint-project-structure.sh instead.
None linkable.
No
* Edit a package.json to change one of the entries in `.engines`, then commit. It shouldn't warn you about it.
* Run `.github/files/lint-project-structure.sh`. That should produce messages about the mismatch.
=> pre-commit hook: Remove package.json engines check

tools/git-hooks/pre-commit-hook.js, tools/parallel-lint.sh
PR #19334 intended to add linting of changed PHP files in the pre-commit
hook, but the actual implementation linted all PHP files if any PHP file
is changed.
This fixes that, by enhancing our wrapper script to be able to be told
when files are being listed on the command line so it can avoid
processing all files.
None linkable.
No.
* Run `composer php:lint`. See that all files are linted.
* Edit some PHP files, then commit. See that only the edited files are linted by the pre-commit hook.
=> pre-commit hook: Only lint changed PHP files

.github/workflows/e2e-tests.yml
Remove an unused field (`pr`) in payload sent to reporting workflow in jetpack-e2e-reports repo. This field was replaced by `pr_number` and was kept for a while for backwards compatibility.
n/a
no
* CI green
* Report successfully generated: https://automattic.github.io/jetpack-e2e-reports/20230/report/
=> E2E checks: removed obsolete field sent to reporter workflow

projects/packages/sync/changelog/fix-sync-checksum-parent-join, projects/packages/sync/src/replicastore/class-table-checksum.php
Fixes:Checksum inconsistent terms
The checksum process is currently identifying terms as inconsistent when the Cache and remote db have the same data. Upon review it was determined that the issue was a parent join that caused multiple rows per term and so multiple values were included in the checksum.
* Resolve discrepancy in terms checksum logic.
NO
* Apply Patch to your Jetpack Site / Checkout branch in beta tester
* Access the JP Debug tool for your site
* Click "Schedule Fix" from Sync Validation panel
* Wait for the fix to complete
* Click "Schedule Checksum" from Sync Validation panel
* Verify that terms align and that other tables align as well.
Alternatively from a WP.com sandbox you can run
switch_to_blog( --BLOG_ID-- );
$validator = new Jetpack_Sync_Validator( …
=> Update checksum query to use a distinct inner join

projects/packages/sync/changelog/fix-checksum-invalid-term-in-term-relationship, projects/packages/sync/src/class-settings.php, projects/packages/sync/src/replicastore/class-table-checksum.php
Fixes Invalid Taxonomy being returned in a checksum.
Currently the Term_Taxonomy table is checksummed based on a disallow list. This implementation has a flaw in that any misc relationships that are not part of registered taxonomies get included in the checksum and lead to inconsistencies being identified that can not be resolved. To ensure only registered taxonomies are included in the checksum we are moving to an allowed (IN) query which has the benefit of being lower footprint as the majority of sites have less taxonomies then the disallow list we maintain.
* Fix term_relationship data inconsistencies in checksum routine.
NO
* Access wp shell and run `Automattic\Jetpack\Sync\Settings::get_allowed_taxonomies_structured();` verify that it returns an array which includes registered …
=> Update term_taxonomy checksum filter to an allow list.

projects/plugins/jetpack/changelog/fix-register-performance-submenu, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/54220
Fixes a regression introduced in https://github.com/Automattic/jetpack/pull/20147, where we mistakenly removed the "Settings > Performance" menu that we added in https://github.com/Automattic/jetpack/pull/20100.
Before | After
--- | ---
N/A.
No.
- Set up the testing environment:
- Simple sites: Apply D63721-code to your WP.com sandbox, and sandbox both the API and a Simple site.
- Atomic sites: Install Jetpack Beta and activate the `fix/register-performance-submenu` branch.
- Go to https://wordpress.com and switch to your test site.
- Make sure the "Settings" menu contains a "Performance" submenu.
=> Nav Unification: Register "Settings > Performance" submenu

pnpm-lock.yaml, projects/packages/connection-ui/changelog/fix-update-requested-components-version-number, projects/packages/connection-ui/package.json, projects/plugins/jetpack/changelog/fix-update-requested-components-version-number, projects/plugins/jetpack/package.json
The repo currently doesn't build because of a version mismatch in `jetpack-components`.
Fixes bug introduced in #20288.
* Match requested `jetpack-components` version to available version.
None.
No.
* Check out the branch
* Run `pnpm i`
* Ensure it works correctly, without complaining about missing dependencies
=> Update requested jetpack components version number

projects/packages/sync/changelog/add-inline-note-re-new-sync-action, projects/packages/sync/src/modules/class-themes.php
fixes #20261 
There are new `delete_theme` and `deleted_theme` hooks in WordPress 5.8. We may want to switch to it once WP 5.8 is our minimum version.
* We don't want to switch to the new hook yet, must wait for WP 5.8 to be our minimum version.
n/a
No
* None needed for this PR.
*
=> Sync: Add note to use new deleted_theme hook

.github/files/renovate-helper.sh, .github/workflows/linting.yml, pnpm-lock.yaml, projects/packages/connection-ui/changelog/add-check-intra-monorepo-deps, projects/packages/connection-ui/package.json, projects/plugins/backup/changelog/add-check-intra-monorepo-deps, projects/plugins/backup/package.json, projects/plugins/jetpack/changelog/add-check-intra-monorepo-deps, projects/plugins/jetpack/package.json, tools/check-intra-monorepo-deps.sh
In other words, have it also check intra-monorepo JS package
dependencies.
And while I'm at it, have it check the monorepo root composer.json too.
p1625657891311300-slack-CDLH4C1UZ
No
Test 1:
* Check out the first commit of this PR.
* Run `tools/check-intra-monorepo-deps.sh`, see it complain about `@automattic/jetpack-connection` deps that weren't updated in #20214.
* Run `tools/check-intra-monorepo-deps.sh -u`, see it reproduce the second commit of this PR.
Test 2:
* Edit the monorepo root composer.json to depend on a wrong version of `automattic/jetpack-codesniffer`.
* Run `tools/check-intra-monorepo-deps.sh`, see it complain about that.
* Run `tools/check-intra-monorepo-deps.sh -u`, see it fix it (and not try to create a change entry for the monorepo root).
Test 3:
* Edit …
=> tools: Make "check-composer-deps" into "check-intra-monorepo-deps"

projects/plugins/jetpack/changelog/e2e-page-listeners, projects/plugins/jetpack/tests/e2e/lib/env/playwright-environment.js
Listen and log `pageerror` and `requestfailed` page events.
1156386383419466-as-1200559827847720
no
* CI green
* Page events of type `pageerror` and `requestfailed` should be logged in console and log file.
=> E2E tests: listeners for page error and request failed

.github/workflows/build.yml
We should not be publishing a release candidate for VaultPress from
jetpack/branch-9.9, for example.
FYI, I already manually deleted the bogus rc entry from https://betadownload.jetpack.me/vaultpress-branches.json.
None
No
* Make sure this PR still is published to both https://betadownload.jetpack.me/jetpack-branches.json and https://betadownload.jetpack.me/vaultpress-branches.json (under "pr", of course).
* Cherry pick this to jetpack/branch-9.9 and see that it doesn't re-publish an "rc" entry to https://betadownload.jetpack.me/vaultpress-branches.json.
=> build: Don't publish the wrong plugin's releases

projects/packages/connection/changelog/fix-packages-connection-test-broken-by-wordbless, projects/packages/connection/tests/php/test-class-webhooks.php
https://github.com/Automattic/wordbless/pull/44 started setting the
correct "siteurl" option, which changed the redirect path returned by
one of the tests here.
None
No
* Is CI happy? Particularly the Code Coverage job, which had been failing due to this.
=> packages/connection: Fix test after WorDBless change

projects/plugins/jetpack/changelog/fix-watch_css_files, projects/plugins/jetpack/gulpfile.babel.js, projects/plugins/jetpack/tools/builder/admin-css.js, projects/plugins/jetpack/tools/builder/frontend-css.js
While working on some CSS issues on the Jetpack plugin I noticed that styles are not generated automatically while running either `jetpack watch` or `cd projects/plugins/jetpack && pnpm watch`. In particular the following files were not triggering a build step:
https://github.com/Automattic/jetpack/blob/12c1ec934857a0c0fa2afe2ddecbddb7cdbf2e4e/projects/plugins/jetpack/modules/widget-visibility/widget-conditions/widget-conditions.css#L0-L1
https://github.com/Automattic/jetpack/blob/dd9bf5dd1629a42d8407bd514c7a6256ede96606/projects/plugins/jetpack/modules/carousel/jetpack-carousel.css#L0-L1
The above files are built as part of 
https://github.com/Automattic/jetpack/blob/d19207606cb70859f6c617ecd46c5f32c6927ad0/projects/plugins/jetpack/tools/builder/admin-css.js#L34 …
=> Adds admin / frontend CSS files to the build watcher.

.github/workflows/linting.yml
We don't include that as part of the workspace so normal development
doesn't need to install all of playwright and so on. But that also means
the root-level `pnpm install` doesn't process it, which can make eslint
be unable to resolve imports.
Came up in code review on #20326
No
* Merge this, then have renovate regenerate #19328, then rebase #20326. See if that fixes the "Linting / ESLint (non-excluded files only)" job.
=> linting: Do pnpm install in Jetpack E2E dir before eslint

projects/plugins/backup/changelog/reorganize-admin-js, projects/plugins/backup/src/js/components/Admin.js, projects/plugins/backup/src/js/components/Backups.js
Fixes #
* A minor change to the way the backups array is parsed to handle a case where backups are deleted but still appear in the activity log.  This is a very rare case in the wild GDPR mostly, but is useful for testing sites without backups.
* Reorganized the Admin.js to make it more obvious where we'll integrate the Manage Connection, Header and Footer segments.
no
* Install plugin and ensure placeholder header / footer / manage connection blocks continue to appear in their designated spaces.
=> Backup Plugin: Reorganize Admin.js to facilitate integration

projects/plugins/jetpack/changelog/fix-current-menu-item-focus, projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
Fixes https://github.com/Automattic/wp-calypso/issues/51513
* On page load, focus on the currently active menu item so it's behaviour is inline with Calypso
**Atomic**
* Install Jetpack Beta and activate this branch
* Navigate between WP Admin pages ensuring that on every new page you visit via the menu that your keyboard focus is active on the active menu item.
**Simple**
* Apply patch `D63692` on your Sandbox and Sandbox a simple site
* Navigate between WP Admin pages ensuring that on every new page you visit via the menu that your keyboard focus is active on the active menu item.
=> Nav unification: create and use function setFocusOnActiveMenuItem

projects/packages/sync/changelog/fix-sync-checksum-performance, projects/packages/sync/src/replicastore/class-table-checksum.php
Monitoring the checksum performance post the 9.9 release we noticed a 50% reduction in performance. Checksums taking 40 seconds on average instead of 20 seconds. To address the performance decrease we are restricting the correlated subquery to the taxonomy table as other joins are on the primary and won't have the same issue.
* Restricted correlated subquery to term_taxonomy joins.
* NO
- Apply Patch to your Jetpack Site / Checkout branch in beta tester
- Access the JP Debug tool for your site
- Click "Schedule Fix" from Sync Validation panel
- Wait for the fix to complete
- Click "Schedule Checksum" from Sync Validation panel
- Verify that terms align and that other tables align as well.
Alternatively from a WP.com sandbox you can run
- switch_to_blog( --BLOG_ID-- );
- $validator = new …
=> Restrict correlated subquery to term_taxonomy joins only

projects/plugins/jetpack/changelog/fix-comments-break-social-login, projects/plugins/jetpack/modules/comments/base.php
Commenting on a post after a social login is broken, if the user tries to post comments after their first comment. After connecting a social profile, the first comment is correctly published. But from the second comment onwards, the user will see an error on the page after posting a comment, preventing them from posting any further comments. Here's an example:
To reproduce this issue, try the following steps:
1. Go to any public Jetpack blog and comment on an article after connecting via Twitter or Facebook.
2. After the page reloads, either on the same article or any other article on the same site, post a comment and see the error message shown in the GIF above.
pd2HMz-27-p2
No
1. On a JP connected site, enable commenting with social options by enabling the following option in WP.com in …
=> Fixes broken comments with social login

projects/plugins/jetpack/changelog/fix-php-notice-enhanced-opengraph, projects/plugins/jetpack/modules/publicize/enhanced-open-graph.php
Fix PHP notices where no $post information is available.
The notices are visible on WordCamp sites.
* N/A
* No
Not sure to be honest. I wasn't able to reproduce the notice on my own site.
=> Publicize: avoid PHP notices when $post isn't defined yet.

projects/plugins/jetpack/changelog/fix-widget-visibility, projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php, projects/plugins/jetpack/modules/widget-visibility/widget-conditions/widget-conditions.css, projects/plugins/jetpack/modules/widget-visibility/widget-conditions/widget-conditions.js
Lets the widget visibility conditions run using the new gutenberg based
widgets screen.
Fixes #20057 
* Enables visibility conditions to be set on legacy widgets used within the block-based widget editor
No.
- Firstly, use a theme that supports widgets (you probably are already)
- To enable this feature, go to Jetpack → Settings → Writing, scroll down to the Widgets section, and toggle the switch labelled Enable widget visibility controls to display widgets only on particular posts or pages.
This requires testing on WordPress 5.8
* Go to 'Appearance > Widgets'
* Press + inside the editor
* Press visibility, a form should appear
* Set some conditions, e.g. 'Hide if User is Logged Out'
* Press Update near the top of the screen
* Go to the front-end and look at the widget area, the widgets …
=> Widget visibility: supporting load conditions for legacy widgets in gutenberg widgets screen

projects/plugins/jetpack/changelog/fix-widget-wpcom-block-editor, projects/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
Related: #20357
Since the WordPress.com Block editor relies on wp-editor, and since that dependency cannot be used in the widget editor (see https://core.trac.wordpress.org/changeset/51393 ), let's not load the WordPress.com editor scripts in the widget editor.
* Primary issue: #20357
* No
* Start from a site where Jetpack is connected to WordPress.com and where you are running WordPress 5.8 RC.
* Go to Appearance > Widgets.
* The `wpcom-block-editor` scripts should not be enqueued.
=> WordPress.com Block Editor: do not use in the upcoming Block-based Widgets Editor

projects/js-packages/connection/changelog/fix-rna-connection-screen-loading, projects/js-packages/connection/components/connect-screen/index.jsx, projects/js-packages/connection/components/connect-screen/style.scss
* hide connection screen while loading the connection status
Related to #20167
No.
_If you're using a JN site, you need to install [this plugin](https://gist.github.com/sergeymitr/bc005e1b893e778c03e4f43debb91c30) to activate the Connection Manager page._
1. Disconnect Jetpack.
2. Go to "Tools -> Connection Manager".
3. Fully connect, you should be taken back to the Connection Manager.
4. Reload the Connection Manager page. Confirm that the page is empty, then the line "Site and User Connected" appears. The connection screen layout should not appear even for a moment while the page is loading if the connection is fully established.
=> RNA Connection: hide connection screen while loading the status

projects/packages/backup/changelog/update-add_package_versions, projects/packages/backup/composer.json, projects/packages/backup/src/class-package-version.php, projects/packages/connection/changelog/update-add_package_versions, projects/packages/connection/composer.json, projects/packages/connection/src/class-package-version.php, projects/packages/sync/changelog/update-add_package_versions, projects/packages/sync/composer.json, projects/packages/sync/src/class-package-version.php, projects/plugins/backup/changelog/update-add_package_versions, projects/plugins/backup/composer.lock, projects/plugins/jetpack/changelog/update-add_package_versions, projects/plugins/jetpack/composer.lock
* Add new classes, `Package_Version`, to the Sync, Connection, and Backup packages.
* Add a constant that contains the package version string to the new `Package_Version` classes.
* Update the packages' `composer.json` files to include the `version-constants` extra value.
* p9dueE-3b1-p2
* no
* n/a
=> Add package version constants to the Sync, Connection, and Backup packages

projects/packages/sync/changelog/fix-return-setting-value-of-jetpack-sync-settings-options, projects/packages/sync/src/modules/class-options.php, projects/plugins/jetpack/changelog/fix-return-setting-value-of-jetpack-sync-settings-options, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
Jetpack Sync Settings have a custom Settings class that integrated option values with various filters. When options are synced to WP.com we need to ensure the Settings logic is used so that the correct values are persisted to allow for proper functionality of cache based functionality.
Options module updated to use Settings class for jetpack_sync_settings_* options
No
Unit testing is included in the PR
To manually test perform the following actions
1) delete_option( 'jetpack_sync_settings_post_meta_whitelist' );
2) $module  = Automattic\Jetpack\Sync\Modules::get_module( 'options' );
3) $module->get_all_options();
4) Verify that the jetpack_sync_settings_post_meta_whitelist is not empty but an array that matches
Automattic\Jetpack\Sync\Settings::get_setting( 'post_meta_whitelist' );
5) …
=> Update Options module to return jetpack_sync_settings_* options from Settings class

projects/plugins/jetpack/changelog/add-soft-fail-modules, projects/plugins/jetpack/jetpack.php, projects/plugins/jetpack/load-jetpack.php, projects/plugins/jetpack/tests/php/bootstrap.php
After #20367, the modules/module-headings.php file is not always in the development environment (unbuilt version Jetpack), but load-jetpack.php required it.
* Soft-fail if modules/module-headings.php is not present in a similar way as it does if our autoloader is not present.
* Update the admin_notice message to add that building Jetpack is required.
* Add autoloader and module-headings.php check to unit test bootstrap and have an informative failure if not built (previously, would just exit without outputting the error).
p1626455992369100-slack-CDLH4C1UZ
No
* `jetpack clean plugins/jetpack` and select vendor and "other ignored files"
* Run `jetpack docker up`
* Load docker instance and visit wp-admin. If Jetpack isn't active, try to activate it.
* Before patch: If JP is already active, …
=> Development: Soft-fail if Jetpack is not built

projects/plugins/beta/changelog/fix-beta-tag-with-v, projects/plugins/beta/composer.json, projects/plugins/beta/jetpack-beta.php, projects/plugins/beta/src/class-autoupdateself.php
We'll also want to replace the autotagger's tags when making releases
for a few months, so people using older versions get prompted to
upgrade.
p1626385556043300-slack-CBG1CP4EN
No
* ???
=> Beta plugin: Recognize releases with tags prefixed with "v"

projects/plugins/beta/changelog/add-beta-breadcrumb-menu, projects/plugins/beta/composer.json, projects/plugins/beta/jetpack-beta.php, projects/plugins/beta/src/admin/notice.template.php, projects/plugins/beta/src/admin/plugin-manage.template.php
When navigating to a plugin to manage, users may be confused on how to get back home to the main plugin selection screen. They could click the Jetpack Beta Tester logo in the header, but that might not be fully apparent. This PR adds a small breadcrumb link to get back home.
* No.
* After pulling down changes, navigate between the specific plugin management screens (e.g. `/wp-admin/admin.php?page=jetpack-beta&plugin=vaultpress`).
* The `Jetpack Beta Tester Home` link should take you back to the main selection screen.
=> Beta: add breadcrumb link back to main selection screen

projects/plugins/jetpack/changelog/update-build_message, projects/plugins/jetpack/jetpack.php
* An incomplete Jetpack installation in a development environment is most likely caused by Jetpack being activated before it has been built, and the solution is to build Jetpack. The `Development Environment` document is large, so let's take the developer directly to the `Building your project` section of the document. I think this change makes the notice more useful, especially to new contributors who may be unfamiliar with setting up and working in the Jetpack development environment.
* n/a
* no
1. Delete the vendor files and `modules/module-headings.php` file. You can use this command: `jetpack clean plugins/jetpack` and select vendor and "other ignored files".
2. Navigate to a `wp-admin` page. You should see the incomplete Jetpack notice with the following text:
> Your installation of …
=> Jetpack: Change the GH link in the incomplete Jetpack notice.

projects/plugins/jetpack/changelog/fix-force-calypso-links-when-sso-is-disabled, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php
Fixes https://github.com/Automattic/wp-calypso/issues/54499
* Instead of relying on the global wp-admin toggle and on Dashboard Quick switcher preferences, we should force Calypso interfaces in the menu for Atomic sites that have Jetpack SSO disabled. 
* Switch to this branch using Jetpack Beta
* Make sure you have the wp-admin toggle turned on in me/account
* Make sure that you have a quick switcher preference for a page.
* Go to an Atomic site and disable SSO.
* Make sure that all links that should have a WP-Admin page and a Calypso page are always pointing to the Calypso interface.
=> Force Calypso interfaces when sso is disabled

projects/plugins/jetpack/changelog/improve-seo-load-order, projects/plugins/jetpack/load-jetpack.php, projects/plugins/jetpack/modules/module-extras.php
Fixes #19511
I didn't track down quite what was causing it, but improving the load order should take care of it.
* Load files that only define functions (not call them) to earlier in the process.
n/a
No.
* Not sure how to reproduce, so not sure how to test. 
* Ensure nothing breaks in the unit test?
=> SEO: Earlier load of functions

.github/files/build-all-projects.sh, tools/changelogger-release.sh, tools/replace-next-version-tag.sh
And similarly for `@deprecated`. More specifically, if you write any of
- `@since $$next-version$$`
- `@deprecated $$next-version$$`
- `@deprecated since $$next-version$$`
then the `$$next-version$$` will be replaced with the appropriate
version number on release (using `tools/changelogger-release.sh`).
The appropriate alpha version will also be used when for the mirror repo
(via `.github/files/build-all-projects.sh`).
Using the string `$$next-version$$` elsewhere will result in an error during the
build.
p9dueE-2zB-p2
p9dueE-3cJ-p2
No
* See that the build on this PR is happy.
* Make a PR based on this that uses the relevant constructs. Check that the artifacts from the Build workflow show the constructs replaced.
* Run `tools/changelogger-release.sh` where the released packages use the …
=> tools: Add the ability to do `@since $$next-version$$`

projects/plugins/jetpack/changelog/fix-hide-security-settings-menu, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php
Part of a fix for https://github.com/Automattic/wp-calypso/issues/51820
* Only adds the security nav item to the Atomic admin menu if the site has the `security-settings` feature added in D63248-code
* This is necessary because not all Atomic sites will have access to the `security-settings` modules (Jetpack monitor, protect, sso) going forward
N/A
Nope!
* Go to an Atomic site that does not have the `security-settings` feature, e.g. an Atomic site with the Business plan removed or a free / personal / premium Atomic site with a marketplace subscription
* Verify that the Settings > Security nav item isn't there
* Regression: Go to an Atomic site that does have the `security-settings` feature, e.g. an Atomic site with a Business plan
* Verify that the Settings > Security nav item is there
=> Atomic admin menu: Only show security nav item if site has security settings feature

projects/plugins/jetpack/changelog/fix-my-sites-on-atomic-without-sso, projects/plugins/jetpack/modules/masterbar/admin-menu/load.php
This PR fixes the scenario in which My Sites navigation displays an empty slider that happens when the Nav-unification is disabled on Atomic sites with SSO disabled.
Fixes https://github.com/Automattic/wp-calypso/issues/54502
* We rely on the `jetpack_load_admin_menu_class` filter to disable the My Sites navigation for sites with nav-unification enabled. However, there's a case when the filter still returns a class even though the nav-unification is disabled. In this case, the `My Sites` navigation from masterbar remains disabled. 
No
* Go to an Atomic site and switch to this branch using Jetpack Beta.
* Go to Jetpack > Dashboard > Settings and disable SSO.
* Go to WP-Admin and click on the `My Sites` link.
* You should be able to see the old navigation opening using the slider.
=> Fix "My Sites" navigation in WP-Admin on Atomic sites  with SSO disabled

projects/plugins/jetpack/changelog/fix-tiled-gallery-srcset-width, projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery.php
It had the width and height swapped when processing images to generate
the srcset attribute. This is most noticeable when the gallery contains
images that are much wider than they are high, resulting in ridiculously
small images in the srcset that the browser then scales up into a blurry
mess.
Fixes Automattic/jpop-issues#6772
6772-gh-Automattic/jpop-issues
No
* Create a tiled gallery where the images are much wider than they are high. Use the default layout.
* See if the images look normalish, or if they're a blurry mess.
=> Tiled gallery: Don't swap width and height in srcset

projects/plugins/jetpack/changelog/update-arrays_are_similar, projects/plugins/jetpack/tests/php/sync/test_interface.jetpack-sync-replicastore.php
The `WP_Test_iJetpack_Sync_Replicastore::arrays_are_similar` method isn't needed. Just use PHPUnit's `assertEquals` method instead.
* n/a
* no
* Verify that the unit tests are passing.
=> Sync: remove the arrays_are_similar helper method from WP_Test_iJetpack_Sync_Replicastore

.npmrc, projects/plugins/jetpack/changelog/add-force-node-version-match, projects/plugins/jetpack/tests/e2e/.npmrc
Throws error if locally installed node version is not matching one defined in package.json
Fixes #20428
n/a
n/a
* switch to older node version: `nvm use 14.16.0`
* run any `pnpm` command: `pnpm lint`
error example:
```
✗ pnpm lint
 ERROR  Your Node version is incompatible with "/Users/brbrr/Developer/a8c/jetpack".
Expected version: ^14.16.1
Got: v14.16.0
This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```
=> Force local node version to match expected

projects/plugins/jetpack/changelog/fix-jetpack-build-module-header-step-fail, projects/plugins/jetpack/gulpfile.babel.js
Gulp does the right thing if we return the "child_process" object from
the task function, so let's just do that.
https://gulpjs.com/docs/en/getting-started/async-completion/
I saw this during discussion of p1626874210189400-slack-CBG1CP4EN, but probably not actually the cause of the problem there.
no
* Edit `projects/plugins/jetpack/tools/build-module-headings-translations.php` to error out, e.g. by adding `exit(1);` at the end.
* See if `jetpack build plugins/jetpack` properly fails.
=> Jetpack: Fail build if the php:module-heading step fails

projects/packages/identity-crisis/changelog/update-remove_example_url, projects/packages/identity-crisis/tests/php/test-identity-crisis.php
* The `return_example_url` method is not needed, so remove it.
* n/a
* no
* Verify that the tests pass.
=> Identity Crisis: remove unneeded test helper method return_example_url

projects/plugins/jetpack/changelog/add-media-library-size, projects/plugins/jetpack/class.jetpack-heartbeat.php
* Includes output of `get_space_used` or shim code as part of the heartbeat array.
To be used to help us determine the general sizes of the media library on sites.
p1HpG7-cyv-p2#comment-47782
* We would add tracking the size of the media library as a discreet item. We could calculate something close to this with existing data.
* On a site with this PR, run the debugger. See the new value as part of the heartbeat.
=> Heartbeat: Include media library size

projects/plugins/backup/changelog/update-backup-plugin-links, projects/plugins/backup/src/js/components/Admin.js, projects/plugins/backup/src/js/components/Backups.js
Fixes #20356
* Updated all external links to use getRedirectUrl
* Updated the 'Upgrade Now' button (visible when a site has no backup capabilities) to go to jetpack.com/upgrade/backup
* All non-dashboard links use new `backup-plugin-` prefixed redirect sources.
1200631314158697-as
No.
* Install the Backup Plugin
* 7 links were updated to use redirect
* Upgrade Now is visible if you have no plan on the site (remove plan from Store Admin and you may need to wait up to 15min for cache)
* The Real-time upgrade CTA is only visible if you don't have Real-time but do have backup, so when adding a new plan, just add Backup Daily so this will be visible
* `See your site's activity` link is visible with a backup plan
* `See your backups` link is visible with a successful backup
* The dashboard link …
=> [Plugin] Backup: Updated links and changed to use Jetpack Redirect service

projects/plugins/backup/changelog/update-integrate-connection-status-card-in-backup-plugin, projects/plugins/backup/src/js/components/Admin.js, projects/plugins/backup/src/js/hooks/useConnection.js
* Replaces the current Connection Management section with the `ConnectionStatusCard`component.
pbuNQi-1w3-p2
No
**Important:** Unfortunately, until we get [this PR](https://github.com/Automattic/jetpack/pull/20440) merged we can't test with standalone Backup plugin.
- Spin up a new JN site or test locally with Jetpack active
- Activate the Backup Plugin
- Navigate to `/wp-admin/admin.php?page=jetpack-backup`
- Fully connect by clicking the `Set up Jetpack` button 
- Confirm that you see your WPCOM user info as displayed below:
- Try disconnecting by clicking the `Disconnect` link
- After successful disconnection you should be presented with the `ConnectScreen` again
- We have already requested and got review from Design for the  `ConnectionStatusCard` RNA component. There's an existing …
=> Backup plugin: Integrate ConnectionStatusCard RNA component

projects/packages/sync/changelog/fix-sync-sender-upload-size, projects/packages/sync/src/class-sender.php
To reduce OOM an other errors we enforce a maximum size on the data sent to WP.com for processing. This check makes use of strlen however if encoding is disabled it attempts to run strlen on an array which causes php warnings and also bypasses the content limit. This update ensures the encoded object is used in the strlen check.
Fixes # https://wp.me/p9F6qB-7bJ
* Sync Sender - resolve strlen usage that causes php warnings
No
Changes are covered by unit/integration tests.
Modify content on a Jetpack connected site and verify it Syncs and is persisted to the cache.
=> Fix bug where strlen is being called on the raw unencoded items

projects/plugins/jetpack/changelog/update-learn_more_rel, projects/plugins/jetpack/modules/stats/class-jetpack-stats-upgrade-nudges.php
* Add the `rel="noopener noreferrer"` attribute to the Learn More links in the nudge items.
Reference: https://web.dev/external-anchors-use-rel-noopener/
* This is a follow-up to PR #20436.
* n/a
* no
1. Edit your `wp-config.php` and add `define( 'JETPACK_DEV_TEST_STATS_UPGRADE_NUDGES', true );`
2. Install and activate this branch. Connect Jetpack.
3. In wp-admin, navigate to Jetpack -> Site Stats.
4. Confirm that the Learn More links in the nudges include the `rel` attribute.
=> Stats: add rel attribute to Learn More links

projects/plugins/jetpack/changelog/update-stats-nudges-view-events, projects/plugins/jetpack/modules/stats/class-jetpack-stats-upgrade-nudges.php
Add a tracking event when the Stats page upgrade Nudges are displayed and rename the click event for consistency.
* tracks when the stats page upgrade nudges are displayed
1200651327748745-as-1200651327748784
Yes.
* Add `define( 'JETPACK_DEV_TEST_STATS_UPGRADE_NUDGES', true );` to `wp-config.php`
* Go to Jetpack -> Site Stats
* Go to tracks live view and look for events `jetpack_stats_nudges_%`
* Make sure the `view` events are recorded
* On your site Activate Boost or CRM / and or buy a plan - something that will make some Nudgets disappear.
* Load the page again
* Make sure only events from the visible nudges are recorded in Tracks.
=> track events when nudges are displayed

projects/plugins/jetpack/changelog/activate-stats-upgrade-nudges, projects/plugins/jetpack/modules/stats/class-jetpack-stats-upgrade-nudges.php
* Remove stats page Upgrade nudges feature flag and activate it for everyone
1200651327748745-as-1200651327748779
No
* Make sure the `JETPACK_DEV_TEST_STATS_UPGRADE_NUDGES` constant is NOT set in you wp-config
* Go to Jetpack > Site Stats
* Confirm the Upgrade Nudges are displayed at the bottom of the page
=> Remove stats page Upgrade nudges feature flag and activate it for everyone

projects/packages/sync/changelog/update-carousel-add-option-to-toggle-background-image, projects/packages/sync/src/class-defaults.php, projects/plugins/jetpack/_inc/client/writing/writing-media.jsx, projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php, projects/plugins/jetpack/changelog/update-carousel-add-option-to-toggle-background-image, projects/plugins/jetpack/changelog/update-fix-and-reenable-carousel-background, projects/plugins/jetpack/modules/carousel/jetpack-carousel.css, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js, projects/plugins/jetpack/modules/carousel/jetpack-carousel.php, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
Fixes 290-gh-Automattic/view-design
* Re-enables solid background colors using the average color of the image, with a gradient in opacity from 0.5 to 0.25
* Fixes a bug where the background image of the first & last slides would sometimes disappear when swiping backwards
* ~~Re-enables blurred background images in the carousel, which were previously hidden behind a flag~~
* ~~Fixes a bug where the background image was not sized/centered properly, so the background image would be "zoomed in" to the top left corner. Now the image is centered and scaled to best fit~~
* ~~Since the Canvas 2D API [does not have browser support for Safari on desktop or iOS](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#browser_compatibility), we detect when the feature is unsupported and fallback to …
=> [Carousel]: Reenable background color

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php, projects/plugins/jetpack/changelog/add-admin-menu-rest-api-badge, projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php
Related https://github.com/Automattic/wp-calypso/issues/54464
* Add badge to the JetPack admin menus endpoint. We use this to ensure we have a beta badge for the Site Editor menu.
* Apply diff
* Sandbox public-api
* Open the Calypso admin of one of your sites with site editor enabled
* Open inspector and find this request: https://public-api.wordpress.com/wpcom/v2/sites/_YOUR_SITE_ID_/admin-menu/?_envelope=1
* Confirm response contains the site editor with a badge property. (badge = "beta")
=> Add badge to admin menus endpoint

projects/packages/sync/changelog/fix-sync-wp-error, projects/packages/sync/changelog/fix-sync-wp-error-1, projects/packages/sync/src/class-actions.php, projects/packages/sync/src/class-package-version.php, projects/packages/sync/src/class-queue.php, projects/packages/sync/src/class-replicastore.php, projects/packages/sync/src/class-rest-sender.php, projects/packages/sync/src/class-sender.php, projects/packages/sync/src/class-server.php
Fixes issue reported from WordCamp.org:
Uncaught Error: Class 'Automattic\Jetpack\Sync\WP_Error' not found in /.../wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:37
* For the Rest_Sender class, add `use WP_Error` to resolve the fatal.
* Added `use WP_Error` to other files that previously used \WP_Error so all are they same now.
n/a
No.
* None. It's a syntax error really.
=> Sync: Utilize import for WP_Error

projects/plugins/jetpack/changelog/fix-workaround-bad-wpcom-minifier-part-1, projects/plugins/jetpack/tools/webpack.config.search.js
The minifier seems to choke on newer JS, but we can avoid it by naming
the file to end in ".min.js".
At some point we'll probably need to do this to more files too.
p1627570375202400-slack-C025Q5RK2
No
* Load onto wpcom infrastructure somehow, and see if the built file avoids being broken without having to include `?minify=no` in the URL.
=> Jetpack: Rename a JS file to avoid an outdated wpcom minifier

projects/packages/sync/CHANGELOG.md, projects/packages/sync/changelog/fix-sync-wp-error, projects/packages/sync/changelog/fix-sync-wp-error-1, projects/packages/sync/src/class-package-version.php
* Backport new version release from 10.0 beta: https://github.com/Automattic/jetpack/commit/a632065f5617394514c07ef680a6658370bfa778
* No.
* Proofread
=> Sync: backport new package version from 10.0-beta

projects/packages/sync/changelog/revert-20377-update-fix-and-reenable-carousel-background, projects/packages/sync/src/class-defaults.php, projects/packages/sync/src/class-package-version.php, projects/plugins/jetpack/_inc/client/writing/writing-media.jsx, projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php, projects/plugins/jetpack/changelog/revert-20377-update-fix-and-reenable-carousel-background, projects/plugins/jetpack/modules/carousel/jetpack-carousel.css, projects/plugins/jetpack/modules/carousel/jetpack-carousel.js, projects/plugins/jetpack/modules/carousel/jetpack-carousel.php, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
Reverts the colorized background feature for the carousel for the time being; the feature will be revisited in the next release cycle when there is time for sufficient testing. (JP 10.1)
Discussion: https://github.com/Automattic/jetpack/pull/20476#issuecomment-891162815
No
Checkout PR to local test env.
View the carousel settings under Jetpack Settings -> Writing and verify that the setting for colorized backgrounds no longer appears.
Add a gallery to a post and open in frontend and make sure the background is solid black/white (depending on Light Mode/ Dark mode settings)
This should not require a diff as the diff for #20377 (D64175-code) was not merged.
Reverts Automattic/jetpack#20377
=> Revert "[Carousel]: Reenable background color"

projects/packages/sync/CHANGELOG.md, projects/packages/sync/changelog/revert-20377-update-fix-and-reenable-carousel-background, projects/packages/sync/src/class-package-version.php
* Backport new version release from 10.0 beta: https://github.com/Automattic/jetpack/commit/4056eedcc8d9825eb8a5dfcf8608d9457067780f
N/A
No.
Proofread.
=> Sync: backport v1.24.2 from JP 10.0-beta

projects/github-actions/repo-gardening/changelog/update-repo-gardening-boost, projects/github-actions/repo-gardening/src/tasks/add-labels/index.js
Follow-up from #19891
Now that Boost is in the monorepo, its paths have changed. Our action should be updated accordingly.
* N/A
* No
* In Boost PRs, module names should be automatically labeled from now on. You should be able to test that by opening a PR against this branch, that makes changes to `projects/plugins/boost/app/admin/index.php`, or `projects/plugins/boost/compatibility/`, or `projects/plugins/boost/app/modules`.
=> Repo Gardening: update paths used for label detection for the Boost plugin

projects/plugins/boost/changelog/add-jetpack-watch-cli-for-boost, projects/plugins/boost/composer.json, projects/plugins/boost/package.json
* Add watch entry in composer for compatibility with "jetpack watch" cli 
N/A
N/A
* Run `jetpack watch plugins/boost` and it should run the Jetpack Boost plugin watch process
=> Boost: Add watch entry in composer for compatibility with "jetpack watch" cli 

projects/plugins/jetpack/changelog/fusion-sync-aerych-r229758-wpcom-1628006252, projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-comment-endpoint.php
This adds a new field to comments returned by comments endpoints.  The new field indicates whether the current user has replied to a specific comment.
The field is a simple bool rather than an int for the ID of the reply since there could be more than one.
* Differential Revision: D64353-code
* This commit syncs r229758-wpcom.
* More context in this thread: pbArwn-2ks-p2#comment-3471
* No
Sandbox this change and visit the following endpoints for sites where you have replied to comments.  Confirm that `i_replied` is `true` for comments to which you have replied and is `false` otherwise.
/sites/%s/comments
/sites/%s/comments/%d
/sites/%s/posts/%d/replies
=> REST API: Adds 'i_replied' field to comments in comments endpoint responses

projects/plugins/boost/changelog/fix-boost-phpunit-tests, projects/plugins/boost/composer.json, projects/plugins/boost/composer.lock, projects/plugins/boost/tests/php/class-base-test-case.php, projects/plugins/boost/tests/php/lib/test-class-url.php, projects/plugins/boost/tests/php/lib/test-class-viewport.php, projects/plugins/boost/tests/php/mocks.php
Fix broken phpunit tests in Jetpack Boost.
* Remove dependency on `WP_Unit`; it requires a higher version of PHP than the Monorepo env. Replaces it with Brain Monkey.
no.
- Run the unit tests with `composer run test-php` from inside the Boost directory. See that it doesn't explode horribly.
=> Fix Boost phpunit tests

projects/plugins/jetpack/changelog/fix-20439, projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php
* Change "All Pages" label in dropdown to those one saved as "all_items" in taxonomy configuration
* Go to Widgets settings
* Open Widget Visibility
* Choose "Show if" taxonomy
* Instead of "All Pages" see taxonomy translation for this label
=> Widget Visibility - rename taxonomy label "All Pages" in dropdown

projects/plugins/jetpack/changelog/fix-e2e-mailchimp-test, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/blocks/mailchimp.js
Fix for Mailchimp e2e test that started failing after the text of a button was changed.
n/a
no
* E2E tests should pass
=> E2E tests: fix for mailchimp test

pnpm-lock.yaml, projects/js-packages/api/changelog/fix-rna-api-dependency, projects/js-packages/api/index.jsx, projects/packages/connection-ui/changelog/fix-rna-api-dependency, projects/packages/connection-ui/package.json, projects/plugins/backup/changelog/fix-rna-api-dependency, projects/plugins/backup/package.json
- Add missing `@automattic/jetpack-api` dependency to the Backup and Connection UI.
- Add back the API methods accidentally left behind
Related to #20531
No.
1. Build Backup and Connection UI.
2. Confirm that "Backup" and "Tools -> Connection Manager" pages load well with no JS errors.
3. Disconnect Jetpack, go to "Backup" and go through the connection flow. Confirm that it went fine.
=> RNA: bring back the missing API pieces

projects/packages/autoloader/README.md, projects/packages/autoloader/changelog/update-autoloader_readme
Fixes #20546
* Update the README file to specify that the autoloader can only control which version of a package is loaded if all plugins that use the package use this autoloader.
* n/a
* no
* n/a
=> Autoloader: update readme

projects/plugins/jetpack/changelog/update-stats_tracking_learn_more, projects/plugins/jetpack/modules/stats/class-jetpack-stats-upgrade-nudges.php
* Add tracking events to the `Learn more` links in the Stats page upsell nudges. The tracking events will be triggered when the `Learn more` links are clicked.
* p1HpG7-cfa-p2#comment-48099
Yes. We track when the `Learn more` links in the upsell nudges are clicked.
To ensure that all of the stats page upsell nudges are displayed, the test site should be in the following state:
* Free Jetpack plan.
* Jetpack CRM not installed or not active.
* Jetpack Boost not install or not active.
1. Install and activate this branch of Jetpack. Connect Jetpack.
2. Navigate to wp-admin -> Jetpack -> Site Stats.
3. Scroll to the bottom of the page. Click on each of the `Learn more` links in the upsell nudges.
a. Confirm that each learn more link destination is opened in a new tab.
b. In tracks live view, …
=> Stats: add tracking to learn more links in upsell nudges

projects/plugins/boost/app/assets/src/js/pages/settings/sections/AdvancedCriticalCss.svelte, projects/plugins/boost/app/assets/src/js/stores/critical-css-recommendations.ts, projects/plugins/boost/app/assets/src/js/utils/generate-critical-css.ts, projects/plugins/boost/app/assets/src/js/utils/make-admin-ajax-request.ts, projects/plugins/boost/app/modules/critical-css/class-critical-css.php, projects/plugins/boost/changelog/add-jetpack-boost-clear-dismissed-recommendations
This is a port of the PR from the Legacy Jetpack Boost repository
* Allow to clear dismissed Critical CSS recommendations.
See the demo video below:
https://user-images.githubusercontent.com/927932/128448056-d2420d56-b15f-4091-b5f9-a0dd7328fce9.mov
N/A
N/A
* Refer to the demo video above.
=> Boost: Implement the feature to clear dismissed Critical CSS recommendations

projects/packages/sync/changelog/fix-jetpack-sync-get-sync-objects-post, projects/packages/sync/src/class-package-version.php, projects/packages/sync/src/class-rest-endpoints.php, projects/plugins/boost/changelog/fix-jetpack-sync-get-sync-objects-post, projects/plugins/boost/composer.json
* Make `/sync/object/get_sync_objects` endpoint accessible via `POST`. Retain `GET` as backwards-compatibility. 
N/a
No
* To be specified later as it needs a WPCOM change.
=> Jetpack Sync: Add /sync/object endpoint access via POST

projects/plugins/jetpack/changelog/fix-e2e-block-search-input-selector, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/block-editor.js
The selector for block search input field changed in Gutenberg standalone version and this fails out scheduled blocks tests with standalone Gutenberg.
p1628253905220700-slack-CBG1CP4EN
no
* E2E tests should pass
=> E2E tests: Fix selector for block editor search field

.github/files/required-review.yaml
﻿Since that lock file gets modified when they add new dependencies in their plugin's dependencies, let's not block them for that.
* N/A
* No
* Not much to test here. This should unblock things for Boost and Backup teams in the future.
=> Reviews: allow teams to approve changes to monorepo's lock file

projects/packages/tracking/README.md, projects/packages/tracking/changelog/add-tracks-docs
Adds a README file to the Tracking package along with documentation on how to use it.
Fixes #15929
Fixes #17569
* Adds a README file to the Tracking package along with documentation on how to use it.
n/a
No
Proofread the documentation
* Ajax and PHP tracking were recently tested by me
* I tested pixel tracking a long time ago. It should still be working the same way
* Please confirm that the console command is the right one
=> Add documentation to the Tracking package

projects/plugins/boost/app/assets/src/css/components/critical-css.scss, projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssErrorDescription.svelte, projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssShowStopperError.svelte, projects/plugins/boost/changelog/update-boost-css-showstopper-design
This PR was "left behind" when Jetpack Boost was migrated to the Jetpack Monorepo: 1057-gh-Automattic/jetpack-boost
This PR migrates the original changes to the Monorepo, but also adds a couple of minor tweaks:
- When an `UknownError` occurred on all pages in a site, its error message was hidden in the showstopper view, because the `rawError` information was hidden along with the suggestion. This PR separates the raw error info from the suggestion so it can be shown even in Showstoppers.
- Consistent `transition:slide` rules used for all see | hide error links.
* Updates display of "0 CSS files generated" error to match other showstopper errors, including the "Retry / Contact Support" flow.
no.
1. Break Critical CSS Generation in such a way as to cause a showstopper error. e.g.: cause a …
=> Boost: Show standard Showstopper flow for 0 files generated.

projects/plugins/boost/app/assets/src/css/components/critical-css.scss, projects/plugins/boost/app/assets/src/css/components/error-message.scss, projects/plugins/boost/app/assets/src/css/main/mixins.scss, projects/plugins/boost/changelog/update-boost-css-error-mobile-styles
This PR was "left behind" when Jetpack Boost was migrated to the Jetpack Monorepo: 1059-gh-Automattic/jetpack-boost
This PR fixes a couple of issue with the design on mobile:
- Issue with long URLs breaking the design as they were overflowing their containers. I have added some logic to wrap them.
- issue with the Refresh/Contact Support buttons squashing to much the left hand side paragraph. I have made some changes to have the button sections as a block for small devices and flex on larger displays.
* Improve display of Critical CSS showstopper errors on small screens
no
1. Cause Critical CSS Generation to fail with a showstopper (e.g.: throw a 500 error on every page)
2. Check out the error display on small screens, make sure it doesn't run off the display or look weird.
=> Boost: Refactor CSS to Improve UI on small devices

projects/plugins/boost/app/assets/src/css/components/error-message.scss, projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssErrorDescription.svelte, projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssShowStopperError.svelte, projects/plugins/boost/changelog/fix-critical-css-details
* Add logic to not show 'See Error Message' text if no details are available.
* Ensure that the correct error message details are in the correct colour.
N/A
N/A
Force to generate a Showstopper error and:
- Make sure that correct error message details are displayed in black color.
- Make sure that the 'See Error Message' text is not showing if no error details are available.
=> Boost: Fix some minor UI issues with Critical CSS Showstopper error

tools/check-intra-monorepo-deps.sh
When using `tools/changelogger-release.sh` to update changelogs for release, I hit ran into a path error:
```
Processing plugins/boost...
Processing packages/autoloader...
There are no changes with content for this write. Proceed? [y/N] y
Processing packages/lazy-images...
Processing packages/tracking...
Updating dependencies...
Creating changelog entry for plugins/debug-helper composer.lock update
tools/check-intra-monorepo-deps.sh: line 100: cd: projects/packages/changelogger: No such file or directory
```
This PR fixes the issue by changing to the `changelogger` directory using an absolute path, care of `$BASE` instead of using a relative path.
* Use an absolute path when changing directory in `check-intra-monorepo-deps.sh`.
no
1. Try using `tools/changelogger-release.sh` to prepare a …
=> Fix relative path in intra-deps checker tool

projects/plugins/boost/changelog/update-boost-release-cycle, projects/plugins/boost/composer.json, projects/plugins/boost/composer.lock, projects/plugins/boost/jetpack-boost.php, projects/plugins/boost/package.json
* Start the new release cycle for the Boost plugin after releasing 1.2.0 Beta.
* N/A
* No
* Is CI happy?
=> Boost: start new release cycle

projects/plugins/boost/changelog/add-boost-wp-tested-version, projects/plugins/boost/readme.txt
* I am not entirely sure if this can be done the release process so I am putting forward this PR to update the WordPress tested up to version in the readme file. Otherwise for WordPress 5.8, Jetpack Boost plugin in the Plugin search area comes with the test "Untested with your version of WordPress".
N/A
N/A
- Once release, Jetpack Boost will show with the wording "Compatible with your version of WordPress" like in the screenshot below for the Jetpack plugin:
=> Boost: Update WordPress tested up to version in the readme file

projects/plugins/jetpack/changelog/fix-e2e-fix-paypal-block-no-fill, projects/plugins/jetpack/tests/e2e/lib/pages/jetpack-connect/site-topic.js, projects/plugins/jetpack/tests/e2e/lib/pages/page-actions.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/block-editor.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/blocks/eventbrite.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/blocks/pinterest.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/blocks/simple-payments.js, projects/plugins/jetpack/tests/e2e/lib/pages/wpcom/checkout.js, projects/plugins/jetpack/tests/e2e/lib/pages/wpcom/connections.js
* The mandatory fields in PayPal blocks are not getting filled, leading to occasional PayPal test failure. Why occasional? Apparently if you're fast enough, which Playwright is, you can publish the post before the fields are validated and errors are thrown.
* Fixed the selectors so that fields are no properly filled.
* Replaced `page.type` with `page.fill` everywhere we're filling forms, as `fill` method is the recommended one because it also checks for fields being editable before filling them with text.
1156386383419466-as-1200757549786732
no
* E2E tests need to pass
=> E2E tests: Fix Paypal block fields not getting filled

projects/js-packages/components/changelog/fix-jetpack-footer-default-prop, projects/js-packages/components/components/jetpack-footer/index.jsx
* Adds a default value for the `a8cLogoHref` URL prop; previously was blank.
* The `/wp-admin/admin.php?page=jetpack_about` page would only be available if Jetpack was activated, which won't always be the case (e.g. standalone Backup plugin). We could consider linking by default to an `automattic.com` page or maybe a new `jetpack.com` page with similar content as the `jetpack_about` page.
No.
* After pulling down these changes to local dev, adding a `<JetpackFooter />` with no `a8cLogoHref` prop value provided should default to: https://www.jetpack.com
=> JetpackFooter: add default a8cLogoHref prop value

projects/github-actions/required-review/README.md, projects/github-actions/required-review/changelog/add-single-user-review-support, projects/github-actions/required-review/package.json, projects/github-actions/required-review/src/team-members.js
This PR adds support for specifying individual users in the required-review config.
When a team name is prefixed with `@`, it is treated as a single-user team containing the named GitHub user. For example, `@thingalon` would be treated as a virtual team with one (utterly amazing 😉 ) team member.
For example:
```
- name: Boost
paths:
- 'projects/plugins/boost/**'
- 'pnpm-lock.yaml'
teams:
- heart-of-gold
- jetpack-approvers
- '@davidlonjon'
```
It should happily work with the existing `any-of` and `all-of` features.
Fixes #20610 
* Add support for naming individuals in required reviewers config, by using an `@` prefix.
no
1. Check out this branch, then modify `.github/files/required-review.yaml` to add a user (e.g.: `'@davidlonjon'`) to the list of Boost reviewers. See above example.
2. …
=> Add support for specifying individual users as required reviewers

projects/plugins/jetpack/changelog/update-sso-redirect, projects/plugins/jetpack/modules/sso.php
﻿This was added in #15140. Removing it means making the log in process a bit faster.
* Internal reference: p55Cj4-1bO-p2
* No
* On a site with SSO enabled, log out and log back in.
* You should be redirected to WordPress.com and then back to your site, without going through jetpack.com.
=> SSO: remove Jetpack.com redirect during login process

projects/plugins/jetpack/changelog/try-fix-sso-tests, projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-sso.php
SSO tests were failing because not enough data was synchronized to return the callables.
This patch is a naive fixed based on patterns seen in other tests - run do_sync() in the before block so that exists stuff is already synced.
* Fix broken SSO tests
No
```sh
jetpack docker phpunit -- --testdox --filter=Jetpack_Sync_SSO
```
=> Fix broken SSO tests

projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssShowStopperError.svelte, projects/plugins/boost/app/modules/critical-css/class-critical-css-state.php, projects/plugins/boost/changelog/fix-boost-backwards-compatibility
Jetpack Boost 1.2.0 changes the way that Critical CSS errors are raised and stored, making them more consistent and appropriate for display in the new UI.
However, if there is old error data left in the database from a previous version, it can cause crashes or display issues in the current beta. 
This PR fixes the issue by filtering out old Critical CSS failure information, instead showing a very generic error message for these cases: 
This will only affect users who have previously had issues generating Critical CSS, and have since upgraded to 1.2.0. It will encourage them to try again, and they will then receive the updated error flow. 
* Filter out invalid Critical CSS error data, ensuring leftover old errors from previous versions do not cause crashes or display issues.
no
1. Install …
=> Boost: Prevent display issues / crashes from leftover Critical CSS Error data

projects/plugins/boost/.gitattributes, projects/plugins/boost/changelog/fix-boost-ignore-docker-folder-for-release
* Ignore the Docker folder from being added into production release
N/A
N/A
* Go to '..'
* Make sure that the `docker` folder does not appear in the https://github.com/Automattic/jetpack-boost-production repo
=> Boost: Ignore the Docker folder from being added into production release

projects/plugins/boost/app/assets/src/js/utils/load-critical-css-library.ts, projects/plugins/boost/changelog/fix-boost-load-gen-library-with-version
* Include Boost version as GET parameter when loading gen library to avoid caching issues
N/A
N/A
* Generate Critical CSS with Boost plugin version 1.1.1 with errors
* Upgrade to Jetpack Boost version 1.2.0 (Do not clear browser cache) and make sure that the UI is presenting error correctly.
=> Boost: Add versioning to the loading of the Critical CSS Gen library

projects/plugins/jetpack/changelog/fix-missing-textdomain-content-options, projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php
Fixes #20664
Let's use our own textdomain for now.
See this trac ticket for more info:
https://core.trac.wordpress.org/ticket/47511#comment:19
* No
* No
* Not much to test here, the string should not change.
=> Content Options: add missing textdomain for core string

projects/packages/connection/changelog/update-remove_tracked_packages_on_disconnect, projects/packages/connection/src/class-manager.php, projects/packages/connection/src/class-package-version.php, projects/packages/connection/tests/php/test_Manager_unit.php
Upon disconnecting a site, the `jetpack_package_versions` option should be removed as it depends on the Jetpack Connection.
* Updates `disconnect_site` method in `Jetpack\Connection\Manager` to remove the stored package versions.
1200561894344934-as-1200719679037708/f
No
D65339-code
=> Connection: Remove tracked DNA packages on disconnect

.github/files/gh-autotagger/workflows/autotagger.yml, .github/files/gh-npmjs-autopublisher/workflows/npmjs-autopublisher.yml
This was added in #20454 and #20455, but is causing issues when trying to run those actions in the mirror repos:
```
[36;1mif [[ -z "$TOKEN" ]]; then echo '::error::The secret API_TOKEN_GITHUB must be set.' exit 1 fi[0m
shell: /usr/bin/bash -e {0}
env:
TOKEN:
line 2: syntax error: unexpected end of file
```
* No
* N/A
* Nothing will change in the monorepo, we'll only see the result in the mirror repos once we merge this.
=> GitHub actions: add pipe to allow for multiline script run

projects/packages/connection/changelog/fix-connection-secrets-length, projects/packages/connection/src/class-secrets.php, projects/packages/connection/tests/php/test_Secrets.php
Fixes #20672
Jetpack connection requires that the secrets generated are 32 characters long. However, if a theme or plugin hooks into the `random_password` filter they can mess things up and return a shorter password, thus not allowing the site to connect.
This PR assures that the secrets generated have the right length in `Automattic\Jetpack\Connection\Secrets::secret_callable_method()`
* Connection: Make sure generated secrets have the required length
https://github.com/Automattic/jetpack/issues/20672
No
* kick off a new site on `master`
* Add the following code to your themes's `function.php` or as a mu-plugin
```PHP
add_filter( 'random_password', function( $pass ) { return substr($pass, 0, 6); } );
```
* Try to Connect Jetpack and confirm it fails (secret_1 is malformed)
* checkout …
=> Make sure generated secrets have the required length

projects/plugins/jetpack/changelog/adjust-where-beta-testing-is-shown, projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-p2-admin-menu.php, projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
Summary:
This is a follow-up to D63456 where the Beta Testing link was added to WPCOM.
This diff includes the following:
- adds it to Atomic sites
- removes the link from P2 sites
Test Plan:
* Sandbox `[private link]`
* Apply this patch
* Go to a P2 page (ex. https://wordpress.com/home/[private link])
* Delete the calypso IndexedDB database to ensure the latest menu items will be shown
* There **should not** be Beta Testing link in the sidebar menu
{F8980610}
Testing for Atomic is a bit trickier:
* Set up an ephemeral site [[ https://[private link] | here ]] and connect it to your WordPress account
* You'll need ssh into the site and copy the changed files into `~/wp-content/plugins/jetpack/modules/masterbar/admin-menu`
* Go to the site's Calypso dashboard (ex. …
=> Make Beta Testing link appear on Atomic but not on P2
