projects/github-actions/push-to-mirrors/.gitignore

Since it has a composer.json, if someone runs composer a composer.lock
and a vendor directory will be created. Ignore them.
None.
No.
* Run `composer install` in `projects/github-actions/push-to-mirrors/`. `git status` should not report any untracked files.
* None needed.

push-to-mirrors: Add .gitignore

---

projects/plugins/beta/class-jetpack-beta-admin.php

Fixes #18605
* Changes an instance of `printf` to `sprintf` that removes some unwanted copy in the welcome message. 
N/A
No.
* On a test site, activate the beta plugin
* See the `219` at the end of one of the welcome message sentences.
* Activate this branch
* See the `219` go away. 
**Before**
**After**
* Fixes some errant copy appearing in the beta plugin welcome message.

Beta Plugin: Fix Welcome Message

---

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php
projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php

Fixes https://github.com/Automattic/wp-calypso/issues/49350
* Truncates menu titles up to point of encountered html tags to avoid returning any unexpected HTML markup.
N/A
No
* Apply patch D56407-code to your Sandbox
* Create a site with Site Editor (`/new?flags=gutenboarding/site-editor`)
* Navigate to Calypso and observe before and after of the menu item "Site Editor" below which should be represented on your test site.
**Before**
**After**
N/A

Fix: Remove unexpected markup from menu titles

---

tools/git-hooks/post-merge-checkout-hook.sh

In the post merge hook, use the CLI commands.
* see above
n/a
n/a
* Switch to a branch with a change in a yarn.lock file (currently master works for me).
* Switch to this branch.
Result:
* n/a

Git Hooks: Use CLI commands

---

projects/plugins/jetpack/extensions/shared/components/media-player-control/index.js

This PR simply removes a useless CSS class initially added to tweak the control, but now it's not necessary anymore.
Fixes #
* Media Player Control: remove useless  CSS class
No
* Create a podcast player + a conversation/dialogue block
* Plays the player
* Confirm the media player control still looks there
MM:SS | HH:MM:SS
--------|--------
*

Media Player Control: remove useless  CSS class

---

projects/plugins/beta/README.md

Fixes p1612911218308400-slack-CBG1CP4EN
* It's important that the binary is `jetpack-beta.zip` for a couple places we direct link to it.
n/a
n/a
* None really.
* n/a

Beta: Improve release instructions

---

projects/plugins/jetpack/extensions/blocks/conversation/edit.js
projects/plugins/jetpack/extensions/blocks/conversation/utils.js

This PR fixes an issue when pasting text with format in the speaker input.
* Dialogue: clean format when pasting speaker label
* Start to edit a conversation/dialogue composition
* Copy a text with format style, for instance: **_RetroFox_**
* Confirm the text is pasted applying the format, but generating a dirty text.
* Confirm with these changes the format style is removed 
**before** | **after**
-------|---------
*

Dialogue: clean format when pasting speaker label

---

docs/development-environment.md
projects/packages/README.md
tools/docker/README.md

Fixes #18795
* Since #18593, we encourage folks to run tests locally for packages. Let's update the docs accordingly.
* N/A
* No
* Do the instructions make sense?
* N/A

Docs: update instructions to test packages

---

projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-feed-locator.php
projects/plugins/jetpack/_inc/lib/class-jetpack-podcast-helper.php
projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-podcast-player.php
projects/plugins/jetpack/extensions/blocks/podcast-player/api.js
projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js
projects/plugins/jetpack/extensions/blocks/podcast-player/edit.js
projects/plugins/jetpack/extensions/blocks/podcast-player/editor.scss
projects/plugins/jetpack/extensions/blocks/podcast-player/state.js
projects/plugins/jetpack/tests/php/_inc/lib/test-class-jetpack-podcast-feed-locator.php

This builds on #18670, which adds the basic episode selection UI, along with the changes needed to the API.
Feedback on that was that the episode selector shouldn't live in the placeholder, and that the sidebar is the most logical place.
This change puts the episode selector combobox in the sidebar with the other block settings.
There are still some things to iron out with the code, but it would be good to get some opinions on whether this still feels like the right approach.
* Use this branch, and add a podcast block to a post/page
* Play around with the settings and see how it feels!
* Check that swapping the RSS feed still works
* Podcast Player: Allow the episode to be selected from the block sidebar.

Podcast Player: Add the episode selector to the sidebar

---

projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js
projects/plugins/jetpack/extensions/shared/create-block-from-inner-blocks-template.js

Some new features uses [createBlocksFromInnerBlocksTemplate()](https://github.com/WordPress/gutenberg/blob/fe0ade060e3169e7aa3f4fd3f82e2d10c95d5619/packages/blocks/src/api/factory.js#L70) core function to create blocks from a template. Unfortunately, this function is not available for WordPress sites with `version 5.5`. This PR adds a helper function with fallback in case it isn't available to avoid breaking issues.
Fixes #
* Shared: add createBlocksFromInnerBlocksTemplate() fallback
No
* Disable the Gutenberg plugin in case you're working with it.
* Switch to WordPress `5.5`. If you use Jetpack env tool: `yarn docker:wp core update --version=5.5 --force`
* Create a new podcast episode using the following link:
```
http://localhost/wp-admin/post-new.php?action=edit&anchor_podcast=22b6608&a …
```

Shared: add createBlocksFromInnerBlocksTemplate() fallback

---

projects/plugins/jetpack/extensions/blocks/dialogue/edit.js

This PR fixes a bug when copy blocks and paste them into the dialogue content.
Fixes #
* Dialogue: fix copy/paste block into block content.
p7DVsv-atS-p2#comment-34461
No
* Create/Edit a post
* Create a random block
* Create Conversation/Dialogue blocks
Canvas | Outline
-----|----
* Copy the random block...
* ...and paste it into the Dialogue content
**before**
* The Dialogue block keeps empty
* There is an error in the dev console.
Canvas | Dev Console
------|------
**after**
* There are no errors in the dev console
* the blocks are pasted and now are children of the Conversation block
Canvas | Outline | Dev console
----|-----|-----
*

Dialogue: fix copy/paste block into block content

---

tools/cli/helpers/projectHelpers.js

We tried to match the regex documented at
https://getcomposer.org/doc/04-schema.md#name for allowed package names.
But somehow we lost the `/` in the middle. We really only wanted the
part after the slash: `^[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$`
But that wouldn't satisfy CodeQL. We could simplify that to the more
efficient `^[a-z0-9]+(([_.]|-{1,2})[a-z0-9]+)*$`
But that's not what Composer is actually using (or, AFAICT, has ever
used). They just use `^[a-z0-9_.-]+$`, see
https://github.com/composer/composer/blob/03e8cacd/src/Composer/Command/InitCommand.php#L239
None.
No.
* Does it still work?
* Is CodeQL happier now?
* None needed.

CLI: Fix CodeQL warning

---

projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/aquatic/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/classic-blue/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/classic-bright/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/classic-dark/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/contrast/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/nightfall/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/powder-snow/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/sakura/colors.scss
projects/plugins/jetpack/modules/masterbar/admin-color-schemes/colors/sunset/colors.scss
projects/plugins/jetpack/package.json
projects/plugins/jetpack/yarn.lock

* update color studio dependency to 2.4.0
* update color schemes to draw on color studio for color values
Since https://github.com/Automattic/wp-calypso/pull/49489 Calypso is using the latest version of Color Studio which added color tweaks to the Blue and Celadon colors that are being used by the Admin Color Schemes. For Nav Unification this is an issue as it means that the colors are now out of sync between Calypso and wp-admin. To bring them back into sync and at the same time make future maintenance easier, in this PR we're updating Admin Color Schemes to use Color Studio variables instead of hardcoded values. For full context see p9Jlb4-28F-p2.
Fixes https://github.com/Automattic/wp-calypso/issues/49826
* No
* Activate the `WordPress.com toolbar` in Jetpack Settings > Writing
* Go to …

Update Color Studio and make use of it in Admin Color Schemes

---

projects/plugins/jetpack/modules/comments/comments.php

* Follow-up to #18812. Let's update the reference to this constant.
* N/A
* No
* Go to Jetpack > Settings and enable the Comments module
* You should not see any Fatal error.
* N/A

Comments: update reference to token key

---

tools/cli/commands/generate.js
tools/cli/skeletons/github-actions/action.yml

CLI: Add Generate Github Actions

---

jetpack.php
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Update version numbers to start release cycle
* N/A
No
* N/A

General: update version numbers to start 9.5 release cycle

---

.github/workflows/build.yml

We currently trigger build on "push", which runs in the context of the
forked repo and so the PR doesn't see it as having run.
So also run on PR, but only for forked PRs.
p1614694771483300-slack-CBG1CP4EN
No.
* This PR itself is a forked PR, so see if the "Build all projects" job shows as having run.
* None needed.

Build: Build for forked PRs

---

tools/cli/commands/generate.js

Fixes #
* Refactors Jetpack Generate tool by DRY'ing the project generation.
N/a
No.
* Open your favorite shell
* Run `jetpack generate` 
* Follow the flow for creating a new project 
* Everything should work
* Try generating a project using the project and name flags, i.e. `jetpack generate plugin --name plugin-name`
* N/a

CLI: Refactors Jetpack Generate 

---

docs/monorepo.md

**Changes proposed in this Pull Request:**
Updates the monorepo.md doc to include Jetpack Generate instructions.
**Jetpack product discussion**
N/a
**Does this pull request change what data or activity we track or use?**
No.
**Testing instructions:**
- Read the monorepo doc
- You should be able to read it and see the updated instructions.
Proposed changelog entry for your changes:
N/a

Updates Monorepo Doc

---

.github/workflows/build.yml
.github/workflows/composer.yml
.github/workflows/e2e-tests.yml
.github/workflows/gardening.yml
.github/workflows/linting.yml
.github/workflows/phpcompatibility-dev.yml
.github/workflows/tests.yml

* Fix job skipping in Linting workflows. #18173 made a mistaken assumption that broke it.
* Always run the PHP lint jobs, the hack from #17940 breaks on forked PRs and the lint jobs are fast anyway.
* Cleanup CodeClimate env logic. It broke on forked PRs, and possibly was wrong on pushes too.
* Skip E2E tests for for forked PRs, they use secrets and so can't run successfully for forked PRs.
* Sync the code in various workflows that sets up PHP and Node. Now we'll always use the version from `.nvmrc` and `.github/php-version`.
None.
No.
* Do tests work?
* Make a forked PR based on this PR (or just look at #18980), does the Code coverage test work and does it skip E2E tests?
* None needed.

actions: Cleanup GitHub workflows

---

.github/files/build-all-projects.sh
tools/cli/commands/build.js

I was looking at build job logs and noticed there was little information on how the build actually went, just
2021-03-03T17:32:00.8157352Z [17:32:00] Building plugins/jetpack [started]
2021-03-03T17:34:34.9430343Z [17:34:34] Building plugins/jetpack [completed]
I thought we had added and used a verbose mode in CI, but it looks like that was in the context of using `jetpack install` rather than `jetpack build`.
Also, while testing this I wound up with the "linked" copy of the CLI being in /tmp, and got weird error messages about "Something is missing from your install". In other CI scripts we just run tools/cli/bin/jetpack directly when needed, so do that instead.
None.
No.
* Does the build still work?
* Do the logs contain more detailed information?
* None needed.

cli: Verbose build for CI

---

projects/plugins/jetpack/changelog.txt
projects/plugins/jetpack/readme.txt

* Changelog entries for 9.5.1 release
N/A
No
* This is it.

Changelog: add 9.5.1 entries

---

projects/packages/changelogger/lib/README.md

The changelogger tool includes a separable library for parsing and formatting changelogs. Add a README.md for it, mainly to point out that it is in fact separable if there's call for it.
None.
No.
* Proofread the readme.
* None needed.

changelogger: Add some docs for the included Changelog library

---

.github/workflows/linting.yml
tools/eslint-excludelist.json

It was looking at phpcs-excludelist.json twice, instead of looking at
eslint-excludelist.json the second time. Which caused it to not detect
that a JS file was fixed in #19001.
Also add a little more output into the GH logs.
None.
No.
* Make a PR based on this one fixing lints in a JS file. Does CI flag that eslint-excludelist.json should be updated?
* None needed.

CI: Fix bug in excluded files check

---

.github/actions/repo-gardening/src/tasks/add-labels/index.js

* Add "Docs" labels to edits made to files within /docs/
n/a
n/a
* On a PR based on this branch, make a change to a file in the /docs/ file.
* Create PR. See it work.
* Or merge and check next time we have a doc update.
* n/a

Repo Gardening: Auto-label docs changes

---

projects/plugins/jetpack/tests/php.multisite.xml

Jetpack: Use SpeedTrap in multisite tests
May as well get a list of slow tests there too.
None.
No.
* Look at the output from the Jetpack multisite test. See that a list of slow tests shows up, like it does for the normal tests.
* None needed.

Jetpack: Use SpeedTrap in multisite tests

---

projects/packages/changelogger/CHANGELOG.md
projects/packages/changelogger/changelog/add-start-using-changelogger
projects/packages/changelogger/changelog/add-versioning-with-changelogger
projects/packages/changelogger/changelog/initial-release
projects/packages/changelogger/composer.json
projects/packages/changelogger/src/Application.php
projects/plugins/jetpack/changelog/update-release-changelogger-1.0.0
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

Update changelogger for 1.0.0 release. After this is merged and mirrored, v1.0.0 should be tagged in the mirror repo.
None.
No.
* None

Update/release changelogger 1.0.0

---

projects/packages/changelogger/changelog/add-changelogs-for-everything.2

Crossed PRs wound up missing a change file that was supposed to be part
of 1.0.0.
None.
No.
* None.

changelogger: Fix 1.0.0 release

---

.github/workflows/e2e-tests.yml
projects/plugins/jetpack/changelog/update-e2e-improvements
projects/plugins/jetpack/tests/e2e/lib/env/playwright-environment.js
projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/jetpack.js
projects/plugins/jetpack/tests/e2e/lib/pages/wpcom/login.js
projects/plugins/jetpack/tests/e2e/lib/reporters/slack.js
projects/plugins/jetpack/tests/e2e/lib/utils-helper.js

* add missing await call to onFailure handler.
* Log apache logs from tests container.
* Update slack reporter retry policy to fail fast.
* retry wpcom login if any of the steps failed.
n/a
n/a
* Make sure tests are green
*

E2E Tests: minor improvements

---

projects/packages/autoloader/changelog/fix-autoloader-tests
projects/packages/autoloader/tests/php/lib/class-test-plugin-factory.php

Composer rebuilt the package which changed the hash. See
https://github.com/composer/composer/issues/9746#issuecomment-793984249.
p1615303604201500-slack-CBG1CP4EN
No.
* Do tests pass now?

autoloader: Update composer 2.0.9 hash in tests

---

.github/files/list-changed-projects.php
.github/files/require-change-file-for-touched-projects.php

GH displays it on a background of a slightly different gray that makes
it almost unreadable.
None.
No.
* Look at the logs for the relevant CI jobs. Can the debug output be read?

CI: Don't use dark grey as a "debug" color in CI

---

.github/actions/repo-gardening/src/tasks/wpcom-commit-reminder/index.js

`diffId` will be null if there is no match.
Followup to #19101.
None.
No.
* This runs on push to master, so merge and see?

Actions: Fix error in commit-reminder check

---

.github/actions/repo-gardening/src/tasks/add-milestone/index.js

Rather than raising an error about it, detect this situation and abort.
None.
No.
* Since this runs on push to master, merge and watch?

Actions: Don't try to add a milestone if there are no plugins

---

.github/workflows/linting.yml

PR #18979 did a bunch of cleanup, then #18945 added some new jobs that
had been done in the pre-cleanup style. Clean them up too.
None, but see #18979.
No.
* Is CI happy?

ci: Sync fetching of PHP and Node in new linting jobs

---

tools/docker/bin/install.sh

The Core Control plugin is another really handy one to help when debugging situations. Adding this to what gets installed during Docker setup.
* Adds Core Control to Docker.
p9dueE-2zM-p2
No.
* `yarn docker:clean && yarn docker:up` (warning: this will delete your docker).
* Make sure Core Control is there.

Docker: Add Core Control plugin

---

docs/development-environment.md

* Minor docs update.
n/a
n/a
* n/a

Bump docs to mention Node 12.

---

projects/packages/password-checker/.gitattributes
projects/packages/password-checker/CHANGELOG.md
projects/packages/password-checker/changelog/add-changelogger-to-password-package
projects/packages/password-checker/composer.json

We're wanting to use it for every project.
p9dueE-2qL-p2
1199658893173824-as-1199910496214526
No.
* Is changelogger happy in CI?

password-checker: Add changelogger

---

.github/actions/repo-gardening/src/get-plugin-names.js
.github/actions/repo-gardening/src/tasks/add-milestone/index.js
.github/actions/repo-gardening/src/tasks/check-description/index.js

﻿* Add in more debugging comments.
﻿* Better handle plugin names with spaces in them.
* Display the plugin name with capitals in the description check comment.
* Do not try to add a milestone to a merged PR if it touches multiple plugins. The milestone will not give useful information as to when the PR will be shipped, since it will be shipped to multiple places.
* N/A
* No
* See the comment in #19148.

Gardening: clean up milestone management.

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-changelog-952
projects/plugins/jetpack/readme.txt

* This PR updates the readme with the most recent changes made for the 9.5.2 release.
* N/A
* No.

General: Update changelog for internal point release

---

projects/plugins/jetpack/changelog/add-related-posts-tests
projects/plugins/jetpack/extensions/blocks/related-posts/controls.js
projects/plugins/jetpack/extensions/blocks/related-posts/edit.js
projects/plugins/jetpack/extensions/blocks/related-posts/test/controls.js
projects/plugins/jetpack/extensions/blocks/related-posts/test/edit.js
projects/plugins/jetpack/extensions/blocks/related-posts/test/fixtures/jetpack__related-posts.html
projects/plugins/jetpack/extensions/blocks/related-posts/test/fixtures/jetpack__related-posts.json
projects/plugins/jetpack/extensions/blocks/related-posts/test/fixtures/jetpack__related-posts.parsed.json
projects/plugins/jetpack/extensions/blocks/related-posts/test/fixtures/jetpack__related-posts.serialized.html
projects/plugins/jetpack/extensions/blocks/related-posts/test/validate.js

* Pulls settings out of the block into a Controls component for simplification/separate testing
* Adds tests
p1HpG7-b3G-p2
* Run tests from the projects/plugins/jetpack folder with:
```
yarn jest extensions/blocks/related-posts/test/edit.js
yarn jest extensions/blocks/related-posts/test/controls.js
yarn jest extensions/blocks/related-posts/test/validate.js
```
* Manually test the Related Posts block, especially focusing on updating attributes in the Inspector controls and block toolbar.

Related Posts: Add unit tests

---

.github/workflows/build.yml

Time needed seems to have increased since January 2021.
None.
No.

actions: Increase timeout for "Build all projects"

---

.github/actions/repo-gardening/readme.md

That readme hadn't been updated with the newly created tasks we added to that action. This changes that.
* N/A
* No

Gardening: update readme to mention new tasks

---

.github/workflows/gardening.yml

Fixes #19099
Such runs can end up conflicting with each other, as outlined in the issue above.
* N/A
* No
* Examine actions for this PR, which will be created with some labels already.

Gardening: avoid duplicated runs of the action

---

tools/changelogger-validate-all.sh

If `changelogger version` returns an error, flag it in a way that will
be noticed.
p1616096895158800/1616015585.089400-slack-CBG1CP4EN
No.
* Try it with a PR that has such an error, e.g. a missing CHANGELOG.md.

tools: Highlight errors from `changelogger version` in changelogger-validate-all.sh

---

.github/actions/repo-gardening/package.json
.github/actions/repo-gardening/src/get-affected-changelogger-projects.js
.github/actions/repo-gardening/src/get-files.js
.github/actions/repo-gardening/src/get-next-valid-milestone.js
.github/actions/repo-gardening/src/tasks/add-labels/index.js
.github/actions/repo-gardening/src/tasks/check-description/index.js

* Add check for changelog entries
* Refactor checks and recommendations rendering
* Fix few issues with Milestone detection and outptut.
n/a
n/a
* Check the bot comment in this test PR: https://github.com/Automattic/jetpack/pull/19200
* Make changes to projects with and without changelogger, make sure the check reflects that

Actions: Add changelog entry check for Repo Gardening action

---

.github/actions/repo-gardening/src/tasks/check-description/index.js

The paths in `files` are relative to the monorepo root, so make the
string we're looking for so relative too.
p1616434195281100/1616427747.259300-slack-CBG1CP4EN
No.
* Create a PR touching projects, with change files. See that it doesn't incorrectly claim it needs change files.

repo-gardening: Fix changelog file check

---

.github/actions/repo-gardening/src/tasks/check-description/index.js

Since the comment from the action can be quite long, let's highlight anything that needs to change with some bold and an additional emoji.
﻿See p1616432372272500-slack-jetpack-crew
* No
* See this PR for a failing comment and a check: #19247

Gardening: highlight recommendations with bold and emoji

---

projects/packages/blocks/CHANGELOG.md
projects/packages/blocks/changelog/add-changelogs-for-everything
projects/packages/blocks/changelog/add-editor-style-dependency-when-registering-jetpack-blocks
projects/packages/blocks/changelog/add-enable-package-autotagger-to-test
projects/packages/blocks/changelog/fix-cli-composer-install-vs-update
projects/packages/blocks/changelog/update-branch-alias-all-packages
projects/packages/blocks/changelog/update-changelogger-allow-unreleased-date
projects/packages/blocks/composer.json
projects/packages/changelogger/CHANGELOG.md
projects/packages/changelogger/changelog/add-enable-package-autotagger-to-test
projects/packages/changelogger/changelog/fix-cli-composer-install-vs-update
projects/packages/changelogger/changelog/fix-project-version-exit-code
projects/packages/changelogger/changelog/update-branch-alias-all-packages
projects/packages/changelogger/changelog/update-changelogger-allow-unreleased-date
projects/packages/changelogger/src/Application.php
projects/plugins/jetpack/changelog/update-blocks-release
projects/plugins/jetpack/composer.lock

﻿This also releases a new version of the Changelogger, which is a dependency.
* N/A
* No

Packages: release a new version of the Blocks package

---

projects/packages/changelogger/changelog/fix-changelogger-version
projects/packages/changelogger/src/Application.php

PR #19242 did a release while #19252 was merged on the basis of
pre-release check runs so it didn't get bumped with the latter.
None
No
* Is CI happy?

changelogger: Bump version

---

.github/workflows/linting.yml

The checks were being incorrectly skipped because they didn't declare
that they need the "detect changed files" job, and unfortunately GH
didn't complain about the attempt to access a missing value.
None
No
* Make a PR touching a composer.json, composer.lock, package.json, or yarn.lock. Does the check run?
Closes #19277

linting: Add missing "needs" in linting workflow

---

.github/files/lint-project-structure.sh

Fix typo in lint-project-structure.sh
Fortunately it doesn't affect the actual functioning of the script, just
the debug output.
None
No
* Look at the output of the "Run .github/files/lint-project-structure.sh" step in the "Project structure", e.g. [here](https://github.com/Automattic/jetpack/runs/2185537914?check_suite_focus=true#step:3:6). It should have actual output instead of a lot of lines saying `%@`.

actions: Fix typo in lint-project-structure.sh

---

.github/actions/repo-gardening/src/tasks/check-description/index.js

Don't check renovate's PR's descriptions. It won't ever pass, and we don't care.
None
No
* Merge this, then trigger renovate to create or rebase a PR.

gardening: Don't check renovate's description

---

tools/cli/commands/changelog.js

* Adds "choices" for accepted changelogger commands via the CLI. This allows them to be printed in the help text.
n/a
No
* `jetpack changelog` and see the help text.
* `jetpack changelog nope` to see the error for an invalid choice.

CLI: Add choices for Changelog cmd

---

.github/files/lint-project-structure.sh
.github/renovate.json
.github/workflows/linting.yml
tools/check-renovate-ignore-list.js
tools/git-hooks/pre-commit-hook.js

There's no point in having renovate mess with these, we have other
scripts that keep them all up to date.
And use the pre-commit hook and CI to keep the ignore list up to date.
https://github.com/Automattic/jetpack/pull/19242#issuecomment-804285761
No
* Merge, then trigger renovate to re-run #19291 and see what happens?

renovate: Ignore all monorepo packages

---

.github/files/lint-project-structure.sh
tools/cli/commands/generate.js

Require that all packages specify a branch-alias by checking for it in the existing "Project structure" check.
Also have the CLI generate command add the branch alias to new packages.
None.
No.
* Try removing the branch-alias from a package, or creating a new package without one.
* Confirm that `jetpack generate` for a package includes a branch-alias.

linting: Require that all packages specify a branch-alias

---

tools/check-composer-deps.sh
tools/includes/chalk-lite.sh

Only print the ending "tools/check-composer-deps.sh -u" suggestion at
the very end, not after each slug.
Also fix the tput call in chalk-lite to not complain if $TERM is not
set.
None
no
* Make a PR that will have errors from check-composer-deps.sh for multiple packages. Check the output.

tools: Fix check-composer-deps.sh output

---

tools/check-renovate-ignore-list.js

Adds some additional detail to the error messages.
*
n/a
no
* Add an extra line with a fake package to .github/renovate.json around L13.
* See the error message.

Renovate: Clarify the error messages

---

projects/plugins/jetpack/_inc/client/components/forms/styles.scss
projects/plugins/jetpack/_inc/client/traffic/index.jsx
projects/plugins/jetpack/_inc/client/traffic/seo.jsx
projects/plugins/jetpack/_inc/client/traffic/seo/custom-seo-titles.jsx
projects/plugins/jetpack/_inc/client/traffic/seo/test/component.js
projects/plugins/jetpack/_inc/client/traffic/style.scss
projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php
projects/plugins/jetpack/changelog/add-seo-wpadmin-settings
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
projects/plugins/jetpack/modules/seo-tools/jetpack-seo-titles.php
projects/plugins/jetpack/package.json
projects/plugins/jetpack/yarn.lock

* Make the SEO Tools module settings available in WP Admin; currently WP Admin links to Calypso for these settings.
* Builds upon https://github.com/Automattic/jetpack/pull/17309
* Internal PT: p1HpG7-ba8-p2
No
1. Pull down these changes on a Jetpack connected site.
2. Observe the SEO Tools settings from the Calypso management page at `wordpress.com/marketing/traffic/__SITE_URL__`
3. Make sure the SEO Tools module is turned on `Enable SEO Tools to optimize your site for search engines`
4. Set some custom `Page Title Structure` values for each page-type/section (e.g. Front Page, Archives, etc.); be sure to use some of the buttons to insert the dynamic values (e.g `+ Site Title`, `+ Tagline`, etc.)
5. Navigate to the equivalent WP Admin settings page at …

SEO: Add module settings to WP Admin

---

.github/files/gh-autotagger/workflows/autotagger.yml
projects/github-actions/push-to-mirrors/changelog/update-actions-avoid-git-config-global
projects/github-actions/push-to-mirrors/push-to-mirrors.sh

We can accomplish the same by setting environment variables.
None
No
* Could try running things locally, but "merge and observe" is probably the best bet.

actions: Avoid `git config --global`

---

.github/files/renovate-helper.sh
.github/renovate.json
.github/workflows/renovate-helper.yml

When renovate pushes one of its dependency updates, it will be lacking
the required changelogger change files. This action has matticbot add
those files.
None
No
* See that the new job is skipped on this PR, as this isn't a renovate PR.
* Merge, then trigger renovate to rebase some of its PRs.

renovate: Helper action to add change files to renovate PRs

---

tools/cli/helpers/tasks/installProjectTask.js

Yarn by default does not handle concurrent runs well, like what we do
for the CLI `jetpack install --all`. Multiple processes accessing the
same cache entry can interfere with each other leading to strange
errors.
The official workaround for that is to pass `--mutex` to yarn to have it
serialize its own runs (everything, not just the cache access,
unfortunately), rather than yarn implementing locking in the cache
accessing itself and using it by default.
See https://github.com/yarnpkg/yarn/issues/683 and https://github.com/yarnpkg/yarn/issues/4102
for details.
Since the yarn developers are uninterested in fixing any remaining bugs
in yarn (they've moved on to "yarn 2" aka "berry"), there's not even any
point in trying to get it fixed upstream.
None
No
* Run `jetpack install --all` and see …

cli: Work around yarn cache concurrency bug

---

projects/plugins/jetpack/changelog/add-readme-969
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json
projects/plugins/jetpack/readme.txt

* Following-up from #19342, let's update the readme now. 
* N/A
* No
* Not much to test here, this should be a straight copy from the changelog that was already reviewed.

9.6: update readme to new changelog

---

docs/writing-a-good-changelog-entry.md

As of Jetpack 9.7 we're including non-user-facing changes in a section
for that purpose. So update the docs to reflect that.
#19131
No
* Read the doc.

docs: Update "Writing a good changelog entry" doc

---

.github/workflows/pr-is-up-to-date.yml

Always checkout master, even on tag pushes.
Pass the matticbot token to .github/files/pr-update-to.sh so the push
to the tag triggers the workflow to re-run (the default token suppresses
action triggering).
Merge the two jobs, only one will ever run anyway and this avoids
showing another skipped job on every PR (and they aren't long enough
that it's a readability issue).
None
No
* Merge and observe again.

actions: Rework pr-is-up-to-date workflow

---

.github/files/pr-update-to.sh
.github/workflows/pr-is-up-to-date.yml

We're still not getting the automated tag update to trigger the action
that's supposed to fire on push to the tag. Let's try setting the token
on the action/checkout call instead of doing `git remote set-url`.
None
No

actions: Set token on pr-is-up-to-date checkout

---

projects/github-actions/repo-gardening/CHANGELOG.md
projects/github-actions/repo-gardening/changelog/add-gardening-editorial-task
projects/github-actions/repo-gardening/changelog/add-rna-connection-in-place
projects/github-actions/repo-gardening/changelog/expand-gardening-clean-labels
projects/github-actions/repo-gardening/changelog/update-autotagger-for-actions
projects/github-actions/repo-gardening/changelog/update-gardening-action-extract
projects/github-actions/repo-gardening/changelog/update-gardening-action-setup
projects/github-actions/repo-gardening/changelog/update-gardening-required-parameters
projects/github-actions/repo-gardening/composer.json
projects/github-actions/repo-gardening/package.json

﻿This should allow us to start using a stable version of the action in other repos. See the conversation in https://github.com/Automattic/vaultpress/pull/113 to find out more.
* N/A
* No
* The action should keep working on this PR.

Repo Gardening: release version 1.1.0

---

.github/workflows/build.yml

We don't use tags in the monorepo for releases and such anymore, as that
happens in the mirror repos instead. But we are starting to use tags for
repo management, and there's no point in wasting time building them when
we've probably already built for the branch.
None
No
* Make sure the build-on-push job ran for this PR.
* Merge this.
* Push a tag. Is a build job triggered?

build: Only build branches and PRs, not tags

---

projects/github-actions/pr-is-up-to-date/CHANGELOG.md
projects/github-actions/pr-is-up-to-date/changelog/add-pr-up-to-date-check
projects/github-actions/pr-is-up-to-date/changelog/fix-pr-up-to-date
projects/github-actions/pr-is-up-to-date/changelog/update-autotagger-for-actions

Release v1.0.0
None
No
* Merge, then make sure the autotagger tagged the mirror repo properly.

pr-up-to-date: Release v1.0.0

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/add-readme-969
projects/plugins/jetpack/changelog/fix-admin-menu-check-position
projects/plugins/jetpack/changelog/fix-admin-menu-styles-dependencies
projects/plugins/jetpack/changelog/fix-payments-connect-to-stripe
projects/plugins/jetpack/changelog/fusion-sync-yoavf-D59714-code-1617527
projects/plugins/jetpack/changelog/fusion-sync-yoavf-r223672-wpcom-1617271820
projects/plugins/jetpack/changelog/remove-jsonp-check
projects/plugins/jetpack/changelog/try-jetpack-changelog-backend-section
projects/plugins/jetpack/changelog/update-changelog
projects/plugins/jetpack/changelog/update-changelog-link
projects/plugins/jetpack/changelog/update-final-changelog-96
projects/plugins/jetpack/readme.txt

* This PR brings in the changes that we made to the changelog for the 9.6 release, from the PRs that were cherry-picked to the release branch.
* N/A
* No

Changelog: final changes for the 9.6 release

---

projects/plugins/jetpack/changelog/update-readme-seo
projects/plugins/jetpack/readme.txt

Fixes #19452
* Updates readme.txt to remove SEO as a paid feature
n/a
n/a
* n/a
*

Readme: Remove ref to SEO as paid

---

projects/plugins/jetpack/changelog/fix-e2e-docs-typos
projects/plugins/jetpack/tests/e2e/README.md

Fix a couple of errors in the E2E documentation.
No.
Read the amended documentation.

Docs: fix typos in E2E README

---

.github/files/check-lock-files.sh
.github/workflows/linting.yml
yarn.lock

Apparently `yarn install --frozen-lockfile` doesn't always "fail if an
update is needed" as documented. Sometimes it instead just ignores the
update. So check for `yarn install` producing a diff instead, like we do for composer.
Then update yarn.lock after #19161.
None.
No.
* Is CI happy?

linting: Improve check for yarn.lock being up to date

---

projects/packages/a8c-mc-stats/CHANGELOG.md
projects/packages/a8c-mc-stats/changelog/2021-03-30-16-43-23-939963
projects/packages/assets/CHANGELOG.md
projects/packages/assets/changelog/2021-03-30-16-43-23-939963
projects/packages/changelogger/CHANGELOG.md
projects/packages/changelogger/changelog/fix-changelogger-extra-newlines
projects/packages/changelogger/src/Application.php
projects/packages/connection/CHANGELOG.md
projects/packages/connection/changelog/2021-03-30-16-43-23-939963
projects/packages/connection/changelog/fix-rest-authentication-infinite-loop
projects/packages/connection/changelog/fix-token-validation-logic
projects/packages/constants/CHANGELOG.md
projects/packages/constants/changelog/2021-03-30-16-43-23-939963
projects/packages/heartbeat/CHANGELOG.md
projects/packages/heartbeat/changelog/2021-03-30-16-43-23-939963
projects/packages/options/CHANGELOG.md
projects/packages/options/changelog/2021-03-30-16-43-23-939963
projects/packages/roles/CHANGELOG.md
projects/packages/roles/changelog/2021-03-30-16-43-23-939963
projects/packages/status/CHANGELOG.md
projects/packages/status/changelog/2021-03-30-16-43-23-939963
projects/packages/terms-of-service/CHANGELOG.md
projects/packages/terms-of-service/changelog/2021-03-30-16-43-23-939963
projects/packages/tracking/CHANGELOG.md
projects/packages/tracking/changelog/2021-03-30-16-43-23-939963
yarn.lock

Release a new version of the package to be able to ship #19439 with 9.6.1.
**Note** This also includes a yarn.lock update, but this should be fixed with #19456 
* N/A
* No

Connection: release a new version of the package and dependents

---

projects/packages/connection/CHANGELOG.md
projects/packages/connection/changelog/fix-nonce-cleanup-zero

This is a compiled changelog for the 1.25.2 version of the Connection package, including a cherry-picked fix from #19513. This has already been committed to the release branch in 1bea651d9bfdd170a3890bd116af97e3d4bfdb1e.
* N/A
* No

Connection: Changelog for 1.25.2 release

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-cover-block-paid-block-media-placeholder-flex-child
projects/plugins/jetpack/changelog/fix-search-excluded-post-types-pagination-bug
projects/plugins/jetpack/changelog/fix-search-ie11-bugs
projects/plugins/jetpack/changelog/fix-sharing-offline-mode
projects/plugins/jetpack/changelog/fix-stats-bug
projects/plugins/jetpack/changelog/fusion-sync-yoavf-D59840-code-1617790596
projects/plugins/jetpack/changelog/update-961-readme
projects/plugins/jetpack/changelog/update-admin-menu-sync-wpcom
projects/plugins/jetpack/changelog/update-readme-seo
projects/plugins/jetpack/changelog/update-seo-meta-char-count
projects/plugins/jetpack/changelog/update-show-links-manager-with-invisible-links
projects/plugins/jetpack/changelog/update-spinner-component-to-core
projects/plugins/jetpack/readme.txt

* This is the changelog for the 9.6.1 release.
* Note that it already includes #19513.
* N/A
* No

Changelog: update for 9.6.1 release

---

tools/docker/bin/install.sh

* Adds Gutenberg to the Jetpack Docker default install. To aid in testing with Gutenberg and upcoming Core changes (e.g. FSE)
n/a
No.
* n/a
*

Docker: Install Gutenberg

---

projects/github-actions/repo-gardening/CHANGELOG.md
projects/github-actions/repo-gardening/changelog/add-gardening-oss-label
projects/github-actions/repo-gardening/changelog/update-gardening-check-progress-label
projects/github-actions/repo-gardening/package.json

﻿* This will allow other repos to use the new task introduced in #19382.
* p3btAN-1nR-p2#comment-13830
* D60289-code
* No
* Not much to test here, just check the changelog for typos.

Gardening: release a new version of the action.

---

projects/plugins/jetpack/changelog/add-field-for-zendesk-meta
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php

This PR syncs rWP224304/  D59613-code.
(Follows the instructions in the commit process on syncing code to or from Jetpack for a file also distributed in Jetpack).
Adds new field to get zendesk meta in the /me/sites API for mobile apps.
p3hLNG-18e
No change.
Changes tested according to the test plan included in D59613

Add a field for zendesk meta in the me/sites API

---

tools/jetpack-live-branches/jetpack-live-branches.user.js

* Adds support in Live Branches to auto-install TT1-Blocks
n/a
No
* Using TamperMonkey, etc install the script on this branch. (Direct link to the raw: https://github.com/Automattic/jetpack/raw/0d66928028fc2fffde924e342f03bc0a50dacc3b/tools/jetpack-live-branches/jetpack-live-branches.user.js )
* On a PR, see the TT1-Blocks checkbox.
* Use it.
* On the JN site that opens, comfirm the theme is installed (not activated) under Appearance->Themes

Live Changes: Add support for installing TT1-Blocks

---

.github/files/renovate-helper.sh

We use prettier to ensure a consistent formatting of the JSON files. The lack of it is causing #19610 to fail.
None
No
* Rebase #19610 on this and see if it works. Or merge this then trigger renovate to do the rebase.

renovate-helper: Needs yarn install for prettier

---

.github/workflows/e2e-tests.yml
projects/plugins/jetpack/changelog/e2e-testspace-folders

Group results in Testspace under folders based on our matrix values.
n/a
no
* CI happy.
* In Testspace the results are grouped in folders.

e2e: Use folders in Testspace

---

projects/plugins/jetpack/changelog/fix-e2e-fix-hover-action
projects/plugins/jetpack/tests/e2e/lib/pages/page-actions.js

Fixed the hover action calling the wrong Playwright page action.
n/a
no
* All E2E tests pass

E2E: Fix hover action

---

to-test.md

* Add testing list for the upcoming Jetpack release.
* N/A
* No

Jetpack 9.7: add testing list

---

projects/plugins/jetpack/changelog/add-9.8-alpha
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

- Bump version
- Changelog
Bumps version.
* ver bump
n/a
no
* Go to '..'
*

Jetpack: Ver bump to 9.8-alpha

---

docs/monorepo.md

* Avoid GH linkifying pseudo-URLs by interrupting them with a &lt;span>.
* One place where a single-quote was used instead of a backquote,
throwing off the inline-code markup.
Discussed in code review on #19682
No
* Look at the rendered version of the file, does it look right?

docs: Fix typos in monorepo.md

---

projects/packages/jitm/CHANGELOG.md
projects/packages/jitm/changelog/update-jitm_use_connection_auth_url
projects/packages/jitm/src/class-jitm.php

* Update JITM package for Jetpack 9.7 release.
* This will allow us to include the changes from #19720 into that release.
* N/A
* No
* Not much to test here, check for typos
* Check that the version number is correct.

JITM: update package version (see #19720)

---

projects/plugins/jetpack/changelog/add-insta-oembed-note
projects/plugins/jetpack/modules/shortcodes/instagram.php

* Adds a version number to remove our removal of Core oembed support. Core dropped Insta in 5.5.2, so once 5.6 is our min ver, we can remove these lines/comment.
n/a
no
* none
*

Embeds: Note when to remove our removal of Core Insta

---

projects/plugins/jetpack/_inc/lib/debugger/class-jetpack-cxn-tests.php
projects/plugins/jetpack/changelog/update-sync-site-health-messages

In our connection tests we reference running a Full Sync which is outdated nomenclature that can mislead support. This patch updates Full Sync references to use the fix nomenclature of updated support tooling.
Update Full Sync references to fix
NO
Verify spelling and phrasing.

Update Full Sync references to fix nomenclature.

---

.github/workflows/linting.yml

I've seen it get cancelled a time or two lately, it seems the runtime is
getting close to the current limit.
p1620320214350000-slack-CBG1CP4EN
No
* N/A

linting: Update timeout for "Check linter exclude lists"

---

tools/check-copied-files.sh

When that script is run from the git precommit hook, we shouldn't fail
the commit just because jq is missing as it's not exactly a standard
tool. But print a warning about it.
When it's run in CI, however, we do want to fail if jq is somehow
missing. Not that several other CI checks won't also fail in that
case, but the nicer error message is probably good.
p1620321043351600/1620320214.350000-slack-CBG1CP4EN
No
* Uninstall jq, then try to commit something. It should warn but not block the commit.

tools: Check for jq before using it in check-copied-files.sh

---

projects/plugins/jetpack/changelog/update-plugin-name
projects/plugins/jetpack/class.jetpack.php
projects/plugins/jetpack/jetpack.php

Per request from Rob Pugh, remove "by WordPress.com" from the plugin name and update the description.
* Update the plugin name.
n/a
n/a
* Verify the updated name in the Plugins list.

General: Update the Jetpack plugin name

---

projects/plugins/jetpack/changelog/update-desc
projects/plugins/jetpack/class.jetpack-connection-banner.php
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/readme.txt

Fixes https://github.com/Automattic/jetpack/pull/19822#issuecomment-839747973
* Removes "the" from the description.
p1620818588110700/1620771107.102600-slack-GQK64C7B4
n/a
* n/a
*

General: Update description

---

docs/development-environment-cli-support.md
docs/development-environment.md
tools/docker/README.md

Updating some docs early. We're going to be moving away from yarn, but the `jetpack` commands already work. Might as well update the docs now to prime the engine.
* Suggest `jetpack` CLI usage in our docs.
n/a
n/a
* n/a
*

Docs: Use CLI instead of yarn docker:

---

.github/workflows/e2e-tests.yml

While back when I added scheduled Gutenberg tests, I probably messed up the rebase, and the Gutenberg install script started to fail, which wasn't obvious due to scheduling.
* Fix Gutenberg installation script
n/a
n/a
* Check E2E run where "Set up Gutenberg" is running: https://github.com/Automattic/jetpack/pull/19864/checks?check_run_id=2601440805
*

E2E Tests: Fix scheduled gutenberg builds 

---

.github/workflows/build.yml

Broken in #19855, I misunderstood what was happening there.
p1621437875049000/1621422067.039000-slack-CBG1CP4EN
No
* Merge this, then look at the Build job that runs in response to the master push.

build: Push to JP Beta on push to master as well

---

tools/cli/skeletons/github-actions/.gitattributes
tools/cli/skeletons/packages/.gitattributes
tools/cli/skeletons/plugins/.gitattributes

The `production-include` and `production-exclude` tag files, not
directories, so `/**` is needed if you want to tag everything in a
directory. Add a comment pointing that out.
p1621451543068000-slack-CBG1CP4EN
No
* Do `jetpack generate` and see that the generated project has these comments in `.gitattributes`.

cli: Add comment to generated .gitattributes

---

projects/github-actions/repo-gardening/changelog/update-repo-gardening-labels-boost
projects/github-actions/repo-gardening/src/tasks/add-labels/index.js

﻿
This will allow us to start using the task in the Jetpack Boost repo.
* N/A
* No
* I would recommend checking the changes and ensuring they match the file structure in the Jetpack Boost repo.
* We can also check and ensure this PR still gets labeled properly.

Repo Gardening: extend the label configuration we support

---

projects/plugins/jetpack/changelog/e2e-fix-typo-e2e-infra
projects/plugins/jetpack/tests/e2e/bin/container-setup.sh

Fixes #
Fix wrong command name in `container-setup.sh` script usage 
n/a
n/a
n/a

Fixed typo in script usage

---

docs/development-environment.md

Just noticed that we didn't bump this when we did the rest of the node 12->14 changes.
* Updates docs.
n/a
n/a
* n/a

Docs: Update Node version

---

projects/github-actions/repo-gardening/CHANGELOG.md
projects/github-actions/repo-gardening/changelog/fix-boost-module-name
projects/github-actions/repo-gardening/package.json

﻿This will be needed to ship the fix from #19908
* N/A
* No
* Not much testing to do here. Check for typos.

Repo gardening: release new version

---

projects/packages/jitm/changelog/remove-filter_from_redirect
projects/packages/jitm/composer.json
projects/packages/jitm/src/class-jitm.php
projects/packages/redirect/changelog/remove-filter_from_redirect
projects/packages/redirect/composer.json
projects/packages/redirect/src/class-redirect.php
projects/plugins/jetpack/changelog/remove-filter_from_redirect
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

* Removes an unused and unnecessary filter from the Redirect package
p1621589592143400-slack-CBG1CP4EN
No
* Are the tests passing?

Remove filter from redirect

---

to-test.md

* Update Jetpack 9.8 `to-test.md` testing list.
N/A
No.
* General proofreading checking for typos, clarity, or info that should be added/removed.

Jetpack 9.8: add testing list

---

projects/plugins/jetpack/changelog/add-init-99-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init 9.9-alpha release cycle
* N/A
* No.
* N/A

Jetpack 9.9 init new cycle

---

projects/packages/jitm/changelog/kraftbj-patch-2
projects/packages/jitm/src/class-jitm.php

We use x.y.z, not x.y. This patch cleans up the UI for developer.jetpack.com.
* see above
* n/a
no
* n/a

JITM: Update inline doc version number

---

projects/plugins/jetpack/changelog/fix-carousel-comments
projects/plugins/jetpack/modules/carousel/jetpack-carousel.php

﻿- Carousel: harden fetching comments in Carousel view
- Add changelog
* Internal reference: p3btAN-1rn-p2
No
* See p1622482214015000-slack-C01U2KGS2PQ

Carousel: harden fetching comments.

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-9.8-story-block-notice-message
projects/plugins/jetpack/changelog/fix-carousel-comments
projects/plugins/jetpack/changelog/fix-invalid-media-only-styles-amp
projects/plugins/jetpack/changelog/fix-jetpack-search-photon-svg
projects/plugins/jetpack/changelog/fix-posts-page-icon
projects/plugins/jetpack/changelog/story-block-fix-muted
projects/plugins/jetpack/readme.txt

* This ports back the changes that were made in the release branch to `master`.
* N/A
* No
* Not much to test, this has already been pushed with the release branch.

Changelog: update with changes from 9.8 release branch

---

package.json
pnpm-lock.yaml
projects/plugins/jetpack/changelog/update-vulnerable-js-deps
projects/plugins/jetpack/package.json
projects/plugins/jetpack/tests/e2e/pnpm-lock.yaml

* browserslist to 4.16.6
* ssri to 7.1.1
* swiper to 6.7.0
* Remove markdown-spellcheck dep
It seems to only be used for a "test-spelling" script that I haven't
heard of anyone using, and the package itself hasn't been updated in
years and has dependencies with vulnerabilities.
postcss and url-regex will have to wait for updates to the things that
depend on them.
Also, in the separate projects/plugins/jetpack/tests/e2e/ workspace,
* hosted-git-info to 2.8.9
* ws to 7.4.6 where possible
Did this after seeing that GitHub's dependabot doesn't understand pnpm in #19928.
No
* Do things depending on these things still work? Particularly the slideshow block that uses swiper.

Update vulnerable JS deps as identified by `pnpm audit`

---

pnpm-lock.yaml
projects/packages/connection-ui/babel.config.js
projects/packages/connection-ui/changelog/fix-babel-transform-runtime-absoluteRuntime
projects/packages/connection-ui/package.json
projects/plugins/backup/babel.config.js
projects/plugins/backup/changelog/fix-babel-transform-runtime-absoluteRuntime
projects/plugins/backup/package.json

@babel/plugin-transform-runtime needs `absoluteRuntime` set when we link
to other monorepo JS packages. Calypso-build uses this plugin, but does
not set the option (https://github.com/Automattic/wp-calypso/issues/53353).
Copy our hack from Jetpack to plugins/backup and packages/connection-ui.
Also add deps on @babel/runtime, since correct use of
@babel/plugin-transform-runtime requires that.
p1622664503183600-slack-CBG1CP4EN
No.
* Check that the following pages work without reporting errors about @babel/runtime stuff not being found:
* /wp-admin/tools.php?page=jetpack-backup
* /wp-admin/tools.php?page=wpcom-connection-manager

backup, connection-ui: Set absoluteRuntime for @babel/plugin-transform-runtime (via calypso-build)

---

package.json
pnpm-lock.yaml
projects/js-packages/connection/changelog/remove-unneeded-monorepo-deps
projects/js-packages/connection/package.json
projects/plugins/backup/changelog/remove-unneeded-monorepo-deps
projects/plugins/backup/package.json

Nothing in the monorepo root uses concurrently or react. Also the
browserslist config for @wordpress/browserslist-config probably belongs
in projects that use it.
None
No
* Is CI happy?
* Do any other tools still work?

Remove more unneeded deps from the monorepo root

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-carousel-undefined-wpcom
projects/plugins/jetpack/changelog/fix-related-posts-img-height
projects/plugins/jetpack/changelog/story-block-update-media-selection-add
projects/plugins/jetpack/changelog/story-block-update-multiple-stories-per-post
projects/plugins/jetpack/changelog/update-client-lock-autoupdates
projects/plugins/jetpack/readme.txt

* Ports back changelog/readme changes from the 9.8.1 point release.
* N/A
* No.
* Not much to test, 9.8.1 has been shipped.

Changelog: update with changes from 9.8.1

---

tools/docker/mu-plugins/fix-monorepo-plugins-url.php

Fixes a situation in our Docker setup:
* Activate Jetpack Beta plugin.
* Activate a Beta-driven version of the plugin (e.g. Release Candidate) -- this means that Jetpack is loading from `/jetpack-dev/` not the monorepo version of the plugin.
* Have a package in the monorepo with updates newer than the latest version, say adding a new method.
* In the Jetpack Beta plugin, utilize the new method.
Before this patch, the stable versions are preferred, so the autoloader takes them from the Beta-driven version of Jetpack. After this patch, the dev-master version from Beta will be used, allowing the new method to be accessible.
* For our Docker env, prefer monorepo versions.
n/a
No
* Situation above. Can checkout the `add/admin-page-package` branch to see the error under the above circumstances …

Docker: Use monorepo packages

---

pnpm-lock.yaml
projects/github-actions/repo-gardening/changelog/update-gardening-concurrency
projects/github-actions/repo-gardening/package.json
projects/github-actions/repo-gardening/src/get-files.js
projects/github-actions/repo-gardening/src/get-labels.js
projects/github-actions/repo-gardening/src/get-next-valid-milestone.js
projects/github-actions/repo-gardening/src/tasks/add-labels/index.js
projects/github-actions/repo-gardening/src/tasks/add-milestone/index.js
projects/github-actions/repo-gardening/src/tasks/assign-issues/index.js
projects/github-actions/repo-gardening/src/tasks/check-description/index.js
projects/github-actions/repo-gardening/src/tasks/clean-labels/index.js
projects/github-actions/repo-gardening/src/tasks/flag-oss/index.js
projects/github-actions/repo-gardening/src/tasks/notify-design/index.js
projects/github-actions/repo-gardening/src/tasks/notify-editorial/index.js
projects/github-actions/repo-gardening/src/tasks/wpcom-commit-reminder/index.js
projects/github-actions/required-review/changelog/update-gardening-concurrency
projects/github-actions/required-review/package.json
projects/github-actions/required-review/src/paths.js
projects/github-actions/required-review/src/reporter.js
projects/github-actions/required-review/src/reviewers.js
projects/github-actions/required-review/src/team-members.js
tools/cli/helpers/github.js
tools/cli/package.json

* @actions/core 1.2.7 → 1.4.0
* @actions/github 4.0.0 → 5.0.0
* This deprecated `octokit.<endpoint>` in favor of `octokit.rest.<endpoint>`,
so change that all over the place.
* @octokit/auth → @octokit/auth-token
* @octokit/rest 18.5.3 → 18.6.0
Doing this instead of renovate's #19990, may as well get all of it at once.
No
* Is CI happy?
* Does the stuff still work?

Update GitHub @actions and @octokit packages

---

tools/cli/commands/docker.js

Adds new `exec` command to Jetpack `docker` cli
* run `jetpack docker ls` - you should see container folder contents
* run `jetpack docker

Docker: Add exec command

---

projects/plugins/jetpack/changelog/sync-test-reenable
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-posts.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-themes.php

Fixes sync tests disabled in #20050
* N/A
NO
* Verify all Unit Tests complete successfully.

Re-enable Sync tests

---

projects/plugins/jetpack/changelog/update-e2e-in-place-connection-timeout-increase
projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/in-place-authorize.js

* Increase in-place wait timeout
n/a
n/a
* Make sure the tests are green.

E2E Tests: Increase in-place wait timeout

---

docs/development-environment.md
tools/docker/README.md

* This PR updates the docs to match usage for the PHPUnit tests when using the `jetpack` CLI tool.
* N/A
* No
* Try running those commands. Do they work?

Docs: update references to phpunit ran using the Jetpack CLI tool

---

projects/plugins/beta/changelog/fix-beta-production-build-missing-deps
projects/plugins/beta/composer.json
projects/plugins/beta/composer.lock

* Move `jetpack-autoloader` dependency to production dependencies, so production build will include autoloader files.
p1624636389036900-slack-CA17PSW87
n/a
* Before applying this patch, build `plugins/beta` and make sure it's vendor folded does not include autoloader files (`autoload_packages.php` for example)
* Apply this patch
* Build `plugins/beta` and make sure `vendor` includes all the relevant files. Also, try to activate it on local dev install.

Beta: Fix autoloader problem in production build

---

.github/files/pr-update-to.sh

This will enforce testing of future PRs with the new tool version, and
will help prevent accidentally merging changes with old versions
mirrored in e.g. new package.json files.
A comment I'm about to leave on #19565.
No.
* Merge this, then something like #19565, and see if the `pr-update-to` tag gets updated.

CI: Update pr-update-to when tool versions are changed

---

.github/files/required-review.yaml

* Let's allow the backup team to manage PRs for changes to the backup plugin.
* N/A
* No
* Not much to test here, we'll see the changes in the future backup plugin changes.

Approvers: add the Backup plugin to files managed by backup team.

---

projects/plugins/jetpack/changelog/e2e-fix-missing-function
projects/plugins/jetpack/tests/e2e/lib/env/playwright-environment.js

Remove a call to a missing function (deleted in a previous PR).
n/a
n/a
* CI green
* No errors in E2E tests console

E2E tests: fix call to missing function

---

projects/plugins/jetpack/changelog/e2e-no-video-for-passed-tests
projects/plugins/jetpack/tests/e2e/lib/env/playwright-environment.js
projects/plugins/jetpack/tests/e2e/package.json
projects/plugins/jetpack/tests/e2e/pnpm-lock.yaml

Do no save videos for tests that passed.
1156386383419466-as-1200408419584753
no
* CI green
* No video should be saved for tests that passed. No changes for failures, videos should be saved and attached to Allure report as before.

E2E tests: skip saving videos for passed tests

---

projects/plugins/jetpack/changelog/add-init-10-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Fixes #
* bump to next version of Jetpack (10.0)
N/A
* Version 10.0-alpha?

Jetpack - Init version 10.0 cycle

---

projects/plugins/jetpack/changelog/update-9.9-to-test
projects/plugins/jetpack/to-test.md

Jetpack 9.9 Beta - Testing List

---

projects/plugins/jetpack/changelog/2021-06-30-16-41-00-088860
projects/plugins/jetpack/extensions/blocks/contact-form/editor.scss

Fixes https://github.com/Automattic/themes/issues/4049
By setting a specific color on the textarea, the block is preventing the theme CSS from being applied. This removes this specific style which allows the theme CSS to be applied, but it does also reveal an issue with the core CSS which is presumably why this rule was added. IMO the new issue is less severe so this solution is preferable.
Before:
Seedlet:
Quadrat:
After:
Seedlet:
Quadrat:
* Switch to the Quadrat theme
* Open the editor
* Add a contact form 
* Confirm that the textarea has the correct border color

Contact Form: Remove textarea border setting

---

projects/packages/sync/CHANGELOG.md
projects/packages/sync/changelog/fix-checksum-invalid-term-in-term-relationship
projects/packages/sync/changelog/fix-sync-checksum-parent-join

* Updates readme to prep for new package release. 
N/a
N/a
* Proofread?
*

Sync: Bump Package Readme for Release 

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/add-better-carousel-upscaling
projects/plugins/jetpack/changelog/add-carousel-comments-indicator
projects/plugins/jetpack/changelog/add-carousel-error-handling-for-swiper
projects/plugins/jetpack/changelog/fix-carousel-comments-icon-placement
projects/plugins/jetpack/changelog/fix-carousel-image-zoom-on-mobile
projects/plugins/jetpack/changelog/fix-carousel-light-small-screens
projects/plugins/jetpack/changelog/fix-multiple-gallery-bug
projects/plugins/jetpack/changelog/fix-php-notice-milestone
projects/plugins/jetpack/changelog/fix-swiper-merge-followups
projects/plugins/jetpack/changelog/revert-carousel-z-index
projects/plugins/jetpack/changelog/try-carousel-prevent-zoom-transition-slide
projects/plugins/jetpack/changelog/update-9.9-to-test
projects/plugins/jetpack/changelog/update-carousel-fix-prev-button-clicks-on-desktop
projects/plugins/jetpack/changelog/update-carousel-to-avoid-twenty-nineteen-theme-heading-conflicts
projects/plugins/jetpack/changelog/update-carousel-to-use-svgs
projects/plugins/jetpack/changelog/update-refactored-carousel-pagination-to-use-normal-font-weight
projects/plugins/jetpack/changelog/update-site-logo-block-compatibility
projects/plugins/jetpack/readme.txt

* Backports the changelog and readme from the release branch `jetpack/branch-9.9` to master
n/a
no
Proofread

Backport Changelog and Readme from 9.9 to Master

---

projects/plugins/backup/changelog/add-backup-worg-slug
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/backup/readme.txt

Adds the w.org slug for the Backup plugin.
* n/a
n/a
No
* n/a
*

Backup: Add w.org slug

---

.github/actions/deepen-to-merge-base/action.yml
.github/workflows/build.yml
.github/workflows/e2e-tests.yml
.github/workflows/linting.yml
pnpm-lock.yaml
projects/github-actions/pr-is-up-to-date/action.yml
projects/github-actions/pr-is-up-to-date/changelog/fix-gh-actions-context-vars-in-run
projects/github-actions/push-to-mirrors/action.yml
projects/github-actions/push-to-mirrors/changelog/fix-gh-actions-context-vars-in-run
tools/js-tools/git-hooks/pre-commit-hook.js
tools/js-tools/lint-gh-actions.js
tools/js-tools/package.json

It's better to pass values via environment variables rather than
directly substituting into the shell script.
Also add a new CI and pre-commit check to look for this in the future.
p1625853184382100-slack-CBG1CP4EN
No
* Is CI happy?
* Try reverting some of the yaml file changes in this PR. The pre-commit check should complain. If you ignore and push anyway, CI should also complain.

actions: Avoid context vars in `run` steps

---

projects/packages/abtest/changelog/update-manager_get_connected_users
projects/packages/abtest/composer.json
projects/packages/backup/changelog/update-manager_get_connected_users
projects/packages/backup/composer.json
projects/packages/connection-ui/changelog/update-manager_get_connected_users
projects/packages/connection-ui/composer.json
projects/packages/connection/changelog/update-manager_get_connected_users
projects/packages/connection/composer.json
projects/packages/connection/src/class-manager.php
projects/packages/connection/src/class-tokens.php
projects/packages/identity-crisis/changelog/update-manager_get_connected_users
projects/packages/identity-crisis/composer.json
projects/packages/identity-crisis/package.json
projects/packages/identity-crisis/src/class-identity-crisis.php
projects/packages/jitm/changelog/update-manager_get_connected_users
projects/packages/jitm/composer.json
projects/packages/jitm/src/class-jitm.php
projects/packages/licensing/changelog/update-manager_get_connected_users
projects/packages/licensing/composer.json
projects/packages/sync/changelog/update-manager_get_connected_users
projects/packages/sync/composer.json
projects/plugins/backup/changelog/update-manager_get_connected_users
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/update-manager_get_connected_users
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

When we introduced the `Tokens` class to the Connection package in #18812 we discussed how we should split responsibilities between the Tokens and the Manager classes.
Tokens should know where and how all the tokens are stored.
Manager should hold all the logic that interprets what the tokens mean. Is site connected? Has connected Admin? And also, `get_connected_users`.
In [this comment](https://github.com/Automattic/jetpack/pull/18812#issuecomment-779977892) I highlight this division of responsibility and in [this comment](https://github.com/Automattic/jetpack/pull/18812#discussion_r578330086) @fgiannar suggests how we should do it.
However, we forgot to do this and this method was merged with the logic in the Tokens class, [but still serving as an internal method called by the …

Move get_connected_users logic back to the Manager class

---

tools/version-packages.sh

It was updating the direct dependencies, but leaving the indirect
dependencies at monorepo versions. This resulted in us releasing Jetpack
9.8 with a dev-master version of automattic/jetpack-password-checker.
Since we now have that extra `composer update` call at the end to update
all the packages, we can pass --no-update to the `composer require`
calls to save all the updates until the end.
p1626278072007900/1626182894.454600-slack-CBG1CP4EN
No
* Run `tools/version-packages.sh projects/plugins/jetpack`.
* Check that the version of automattic/jetpack-password-checker is not dev-master.

tools: version-packages.sh should update indirect deps too

---

projects/plugins/beta/README.md
projects/plugins/beta/changelog/update-beta-plugin-release-instructions
projects/plugins/beta/composer.json
projects/plugins/beta/composer.lock

* Use `changelogger-release.sh` instead of manually editing the
changelog.
* Use the autotagger instead of manually tagging.
None
No
* Merge this. See that the autotagging action gets added to the mirror repo. Then we'll merge the followup I'm about to submit that does an actual release.

Beta plugin: Update release instructions

---

projects/packages/sync/CHANGELOG.md
projects/packages/sync/changelog/fix-return-setting-value-of-jetpack-sync-settings-options

* Backports sync changelog after bumping to 1.23.3
https://github.com/Automattic/jetpack/pull/20383
No
* Proofread

Backport Sync Changelog for 1.23.3

---

projects/plugins/beta/changelog/fix-beta-elem-not-found
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php
projects/plugins/beta/src/admin/admin.js

After PR: https://github.com/Automattic/jetpack/pull/20168
There were a few element not found errors since the plugin layout was adjusted; this PR cleans those errors up.
* No.
* After pulling down changes, the Beta plugin should function as expected still - try the different plugin sections while you have your browser console open.

Beta: fix minor JS errors

---

projects/plugins/beta/CHANGELOG.md
projects/plugins/beta/changelog/add-beta-breadcrumb-menu
projects/plugins/beta/changelog/fix-beta-elem-not-found
projects/plugins/beta/changelog/fix-beta-tag-with-v
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php

Release Jetpack Beta plugin v3.0.1
p1626385556043300-slack-CBG1CP4EN
No
* Nothing much to test, really.

Beta plugin: Release 3.0.1

---

projects/plugins/beta/changelog/fix-beta-typo
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php
projects/plugins/beta/src/admin/plugin-manage.template.php

"Search for a releases" → "Search for a release".
None
No
* Go to the plugin management page for Jetpack. Check the text in the releases search box.

Beta plugin: Fix a typo

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-caption-in-carousel
projects/plugins/jetpack/changelog/fix-carousel-comments-icon-jump-when-comments-loaded
projects/plugins/jetpack/changelog/fix-carousel-icon-weight
projects/plugins/jetpack/changelog/fix-corousel-css-leakage-bug
projects/plugins/jetpack/changelog/fix-customize-enqueue-block-dependencies
projects/plugins/jetpack/changelog/fix-mapblock-customizer-widget
projects/plugins/jetpack/changelog/fix-register-performance-submenu
projects/plugins/jetpack/changelog/fix-return-setting-value-of-jetpack-sync-settings-options
projects/plugins/jetpack/changelog/fix-widget-visibility
projects/plugins/jetpack/changelog/fix-widget-wpcom-block-editor
projects/plugins/jetpack/changelog/jetpack-branch-9.9
projects/plugins/jetpack/changelog/remove-carousel-image-directory
projects/plugins/jetpack/changelog/update-block-editor-settings-deprecation
projects/plugins/jetpack/changelog/update-carousel-css-tweaks
projects/plugins/jetpack/changelog/update-manager_get_connected_users
projects/plugins/jetpack/changelog/update-nav-unification-store-preferred-view
projects/plugins/jetpack/readme.txt

* Backports changelog and stable tag from 9.9.1 back to master
n/a
no
* Proofread

Backport Changelog File and update Stable Tag to 9.9.1 

---

.github/workflows/linting.yml
tools/check-changelogger-use.php

Move .github/files/require-change-file-for-touched-projects.php to
tools/check-changelogger-use.php, pass base and head refs via the
command line instead of reading the GitHub Actions environment, and use
a more human-friendly output when not running under CI.
Code review on #20303
No
* Is CI happy, and showing proper output for the relevant job?
* Make a commit that touches a project, without adding a change file. Run the script, e.g. `tools/check-changelogger-use.php origin/master HEAD`. Does the output look sensible?
* Run the script again with CI set, e.g. `CI=1 tools/check-changelogger-use.php origin/master HEAD`. Does the output look good for Actions?
* Add a change file, then run it again. Does it no longer complain?

tools: Make "check-changelogger-use" a proper tool

---

tools/docker/README.md

* Fixes an anchor link to: https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md#install-development-tools
No
* Visit https://github.com/Automattic/jetpack/blob/master/tools/docker/README.md
* Note the Jetpack's require tools link doesn't link to the correct ID anchor
* Ensure the new link does (You can copy/paste it into your browser from the code)

Updated install development tools link

---

projects/plugins/jetpack/changelog/add-init-jp-10.0-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init Jetpack 10.1 release cycle
* N/A
* Proofread cycle version bump.

Init Jetpack 10.1 release cycle

---

projects/plugins/jetpack/changelog/update-jp-10.0-to-test
projects/plugins/jetpack/to-test.md

* Jetpack 10.0: update to-test.md beta testing instructions.
* No.
* Proofread the beta testing instructions.

Jetpack 10.0: update to-test.md

---

.github/renovate.json

Readding the labels Jeremy had applied manually, looks like the bot
removed them when it added this feature.
None
No
* Merge, then see if the bot re-adds the labels on the dashboard issue.

renovate: Set dependencyDashboardLabels

---

projects/plugins/beta/changelog/fix-beta-plugin-undefined-index
projects/plugins/beta/src/class-hooks.php

Adds a guard against an undefined index warning.
Fixes #20489
#20489
no
* Try repeating the report in #20489

Beta plugin: Guard against undefined index

---

projects/plugins/beta/CHANGELOG.md
projects/plugins/beta/changelog/add-beta-shiny-updates
projects/plugins/beta/changelog/fix-beta-plugin-master-updates
projects/plugins/beta/changelog/fix-beta-plugin-undefined-index
projects/plugins/beta/changelog/fix-beta-search
projects/plugins/beta/changelog/fix-beta-typo
projects/plugins/beta/changelog/update-move_idc_tests
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php

* Release v3.0.2
None
No
* Nothing really to test.

Beta plugin: Release v3.0.2

---

tools/docker/README.md

I had a small error running Jurassic Tube and eventually found the fix, which required resetting my docker environment.

Add instructions for fixing installation error with Jurassic Tube

---

projects/packages/README.md

Add documentation about the `$$next-version$$` support added in: https://github.com/Automattic/jetpack/pull/20386
p9dueE-3gR-p2
No.
Proofread for typos and readability.

Docs: update with package version annotation info

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/add-admin-menu-rest-api-badge
projects/plugins/jetpack/changelog/add-carousel-prevent-interaction-on-transition
projects/plugins/jetpack/changelog/add-site-edior-beta
projects/plugins/jetpack/changelog/fix-carousel-title-formatting
projects/plugins/jetpack/changelog/fix-search-block-attribute-bug
projects/plugins/jetpack/changelog/revert-20377-update-fix-and-reenable-carousel-background
projects/plugins/jetpack/readme.txt

* Backport changelogs, readme.txt, and stable tag version from the 10.0 release branch.
N/A
No.
Proofread.

Jetpack: backport 10.0 changelog and stable tag version

---

tools/cli/commands/clean.js

* For plugins, composer.lock files are checked in. The current method of gathering files to clean won't find files that are untracked or not gitignored. This PR adds a way to filter and clean composer.lock files that are checked in for plugins.
p1628610161316400-slack-CBG1CP4EN
No.
* Run `jetpack clean` and choose a plugin.
* Choose the option to delete composer.lock
* Make sure it removes it.
* Try a few other combinations of commands, passthroughs, packages still work the same, etc.
Note this does not apply to the `all` command, since that's a sweeping destructive action and we expect composer.lock files to be checked in, we intentionally ignore them there. We could revisit this.

CLI: Allow Jetpack Clean to Remove Checked in composer.lock files for Plugins

---

pnpm-lock.yaml
projects/packages/connection-ui/changelog/fix-broken-test-jest-dependency
projects/packages/connection-ui/package.json

Fixes broken test `pnpm run test-search` in `projects/plugins/jetpack`
Example failure:
```
FAIL  modules/search/instant-search/lib/test/filters.test.js
[test-search-scripts]   ● Test suite failed to run
[test-search-scripts] 
[test-search-scripts]     TypeError: Cannot read property 'cwd' of undefined
[test-search-scripts] 
[test-search-scripts]       at Object.getCacheKey (../../../node_modules/.pnpm/babel-jest@27.0.6_@babel+core@7.12.10/node_modules/babel-jest/build/index.js:297:33)
[test-search-scripts]       at ScriptTransformer._getCacheKey (../../../node_modules/.pnpm/@jest+transform@26.6.2/node_modules/@jest/transform/build/ScriptTransformer.js:256:23)
[test-search-scripts]       at ScriptTransformer._getFileCachePath (../../../node_modules/.pnpm/@jest+transform@26.6.2/node_modules …
```

Fix broken test jest dependency

---

docs/development-environment.md

* Fix a minor typo issue in the Development Environment breaking internal anchor.
N/A
N/A
Just double check that the documentation fix is correct.

Documentation: Fix minor typo issue

---

projects/plugins/backup/changelog/update-backup-release-cycle-030
projects/plugins/backup/composer.json
projects/plugins/backup/jetpack-backup.php

Start a new release cycle for the Backup plugin.
* No
* No
* Is CI happy?

Backup: start new release cycle

---

projects/js-packages/eslint-changed/CHANGELOG.md
projects/js-packages/eslint-changed/bin/eslint-changed.js
projects/js-packages/eslint-changed/changelog/add-npm-publishing
projects/js-packages/eslint-changed/changelog/remove-licensetxt
projects/js-packages/eslint-changed/changelog/renovate-eslint-and-plugins
projects/js-packages/eslint-changed/changelog/update-move-eslint-changed-to-project
projects/js-packages/eslint-changed/changelog/update-node-version-14161
projects/js-packages/eslint-changed/package.json

﻿Related issues: #20454, #20455
* Internal reference: p9dueE-3eM-p2
* No
* Upon merging this PR, a new tag will be published on https://github.com/Automattic/eslint-changed/releases
* Once that tag exists, a new action will run in that repo (see [running actions here](https://github.com/Automattic/eslint-changed/actions)) to push the new tag to npm.

ESLint Changed: release version for NPM.

---

pnpm-lock.yaml
tools/js-tools/package.json

﻿
This is a follow-up of #20683. Since we have a new version of that tool, let's update its reference.
* No
No
* Is CI Happy?
* Can you run `jetpack install` without getting any warnings?

Update the version of eslint-changed referenced in repo

---

projects/plugins/backup/changelog/update-readme
projects/plugins/backup/readme.txt

* Updated readme to replace boiler plate information
No.
* None

[Plugin] Backup: Updated readme.txt with additional information

---

projects/plugins/jetpack/changelog/e2e-optimize-prerequisites
projects/plugins/jetpack/tests/e2e/README.md
projects/plugins/jetpack/tests/e2e/jest.config.js
projects/plugins/jetpack/tests/e2e/lib/env/test-setup.js
projects/plugins/jetpack/tests/e2e/specs/connection.test.js
projects/plugins/jetpack/tests/e2e/specs/free-blocks.test.js
projects/plugins/jetpack/tests/e2e/specs/plugin-updater.test.js
projects/plugins/jetpack/tests/e2e/specs/pre-connection.test.js
projects/plugins/jetpack/tests/e2e/specs/pro-blocks.test.js
projects/plugins/jetpack/tests/e2e/specs/recommendations.test.js
projects/plugins/jetpack/tests/e2e/specs/search.test.js

* Follow up of #20605 
* Optimized the specs prerequisites. Removed redundant `test-setup.js` file and removed unnecessary wpcom login actions.
n/a
n/a
* All e2e tests should pass

E2E tests: optimize specs prerequisites

---

.github/renovate.json
pnpm-lock.yaml
projects/js-packages/base-styles/.gitattributes
projects/js-packages/base-styles/.gitignore
projects/js-packages/base-styles/.npmrc
projects/js-packages/base-styles/CHANGELOG.md
projects/js-packages/base-styles/README.md
projects/js-packages/base-styles/changelog/add-storybook
projects/js-packages/base-styles/composer.json
projects/js-packages/base-styles/package.json

See #20629
Removing elements from 20629 to make it easier to digest what's changing and what may be breaking.
* Adds a base-styles packages. Not used yet.
n/a
No.
* None yet. This just adds a shell packages. Nothing to see here.
*

JS Packages: Add Base Styles package

---

tools/project-version.sh

When run via CI, it hints that you can fix the problem using
`tools/project-version.sh -u`. It should do that in non-CI mode too.
None
No
* Try running `tools/project-version.sh -c 1.2.3 plugins/jetpack`. It should include instructions on how to fix the problem after all the errors.
* Try running `CI=1 tools/project-version.sh -c 1.2.3 plugins/jetpack`. It should include instructions on how to fix the problem in each error line, with no extra output at the end.

tools: project-version.sh should hint at solution in non-CI mode too

---

tools/check-intra-monorepo-deps.sh

Alternative to #20719
Fixes #
*
* Go to '..'
*

Add -a option for auto suffixing changelog entries created by tools/check-intra-monorepo-deps.sh

---

projects/github-actions/required-review/CHANGELOG.md
projects/github-actions/required-review/changelog/fix-required-reviews-multiple-paths-and-negation
projects/github-actions/required-review/package.json

Release v2.2.0
Needed for #20749
No
* Merge, then make sure the new release is tagged in the mirror repo.

required-review: Release v2.2.0

---

.github/files/required-review.yaml
.phpcs.xml.dist
projects/plugins/search/.gitattributes
projects/plugins/search/.gitignore
projects/plugins/search/CHANGELOG.md
projects/plugins/search/README.md
projects/plugins/search/changelog/add-search-plugin
projects/plugins/search/composer.json
projects/plugins/search/composer.lock
projects/plugins/search/jetpack-search.php
projects/plugins/search/package.json
projects/plugins/search/phpunit.xml.dist
projects/plugins/search/readme.txt
projects/plugins/search/tests/php/bootstrap.php

- Skeleton for a Search plugin
* Add initial skeleton. It doesn't do anything yet.
To be added.
No
* None at this time.

Search: Add skeleton for Search standalone

---

projects/plugins/jetpack/changelog/start-102-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start the new release cycle after #20892.
* No
* No
* Is CI happy?

Release: start 10.2 cycle

---

projects/plugins/jetpack/changelog/add-10.1-to-test-instructions
projects/plugins/jetpack/to-test.md

* Updates to-test.md file.
N/a
No
* Proofread

Update To-Test.md for Jetpack 10.1

---

projects/packages/heartbeat/changelog/fix-typo-heartbeat
projects/packages/heartbeat/src/class-heartbeat.php
projects/plugins/jetpack/changelog/fix-typo-heartbeat
projects/plugins/jetpack/class.jetpack-heartbeat.php

* Fixes typo of `hearbeat` to `heartbeat` in a couple places.
n/a
n/a
* n/a

Heartbeat: Fix typo

---

projects/packages/connection/CHANGELOG.md
projects/packages/connection/changelog/fix-reconnect-button-missing
projects/packages/connection/src/class-package-version.php
projects/plugins/jetpack/changelog/jetpack-branch-10.1
projects/plugins/jetpack/composer.lock

* Backports changelog from connection package after cherry picked release. 
N/a
no
* Proofread
*

Backport Connection Package Changelog from Release

---

projects/packages/heartbeat/CHANGELOG.md
projects/packages/heartbeat/changelog/fix-typo-heartbeat
projects/packages/sync/CHANGELOG.md
projects/packages/sync/changelog/fix-jetpack-sync-checksum-better-woo-handling
projects/packages/sync/changelog/fix-wporg-notices
projects/packages/sync/src/class-package-version.php

* Backports changelog from Sync and Heartbeat packages after cherry picked release. 
N/a
no
* Proofread
*

Backport Sync and Heartbeat Changelog from Release

---

.github/renovate.json

Changes in #20917 resulted in some errors about "Each packageRule must
contain at least one non-match* or non-exclude* field". Apparently just
an `extends` isn't enough.
Also, even though it doesn't complain, the `extends` value is supposed
to be an array. So make it so. And `supportPolicy` has been deleted, so
remove it.
None
No
* Merge and see if renovate is happy now.

renovate: Fix config

---

projects/plugins/jetpack/changelog/update-title-filter
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php

* The filter needs all args, so including the post_id.
See https://developer.wordpress.org/reference/hooks/the_title/
Follow-up to: https://github.com/Automattic/jetpack/pull/20637
Internal: p1630690596241200-slack-CBG1CP4EN
n/a
* 
*

Related Posts: Prevent fatal when not passing all filter args

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-button-block-markup
projects/plugins/jetpack/changelog/fix-calyps-build-hack
projects/plugins/jetpack/changelog/fix-customberg-result-highlight
projects/plugins/jetpack/changelog/fix-fix-style-for-super-wide-screen
projects/plugins/jetpack/changelog/fix-hide-search-menu-on-disconnect
projects/plugins/jetpack/changelog/fix-removing-social-icons
projects/plugins/jetpack/changelog/fix-tiled-gallery-transform-again
projects/plugins/jetpack/changelog/fix-typo-heartbeat
projects/plugins/jetpack/changelog/fix-widget-vis-php-notice
projects/plugins/jetpack/changelog/update-carousel-nav-colors
projects/plugins/jetpack/changelog/update-carousel_css_fix
projects/plugins/jetpack/changelog/update-title-filter
projects/plugins/jetpack/readme.txt

* Backports changelog and bumps stable version after Jetpack 10.1 release. 
N/a
No
* Proofread
*

Backport Changelog From 10.1 Release

---

projects/js-packages/connection/changelog/update-connection-status-card-styles
projects/js-packages/connection/components/connection-status-card/style.scss

Minor tweaks in styles for `ConnectionStatusCard` RNA component
`ConnectionStatusCard` component: Apply styling refinements as discussed [here](https://github.com/Automattic/jetpack/pull/20398#issuecomment-885661818)
1199658893173824-as-1200636806056127/f
No
See https://github.com/Automattic/jetpack/pull/20398
We are mainly interested in the styling refinements discussed in [this comment](https://github.com/Automattic/jetpack/pull/20398#issuecomment-885661818)

Connection status card: Update styles

---

tools/js-tools/list-gh-secrets.js

I found I wanted such a tool when checking that the list in the field
guide was up to date (it was).
None
No
* Run it.

tools: Add a tool to list GitHub secret names in repos

---

projects/packages/post-list/changelog/fix-post-list-mirror-repo-name
projects/packages/post-list/composer.json

The repo canonically has an uppercase `A`, and that's what all the other
projects use.
This can avoid confusion in case of case-sensitive sorting, and
directory naming in the build artifact.
None
No
* Look at the build artifact, does it no longer have both "Automattic" and "automattic" subdirs?

post-list: Fix mirror repo name

---

projects/plugins/backup/changelog/update-backup-readme-docs
projects/plugins/backup/readme.txt

Fixes #21081
* Changes to the readme to include more info about support docs.
* No
* No

Backup: update readme to include support doc info

---

projects/plugins/jetpack/changelog/fix-cpt-call
projects/plugins/jetpack/modules/custom-post-types/testimonial.php

Partial for #21039
* Changes the logic to only load admin-only code in the admin context to improve performance for front-end and logged out.
p3topS-VE-p2
n/a
* On a site with testimonials enabled without any testimonials, and using Query Monitor or something similar, load the front end of the site.
* Before, see the DB hit to count testiomonais. After, no hit.

Custom Content Types: Improve loading of Testimonal CPT

---

tools/cli/helpers/docker-config.js
tools/docker/compose-extras.yml.sample
tools/docker/compose-volumes.yml.sample

﻿
In #20256, we updated our Docker configuration so it accepts different personal config files. Those files are yml files, not json, as per feedback on the PR.
* No
* No

Docker: update references to extra config files.

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature-request.yml

For all templates, make the "Other" option for "Affected Plugin" be
"None / Other", since issues may impact no plugin at all (e.g. it may be
something about packages or tools).
For bug reports, allow "Other" for OS, as people might use different
operating systems.
For bug reports, allow "None / Other" for the browser as people might
use other browsers or the issue might not involve a browser at all (e.g.
CLI tools or backend code).
None
Not really. It changes what data people are asked to submit if they file a bug.
* View the actual file (not the diff) for each issue template and make sure GitHub is not reporting any warnings.
* Merge, then test.

issue templates: Add more "none/other" options

---

pnpm-lock.yaml
projects/plugins/jetpack/_inc/client/mixins/url-search/index.js
projects/plugins/jetpack/changelog/remove-unnecessary-page-dep
projects/plugins/jetpack/package.json

We haven't been using this library correctly in the first place, and it
has now broken the incorrect way we were using it (see #21117).
It seems that the way we were using it works out as equivalent to a
single line of JS, so just do that.
p1631824628152000/1544445965.249000-slack-CBG1CP4EN
No
* Is CI happy?
* Does the relevant stuff still work?

jetpack: Replace unnecessary `page` dep

---

projects/packages/post-list/CHANGELOG.md
projects/packages/post-list/changelog/add-post-list-package
projects/packages/post-list/changelog/fix-post-list-mirror-repo-name
projects/packages/post-list/changelog/refactor-server-side
projects/packages/post-list/changelog/update-posts-list-default-columns
projects/packages/post-list/src/class-post-list.php

Fixes #20941
* Releases the Post List package
p1632331521278800-slack-CBG1CP4EN
Nope.
* Enable the post list package and check that it works (post thumbnails appear in the posts list on wp-admin, Tags and Categories are hidden by default)

Release new post list package

---

projects/plugins/jetpack/changelog/init-jetpack-10.3-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init Jetpack 10.3 release cycle.
No.

Init Jetpack 10.3 release cycle

---

projects/plugins/jetpack/changelog/update-jetpack-10.2-totest
projects/plugins/jetpack/to-test.md

* Update Jetpack 10.2 `to-test.md`
No.
Proofread testing instructions.

Update Jetpack 10.2 to-test.md

---

projects/plugins/jetpack/changelog/fix-activation-source-notice
projects/plugins/jetpack/class.jetpack.php

Fixes #21264
I'm not too sure how to reproduce, but this seems like a logical change.
* No
* No
* Not sure how to best test this since it requires starting from a site without Jetpack.
* Does the code look good?

General: avoid PHP notices when path is not set.

---

projects/plugins/boost/changelog/boost-version-bump
projects/plugins/boost/composer.json
projects/plugins/boost/composer.lock
projects/plugins/boost/jetpack-boost.php
projects/plugins/boost/package.json

* Bump version numbers to 1.3.1-alpha, in preparation for next milestone.
n/a
no
n/a

Update main branch boost to 1.3.1-alpha

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-avoid-errors-related-posts
projects/plugins/jetpack/changelog/fix-disable-webpack-concatenateModules-optimization
projects/plugins/jetpack/changelog/fix-search-translation
projects/plugins/jetpack/changelog/jetpack-branch-10.2
projects/plugins/jetpack/changelog/remove-tracking-ajax-callback
projects/plugins/jetpack/changelog/update-check_for_is_site_connection
projects/plugins/jetpack/changelog/update-tracking_ajax_callback
projects/plugins/jetpack/changelog/update-widget-visibility-block-editor-top-level
projects/plugins/jetpack/readme.txt

* Backports Jetpack 10.2-beta changelog updates.
* Updates Jetpack stable tag version in `readme.txt` to 10.2
No.
* Proofread changes.

Backport Jetpack 10.2-beta changelog

---

projects/plugins/beta/CHANGELOG.md
projects/plugins/beta/changelog/2021-08-10-04-36-40-409222
projects/plugins/beta/changelog/add-changelogger-squash-command
projects/plugins/beta/changelog/renovate-lock-file-maintenance
projects/plugins/beta/changelog/renovate-php-parallel-lint-php-parallel-lint-1.x
projects/plugins/beta/changelog/renovate-yoast-phpunit-polyfills-1.x-1
projects/plugins/beta/changelog/try-remove-composer-update-2
projects/plugins/beta/changelog/update-composer-to-2.1
projects/plugins/beta/changelog/update-eslint-jsdoc
projects/plugins/beta/changelog/update-issue-links
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php

* Janitorial release of the Beta Plugin v3.0.3
`> tools/find-unreleased-projects.sh 60`
No.
* Proofread.

Beta Plugin: release v3.0.3

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-jetpack-upgrade-page-currency
projects/plugins/jetpack/changelog/update-changelogs-from-103
projects/plugins/jetpack/changelog/update-publicize-fix-panel-issue
projects/plugins/jetpack/readme.txt

* Bring back 10.3 changelog updates from the release branch to `master`.
* N/A
* No

Janitorial: bring back 10.3 changelog updates to master

---

projects/plugins/jetpack/changelog/update-weekly-104a2
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start this week's new release cycle
* N/A
* No
* Is CI happy?

Janitorial: start 10.4-a.2 release cycle

---

tools/e2e-commons/bin/e2e-env.sh

Deactivate SSO module in e2e test environment. This is a quick fix solution for login flow failure when SSO is suggested.
https://app.asana.com/0/1156386383419466/1200597257111301
no
- E2E tests should pass

E2E tests: deactivate SSO module

---

tools/create-release-branch.sh

Just fixes a small type in to the create-release-branch.sh script that I noticed.
N/a
No.
Proofread.

Fix typo in create-release-branch.sh

---

projects/plugins/jetpack/changelog/Infinity-Scroll-allowed-vars
projects/plugins/jetpack/modules/infinite-scroll/infinity.php
projects/plugins/jetpack/tests/php/modules/infinite-scroll/test_class.infinite-scroll.php

* Reverts Automattic/jetpack#21550
p1636493848144400-slack-C010KDAPG49
No
* Make sure infinite scroll still works.
*

Revert "Jetpack Plugin: Fixing Infinite scroll allowed var result"

---

.github/actions/tool-setup/action.yml

Now that [GitHub has made it possible to use them][1], enable the conditions
to allow for avoiding installing php or node in actions that don't need
them.
[1]: https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/
None
No
* Is CI happy?
* Do jobs that set false for `php` or `node` show them not being installed anymore?

actions: Enable conditions in tool-setup action

---

projects/packages/assets/CHANGELOG.md
projects/packages/assets/changelog/add-assets-wp_register_script-wrapper
projects/packages/assets/src/class-assets.php

Please add testing instructions to projects/plugins/jetpack/to-test.md in a new commit as part of your PR. -->
Changelog file for new package release.
n/a
no
Proofread

Assets: Changelog for package version 1.12.0

---

projects/plugins/jetpack/changelog/fix-spelling
projects/plugins/jetpack/extensions/blocks/repeat-visitor/test/validate.js
tools/cli/commands/docker.js
tools/docker/docker-compose.yml
tools/e2e-commons/pages/wpcom/login.js

Fixes a couple instances of "Wordpress" sneaking in. The most visible is the help text for the `jetpack docker` command.
* Spelling updates.
See https://developer.wordpress.org/reference/functions/capital_p_dangit/
no.
* `jetpack docker` -- does the text for the `sh` command contain the correct capitalization?

Janitorial: Update WordPress Spelling

---

projects/js-packages/eslint-config-target-es/CHANGELOG.md
projects/js-packages/eslint-config-target-es/changelog/add-eslint-config-target-es
projects/js-packages/eslint-config-target-es/changelog/add-mirror-for-eslint-config-target-es
projects/js-packages/eslint-config-target-es/changelog/fix-eslint-config-target-es-readme
projects/js-packages/eslint-config-target-es/package.json

Seems to be ready to use.
None
No
* Merge this, then see that it published to npmjs.com as intended.

eslint-config-target-es: Release 1.0.0!

---

projects/plugins/jetpack/changelog/fix-jetpack-unit-wpcom
projects/plugins/jetpack/tests/php.multisite.xml
projects/plugins/jetpack/tests/php/bootstrap.php
projects/plugins/jetpack/tests/php/core-api/wpcom-fields/test-class.subscribers-endpoint.php
projects/plugins/jetpack/tests/php/lib/mock-functions.php
projects/plugins/jetpack/tests/php/modules/masterbar/data/admin-menu.php
projects/plugins/jetpack/tests/php/modules/subscriptions/test_class.jetpack-subscriptions.php

* Wraps a mock function in an exists check and combines it with another mock function in a new file.
* Updates file inclusion to account for synced files on wpcom.
p9dueE-3LL-p2
No
* This shouldn't need testing if the automated tests return green. I think.

Tests: Fix unit tests for wpcom

---

projects/plugins/jetpack/changelog/start-10.4-a.8
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

- Start 10.4-a.8
Fixes #
* n/a
n/a
n/a
* CI Happy?
*

Jetpack: Start 10.4-a.8

---

projects/packages/assets/changelog/update-assets-register_script-missing-doc
projects/packages/assets/src/class-assets.php

Documentation of the `css_dependencies` option was missing.
None
No
* I guess check the added doc for typos?

assets: Add missing options doc

---

projects/packages/assets/CHANGELOG.md
projects/packages/assets/changelog/add-register_script-textdomain
projects/packages/assets/changelog/renovate-brain-monkey-2.x
projects/packages/assets/changelog/update-assets-register_script-missing-doc
projects/packages/constants/CHANGELOG.md
projects/packages/constants/changelog/renovate-brain-monkey-2.x

Title says it all.
p1637595583170700-slack-C01U2KGS2PQ
No
* ???

assets: Release 1.13.0

---

projects/plugins/backup/CHANGELOG.md
projects/plugins/backup/changelog/fix-connection-ui-activator
projects/plugins/backup/changelog/update-backup_init_idc
projects/plugins/backup/readme.txt

* Port back changelog, readme and stable tag version changes for the 1.0.1 release
n/a
No
Proof read.

Update/jetpack backup version 1.0.1

---

projects/plugins/jetpack/changelog/update-weekly-104a10
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Update version numbers to Jetpack 10.4-a.10 to start new cycle
* N/A
* No
* Not much to test here. Are the version numbers okay?

Janitorial: update version numbers to start 10.4-a.10 cycle

---

projects/packages/my-jetpack/changelog/update-my-jetpack-repo
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/package.json
projects/plugins/jetpack/changelog/update-my-jetpack-repo
projects/plugins/jetpack/composer.lock

* Let's ensure that updates to the My Jetpack package can be pushed to a mirror repo.
* N/A
* No
* Is CI Happy?

Janitorial: create mirror repo for the My Jetpack package

---

pnpm-lock.yaml
projects/js-packages/licensing/changelog/add-license-styling-2
projects/js-packages/licensing/components/activation-screen-controls/style.scss
projects/js-packages/licensing/components/activation-screen-illustration/index.jsx
projects/js-packages/licensing/components/activation-screen-illustration/style.scss
projects/js-packages/licensing/components/activation-screen-illustration/test/component.jsx
projects/js-packages/licensing/components/activation-screen-success-info/style.scss
projects/js-packages/licensing/components/activation-screen/style.scss
projects/js-packages/licensing/package.json
projects/plugins/jetpack/changelog/add-license-styling-2
projects/plugins/jetpack/package.json

* Add Styling to the License Flow to improve how it handles smaller displays
| Narrow | Medium | Wide |
|------|---------|---------|
| ![Screen Shot 2021-11-23 at 09 16 03](https://user-images.githubusercontent.com/2810519/143072729-c8a87f7b-f4b3-44dc-be2d-12a96b6455d0.png) | ![Screen Shot 2021-11-23 at 09 15 48](https://user-images.githubusercontent.com/2810519/143072809-bf72c65b-8062-43a2-8b74-b909e200429f.png) | ![Screen Shot 2021-11-23 at 09 19 45](https://user-images.githubusercontent.com/2810519/143072895-097a27e2-7dd1-47ed-b97f-ebc0ff3be947.png) |
p1HpG7-cSg-p2
* Go to `/wp-admin/admin.php?page=jetpack#/license/activation`
* Modify the viewport size and see how the flow screen behaves

License Flow: Assorted Styling Improvements

---

projects/plugins/jetpack/_inc/client/product-descriptions/product-description/test/fixtures.js
projects/plugins/jetpack/changelog/update-upsell-products-copy
projects/plugins/jetpack/class.jetpack.php

Context: 1198218726984184-as-1201400680357126/1201408053382777/f
* Updates the Backup and Security products descriptions
p1HpG7-dEh-p2#comment-50592
No
* Spin up a site with Jetpack Free (it's easier to test with no products)
* Go to `/wp-admin/admin.php?page=jetpack#/product/security` and `/wp-admin/admin.php?page=jetpack#/product/backup`. Alternatively, you can reach those pages clicking on an Upgrade button on the At a Glance page.
* Confirm the copy matches the one in the PR

Product Page: Update Security and Backup description

---

projects/packages/licensing/CHANGELOG.md
projects/packages/licensing/changelog/update-increase-license-activation-request-timeout
projects/plugins/jetpack/changelog/jetpack-branch-10.4
projects/plugins/jetpack/composer.lock

Backports changelog after cherry-picking licensing change to release branch and releasing a new version of the licensing package.
n/a
no
Proof

Backport Licensing Changelog

---

projects/js-packages/storybook/changelog/fix-storybook-stories-tab
projects/js-packages/storybook/storybook/webpack.config.js

Fixes the loading of stories code in the Stories tab... 
After
Before
* Updates the regex test pattern for story files in the storybook webpack config file. 
No.
No.
* Checkout this PR
* `cd projects/js-packages/storybook` 
* Run storybook `pnpm run storybook:dev`
* Visit the Admin Page Component
* Expect to see the code for the story

Storybook: Fix the stories tab loading

---

projects/plugins/jetpack/changelog/phpcs-monitor
projects/plugins/jetpack/modules/monitor.php
tools/phpcs-excludelist.json

Fixes #21986
* PHPCS the Monitor module within Jetpack.
n/a
No.
* Verify changes makes sense.
*

PHPCS: Monitor

---

projects/plugins/jetpack/changelog/phpcs-shortlinks
projects/plugins/jetpack/modules/shortlinks.php
projects/plugins/jetpack/modules/site-icon/site-icon-functions.php
tools/phpcs-excludelist.json

Fixes #21988
* PHPCS for Site Icon Functions and Shortlinks file.
* NOTE: Strict compare changes for the shortlinks. They are all strings that would only be strings, but do double-check me.
n/a
No.
* Review changes.
* Pay attention to the strict compare updates.

PHPCS: Shortlinks and Site Icons

---

pnpm-lock.yaml
projects/js-packages/licensing/changelog/fix-license-flow-design
projects/js-packages/licensing/components/activation-screen-controls/index.jsx
projects/js-packages/licensing/components/activation-screen-controls/style.scss
projects/js-packages/licensing/components/activation-screen-controls/test/component.jsx
projects/js-packages/licensing/components/activation-screen-success-info/style.scss
projects/js-packages/licensing/components/activation-screen/index.jsx
projects/js-packages/licensing/package.json
projects/plugins/jetpack/changelog/fix-license-flow-design
projects/plugins/jetpack/package.json

* Refine Copy in License Activation
* Do not disable Activation button based on state of license activation
* Switch button from standard Jetpack Green styling to Emerald
| State | Screenshot |
|------|-------------|
| Start | <img width="922" alt="Screen Shot 2021-12-02 at 10 14 47" src="https://user-images.githubusercontent.com/2810519/144479850-4e693efe-e287-4fbb-9fb2-c42ee2bbd3cc.png"> |
| Button Focus | <img width="922" alt="Screen Shot 2021-12-02 at 10 14 52" src="https://user-images.githubusercontent.com/2810519/144479934-1d3f448a-6e72-4904-a2d8-93b3809bc323.png"> |
| With Empty Input Error | <img width="922" alt="Screen Shot 2021-12-02 at 10 15 23" src="https://user-images.githubusercontent.com/2810519/144480020-fa5b6e73-d809-430e-9bc6-6659deaa2c12.png"> |
| Success Screen | <img …

Refine new License Activation Flow UX

---

pnpm-lock.yaml
projects/js-packages/licensing/CHANGELOG.md
projects/js-packages/licensing/changelog/fix-license-flow-design
projects/js-packages/licensing/package.json
projects/plugins/jetpack/changelog/jetpack-branch-10.4
projects/plugins/jetpack/package.json

Backports changes to js licensing package.*
N/a
no
proof

Backport JS Licensing Changelog

---

pnpm-lock.yaml
projects/js-packages/connection/CHANGELOG.md
projects/js-packages/connection/changelog/fix-style-conflicts-in-disconnect-flow
projects/js-packages/connection/package.json
projects/js-packages/partner-coupon/changelog/jetpack-branch-10.4
projects/js-packages/partner-coupon/changelog/update-backport-connection-package
projects/js-packages/partner-coupon/package.json
projects/js-packages/storybook/changelog/jetpack-branch-10.4
projects/js-packages/storybook/changelog/update-backport-connection-package
projects/js-packages/storybook/package.json
projects/packages/connection-ui/changelog/jetpack-branch-10.4
projects/packages/connection-ui/changelog/update-backport-connection-package
projects/packages/connection-ui/package.json
projects/plugins/backup/changelog/jetpack-branch-10.4
projects/plugins/backup/changelog/update-backport-connection-package
projects/plugins/backup/package.json
projects/plugins/jetpack/changelog/jetpack-branch-10.4
projects/plugins/jetpack/changelog/update-backport-connection-package
projects/plugins/jetpack/package.json

Backports connections JS package release
n/a
No.
Proof?

Backport Connection JS Package Release

---

projects/plugins/jetpack/changelog/phpcs-notes
projects/plugins/jetpack/modules/notes.php
tools/phpcs-excludelist.json

Fixes #21987
* PHPCS all the things.
There's some really old code in here--ensuring that we're on IE 9 at least. This should be for a separate PR since it is more functional than strictly standards.
n/a
n/a
* JN site, enable Notifications on a connected Jetpack. Ensure that the notifications bubble in the admin menu and clicking it works.
*

Notifications: PHPCS

---

docs/development-environment.md

Fixes outdated reference since p9dueE-3x6-p2
* Updates docs.
p9dueE-3x6-p2 and p1638890991092300-slack-C02HQGKMFJ8
n/a
* n/a

Monorepo now uses Composer 2.1

---

projects/plugins/jetpack/CHANGELOG.md

Backport changelog entries from 10.4 release.
n/a
no
proof

Backport 10.4 Changelog

---

tools/docker/mu-plugins/fix-monorepo-plugins-url.php

When #21934, we forgot to update this to account for it.
p1638906654070600-slack-CBG1CP4EN
No
* Check that Jetpack packages' assets don't contain `/usr/local/src`, e.g. by going to the Jetpack dashboard and looking at the paths for the various packages' CSS.

docker: Fix mu-plugins/fix-monorepo-plugins-url.php

---

projects/plugins/jetpack/changelog/phpcs-jetpack-class-docs-2
projects/plugins/jetpack/class.jetpack.php

Supports #21952
* Various PHPCS of mainly docs and related changed lines.
n/a
n/a
* Everything makes sense? CI happy?

PHPCS: class.jetpack Docs 2

---

projects/plugins/jetpack/changelog/update-init-jetpack_10.5-a.4
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init version 10.5-a.4
n/a
n/a
Proofread.

Jetpack: init 10.5-a.4

---

projects/plugins/boost/changelog/e2e-bump-dependencies
projects/plugins/boost/tests/e2e/package.json
projects/plugins/boost/tests/e2e/pnpm-lock.yaml
projects/plugins/jetpack/changelog/e2e-bump-dependencies
projects/plugins/jetpack/tests/e2e/package.json
projects/plugins/jetpack/tests/e2e/pnpm-lock.yaml
tools/e2e-commons/package.json
tools/e2e-commons/pnpm-lock.yaml

Bump dependencies in all e2e tests projects.
n/a
no
* Is CI green?

E2E tests renovate: bump dependencies

---

projects/js-packages/i18n-check-webpack-plugin/changelog/fix-i18n-check-test
projects/js-packages/i18n-check-webpack-plugin/tests/fixtures/complex-test/webpack.config.js

A test broke when we added i18n-loader to webpack-config.
p1639601667250500-slack-CBG1CP4EN
no
* Does the test pass now?

i18n-check-webpack-plugin: Fix a broken unit test

---

projects/plugins/launchpad/changelog/add-build-steps-launchpad
projects/plugins/launchpad/composer.json
projects/plugins/launchpad/package.json

Adds build steps for Launchpad plugin.
n/a
no
Run `jetpack build plugins/launchpad` and see that upon activation, the Launchpad wp-admin settings page loads.
Run `jetpack build plugins/launchpad -p` and see that the production build fails for some undetermined reason.

Launchpad: Add Build Steps

---

projects/plugins/jetpack/changelog/update-vimeo-video-format-regex
projects/plugins/jetpack/modules/shortcodes/vimeo.php

Follow-up to #22115
* See https://github.com/Automattic/jetpack/pull/22115#discussion_r770630570
* N/A
* No
* See instructions in #22115.

Vimeo: tweak the regex used to get Vimeo URLs for oEmbed

---

projects/plugins/vaultpress/changelog/update-vaultpress-tested-version
projects/plugins/vaultpress/readme.txt

* Update Tested version of WordPress 5.8
No
* n/a

[Plugin] VaultPress: Updated Tested WordPress version

---

.github/files/required-review.yaml

The contract has ended successfully.
* 
pc9hqz-cn-p2
- No.
* n/a

Boost: Remove contractor

---

projects/packages/assets/CHANGELOG.md
projects/packages/assets/changelog/add-assets-textdomain-aliasing
projects/packages/assets/changelog/add-phpcs-per-director-config
projects/packages/assets/changelog/add-phpcs-per-director-config#2
projects/packages/assets/changelog/fix-phpcs-textdomain-config
projects/packages/assets/src/class-assets.php
projects/packages/changelogger/CHANGELOG.md
projects/packages/changelogger/changelog/add-phpcs-per-director-config
projects/packages/changelogger/src/Application.php

Releasing Assets v1.15.0. And an incidental release for Changelogger too.
p1640037268361500/1640032508.356600-slack-CBG1CP4EN
No
* ???

Assets: Release v1.15.0

---

projects/packages/composer-plugin/CHANGELOG.md
projects/packages/composer-plugin/changelog/add-composer-plugin-i18n-map

Release it.
p1640038456362000/1640032508.356600-slack-CBG1CP4EN
No
* ???

composer-plugin: Release v0.2.0

---

projects/js-packages/i18n-check-webpack-plugin/README.md
projects/js-packages/i18n-check-webpack-plugin/changelog/fix-i18n-check-doc-error

Forgot to update an example when copy-pasting from i18n-loader. Oops.
None
No
* Read the doc.

i18n-check: Fix a doc error

---

projects/plugins/jetpack/changelog/update-jetpack-10.6-a.0-init-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Jetpack: init 10.6-a.0 cycle
n/a
No.

Jetpack: init 10.6-a.0 cycle

---

projects/plugins/jetpack/changelog/update-jp-10.5-beta-to-test
projects/plugins/jetpack/to-test.md

Jetpack: update to-test.md for 10.5-beta
n/a
No.
Proofread.

Jetpack: update to-test.md for 10.5-beta

---

projects/packages/assets/CHANGELOG.md
projects/packages/assets/changelog/fix-assets-alias_textdomain-during-activation-is-not-_doing_it_wrong

Release assets package version 1.16.1 so we can use it in the JP 10.5 release branch.
n/a
No.
Proofread.

assets: release package version 1.16.1

---

pnpm-lock.yaml
projects/js-packages/idc/CHANGELOG.md
projects/js-packages/idc/changelog/add-idc-errors
projects/js-packages/idc/package.json
projects/js-packages/storybook/changelog/jetpack-branch-10.5
projects/js-packages/storybook/changelog/update-js-pkg-idc-v0.8.0
projects/js-packages/storybook/package.json
projects/packages/identity-crisis/changelog/jetpack-branch-10.5
projects/packages/identity-crisis/changelog/update-js-pkg-idc-v0.8.0
projects/packages/identity-crisis/package.json

Release js-packages/idc v0.8.0
n/a
No.

Release js-packages/idc v0.8.0

---

pnpm-lock.yaml
projects/packages/my-jetpack/changelog/add-wordpress-components-my-jetpack
projects/packages/my-jetpack/package.json

* Includes `@wordpress/components` as dep into `my-jetpack`.
No.
Nothing to test.

My Jetpack: Add wordpress components

---

.github/workflows/build.yml

Finding ways to speed this up is on my list, but until then let's bump
the timeout so people's PRs can be merged.
Nothing linkable
No
* Nothing much to test.

actions: Bump build timeout

---

projects/plugins/jetpack/changelog/update-version-jetpack-atomic-106a4
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start a new release cycle following the 10.6-a.3 Atomic release.
* N/A
* No
* Is CI Happy?
* Check if the release version matches what's expected (10.6-a.4)

Release management: start new release cycle

---

docs/quick-start.md

Updates docs to provide info on installation script.
N/a
No.
Proofread?

Docs: Update info on Monorepo Installation Script

---

.github/workflows/gardening.yml

After #22390, we need to install now before `composer build-development`.
Closes #22398
p1642542122435300-slack-CBG1CP4EN
No
* Make a PR based on this one and see if the gardening workflow works, I guess.

actions: Fix gardening workflow build

---

projects/plugins/jetpack/changelog/update-phpcs-verification-tools
projects/plugins/jetpack/modules/verification-tools/blog-verification-tools.php
projects/plugins/jetpack/modules/verification-tools/verification-tools-utils.php
tools/phpcs-excludelist.json

#21981
Fix phpcs errors in verification tools module.
n/a
no
* Proof/test

PHPCS: Verification Tools

---

projects/plugins/jetpack/CHANGELOG.md

* Bring back changes from the release branch.
* N/A
* No
* Is CI happy?

Janitorial: add changelog for 10.5.1 release

---

projects/plugins/jetpack/changelog/add-release-cycle-107a0
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start new release cycle
* N/A
* No
* Is CI Happy?

Release: start 10.7-a.0 cycle

---

projects/packages/plugins-installer/changelog/fix-install-skin-error-message
projects/packages/plugins-installer/src/class-automatic-install-skin.php

Fixes the method logic
* fix the set_error_message logic
https://github.com/Automattic/jetpack/pull/22477#discussion_r791766602
No
* Read the code

fix the set_error_message logic

---

projects/packages/my-jetpack/changelog/add-my-jetpack-plugin-installation
projects/packages/my-jetpack/changelog/add-my-jetpack-plugin-installation#2
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/products/class-boost.php
projects/packages/plugins-installer/changelog/add-my-jetpack-plugin-installation
projects/packages/plugins-installer/src/class-plugins-installer.php
projects/plugins/backup/changelog/add-my-jetpack-plugin-installation
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/add-my-jetpack-plugin-installation
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

Fixes Fatal error not finding `is_plugin_active` function in some cases
* Uses Plugins Installer package in My Jetpack
p1643227675096100-slack-C02TQF5VAJD
No
* Check all the API requests made in Jetpack Dashboard are working

Uses Plugins Installer package in My Jetpack

---

projects/plugins/jetpack/changelog/fix-easy-markdown-filter-var
projects/plugins/jetpack/modules/markdown/easy-markdown.php

Fixes: https://github.com/Automattic/jetpack/pull/22415#discussion_r791056887
Previously used `filter_var` by mistake when we intended to use `filter_input`
n/a
No
No functionality changes - markdown still work/change seem logical?

Markdown: Fix filter_var usage

---

projects/packages/my-jetpack/changelog/add-hide-my-jetpack-not-connected-site
projects/packages/my-jetpack/src/class-initializer.php

Fixes #22481 
* Do not initialize My Jetpack if site not connected
#22481
No
* New site, disconnect Jetpack
* Verify that the My Jetpack menu is not present
* Connect site at a site level only
* verify that the My Jetpack menu appears
* connect a user
* verify that the My Jetpack many appears

Do not initialize My Jetpack if site not connected

---

projects/packages/my-jetpack/changelog/fix-my-jetpack-tests
projects/packages/my-jetpack/changelog/fix-my-jetpack-tests#2
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/tests/php/test-products-rest.php
projects/plugins/backup/changelog/fix-my-jetpack-tests
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/fix-my-jetpack-tests
projects/plugins/jetpack/composer.lock

Fixes My Jetpack tests not caught in last PR
* Fix My jetpack tests
p1643403981538199-slack-CBG1CP4EN
No
* Watch CI

Fix My jetpack tests

---

.github/files/list-changed-projects.sh

It was dropping the first project, causing needed tests to be skipped.
None
No
* `echo '{ "pull_request": { "base": { "sha": "cd75f368188bc30763623b0d080fdfa1234e8f16" }, "head": { "sha": "cc220d50bc05efbb56009344d93c3f8dc95c178f" } } }' > /tmp/event.json`
* `GITHUB_EVENT_NAME=pull_request GITHUB_EVENT_PATH=/tmp/event.json .github/files/list-changed-projects.sh`
* The last line of output should be `{"packages/my-jetpack":true,"plugins/backup":true,"plugins/jetpack":true}`

Fix list-changed-projects.sh

---

.github/files/setup-wordpress-env.sh

Remove hack now that WP 5.9 is "latest"
None
No
* Is CI happy?

actions: Remove hack now that WP 5.9 is "latest"

---

projects/js-packages/components/changelog/update-js-packages-components-organize-stories
projects/js-packages/components/components/action-button/stories/index.jsx
projects/js-packages/components/components/admin-page/stories/index.jsx
projects/js-packages/components/components/admin-section/stories/index.jsx
projects/js-packages/components/components/automattic-byline-logo/stories/index.jsx
projects/js-packages/components/components/decorative-card/stories/index.jsx
projects/js-packages/components/components/jetpack-footer/stories/index.jsx
projects/js-packages/components/components/jetpack-logo/stories/index.jsx
projects/js-packages/components/components/layout/stories/index.jsx
projects/js-packages/components/components/pricing-card/stories/index.jsx
projects/js-packages/components/components/spinner/stories/index.jsx

This PR suggests changing the organization of stories by project and package. With this, it gets clearer which story belongs to the component and package.
Fixes #
* Components: reorganize stories of js-packages components by project and package name
No
```bash
```
```bash
```
* Open http://localhost:50240
* Take a look at the sidebar
before | after
-----|-------

Components: re organize stories by project and package name

---

projects/packages/my-jetpack/_inc/components/plans-section/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/stories/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-stories-re-organize

In the same spirit of `js-packages/components`, let's reorganize the stories of My Jetpack under the `Projects` section:
Fixes #
*
```bash
```
```bash
```
* Open http://localhost:50240
* Take a look at the sidebar
before | after
-----|-----

My Jetpack: reorganize stories by project/type/

---

projects/plugins/vaultpress/changelog/update-vaultpress-requirements
projects/plugins/vaultpress/readme.txt

Fixes #
* The plugin is compatible with WP 5.9, let's show it in readme.
* N/A
* No

VaultPress: update WordPress version requirements

---

projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-connect-all-products

This PR connects all Product cards with the data provider because it's the time.
* My Jetpack: connect all product cards with data provider
No
* Confirm you see all Product cards properly rendered
* Confirm you can activate/deactivate the products. Some of them will return an error. It's possible to make Boost work.
* You can take a look at the network tab.
https://user-images.githubusercontent.com/77539/151867075-58ff9a7d-18ef-4bfa-ab93-90b90836fb2b.mov

My Jetpack: connect all product cards with data provider

---

projects/plugins/vaultpress/changelog/start-vaultpress-222-cycle
projects/plugins/vaultpress/composer.json
projects/plugins/vaultpress/readme.txt
projects/plugins/vaultpress/vaultpress.php

* VaultPress: start new release cycle
* I'm also taking that opportunity to bring back readme changes with latest changes from the release branch. I really should have included those in #22591 but forgot. 
* N/A
* No
* Is CI happy?

VaultPress: start new release cycle

---

.gitignore
composer.json
composer.lock
docs/examples/bootstrap.php
projects/packages/assets/changelog/add-disallow-relative-includes-2
projects/packages/assets/src/class-assets.php
projects/packages/codesniffer/Jetpack/ruleset.xml
projects/packages/codesniffer/changelog/add-disallow-relative-includes
projects/packages/codesniffer/changelog/add-disallow-relative-includes-2
projects/packages/codesniffer/composer.json
projects/packages/my-jetpack/changelog/add-disallow-relative-includes
projects/packages/my-jetpack/tests/php/test-module-product.php
projects/plugins/debug-helper/changelog/add-disallow-relative-includes-2
projects/plugins/debug-helper/modules/class-broken-token.php
projects/plugins/debug-helper/plugin.php
projects/plugins/jetpack/3rd-party/bbpress.php
projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-about-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-settings-page.php
projects/plugins/jetpack/_inc/lib/debugger.php
projects/plugins/jetpack/changelog/add-disallow-relative-includes
projects/plugins/jetpack/changelog/fix-widget-visibility-roles-wpcom
projects/plugins/jetpack/class.jetpack-network.php
projects/plugins/jetpack/class.jetpack.php
projects/plugins/jetpack/modules/related-posts.php
projects/plugins/jetpack/modules/scan/scan.php
projects/plugins/jetpack/modules/widget-visibility/editor/index.jsx
projects/plugins/jetpack/tests/php/bootstrap.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-callables.php
tools/phpcs-new-rule.sh

- Disallow relative file includes to align with WP.com coding standards
- Update relative path in 3rd-party directory.
WordPress.com hard-enforces no relative file includes so adding this to our Codesniffer.
Additionally, fix existing violations of this standard.
* Adds the WordPress VIP CS to Codesniffer.
* Only include the Disallow Relative Include rule for now.
None.
No.
* Before and after the final commit, run `vendor/bin/phpcs projects/plugins/jetpack/3rd-party`
* Check CI for other violations of this in fully passed files.

Codesniffer: Disallow relative includes

---

projects/plugins/jetpack/changelog/add-init-10.7-a.2-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Starts next Jetpack cycle.
Bumps to 10.7-a.2
n/a
no
* Proof

Jetpack 10.7-a.2 Cycle Start

---

composer.lock
pnpm-lock.yaml
projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/crm-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/_inc/utils/to-camel.js
projects/packages/my-jetpack/changelog/update-my-jetpack-add-product-interstitial-cmp
projects/packages/my-jetpack/package.json

As part of the [Interstitial implementation](https://github.com/Automattic/jetpack/issues/22572), 've created the `<ProductDetailCard />` component that's the base of the `<BoostDetailCard />` and `<BoostDetailCard />` components. Although it still WIP, is a good moment to merge and iterate later. 
Fixes #
* My Jetpack: Add ProductDetailCard component
No
* Build My Jetpack
```bash
> jetpack build packages/my-jetpack
```
```bash
```
```bash
```
* Open http://localhost:50240
* Take a look at the sidebar
**Jetpack Backup**
**Jetpack Boost**
https://user-images.githubusercontent.com/77539/152218141-a87d0759-b959-495b-966d-f2802b645ab8.mov

My Jetpack: Add ProductDetailCard component

---

pnpm-lock.yaml
tools/cli/commands/build.js
tools/cli/commands/install.js
tools/cli/helpers/normalizeArgv.js
tools/cli/helpers/prefix-stream.js
tools/cli/package.json

When building multiple projects, `jetpack build` will now build them in
parallel when possible. A `--concurrency` option is added to limit the
maximum number of concurrent project builds.
We can't quite use this in the GitHub Action yet, as for that we first
need to move all the before-build and after-build code into the build
action somehow. That's left for a future PR.
p9dueE-4dJ-p2
No
* Try it out!
* Note this shouldn't have much of an effect on the CI Build job yet. Might speed up the Boost E2E tests slightly though.

cli: Build in parallel!

---

projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/styles.module.scss
projects/packages/my-jetpack/_inc/hooks/use-notice/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-connection-redirect

Closes #22291
* Update `notice` styles to match `Figma`.
* Redirect `notice` button for `connection` route.
N/A.
No.
* Disconnect Jetpack
* Reconnect it, but doesn't connect wpcom account.
* Navigate to My Jetpack.
* Click in `Connect now`.
* It should redirect you to `ConnectionScreen`.
https://user-images.githubusercontent.com/1663717/152417535-9c28c26c-da6f-45c0-84d3-1191ea6bc6e1.mp4

My Jetpack: Add notice styles improvement and redirect for connection route

---

projects/packages/my-jetpack/changelog/update-my-jetpack-add-title-and-features-to-products-data
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-boost.php
projects/packages/my-jetpack/src/products/class-crm.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-videopress.php
projects/packages/my-jetpack/tests/php/class-broken-product.php

Fixes #
* My Jetpack: Add title and features to products data
No
* Confirm you see title and features fields for Backup and Boost

My Jetpack: Add title and features to products data

---

projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/connection-screen/index.jsx
projects/packages/my-jetpack/_inc/components/go-back-link/index.js
projects/packages/my-jetpack/_inc/components/go-back-link/stories/index.jsx
projects/packages/my-jetpack/_inc/components/go-back-link/styles.module.scss
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/style.module.scss
projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-re-organize-layout

This PR adds the `Go back` link to the Boost interstitial page, refactoring with the most relevant points
* Extract and `<GoBackLink />` component from `<ConnectionScreen />`
* Add a basic `<Layout />` component that adds the `<GoBackLink />` when required
* Set up the `/connection` and `add-boost` routes to show the Go Back link in the header.
* Tweak layout sizes
Fixes #
* My Jetpack: Introduce basic Layout component. Add GoBackLink component
No
* Apply these changes
* Confirm you see the Go Back link for
* `https://<your-testing-site>/wp-admin/admin.php?page=my-jetpack#/connection`
* `https://<your-testing-site>/wp-admin/admin.php?page=my-jetpack#/add-boost`
#/connection | #/add-boost
-----|------
https://user-images.githubusercontent.com/77539/152561814-06a2a26e-82dd-4e19-b9e4-32ad81cf …

My Jetpack: Introduce basic Layout component. Add GoBackLink component

---

projects/packages/my-jetpack/changelog/update-my-jetpack-add-search-product-data
projects/packages/my-jetpack/src/products/class-search.php

This PR adds data for the Search product.
Fixes #
* My Jetpack: add search product data
* Take a look at the `myJetpackInitialState.products.items.search`

My Jetpack: add search product data

---

composer.json
composer.lock

Pin to the current git head, so it won't trigger "lock file is out of
date" every time upstream merges something.
None yet
No
* ???

Pin wpcs dev-develop dependency

---

projects/packages/my-jetpack/changelog/fix-search-typo
projects/packages/my-jetpack/src/products/class-search.php

Fixes typo
It didn't error because PHP namespaces are case insensitive
* Fixes typo
N/A
* Nothing really

My Jetpack: fix typo in search product

---

projects/js-packages/licensing/changelog/fix-license-activation-title-line-height
projects/js-packages/licensing/components/activation-screen-success-info/product-details/style.scss

Fixes 1201509629272450-as-1201653224938704
* Decrease the `line-height` of the title to 52px to make it match designs.
No. It does not.
* Download this PR.
* Start a local version of Jetpack.
* Connect Jetpack to your WP.com account.
* Go to https://cloud.jetpack.com/pricing and purchase any Jetpack product other than Search.
* Do not activate the license.
* Go back to your site's WP Admin.
* Enter the activation flow ( `https://[your-site]/wp-admin/admin.php?page=jetpack#/license/activation` ).
* Enter your license key.
* Verify that the product is activated and that the title's `line-height` is set to 52px.

Jetpack Licensing: decrease `line-height` of the License Activation's title 

---

tools/cli/skeletons/packages/.phpcs.dir.xml

Changes templating in packages generate command to use lowercase letter for text-domain value.
https://github.com/Automattic/jetpack/runs/5109798512?check_suite_focus=true#step:5:31
No
* CI Happy?
*

CLI: Update generate packages template to use lower case value

---

.github/workflows/linting.yml
.github/workflows/phpcompatibility-dev.yml

We missed a lint error introduced in #22482 because the linting jobs
didn't trigger on addition of a `.pnpcs.dir.xml` file. Add that to the
list.
Also we were missing detection of changes to per-directory
`.eslintignore`. And things like `.eslintrc.json` that we don't
currently use. Add them too.
p1644331878798119-slack-CBG1CP4EN
No
* Create a PR reverting #22736. CI should run the linting tests and flag the problem.

actions: Update linting config file checks

---

projects/js-packages/connection/changelog/update-connection-organize-stories
projects/js-packages/connection/components/connect-screen/basic/stories/index.jsx
projects/js-packages/connection/components/connect-screen/required-plan/stories/index.jsx

This PR re organizes the stories aligned to other packages.
Fixes #
* My Jetpack: Re organize components stories by project/name
```bash
```
```bash
```
* Confirm the `connection` components are into `JS PACKAGES` group, together with `COMPONENTS`
before | after
-----|-----

My Jetpack: Re organize components stories by project/name

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-compute-discount-price
projects/packages/my-jetpack/src/products/class-search.php

Show discounted price in Product Detail card. Right now, the discounted price is the same value as the price.
Fixes https://github.com/Automattic/jetpack/issues/22702
* My Jetpack: Show discounted price in Product Detail card
no
* Go to Search detail card `https://<your-testing-site>/wp-admin/admin.php?page=my-jetpack#/add-search`
* Confirm the discounted price is shown there
befpre | after 
-----|-----
Show discounted price in Product Detail card

My Jetpack: Show discounted price in Product Detail card

---

projects/plugins/jetpack/changelog/add-jetpack-10.7-a.4-init
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Inits new Jetpack cycle 10.7-a.4
n/a
No
* Proof

Jetpack 10.7-a.4 Cycle Init

---

projects/packages/my-jetpack/_inc/components/product-detail-card/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/utils.js
projects/packages/my-jetpack/_inc/components/product-interstitial/stories/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-product-stories

Fixes #
* My Jetpack: tidy Product stories
No
**Storybook**
```bash
```
```bash
```
Navigate the Product stories.
Disclaimer: There is an erratic issue that happens when the components are renderer:
Probably you may like to switch between other components to fix this temporary issue.
https://user-images.githubusercontent.com/77539/153284889-459b4ceb-2d21-40f0-907d-fa15113a7778.mov

My Jetpack: tidy Product stories

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/utils.js
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/stories/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-add-anti-spam-product-card
projects/packages/my-jetpack/src/products/class-anti-spam.php

On this PR:
* Fill data into the Anti_Spam class
* Add mock data
* Create Anti-Spam stories
Fixes #
* My Jetpack: Add Anti-Spam Product detail card
No
**Storybook**
```bash
```
```bash
```
`http://localhost:50240/?path=/story/packages-my-jetpack-product-detail-card--jetpack-anti-spam-card`
_Shame note: in case you get the `Cannot read properties of undefined (reading 'map')` error there, please change the product story again and again. It should show, at some moment, the proper visualization._

My Jetpack: Add Anti-Spam Product detail card

---

docs/development-environment.md

* Provides reference to both the ruleset and the monorepo phpcs root.
p1644516494571689-slack-CDLH4C1UZ
n/a
* n/a
*

Docs: Provide both JP rule path and the entry point for JP

---

projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/_inc/hooks/use-my-jetpack-navigate/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-update-backup-data
projects/packages/my-jetpack/src/products/class-backup.php

This PR:
* Updates the Backup product data
* Update the mock data
* ~Update Backup Icon~ Handled [here](https://github.com/Automattic/jetpack/pull/22799) 
* Register and connect `/add-backup` route
Fixes #
* My Jetpack: Update Backup product data. Teak Icon.
* Click on `Add Backup` link
* Confirm you see the Backup Interstitial page. In case you don't have access to the `Add Search` link, open a tab with the `add-backup` route.
```
https://your-testing-site/wp-admin/admin.php?page=my-jetpack#/add-backup
```

My Jetpack: Update Backup product data.

---

.github/workflows/build.yml

We bumped it up in #22357 until I had time to improve the build speed.
Build speed is now improved, so let's turn it back down.
PT: p9dueE-4dJ-p2
No
* Nothing much to test.

actions: Reduce build timeout

---

pnpm-lock.yaml
projects/js-packages/storybook/changelog/try-storybook-addon-turbo-build
projects/js-packages/storybook/package.json
projects/js-packages/storybook/storybook/main.js

The main change here (according to its documentation) is that it will
use esbuild instead of terser for minification. Since we don't need
things like preserving of translator comments in the storybook, that's
probably ok. Let's see how it performs.
PT: p9dueE-4dJ-p2
No
* Is the build faster? (since it touches pnpm-lock, it'll build everything so we can probably tell)
* Check the built storybook artifact. Does it still work?

storybook: Try storybook-addon-turbo-build

---

projects/packages/my-jetpack/_inc/components/icons/index.jsx
projects/packages/my-jetpack/_inc/components/icons/stories/index.jsx
projects/packages/my-jetpack/_inc/components/icons/style.module.scss
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/utils.js
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-add-security-bundle-card

This PR adds the Security Product component to show in the UI.
* Refact icons component adding the ⭐️ Icon
* Refact ProductDetailCard to deal with the `isBundle` variation.
* Add stories - mock security data
Fixes #
* My Jetpack: Add Security Product Bundle
No
**Storybook**
```bash
```
```bash
```
* Check Star Icon is in the Icons section

My Jetpack: Add Security Product Bundle

---

projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/changelog/update-my-jetpack-update-search-product-data

Handles the `Add Search` link in the My Jetpack dashboard, opening the interstitial page by clicking on it
* My Jetpack: Handle Add Search link to my Jetpack dashboard card
No
* `jetpack build packages/my-jetpack` and add constant `define( 'JETPACK_ENABLE_MY_JETPACK', true );`
* Click on the `Add Search` link in the card of my Jetpack dashboard
* Confirm the interstitial page opens.
Card | Interstitial
-----|-----

My Jetpack: Handle `Add Search` link to my Jetpack dashboard card

---

.github/workflows/slack-workflow-failed.yml

This workflow runs after certain other workflows have completed on
pushes to master or release branches. If the other workflow failed, it
will post a message about it to Slack.
Note I've already configured the new channel secret to point to a debug channel (the one at p1644611412383279-slack-C02SV8APDTM). If we merge this now, it'll start reporting there. We can adjust the secret later once we've decided it's working right.
I forget if we ever wrote anything down about this one
No
* Copy this to the master branch of some repo somewhere, set up the secrets, adjust the workflow names and branches if necessary, then have something fail and see if it posts. Or just take my word for it that that's how I made p1644611412383279-slack-C02SV8APDTM happen.
* Merge this, then watch my debug channel …

actions: Send a Slack notification on workflow failure on master

---

projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-add-more-interstitial-pages

This PR finishes the first approach of the interstitial pages. There are some things to keep polishing but better to do it in follow-up PRs.
Fixes #
* My Jetpack: finish the first approach of Backup, Anti-Spam, and Scan interstitial pages
**Storybook**
```bash
```
```bash
```

My Jetpack: finish the first approach of Backup, Anti-Spam, and Scan interstitial pages

---

projects/packages/my-jetpack/_inc/components/product-card/stories/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-remove-duplicated-icon

Remove duplicated Icon component from the Product Card story.
Fixes #
* My Jetpack: Remove duplicated Icon in Product Card story
**Storybook**
```bash
```
```bash
```
Check the Product Card story
`http://localhost:50240/?path=/story/packages-my-jetpack-product-card--default`

My Jetpack: Remove duplicated Icon in Product Card story

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-product-data-bug

This PR fixes an issue that happens with data about security.
Fixes #
*
* Click on `Add Search` link
* You should see the interstitial page.

My Jetpack: set default values for product data in the client side (custom hook)

---

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-gather.php
projects/plugins/jetpack/changelog/update-twitter-unroll-endpoint-revert

Following the discussion in https://github.com/Automattic/jetpack/issues/22744#issuecomment-1033991346 , we reverted the change on WordPress.com in D74671-code.
* N/A
* No
* Not much to test here, this shouldn't change anything for now.

Unroll Twitter Threads: revert changes from #22657

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-provide-security-product-data
projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-security.php

This PR restores the Security Bundle product. For this:
* Define Security data on the server-side
* Removes the temporary [fix](https://github.com/Automattic/jetpack/pull/22847)
Fixes #
* My Jetpack: restore Security bundle product.
* Check `#/add-search` and `#/add-scan` work as expected.
#/add-backup | #/add-scan
------|-----

My Jetpack: restore Security bundle product

---

projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/changelog/my-jetpack-connect-anti-spam-interstitial-page

This PR registers the `#/add-anti-spam` route, and renders the interstitial Anti-Spam component on it.
Fixes #
* My Jetpack: register `#/add-anti-spam` route. Connect with interstitial page.
No
* Go to the add Anti-Spam route
`https://your-testing-site/wp-admin/admin.php?page=my-jetpack#/add-anti-spam`
* Confirm you see the Anti-Spam interstitial page.
~You may see a weird background grey color. It's handled by https://github.com/Automattic/jetpack/pull/22855~

My Jetpack: register `#/add-anti-spam` route. Connect with interstitial page.

---

projects/packages/my-jetpack/changelog/update-connection-check-labels
projects/packages/my-jetpack/src/class-rest-purchases.php

This is a minor fix in the variable names and error messages to make sure we are referring to Site level connection and not USER connection
* Fixed connection check labels and error message
N/A
No
* Check code changes
*

My Jetpack: Fixed connection check labels and error message

---

projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-product-detail-title

* My Jetpack: Fix the title height in the Product detail component
No
* Go to the Search Interstitial page
`https://your-testing-site/wp-admin/admin.php?page=my-jetpack#/add-search`
* Resize changing the viewport width
* Confirm the following visual changes
before | after
----|-----

My Jetpack: Fix the title height in the Product detail component

---

projects/plugins/jetpack/changelog/update-phpcs-json-endpoints
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-add-widget-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-bulk-delete-post-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-bulk-restore-post-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-bulk-update-comments-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-comment-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-delete-media-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-delete-media-v1-1-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php
tools/phpcs-excludelist.json

Fixes #21954
* Fixes PHPCS issues in the first batch of JSON endpoints.
There are a few things I ignored for the sake of velocity. Tried to label them as @todo where appropriate, but if anything jumps out as something we should address now please lmk.
n/a
No
* Proof
* Is there another method of testing these endpoints?

PHPCS: JSON Endpoints bulk/commend/delete/edit

---

projects/packages/my-jetpack/changelog/update-security-bundle-checks
projects/packages/my-jetpack/src/products/class-security.php

* Add proper checks for required plans and action to activate the security bundle
N/A
No
* Check the initial state and verify Security product information
* Buy security or Complete plan and check again that `has_required_plan` is `true`
* Try to POST and activate the product and verify all 3 products of the bundle are activated

My Jetpack: Add proper checks and methods for security product

---

.github/workflows/slack-workflow-failed.yml

The field in the event data is the entire commit message, not just the
summary. We only want the summary in the Slack notification, so trim it
at the first newline.
None
no
* ???

action: Use only commit summary in Slack notification

---

projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/crm-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-manage-url

Closes #22893 
* Add `onManage` redirect on each card pointing for `manageUrl`.
N/A
No.
* Go to `My Jetpack` page
* Make sure that the product is activated.
* Click on `Manage` button.
https://user-images.githubusercontent.com/1663717/154152971-8b2c865f-e22b-4d39-8031-0f86564732e5.mp4

My Jetpack: Add manage url redirect

---

projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-post-counts-v1-1-endpoint.php

- Rename whitelist
- Update comments regarding ignoring wpdb prepare
Merges into #22903
* Updates "whitelist" to better language.
* Verified the prepare ignores and added contextual note.
n/a
n/a
* n/a

PHPCS: JSON Endpoint Updates

---

projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/changelog/update-my-jetpack-change-product-discount-to-50
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-security.php
projects/packages/my-jetpack/src/products/class-videopress.php
projects/packages/my-jetpack/tests/php/test-wpcom-products.php

This PR tweaks Product discount value to `50`
Fixes #
* My Jetpack: tweak Product discount value
* Go to an interstitial page
* Check the discounted value of the product is computed according to the discount of `50`

My Jetpack: tweak Product discount value

---

projects/plugins/jetpack/changelog/add-jetpack-10.7-a.6-init
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Inits Jetpack 10.7-a.6
n/a
No
* Proof'
*

Jetpack 10.7-a.6 Init Cycle

---

projects/packages/my-jetpack/changelog/fix-hybrid-product-plugin-check
projects/packages/my-jetpack/src/products/class-hybrid-product.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/tests/php/test-product-multiple-filenames.php

Fixes error when Backup was incorrectly reporting `plugin_absent` when used only with Jetpack plugin
* Fix check for plugin installation for hybrid products
N/A
No
* Launch a new site only with Jetpack plugin
* Make sure Backup plugin is not installed
* Connect jetpack
* Click on Add Backup
* Complete the purchase
* Back on My Jetpack, make sure Backup displays as Active
* Confirm the Backup plugin was not installed
*

Fix check for plugin installation for hybrid products

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-product-prices
projects/packages/my-jetpack/src/class-wpcom-products.php
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-security.php
projects/packages/my-jetpack/src/products/class-videopress.php
projects/packages/my-jetpack/tests/php/test-wpcom-products.php

On this PR
* Use yearly plans for all products
* Try to pick the discount price from the API
* Otherwise, computes them with 50%
* Update UI
* Fix the checkout links
Fixes #
* My Jetpack: fix product prices and checkout link
* Check the 
before | after
------|-------

My Jetpack: fix product prices and checkout links

---

projects/packages/my-jetpack/_inc/components/product-detail-card/button.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-cta-button

Fix regression on interstitial CTA buttons.
* Update `ProductDetailCard` to use only `isPressed`.
N/A
No.
* Go to `My Jetpack` page.
* Navigate to some interstitial page.
* Hover CTA button
* It should not become blue.

My Jetpack: Fix interstitial CTA button layout

---

.github/files/pr-update-to.sh

I missed [this note][1] when doing #22860
> Note: An event will not be created when you push more than three tags
> at once.
So let's push each tag individually.
[1]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
p1645036637136349-slack-CBG1CP4EN
no
* Can't really test until the next time we do a release.

actions: Push one tag at a time in pr-update-to.sh

---

projects/packages/my-jetpack/changelog/update-my-jetpack-update-crm-manage-link
projects/packages/my-jetpack/src/products/class-crm.php

This changes the manage link of the CRM to point to its dashboard.
Fixes #
* My Jetpack: Point CRM manage link to its dashboard
* Install CRM
* Click on the Manage button
* Confirm you end up in the CRM dashboard
before | after
------|------
https://testing-site/wp-admin/admin.php?page=zerobscrm-plugin-settings | https://testing-site/wp-admin/admin.php?page=zerobscrm-dash

My Jetpack: Point CRM manage link to its dashboard

---

projects/plugins/jetpack/changelog/fix-publicize-wpcom-linting-errors
projects/plugins/jetpack/modules/publicize/publicize.php

This PR fixes some WPCOM-specific linting issues to deploy #22511 and #22974.
* Fix WPCOM-specific linting errors.
No.
* Make sure WPCOM-specific tests are passing.

Publicize: Fix WPCOM-specific linting errors

---

projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-simplify-after-plugin-installation

This is a refactoring PR to simplify the process when the client redirects, or not, to the checkout page after installing/activating a paid product.
Fixes #
* My Jetpack: Simplifies redirect logic after activating Product
No
* Active Jetpack plugin (needed to resolve the `unlinked=1` feature)
* Try to add a paid plan with a Free site
* Confirm you see the page to connect Jetpack
* Buy the plan
* Check it works as expected
Step | screenshot
-----|-----
Add Backup interstitial | <img width="909" alt="image" src="https://user-images.githubusercontent.com/77539/154755341-ce631f71-e6c3-48a1-8ae2-260d8b54c9b3.png">
Installing | <img width="531" alt="image" src="https://user-images.githubusercontent.com/77539/154755966-150b4039-50d0-413d-bc79-6919dccf64bb.png">
Redirected to the connect the user …

My Jetpack: Simplify redirect logic after activating Product

---

.github/workflows/pr-is-up-to-date.yml

Since it's using `pull_request_target` rather than `pull_request`, we
need to manually fetch (but not check out!) the PR and diff against
that, since `master` and `HEAD` are the same thing from
`actions/checkout`.
None really
No
* Make sure that the run with a dummy change to a project includes that project's tag.
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/5289112045?check_suite_focus=true#step:5:19

actions: Use the correct diff in the pr-is-up-to-date workflow

---

projects/plugins/jetpack/changelog/add-jetpack-10.7-test.md
projects/plugins/jetpack/to-test.md

Just updates testing instructions for 10.7
n/a
No
* Proof

Jetpack: 10.7 Testing Instructions

---

projects/plugins/jetpack/changelog/2022-02-22-19-03-45-607900
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Bumps version to 10.8-a.0
Bumps the version
n/a
No
* Proofreadd
*

Init 10.8-a.0 Cylce

---

projects/packages/my-jetpack/changelog/update-my-jetpack-fix-error-500-when-activating-products
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php
projects/packages/my-jetpack/src/products/class-backup.php

Fixes https://github.com/Automattic/jetpack/issues/23040
* My Jetpack: Use Jetpack namespace to fix fatal error
Follow the steps defined in the issue https://github.com/Automattic/jetpack/issues/23040
Confirm you can activate/deactivate the products.

My Jetpack: Use Jetpack namespace to fix fatal error

---

projects/packages/my-jetpack/changelog/update-backup-my-jetpack-doc
projects/packages/my-jetpack/src/products/class-backup.php

Very minor. Just fixing up a docblock.
*
n/a
n/a
* none
*

My Jetpack: Minor inline docs update

---

projects/packages/my-jetpack/CHANGELOG.md
projects/packages/my-jetpack/changelog/update-backup-my-jetpack-doc
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-error-500-when-activating-products
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php

Releases My Jetpack 0.6.3
Changelog file for release.
N/a
No.
* Proof
*

My Jetpack: Release 0.6.3

---

projects/github-actions/pr-is-up-to-date/changelog/fix-pr-is-up-to-date-stray-comma
projects/github-actions/pr-is-up-to-date/funcs.sh

Fixes this warning message
```
.../pr-is-up-to-date/funcs.sh: line 137: local: `MB,': not a valid identifier
```
None
No
* Hard to really test, you'd have to set the right environment variables to be able to run the script locally.

pr-is-up-to-date: Remove a stray comma

---

projects/github-actions/pr-is-up-to-date/changelog/add-pr-is-up-to-date-disable-automatic-gc
projects/github-actions/pr-is-up-to-date/funcs.sh

GitHub's own checkout action disables automatic garbage collection. We
should probably do the same for our checkout.
Plus it stops the automatic GC from getting confused and spamming every
checkout later on like happened in
https://github.com/Automattic/jetpack/runs/5294984428?check_suite_focus=true#step:5:2422
none
no
* Hard to test, you'd have to set the right environment variables to run the script locally.

pr-is-up-to-date: Disable automatic GC

---

projects/plugins/jetpack/changelog/update-testing-list-107
projects/plugins/jetpack/to-test.md

* Bring back testing changes that were removed by mistake in #23030.
* p1645615408011759-slack-CBG1CP4EN
* No

Testing list: bring back changes that were removed in #23030

---

projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-update-headline

This PR updates the My Jetpack headling. Go to #23063 for more detail.
Fixes https://github.com/Automattic/jetpack/issues/23063
* My Jetpack: update My Jetpack dashboard headline
No
* Confirm the headline changes according to the images below
before | after
----|-----

My Jetpack: update My Jetpack dashboard headline

---

projects/packages/my-jetpack/changelog/update-my-jetpack-install-backup-bug
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-hybrid-product.php

This PR fixes the issue reported below. Basically, and thus Backup is a hybrid product, it's possible to activate the product installing/activating the Plugin by itself, or via Jetpack plugin.
This PR activates the self-installed plugin like the first option. Otherwise, will try to install Jetpack.
Fixes https://github.com/Automattic/jetpack/issues/23031
* My Jetpack: handle plugin activating from Hybrid class
No
* Try to reproduce the error described here https://github.com/Automattic/jetpack/issues/23031. It should fix the issue.
* Check Backup is installed when the Jetpack plugin is not installed.

My Jetpack: handle plugin activating from Hybrid class

---

tools/cli/tests/unit/helpers/prefix-stream.test.js

Set the timeout for 110ms so it's less likely to take <100ms like it did
in https://github.com/Automattic/jetpack/runs/5305883453?check_suite_focus=true#step:9:223
none
no
* Kind of hard to really test.

cli: Adjust a timing-related test in prefix-stream.test.js

---

projects/packages/my-jetpack/changelog/fix-hybrid-product-activation
projects/packages/my-jetpack/src/products/class-hybrid-product.php

Small fixes to Hybrid product activation
* Do not silently activate Jetpack. Jetpack has routines hooked to activation that we don't want to skip
* Since the 2 activations happen inside condition, we need to return an error at the end. Otherwise it will look like the activation suceeded (as the doc block says, `activate_plugin` returns NULL on success)
* Minor fixes to Hybrid product activation
p1645646360142999-slack-C02TQF5VAJD
No
See https://github.com/Automattic/jetpack/pull/23071

Do not silently activate Jetpack

---

projects/packages/analyzer/CHANGELOG.md
projects/packages/analyzer/changelog/add-analyzer-api
projects/packages/analyzer/changelog/fix-analyzer-script-default-from-version
projects/packages/analyzer/changelog/renovate-pin-dependencies
projects/packages/analyzer/changelog/update-analyzer-required-php-version
projects/packages/analyzer/changelog/update-slurper-2
projects/packages/analyzer/changelog/update-slurper-script

Been a little while since a release and we've made some changes. Let's ship them out. Nothing else in the repo depends on this package.
* Releasing.
n/a
No.
* None needed.

Analyzer: Release a new version

---

projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-remove-global-notices

Fixes #22502 
* Update `admin` styles to remove global notices.
N/A.
No.
* Goes to `tools/docker/wordpress` in our local env.
* Open `wp-admin/includes/update.php`
* Navigate to `update_nag` method.
* Comment all `if` blocks (probably lines `284-286`, `290-292`, `296-298`).
* Comment current changes applied on this PR.
* Open `My Jetpack` page and you'll see WordPress update version notification.
* Return the code applied on this PR.
* The notice should disappear.

My Jetpack: Remove global notices

---

projects/packages/my-jetpack/_inc/components/icons/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-update-icons

This PR updates the Product Icons definition.
Fixes #
* My Jetpack: update Product Icons
p1HpG7-ePH-p2#comment-52538
No
* Run Storybook
```
> cd ./jetpack/projects/js-packages/storybook
```
```
```
* Go to Icons section
* Confirm icons look as expected
* Go to My Jetpack Dashboard
* Take a look at Product Icons
* Confirm they look as expected

My Jetpack: update Product Icons

---

projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-do-not-apply-height-to-footer-logo

My Jetpack: set height of Jetpack logo in the footer
Fixes #
* My Jetpack: set height of Jetpack logo in the footer
* Confirm the height of the Logo in the footer looks good (16px)
before | after
------|------

My Jetpack: set height of Jetpack logo in the footer

---

projects/packages/my-jetpack/CHANGELOG.md
projects/packages/my-jetpack/changelog/update-release-packages-again
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php
projects/packages/status/CHANGELOG.md
projects/plugins/jetpack/changelog/update-release-packages-again
projects/plugins/jetpack/composer.lock

Releasing these two packages again.
n/a
no
Proof
* Go to '..'
*

Packages: Release Status and My Jetpack (again)

---

projects/packages/my-jetpack/changelog/fix-my-jetapack-browser-cache
projects/packages/my-jetpack/src/class-initializer.php

* Disable browser cache for My Jetpack
N/A
No
* Apply this branch
* Refresh the window a couple of times to make sure new headers are read by the browser
* Open a new tab and go to Plugins
* Activate (or Deactivate) Akismet
* Go to the tab that is open in My Jetpack
* Navigate to any other page in wp-admin
* Hit the "back" button in the browser
* Verify that the "Anti Spam" card reflects the new state
Run the same test in the master branch and confirm that when you go back to My Jetpack, the Anti spam product card still shows the old state.
*

My Jetpack: Disable browser cache for My Jetpack

---

projects/plugins/backup/CHANGELOG.md
projects/plugins/boost/CHANGELOG.md

* Update Boost and Backup changelog from the stable releases.
n/a
no
* Does it blend? (rather does CI pass?)

Backport Boost and Backup changelogs

---

projects/packages/my-jetpack/changelog/udpate-my-jetpack-filter-jetack-plugin-links
projects/packages/my-jetpack/src/class-initializer.php
projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/tests/php/test-hybrid-product.php
projects/packages/my-jetpack/tests/php/test-module-product.php
projects/packages/my-jetpack/tests/php/test-product-multiple-filenames.php
projects/packages/my-jetpack/tests/php/test-products-rest.php
projects/packages/my-jetpack/tests/php/test-wpcom-products.php
projects/plugins/jetpack/changelog/udpate-my-jetpack-filter-jetack-plugin-links
projects/plugins/jetpack/class.jetpack.php

This PR adds the `My Jetpack` action to all Jetpack plugins on the plugins page. It removes code from the Jetpack plugin that adds the same link. 
Fixes https://github.com/Automattic/jetpack/issues/22879
* My Jetpack: add My Jetpack action link to all Jetpack plugins
* Go to wp-admin plugins page: `https://testing-site/wp-admin/plugins.php`
* Take a look at the actions links
* Confirm that you see the `My Jetpack` link to all Jetpack plugins that are installed in your testing site.

My Jetpack: add My Jetpack action link to all Jetpack plugins

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-publicize-classic-editor-save-meta
projects/plugins/jetpack/changelog/fix-publicize-custom-message
projects/plugins/jetpack/changelog/jetpack-branch-10.7
projects/plugins/jetpack/changelog/update-module-activation-hooks
projects/plugins/jetpack/changelog/update-testing-list-107
projects/plugins/jetpack/changelog/update-use-connection-redirect-uri
projects/plugins/jetpack/readme.txt

Backports 10.7 changes back to master.
n/a
No
* Proof it
*

Backport 10.7 Changelog

---

projects/packages/my-jetpack/_inc/components/product-interstitial/stories/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-interstitial-stories

Fixes #
* My Jetpack: fix stories of Interstitial Pages
* Test with the Storybook
```
cd jetpack/projects/js-packages/storybook/
```
```
pnpm install & pnpm storybook:dev
```
Open a tab with `http://localhost:50240/`
* Confirm that Interstitial pages work (almost) as expected.
Known issues:
* Sometimes you need to change the Interstitial page in order to populate the mock data
* Prices are not properly mocked.

My Jetpack: fix stories of Interstitial Pages

---

.gitattributes

We don't need .eslintrc.js in production mirrors.
* see above.
n/a
n/a
* After merge, see if the .eslintrc.js is removed from the beta plugin production mirror.

Exclude eslintrc.js from production mirrors

---

projects/plugins/jetpack/changelog/update-jetpack-10.8-a.2-init-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Jetpack: init 10.8-a.2 cycle
n/a
No.
Proofread.

Jetpack: init 10.8-a.2 cycle

---

projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/changelog/update-my-jetpack-products-data-janitorial
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-security.php
projects/packages/my-jetpack/src/products/class-videopress.php

This is a janitorial PR about product data. It removes a hardcoded `discount` value as well as updates the mock data to polish the Product stories.
Fixes #
* My Jetpack: clean/tidy Product data
No
* Test with a site with a Free site
* Confirm the Intsertitial pages for paid products is ok, for instance `Backup` product
* With the storybook take a look at the stories. The product prices make more sense
*

My Jetpack: clean/tidy Product data

---

projects/packages/my-jetpack/_inc/components/connection-screen/index.jsx
projects/packages/my-jetpack/_inc/components/connection-screen/styles.module.scss
projects/packages/my-jetpack/changelog/update-connection-screen-features-list

Closes #22649 
* Added `See all jetpack features` link at Connect Screen.
N/A
No.
* Disconnect your WordPress.com user.
* Navigate to `My Jetpack` page and clicks to connect user.
* You should see `Connection Screen` with link for all Jetpack Features.

My Jetpack: Add all features link at connection screen

---

tools/check-development-environment.sh

Fixes #23254
* Adds a check for required PHP extensions.
p1646423074599069-slack-CDLH4C1UZ
No.
* cd into the project root.
* Run `tools/check-development-environment.sh`
* Check if all required extensions are installed.
* For extra testing, add a non-existent extension to the script and make sure it fails.

Tools: Check for required PHP extensions

---

tools/docker/Dockerfile

I found I wanted it and it was missing.
None
No
* Is the Build Docker job happy?
* Try `docker run --rm -it ghcr.io/automattic/jetpack-wordpress-dev:pr-23255 bash` and see if `zip` can be run.

Install `zip` in the docker env

---

projects/packages/codesniffer/changelog/update-codesniffer-is-test-hack
projects/packages/codesniffer/hacks/PHPUnitTestTrait.php
projects/plugins/jetpack/changelog/update-codesniffer-is-test-hack
projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-authentication.php
projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-external-media.php
projects/plugins/jetpack/tests/php/core-api/wpcom-fields/test-class.service-api-keys.php
projects/plugins/jetpack/tests/php/core-api/wpcom-fields/test-class.subscribers-endpoint.php
projects/plugins/jetpack/tests/php/modules/post-by-email/test-class.post-by-email-api.php
projects/plugins/jetpack/tests/php/modules/widgets/migrate-to-core/test_migrate-to-core-gallery-widget.php
projects/plugins/jetpack/tests/php/sync/server/class.jetpack-sync-test-replicastore.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-posts.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-queue.php
projects/plugins/jetpack/tests/php/sync/test_interface.jetpack-sync-replicastore.php

Resync the trait with upstream, and update our hack to detect "Testcase"
and "Testbase" too. Then fix the affected sniffs.
Also it turns out `Jetpack_Sync_Test_Replicastore::get_post()` was
returning false when the actual store returns null. Fix that too.
p1646402014118889/1646383848.458609-slack-C034JEXD1RD
No
* Is CI happy?

codesniffer: Update PHPUnitTestTrait hack

---

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-landing-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-settings-page.php
projects/plugins/jetpack/changelog/update-phpcs-admin-pages
tools/phpcs-excludelist.json

Fixes #21948
* Mostly cleared simple errors
* Added wp_kses() in class.jetpack-settings-page
* Replaced the file_get_contents with WP_Filesystem 
n/a
no
* Test all admin pages and see if everything shows up.

PHPCS: admin pages

---

projects/packages/my-jetpack/changelog/fix-backup-flow
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/tests/php/assets/jetpack-mock-plugin.txt
projects/packages/my-jetpack/tests/php/test-hybrid-product.php

Fixes #23252
This was a regression added by https://github.com/Automattic/jetpack/pull/23178
* Fix get_manage_url and get_post_activation_url in the Backup product
#23252
No
* See  #23252

My Jetpack: Fix backup flow

---

projects/plugins/jetpack/changelog/add-init-10.8-a.4
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Jetpack: init 10.8-a.4 cycle
n/a
No.
Proofread.

Jetpack: init 10.8-a.4 cycle

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/add-init-10.8-a.6
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init Jetpack 10.8-a.6 version cycle.
n/a
No.
Proofread.

Jetpack: init 10.8-a.6

---

projects/packages/autoloader/CHANGELOG.md
projects/packages/autoloader/changelog/remove-upgrade-handler

New version of the Autoloader due to the issue with the Upgrade Handler.
* bump
n/a
no
* n/a

Autoloader: Tag next version

---

projects/js-packages/components/changelog/update-theme-provider-new-values
projects/js-packages/components/components/theme-provider/index.jsx
projects/js-packages/components/components/theme-provider/stories/index.jsx

It includes `--jp-gray-10`, `--font-size-body-small` and `--spacing-base` that's being used on `My Jetpack` and is part of our `Design Tokens`.
* Added `3` new vars at `ThemeProvider`.
N/A
No.
* Start `Storybook`
* Goes to `Theme Provider / Tokens`.
* You should see the new values there.

RNA: Add new values from `My Jetpack` at `ThemeProvider`

---

.github/workflows/linting.yml

In #23305 we added a new rule to the Codesniffer that was already included in the provided CS packages, but the check of non-excluded files was skipped since it didn't touch an expected file.
This would run the check anytime something within the Codesniffer package has been updated. Props @anomiex.
* Runs linting for any change in the codesniffer pkg.
p1646781202412169-slack-C032DVAHMK3
No.
* Create a PR off of this to revert the revert done in #23313 and see if the CI catches the issue.

Actions: Check all non-excluded files if something in the codesniffer pkg changed

---

projects/plugins/jetpack/changelog/update-jetpack-qr-post-print-jetpack-logo
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/components/qr-post.js
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/editor.scss
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/hooks/use-site-logo.js

This PR renders a Jetpack logo into the QR Post component when the site doesn't have an icon. It renders the Jetpack logo using the react jetpack-component, to finally convert it to base64 data.
Fixes https://github.com/Automattic/jetpack/issues/23332
* Jetpack: add Jetpack logo as QRPost site logo fallback
* Go to a testing site without a site log
* Publish
* Confirm you see the Jetpack logo in the QR Post code
* Add a site log
* Create a new post. Publish
* Confirm now you see the site logo in the QR Post code

Jetpack: add Jetpack logo as QRPost site logo fallback

---

projects/plugins/jetpack/changelog/update-jetpack-qr-post-tweak-code-width
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/components/qr-post.js

Jetpack: tweak QR Post code width
Fixes #
* Jetpack: tweak QR Post code width
* Get the QR Code
* Confirm the width of the QR code is aligned with the buttons
before | after
-----|-----

Jetpack: tweak QR Post code width

---

tools/get-contributor-list.sh

Matticbot shows up as "Calypso Bot", not "matticbot".
None
No
* Try the command from the script both before and after with an appropriate range of commits, I guess.

tools: Update exclusion in get-contributor-list.sh

---

.github/actions/tool-setup/action.yml
.github/files/gh-autorelease/workflows/autorelease.yml
.github/files/gh-autotagger/workflows/autotagger.yml
.github/files/gh-npmjs-autopublisher/workflows/npmjs-autopublisher.yml
.github/files/gh-wp-svn-autopublish/workflows/wp-svn-autopublish.yml
.github/workflows/block-performance.yml
.github/workflows/build-docker.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/e2e-tests.yml
.github/workflows/gardening.yml
.github/workflows/linting.yml
.github/workflows/phpcompatibility-dev.yml
.github/workflows/pr-is-up-to-date.yml
.github/workflows/renovate-cleanup.yml
.github/workflows/required-review.yml
.github/workflows/stale.yml
.github/workflows/tests.yml
projects/github-actions/push-to-mirrors/README.md
projects/github-actions/push-to-mirrors/changelog/update-actions-to-node16
projects/github-actions/repo-gardening/README.md
projects/github-actions/repo-gardening/action.yml
projects/github-actions/repo-gardening/changelog/update-actions-to-node16
projects/github-actions/repo-gardening/package.json
projects/github-actions/required-review/README.md
projects/github-actions/required-review/action.yml
projects/github-actions/required-review/changelog/update-actions-to-node16
projects/github-actions/required-review/package.json

It seems this has been around since November, although if they announced
it I missed it. Anyway, I'd guess the node12 runner will be going away
soon.
Marking these as major changes since that's what GH did when doing this
to their own actions.
Then adjust the version refs to pull in those major updates to the GH actions.
None
No
* Is CI happy?

Update our actions to use the node16 runner

---

projects/packages/terms-of-service/changelog/add-deprecation-property-tos
projects/packages/terms-of-service/composer.json

This is a tiny change that adds a `deprecated` property to the `composer.json` to prepare it for removal from the Monorepo. This final change was suggested by @sergeymitr to make sure we're letting users know of the package that needs to be installed instead.
* Adds a deprecation property to the composer file.
N/A
* None
* No testing needed.

Add a deprecation property to the hoisted ToS package.

---

.github/workflows/slack-workflow-failed.yml

If it does, we should probably look into it as it probably means that
the tags didn't get updated correctly.
None
No
* Nothing really to test.

actions: Notify Slack if pr-is-up-to-date fails

---

projects/packages/terms-of-service/CHANGELOG.md
projects/packages/terms-of-service/changelog/add-deprecation-property-tos
projects/packages/terms-of-service/changelog/fix-status-needs-caching
projects/packages/terms-of-service/changelog/hoist-jetpack-terms-of-service
projects/packages/terms-of-service/changelog/hoist-jetpack-terms-of-service#2
projects/packages/terms-of-service/src/class-terms-of-service.php

See #23471
Final release of the terms-of-service package before deleting it from the repo.
* final release.
no
no
* none

Final release for ToS package

---

docs/development-environment.md

* Based on feedback in p9dueE-4E8-p2#comment-7562 , I've added a couple more details to the section about developing on Windows.
* N/A
* No

Dev docs: update Windows section

---

tools/cli/commands/changelog.js

Just adds a squash complete success message when squashing is completed. Just for the aesthetics.
n/a
no
* Doesn't need much testing, but you can run `jetpack changelog squash plugins/jetpack` to make sure the success message shows.

CLI: Add Squash Complete Notification

---

pnpm-lock.yaml
tools/cli/commands/changelog.js
tools/cli/package.json

https://github.com/Automattic/jetpack/pull/23500
Removes simple-git dependency. 
None really, we just don't need it anymore now that I know how to fetch the info without the dependency. One less thing to maintain.
No
* This was used to `git add` changelog files when runnin the changelogger, so just try and add a changelog file using `jetpack changelog add [project-type/project] and see if it stages it still.*

CLI: Remove Simple Git Dependency

---

projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-plans-section

Fixes #23489 
Fixes #23512
Fixed #23513
* Update organization and copy of the Plans section
p1HpG7-fbl-p2
No
* Test it without any plans; with one plan and with more than one plan
* Check that the adjustments described in the issue were implemented

My Jetpack: Update organization and copy of the Plans section

---

projects/plugins/jetpack/changelog/phpcs-geolocation
projects/plugins/jetpack/modules/geo-location.php
projects/plugins/jetpack/modules/geo-location/class.jetpack-geo-location.php
tools/phpcs-excludelist.json

PHPCS cleanup for geo-location features.
Closes #21975
No.
Proofread. All changes currently made are non-functional in nature.

PHPCS: Geolocation

---

.github/renovate-config.js

After #23497 fixed some ranges so renovate would see them, we need to
tell it that those ranges should be widened rather than replaced.
No discussion, but prompted by #23548
No
* I guess merge this then see if the next renovate run makes #23548 go away.

renovate: Flag additional packages as needing ranges

---

projects/packages/my-jetpack/_inc/components/connected-product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/hooks/use-product/Readme.md
projects/packages/my-jetpack/_inc/state/actions.js
projects/packages/my-jetpack/changelog/update-my-jetpack-clean-deactivation-product-code

This is a follow-up PR that removes unused code that handles the deactivation process of a product.
Fixes https://github.com/Automattic/jetpack/issues/23546
* My Jetpack: Remove client code that handles the deactivation process of a product
Since it's a janitorial PR, the testing instructions gets reduced to check everything works as expected.
* Check `Activate`
* Check Manage button
* Check Product card status according to product state
* ...

My Jetpack: Remove client code that handles the deactivation process of a product

---

composer.lock

I made a change to our fork, so the lock file needs updating.
None
No
* Is CI happy?
* Check that phpcs stuff still works right.

Update automattic/php_codesniffer ref

---

projects/plugins/jetpack/changelog/update-jetpack-10.8-a.10-init
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Jetpack: init 10.8-a.10 cycle
n/a
No.
Proofread.

Jetpack: init 10.8-a.10 cycle

---

projects/plugins/jetpack/changelog/try-payment-block-jp-upgrade-nudge
projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx
projects/plugins/jetpack/extensions/blocks/recurring-payments/index.js
projects/plugins/jetpack/extensions/store/membership-products/selectors.js

Follow up to #23545
*
* Go to '..'
*

Payment Button Block: Add back the JP upgrade nudge

---

.github/files/lint-project-structure.sh
projects/packages/google-fonts-provider/changelog/add-project-structure-check-for-jetpack-library
projects/packages/google-fonts-provider/composer.json
projects/packages/google-fonts-provider/package.json
projects/packages/plugins-installer/changelog/add-project-structure-check-for-jetpack-library
projects/packages/plugins-installer/composer.json
projects/packages/publicize/changelog/add-project-structure-check-for-jetpack-library
projects/packages/publicize/composer.json
projects/plugins/backup/changelog/add-project-structure-check-for-jetpack-library
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/add-project-structure-check-for-jetpack-library
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/add-project-structure-check-for-jetpack-library
projects/plugins/jetpack/composer.lock
projects/plugins/social/changelog/add-project-structure-check-for-jetpack-library
projects/plugins/social/composer.lock
projects/plugins/starter-plugin/changelog/add-project-structure-check-for-jetpack-library
projects/plugins/starter-plugin/composer.lock

In order for the i18n to actually work, a package with i18n strings must
set its `type` in composer.json to "jetpack-library" so
jetpack-composer-plugin will put it into `jetpack_vendor/` instead of
`vendor/`.
This is easy to overlook, so let's add a check for it.
None
No
* See that the run before fixing the existing packages produces the relevant errors.
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/5680950531?check_suite_focus=true

linting: Check that packages with i18n set `.type` to `jetpack-library`

---

projects/plugins/jetpack/_inc/client/components/button/README.md
projects/plugins/jetpack/changelog/update-button-rna-prop-doc

This PR documents the `rna` prop of the `Button` component in the Jetpack plugin.
[Context](https://github.com/Automattic/jetpack/pull/22255#discussion_r821545940)
No.
Confirm the documentation is clear enough.

Documented the `rna` prop of the Button component

---

projects/js-packages/connection/changelog/fix-react-errors
projects/js-packages/connection/components/connected-plugins/index.jsx
projects/js-packages/connection/components/disconnect-card/index.jsx
projects/js-packages/connection/components/disconnect-dialog/steps/step-disconnect.jsx

* Fixes a couple of React warning and errors
NA
No
* Click Disconnect
* Make sure there are no React errors in the console

Fix react errors

---

tools/cli/helpers/runCommand.js

Setting `shell: true` causes shell metacharacters in arguments to
potentially be expanded, which is unsafe. Better to not pass it,
especially since neither of the existing callers rely on it anyway.
None
No
* Try doing `jetpack changelog add` and supplying a name containing spaces to "Name your change file". It should fail without this PR, and succeed with it.

cli: Don't set `shell: true` in runCommand helper

---

projects/packages/codesniffer/Jetpack/ruleset.xml
projects/packages/codesniffer/changelog/remove-yoda

- Do not flag non-yodas. No opinion if they should be disallowed, but at least stop trying to fix them everywhere.
* Allow Yodas, allow lack of Yoda.
p1648236433120419-slack-C032DVAHMK3
#yolofriday
No.
* None

Codesniffer: Do not enforce Yoda

---

projects/plugins/jetpack/changelog/update-jetpack-10.8-testing-instructions
projects/plugins/jetpack/to-test.md

Update testing instructions for Jetpack 10.8-beta
n/a
No.
Proofread.

Jetpack: update to-test.md for 10.8

---

projects/github-actions/repo-gardening/changelog/update-gardening-fusion-comment
projects/github-actions/repo-gardening/src/tasks/wpcom-commit-reminder/index.js

* ﻿See p1648537618000519-slack-CDLH4C1UZ
* N/A
* No
* Not much to test here, check for typos.

Fusion comment bot: update working to avoid confusion

---

docs/rest-api.md
projects/plugins/jetpack/changelog/update-rest-api-doc

* This is a continuation of #21598, cherry-picking the work done there and finishing off adding language attributes to the other code blocks.
p1648559442875829-slack-C02HQGKMFJ8
No.
* Preview in Markdown - does everything look pretty?

Docs: Adding code highlighting in rest-api.md

---

projects/plugins/jetpack/changelog/update-jetpack-init-10.9-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Jetpack: init 10.9 cycle
n/a
No.
Proofread.

Jetpack: init 10.9 cycle

---

projects/js-packages/base-styles/changelog/fix-quotes-skeleton
projects/js-packages/base-styles/package.json
projects/js-packages/storybook/changelog/fix-quotes-skeleton
projects/js-packages/storybook/package.json
projects/packages/admin-ui/changelog/fix-quotes-skeleton
projects/packages/admin-ui/package.json
projects/packages/admin-ui/src/class-admin-menu.php
projects/packages/google-fonts-provider/changelog/fix-quotes-skeleton
projects/packages/google-fonts-provider/package.json
projects/packages/publicize/changelog/fix-quotes-skeleton
projects/packages/publicize/package.json
tools/cli/skeletons/common/package.json

Orginally flagged in #23587
The skeleton had an unbalanced quote. It didn't cause any harm, I don't think, but let's clean things up. let's tidy things up.
* Fixed unbalanced quote
n/a
No.
* None.

Build: Fix incomplete quote in build command

---

tools/js-tools/git-hooks/pre-commit-hook.js

https://github.com/Automattic/jetpack/pull/23568 seems to have broken the pre-commit hooks when committing changes to Jetpack Boost svelte files.
It looks like it's broken because the pre-commit hook explicitly name the root level `.prettierrc.js` file. As of https://github.com/Automattic/jetpack/pull/23568, Svelte support has been moved into the Jetpack Boost `.prettierrc.js` file.
This PR fixes the problem by ensuring our pre-commit hooks auto-detect the correct prettier file to use for each file being checked. It searches up the path from each file, to find the "closest" prettierrc file to apply.
* Auto-detect the correct prettierrc file to use for each file being checked during pre-commit.
n/a
no
* Make a change to some non-Boost files,
* Make a change to some boost-specific Svelte …

Update pre-commit hook to use local prettier configs per file

---

pnpm-lock.yaml
projects/plugins/boost/changelog/e2e-bump-pw-1.20.1
projects/plugins/boost/tests/e2e/package.json
projects/plugins/jetpack/changelog/e2e-bump-pw-1.20.1
projects/plugins/jetpack/tests/e2e/package.json
projects/plugins/search/changelog/e2e-bump-pw-1.20.1
projects/plugins/search/tests/e2e/package.json
tools/e2e-commons/package.json

Bump e2e tests dependencies to the latest versions.
n/a
no
* CI happy?

Bump e2e dependencies versions

---

projects/js-packages/connection/changelog/update-compoents-connection-status-card
projects/js-packages/connection/components/connection-status-card/index.jsx
projects/js-packages/connection/components/connection-status-card/style.scss

This PR tweak connection card styles and wording.
Fixes https://github.com/Automattic/jetpack/issues/23694
* My Jetpack: tweak connection card styles and wording
* Go to My Jetpack overview
* Ensure the user is not connected
* Confirm after these changes:
* text color is now `--jp-red-60`
* font-size: `16px` (--font-body)
* font-height: `24px` (Text body variant)
before | after
------|------

My Jetpack: tweak connection card styles and wording

---

pnpm-lock.yaml
projects/plugins/protect/changelog/update-protect-replace-connection-screen
projects/plugins/protect/src/js/components/admin-page/index.jsx

* Use the Connection Screen that does not require a plan
N/A
No
* Go to Jetpack Protect and see if the connection works
*

Protect: Change connection screen

---

projects/packages/changelogger/changelog/fix-changelogger-deduplication
projects/packages/changelogger/src/Application.php
projects/packages/changelogger/src/WriteCommand.php
projects/packages/changelogger/tests/php/tests/src/WriteCommandTest.php

If we have a dozen change entries that all say "Updated package
dependencies", those should be deduplicated.
That should happen even if `--deduplicate=0`. Allow setting
`--deduplicate=-1` to disable it if necessary.
https://github.com/Automattic/jetpack/pull/23680#discussion_r837658196
p9dueE-4Ot-p2#comment-7682
No
* Create multiple duplicate change entries in a project, then run `changelogger write`. Only one copy should appear in the output changelog.

changelogger: Deduplicate input entries

---

projects/js-packages/shared-extension-utils/CHANGELOG.md
projects/js-packages/shared-extension-utils/changelog/update-subscribe-block-pages-private
projects/js-packages/shared-extension-utils/package.json

Shared Extension Utils: release v0.4.0
n/a
No.
Proofread, this is a backport release from jetpack/branch-10.8

Shared Extension Utils: release v0.4.0

---

projects/js-packages/components/changelog/update-my-jetpack-interstitial-styles
projects/js-packages/components/components/text/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-interstitial-styles

This PR improves and tweaks the Interstitial pages, conformed some feedback received by designers folks. Significant changes:
* Do not use Layout to define the Product Detail components. Instead of that, Rely on Text and Text-based components (H2, H3, Title...)
* Update box model for feature items list, etc
* Simplify getting the Product Icon
* etc
Fixes #
* My Jetpack: Improve and tweak styles of Product and Interstitial components/pages
* With storybook
* Take a look at Product details components
* Take a look at Interstitial pages
* Take a look at interstitial pages from there
before | after
------|------
**Inspecting Product Detail card**. Pay attention to box-model
https://user-images.githubusercontent.com/77539/161125657-d9195d46-7e23-4c50-9a85-9c47ada735 …

My Jetpack: Improve and tweak styles of Product and Interstitial components/pages

---

projects/packages/changelogger/changelog/update-changelog-error
projects/packages/changelogger/lib/KeepAChangelogParser.php
projects/packages/changelogger/src/Application.php

When doing the manual 1.0 bump in a project's changelog, you need to also update the GitHub compare line at the bottom so the markdown link works 
correctly. The error message is trying to say that but I didn't understand so thinking others might not either.
* Additional text to the error.
See #23711 code review.
n/a
* As of right now, ` tools/changelogger-release.sh packages/my-jetpack `
* Manually update the CHANGELOG.md to 1.0.0 for the latest version, but only do the item at the top.
* `tools/fixup-project-versions.sh` -- see error text.

Changelogger: More verbose error text

---

.github/renovate-config.js

They don't seem to be a monorepo, but they seem to interdepend and get
updated around the same time anyway. So let's group them.
none
no
* I guess you could go to https://github.com/Automattic/jetpack/actions/workflows/renovate.yml and trigger a dry-run pointing at this branch.

renovate: Group GitHub API packages

---

.github/renovate-config.js

Since we switched most of our packages from "library" to
"jetpack-library", renovate is wanting to pin the `require`
dependencies.
Unfortunately renovate doesn't give a way to directly override the type
detection, but we can build a list of packages and override
`rangeStrategy` to match what it should be doing.
None
No
* Possibly going to https://github.com/Automattic/jetpack/actions/workflows/renovate.yml and doing a dry run against this branch would show in the logs that it no longer wants to pin `wikimedia/aho-corasick` to 1.0.1 in projects/packages/waf/composer.json (unlike https://github.com/Automattic/jetpack/runs/5823134906?check_suite_focus=true#step:4:4872 for example)
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/5824474813?check_suite_focus=true#step:4:5200

renovate: Treat our libs as libs

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/add-pro-plan
projects/plugins/jetpack/changelog/fix-carousel-nonce
projects/plugins/jetpack/changelog/jetpack-branch-10.8
projects/plugins/jetpack/changelog/update-crm-panel-non-admins
projects/plugins/jetpack/changelog/update-form-plugin-button-spacing
projects/plugins/jetpack/changelog/update-google-fonts-beta
projects/plugins/jetpack/changelog/update-subscribe-block-pages-private
projects/plugins/jetpack/readme.txt

Backports the 10.8 changelog and readme changes.
n/a
No.
Proofread.

Jetpack: backport 10.8 changelog and readme

---

pnpm-lock.yaml
projects/js-packages/eslint-config-target-es/CHANGELOG.md
projects/js-packages/eslint-config-target-es/changelog/fix-eslint-dependency
projects/js-packages/eslint-config-target-es/changelog/renovate-major-eslint-packages
projects/js-packages/eslint-config-target-es/changelog/renovate-mdn-browser-compat-data-4.x
projects/js-packages/eslint-config-target-es/changelog/renovate-mdn-browser-compat-data-4.x#2
projects/js-packages/eslint-config-target-es/changelog/renovate-mdn-browser-compat-data-4.x#3
projects/js-packages/eslint-config-target-es/changelog/renovate-wordpress-monorepo
projects/js-packages/eslint-config-target-es/changelog/renovate-wordpress-monorepo-2
projects/js-packages/eslint-config-target-es/changelog/update-pnpm-version
projects/js-packages/eslint-config-target-es/package.json
projects/packages/changelogger/CHANGELOG.md
projects/packages/changelogger/changelog/fix-changelogger-deduplication
projects/packages/changelogger/changelog/update-changelog-error
projects/packages/changelogger/src/Application.php
projects/packages/codesniffer/CHANGELOG.md
projects/packages/codesniffer/changelog/add-disallow-relative-includes
projects/packages/codesniffer/changelog/add-disallow-relative-includes-2
projects/packages/codesniffer/changelog/fix-lint-for-dev-deps
projects/packages/codesniffer/changelog/remove-yoda
projects/packages/codesniffer/changelog/update-codesniffer-is-test-hack
projects/packages/codesniffer/changelog/update-phpcs-rules
projects/packages/codesniffer/changelog/update-wpcs-to-dev-branch

Release projects that haven't had releases for 60+ days. 
n/a
No.
Proofread.

Projects: release stale projects as of 10.8

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Updates 	ISSUE_TEMPLATE/bug-report.yml, ISSUE_TEMPLATE/enhancement.yml, and ISSUE_TEMPLATE/feature-request.yml
* Updates 	ISSUE_TEMPLATE/bug-report.yml, ISSUE_TEMPLATE/enhancement.yml, and ISSUE_TEMPLATE/feature-request.yml to include Protect, Search and Social plugins
no
Confirm changes make sense

Issue templates: Update bug, enhancement, and feature request templates to include Protect, Search and Social plugins

---

tools/cli/commands/build.js

Every once in a while the parallel build fails because one process is
writing composer.json at the same moment another process tries to read
it. The reader sees an empty or incomplete file, and composer chokes.
We can avoid these races by writing the file to a temporary name then
renaming it, as a file rename should be an atomic operation.
p1649181153863639-slack-C034JEXD1RD
No
* Is the build happy? Is there no unexpected change in the build artifacts?
* Unfortunately testing the failure is difficult, as it's fairly intermittent. What I did locally was to run two processes, one using the `writeFileAtomic` or `copyFileAtomic` functions introduced here to repeatedly write a file and the other repeatedly reading it and checking if it got an incomplete value.

build: Avoid races when writing composer.json

---

projects/plugins/jetpack/changelog/add-jetpack-10.9-a.2
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init 10.9-a.2 cycle.
n/a
No.
* Proof-read.

Jetpack 10.9-a.2 init

---

docs/quick-start.md

The previous command, which seems like it should work, often doesn't. Switches to the more stable command.
*
* Go to '..'
*

Update quick start docs commands

---

projects/plugins/jetpack/_inc/client/at-a-glance/protect.jsx
projects/plugins/jetpack/_inc/client/security/protect.jsx
projects/plugins/jetpack/changelog/update-protect-name-in-ui
projects/plugins/jetpack/modules/protect.php
projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-authentication.php

This naming matches what we call it in our external marketing, such as in Jetpack.com https://jetpack.com/features/security/brute-force-attack-protection/. 
It changes the UI only, module slug etc are not impacted. 
- Updates the name of the Brute Force Protection feature
One side effect of updating the name in the module header is that it now shows in a different order (alphabetical) in the legacy `/wp-admin/admin.php?page=jetpack_modules` page. 
[pbNhbs-2nv-p2](pbNhbs-2nv-p2)
No
Make sure all the toggles and things to activate/deactivate still work?

Protect: Update name in the UI to "Brute force protection"

---

pnpm-lock.yaml
projects/plugins/starter-plugin/changelog/add-starter-to-beta
projects/plugins/starter-plugin/composer.json
projects/plugins/starter-plugin/composer.lock

- Enable beta plugin to offer the Starter plugin
* This plugin won't be served via w.org, so removing that and adding a slug for the beta plugin instead.
* A mirror repo has already been created.
To assist in testing changes to it. See https://github.com/Automattic/jetpack/pull/23759#issuecomment-1088193975
no
* Does this generate a manifest for the beta server?

Starter Plugin: Serve via Beta Plugin

---

projects/plugins/protect/changelog/update-protect-vulnerabilities-list-redirect
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/stories/index.jsx

Insert the `vulnerability` title and redirect it to `wpscan` database for more details.
* Add `vulnerability.title` usage.
* Redirect `title` for `wpscan/vul-id`.
N/A
No.
* Start `Storybook`
* Navigate to `Protect/Components/VulnerabilitiesList`
* You should see new title and redirect.
https://user-images.githubusercontent.com/1663717/162283960-a6487de3-1b5b-4045-bd2f-ed409416bc2f.mp4

Protect: Add `title` and redirect at `VulnerabilitiesList`

---

tools/cli/commands/build.js

Since we switched to parallel builds, the "reference" fields that
Composer calculates by hashing the composer.json and path-repo options
have been changing with every build, due to nondeterministic content of
those path-repo options.
This makes it deterministic: include only the versions for the
dependencies of the package being built, and include them in
alphabetical order.
None
No
* Run the Build job multiple times. The mirror data in the build artifacts for the multiple runs should be the same.
* :heavy_check_mark: Build artifacts at https://github.com/Automattic/jetpack/actions/runs/2111489345 versus https://github.com/Automattic/jetpack/actions/runs/2111560430 have the same content for all mirrors.

cli: Avoid including ever-changing "reference" in vendor/ files

---

.github/files/process-coverage.sh

If it's inside the group, it's a little harder to find.
None
No
* No idea, you'd have to trigger an error on demand.

actions: Move error outside group in coverage upload'

---

projects/plugins/jetpack/changelog/update-monorepo-10.9-a.3
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init 10.9-a.4 cycle.
n/a
No.
* Proof-read.

Init 10.9-a.4

---

projects/plugins/protect/changelog/add-protect-site-health-check
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/class-site-health.php
projects/plugins/protect/src/class-status.php

* Adds checks to the admin Site Health page
p1HpG7-fgl-p2
No
* Set up your site
* in your wp-config  add:
```
define( 'JETPACK_PROTECT_DEV__BYPASS_CACHE', true );
define( 'JETPACK_PROTECT_DEV__API_RESPONSE_TYPE', 'complete' );
```
* Go to Tools > Site Health
* Check there is a failing check with 3 vulnerabilities found and their titles
* Check the link to Protect page
* Change the value of `JETPACK_PROTECT_DEV__API_RESPONSE_TYPE` to `complete_green`
* Go back to Site Health
* Click on "Passed tests"
* Make sure there's a test saying: "No known vulnerabilities found"
* Check the texts, see if it's ok. look for typos

Protect: Add checks to the Site Health page

---

tools/check-development-environment.sh
tools/cli/bin/jetpack.js
tools/cli/helpers/checkEnvironment.js

Using monorepo tooling with the wrong composer version can cause composer.lock issues which don't get surfaced until CI checks them. This PR will enforce the composer version being used with the CLI to make sure devs are using the version we need to prevent broken PRs. This PR also lays some groundwork in case we want to do additional kinds of checks in the future.
Check seems performant enough to run on every usage of the CLI, but if it's a problem, we could change when it's used. 
Checks the dev environment's composer version against the monorepo required version before running any `jetpack` CLI command, along with instructions on how to fix. *
[N/a](p1649860244940259-slack-C01U2KGS2PQ)
No
* Pull down this PR
* Run `composer self-update` to update composer to the latest version (which …

CLI: Enforce monorepo composer version

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-comment-form-nonce
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Bumps Jetpack to 10.9-a.6 after releasing 10.9-a.5 on atomic.
Bumps to 10.9-a.6
n/a
no
* Proof
*

Init 10.9-a.6 cycle

---

projects/plugins/protect/changelog/add-themes-to-protect-initial-state
projects/plugins/protect/src/class-jetpack-protect.php

* Add intalledThemes to the initial state
N/A
No
* Go to Jetpack > Protect
* Inspect `jetpackProtectInitialState` global var and verify `installedThemes` property

Add intalledThemes to the initial state

---

.phpcs.xml.dist
composer.json
composer.lock
projects/packages/codesniffer/Jetpack/ruleset.xml
projects/packages/codesniffer/changelog/add-codesniffer-missing-wp-rules
projects/packages/codesniffer/composer.json

We're currently pulling in rules from WordPress-Core, WordPress-Docs,
and WordPress-Extra. It turns out that that misses four rules from
"WordPress":
- WordPress.DB.DirectDatabaseQuery
- WordPress.DB.SlowDBQuery
- WordPress.Security.ValidatedSanitizedInput
- WordPress.Utils.I18nTextDomainFixer
WordPress.Utils.I18nTextDomainFixer is no problem, it's redundant to
WordPress.WP.I18n (for some reason they put the fixing logic into a
separate rule) and doesn't report anything unless configured anyway.
WordPress.DB.SlowDBQuery overall seems fairly pointless. It just blindly
looks for assignments to certain array keys with no context, so it's
prone to both false positives and false negatives. Since wpcom doesn't
enforce it either, let's ignore it.
For the other two we'll have to clean up our …

codesniffer: Prepare for adding missing WordPress rules

---

projects/js-packages/connection/changelog/update-jetpack-deactivation
projects/js-packages/connection/components/disconnect-dialog/steps/step-disconnect.jsx
projects/plugins/jetpack/_inc/client/components/jetpack-benefits/index.jsx
projects/plugins/jetpack/_inc/client/portals/plugin-deactivation.jsx
projects/plugins/jetpack/changelog/update-jetpack-deactivation
projects/plugins/jetpack/class.jetpack.php

* Do not hard disconnect Jetpack on plugin deactivation
p9dueE-4n9-p2
No
* Activate a secondary plugin like Boost and/or Backup
* Go to Plugins
* Confirm the link to deactivate Jetpack says only "Deactivate" (and not 'Disconnect and Deactivate')
* Click Deactivate
* Confirm the dialog shows information about the active features you have and no mention to other plugins
* Test with different Jetpack modules active
* Make sure disconnecting from the Jetpack Dashboard still works and shows the survey

Do not hard disconnect Jetpack on deactivation

---

projects/packages/my-jetpack/README.md
projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/add-license-screen/index.jsx
projects/packages/my-jetpack/_inc/components/add-license-screen/styles.module.scss
projects/packages/my-jetpack/changelog/add-licensing-skeleton-to-my-jetpack
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php
projects/plugins/backup/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/boost/composer.json
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock
projects/plugins/protect/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/protect/composer.json
projects/plugins/protect/composer.lock
projects/plugins/search/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/search/composer.json
projects/plugins/search/composer.lock
projects/plugins/social/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/social/composer.json
projects/plugins/social/composer.lock
projects/plugins/starter-plugin/changelog/add-licensing-skeleton-to-my-jetpack
projects/plugins/starter-plugin/composer.json
projects/plugins/starter-plugin/composer.lock

* Adds some skeleton for adding in the licensing UI to My Jetpack.
This is necessary to support handling licenses across standalone plugins.
No.
- Checkout PR
- Go to `$site.com/wp-admin/admin.php?page=my-jetpack#/add-license`
- Ensure that you get an empty page
- Set feature flag per README
- Ensure that page loads
- Ensure that you see hello world
- Ensure no errors in console

My Jetpack: Adds a skeleton for adding the licensing UI to My Jetpack

---

projects/js-packages/components/changelog/update-components-add-button-text-property-to-product-offer-cmp
projects/js-packages/components/components/product-offer/index.jsx
projects/js-packages/components/components/product-offer/stories/index.jsx

It allows customize the button text of the ProductOffer, something needed for future usages.
Fixes #
* RNA: Add buttonText property to the ProductOffer component
* Go to the story of the ProductOffer component
* Check it shows the same message for the button as usual: `Add {product-slug}` 
* Open the controls panel
* Set the custom message by defining the buttonText property
https://user-images.githubusercontent.com/77539/163804883-6fccab3c-314c-49af-991a-712d2a4b0788.mov

RNA: Add buttonText property to the ProductOffer component

---

projects/js-packages/components/changelog/update-protect-add-product-offer-card
projects/plugins/protect/changelog/update-protect-add-product-offer-card
projects/plugins/protect/src/js/components/product-offer/index.jsx
projects/plugins/protect/src/js/components/product-offer/stories/index.jsx

Fixes #
* Protect: add ProductOffer component
* Go to `Plugins / Protect / Product Offer`
* Confirm you see the component there

Protect: add ProductOffer component

---

projects/js-packages/eslint-changed/changelog/update-eslint-changed-package-json-metadata
projects/js-packages/eslint-changed/package.json

I'm considering updating all the projects along these lines, but I want
to do a single project as a test case first.
In particular, let's see what npmjs.com makes of the `.bugs.url` here.
None
No
* Do the URLs work?
* Execute `npm bugs` or `pnpm bugs` in `projects/js-packages/eslint-changed/`. Does it open the right URL?

eslint-changed: Update package.json metadata

---

projects/js-packages/eslint-changed/CHANGELOG.md
projects/js-packages/eslint-changed/bin/eslint-changed.js
projects/js-packages/eslint-changed/changelog/add-jsconfig-to-js-packages
projects/js-packages/eslint-changed/changelog/fix-eslint-dependency
projects/js-packages/eslint-changed/changelog/remove-unneeded-dep
projects/js-packages/eslint-changed/changelog/update-eslint-changed-package-json-metadata
projects/js-packages/eslint-changed/changelog/update-pnpm-version
projects/js-packages/eslint-changed/package.json

Release eslint-changed. Mainly to test #23986.
None
No
* Merge, then see that the auto-tagger and auto-releaser did their things.

eslint-changed: Release v2.0.2

---

projects/plugins/jetpack/changelog/update-phpcs-css-wpcom
projects/plugins/jetpack/modules/custom-css/custom-css.php

* Wpcom has some additional checks for sanitization, this PR just brings things in parity a bit more.
Wpcom diff: D78868-code
p1650302959827749-slack-C032DVAHMK3
no
* Proof and test?
*

PHPCS: Custom CSS Sanitization for WPCOM

---

projects/js-packages/components/changelog/update-js-components-product-description-typhography
projects/js-packages/components/components/product-offer/index.jsx
projects/js-packages/components/components/product-offer/stories/index.jsx
projects/plugins/protect/changelog/update-js-components-product-description-typhography

This PR adds a new `subTitle` property that is rendered just below to the primary title of the ProductOffer component.
Fixes #
* JS Components: add the new subTitle prop to the ProductOffer component
* Go to the ProductOffer component:
`http://localhost:50240/?path=/docs/js-packages-components-product-offer--security-bundle`
* Set a subTitle value using the story controls
* Take a look at the spacing values, font-size, etc.
https://user-images.githubusercontent.com/77539/163850599-f4cb371b-fc30-4017-8bea-fe9edf202db5.mov

JS Components: add the new subTitle prop to the ProductOffer component

---

projects/plugins/jetpack/changelog/add-jetpack-10.9-a.8
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init 10.9-a.8 cycle.
n/a
No.
* Proof-read.

Init 10.9-a.8

---

projects/plugins/protect/changelog/update-protect-add-product-offer-card-component
projects/plugins/protect/src/js/components/product-offer/index.jsx
projects/plugins/protect/src/js/components/product-offer/stories/index.jsx

This PR tweaks the Protect product offer component which will be used to implement the interstitial page and also to deal with the connection workflow.
Fixes #
* Protect: Add product offer component
No
* Go to Plugins / Protect / Product Offer component
* Take a look at the component.
* Play with a couple of props.
https://user-images.githubusercontent.com/77539/164245720-702db069-a246-4d83-8c2b-a66a032c57ac.mov

Protect: Tweak product offer component

---

projects/plugins/protect/changelog/update-protect-add-interstitial-component
projects/plugins/protect/src/js/components/interstitial/index.jsx
projects/plugins/protect/src/js/components/interstitial/stories/index.jsx

This PR adds the first approach of the interstitial page of the Protect plugin. Next step is adding the connection user logic, and also the checkout process for the Bundle product.
The security bundle data is being defined statically. We should to find out a way to share these data among all pkg/plugins/products.
Fixes #
* Protect: Add first approach of Interstitial page
* Go to `Plugins / Protect / Interstitial`
* Take a look at the story
* Confirm data is ok

Protect: Add first approach of Interstitial page

---

pnpm-lock.yaml
projects/plugins/protect/changelog/update-protect-add-prop-types-dep
projects/plugins/protect/package.json

This PR adds the `prop-types` module dependency.
Fixes #
* Protect: Add missing prop-types module dependency
Not too much to do. Check everything is working as expected

Protect: Add missing prop-types module dependency

---

projects/js-packages/components/changelog/update-js-components-add-error-message-to-product-offer
projects/js-packages/components/components/alert/index.jsx
projects/js-packages/components/components/alert/stories/index.jsx
projects/js-packages/components/components/alert/style.module.scss
projects/js-packages/components/components/product-offer/index.jsx
projects/js-packages/components/components/product-offer/stories/index.jsx
projects/plugins/protect/changelog/update-js-components-add-error-message-to-product-offer
projects/plugins/protect/src/js/components/product-offer/stories/index.jsx

On this PR
* Introduce the `<Alert />` component to the jetpack-components pkg
* Add error property to the Protect Product offer component
* Improve story
Note: we need to confirm the colors and the icons with designers' folks. However, and considering that it will be used only by the ProductOffer component with the `error` level, we are wok to go ahead and iterate in follow-up PRs.
Fixes #
* JS Components: Introduce Alert component
* Go to `JS Packages / Components / Alter` component. Play with the story controls
* Go to 'Plugins / Protect / ProductOffer` story.
* Show the error by the control toggle control

JS Components: Introduce Alert component

---

projects/plugins/protect/README.md
projects/plugins/protect/changelog/update-testing-api-options
projects/plugins/protect/src/class-status.php

* Adds support to more options provided by the testing API
No
* See the addition to the README and add the new constant
* Check that the API response include core vulnerabitlites as you requested

support more testing api responses

---

tools/docker/mu-plugins/debug.php

* Removes a feature flag committed in #23974
NA
No
* Checkout PR and build
* Load Jetpack in docker environment
* Ensure the UI loads

Docker: Removes a feature flag inadvertently committed in #23974

---

pnpm-lock.yaml
projects/plugins/protect/changelog/add-protect-footer
projects/plugins/protect/src/js/components/footer/index.jsx
projects/plugins/protect/src/js/components/footer/stories/index.jsx
projects/plugins/protect/src/js/components/footer/styles.module.scss

Just create the component. Clicks will be handled in a follow up
* Creates the Footer component for the Jetpack plugin
NA
No
* Go to Protect -> Footer
* See if looks right in different resolutions
* Note: still need to verify and replace icons

Create Footer component

---

projects/plugins/jetpack/changelog/update-monorepo-11.0
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Init 11.0-a.0 cycle.
N/a.
No.
* Proof-read.

Jetpack 11.0 init cycle

---

projects/plugins/jetpack/changelog/add-10.9-testing-instructions
projects/plugins/jetpack/to-test.md

* Update 10.9 `to-test.md` testing list.
n/a
No.
* Proof-reading for any grammar issues / typos, and to make sure everything is there that should be.

Jetpack 10.9 - updating testing list

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/add-jetpack-10.9-beta-changelog-readme-fixup
projects/plugins/jetpack/readme.txt

* Fixes up the changelog and readme for the 10.9-beta release.
N/a.
No.
* Proof-read.

Jetpack 10.9-beta changelog readme fixup

---

tools/plugin-changelog-to-readme.sh

We're going to try putting these in the changelog going forward, but we
don't want them in the readme too.
No
Someone on a Mac with their old version of `sed` needs to be sure to test this. The change itself should be fine, but I'm not sure of Mac's sed supports comments in the script.
* `jetpack changelog write plugins/starter-plugin --add-pr-num --use-version 1.0.0`
* Verify that the generated changelog includes PR numbers.
* `jetpack release plugins/starter-plugin readme`
* Verify that the changed readme.txt does not include PR numbers.

tools: Strip PR numbers in plugin-changelog-to-readme.sh

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-readme-109-2
projects/plugins/jetpack/readme.txt

Follow-up to #24091
Among other things:
- Ensure each entry is consistent (same use of present tense, capitals).
- Mark new VideoPress feature as major enhancement.
- Remove entries that concern things that were iterated upon during the release cycle.
- Merge some entries together.
- Reword some entries to avoid confusion, or put emphasis on what will be interesting for site owners.
- Order alphabetically.
* N/A
* No

General: tweak changelog and readme contents

---

pnpm-lock.yaml
projects/plugins/boost/changelog/origin-update-remove-unused-outdated-rollup-polyfill-plugin
projects/plugins/boost/package.json
projects/plugins/boost/rollup.config.js

`rollup-plugin-node-builtins` hasn't been updated in 5 years, and
depends on really old versions of a lot of packages.
It turns out that removing this plugin makes no difference to the build:
it still succeeds, and the built files are identical. So let's do that.
If at some point in the future it turns out that a polyfill is needed
again, add one that's up to date (currently `rollup-plugin-polyfill-node`).
None
No
* There should be no change to the built JS as a result of this change.

boost: Remove outdated rollup polyfill plugin

---

projects/packages/connection/changelog/revert-deprecate-soft-disconnect
projects/packages/connection/docs/authorize-user.md
projects/packages/connection/docs/register-site.md
projects/packages/connection/src/class-manager.php
projects/packages/connection/src/class-plugin-storage.php
projects/packages/connection/src/class-plugin.php

This reverts #23991
* Reverts the broken deprecate soft disconnect PR.
p1651023531345719-slack-C02AVAR9B
No
* Tbd/test connection.
*

Revert: Deprecate Soft Disconnect

---

projects/packages/connection/CHANGELOG.md
projects/packages/connection/changelog/revert-deprecate-soft-disconnect
projects/plugins/jetpack/changelog/update-connection-package-changelog-backport
projects/plugins/jetpack/composer.lock

* Backports changelog from connection package release.
n/a
No.
* Proof-read.

Backporting changelog for connection package

---

projects/plugins/protect/changelog/add-protect-footer-implement
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/footer/index.jsx

* Add Footer to the admin page
p1HpG7-fgl-p2
No
* Connect Protect
* Make sure you see the Footer and that it looks good
* Confirm that clicking the Learn more link takes you to the redirect service (the redirect is not registered yet because the page doesn't exist)
* Confirm that clicking the button takes you to the checkout page. 
* Verify the Checkout URL for the site url and redirect url
* verify that when the user is not connected `unlinked=1` is added to the URL
---
- https://app.asana.com/0/0/1202183900595779

Protect: Add Footer to the admin page

---

projects/plugins/jetpack/changelog/fix-custom-css-class-warning
projects/plugins/jetpack/modules/custom-css/custom-css.php

Fixes error thrown on unrelated PRS.
* PHPCS ignore the line totally
no
* CI happy?
*

CSS: Fix CSS warning

---

projects/plugins/jetpack/_inc/client/at-a-glance/search.jsx
projects/plugins/jetpack/changelog/update-glance-search

Fixes #
* Updates plan checks with feature checks for the search box on At a Glance.
No.
* Go to `/wp-admin/admin.php?page=jetpack#/dashboard` on your Jetpack test site.
* On a site with a jetpack search upgrade, make sure the box looks like this: 
* On a site without a search upgrade, make sure the box looks like this:

Search: Use feature checks on At a Glance

---

pnpm-lock.yaml
projects/plugins/protect/changelog/add-api-dep
projects/plugins/protect/package.json

Fixes Build
* Add missing dependency
p1651175991327219-slack-C034JEXD1RD
No
* Watch builds

Protect: add missing dependency

---

projects/plugins/protect/README.md
projects/plugins/protect/changelog/fix-protect-connection-init
projects/plugins/protect/src/class-jetpack-protect.php

Fixes regression introduced in https://github.com/Automattic/jetpack/pull/24117
* Fix connection initialization
NA
No
* Activate Protect plugin alone, without any other Jetpack plugin
* Confirm connecting and disconnecting are working

Protect: Fix connection initialization

---

projects/plugins/jetpack/_inc/client/performance/search.jsx
projects/plugins/jetpack/changelog/update-performance-search

* Updates plan checks with feature checks in Search settings.
No
* [Create a jurassic ninja site](https://jurassic.ninja/specialops/) with Jetpack Beta with this branch being enabled.
* Connect to your site and chose a free plan
* Navigate to `/wp-admin/admin.php?page=jetpack#/performance` and verify the instant search settings are disabled.
* <img width="1019" alt="image" src="https://user-images.githubusercontent.com/1398304/165849503-048324a3-54d6-4ee0-8d67-c6c16370cab5.png">
* Upgrade to a search plan and verify the search settings are available.

Search Settings: Use feature checks for feature gating

---

projects/plugins/jetpack/_inc/client/pro-status/index.jsx
projects/plugins/jetpack/_inc/client/security/waf.jsx
projects/plugins/jetpack/changelog/remove-unused-props

* Removed unused component props.
p9dueE-4T6-p2
No
* Open the changed files and see if you can find any remaining uses/mentions of `planClass`.

Client: Remove unused planClass props

---

projects/plugins/protect/changelog/update-protect-tweak-footer-spacing
projects/plugins/protect/src/js/components/footer/index.jsx
projects/plugins/protect/src/js/components/footer/styles.module.scss

This PR tweaks some visual issues in the Footer component
Fixes #
* Protect: tweak footer section
* Go to Protect plugin.
* Confirm visually the footer looks good
* Take a look at the recording events, just in case (by clicking on the Get Protect button)
before | after
-----|------
---
- https://app.asana.com/0/0/1202204855890077

Protect: tweak footer

---

projects/plugins/jetpack/changelog/phpcs-update-menu-json-endpoint
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-menus-v1-1-endpoint.php

Just undoes a strict comparison check that the wpcom checks caught as problematic.
n/a
No
* Nothing really to test.'
*

PHPCS: One Endpoint Fix

---

projects/js-packages/components/changelog/update-js-components-button-cmp
projects/js-packages/components/components/button/index.jsx
projects/js-packages/components/components/button/stories/Button.mdx
projects/js-packages/components/components/button/stories/index.jsx
projects/js-packages/components/components/button/style.module.scss

This PR adds the `weight` to be able to set the font weight of the button. Some consideration:
* Font weight is `600` as default for all variations/sizes.
* `weight` accepts two values: `bold` (default) and `regular`
Fixes #
* JS Components: add `regular` prop to Button component
p1651518365987469-slack-C02TQF5VAJD
No
* Test with storybook
* Take a look at the doc section
https://user-images.githubusercontent.com/77539/166323470-0b7c37ff-e343-48a5-8ef1-813a63e0a4f1.mov

JS Components: add weight prop to Button component

---

projects/js-packages/connection/CHANGELOG.md
projects/js-packages/connection/changelog/revert-jetpack-soft-disconnect
projects/js-packages/connection/package.json

* Backports changelog from connection package release. Bringing in package changes related to #24209.
n/a
No.
* Make sure the package version numbers are correct (0.17.11), primarily.

Connection package updates backporting to master

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-stable-tag-10.9
projects/plugins/jetpack/readme.txt

Forgot to update the stable tag in the readme.txt when backporting to master. Also updated the link in the readme markdown for fun.
n/a
No
* Proof*

Update Readme and Changelog

---

projects/plugins/jetpack/changelog/add-init-11.0-a.2
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init 11.0-a.2
*n/a
n/a
no
* Go to '..'
*

Init 11.0-a.2

---

projects/plugins/protect/changelog/update-remove-full-sync
projects/plugins/protect/src/class-jetpack-protect.php

Full Sync Immediately is now added by default. See https://github.com/Automattic/jetpack/pull/24237
*
p9dueE-51L-p2#comment-7855
No
* Activate and Connect Protect
* Activate Jetpack Debug tools
* Go to Jetpack Debug and activate "Sync Data Settings Utility"
* Go to Jetpack Debug -> Sync Data Settings Utility
* Make sure `Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately` is part of the `jetpack_sync_modules` list
---
- https://app.asana.com/0/0/1202210952011295

Protect: remove full_sync from sync configuration

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-Fixed-changelog-readme-11.0-a.1
projects/plugins/jetpack/readme.txt

Fixing changelog and readme for 11.0-a.1
n/a
n/a
no
* Go to '..'
*

Fixed changelog and readme for 11.0-a.1

---

projects/plugins/jetpack/changelog/fix-flaky-test
projects/plugins/jetpack/extensions/shared/test/execution-lock-test.js

The test sometimes measures 1 ms less than expected. Take that into
account.
And while we're at it, reduce the time taken by these waiting tests. We
can probably get accurate results with delays 10× shorter than was being
used.
p1651686422507089/1651686269.756069-slack-C034JEXD1RD
No
* Run the test many times (e.g. `while pnpm jest extensions/shared/test/execution-lock-test.js; do :; done`). See if it always passes.

jetpack: Fix a flaky test added in #24140

---

projects/plugins/boost/changelog/improve-boost-wordpress-org-listing-patch
projects/plugins/boost/readme.txt

Same project as previously here `pc9hqz-o8`
No
No testing needed. Readme.txt change

putting back in the except as accidentally removed it when adding to body

---

projects/plugins/jetpack/changelog/add-jetpack11.0-a.4
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init 11.0-a.4
*init cycle
n/a
n/a
* Go to '..'
*

Init 11.0-a.4

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-changelog-readme-11.0-a.3
projects/plugins/jetpack/readme.txt

- [not verified] Fix changelog and readime
- Add changelog
Update changelog and readme
*n/a
n/a
n/a
* Go to '..'
*

Changelog and readme update for 11.0-a.3

---

projects/packages/publicize/CHANGELOG.md
projects/packages/publicize/changelog/fix-pub-namespace
projects/packages/publicize/package.json

Update the package
*n/a
n/a
n/a
* Go to '..'
*

Publicize: Update package

---

readme.md

- Update Team in `readme.md`
n/a
No.
- Any other updates needed?
- Proofread.

Readme: team updates

---

projects/plugins/protect/changelog/update-disconnection-methods
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/starter-plugin/changelog/update-disconnection-methods
projects/plugins/starter-plugin/src/class-jetpack-starter-plugin.php

This PR updates the usage of the connection package using the proxy method instead of calling individual methods for each step of the disconnection routine.
The new methods make sure we fire the proper hooks and trigger stats and tracks events.
There should be no functional changes.
p9dueE-4n9-p2
No
* Check connection and disconnection work as expected

Protect & Starter: Change methods used to disconnect

---

.github/workflows/linting.yml

The PR that added it doesn't specify, but this was added back when we
still used yarn and didn't use workspaces. Let's see if things work with
this removed, which should save about 5 minutes on these tests.
p1652292300577419-slack-CBG1CP4EN
No
* Should be good to go as long as CI is happy.

linting: Remove `jetpack install --all`

---

projects/plugins/jetpack/changelog/phpcs-jetpack-class-more
projects/plugins/jetpack/class.jetpack.php

A partial PHPCS for class.jetpack.php. Restarting making slow/steady progress on this file. See #21952
* General PHPCS
n/a
No.
* Verify the changes are not problematic.

PHPCS: class.jetpack.php

---

projects/plugins/jetpack/changelog/update-response-themes
projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-themes-endpoint.php

Fixes https://github.com/Automattic/wp-calypso/issues/62822
* Add `update` to the `_response_format`. It is already included in the response.
p1652805877675499-slack-CBG1CP4EN
No.
* Before and after this patch, hit the v1 /sites/[site]/themes endpoint. Notice that "update" is already part of each theme in either case.

JSON API: Update theme response array to match output

---

projects/plugins/jetpack/changelog/phpcs-class-jetpack
projects/plugins/jetpack/class.jetpack.php

Supports #21952
* More various PHPCS. Just chipping away and not wanting things to get stale with such a large file. This one is mainly "simple" things.
n/a
No.
* Review manually, run Jetpack.

PHPCS: More class.jetpack.php

---

projects/plugins/jetpack/changelog/init-11.0-a.8
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init new cycle 11.0-a.8
*n/a
n/a
n/a
* Go to '..'
*

Init jetpack 11.0-a.8

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-changelog-fix-11.0-a.7
projects/plugins/jetpack/readme.txt

Fixing the changelg file for 11.0-a.7.
Readme fill be generated and cherry-picked after this PR is merged.
*n/a
n/a
n/a
* Read

Changelog fix for 11.0-a.7

---

projects/plugins/jetpack/changelog/init-11.0-a.10
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init 11.0-a.10
*n/a
n/a
n/a
* Go to '..'
*n/a

Init 11.0-a.10

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-master-1091-changelog
projects/plugins/jetpack/readme.txt

This brings back changes from the `jetpack/branch-10.9` branch to `master`.
- Update changelog and readme for point release
- Update stable version to current stable
* N/A
* No
* Do the changes look good?

Jetpack: update changelog with 10.9.1 entries

---

projects/plugins/backup/changelog/start-backup-1.3.1
projects/plugins/backup/composer.json
projects/plugins/backup/jetpack-backup.php

Let's start the next cycle.
* n/a
n/a
n/a
* n/a

Start Backup 1.3.1 cycle

---

projects/packages/backup/.gitattributes
projects/packages/backup/changelog/fix-backup-building
projects/packages/backup/src/class-package-version.php

Let's ship the built files!
* add entry to gitattributes
p1652987289196589-slack-C01U2KGS2PQ
no
* check the built version to make sure the UI works

Fix build for Backup

---

projects/packages/backup/.gitattributes
projects/packages/backup/changelog/fix-backup-building-2

Missed a couple of **
*
n/a
no
* n/a

Fix backup build

---

projects/plugins/debug-helper/changelog/add-debug-helper-modules-page
projects/plugins/debug-helper/modules/class-modules-helper.php
projects/plugins/debug-helper/plugin.php

Adds a new debug helper page/module aimed at easier debugging for Jetpack feature modules. It's kinda useful when jumping between plugins, and testing out expected values of the callables and options. 
Currently it simply lists the values of the `available` and `active` methods and options. 
p1652965539642009-slack-CBG1CP4EN
No
- Enable the debug plugin
- Enable to  Jetpack Modules Debug Helper setting
- Go to `/wp-admin/admin.php?page=modules-helper` to view.

Debug helper: Add helper page for Jetpack modules

---

projects/packages/status/changelog/add-notes-for-wpengine
projects/packages/status/src/class-status.php

See #21504
Adding some inline documentation for easier future reference.
* Just some notes.
n/a
No.
* none

Status: Add documentation re WP Engine

---

projects/packages/backup/CHANGELOG.md
projects/packages/backup/changelog/fix-backup-building
projects/packages/backup/changelog/fix-backup-building-2
projects/packages/backup/src/class-package-version.php
projects/packages/status/CHANGELOG.md
projects/packages/status/changelog/update-module-methods-jetpack-agnostic

New version of the Backup package. Status is coming along for the ride.
* new release
n/a
n/a
* n/a

Backup: New version of the package

---

projects/plugins/jetpack/changelog/init-11.0-a.12
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Init 11.0-a.12
*n/a
n/a
n/a
* n/a

Init Jetpack 11.0-a.12

---

projects/plugins/jetpack/changelog/phpcs-fix-like-nonce
projects/plugins/jetpack/modules/likes/jetpack-likes-settings.php

Fixes issues with the nonces checks introduced in https://github.com/Automattic/jetpack/pull/24368
* Fixes some nonces
https://github.com/Automattic/jetpack/pull/24368
No
* Proof it
* You can test some of the nonce logic by sandboxing the wpcom diff, visiting the wp-admin posts page and opening a post in the classic editor. Try to enable/disable likes per posts.
* Visit 'yourwpcomsandbox.com/wp-admin/options-general.php?page=sharing' and see if the `WordPress.com Likes are` logic works
*

Likes: Fix some nonce issues

---

projects/plugins/jetpack/changelog/fix-incorrect_constant
projects/plugins/jetpack/src/class-tracking.php

E_WARNING: Use of undefined constant COOKIE_PATH - assumed 'COOKIE_PATH' (this will throw an Error in a future version of PHP)
Page:
/xmlrpc.php?for=jetpack
File:
wp-content/plugins/jetpack/src/class-tracking.php:98
Stack Trace:
wp_xmlrpc_server->serve_request, IXR_Server->IXR_Server, IXR_Server->__construct, IXR_Server->serve, IXR_Server->call, Jetpack_XMLRPC_Server->remote_authorize, Automattic\Jetpack\Connection\Manager->authorize, do_action('jetpack_user_authorized'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\Jetpack\Plugin\Tracking->jetpack_user_authorized,
Introduced via #24418
* The correct constant is used, See core:
https://github.com/WordPress/wordpress-develop/blob/95d26d682fb0fcb77fed308436e87914f7ce2e82/src/wp-includes/default-constants.php#L285-L290
N/A
No
* …

Use the correct constant, COOKIEPATH instead of COOKIE_PATH.

---

projects/js-packages/components/changelog/add-col-components-offset
projects/js-packages/components/components/layout/breakpoints.module.scss
projects/js-packages/components/components/layout/col/index.jsx
projects/js-packages/components/components/layout/col/style.module.scss
projects/js-packages/components/components/layout/container/style.module.scss
projects/js-packages/components/components/layout/stories/index.jsx

For some of our layouts we need to start the column, not after the previous one, but some columns after, which makes it necessary to control where the column start or ends..
Example:
```es6
<Col lg={{ start: 6, end: 9 }}>
```
* Move `Container` and `Col` styles to be based on SASS and share key values.
* Open a new option called `start/end` in `Col`.
N/A
No.
_First_
* Start Storybook.
* Navigate to `Components/Layout/Default` story.
* Check usage and do some tests.
_Second_
* Start `Protect | Backup | Social` plugins.
* Navigate to their admin pages and `My Jetpack` page.
* Everything should be the same.

Layout: Support `start/end` prop in `Col` component

---

projects/plugins/jetpack/changelog/e2e-debug-mailchimp-test
projects/plugins/jetpack/tests/e2e/specs/post-connection/pro-blocks.test.js
tools/e2e-commons/pages/wp-admin/blocks/mailchimp.js

This is a temporary quick fix of the broken Mailchimp e2e test. The root cause is being investigated, and this change should be reversed when the problem gets fixed.
n/a
no
- Mailchimp e2e test should pass

E2E tests: fix Mailchimp test

---

projects/plugins/jetpack/changelog/update-format-number-subscribers-block
projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js

* The number of subscribers that will see a post, which is shown in the subscribers panel when publishing, currently it not formatted. This PR adds formatting.
p1653675252620949-slack-C0299DMPG
No
* Checkout PR
* Publish a post on a site that has more than 1,000 subscribers or change the const to a let and manually modify the number

Subscribers: Number format subscribers count for subscribers panel in editor

---

readme.md

Fix minor typos in README, including missing commas and capitalization. 
No
* Do you see any typos?

Fix minor typos in README

---

projects/plugins/jetpack/changelog/update-sync-comments-base
projects/plugins/jetpack/modules/comments/base.php

Small follow-up to #24528 syncing up changes made in D78705-code
n/a
No.
Proofread.

Comments: sync base.php file with D78705 changes

---

pnpm-lock.yaml
projects/plugins/boost/changelog/remove-node-wp-i18n
projects/plugins/boost/package.json
projects/plugins/jetpack/changelog/remove-node-wp-i18n
projects/plugins/jetpack/package.json
projects/plugins/search/changelog/remove-node-wp-i18n
projects/plugins/search/package.json

Back in the day we used this to build pot files and add text domains.
But the pot building was removed long ago in favor of WordPress.org's
translation infrastructure, and the text domain adding is redundant to
eslint and phpcs rules we've had for a while.
None
No
* Nothing should change, this seems to have been entirely unused.

Remove JS dep node-wp-i18n

---

projects/plugins/jetpack/changelog/update-start-111-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start a new release cycle after pushing the Beta.
* N/A
* No
* Is CI Happy?

Jetpack 11.1: start release cycle

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-readme-testing-list
projects/plugins/jetpack/readme.txt
projects/plugins/jetpack/to-test.md

* In preparation for the Beta release, update the changelog, the readme, and the testing list.
* N/A
* No

General: update changelog and testing list.

---

projects/plugins/social/changelog/fix-jetpack-social-screenshot-captions
projects/plugins/social/readme.txt

Update screenshot captions in readme.txt
* Update screenshot captions for Jetpack Social to match new screenshots.
No.
N/A

Jetpack Social: Update screenshot captions in readme.txt

---

projects/plugins/protect/changelog/add-protect-readme-differences-details
projects/plugins/protect/readme.txt

This adds some details to the answer in one of the FAQ questions of the Jetpack Protect plugin.
* No functional changes, just readme text.
Linked doc in pbNhbs-2xP-p2#comment-8729
No.
* None, as there is no functionality changed.

Added details to the FAQ question on how Jetpack Protect is different from other Jetpack products.

---

projects/plugins/protect/changelog/add-protect-post-1.0.0
projects/plugins/protect/composer.json
projects/plugins/protect/jetpack-protect.php

Currently called 1.0.1-alpha
* N/A
* No
Not much to test here.

Start a new release cycle for Jetpack Protect

---

projects/plugins/boost/app/assets/src/js/utils/upgrade.ts
projects/plugins/boost/changelog/update-checkout-to-yearly

Fixes 25-gh-Automattic/boost-cloud
* Clicking "Upgrade Jetpack Boost" button on the Benefits interstitial page redirects to the checkout page with yearly package instead of monthly package.
NA
No
* Go to Jetpack Boost dashboard.
* Click "Upgrade Jetpack Boost" button under Optimize CSS loading.
* Click "Upgrade Jetpack Boost" button on the Benefits interstitial page.
* Ensure that "One year" package is selected by default in the checkout page.

Boost: Update checkout redirection to yearly package

---

projects/plugins/protect/changelog/add-protect-faq-updates
projects/plugins/protect/readme.txt

* Adds two new entries to the Protect FAQ
* Note, this will need to be manually added to wp.org SVN trunk (and the 1.0.0 tag, or no?)
pbNhbs-2xP-p2#comment-8784
pbNhbs-2xY-p2#comment-8774
No.
Preview the readme, make sure it looks fine.

Protect FAQ updates

---

projects/packages/waf/actions.php
projects/packages/waf/changelog/add-suppress-waf-on-atomic

* Adds the Jetpack modules filter removing the `waf` module when on the Atomic platform
Based on pbuNQi-2Oa-p2#comment-4571 and further thinking about the state of the rules.
No.
* Apply this PR on a normal site, possibly via the beta plugin
* Verify that the WAF module still behaves normally
* Verify that standalone mode still works with no errors
* Apply this PR on an Atomic ephemeral site, via the beta plugin
* Verify that even if you had previously enabled it in settings, the WAF does not show up and is disabled

WAF: Disable on atomic

---

projects/packages/waf/CHANGELOG.md
projects/packages/waf/changelog/add-suppress-waf-on-atomic

* This will allow us to ship #24607 in Jetpack 11.0
* N/A
* No

WAF: release a new version

---

projects/packages/waf/CHANGELOG.md
projects/packages/waf/changelog/fix-waf-run-hook

* This will include changes from #24633
* N/A
* No

WAF: prepare new release for Jetpack 11.0

---

projects/plugins/boost/changelog/fix-e2e-tests
projects/plugins/boost/tests/e2e/lib/pages/wp-admin/JetpackBoostPage.js

Fixes Boost e2e tests
* Connection e2e test waits for optimization status API call which is introduced in #24630
p1654515967616059-slack-CBG1CP4EN
No
* Run Boost e2e tests.
* Ensure that connection tests pass.

Boost: Fix connection e2e tests

---

tools/cli/package.json

#24634 and #24635 were fine on their own, but in combination it wound up trying to run the newly-added tests from the skeleton too. Adjust the jest command to fix that.
p1654524763147369-slack-C034JEXD1RD
No
* Is CI happy now?

cli: Only run cli tests, not tests in the skeletons

---

tools/e2e-commons/config/default.cjs
tools/e2e-commons/config/playwright.config.default.cjs
tools/e2e-commons/reporters/reporter.cjs

* Adds simple reporter to log start/finish of the test case/test run.
n/a
n/a
* Check the log file in the CI artifacts.
* Make sure there are entries that indicate the beginning and end of the specs and tests.

E2E Tests: Log start/finish of the test execution

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-backport-changes-11.0
projects/plugins/jetpack/readme.txt

- Backporting readme and changelog updates from 11.0 branch
- Bump versions in readme and changelog updates from 11.0 branch
Fixes #
*
* Go to '..'
*

Backport readme and changelog edits from 11.0 branch

---

projects/plugins/jetpack/changelog/update-jetpack-init-11.1-a.2
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Jetpack: init 11.1 a.2
n/a
No.
Proofread.

Jetpack: init 11.1-a.2

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-jp-11.1-a.1-changelog-editorial
projects/plugins/jetpack/readme.txt

Jetpack: 11.1-a.1 changelog editorial
n/a
No.
Proofread.

Jetpack: 11.1-a.1 changelog editorial

---

projects/plugins/beta/CHANGELOG.md
projects/plugins/beta/changelog/2022-03-09-12-05-34-499604
projects/plugins/beta/changelog/2022-04-12-14-16-42-370110
projects/plugins/beta/changelog/add-beta-plugin-update-uri
projects/plugins/beta/changelog/fix-beta-download-with-v
projects/plugins/beta/changelog/fix-beta-plugin-links
projects/plugins/beta/changelog/fix-composer-dep-or
projects/plugins/beta/changelog/fix-non-jetpack-WordPress.Security.ValidatedSanitizedInput
projects/plugins/beta/changelog/remove-upgrade-handler
projects/plugins/beta/changelog/renovate-lock-file-maintenance
projects/plugins/beta/changelog/renovate-lock-file-maintenance#2
projects/plugins/beta/changelog/renovate-lock-file-maintenance#3
projects/plugins/beta/changelog/update-beta-add-trunk
projects/plugins/beta/changelog/update-changelogger-add-pr-num
projects/plugins/beta/changelog/update-cli-classes
projects/plugins/beta/changelog/update-composer-2.3
projects/plugins/beta/changelog/update-use-package-publicize
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php

* Prepares for the Beta Tester plugin to be released.
n/a
No.
* Proof-read - changes should be in the changelog file, in jetpack-beta.php (and composer.json). There is no readme.txt.

Beta: Preparing the new Beta Tester plugin release

---

projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte
projects/plugins/boost/changelog/fix-e2e-tests-again

Fixes e2e tests
* fix e2e tests
n/a
no
* see e2e tests are fixed.

Fix broken e2e tests

---

projects/plugins/jetpack/changelog/update-jetpack-init-11.1-a.4
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

Jetpack: init 11.1-a.4 cycle
n/a
No.
Proofread.

Jetpack: init 11.1-a.4 cycle

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/update-jp-11.1-a.3-changelog-editorial
projects/plugins/jetpack/readme.txt

Jetpack: 11.1-a.3 changelog editorial
n/a
No.
Proofread.

Jetpack: 11.1-a.3 changelog editorial

---

projects/plugins/protect/changelog/enhancement-protect-remove-superfluous-linebreaks
projects/plugins/protect/readme.txt

... as they are converted to HTML line breaks on the plugin listing page.
There are some superfluous line breaks in the Protect readme which do get translated to HTML line breaks on the plugin listing page.
* Remove the line breaks so they do not appear on the plugin listing page.
1201069996155224-as-1202445188311391 based on p1655131753100419-slack-C029WFNV69M 
No.
* You can paste the new version into wpreadme.com and confirm the breaks are gone.

Removed superfluous line breaks in Protect readme
