Automattic/jetpack

projects/js-packages/storybook/changelog/add-gutenberg-components
projects/js-packages/storybook/storybook/main.js

Adds the live, [published Gutenberg components tree](https://wordpress.github.io/gutenberg/) to Storybook.
* Add live Gutenberg components to the Storybook tool
No
```sh
cd projects/js-packages/storybook
pnpm run storybook:dev
```
Confirm that Gutenberg components appear in the UI, per screenshot:

Add Gutenberg components to Storybook

---

projects/js-packages/base-styles/changelog/try-html-only-stories
projects/js-packages/base-styles/stories/button.scss
projects/js-packages/base-styles/stories/button.stories.mdx
projects/js-packages/storybook/changelog/try-html-only-stories
projects/js-packages/storybook/storybook/main.js
projects/js-packages/storybook/storybook/stories/docs/howto.story.mdx
projects/js-packages/storybook/storybook/style.scss
projects/js-packages/storybook/storybook/webpack.config.js

Adds an example Storybook.JS story in the base-styles package to show how we can sketch out components in this way.
* Add html-only storybook stories in the base-styles package
No
```
cd projects/js-packages/storybook
pnpm run storybook:dev
```
Confirm that there is an Example/HTML story present in the sidebar, and that it shows three button states.

Lightweight HTML stories for component prototyping

---

projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts
projects/plugins/boost/changelog/add-critical-css-418-error

Fixes #20696
Added a new HTTP error suggestion in case of 418 errors.
no
* Force a 418 error (You can do it by targeting `$_GET['jb-generate-critical-css']` in an mu file). 
```
<?php
if ( ! empty( $_GET['jb-generate-critical-css' ] ) ) {
if ( strpos( $_SERVER['REQUEST_URI'], 'sample-page' ) !== false ) {
header("HTTP/1.0 418 I'm A Teapot");
die();
}
}
```
* Try to regenerate critical CSS and check the message.

Boost: Explicit help for 418 errors

---

projects/plugins/jetpack/changelog/fix-carousel-image-sizing-issue
projects/plugins/jetpack/modules/carousel/jetpack-carousel.js

* Increase image max sizes for all images, not just those below 1000px to prevent reported issues with image quality when large images are downsized with photon. (issue reported at p9F6qB-7kv-p2)
No
* Check out PR in local dev and run with external domain name so jetpack can be fully connected
* Turn on image optimisation and carousel
* Upload a very hi res image to gallery, eg. 5000px/10MB + and view in Carousel and make sure resized quality is acceptable
Before:
image reduced from 10MB to 67KB
After:
Image reduced from 10MB to 531KB

Carousel: fix issue with image quality

---

projects/github-actions/required-review/changelog/fix-required-reviews-multiple-paths-and-negation
projects/github-actions/required-review/package.json
projects/github-actions/required-review/src/requirement.js

Passing multiple path-patterns with some of the non-first patterns being
negated gave unexpected results. For example,
paths:
- '!a'
- '!b'
would match everything including `a` and `b`, since the `!a` matches `b`
and the `!b` matches `a`.
What we want is for a non-first negated pattern to only exclude paths
that were matched by an earlier pattern, it should not add new paths.
That's the behavior already implied by README.md.
None
No
* Check out this, then cherry pick #20749 too, then try `projects/github-actions/required-review/test.sh 20518` and examine the output to see that all the "Checking reviewers" in the output include "Members of heart-of-gold" as an option.

required-review: Fix handling of multiple paths and negation

---

tools/cli/commands/clean.js

Chances are they really want to use `tools/composer-update-monorepo.sh`,
so point them in that direction.
p1629214200024600/1628610161.316400-slack-CBG1CP4EN
No
Test 1:
* Run `jetpack clean` and choose a plugin.
* Choose the option to delete `composer.lock`.
* See that it prompts you to confirm, with a suggestion to use `tools/composer-update-monorepo.sh` instead.
Test 2:
* Run `jetpack clean plugins composer.lock`.
* See that it prompts you to confirm, with a suggestion to use `tools/composer-update-monorepo.sh` instead.

CLI: Warn before cleaning a checked-in composer.lock

---

projects/js-packages/storybook/.gitattributes
projects/js-packages/storybook/.gitignore
projects/js-packages/storybook/changelog/fix-storybook-in-mirror-repo
projects/js-packages/storybook/package.json

GH only allows pages to be in `/` or `/docs`, so build to `/docs`.
See #20778
No.
* Check the jetpack-build artifact produced by the "Build" workflow. See that Automattic/jetpack-storybook is present in the archive, with the appropriate contents.
* Merge this, wait for the publish, configure Pages in the mirror repo, and see that the content shows properly at https://automattic.github.io/jetpack-storybook/.

storybook: Change build dir to make GH happy

---

projects/plugins/jetpack/changelog/fix-carousel-null-ref
projects/plugins/jetpack/modules/carousel/jetpack-carousel.js

* The `commentsIcon` may be null if user has "Show comments area in carousel" option turned off, so check that the element reference is not null first.
Internal: p1629487288195100-slack-CB0B2G43X
Patch already applied to wpcom: r230597-wpcom
No.
* Apply changes, and in `/wp-admin/options-media.php` make sure the carousel is enabled, but `Show comments area in carousel` is turned off.
* Open a gallery and make sure you don't receive any JS errors, and that the carousel functions as expected.

Carousel: fix element null ref

---

pnpm-lock.yaml
tools/js-tools/package.json

We always want the monorepo version, and js-tools is private so no need
to really declare the dep.
This will avoid a repeat of the need for #20688.
p1628868885472200/1628868742.471100-slack-CBG1CP4EN
No
* Change the version in `projects/js-packages/eslint-changed/package.json` to something like "2.0.0".
* Run `pnpm install`. It should work without error.

No need for a versioned dep from js-tools to eslint-changed

---

projects/packages/constants/changelog/update-small-packages-annotations
projects/packages/constants/src/class-constants.php
projects/packages/device-detection/changelog/update-small-packages-annotations
projects/packages/device-detection/src/class-device-detection.php
projects/packages/heartbeat/changelog/update-small-packages-annotations
projects/packages/heartbeat/src/class-heartbeat.php
projects/packages/licensing/changelog/update-small-packages-annotations
projects/packages/licensing/src/class-licensing.php

This PR updates the package annotation to match them with the package verison instead of the Jetpack version.
When the annotation refers to a feature that existed before the package was created we are going to change it to the first released version of the package and add a new annotation (eg. `@since-jetpack`) to register when this was first added to the Jetpack plugin
* Updates the annotation versions to match the package version
p9dueE-3cJ-p2
No
* Look at the code
* Check if the versions changed match the conversion table in p9dueE-3cJ-p2

update versions in annotations

---

projects/plugins/jetpack/changelog/e2e-disable-updater-test
projects/plugins/jetpack/tests/e2e/.eslintrc.js
projects/plugins/jetpack/tests/e2e/specs/plugin-updater.test.js

* Temporarily disable plugin updater test until it can be brought to a more stable version.
pd5faL-1m-p2
no
* E2e test pass
* Plugin updater test is skipped

Disable plugin updater test

---

.github/workflows/e2e-tests-atomic.yml
.github/workflows/e2e-tests.yml
projects/plugins/jetpack/changelog/fix-e2e-atomic-workflow

Fix broken e2e on atomic test site workflow caused by missing action. The workflow was probably added at the same time #20838 removed the action.
no
no
* [E2E tests on Atomic sites workflow](https://github.com/Automattic/jetpack/actions/workflows/e2e-tests-atomic.yml?query=branch%3Afix%2Fe2e-atomic-workflow) should run successfully

E2E tests: Fix missing action for atomic workflow

---

.github/files/build-all-projects.sh

* Fix a typo at the top of build-all-projects.sh
* It runs fine when it creates the BUILD_BASE directory itself, but if you create an empty directory beforehand, it stops running, because it mistakenly checks another variable. 
* In bash, run `rm -rf /tmp/build && export BUILD_BASE='/tmp/build' && mkdir $BUILD_BASE && .github/files/build-all-projects.sh`
* Expect to see: Build starts
* Actually see: ` already exists, and is not a directory.`
* After fix, see: Build starts

Change BUILD_DIR -> BUILD_BASE in initial checks of build-all-projects.sh

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Fixes issue `body[1]: options must not include the reserved word, 'None'.` introduced in https://github.com/Automattic/jetpack/pull/20821
More info at: https://gh-community.github.io/issue-template-feedback/structured/#body0-options-must-not-include-the-reserved-word-none
> This is fixed by removing "None" as an option. If you want a contributor to be able to indicate that they like none of those types of pies, you can additionally remove the required validation:
Instead, I've simply changed "None" to "Other" for now.
Internal: p1630349786015800-slack-CDLH4C1UZ
No.
* Proofread, then merge & test issue templates are visible.

Fix issue templates

---

projects/plugins/jetpack/changelog/e2e-dont-throw-cli
projects/plugins/jetpack/tests/e2e/lib/env/playwright-environment.js
projects/plugins/jetpack/tests/e2e/lib/utils-helper.js

* Don't throw if getting debug log from Docker container fails. 
* Changed log level to debug for page errors and requests fails to reduce noise in CI console.
n/a
no
* CI green

E2E tests: improve error handling

---

projects/plugins/jetpack/changelog/fix-pre-connection-test
projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/jetpack.js
projects/plugins/jetpack/tests/e2e/specs/pro-blocks.test.js

One of the pre-connection tests started to fail, presumably after a new connection banner was added. Apparently, new banner gets rendered async, but our tests were expecting the banner to be there already. I added a simple wait, and it does fixes the tests.
n/a
n/a
* Make sure CI is green
*

E2E Tests: Fix pre-connection test

---

projects/plugins/jetpack/changelog/update-carousel_cursor_css
projects/plugins/jetpack/modules/carousel/jetpack-carousel.css

* The cursor should only change to a pointer when over an img or a figcaption that is the sibling of an img.
**I'm not sure if this change adequately covers all situations where images can be opened in the carousel.** If you know any other situations that should be tested (maybe galleries from other plugins?), please let me know.
I'm suggesting this as a possible temporary solution to the issue reported in #13428, until we have a better solution for gallery parsing.
* n/a
* no
1. Install, activate, and connect the master branch of Jetpack.
2. In wp-admin, navigate to Jetpack -> Settings -> Writing. Enable the `Display images in a full-screen carousel gallery` setting. It's in the `Media` section, at the top.
3. Create a new post to test the Gallery block:
a. Add a Gallery block with some …

Carousel: add more specific selectors for the carousel cursor

---

projects/plugins/jetpack/changelog/fix-removing-social-icons
projects/plugins/jetpack/modules/widgets/social-icons/social-icons-admin.js

* Simulating a click on `.widget-control-save` doesn't seem to work as it
did previously, so we're triggering a change event in a different way
here.
* Fixes #20846
#20846 
No.
* With changes pulled down, in the Customizer add some social icons to the `Social Icons (Jetpack)` widget.
* Publish those changes.
* Make sure you can see social icons on the frontend.
* Then back in the Customizer, you should be able to edit the widget and `Remove` social icons. The Publish/Update buttons should become active without clicking any other widget options.
* These same steps should work in the block-based widget editor as well.
* There should be no JS errors generated.

Social Icons: fix being able to remove icons

---

package.json
pnpm-lock.yaml

They refactored everything to use either 4 or 5, but left a lot of
webpack 4 deps in various subpackages. Either unused, or using
functionality that wasn't changed between 4 and 5.
This PR adds overrides to force webpack 5 in place of 4. That removes a
bunch of webpack 4 deps on chokidar 2, which is itself deprecated and
depends on a version of glob-parent that `pnpm audit` complains about.
None
No
* Is the build happy?
* Does the storybook code in the build artifact look good?

storybook: Use webpack 5 everywhere

---

projects/plugins/jetpack/changelog/update-widget-visibility-editor-readme
projects/plugins/jetpack/modules/widget-visibility/editor/README.md

Follow-up for #20910
* Just a doc update
* ﻿See https://github.com/Automattic/jetpack/pull/20910#discussion_r700195352
* No
* No
* Check for typos?

Widget Visibility build tools: adjust command in readme

---

projects/packages/connection/changelog/fix-reconnect-button-missing
projects/packages/connection/src/class-manager.php
projects/packages/connection/src/class-package-version.php

If user token exists, the connection screen doesn't show the "Connect" button.
Therefore, if reconnect process requires user to reconnect, we need to remove the existing invalid user token so they would be able to connect their WP.com account again.
This PR makes the reconnect process remove user token if it's invalid before initiating the user connection process.
p1630509554174800-slack-CBG1CP4EN
1. Connect Jetpack, then use the "Broken Token" plugin to set an invalid user token.
2. Go to the "Reconnect" modal page: `/wp-admin/admin.php?page=jetpack#/reconnect`, click "Reconnect".
3. Confirm that the "Connect" button shows up.
4. Complete the user connection process, make sure it goes well.
5. Go back to the "Broken Token" plugin and remove the user token entirely, but leave the primary …

Connection: remove invalid user token before reconnect

---

projects/plugins/backup/changelog/fix-backup-dashboard-styling
projects/plugins/backup/src/js/components/Admin.js
projects/plugins/backup/src/js/components/Backups.js
projects/plugins/backup/src/js/components/admin-style.scss
projects/plugins/backup/src/js/components/rna-styles.scss

* fix dashboard styling for the Backup plugin
* bring back the "Cloud" icon, the path changed after the Webpack update (#20789)
p1HpG7-cGL-p2#comment-48367
No.
1. Connect Jetpack Backup, purchase a Backup plan.
2. Confirm that the Dashboard renders well, and looks good.

Backup: fix dashboard styling

---

projects/plugins/jetpack/changelog/update-videopress-block-edit-icon
projects/plugins/jetpack/extensions/blocks/videopress/edit.js

This PR updates the icon for the edit button in the toolbar for the VideoPress block.
**Before**
**After**
I made the icon a bit smaller so that it fits in with the other icons on the toolbar that are still "dashicons".
* Updates edit icon to the svg available at: https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library
pxWta-Zz-p2
No
* Add or edit a VideoPress block, you should see the new icon and clicking it should take the block back to the upload/select video view.
* Hopefully the icon looks nice 😉

VideoPress Block: New Icon for Edit Button

---

projects/packages/sync/changelog/fix-jetpack-sync-checksum-better-woo-handling
projects/packages/sync/src/class-package-version.php
projects/packages/sync/src/class-replicastore.php
projects/packages/sync/src/replicastore/class-table-checksum.php

* Add a check inside the `Table_Checksum` class to verify if WooCommerce tables should be enabled.
* Previously we only checked on the level up - in `Replicastore` and only when we were making a `checksum_all` request.
* Any request for a specific WooCommerce table afterwards would result in a Table not existing error and show up in the error logs.
* This PR changes the behavior and throws an exception if WooCommerce is not enabled.
N/a
No.
* TBD

Jetpack Sync: Checksums: Better handling of WooCommerce tables

---

projects/plugins/jetpack/changelog/fix-tiled-gallery-transform-again
projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/index.js

Fixes #13254
* Instead of setting a default columnWidths in transform, which only works with transforming a very small gallery, check for an empty columnWidths array on mount instead
No
* Check out PR to local dev env
* Add a core gallery block with 4 or more images
* Make sure transform works, then save post/page and make sure it still displays correctly in the editor and frontend

Tiled gallery: fix transform again

---

projects/plugins/jetpack/changelog/fix-button-block-markup
projects/plugins/jetpack/extensions/blocks/button/button.php

Fixes #20924
Since `$wrapper_attributes` is already fully formed, we do not need any extra quotes in the final output.
* No
* No
* Start from a connected site.
* Go to Posts > Add New, and add a Revue block or a MailChimp block.
* Play with the button settings, add custom colors, ..
* Publish your post.
* Ensure the button markup is correct.

Blocks: fix HTML markup of buttons added to our blocks.

---

projects/plugins/jetpack/changelog/update-carousel_css_fix
projects/plugins/jetpack/modules/carousel/jetpack-carousel.css

* The CSS selector for the pointer cursor is incorrect. Fix it by specifying that the `img+figcaption` selector must have the `data-carousel-extra` attribute. This problem was introduced in PR #20882, which has been merged but not released.
* p8oabR-IS-p2#comment-5462
* no
This PR fixes a problem that occurs when the Carousel feature is disabled.
1. Install, activate, and connect the release candidate of Jetpack version 10.1.
2. Create a post with a Gallery block. 
a. Make sure to add multiple images and make sure that the images have captions.
b. Add a Columns block. In each column, add something like a paragraph block with some text.
3. Create a post with a Tiled Gallery block.
a. Make sure to add multiple images.
b. Add a Columns block. In each column, add something like a paragraph …

Carousel: Fix cursor css selector

---

projects/packages/sync/changelog/fix-wporg-notices
projects/packages/sync/src/class-rest-sender.php

Fixes a series of E_NOTICEs thrown when testing on w.org:
```
E_NOTICE: Undefined index: pop in /home//public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:47
```
```
E_NOTICE: Undefined index: encode in /home//public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:66
```
```
E_NOTICE: Undefined index: encode in /home//public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:73
```
* Adds some checks.
n/a
No.
* Unclear how to reproduce, going off of log review.
*

Sync: Defensive coding against E_NOTICE

---

.github/files/renovate-helper.sh
.github/renovate.json

* Helper: Pass `-a` to check-intra-monorepo-deps.sh.
* Use renovate's built-in `packages:eslint` grouping.
* Group JS unit testing packages with `packages:jsUnitTest`.
* Try enabling lock file maintenance, scheduled for the Monday after the
first Tuesday of the month.
* Remove obsolete `ignoreDeps` entries, nothing directly depends on any
of these anymore.
None
No
* Merge, then have renovate rebase #20905, see if the helper works now.
* Merge, then see how renovate reacts.

Update renovate config

---

projects/plugins/jetpack/changelog/update-carousel-nav-colors
projects/plugins/jetpack/class.jetpack.php
projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
projects/plugins/jetpack/tools/builder/frontend-css.js

Sometimes the carousel is showing blue prev/next nav buttons (regardless of black/white carousel color scheme):
Edit: Seems like the root issue has to do with CSS file load order, see: https://github.com/Automattic/jetpack/pull/20940#issuecomment-912148708
Internal, asked in testing: p8oabR-IS-p2#comment-5467
No.
* After applying changes, you should see the carousel nav buttons be based off the carousel color scheme rather than being blue all the time.

Carousel: update prev/next nav button colors

---

projects/plugins/jetpack/changelog/fix-widget-vis-php-notice
projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php

Fix the following PHP notice:
> PHP Notice:  Undefined property: stdClass::$post_status in /var/www/html/wp-admin/includes/misc.php on line 1433
Fixes #18616
#18616
No.
* Before patching, on a site with Jetpack active make sure you have a couple pages published and that the Widget Visibility module is turned on.
* Visit `/wp-admin/widgets.php` and verify that you can see the mentioned PHP Notice.
* Patch with change and make sure that you are no longer seeing the notice when visiting `/wp-admin/widgets.php`.

Widget Visibility: fix undefined property ref

---

tools/check-intra-monorepo-deps.sh

`pnpm install` defaults to `--frozen-lockfile` when running in GH Actions,
which is specifically what we don't want when the renovate helper runs
`check-intra-monorepo-deps.sh -u`. So have it detect when it's running
in CI and pass `--no-frozen-lockfile` in that case (and also omit the
`--silent` that made this so hard to debug).
None
No
* Merge this, then trigger renovate to recreate #20905. Hopefully it works now.

tools: Fix check-intra-monorepo-deps.sh in CI mode

---

.github/workflows/renovate-helper.yml

Currently it looks at the "actor", which on a re-run is apparently the
user re-running the action rather than the user that triggered it in the
first place. Have it look at the user associated with the PR instead.
None
No
* Merge this, then trigger renovate to create a PR. The workflow should run.
* Merge this, then find a renovate PR where renovate[bot] is still the most recent user, and re-run the workflow. It should actually run instead of skipping.

action: Allow renovate helper workflow re-run

---

projects/plugins/jetpack/changelog/fix-calyps-build-hack
projects/plugins/jetpack/tools/webpack.config.extensions.js

Fixes #20898
* Calyspo build's process sets publicPath to '/' instead of the default __webpack_public_path__. This PR overrides the Calypso build config where necessary to prevent breaking image file paths such as those in the block previews.
p1630700944248800-slack-CBG1CP4EN
No
* Go to add a new post
* Check a few blocks, such as slideshow, tiled gallery, image compare, etc. 
* Before this patch, image preview doesn't show images and you'll see errors in the console. 
* Post patch, preview images should appear and console errors regarding GET requests should not be present.
* General regression testing
Fix may need to be applied elsewhere as well, but couldn't find anything else broken in testing so far.

Fix Block Previews

---

.gitignore
tools/js-tools/git-hooks/pre-commit-hook.js
tools/js-tools/git-hooks/prepare-commit-msg.js

Fixes https://github.com/Automattic/jetpack/issues/20969
The code was relying on `.git` being a folder, but this is not always the case. For example, when Jetpack is a submodule within another git repository, `.git` is a file that points to the parent repository's `.git/modules/jetpack` folder.
More information about how `.git` works in the context of a git submodule can be found here: https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.8.txt#L109-L114
* Move git hook data from `.git` to `.git-hook-data`
* Add `.git-hook-data` to the `.gitignore`
This change affects the development setup, related conversation is here: p1630958602197300-slack-C6UJ0KRKQ
No
1. Create a new folder and enter that folder e.g. `mkdir testme && cd testme`
2. Initialize a new git repository: `git …

Fix git hooks when Jetpack is a git submodule of another repository 

---

.github/actions/tool-setup/action.yml
.github/files/list-changed-projects.php
tools/get-wp-version.php

It seems that the default is to set `error_reporting` to
`E_ALL & ~E_DEPRECATED & ~E_STRICT`. Probably more useful to check for
deprecation warnings and such too.
This is probably going to matter once we start testing with PHP 8.1,
which adds return types to a bunch of interfaces and emits
deprecation warnings if you don't use them.
None
No
* Is CI happy?

actions: Display all PHP errors in CI

---

projects/plugins/jetpack/changelog/remove-custom-css-placeholder-text
projects/plugins/jetpack/modules/custom-css/custom-css.php

* Removes placeholder text from the Custom CSS module. This change was already made on wpcom as part of other changes to align the "Additional CSS" area on Simple Sites with Jetpack/Atomic: r230650-wpcom
This text was not previously visible on Jetpack sites.
I was notified when commiting D65448-code
N/A
* Go to Appearance > Additional CSS or the Customizer > Additional CSS
* Check that there is no change and the area works as expected.
* Go to Jetpack > Settings > Writing and enable the Jetpack module:
* Check that additional options show up and work as expected.

Custom CSS: Remove placeholder text to sync with wpcom

---

projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-search-dashboard-page.php
projects/plugins/jetpack/changelog/add-search-menu-translator-context

The menu item for 'Search' can end up being a verb in some languages because we're reusing the translation for "do a search". This PR adds a translator context so it's clear that this a product name shown in the menu.
See 'Disambiguation by context' section here:
https://codex.wordpress.org/I18n_for_WordPress_Developers
Discussed in pxLjZ-6Bs-p2.
No.
On a site with Jetpack Search enabled, go to wp-admin and check that 'Search' appears in the Jetpack submenu. (It will not appear translated because this translation has not been completed yet.)

Search: add translator context to menu item to ensure correct translation

---

tools/cli/commands/cli.js

* Adds a status command that returns what working directory the CLI is linked to. 
Sometimes when working with different checked out versions of the repo, you need to switch which directory the cli is linked to. This lets you see what directory it's currently linked to before switching.
No.
* Check this branch out
* run `jetpack cli status`
* It should return the working directory you're on. 
* After merge, we can test and make sure it returns the correct path if there are multiple checked out repos.

CLI: add 'cli status'

---

projects/plugins/jetpack/_inc/client/components/settings-card/index.jsx
projects/plugins/jetpack/_inc/client/performance/index.jsx
projects/plugins/jetpack/_inc/client/performance/media.jsx
projects/plugins/jetpack/changelog/fix-settings-media-site-only

The Media card gets displayed in the site-only mode if a plan that supports VideoPress has already been purchased.
In this PR we make it show the "Connect" button instead.
p8oabR-IS-p2#comment-5501
No.
1. Create new JN site (free plan), connect it in site-only mode.
2. Go to "Settings -> Performance -> Media", confirm that you see the "Connect" button and don't see the media settings.
3. Click "Connect", connect the user.
4. Go to "Settings -> Performance -> Media", confirm that you see the "Upgrade" button now. No media settings should show up.
5. Click "Upgrade", complete the purchase.
6. Go to "Settings -> Performance -> Media", confirm that you see the media settings. Try to switch the VideoPress setting on and off, confirm that the value persists upon page reloading.
7. Disconnect …

Settings: show "Connect" button on Media card in site-only mode

---

projects/plugins/jetpack/changelog/add-class-subscription-button
projects/plugins/jetpack/modules/subscriptions/views.php

Fixes https://github.com/Automattic/jetpack/issues/16263 
* Adds `wp-block-button__link` to the button on the subscription widget.
NO
1. Add a subscription form to a site
1. Go to the live site
1. Verify that the submit button has the CSS class `wp-block-button__link`

Subscription Block: adds class to submit button

---

projects/plugins/jetpack/changelog/fix-jetpack-sync-unit-tests-failing
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-posts.php

* Fix broken Jetpack Sync unit tests
N/a
N/a
* Run `jetpack docker phpunit -- --filter WP_Test_Jetpack_Sync_`
* Make sure it finishes OK. There are a few tests that are incomplete, but that's not part of this effort.

Jetpack Sync: Fix broken Sync unit tests

---

projects/plugins/jetpack/changelog/fix-api-multisite-test
projects/plugins/jetpack/tests/php/_inc/lib/test_class.rest-api-endpoints.php

After #21030 was merged, it revealed that one of the tests for multisite is failing. I attempted to fix it, but my knowledge is not enough to fix it without breaking other stuff. To fix test coverage, I decided to skip the test for multisite runs for now.
n/a
n/a
* Make sure Code Coverage action is green.
*

Unit tests: test_get_user_connection_data_with_connected_user skip for multisite

---

projects/plugins/jetpack/changelog/fix-screen-options-switcher-tests
projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php
projects/plugins/jetpack/tests/php/modules/masterbar/test-class-base-admin-menu.php

Fixes #21042
Adds back the `test_handle_preferred_view` and `test_register_dashboard_switcher` tests that were skipped in #21030. 
Seems that these tests were unintentionally terminating the `phpunit` process because some AJAX requests were executing the `handle_preferred_view` function hooked into the `admin_menu` action, as opposed to the one hooked into `wp_ajax_set_preferred_view` which is the only one that should kill the WordPress execution.
To fix that, we now have two separate functions which are hooked independently. 
p9dueE-3sh-p2
No.
- Make sure that Jetpack PHPUnit tests actually succeeds (or check [this direct link](https://github.com/Automattic/jetpack/pull/21055/checks?check_run_id=3586164579#step:9:202)).
- Additionally, check that the Nav Unification's screen switcher …

Admin Menu: Fix skipped tests

---

projects/plugins/jetpack/changelog/fix-vr-shortcode-notification-render
projects/plugins/jetpack/modules/shortcodes/vr.php

This PR addresses the issue where the VR shortcode isn't properly rendered in WPCOM notifications.
The proposed code checks whether it is running on WPCOM and then confirms the display context with the help of `/lib/display-context.php`.
(TODO: Add screenshots.)
To be added.
1. Apply the generated patch to WPCOM sandbox as outlined in p7H4VZ-30i-p2.
2. Make sure there is a subscriber on your site that can receive notifications on newly published posts. Notification settings are located in the subscriber's account at `/following/manage` → (gear icon) "Settings" -> "Notify me of new posts" (toggle):
3. Log in to the account of the user that can publish posts on the site.
4. Create and publish a new post that has the `[vr]` shortcode in it. Example shortcode that can be …

Notifications: Fix VR shortcode render

---

projects/github-actions/repo-gardening/changelog/update-repo-gardening-block-plugins
projects/github-actions/repo-gardening/src/tasks/add-labels/index.js

﻿Since #20944, we now have block plugins in their own directory. Let's make sure our auto-labeling system supports that.
* N/A
* No
* Branch off this branch
* Make a change to `projects/plugins/jetpack/extensions/plugins/sharing/editor.js`
* Commit your changes and open a new PR for it. Do not add any labels as you create the PR.
* The Gardening action should add the product label for you.
* See #21035 for an example.

Label Task: handle new block plugin type

---

projects/plugins/boost/app/assets/src/js/utils/generate-critical-css.ts
projects/plugins/boost/changelog/fix-module-toggle-console-error

Fresh installation of Jetpack boost throws the following error.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'enabled')
at jetpack-boost.js?ver=1.3.0-alpha:1
at Object.subscribe (jetpack-boost.js?ver=1.3.0-alpha:1)
at jetpack-boost.js?ver=1.3.0-alpha:1
at jetpack-boost.js?ver=1.3.0-alpha:1
```
* Fix console error on fresh Boost install.
* Check for existence of `critical-css` property in `modulesState` before checking if the module is enabled.
Slack: C0232B8CUHG/p1631611381010500
No
* Go to a site with Jetpack Boost Plugin freshly installed and activated.
* (If the plugin was already activated before, clear the Jetpack Boost related options from the wp_options table)
* Navigate to wp-admin/admin.php?page=jetpack-boost.
* Open the Browser Console and verify that …

Boost: Fix module toggle console error

---

projects/js-packages/connection/changelog/update-rna-connect-button-error-handling
projects/js-packages/connection/components/connect-button/index.jsx
projects/js-packages/connection/components/connect-button/style.scss

RNA Connect Button: Display error message on site registration failure
* Updates the RNA Connect Button component to display an error message when the request to register the site fails.
1199658893173824-as-1200603127282609/f
No
If you're using a JN site, you need to install[ this plugin](https://gist.github.com/sergeymitr/bc005e1b893e778c03e4f43debb91c30) to activate the Connection Manager page.
- Start with a non-connected site
- Sabotage the response from `jetpack/v4/connection/register` by immediately returning a failed response
- Go to Tools->Connection Manager
- Click the "Set up Jetpack" button
- Verify that an error message shows up, as displayed in the following screenshot:
- By clicking "Set up Jetpack" once more, the error message should not be displayed any more.
**Extra bonus …

RNA Connect Button: Display error message on site registration failure

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.native.js
projects/plugins/jetpack/extensions/editor.native.js

Addresses https://github.com/wordpress-mobile/gutenberg-mobile/issues/3904
* Register the Tiled Gallery block for use in Gutenberg Mobile
- p9ugOq-1Tb-p2
No
Since this PR only affects `*.native.*` files, I don't think this needs testing in the context of the web. For native testing, please refer to https://github.com/wordpress-mobile/gutenberg-mobile/pull/3903.

[RNMobile] Register Jetpack Tiled Gallery for native mobile

---

projects/plugins/jetpack/changelog/update-related-posts-img-lazy
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php
projects/plugins/jetpack/modules/related-posts/related-posts.js

Fixes #13068
Let's add the lazy attribute to all images generated for Related Posts (blocks and appended to post content).
* N/A
* No
* Start with a site that's connected to WordPress.com, with Related Posts active, and with enough posts to generate related posts.
* View one of the posts.
* Inspect the related post markup: you should see the `loading="lazy"` attribute.

Related Posts: enable lazy loading for images.

---

.github/workflows/gardening.yml
projects/github-actions/repo-gardening/README.md
projects/github-actions/repo-gardening/changelog/update-repo-gardening-pr-target
projects/github-actions/repo-gardening/package.json
projects/github-actions/repo-gardening/src/get-affected-changelogger-projects.js
projects/github-actions/repo-gardening/src/get-pr-workspace.js
projects/github-actions/repo-gardening/src/index.js
projects/github-actions/repo-gardening/src/tasks/check-description/index.js

This will let them run for PRs from forked repos. Also it'll reduce the
number of workflow runs, since we won't have runs for both
`pull_request` and `pull_request_target`.
The main drawback is some extra complication for the checkDescription
task, as that looks at the filesystem to determine whether changelogger
was properly used.
None
No
* Make a PR targeting this one (or look at #21079). Check that
* The Gardening workflow does not run on `pull_request`.
* All the labels and comments are still applied as appropriate.

repo-gardening: Use `pull_request_target` for all tasks

---

projects/plugins/jetpack/_inc/client/components/footer/index.jsx
projects/plugins/jetpack/_inc/client/components/jetpack-notices/state-notices.jsx
projects/plugins/jetpack/changelog/update-version-jetpack-atomic

﻿We do not need to display the Jetpack version on WoA sites, where that version is managed by the host.
Worth noting that the Jetpack version is still in use internally for things like tracking, but this should stop the display of the version in the Jetpack footer and in the notice that is displayed after updating to a new version of Jetpack.
This PR does not hide the version that's displayed in the Plugins menu. For this, see 745-gh-wpcomsh
* p9dueE-3ca-p2#comment-6130
* No
* Start from an Atomic site that's connected to WordPress.com, but does not use a custom version of Jetpack.
* Go to Jetpack > Dashboard
* In the footer, you should see the current version of Jetpack.
* Install and activate [the Jetpack Beta plugin](https://github.com/Automattic/jetpack-beta/releases/download/3.0.2/jet …

Admin Page: do not display JP version in UI on WoA sites

---

projects/plugins/jetpack/changelog/fix-sharing-icon-position-button
projects/plugins/jetpack/modules/sharedaddy/sharing.css

This fixes the sharing icons position in icon-only button style, which is currently off-center.
Closes https://github.com/Automattic/jetpack/issues/16301.

Sharing: Icon position fix

---

projects/plugins/boost/app/class-jetpack-boost.php
projects/plugins/boost/app/modules/critical-css/class-critical-css.php
projects/plugins/boost/changelog/fix-clear-css-on-theme-switch

Fixes #21068 
* Changed the hook name to `jetpack_boost_clear_critical_css` in file 
https://github.com/amustaque97/jetpack/blob/d221c20edd5c5506e6deae9b789ae27cda4e068f/projects/plugins/boost/app/modules/critical-css/class-critical-css.php#L165
* Calling the same hook inside the `handle_theme_change` function
* Check out my PR and build the boost plugin
* Generate critical CSS for your current theme.
* Change theme to some other different theme.
* Verify that jetpack boost plugin notice is shown to the user
* Verify critical CSS is not loading for the new theme.
Video recording: https://www.youtube.com/watch?v=OznLHatwz-4
CC @eAdnan007 @thingalon

Boost: clear css on theme switch

---

tools/check-development-environment.sh

Similar to https://github.com/Automattic/jetpack/pull/20971, this PR fixes an issue that arises when Jetpack is a submodule of another repository.
Here, when Jetpack is a submodule, the `tools/check-development-environment.sh` script reports not being inside a git checkout and incorrectly prompts the user to clone the repository.
* Switch from inspecting `.git` to inspecting the output of `git rev-parse --git-dir`. This lets the script work properly even when ran within a submodule git checkout of Jetpack.
None, this is just a tweak to the development tools.
No, nothing.
<details><summary>Verify this issue is present on <code>master</code>:</summary>
<p>
```
cd /tmp && mkdir clone1 && cd clone1
git init
git submodule add https://github.com/Automattic/jetpack.git
cd jetpack
npm install -g …
```

Fix check dev env script when Jetpack is submodule

---

projects/js-packages/components/changelog/fix-warning-jetpack-logo
projects/js-packages/components/components/jetpack-footer/index.jsx

﻿JetpackLogo expects a number for its height prop, we were providing a string. This should avoid any warnings when building the component.
* No
* No
* Go to Jetpack > Dashboard, and check that the footer is displayed properly.
* Locally, `cd projects/plugins/jetpack && pnpm build-client`. You should not see any warnings about JetpackLogo using the wrong prop.

Jetpack Components: fix height prop for JetpackLogo

---

tools/docker/bin/install.sh
tools/docker/bin/run.sh
tools/docker/docker-compose.yml

This PR fixes few issues in jetpack docker:
- passes through `$COMPOSE_PROJECT_NAME` env variable into docker context, which is used in `run.sh` and `install.sh` scripts.
- Updates expected project name from `dev` to `jetpack_dev` to match the value set by `docker.js`
n/a
n/a
* Checkout the PR and build the image locally `jetpack docker build-image`. Probably containers need to be recreated with the new image (`jetpack docker clean` should do the trick)
* Nuke the containers and images OR remove `tools/docker/wordpress-develop` folder
* Start the containers, make sure it pulls from SVN as you do so
* run `jetpack docker phpunit`, and make sure it starts the tests.
*

Docker: Fix a bug in $COMPOSE_PROJECT_NAME

---

projects/plugins/backup/changelog/fix-sass-division-deprecation
projects/plugins/backup/src/js/components/masthead/calypso-mixins.scss
projects/plugins/jetpack/_inc/client/scss/calypso-mixins.scss
projects/plugins/jetpack/_inc/client/scss/functions/rem.scss
projects/plugins/jetpack/changelog/fix-sass-division-deprecation
projects/plugins/jetpack/extensions/blocks/donations/view.scss
projects/plugins/jetpack/extensions/blocks/podcast-player/style.scss
projects/plugins/jetpack/extensions/blocks/story/player/style.scss
projects/plugins/jetpack/extensions/blocks/tiled-gallery/editor.scss
projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/editor.scss
projects/plugins/jetpack/scss/atoms/typography/_functions.scss

This fixes the following warnings during sass processing:
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
```
Sass's sass-migrator tool was used to make the fixes.
#20792
No
* Check that the built CSS files have not changed. Note the `.css.map` and `.asset.php` files may have, but they don't matter to display.
* Or just check if everything still looks the same.

Update division in scss files for sass deprecation

---

tools/docker/Dockerfile
tools/docker/bin/install.sh
tools/docker/bin/run.sh

The way `psysh` is being installed causes `wp` to print `#!/usr/bin/env
php` every time it is run.
Also install.sh prints a weird error (and probably fails to detect
whether WP is installed) because of this plus another bug.
Instead, let's install psysh as a library and require that in `wp`
instead. And may as well do so once globally, instead of blindly
appending the line every startup to /var/www/html/wp-cli.yml.
None
No
Before you begin, if you have a docker env that has been around for a while, check how long your `tools/docker/wordpress/wp- cli.yml` is. 😉 Or do a few `jetpack docker stop && jetpack docker up` cycles while testing #21112, then look. 😉
* Build the image with `jetpack docker build-image`
* Recreate your containers, e.g. by doing `jetpack docker down` then `jetpack …

Docker: Fix shebang printing from `wp`

---

projects/plugins/jetpack/changelog/update-publicize-add-message-control-component
projects/plugins/jetpack/extensions/plugins/publicize/components/form-unwrapped/index.js
projects/plugins/jetpack/extensions/plugins/publicize/components/form/index.js
projects/plugins/jetpack/extensions/plugins/publicize/components/message-box-control/index.js
projects/plugins/jetpack/extensions/plugins/publicize/components/settings-button/index.js
projects/plugins/jetpack/extensions/plugins/publicize/editor.scss

This PR replaces a native textarea with a custom core-friendly `<MessageBoxControl /> component.
Fixes #
Before | After
-----|-----
* Publicize: replace a native texarea with the <MessageBoxControl /> component.
No
* Apply these changes
* Confirm the visual changes in the textarea component.
* Confirm the component is working as expected editing its content.
* Publish the post - confirm it's shared on the social media

Publicize: message box control component

---

projects/plugins/jetpack/changelog/update-google-calendar-sandbox-popups
projects/plugins/jetpack/extensions/blocks/google-calendar/google-calendar.php

Fixes #17788
Over on a site I managed, I notice that on the details event modal, that none of the linked items worked. Specifically, more details and copy to my calendar didn't work. Further, in testing, the "+ Google Calendar" at the bottom right of the calendar view didn't work.
The error that I noticed was that an `allow-popups` permission wasn't being set on the iFrame.
This PR adds that.
- Add `allow-popups` so that functionality within the Google Calendar iFrame works. Specifically, the add to calendar button in the bottom right.
N/A
No
To test:
- Connect Jetpack
- Create new post
- Add Google Calendar block
- Insert embed code
- Click the "More details", "Copy to calendar", "+ Google Calendar" items within the calendar
- Ensure that all work

Google Calendar: Allow iFrame popups

---

projects/plugins/jetpack/changelog/instagram-widget-block
projects/plugins/jetpack/extensions/blocks/instagram-gallery/index.js
projects/plugins/jetpack/modules/widgets/class-jetpack-instagram-widget.php

With the new current widget block editor, the Instagram Widget does not configure properly. The current Instagram Gallery block already exists and offers the same functions. Rather than fixing the broken widget this PR removes it from the `core/legacy-widget` and adds the widget to the REST API to allow a block `transform:` to be created.
Fixes Automattic/wp-calypso#55344
* Added filter to hide `wpcom_instagram_widget` from legacy-widget block
* Added widget_option to allow it to be displayed in the REST API. This will allow it to be "transformed" into the `jetpack/instagram-gallery` block
No discussions
No data changes
* Got to Appearance ⇢ Customize ⇢ Widgets
* Add a new block and select Legacy
* In the dropdown check to make sure the `Instagram (Jetpack)` option is gone
* Next search …

Instagram Widget: Remove from legacy-widget block

---

projects/plugins/jetpack/_inc/client/components/settings-card/index.jsx
projects/plugins/jetpack/changelog/fix-typo-in-ad-banner

Fixes #21133
* Fixes typo in Jetpack ad banner when not connected to wpcom.
N/a
No
* Create a new site.
* Connect using a site-only connection (connect Jetpack, then hit back on the browser before approving user connection)
* Go to Jetpack -> Settings -> Traffic and view the banner that should now say "Connect your WordPress.com account to upgrade and generate income with high-quality ads." instead of "adds."

Ads: Fix Typo in Banner

---

projects/plugins/jetpack/changelog/add-smartframe-embed-support
projects/plugins/jetpack/extensions/extended-blocks/core-embed/index.js
projects/plugins/jetpack/extensions/extended-blocks/core-embed/smartframe.js
projects/plugins/jetpack/extensions/shared/icons.js
projects/plugins/jetpack/modules/shortcodes/smartframe.php
projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.smartframe-HttpRequestCache.json
projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.smartframe.php
projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.soundcloud-HttpRequestCache.json

This PR adds support for SmartFrame embedding. It's heavily inspired by (more like shamelessly copies) gettyimages embedding logic. It adds support for:
1. It adds a SmartFrame embedding block, you can test it by adding a "SmartFrame" block and use [this URL](https://mikael-korpela.smartframe.io/p/mantymetsa_1630927773870/7673dc41a775fb845cc26acf24f1fe4f?source=aHR0cHM6Ly9wYW5lbC5zbWFydGZyYW1lLmlvL29uYm9hcmRpbmc=&t=2natn6iyg4) to test.
2. Smartframe [URLs](https://mikael-korpela.smartframe.io/p/mantymetsa_1630927773870/7673dc41a775fb845cc26acf24f1fe4f?source=aHR0cHM6Ly9wYW5lbC5zbWFydGZyYW1lLmlvL29uYm9hcmRpbmc=&t=2natn6iyg4) URLs using the embed block.
3. SmartFrame shortcodes like `[jetpack_smartframe script-id="6ae67829d1264ee0ea6071a788940eae" image-id="mantymetsa_1630927773870" …

Implement SmartFrame embedding

---

projects/plugins/jetpack/changelog/e2e-add-gh-sha-jetpack-version
projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/blocks/pinterest.js
projects/plugins/jetpack/tests/e2e/lib/utils-helper.js

- Include the commit SHA in Jetpack version when testing using local dev sites.
n/a
no
- Check Slack notifications (p1631797526059200-slack-C1Y1F7ZM1) and [test reports](https://automattic.github.io/jetpack-e2e-reports/21114/report/#suites/de427aebb347850ede0b8a09dd39ece0/80baa395fdca625/)

E2E tests: include commit SHA in Jetpack version

---

projects/packages/post-list/changelog/update-posts-list-default-columns
projects/packages/post-list/src/class-post-list.php

This change hides the category and tag columns from the posts list
screens by default. They can be enabled again in screen options, and
won't be changed if the columns to display has already been adjusted.
Related #21132
No
* Enable the post list package
* View the posts list screen and check the category and tag columns are not displayed by default
* If they are still displayed then you may need to reset the screen options with `delete_user_meta( <YOUR USER ID>, 'manageedit-postcolumnshidden' );`

Posts List: Don't display the category and tag columns by default.

---

projects/plugins/jetpack/changelog/fix-extract-usage-D67194
projects/plugins/jetpack/modules/widgets/facebook-likebox.php
projects/plugins/jetpack/modules/widgets/gallery.php
projects/plugins/jetpack/modules/widgets/rsslinks-widget.php

* Refactor extract() usage; no functionality changes.
* Internal: syncs changes from D67194-code
Internal: p3btAN-1xB-p2
No.
* Code has already been tested on WPcom simple.
* Add all 3 widgets to a new site.
* Ensure they can be saved, and are displayed properly.

Widgets: remove use of extract in widgets

---

projects/plugins/jetpack/_inc/lib/class.color.php
projects/plugins/jetpack/changelog/2021-09-23-18-49-09-569454

* Refactor `extract()` usage; no functionality changes.
* Internal: syncs changes from D67197-code
Internal: p3btAN-1xB-p2
No.
* Code has already been tested on WPcom simple.
* This will require using a specific theme, like Ryu, on your site.
* Each image format post's background color should align with the image used in the post.

Color lib: avoid the use of extract()

---

projects/plugins/jetpack/changelog/fusion-sync-jeherve-r225393-wpcom-1632466003
projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php

Differential Revision: D61013-code
This commit syncs r225393-wpcom.
Use `static::class` instead which is available since PHP 5.6.
* No
* No
* Is CI happy?

PHP 7.4 Compatibility: Remove deprecated function

---

projects/plugins/jetpack/_inc/client/recommendations/prompts/product-suggestions/index.jsx
projects/plugins/jetpack/_inc/client/recommendations/prompts/product-suggestions/style.scss
projects/plugins/jetpack/changelog/update-product-suggestions-introductory-price

Marketing has agreed with Design that we should show a "Introductory price" text to communicate that the price we promote is only for the first purchase.
This PR currently assumes that #21189 will be approved so we do not clash with design.
---
* Add Introductory Pricing indicator/text 
---
* p1HpG7-cY7-p2#comment-48894
---
Nope!
---
* Spin up the Jetpack plugin with this branch
* Create a Jetpack Free connection
* Go to `/wp-admin/admin.php?page=jetpack#/recommendations/product-suggestions`
* Verify that the component looks like the screenshot below.
---
**Before #21189**
**After #21189**
_It's the wrong money back guarantee icon being used in this mock but I wanted to illustrate the similarity in text styles._

Jetpack Plugin: Product suggestion introductory price indicator

---

projects/plugins/jetpack/changelog/update-connection_ready_fallback
projects/plugins/jetpack/class.jetpack.php

If an older version of the Connection package without the `Manager::is_connected` method is loaded and Jetpack is loaded in a way that can't be detected ahead of time (for example via CLI), a fatal error can occur during Jetpack activation.
To fix this, add a fallback to the `Manager::is_registered` method which is available in older versions of the Connection package.
* p91TBi-66k-p2#comment-6467
* no
1. Install and activate the WooCommerce and WooCommerce Payments plugins.
2. Install the latest stable version of Jetpack but don't activate it.
3. Activate Jetpack via cli: `wp plugin activate jetpack`.
4. Activation should fail with a fatal error: `PHP Fatal error:  Uncaught Error: Call to undefined method Automattic\Jetpack\Connection\Manager::is_connected() in …

Jetpack: add a fallback for is_connected in the is_connection_ready method

---

.github/files/setup-wordpress-env.sh
projects/plugins/jetpack/changelog/fix-ci-repo-locating
projects/plugins/jetpack/tests/maybe-downgrade-phpunit.sh

The maybe-downgrade-phpunit logic added in #21157 was just deleting the
monorepo repo entry, which was causing it to re-download all the
monorepo deps from packagist. That's wrong, it should continue to use
the monorepo packages that were checked out.
To avoid that, when the setup-wordpress-env script copies the plugin
into place it needs to update that repo entry in composer.json to point
to the correct path (and set options.symlink = false to match the logic
used originally).
p1632786514389700-slack-CBG1CP4EN
no
* Combine this with #21038 and see if the CI jobs stop erroring out.

ci: Fix composer monorepo repo entry in copied plugin

---

projects/packages/sync/changelog/fix-user-meta-checksums
projects/packages/sync/src/replicastore/class-table-checksum-usermeta.php

Resolve PHP Notice :: Indirect modification of overloaded property WP_User::$allowed_mime_types has no effect
* Resolve Indirect modification notice when performing user meta checksum
No
* See D67470

Fix PHP Notice when manipulating allowed_mime_types

---

projects/plugins/jetpack/changelog/update-social-icons-widget-block-compatibility
projects/plugins/jetpack/extensions/editor.js
projects/plugins/jetpack/extensions/extended-blocks/core-social-links/index.js
projects/plugins/jetpack/extensions/extended-blocks/core-social-links/services.js
projects/plugins/jetpack/modules/widgets/social-icons.php

With the new current widget block editor, the Social Icons Widget is redundant. The core block, [Social Links](https://wordpress.com/support/wordpress-editor/blocks/social-links-block/). This PR removes it from the `core/legacy-widget` and adds the widget to the REST API to allow a block `transforms: ` to be created.
Due to the difference in the way Social Links block compared to the Social Icons widget it may be a little complicated to transfer over the existing icons. In the long term we may be able to get a function that is capable of filtering this based on the URL, but in the interest of resolving this issue sooner rather than later it we may want to save that for a later update.
*Legacy Block*
*Transform*
*Finish*
Working on #21069 
Nope
* Before loading this PR, be sure to add the …

Social Icons Widget: Remove from legacy-widget block

---

projects/plugins/jetpack/changelog/fix-jetpack-coverage-slow
projects/plugins/jetpack/phpunit.xml.dist
projects/plugins/jetpack/tests/php.multisite.xml

Something in #21218 seems to have changed the structure of the `vendor/` in
a way that makes PHPUnit take a very long time to generate the code coverage
report. Since there's no point in it including coverage for `vendor/` (as
nothing in there is part of Jetpack itself; even our monorepo modules should
have their own tests covering them), let's exclude it.
None
No
* Is the "Tests / Code coverage" job completing, in the expected ~20 minutes?

Jetpack: Exclude `vendor/` from coverage

---

projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte
projects/plugins/boost/changelog/fix-offline-score-refresh

Fixes #21229
The auto refresh of score during module toggle was triggering a refresh even when Jetpack is offline. This is a fix for the issue. Now, refresh will not happen if jetpack is offline.
No
* Access boost dashboard while [Jetpack is offline](https://jetpack.com/support/development-mode/). 
* Try to reproduce the issue as in: https://d.pr/v/71e6ur. See if requests dispatch if modules are toggled.
* Try to see if refresh works when Jetpack is not offline.

Boost: Fix offline score refresh

---

.github/workflows/e2e-tests.yml

Fix the Gutenberg setup in the e2e test workflow. It was missed by #21115 
p1633004075206100-slack-C1Y1F7ZM1
no
- Tested with run https://github.com/Automattic/jetpack/pull/21248/checks?check_run_id=3755955141

E2E tests: fix gutenberg setup

---

projects/plugins/jetpack/changelog/fix-disable-webpack-concatenateModules-optimization
projects/plugins/jetpack/tools/webpack.config.extensions.js
projects/plugins/jetpack/tools/webpack.config.js
projects/plugins/jetpack/tools/webpack.config.search-configure.js
projects/plugins/jetpack/tools/webpack.config.search.js
projects/plugins/jetpack/tools/webpack.config.widget-visibility.js

In the current setup, we rely on WordPress's translation infrastructure
scanning the webpacked JavaScript files to find calls to the i18n
functions. The concatenateModules optimization can sometimes
discard (or inline?) such calls, breaking things. A change in
calypso-build 9.0.0 makes this far more likely.
Fixes #21204.
Note the situation with respect to translations still isn't perfect.
- The "translator" comments are lost, unless it happens to pick them up
scanning the unwebpacked sources.
- The `wp i18n make-pot` tool ignores all `*.min.js` files, which we
have to use to avoid a broken minifier that wpcom applies to all `.js`
files that aren't `.min.js`. If the WP translation infrastructure uses
that or uses the same logic...
#21204
No
* I guess run wp i18n make-pot on the output and …

jetpack: Disable webpack's concatenateModules optimization

---

projects/packages/tracking/CHANGELOG.md
projects/packages/tracking/changelog/update-tracking_ajax_hook_and_prefix
projects/packages/tracking/src/class-tracking.php
projects/plugins/jetpack/changelog/jetpack-branch-10.2
projects/plugins/jetpack/composer.lock

* Backports packages/tracking v1.13.11 release from the JP 10.2 release branch: https://github.com/Automattic/jetpack/commit/33eeba2b257a4bb40a3462ca01c8a42398577180
N/A
* Proofread changes.

Backport packages/tracking v1.13.11 from 10.2 branch

---

projects/plugins/jetpack/changelog/fix-subscriptions-widget-amp-compat
projects/plugins/jetpack/modules/subscriptions/subscriptions.js
projects/plugins/jetpack/modules/subscriptions/views.php

This is a follow-up on #18015.
I found that #20763 was causing AMP validation errors due to the enqueueing of a custom script on a page. The introduced script scrolls the subscriptions widget into view if a certain DOM element was on the page. Beyond not working in AMP due to the custom script, this is not ideal because adding a new external script for every page load negatively impacts frontend performance. It also doesn't work if JS is turned off.
I believe the the better fix for #18015 is merely to make sure that the ID for the `form` is passed as the `redirect_fragment` input value. Previously it was relying on the widget wrapper element to have an ID, but this appears to be no longer in place as of WordPress 5.8.
* Revert #20763 to instead scroll to subscription form by passing the …

Subscription Block: Pass form ID as `redirect_fragment` instead of enqueueing `jetpack-subscriptions-js`

---

projects/packages/connection/CHANGELOG.md
projects/packages/connection/changelog/update-hook-for-package-tracker
projects/packages/connection/src/class-package-version.php

* Backports packages/connection v1.30.6 from the JP 10.2 release branch: https://github.com/Automattic/jetpack/commit/87e249cf1342754deb4c614a43cbaf3c0cc1ec09
N/A
* Proofread changes.

Backport packages/connection v1.30.6 from 10.2 branch

---

projects/plugins/jetpack/changelog/fix-avoid-errors-related-posts
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php
projects/plugins/jetpack/modules/related-posts/related-posts.js

In our [support documentation for Related Posts](https://jetpack.com/support/related-posts/customize-related-posts/#delete), we recommend a code snippet to remove the Related Posts section from the post content. This snippet completely removes the main Related Posts DIV causing JS to trigger an error.
See 6959-gh-jpop-issues
The snippet is:
```PHP
function jetpackme_remove_rp() {
if ( class_exists( 'Jetpack_RelatedPosts' ) ) {
$jprp = Jetpack_RelatedPosts::init();
$callback = array( $jprp, 'filter_add_target_to_dom' );
remove_filter( 'the_content', $callback, 40 );
}
}
add_action( 'wp', 'jetpackme_remove_rp', 20 );
```
This PR avoids JS to trigger error in the case the Related Posts DIV is not present in the DOM.
* Avoid errors on related posts when the main DIV is not in the DOM …

Avoid errors on related posts when the main DIV is not in the DOM

---

projects/plugins/jetpack/changelog/update-fix_tracking_constructor_call
projects/plugins/jetpack/class.jetpack.php

* The first parameter in the `Tracking` [constructor](https://github.com/Automattic/jetpack/blob/master/projects/packages/tracking/src/class-tracking.php#L43) is the product name. Fix the `Tracker` constructor call by adding the product name, `jetpack`.
* n/a
* no
I'm not aware of any errors caused by this, so I don't think there's anything specific to test.
1. Install and activate this branch of Jetpack. Connect to WPCOM.
2. Confirm that no errors were generated.

Jetpack: Fix a Tracking constructor call in the Jetpack class.

---

projects/plugins/jetpack/changelog/fix-eventbrite-urls
projects/plugins/jetpack/extensions/blocks/eventbrite/edit.js

As awesomely explained [here](https://github.com/Automattic/jetpack/issues/14507#issuecomment-915264550) by @ivan-ottinger, `testEmbedUrl` helper only checks for status 200. Any URL (like Google.com) can return 200, even though it's a bad embed URL.
This PR marks 200 responses without event IDs incorrect. Hence, rendering an error and allowing the user to convert the embed to a link.
No
Fixes https://github.com/Automattic/jetpack/issues/14507
1. Make sure https://github.com/Automattic/jetpack/issues/14507 isn't reproducible.
2. Make sure you can embed Eventbrite URLs eg: https://www.eventbrite.com/e/lady-gaga-swietuje-love-for-sale-tickets-166928917887?aff=ebdssbcitybrowse&keep_tld=1

Consider Eventbrite URLs without event ids incorrect

---

projects/plugins/jetpack/changelog/2021-09-30-21-44-26-570128
projects/plugins/jetpack/modules/sso.php

* This does not change the default behaviour of the SSO feature. It only allows third-parties to customize the form a bit more.
* Internal reference: pd81WV-6q-p2
* No
* On a site that's connected to wpcom and where you've activated the SSO feature, log out.
* The login form should look the same as before.
* Now, in a functionality plugin, add the following:
```php
add_filter(
'jetpack_sso_login_form_explanation_text',
function () {
return 'That is my new explanation text';
}
);
```
* Notice that the explanation text changes.

SSO: add filter to customize explanation text next to SSO button.

---

.github/renovate.json

We need multiple versions to support multiple versions of PHP.
None, but see #21262.
No
* Merge this, then regenerate #21262 and see that it doesn't pin that dep anymore.

renovate: Don't pin johnkary/phpunit-speedtrap

---

projects/packages/post-list/changelog/update-post-list-thumbnail-logic
projects/packages/post-list/src/class-post-list.php

We currently add the post thumbnail column to all post list displays.
This change checks that the post type supports `thumbnail`, before
adding the column.
Fixes #21274
No
1. On your Jetpack development site, register test post type with a code snippet like:
```php
function test_post_types() {
$labels = array(
'name'          => _x( 'Thumbnail items', 'post type general name' ),
'singular_name' => _x( 'Thumbnail item', 'post type singular name' ),
'menu_name'     => 'Thumbnail',
);
$args   = array(
'labels'      => $labels,
'description' => 'A test post type that supports thumbnails',
'public'      => true,
'supports'    => array( 'title', 'editor', 'thumbnail' ),
'has_archive' => true,
);
register_post_type( 'thumbnail_item', $args );
$labels = array(
'name'          => _x( 'No Thumbnail …
```

Post List: Only display the thumbnail for types that support it

---

projects/packages/config/changelog/update-move_idc_init_config
projects/packages/config/src/class-config.php
projects/packages/sync/changelog/update-move_idc_init_config
projects/packages/sync/src/class-main.php
projects/packages/sync/src/class-package-version.php
projects/plugins/jetpack/changelog/update-move_idc_init_config
projects/plugins/jetpack/class.jetpack.php

* Add support for the identity-crisis package to the Config package.
* Initialize the identity-crisis package in the Jetpack class.
* Remove initialization of the identity-crisis package from the sync package.
* p9dueE-3oW-p2
* no
Testing will consist of verifying that an IDC that's detected by a Sync request works as expected.
1. Install this branch of Jetpack. Activate and connect to WPCOM.
2. Activate the Jetpack Debug plugin.
3. Enable the IDC simulator module in the Jetpack Debug menu.
4. Enable the IDC simulation in the UI.
5. Create a draft post,
6. Observe your site in IDC safe mode.
7. Check the site's debug.log file and verify that no errors were generated.

Identity Crisis: move initialization to the Config package

---

projects/packages/connection/changelog/update-check_idc_response
projects/packages/connection/src/class-client.php
projects/packages/connection/src/class-package-version.php
projects/packages/identity-crisis/changelog/update-check_idc_response
projects/packages/identity-crisis/package.json
projects/packages/identity-crisis/src/class-identity-crisis.php
projects/packages/identity-crisis/tests/php/test-identity-crisis.php
projects/packages/sync/changelog/update-check_idc_response
projects/packages/sync/src/class-actions.php
projects/packages/sync/src/class-package-version.php

* Add a new method, `Identity_Crisis::check_response_for_idc`, which will check whether the response contains an IDC error code.
* Use this method in Sync to determine if the Sync request returned an error code.
* n/a
* no
Testing will consist of verifying that an IDC that's detected by a Sync request works as expected.
The 'idc_detected" key in the request body is not yet being sent by WPCOM.
1. Install this branch of Jetpack. Activate and connect to WPCOM.
2. Activate the Jetpack Debug plugin.
3. Enable the IDC simulator module in the Jetpack Debug menu.
4. Enable the IDC simulation in the UI.
5. Create a draft post,
6. Observe your site in IDC safe mode.
7. Check the site's debug.log file and verify that no errors were generated.

Identity Crisis: Move the check for an idc to the identity-crisis package

---

projects/plugins/jetpack/changelog/add-widget-visibility-click-tracking
projects/plugins/jetpack/modules/widget-visibility/editor/index.jsx

Fixes Automattic/wp-calypso#56582
* Adds Tracks events for Add new rule, Remove rule, Set major and minor rules fields
This adds tracking on click events, so maybe?
* Switch to this PR, go to the Customizer on a site that supports block widgets
* In your browser's console, set local storage to track analytics changes: `localStorage.setItem('debug', 'dops:analytics');`; hit Enter and reload your browser
* Add a new block widget; click the three-dots menu to access the widget settings
* Click Advanced and scroll down to the Visibility section
* Add a new rule; check the browser console to confirm the tracks event fired as expected
* Set the rule's primary parameter - it should fire another event
* Set the rules minor parameter - it should also fire an event
* Remove the rule - it should …

Widget Visibility: Add click tracking

---

projects/plugins/jetpack/changelog/add-videopress-warning-media-new
projects/plugins/jetpack/modules/videopress/class.jetpack-videopress.php

Anecdotal: There used to be a warning at the top of `media-new.php` warning users that uploading from this page would bypass VideoPress and upload directly to their server. This message is now gone and has caused confusion for us and others as we test Jetpack + VideoPress.
This PR re-introduces this message, only when VideoPress is enabled.
Fixes #
* Added an admin notice to the top of `media-new.php` warning the user that VideoPress uploading is not supported here, only when VideoPress is enabled
Nope!
* On any Jetpack site, disable VideoPress (Jetpack -> Settings -> Performance)
* Visit Media -> Add New (not Library -> Add New)
* You should not see any admin notices.
* Enable VideoPress, then return to Media -> Add New
* You should now see the admin notice!

Add admin notice to media-new.php regarding videopress uploads not being supported

---

projects/packages/sync/changelog/fix-minimize-queue-overflow
projects/packages/sync/src/class-listener.php

The Sync Queue resides in the wp_options table and as such we minimize the number of operations we perform on it. One of the optimizations is to save the state of the queue (size) into a transient that has an expiration of 5 minutes. During import or bulk operations it is possible for 10,000 -> 50,000+ actions to occur that greatly overflow the queue and leads to delays and issues with ongoing changes.
This update reduces the expiration to 30 seconds which should reduce the amount of overflow that gets saved in the queue. More Data loss events will trigger but sites will recover faster.
* Reduction of transient expiration to reduce queue size.
No
* Regression Testing. Verify that data flows via Sync into the WP.com Cache

Jetpack Sync :: Reduce overflow to Sync Queue

---

projects/packages/post-list/changelog/add-share-post-action
projects/packages/post-list/composer.json
projects/packages/post-list/src/class-post-list.php
projects/packages/post-list/tests/php/test-post-list.php

This adds the share action to the post list for the 'post' and 'page'
post types. It uses the query parameter to ensure the Jetpack sidebar is
open when the editor loads.
Determining exactly when it's appropriate to have the Share action
available is tricky and based on context. For now we are using a filter,
so the exact logic can be applied as the Post List package is configured
for each environment.
Fixes #21299
No
* Require the post list package and configure it in the same way as in #21274
* Add a filter to force the display of the action `add_filter( 'jetpack_post_list_display_share_action', '__return_true' );`
* Check that you can see a 'Share' post action on the Posts and Pages screens, and that it links to the editor with the `jetpackSidebarIsOpen` set to true.

Post List: Add the Share post action to Posts and Pages

---

projects/plugins/jetpack/changelog/fix-sync-test-settings
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-listener.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-settings.php

In #21296 we reduced the default settings for max_queue_size. After merger it was identified that existing tests were failing as the transient would expire and lead to can_add_to_queue returning false unexpectedly.  This resets the settings in tests that were reducing the queue size and lag so that tests can move forward with expected default behaviors.
* Unit Test updates
No
* Verify Unit Tests all complete without issue.

Sync Unit Test updates

---

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-publicize-share-post.php
projects/plugins/jetpack/changelog/update-publicize-share-post-endpoint
projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-publicize-share-post.php

For backwards compatibility, the publicize share endpoint should allow an empty `message` string. An empty `message` string sets the response message to the title of the current post.
**Jetpack**
`[POST]` `/wpcom/v2/posts/{$postId}/publicize`
**WPCom**
`[POST]` `/wpcom/v2/sites/{$siteId}/posts/{$postId}/publicize`
Posts a message immediately to all of the user's external sites connected to the Publicize feature (Twitter, Facebook, Tumblr, LinkedIn). The `message` is set as a required parameter (an empty string is allowed) and is associated with a post using the {$postId} in the route.
* **message** [string] - This is the message to be posted to the external accounts. An empty string defaults the message to the title of the post.
* **skipped_connections** [array] - This is an array of …

Allow an empty message string in the publicize share endpoint.

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/save.native.js

Allows `getSaveContent` in validation to go through entire `TiledGallerySave` function when loading serialized HTML.
Before, since there were no inner blocks loaded when loading serialized HTML, `TiledGallerySave` was always returning `null`. Now, we add a condition that checks if we have images loaded into the block's `attributes.images` array, and if so, still goes through the entire function.
This ensures that both loading serialized HTML and creating new blocks and adding them manually via the editor results in the same code path taken.
N/A
1. Add tiled gallery block.
2. Add two images.
3. Open settings and change columns to 1.
4. Switch to HTML mode.
5. Select all, cut.
6. Switch back to visual mode.
7. Switch back to HTML mode.
8. Paste the cut HTML.
9. Switch back to visual mode …

Tiled Gallery Block: Fixing Problem Displaying Block Error when >1 Row

---

projects/plugins/jetpack/changelog/remove-wpcom-file-location-search-test
projects/plugins/jetpack/tests/php/modules/search/test-class.jetpack-search-helpers.php

* Removes WP.com-gated code (matches D69492-code).
In support of p9dueE-3mU-p2
This line shouldn't be needed in any case since the autoloader on WP.com loads very early as a mu-plugin.
No.
* n/a -- Removing the calls to the old package locations in D69492-code.

Search Module: Remove extra WPcom gated code

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.native.js

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4195
With this PR, the placeholder text is changed from "ADD IMAGE" to "ADD MEDIA". This is to bring consistency with the text that's seen in other, similar blocks, such as the Gallery and Story blocks.
**Gutenberg Mobile PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/4194
* The MediaPlaceholder component's [`instructions` prop is used](https://github.com/Automattic/jetpack/pull/21620/files#diff-33587eede7ad93ef2a32666df26302b46dfd9d688d44ecf330efcb2e67606b27R152) to update the block's default placeholder text. This matches up with [how the placeholder text is set here in the Story block](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/story/edit.native.js#L188). …

[RNMobile] Tiled Gallery Block: Update placeholder text

---

projects/plugins/jetpack/changelog/update-p2-inbox-menu-item
projects/plugins/jetpack/modules/masterbar/admin-menu/class-p2-admin-menu.php

* This hides the Inbox link on P2s. Inbox is not available on P2s.
No.
* Go to any P2 and verify that you don't see the "Inbox" link in the admin menu.

P2: hide inbox admin menu link

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.native.js

This fixes an error caused by `__experimentalUseInnerBlocksProps` now becoming `useInnerBlocksProps`, which occurred in https://github.com/WordPress/gutenberg/pull/26031 (specifically [this line](https://github.com/WordPress/gutenberg/pull/26031/files#diff-8135527e43db4f10ace2a4a2ab9b0e826463e5846e238c715f05de18a48e2842R10)).
* Update usage of `__experimentalUseInnerBlocksProps` to `useInnerBlocksProps`
p9ugOq-1Tb-p2
Not, it does not.
See https://github.com/wordpress-mobile/gutenberg-mobile/pull/4196

Update usage of useInnerBlocksProps API

---

projects/plugins/jetpack/changelog/remove-nav-unification-preferred-view-param
projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
projects/plugins/jetpack/tests/php/modules/masterbar/test-class-base-admin-menu.php

Fixes https://github.com/Automattic/wp-calypso/issues/54204.
In order to change the preferred view of a screen, we rely on the `preferred-view` param that indicates what's the newly preferred view.
However, there are some WP Admin screens like `upload.php` which present issues if there are unexpected params in the URL.
To prevent these issues, this PR ensures that the `preferred-view` param is removed from the URL after the new preference has been updated.
N/A.
No.
- Prepare the testing environment:
- Simple sites: Apply D69520-code to your WP.com sandbox, and sandbox both the API and a Simple site.
- Atomic sites: Install Jetpack Beta and switch to the `remove/nav-unification-preferred-view-param` branch.
- Go to https://wordpress.com and switch to your test site.
- Go to "Media > Add …

Nav Unification: Remove `preferred-view` param after update

---

projects/plugins/jetpack/changelog/update-publicize-adjust-jetpack-paid-plan-behavior
projects/plugins/jetpack/extensions/plugins/publicize/components/panel/index.js
projects/plugins/jetpack/extensions/plugins/publicize/components/share-post/index.js
projects/plugins/jetpack/extensions/plugins/publicize/components/upsell/index.js
projects/plugins/jetpack/extensions/plugins/publicize/editor.scss
projects/plugins/jetpack/extensions/plugins/publicize/hooks/use-publicize-config/index.js

This PR improves the way that the implementation shows information depending on the RePublicize feature availability.
It takes into consideration mainly two data:
* availability: when the feature is available or not according to the site plan/product feature.
* upgradability: whether the feature can be upgradable via an upsell, or not.
Sometimes we'd like to show an upsell notice to provide to the user a way to get the proper plan/feature. Sometimes we just want to show additional information about the limitation of the site.
Fixes https://github.com/Automattic/jetpack/issues/21528
* Publicize: Handling feature availability information and upgrading
No
When the post hasn't been published, you shouldn't see any kind of information about availability, upgrades, etc
Once the post has been …

Publicize: Handling feature availability information and upgrading

---

pnpm-lock.yaml
tools/js-tools/package.json

Eslint "sharable configs" are supposed to peer-depend on any plugins
they need. But people usually forget this because npm hoisting makes it
usually work anyway.
In this case, eslint-config-wpcalypso was missing a peer dep on
eslint-plugin-react-hooks.
This happened to work before because eslint-changed was shelling out to
eslint, which runs from `node_modules/.pnpm/eslint@7.32.0/node_modules/eslint`,
which was picking up the dep from `node_modules/.pnpm/node_modules` that
even pnpm puts in place to handle crap like this.
When #21606 switched eslint-changed to use eslint's API instead of
shelling out, it doesn't run from within `node_modules/.pnpm/` anymore
(because eslint-changed is in the monorepo), so
`node_modules/.pnpm/node_modules` is no longer in node's path, so it no
longer would …

js-tools: Add missing eslint plugin dep

---

tools/replace-next-version-tag.sh

Some people like to align things.
https://github.com/Automattic/jetpack/pull/21520#discussion_r742912194
No
* Try adding `@since   $$next-version$$` or `@deprecated   since   $$next-version$$` somewhere. Then run `tools/replace-next-version-tag.sh` over it.

tools: Allow extra spaces in next-version tags

---

projects/plugins/boost/app/assets/src/js/pages/settings/sections/Modules.svelte
projects/plugins/boost/changelog/fix-boost-javascript-wording

While reviewing Boost in order to identify useful E2E tests, I have just noticed we are using the wrong reference to the JavaScript word. This PR fixes it.
* Replace javascript with JavaScript
N/A
N/A
* Make sure the reference to JavaScript is correct.

Boost: Fix the official name to the JavaScript word reference

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/index.js

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4158
* The `fill` parameter is [removed from the icon's `Path` element](https://github.com/Automattic/jetpack/pull/21618/files#diff-025ac7803bd106aa93c59895bc274e4a297c5f27934dc461334ed2692cb045f9L202). The fact that this parameter was setting the icon's fill to `currentColor` was causing it to appear as the wrong colour in the apps. By removing this parameter, the icon now reverts back to the default colour that all other blocks use for their icons. 
**Mobile Gutenberg PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/4193
Main project thread for the Tiled Gallery block on mobile: p9ugOq-1Tb-p2
To test, it should be verified that:
1. The icon colour now matches up with other icons within the …

[RNMobile] Tiled Gallery Block: Use default colour for block icon

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/gallery-image/save.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/index.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/square.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/utils/index.js

Re-matching attributes that are serialized between mobile and web Jetpack Tiled Gallery implementations so that we can load serialized HTML from the web and vice versa.
**NOTE** that the URL from the web seems to be broken, but I'm not sure if that's because we're using the demo app to test or not. Will have to check this in detail after we get basic functionality in place.
<details>
<summary>
**Initial HTML used:**</summary>
```
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-square"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row columns-1"><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="49" data-id="60" data-link="https://sandbox1359387942.wpcomstaging.com/screen-shot-2021-03-08-at-2-51-29-pm/" …
```

Tiled Gallery Block - Matching `save` serialized HTML with web

---

projects/packages/sync/changelog/fix-full-sync-user_level
projects/packages/sync/src/modules/class-users.php
projects/plugins/jetpack/changelog/fix-full-sync-user_level
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-full-immediately.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-full.php

Reduce included users in Full Syncs to contributor and above users. This is performed by an explicit check of the {$wpdb->prefix}user_level meta which correlates to a non 0 value.
Fixes https://wp.me/p9dueE-3JV
* Limit the scope of User Full Syncs to contributor and above users.
NO
Create several users on your site, subscribers, contributors, admins, etc
Pre applying patch 
* wp shell
* $um = Automattic\Jetpack\Sync\Modules::get_module( 'full-sync' );  // get full sync module.
* $um->start( [ 'users'=>1 ] ); // initiate a full sync of users.
* $um->get_status(); // returns current status
* // Verify that the "total" for users matches # of users on the site regardless of capabilities.
Post applying patch
* wp shell
* $um = Automattic\Jetpack\Sync\Modules::get_module( 'full-sync' );  // get …

Full Sync :: limit to contributors and above

---

projects/plugins/boost/app/assets/src/css/components/score.scss
projects/plugins/boost/changelog/fix-boost-progress-bar-round-corners

Fixes 1164141197617539-as-1201305007019341
This PR fixes the styles of the progress bar in the Boost plugin, so that its corner are round on small screens as well.
No.
- Download this PR and build the Boost plugin
- Launch your local testing site and makes sure it has the local version of the Boost plugin installed
- Visit the `Jetpack > Boost` section in WPadmin
- Check that on small screens (width < 768px), progress bars have round corners on both sides
- Make sure that for wider screens, the progress bars still look like the capture below
_Small screens: before_
_Small screens: after_
_Wide screens_

Boost: make progress bar corners round on small screens

---

projects/plugins/jetpack/changelog/fix-pexels-search
projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js

There are currently two issues that occur when we search in the Pexels image library:
1. If we hit `Enter` (submit the search form) too quickly after writing our search phrase, we get stuck at the previous search results ([reported in the Calypso repository](https://github.com/Automattic/wp-calypso/issues/57079)).
2. Every time we change the content of the search field (e.g. type one extra letter), a new random search results are addd at the end of the existing search results.
This PR fixes both issues by making sure the `useEffect()` that triggers `getNextPage()` callback responsible for querying example search results is run only when the `PexelsMedia` component mounts initially (and not on every change of the search field - as it was originally).
**Before:** …

Pexels Integration: Make the initial image search for example query run only once

---

projects/plugins/jetpack/changelog/fix-quick-switcher-mapping
projects/plugins/jetpack/modules/masterbar/admin-menu/menu-mappings.php

Fixes https://github.com/Automattic/wp-calypso/issues/54920
* Display the Nav-Unification Quick switcher on edit.php?post_type=post page.
* Use Jetpack Beta and switch to this branch
* Apply D69799-code on your sandbox
* Go to WP-Admin/edit.php (for Posts)
* Click on a Post (doesn't matter which one)
* Click on the WordPress menu logo (Block editor sidebar) and click on "All Posts" link.
* You'll be redirected to edit.php?post_type=post
* Click on "Screen options" and notice that the button for switching to Calypso interface is not missing.

Display Nav Unification Quick switcher on edit.php?post_type=post

---

projects/js-packages/components/components/decorative-card/index.jsx
projects/js-packages/components/components/decorative-card/stories/index.jsx

Quick PR to add the new DecorativeCard component to Storybook.
Also fixed the `propTypes` declaration (first `p` should be lowercase)
Suggested using `oneOf` as a type for the format. Should we do the same for `icon` and consider `unlink` the only possible value for now? (apart from empty)
* Go to `js-packages/storybook` folder
* `pnpm install`
* `pnpm run storybook:dev`
* in the browser, look at Playgoround > Decorative Card. (Default and Unlink)

Fix propTypes and add story

---

projects/packages/status/changelog/2021-11-09-16-21-32-086404
projects/packages/status/src/class-status.php

The `wp_get_environment_type` function was added in WordPress 5.5. Consumer plugins may not be enforcing a minimum WP version of 5.5. Using this package on sites with WP <5.5 will cause a fatal error if `wp_get_environnment_type` is called..
We intend to define minimum WP requirements for the packages in the future.
In the meantime, check that the `wp_get_environment_type` function exists before calling it.
* n/a
* no
1. Create a test site with WP 5.4.
2. Install and attempt to activate the master branch of Jetpack. Notice that Jetpack can't be activated because of the minimum WP version.
3. Manually change the value of the `JETPACK__MINIMUM_WP_VERSION` [constant](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/jetpack.php#L33) to 5.4.
4. The site should crash …

Status: add a function_exists check before calling wp_get_environment_type

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout-picker.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/settings.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/styles.native.scss

Addresses https://github.com/wordpress-mobile/gutenberg-mobile/issues/4192
Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/4221
- Allow users to change the Tiled Gallery's layout
- Layout selection is implemented using Gutenberg's `BlockStyles` component
- Layout selection is displayed in a bottom sheet sub-sheet
Because we want to unblock work on other layouts, this PR only addresses the above issue's most critical points (i.e. layout selection UI, hiding Corner Radius setting for Circle layout, etc). What was explicitly left out is:
- Visual previews of each layout: For the time being, blank previews are shown above each layout's name
- A grid layout for visual previews: Instead, we're showing all layouts in a single, scrollable row
- An icon next to the current …

[RNMobile] Tiled Gallery layout selection basic implementation

---

projects/plugins/backup/changelog/fix-remove-backup-animation-mobile
projects/plugins/backup/src/js/components/Backups.js
projects/plugins/backup/src/js/components/backups-style.scss

Fixes 1164141197617539-as-1201305007019351
In the Backup plugin, the backup-in-progress animation hides the progress bar and the text around. This PR fixes this by hiding the animation on viewports narrower than 960px.
No
- Download this PR and build the Backup plugin
- Launch your local testing site and makes sure it has the local version of the Backup plugin installed
- Get a subscription to Backup
- Visit the `Jetpack > Backup` section in WPadmin
- You should see the backup-in-progress animation once the first backup starts (*)
- Check that the animation is hidden for viewports narrower than 960px
_* If your site already has previous backups, you may not be able to visualize this screen. In that instance, force the call of `renderInProgressBackup` at the bottom of `Backup.js`, and …

Backup: removed backup-in-progress animation on small viewports

---

projects/packages/device-detection/changelog/fix-device-detection-http-user-agent
projects/packages/device-detection/src/class-user-agent-info.php

Fixes `Undefined index: HTTP_USER_AGENT in /srv/www/html/wp-content/plugins/jetpack-dev/vendor/automattic/jetpack-device-detection/src/class-user-agent-info.php on line 1265`
Discovered this while looking through error logs.
* Verify array key exists in a couple instances where we weren't checking before.
None.
No.
* None from me yet.
*

Device Detection: Verify HTTP_USER_AGENT exists

---

tools/deploy-to-svn.sh

﻿
Follow-up to #21574.
When running `svn cp`, we have to provide a commit message. Let's pass it as part of the command so this is done automatically.
* N/A
* No
* I don't know that it can easily be tested until the next Alpha?

SVN release: automate the tag copy commit message

---

.github/workflows/gardening.yml

﻿
Since #21697, we remove PHP tools such as Composer from tools that do not require PHP.
The Gardening action relies on Composer to build the action, so we'll need composer and thus PHP here.
* N/A
* No
* Does the Gardening action test work once we merge this PR? (I don't think we can test with this PR since the changes need to be in the `master` branch to be available to the action).

Gardening: ensure it can use Composer

---

projects/plugins/boost/app/modules/critical-css/class-critical-css.php
projects/plugins/boost/changelog/fix-boost-critical-css-without-javascript

Fixes #21545
* Append to the HTML stylesheet tag the same untouched HTML stylesheet tag within the noscript tag to support the rendering of the stylesheet when JavaScript is disabled.
It is a pretty straightforward solution but there might be some side effects I have not considered except for some few bytes it adds to the document.
N/A
N/A
* Install the "Newsup" theme and its demo content
* Generate Critical CSS
* Open an incognito browser, open the dev tools and disable JavaScript
* Go on a post with a comment box
* With this patch notice that the style is still rendered, try without it and see that the style is not rendered.
See video:
https://user-images.githubusercontent.com/927932/141303115-2696b727-091a-4b19-8703-04d697761adb.mp4

Boost: Implement support for loading stylesheets when JavaScript is disabled in the context Critical CSS being enabled

---

projects/plugins/jetpack/changelog/remove-webpack-output-pathinfo-in-prod-builds
projects/plugins/jetpack/tools/webpack.config.extensions.js
projects/plugins/jetpack/tools/webpack.config.js

There's no point to it, the generated comments just bloat the
CSS and license.txt files.
Note Webpack already defaults it to true for `mode: development` builds,
where it makes a little more sense for the comments to be present.
It's not clear why it was ever being set in the first place,
neither #12463 nor #13070 seem to have any discussion about the
additions.
p9dueE-3MG-p2#comment-6619
No
* Check the built license.txt and css files. There should be fewer comments holding just paths.

jetpack: Don't set Webpack's `output.pathinfo` in production builds

---

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php
projects/plugins/jetpack/changelog/add-external-media-copy-meta
projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-external-media.php

* Allow /sites/${site}/external-media/copy/pexels to insert post meta data 
No
* N/A
* `jetpack docker phpunit -- --filter=Endpoint_External_Media`
* Apply D69692-code to sandbox
* Visit internal vertical-images tool (See: D69577-code for full instructions)
* Choose a vertical
* Enter a search term (example: "building") and press enter or click on magnifying glass
* See photos
* Click on at least on image to select it
* Click on the "Add 1 photos to VERTICAL" button
* see no feedback but use devtools to see that the POST happened :)
* sandbox PduBjF-5-p2 (See: D69577-code for full instructions)
* Visit https://<vertical site>/wp-admin/upload.php (See: D69577-code for full instructions)
* click on the photo you uploaded
* click on edit more details
* On sandbox, edit wp-admin/post.php and …

Allow /sites/${site}/external-media/copy/pexels to insert post meta data 

---

projects/js-packages/eslint-config-target-es/.gitattributes
projects/js-packages/eslint-config-target-es/changelog/add-mirror-for-eslint-config-target-es
projects/js-packages/eslint-config-target-es/composer.json
projects/js-packages/eslint-config-target-es/package.json

Now that this has some testing in the monorepo, let's get ready to
release it.
None
No
* Check that things seem good, here and in https://github.com/Automattic/eslint-config-target-es.
* Check that the build artifact looks sensible.
* After merging, see that it mirrored.

eslint-config-target-es: Configure mirror repo

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/index.js

Partial fix for https://github.com/wordpress-mobile/gutenberg-mobile/issues/4190 (note, this PR won't hide the image's caption, only the settings toggle)
* `__experimentalHideChildBlockControls` is set to `true`, so that a settings toggle/control isn't available for each individual image within the main Tiled Gallery block. 
* The code builds on the work outlined in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4225.
p9ugOq-1Tb-p2 
_Prerequisite: The following testing instructions rely on the code in https://github.com/WordPress/gutenberg/pull/36371, which hasn't been merged into Gutenberg's `trunk` at the time of writing. Please make sure to check out the branch that the code is on if it's not merged into `trunk`._
* With these branches checked out and the …

[RNMobile] [WIP] Tiled Gallery: Hide inner block settings

---

projects/plugins/jetpack/changelog/update-jetpack-weekly-104a6
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start 10.4-a.6 release cycle
* N/A
* No
* Is CI happy?

Janitorial: update Jetpack version for 10.4-a.6 cycle

---

projects/plugins/jetpack/changelog/wpcom-no-longer-forces-http
projects/plugins/jetpack/class.json-api.php

Reverts Automattic/jetpack#21747 (which contained only wpcom changes)
> Barry pointed out that not all wpcom sites have valid certificates. I was able to find at least one where the /sites/ API with this patch returned https:// but it was invalid.
no.
* https://developer.wordpress.com/docs/api/console/
* wp.com api | v1.2 | `/sites/144771104`
* URL should begin with http, not https
The patch that is reverted makes no changes on jetpack sites, only wpcom; and the revert is already on wpcom, so there's really nothing to test.

Revert "WPCOM no longer forces home_urls to be http"

---

.github/files/build-all-projects.sh
projects/packages/changelogger/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/packages/changelogger/composer.json
projects/packages/changelogger/src/Application.php
projects/plugins/backup/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/backup/composer.lock
projects/plugins/beta/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/beta/composer.lock
projects/plugins/boost/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/boost/composer.lock
projects/plugins/debug-helper/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/debug-helper/composer.lock
projects/plugins/jetpack/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/jetpack/composer.lock
projects/plugins/search/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/search/composer.lock
projects/plugins/vaultpress/changelog/remove-special-cases-for-changelogger-in-changelogger
projects/plugins/vaultpress/composer.lock
tools/changelogger-release.sh
tools/changelogger-validate-all.sh
tools/cli/commands/changelog.js

We have special cases in a number of our tools to account for the fact
that Composer doesn't create a `vendor/bin/changelogger` symlink in
packages/changelogger's vendor dir.
Instead, let's use post-install and post-upgrade scripts to ensure that
the link exists, so we don't have to special case it everywhere else.
None
No
* Do `jetpack install packages/changelogger`. See that `projects/packages/changelogger/vendor/bin/changelogger` exists and points to a correct location.

Remove special cases for calling changelogger on packages/changelogger

---

projects/packages/identity-crisis/changelog/update-add_idc_unit_tests
projects/packages/identity-crisis/package.json
projects/packages/identity-crisis/src/class-identity-crisis.php
projects/packages/identity-crisis/tests/php/test-identity-crisis.php

Fixes #21656 
* In `Identity_Crisis::get_mismatched_urls`, check that the `jetpack_sync_error_idc` option value has all of the required keys, and return false if it doesn't.
* Add unit tests for the `Identity_Crisis::has_identity_crisis` and `Identity_Crisis::get_mismatched_urls` methods.
* n/a
* no
If testing with JN, you'll need [this plugin](https://gist.github.com/sergeymitr/bc005e1b893e778c03e4f43debb91c30) activated.
1. Install, activate, and connect this branch of Jetpack.
2. Install the Jetpack Debug Helper plugin.
3. In the Jetpack Debug dashboard, enable the Identity Crisis Simulation Utility module.
4. In the IDC Simulator, enable the IDC Simulation. The siteurl and home values will now be mocked as **example.org**.
5. Cause an IDC by editing a post.
6. Navigate to the Tools -> …

Identity Crisis: add unit tests for has_identity_crisis and get_mismatched_urls

---

pnpm-lock.yaml
projects/js-packages/licensing/changelog/fix-licensing-js-test-runner
projects/js-packages/licensing/package.json

That's why D70048-code is breaking, the munging in the build there
doesn't expect to find it as a non-dev dep.
None. Sigh.
No
* This should do nothing here. Merging the change here with the change in D70048-code should allow that to pass tests.

licensing: jetpack-js-test-runner is a dev dependency

---

projects/js-packages/components/changelog/fix-action-button-min-width
projects/js-packages/components/components/action-button/style.scss
projects/js-packages/connection/changelog/fix-action-button-min-width
projects/js-packages/connection/components/connect-screen/basic/style.scss

Fixes the button width to have a minimum width after a regression introduced by https://github.com/Automattic/jetpack/pull/21711
* Fixes the Action button so it supports longer labels and reverts the fix to the Connect Screen that was breaking the button width
NA
No
* Check the action button on Storybook and test it with a very long label
* See instructions in https://github.com/Automattic/jetpack/pull/21711

Fix Action button width

---

projects/packages/post-list/changelog/fix-post-list-quick-edit
projects/packages/post-list/src/class-post-list.php
projects/packages/post-list/tests/php/test-post-list.php

The customizations that to the post list screen were being made on hooks
that only ran as the page/screen loaded. If a quick edit was made, the
table row returned in the result didn't include the necessary
customizations and would break the table.
There appears to be a WordPress bug where the post actions are not
hidden after a quick edit too. I also noticed the Copy post action was
missing, which might be another issue in Jetpack.
Fixes #21671
No
* Enable the post list package
* Perform a quick edit on a post or page
* Without this PR, the row will be missing the thumbnail and the table will look broken
* With this PR, it should render correctly

Post List: Fix the response after saving a Quick Edit.

---

projects/plugins/jetpack/_inc/lib/class.jetpack-search-performance-logger.php
projects/plugins/jetpack/changelog/remove-smiley-alt-ascii-art

Supports #2856
* For the Search Performance stats pixel, use an empty alt tag.
Alt tags are required, but empty ones are allowed (and suggested) for things like decoration or stats pixels.
n/a
No.
* I'm not immediately sure how to trigger Search Perfomance Logging, but the change is pretty direct.

Stats: remove ASCII art from alt text

---

docs/git-workflow.md

This seems like a good place to document tips and workarounds for
handling issues that commonly come up when doing `git merge` or the
like.
None direct. Probably this sort of thing has been been passed around by word of mouth.
No
* Check the added docs for correctness, grammar, and spelling.

docs: Add some tips about handling merge issues

---

projects/plugins/jetpack/changelog/issue-populate-comment-author-id
projects/plugins/jetpack/class.json-api-endpoints.php

This is a change to the wpcom a REST API in a file that is shipped with Jetpack.  My understanding is currently the preferred workflow is to start with Jetpack and let the change be ported back to wpcom. 
For additional context see the slack conversation and thread at slack-reader-p1637182998015000 cc @khaykov , @westi 
This PR modifies the response returned for a comment author's ID. 
Currently if a comment author's `comment_author_email` field is set the author's ID is always zero.  With this change, the correct user ID for the author will be returned. 
This change will aid in identifying comments belonging to a post's author. 
(To test this, I applied the change directly to the wpcom endpoints and tested via a wpcom sandbox. For self-hosted/jetpack sites I appended the "&force=wpcom" …

REST API: Return user ID for comment author if present.

---

projects/packages/post-list/CHANGELOG.md
projects/packages/post-list/changelog/add-assets-wp_register_script-wrapper
projects/packages/post-list/changelog/fix-post-list-quick-edit
projects/packages/post-list/changelog/fix-post-list-stretched-thumbnail
projects/packages/post-list/src/class-post-list.php

This PR releases the recent updates to the post list package, primarily fixes for issues reported on the RePublicize call for testing (p7DVsv-cZY-p2).
No
This shouldn't need testing as the changes have been tested as part of their associated PRs, but ensuring that nothing is broken with the package would be a good idea!

Post List: Release version 0.2.4

---

projects/plugins/jetpack/changelog/rm-verification-tools-wp-admin
projects/plugins/jetpack/modules/verification-tools/blog-verification-tools.php

Fixes #21823
* The tools have lived in the Jetpack dashboard for more than 3 years, since #10039. Let's retire that redirection now.
* N/A
* No
* Go to Jetpack > Settings > Traffic, and enable Site Verification tools.
* Go to the Tools menu.
* You should not see any settings anymore.

Verification tools: remove old Tools interface

---

projects/packages/assets/changelog/fix-doing-it-wrong-wrong
projects/packages/assets/src/class-assets.php
projects/packages/assets/tests/php/test-assets.php

`$version` parameter can't be omitted.
https://github.com/Automattic/jetpack/pull/21831#discussion_r754626441
Nope.
* Do it wrong, then see if this does `_doing_it_wrong()` right.

assets: Stop doing `_doing_it_wrong` wrong

---

projects/plugins/jetpack/changelog/update-enable-republicize-by-default
projects/plugins/jetpack/class.jetpack-gutenberg.php

* Enable the RePublicize block editor UI by default
RePublicize is an extension of Publicize that lets users on paid plans to re-share their posts whenever they want.
Before this change, Jetpack users could only do so through Calypso.
With this change, the RePublicize UI is added to the block editor's Jetpack Sidebar as well.
Note: we chose to keep the filter defaulting to `true` instead of removing it in order to be able to selectively turn RePublicize off at will on different environments.
More info in the CfT: p7DVsv-cZY-p2
No.
RePublicize is simply an extension of Publicize, and it reuses the same data.
* Start with a free Jetpack site.
* Go to Settings -> Sharing, and turn on "Automatically share your posts to social networks" in the "Publicize connections" section.
* Click on …

RePublicize: Enable the block editor UI by default

---

projects/packages/jitm/changelog/add-jitm-sideload-boost-plugin
projects/packages/jitm/src/class-post-connection-jitm.php
projects/plugins/jetpack/3rd-party/3rd-party.php
projects/plugins/jetpack/3rd-party/jetpack-boost.php
projects/plugins/jetpack/changelog/add-jitm-sideload-boost-plugin

Adds the logic necessary to enable installing and activating the Jetpack Boost plugin via JITM. It mimics the behavior and code pattern of the CreativeMail JITM sideloading and is pretty much a copy paste of the JITM for backups merged in #21719 
This is in preparation of enabling the JITM in wpcom later when we're ready, so that we don't need to wait for another release. The wpcom diff linked below is not up for review, but is useful for testing the PR. 
[p1HpG7-dzq-p2](pbNhbs-1yJ-p2)
No
Set up: 
- Connect to wpcom sandbox
- Apply D70536-code to sandbox
- Make sure Jetpack Boost is not installed on the Jetpack site
- You'll see the JITM on the main wp-admin dashboard as well as the Jetpack dashboard. 
Successful install: 
- Clicking it should install/activate and navigate you to the …

JITM: Sideload Jetpack Boost functionality 

---

pnpm-lock.yaml
projects/js-packages/licensing/changelog/add-license-activate-busy-state
projects/js-packages/licensing/components/activation-screen-controls/index.jsx
projects/js-packages/licensing/components/activation-screen-controls/style.scss
projects/js-packages/licensing/components/activation-screen-controls/test/component.jsx
projects/js-packages/licensing/components/activation-screen/index.jsx
projects/js-packages/licensing/package.json
projects/plugins/jetpack/changelog/add-license-activate-busy-state
projects/plugins/jetpack/package.json

* Add a Busy State and "Working..." text to button while activation request is in-progress
p1HpG7-cSg-p2
* Go to `/wp-admin/admin.php?page=jetpack#/license/activation`
* Submit either any text or a valid license
* Verify the button switches to a busy state matching the screenshot above
* Verify it returns to the previous state when the activation fails.

Add Busy State to License Activation Flow Button

---

projects/js-packages/connection/changelog/update-connect-screen-component
projects/js-packages/connection/components/connect-screen/layout/index.jsx
projects/js-packages/connection/components/connect-screen/layout/style.scss

ConnectScreen RNA component: Fixes the custom grid and background color.
* ConnectScreenLayout: Use flexbox approach instead of floating elements to ensure same height
* ConnectScreenLayout: Add missing base-styles dependency to fix the missing background color
No
* Setup a new JN site with Jetpack-the-plugin and Backup plugin active.
* Go to Jetpack and make sure the left side of the `ConnectScreen` is white and shares the same height with right side.
* Go to Backup and make sure nothing has changed in the `ConnectScreen`

ConnectScreen RNA component: Fix custom grid and background

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/mosaic/index.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/mosaic/resize.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/save.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/styles.native.scss

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4228
Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/4249
* A first iteration of the the Mosaic layout for the WordPress mobile port of the Tiled Gallery block.
p9ugOq-1Tb-p2
It's possible to test that Mosaic layout by inspecting the block's HTML using the editor's HTML mode. However, to further verify that the layout's CSS is working, it's best to test in the main WordPress mobile apps.
1. Checkout the Gutenberg Mobile branch: (tip: if using `gh`, run `gh pr checkout --recurse-submodules add/tiled-gallery-block-mosaic-layout`)
2. Run the packager: `npm run start:reset`
3. Run the WPiOS app's `develop` branch
4. Open the editor and expect it to load from the running packager
5. Add a …

[RNMobile] Tiled Gallery Mosaic layout basic implementation

---

projects/plugins/jetpack/_inc/client/components/jetpack-notices/index.jsx
projects/plugins/jetpack/_inc/client/components/jetpack-notices/style.scss
projects/plugins/jetpack/_inc/client/components/jetpack-notices/user-license-activation.jsx
projects/plugins/jetpack/changelog/update-jetpack-license-activation-banner-copy

Asana task: 1201096622142517-as-1201427659384414
* Update the copy of the license activation banner to make it clear that the user has an available license that can be activated on the site.
* Add to the same banner a link to the user's purchases on WordPress.com.
* This improvement came from feedback left on the project's call for testing p2 post: p1HpG7-dIr-p2#comment-50719.
* It tracks the clicking on the new link that leads to the user's purchases section on WordPress.com.
* Spin up a site using this Jetpack branch.
* Connect Jetpack to your A8C WordPress.com account.
* Enable the A8c Proxy.
* Go to https://cloud.jetpack.com/pricing.
* Select a paid Jetpack product other than Jetpack Search.
* Complete checkout.
* On the "Thank you for purchasing [product-name]!" page, just stop …

Improve the copy of the license activation banner

---

projects/plugins/boost/app/modules/critical-css/class-critical-css.php
projects/plugins/boost/changelog/fix-generate-flag-check

The flag `generating_critical_css` was being set _after_ the decision to render Critical CSS, causing Critical CSS (and all of its page changes) to be rendered while generating Critical CSS.
This PR fixes the issue by replacing the `generating_critical_css` flag with a method called `is_generating_critical_css` which checks the generate nonce the first time it's called, and caches the result for the remainder of the pageload in a static var.
That way, initialization order doesn't matter for this flag.
* Replace `generating_critical_css` flag with `is_generating_critical_css` method, which calculates the value as needed.
n/a
no
* Generate Critical CSS with the Network tab open in your browser tools
* Grab a URL from the Critical CSS generation process in the Network tab with …

Don't render Critical CSS while generating CritCSS.

---

projects/plugins/jetpack/changelog/add-site-intent
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php
projects/plugins/jetpack/sal/class.json-api-site-base.php

Summary:
As we need to show different support articles according to the site intent, add `site_intent` into options list so that we can query from the `/me/sites` endpoint
Related to https://github.com/Automattic/wp-calypso/pull/58486
Test Plan:
1. Go to API Console
2. Select WP.COM API > v1.2
3. Use `/me/sites?fields=options&options=site_intent`
4. Check the response of sites contains `site_intent`
Also, you can follow the testing instructions from https://github.com/Automattic/wp-calypso/pull/58486
Reviewers: #ganon_team, philipmjackson
Reviewed By: #ganon_team, philipmjackson
Subscribers: philipmjackson
Differential Revision: D70637-code
This commit syncs r235663-wpcom.
Fixes #
*
* Go to '..'
*

Support site_intent for `/me/sites` endpoint

---

projects/js-packages/licensing/changelog/fix-user-licensing-error-message-icon
projects/js-packages/licensing/components/activation-screen-controls/style.scss

Asana card: 1201096622142517-as-1201427659384436
* Fix the error icon vertical position and min width.
* Project Thread: p1HpG7-cSg-p2
* No. It does not.
* Spin up a site using this Jetpack branch.
* Connect Jetpack to your A8C WordPress.com account.
* Enable the A8c Proxy.
* Go to https://cloud.jetpack.com/pricing.
* Select a paid Jetpack product other than Jetpack Search.
* Complete checkout.
* On the "Thank you for purchasing [product-name]!" page, just stop there.. (Don't enter a site URL in the input box).
* On your site, visit `/wp-admin/admin.php?page=jetpack#/license/activation`.
* Enter the license key associated with your purchase (you can get it from SA).
* Once the product is activated, refresh the page.
* Try to enter the same license key again.
* Observe the error message …

Licensing JS Package – fix icon positioning and width

---

projects/plugins/jetpack/_inc/lib/plugins.php
projects/plugins/jetpack/changelog/update-install-plugins-mc-stats

Follow-up of the feedback in https://github.com/Automattic/jetpack/pull/21719#discussion_r755386165
This bumps an MC stat when Jetpack tries to install a plugin. This install is used in the JITM sideloading functionality. I've only added stats to install as it's most likely to fail (vs activating). We're interested to see how many sites have trouble "sideloading" plugins through this API, particularly as #21719 and #21719 are merged and will likely get activated from wpcom soon after this release. 
Stat group: `jetpack-install-plugin`
Stat name: `fail-$slug` || `success-$slug`
Related discussions
p1HpG7-dzq-p2
https://github.com/Automattic/jetpack/pull/21719#discussion_r755386165
p1HpG7-dHF-p2
Yes, but it's non-identifying data. Just an incremental stat count. 
You should be able to test …

Plugin Install: Bump MC stat on success or fail.

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/edit.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/save.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/settings.native.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/styles.native.scss

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4281
Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4304
As we're not implementing "link to" functionality in this phase of the native Tiled Gallery block (see https://github.com/wordpress-mobile/gutenberg-mobile/issues/4156), this PR removes the setting from the block's bottom sheet as well as all references to it in the code.
* [The `LinkSettingsNavigation` component is removed](https://github.com/Automattic/jetpack/blob/653cbbe14644daecf9927faee158f5683dbacec8/projects/plugins/jetpack/extensions/blocks/tiled-gallery/settings.native.js#L92-L101) from the Tiled Gallery's settings. 
* To support the removal of the `LinkSettingsNavigation` component, all references to `linkTo` have also been …

[RNMobile] Tiled Gallery: Remove "link to" settings and references

---

.github/PULL_REQUEST_TEMPLATE.md

Looking to how to better communicate that the milestone field is not exclusively for the Release folks to use. Open to suggestions on language.
* Add a new comment to the PR template.
Just some DM feedback about confusion about it.
No.
* n/a.

PR Template: Indicate use of milestone

---

projects/plugins/beta/changelog/update-beta-soft-fail-on-no-internet
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php
projects/plugins/beta/src/class-clicommand.php
projects/plugins/beta/src/class-hooks.php
projects/plugins/beta/src/class-plugin.php

There are some other instances where uncaught exceptions might exist, but focusing on what caught us today.
* Catch exception thrown when there is no network connection for rendering the admin bar or the CLI list command.
p1638297422231800-slack-C01U2KGS2PQ
No.
* On a test site, install the "Airplane Mode" plugin by Norcross in the w.org repo (makes it easy to test no connection to our servers).
* Install a transient plugin, such as the Transient Manager by Pippin.
* Install the Beta plugin.
* Activate Airplane Mode so the site won't connect to our servers.
* Suspend or clear all transients, at least our `jetpack_beta_plugins_json` transient.
* Reload /wp-admin
Before this PR, it would fatal with an uncaught exception. After, wp-admin renders. The Jetpack Beta menu in the admin bar …

Beta: Handle exception when no Internet connection

---

projects/plugins/jetpack/_inc/client/main.jsx
projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php
projects/plugins/jetpack/changelog/fix-no-connection-hide-licensing

This PR disables the `/license/activation` route (`/wp-admin/admin.php?page=jetpack#/license/activation`) when the site is not 'user' connected or if the connected user is not the connection owner.
The licensing activation flow requires a user-level connection to work properly.
Asana task: 1201096622142517-as-1201400491645534/f
* Only show the `/license/activation` route if `isLinked` and if `isConnectionOwner`.
* Fixed small bug where a 403 response from API route `jetpack/v4/licensing/attach-licenses` was returning `null` as the error message.  Not a 403 response returns the generic user permission error message, "You do not have the correct user permissions to perform this action. Please contact your site admin if you think this is a mistake."
p1HpG7-cSg-p2
No.
Ideally you should have …

Hide licenses activation route when user account not linked.

---

tools/js-tools/git-hooks/pre-commit-hook.js

Said someone in Slack:
> Whenever I commit:
> ESLint: we fixed a few hundred formatting issues, refactored everything, and fixed a couple of bugs.
> Also ESLint: `Invalid JSDoc @param type "function"; prefer: "Function"`
The first bit was actually prettier, not eslint. But it should also be
eslint, so let's make that happen.
p1638369236025800-slack-G78B6FYE7
No
* Try adding some fixable eslint things to non-excluded files, then try committing them.

pre-commit: Run `eslint --fix` like we do `phpcbf`

---

projects/plugins/jetpack/changelog/update-twitter-timeline-widget-deprecate
projects/plugins/jetpack/modules/widgets/twitter-timeline.php

The proposed change hides the [Twitter Timeline widget](https://wordpress.com/support/widgets/twitter-timeline-widget/) from the block inserter and the Legacy widget block drop-down menu.
**Before**
Block inserter  |  Legacy Widget block
**After**
Block inserter  |  Legacy Widget block
Users that already have the widget on their site can keep using it. Others can rely on the [Twitter block](https://wordpress.com/support/wordpress-editor/blocks/twitter-block/) instead.
The main purpose of this PR is to reduce the confusion that can come from having multiple blocks with similar features available.
It is worth noting that the Twitter block doesn't have granular settings that are …

Twitter Timeline widget: widget deprecation

---

projects/plugins/jetpack/changelog/fix-legacy-widgets-deprecation-comments
projects/plugins/jetpack/modules/widgets/class-jetpack-instagram-widget.php
projects/plugins/jetpack/modules/widgets/contact-info.php
projects/plugins/jetpack/modules/widgets/social-icons.php
projects/plugins/jetpack/modules/widgets/twitter-timeline.php

The proposed changes fix the comment blocks related to the `hide_widget_in_block_editor()` function that is used in multiple widget files. The goal is to follow the [DocBlock standards](https://docs.phpdoc.org/guide/guides/docblocks.html).
There are no functional/code changes.
This PR is part of the Legacy Widgets Migration project (pdf5j4-4C-p2).
Since there are no functional/code changes, we can review the proposed comments blocks.

Legacy widgets: Fix the `hide_widget_in_block_editor()` comment block to follow the DocBlock standards

---

projects/packages/README.md

* Remove the `Package textdomains` section from the Packages README file since it's not useful.
When the new Jetpack custom Composer installer package is tested and ready to use, we'll update the documentation with a suggestion to use that.
* n/a
* no
* None.

Packages: remove the textdomain section from the README file

---

projects/plugins/jetpack/changelog/fix-blog-subscription-widget-deprecation-comment
projects/plugins/jetpack/modules/subscriptions/views.php

The proposed change fixes the comment block related to the `hide_widget_in_block_editor()` function to make it follow the [DocBlock standards](https://docs.phpdoc.org/guide/guides/docblocks.html).
This is a follow-up to the recent PR https://github.com/Automattic/jetpack/pull/21931.
This PR is part of the Legacy Widgets Migration project (pdf5j4-4C-p2).
Since there are no functional/code changes, we can review the proposed comment block.

Blog Subscription widget: Fix the DocBlock structure of `hide_widget_in_block_editor()`

---

tools/e2e-commons/config/playwright.config.default.cjs

Disabled the slow tests warnings in e2e tests, introduced by #21848 
pd5faL-2m-p2#comment-53
no
- E2E tests should pass, there should be no slow tests warnings.

E2E tests: disable slow tests warnings

---

projects/js-packages/connection/changelog/fix-style-conflicts-in-disconnect-flow
projects/js-packages/connection/components/disconnect-dialog/style.scss

This PR fixes a few styling inconsistencies that affect the disconnect flow when the Gutenberg plugin is active.
* This PR includes CSS changes to fix some styling inconsistencies that appear in the disconnect flow when the Gutenberg plugin is active.
No.
* On a Jetpack test site, test first with the master branch to see the issue.
* On your test site, install the Gutenberg plugin: https://wordpress.org/plugins/gutenberg/
* Activate the Gutenberg plugin
* From the Jetpack Dashboard, in the "Site Connections" area, click on the "Manage site connection" link to open the disconnect flow.
* You should see the disconnect flow modal that looks like this:
* Notice that there is extra whitespace at the top of the modal and that the modal is not width-limited, it scales with the width of the …

Fix some styling inconsistencies in the disconnect flow

---

tools/changelogger-release.sh
tools/check-intra-monorepo-deps.sh

When changelogger-release.sh calls check-intra-monorepo-deps.sh to
update projects individually, we need to not have
check-intra-monorepo-deps.sh try to update pnpm-lock.yaml because the
dependencies may not be in a consistent state until it has finished
updating all projects.
So when check-intra-monorepo-deps.sh is called with a list of projects
to update, rely on the caller (changelogger-release.sh) to do the pnpm
lock file update.
p1638824435259700-slack-C01U2KGS2PQ
No
* Check out c8edd919ccc23891ddd6c0157835ad7241ed7dbc, cherry-pick this PR, then run `tools/changelogger-release.sh js-packages/connection; echo "Exit status was $?"`. It should complete successfully (with a 0 exit status).

tools: Fix changelogger-release.sh logic

---

.github/workflows/block-performance.yml
tools/e2e-commons/package.json

Looks like with #21848 the npm jetpack-connect script was missed, causing block performance tests workflow to fail.
I also fixed the wrong `tunnel-off` command in causing the environment teardown step to return non 0 exit code.
1156386383419466-as-1201474418952825
no
- Cannot be tested before merging with the current workflow triggers. I tested it by changing the trigger, see [this run](https://github.com/Automattic/jetpack/runs/4433315514?check_suite_focus=true)

Block performance tests: fix jetpack-connect script

---

.github/workflows/e2e-tests.yml

Since #21848 the e2e tests `connection` matrix group is running all tests having "connection" in their path, meaning also `pre-connection` and `post-connection` folders. This is a simple fix to address that.
1156386383419466-as-1201474418952822
no
- E2E tests should pass. The job `E2E connection tests` should only include the 2 tests from the connection spec.

E2E tests: fix connection run group running too many tests

---

projects/js-packages/idc/changelog/update-idc-customize-again
projects/js-packages/idc/components/card-fresh/index.jsx
projects/js-packages/idc/components/card-migrate/index.jsx
projects/js-packages/idc/components/idc-screen/index.jsx
projects/js-packages/idc/components/idc-screen/screen-main.jsx
projects/js-packages/idc/components/idc-screen/screen-migrated.jsx
projects/js-packages/idc/components/idc-screen/visual.jsx
projects/js-packages/idc/tools/custom-content-shape.jsx

Partially extracted from #21873
- add the `customContent` property to customize text content of the IDC banner
p9dueE-3Mn-p2
No.
1. Rebuild the Connection Manager package: `jetpack build packages/connection-ui`.
2. Connect Jetpack, go to Jetpack Debug and activate the IDC Simulator.
3. Go to "Jetpack Debug -> IDC Simulator", enable "IDC Simulation" and enter a "Spoof URL".
4. Edit a post and save to make the site sync. Wait a few seconds.
5. Go to "Tools -> Connection Manager", confirm that the RNA IDC screen appears.
6. Click "Move your settings". The "migrated successfully" screen should appear, click "Got it".
7. The page should reload, IDC banners should disappear.
_The IDC banner on the "Docs" tab will not properly transition to the smaller width (the cards won't rearrange …

IDC: content customization

---

projects/plugins/jetpack/changelog/start-1052-cycle
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/jetpack.php
projects/plugins/jetpack/package.json

* Start new release cycle following tagging 10.5-a.1
* N/A
* No
* Is CI happy?
* Do the numbers match?

Releases: start 10.5-a.2 cycle

---

projects/packages/my-jetpack/.gitattributes
projects/packages/my-jetpack/changelog/update-my-jetpack-ignore-raw-files
projects/packages/my-jetpack/package.json

* We do not need to ship dev files in the production version of the package.
* N/A
* No
* Not much to test here, this should just stop us from having files like this one in the production build:
https://github.com/Automattic/jetpack-my-jetpack/blob/8390e0b1eebd5a220091689d92911d7ab9eeedfc/_inc/components/my-jetpack-screen/style.scss

My Jetpack: do not ship scss and jsx files in production build.

---

pnpm-lock.yaml
projects/js-packages/idc/changelog/update-idc_text
projects/js-packages/idc/components/card-migrate/index.jsx
projects/js-packages/idc/package.json
projects/js-packages/storybook/changelog/update-idc_text
projects/js-packages/storybook/package.json
projects/packages/connection-ui/changelog/update-idc_text
projects/packages/connection-ui/package.json

* Update the text in the migrate card.
* p9dueE-3pz-p2
* no
2. Build the connection manager UI: `jetpack build packages/connection-ui`
3. Install and activate the Debug Helper plugin.
4. Navigate to the IDC Simulation page of the Debug Helper plugin, and enable the IDC Simulation.
5. Cause a sync action by editing a post. (This causes the IDC to be detected.)
6. Navigate to Tools -> Connection Manager. The IDC UI should be displayed.
7. Verify that the migrate card text is "Move all your settings, stats and subscribers to your other URL, _{your new url}_. _{your old url}_ will be disconnected from Jetpack.

IDC UI: update the default text in the migrate card

---

projects/plugins/jetpack/changelog/fix-milestone-widget-enqueue-styles
projects/plugins/jetpack/class.jetpack.php
projects/plugins/jetpack/modules/widgets/milestone/class-milestone-widget.php
projects/plugins/jetpack/modules/widgets/milestone/milestone-widget.css
projects/plugins/jetpack/tools/builder/frontend-css.js

This PR fixes an issue where the styles don't load in the Customizer (widget preview in the sidebar) until the changes are saved.
Before  |  After
The legacy widgets (like Milestone) are previewed in the Customizer with the help of an `iframe`. This iframe doesn't have access to styles set in a way that some of the legacy widgets use. Therefore, the widget preview is missing styles until we save the widget settings and reload Customizer (when the styles are loaded in the iframe as well).
The proposed change enqueues default CSS styles for the Milestone widget. These new styles come from a newly-created file `milestone-widget.css`. The preview iframe has access to these styles even before the widget is saved.
The new default CSS …

Milestone widget: Fix CSS styles in Customizer (widget preview)

---

projects/packages/assets/actions.php
projects/packages/assets/changelog/add-use-i18n-loader-webpack-plugin
projects/packages/assets/composer.json
projects/packages/assets/src/class-assets.php
projects/packages/assets/tests/php/test-assets.php
projects/packages/connection-ui/changelog/add-assets-support-for-i18n-loader
projects/packages/connection-ui/composer.json
projects/packages/jitm/changelog/add-assets-support-for-i18n-loader
projects/packages/jitm/composer.json
projects/packages/lazy-images/changelog/add-assets-support-for-i18n-loader
projects/packages/lazy-images/composer.json
projects/packages/my-jetpack/changelog/add-assets-support-for-i18n-loader
projects/packages/my-jetpack/composer.json
projects/packages/post-list/changelog/add-assets-support-for-i18n-loader
projects/packages/post-list/composer.json
projects/packages/tracking/changelog/add-assets-support-for-i18n-loader
projects/packages/tracking/composer.json
projects/plugins/backup/changelog/add-assets-support-for-i18n-loader
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/add-assets-support-for-i18n-loader
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/add-assets-support-for-i18n-loader
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

This script is the one expected by the default configuration of the new
`@automattic/i18n-loader-webpack-plugin`.
Note the `domainMap` is currently empty. Code to fill that in will come
later, as part of #21690, once we figure out the exact form of it.
PT: p9dueE-3MG-p2
Split from #21936
No
* Not much to test here, this just lays groundwork for #21936.

assets: Provide the `wp-jp-i18n-state` script

---

projects/packages/my-jetpack/changelog/add-watch-backup-plugin
projects/packages/my-jetpack/composer.json
projects/plugins/backup/changelog/add-watch-backup-plugin
projects/plugins/backup/changelog/add-watch-backup-plugin#2
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/add-watch-backup-plugin
projects/plugins/jetpack/composer.lock

* ﻿That should allow us to use the Jetpack CLI tool to watch for changes in the plugin, by running `jetpack watch plugins/backup`, as well as changes to the "My Jetpack" package: `jetpack watch packages/my-jetpack`.
* p1639141827208200-slack-G78B6FYE7
* No
* Run `jetpack watch plugins/backup`
* Run `jetpack watch packages/my-jetpack`
* Does it work?

Backup & My Jetpack: add watch command to the plugin and package.

---

.github/workflows/issues-to-projects.yml

Jetpack Boost issues were snapping back to our Project Board's "inbox" column every time they were updated. Unfortunately, the Action we were using always overwrote the project status field on every update.
I [forked the Action](https://github.com/thingalon/project-beta-automations/) and [added support to leave out the `status_value` field](https://github.com/thingalon/project-beta-automations/commit/fe39095d46d75295cad645e99d595aafd49ccb9d). With this fork, issues which are not on the board yet will get pushed into the default (inbox) status column - and existing items on the board will not be affected on update.
I've tested it on another internal repository, and it works well. I've also [submitted my changes upstream](https://github.com/leonsteinhaeuser/project-beta-automations/pull/19). …

Prevent issues returning to Inbox on update.

---

projects/js-packages/babel-plugin-replace-textdomain/README.md
projects/js-packages/babel-plugin-replace-textdomain/changelog/fix-babel-replace-textdomain-when-missing
projects/js-packages/babel-plugin-replace-textdomain/src/index.js
projects/js-packages/babel-plugin-replace-textdomain/tests/__snapshots__/plugin.test.js.snap
projects/js-packages/babel-plugin-replace-textdomain/tests/fixtures/bad-args.js
projects/js-packages/babel-plugin-replace-textdomain/tests/plugin.test.js

It should also fix up calls with no domain parameter at all, like
`__('foo')`.
Also, clean up the code a bit, and actually replace the nodes instead of
munging the value (which I'm not sure is actually supported).
PT: p9dueE-3MG-p2
No
* Is CI happy?

babel-plugin-replace-textdomain: Replace missing domains too

---

projects/plugins/jetpack/changelog/fix-php-notice-contact-form-value
projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php

Fixes #22079
* Avoid a PHP notice in some edge-cases with the Contact form module.
* N/A
* No
I am not quite sure how to reproduce this, so I do not have detailed steps to test for that specific bug.
* Go to Jetpack > Settings and ensure that the contact form module is active.
* Go to Posts > Add New and create a new form block, with multiple different fields.
* Publish post, and submit a test form.
* Check the email you got; it should inlude all the fields you've submitted.

Contact Form: avoid PHP notices in submitted forms in some cases.

---

tools/get-contributor-list.sh

When releasing a beta, the script currently won't let you check a version number in CHANGELOG.md such as 10.4-beta. This update will allow that match.
N/a
n/a
Easiest way is to go to Jetpack's CHANGELOG.md file and append `-beta` to the 10.4 release section, so it reads 10.4-beta.
Then try running `tools/get-contributor-list.sh plugins/jetpack 10.4`. Things should work fine. Without the extra regex, the script will fail.

Tools: Update get-contributor-list script to allow -beta

---

projects/plugins/jetpack/changelog/update-vimeo-video-format
projects/plugins/jetpack/modules/shortcodes/vimeo.php
projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.vimeo.php
tools/phpcs-excludelist.json

Fixes #10529
This PR makes some changes to both Vimeo shortcode tests (consolidate the existing tests, fix linting errors, avoid duplications and rely on data providers to simplify things), as well as update the oEmbed provider regex to pull out IDs from Vimeo URLs. We can then use those IDs in the existing shortcode.
* N/A
* No
* Go to Jetpack > Settings, and enable the Shortcodes feature
* Go to Posts > Add New, add some test content.
* Between 2 paragraphs, add the following URLs on their own line (not as links, not formatted, just the URLs on their own):
* `https://vimeo.com/289091934/cd1f466bcc`
* `https://vimeo.com/album/2838732/video/6342264`
* `https://vimeo.com/6342264`
* `http://player.vimeo.com/video/18427511`
* Ensure those videos are then rendered on the frontend when …

Vimeo Embeds: support more URL formats, such as videos in playlists

---

projects/plugins/jetpack/changelog/update-remove-facebook-share-count-code
projects/plugins/jetpack/modules/sharedaddy/sharing-service.php
projects/plugins/jetpack/modules/sharedaddy/sharing.js

The recommended way to display the share counter for Facebook posts is to use the official buttons. The non-official buttons used to display the share counters as well in the past, but have become nonfunctional, due to Facebook requiring us to send an access token for it. This PR will remove the non-functional code that's in place to display the share count for the non-official buttons. 
Fixes https://github.com/Automattic/jetpack/issues/22113
- Remove the code in place to fetch shares for non-official facebook share button 
p7DVsv-6n6-p2
No
1. Go to Jetpack->Settings->Sharing.
2. Under sharing buttons, enable the option "Add sharing buttons to your posts and pages".
3. Click on configure sharing buttons and choose any option except for "official buttons" as shown below.
4. Create a blog …

Remove Facebook share counter code for non-official buttons

---

tools/docker/bin/fakepot.sh

WordPress.org's translation infrastructure uses --ignore-domain, we
should too.
None
No
* Try running it in the docker env on `/var/www/html/wp-content/plugins/backup`. Check that the produced files contain strings from packages.

docker: Fix "fakepot" `wp i18n` command

---

projects/plugins/backup/changelog/update-plugins-load-assets-i18n-map
projects/plugins/backup/jetpack-backup.php
projects/plugins/boost/changelog/update-plugins-load-assets-i18n-map
projects/plugins/boost/composer.json
projects/plugins/boost/composer.lock
projects/plugins/boost/jetpack-boost.php
projects/plugins/jetpack/changelog/update-plugins-load-assets-i18n-map
projects/plugins/jetpack/jetpack.php

For Jetpack, this will keep the packages' i18n working once we update
the packages to use aliasable domains instead of "jetpack".
For Backup and Boost, this will make the packages' i18n _start_ working
once we do that update (and once a version with `jetpack_vendor/` is
pushed to wporg svn so the translations exist).
When we add use of jetpack-composer-plugin to other plugins (e.g.
Search), we'll need to remember to do something similar to each of them
too.
For #21690 
No
* This shouldn't make any visible difference yet.

Load the i18n-map in plugins

---

pnpm-lock.yaml
projects/js-packages/i18n-check-webpack-plugin/README.md
projects/js-packages/i18n-check-webpack-plugin/changelog/add-i18n-check-expected-textdomain
projects/js-packages/i18n-check-webpack-plugin/package.json
projects/js-packages/i18n-check-webpack-plugin/src/I18nCheckPlugin.js
projects/js-packages/webpack-config/changelog/add-i18n-check-expected-textdomain
projects/js-packages/webpack-config/package.json
projects/js-packages/webpack-config/src/webpack.js

If the textdomain used is not the expected domain, raise an error.
Then set this in our webpack-config based on the contents of
composer.json, to help ensure that plugins and packages actually use the
expected domain.
None
No
* Edit `projects/plugins/backup/babel.config.js` to set the domain to something other than "jetpack-backup", and see if a production build fails with the appropriate error.

i18n-check-webpack-plugin: Allow specifying the expected textdomain

---

projects/packages/composer-plugin/changelog/fix-composer-plugin-dev-versions
projects/packages/composer-plugin/changelog/fix-composer-plugin-dev-versions#2
projects/packages/composer-plugin/src/class-plugin.php

"1.2.x-dev" is not valid semver. Replace anything that's invalid with
"0.0.0" so plugins with released versions will be preferred as the
source for i18n.
Also fix the attempted deletion of the i18n-map file if the plugin is
misconfigured.
None
No
* Probably the easiest way to test the version number bit is
* `rm -rf projects/plugins/jetpack/vendor/ projects/plugins/jetpack/jetpack_vendor/`
* `composer -d projects/packages/assets config extra.textdomain jetpack-assets`
* `tools/composer-update-monorepo.sh projects/plugins/jetpack/`
* Inspect `projects/plugins/jetpack/jetpack_vendor/i18n-map.php`, it should not contain a mapping for "jetpack-assets" version "1.15.x-dev".
* Probably the easiest way to test the i18n-map deletion is to create a temporary directory somewhere, then create this …

composer-plugin: Don't output invalid versions in i18n-map

---

projects/plugins/debug-helper/changelog/update-notice_when_sync_disabled
projects/plugins/debug-helper/modules/class-idc-simulator.php

Sync can be disabled in the Debug Helper plugin's IDC Simulator module. This allows for easy testing of IDC handling on REST requests. However, if a user disables Sync and forgets to reenable it, it can be hard to track down why Sync isn't working.
To prevent this confusion, let's display an admin notice when the IDC Simulator module has disabled Sync.
* n/a
* n/a
1. Install, activate, and connect Jetpack.
2. Install and activate this branch of the Debug Helper plugin.
3. Enable the IDC Simulator module in the Debug Helper plugin.
4. In the IDC Simulator module, disable Sync. An admin notice informing you that Sync is disabled should be displayed.
5. Navigate to other wp-admin pages and confirm that the admin notice is displayed. (Note the admin notices are not displayed on the Jetpack …

Debug Helper IDC Simulator: Display an admin notice when the module disables Sync

---

projects/plugins/jetpack/changelog/fix-widget-visibility-notice
projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php

Prevents an E_NOTICE being triggered when running in a non-web
environment.
Fixes issue brought up at https://github.com/Automattic/jetpack/pull/20255#issuecomment-998027246
No
1. Use a theme that supports widgets (you probably are already)
2.  Go to Jetpack → Settings → Writing, scroll down to the Widgets section, and toggle the switch labelled Enable widget visibility controls to display widgets only on particular posts or pages.
3. Go to Appearance -> Widgets
4. Add a widget, you should see a preview of it
5. Click on one of the blocks you've added
6. Go to the 'Block' sidebar and expand 'Advanced'
7. Set a 'visibility' like 'Show this block if page is frontpage'
8. Press update
9. Look at the frontpage of the site, it should display the widget
10. Look at another page of the site, it …

Conditional widgets: Check REQUEST_METHOD set before use

---

projects/packages/connection-ui/changelog/fix-assets-register-textdomain
projects/packages/connection-ui/src/class-admin.php
projects/packages/identity-crisis/changelog/fix-assets-register-textdomain
projects/packages/identity-crisis/src/class-ui.php
projects/packages/my-jetpack/changelog/fix-assets-register-textdomain
projects/packages/my-jetpack/src/class-initializer.php

When #22151 assigned text domains to the packages, it missed the domains
in calls to Assets::register_script().
We should make a sniff to catch this in the future, but for now let's
just fix it.
None
No
* ???

Fix package Assets::register_script() textdomains

---

tools/docker/bin/fakepot.sh

Chances are the plugin will have symlinks to the composer packages. As
it is now, it'll just copy the links without even adjusting their
targets, meaning that any i18n from the packages won't be fake-potted.
We can't just fix the symlinks' targets though, as then `wp i18n
make-pot` will probably wind up descending into various WorDBless copies
of WordPress.
The fix is to check for copied symlinks, and for each one do a recursive
copy from the target package using the same algorithm that handles
.gitignore, production-include, and such.
None
No
* `rm -rf projects/plugins/backup/vendor projects/plugins/backup/jetpack_vendor`
* `jetpack build packages/identity-crisis`
* `jetpack build plugins/backup`
* `jetpack docker exec /var/scripts/fakepot.sh /var/www/html/wp-content/plugins/backup`
* …

Docker: Fix fakepot symlink handling

---

projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php
projects/plugins/jetpack/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
projects/plugins/jetpack/changelog/rm-stats-hide-smiley-option
projects/plugins/jetpack/modules/stats.php

Fixes #22192
* The tracking pixel is now always hidden by default, so we do not really need that option, or to check for that option anymore.
* N/A
* No
* Start with a site with the Stats feature active, and with this branch.
* Open the site an an incognito window.
* Ensure you see the following in the head: `<style type='text/css'>img#wpstats{display:none}</style>`

Stats: remove the legacy hide_smile option

---

projects/plugins/jetpack/changelog/fix-stats-embeds
projects/plugins/jetpack/modules/stats.php

Fixes #22179
* When a post is embedded into another site, it's not really a view of that post; only an excerpt of the post is displayed. As a result, it is best not to count a view when such an embedded post is displayed.
* N/A
* No
* You'll need 2 sites for this;
* The Stats module needs to be active on both sites.
* one of them has to be running this branch (call it Site B).
* On site A, publish a new post. In that post, include (on its own line) a link to a post from Site B.
* In an incognito window (so you're not logged in to those sites), visit the post you just published.
* In your network tab in dev tools, filter for `g.gif`
* Notice that the tracking pixel is called once for the post you are viewing.
* Now, on site B, revert to using latest stable.
* Refresh the post in the …

Stats: do not add tracking pixel to embed views

---

projects/plugins/jetpack/_inc/client/components/masthead/header-nav.jsx
projects/plugins/jetpack/_inc/client/components/masthead/index.jsx
projects/plugins/jetpack/_inc/client/components/masthead/style.scss
projects/plugins/jetpack/changelog/restore-header-nav-for-woa-sites

* Add back the `Dashboard | Settings` header nav buttons that were removed in #22130. For now, we will show the buttons only on WoA sites since they lack a "Settings" submenu item.
p1HpG7-dHF-p2#comment-51529
No.
* On a WoA site, using the Jetpack Beta Tester plugin, checkout Bleeding Edge and see that in Calypso for the Jetpack menu item `/wp-admin/admin.php?page=jetpack#/dashboard` you don't see the `Dashboard | Settings` header nav.
* Next, checkout this feature branch and see that the `Dashboard | Settings` nav has returned.
* Checkout this feature branch on a bleeding edge non-WoA site (JN) and see that the `Dashboard | Settings` are not shown.

Restore HeaderNav, only show on WoA sites

---

projects/packages/connection/changelog/update-jetpack-connection-active-plugins-no-sync
projects/packages/connection/src/class-manager.php
projects/packages/connection/src/class-plugin-storage.php
projects/packages/connection/tests/php/test_plugin_storage.php

The `jetpack_connection_active_plugins` option is Connection specific, however relies on Jetpack Sync to be kept up to date with the Cache site on WPCOM.
This PR ensures that `jetpack_connection_active_plugins` is consistent on both ends of the Connection, even when Sync is not present.
* `Jetpack\Connection\Plugin_Storage` class: Added `update_active_plugins_wpcom_no_sync_fallback` method which makes a remote request to WPCOM's `jetpack-active-connected-plugins` endpoint
* `Jetpack\Connection\Plugin_Storage` class: Updated `update_active_plugins_option` method to check if Sync is present and enabled and if not, utilize the introduced `update_active_plugins_wpcom_no_sync_fallback` as fallback.
1201445365181527-as-1201445365181550/f
No
D71611-code

Jetpack Connection: Add jetpack_connection_active_plugins fallback when Sync is not present

---

projects/plugins/jetpack/changelog/update-wordads-header-ad
projects/plugins/jetpack/modules/wordads/class-wordads.php
projects/plugins/jetpack/modules/wordads/php/class-wordads-sidebar-widget.php

* Fixes issue with top header ad markup being added to the the `<head>` instead of in the `<body>`. The ad will now be placed before the first-child element of the `<body>` by default.
* Adds a `wordads_header_ad` action that can be used in the template to place the top header ad. When the action is used, the default placement in the `<body>` will be suppressed. The action will only be allowed once per page.
* Adds `leaderboard` to the allowed sizes when placing the Ads Widget.
No
* Visit ads enabled site with the `Top of each page` additional ad placement turned on.
* Verify the top ad markup is the first element in `<body>`.
* Add `do_action( 'wordads_header_ad' );` to your theme template.
* Verify the top ad markup displays at the correct location where the action was fired.
* Verify …

[Ads]: Add action for manual placing of top header ad. Allow leaderboard size for Ads Widget

---

.github/workflows/issues-to-projects.yml

In #22080, I switched from `leonsteinhaeuser/project-beta-automations@v1.0.2` to my own fork which added support for pushing issues to project boards _without_ specifying a target status / column.
My [change has been accepted upstream](https://github.com/leonsteinhaeuser/project-beta-automations/pull/19) and [released in 1.0.3](https://github.com/leonsteinhaeuser/project-beta-automations/releases/tag/v1.0.3) of the original tool.
Now that the change has been accepted upstream, this PR returns to using the original upstream lib.
* Switch back to using upstream version of `leonsteinhaeuser/project-beta-automations` - release 1.0.3
n/a
no
I've [tested it in the Boost Hydra repos](https://github.com/Automattic/boost-hydra/commit/f07bfccddff3c82632f369e857d4f950174a9f3b). Beyond that, this …

Switch back to upstream project automation tool

---

projects/plugins/jetpack/changelog/update-sync_option_test_failure_message
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php

* Fix typos in the failure message in the `assertOptionIsSynced` method.
* n/a
* no
Testing shouldn't be necessary, but you can manually cause a test failure and verify that the failure message does not contain typos if you'd like. For example:
1. Change `$this->assertEqualsObject` to `$this->assertNotEquals` in this line: https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php#L289
2. Run a test that uses `assertOptionIsSynced`: `jetpack docker phpunit -- --filter=test_sync_default_contentless_options`
3. Confirm that the test failure message doesn't contain typos.

Tests: Fix typos in the failure message in the assertOptionIsSynced method

---

projects/plugins/jetpack/changelog/update-multisite_comment
projects/plugins/jetpack/tests/php/bootstrap.php

* Fix the logic which determines whether to display the multisite comments for PHP unit tests.
* n/a
* no
Test three conditions with the `WP_TESTS_MULTISITE` constant:
1. Add `define( 'WP_TESTS_MULTISITE', true);` before the multisite logic in the `bootstrap.php` file: https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/tests/php/bootstrap.php#L61
2. Run a test: `jetpack docker phpunit -- --filter=test_sends_stats_data_on_heartbeat_on_multisite`
3. Notice that the `To run Jetpack multisite, use -c tests/php.multisite.xml  Disregard Core's -c tests/phpunit/multisite.xml notice below.` comment **is not** displayed.
1. Add `define( 'WP_TESTS_MULTISITE', false);` before the multisite logic in the `bootstrap.php` file: …

Tests: fix the multisite logic

---

projects/packages/assets/changelog/fix-assets-alias_textdomain-during-activation-is-not-_doing_it_wrong
projects/packages/assets/src/class-assets.php

Plugin activation comes after the wp_default_scripts hook, but that's
expected so don't call `_doing_it_wrong` in that case.
p1641335901414900-slack-C01U2KGS2PQ
No
* Deactivate Jetpack, then activate it again. Check that warnings about "Textdomain aliases should be registered before the `wp_default_scripts` hook" are not produced.
* If testing this on a JN site, use the Beta Plugin to activate the branch version. Activating it via the Plugins page will activate 10.4 rather than the branch, and 10.4 doesn't have the bug in the first place.

Assets: Suppress "doing it wrong" warning for aliases during plugin activation

---

projects/plugins/jetpack/changelog/update-social-menu-nav
projects/plugins/jetpack/modules/theme-tools/social-menu.php

﻿This is no longer necessary. Read more about it here:
https://core.trac.wordpress.org/ticket/54054
> According to HTML5 documentation, adding role="navigation" to a <nav> element is unnecessary (and not permitted).
* Primary issue: #21322
* No
* Not much to test here, there should be no functional changes.

Social Menu: remove role navigation attribute from nav item

---

pnpm-lock.yaml
projects/js-packages/licensing/changelog/fix-license-button-specificity
projects/js-packages/licensing/components/activation-screen-success-info/primary-link/style.scss
projects/js-packages/licensing/package.json
projects/plugins/jetpack/changelog/fix-license-button-specificity
projects/plugins/jetpack/package.json

﻿
When using the Gutenberg plugin, an additional stylesheet is enqueued in the Jetpack React dashboard, with specific styles for `.components-button` that overwrite our existing styles.
By being more specific, we should be able to ensure that our styles will remain.
**Before**
**After**
* This was reported in p8oabR-LV-p2#comment-5750
* No
* Start with a site running Jetpack and this branch, and the Gutenberg plugin.
* Connect your site to WordPress.com. Do **not** buy any plan yet.
* Go to https://cloud.jetpack.com/pricing and purchase a Backup product.
* Do not attach it to your site just yet.
* Go to https://wordpress.com/me/purchases/ and locate the product you just bought (you can search for "Pending" to locate the purchase if you have a lot on that page).
* On the product page, copy …

Licensing buttons: ensure styles are specific enough

---

projects/plugins/jetpack/changelog/fix-donations-missing-div
projects/plugins/jetpack/extensions/blocks/donations/donations.php

The domains block server-side render was missing a closing div tag,
which caused a variety of layout issues.
Fixes #20309, #19766, #18165
No
1. Ensure you're on a paid wp.com plan (or a jetpack complete plan if testing on jetpack)
2. Create a new post
3. Add a Donations block to the post
4. Insert a full width column block underneath the donations block (you'll need to click on one of the icons to change the column block to full width)
5. Add some content to the columns
6. Gutenberg should display this as full width
7. Save the post
8. View the post - before this change the columns block should not be full width and after it should
Before | After
-------|------
There's a variety of other scenarios too, e.g. placing the donations block inside a cover block and then having cover blocks …

Correct mark-up for donations block

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/mosaic/index.js
projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/mosaic/resize.js

Fixes failing JS test that was introduced by a bug in https://github.com/Automattic/jetpack/pull/21767/files. The failing test is:
```
FAIL extensions/blocks/tiled-gallery/layout/mosaic/test/index.js
● renders as expected
TypeError: row.querySelectorAll is not a function
58 | function getRowCols( row ) {
59 | 	return Platform.select( {
> 60 | 		web: () => Array.from( row.querySelectorAll( '.tiled-gallery__col' ) ),
| 		                           ^
61 | 		native: () => row,
62 | 	} )();
63 | }
```
- Bug fix for the Tiled Gallery on the web (this bug isn't on `master`, it's only on our feature branch).
p9ugOq-1Tb-p2
Verify that the `JS tests` CI check passes. The "Code coverage" test may fail for different reasons, as long as it doesn't fail due to the above error.

[RNMobile] Fix Tiled Gallery JS test failure 

---

pnpm-lock.yaml
projects/js-packages/idc/changelog/add-idc-errors
projects/js-packages/idc/components/card-fresh/index.jsx
projects/js-packages/idc/components/card-migrate/index.jsx
projects/js-packages/idc/components/error-message/error-gridicon.jsx
projects/js-packages/idc/components/error-message/index.jsx
projects/js-packages/idc/components/error-message/style.scss
projects/js-packages/idc/components/idc-screen/index.jsx
projects/js-packages/idc/components/idc-screen/screen-main.jsx
projects/js-packages/idc/components/idc-screen/stories/index.jsx
projects/js-packages/idc/components/idc-screen/visual.jsx
projects/js-packages/idc/components/safe-mode/index.jsx
projects/js-packages/idc/hooks/use-migration.jsx
projects/js-packages/idc/hooks/use-start-fresh.jsx
projects/js-packages/idc/package.json
projects/js-packages/idc/state/actions.jsx
projects/js-packages/idc/state/reducers.jsx
projects/js-packages/idc/state/selectors.jsx
projects/js-packages/storybook/changelog/add-idc-errors
projects/js-packages/storybook/package.json
projects/packages/identity-crisis/changelog/add-idc-errors
projects/packages/identity-crisis/package.json

- Display error messages if IDC resolution fails.
p9dueE-3pz-p2#comment-6682
No.
1. Rebuild the package if testing locally: `jetpack build packages/identity-crisis`
2. Connect Jetpack, go to Jetpack Debug and activate the IDC Simulator.
3. Go to "Jetpack Debug -> IDC Simulator", enable "IDC Simulation" and enter a "Spoof URL".
4. Edit a post and save to make the site sync. Wait a few seconds. Open any WP-admin page, confirm that the IDC screen appears.
5. Switch the browser to offline mode, or disconnect from the internet entirely. Click on "Move your settings", "Create a fresh connection", and "Stay in Safe Mode" buttons. Confirm that the errors show up, and other errors disappear when you click a button.
6. Click on the "Find out more here" link, confirm that the support page opens in a …

IDC: display resolving errors

---

projects/plugins/jetpack/changelog/fix-donations-block-reuse-stored-plan-ids
projects/plugins/jetpack/extensions/blocks/donations/tabs.js

Fixes https://github.com/Automattic/jetpack/issues/22049
There are some cases where the stored plan IDs in the attributes of the Donations block are erased if they are edited by a user who is not the plan owner. To solve that, this PR introduces a safety check to only edit the stored plan IDs if the new ones have a value.
Note that I had a bad time trying to reproduce the issue described in https://github.com/Automattic/jetpack/issues/22049 (only managed to replicate it once), but I suspect this fix should prevent it from happening.
p9MPsk-1iY-p2#comment-12131
No.
- [Spin up a JN site running changes from this PR](https://jurassic.ninja/create?jetpack-beta&branches.jetpack=fix/donations-block-reuse-stored-plan-ids).
- Set up Jetpack and start for free.
- You need to sandbox the WP.com …

Donations block: Reuse stored plan IDs

---

projects/plugins/jetpack/extensions/blocks/tiled-gallery/save.native.js

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4306
Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/4433
This PR addresses the pixelated images we see on Tiled Galleries. The cause was a hard-coded image dimension set in the block's `save` function.
A workaround is to omit the width and height altogether, which allows images to be rendered at full-resolution on the frontend. 
A solution is out of the scope of this PR and this is why: Image blocks, which we used in the Tiled Gallery here, don't expose their width or height via the image's block attributes. I can't find a way to ask an inner image block for its width or height. https://github.com/WordPress/gutenberg/issues/23244 tracks the need to make the image block provide a default width and …

[RNMobile] Fix pixelated Tiled Gallery images

---

projects/plugins/jetpack/changelog/fix-donations-without-stripe
projects/plugins/jetpack/extensions/blocks/donations/donations.php

When adding/editing a document with a Donations block that doesn't have
stripe connected it displays a prominent message saying that the block
will be hidden to visitors until stripe is connected. In actual fact it
displays a partial, broken block.
This change does as the message says, and displays nothing on the site
front-end to visitors, unless stripe is connected.
Note that the linked bug proposes that the display on the front-end ought to display a warning rather than nothing at all. I'm open to discuss that, but I decided to display nothing at all because:
* It's what the existing message says in the editor, so it's clear that Stripe needs connecting already.
* When a Stripe account becomes disconnected there is an email and a notification explaining that they need connecting, so …

Donations: Don't display on front-end if stripe disconnected

---

projects/packages/identity-crisis/changelog/fix-idc_query_args_check_staging_offline
projects/packages/identity-crisis/src/class-identity-crisis.php
projects/packages/identity-crisis/tests/php/test-identity-crisis.php

* IDCs should not be detected and the IDC UI should not be displayed when the site is in offline or staging mode. Check whether the site is in offline or staging mode before adding the IDC query arguments to authenticated REST requests.
* n/a
* no
1. Install and activate this branch of Jetpack.
3. Put the site in staging mode. In the site's `wp-config.php` file, set the `JETPACK_STAGING_MODE` constant to true using this line: `define( 'JETPACK_STAGING_MODE', true );`.
4. Using the Jetpack Debug Helper plugin and its IDC Simulator module, cause an IDC.
5. Confirm that the IDC UI is not displayed. You can also check the request URLs in the IDC Simulator module to confirm that the idc query args (`idc`, `siteurl`, and `home`) have not been added to the request URLs.
6. …

Identity Crisis: Do not add IDC query args to requests when in offline or staging mode

---

projects/plugins/jetpack/changelog/update-check_for_alias_textdomains_method
projects/plugins/jetpack/jetpack.php

* Check that the `Assets::alias_textdomains_from_file` method exists before calling it. This could
prevent fatals that would occur if an older version of the Assets package which doesn't have that
method is loaded.
* p1641832336007500-slack-C025MP1Q3HT
* no
I don't think any testing is necessary.

Jetpack plugin: check that an Assets package file exists before calling it

---

projects/plugins/jetpack/CHANGELOG.md
projects/plugins/jetpack/changelog/fix-display-bundle-woa
projects/plugins/jetpack/changelog/fix-install-plugins-aag-multisite
projects/plugins/jetpack/changelog/fix-jetpack-modules-this-as-window
projects/plugins/jetpack/changelog/fix-license-button-specificity
projects/plugins/jetpack/changelog/fix-widget-visibility-match-all
projects/plugins/jetpack/changelog/jetpack-branch-10.5
projects/plugins/jetpack/changelog/rm-crm-aag-card
projects/plugins/jetpack/changelog/update-check_for_alias_textdomains_method
projects/plugins/jetpack/readme.txt

* Ports back changelog & readme changes from the 10.5 release branch.
* Update readme.txt stable tag to match WPorg trunk.
n/a
No.

Jetpack: port back changelog from 10.5 release branch

---

projects/plugins/jetpack/changelog/add-image-compare-block-align-tool
projects/plugins/jetpack/extensions/blocks/image-compare/edit.js
projects/plugins/jetpack/extensions/blocks/image-compare/index.js

Fixes #15740 
The proposed change adds `wide` and `full` width alignment options to the Image Compare block for better editing experience.
Before | After |
| ![Markup on 2022-01-11 at 12:48:48](https://user-images.githubusercontent.com/25105483/148937630-9d85af96-50c5-468c-b940-10eeea99ef71.png)  | ![Markup on 2022-01-11 at 12:47:04](https://user-images.githubusercontent.com/25105483/148937622-00a6b95a-a508-4585-92a6-5d774eeab0e4.png)  |
Related issue: https://github.com/Automattic/wp-calypso/issues/47681
This PR is a part of the _Expanding Jetpack Block design tooling for Full Site Editing_ project: pdDOJh-6-p2.
1. Create a new post or a page with the Image Compare block
2. There should be a new Align tool in the block toolbar available …

Image Compare block: Add `wide` and `full` alignment options

---

projects/plugins/jetpack/changelog/update-settings-default-values
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
projects/plugins/jetpack/tests/php/json-api/test-class.wpcom-json-api-site-settings-v1-4-endpoint.php

An array with the value of false is not what we're looking for.
* Changes the default value of `woocommerce_onboarding_profile` from `array( 0 => false )` to `array()`.
No
Run unit tests with the command: `jetpack docker phpunit -- --filter=WP_Test_WPCOM_JSON_API_Site_Settings_V1_4_Endpoint`

Site Settings: Default to empty array for WooCommerce Onboarding Profile

---

projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/components/plan-section/index.jsx
projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-plan/Readme.md
projects/packages/my-jetpack/_inc/hooks/use-plan/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-fetch-site-features
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php

Closes #22288
This PR does the first implementation of the Plan section. The most relevant parts of it:
* Data propagation, end to end from wpcom to the client/frontend
* Deal with data adding the `usePlan()`  custom hook
* Pretty basic `<PlansSection />` component.
No
* Apply these changes
* Go to My Jetpack section
* Confirm you see the pretty basic Plan section there.
* you can take a look at how the client performs the endpoint request
`https://retrowolf.ngrok.io/wp-json/my-jetpack/v1/site`
* also, inspect the `<PlansSection />` component.

My Jetpack: first implementation of plans section

---

projects/packages/composer-plugin/changelog/fix-composer-plugin-versions
projects/packages/composer-plugin/src/class-plugin.php

Composer's `getVersion()` likes to return 4-component versions, while
semver only allows for three components. Strip the extra component when
generating the i18n map file.
None
No
1. Check out jetpack/branch-10.5
2. Cherry-pick this PR
3. `cd projects/plugins/jetpack`
4. `composer config repositories.0 path ../../packages/composer-plugin/`
5. `composer update automattic/jetpack-composer-plugin`
6. Examine `jetpack_vendor/i18n-map.php`. Packages should have correct version numbers, not "0.0.0".

composer-plugin: Recognize composer's 4-component versions

---

projects/packages/my-jetpack/changelog/fix-typo-my-jetpack-scripts
projects/packages/my-jetpack/src/class-initializer.php

Updates `Initializer: enqueue_scritps()` to  `Initializer: enqueue_scripts()` 
* Renames the method as it had a typo
no
Incoming

My Jetpack: Janitorial - Fix typo in method name enqueue_scripts

---

projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/_inc/components/plans-section/style.scss
projects/packages/my-jetpack/changelog/update-plans-section-style

Fixes #22330
Updates the style of the Plans Section according to proposed design
* Introduces style.scss for the Plans Section component
* Uses style resembling the proposed one
no
* Build with `jetpack build packages/my-jetpack`.
* Have Jetpack Backup and a plan for it (either Upgrade to Security or Backup)
* Checkout the My Jetpack page.
* Confirm the styles look updated
* Note the updated styles for the Plans section even though it looks different than the Connection Section

My Jetpack: Update Plans Section style

---

projects/js-packages/connection/changelog/update-connect-plan-button
projects/js-packages/connection/components/connect-screen/required-plan/style.scss

* Fixed the style overrides for the Get Jetpack Backup button
No.
* Start a JN site with the Backup Plugin
* Visit the connection screen and ensure the Required Plan connection screen matches Storybook
Storybook: https://automattic.github.io/jetpack-storybook/?path=/docs/connection-connect-screen-with-required-plan--default

[JS-package: Connection] Fixed style for button on Required Plan screen

---

pnpm-lock.yaml
projects/packages/my-jetpack/changelog/update-my-jetpack-unit-tests-scripts
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/jest.setup.js
projects/packages/my-jetpack/package.json
projects/plugins/backup/changelog/update-my-jetpack-unit-tests-scripts
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/update-my-jetpack-unit-tests-scripts
projects/plugins/jetpack/composer.lock

Include scripts for `test`, `watch` and `coverage` related with JS files.
* Add `test` script into `package.json`.
* Add `test-js`, `test-js-watch` into `composer.json`.
* Add JS coverage into `test-coverage`.
No.
_To run general all tests_
* Run `jetpack test packages/my-jetpack js`
* Tests will run
_To enter watch mode_
* Run `jetpack test packages/my-jetpack js-watch`
* It will enter into watch mode.
_To run coverage_
* Run `jetpack test packages/my-jetpack coverage`
* Tests will run and `coverage` folder will be created.
_To run with COVERAGE_DIR_
* Run `COVERAGE_DIR=agora jetpack test packages/my-jetpack coverage`
* Tests will run and `agora` folder will be created.

My Jetpack: Add scripts for JS tests

---

projects/packages/assets/changelog/fix-assets-contentdir-not-in-abspath
projects/packages/assets/src/class-assets.php
projects/packages/assets/tests/php/test-assets.php

When generating the base URL from `WP_LANG_DIR`, handle the case where
`WP_LANG_DIR` is in `WP_CONTENT_DIR` but `WP_CONTENT_DIR` is not in
`ABSPATH`.
p1642416715007500/1639739679.124300-slack-C82FZ5T4G
No
* Set up a site where `WP_CONTENT_DIR` is not in `ABSPATH` (e.g. an Atomic Ephemeral site). Then set a non-English locale and try out Instant Search.
* If it fails, at least make sure it tried to fetch a correct URL and got a 404 because the language pack hasn't been updated for changed Instant Search script paths in 10.6-a.1 yet.

Assets: Handle `WP_CONTENT_DIR` not in `ABSPATH`

---

docs/development-environment.md

Update dev docs with new Composer version that the monorepo uses, was updated in #22373
#22373
No.
Proofread.

Docs: monorepo now uses Composer v2.2.x

---

projects/packages/my-jetpack/.gitattributes
projects/packages/my-jetpack/changelog/update-my-jetpack-do-not-ship-raw-files

﻿We ship the build directory:
https://github.com/Automattic/jetpack-my-jetpack/tree/v0.3.3/build
We consequently do not need raw files.
* N/A
* No
* Not much to test here I'm afraid. Does it make sense? 
* You can check the generated zip for that package in the build GitHub action; it should not include the `_inc` dir.

My Jetpack build: do not ship raw files in production bundle

---

projects/plugins/jetpack/_inc/client/components/jetpack-notices/user-license-activation.jsx
projects/plugins/jetpack/changelog/fix-activation-notice-proptypes

Closes #22382
This PR fixes issue #22382 where in development mode, a prop type warning was being output to the console originating from the `UserLicenseActivationNotice` component.
**Implementation notes:**
- `activationNoticeDismissInfo.last_detached_count` was set as a "required" prop and this was throwing a prop type warning because by default the value will be `null`.
- To fix this, I removed the requirement for the prop to be "required", and instead set the default value to `null` via React `defaultProps`.
#22382
No
1. Spin up a local development version of Jetpack (localhost docker env for example). Connect Jetpack and visit the Jetpack dashboard.
2. Open the dev console.
3. Verify you **DO NOT** see a warning in the console that says: ```Warning: Failed prop type: The prop …
```

Fix prop type warning in UserLicenseActivationNotice component.

---

projects/plugins/backup/changelog/fix-classname-use-prop
projects/plugins/backup/src/js/components/Backups.js

Correct occurrencies where `class` is used instead o `className`.
In React the class property must be named className.
Fixes https://github.com/Automattic/jetpack/issues/22378
* Change class to ClassName, as it should be on React. 
No
1- Start your Jetpack local environment
2- On the `wp-config.php` of your site, add `define( SCRIPT_DEBUG, true );` so the React warnings are shown. If you're running JP on Docker, the wp-config should be in `tools/docker/wordpress/wp-config.php`
3- Make sure your site has a plan and visit the Backup wp-admin page
4- Open the dev console
Confirm you see no messages with this Warning: Invalid DOM property class. Did you mean className?

Backup: Correct wrong use of className prop

---

projects/js-packages/connection/changelog/fix-redirectUri-connection-status-card
projects/js-packages/connection/components/connection-status-card/index.jsx

Makes the redirectUri property to be `isRequired` and sets it to null by default
Fixes some Warning shown when loading my Jetpack 
* Adds default prop  `isRequired` value set to `null`
* makes `redrectUri` not be required
no
* Run `jetpack build packages/my-jetpack`.
* Your site has to have `SCRIPT_DEBUG` constant set to true
* Make sure you can see the My Jetpack page.
* Visit My Jetpack with the browser console open.
* Confirm you don't see an error like this:
`Warning: Failed prop type: The prop `redirectUri` is marked as required in `ConnectionStatusCard`, but its value is `null`.`

Connection: Make redirectUri not be required in ConnectionStatusCard

---

projects/plugins/jetpack/changelog/fix-scan-warning
projects/plugins/jetpack/modules/scan/class-admin-sidebar-link.php

Fixes 7219-gh-Automattic/jpop-issues
* Fixes a warning that happens when a non admin users open wp-admin:
```
[19-Jan-2022 03:29:36 UTC] PHP Notice:  Undefined index: jetpack in /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/scan/class-admin-sidebar-link.php on line 101
[19-Jan-2022 03:29:36 UTC] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/scan/class-admin-sidebar-link.php on line 101
```
No.
* Connect your jetpack and make sure that the scan submenu is showing.
* Create a non admin user.
* Open wp-admin using that user and verify your logs to make sure the warning doesn't occur.

Fix warning on Scan module

---

projects/plugins/backup/changelog/fix-backup-connect-properties
projects/plugins/backup/src/js/components/Admin.js
projects/plugins/backup/src/js/hooks/useConnection.js

Fixes #22380
* Changed the default for prices from null to 0
No
* On the local environment, run jetpack watch plugins/backup standing on master
* Visit the connection screen for Backup, disconnect first if necessary
* Confirm you do not see warnings related to `priceBefore` and `priceAfter`
* Connect, and without a plan, visit the Backup page
* Confirm again no warnings in the dev console related to `priceBefore` and `priceAfter`

[Plugin] Backup: Updated default of prices from null to 0

---

projects/packages/my-jetpack/changelog/remove-plans-endpoints-my-jetpack
projects/packages/my-jetpack/src/class-initializer.php

Removes an endpoint that was replaced by the purchases endpoint
Fixes #22430
* Removes registration of `my-jetpack/v1/site/plans` as an endpoint.
none
None

My Jetpack: Remove superseded endpoint my-jetpack/v1/site/plans

---

projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/_inc/components/plans-section/style.module.scss
projects/packages/my-jetpack/changelog/update-css-module-plans-section

Introducess css module for the Plans Section component
Follow-up to #22345
* Adds styles.module.scss file under `components/plans-section`.
no
* Build with `jetpack build packages/my-jetpack`.
* Have Jetpack Backup and a plan for it (either Upgrade to Security or Backup)
* Checkout the My Jetpack page.
* Confirm the styles look as before

My Jetpack: Update Plans section component to use css module

---

.github/files/build-all-projects.sh

Let's attempt, when building a production version of Jetpack, to copy some files to their previous location pre-10.5.
﻿Internal references:
- p9dueE-4fc-p2
- p1642671449497200-slack-CBG1CP4EN
* No
* Click on the Build check below, and in the summary view click to download "jetpack-build"
* Uncompress the downloaded archive, navigate to the Jetpack plugin (`jetpack-production`), and check that the files can be found at the old location (`vendor/automattic/...`)
* Zip just the Jetpack plugin (make sure the folder is named just `jetpack` before zipping).
* Create a new JN site with Jetpack and the WP Rollback plugin.
* SSH into the site, and tail the debug.log.
* Using the WP Rollback plugin, rollback to Jetpack version 10.4
* Connect your site to WordPress.com.
* Go to Plugins > Add New > …

Build: copy files from the new vendor dir to previous location

---

projects/plugins/jetpack/_inc/client/at-a-glance/boost/index.jsx
projects/plugins/jetpack/_inc/client/at-a-glance/crm/index.jsx
projects/plugins/jetpack/_inc/client/components/plugin-dash-item/README.md
projects/plugins/jetpack/_inc/client/components/plugin-dash-item/index.jsx
projects/plugins/jetpack/_inc/client/components/plugin-dash-item/test/component.js
projects/plugins/jetpack/changelog/add-plugin-dash-multi-plugin-support

Currently, the `PluginDashItem` component accepts a single `pluginFile` prop, and checks to see if the provided plugin is installed and active when rendering the dash item's content.
This PR adds support to `PluginDashItem` to accept *multiple* plugin files, and then consider the plugin installed or active if *any one* of the provided plugin files are installed or active.
This is then implemented in the existing use of `PluginDashItem` in `DashBoost` to consider both the release and beta plugins, which have differing paths (`jetpack-boost` and `jetpack-boost-dev` respectively).
This ensures a consistent behaviour from `PluginDashItem` whether the user has the release or beta version of Jetpack Boost installed.
Fixes 1164141197617539-as-1201689448751944
* Converts `PluginDashItem`'s …

Add support for Beta Plugins to PluginDashItem

---

pnpm-lock.yaml
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-analytics/README.md
projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/changelog/add-analytics-to-my-jetpack
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php
projects/plugins/backup/changelog/add-analytics-to-my-jetpack
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/add-analytics-to-my-jetpack
projects/plugins/jetpack/composer.lock

Introduces an `useAnalytics` hook. 
The hook utilizes the connection initial state to `initialize` the jetpack analyticis lib.
* Introduces `my-jetpack/hooks/use-analytics`.
* Adds firing of `jetpack_myjetpack_page_view` event when the My Jetpack page is viewed.
* Adds conditional loading of Tracks Js on the My Jetpack initializer class.
* Adds dependency on `terms-of-service` 
* Adds dependency on `tracking`.
* **The script is only loaded if the User is connected**
Well... yes.
* Checkout this branch...
* Open the browser.
* Connect Jetpack.
* Go to "Jetpack -> My Jetpack", Confirm that the developer console displays the events `jetpack_wpa_click` and `jetpack_myjetpack_page_view`. …

My Jetpack: Add analytics hook

---

projects/plugins/jetpack/changelog/add-markdown-block-align-and-spacing-feature
projects/plugins/jetpack/extensions/blocks/markdown/index.js
projects/plugins/jetpack/extensions/blocks/markdown/renderer.js
projects/plugins/jetpack/extensions/blocks/markdown/save.js
projects/plugins/jetpack/extensions/blocks/markdown/test/__snapshots__/markdown-renderer.js.snap

The proposed change adds Align (Wide & Full Width) and Dimensions (Padding) features to the Markdown block.
Before | After |
| ![Markup on 2022-01-20 at 16:12:13](https://user-images.githubusercontent.com/25105483/150366471-449e098b-7413-4deb-b5cc-77d36350af58.png) | ![Markup on 2022-01-20 at 16:09:17](https://user-images.githubusercontent.com/25105483/150366566-1999d578-a7d0-498e-8e3f-1041898ae593.png) |
This PR is a part of the _Expanding Jetpack Block design tooling for Full Site Editing_ project: pdDOJh-6-p2.
1. Create a new post or a page with the Markdown block
2. There should be a new set of features: Align (in the block toolbar) and Dimensions / Padding (in the block sidebar).
3. Experiment with the new features and observe …

Markdown block: Add Align and Spacing features

---

projects/plugins/jetpack/changelog/add-contact-info-block-color-typography-spacing-features
projects/plugins/jetpack/extensions/blocks/contact-info/index.js

The proposed change adds color, typography and spacing (padding) features to the Contact Info block.
Before | After |
| ![Markup on 2022-01-13 at 14:24:59](https://user-images.githubusercontent.com/25105483/149338638-47728020-7907-4ce9-b562-26deb838b081.png) | ![Markup on 2022-01-13 at 14:26:04](https://user-images.githubusercontent.com/25105483/149338709-38b41f21-ef4b-4b6d-9015-8b8a1b2b6838.png) |
This PR is a part of the _Expanding Jetpack Block design tooling for Full Site Editing_ project: pdDOJh-6-p2.
1. Create a new post or a page with the Contact Info block
2. There should be a new set of features (colors, typography and spacing) in the block sidebar.
3. Experiment with the new features and observe whether the change applies …

Contact Info block: Add color, typography and spacing features

---

tools/js-test-runner/jest-config/default.config.js

The coverage report started taking an extra 10 minutes after
packages/my-jetpack added JS tests because it was reporting coverage for
all of WordPress that was brought in via WorDBless. Exclude that by
default.
Also exclude the `jetpack_vendor/` directory from
packages/composer-plugin for good measure.
None
No
* In the "Tests / Code coverage" job, check that the JS tests for packages/my-jetpack take closer to 5 seconds than 580.
* :heavy_check_mark: [5.738s](https://github.com/Automattic/jetpack/runs/4925842664?check_suite_focus=true#step:9:4180)

js-test-runner: Add WorDBless dir to jest collectCoverageFrom

---

.github/files/build-all-projects.sh

* Adds plugins/backup to have vendor files copied to avoid conflicts when upgrading from 1.0.1 to 1.1.0
Internal references:
p9dueE-4fc-p2
p1642671449497200-slack-CBG1CP4EN
No.
* Click on the Build check below, and in the summary view click to download "jetpack-build"
* Uncompress the downloaded archive, navigate to the Jetpack Backup plugin (jetpack-backup-plugin), and check that the files can be found at the old location (vendor/automattic/...)
* Zip just the Jetpack Backup plugin (make sure the folder is named just jetpack-backup before zipping).
* Create a new JN site without any plugins
* SSH into the site, and tail the debug.log.
* Go to Plugins > Add New > Search for Jetpack Backup and install from .org (v1.0.1) - Activate
* Connect your site to WordPress.com from Jetpack > Backup …

Build - Add plugins/backup to previous vendor copy logic

---

projects/plugins/jetpack/changelog/fusion-sync-yoavf-r238742-wpcom-1642953249
projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php

Fixes #22460.
This commit syncs r238742-wpcom.
In #22414, a couple of the changes switched to strict equality when the actual data compared had different types.
This meant that if a legacy widget was saved with visibility on a specific page, it would never show on that page (or any other page).
This was documented in https://github.com/Automattic/wp-calypso/issues/60352 and https://github.com/Automattic/wp-calypso/issues/60355
* Fixes regression by casting the page ID data from the visiblity rule to int
* No
* Add a legacy widget to a theme with a widget area
* Set the widget to be visible on a specific page
* Update
* Visit that page, widget should be visible

widget-conditions: fix regression introduced in #22414

---

pnpm-lock.yaml
projects/js-packages/config/changelog/add-missing-nyc-deps
projects/js-packages/config/package.json
projects/js-packages/licensing/changelog/add-missing-nyc-deps
projects/js-packages/licensing/package.json
projects/js-packages/partner-coupon/changelog/add-missing-nyc-deps
projects/js-packages/partner-coupon/package.json
projects/js-packages/webpack-config/changelog/add-missing-nyc-deps
projects/js-packages/webpack-config/package.json
tools/cli/commands/generate.js
tools/cli/package.json

When creating a JS package, the CLI is pre-filling the test-coverage
script with a call to `nyc`. But it wasn't also pre-adding a dependency
on nyc, resulting in coverage not working for several packages.
Also, add the missing dep to those packages.
None
No
* Check that the coverage job isn't failing to run for these packages (e.g. not [this](https://github.com/Automattic/jetpack/runs/4923504024?check_suite_focus=true#step:9:501)).
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/4926248885?check_suite_focus=true#step:9:505
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/4926248885?check_suite_focus=true#step:9:1126
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/4926248885?check_suite_focus=true#step:9:1212
* :heavy_check_mark: …

cli: Add missing `nyc` dep when creating JS packages

---

projects/js-packages/i18n-loader-webpack-plugin/README.md
projects/js-packages/i18n-loader-webpack-plugin/changelog/update-move-i18n-loader-pkg-path-into-assets
projects/js-packages/i18n-loader-webpack-plugin/src/I18nLoaderPlugin.js
projects/packages/assets/changelog/update-move-i18n-loader-pkg-path-into-assets
projects/packages/assets/src/class-assets.php
projects/packages/assets/src/js/i18n-loader.js
projects/packages/assets/tests/js/i18n-loader.test.js
projects/packages/assets/tests/php/test-assets-files/i18n-map.php
projects/packages/assets/tests/php/test-assets.php
projects/packages/composer-plugin/changelog/update-move-i18n-loader-pkg-path-into-assets
projects/packages/composer-plugin/composer.json
projects/packages/composer-plugin/src/class-plugin.php
projects/plugins/backup/changelog/update-move-i18n-loader-pkg-path-into-assets
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/update-move-i18n-loader-pkg-path-into-assets
projects/plugins/boost/composer.json
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/update-move-i18n-loader-pkg-path-into-assets
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

Instead of having to have every package know where it will end up in the
plugin, we can have jetpack-composer-plugin pass the paths to
jetpack-assets and let the latter's JS prepend that when hashing the
script path.
This is an alternative to #22407.
p1642603817021400/1639739679.124300-slack-C82FZ5T4G
No
* Create an updated language pack (e.g. in the docker env with /var/scripts/fakepot.sh) and try Instant Search.

lazy js i18n: Move package→plugin path mapping into Assets

---

projects/packages/my-jetpack/changelog/update-my-jetpack-check-connectivity-when-requesting
projects/packages/my-jetpack/src/class-rest-purchases.php

Fixes #
* My Jetpack: check user connectivity before hitting wpcom side
* With a user connected, confirm no issues in there
* Disconnect the user
**Without these changes**,
* App got broken. White screen.
* Confirm you get an error in the client. 
* Check the `site/purchases` endpoint. Get an error without error status:
** With these changes**
* Confirm you see the error in the dev console
* App is not broken. You still see the products list and My Plan section
* You'd like to take a look at the network tab, too.

My Jetpack: check user connectivity before hitting wpcom side

---

projects/js-packages/connection/changelog/fix-proptypes-connected-plugins
projects/js-packages/connection/components/connected-plugins/index.jsx

Fixes #22479
* Fixes typo in ConnectedPlugins propTypes.
none
1. On a connected site, visit the My Jetpack page
2. Run `jetpack build packages/my-jetpack`.
2. build with 
1. Have `SCRIPT_DEBUG` on as a constant in wp-config.php
2. open the browser console
2. Attempt to disconnect site by clicking Disconnect from the Connection Status card
3. Confirm you don't see an error like this:
```
Warning: Component ConnectedPlugins declared PropTypes instead of propTypes. Did you misspell the property assignment?
in StepDisconnect (created by DisconnectDialog)
```

Connection: Fix misspelling of propTypes in ConnectedPlugins component from connection js-package

---

projects/plugins/jetpack/changelog/add-testing-list-106
projects/plugins/jetpack/to-test.md

* Testing list for the upcoming version of Jetpack.
* N/A
* No

Jetpack: add testing list for 10.6

---

.github/files/generate-ci-matrix.php

Band-aids issue with PHP unit tests cancelling at 15 minutes.
* Bump to 20 min
p1643127805171900-slack-C01U2KGS2PQ
No.
* Do the unit tests complete?
*

Bump PHP test timeout to 20 min

---

projects/plugins/jetpack/changelog/try-reduce-sync-search-test-data
projects/plugins/jetpack/tests/php/sync/class-test-jetpack-sync-search.php

This is a follow up to #19674 . This is a pretty crude change, designed to show at least one way we can speed up the tests from 9 minutes to 11 seconds. I realize that this might be too harsh for this test, since we may want to be sure that every allowed key is tested with the filters/include/exclude lists. Let me know what you think of that approach. Maybe there is a different way how we can narrow down the data set instead of doing a random selection?
* This change reduces the data set that the tests run on.
* N/A
* no
* Run the Sync Search test suite from the Jetpack project folder: `WP_DEVELOP_DIR=/home/zinigor/workspace/wordpress-develop ./vendor/bin/phpunit --filter=Test_Jetpack_Sync_Search`
* Observe that tests take more than 8 minutes.
* Use this PR.
* Observe that tests run in …

Reduced Sync Search test data sample.

---

tools/e2e-commons/bin/e2e-env.sh

The new Twenty Twenty-Two theme breaks some of the e2e tests. 
This is a quick fix, by activating twentytwentyone in the setup phase.
A more complex solution that supports any theme should be considered.
p1643195257206500-slack-CBG1CP4EN
no
- E2E tests pass in CI?

E2E tests: force theme to fix broken tests

---

composer.lock
pnpm-lock.yaml
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/style.scss
projects/packages/my-jetpack/_inc/hooks/use-notice/Readme.md
projects/packages/my-jetpack/_inc/hooks/use-notice/index.js
projects/packages/my-jetpack/_inc/state/actions.js
projects/packages/my-jetpack/_inc/state/reducers.js
projects/packages/my-jetpack/_inc/state/selectors.js
projects/packages/my-jetpack/changelog/update-my-jetpack-implement-global-error
projects/packages/my-jetpack/package.json

This PR implement the first approach to deal with global notice. For this purpose:
* Add global notice to redux store
* Add custom hooks
* Connect primary component to show errors in the UI
* My Jetpack: Implement first approach for global notice
* My Jetpack Implement first approach for global notice
No
**Dispatching actions:**
* Dispatch `my-jetpack` actions to show/clean global notice:
```
wp.data.dispatch( 'my-jetpack' ).setGlobalNotice( 'Testing an info notice', { status: 'info' } )
```
```
wp.data.dispatch( 'my-jetpack' ).setGlobalNotice( 'This is an error', { status: 'error' } )
```
https://user-images.githubusercontent.com/77539/150998618-cac7687d-9132-47fb-a876-d9909e21a69c.mov
**Disconnect the user**
Once you disconnect the …

My Jetpack: Implement first approach for global notice

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/_inc/components/product-cards-section/crm-card.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-plugin-absent-status

Fixes #
This PR updates the status name when the status of the products is _plugin absent_. If fixes validation prop issue that happens since the status provided by the server is not the same that the expected values by the client: `plugin_absent` vs `absent`
* Go to my jetpack dashboard. You should see the following error:
```
Warning: Failed prop type: Invalid prop `status` of value `plugin_absent` supplied to `ProductCard`,
expected one of ["active","inactive","error","absent"].
```
* Confirm with these changes the issue is addressed.

My Jetpack: Update plugin absent status consistently

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/changelog/add-tracks-events-my-jetpack-product-card
projects/packages/my-jetpack/jest.setup.js

Adds tracking for clicks on activate/deactivate links for product cards.
* Introduces functions `activateHandler` and `deactivateHandler` that will call the passed props `onActivate`, and `onDeactivate` after firing Tracks events.
* Renames the prop that `renderActionButton` recevies from 'onActivate` to 'activateHandler'
Introduces 2 new events:
*  `jetpack_myjetpack_product_card_activate_click` fired when the user clicks on a product card activate link
* `jetpack_myjetpack_product_card_activate_click` fired when the user clicks on a product card deactivate link
* Open the developer console, execute …

My Jetpack: Fire Tracks events for product activation and deactivation clicks

---

projects/plugins/jetpack/_inc/client/at-a-glance/index.jsx
projects/plugins/jetpack/changelog/update-render-pair-logic-at-a-glance-jetpack

Updates an imperative logic for rendering pairs of cards inside sections
Fixes annoying warning of missing `key` prop when visiting the Dashboard.
We were looping through items before rendering them and React demanded unique key props. 
* Replaces logic of gathering `pair` for rendering afterwards with `renderPairs`. Introduces local Section component and we use it more declaratively
no
* Check this branch out.
* Enable SCRIPT_DEBUG
* build Jetpack with `jetpack build plugins/jetpack`
* Visit the admin page .
* Open the console
* Confirm you no longer see the warning about lack of unique key in AtAGlance component.
* Confirm that the sections with their cards render the same.

Dashboard: Replace renderPairs logic for a more declarative approach

---

projects/packages/identity-crisis/CHANGELOG.md
projects/packages/identity-crisis/changelog/2022-01-27-11-15-04-994925
projects/packages/identity-crisis/changelog/add-dependency-analysis-in-cli
projects/packages/identity-crisis/changelog/add-idc-safe-mode-bar
projects/packages/identity-crisis/package.json
projects/packages/identity-crisis/src/class-identity-crisis.php

Release packages/identity-crisis v0.7
n/a
No.

Release packages/identity-crisis v0.7

---

projects/plugins/jetpack/changelog/update-my-community-widget-deprecate
projects/plugins/jetpack/modules/widgets/my-community.php

This commit hides the My Community widget from the block inserter and Legacy widget block drop-down menu.
**Before**
Block inserter  |  Legacy Widget block
**After**
Block inserter  |  Legacy Widget block
The My Community widget on WPCOM will have a dedicated deprecation patch as the My Community widget in Jetpack and My Community widget on WPCOM are not synced.
- Add filter to deprecate the My Community widget
- this PR is part of the Legacy Widgets Migration project: pdf5j4-4C-p2
- more info can be found in pdf5j4-7f-p2
1. Navigate to Customizer → Widgets
2. Add the Legacy block and take a look at the dropdown menu. The My Community widget should not be …

My Community widget: widget deprecation

---

projects/plugins/jetpack/_inc/client/components/apps-badge/index.jsx
projects/plugins/jetpack/changelog/fix-card-badge-required-utm_source

Removes `required` requirement for prop `utm_source`
Confirned with @IanRamosC that it does not need to be required.
Fixes #22516
no
* Check this branch out.
* Enable SCRIPT_DEBUG
* build Jetpack  with `jetpack build plugins/jetpack`.
* Visit the admin page . 
* Open the console
* Confirm you only see this red warning:
*  About usage of `javascript:void(0)` in `href` props for an `a`. Will handle this on another PR

Dashboard: Update Apps Badge to not require utm_source prop

---

projects/packages/my-jetpack/changelog/fix-breaking-unit-tests
projects/packages/my-jetpack/jest.setup.js

Fix failing unit tests in packages/my-jetpack - myJetpackRest is undefined.
Added a  basic mock object on the window to allow the test to proceed - and passes as before.
n/a
No
Change to the `projects/packages/my-jetpack` from the project root and run `pnpm t`
Tests should now pass

Fix breaking unit tests

---

projects/packages/my-jetpack/_inc/components/connections-section/index.jsx
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/_inc/hooks/use-my-jetpack-connection/index.js
projects/packages/my-jetpack/_inc/hooks/use-notice/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-handle-when-no-site-connected

This PR handles the issue when there is no connection to wpcom, performing a client redirect to the main Jetpack dashboard. Currently, under this situation, it produces a Fatal Error showing a classical white screen page.
Fixes https://github.com/Automattic/jetpack/issues/22481
* My Jetpack: Handle when site is not connected
No
* Disconnect the site. You can use the Jetpack Debug plugin -> `Clean blog token `
* Confirm you get a white screen
* Confirm the errors in the console
* With these changes, confirm the there is no errors in the console
* The client performs a redirect to the Jetpack dashboard

My Jetpack: Handle when site is not connected

---

projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-tweak-status-cmp-dims

It tweaks the status component of the Product card, aligning it with the action button:
Fixes #
* My Jetpack: tweak dims of the Product card status
No
* Go to My jetpack dashboard
before | after
-------|------
*

My Jetpack: tweak dims of the Product card status

---

projects/packages/my-jetpack/_inc/components/product-card/stories/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-stories-for-product-card

The stories for ProductCard are broken since they expect a connected user to when trying to track events. To fix this issue, the PR defines a fake empty object, and also tweaks the `useAnalitics()` hook, checking the data before initializing the analytics. 
Fixes #
* My Jetpack: Fix stories for ProductCard component
No
* Start js-packages storybook
```
```
```
pnpm install & pnpm storybook:dev
```
*before*
*after*
* Confirm it keeps tracking event, when:
* My Jetpack dashboard is rendered
* Activating/Deactivating a product

My Jetpack: Fix stories for ProductCard component

---

projects/packages/my-jetpack/_inc/components/product-cards-section/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-product-cards-gap

Fixing the gap between the `ProductCard` components into `ProductCardsSection`
* Update `horizontalSpacing` and `horizontalGap` in `ProductCardsSection`.
No.
* Build My Jetpack (`jetpack build packages/my-jetpack`)
* Open `My Jetpack` page.
* Check the gap between the `ProductCard` components

My Jetpack: Fix gap between product cards

---

projects/plugins/jetpack/changelog/add-email-share-amp-support
projects/plugins/jetpack/modules/sharedaddy/amp-sharing.css
projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php

See #9730
This PR adds an AMP-compatible version of the email share button, to go with the other supported sharing services. 
* N/A.
* No.
* If it's not already running one, switch your test site to an AMP compatible theme -- this can include any of the default themes.
* If your site isn't already running it, install and activate the [AMP plugin](https://wordpress.org/plugins/amp/).
* Navigate to WP Admin > AMP; switch your site to 'Standard' under 'Template Mode', and click Save.
* If your site isn't already running it, install and activate the [Akismet plugin](https://wordpress.org/plugins/akismet/); this is required to add the Email Share button to your site. 
* Navigate to WP Admin > Jetpack > Settings > Sharing, and enable sharing on your site; click 'Configure Share buttons', and …

Sharing: Add an AMP-compatible version of the email share button

---

pnpm-lock.yaml
projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/hooks/use-route-blocker/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-routes
projects/packages/my-jetpack/package.json

Implement the route system inside My Jetpack, with a hook to block direct navigation to the component.
* Setup `HashRouter` and `Routes`.
* Include `useRouteBlocker` that blocks direct route access for some component, it will only be allowed if coming from other router.
p1643660572899069-slack-C02TQF5VAJD
No.
* Goes into `MyJetpackScreen` component
* Insert a `Link` component from `react-router-dom` any place, and set the `to` for `/new` route.
* Build `My Jetpack` (`jetpack build packages/my-jetpack`).
* Navigate to `My Jetpack`.
* Click in the `Link`.
* It should load the `New` screen.
* Go back and try to go forward.
* It will redirect you back to the `My Jetpack` screen.
* Click on the link again.
* Refresh the page.
* It will redirect you back to the `My Jetpack` screen. …

My Jetpack: Add react-router for route handling

---

projects/packages/my-jetpack/changelog/update-my-jetpack-connect-backup-product-class
projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-boost.php
projects/packages/my-jetpack/src/products/class-crm.php
projects/packages/my-jetpack/src/products/class-product.php

This PR:
* Connects the Backup product class to the Product class when providing product info e5828c6615d0b6387e0fb7b7f297f628382a9daa
* And also adds the `long_description` and `features` fields.
* 
Fixes #
* My Jetpack: connect Backup product class with Product class. Add long_description and features fields.
p1643719015043149-slack-
No
* My Jetpack dashboard
* Take a look at the Products Data. You can expose it in the dev console:
```
myJetpackInitialState.products.items.backup
```
* Confirm you see the backup product detail, wth the long description and features files populated.

My Jetpack: My Jetpack: connect Backup product class with Product class

---

tools/cli/commands/build.js

When multiple projects are being built, build them in dependency order
(i.e. each project's dependencies are build before the project is).
If the new `--deps` option is specified, include all dependencies of the
specified projects in the build.
PT: p9dueE-4dJ-p2
No
* `jetpack build plugins/jetpack packages/assets` should build Assets first.
* `jetpack build --deps plugins/jetpack` should build all the dependencies of Jetpack before building Jetpack.
* `jetpack build` should ask if you want to build dependencies after asking which project you want to build.
* `jetpack build --deps` and `jetpack build --no-deps` should both prompt for a project but avoid the extra question.

cli: Build in dependency order, optionally with dependencies

---

projects/js-packages/storybook/changelog/update-storybook-add-jetpack-dashboard-bg-color
projects/js-packages/storybook/package.json
projects/js-packages/storybook/storybook/preview.js

This PR adds the Jetpack Dashboard background color, along with Light and Dark ones.
* Storybook: Add 'Jetpack Dashboard' background color
```bash
```
```bash
```
* Open http://localhost:50240
* Take a look at the background colors

Storybook: Add 'Jetpack Dashboard' background color

---

projects/packages/my-jetpack/_inc/state/resolvers.js
projects/packages/my-jetpack/changelog/udpate-my-jetpack-avoid-product-resolver

This PR avoids performing a request for each product. We consider it unneeded since the products list is already populated and exposed to the client via the `myJetpackInitialState` global var.
Fixes https://github.com/Automattic/jetpack/issues/22598
* My Jetpack: avoid performing a request for each product
No
* Go to my Jetpack dashboard
* Confirm the client does not perform additional requests for each product. For instance:
* Confirm the app keeps working as expected. Activate/Deactivate `Boost` and `VideoPress` for instance.
* Confirm the activation state is consistent after a hard-refresh

My Jetpack: avoid performing a request for each product

---

projects/packages/my-jetpack/changelog/add-user-connection-requirement
projects/packages/my-jetpack/src/class-rest-products.php
projects/packages/my-jetpack/src/products/class-boost.php
projects/packages/my-jetpack/src/products/class-crm.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/tests/php/test-products-rest.php

* add user connection requirement to product info
* Improve error codes on REST API
N/A
No
* Open the console and check `myJetpackInitialState` global var
* Check that the products include a `requires_user_connection` key
* Try to activate Scan and see that the response code is 400

add user connection requirement to product info

---

projects/plugins/vaultpress/.gitattributes
projects/plugins/vaultpress/changelog/update-vaultpress-excluded-file

* Avoid shipping a file that is not needed on production installs.
* N/A
* No

VaultPress: do not ship PHPCS config file in production

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/changelog/add-record-event-for-on-add

Adds tracking for clicks on add links for product cards.
* Introduces function `addHandler`  that will call the passed prop `onAdd` after firing Tracks event.
Introduces 1 new event:
*  `jetpack_myjetpack_product_card_add_click` fired when the user clicks on a product card add link
* Go to "Jetpack -> My Jetpack", Confirm that the developer console displays the events `jetpack_myjetpack_product_card_add_click` ` when clicking such link from the CRM product card for example.

My Jetpack: Fire Tracks events for click on product add link

---

projects/packages/admin-ui/.phpcs.dir.xml
projects/packages/admin-ui/changelog/add-anti-spam-my-jetpack
projects/packages/admin-ui/composer.json
projects/packages/admin-ui/src/class-admin-menu.php
projects/packages/my-jetpack/changelog/add-anti-spam-my-jetpack
projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/plugins/backup/changelog/add-anti-spam-my-jetpack
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/add-anti-spam-my-jetpack
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/add-anti-spam-my-jetpack
projects/plugins/jetpack/composer.lock

This PR does 2 things
1. It adds the Anti Spam product associated to the akismet plugin into My Jetpack
2. Handles the Akismet menu item when used alongside other stand-alone plugins -> When Jetpack plugin is present, Akismet menu item is moved under the Jetpack top level menu, but if Akismet is active alongside other stand-alone plugins, it wasn't. This PR changes the Admin_Menu class to handle this.
* Creates the Anti Spam product class
* Makes Admin UI package handle the askismet menu when Jetpack plugin is not present
N/A
No
* Activate a stand-alone plugin like boost or backup (and NOT Jetpack)
* Activate Anti Spam
* Confirm Akismet plugin was activated
* Confirm Anti-Spam menu item was added to the Jetpack menu and it links to the Akismet admin page
* Activate …

Add anti spam into my jetpack

---

.github/files/create-e2e-projects-matrix.sh

*  After merging #22318 the scheduled e2e test runs are failing. Apparently `list-changed-projects.sh` only supports GITHUB_EVENT_NAME pull_request or push, resulting in an `unsupported GITHUB_EVENT_NAME` error for scheduled runs.
* With this fix `list-changed-projects.sh` is only called for pull_request or push events
n/a
no
- Run `./.github/files/create-e2e-projects-matrix.sh` with different GITHUB_EVENT_NAME and CRON values

E2E tests: fix unsupported GITHUB_EVENT_NAME for schedule runs

---

projects/packages/waf/.gitattributes
projects/packages/waf/changelog/update-ignored-config-waf

* We do not need that file in production builds.
* N/A
* No

WAF: do not ship .phpcs.dir.xml in production build

---

projects/packages/my-jetpack/_inc/state/actions.js
projects/packages/my-jetpack/_inc/state/reducers.js
projects/packages/my-jetpack/changelog/fix-set-product-status-reducer-my-jetpack

We were attempting to destructure a string value (`status`)
...Thus attempting to upate the state like this: 
Fixes SET_PRODUCT_STATUS action
* Removes destructuring operator. 
no
Just confirm it makes sense

My Jetpack: Fix reducer for SET_PRODUCT_STATUS

---

projects/packages/my-jetpack/changelog/update-my-jetpack-add-pricing-harcoded-product-data
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-boost.php
projects/packages/my-jetpack/src/products/class-crm.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-videopress.php
projects/packages/my-jetpack/tests/php/class-broken-product.php

This PR exposes the pricing data for each product, adding the `get_pricing_for_ui()` static method to the Product class. We can define the way that we are going to get and propagate these data. Hardcoding vs pulling from wpcom.
The data provided should be enough to show the following price section of the Product card:
Fixes #
* My Jetpack: expose pricing product data
* Go to My Jetpack page
* Check the Product items taking a look at the items:
```
myJetpackInitialState.products.items
```

My Jetpack: expose pricing product data

---

.github/renovate.json
projects/packages/plans/.gitattributes
projects/packages/plans/.gitignore
projects/packages/plans/CHANGELOG.md
projects/packages/plans/README.md
projects/packages/plans/changelog/extract-jetpack-plans
projects/packages/plans/composer.json
projects/packages/plans/package.json
projects/packages/plans/phpunit.xml.dist
projects/packages/plans/src/class-current-plan.php
projects/packages/plans/src/class-plans.php
projects/packages/plans/src/example.php
projects/packages/plans/tests/php/bootstrap.php
projects/packages/plans/tests/php/test-current-plan.php

This PR creates a new package with functionality to fetch Plans data from WPCOM.
For now, it copies the classes from the Jetpack plugin. Usage in the Jetpack plugin will be replaced in subsequent PRs as this must be synced with changes in WPCOM as well.
We need this to move the work on the My Jetpack feature.
* Create new Plans package
N/A
No
* Nothing for now, the package is not used
* Let's see if the tests pass

Create new Plans package

---

projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-open-boost-interstitial

This PR register a new `/add-boost` route tied to the `<BoostInterstitial />` component. Also, Adds a handler to the `onAdd()` BoostCard property to lead the user to the interstitial page by clicking on the `Add Boost` link
Note: We are going to add the `Go back link` in a follow-up.
Fixes https://github.com/Automattic/jetpack/issues/22655
* My Jetpack: Connect Boost card with the interstitial page via /add-boost root
No
* Set up in order to do not have `Boost` available in your dashboard. You can hardcode the [get_status()](https://github.com/Automattic/jetpack/blob/56b5e9d2be8d4cfd0f2cb3c716308e74abb9af76/projects/packages/my-jetpack/src/products/class-product.php#L149-L158) method forcing this `plugin_absent` status.
* Confirm you see the interstitial page by …

My Jetpack: Connect Boost card with the interstitial

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-fix-tracking-events-handler

My Jetpack: useCallback for track functions that are bound to onEvents
Fixes https://github.com/Automattic/jetpack/issues/22660
* My Jetpack: useCallback for track functions that are bound to onEvents
Yes
* Check events are properly working after these changes
```
localStorage.setItem( 'debug', 'dops:analytics*' );
```
* When the My Jetpack shows up
* Activating/Deactivating a product

My Jetpack: useCallback for track functions that are bound to onEvents

---

projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/add-event-interstitial-my-jetpack

Adds tracking for views on product interstitial pages
* Introduces side effect for firing `jetpack_myjetpack_product_interstitial_view`.
Introduces 1 new event:
*  `jetpack_myjetpack_product_interstitial_view` fired when the user views the interstitial page
* Go to this patch `wp-admin/admin.php?page=my-jetpack#/add-boost`. |
* Confirm that the developer console displays the events `jetpack_myjetpack_product_interstitial_view`

My Jetpack: Fire Tracks event when showing product Interstitial page

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/add-my-jetpack-tracks-event-interstitial-click

Adds tracking for click on product interstitial pages CTA buttons
* Introduces firing of  `jetpack_myjetpack_product_interstitial_add_link_click`.
Introduces 1 new event:
*  `jetpack_myjetpack_product_interstitial_add_link_click` fired when the user views the interstitial page
* Go to this patch `wp-admin/admin.php?page=my-jetpack#/add-boost`. 
* Click the Add... button
* Confirm that the developer console displays the events `jetpack_myjetpack_product_interstitial_add_link_click`

My Jetpack: Fire Tracks event when clicking CTA button on product Interstitial page

---

projects/plugins/jetpack/changelog/update-internet-defense-league-widget-deprecate
projects/plugins/jetpack/modules/widgets/internet-defense-league.php

The proposed change hides the _Internet Defense League_ widget from the block inserter and _Legacy widget_ block drop-down menu.
**Before**
Block inserter  |  Legacy Widget block
**After**
Block inserter  |  Legacy Widget block
- Add filter to deprecate the _Internet Defense League_ widget
WPCOM version of this widget is out of sync with the Jetpack version and will be deprecated in a related patch: D74186-code.
- this PR is part of the Legacy Widgets Migration project: pdf5j4-4C-p2
- more info can be found in pdf5j4-7f-p2
1. Navigate to Customizer → Widgets
2. Add the _Legacy widget_ block and take a look at the dropdown menu. The _Internet Defense League_ …

Internet Defense League widget: Widget deprecation

---

projects/packages/plans/changelog/update-plans-mirror-repo
projects/packages/plans/composer.json
projects/packages/plans/src/class-current-plan.php

Follow-up from #22650
﻿* [x] Plans: update composer info to support mirror repo.
* N/A
* No
* Not much to test here since the package isn't being used yet.

Plans: update to support mirror repo.

---

projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-gather.php
projects/plugins/jetpack/changelog/update-twitter-unroll-endpoint

﻿Until now, the endpoint was available to anyone, and one could pass any Twitter Thread to that endpoint to make a blog-authenticated request to WordPress.com, and then, in turn, an authenticated request to the Twitter API using our app credentials.
Here is an example:
https://jeremy.hu/wp-json/wpcom/v2/tweetstorm/gather?url=https://twitter.com/KieranBinchy/status/1488812175372267526
That endpoint is currently used in the block editor (so only by folks with contributing capabilities on a given site) to "unroll" a Twitter Thread, i.e. pull all tweets from a thread based off a single tweet.
I think it would be fine to limit that endpoint to contributors.
- This merges r239582-wpcom from WordPress.com (D74346-code).
- Related post: p3btAN-1Fc-p2
* No
* Paste in the …

Twitter Gather: make endpoint restricted to contributors

---

projects/packages/my-jetpack/changelog/add-my_jetpack_has_plan
projects/packages/my-jetpack/changelog/add-my_jetpack_has_plan#2
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/src/products/class-search.php
projects/plugins/backup/changelog/add-my_jetpack_has_plan
projects/plugins/backup/changelog/add-my_jetpack_has_plan#2
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/add-my_jetpack_has_plan
projects/plugins/jetpack/changelog/add-my_jetpack_has_plan#2
projects/plugins/jetpack/composer.lock

This PR starts to check whether the site's current plan (or purchase) supports the product.
The first product we are checking is "Search", by using the search package.
* Add has_required_plan to product info and implement it in Search
N/A
* Inspect the global `myJetpackInitialState` var
* Verify that all products have `has_required_plan` equals `true` except from Search
* Buy a plan or product that include Search
* Check again and verify that Search is now also `true`

Add has_required_plan to product info and implement it in Search

---

.phpcs.xml.dist
projects/plugins/jetpack/changelog/update-phpcs-remove-global-exemption
projects/plugins/jetpack/extensions/blocks/podcast-player/templates/playlist-track.php
projects/plugins/jetpack/extensions/blocks/podcast-player/templates/podcast-header-title.php
projects/plugins/jetpack/extensions/blocks/podcast-player/templates/podcast-header.php
projects/plugins/jetpack/extensions/blocks/podcast-player/templates/podcast-title.php

The Jetpack ruleset is not used on WP.com, so our rule excluding the podcast template files from the undeclared variable sniff does not apply. We can remove that to disable by file so it'll work on WP.com.
* Moves PHPCS ignore.
n/a
No.
* CI happy?

PHPCS: Ignore rule by file for WP.com

---

projects/packages/my-jetpack/changelog/add-scan-and-backup-purchase-check
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php

* Add plan verification for backup and scan in the My Jetpack package
N/A
No
* check the value of `myJetpackInitialState` global var
* verify that Backup and Scan have `has_required_plan` as false
* Buy a backup or scan plan (or security bundle)
* check the variable again and verify the product you bought is now true

Add plan verification for backup and scan

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-use-pricing-data

This PR implements Free price for the Boost product.
Fixes #
* My Jetpack: Implement Free price for Boost product
No
* Go to My Jetpack / Boost interstitial 
`https://<your-testing-site>/wp-admin/admin.php?page=my-jetpack#/add-boost`
* Confirm visually you see the Free text there
**Using Storybook**
* Build My Jetpack
```bash
> jetpack build packages/my-jetpack
```
```bash
```
```bash
```
Backup | Boost
-----|------

My Jetpack: Implement Free price for Boost product

---

projects/plugins/jetpack/changelog/update-premium-content-transformations
projects/plugins/jetpack/extensions/blocks/premium-content/index.js

Premium content blocks currently offer a transformation from any source
block, including existing premium content blocks. When the user tries to
transform a premium content block to a premium content block it is
detected and nothing happens.
This change doesn't offer the transformation in the first place, which
reduces confusion and menu clutter.
Partly fixes #22423
no
1. Apply patch
2. Build extension with `pnpm run build-extensions` from `projects/plugins/jetpack/extensions`
3. Open the add new post screen
4. Add a premium content block
5. Click the premium content block (not it's children)
6. See it doesn't offer a transformation to a premium content block
Before | After
-------|------

Premium Content Block: Don't offer transform to self

---

projects/plugins/jetpack/_inc/client/my-plan/my-plan-header/index.js
projects/plugins/jetpack/changelog/update-always-show-activate-a-product

Fixes 1164141197617539-as-1201757324416015/f
* Update the logic for "Activate a Product" button in "My Plan" to be always visible.
* Previously it was visible only if the user had at least one detached purchase.
pbNhbs-1dQ-p2
No
* Ensure that your WPCOM account doesn't have any detached Jetpack purchases
* Boot up this PR and fire it up
* Go to wp-admin > Jetpack > My Plan
* Confirm that "Activate a Product" button is visible
* Now add a detached license to your WPCOM account
* To do that, goto to [cloud.jetpack.com/pricing](https://cloud.jetpack.com/pricing) and purchase any plan and don't attach it to any site.
* Now goto My Plan page again
* Confirm that you see the notice above the navigation about an available product license key.
* Confirm that "Activate a Product" button is visible …

Always show the Activate a Product button

---

projects/plugins/jetpack/changelog/rm-duplicate-docblock-related-posts
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php

Fixes #
https://github.com/Automattic/jetpack/pull/22270#issuecomment-1024368342
* Removed duplicate `jetpack_relatedposts_returned_results` filter docblock 
* Updated `$post_id` type to int
No
NA
* Go to '..'
*

Removed duplicate docblock for jetpack_relatedposts_returned_results filter

---

projects/plugins/boost/changelog/e2e-update-eslint-config
projects/plugins/boost/tests/e2e/README.md
projects/plugins/boost/tests/e2e/lib/pages/wp-admin/JetpackBoostPage.js
projects/plugins/jetpack/changelog/e2e-update-eslint-config
projects/plugins/jetpack/tests/e2e/README.md
tools/e2e-commons/.eslintrc.cjs
tools/e2e-commons/README.md
tools/e2e-commons/pnpm-lock.yaml

* Update e2e tests eslint configuration to extend a more relevant set of rules: `plugin:@wordpress/eslint-plugin/esnext` instead of `plugin:@wordpress/eslint-plugin/recommended`.
* Make eslint config also extend `prettier`, to avoid conflicts between eslint formatting rules and prettier. This should disable formatting rules. Prettier runs as a commit hook using the monorepo config. These rules can be in conflict with whatever is configured in e2e tests eslint.
pd5faL-2u-p2
no
* Break a formatting rule in an e2e project file, run eslint on that file => no error/warning is expected. Eslint should not complain about formatting rules. Running prettier on that file should correct the problem.

E2E tests: update eslint config

---

projects/packages/my-jetpack/changelog/update-support-multiple-folders-for-plugin
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-boost.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/tests/php/test-hybrid-product.php
projects/packages/my-jetpack/tests/php/test-product-multiple-filenames.php

Plugins developed in the monorepo might run in different folder names depending on the context.
For example, the backup main file can be:
* `backup/jetpack-backup.php` in the monorepo
* `jetpack-backup/jetpack-backup.php` in the distributed plugin
* `jetpack-backup-dev/jetpack-backup.php` when used via Jetpack Beta plugin
* Support multiple folder for each plugin
N/A
No
Plugin status and activation should work in the local environment, in Jurassic Ninja and in Jurassic Ninja with Jetpack Beta.
Let's try this with Boost.
In your local dev environment:
* Install and connect Backup just so you have access to the My Jetpack page
* Check that Boost is not active
* Activate Boost plugin
* Go back to My Jetpack and see that Boost is now active
Now spin up a Jurassic Ninja site and do the same …

My Jetpack: Support multiple folder for each plugin

---

projects/packages/my-jetpack/_inc/components/plans-section/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/constants.js
projects/packages/my-jetpack/_inc/utils/get-product-checkout-url.js
projects/packages/my-jetpack/changelog/update-my-jetpack-add-product-checkout-link
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/package.json
projects/plugins/backup/changelog/update-my-jetpack-add-product-checkout-link
projects/plugins/backup/composer.json
projects/plugins/backup/composer.lock
projects/plugins/jetpack/changelog/update-my-jetpack-add-product-checkout-link
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock

This PR sets the checkout URL for the `Add Product` button, on the product detail page. The URL is based on the redirects Jetpack system.
* Keep working on the action post buying the product. We'd like to be able to redirect wherever we want, activate the product, and so on.
Fixes https://github.com/Automattic/jetpack/issues/22701
* My Jetpack: Set checkout URL for the Product
No
* Test with a site without the Search product
* You should see the `Add Search` link in the product card
* It should redirect to the checkout page by clicking on the Add product button
* Once you buy the product, it should go back to the My Jetpack dashboard
* Now, you should be able to activate/deactivate the Search product. …

My Jetpack: Set checkout URL for the Product

---

docs/coding-guidelines.md

* Adding working link and explanation to Jetpack unit tests on the [Coding Guidelines markdown page](https://github.com/Automattic/jetpack/blob/master/docs/coding-guidelines.md)
* n/a
* Testing the link to the Jetpack unit tests should work, and the brief explanation should make it clear what you are clicking on

Docs: Adding working link and explanation for Jetpack unit tests to the Coding Guidelines page

---

projects/plugins/jetpack/changelog/update-widget-visibility-site-type-dep
projects/plugins/jetpack/modules/widget-visibility/editor/index.jsx

* ﻿In #22527, I copied over a utility function that we used in the block bundle to use in the Widget visibility bundle. However, starting in #22733, that utility function is now part of an external js package that we can use in the Widget visiblity bundle. Let's do that and save some duplication!
* N/A
* No
* You'll want to test this on wpcom simple as well as Jetpack
* In Jetpack > settings, ensure the Widget visibility feature is active.
* go to Appearance > Widgets
* Add a block
* in the right block sidebar, scroll down and open the "Advanced" panel.
* Add a visibility rule
* in the options, you should see the option to filter by user role, or to check whether the user is logged in or not.
* On WordPress.com, those options should not appear.

Widget Visibility: switch to using shared js package utility

---

projects/js-packages/storybook/changelog/add-storybook-no-sourcemap
projects/js-packages/storybook/storybook/webpack.config.js

It was only generating one small sourcemap anyway, and disabling
sourcemaps speeds up webpack significantly.
PT: p9dueE-4dJ-p2
No
* Is the build faster?
* :heavy_check_mark: It's hard to draw conclusions from a single build, but it looks like it may have saved ~40 seconds.

storybook: Disable generation of sourcemaps

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/changelog/add-manage-link-Tracks-event

Adds tracking for click on product card Manage butons
* Introduces firing of  `jetpack_myjetpack_product_card_manage_click`.
Introduces 1 new event:
*  `jetpack_myjetpack_product_card_manage_click` fired when the user views the interstitial page
* On an active product card
* Click the Manage... button
* Confirm that the developer console displays the events `jetpack_myjetpack_product_card_manage_click`

My Jetpack: Fire Tracks event when clicking Manage button on product card

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/stories/index.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/crm-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/changelog/update-pass-slug-to-product-card

Needed for #22755
* Makes `slug` be a required Prop in ProductCard
* Makes the `useProduct` hook return `slug`
* Makes the specific product components pass slug on <ProductCard/> usage.
* Visit My Jetpack.
* Confirm you see no errors in the console (Due to slug now being a reuquired prop)

My Jetpack: Pass slug prop to ProductCard

---

projects/plugins/jetpack/_inc/client/my-plan/my-plan-card/index.jsx
projects/plugins/jetpack/changelog/fix-broken-image-in-plan-placeholder

Fixes 1164141197617539-as-1200760947306498/f
* Display plan icon only if the plan is valid.
* It means that when the plan is being loaded, there will be no plan icon in the loading placeholder
1164141197617539-as-1200760947306498/f
No
* Boot up this PR and 🔥 it.
* Go to wp-admin > Jetpack > My Plan
* Reload the. page if you need to
* Confirm that you don't see any broken image in plan loading placeholder
Screenshots
|BEFORE|AFTER|
|-|-|
| <img width="1012" alt="Screenshot 2022-02-09 at 3 52 28 PM" src="https://user-images.githubusercontent.com/18226415/153182470-f461724a-8971-46d3-a439-4a71b27f41c0.png"> | <img width="1007" alt="Screenshot 2022-02-09 at 3 53 16 PM" src="https://user-images.githubusercontent.com/18226415/153182517-7d7d36f6-f520-4611-b9d3-1a5e788a7928.png"> |

Fix broken image in plan loading placeholder in "My Plan"

---

projects/packages/my-jetpack/_inc/state/constants.js
projects/packages/my-jetpack/_inc/state/resolvers.js
projects/packages/my-jetpack/changelog/update-my-jetpack-initial-state

Avoid fetching all products data on the initial render, since most of them come from the backend already populated.
* Include `isFulfilled` into `getProduct` resolver, which looks for the initial state and list of products that need initial fetch.
* Dispatch `isFetching` in `getProduct` resolver, to avoid user interact with product before initial fetch.
N/A
No.
* Build `My Jetpack`(`jetpack build packages/my-jetpack`)
* Open the initial page.
* Inspect the request, you should see only `scan` being fetched.
https://user-images.githubusercontent.com/1663717/153309190-4ea8e82b-b09b-44db-bd9d-43463dcd9009.mp4

My Jetpack: Avoid fetch all products on initial render

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-cta-button

Fixes #22704 
* Add `isPressed` prop into `Button` for `ProductDetailCard`.
No.
* Build `My Jetpack`(`jetpack build packages/my-jetpack`)
* Navigate to `add-bost` and `add-search` routes.
* You should see black button.

My Jetpack: Correct style for `<ProductDetailCard />` button

---

projects/plugins/jetpack/changelog/try-payment-selects
projects/plugins/jetpack/extensions/blocks/premium-content/edit.js
projects/plugins/jetpack/extensions/blocks/premium-content/logged-out-view/edit.js
projects/plugins/jetpack/extensions/blocks/premium-content/subscriber-view/edit.js

When a block inside a premium content block is selected using the block list view tree, switch premium content to display the Subscriber/Guest view that contains it
Fixes #22426
No
1. Apply patch
2. If on a JP site then enable beta blocks
3. Ensure you have a paid plan
4. Create a post
5. Add a premium-content block
6. Open the list view sidebar
7. Select one of the children of the subscriber view or the subscriber view itself
8. You should see the guest view blocks in the content area disappear and the subscriber view blocks appear.
9. Select one of the children in the guest view or the guest view itself and the opposite should happen

Premium content: Switch view

---

projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/state/actions.js
projects/packages/my-jetpack/changelog/update-my-jetpack-request-error-notice

Closes #22627 
* Calls `setGlobalNotice` on product request failures.
N/A
No.
* Build `My Jetpack` (`jetpack build jetpack/my-jetpack`)
* Disconnect your user from wordpress.com
* Try to activate some product that requires a connection (like Scan).
* You should see a message saying that activation failed.
https://user-images.githubusercontent.com/1663717/153298963-a7d18666-e0cc-403a-ba69-9809aba439d3.mp4

My Jetpack: Notices for request errors

---

projects/plugins/jetpack/_inc/client/my-plan/my-plan-header/index.js
projects/plugins/jetpack/changelog/update-free-plan-description

Fixes 1164141197617539-as-1201340609889764/f
* Update the description of Jetpack Free plan in My Plan tab to not include the active standalone products which are already active for the site 
* The logic is copied from Calypso from [here](https://github.com/Automattic/wp-calypso/blob/bbe31df69fea04abd0b7d3df71aabb4fa597d693/packages/calypso-products/src/plans-list.tsx#L1302-L1334).
p1HpG7-dpL-p2#comment-50044
No
* Boot up this PR and 🔥  it.
* Go to wp-admin > Jetpack > My Plan
* Check the free plan description
* Now add a Backup plan to the site
* Confirm that the Free plan description does not include "backup"
* Add Scan plan to the site.
* Confirm that the Free plan description does not include "scan"
Screenshots
BEFORE
AFTER
- When there is both Backup and Scan
- When there is just …

Update Free plan description based upon active products

---

projects/plugins/jetpack/changelog/fix-premium-content-transformation-disallowlist
projects/plugins/jetpack/extensions/blocks/premium-content/index.js

Since there's no reason to allow transforming markup blocks to Premium Content block, let's not allow the user to transform them to Premium Content.
Fixes #22422 (Partially).
Disallows the following blocks to be transformed to Premium Content block:
* core/nextpage
* core/spacer
* core/separator
* core/more
* core/loginout
* core/post-navigation-link
* WPCOM: Apply D74740-code on your sandbox
* Atomic: Use Jetpack Beta plugin and switch to this branch
* Go to a new post and add one of the above mentioned blocks (e.g. core/spacer).
* Open the transforms dropdown and make sure that "Premium Content" block is no longer available.
* Try various variations (e.g. multiple block select blocks, multiple blocks that have at least one paragraph block)

Premium Content block: Disallow markup blocks to be transformed to Premium Content block

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-product-card-action-button

Replaces the usage renderActionButton for a component like usage pattern
Fixes inability to tamper with args passed to action button using React Dev Tools
* Renames renderActionButton to ActionButton
* Update usage inside JSX to reflect the fact it's a component now
no
* Confirm all buttons render properly and no error is shown on the console.
* Confirm you're able to inspect the Action button as a component with the React Dev Tools

My Jetpack: Replace renderActionButton function for ActionButton component

---

projects/plugins/jetpack/changelog/add-related-posts-block-design-tools
projects/plugins/jetpack/extensions/blocks/related-posts/index.js
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php

* Add color, spacing, typography & align (wide & full) design tools to the Related Posts block.
This PR is a part of the Expanding Jetpack Block design tooling for Full Site Editing project: pdDOJh-1P-p2 & pdDOJh-6-p2
I recommend testing this on a sandboxed existing WPCOM site using D74562-code as you'll need data for Related Posts.
1. Add Related Post block.
2. On the **Block Inspector** sidebar, you should see:
- Color (Text, Background, Link option)
- Typography (Size & Line Height option)
- Dimensions (Padding & Margin option)
3. On the **Block Toolbar**, you should see:
- Align (Full & Wide align option)
4. Check that they render fine both on the editor and the post page itself.
Note: Different themes may support different style attributes. Some theme suggestions to …

Related Posts Block: Add color, spacing, typography & align design tools.

---

projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-about-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
projects/plugins/jetpack/changelog/fix-A11n_data_load

Fixes #22666
The fetch_a8c_data() is being loaded on each WP-Admin page although it's only relevant to the Jetpack About page.
* Added a condition that loads data only on a page that has the current page hook set to 'admin_page_jetpack_about'.
* Changed the expiry of the `jetpack_a8c_data` transient to one week. Internal reference: p1644577543217449-slack-C0D96691V
No
* Find and delete the `jetpack_a8c_data` transient.
* Load any WP-Admin page (except the about page) and check if the transient is created. It shouldn't be.
* Go to Jetpack About page and check if the transient is created and the about page is showing correct data (number of people, languages...).

Improve fetching a11n data on About page

---

projects/packages/tracking/changelog/update-tracking-asset-dep
projects/packages/tracking/src/class-tracking.php

* The Tracking script relies on jQuery, so we should add it as dependency so it can be loaded by WordPress when loading `jptracks`.
* This was not an issue until today since we've only loaded Tracks in wp-admin, where jQuery is already enqueued. But with #22818, this may change, and thus we'll need to properly declare our dependencies.
* N/A
* No
* On a brand new site that does not run Jetpack, create a new plugin.
* Add the following dependencies to your plugin:
```
"require": {
"automattic/jetpack-tracking": "1.14.x-dev",
"automattic/jetpack-autoloader": "2.10.x-dev",
"automattic/jetpack-composer-plugin": "1.1.x-dev",
"automattic/jetpack-connection": "1.36.x-dev"
}
```
* In your plugin, load the autoloader.
* Load Track's script like so:
```
use Automattic\Jetpack\Tracking as Tracks; …
```

Tracking: add missing jQuery dependency

---

projects/packages/my-jetpack/changelog/change-my-jetpack-scan-status
projects/packages/my-jetpack/src/products/class-module-product.php
projects/packages/my-jetpack/src/products/class-scan.php

Scan looks like a module but it's not. All information about its activation lives in WPCOM.
This PR adapts its behavior to:
* consider itself active if Jetpack plugin is active and the plan was purchased (no need to activate any module)
* When activation is triggered, it does not fail if the scan module can not be found
* Fix Scan activation status
NA
No
* Launch a new site
* Confirm scan is not active
* Activate Jetpack plugin
* Buy Scan
* Go to My Jetpack and confirm Scan is shown as active
NOTE: we are not covering the activation and purchase flow in this PR

My Jetpack: Fix Scan activation and status

---

projects/plugins/jetpack/changelog/remove-is-frontend-cron-check
projects/plugins/jetpack/functions.global.php

Fixes https://github.com/Automattic/jetpack/issues/22410
Removes the `wp_doing_cron` check from the `jetpack_is_frontend` function, since it seems that some cron requests may result on frontend requests (e.g. when using the Super Cache plugin). That way, blocks will no longer be rendered as fallbacks on these requests.
N/A.
No.
- Go to `wp-admin/post-new.php`.
- Insert a Contact Form block.
- Publish the post.
- Add the following code to a mu-plugin: `add_filter( 'wp_doing_cron', '__return_true' );`
- Visit the published post.
- Make sure the contact form is displayed correctly.

Blocks: Remove cron check from `jetpack_is_frontend`

---

projects/packages/my-jetpack/changelog/my-jetpack-fix-products-upgradibility
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-search.php

This PR fixes the upgradability of `search` and `anti-spam`: Search is not upgradable by the security plan but Anti-Spam is.
It impacts straightly in the UI.
Fixes #
* My Jetpack: fix products upgradability
* Go to `#/add-search` page. Confirm you see the background color white.
`https://your-testing-site/wp-admin/admin.php?page=my-jetpack#/add-search`

My Jetpack: fix products upgradability

---

projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-footer

Since `wp-admin` has a lot of possibilities on top of `sidebar`, `footer messages`, etc, the usage of `vh` for `height` causes more side-effects than expected, based on that I moved to just use the available `height`.
* Move from `100vh` to `100%` in all tree.
N/A
No.
* Open `My Jetpack` page.
* Move to some interstitial pages (`add-boost`, `connection`, ...)
* You should not see the footer as below:
_Connection Interstitial_

My Jetpack: Fix footer layout on interstitial pages

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/changelog/fix-boost-checkout-my-jetpack

Fixes #22844
* Updates setting of productUrl to only happen if product is not free
* Visit `/wp-admin/admin.php?page=my-jetpack#/add-boost`
* Confirm clicking the button does not lead to checkout flow

My Jetpack: Only pass a productUrl if the product is not free on interstitial pages

---

projects/packages/my-jetpack/_inc/components/my-jetpack-screen/styles.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-global-notice-style

Closes #22843 
* Fix notice dismiss button alignment.
* Update notice error icon color.
N/A
No
* Go to `state/actions.js`
* Simulate an error throw on `requestProductStatus` method (line 33)
* Try to activate or deactivate one module.
* It should show the notice with improved styles.

My Jetpack: Improve global notice style

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/changelog/fix-lack-of-key-in-bundle-icon-loop-my-jetpack

Fixes warning about duplicated key
* Visit `/wp-admin/admin.php?page=my-jetpack#/add-search`.
* Open the console and confirm there's no React warning about duplicate keys

My Jetpack: Use proper key when looping through product detail icons and rendering the plus icon 

---

projects/packages/my-jetpack/changelog/update-my-jetpack-add-videopress-interstitial
projects/packages/my-jetpack/src/products/class-videopress.php

This PR adds VideoPress product data to be used to show them in the UI.
* My Jetpack: add VideoPress product data
No
* Print the `videopress` field of the `myJetpackInitialState` global var. Confirm you see `title`, `longDescription`, `features`...

My Jetpack: add VideoPress product data 

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/crm-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/changelog/add-fix-connection-error-link-my-jetpack

Makes the fix connection button redirect to the connection screen (`/connection` route).
Fixes #22865
* Makes the ProductCard fix connection button always navigate to `/connection` route.
* Adds firing of Tracks event `jetpack_myjetpack_product_card_fixconnection_click`
yes. 
* Add the `jetpack_myjetpack_product_card_fixconnection_click` event
**Option a**
* Open My Jetpack
* With the React Dev tools, edit a component like Search and set its prop `status` to `error`
* Expect to be shown the "Fix connection" button on that Card
* Click it and confirm you're taken to the connection screen
**Option b**
* Install Backup, connect and activate the product
* Confirm the product shows as active
* Use the broken token tool and "clear user tokens"
* Go back to My Jetpack
* …

My Jetpack: Make click on Fix connection show connection route

---

projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/hooks/use-connection-watcher/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-use-nav-custom-hook

This PR updates when using the navigation with the useMyJetpackNavigate () cusotm hook
Fixes #
* My Jetpack: useMyJetpackNavigate when it's worth it
No
* Check that all `/add-boost`,  `add-scan`, and the global notices link work as expected
*

My Jetpack: useMyJetpackNavigate when it's worth it

---

projects/plugins/jetpack/changelog/fix-external-media-modal-cannot-close
projects/plugins/jetpack/extensions/shared/external-media/media-button/index.js

Fixes https://github.com/Automattic/wp-calypso/issues/59985
* As `mediaProps` has `onClose` property, spreading it after the customized `onClose` function overwrites the customized one so that the external media modal cannot be closed. So I reorder the spreading `mediaProps` and call the `mediaProps.onClose` function inside customized `onClose` function if it is existed.
N/A
No
* apply soon-to-be-generated Diff to your WPCom sandbox
* Open an existing post (or create a new one)
* Insert an image block
* Select Image > Google Photos or Pexels Free Photos
* Close the modal
https://user-images.githubusercontent.com/13596067/153846267-c24d50b0-816e-48f8-a953-848ec67cf0ca.mov

Media Button: Fix the external medial modal cannot be closed

---

projects/plugins/jetpack/changelog/fix-photon-srcset-svg
projects/plugins/jetpack/class.photon.php

Fixes #22692
Photon hooks into the `wp_calculate_image_srcset` filter to add Photon domain and parameters to srcset image URLs generated for each image in a post. However, other plugins can also hook into that same filter, and some empty the array of images available for srcset. Let's support that use-case by checking not only for an array of images, but for an array that is not empty.
This PR particularly aims to solve a conflict with [the SVG Support plugin](https://wordpress.org/plugins/svg-support/). [Here](https://plugins.trac.wordpress.org/browser/svg-support/trunk/functions/attachment.php?rev=2672900#L263) is where that plugin hooks into `wp_calculate_image_srcset`.
* N/A
* N/A
* Start with a site that's connected to WordPress.com, and where you've activated Jetpack's Site …

Photon: ensure fallback when 3rd-parties empty array of sources

---

projects/packages/my-jetpack/_inc/components/product-detail-card/button.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/add-install-on-interstitial
projects/packages/my-jetpack/src/class-rest-products.php

Adds mechanism for sideloading product plugins when clicking the _Add Product_ button on interstitial pages.
**I am not so sure I like this flow now that I've seen it working here.**
* Makes Boost and Backup be installed from the interstitial pages.
* Adds button component with spinner next to product-detail-card component. Jetpack's ActionButton is not styled properly as to be useful here rapidly
* Replaces usage of regular Button for this new ProductDetailButton
no
1. Test that the scan interstitial leads directly to the checkout page for the Scan and Security products.
2. Remove the boost plugin
3. Visit My Jetpack.
4. Click Add Boost link. Expect to see the interstitial page for Boost
5. Click Add boost button on the interstitial. Expect to see a spinner
6. Expect to get reidrected to …

My Jetpack: Install products from interstitial page

---

.github/files/pr-update-to.sh

We're going to start using per-project pr-update-to tags to avoid e.g. a
release of Jetpack from invalidating PRs touching only Boost. Part of
that is that we'll need to create all those tags; that will be done
manually. But then we also need to keep those tags up to date as things
are released, which is what this PR is for.
Actually using the tags will come later. For now this also updates the
global pr-update-to tag whenever a per-project tag is updated.
none to link
no
* You could try running the script locally, with the `git push` at the end commented out, see if it reports no tag updates needed.
* Then copy the script into a checkout of something like e56542cd09e1c6a509faf42e3e49fee81a3b5dd2 and do the same. Since that commit has various changes, it should report tag updates.
* Merge …

actions: Maintain per-project pr-update-to tags

---

projects/packages/waf/actions.php
projects/packages/waf/changelog/enhancement-rename_waf_allow_function

Follow-up for a review nitpick in #22816. More details in [this comment](https://github.com/Automattic/jetpack/pull/22816#discussion_r807049405).
* See linked PR above.
No.
The change is trivial, but if you really want to test it:
* Go to the original PR linked above and follow its testing instructions.

Removed prefix from is_allowed_mode() function since we are in the waf namespace anyway.

---

projects/packages/my-jetpack/_inc/components/product-detail-card/stories/mock-data.js
projects/packages/my-jetpack/_inc/hooks/use-product/index.js
projects/packages/my-jetpack/changelog/update-my-jetpack-check-product-purchase
projects/packages/my-jetpack/src/class-wpcom-products.php
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-security.php
projects/packages/my-jetpack/src/products/class-videopress.php
projects/packages/my-jetpack/tests/php/test-wpcom-products.php

On this PR
* Propagate wpcom product name according to what we'd like to show
* try to pull discount value from wpcom side
* Add a discount value fallback when it isn't provided by wpcom 
Fixes #
*
No
* Compares Product prices with Jetpack pricing page. For instance, `Search`
My Jetpack | Jetpack Pricinf
-------|------
`https://retrowolf.ngrok.io/wp-admin/admin.php?page=my-jetpack#/add-search` | `https://cloud.jetpack.com/en/pricing/retrowolf.ngrok.io?site=retrowolf.ngrok.io`
Disclaimer: `Security` bundle shows a different value. Let's address this issue in a follow-up PR

My Jetpack:  Pull product discount from wpcom

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-set-checkout-url-properly
projects/packages/my-jetpack/src/products/class-anti-spam.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php
projects/packages/my-jetpack/src/products/class-security.php
projects/packages/my-jetpack/src/products/class-videopress.php

This PR exposes the wpcom product slug to be used to build the checkout product URL. 
(1) Disclaimer: it started to duplicated code so let's address it in a follow-up PR. Probably it's time to add `useCheckoutUrl()` hook \m/
(2) Disclaimer: we have some issues with the user currency. Something that we need to address, in a follow-up PR.
Fixes https://github.com/Automattic/jetpack/issues/22901
* My Jetpack: Set properly the checkout link for Products
* Test with a site with a free plan
* When installing a new paid product, confirm that the error shown above doesn't appear
* Confirm that the product on the checkout page matches the product in My Jetpack, for instance testing with `Backup` product:
My Jetpack | Checkout
------|------

My Jetpack: Set properly the checkout link for Products

---

projects/packages/connection/changelog/fix-sso-wpcom-user-id
projects/packages/connection/src/class-manager.php
projects/packages/connection/src/class-package-version.php
projects/plugins/jetpack/changelog/fix-sso-wpcom-user-id
projects/plugins/jetpack/modules/sso.php

SSO module adds meta key `wpcom_user_id` after first SSO sign in.
During all subsequent sign-ins Jetpack will check if the stored `wpcom_user_id` value matches the ID of the user trying to connect, and block the sign in attempt if it doesn't.
When a secondary user removes their user connection, we remove their `wpcom_user_id` meta value, so they can continue using SSO if they later connect as a different WP.com user.
However, we never do that for the primary user. If the primary user disconnects Jetpack, and connects later using different WP.com account, the `wpcom_user_id` meta value will not be updated, so they will not be able to connect via SSO.
The only way to resolve the issue to remove `wpcom_user_id` from the database manually.
* remove the current user's `wpcom_user_id` meta key …

SSO: removing wpcom_user_id upon disconnect

---

projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/fix-my-jetpack-videopress-anti-spam-clicks
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php

Fixes clicks not working on CRM, VideoPress and Anti-Spam  cards
* Adds click handler for Add actions on CRM, VideoPress and Anti-Spam cards
No
* Visit My Jetpack
* With the React Dev Tools (components tab) forge the state of the VideoPress, Anti-Spam and CRM cards to be `"plugin_absent"`.
* Confirm clickin Add on them pops up the interstitial and that you can install the plugins from the individiual price buttons.

My Jetpack: Fix Add click for CRM, VideoPress and Anti-Spam product cards

---

projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/fix-click-on-scan-and-search-my-jetpack

Fixes clicks not working on Scan and Search  cards
Closes #22927 
* Adds installer prop to interstitials
No
* Visit My Jetpack
* Rmove the Jetpack plugin 
* Confirm clickin Add on Scan or Search installs the Jetpack plugin

My Jetpack: Fix Add click for Scan and Search product cards

---

projects/packages/my-jetpack/changelog/fix-my-jetpack-purchases-i18n
projects/packages/my-jetpack/src/class-rest-purchases.php

While testing My Jetpack on a site set to French, I noticed some issues with current plan information.
In the Jetpack client, we have `ProductExpiration` and a hardcoded list of localized product titles based on the active purchases on the site (in `MyPlanBody`). In My Jetpack, however, we pull all the data from the `purchases` endpoint on WordPress.com. As a result, that section of My Jetpack is not translated:
What do you think about retrieving a translated version whenever possible? It's not a perfect solution since the expiration dates won't use the date format set for that site in Settings > General (we'd need to implement something like in the Jetpack plugin to make that happen I think), but at least it will be translated.
* N/A
* No
* Start with a site with language set to French, …

My Jetpack / Purchases: retrieve localized version of purchases

---

projects/packages/my-jetpack/changelog/update-my-jetpack-apply-coupon-when-exists
projects/packages/my-jetpack/src/class-wpcom-products.php
projects/packages/my-jetpack/tests/php/test-wpcom-products.php

~# Depends on https://github.com/Automattic/jetpack/pull/22928~
This PR applies the coupon discount to the Product price when it exists.
Currently, some products have a discount (valid until Feb 22). 
Fixes #
* My Jetpack: Apply coupon discount to Product price when it exists
* Test with a Free site
* Check that all product prices shown on the interstitials page are consistent with what the checkout page shows.
Keep in mind that the price is shown on the interstitial by month.
For instance, with Backup:
Interstitial | Checkout
-----|------
`$9.92`/ `$3.94` | `$119` / `$47.20`
.    | `119 / 12 ~= 9.92` / `47.20 / 12 ~= 3.94`

My Jetpack: Apply coupon discount to Product price when it exists

---

projects/plugins/jetpack/changelog/fix-media-endpoint-restore-media
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php

Fixes #22935
* WordPress.com has its own media structure; let's limit that implementation to WordPress.com simple sites and use the default behaviour on self-hosted sites.
* N/A
* No
1. Start from a site that's connected to WordPress.com, where you've uploaded some images in the past. 
2. Go to `https://wordpress.com/media/yoursite.com`
3. Select an image, and click on Edit (you can also upload a new image and produce the same result)
4. Click on "Edit Image" in the right corner of the image.
5. Save your changes.
6. Go back to edit the same image.
7. A "Restore Image" button now appears next to the "Edit Image" button. Click it
8. When not running this branch, you should get an error, and a Fatal error in your logs.
9. When running this branch, the original version of the image should be …

WPCOM API: avoid fatals when editing images from the API.

---

projects/plugins/jetpack/changelog/2022-02-17-11-22-57-699265
projects/plugins/jetpack/class.json-api-endpoints.php
projects/plugins/jetpack/modules/videopress/utility-functions.php

﻿* When viewing Media from Calypso, including videos, old and new, you may run into warnings. This should fix that.
```
PHP Warning:  Undefined array key "rating" in /wp-content/plugins/jetpack-dev/modules/videopress/utility-functions.php on line 484
PHP Warning:  filesize(): stat failed for https://videos.files.wordpress.com/vgpx3cCK/screen-recording-2021-10-26-at-9.41.35.mov in /wp-content/plugins/jetpack-dev/class.json-api-endpoints.php on line 1525
```
* N/A
* No
* Start from a site that's connected to WordPress.com, with a Video plan, and where you uploaded videos in the past.
* Tail your site's error log.
* Access `https://wordpress.com/media/yoursite.com`
* Ensure you see no errors in your log.

VideoPress: avoid PHP warnings when accessing media from API.

---

projects/github-actions/repo-gardening/changelog/fix-repo-gardening-milestone-error
projects/github-actions/repo-gardening/package.json
projects/github-actions/repo-gardening/src/tasks/add-milestone/index.js

* Let's avoid having the whole workflow fail when a valid milestone cannot be found. See https://github.com/Automattic/jetpack/actions/runs/1858103640 for example, where it threw an error just because Boost only has an opened milestone with a due date in the past.
* ﻿Instead, just abort the task and display the error in the log.
* p1645094099777259-slack-C02SV8APDTM
* No
* Not much to test here; let's see if the next Boost PR without a milestone attached throws an error when it's merged?

Repo Gardening: avoid throwing an error when no valid milestone

---

projects/plugins/boost/app/class-jetpack-boost.php
projects/plugins/boost/changelog/add-my-jetpack-to-boost
projects/plugins/boost/changelog/add-my-jetpack-to-boost#2
projects/plugins/boost/composer.json
projects/plugins/boost/composer.lock

* Adds My Jetpack page to the Boost plugin
No
* Build the Boost plugin
* Add `define( 'JETPACK_ENABLE_MY_JETPACK', true ); ` to your wp-config.php
* Make sure My Jetpack menu item is shown even when only the Boost plugin is enabled

Boost: Add My Jetpack page

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/_inc/components/product-detail-card/button.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-buttons-links

Related with #22649 and #22647
* Add CSS vars from `wp-admin` to override some `wordpress/components`.
* Remove all `isPressed` props.
N/A
No.
* Go to `My Jetpack` page.
* Navigate and interact with buttons (Home, Interstitials, and Connection).
* You should see all buttons in black style.

My Jetpack: Move out from `isPressed` props on `Wordpress/Buttons`

---

projects/plugins/jetpack/changelog/fix-publicize-double-escaping
projects/plugins/jetpack/modules/publicize/ui.php

Fixes a minor bug introduced in #22511.
* Fixes a minor regression causing the connections info in the Publicize metabox in the Classic Editor to be double escaped.
No.
* Open a new Classic Editor post window.
* Ensure the connections in the Publicize metabox are displayed properly.

Publicize: Fix double escaping in Classic Editor

---

projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-tweak-interstitial-upgradable-layout

This PR updates the layout of the interstitial page when it has an upgradable bundle making it more similar to the design.
Fixes #
* My Jetpack update interstitial page when it has an upgradable bundle
* Go to an interstitial page that has the upgradable option
* Confirm visually the changes in the widths of both cards
before | after
-----|------

My Jetpack update interstitial page when it has an upgradable bundle

---

projects/packages/my-jetpack/changelog/update-my-jetpack-check-forpurchase-after-check-for-active
projects/packages/my-jetpack/src/products/class-product.php

Fixes lack of connection error status in Product cards when they had been active prior to visiting My Jetpack
* Moves the check for purchase inside the check for active.
p1645195048392569/1645194604.515169-slack-C02TQF5VAJD
no
1. On a site with just Boost active and My Jetpack enabled. 
2. Connect with boost. 
3. Add Jetpack Backup from the plugin repository
4. Visit My jetpack
5. Confirm you see the "requires user connection" message and the "Fix connection" button on the card

My Jetpack: Check if product is active before checking if it requires plan

---

projects/packages/my-jetpack/changelog/add-write-access-initial-state
projects/packages/my-jetpack/src/class-initializer.php

We want to correctly inform the user when we are not able to install plugins for them, so we are adding this information on the initial state.
Since the check is made by trying to write a file to the filesystem, I decided to cache this so we don't do it on every request to My Jetpack. By using transients, there could be ambiguity if we stored a boolean (get_transient will return false if the transient does not exist), so I went with `yes` and `no`.
* Add Filesystem write access to the initial state
p1645191421562159-C02TQF5VAJD-slack
No
* Go to My Jetpack page
* inspect the global `myJetpackInitialState` var and verify there's a `fileSystemWriteAccess` var with a value of `yes` or `no`
* On your local dev env, it should probably be "no" (if it's like mine)
* On a JN site it should be …

Add Filesystem write access to the initial state

---

projects/js-packages/connection/changelog/fix-connection-status-card-props
projects/js-packages/connection/components/connection-status-card/index.jsx

Fixes a warning introduced by wrong `prop-type` on `ConnectionStatusCard`
* Updates `onConnectUser` prop type.
N/A
No
* Go to `My Jetpack`
* Open the console and you should not see React warnings

Connection: Fix `<ConnectionStatusCard />` prop-type

---

projects/plugins/backup/changelog/fix-backup-section-padding
projects/plugins/backup/src/js/components/Admin.js

Fixes #22887 
* Fixes all spacing for `Container` inside `Backup` plugin.
N/A
No
* Go to `Backup` standalone plugin page.
* It should have spacing on the hero section.

Backup: Fix spacing regression for all containers

---

projects/plugins/boost/changelog/e2e-fix-readme
projects/plugins/boost/tests/e2e/README.md
projects/plugins/jetpack/changelog/e2e-fix-readme
projects/plugins/jetpack/tests/e2e/README.md

Fix some outdated `pnpm` commands in e2e tests readme files.
n/a
no
* CI happy

Docs: update outdated pnpm commands in e2e readme

---

projects/plugins/jetpack/_inc/client/dashboard-widget/style.scss
projects/plugins/jetpack/changelog/fix-jetpack-stats-screen-option
projects/plugins/jetpack/class-jetpack-stats-dashboard-widget.php

Fixes #22811
Style change to display the label text  for the Stats by Jetpack Screen Option checkbox toggle
* Checkout this branch and rebuild jetpack plugin and dependencies
* Launch locally e.g. via jurassic tube
* Expand the screen options
* You should now see label text next to the Stats by Jetpack checkbox where before it was 'anonymous' with no label text
Before:
After:

Fix jetpack stat screen option checkmark style

---

projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/changelog/add-tracks-events-my-jetpack-security-product-card

Fixes lack of event tracking when clicking the Add Security button on the product interstitial
* Fixes click tracking on My Jetpack interstitial for Security bundle
* Go to this patch `wp-admin/admin.php?page=my-jetpack#/add-scan`. 
* Click the Add Security button on the right card
* Confirm that the developer console displays the events `jetpack_myjetpack_product_interstitial_add_link_click`

My Jetpack: Fix click tracking on My Jetpack interstitial for Security bundle

---

projects/packages/my-jetpack/changelog/update-product-needs-purchase-status
projects/packages/my-jetpack/src/products/class-product.php

Fixes situation where `needs_purchase` status was not being returned.
* Return needs purchase status for Module Products
p1645472714319129-C02TQF5VAJD-slack
No
* Backup with active plugin but without a plan should return `needs_purchase` - but should return an error if user is not connected
* Scan and Search should return `needs_purchase` if plugin is active but plan is missing

My Jetpack: Return needs purchase status for Module Products

---

projects/packages/my-jetpack/README.md
projects/packages/my-jetpack/changelog/remove-feature-flag-my-jetpack
projects/packages/my-jetpack/src/class-initializer.php

Sets My Jetpack loading to on by default. 
* Removes check for constant
* Updates README.md
p9dueE-4rG-p2
no
**On a site with Boost bleeding edge and connected.**
* Confirm the My Jetpack page is shown without any constant set
**On a site with Backup bleeding edge and connected.**
* Confirm the My Jetpack page is shown without any constant set
**On a site with Jetpack bleeding edge and connected.**
* Confirm the My Jetpack page is shown without any constant set

My Jetpack: Remove check for feature flag JETPACK_ENABLE_MY_JETPACK

---

.github/files/pr-update-to.sh
.github/workflows/pr-is-up-to-date.yml
projects/github-actions/pr-is-up-to-date/.gitattributes
projects/github-actions/pr-is-up-to-date/README.md
projects/github-actions/pr-is-up-to-date/action.yml
projects/github-actions/pr-is-up-to-date/changelog/update-pr-is-up-to-date-multiple-tags
projects/github-actions/pr-is-up-to-date/changelog/update-pr-is-up-to-date-multiple-tags#2
projects/github-actions/pr-is-up-to-date/composer.json
projects/github-actions/pr-is-up-to-date/funcs.sh
projects/github-actions/pr-is-up-to-date/run.sh
projects/github-actions/pr-is-up-to-date/tests/funcs.sh
projects/github-actions/pr-is-up-to-date/tests/run-tests.sh
projects/github-actions/pr-is-up-to-date/tests/test-010-init_repo.sh
projects/github-actions/pr-is-up-to-date/tests/test-020-fetch_prs.sh
projects/github-actions/pr-is-up-to-date/tests/test-030-should_process_pr.sh
projects/github-actions/pr-is-up-to-date/tests/test-040-process_pr.sh

In our monorepo, we don't want releases of one project to make PRs
against another out of date. The solution is to have one tag per project
(plus the global tag for situations when CI infrastructure changes) and
only check the PR against the relevant project.
This needs two changes in the action:
1. When called on PR, allow specifying multiple tags.
2. When called on tag push, allow specifying the paths the pushed tag
affects.
None to link
No
* You could merge this into master on a fork, then try merging things and updating tags and seeing if it works right. Or you could run the script locally with the proper environment variables set (just don't set `CI` and it won't try to update GitHub).
* Also, proofread the updated docs.

pr-is-up-to-date: Allow checking multiple tags

---

projects/plugins/jetpack/changelog/fix-subscribe-block-color-serialization
projects/plugins/jetpack/extensions/blocks/subscriptions/controls.js
projects/plugins/jetpack/extensions/blocks/subscriptions/edit.js

The proposed changes make sure that when user selects one of the theme-registered palette colors for the block border color:
the color will be saved as the palette color (e.g. "primary") instead of the related color code (e.g. `#000000`).
Before:
After:
- use `setBorderColor()` instead of `setAttributes()` to handle the Subscribe block border color changes
- p1645006316158349-slack-C02TCEHP3HA
1. Create a new page or a post and add Subscribe block to it
2. Change the border color block setting. Try the _theme preset colors_ and also _custom ones_:
3. Save the changes
4. Observe the changes on both: block editor and frontend. Color should change correctly
5. If you select one of the preset colors, the color should be applied using a CSS class, not an inline style. This can …

Subscribe block: Fix Border Color Serialization

---

projects/plugins/jetpack/changelog/remove-jetpack-menu-item
projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php

Fixes https://github.com/Automattic/wp-calypso/issues/54652
* This PR removes jetpack submenu item from the settings menu on the unsupported plan.
- Copy the changes proposed in this PR to your atomic site.
- visit your site
Free Atomic:
- Verify `Settings` > `jetpack` submenu is not be visible
Atomic with a higher plan:
- Make sure `Settings` > `jetpack` is visible as usual.

Jetpack Settings Submenu: Hide submenu item from menu on unsupported plan

---

projects/github-actions/pr-is-up-to-date/changelog/update-try-to-fix-run-sh
projects/github-actions/pr-is-up-to-date/run.sh

Please add testing instructions to projects/plugins/jetpack/to-test.md in a new commit as part of your PR. -->
After #22925 was merged, pr-is-up-to-date started failing with `/home/runner/work/jetpack/jetpack/./projects/github-actions/pr-is-up-to-date/run.sh: line 5: ./funcs.sh: No such file or directory` - this PR tries to specify the source for funcs.sh more specifically to see if that does the trick.
n/a
No
* Does the test pass?
*

Pr-is-up-to-date: Fix run.sh source

---

projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx
projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/changelog/add-version-tracks-my-jetpack
projects/packages/my-jetpack/src/class-initializer.php

Fixes #
* Introduces a bare recordEvent function exported from `useAnalytics` that can be used instead of `tracks.recordEvents`
* Makes every event fired carry the My Jetpack version from where it was firedf
* We update every event from My Jetpack to carry a `version` property.
* Checkout this branch on a site with Jetpack connected the Backup plugin active
* Go to this path `wp-admin/admin.php?page=my-jetpac`. 
* Click the Add Security button on the right card, active buttons, manage, etc. Confirm you see the version on each event

My Jetpack: Send My Jetpack version with fired events

---

projects/packages/my-jetpack/changelog/update-my-jetpack-fix-extras-manage-link
projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-extras.php

This PR sets the status of the `Extras` card according to the Jetpack plugin.
Fixes https://github.com/Automattic/jetpack/issues/23019
* My Jetpack: My Jetpack: set status and manage link of Extras card
No
**Check `Extras` is not available/active le when Jetpack plugin is not available/active**
* Active `Boost` plugin, for instance
* Go to My Jetpack overview
* Confirm the `Extras` is available/active
* Clicking on `Active` triggers an error (going to be handled in a follow-up PR)
**Check `Extras` is active when Jetpack plugin is active**
* Confirm that when the Jetpack plugin is active, `Extras` is active too.
* Confirm that, when it's active, the Manage link leads to the Jetpack plugin dashboard.

My Jetpack: set status and manage link of Extras card

---

projects/plugins/jetpack/_inc/lib/core-api/class.jetpack-core-api-site-endpoints.php
projects/plugins/jetpack/changelog/add-gate-for-videopress-active

Improves the performance of the API to only count VideoPress videos if that module is active.
* Adds a module check.
p1645543635194369-slack-CDLH4C1UZ
No.
* On a connected Jetpack site with a lot of attachments, check the performance of the API before or after.

API: Only count VideoPress files if that module is active

---

projects/packages/analyzer/changelog/fix-analyzer-script-default-from-version
projects/packages/analyzer/scripts/jetpack-svn.php

Fixes a bug in the jetpack-svn.php script when using default "jetpack from" parameter. The loop is unnecessary and was returning `9.9.1` version. Get the latest tagged version directly from the response object instead. 
Gets the latest tagged version directly from the response object instead of trying to loop through them all. 
N/A
No
You could error_log the `$from_version` before and after the patch is applied.

Analyzer: Fix bug when getting latest stable version by default.

---

projects/packages/autoloader/changelog/fix-autoloader-coverage-for-upstream-change
projects/packages/autoloader/tests/php/bin/test-coverage.php
projects/packages/autoloader/tests/php/lib/class-test-plugin-factory.php

sebastianbergmann/php-code-coverage@0f89e2c renamed some internal
classes, one of which we were using to munge line numbers for the
autoloader coverage report.
Unfortunately there doesn't really seem to be any cleaner way to do
this. At the least we can read the class name with `get_class()`
instead of hard coding it.
Also, since it came up while trying to test this locally, set
`COMPOSER_HOME` when trying to run old versions of composer that don't
recognize new-format GitHub OAuth tokens so it doesn't complain about
the one that's probably in the local config.
None really
No
* Does the coverage test pass again?

autoloader: Fix coverage generation for upstream change

---

projects/packages/my-jetpack/changelog/fix-get-product-names
projects/packages/my-jetpack/src/class-products.php

Fixes `get_product_names` method so it does not load all products information. This avoids the site triggering requests in every page load.
* Do not load all data of the products on get_product_names method
p8oabR-Oy-p2#comment-5997
No
* Looking at the Query Monitor plugin information, confirm there are no requests being triggered by My Jetpack, outside of the My Jetpack page

My Jetpack: Fix get_product_names to not make requests

---

projects/packages/my-jetpack/changelog/update-disable-my-jetpack-multisite
projects/packages/my-jetpack/src/class-initializer.php

My Jetpack won't work properly on Multisite installations yet. Let's disable it for now
* Disable My Jetpack on Multisite
p1645634234434789-slack-C02TQF5VAJD
No
* Launch a Multisite site ([JN link for launching with boost and multisite on subdirs](https://jurassic.ninja/create?jetpack-beta&branches.jetpack-boost=update/disable-my-jetpack-multisite&wp-debug-log&subdir_multisite))
* Make sure My Jetpack never shows up after the site is connected

My Jetpack: Disable for Multisite installations

---

projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/changelog/fix-recordevent-my-jetpack-memoize

Fixes double/triple tracking of events
* Wraps `recordEvent` with `useCallback` hookl
p1645633985514979-slack-C02TQF5VAJD
no and yes. Fixes tracking, but nothing new is introduced
* Checkout to this branch 
* Visit My Jetpack
* open the console and run `localStorage.debug='dops:analytics';`
* Refresh the page
*  Confirm that you only see one page view event for `jetpack_myjetpack_product_card_add_click`

My Jetpack: Memoize RecordEvent from useAnalytics hook

---

projects/packages/analyzer/changelog/update-analyzer-required-php-version
projects/packages/analyzer/composer.json

Updates the PHP requirement to allow using PHP 7.4. 
This allows us to run it in our wpcom sandboxes. 
Changes minimum PHP version to 7.4
@brbrr said it's probably fine p1645624757709889/1645621224.278529-slack-CBG1CP4EN
No 
Not really sure. Testing in a PHP 7.4* environment (wpcom) WFM.

Analyzer: Change minimum PHP version to 7.4

---

projects/packages/my-jetpack/_inc/hooks/use-connection-watcher/index.js
projects/packages/my-jetpack/_inc/state/selectors.js
projects/packages/my-jetpack/changelog/update-fix-my-jetpack-connection-notice

Fixes a regression caused by #23073, since all manipulation on the product that was being directly on the original object, the entire data on the store was getting modified for `camelCase`, since it was moved to `selector` and not modified the original object, the connection was using in `camelCase` direct from `getProducts`, because of this it stopped to work.
This already will help on follow-up PRs about `ConnectionStatusCard`.
* Move `getProductsThanRequiresUserConnection` to own selector using `snake_case`.
* Use that on `useConnectionWatcher` and move message out of `useEffect` to avoid recalling `useEffect` unnecessary.
N/A
No.
* Disconnect user from the site.
* Goes to `My Jetpack` page.
* You should see the notice saying about connection.

My Jetpack: Fix My Jetpack connection notices

---

projects/plugins/jetpack/changelog/fix-add-missing-plugins-menu-woa-site
projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php

Fixes #https://github.com/Automattic/wp-calypso/issues/59734
* This is follow-up PR to fix changes introduces by #22786. Due to the capability being removed the plugins.php menu went missing. This PR re-adds the Plugins menu for the Atomic site with unsupported plans. 
- in your atomic dev blog, copy the changes proposed in this PR
- visit your site
- make sure that Plugins links to Calypso [https://wordpress.com/plugins/[DOMAIN]](https://wordpress.com/plugins/%5BDOMAIN%5D)
- You don't see any submenu under Plugins menu
- make sure that Plugins -> Add New still links to Calypso [https://wordpress.com/plugins/[DOMAIN]](https://wordpress.com/plugins/%5BDOMAIN%5D)
- make sure that Plugins links to the default WP admin wp-admin/plugins.php page.
- make sure that Plugins -> Installed Plugins …

Add missing plugins sidebar menu for Atomic site with unsupported plan

---

projects/packages/my-jetpack/changelog/update-beta-badge-style
projects/packages/my-jetpack/src/class-initializer.php

Fixes #22962
* Updates styles on Beta badge
no
* Check the beta badge on an RTL language 
* Confirm it looks like in the screenshot

My Jetpack: Fix styles for beta badge on RTL languages

---

projects/packages/my-jetpack/_inc/components/connections-section/index.jsx
projects/packages/my-jetpack/changelog/add-connected-plugins-my-jetpack-disconnect
projects/packages/my-jetpack/src/class-initializer.php

Adds the list of connected plugins to the disconnect dialog.
This is a temporary approach while we don't incorporate this into the js connection package.
Known issue: if you activate a plugin and click Disconnect without a page refresh, the activated plugin will not show up in the list
* Added list of connected plugins to Disconnect dialog in My Jetpack
https://github.com/Automattic/jetpack/issues/23079
No
* Activate More than one plugin. e.g. Boost and Jetpack
* Click Disconnect
* Confirm that the modal window shows the correct list of active plugins using the conection

My Jetpack: add connected plugins to Disconnect dialog

---

projects/plugins/jetpack/changelog/fix-publicize-classic-editor-save-meta
projects/plugins/jetpack/modules/publicize/publicize.php

Fixes a bug in Publicize that caused some post meta in the Classic Editor to not get saved properly.
* Removes the incorrect sanitation that caused an array to get converted to an empty string, causing the following if statement to always return false.
p1645738067416259-slack-CBG1CP4EN
p1645728865017369-slack-C02JJ910CNL
No.
* Start a new post with Publicize enabled.
* Disable Publicize for a specific connection for that post (e.g. don't post to Facebook or Twitter)
* Save as draft.
* Confirm the connection is still unchecked.

Publicize: Fix post meta not saving properly in Classic Editor

---

projects/packages/README.md
tools/replace-next-version-tag.sh

Allow the `$$next-version$$` token to be passed to the WordPress
deprecation notice functions too. Note the token must be inside
single-quotes and the call must be all on one line and indented with
tabs.
Nothing I recall to link to. I think it has been mentioned once or twice.
No
* Add a deprecation like `_deprecated_function( __METHOD__, 'jetpack-$$next-version$$' )` somewhere in a project. Then run the script for that project and see that it's updated correctly.

tools: Allow `$$next-version$$` in deprecation functions

---

projects/packages/my-jetpack/_inc/admin.jsx
projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-footer-automattic-logo

Fixes #23109
Should be followed up by a PR that addresses #23112
* Passes down `a8cLogoHref ` prop set to `https://automattic.com
p8oabR-Oy-p2#comment-6033
No
* Visit My Jetpack
* Hover on the Automattic logo at the footer
* Confirm it links to automattic.com
* Click an "Add..." link on a card
* Hover on the Automattic logo at the footer
* Confirm it links to automattic.com

My Jetpack: Update automattic logo href in the footer

---

projects/plugins/jetpack/.gitattributes
projects/plugins/jetpack/changelog/add-jetpack-include-waf-dep-in-build

PR #22816 added packages/waf to Jetpack, and that package has a
(non-dev) Composer dep. If we want the package to work (someday, looks
like there's no UI for enabling or configuring it yet), that dep will
need to be included in the plugin bundle.
p1645724524900839/1645722448.473329-slack-C01U2KGS2PQ
No
* Check the build artifact for the Jetpack plugin. Make sure the aho-corasick library is included in the bundle.

jetpack: Include a WAF composer dep in the build

---

projects/packages/my-jetpack/_inc/components/my-jetpack-screen/styles.module.scss
projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-keep-tweaking-styles

On this PR:
✅ Page heading weight.
✅ Buttons border-radius from 2px to 4px.
✅ My Plan text for no plan and manage plans.
Fix partially https://github.com/Automattic/jetpack/issues/23014
*
* My Jetpack
* Confirm the style tweaks

My Jetpack: My Jetpack: Handle cosmetic tweaks

---

projects/github-actions/pr-is-up-to-date/changelog/fix-pr-up-to-date-workflow-timeout
projects/github-actions/pr-is-up-to-date/funcs.sh
projects/github-actions/pr-is-up-to-date/run.sh

When processing a tag push and PATHS is set, we need to find the merge
base to get the diff to determine if the paths are touched.
But it's a lot faster to fetch 100 revisions at once than to fetch 10
revisions 10 times. So instead of fetching to each PR's merge base,
which will likely enough fetch a few revisions for every PR beyond a
certain age, fetch arbitrary blocks of revisions.
None
No
* You could set the relevant environment variables and run the script manually. Or merge then watch the run on the next tag push.

pr-is-up-to-date: Speed up processing of tag pushes with paths

---

projects/packages/status/changelog/fix-site-suffix-colon
projects/packages/status/src/class-status.php
projects/packages/status/tests/php/test-status.php

In response to https://github.com/Automattic/wp-calypso/issues/61464
Some plugins add trailing slash to the WP home URL, resulting in the site suffix ending with `::` (e.g. `example.org::`).
That causes issues with Calypso, and this PR removes the trailing `::` it happens to be there.
* remove trailing semicolons from the site suffix
https://wp.me/p9F6qB-8EL
No.
_Before checking out the PR, please try reproducing the issue:_
1. Connect Jetpack
2. Install and activate the following plugins: Polyland, Elementor, Polylang Connect for Elementor
3. Go to your site's Calypso section (e.g. "Stats") and then click on "Plugins".
4. Confirm that the site suffix in the URL contains the trailing `::` (e.g. `your-site.example.org::`). The plugin page will not load.
5. Checkout the branch, close the …

Connection: remove trailing semicolons from the site suffix

---

projects/packages/my-jetpack/changelog/fix-wp-error-my-jetpack
projects/packages/my-jetpack/src/class-rest-products.php

*  Adds `use WP_Error` statement.
no
Confirm changes make sense. Line [110](https://github.com/Automattic/jetpack/blob/e1f49a69ab8f90a34aff53f8d9ef13a196b421c4/projects/packages/my-jetpack/src/class-rest-products.php#L110) is using WP_Error but this symbol hasn't been imported nor it's referred to via the global namespace.

My Jetpack: Declare usage of WP_Error in REST Products class to prevent fatal

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/_inc/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-keep-tweaking-style-2

In this PR:
* Product Card spacing not following 8px rule.
* Product Card button height to 32px
* Fix horrible style issue in Product card dropdown.
I've added a wrapper to the actions in order to locate them always at the bottom of the card to make all of them aligned among them.
Fixes https://github.com/Automattic/jetpack/issues/23014
* My Jetpack: tweak product card box model.
* Confirm the dropdown button has border-radius properly applied
before | after
----|-----
* Confirm button height is 32px
* Confirm space between title and description is 8px
* Confirm actions are always located at the bottom of the card, for instance, changing the height of the card:

My Jetpack: tweak product card box model.

---

projects/github-actions/repo-gardening/changelog/fix-gardening-cache-milestones
projects/github-actions/repo-gardening/src/get-next-valid-milestone.js

When multiple plugins are touched, it was hitting the milestones
endpoint for each one. We can reduce API calls slightly by caching the
results.
None
No
* ???

repo-gardening: Cache results from the milestones endpoint

---

projects/plugins/jetpack/changelog/update-module-activation-hooks
projects/plugins/jetpack/class.jetpack.php
projects/plugins/jetpack/tests/php/general/test_class.jetpack.php

Enhances `Jetpack::update_active_modules` method by taking the `pre_update_option_jetpack_active_modules` filter into account before firing the corresponding `jetpack_activate_module` and `jetpack_deactivate_module` hooks.
The logic is to compare the `jetpack_active_modules` option value before and after the update and based on the differences decide which modules were **just** activated or deactivated in order to fire the corresponding hooks.
* Updates `Jetpack::update_active_modules` method by relying on the `jetpack_active_modules` option value before and after the update in order to fire the corresponding hooks. This approach ensures that if a consumer uses the `pre_update_option_jetpack_active_modules` filter, it will be respected.
* Removes redundant hook from …

Jetpack: Take pre_update_option filter into account when firing active module hooks

---

projects/plugins/jetpack/changelog/fix-p2-subscribe-block
projects/plugins/jetpack/extensions/index.json

#22912 added publish panels, and thus a dependency with `@wordpress/edit-post`, but that is not available on that `no-post-editor` bundle, used on the frontend of P2s.
* p1646062066323259-slack-C010KDAPG49
* No
* On WordPress.com, apply D75812-code and sandbox a P2.
* See if Jetpack blocks are available in the post editor on the frontend.

Subscribe block: remove from P2 bundle

---

.github/workflows/slack-workflow-failed.yml

We've decided to split the notifications, with master going to one
channel and release branches going to another.
There are two ways this could have been done: have a step determine the
channel as an output to feed to the send-message step, or have
send-message steps per channel with `if` used to enable the appropriate
steps. I decided to go with the latter, since it's more straightforward
that way if at some point in the future we decide messages might want to
go to more than one channel (e.g. say Boost wanted notifications about
their release branch to go to their channel too).
p9dueE-4wL-p2#comment-7473
No
* Hard to directly test this, mostly we'll have to merge then wait for things to fail.

actions: Direct CI Slack notifications to different channels

---

.github/workflows/slack-workflow-failed.yml

`github.ref` will always be master, because that's where `workflow_run`
runs the workflow from. The branch with the failing workflow that
triggered the `workflow_run` event is available as
`github.event.workflow_run.head_branch`.
p1646070824573589/1646069834.054499-slack-C034JEXD1RD
No
* Merge and wait for another notification.

actions: Fix branch detection in slack notification workflow

---

projects/plugins/jetpack/changelog/fix-warning-premium-content
projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js

Follow-up to #22691
* Avoid warnings such as
```
wp.data.select( 'core/editor' ).getSelectedBlock` is deprecated since version 5.3 and will be removed in version 6.2. Please use `wp.data.select( 'core/block-editor' ).getSelectedBlock` instead.
```
* N/A
* No
* On a WoA site, try to use the Premium content block; it should still work, especially the feature highlighted in #22691. You can follow the testing instructions there.

Premium content: avoid deprecation warning.

---

projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-product.php
projects/packages/my-jetpack/src/products/class-search.php

simplify hook registration

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-cta-button-alignments
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php

This PR aligns CTA buttons of the My Jetpack overview taking reference from the card bottom.
Fixes https://github.com/Automattic/jetpack/issues/23190
* My Jetpack: align CTA buttons of My Jetpack overview
* Go to My Jetpack overview
**before**
**after**

My Jetpack: align CTA buttons of My Jetpack overview

---

.github/workflows/build.yml

We noticed the other day that GitHub incorrectly ran the workflow on a
push to a branch named "fix/slack-workflow-branch-detection".
This turned out to be due to a bug in GitHub's pattern matching code.
They intended for a pattern like `**/foo/bar` to act like .gitignore in
that the `**/` would match zero or more path components and therefore
match "foo/bar" at the repo root. But what they actually do is have it
make the pattern be completely unanchored, so it'll also incorrectly
match something like "notfoo/bar".
Since we want to match "one or more path-like components" anyway, we can
work around that bug by using a pattern like `**/*/branch-**`, meaning
"zero or more path-like components, followed by exactly one path-like
component, followed by `branch-**`". …

actions: Work around branch matching bug

---

projects/plugins/jetpack/changelog/remove-duplicate-related-posts-filter
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php

In #22270 we added a second call to the
`jetpack_relatedposts_returned_results`, so the output could be
modified, but it was passed a single related post rather than an array
of results.
Because of this, any existing code hooked into the filter caused a fatal
error as it tried to process a scalar as an array.
This PR reverts the change. It looks like the output can still be
modified in the same way as the testing instructions for #22270 without
it.
p1646335055245699-slack-CDD9LQRSN
No
* Follow the instructions for 'Related Posts injected at the bottom of each post via JS' in #22270
* Without this change you should see errors in the logs similar to: `Uncaught Error: Cannot use a scalar value as an array in ...`
* With this change it should work as described.

Related Posts: Remove duplicated filter

---

projects/plugins/beta/changelog/fix-beta-download-with-v
projects/plugins/beta/composer.json
projects/plugins/beta/jetpack-beta.php
projects/plugins/beta/src/class-autoupdateself.php

Back in #20385, we fixed it to recognize versions like "v3.1.1". But we
left it downloading from the URL based on the version number without the
"v".
Fixes #23184
p1646171473021239-slack-C01U2KGS2PQ
No
Testing the update logic is a little tricky.
* Install the release version of Jetpack Beta 3.1.1.
* `cd wp-content/plugins/jetpack-beta`
* Apply the patch from this PR: `curl -L https://github.com/Automattic/jetpack/pull/23185.diff | patch -p4`
* Point the self-update at a fork I've prepared: `sed -E -i 's!Automattic([-/]jetpack-beta)!anomiex\1!' src/class-autoupdateself.php`
* It should offer an update to a version 3.1.2. Updating to that should work.

beta: Download from correct URL for a tag like "v3.1.1"

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/anti-spam-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/backup-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/boost-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/connected-product-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/crm-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/extras-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/scan-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/search-card.jsx
projects/packages/my-jetpack/_inc/components/product-cards-section/videopress-card.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-product-card-janitorial

This PR iterates over ProductCard components in order to simplify and reduce the code.  There is a bunch of repeated code that can be simplified thanks to the `useProduct()` hook, name conventions, etc. The goal is, again, to make the code more eligible, simpler, but without removing the ability to customize some of them when it's required. `showDeactivate` is an example of it.
Fixes #
* Introduces <ConnectedProductCard/> component.
* SImplifies code in product cards by using <ConnectedProductCard/> instead of <ProductCard/> directly
no
* Go to My Jetpack dashboard. Confirm everything works as expected:
*  Activate/Deactivate Product
* Add Product link leads to the Interstitial page
* Confirm it triggers events
* etc

My Jetpack: tidy Product card component

---

projects/plugins/jetpack/changelog/fix-videopress-set-core-video-attributes
projects/plugins/jetpack/extensions/blocks/videopress/edit.js
projects/plugins/jetpack/extensions/blocks/videopress/resumable-upload/index.js
projects/plugins/jetpack/extensions/blocks/videopress/resumable-upload/use-uploader.js

Fixes a bug where resumable video uploads were not properly setting the attachment id and/or src, which the block expects to receive as attributes. We noticed that some block settings were not saving properly, due to the missing `id`.
_Note: This is currently only an issue on wpcom simple sites for Automatticians._
* Sets the `id` and `src` attributes when selecting a video from the media library.
* Also sets the `id` and `src` attributes after a resumable upload completes.
pxWta-16I-p2
No
* You must test this on your wp.com sandbox on a site that has VideoPress enabled (Premium plan or better)
* Apply D76041-code to your sandbox, and also apply D76039-code ( `arc patch D76039 --nobranch` )
* Create a new post in Gutenberg and add select a video from the media library.
* Open the block …

VideoPress: Fix missing block attributes when using resumable uploads

---

projects/plugins/jetpack/_inc/client/dashboard-widget/style.scss
projects/plugins/jetpack/changelog/fix-remove-duplicate-svg-logo
projects/plugins/jetpack/class-jetpack-stats-dashboard-widget.php

The Jetpack logo that was added to the dashboard stats widget gets loaded several times on the same page, and was causing performance and accessibility issues. The logo gets attached to the move up & down, and toggle widget buttons. 
For that reason, screen readers read buttons as "Move Stats by box up...". 
This issue is also related to the broken Screen options issues mentioned  here: https://github.com/Automattic/jetpack/pull/22812
Fixes #22669
* Removed the logo from the dashboard widget title. The title is now plain text "Stats by Jetpack".
* Created a new widget footer section and added the logo there to keep the branding consistency. 
* Added Configure Stats and Learn More links to the new footer section.
* Applied styles from the Jetpack dashboard to the blocked numbers in the …

Stats: removed the logo form dashboard widget title

---

projects/plugins/boost/app/assets/src/js/pages/settings/elements/Module.svelte
projects/plugins/boost/app/assets/src/js/pages/settings/sections/Modules.svelte
projects/plugins/boost/app/assets/src/js/utils/cloud-css.ts
projects/plugins/boost/changelog/update-clear-cloud-css-status-poll

Fixes #23263
* Add an event handler for module `disabled`.
* Stop polling cloud CSS status if the module is disabled.
N/A
No
* Open dev-tools on browser and monitor the network tab.
* Enable(or disable and re-enable) the cloud CSS module.
* Once it is enabled, notice that cloud CSS status is polling (`GET wp-json/jetpack-boost/v1/cloud-css/status`).
* Disable the module.
* The requests going out to the polling URL should stop once the module is disabled.

Boost: clear cloud CSS status poll

---

pnpm-lock.yaml
projects/plugins/boost/changelog/update-critical-css-lib
projects/plugins/boost/package.json

Taking in https://github.com/Automattic/jetpack-boost-critical-css-gen/issues/26
* Use release 0.0.4 of jetpack-boost-critical-css-gen
N/A
no
* Create a [webpage that would produce critical CSS with keyframe](https://gist.github.com/eAdnan007/f7d2bbf2a7990d2ef3e088654cbcc9cd)
* Generate Critical CSS for that page and make sure no @keyframe rules are present.

Update critical CSS generation library to 0.0.4

---

projects/plugins/boost/app/features/optimizations/cloud-css/Cloud_CSS.php
projects/plugins/boost/app/features/optimizations/critical-css/Critical_CSS.php
projects/plugins/boost/app/lib/critical-css/Admin_Bar_Compatibilty.php
projects/plugins/boost/changelog/fix-boost-admin-bar

When loading a site as a logged-in user, the admin bar can sometimes appear as a full screen FOUC when using Critical CSS.
In previous versions of Boost, we mitigated this by pushing the admin bar's HTML elements down to the footer - so that they are only brought up to the head of the page via CSS styles.
However, when we refactored our Critical CSS classes this got left out.
This PR reinstates our admin-bar compatibility fix for Critical CSS.
* Reinstate calls to admin-bar compatibility classes.
n/a
no
* Generate Critical CSS for your site
* Visit your homepage as a logged in user
* Verify the admin bar looks ok, there is no FOUC, and the admin bar's div is near the footer in the HTML source.

[Boost] Defer admin bar

---

projects/plugins/jetpack/changelog/add-stripe-connect-to-payment-button-blocks
projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx
projects/plugins/jetpack/extensions/blocks/recurring-payments/index.js
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/fixtures/jetpack__recurring-payments--with-color-attrs__deprecated-1.serialized.html
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/fixtures/jetpack__recurring-payments--with-custom-color-attrs__deprecated-1.serialized.html
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/fixtures/jetpack__recurring-payments.html
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/fixtures/jetpack__recurring-payments.json
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/fixtures/jetpack__recurring-payments.parsed.json
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/fixtures/jetpack__recurring-payments.serialized.html

Now the InnerBlocks of the Payment Button block is able to connect Stripe.
Fixes [#61422](https://github.com/Automattic/wp-calypso/issues/61422)
* Propagated the block controls to it's children using the `__experimentalExposeControlsToChildren` Gutenberg supports attribute.
The `__experimentalExposeControlsToChildren` does not support choosing a subset of controls to inherit. In order to avoid having alignment controls twice on the child blocks, I've removed support for aligning on the Payment Button block. We can still align the buttons as we did before, the only difference will be that the main block won't have this option. I don't anticipate this being a blocker since the component maintains all its previous functionality. If someone has a strong opinion, we should tackle it on a …

Payment Button Block: InnerBlocks have the ability to connect Stripe

---

projects/plugins/jetpack/changelog/add-payments-block-support-reference
projects/plugins/jetpack/extensions/blocks/recurring-payments/index.js

Fixes [#61420](https://github.com/Automattic/wp-calypso/issues/61420)
* Added a link to the block reference/documentation.
1. Create or Edit a post.
2. Add a Payments Button block.
3. You should see a link to the support reference.
4. Click on the link
5. WPCom support page should be shown.
1. Create or Edit a post.
2. Add a Payments Button block.
3. You should see a link to the support reference.
4. Click on the link
5. Jetpack support page should be shown.
https://user-images.githubusercontent.com/1989914/156579541-09c533da-894f-4d48-ad1a-353443c0a3c7.mp4

Payments Button Block: Add payments block support reference link

---

projects/plugins/jetpack/changelog/fix-payment-block-upgrade-message-obscured
projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/editor.scss

Fixes [#61419](https://github.com/Automattic/wp-calypso/issues/61419)
Currently, the upgrade nudge interferes with the block controls, this PR solves the issue.
* The necessary rules were already in place, we just had to create a rule with more specificity so that the default wp-core behavior can be overridden without the need to use `!important`.
* This PR fixes the issue not only for the Payment Block but for all the blocks that require/show the upgrade nudge.
* Create or Edit a new Post
* Add any/all the blocks that require an upgraded subscription.
* You shall see that the block controls are shown without interfering with the upgrade nudge.
#### Test evidence
https://user-images.githubusercontent.com/1989914/156790069-dbf6c875-e5d9-46a8-8bb6-4974ae0df0e5.mp4

Payment Block: fix payment block upgrade message obscured

---

projects/plugins/jetpack/changelog/add-jetpack-upload-handler-can-upload-filter
projects/plugins/jetpack/changelog/add-upload-block-filter
projects/plugins/jetpack/class.jetpack.php

Related to #https://github.com/Automattic/wp-calypso/issues/51594
* Add a new filter which can be used to block uploads processed by remote_request_handlers() -> upload_handler() 
*  For example, a WP.com user using calypso to upload to a Jetpack or Atomic site
An example use of the filter is 832-gh-Automattic/wpcomsh . This prevents WoA users from using `https://wordpress.com/media/<site>` to upload files to their site, if that upload would take them over disk quota. Currently, this upload path goes through  `(wpcom) upload_jetpack_files() -> Jetpack_Client::upload_files() --> curl` `--http-->` `(jetpack) do_action 'wp_ajax_nopriv_jetpack_upload_file' -> remote_request_handlers() -> upload_handler()`. No file upload size checking is done in this path, as far as I can tell.  Adding the …

Add filter for optional blocking of file uploads in upload_handler()

---

projects/plugins/jetpack/changelog/update-qr-registration
projects/plugins/jetpack/class.jetpack-plan.php
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/post-publish-qr-post-panel.php

Follow-up to #23281
﻿Since the plugin will be free for everyone, we do not need to check for a plan in the process.
Discussion: https://github.com/Automattic/jetpack/pull/23281#discussion_r821477445
This will also avoid having to update things on WordPress.com's end to declare support for the new plugin there.
* N/A
* No
* Publish a new post
* You should see the QR post-publish panel.

QR Plugin: update plugin registration

---

projects/plugins/jetpack/changelog/update-rjetpack-render-qr-post-code-in-sidebar
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/index.js

This PR renders the QR code for the post in the sidebar once the post is published.
Fixes https://github.com/Automattic/jetpack/issues/23276
* Jetpack: render QR Code once the post is published
* Publish
* Confirm you see the QR Code rendered in the post-publish sidebar
* Confirm the QR code leads to the published post
https://user-images.githubusercontent.com/77539/157245088-1c878390-99f6-467b-bd86-0562da1edccc.mov

Jetpack: render QR Code once the post is published

---

projects/packages/my-jetpack/_inc/hooks/use-analytics/index.js
projects/packages/my-jetpack/changelog/add-referring-plugins-to-tracks

Fixes #23169 
* Add a new property to My Jetpack tracking events containing the slugs of the connected plugins
N/A
Yes. It adds an additional property to the tracking events triggered by My Jetpack. This property contains the slugs of all the plugins from the Jetpack family that are being powered by the Jetpack connection
* Enable debigging for tracks typing `localStorage.setItem( 'debug', 'dops:analytics*' );` in your console (if you haven't done this before) 
* Click the buttons
* Make sure the events triggered (and logged into the console) contain a new `referral_plugins` property
* Make sure the value of the property correclty matches the active jetpack plugins
* Is the property name good?
* The value should always be a list of the jetpack plugins slugs without the …

My Jetpack: Add connected plugins to tracking events

---

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-settings-page.php
projects/plugins/jetpack/changelog/fix-admin_pages_filesystem_error

WP_Filesystem is not needed when reading files that are a part of the plugin.
Fixing a bug introduced in #23219 related to the usage of WP_Filesystem.
Discussion in: 
* p1646733934456429-slack-CBG1CP4EN
* p1646740974319369-slack-C02HQGKMFJ8
* Reverted using WP_Filesystem to file_get_contents.
none
no
* E2E test shouldn't fail.
* Try loading admin pages in e2e environment.

Admin: reverted using WP_Filesystem to file_get_contents

---

projects/js-packages/connection/changelog/update-fix-login-link-connection-card
projects/js-packages/connection/components/connect-screen/required-plan/test/component.jsx
projects/js-packages/connection/components/connect-screen/required-plan/visual.jsx

Fixes #23286
Addressed partially #23055
* Updates the label for the ActionButton on the ConnectScreenRequiredPlanVisual to read "Log in to get started" instead of "Log in"
* Updates related test
p1HpG7-ePH-p2#comment-52499
2. On a site connected but with disconnected user, and the Jetpack backup plugn installed, visit the Jetpack backup admin page
3. Confirm the "Log in to get started" is a full link"
4. Click it to connect
5. Expect to see the whole sentence switch to a spinner

Connection: ConnectScreenRequiredPlanVisual  Update login in link-button label from "Log in" to "Log in to get started"

---

projects/packages/codesniffer/Jetpack/ruleset.xml
projects/packages/codesniffer/changelog/update-phpcs-wpcom

- Use the generic WordPress ruleset to match WP.com
The docs read to me that the generic WordPress ruleset just add a combo of other rules, but apparently, it has its own sniffs too. Adding this to match what WP.com has.
* Adds WordPress ruleset
n/a
No.
* See how mad the CI gets.

PHPCS: Add WordPress ruleset

---

projects/plugins/boost/app/assets/src/js/utils/analytics.ts
projects/plugins/boost/changelog/fix-check-for-tracks

Fixes #22443
* Check if tracks library is present before using it
N/A
No
* Dequeue tracks library
* Try to generate critical CSS
* See if it succeeds

Boost: check for tracks

---

.github/files/test-plugin-update/mu-plugin.php
.github/files/test-plugin-update/prepare-zips.sh
.github/files/test-plugin-update/setup.sh
.github/files/test-plugin-update/test.sh
.github/workflows/build.yml

After several problems with plugin upgrades failing since #23039, we
need a more robust CI test for plugin upgrades failing.
For each plugin built, this will test upgrading via the web UI and
wp-cli, from the latest stable (if any) and from the built version to a
hypothetical future version.
p9dueE-4Bm-p2
Related to p9dueE-4zF-p2 
No
* Are the existing Build jobs happy?
* Is the new job happy too?
* Submit a PR based on this one that reverts #23253 or #23246 or #23207. Does the new job fail on it with a reasonable message?
* :heavy_check_mark: https://github.com/Automattic/jetpack/actions/runs/1947464089
* Submit a PR based on this one that doesn't build any plugins. Make sure the workflow works right.
* :heavy_check_mark: https://github.com/Automattic/jetpack/actions/runs/1947473452

actions: Test upgrading of built plugins

---

projects/plugins/boost/app/rest-api/endpoints/Recommendations_Dismiss.php
projects/plugins/boost/changelog/fix-deprecation-warnings
projects/plugins/jetpack/changelog/fix-deprecation-warnings
projects/plugins/jetpack/modules/markdown/easy-markdown.php

PHP 8.1 deprecates the `FILTER_SANITIZE_STRING` constant. We only reference it in two places; a no-longer-used method `WPCom_Markdown::get_post_screen_post_type()` method, and in Jetpack Boost's Recommendation dismissal API endpoint.
This PR cleans up both instances, and additionally marks `WPCom_Markdown::get_post_screen_post_type()` as deprecated to verify it can safely be removed in future versions of Jetpack.
* Replace `FILTER_SANITIZE_STRING` with `FILTER_UNSAFE_RAW` in `WPCom_Markdown::get_post_screen_post_type()`
* Mark `WPCom_Markdown::get_post_screen_post_type()` as deprecated.
* Replace `FILTER_SANITIZE_STRING` with `sanitize_title` in the Boost recommendation dismissal API endpoint.
n/a
no
* Ensure you can still delete Critical CSS recommendations in Jetpack Boost.

Fix deprecation warnings from PHP 8.1

---

projects/plugins/jetpack/changelog/fix-publicize-isset-check
projects/plugins/jetpack/modules/publicize/publicize-jetpack.php

Fixes an error with the Publicize settings page in Jetpack showing a warning with `WP_DEBUG` enabled.
* Add missing isset check.
N/A
No.
* Enable `WP_DEBUG`: `define( 'WP_DEBUG', true )`
* Go to Jetpack > Sharing settings (https://example.com/wp-admin/options-general.php?page=sharing)
* Verify there's no visible warning

Publicize: Add missing isset check

---

projects/packages/sync/changelog/update-search-taxonomy-allow-list
projects/packages/sync/src/class-package-version.php
projects/packages/sync/src/modules/class-search.php

ETB requires additional taxonomies to be synced for usage in filters of Jetpack Search. The definitive allow list is maintained in WP.com and updated in D76393. This PR updates the Jetpack mapping which is for informational purposes to users until we update WP.com to use the Jetpack package directly.
Fixes # https://wp.me/p9MPsk-X0
* Update the taxonomy allow list to include ETB custom taxonomies
No changes to synced data.
* N/A. Unit Testing is sufficient.

Jetpack Search :: Add ETB taxonomy to allowed list.

---

projects/plugins/jetpack/_inc/client/components/support-card/index.jsx
projects/plugins/jetpack/_inc/client/recommendations/index.jsx
projects/plugins/jetpack/changelog/add-support-liknks-jetpack

Fixes #23266
Fixes #23267
* Introduces a support button on the dashboard linking to the getting started page
* Introduces 2 links at the botton of the recommendatios card linking to the getting started page and the supported page respectively
* pcKp4R-9E-p2
* Design: p1HpG7-eji-p2 (**check the Accepted answer**)
pcKp4R-9E-p2
Yes. Introduces a few events
2. Visit the dashboard
Confirm the first button points to the getting started page
4. Visit the Recommendations tab
Confirm the first links points to the getting started page and the second one to the Jetpack support page.

Jetpack: Dashboard/Assistant - Add support links

---

projects/plugins/jetpack/_inc/client/state/connection/actions.js
projects/plugins/jetpack/changelog/fix-restore-connection-missing-button

* adjust the Jetpack state to mark user as unlinked after it's been unlinked during connection restore
p9F6qB-7xg-p2
No.
1. Connect Jetpack.
2. Set invalid blog and user tokens.
3. Go to Jetpack Dashboard, you should see the error notice with "Restore Connection" button.
4. Click "Restore Connection". After a little wait, you should see the connection screen. Confirm that the "Connect Your User Account" button shows up.
5. Finish the connection flow, confirm it works correctly.

Jetpack: fix missing "Connect User" button after connection restore.

---

projects/plugins/jetpack/changelog/update-fix-flaky-sync-test
projects/plugins/jetpack/tests/php/sync/test_interface.jetpack-sync-replicastore.php

Fixes flaky `test_checksum_histogram` Jetpack Sync test.
* Fixes a logic error in `test_checksum_histogram`: When randomly generating comments, instead of checking the current comment id exists in the array of generated comments, we were checking for the post id instead.
1201642007924219-as-1201934645546364/f
No
Look at the code and make sure the proposed changes are sane.

Sync test: Remove random logic from test_checksum_histogram

---

projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
projects/plugins/jetpack/changelog/fix-extend-filtering-admin-pages

In #23219 I added wp_kses() to filter  the contents of static.html page using 'post' as a default context. This caused  a code flash like this:  
Discussed here: p1646849281583459-slack-C02HQGKMFJ8
* Used wp_kses_allowed_html to extend the filter with 'style' tag.
* Go to any admin page and scroll to the bottom of the page. 
* You shouldn't see the .vp-deactivated show up.
I'm not sure this is the right way to go about this. Pinging @anomiex and @jeherve as you have already helped me with this code.

Admin pages: remove extra filtering

---

projects/plugins/jetpack/changelog/update-jetpack-qr-post-in-jetpack-sidebar
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/index.js

Fixes https://github.com/Automattic/jetpack/issues/23331
* Jetpack: Add QRPost code to Jetpack sidebar
No
* Go to add a new post
* Confirm the Jetpack sidebar does not have the QR Post panel
* Create, save and publish the post
* Confirm now the Jetpack sidebar shows the QR Post panel
https://user-images.githubusercontent.com/77539/157541955-26937415-bb4d-4eee-aa82-2b562494dcf5.mov

Jetpack: Add QRPost code to Jetpack sidebar

---

projects/github-actions/repo-gardening/changelog/fix-repo-gardening-changelog-check
projects/github-actions/repo-gardening/src/get-files.js

We've long had a problem where the "add changelog entries" check was
incorrectly detecting that no change entry was added. Looking into this,
I find that it seems to always be release PRs, where GitHub is detecting
the removed change files as being renamed into a different project.
The fix is to have our `getFiles()` function record both the old and new
names of renamed files so they can be properly considered.
Nothing specific
No
* You could run the following two commands, which should produce the same output
* `git -c core.quotepath=off diff --no-renames --name-only 5774b9d^...5774b9d | sort`
* Assuming TOKEN in the environment holds a GitHub access token and you're in the repo-gardening directory, `node -e 'process.env.NODE_ENV="test"; const { getOctokit } = require( "@actions/github" …

repo-gardening: Consider both old and new names of moved files as modified

---

projects/plugins/jetpack/changelog/update-fix-sync-flaky-unit-test
projects/plugins/jetpack/tests/php/sync/test_interface.jetpack-sync-replicastore.php

Fixes the `WP_Test_IJetpack_Sync_Replicastore::test_strips_non_ascii_chars_for_checksum` flaky test.
* Updates `test_strips_non_ascii_chars_for_checksum` sync test to remove the flakiness caused by comparing checksums for 2 posts with potentially different `post_modified` fields.
p1646953394702879-slack-C034JEXD1RD
No
Looking at the code should be enough.

Jetpack Sync tests: Fix flaky test_strips_non_ascii_chars_for_checksum

---

projects/plugins/jetpack/changelog/update-jetpack-qr-post-remove-title-from-qr-content
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/components/qr-post.js

Currently, we are using post title and post permalink to generate the QR code. This PR removes the title and uses only the permalink that, in the end, is what we need to lead the user to the post page.
Fixes https://github.com/Automattic/jetpack/issues/23372
* Jetpack: QRPost: use only permalink to generate QR code
No
* Test the QRPost feature as usual
* Everything should work as expected

Jetpack: QRPost: use only permalink to generate QR code

---

projects/plugins/jetpack/changelog/fix-videopress-resumable-upload-id-type
projects/plugins/jetpack/extensions/blocks/videopress/resumable-upload/use-uploader.js

Additional follow-up from https://github.com/Automattic/jetpack/pull/23226
Fixes an issue when using resumable VideoPress uploads where the block's `id` was incorrectly set with a string data type, causing the id to be lost when the page was reloaded due to a type mismatch.
* Convert the `mediaId` passed down when a resumable upload succeeds to a `Number` so that the `id` will be saved and restored properly.
pxWta-16I-p2
No
* Enable Jetpack VideoPress
* Add this code at line 235 of `class.videopress-gutenberg.php` to enable resumable uploads:
`wp_add_inline_script( 'jetpack-videopress-gutenberg-override-video-upload', 'var videoPressResumableEnabled = true;' );`
* Upload a new video to the block editor, it should use the resumable uploader.
* Switch to the `Code editor` mode, and the …

VideoPress Block: Fix issue where id attribute was not restoring properly when using resumable uploads

---

projects/plugins/jetpack/changelog/update-videopress-resumable-uploader-design
projects/plugins/jetpack/extensions/blocks/videopress/resumable-upload/index.js
projects/plugins/jetpack/extensions/blocks/videopress/resumable-upload/style.scss

Updates the design of the resumable uploader based on some design feedback from @evilluendas:
* Changes `Video` label to `VideoPress`
* Tighter margin between text and progress bar
* Rounded progress bar with 8px height
* File size moved to the left side with an `emdash` added between it and the file name.
pxWta-16I-p2
No
* Enable Jetpack VideoPress
* Add this code at line `235` of `class.videopress-gutenberg.php` to enable resumable uploads: 
`wp_add_inline_script( 'jetpack-videopress-gutenberg-override-video-upload', 'var videoPressResumableEnabled = true;' );`
* Add a video in the block editor.
* Observe that the new styles look good and the block still works as expected.

VideoPress: Design tweaks for resumable uploader

---

projects/plugins/social/README.md
projects/plugins/social/changelog/fix-jetpack-social-admin-page
projects/plugins/social/composer.json
projects/plugins/social/readme.txt
projects/plugins/social/src/js/components/admin-page/index.jsx

Follow-up to #23395
Fixes Admin page not loading
* Updates initial state variable name
* Updates README files references to old name
* Update composer.json file `autoloader-suffix`.
no
2. Build Jetpack Social with `jetpack build plugins/social`
3. Confirm the admin page for Jetpack Social works

Social: Fix admin page (and remaining references to Reach)

---

projects/packages/my-jetpack/changelog/remove-my-jetpack-beta-badge
projects/packages/my-jetpack/src/class-initializer.php

Removes beta Badge from My Jetpack menu item
<table>
<tr>
<td>
Before<br/>
<td>After<br/>
</table>
* Removes the Beta indicator from the menu item for My Jetpack
no
* Checkout this branch on a connected site
* Confirm the beta badge for My Jetpack on the sidebar is gone

My Jetpack: Remove beta badge from  menu item

---

projects/plugins/jetpack/changelog/update-jetpack-qr-block-open-in-a-modal
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/components/image-actions-panel-row.js
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/components/qr-post.js
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/editor.scss
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/index.js
projects/plugins/jetpack/extensions/plugins/post-publish-qr-post-panel/utils/handle-download-qr-code.js

This PR renders the QR code of the post into a modal component.
before | after
------|------
Fixes Jetpack: Render QRPost into a modal component
* Jetpack: Render QRPost into a modal component
* Create a new post or edit a published post
* Confirm you see the `Get QR code` button in both sidebars (post publish and Jetpack)
* Confirm the QR code shows in a modal by clicking on the button mentioned above
* Confirm you can view and download the qr code image
https://user-images.githubusercontent.com/77539/157935403-ae209337-1160-405c-8623-05a84b7f0bf2.mov

Jetpack: Render QR Post into a modal component

---

.github/files/lint-project-structure.sh
composer.lock
projects/packages/codesniffer/changelog/fix-lint-for-dev-deps
projects/packages/codesniffer/composer.json
projects/plugins/social/changelog/fix-lint-for-dev-deps
projects/plugins/social/composer.json
projects/plugins/social/composer.lock

Certain composer dependencies on dev versions of packages cause
problems. Lint for those so people can't accidentally add them.
The problematic cases are:
- Any project committing `composer.lock` has a dep on a dev version of
something that isn't anchored to a specific git ref.
- Any composer package has a non-dev dep on a dev version of something,
even if anchored to a specific git ref.
- Monorepo-internal deps are always an exception to the above.
Then fix two cases that trip the new lint check:
- plugins/social needs to depend on a release version of WorDBless, like
plugins/boost does.
- packages/codesniffer needs to adjust its dep on wp-coding-standards/wpcs
dev-develop so reusers aren't forced to do the alias dance.
None
No
* Is CI happy?
* Try reverting some of the project changes, …

linting: Lint for problematic composer dev deps

---

projects/plugins/boost/app/assets/src/css/admin-style.scss
projects/plugins/boost/app/assets/src/css/components/badge.scss
projects/plugins/boost/app/assets/src/js/pages/settings/sections/Modules.svelte
projects/plugins/boost/changelog/update-cloud-css-feature-copy

Fixes #23321
* Add upgraded badge on cloud CSS feature
* Change cloud CSS feature title
* Change cloud CSS feature description
N/A
No
* Define `JETPACK_BOOST_CLOUD_CRITICAL_CSS` as `true`.
* Visit Boost settings page.
* Check if the "Upgraded" badge is visible and the text reflect changes.

Boost: Update cloud css feature copy

---

projects/plugins/jetpack/changelog/fix-show-premium-content-after-subscribe
projects/plugins/jetpack/extensions/blocks/premium-content/login-button/login-button.php
projects/plugins/jetpack/extensions/blocks/premium-content/premium-content.php

Fixes [#23135](https://github.com/Automattic/jetpack/issues/23135) & 458-gh-Automattic/payments-shilling
* Now when a user finishes the subscription process he is able to see the premium contents.
* Sandbox the store (Recommended).
* View as a user a post that has a premium content block (make sure you aren't logged in).
* Click on the subscribe button and complete the subscription process.
* Close the subscription window, you should see the premium content.
* The best way to test this scenario is to add an invalid token as a parameter.
* Get the post URL and token=invalid
* Open the URL
* You should not see the login button and see the subscribe button.
* You should not see the premium content.

Premium Content Block: show premium content after subscribe

---

docs/git-workflow.md

* Adding information under ['Keeping your Branch up-to-date'](https://github.com/Automattic/jetpack/blob/master/docs/git-workflow.md#keeping-your-branch-up-to-date) to include Git commands relevant to merging and rebasing into a parent PR instead of master.
n/a
No.
* Do the steps under ['Keeping your Branch up-to-date'](https://github.com/Automattic/jetpack/blob/master/docs/git-workflow.md#keeping-your-branch-up-to-date) read well or does this additional change over-complicate the suggested process?

Docs: Adding minor Git workflow edits for the Git Workflow doc

---

.github/workflows/build.yml

While this step usually takes only a second or two, increasingly often
lately it has instead been taking around 60. Bump the timeout to avoid
failed jobs.
I also filed a ticket with GitHub to ask if that's expected behavior.
p1647338557374969-slack-C034JEXD1RD and a few previous
No
* Nothing really to test.

build: Increase timeout on download-artifact action

---

projects/plugins/jetpack/changelog/fix-remove-obsolete-strptime
projects/plugins/jetpack/modules/videopress/class.videopress-video.php

The PHPCompatibility check recently started warning that strptime is
deprecated in PHP 8.1. The only use was in a branch that was kept for
compatibility with PHP 5.2, back when we still supported that version.
None
No
* ???

jetpack: Remove old PHP 5.2 compatibility code

---

projects/plugins/jetpack/changelog/fix-resumable-uploader-core-styles
projects/plugins/jetpack/extensions/blocks/videopress/resumable-upload/style.scss

Fixes: https://github.com/Automattic/wp-calypso/issues/61983
Setting the default `color` and `font-family` for the component fixes the issue where a theme could apply a different text color or font.
Before:
After:
* CSS Fixes
pxWta-16I-p2
No
* Apply diff to wp.com sandbox.
* Install the `Kingsley` theme.
* Add a resumable upload to a post, the text color should be black and the font should be the default for the block editor.

VideoPress: Fix broken styles in resumable uploader component

---

.github/actions/tool-setup/action.yml

The main thing here is changing the call to actions/setup-node to pass a
version like `^16.13.2` instead of `16.13.2`. It turns out that action
wastes API calls if given an explicit version that isn't one of the ones
in GitHub's cache (and GH currently has 16.14.0 cached rather than
16.13.2), and this can be avoided with the caret-range.
This also does some other cleanup:
* GH has improved the logging output for compound actions, we probably
don't need the sectioning printfs anymore.
* For run steps, add a comment as the first line for better output.
* Let actions/setup-node set up the pnpm caching instead of manually
calling actions/cache.
None
No
* Check the appropriate steps of some of our workflow jobs using the action.
* :heavy_check_mark: It should be pulling in Node 16.14.0 from …

actions: Improve the "tool setup" action

---

composer.lock
projects/packages/assets/changelog/fix-composer-dep-or
projects/packages/assets/composer.json
projects/packages/changelogger/changelog/fix-composer-dep-or
projects/packages/changelogger/composer.json
projects/packages/changelogger/src/Application.php
projects/packages/ignorefile/changelog/fix-composer-dep-or
projects/packages/ignorefile/composer.json
projects/plugins/always-use-jetpack-open-graph/changelog/fix-composer-dep-or
projects/plugins/always-use-jetpack-open-graph/composer.lock
projects/plugins/backup/changelog/fix-composer-dep-or
projects/plugins/backup/composer.lock
projects/plugins/beta/changelog/fix-composer-dep-or
projects/plugins/beta/composer.lock
projects/plugins/boost/changelog/fix-composer-dep-or
projects/plugins/boost/composer.lock
projects/plugins/debug-helper/changelog/fix-composer-dep-or
projects/plugins/debug-helper/composer.lock
projects/plugins/jetpack/changelog/fix-composer-dep-or
projects/plugins/jetpack/composer.lock
projects/plugins/search/changelog/fix-composer-dep-or
projects/plugins/search/composer.lock
projects/plugins/social/changelog/fix-composer-dep-or
projects/plugins/social/composer.lock
projects/plugins/vaultpress/changelog/fix-composer-dep-or
projects/plugins/vaultpress/composer.lock

Composer prefers `||`, and renovate doesn't seem to support `|`. So
switch to `||` in the places where we had `|`.
None
No
* Is CI happy?

Use `||` rather than `|` in composer.json

---

projects/packages/sync/changelog/update-sync-dedicated-sync-setting
projects/packages/sync/src/class-defaults.php
projects/packages/sync/src/class-package-version.php
projects/plugins/jetpack/changelog/update-sync-dedicated-sync-setting
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-sender.php

Sync: Enable syncing of dedicated_sync_enabled setting
* Adds `jetpack_sync_settings_dedicated_sync_enabled` to Sync whitelisted options
No
D77031-code

Sync: Enable syncing of dedicated_sync_enabled setting

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-product-card-theme

Keep the movement out of `base-styles` using `design tokens` provided by `ThemeProvider` and `Text` component.
* Move texts to use `Text` component.
* Update styles to use `design tokens`.
N/A
No.
* Open `My Jetpack` page.
* Product Card should have no visual effect (*except for the title, since it was using the wrong weight for it variant)

My Jetpack: Usage of `Text` and design tokens at `ProductCard`

---

projects/plugins/jetpack/changelog/update-api-allow-video-uploads
projects/plugins/jetpack/class.json-api-endpoints.php

Updates `class.json-api-endpoints.php` with changes from D76475-code. These changes only affect WP.com, since [we bail the `allow_video_uploads` check for self-hosted Jetpack sites](https://github.com/Automattic/jetpack/blob/c58670b53bef25f41e03dc8b8b0939ff1b09851d/projects/plugins/jetpack/class.json-api-endpoints.php#L2344-L2347).
N/A.
No.
Not needed, since changes have been already tested in D76475-code and they only affect WP.com.

VideoPress: Update API endpoint with new feature check function

---

.github/files/test-plugin-update/test.sh

In #23076 we ran into some errors during plugin uninstall, which
produced unhelpful output. We should catch those errors to produce
helpful output instead.
None really.
No
* Check the run of the job in this PR where it was based on #23076 rather than master.
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/5630770699?check_suite_focus=true

actions: Handle uninstall errors in plugin upgrade test

---

projects/github-actions/pr-is-up-to-date/funcs.sh
tools/cli/commands/changelog.js

When someone runs `jetpack changelog add`, the auto-adder prompts if you want to add the changelog files automatically if it finds projects that need one. Previously if you declined, it would default to interactive mode. This changes the behavior so it just stops the process, since it's not very clear that saying no would default you to interactive mode at all.
https://github.com/Automattic/jetpack/pull/23359#issuecomment-1070997218
No
* Make a change to a project
* Run `jetpack changelog add`
* saying yes should give you the prompts as usual
* saying no should exit the changelogger altogether (instead of defaulting to interactive mode)
*

CLI: Change Changelogger Auto-add behavior

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-add-error-style-to-product-card

This PR adds error styles to the whole Product card component, according to the design feedback:
before | after
----|----
Fixes https://github.com/Automattic/jetpack/issues/23518
Related with https://github.com/Automattic/jetpack/issues/23483
* My Jetpack: add error styles to the whole Product card component
* Use storybook
* Go to Product Card story http://localhost:50240/?path=/story/packages-my-jetpack-product-card--default
* Set the error status
* Confirm you see the red border around the product card

My Jetpack: add error styles to the whole Product card component

---

docs/monorepo.md
docs/quick-start.md
docs/yarn-upgrade.md
package.json
tools/cli/README.md
tools/cli/commands/cli.js

pnpm cli-setup seems flaky at best, but `pnpx jetpack cli link` seems to always work. Should we prefer that in our docs and processes?
* Update various things to use pnpx instead.
Various.
No.
* On a fresh system, try `pnpm install && pnpx jetpack cli link`
* `jetpack cli status` -- does it work?

CLI: Prefer pnpx jetpack cli link

---

projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/_inc/components/plans-section/style.module.scss
projects/packages/my-jetpack/changelog/fix-plan-section-margin-top-my-jetpack

Fixes margin between section title and plan title
Follow-up to #23493 for addressing #23489 and #23512
<table>
<tr>
<td>Before<br/>
<td>After<br/>
</table>
Fixes #
* Adds a 16px top margin to the purchases section
none
* Checkout this branch on a connected Jetpack site with at least one plan.
* Visit My Jetpack and confirm there's a margin below the "Your plan" header

My Jetpack: Update Plans section top margin for plan list

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-update-card-buttons

This PR changes the action buttons of the Product Card according to the design feedback,
p1HpG7-fbl-p2#comment-53119
before | after
------|------
Fixes https://github.com/Automattic/jetpack/issues/23483
* My Jetpack: Replace Manage button with a simple button (no more dropdown). Disconnect button is removed, too.
Yes. We stop firing the `jetpack_myjetpack_product_card_deactivate_click` event
* Use storybook
* Go to Product Card story http://localhost:50240/?path=/story/packages-my-jetpack-product-card--default
* Change the status
* Confirm you see the changes in the Manage button
------------
* Go to My Jetpack overview
* Confirm you can activate the product for those inactive ones
* Confirm you see a (secondary) manage button for active products
* Confirm the manage button leads to the …

My Jetpack: change action buttons of the Product card

---

projects/plugins/jetpack/changelog/add-shortlinks-support-editor
projects/plugins/jetpack/modules/shortlinks.php

Fixes #12934
* We currently only add the Shortlinks interface in the block editor for a few hardcoded post types. Since site owners can declare shortlinks support in their own post types, we should ensure the shortlinks interface is displayed when editing those custom post types as well.
* N/A
* No
* Go to Jetpack > Settings, and enable the Shortlinks feature.
* Go to Posts > Add New, save a draft, and ensure you see the shortlinks interface in the Jetpack plugin sidebar.
* Go to Plugins > Add New and add the Code Snippets plugin.
* Create a new snippet where you'll paste a random post type you'll have created [here](https://generatewp.com/post-type/).
* In that post type snippet, add 2 things:
* In the `supports` declaration, add both `shortlinks` and `editor`.
* Add the `show_in_rest` …

Shortlinks: ensure the block editor shows for CPTs.

---

tools/e2e-commons/config/default.cjs

The warning `Warning: getDefaultProps is only used on classic React.createClass definitions` is displayed in console and it pollutes our e2e tests logs. With this PR the warning will be ignored by our logger.
1156386383419466-as-1201996635281920
no
* Tests pass in CI
* Check e2e-debug log, it should not contain the ignored string

E2E tests: ignore getDefaultProps console warning

---

projects/packages/my-jetpack/changelog/update-my-jetpack-should-initialize-filter
projects/packages/my-jetpack/src/class-initializer.php

Currently the filter gets superseded by the connection. It's expected that setting the filter manually should be the final decider on whether it should load. 
Minor refactor of should_initialize() to respect `jetpack_my_jetpack_should_initialize` when set to true and not connected. 
N/A
No
With filters: 
- `add_filter( 'jetpack_my_jetpack_should_initialize', '__return_true' );` When the site is not connected should show My Jetpack. 
- `add_filter( 'jetpack_my_jetpack_should_initialize', '__return_false' );` When the site is connected should not show My Jetpack. 
No filter applied: 
- When not connected, no My Jetpack
- When connected, My Jetpack.

My Jetpack: Fix jetpack_my_jetpack_should_initialize filter to respect when set to true. 

---

projects/packages/sync/changelog/fix-dedicated-sync-retry-after
projects/packages/sync/src/class-dedicated-sender.php
projects/packages/sync/tests/php/test-dedicated-sender.php

Fixes a logic error in the Dedicated Sync flow:
When checking whether we should spawn the Dedicated Sync request we used to return an error if the corresponding `Retry-After` option was set.
This option is set when WPCOM sends us a `Retry-After` header in the response, however when checking it's possible that this is already expired.
If that's the case we need to actually spawn the Dedicated Sync request so that the corresponding option get's cleared.
* `Dedicated_Sender::spawn_sync`: Allow spawning the Dedicated Sync request if Retry-After is expired.
No
**Before**
- In a connected JN site set this option to a past timestamp, aka `wp option update jp_sync_retry_after_sync 1648027252.236685`
- Enable Dedicated Sync `wp option update jetpack_sync_settings_dedicated_sync_enabled 1`
- …

Dedicated Sync: Allow spawning request with expired Retry-After

---

projects/plugins/jetpack/changelog/update-extensions-documentation
projects/plugins/jetpack/extensions/README.md

* Changing the information under ['How do I merge extensions to WordPress.com?'](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/README.md#how-do-i-merge-extensions-to-wordpresscom) to explain more about the impact of release schedules when merging new features to WordPress.com.
p1647957549560379/1647508512.415689-slack-CBG1CP4EN
No.
* Check that the wording under ['How do I merge extensions to WordPress.com?'](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/README.md#how-do-i-merge-extensions-to-wordpresscom) correctly conveys the possible issue - let me know if not!

Extensions: Wording change for WPcom workflow in README.

---

projects/packages/my-jetpack/_inc/components/product-card/index.jsx
projects/packages/my-jetpack/changelog/update-product-status-styles
projects/packages/my-jetpack/src/class-products.php

Fixes #23550 
* Update the way produc cards look in each status
p1HpG7-fbl-p2#comment-53125
No
* Test product cards in all 5 different possible states and make sure they look the same as defined in the issue (screenshot below)
* Note: At this moment, we are not allowing non-admins to access My Jetpack, so ignore this part of the design
Changes from previous version:
* `plugin_absent` now looks like an Inactive card, but with a primary button with the "Purchase" label that takes the user to the interstitial page
* `inactive` now displays a secondary button (not primary)

Updated the styles for card statuses

---

projects/plugins/jetpack/changelog/fix-gutenberg-store-error
projects/plugins/jetpack/extensions/store/membership-products/index.js

Fixes a Redux Store regression for Premium content block
* Fixes a regression in Premium content block when the Gutenberg plugin is disabled on Atomic sites.
* Atomic: Switch to this branch using Jetpack Beta
* Disable the Gutenberg plugin on your site
* Go to wp-admin/post-new.php
* Add the Premium Content block.
* Make sure the block is added without displaying an error in the console log:

Premium content block: Fixed store middleware regression on older Gutenberg versions.

---

projects/plugins/jetpack/changelog/update-product-management-nomenclature
projects/plugins/jetpack/extensions/blocks/premium-content/edit.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/constants.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/toolbar-control.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/utils.js
projects/plugins/jetpack/extensions/store/membership-products/actions.js
projects/plugins/jetpack/extensions/store/membership-products/resolvers.js

Fixes #23571
* Add a list of strings to be used by the `ProductManagementControls` component and the `jetpack/membership-products` store, based on a given product type.
We've chosen this centralized approach instead of the more common `sprintf` because it's a bit clearer, generates less cognitive load on the component's consumers, and it's easier to maintain.
p1648029677784879-slack-CDLH4C1UZ
No.
* Sandbox a WordPress.com site on a paid plan and an active Stripe connection.
* Open the editor and insert a Premium Content block.
* Look around the block (toolbar, sidebar), try adding new products.
* Make sure all the strings and messages are about "subscriptions".

Payment Blocks: Use correct product type nomenclature in the shared management controls

---

projects/plugins/jetpack/changelog/fix-product-manager-site-editor
projects/plugins/jetpack/extensions/shared/components/product-management-controls/toolbar-control.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-open-block-sidebar.js

Fixes #23443
* Make the `ProductManagementControls` "add new" toolbar control open the correct sidebar on every editor type.
Post, site, and widgets editor all implement the block settings sidebar in a slightly different way.
The Premium Content block (and subsequently the shared `ProductManagementControls`) only targeted the post editor sidebar when using the "add new" control from the toolbar.
This PR makes the "add new" control handle all three types of editor sidebars.
To know the current editor, it checks if the corresponding Redux store is loaded.
Since we are only checking for existence, not using, we are not importing those stores, and we don't need to add them to the package dependencies.
The PR also:
- Adds a brief timeout to allow for the sidebar to open before attempting to …

Payment Blocks: Fix "add new" not opening the block sidebar on site and widgets editor.

---

projects/plugins/backup/changelog/fix-backup-site-title-on-progress
projects/plugins/backup/src/js/components/Backups.js
projects/plugins/backup/src/js/selectors/site-data.js
projects/plugins/backup/src/php/class-initial-state.php

Fixes rendering of rogue site title
Fixes #23619
* Leverages the site title in the message shown while a backup is in progress
no
**Fresh site**
1. On a fresh site running this branch ([JN link](https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=fix/backup-site-title-on-progress&wp-debug-log)), install Backup and connect it paying for a plan
2. Expect to be back on the Backup admin page and see the progress bar reading "Backing up your Site Name" (where Site Name) should be your real site name)
**On a dev environment**
2. Visit the Backup admin page, and open the dev console, then switch to the Component tab
4. Find the <Backups/> component and updated the first "Select" entry to read `1`.   
5. Expect to see the progress status showing your site's …

Backup: Use real site title (name) when showing progresss text on admin page

---

projects/packages/my-jetpack/_inc/components/heading/index.jsx
projects/packages/my-jetpack/_inc/components/heading/stories/index.jsx
projects/packages/my-jetpack/_inc/components/heading/stories/style.module.scss
projects/packages/my-jetpack/_inc/components/heading/style.module.scss
projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/_inc/components/plans-section/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-plans-section-tweakness

This PR tweaks the plans sections according to the feedback described here. For this purpose, I've created a couple of components to be reused in the whole UI of the app.
Fixes https://github.com/Automattic/jetpack/issues/23542
* My Jetpack: tweak plan sections box model.
* With Storybook
* Check the heading components
* Confirm the margin values:
* Testing with My Jetpack dashboard
* Confirm margins look right.

* My Jetpack: tweak plan sections box model

---

.github/files/lint-project-structure.sh
.github/files/list-changed-projects.sh
.github/workflows/linting.yml
pnpm-lock.yaml
projects/plugins/protect/changelog/fix-monorepo-version-refs-lint
projects/plugins/protect/composer.lock
projects/plugins/protect/package.json
projects/plugins/starter-plugin/changelog/fix-monorepo-version-refs-lint
projects/plugins/starter-plugin/package.json
tools/check-intra-monorepo-deps.sh
tools/version-packages.sh

It seems likely to have been broken since #22433 added a call to the
Jetpack CLI without there being a `pnpm install` first. Add that to the
action.
Also update the script to detect this sort of error and handle it
better, instead of trying to lint a project with the improbably name of
"? Install the following package: jetpack@latest? (Y/n) ‣ ", and pass
the `--no-install` flag to `pnpx` in a few more places for good measure.
p1648211555656609-slack-CBG1CP4EN
No
* We have some cases in the repo now, see that the run before adding the commit fixing them detects them.
* :heavy_check_mark: https://github.com/Automattic/jetpack/runs/5692674389?check_suite_focus=true#step:5:77

linting: Fix monorepo version refs lint

---

projects/packages/autoloader/changelog/fix-autoloader-test-failed-download-check
projects/packages/autoloader/tests/php/lib/class-test-plugin-factory.php

Rather than failing with "The Composer file downloaded has a different
SHA256 than expected", fail with something along the lines of
"Failed to download &lt;url>: &lt;reason>".
p1648197192791289/1648194130.870349-slack-C034JEXD1RD
No
* I suppose you could edit the URL to something invalid then try running the tests locally. Don't forget to remove `tests/php/tmp/` first so it doesn't used a cached download.

autoloader: Better error message if test fails due to download error

---

projects/packages/connection/changelog/fix-jetpack-webhooks
projects/packages/connection/src/class-webhooks.php
projects/packages/connection/tests/php/test-class-webhooks.php

Fixes #23658 
In the Connection package, we were always calling `exit` in the webhook handler, thus not allowing Jetpack class to handle the other cases not covered in the connection package. (cc @sergeymitr FYI)
* Fixes webhook handling by the Jetpack plugin 
p1648493724551759-slack-C01U2KGS2PQ
No
* Go to `/wp-admin/admin.php?page=jetpack_modules` and try activating/deactivating modules
Check for regressions on the webhooks handled by the connection package (making sure what was done in https://github.com/Automattic/jetpack/pull/23382 still works)
* launch a new site only with Boost in this branch
* Connect Boost
* Click to Add Backup -> then click on the button on the product screen
* You should be redirected to Authorize your user
* After authorizing your user, you …

Fix webhook handling in Jetpack

---

projects/plugins/jetpack/changelog/fix-notice-masterbar-feature-check-20220329
projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php

Follow-up to #23585
That function is defined in wpcomsh, but in some cases that mu-plugin may be removed / not up to date, and we need to account for that.
* N/A
* No
* Not easy to test, since you need a WoA sandbox where the wpcomsh mu-plugin is not up to date, but this should be a fairly straightforward change to review.

Masterbar: avoid Fatals when function does not exist

---

projects/plugins/jetpack/changelog/fix-notice-masterbar-20220329
projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php

﻿Avoid PHP notices like this one:
```
[28-Mar-2022 09:38:57 UTC] PHP Notice:  Undefined variable: jetpack_locale in /srv/htdocs/wp-content/plugins/jetpack-dev/modules/masterbar/masterbar/class-masterbar.php on line 442
```
* N/A
* No
I'm not quite sure how to reproduce, I ran into the issue when checking the logs for my WoA sandbox.
* Try to go to Jetpack > Settings > Writing
* Enable the WordPress.com toolbar module
* Ensure you do not see the above error in your logs.

Masterbar: avoid PHP notices when locale is not defined

---

projects/plugins/jetpack/_inc/client/at-a-glance/crm/index.jsx
projects/plugins/jetpack/changelog/update-wording-crm-plugin-upsell
projects/plugins/jetpack/modules/stats/class-jetpack-stats-upgrade-nudges.php

* Add a mention of "Free" to the Jetpack CRM description.
* ﻿See pbNhbs-2k2-p2#comment-7451
* No
* Start with a connected site.
* Go to Jetpack > Dashboard as well as Jetpack > Site Stats
* Check the CRM banners, they should mention "Free".

Jetpack CRM: adjust wording

---

.husky/pre-push
tools/js-tools/git-hooks/pre-push-hook.js

PR #23359 added code to have the pre-push hook run `jetpack changelog add`,
but this code fails if the push is happening via an IDE where a tty is
not available.
The fix is in two parts: First, don't redirect stdin from /dev/tty in
.husky/pre-push if it's going to fail. Second, don't try to run
`jetpack` in pre-push-hook.js if stdin isn't a tty.
p1648544038507239-slack-CDLH4C1UZ
No
* Create a branch based on this one, probably one needing a change file added, and try pushes from a console and an IDE.
* From console, `jetpack changelog add` should be run if needed.
* From an IDE, `jetpack changelog add` should not be. Instead, the push should just be rejected with an appropriate message if a change entry file is needed.

pre-push hook: Don't fail if no tty is available

---

projects/plugins/jetpack/_inc/client/components/settings-card/test/component.js
projects/plugins/jetpack/_inc/client/components/settings-group/test/component.js
projects/plugins/jetpack/_inc/client/writing/index.jsx
projects/plugins/jetpack/_inc/client/writing/theme-enhancements.jsx
projects/plugins/jetpack/changelog/update-google-fonts-beta
projects/plugins/jetpack/modules/google-fonts.php
projects/plugins/jetpack/modules/module-info.php

Follow-up from #23295
* The feature is still under development, and we'll need to make some more changes before it's ready for prime-time. Let's make that clear in the plugin by marking the module as beta and removing the toggle from the dashboard to avoid setting wrong expectations.
* Internal reference: p1HpG7-flD-p2#comment-53417
* No
* Go to Jetpack > Settings > Writing, and scroll down to the Theme Enhancements section; you should not see a section about Google Fonts.
* Go to Jetpack > Modules (from the link at the bottom of the dashboard page). You should see the Google Fonts module, but with a Beta label.

Google Fonts: mark feature as Beta and remove from dashboard.

---

projects/plugins/jetpack/changelog/update-jetpack-seo-feature-gating
projects/plugins/jetpack/modules/seo-tools/class-jetpack-seo-utils.php

In #23189, we started using the new feature gating for WPcom sites in `Jetpack_Plan::supports()`. Given upcoming Dotcom pricing changes, this moves the feature gating for the SEO Tools to use `Jetpack_Plan` on WPcom sites.
See: pdgrnI-wV-p2#comment-1061
* use `Jetpack_Plan::supports()` instead of blog stickers for the SEO Tools gating
* this shouldn't functionally change anything for existing users, just allow the Pro plan to access the tools
N/A
**Jetpack sites:**
- [Spin up a JN site using this branch](https://jurassic.ninja/create?jetpack-beta&branches.jetpack=update/jetpack-seo-feature-gating).
- Set up Jetpack and keep it on the Free plan
- In Calypso, visit Tools > Marketing > Traffic
- Verify that you can see the SEO sections without any gating
- Verify that updating the Page Title …

SEO Tools: use new feature gating for WPcom sites

---

projects/plugins/jetpack/changelog/update-form-plugin-button-spacing
projects/plugins/jetpack/extensions/blocks/contact-form/components/jetpack-crm-integration/jetpack-crm-integration-settings-plugin-state.js
projects/plugins/jetpack/extensions/blocks/contact-form/components/jetpack-newsletter-integration-settings-plugin-state.js
projects/plugins/jetpack/extensions/blocks/contact-form/editor.scss

Form: make margin around the CRM and Newsletter plugin buttons consistent. Also use same margin for the activating/installing states so the buttons don't jump around.
Raised via internal testing: p8oabR-PC-p2#comment-6134
No.
Observe post-patch design.
**Before:**
**After:**

Form: make margin around the CRM and Newsletter plugin buttons consistent

---

projects/plugins/jetpack/changelog/fix-carousel-nonce
projects/plugins/jetpack/modules/carousel/jetpack-carousel.php

Fixes #23728
* PR #22770 introduced a nonce check which caused issues for comments in carousels. This PR fixes that by removing the nonce check.
p1648736983705859-slack-C01U2KGS2PQ
No.
* There are some great [testing instructions here](https://github.com/Automattic/jetpack/issues/23728#issuecomment-1084661729) - however the network tab response should now not show a failure message under 'Preview', and comments should show under the images in the carousel.

Carousel: Fixing comments issue with nonce checks

---

projects/plugins/jetpack/changelog/fix-subscribe-block-default-style-selected
projects/plugins/jetpack/extensions/blocks/subscriptions/index.js

Fixing [the issue](https://github.com/Automattic/jetpack/issues/23480) where the subscribe block is displayed in "Split" style in block editor by default while the default "Style" setting selection is incorrectly set as "Compact".
Now both the subscribe block displayed and the "Style" block setting selected will be both set to "Split" by default.
* make `Split` button in the `Styles` setting of subscribe block selected by default
No
1. Go to create a new post.
2. Insert the Subscribe block.
3. Ensure that both the default style applied and selected in the block's `Styles` setting is `Split`.

Subscribe block: correct default style selection to split style

---

projects/js-packages/components/changelog/update-js-components-improve-text-doc
projects/js-packages/components/components/text/stories/Text-MDX-Documentation.mdx
projects/js-packages/components/components/text/stories/headings.index.jsx
projects/js-packages/components/components/text/stories/index.jsx

This PR adds a story document to the `<Text />`
Fixes https://github.com/Automattic/jetpack/issues/23592
* JS Components: Add story doc to Text components
* Go to Text story (default)
* Click on doc tab
* Take a look at the document (feedback more than welcomed)
https://user-images.githubusercontent.com/77539/161064357-a12bb841-52c0-44a7-a7d4-78ca3376b9a6.mov

JS Components: Add story doc to Text components

---

projects/plugins/jetpack/changelog/update-mailchimp-popup-widget-deprecate
projects/plugins/jetpack/modules/widgets/mailchimp.php

The proposed change hides the _Mailchimp Popup_ widget from the block inserter and _Legacy widget_ block drop-down menu.
**Before**
Block inserter  |  Legacy Widget block
**After**
Block inserter  |  Legacy Widget block
- Add filter to deprecate the _Mailchimp Popup_ widget
- pdf5j4-7f-p2
1. Make sure the test site has a theme that support widgets activated (e.g. Twenty Twenty-onee)
2. Make sure the "_Make extra widgets available for use on your site including subscription forms and Twitter streams_" Jetpack setting in `wp-admin/admin.php?page=jetpack#/writing` is activated:
3. Navigate to Customizer → Widgets
4. Add the _Legacy widget_ block and take a look at …

Mailchimp Popup widget: Widget Deprecation

---

tools/check-changelogger-use.php
tools/js-tools/git-hooks/pre-push-hook.js

If change entry files exist but aren't committed, the script should say
so instead of saying that they need to be added.
Further, when run from the pre-push hook, it would be nice if it would
offer to commit the entries.
p1648733008882149/1648675066.428619-slack-CDLH4C1UZ
No
Test the following cases:
* Push with no missing change entries.
* Push should succeed.
* Push with only missing change entries.
* Changelogger should run, as before.
* Push (via command line) with only uncommitted change entries.
* You should be prompted to merge. Answer "N".
* Push should be rejected with sensible messages and without trying to run changelogger.
* Push (via command line) with only uncommitted change entries.
* You should be prompted to merge. Answer "Y".
* You should be prompted to push again. The …

tools: Let check-changelogger-use.php detect uncommitted change entries

---

projects/plugins/boost/app/assets/src/css/main/dashboard.scss
projects/plugins/boost/changelog/fix-whitespace
projects/plugins/boost/rollup.config.js

Fixes #23752
* Do not minify CSS during development builds.
* Fix whitespace issue introduced at f651a7a4ba
N/A
No
* Go to Boost settings page
* Regenerate assets
* Check if whitespace still persists as mentioned in #23752.
* Try `jetpack build plugins/boost` vs `jetpack watch plugins/boost` commands and make sure `build` generates minified CSS while `watch` generates un-minified.

Boost: Fix paragraph spacing in settings page

---

.github/renovate-config.js

By default renovate tries to autodetect whether it should use semantic
commits or not. The autodetection seems somewhat flaky, it decides "yes"
if the latest commit starts with "Fix".
Since we don't currently want to use these, let's explicitly disable
them.
None. But it's why https://github.com/Automattic/jetpack/pull/23744#event-6354927242 happened.
No
* 🤷 You'd first have to make the latest commit fool renovate's autodetection to be able to tell.

renovate: Explicitly disable semantic commits

---

projects/packages/sync/changelog/update-cron-dedicated-sync
projects/packages/sync/src/class-actions.php

If Dedicated Sync is enabled, and there are items in the queue, and WP-Cron runs and picks up the Sync cron job it would try to continuously start the Dedicated Sync thread/request. 
This causes a lot of errors on the WPCOM side that might slow down the sync flow. 
This PR makes Dedicated sync run only once if in WP-Cron context.
N/a
No
* Apply PR
* Add events in the Sync queue
* For example using generate: `wp post generate --count=800 --url="<YOUR_TEST_SITE>"`
* Wait for the Cron to run
* Make sure the `do_sync` call is done only once.
Notes: It might be helpful if you add logging entries to the `do_sync` and `\Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type` methods to monitor how the cron process runs them. 
Props to @bisko , see https://github.com/Automattic/jetpack/pull/23755

Jetpack Sync: Run cron sync only once on Dedicated Sync flow

---

projects/packages/my-jetpack/_inc/components/product-detail-card/index.jsx
projects/packages/my-jetpack/_inc/components/product-detail-card/style.module.scss
projects/packages/my-jetpack/changelog/update-my-jetpack-align-prices-in-interstitial-cmp

This PR aligns the price boxes in the interstitial page.
Fixes #
* My Jetpack: align price boxes in the interstitial product page
p1649161731079189-slack-C02TQF5VAJD
No
* Go to some interstitial upgradable page, for instance `https://<your-testing-site>/wp-admin/admin.php?page=my-jetpack#/add-backup`
* Confirm price description is located below to the prices.
**before**
**after**

My Jetpack: align price boxes in the interstitial product page

---

.github/files/required-review.yaml

With the WAF package and the Protect plugin, the Scan team has ownership of these two projects. Granting them approval ability so they can approve 
PRs that consist of their code.
* Adds Scan projects and team.
* Per discussion, split Backup and Scan permissions to the proper team.
p1649156720075049-slack-C029WFNV69M
I'll p2 once it lands.
No.
* Create a PR based on this branch. Only touch a WAF package. Submit and have a member of Scan approve.

Approvals: Scan to approve Scan code

---

pnpm-lock.yaml
projects/js-packages/components/index.jsx
projects/plugins/protect/changelog/add-protect-vulnerabilities-list
projects/plugins/protect/package.json
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/stories/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/styles.module.scss

Introduce the `VulnerabilitiesList` component, which renders the list of vulnerabilities with risk.
* Add `VulnerabilitiesList` component.
* Use `VulnerabilitiesList` component at `AdminPage`.
1202064326332560-as-1202064326332567/f
No.
* Start `protect` plugin
* Navigate to `homepage`.
* You should see vulnerabilities list.

Protect: Add `VulnerabilitiesList` component

---

projects/js-packages/connection/changelog/update-connect-screen-add-skip-user
projects/js-packages/connection/components/connect-screen/basic/index.jsx
projects/js-packages/connection/components/use-connection/index.jsx
projects/plugins/protect/changelog/update-connect-screen-add-skip-user
projects/plugins/protect/src/js/components/admin-page/index.jsx

This PR adds the option to skip the user connection step in the ConnectionScreen component.
This allows plugins to provide a one click connection experience.
We also add this behavior to the Protect plugin
* Adds the `skipUserConnection` prop to the `ConnectScreen` component
* Make Protect plugin require only a site-level connection
p1HpG7-fgl-p2#comment-53520
No
* Activate only Protect
* Go to Protect page and click Set up
* Confirm that the Protect main admin page is loaded after connection is established without any page refreshes
* Confirm that the site is properly connected at a site level

Adding skipUserConnection option to the connection screen

---

projects/js-packages/components/changelog/fix-button-link-variant
projects/js-packages/components/components/button/index.jsx
projects/js-packages/components/components/button/style.module.scss
projects/js-packages/components/index.jsx
projects/js-packages/components/package.json

Fixing some problems with Button as we started to use it at `Protect`.
* Export it at `index`.
* Fix `padding` for `Link` variant.
* Add target as `_blank` for `External` variant.
* Pass rest props down to `WPButton`.
N/A
No.
* Start Storybook.
* Navigate to `JS Packages/Components/Button`.
* You should see: 
* New padding for Link
* External opening a new tab
* Props going down to WPButton.

RNA: Export `Button` and fix `Button` link variant padding and target

---

projects/plugins/protect/changelog/add-installed-plugins-protect-initial-state
projects/plugins/protect/composer.json
projects/plugins/protect/composer.lock
projects/plugins/protect/src/class-jetpack-protect.php

* Add list of installed pĺugins to the initial state
p1HpG7-fgl-p2
No
* Go to Jetpack Protect
* Inspect the global variable `jetpackProtectInitialState` in your browser
* Confirm it has a `installedPlugins` property with the list of plugins installed in your site

Protect: Add list of installed pĺugins to the initial state

---

projects/js-packages/components/changelog/update-js-component-fix-button-classname-issue
projects/js-packages/components/components/button/index.jsx
projects/js-packages/components/components/button/stories/index.jsx

This PR fixes an issue when trying to add a custom className to the Button component. Currently, a `propsClassName` class name is added instead of the proper one.
Fixes #
* JS Components: fix className prop in Button component
No
* Test with Storybook
* Use the Primary story
* Confirm you can set and edit the custom class name

JS Components: fix className prop in Button component

---

projects/packages/my-jetpack/_inc/utils/get-product-checkout-url.js
projects/packages/my-jetpack/changelog/fix-checkout-url-for-subdirs

Fixes #23812
All references to sites in Calypso uses a sanitized URL for the site where slashes are replaces with `::`.
The bug was that we were building the URL using the JS `URL` object and when it saw the `::` in the URL it was mistaken it as the protocol.
The fix was to do a simple concatenation.
* Fix bug in checkout URLs for sites in installed subdirs
N/A
No
* See  #23812 and/or directly test the function behavior by playing with the value of `siteSuffix`

Fix bug in checkout URLs for sites in subdirs

---

projects/plugins/jetpack/changelog/update-googleplus-rm
projects/plugins/jetpack/modules/comments.php
projects/plugins/jetpack/modules/module-info.php
projects/plugins/jetpack/modules/sharedaddy.php
projects/plugins/jetpack/modules/shortcodes.php

Fixes #23837
* Remove mentions of the old "Google+" service from our descriptions.
* N/A
* No
* Not much to test here, this is just updating some old strings.

Janitorial: remove mentions of defunct Google+ service.

---

projects/packages/composer-plugin/changelog/add-composer-plugin-modifies-install-path-flag
projects/packages/composer-plugin/composer.json
projects/plugins/backup/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/jetpack/composer.lock
projects/plugins/protect/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/protect/composer.lock
projects/plugins/search/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/search/composer.lock
projects/plugins/social/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/social/composer.lock
projects/plugins/starter-plugin/changelog/add-composer-plugin-modifies-install-path-flag
projects/plugins/starter-plugin/composer.lock

This setting, added in composer 2.2.9, signals to Composer that the
plugin will change the install paths of other packages and so should be
installed early in the process.
https://getcomposer.org/doc/articles/plugins.md#plugin-modifies-install-path
None. [composer/composer#10618](https://href.li?https://github.com/composer/composer/issues/10618) may be relevant though.
No
* No idea. Not sure if we'd actually be affected by the composer change in 2.2.8 in the first place, as it seems to have to do with indirect dependencies or something.

composer-plugin: Set plugin-modifies-install-path flag

---

projects/plugins/jetpack/changelog/fix-product-manager-no-products-create
projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/invalid-product-warning.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/utils.js
projects/plugins/jetpack/extensions/store/membership-products/resolvers.js

* Prevent creating a new product on an existing payment block if the site has no products and the block is using an invalid product ID.
* Update the copy for the Payment Button block to use the generic "payment plan" phrasing instead of the Premium Content-specific "subscription".
This PR fixes an edge case where the `getProducts` selector used by payment blocks would automatically create a new product if the site has no products.
It was mostly intended to pre-populate payment blocks on "empty" sites, but it ended up creating (and auto-selecting) new products also for existing blocks whose product has been deleted.
In that case, the block is supposed to show an invalid product warning instead, but the "no products" case runs earlier than the invalid product scenario.
The fix simply makes …

Payment Blocks: Avoid creating a new product if the site has no products and the block has an invalid product ID

---

projects/plugins/protect/changelog/update-protect-fix-fatal-getting-vuls
projects/plugins/protect/src/class-status.php

This PR fixes a fatal PHP error when picking the sites vuls.
Fixes #
* Protect: Fix Fatal when checking whether site site has vuls
* Get the site vulnerabilities 
* without these changes, confirm you get the fatal error
```
[08-Apr-2022 15:08:04 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /usr/local/src/jetpack-monorepo/projects/plugins/protect/src/class-status.php:90
```
* Confirm this PR fixes the bug

Protect: Fix Fatal when checking whether site site has vulnerabilities

---

projects/plugins/jetpack/changelog/fix-product-manager-child-blocks-add-new
projects/plugins/jetpack/extensions/blocks/premium-content/edit.js
projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx
projects/plugins/jetpack/extensions/shared/components/product-management-controls/context.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/invalid-product-warning.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/toolbar-control.js
projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-open-block-sidebar.js

Related to #23633
* Select the parent payment block before opening its sidebar when creating a new product.
* Also refactor the `ProductManagementControls` component to use context instead of unnecessarily passing props around.
This change fixes a minor issue introduced by https://github.com/Automattic/jetpack/pull/23567 which exposes the parent payment button controls to children blocks.
The controls' "add new" toolbar item opens the sidebar, where the form is displayed.
Though, doing so from a child block would open the child's sidebar instead of the parent's.
No.
* On a site with a paid plan and an active Stripe connection, add the Payment Button block.
* Click on the button: it should select the child Jetpack Button block (double-check in the List View if you need confirmation).
* …

Payment Blocks: Fix add new product not working on child blocks

---

projects/js-packages/components/changelog/update-js-components-fix-offer-issues
projects/js-packages/components/components/product-offer/index.jsx
projects/js-packages/components/components/product-offer/style.module.scss

It fixes a visual issue reported by @keoshi [here](https://github.com/Automattic/jetpack/pull/23842#issuecomment-1092604456)
Fixes #
* RNA: fix ProductOffer button loading state issue
* Go to `Packages/Componens/ProductOffer` story
* Confirm the Add button doesn't change when switching to `isLoading` state
https://user-images.githubusercontent.com/77539/162460837-cf40d946-2276-4cea-b488-a0022897a145.mov

RNA: fix ProductOffer button loading state issue

---

projects/plugins/jetpack/changelog/fix-slideshow-block-in-layout-grid-block-blowout
projects/plugins/jetpack/extensions/blocks/slideshow/editor.scss
projects/plugins/jetpack/extensions/blocks/slideshow/style.scss

Fixes https://github.com/Automattic/wp-calypso/issues/39956
* Fixes grid blowout when Slideshow Block is inserted inside Layout Grid Block.
**Why did it break?**
Slideshow block's width is blowing out because the parent grid element expands itself to the width of the slideshow block. The resize observer in the Swiper library detects the change in width and resizes the Slideshow block, causing the parent grid to again re-expands itself. This vicious cycle continues to repeat itself until the width is blown out of proportion.
**How was it fixed?**
Make the slideshow block behave like a grid block when inserted inside the layout grid block.
Maintenance work.
No.
* Install "Layout Grid Block" plugin.
* Go to block editor.
* Insert a layout grid block.
* Insert slideshow block into the grid.
* …

Slideshow Block: Fix grid blowout when inserted inside Layout Grid Block.

---

projects/plugins/jetpack/changelog/fix-top-posts-display-posts
projects/plugins/jetpack/modules/widgets/top-posts.php

Fixes #23832
In #23429 I messed up; I moved actions that could be used to echo data within each post into a method that returned all posts. Let's restore the past behaviour, while keeping the fix and some of the logic.
* N/A
* No
* On a brand new site, connect to WordPress.com.
* In Jetpack > Settings, ensure that both the Stats module and the extra widgets module is active.
* Go to Apperance > Themes and switch to a theme that supports widgets, such as Twenty Twenty.
* Go to Apperance > Widgets and add a Top Posts widget.
* Visit some of the posts on the frontend while logged out, to create visits in stats.
* Add the following to a functionality plugin (like Code Snipppets):
```php
add_action( 'jetpack_widget_top_posts_after_post', function ( $post_id ) {
$post_date = get_post_time( …
```

Top Posts: ensure hooks can still be used to echo data in widget.

---

projects/plugins/jetpack/changelog/update-custom-css
projects/plugins/jetpack/modules/custom-css/custom-css.php

Backports p3btAN-1IZ-p2 / r243392-wpcom from WP.com 
* This code doesn't run in Jetpack, but still lives here. While we should remove it outright, backporting this until we work on that.
See above.
n/a
* n/a doesn't run in Jetpack already running on WP.com.

Custom CSS: Improved saving

---

pnpm-lock.yaml
projects/plugins/jetpack/_inc/client/components/popover/index.jsx
projects/plugins/jetpack/changelog/remove-old-core-js-dep
projects/plugins/jetpack/package.json

core-js v2.6.12 has a deprecation notice:
> core-js@<3.4 is no longer maintained and not recommended for usage due
> to the number of issues. Because of the V8 engine whims, feature
> detection in old core-js versions could cause a slowdown up to 100x
> even if nothing is polyfilled. Please, upgrade your dependencies to
> the actual version of core-js.
That's being pulled in as an indirect dependency of a package
`click-outside`, last updated 6 years ago and easily replaceable with a
tiny bit of inline code now that we've dropped support for IE9.
Removing that package drops 4 other indirect deps on old packages.
None
No
* Go to Jetpack's Settings page. Click the ⓘ icon next to one of the settings that has it, and make sure the popover doesn't go away if you click inside but does if you …

jetpack: Rework popover dismissal to remove obsolete indirect dep

---

projects/plugins/starter-plugin/changelog/update-starter-plugin-cleanup
projects/plugins/starter-plugin/composer.json
tools/cli/commands/generate.js
tools/cli/helpers/projectNameTransformations.js

Fixes #23866
- Replace the `description` field in `composer.json` with supplied project description.
- Replace the `release-branch-prefix` in `composer.json` with supplied project name (without jetpack- prefix).
n/a
No.
* With changes pulled down, run `jetpack generate` using the `plugins`, `mirror repo`, and `use Jetpack Starter plugin` options.
* Check the generated `composer.json` to make sure the entered description has been used, and that the `release-branch-prefix` is the entered project's normalized name. Other generated files should be as expected.

Starter Plugin: minor cleanup for CLI generation

---

projects/packages/my-jetpack/_inc/state/resolvers.js
projects/packages/my-jetpack/changelog/update-my-jetpack-error-handling
projects/packages/my-jetpack/src/class-rest-purchases.php
projects/packages/my-jetpack/src/products/class-backup.php
projects/packages/my-jetpack/src/products/class-scan.php
projects/packages/my-jetpack/src/products/class-search.php

This PR makes 2 changes to better handle errors in My Jetpack. Mostly errors related to the site being unable to reach WPCOM.
First, we reduce the timeout of the requests we make to check for each product statuses. Since we can make many requests, each requests hangs for a while and the server may run out of time. Reducing the timeout of each individual requests helps avoid it from happening.
Also, if WPCOM was unreachable, the whole UI would crash because the `PlansSection` component would fail to render the purchases data. This PR avoids the error and adds a error message to the global notices in the page
* My Jetpack: Better error handling when the server is unreachable
N/A
No
* Easiest way to emulate the problem is to sandbox your site and make sure the sandbox is offline
* Visit My …

My Jetpack: Better error handling

---

.github/files/renovate-post-upgrade-run.sh
.github/files/renovate-post-upgrade.sh

The post-upgrade script is printing spurious Xdebug warnings due to an
unwritable log file, which may hide legitimate problems. Symlink that
log file to /dev/null to avoid that.
Renovate's pnpm lock file maintenance works by deleting the lock file
then doing a `pnpm install` to recreate it. But if pnpm finds its
metadata in `node_modules/`, it will use that instead of recreating the
lock file from scratch as renovate intends. So we need to make sure the
post-upgrade script doesn't leave a `node_modules/` behind.
The lock file maintenance problem is mentioned in https://github.com/Automattic/jetpack/pull/23893#issuecomment-1095253142
The spurious Xdebug warning can be seen at https://github.com/Automattic/jetpack/pull/23893#issuecomment-1095548421
No
If you really want to test this:
* Fork …

renovate: Fix errors post-upgrade scripts

---

projects/plugins/jetpack/_inc/client/traffic/ads.jsx
projects/plugins/jetpack/changelog/fix-change-jetpack-ads-to-wordads
projects/plugins/jetpack/modules/widgets/eu-cookie-law/form.php
projects/plugins/jetpack/modules/wordads/class-wordads.php

* This PR replaces the words "Jetpack Ads" with WordAds.
82-gh-Automattic/wordads-issues
p1647977972298469-slack-C02S30USNRM
No.
Before testing, if you already have the Jetpack project, remember to update the dependencies to see the changes:
```
jetpack build
? What type of project are you working on today? plugins
? Please choose which project jetpack
? Build dependencies of plugins/jetpack too? Yes
```
Test instructions for changes on `projects/plugins/jetpack/_inc/client/traffic/ads.jsx`:
* Go to Jetpack > Settings > Traffic tab.
* Enable option "Customize your ads.txt" file.
* Check if the word WordAds is shown instead of "Jetpack Ads".
Test instructions for changes on `projects/plugins/jetpack/modules/widgets/eu-cookie-law/form.php`:
* Go to Jetpack > Settings > Writing tab.
* Enable …

[WordAds]: Replace "Jetpack Ads" with WordAds

---

projects/packages/my-jetpack/_inc/components/connected-product-offer/index.jsx
projects/packages/my-jetpack/_inc/components/connected-product-offer/stories/index.jsx
projects/packages/my-jetpack/_inc/components/connected-product-offer/stories/mock-data.js
projects/packages/my-jetpack/_inc/components/connected-product-offer/stories/utils.js
projects/packages/my-jetpack/changelog/add-connected-product-offer-component-my-jetpack

Follow-up to #23874
Re-introduces the ConnectedProductOffer component without swapping it for ConnectedProductDetailCard
* Introduces `ConnectedProductOffer` to My Jetpack
* INcludes cherry-picked commits 51ee5bf4a3ef6da9eb5bdb2fdf0725ea817a0153 and 6764bff824b558aba592154a289bd11ade4dfcbe from #23930
See https://github.com/Automattic/jetpack/pull/23931 and p1649860877787919-slack-C02TQF5VAJD
no
* Launch Storybook
* Go to the ConnectedProductOffer story
* Switch the product by selecting the slug 
https://user-images.githubusercontent.com/77539/162457966-530c710d-08ca-464a-8965-1245ecbb88e2.mov

My Jetpack: Reintroduce ConnectedProductOffer (Revamp of 23874)

---

projects/plugins/boost/app/admin/class-admin.php
projects/plugins/boost/app/assets/src/js/global.d.ts
projects/plugins/boost/app/assets/src/js/pages/benefits/BenefitsInterstitial.svelte
projects/plugins/boost/app/assets/src/js/pages/purchase-success/PurchaseSuccess.svelte
projects/plugins/boost/app/assets/src/js/pages/settings/elements/PremiumCTA.svelte
projects/plugins/boost/app/assets/src/js/pages/settings/sections/Support.svelte
projects/plugins/boost/app/assets/src/js/utils/paid-plan.ts
projects/plugins/boost/app/assets/src/js/utils/upgrade.ts
projects/plugins/boost/app/contracts/Boost_API_Client.php
projects/plugins/boost/app/features/optimizations/Optimizations.php
projects/plugins/boost/app/lib/Boost_API.php
projects/plugins/boost/app/lib/Premium_Features.php
projects/plugins/boost/app/lib/WPCOM_Boost_API_Client.php
projects/plugins/boost/app/rest-api/endpoints/Optimization_Status.php
projects/plugins/boost/changelog/add-premium-upgrade-flow

Fixes 44-gh-Automattic/boost-shield-api
Requires patch: D78422-code
pc9hqz-iD-p2
No
* Apply D78422-code on your sandbox
* Load the boost settings page and follow the upgrade flow
* After the purchase is done, you should be able to see that Automatic critical CSS replaced the local critical CSS module

Boost: Add premium upgrade flow

---

projects/plugins/jetpack/changelog/fix-double-ads-txt-request
projects/plugins/jetpack/modules/wordads/class-wordads.php

Addressed from 89-gh-Automattic/wordads-issues
* This PR stores the ads.txt content in a variable, avoiding being requested twice on the WPCOM endpoint.
No.
* Access the ads.txt path from url, and check if it's showing as expected.
* Url example: https://yourblog.com/ads.txt

[WordAds]: Fix double requesting ads.txt

---

projects/plugins/jetpack/changelog/fix-comment-form-nonce
projects/plugins/jetpack/modules/comments/comments.php

Fixes wp-calypso#62646
Issue originally introduced here: #23439
* This PR moves around two code blocks, prioritising a check for Jetpack 'sig' and 'token_key' parameters before verifying the nonce, as those parameters don't exist on comments for non-support post-types.
* This fixes the issue (nonce verification failure message) that occurs when attempting to add a product review on a Jetpack and WooCommerce connected site. It also enables people to post comments when using custom post-types, which was also resulting in the nonce verification failure message.
* p1649892098202479-slack-CBG1CP4EN
* Also related to #23944
No.
* Activate Jetpack Comments at Jetpack > Settings > Discussion
* Install and activate WooCommerce and add a product. Add a product review, and you shouldn't see a nonce …

Comments: Prevent nonce verification when post-types don't support Jetpack comment forms.

---

projects/plugins/debug-helper/changelog/add-autoloader-debugger-enhancements
projects/plugins/debug-helper/modules/class-autoloader-debug-helper.php

Thanks to a suggestion by @ObliviousHarmony this PR changes the way we find the Autoloader namespace and avoids unnecessary looping. In addition to that it adds currently loaded file indicator:
* Adds better namespace detection.
* Adds loaded file indicator.
* N/A
No.
* Enable the Autoloader debugger in the Jetpack Debug Tools plugin.
* Open the Autoloader debugger page.
* Make sure the current plugin version and path are detected correctly, try disabling/enabling development packages autoloading: `define( 'JETPACK_AUTOLOAD_DEV', true );`
* Make sure you see the currently loaded file indicators and things look sane (only one included file per class, etc.)

Added Autoloader debugger enhancements for better debugging.

---

projects/js-packages/connection/changelog/fix-jetpack-react-warning
projects/js-packages/connection/components/disconnect-dialog/index.jsx

Fixes a PropType warning in Jetpack Dashboard.
This component is used by other components in the js packages, but also directly consumed by Jetpack plugin, which passes this argument in a different way, but both ways work.
* Fix a React warning in the Jetpack dashboard
https://github.com/Automattic/jetpack/pull/23358#issuecomment-1100076974
No
* Make sure you have `define( 'SCRIPT_DEBUG', true );` in your wp-config
* Activate other Jetpack plugin
* Go to Jetpack Dashboard
* Confirm there is no warning in the console about `connectedPlugins` type

Fix React warning

---

projects/plugins/jetpack/changelog/fix-videopress-metadata
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-media-v1-1-endpoint.php

* This PR adds some functionality that was added in WordPress.com, that includes video privacy metadata. Without that information it isn't possible to add video descriptions via the WordPress.com dashboard (https://wordpress.com/media/).
p1650010696620729-slack-CBG1CP4EN
p9o2xV-21I-p2#comment-5794
No.
* Apply this PR, and in the WordPress.com dashboard (https://wordpress.com/media/) upload a new video. Once uploaded, click to edit and add a description. There shouldn't be any errors and the description should stick.

VideoPress: Fixing an issue adding video descriptions in WordPress.com

---

projects/plugins/protect/changelog/add-get-themes-to-protect
projects/plugins/protect/src/class-jetpack-protect.php

* Add get_themes callable to Protect configuration of Sync
NA
No
* Activate and connect Protect (and only protect)
* Go to Jetpack Debugger > Sync Data Settings Tester
* Confirm `get_themes` is listed under `jetpack_sync_callable_whitelist`

add get themes to synced callables in Protect

---

projects/js-packages/connection/changelog/add-allow-secondary-user-conn-my-jetpack
projects/js-packages/connection/components/connection-status-card/index.jsx
projects/js-packages/connection/components/connection-status-card/test/component.jsx

Fixes #23914
* Allow secondary users to connect from My Jetpack
NA
No
* Install Jetpack or any jetpack plugin and fully connect site and user
* Go to My Jetpack and confirm you see the information that your user is connected
* Log in with another admin and visit My Jetpack
* Confirm you see a link to connect your user
* Connect your user with a different wpcom user
* Confirm the flow works (test a flow where you are already logged in to wpcom and another one where you are not)
* Back to My Jetpack, confirm you see the information about your user connection
Things outside the scope of this PR:
- only admins will be able to connect from My Jetpack because My Jetpack is not visible to other users
- Some connection flows are broken if you are using only a stand-alone plugin - because the …

Allow secondary users to connect from My Jetpack

---

projects/plugins/jetpack/changelog/add-filter-stats-footer-data
projects/plugins/jetpack/modules/stats.php

* Allow filtering the WPCOM JS and AMP stats footers individually.
* WPCOM JS was already filterable via the stats_array hook.
* Add the following code as an mu-plugin:
```
add_filter( 'jetpack_stats_footer_amp_data', function( $data ) {
$data['amp_data'] = 'yup';
return $data;
} );
add_filter( 'jetpack_stats_footer_js_data', function( $data ) {
$data['js_data'] = 'yup';
return $data;
} );
```
* Visit a page on the site and observe that the JS stats parameters include `js_data:'yup'`.
* Visit an AMP page on the site (active the AMP plugin and turn on Standard mode) and observe that the AMP pixel stats parameters include `amp_data=yup`.

Stats: Add ability to filter JS and AMP stats footer data

---

projects/js-packages/connection/changelog/fix-secondary-user-warning
projects/js-packages/connection/components/connection-status-card/index.jsx

* Fixes  warning that should not be displayed.
NA
No
* Activate VideoPress
* Log in as a secondary user and go to My Jetpack
* Make sure you see a link to connect the user, but no error or warning saying a user is required
* Go to Jetpack debug > Broken tokens and delete user tokens
* Go to My Jetpack with both users and confirm you see the error message

My Jetpack: Fix warning that should not be displayed

---

projects/packages/publicize/changelog/fix-add-legacy-checks-to-publicize
projects/packages/publicize/src/class-publicize-base.php
projects/packages/publicize/src/class-publicize.php
projects/plugins/jetpack/changelog/fix-add-legacy-checks-to-publicize
projects/plugins/jetpack/modules/publicize/publicize-jetpack.php
projects/plugins/jetpack/modules/publicize/publicize.php

* Fixes an issue where bulk publishing posts would publicize many posts by disabling publicizing posts when in a bulk edit context.
See p9MPsk-1BR-p2
No
- Checkout PR
- Ensure that you have active Publicize connections
- Publish a post
- Ensure that it gets publicized
- Create a draft post
- Go to your posts list
- Toggle the check box for your post
- Bulk edit
- Change the status to publish
- Save
- Ensure the post does not get published

Publicize: Apply legacy checks to not publicize in certain contexts

---

projects/github-actions/required-review/README.md
projects/github-actions/required-review/action.yml
projects/github-actions/required-review/changelog/update-required-review-needs-token

It was always effectively required, as the standard `GITHUB_TOKEN` lacks
the ability to read team membership and reading team membership is
needed for the action to actually do anything.
This adjusts things to better reflect that situation, and documents the
scopes the supplied token needs to have.
Fixes #23938
No
* Do the updated docs make sense?
* First you'd figure a way to use the dev version of this (e.g. commit the built version to a fork), then try using it without specifying a token.

required-review: Indicate that the `token` parameter is required

---

projects/github-actions/required-review/changelog/fix-required-review-rereview
projects/github-actions/required-review/src/reviewers.js

It seems that GitHub, in at least some cases, will return re-reviews
separately from its API. When checking if a PR is mergable it only looks
at the latest review from each user. This action should do the same.
Fortunately the API appears to return the reviews in the proper order
already, so we can just add or remove the user from the list of
approvers as we see each one.
Fixes #23083
* Arrange for the modified copy of the action to be used somewhere, then make a PR and try various combinations of approving, dismissing, and re-reviewing (to approve or request changes) without dismissing.

required-review: Fix handling of re-reviews

---

projects/packages/waf/.phpcs.dir.xml
projects/packages/waf/changelog/fix-WordPress.Security.ValidatedSanitizedInput-in-waf
projects/packages/waf/src/class-waf-runtime.php
projects/packages/waf/src/functions.php

Three messages:
* InputNotValidated: Add a few `isset()` checks.
* MissingUnslash: Add a stub `Automattic\Jetpack\Waf\wp_unslash()` that
will call WordPress's `wp_unslash()` if it is defined or do nothing
otherwise, on the assumption that in the former case WordPress has
mangled the superglobals with `wp_slash()` while in the latter that
hasn't happened (yet).
* InputNotSanitized: Ignore. This code is all about sanitization, we
don't need to pre-sanitize before we sanitize.
See #23942
No
* Make sure things still work properly, both in standalone mode and not.

waf: Fix WordPress.Security.ValidatedSanitizedInput sniff

---

projects/js-packages/components/changelog/update-js-components-product-offer-support-jetpack-logo
projects/js-packages/components/components/product-icons/index.jsx
projects/js-packages/components/components/product-icons/style.module.scss
projects/js-packages/components/components/product-offer/index.jsx
projects/js-packages/components/components/product-offer/stories/index.jsx
projects/js-packages/components/components/product-offer/style.module.scss
projects/js-packages/components/package.json

This PR allows to set a custom icon to the ProductOffer component. it comes up because currently is not possible to implement part of the Protect interstitial page:
Fixes #
* Add and expose `<JetpackIcon />` component
* Add `icon` property to the ProductOffer component
p1650293215361349-slack-C02TQF5VAJD
No
* This PR adds a new story to the ProductOffer named `Jetpack Protect`
* Take a look at the card header.
* Confirm the Jetpack icon is there.
* Confirm the size (32px)

JS Components: Add `icon` property to the ProductOffer component

---

projects/plugins/jetpack/changelog/fix-recurring-payments-failing-test
projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx
projects/plugins/jetpack/extensions/blocks/recurring-payments/test/edit.js

* Fix failing tests because of an editor type mismatch caused by imported packages side-effects.
The Payment Button block uses the `getEditorType` utility to determine the current editor type.
If the block is used in the post editor, it will use the post's permalink as a fallback URL for the button, when it's rendered off-site (e.g. email, RSS feed, etc.).
`getEditorType` relies on the various core `edit-` packages. E.g. `@wordpress/edit-site` would indicate that we are using the site editor.
In a testing context, `getEditorType` would return "unknown", which would correctly stop the Payment Button to try to grab the post permalink.
https://github.com/Automattic/jetpack/pull/23979 added a `@wordpress/edit-post` store import into a component internally used by the Payment Button block.
The …

Payment Blocks: Fix failing tests because of an editor type mismatch

---

projects/js-packages/connection/changelog/update-js-connection-use-connection-defaul-values
projects/js-packages/connection/components/use-connection/index.jsx

This PR defines default values for the `useConnection()` hook. So with these changes is possible to get connection data simply doing something like...
```jsx
const MyComponent = () => {
const { isRegistered } = useConnection();
return (
// ...
);
}
```
These data is picked from the `JP_CONNECTION_INITIAL_STATE` global var.
Fixes #
* JS Connection: add default arg values for the useConnection() hook
p1650476850617069/1650473629.299269-slack-C02TQF5VAJD
These change should not change the workflow of the connection flow, not introducing braking changes either.
I suggest testing the connectivity in My Jetpack overview page.

JS Connection: add default arg values for the useConnection() hook

---

projects/plugins/jetpack/changelog/sync-gmovr-r242892-wpcom
projects/plugins/jetpack/modules/masterbar/nudges/additional-css/class-atomic-additional-css-manager.php
projects/plugins/jetpack/modules/masterbar/nudges/additional-css/class-wpcom-additional-css-manager.php
projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-additional-css-manager.php
projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-additional-css-manager.php

This PR updates Jetpack following similar changes on WordPress.com.
﻿- Masterbar: Update nudge for Pro plan
- Update tests
WordPress.com references:
- D77832-code
- D77823-code
* N/A
* No
* See diffs above for instructions.
* Is CI happy?

Nav-unification: update nudge to support Pro plan.

---

projects/plugins/jetpack/changelog/fix-atomic-gutenberg-missing-styles
projects/plugins/jetpack/class.jetpack-gutenberg.php

Fixes #22787
* Enable the hotfix we use on Simple Sites for Atomic sites too.
* Use Jetpack Beta and switch to this branch
* Make sure that your site has Gutenberg plugin activated.
* Make sure that you have a FSE compatible theme installed.
* Go to Appearance > Editor (beta)
* Add the Donations block and make sure that it's styled properly.
* Note: the issue can be reproduced on all browsers, not just FIrefox.

Load block editor styles inline for iframed editors on Atomic sites

---

projects/packages/waf/actions.php
projects/packages/waf/changelog/add-waf-update-cron
projects/packages/waf/src/class-waf-runner.php

* Adds a cron to update the rules hourly
* Changes the way we connect to the remote API, when on a cron context we don't have a logged in user, so we need to connect to the API using a blog token instead of a user token.
1201069996155224-as-1201965730421001
No.
* Go to the cron events page under tool in your wp-admin and force the cron to run
* Verify that the rules were updated accordingly
* Verify that a timestamp of when the cron ran was saved in the `jetpack_waf_last_updated_timestamp` wp_option

WAF: Add cron to regularly update rules

---

tools/e2e-commons/config/default.cjs

A React warning started polluting the e2e tests logs. This PR adds it in the console ignore list.
n/a
no
* CI green

E2E tests: Ignore a console React warning that's polluting test logs

---

projects/packages/connection/changelog/update-remove_connection_function
projects/packages/connection/src/class-manager.php

We had 2 methods that were doing a very similar things: disconnecting jetpack.
`disconnect_jetpack` was doing some extra cleaning and also firing track events, while `remove_connection` was the preferred API for stand-alone plugins and did not perform those additional cleaning and tracking.
This PR unifies it all in `jetpack_disconnect` and makes `remove_connection` a simple proxy method with different default values for the parameters.
This ensures that Jetpack will still trigger disconnection events after https://github.com/Automattic/jetpack/pull/23957
Note: https://github.com/Automattic/jetpack/pull/23991 will also change `remove_connection` and it will end up with just one line.
* Make remove_connection a proxy method and centralize disconnection on just one method
p9dueE-4n9-p2
No
* …

Make remove_connection a proxy method

---

projects/js-packages/components/changelog/fix-text-component-reset
projects/js-packages/components/components/text/index.jsx
projects/js-packages/components/components/text/style.module.scss

Fixes #23954
This avoids applying reset for all elements, instead `Text` specifics, which was causing some problems on global styles.
* Apply directly `reset` class for `Text` component.
N/A
No.
* Open Storybook
* Navigate to `JS Packages/Components/Text`
* Check if `margins` and `padding` props are still being applied by props and default margin is still not being applied.
* Navigate to `My Jetpack`.
* Try to disconnect.
* Dialog should have the correct margin.

Components: Fix default reset for `Text` components.

---

projects/js-packages/components/changelog/tweak-dialog-and-product-offer-components
projects/js-packages/components/components/dialog/style.module.scss
projects/js-packages/components/components/product-offer/index.jsx
projects/js-packages/components/components/product-offer/style.module.scss
projects/plugins/protect/changelog/update-protect-update-connect-page
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/interstitial/index.jsx
projects/plugins/protect/src/js/components/interstitial/stories/index.jsx
projects/plugins/protect/src/js/components/product-offer/index.jsx

This PR replaces the usage of the `<ConnectionScreen />` component (which belongs to jetpack-connection pkg) by the Protect Interstitial page.
Disclaimer: It implements the connection workflow for the Protect plugin. Security bundle will be addressed in a follow-up PR.
Fixes #
* Security: replace ConnectionScreen with the Interstitial component. Relevant changes:
- Update AdminPage component
- Tweak Dialog and ProductOffer jetpack-components
- Simplify Protect interstitial page
* Disconnect the site
* Go to Protect plugin page
* Confirm you see the interstitial page
* Confirm you can connect the site by clicking on the `Get started with Jetpack Protect` button.
https://user-images.githubusercontent.com/77539/164505463-f90df7ec-9ff8-43af-b174-86950e3f4e20.mov

Protect: replace ConnectionScreen with the Interstitial component

---

projects/plugins/protect/changelog/update-protect-add-error-message-when-adding-plugin
projects/plugins/protect/src/js/components/product-offer/index.jsx

This PR adds error message to the Protect Offer component when adding the plugin fails.
Fixes #
* Protect: add error message when adding plugin fails
* Disconnect the site
* Go to Protect plugin page: `http://<your-testing-site>/wp-admin/admin.php?page=jetpack-protect`
* Test with localhost because it's easy to generate a `403` response error
* Try to add Protect
* You should see the error there
https://user-images.githubusercontent.com/77539/164784410-7496461a-31ba-4999-a7e6-f90bf5a2781f.mov
* Testing with a valid hostname it should connect
https://user-images.githubusercontent.com/77539/164784385-669d784a-367c-4fb1-b6f8-3534b0c11a11.mov

Protect: add error message when adding plugin fails

---

projects/plugins/jetpack/changelog/fix-recurring-payments-no-editor
projects/plugins/jetpack/extensions/index.json

Fixes #24031
* Do not load the Payment Button block on P2's frontend editor.
* N/A
* No
* On WordPress.com Simple, sandbox a P2 site
* Apply this patch (D79443-code)
* Open the site; you should see Jetpack blocks available in the block picker, such as the Markdown block or the Slideshow block.

Payments: do not load the block on P2's frontend editor

---

projects/plugins/jetpack/_inc/lib/class-jetpack-recommendations.php
projects/plugins/jetpack/changelog/update-plan-checks-for-conditional-recommendations
projects/plugins/jetpack/tests/php/_inc/lib/test-class-jetpack-recommendations.php

This PR updates the logical checks used for enabling conditional recommendations. Primarily, the updates check whether the site's plan provides given features in addition to checking the status of different modules or plugins to determine if a recommendation should be enabled.
No
This PR updates the logical checks for enabling the following conditional recommendations, which are each addressed below
* Security Plan
* Anti-spam
* VideoPress
Note: if you are using the same test site to test multiple scenarios below, you will need to reset the `recommendations_conditional` option between tests. If you are using the docker development environment, you can run the following command with `jetpack docker`:
```
wp jetpack options delete recommendations_conditional
```
**Security Plan**
* The …

Update checks for conditional recommendations

---

projects/plugins/protect/changelog/update-protect-fix-primary-layout-spacing
projects/plugins/protect/src/js/index.js
projects/plugins/protect/src/js/styles.module.scss

This PR sets box-sizing as border-box for all elements, fixing an annoying issue produced in the primary layout.
Fixes #
* Protect: fix right margin in primary layout
* Go to Protect page
* Check the layout size is fixed, removing an annoying horizontal scrollbar 
* 
* Confirm the page has a proper margin right.
before | after
------|------
---
- https://app.asana.com/0/0/1202182937012539

Protect: fix right margin in primary layout

---

projects/plugins/boost/app/features/optimizations/cloud-css/Cloud_CSS_Request.php
projects/plugins/boost/changelog/update-cloud-css-request-id

* Cloud CSS request is updated to contain a unique request ID with the help of timestamp.
NA
No
* Checkout the changes from this PR
* Follow the instructions in 53-gh-Automattic/boost-shield-api to test the logs
* Ensure that each request is listed separately under the `Requests` section in the dashboard.

Boost: Update Cloud CSS request to contain unique request ID

---

projects/plugins/protect/changelog/update-protect-summary-redesign
projects/plugins/protect/src/js/components/summary/index.jsx
projects/plugins/protect/src/js/components/summary/styles.module.scss

Update Summary to match the new layout.
⚠️ Storybook doesn't work right now, since we need to mock data.
* Remove cards from `Summary` component.
* Get data from `useProtectData` hook.
p1HpG7-fFV-p2
No.
* Start `Protect`
* Navigate to plugin page.
---
- 0-as-1202117981194293

Protect: Redesign `Summary` component

---

projects/plugins/boost/app/class-jetpack-boost.php
projects/plugins/boost/changelog/fix-boost-broken-uninstall-sql

On uninstall, this gets logged
```
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3 for query
DELETE
FROM    `wp_options`
WHERE   `option_name` LIKE jetpack_boost_%
```
The problem is that the argument to LIKE is not quoted.
p1651066777319939-slack-C01U2KGS2PQ
No
* Execute `wp plugin uninstall boost`.
* Check the logs. Without this PR the mentioned message should be logged, while with it the message should not be.

boost: Fix broken SQL query on uninstall

---

projects/plugins/protect/changelog/update-protect-list-section
projects/plugins/protect/src/js/components/admin-page/index.jsx

Move `VulnerabilitiesList` back to the hero section.
* Move `VulnerabilitiesList` to `AdminHeroSection`.
N/A
No.
* Start Protect
* Navigate to admin page.
* You should see `Vuls List` inside `Hero Section`

Protect: Move `VulnerabilitiesList` to hero section

---

projects/plugins/jetpack/_inc/client/at-a-glance/activity.jsx
projects/plugins/jetpack/changelog/update-glance_activity

I came across this as I was looking for `getSitePlan()` calls to be replaced with feature checks.
* No functional changes. 
* Removed code that was commented out in #8311.
No
Probably not necessary?
* Pull up the Jetpack Dashboard and verify the Activity box still displays the same message as before.

Activity: Remove unused code 

---

projects/packages/waf/changelog/fix-waf-db-log
projects/packages/waf/src/class-waf-runtime.php

* Fix db logging when a request is blocked by our WAF
p1650845956991089/1650639283.564489-slack-C029WFNV69M
No.
* Checkout this branch and build the plugin with all it's dependencies
* Force a request to be blocked with the `jetpack-waf-always-block` query string parameter
* Verify that the request was logged to the blocklog file and the database as well.
*

WAF: Save log info in the database

---

projects/plugins/protect/changelog/update-protect-implement-add-security-workflow
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/footer/index.jsx
projects/plugins/protect/src/js/components/interstitial/index.jsx
projects/plugins/protect/src/js/components/product-offer/index.jsx
projects/plugins/protect/src/js/components/product-offer/stories/index.jsx

This PR implements the Add Security checkout workflow. It uses the implementations done in https://github.com/Automattic/jetpack/pull/24122 and https://github.com/Automattic/jetpack/pull/24113.
Fixes #
* Protect: implement "Add Security plan" workflow.
* Test with a site with a Free plan
* No connected user either site
* Active Protect plugin
* Go to Protect plugin page
* You should see the interstitial page
* Click on `Add Security plan` to walk thourhg of the checkout process
* Confirm you get redirected to the Jetpack connect user page
* Once user connects, the client redirect to the checkout page
* Once you buy the plan, the client redirects to the Plugin page
* Confirm you don't see the interstitial page. Instead, you see the Protect plugin page …

Protect: implement "Add Security plan" workflow.

---

projects/js-packages/connection/changelog/update-re-organize-exposing-connection-data
projects/js-packages/connection/hooks/use-product-checkout-workflow/Readme.md
projects/js-packages/connection/hooks/use-product-checkout-workflow/index.jsx
projects/packages/connection/changelog/update-re-organize-exposing-connection-data
projects/packages/connection/src/class-initial-state.php
projects/plugins/protect/changelog/update-re-organize-exposing-connection-data
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/footer/index.jsx

This PR reorganizes the code among Connect, JS Connect, and the Protect plugin in order to make the API of some helpers and hooks simpler, making the focus on the recent `useProductCheckoutWorkflow()` custom hook.
Follow-up from https://github.com/Automattic/jetpack/pull/24122#discussion_r860154635
Fixes #
*
p1651081554136539-slack-C02TQF5VAJD
No
* Test with Protect plugin
* Connect the site
* You should see the Footer section, with the `Get Jetpack Security` button there
* Confirm the browser leads you properly to the checkout page. It will try to log in the user in case it isn't already logged.
* It should go back to the Protect primary page
* Also you can take a look at the URL, trying to confirm it's well-formed.
---
- To see the specific tasks where the Asana app for GitHub is being …

Reorganize how exposing and consuming connection data

---

projects/plugins/protect/changelog/update-protect-vuls-list-empty
projects/plugins/protect/src/js/components/summary/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/empty.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/styles.module.scss
projects/plugins/protect/src/js/components/vulnerabilities-list/use-vuls-list.js

Insert the empty mode, when no vulnerabilities have been found.
* Add `EmptyList` in `VulnerabilitiesList`.
* Do not select the initial item at `Navigation` if has no vul.
* Do not render the number of vuls text at `Summary` if has no vul.
1202064326332560-as-1202117981194332/f
No.
* Start `Protect`
* Navigate to admin page.
* Set `JETPACK_PROTECT_DEV__API_RESPONSE_TYPE` to `complete_green`.
* You should see empty state.

Protect: Add empty scenario for `List` and `Summary`

---

projects/plugins/jetpack/_inc/client/recommendations/product-card-upsell/index.jsx
projects/plugins/jetpack/changelog/fix-assistant-show-base-price

This PR makes sure a price is shown in the Assistant product cards, even if no introductory offer is available.
_Backup has no introductory offer, and the product card doesn't show any price_
Context: p8oabR-QB-p2#comment-6247
No.
**Regression testing**
- Make sure that your curency has an intro offer for Backup and Security, such as with USD
- Spin up a new JN site with this branch, and another one with the release candidate branch
- Complete the connection flow, getting Jetpack Free, with both of them
- Visit `/wp-admin/admin.php?page=jetpack#/recommendations/product-suggestions` in both sites, and make sure prices are the same
- Then visit `/wp-admin/admin.php?page=jetpack#/recommendations/summary` and do the same
**Actual testing**
- Update your currency to Turkish lira (TRY)
- Spin …

Assistant: Show product price if no intro offer

---

projects/plugins/jetpack/_inc/client/recommendations/prompts/prompt-layout/index.jsx
projects/plugins/jetpack/changelog/fix-assistant-discount-card-bg

This PR removes a lingering background showing behind the discount card in the Assistant, when starting the flow from the banner in the dashboard.
Context: [p8oabR-QB-p2#comment-6250](p8oabR-QB-p2#comment-6254)
No.
- Spin up a new JN site with this branch
- Complete the connection flow, getting Jetpack Free
- Visit `/wp-admin/index.php`
- Click _Continue_ in the Assistant banner in the dashboard
- You should now see the discount card in the Assistant. Make sure there's no background except the color blob behind the discount card.
_Before_
_After_

Assistant: Hide old background behind discount card

---

projects/plugins/jetpack/changelog/fix-contact-form-csv-export
projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php

Fixes #24170
Because of [a change in Core WordPress](https://github.com/WordPress/wordpress-develop/commit/99fd93c7dff9d3669f25f5f13a2358e65c14bde9), admin_post actions are now enforced. This PR changes a hook from `admin_init` to `admin_post_feedback_export` to prevent the page die-ing with 400.
See: p1651226424159739/1651215033.747819-slack-C01A60HCGUA
No
1. Go to My Site > Feedback
2. Click on Download button
3. CSV Export should be generated.

Fix Contact form CSV export

---

projects/plugins/jetpack/_inc/client/recommendations/sidebar/one-click-restores/index.jsx
projects/plugins/jetpack/changelog/update-oneclickrestores

Fixes #
* Replaces plan checks with a feature check to determine if the current site has real-time backups.
No
* [Create a jurassic ninja site](https://jurassic.ninja/specialops/) with a "Jetpack Backup (Real-time)" plan and Jetpack Beta with this branch being enabled.
* Connect to your site and chose a free plan
* Go through the recommendation steps until the last card.
* Make sure the sidebar card mentions "real-time backups" not daily backups.

One Click Restores: Use feature checks to determine backup type

---

projects/plugins/jetpack/_inc/client/state/recommendations/reducer.js
projects/plugins/jetpack/_inc/client/state/site/reducer.js
projects/plugins/jetpack/changelog/update-scan-feature-check

* Replaces purchase check with a feature check to determine if the current site has Scan.
No
* [Create a jurassic ninja site](https://jurassic.ninja/specialops/) with a "Jetpack Backup (Real-time)" plan and Jetpack Beta with this branch being enabled.
* Connect to your site and chose a free plan
* Go through the recommendation steps until the last card.
* Make sure the sidebar card shows the one-click backups card 
* Add a Scan plan to your site. It should now show the download app card.

Recommendations: Use feature check for one click restores

---

projects/plugins/jetpack/_inc/client/security/backups-scan.jsx
projects/plugins/jetpack/changelog/update-scan-settings-plan-checks

* Updates plan checks with feature checks in Backup & Scan settings.
No
* [Create a jurassic ninja site](https://jurassic.ninja/specialops/) with Jetpack Beta with this branch being enabled.
* Connect to your site and chose a free plan
* Navigate to `/wp-admin/admin.php?page=jetpack#/security`
* On sites without Jetpack Backup or Scan, a prompt to upgrade should show.  <img width="701" alt="Screen Shot 2022-04-28 at 2 37 31 PM" src="https://user-images.githubusercontent.com/1398304/165849916-d8dbd10b-39dd-4812-ab8b-c7d2ece05aef.png">
* On sites with Jetpack Backup but not Scan, the card should refer to configuring only Jetpack Backup. <img width="605" alt="Screen Shot 2022-04-28 at 2 46 42 PM" src="https://user-images.githubusercontent.com/1398304/165852027-3dff104b …

Security Settings: Use feature check in backup & scan

---

projects/js-packages/connection/changelog/revert-jetpack-soft-disconnect
projects/js-packages/connection/components/disconnect-dialog/steps/step-disconnect.jsx
projects/plugins/jetpack/_inc/client/components/jetpack-benefits/index.jsx
projects/plugins/jetpack/_inc/client/portals/plugin-deactivation.jsx
projects/plugins/jetpack/changelog/revert-jetpack-soft-disconnect
projects/plugins/jetpack/class.jetpack.php

Revert https://github.com/Automattic/jetpack/pull/23957
If this is shipped without https://github.com/Automattic/jetpack/pull/24105 we would lose some tracks and stats on jetpack disconnection.
* Reverts jetpack soft disconnection
* Activate a secondary plugin like Boost and/or Backup
* Go to Plugins
* Confirm the link to deactivate Jetpack says 'Disconnect and Deactivate'
* Click Disconect & Deactivate
* Confirm the dialog shows information about other connected plugins and about the active features
* Make sure all other plugins are disconnected when you deactivate Jetpack
* Make sure disconnecting from the Jetpack Dashboard still works and shows the survey

Revert Jetpack soft disconnect

---

projects/js-packages/components/changelog/update-js-components-spinner
projects/js-packages/components/components/button/style.module.scss

This PR fixes a visual issue in the Spinner components that happen for WordPress version < 6.0. Basically. The new spinner design from [WordPress/gutenberg#37551](https://github.com/WordPress/gutenberg/pull/37551) will be in WP 6.0 but isn't in 5.9 (thanks to @anomiex)
Fixes JS Components: fix weird spinner visual issue for WordPress < 6.0
*
* Go to Protect plugin
* Disconnect the site
* Testi with WP < 6.0
before | after
------|------
---
- https://app.asana.com/0/0/1202204855890091
- https://app.asana.com/0/0/1202203997123736

JS Components: fix weird spinner visual issue

---

projects/plugins/jetpack/_inc/client/recommendations/product-card-upsell/index.jsx
projects/plugins/jetpack/changelog/fix-assistant-no-intro-price

This PR corrects the price shown in the Assistant product cards when no intro offer is available.
Context: p8oabR-QB-p2#comment-6247
No.
- Update your currency to one that doesn't have an intro offer for Backup or Security, such as Turkish lira (TRY)
- Spin up a new JN site with this branch
- Complete the connection flow, getting Jetpack Free
- Visit `/wp-admin/admin.php?page=jetpack#/recommendations/product-suggestions`
- Check that for both Backup and Security, the prices matche what you see in the checkout page. Prices are shown by month in the former, and by year in the latter, so you'll have to divide/multiple by 12.

Assistant: Fix product price without intro offer  

---

projects/plugins/jetpack/_inc/client/components/settings-card/index.jsx
projects/plugins/jetpack/changelog/update-settings-plan-checks

- No functional changes, everything should work as before
- Moves from plan checks to feature checks to display the upsell nudges in Jetpack > Settings
p9dueE-4T6-p2
No.
* [Spin up a JN site using this branch](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack=update/settings-plan-checks).
* Set up Jetpack and start with a Free plan.
* Go to WP Admin > Jetpack > Settings.
* Make sure you see the following upsell nudges:
Feature | Settings
--- | ---
Anti-spam | <img width="1031" alt="antispam 1" src="https://user-images.githubusercontent.com/1233880/165951913-2d3dded0-13ef-4af5-a50a-7d008f6d82f8.png">
Google Analytics | <img width="1015" alt="google-analytics 1" src="https://user-images.githubusercontent.com/1233880/165951945-be84e9a4-e68f-405b-b8e3-24f46ec702dd.png">
Scan | <img …

Settings: Display upsells using feature checks

---

pnpm-lock.yaml
projects/js-packages/storybook/.gitattributes
projects/js-packages/storybook/changelog/fix-storybook-test-deps
projects/js-packages/storybook/composer.json
projects/js-packages/storybook/package.json
projects/js-packages/storybook/tests/deps.test.js

We have a comment at the top of projects.js asking that people keep the
list in sync with the list of dependencies in composer.json, but it
seems this is easy to miss. Let's also add a test checking for the
match.
For example, #23780 missed updating composer.json when adding to the
list, and since the dependency was missing #24078 didn't know to try
rebuilding storybook when plugins/protect was changed, which allowed it
to be merged and break the build in master (necessitating #24160).
p1651176382871569-slack-CBG1CP4EN
No
* Is CI happy? Did the new test run?
* Adjust composer.json and/or projects.js. Does the test fail if they don't match?

storybook: Test that deps match projects.js

---

projects/plugins/jetpack/changelog/fix-admin-menu-tests-wp6
projects/plugins/jetpack/tests/php/modules/masterbar/test-class-admin-menu.php

WordPress 6.0 will change how menus are positioned when there is a collision between items that are supposed to be in the same position: https://core.trac.wordpress.org/ticket/40927
In such cases, WordPress generates a pseudorandom number to be used as the position key in order to guarantee there are no duplicated keys. However, the logic for generating that number has changed in WordPress 6.0.
We had a couple of tests that relied on such number, so to avoid failures in these tests in WordPress 6.0 this PR adapts their implementation to don't rely in it.
Originally reported by @david-binda in D79094-code.
* See #24082
No.
Make sure tests pass.

Admin menu: Avoid usage of pseudorandom numbers in tests

---

projects/plugins/protect/changelog/update-protect-learn-more-link
projects/plugins/protect/src/js/components/footer/index.jsx
projects/plugins/protect/src/js/components/footer/styles.module.scss

Fixes #
* Protect: use weight Button prop to style the "learn more" footer link
* Go to Protect dashboard
* Confirm the "Learn More" link looks ok ( `font-weight`: 400 )
---
- https://app.asana.com/0/0/1202211721983865

Protect: use weight Button prop to style the "learn more" footer link

---

projects/packages/publicize/changelog/update-publicize-calpyso-redirect-url
projects/packages/publicize/composer.json
projects/packages/publicize/package.json
projects/packages/publicize/src/class-publicize-base.php
projects/packages/publicize/src/class-publicize-ui.php
projects/plugins/jetpack/changelog/update-publicize-calpyso-redirect-url
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock
projects/plugins/jetpack/modules/publicize/publicize.php
projects/plugins/jetpack/modules/publicize/ui.php
projects/plugins/social/changelog/update-publicize-calpyso-redirect-url
projects/plugins/social/composer.json
projects/plugins/social/composer.lock

Broken down from https://github.com/Automattic/jetpack/pull/24172
* Moved the standalone function publicize_calypso_url into the Publicize Base class. This was done because the method publicize_calypso_url will be called from the Jetpack Social plugin using the global $publicize object.
* publicize_calypso_url, now accepts a param called $source, which will determine the redirect URL. If the source is `jetpack-social-connections-classic-editor` or `jetpack-social-connections-admin-page`, the user will be redirected to Jetpack Cloud, if they only have the Jetpack Social plugin enabled and the Jetpack plugin is disabled. 
* The above change has been done in the Publicize files of the Jetpack plugin modules directory as well as the Publicize package. Jetpack the plugin and Jetpack Social use …

Publicize: add calypso redirect URLs #

---

projects/packages/waf/actions.php
projects/packages/waf/changelog/fix-waf-package-actions

* This changes the actions file to return early if the waf module is disabled.
p1651249885661069-slack-C029WFNV69M
No.
* Disable the WAF module.
* Verify that the cron wasn't scheduled.
* Define the IS_WPCOM constant.
* Verify that no code from actions.php is executed when the constant is defined.

WAF: Don't execute code if on WPCOM

---

projects/packages/sync/changelog/update-must-sync-data-settings
projects/packages/sync/src/class-data-settings.php
projects/packages/sync/src/modules/class-full-sync-immediately.php
projects/packages/sync/tests/php/data-test-data-settings.php

Ensures that the Full Sync module is always present, no matter the plugin's (consumer) Sync related config.
Full Sync is required for the Initial Sync to trigger upon establishing a Site Connection.
* `Automattic\Jetpack\SyncData_Settings`: Adds `Full_Sync_Immediately` module  in `MUST_SYNC_DATA_SETTINGS`
* `Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately`: Fixes a bug that prevented the Initial Sync to start successfully if `Users` Sync module was not loaded.
p9dueE-51L-p2
No
TBD

Jetpack Sync Config: Full Sync module in "must sync" settings

---

tools/docker/Dockerfile

While nothing we have requires it, it's a "nice to have" and WordPress's
site health screen complains if it's missing.
None
No
* Once the "Build Docker" job here finishes, change [tools/docker/docker-compose.yml line 37](https://github.com/Automattic/jetpack/blob/add/docker-php-intl-module/tools/docker/docker-compose.yml#L37) to point to `ghcr.io/automattic/jetpack-wordpress-dev:pr-24249` and restart your docker env (`jetpack docker stop && jetpack docker up -d`). The Site Health screen in wp-admin should no longer complain about "One or more recommended modules are missing".

docker: Add PHP's intl module to the docker env

---

projects/plugins/protect/changelog/update-clear-protect-cache-deactivation
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/class-status.php

* Flush cache on plugin deactivation
N/A
No
* Activate and connect Protect
* Make sure the option is populated: `wp option get jetpack_protect_status`
* Deactivate the plugin
* Make sure the option was deleted
---
- https://app.asana.com/0/0/1202210952011303

Protect: Flush cache on plugin deactivation

---

projects/plugins/protect/changelog/update-protect-pull-security-bundle-data
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/js/hooks/use-protect-data/index.js
projects/plugins/protect/src/js/state/actions.js
projects/plugins/protect/src/js/state/reducers.js
projects/plugins/protect/src/js/state/resolvers.js
projects/plugins/protect/src/js/state/selectors.js
projects/plugins/protect/src/js/state/store.js

This PR exposes the Security bundle data to the client. For this:
* It requests the Security bundle product taking advantage of the My Jetpack Products class
* Exposes from the server-side to the client through `jetpackProtectInitialState` the global var.
* Propagate the data via the Protect Store.
Fixes #
* Protect: request and expose to the client the Security bundle data
No
* No UI changes here.
* Go to Protect plugin
* Get the protect data via the getSecurityBundle() selector
```
wp.data.select( 'jetpack-protect' ).getSecurityBundle()
```
---
- https://app.asana.com/0/0/1202230042727404

Protect: request and expose to the client the Security bundle data

---

projects/plugins/protect/changelog/update-add-protect-error-icon
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/admin-page/styles.module.scss
projects/plugins/protect/src/js/components/alert-icon/index.jsx
projects/plugins/protect/src/js/components/alert-icon/stories/index.jsx

This PR adds an SVG Alert icon when having problems scanning the site. It's a follow up of https://github.com/Automattic/jetpack/pull/24261
Fixes #
*
* Take a look at the Alert Icon story: `http://localhost:50240/?path=/story/plugins-protect-alert-icon--default`
* Take a look at Protect overview page
---
- https://app.asana.com/0/0/1202230774714214

Protect: Add alert icon when having problem scanning the site

---

projects/plugins/protect/changelog/update-protect-add-scan-to-footer
projects/plugins/protect/src/js/components/footer/index.jsx

When the site already has the Security bundle product, we'd like to suggest the Jetpack Scan to customers. That's what this PR does.
Based on the site's plan data, it switches between offering the Security product or suggesting getting started to use Jetpack Scan.
~Disclaimer: the link to the Jetpack Scan is not defined.~ Set redirect URL with `protect-footer-get-started-scan`
Fixes #
* Protect: Add Jetpack Scan to promotion section when site has Security bundle
* In the Protect dashboard
* With a site without a Security plan, confirm you see the Security bundle suggestion
* With a site with a Security plan, confirm you see the Jetpack Scan suggestion
With security bundle | Without security bundle
------|------
---
- To see the specific tasks where the Asana app for GitHub is being used, …

 Protect: Add Jetpack Scan to footer promotion section

---

projects/packages/waf/changelog/allow-rules-api-401
projects/packages/waf/src/class-waf-runner.php

This PR prevents 401 responses from the rules.php API endpoint from throwing exceptions. Jetpack users without a plan that includes Scan still have access to the Firewall/WAF module, so a `401` in this case can be a valid and acceptable response.
* Includes request response code in connection exception thrown in `get_rules_from_api()`.
* Adds a new `$throw_api_exception` that is set to `false` when the exception code is `401`, and then related exceptions are only thrown when `$throw_api_exception` evaluates as true.
1201069996155217-as-1202234313419420/f
No
* Spin up a Jetpack site with a free plan.
* Activate, deactivate, then reactivate the WAF module from the settings screen.
* Validate that there are no errors.

WAF: Do not throw API exceptions for users who do not have API access

---

projects/js-packages/connection/changelog/update-jetpack-soft-deactivation
projects/js-packages/connection/components/disconnect-dialog/steps/step-disconnect.jsx
projects/plugins/jetpack/_inc/client/components/jetpack-benefits/index.jsx
projects/plugins/jetpack/_inc/client/portals/plugin-deactivation.jsx
projects/plugins/jetpack/changelog/update-jetpack-soft-deactivation
projects/plugins/jetpack/class.jetpack.php

This reverts commit https://github.com/Automattic/jetpack/commit/14de12accb24de15c01deee738ca6c9b04a2c5df.
and brings back https://github.com/Automattic/jetpack/pull/23957
* Do not hard disconnect Jetpack on plugin deactivation
p9dueE-4n9-p2
No
* Activate a secondary plugin like Boost and/or Backup
* Go to Plugins
* Confirm the link to deactivate Jetpack says only "Deactivate" (and not 'Disconnect and Deactivate')
* Click Deactivate
* Confirm the dialog shows information about the active features you have and no mention to other plugins
* Test with different Jetpack modules active
* Make sure disconnecting from the Jetpack Dashboard still works and shows the survey

Do not hard disconnect Jetpack on deactivation

---

projects/plugins/starter-plugin/changelog/update-starter-plugin-hooks
projects/plugins/starter-plugin/jetpack-starter-plugin.php
projects/plugins/starter-plugin/src/class-jetpack-starter-plugin.php

* add activation and deactivation hooks to the Starter plugin
N/A
No
* Generate a new plugin using `jetpack generate` CLI command
* Make sure to use the Starter plugin as a base when asked
* Check that all additions of this PR have been correctly replaced to the new plugin slug
* Build your new plugin
* Activate your new plugin
* Confirm you got redirected to the plugin's page
* Connect
* Go to Plugins
* Make sure the "Settings" link takes you to the plugin's page
* Deactivate the plugin
* Make sure the site got disconnected (if there was no other active plugin using the connection)

Starter plugin: add activation and deactivation hooks

---

projects/plugins/jetpack/changelog/fix-subs-typo-message
projects/plugins/jetpack/modules/subscriptions/views.php

Fixes #24287
* Fix mistake in confirmation message.
* N/A
* No
* Start from a site that's connected to WordPress.com, and where you have enabled the Subscriptions feature.
* In Appearance > Themes, switch to a non-block theme like Twenty Twenty.
* Go to Appearance > Widgets and add a blog subscriptions widget.
* On the frontend of your site, use a test email to subscribe your testing site.
* Confirm your subscription.
* Go back to the frontend of your site, and try to subscribe again using that same email address.
* See the error message with the new wording.

Subscriptions: fix mistake in pending message

---

tools/cli/commands/changelog.js

* When running `jetpack chaneglog add`, print an example of a good changelog entry.
Internal: p9dueE-4R7-p2#comment-7754
No.
* After patching, make a change to one of the project files (e.g. Jetpack), then try running `jetpack changelog add`.
* You should see the help text printed as such:

Jetpack CLI: add example of a change entry for the 'add' command

---

projects/plugins/jetpack/changelog/update-lazy-load-instagram-block-images
projects/plugins/jetpack/extensions/blocks/instagram-gallery/instagram-gallery.php

* Add the `loading=lazy` attribute to the images fetched by the block.
Note: unfortunately I don't see width/height dimensions returned by the current Instagram API implementation we use, it'd be nice to have this for the images to prevent reflow.
Alongside #24277 this closes #19086
No.
- Pre-patch, add a Instagram Latest Posts block to a test post (requires connection). Place a large spacer block above the Instagram one to test the lazy load aspect. Inspect the HTML of the block images to see that they don't contain the `lazy` attribute.
- Post-patch, you should be able to see the `lazy` attribute, and if you inspect the network tab the images should load in lazily on page scroll.

Latest Instagram Posts block: lazy load the images

---

projects/packages/redirect/changelog/fix-get-site-suffix-subdirectory-woa-sites
projects/packages/redirect/tests/php/test-redirect.php
projects/packages/status/changelog/fix-get-site-suffix-subdirectory-woa-sites
projects/packages/status/src/class-status.php
projects/packages/status/tests/php/test-status.php

Fixes https://github.com/Automattic/wp-calypso/issues/61464
Changes the `get_site_suffix` function to use the `site_url` option on WoA sites to avoid plugins from interfering with the site suffix, since there are some plugins like WPML that may change the main url to `<DOMAIN>/<LOCALE>` which breaks the navigation to Calypso.
p9F6qB-8EL-p2
No.
- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/) on a WoA site.
- Go to `/wp-admin/admin.php?page=jetpack-beta&plugin=jetpack` and switch to the branch of this PR.
- Add the code below to your WoA site to overwrite your `home_url` option with a fake locale path (*):
```
add_filter( 'home_url', function( $home_url ) {
return $home_url . '/en';
} );
```
- Make sure that all links to Calypso (`wordpress.com`) in the …

Status: Get site suffix from site URL on WoA sites

---

projects/packages/my-jetpack/_inc/components/connection-screen/index.jsx
projects/packages/my-jetpack/changelog/update-my-jetpack-connection-add-from

* Begins attributing connections coming from My Jetpack by adding the `from` prop
* Adds `redirectUri` arg to support the ability to redirect the user back to My Jetpack after the user connection. Note the word prepare, because it'll require a patch on WPCOM to actually do the redirect back.
Related to #24251. I want to redirect users back to My Jetpack after connection when that user's connection originates from My Jetpack. To do that, we need to now the `from` and `redirectUri`.
But, more importantly, we need the `from` to attribute the connection.
Yes. But, I don't believe in a meaningful way that requires privacy updates. 
It begins adding `my-jetpack` as the `from` arg in the connection URL when the user originates a connection from My Jetpack. We already track this `from` arg …

My Jetpack: Add from and redirectUri args to connection

---

projects/plugins/boost/app/lib/class-connection.php
projects/plugins/boost/changelog/boost-update-disconnection

This PR updates the usage of the connection package using the proxy method instead of calling individual methods for each step of the disconnection routine.
The new methods make sure we fire the proper hooks and trigger stats and tracks events.
There should be no functional changes.
Also, do not enable plugin on connection (this is deprecated). As a suggestion, Boost could use the v4 REST endpoint provided by the connection package to establish the connection, no need to build its own server-side connection method.
I also deleted some `todo` comments:
```
// @todo: implement clearing of IDC options
// Jetpack_IDC::clear_all_idc_options();
```
If this is needed, it should be handled by the IDC package. I'm creating a task to check on that
```
// @todo: implement check of updating activated …
```

Boost: Update connection usage

---

projects/packages/lazy-images/changelog/update-lazy-images-filter-init
projects/packages/lazy-images/src/lazy-images.php

- Change `Jetpack_Lazy_Images::__construct` to `setup_filters` on hook `the_post` rather than `wp_head`.
-  [the_post](https://developer.wordpress.org/reference/hooks/the_post/) - "Fires once the post data has been set up." Which I think makes more sense than `wp_head` since Lazy Images modifies the posts contents.
This change hopes to resolve the following issues for Jetpack Lazy Images:
1. Not working for block themes, closes #24253
2. Not working for admin post views.
3. Not working for Latest Instagram Posts block #19086
Closes #15354
n/a
No.
- For `#1` above, follow instructions in #24253
- For `#2`, you can then switch two theme Twenty Twenty and try viewing your test post as an admin to see that the Jetpack Lazy Images isn't running as expected (look for the `jetpack-lazy-image` …

Lazy Images: run lazy-images setup filters to run on 'the_post'

---

projects/packages/waf/changelog/add-waf-update-endpoint
projects/packages/waf/src/class-waf-endpoints.php

* This adds an endpoint that will be called after a plan that includes our WAF is bought so the customer can get updated rules.
1201069996155224-as-1202197114468148
No.
* Call this endpoint for a site that has a scan subscription.
* Verify that the rules were updated.

WAF: Add endpoint to update rules on demand

---

.github/workflows/renovate.yml

Yesterday a run failed because the token hit the 5000/hr rate limit.
Let's track the rate limit on each run to see whether it seems the token
is chronically near the limit or if that was a fluke.
Note hitting the /rate_limit endpoint doesn't itself count towards the
rate limit.
p1652358268639879-slack-CBG1CP4EN
No
* Look at the dry run at https://github.com/Automattic/jetpack/runs/6406008517?check_suite_focus=true

renovate: Log GitHub API rate limits pre- and post-run

---

projects/plugins/boost/changelog/improve-boost-wordpress-org-screenshots
projects/plugins/boost/readme.txt

The WordPress.org readme had an old screenshot. This PR adds reference to the new screenshots - added a before and after speed score screenshot.
No changes to Boost code
Not applicable. Small change.
No
Check that the new screenshots appear on the listing and they have captions

Boost: New Screenshots and Readme reference

---

projects/packages/backup/changelog/update-my-jetpack-add-protect-product-data
projects/packages/backup/composer.json
projects/packages/my-jetpack/changelog/update-my-jetpack-add-protect-product-data
projects/packages/my-jetpack/composer.json
projects/packages/my-jetpack/package.json
projects/packages/my-jetpack/src/class-initializer.php
projects/packages/my-jetpack/src/class-products.php
projects/packages/my-jetpack/src/products/class-protect.php
projects/plugins/backup/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/backup/composer.lock
projects/plugins/boost/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/boost/composer.json
projects/plugins/boost/composer.lock
projects/plugins/jetpack/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/jetpack/composer.json
projects/plugins/jetpack/composer.lock
projects/plugins/protect/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/protect/composer.json
projects/plugins/protect/composer.lock
projects/plugins/search/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/search/composer.json
projects/plugins/search/composer.lock
projects/plugins/social/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/social/composer.json
projects/plugins/social/composer.lock
projects/plugins/starter-plugin/changelog/update-my-jetpack-add-protect-product-data
projects/plugins/starter-plugin/composer.json
projects/plugins/starter-plugin/composer.lock

This PR adds the Protect class. It's a pretty basic implementation but useful to enhance when required. So far, it simply defines data about the product such as title, description, price, etc.
And since it's included in the products list, the data is available via the product endpoint and propagated to the client, too, in the My Jetpack global var.
Fixes #
* My Jetpack: Add Protect class
The easiest way to test the whole approach is to check whether the Protect data is available to the client, either looking at the global bar or using the `getProduct()` selector.
* Go to My Jetpack overview page
* Type the whole protect file path `myJetpackInitialState.products.items.protect`
* Confirm you see the data there
* Select the data by using the proper selector: …

My Jetpack: Add Protect class

---

projects/packages/codesniffer/Jetpack/ruleset.xml
projects/packages/codesniffer/changelog/update-ruleset-wordpress

While the rule is important, we currently attempt to autofix PHPCS errors in our pre-commit hook. When this happens and an array key is automatically renamed from wordpress to WordPress for example, we may inadvertently add errors via the automated tools.
Let's not do that.
Related discussion: p1652454457615319-slack-CBG1CP4EN
No
* Branch off from this branch.
* Locally, edit an array in a PHP file to add a `'wordpress' => 'bar'` pair. You can do so [here](https://github.com/Automattic/jetpack/blob/e9eeab71ce1644416f6b94f1830742f48b8b7436/projects/plugins/jetpack/modules/custom-post-types/nova.php#L174) for example.
* save your changes, stage and commit.
* Ensure that `wordpress` wasn't automatically updated to `WordPress`.

Codesniffer: allow the use of lowercase WordPress

---

projects/js-packages/components/changelog/update-dialog-component-api
projects/js-packages/components/components/dialog/index.tsx
projects/js-packages/components/components/dialog/stories/index.tsx
projects/js-packages/components/components/dialog/stories/js-components.components.dialog.story.mdx
projects/js-packages/components/components/dialog/stories/style.module.scss
projects/js-packages/components/components/dialog/style.module.scss
projects/js-packages/components/components/text/stories/Text-MDX-Documentation.mdx
projects/plugins/protect/changelog/update-dialog-component-api
projects/plugins/protect/src/js/components/footer/index.jsx
projects/plugins/protect/src/js/components/interstitial/index.jsx

This PR iterates over the Dialog component.
1. Rename the `split` property by `isTwoSections`.
It's more aligned with the design terminology.
3. Start to handle layout on mobile.
Taking advantage of the new `useBreakpointsMatch()` hook, it shows or hides the `secondary` section when the Dialog is in one-section mode. Next issues will be addressed in follow-up PRs
4. General Dialog stories improvements.
5. Defines `secondary` Dialog property as optional.
Some points to keep in mind:
* most of the changes are about Dialog stories.  Not a big deal.
* `<Dialog />` component is used only by the Protect plugin, reducing the probability of adding breaking changes.
There is still stuff to tweak in mobile: margins, padding, etc. It's going to be handled in a follow-up PR.
Fixes #
* JS Components: …

JS Components: rename split Dialog property. Handle layout on mobile.

---

projects/plugins/protect/changelog/update-protect-remove-product-mock-data
projects/plugins/protect/src/class-jetpack-protect.php
projects/plugins/protect/src/js/components/interstitial/stories/mock.js
projects/plugins/protect/src/js/components/product-offer/index.jsx
projects/plugins/protect/src/js/components/product-offer/stories/index.jsx
projects/plugins/protect/src/js/hooks/use-protect-data/index.js
projects/plugins/protect/src/js/state/actions.js
projects/plugins/protect/src/js/state/reducers.js
projects/plugins/protect/src/js/state/selectors.js

This PR takes advantage of the data provided by My Jetpack to remove the mock product data.
This is a follow-up of https://github.com/Automattic/jetpack/pull/24347.
Fixes #
* Protect: use data provided by My Jetpack to render Product offer
Should not be any visual change in the UI, but anyway:
**Using storybook**
* Go to [Plugins / Protect / Product Offer story](http://localhost:50240/?path=/story/plugins-protect-product-offer--default)
* Confirm the data shown by the component is right
**Using Protect plugin page**
* Disconnect the site
* Go to Protect plugin page
* Confirm the data shown there is right
* Get the protect data using the selector:
```
wp.data.select( 'jetpack-protect' ).getProductData()
```
---
- To see the specific tasks where the Asana app for …

Protect: use data provided by My Jetpack to render Product offer

---

projects/plugins/boost/app/lib/critical-css/Critical_CSS_State.php
projects/plugins/boost/changelog/update-cloud-css-timeout-error

This PR partially addresses #24115 
* Updated descriptive Cloud CSS timeout error message.
NA
No
* Define a small timeout window by updating [HOUR_IN_SECONDS](https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/lib/critical-css/Critical_CSS_State.php#L92)
* Update Cloud CSS to never generate CSS by updating [request_generate](https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/features/optimizations/cloud-css/Cloud_CSS.php#L125)
* Visit Jetpack Boost plugin Dashboard
* Enable "Automatically Optimize CSS Loading" or click "Refresh"
* Wait for the timeout and ensure that the following message is displayed: "Timeout while waiting for Critical CSS from the Boost Service"

Boost: Update Cloud CSS timeout error message

---

projects/packages/my-jetpack/_inc/components/plans-section/index.jsx
projects/packages/my-jetpack/changelog/Hide Activate a license link if there is no user connection since user connection is required

Updates the link for activating a license such that it will send users to the connection screen when there is no user connection.
We do this because activating a license requires a user connection. It _may_ be possible to make license activation not require a user connection, but that could lead to some weird flows.
NA
No
* Checkout branch
* Set `define( 'JETPACK_ENABLE_MY_JETPACK_LICENSE', true );`
* Connect your site but do not complete the user connection
* Go to "My Jetpack" page
* Ensure that you see a link prompting you to connect your site to activate a license
* Click that link
* Connect your site
* Click "Start for free" to return to your site
* Navigate to My Jetpack again. Yes, this is borked, but on a larger level which we need to fix for standalone plugins generally. See …

My Jetpack: Update "Activate a license" link to send user to connection when not user connnected

---

projects/plugins/boost/app/class-jetpack-boost.php
projects/plugins/boost/changelog/add-track-boost-deactivation

Fixes 42-gh-Automattic/boost-shield-api
* Track Boost deactivation
pbNhbs-2k2-p2#comment-7439
Yes, the plugin now tracks when it is deactivated.
* Activate Jetpack Boost
* Deactivate Jetpack Boost
* Search event name `jetpack_boost_deactivate_plugin` in tracks

Track boost deactivation

---

projects/plugins/jetpack/_inc/client/performance/search.jsx
projects/plugins/jetpack/_inc/client/performance/test/component.js
projects/plugins/jetpack/_inc/client/performance/test/fixtures.js
projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php
projects/plugins/jetpack/changelog/fix-remove-search-widget-cta-on-uneligible-themes
projects/plugins/jetpack/tests/php/_inc/lib/test-class-jetpack-redux-state-helper.php

Fixes https://github.com/Automattic/wp-calypso/issues/60362
* Removes search widget CTA in "WP Admin -> Jetpack -> Settings -> Performance  -> Search" on uneligible themes. Before the change, the search widget was displayed regardless of widget support in the currently used theme.
N/A
No
* Log in to WP Admin
* Ensure that the site uses a theme that supports widgets eg. "Blask"
* Go to "Jetpack -> Settings" and then open the "Performance" tab
* Enable "search" and disable "instant search experience"
* Validate that the "Add Jetpack Search Widget" button exists in the "Search" panel
* Log in to WP Admin
* Ensure that the site uses a theme that doesn't support widgets eg. "Twenty Twenty-Two" or "Blockbase"
* Go to "Jetpack -> Settings" and then open the "Performance" tab
* Enable "search" …

Search: Remove search widget cta on uneligible themes

---

pnpm-lock.yaml
projects/plugins/boost/changelog/update-boost-use-consistent-tsconfig
projects/plugins/boost/package.json
projects/plugins/boost/tsconfig.json
tools/js-tools/tsconfig.base.json

In preparation for #24329 and to have a consistent TS type checking, we need to use a consistent TS configuration throughout the monorepo. Only Boost uses its own `tsconfig.json` which is different from other areas of the codebase.
- This PR updates `plugins/boost/tsconfig.json` to use a consistent config by extending `js-tools/tsconfig.base.json` in order to have a consistent tsconfig throughout the monorepo. Previously, it extended [`@tsconfig/svelte/tsconfig.json`](https://unpkg.com/browse/@tsconfig/svelte@3.0.0/tsconfig.json).
- The new config retains the existing config though, by copying over the three different options from `@tsconfig/svelte/tsconfig.json`.
No
* Run `jetpack build plugins/boost` and `jetpack build --all`
* Confirm that the build is successful.

Update boost/tsconfig to use js-tools/tsconfig.base.json

---

projects/js-packages/components/changelog/update-protect-interstial-md-size
projects/js-packages/components/components/dialog/index.tsx
projects/plugins/protect/changelog/update-protect-interstial-md-size
projects/plugins/protect/src/js/components/interstitial/index.jsx
projects/plugins/protect/src/js/components/interstitial/styles.module.scss

This PR reduces the padding in both sections of the Interstitial page when on medium viewport size.
Also, it sets up the Dialog layout depending on this breakpoint, from `5 | 3` to `4 | 4`
Disclaimer: there is still an issue that we need to tackle to make the UI better in different screen sizes.
Fixes #
* Set up the Dialog grid depending on the viewport size.
* Tweak primary and secondary sections of Dialog in small and medium viewport sizes
* Go to Protect dashboard
* Disconnect the site in case it's already connected
* Take a look at the interstitial page
* play with the viewport size. You'd like to use the mobile tool of our client
* Confirm the page looks better
before  | after
------|-------

Protect: polish interstitial page in medium viewport size

---

projects/plugins/jetpack/changelog/update-subscriptions-confirmation-request-email-default-body
projects/plugins/jetpack/modules/subscriptions.php

The proposed change updates the default "Blog follow email text" setting (in `wp-admin/options-reading.php`). The new default copy is used in the "Confirmation Request" email template:
Before:
After:
- related Slack discussion: p1652335378623919-slack-C02TCEHP3HA
- related WPCOM patch: D80915-code
Make sure the Subscriptions are enabled:
1. Apply the PR
2. Navigate to `wp-admin/options-reading.php` settings page and make sure the new default text is displayed
3. If you replaced the default text with a custom one before, the proposed change won't have any effect on that custom text

Update "Confirmation request" email default body

---

projects/plugins/protect/changelog/update-protect-small-viewport-list-navigation
projects/plugins/protect/src/js/components/navigation/group.jsx
projects/plugins/protect/src/js/components/navigation/index.jsx
projects/plugins/protect/src/js/components/navigation/item.jsx
projects/plugins/protect/src/js/components/navigation/styles.module.scss
projects/plugins/protect/src/js/components/navigation/use-menu-navigation.js
projects/plugins/protect/src/js/components/vulnerabilities-list/index.jsx
projects/plugins/protect/src/js/components/vulnerabilities-list/navigation.jsx

Add a new mode for `Navigation` component and use it in `small/medium` viewports.
* Introduce `dropdown` mode at `Navigation`.
* Use `dropdown` mode in `small/medium` viewports.
N/A
No.
* Start `Protect`.
* Navigate to `Protect` admin page.
* Reduce the viewport and interact with navigation dropdown.
https://user-images.githubusercontent.com/1663717/168929300-2098a260-d0da-469a-bb90-84dff6639cd1.mp4

Protect: Introduce `Navigation` dropdown mode

---

projects/plugins/jetpack/changelog/update-stats-smiley-css
projects/plugins/jetpack/modules/stats.php

Fixes #24423
* Remove a `type` attribute that's not really necessary anymore, it was really only useful with HTML4.
* N/A
* No
* Start from a site connected to WordPress.com with the Stats feature active.
* Open the site in an incognito window.
* You should not see any smiley face in the footer of your site.

Stats: remove unnecessary type attribute from style element.

---

projects/plugins/jetpack/changelog/fix-vp-core-video-validation
projects/plugins/jetpack/extensions/blocks/videopress/editor.js

- For the block `attributesDefinition` VideoPress provides, add a selector for the `src` attribute.
If a video block does not have a VideoPress `guid`:
https://github.com/Automattic/jetpack/blob/f9674a61bea783593236c1ac87887ff59422736a/projects/plugins/jetpack/extensions/blocks/videopress/save.js#L42-L53
We send things back to the `core/video` save method - which should have a valid src to [save](https://github.com/WordPress/gutenberg/blob/5623107f40907061ce670d8cfe51641a1cd47bd9/packages/block-library/src/video/save.js#L24-L26).
Fixes #23953
No.
Before patching, reproduce validation error:
- Disconnect and deactivate Jetpack plugin.
- Create/edit a post and add a core video block with a video of your choice.
- Reactivate and connect Jetpack.
- Open the test post for editing again and …

VideoPress: fix validation error for core/video

---

.github/workflows/block-performance.yml

Changes to `.pnpmfile.cjs` introduced by #24355 broke the setup step in Block Performance tests job. Gutenberg requires node 14, and the changes introduce the use of logical OR assignment that's only available on Node >= 15. 
Since Gutenberg only needs Node, I replaced the `.github/actions/tool-setup` with `actions/checkout@v3`, thus skipping the `.pnpmfile.cjs`
n/a
no
- See run [6505198228](https://github.com/Automattic/jetpack/runs/6505198228?check_suite_focus=true)

[Performance tests] Fix performance tests broken setup

---

tools/cli/commands/docker.js

- Check to make sure Docker is running before executing `jt-up` command.
- When running `jt-up`, check to see if the default `jetpack_dev_wordpress*` container is up and running, if not print some help text.
- When running `jt-down`, don't show the "Remember! This is creating a tunnel..." message since we are disconnecting.
> Could we detect that Docker is not up yet and either bring it up or at least provide notice that jetpack docker up -d is needed.
I decided to go with just some help text here. The `jt-up` command could fail for other reasons aside from the container not being started, so trying to check for the container status or bring it up manually seems heavy-handed. We also don't know if people prefer running detached `-d` or not for example.
Closes #22540
No.
- Before patching, …

JP CLI: add help text for jt-up command failures

---

projects/plugins/jetpack/changelog/fix-notice-widget-visibility-1135
projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php

In some scenarios (maybe with some other plugins impacting widgets), one can run into the following warning:
```
Warning: Invalid argument supplied for foreach() in /var/www/wp-content/mu-plugins/jetpack-10.9/modules/widget-visibility/widget-conditions.php on line 1135
```
Let's try to avoid that.
Internal references:
- pcfWIW-Rj-p2#comment-2430
- p1653037254767549-slack-CDD9LQRSN
* No
* I'm not super clear on how to reproduce the original warning, but I would recommend enabling the Widget Visibility feature and ensuring it still works properly.
* Note that you need to use a theme that supports widgets to be able to use the feature. Twenty Twenty is a good example.

Widget Visibility: avoid PHP warnings when loading widgets.

---

projects/plugins/social/changelog/add-jetpack-social-admin-design
projects/plugins/social/src/js/components/admin-page/index.jsx
projects/plugins/social/src/js/components/connection-screen/index.js
projects/plugins/social/src/js/components/connections/index.js
projects/plugins/social/src/js/components/connections/styles.module.scss
projects/plugins/social/src/js/components/module-toggle/index.js

This is a very simple PR that moves some of the components in the Jetpack Social admin page to their own file. The main goal is to make future iterations easier to review.
* Move some components to their own files.
N/A
No.
* Build the plugin files: `jetpack build plugins/social`
* Make sure the connection screen still displays properly and that you can connect.
* After connection, confirm that the module toggle works (use `jetpack docker wp option get jetpack_active_modules` to check for the Publicize module).
* Make sure social media connections show in the admin screen.

Social: Extract component to their own files

---

projects/packages/lazy-images/changelog/2022-05-23-13-59-05-035657
projects/packages/lazy-images/src/lazy-images.php

Let's short-circuit early in RSS feeds, we do not need to be lazy loading images there.
References:
- Follow-up from #24277
- https://github.com/Automattic/newspack-plugin/pull/1658
- p1653313484308279-slack-CBG1CP4EN
* No
* Start with a Jetpack site where you've activated the Lazy Load feature under Jetpack > Settings > Performance.
* Publish a few posts with some featured images set for each post.
* Install ["Shoyu RSS/Atom Feed Preview" chrome extension"](https://chrome.google.com/webstore/detail/shoyu-rssatom-feed-previe/ilicaedjojicckapfpfdoakbehjpfkah) to preview a feed (other RSS viewers seem to handle the lazy-loaded images)
* Preview a site's feed (`site.com/feed`)
* Ensure that the featured images appear.

Lazy Images: do not lazy-load images in RSS feeds

---

projects/plugins/jetpack/changelog/fix-save-cpt-sharing
projects/plugins/jetpack/modules/sharedaddy/sharedaddy.php

I had added the field, but ended up not using because of saving issues (see c5611e64a3df43a73ef5878a9bb3758d9c80b232).
* N/A
* No
* Start with a site with Jetpack connected and the sharing module active.
* Create a new CPT like so:
```php
add_action(
'init',
function () {
register_post_type(
'example_cpt',
array(
'label'               => __( 'Post Type', 'jeherve-cpt' ),
'description'         => __( 'Post Type Description', 'jeherve-cpt' ),
'labels'              => array(
'name'          => _x( 'Post Types', 'Post Type General Name', 'jeherve-cpt' ),
'singular_name' => _x( 'Post Type', 'Post Type Singular Name', 'jeherve-cpt' ),
),
'supports'            => array( 'title' ),
'hierarchical'        => false,
'public'              => true,
'show_ui'             => true,
'show_in_menu' …
```

Sharing: remove nonce field that was added in #24412

---

projects/js-packages/components/changelog/update-protect-iterate-over-admin-page
projects/js-packages/components/components/dialog/index.tsx
projects/js-packages/components/components/dialog/stories/js-components.components.dialog.story.mdx
projects/plugins/protect/changelog/update-protect-iterate-over-admin-page
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/admin-page/styles.module.scss
projects/plugins/protect/src/js/components/alert-icon/index.jsx
projects/plugins/protect/src/js/components/alert-icon/styles.module.scss
projects/plugins/protect/src/js/components/footer/index.jsx
projects/plugins/protect/src/js/components/footer/styles.module.scss

This PR iterates over the Admin page to re-implement the layout composition.
Currently, there is a not very well usage of the Layout in the AdminPage and Footer components.
To deal with this, I've introduced a new SeventyFiveLayout component which takes over to render properly the main and secondary sections. This component tries to achive the layout defined by designers folks.
Fixes #
* JS Components: Add isCard property to Dialog component
* Protect: Re implement Error admin page by using Dialog component
* Protect: Tweak Alert icon
* Go to Protect
* Set up your testing site to see the error page
* Confirm the layout looks good
In the image below, there are two SeventyFiveLayout components.
Try to active the grid by using the dev tool. Both instances, the error message and the footer …

Protect: update Admin page layout composition

---

projects/js-packages/components/changelog/update-record-meter-bar-legend-format
projects/js-packages/components/components/record-meter-bar/index.tsx
projects/js-packages/components/components/record-meter-bar/stories/index.tsx
projects/js-packages/components/components/record-meter-bar/style.scss

This PR alters the RecordMeterBar component to take an optional legend formatting prop. When passed in as true, the legend displays with the count after the label instead of before. 
no
* Run `cd projects/js-packages/storybook && npm run storybook:dev` and confirm that you see RecordMeterBar component in Storybook.
* Under RecordMeterBar, choose the story 'Label Before Count'.
You can also run the unit tests for js-packages/components by running `jetpack test`.

RecordMeterBar Component: Adds a prop to display legend count after label

---

projects/js-packages/components/changelog/update-protect-update-admin-soon-section
projects/js-packages/components/components/dialog/index.tsx
projects/js-packages/components/components/dialog/stories/js-components.components.dialog.story.mdx
projects/plugins/protect/changelog/update-protect-update-admin-soon-section
projects/plugins/protect/src/js/components/admin-page/index.jsx
projects/plugins/protect/src/js/components/admin-page/styles.module.scss

Similarly to [this](https://github.com/Automattic/jetpack/pull/24434), this PR re-implements the "Your results will be ready soon" admin section layout.
Fixes #
*  Protect: Re implement "Your results will be ready soon" layout
* Set Protect to show the "Your results will be ready soon" page
* Confirm the sections looks well, same that layout that the Admin error page, and aligned with the footer.

 Protect: Re implement "Your results will be ready soon" layout

---

projects/plugins/protect/changelog/fix-protect-navigation-icon-spacing
projects/plugins/protect/src/js/components/navigation/label.jsx
projects/plugins/protect/src/js/components/navigation/styles.module.scss

* Adds 8px of padding between the navigation label and icon, to prevent them from getting too close when the label is very long.
* Adds a `<span>` with `overflow-x: hidden` and `text-overflow: ellipsis` inside the navigation label, to prevent long names from overflowing outside of the container. 
1202232924268038-as-1202326318206113
No.
* Boot up this PR and visit the Protect admin page.
* Either install a plugin with a long name, or use dev tools to insert your own in the navigation.
* Validate that the navigation label does not touch the icon, regardless of the character count.
* Validate that the navigation label does not overflow, regardless of the character count.
Before/After:
Before:
After:

Protect: Prevent Navigation Items From Touching Navigation Icons

---

projects/plugins/jetpack/_inc/client/at-a-glance/videopress.jsx
projects/plugins/jetpack/_inc/client/lib/plans/constants.js
projects/plugins/jetpack/_inc/client/performance/media.jsx
projects/plugins/jetpack/_inc/client/state/recommendations/reducer.js
projects/plugins/jetpack/_inc/client/state/site/reducer.js
projects/plugins/jetpack/changelog/refactor-use-wpcom-features-check

This purpose of this PR is to convert VideoPress plan checks into feature checks to help consolidate the source of truth on what plans have the VideoPress feature. (P2 primer: p58i-cef-p2) This is done by leveraging `hasActiveSiteFeature`.
This PR affects 3 places in the front end.
- Dashboard > At a Glance > Performance and Growth > VideoPress
- Settings > Performance > Media > VideoPress
- Dashboard > Recommendations (VideoPress is recommended after 2 weeks)
There should be no noticeable changes from production EXCEPT for one. Jetpack Complete (purchased after '2021-10-07') plans should now show the storage bar in At a Glance and in Performance. (Reference p1651177148184529-slack-CDLH4C1UZ)
- This PR leverages the new WPCOM_Features legacy feature support (D80783-code). The legacy …

Update Videopress plan checks to feature checks.

---

projects/plugins/social/changelog/fix-jetpack-social-admin-page-spacing
projects/plugins/social/src/js/components/admin-page/index.jsx
projects/plugins/social/src/js/components/admin-page/styles.module.scss
projects/plugins/social/src/js/components/info-section/styles.module.scss
projects/plugins/social/src/js/components/toggle-section/styles.module.scss

In https://github.com/Automattic/jetpack/pull/24479, some spacing variables were removed that we were using in the Jetpack Social admin page. This PR adds alternatives to fix the layout spacing.
* Replace missing variables with alternatives
* Add box-sizing to the container to prevent mobile overflow.
p1653636502671999-slack-C02JJ910CNL
No.
* Go to the admin page.
* Ensure all the elements have proper spacing.
* Resize it to tablet and mobile spacing, and ensure the layout doesn't overflow.
* Repeat these steps on the connections screen.

Social: Fix spacing on admin page

---

projects/js-packages/components/changelog/update-js-components-theme-provider-handling
projects/js-packages/components/components/theme-provider/Readme.md
projects/js-packages/components/components/theme-provider/index.jsx
projects/js-packages/components/components/theme-provider/stories/index.jsx
projects/js-packages/storybook/changelog/update-js-components-theme-provider-handling
projects/js-packages/storybook/storybook/preview.js

This PR fixes the visual issues produced by the ThemeProvider in the stories.
Although creating more than one instance per page of the ThemeProvider isn't encouraged, it's still doable. When it happens, the implementation malfunctions in how styles (style variables) are defined/injected by the provider. Basically, the component will create a new wrapper element per instance, with the same element ID attribute.
Even more, it will try to inject the styles querying the element by ID, which ends up setting the style only for the first match of the provider wrapper element.
Visually, it decorates only the first story. For instance, the Button story:
Using the inspector, when searching by `jetpack-theme-provider` five elements are found. However, the first element is the only that has the CSS …

Storybook: fix styles defined by the ThemeProvider

---

projects/plugins/protect/changelog/update-protect-scan-cta
projects/plugins/protect/src/js/components/footer/index.jsx

This PR updates the Call To Action wording for a user who already has the Jetpack Security Bundle. The wording changes:
**Old:** Increase your site protection with Jetpack Scan
**New:** Learn how Jetpack Scan increases your site protection
https://wp.me/p1HpG7-g36#comment-54548
No
* Set up test site with Protect plugin and Security Bundle
* Notice the CTA at the bottom left of the page "Increase your site protection with Jetpack Scan"
* Notice the CTA at the bottom left of the page now says "Learn how Jetpack Scan increases your site protection"

Protect: Update verbiage of CTA

---

projects/plugins/jetpack/changelog/update-IS-GA
projects/plugins/jetpack/modules/infinite-scroll.php

Fixes #24532
* Adds feature checks for Google Analytics to Infinite Scroll GA settings.
* Install an Infinite Scroll-compatible theme (Twenty Thirteen for example).
* Enable Infinite Scroll in Jetpack settings by searching for it.
* Go to Settings > Reading and see if the Google Analytics option is available.
* On the front-end, bring up the browser console and check `infiniteScroll.settings.google_analytics` to be false`.

Infinite Scroll: Show GA option when site has GA support

---

projects/plugins/jetpack/changelog/remove-google-comments-provider
projects/plugins/jetpack/modules/comments.php

- From internal D78705-code, looks like Google accounts have been removed for the time being as a sign-in option for comments. The Comments module description has been updated to reflect that.
- Updated corresponding support doc: https://jetpack.com/support/comments/
- Internal: p7H4VZ-3uJ-p2#comment-10420
- Closes #24522
No.
Proofread.

Comments: Google accounts no longer an identity provider

---

.github/CODEOWNERS

Add Jetpack Search team to CODEOWNERS for projects/plugins/search so we're automatically prompted for review when the plugin changes.
No.
Check that the changes follow the correct format for CODEOWNERS. Github automatically validates it and you can see the result of the validation here:
https://github.com/Automattic/jetpack/pull/24575/files

Add Jetpack Search team to CODEOWNERS for projects/plugins/search

---

projects/plugins/boost/app/features/optimizations/cloud-css/Cloud_CSS.php
projects/plugins/boost/app/features/optimizations/cloud-css/Cloud_CSS_Cron.php
projects/plugins/boost/app/lib/critical-css/Critical_CSS_Invalidator.php
projects/plugins/boost/app/lib/critical-css/Critical_CSS_State.php
projects/plugins/boost/changelog/add-cloud-css-cron

Fixes 83-gh-Automattic/boost-shield-api
**Note:** Designed to be used alongside 48-gh-Automattic/boost-cloud
* Added a cron job that periodically checks if the last cloud CSS failed.
* It will then resubmit the request for retry.
N/A
No
* Check if the cron is registered. A plugin that might help: [Advanced Cron Manager]
* Produce some errors during the generation of cloud-css, perhaps using the Boost Dev Companion plugin.
* Disable the error generation on the Dev companion plugin
* Let WP run the cron job or force it using [Advanced Cron Manager].
* See if CCSS retried.
[Advanced Cron Manager]: https://wordpress.org/plugins/advanced-cron-manager/

Boost: Add cloud css cron

---

projects/js-packages/components/changelog/update-record-meter-bar-component-add-sorting
projects/js-packages/components/components/record-meter-bar/index.tsx
projects/js-packages/components/components/record-meter-bar/stories/index.tsx

This PR alters the RecordMeterBar component to take an optional legend formatting prop. When passed in as true, the legend displays with the count after the label instead of before. 
no
* Run `cd projects/js-packages/storybook && npm run storybook:dev` and confirm that you see RecordMeterBar component in Storybook.
* Under RecordMeterBar, choose the story 'Default' and try changing 'sortByCount' under 'Controls'.
* Confirm that sort is updated in ascending or descending order.
You can also run the unit tests for js-packages/components by running `jetpack test`.

RecordMeterBar Component: Adds a prop to sort items by count value

---

projects/plugins/jetpack/changelog/fix-wpvideo-shortcode-useaveragecolor
projects/plugins/jetpack/modules/videopress/class.videopress-player.php
projects/plugins/jetpack/modules/videopress/shortcode.php

Fixes #24614
This PR changes "false" to false for wpvideo's useaveragecolor shortcode param, so the param could be properly casted to boolean.
It also adds strict checks in shortcode attributes to remove phpcs ignore.
No.
* On a Jetpack site with VideoPress enabled
* Go to your media library and upload a new video or find an existing one already uploaded to VideoPress
* Copy the video GUID
* Add a /shortcode block
* `[wpvideo <your_guid> useAverageColor=true]`
* Save and preview
* ✅ The seekbar should change color while playing the video
* Go back to the editor
* Change useAverageColor to "false" `[wpvideo <your_guid> useAverageColor=false]`
* Save and preview
* ✅ The seekbar should not change color while playing the video
* Use the same test procedure for 0 and 1 (0 …

Wpvideo shortcode: fix useAverageColor parameter handling for "false"

---

composer.json
composer.lock

It's annoying that composer puts the timestamp of the latest commit in
the lock file even though we're locked to a specific earlier commit.
Since a fork already exists at Automattic/WordPress-Coding-Standards,
let's point to that instead and tag the appropriate commit so this stops
happening.
None
No
* 🤷

Switch WPCS to a fork

---

projects/plugins/jetpack/changelog/fix-related-posts-fatals
projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php

This should fix fatals introduced in #22201.
```
Uncaught TypeError: Argument 1 passed to Jetpack_RelatedPosts::action_frontend_init_ajax() must be of the type array, null given, called in wp-content/mu-plugins/related-posts/jetpack-related-posts.php on line 227 and defined
```
- Syncs r246829-wpcom
- D82022-code
* p1654219480093619-slack-CDLH4C1UZ
* No
* Start with a site that has lots of posts and related posts active.
* When viewing a single post, add the following query string to the URL: `?relatedposts=1&relatedposts_exclude%5B0%5D=exp&relatedposts_exclude%5B1%5D=%3D1`
* The page should load with no issues, and display related posts data.

Related Posts: avoid using strings in array_values

---

projects/packages/waf/actions.php
projects/packages/waf/changelog/fix-waf-run-hook

* This changes the hook we're using for the WAF run.php file to plugins_loaded. This ensures we're not going to run before Jetpack is loaded which is needed to use the Modules class to verify if the package is enabled or not.
No.
* Checkout this branch on a test site with a scan subscription.
* Activate the WAF module.
* Verify that the rules are being executed.

WAF: Change the run.php hook to plugins_loaded

---

projects/plugins/boost/app/assets/src/js/pages/settings/sections/Modules.svelte
projects/plugins/boost/app/assets/src/js/pages/settings/sections/Tips.svelte
projects/plugins/boost/changelog/external links through redirect service
projects/plugins/boost/readme.txt

This PR updates the external links to run through the redirect system as per the FG `/jetpack-redirects/`. The `readme.txt` links have also been updated with hard coded links through the redirect system.
- Go to `/wp-admin/admin.php?page=jetpack-boost`
- Click the links in the modules (3 links) and in the tips sections (2 links)
- These will route via the Jetpack redirect system to the same destination as before
- The `readme.txt` links need to be checked by copying them into a browser (until the plugin is deployed) 
- I also tested that the changes didn't break the toggles or speed test
- I also checked that the click event was recorded on logstash 
Since the links are now going through the Jetpack redirect service we'll be able to see the number of times the link is clicked as well as …

[Boost] External links updated in plugin

---

tools/js-tools/git-hooks/pre-commit-hook.js

We had been running non-excluded files through both `phpcs`/`eslint` and
`phpcs-changed`/`eslint-changed`. If we do the former there's no need
for the latter.
For that matter, `eslint --fix` will report any remaining problems and
exit with a proper code, so there's no need to run a file through both
`eslint --fix` and `eslint`. Unfortunately `phpcbf` isn't so helpful, so
we still have to run through `phpcs` after that one.
None
No
PHP files:
* Make a change to a non-excluded PHP file. Commit. Output should indicate it was passed to phpcs, but phpcs-changed was not run.
* i.e. you should see `> phpcs -p -s '--runtime-set' 'ignore_warnings_on_exit' '1' '<file>'` in the output, but not `> phpcs-changed -s --git '<file>'`
* Make a change to an excluded PHP file. Commit. Output should indicate …

git: pre-commit hook shouldn't check files twice

---

projects/plugins/jetpack/changelog/fix-contact-form-checkboxes-24625
projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php

Fixes #24625
* This is a follow-up from #24450, which removed handling of arrays.
* N/A
* No
* Create a new Form block
* Inside that form, add a multiple checkbox field, with multiple possible entries.
* Publish your post.
* Submit a form after clicking on multiple choices in the multiple checkbox field.
* The data should appear in the confirmation page, and in wp-admin.

Form: support saving array of data, such as multiple checkboxes

---

projects/plugins/jetpack/changelog/fix-customcss-menu-woa
projects/plugins/jetpack/class.jetpack-admin.php

Fixes the issue [mentioned here](https://github.com/Automattic/jetpack/pull/23670#issuecomment-1145133771).
* More specifically, this PR introduces a check to see if a site is WoA - if it is and doesn't have the Custom CSS feature available, the Additional CSS menu item isn't added (not via Jetpack anyway - [this is handled independently](https://github.com/Automattic/jetpack/pull/19965)). 
* This fixes a regression introduced in [this PR](https://github.com/Automattic/jetpack/pull/23670), affecting WoA sites without a plan, where duplicate Additional CSS menu items appeared.
See link above.
No.
* To test, Create a WoA ephemeral site (internal testing only).
* First test by removing the plan that enabled the site to be WoA - you should notice duplicate Additional CSS menu items under …

Custom CSS: Adding a check for WoA sites to prevent duplicate menu items

---

tools/cli/commands/generate.js
tools/cli/skeletons/js-packages/.nycrc
tools/cli/skeletons/js-packages/src/index.js
tools/cli/skeletons/js-packages/test-main.jsx
tools/cli/skeletons/js-packages/tests/.eslintrc.cjs
tools/cli/skeletons/js-packages/tests/index.test.js

Following Calypso's lead, let's start standardizing on `jest` and
`@testing-library` for JS testing. And a good way to start that is to
update the `jetpack generate` CLI command to stop including
`js-test-runner` in the generated skeleton.
p4TIVU-a8r-p2#comment-11500
No
* Try generating a js-package and see that it looks right.

cli: Remove js-test-runner from js-package skeleton

---

projects/plugins/jetpack/changelog/fix-videopress-copy-button-chrome
projects/plugins/jetpack/modules/videopress/class.videopress-player.php

Related  to Automattic/greenhouse#1199
Copy button in the share modal is not working in Chrome because of an allow policy.
This PR adds allow="clipboard-write" to the generated iframe in order to fix that.
No.
* On a Jetpack site with VideoPress enabled
* Apply this patch
* Use Google Chrome
* Go to your media library and get the GUID of a VideoPress video (or upload a new one)
* Add a /shortcode block
* `[wpvideo <your_guid>]`
* Save and preview
* ✅ The generated iframe should contain 'allow="clipboard-write"' as attribute
* ✅ The copy buttons in the share menu should work on Chrome

Add allow="clipboard-write" in VideoPress iframe embed to fix clipboard API in Chrome

---

projects/packages/blocks/changelog/fix-related-posts-fse
projects/packages/blocks/src/class-blocks.php
projects/packages/blocks/tests/php/test-blocks.php

Fixes #24619
* We previously only relied on a function provided in Gutenberg, `gutenberg_is_fse_theme()`, to check whether a theme was a block-based theme. Now that the feature made its way to core, there is a Core function we can (and should) use instead: `wp_is_block_theme()`.
**Note**
I had originally added a new test, but I could not get it to work. I kept receiving this error:
```
1) Automattic\Jetpack\Test_Blocks::test_is_fse_theme_via_core_function
Patchwork\Exceptions\DefinedTooEarly: The file that defines wp_is_block_theme() was included earlier than Patchwork. This is likely a result of an improper setup; see readme for details.
```
* N/A
* No
* Start with a site with some existing content.
* Go to Jetpack > Settings > Traffic and enable Related Posts.
* Go to Appearance > …

Related posts: use latest core function to check block-based theme

---

.github/files/gh-autotagger/workflows/autotagger.yml

* In preparation for renaming 'master' to 'trunk' in the Jetpack monorepo and mirror repos, this PR adds a trunk branch to the branches on which the `autotagger.yml` file will check for pushes to. Once merged, this will change the `.github/workflows/autotagger.yml` files in each of the mirror repositories to match.
* This should allow for a seamless change when the 'master' branch is renamed.
p9dueE-59T-p2 
No.
* No actual testing for this one before merging, other than checking that the 'trunk' addition is added to the `autotagger.yml` file correctly.
* After merging and after the action to push to mirror repos has run, check in the mirror repos to make sure the `autotagger.yml` file has been updated (for example in [jetpack-changelogger](https://github.com/Automattic/jetpack-changelogger …

GitHub Actions: Updating autotagger.yml to act on a push to trunk as well as master

---

projects/plugins/jetpack/_inc/client/security/style.scss
projects/plugins/jetpack/_inc/client/security/waf.jsx
projects/plugins/jetpack/changelog/add-support-links
projects/plugins/jetpack/modules/module-info.php

This PR adds links to the [Jetpack Firewall support page](https://jetpack.com/support/jetpack-firewall/) to the WAF settings group. 
* Adds the following support information to the settings group, with a link to the support page: "The Jetpack Firewall is a web application firewall designed to protect your WordPress site from malicious requests.
* Links the "Beta" badge to the support page.
1201069996155217-as-1202326318206132/f
No.
* Go to `/wp-admin/admin.php?page=jetpack#/settings`
* Validate the Firewall's beta badge links to the support page.
* Validate the Firewall's settings group displays the additional information, and links to the support page.
Existing additional info pattern used by backup:
PR adds the same pattern to firewall:

WAF: Add support links and more information

---

projects/plugins/jetpack/_inc/client/security/style.scss
projects/plugins/jetpack/_inc/client/security/waf.jsx
projects/plugins/jetpack/changelog/update-waf-upgrade-messaging

This PR updates the description shown to users who do not have an active plan that provides access to the latest Firewall rules, in an attempt to better inform users about their access to firewall rules and the value of upgrading their Jetpack plan to include access to said rules.
* Updates wording of notice to users without a plan that includes access to latest firewall rules.
* Adds an `<InfoNotice />` with additional information firewall rules.
pbuNQi-33j-p2
1201069996155217-as-1202326318206132/f
No.
* Go to `/wp-admin/admin.php?page=jetpack#/settings` on a free Jetpack site
* Validate that the rules notice is displayed per the screenshot below:

WAF: Update messaging for sites without latest rules access

---

pnpm-lock.yaml
projects/plugins/jetpack/changelog/update-jetpack-remaining-tests-to-jest
projects/plugins/jetpack/modules/.eslintrc.js
projects/plugins/jetpack/modules/videopress/js/test/test-gutenberg-video-upload.js
projects/plugins/jetpack/package.json
projects/plugins/jetpack/tests/jest.config.client.js
projects/plugins/jetpack/tools/webpack.config.js

After previous PRs, two package.json scripts were left using
js-test-runner. Neither was being run in CI; one had only one test, and
one had none at all.
Both of these are now merged into the "client" tests. Note that module
tests are now expected to be named with the usual `**/test/*.[jt]s?(x)`
pattern, rather than the strange `**/test-*.js` it had been using
before. The one existing test already matched both patterns.
And, as usual, linting is set up for the tests that didn't already have
it.
Jetpack no longer uses js-test-runner, mocha, sinon, or chai. We still
need to remove use of enzyme in favor of testing-library, but I'll leave
that for a later PR.
Working towards p4TIVU-a8r-p2#comment-11500
No
* Is CI happy?

jetpack: Use jest for remaining tests

---

projects/packages/backup/changelog/remove-backup-connection-title-dup
projects/packages/backup/src/js/hooks/useConnection.js

Removes a double headline from the connection screen.
> The two headlines with the same font size make it look like a weird sentence. Can you remove the first line? - @robertbpugh 
No.
* Add this build to an existing or new site and disconnect (or never connect) Jetpack to see the connection screen
* You can start up a Jurassic Ninja site with Jetpack Beta and pick this feature branch as the Jetpack Backup version
* Ensure the screen looks like the screenshot and doesn't have the 'The best real-time WordPress backups' line

[Package] Backup - Removed double headline from connection screen

---

projects/packages/changelogger/changelog/add-changelogger-more-non-feature-branch-names
projects/packages/changelogger/src/AddCommand.php
projects/packages/changelogger/src/Application.php

We were already recognizing 'main', 'master', and 'trunk'. Let's take
some more from those Composer itself recognizes: 'current', 'default',
'develop', 'latest', 'next', 'support', and 'tip'.
And let's throw 'production' in there too, I've seen that one somewhere.
None
No
* Try creating a branch with any of these names, then do `changelogger add`. It should suggest a date-based filename instead of using the branch name.
* Any other names people have been using?

changelogger: Recognize more non-feature-branch names

---

projects/packages/connection/changelog/update-old_cookie_regex
projects/packages/connection/legacy/class-jetpack-tracks-client.php

Fixes #
Updates the regex used to see if a `tk_ai` cookie is valid. This should now match any id's that follow `<lower case product name>:<24 characted base 64 id>` (ex: `jetpack:I8XJISGzESHE1TIORR+g+A8c` or `woo:U9Lx7TjnsFTvC2bdzkgznFau`
Slack discussion here: p1654803569461579-slack-CBG1CP4EN
No
* Start a fresh Wordpress site without activating Jetpack and install and activate WooCommerce
* Notice how a `tk_ai` cookie is generated for Woo ( under Devtools > Application > Cookies > your domain )
* Activate Jetpack (with this build) and navigate to a couple different pages within Wordpress
* The `tk_ai` cookie should remain as the `woo:....` cookie and not be overwritten by a `jetpack:...` cookie.

Fix regex for matching existing `tk_ai` cookies

---

tools/docker/Dockerfile

The main change here is switching the pnpm install to `npm install -g`,
as `corepack` is apparently per user rather than global. Sigh.
Then I took the opportunity to clean up a few other things:
* Remove `software-properties-common` after using it, which gets rid of
89 other unneeded packages (80M).
* Remove a random cache dir, `~/.launchpadlib` (2.2M).
* Avoid installing PHP 7.4 (through a recommendation on php-apcu-bc) and
some other recommendations to save another 33 packages (89M, but some
were shared with the first bullet).
* And another random cache dir, `~/.composer` (1.9M).
In total it brings the size from 704M down to 580M.
None, but it should fix Renovate on #24702, #24703, and #24704.
No
* The main thing is to load the new image with `docker run --rm -it --user 1000` and see …

docker: Clean up Dockerfile

---

composer.lock
projects/packages/codesniffer/changelog/fix-codesniffer-composer-dev-deps
projects/packages/codesniffer/composer.json

For a while now we've been depending on a particular commit of WPCS that
works with PHP 8. We had been doing that as `dev-develop#<sha>`, which
Composer only halfway supports.
Now that WPCS has updated their dev-develop to depend on phpcs 3.7,
Composer is getting confused because it's still trying to apply the
composer.json metadata from the tip of dev-develop rather than the sha
we're pointing to.
Since we already have a fork from #24627, let's go ahead and use that
here too to avoid the problem. Hopefully someday WPCS will finally do a
release...
p1655129609166099-slack-C034JEXD1RD
no
* Is CI happy again?

codesniffer: Fix dev dep on WPCS

---

projects/plugins/jetpack/changelog/fix-jetpack-watch
projects/plugins/jetpack/package.json
projects/plugins/social/changelog/fix-jetpack-watch
projects/plugins/social/package.json

When #24508 added `NODE_PATH` to various invocations of webpack to fix
builds, it forgot to do the same to the watch commands.
These two plugins seem to be the only ones that don't call through to
their build command with `--watch` added.
Fixes #24714
no
* Try `jetpack watch` on various projects, particularly plugins/jetpack and plugins/social.

jetpack, social: Fix `jetpack watch` command

---

projects/plugins/jetpack/changelog/fix-sync-delays-test
projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-sender.php

Fix the inconsistent unit test `WP_Test_Jetpack_Sync_Sender::test_delays_next_send_if_exceeded_sync_wait_threshold()` by allowing more variation in the Sync timing.
1202427859356518-as-1202032023127869
No.
- make sure the PR tests pass
- re-run the PHP unit tests a few times to confirm the fix helped

Sync: adjust the time variation for the delays test
