modules/likes.php
Partial fix for #4257.
* Removing the 4.5 conditional block.
* Enable Likes
* Verify that Likes render on posts and not in a preview.
=> Removing the 4.5 conditional block.

modules/stats.php
Cleanup modules/stats.php using WordPress php Coding Standards. (Replay of #5398)
=> Stats: Coding Standards updates

modules/stats.php
Fixes the sloppy docblocks that were just merged in #6364
=> Fix @return values in docblocks

modules/shortcodes/twitchtv.php
Fixes #6100
* Updates Twitch.tv embed shortcode to use Twitch's updated embed URLs properly.
* Imported from shortcode updates made to WordPress.com
* Embed a twitchtv shortcode in a new post, and test to make sure it can play the live stream properly. eg: `[twitchtv url="http://www.twitch.tv/leveluplive" width="400" height="244" autoplay="false" muted="true"]`
* Updated Twitch.tv shortcode to use Twitch's updated embedded player.
=> Update TwitchTV shortcode handling, based on wpcom codebase

class.jetpack-jitm.php
Fixes #
* Update copy of WooCommerce Services JITMs
=> Update WCS JITM copy to indicate that services are free.

modules/contact-form/admin.php, modules/contact-form/grunion-contact-form.php
Replaces #5993 with an additional commit addressing @jeherve's [comment](https://github.com/Automattic/jetpack/pull/5993#pullrequestreview-20101264) there.
=> Grunion: remove double slashes from file paths

_inc/client/writing/composing.jsx
Fixes #6213
Follow up of https://github.com/Automattic/jetpack/pull/6358
* Adds Proofreading legend to match Calypso (and looks better)
* Go to Settings > Writing > Composing > Advanced options
=> Add proofreading legend

_inc/client/writing/custom-content-types.jsx
Follow up of #6356
* go to Settings > Writing
Related issue: https://github.com/Automattic/jetpack/issues/6210#issuecomment-275782686
=> Remove unnecessary description for Custom Content Types

_inc/client/traffic/ads.jsx, _inc/client/traffic/index.jsx
Updating settings per: https://github.com/Automattic/jetpack/issues/6224
=> Ads: Update Settings Card to new UI

modules/module-headings.php
Fixes #6265
Updates module-headings for the feature branch so it's not always showing a diff on build.
=> Build module headings for feature/settings-overhaul branch.

_inc/client/components/masthead/index.jsx, _inc/client/main.jsx, yarn.lock
Fixes #4821
Replaces the help/feedback links with dash/settings buttons. 
To Test: 
- When admin page is loading, make sure that the header doesn't have any button selected 
- When page is done loading, make sure the correct button is highlighted corresponding to the path. 
- Click around and make sure button primary changes/reacts correctly
=> Masthead: new nav buttons/links

functions.photon.php
This is a continuation of #4724 with fixed whitespace.
Props to @bhubbard
=> Fix Whitespace in #4724

modules/contact-form/js/grunion.js
=> Contact Form: correct a typo

_inc/client/state/settings/actions.js
Fixes #6286 
* removes the "Updating settings..." notices
* test toggles and saving settings using the save settings button
=> Settings UI: don't show progress notices.

modules/protect.php
Fixes #4216
* Added href to the support link.
* Lock yourself out of your site and you'll see the support page link goes to the correct section.
=> Changing the support page URL

_inc/client/components/module-settings/index.jsx, _inc/jetpack-strings.php
* Fix typos
* Look at word, check it's not a typo
* Fixed some typos
=> Fix `notificaton` typo

_inc/client/components/dash-item/style.scss
=> DashItem: fix disabled overflow text shadow

_inc/client/security/protect.jsx
=> Settings: change brute force label from Current to lowercase current

modules/widget-visibility/widget-conditions.php, modules/widget-visibility/widget-conditions/widget-conditions.css, modules/widget-visibility/widget-conditions/widget-conditions.js
This fixes issue #852. (Replay of #3289 by @atrus1701 )
Add the option to match all conditions specified for the widget.
This is related to Pull Request #3210. This original Pull Request contained several fixes that are being broken out into several smaller requests.
=> Widget Visibility: add ability to match ALL conditions.

json-endpoints/jetpack/class.jetpack-json-api-themes-endpoint.php, readme.txt, to-test.md
Changelog and Testing list for the upcoming Jetpack release.
- Makes a few changes to new filter docblocks to match standards and help parser.
- Update of the stable version in the readme.
- Update the contributor lists.
- Update the link to create a new support thread in the GitHub issue template.
- Copy 4.6 to the changelog.txt file.
- Remove old release from the changelog in readme.txt to keep it short.
- Fix typo in readme.txt
=> Jetpack 4.7: Changelog

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes #6539
* Add new method that filters unused parameters.
* Replace the old validation method with the new one.
* Open Jetpack and activate Custom Content Types module
* Enable Portfolio Projects
* Make sure that post type has been registered.
cc @roccotripaldi @tyxla
=> REST API: Fix module settings updating

readme.txt
=> Refine the 4.7 release changelog

modules/widget-visibility/widget-conditions/rtl/widget-conditions-rtl.css
Fixes #6602 
* Adds missing RTL changes to Widget Visibility.
=> Added RTL changes to Widget Visibility.

changelog.txt, readme.txt
Changelog for the upcoming point release.
=> Jetpack 4.7.1: Changelog.

.travis.yml
Fix travis failure caused by change to PHPUnit 6
=> Fix Travis fails

_inc/client/writing/media.jsx
=> Photon: updated tiled galleries descriptive text

class.jetpack.php
Got rid of one of the hooks and added a check to only upgrade on full load.
The problem is that Jetpack gets activated late in the page load when updating. This results in no modules loaded - just the core, which handles `plugin_upgrade`. Up to this point we didn't really need modules and so everything went smoothly.
This time with Widget Visibility migration we need modules to be loaded to have the migration method, plus we need modules to register all widgets and be able to get their instances.
So the proposed solution is be to check if Jetpack has been fully loaded and only run update routines only if it has been.
We are doing it by checking if `wp_loaded` has fired, and `jetpack_modules_loaded` has not fired. This means that `jetpack_modules_loaded` wouldn't be fired at all at this …
=> Fixed the Widget Visibility migration script to run on plugin updates.

_inc/client/traffic/site-stats.jsx
I think this fits a little better. CC @rickybanister and @ashleighaxios for any design/copy thoughts.
=> Adds SettingsCard for stats settings

_inc/client/components/settings-card/index.jsx, _inc/client/components/support-card/index.jsx, _inc/client/security/antispam.jsx
I update little bits of text. Nothing drastic. Let's discuss and see if we can't refine the strings available while @zinigor adds the missing banners. Either update our shared doc and ping me or comment/commit to this PR. Thanks!
We're missing:
CC @richardmuscat @ashleighaxios @rickybanister @zinigor
=> Revise upgrade banner text

_inc/client/at-a-glance/style.scss, _inc/client/components/connect-button/index.jsx, _inc/client/components/jetpack-disconnect-dialog/index.jsx, _inc/client/scss/variables/_colors.scss
Fixes #6184
* make disconnection dialog great
* try to disconnect 
For the chat icon to show, this PR must be linked
https://github.com/Automattic/dops-components/pull/104
=> Settings UI: update site disconnect dialog

_inc/client/components/settings-card/index.jsx
=> Remove video upgrade card going from premium to business

_inc/client/README.md, _inc/client/components/support-card/index.jsx, _inc/client/components/support-card/style.scss, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php
* remove avatars from support block
=> Settings UI: delete support block avatars

modules/theme-tools/content-options/customizer.js, modules/theme-tools/content-options/post-details.php
Inspired by
https://snook.ca/archives/html_and_css/hiding-content-for-accessibility
=> Content Options: Improve post details clipping

_inc/client/at-a-glance/scan.jsx, _inc/client/components/dev-card/index.jsx, _inc/client/plans/plan-body.jsx, _inc/client/plans/plan-header.jsx, class.jetpack.php
There are some additional plan slugs that we need to add. Additionally, need to add these to any functions to automatically activate/deactivate modules.
=> Adds additional plan slugs to active plan function

changelog.txt, modules/sitemaps/sitemap-buffer.php, modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-constants.php, modules/sitemaps/sitemap-finder.php, modules/sitemaps/sitemap-librarian.php, modules/sitemaps/sitemap-logger.php, modules/sitemaps/sitemap-state.php, modules/sitemaps/sitemap-stylist.php, modules/sitemaps/sitemaps.php, readme.md, readme.txt, sync/class.jetpack-sync-module-users.php, to-test.md
=> Jetpack 4.8: changelog.

_inc/lib/admin-pages/class.jetpack-react-page.php, tools/export-translations.php
This is a replay of #6805 that was based on a branch other than `master` and got lost in the merging process, so merging this one instead.
=> Use the whole locale slug instead of just a prefix. (#6805)

jetpack.php, package.json
Among other things this will help `master` to stay ahead of `branch-4.8` version-wise.
=> Bumped version to 4.9-alpha.

_inc/client/components/settings-card/style.scss
=> Fixes spacing of foldable card to match other settings cards for now

modules/minileven.php, modules/module-headings.php
Minileven is only loaded on phones, not on tablets.
=> Mobile Theme: update description to remove mention of tablets.

modules/sitemaps/sitemap-constants.php
Follow up to https://github.com/Automattic/jetpack/pull/6852#issuecomment-290848283
=> Sitemaps: lower the sitemap size limit

_inc/client/main.jsx, _inc/client/traffic/related-posts.jsx
Fixes #6935
- add translation comment
- remove word that wasn't supposed to be there
- Fix minor ESLint warnings.
=> Settings UI: add translation comment.

to-test.md
The current testing list isn't relevant anymore. I think it'd be nice to remove it, and then push a new `master-stable` once that's done.
=> Testing List: remove old testing list elements.

sync/class.jetpack-sync-module-plugins.php, tests/php/sync/test_class.jetpack-sync-plugins.php
Jetpack Sync: Add sync event for plugin installation
* Addition of 'jetpack_installed_plugin' action
* phpunit
Added 'jetpack_installed_plugin' action
=> Jetpack Sync: Add sync event for plugin installation

json-endpoints/class.wpcom-json-api-list-roles-endpoint.php
This syncs changes added by @yoavf
=> REST API: List Roles - localize role names

json-endpoints/class.wpcom-json-api-get-post-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Brings code between dotcom and Jetpack in sync for several endpoints.
=> Sync get post endpoints.

json-endpoints/class.wpcom-json-api-update-taxonomy-endpoint.php
@codebykat please take a look at your change here and see if it's OK to get in.
=> Synchronizes the taxonomy endpoint.

yarn.lock
This updates `yarn.lock` with the most current versions of dependencies.
=> Refreshed dependencies by running yarn upgrade.

modules/protect/shared-functions.php
=> Fix port detection so it doesn't break ipv6

_inc/lib/admin-pages/class.jetpack-react-page.php
Fixes #6645
* Stats: avoid PHP warnings and errors in the Stats dashboard on Multisite.
=> Stats: Make sure get_editable_roles exists before to use it.

class.jetpack-jitm.php, phpunit.xml.dist, tests/php/test_class.jetpack-jitm.php, yarn.lock
* Adds unit tests for the Just In Time Message class
* Unit tests should pass
Increase code coverage of unit tests
=> JITM: Add unit tests for JITM class

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Jetpack Sync: Adding sync event for theme update
Jetpack Sync: Adding sync event for theme update
phpunit runs additional test for functionality
=> Jetpack Sync: Adding sync event for theme update

locales.php
Upstream updates. Removes an invisible char on Czech native name, and add a few new locales.
=> Locales: updates from GP

_inc/client/main.jsx
=> Make sure to only load when site is connected

json-endpoints/class.wpcom-json-api-site-user-endpoint.php
@ebinnion this should work fine for Jetpack, but could you take a glance anyway please?
=> Synchronies the site user endpoint.

modules/after-the-deadline/config-unignore.php, modules/after-the-deadline/proxy.php
Merge some changes from WPCOM-side down to Jetpack.
=> WPCOM Sync: After the Deadline.

json-endpoints.php
Brings the `json-endpoints.php` file in sync with WordPress.com code.
=> Sync the JSON endpoints definition file.

_inc/client/components/jetpack-notices/index.jsx
=> Fix "Not Connected" language

jetpack.php, package.json, readme.txt
=> Bump ver to 5.0-alpha

json-endpoints/jetpack/class.jetpack-json-api-user-create-endpoint.php, json-endpoints/jetpack/json-api-jetpack-endpoints.php
Adds an endpoint that lets us create users. 
* Adds a new endpoint to allows us to create users. 
* Apply the .com patch ...
* Test the api endpoint to make sure that it works as expected.
=> API: Add create user endpoint

sync/class.jetpack-sync-actions.php, sync/class.jetpack-sync-sender.php, tests/php/sync/test_class.jetpack-sync-sender.php
Improve debugging output for AT
=> Jetpack Sync: Sender: Return errors instead of plain `false`

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Jetpack Sync: Add sync action for theme edit
Adds a sync action for theme edit
phpunit runs a new test that tests the functionality
=> Jetpack Sync: Add sync action for theme edit

json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
=> Just fixing a typo in the documentation

json-endpoints/class.wpcom-json-api-list-users-endpoint.php, json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
@dbtlr this PR syncs the media upload endpoint, please take a look at the changes. I'm mostly wondering if it's OK to sync stuff that works with the upload token auth.
=> Synchronize media and settings endpoints.

class.json-api-endpoints.php, class.json-api.php
This syncs changes from dotcom changes to the base API endpoint classes.
=> Syncs JSON API base classes.

_inc/client/at-a-glance/style.scss
=> Removes bottom alignment of content on dashitems

.travis.yml
Closes #7064
Quicker for me to create a fresh PR ;)
=> Remove duplicate `nvm install`

docs/development-environment.md
=> Docs: update yarn version

class.json-api-endpoints.php
=> Make sure that videoPress media items return their videopress_guid

json-endpoints.php
This commit syncs r156796-wpcom.
Fixes #
*
*
=> API: initialize "list posts" endpoint v1.2

sync/class.jetpack-sync-sender.php
=> Remove extra semicolon

sync/class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-listener.php
Adds the user roles to the actor object that gets sent by every sync. 
* Adds the user role to each sync request.
=> Sync: get_actor sents the user role

bin/partner-cancel.sh, bin/partner-provision.sh
Small cleanups based on http://www.shellcheck.net/
=> Clean up partner scripts based on shellcheck.net results

jetpack.php, package.json, readme.txt
WP 4.8 comes out this week. Likely we probably should have bumped this already since 5.0 includes compat stuff for 4.8, but alas. Let's bump everything!
=> Bumps tested to version and dev verisions

sync/class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-listener.php
Adds additional sync actor information to mirror that on .com for activity log
Additional fields for sync actor array
phpunit
=> Jetpack Sync: Add additional sync actor information to mirror that on .com for activity log

modules/theme-tools/content-options.php, modules/theme-tools/content-options/blog-display.php, modules/theme-tools/content-options/customizer.js, modules/theme-tools/content-options/customizer.php, modules/theme-tools/content-options/featured-images-fallback.php, modules/theme-tools/content-options/featured-images.php, modules/theme-tools/content-options/post-details.php
To keep it inline with WordPress.com
* New Featured Images fallback option
* New Hide Comment link option
* Fix WooCommerce Product featured image
=> Content Options: Multiple changes

class.jetpack-client-server.php, class.jetpack.php
Fixes #3546
* After talking with @roccotripaldi and @kraftbj (100% @kraftbj's idea btw, I just executed) ... we don't need to set state on xmlrpc requests. So, let's not do that. Now we're not trying to send a bajillion length headers back :D
* nginx default config will no longer respond with 502 during authorization
- Fix elusive nginx 502 error...
=> Fix the elusive nginx 502 error

_inc/client/components/jetpack-connect/index.jsx
=> Jumpstart: remove ellipsis from CTA link.

modules/likes/queuehandler.js
Refactor queue handler postMessage processing to use switch statement instead of multiple ifs.
Resolves: https://github.com/Automattic/jetpack/issues/7403
* Verify that post and comment likes still work as expected.
=> Comment likes: refactor queue handler code

modules/minileven.php, modules/module-headings.php
=> Mobile Theme: Update verbiage for feature

modules/masterbar/masterbar.php
* updates version after style changes on dotcom side
=> Masterbar: update cache buster string

class.jetpack-cli.php
After running `wp jetpack sync start` in my sandbox, I noticed that the command hits an infinite loop.
After debugging, it appears that it was because we changed some logic around syncing, specifically, we return `WP_Error` objects instead of `false` for sync now as of #7135.
This PR updates the `wp jetpack sync start` command to work with `WP_Error` and also improves the error handling a bit by displaying the error code and erroring out the command.
To test:
- In current master, run `wp jetpack sync start` and verify infinite loop
- Checkout this PR
- Run same command
- Ensure no infinite loop
=> CLI: Fix infinite loop in wp jetpack sync start command

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Adds widget details to Activity Log
* Widget name sent on add and remove, suppress edit activity when added
* phpunit
=> Jetpack Sync: Add widget details to Activity Log

class.jetpack-jitm.php
Records a jitm impression
* View a jitm, see the event in tracks.
NA
=> Add tracks for impressions of jitms

_inc/client/components/upgrade-notice-content/index.jsx
We need to add a space here so it renders right. 
needs to be cherry-picked to the 5.2 branch.
=> Admin: Correct typo

class.jetpack.php
* verify that `host` and `path` indexes exist and are not empty
=> Make sure host and path exist before using them

sync/class.jetpack-sync-module-themes.php
Add additional sync args for theme actions for Activity Log
Add additional sync args for theme actions for Activity Log
*phpunit
=> Jetpack Sync: Add additional sync args for theme actions for Activity Log

modules/contact-form/grunion-editor-view.php, modules/contact-form/js/editor-view.js
=> Add in field template for url type.

_inc/client/components/jetpack-notices/state-notices.jsx
Since the point release is going out so soon after initial release, let's give people who haven't yet upgraded a chance to see it.
=> Show welcome notice for Contact Forms in 5.2.1

.travis.yml, jetpack.php, package.json, readme.txt, yarn.lock
This PR also adds now separate package json-loader https://github.com/webpack-contrib/json-loader
=> Update versions and yarn lock file

modules/contact-form/grunion-contact-form.php
=> Fix “successfull” typo

class.jetpack.php, modules/likes.php, modules/likes/style.css
=> Likes: Remove Open Sans

_inc/client/components/jetpack-notices/index.jsx, _inc/client/components/jetpack-notices/style.scss, yarn.lock
Fixes #6293, replacing the simple notice with a Banner style as per @MichaelArestad's suggestion in the issue.  
To test: 
- View the Jetpack admin as an unlinked user and observe the banner.  
- Make sure linking the user account still works.
=> Update the "Unlinked User" notice to a banner, and improve verbiage

class.jetpack-cli.php
Uses blog auth and the `/test-connection` endpoint to verify that the site can talk to WP.com and also WP.com can talk to the site.
Run `wp jetpack test-connection` on sites with the following states:
* No local connection (should show "error" message: `Error: Jetpack is not currently connected to WordPress.com`)
* Valid local connection + WP.com connection (should show "success" message: `Success: {Site Name} is connected.`)
* Local connection + no WP.com connection OR invalid local connection + WP.com connection (should show "error" message that the request could not be validated.)
=> CLI: Add command to test Jetpack connection

sync/class.jetpack-sync-actions.php, sync/class.jetpack-sync-module-callables.php, sync/class.jetpack-sync-module-constants.php, tests/php/sync/test_class.jetpack-sync-full.php, tests/php/sync/test_class.jetpack-sync-integration.php
=> Alternative to #7709

jetpack.php, readme.txt
=> Update description texts.

sync/class.jetpack-sync-actions.php
Fixes #
Possible errors
ask @enejb
=> Sync: Check that full_sync module is available

docs/development-environment.md
Fixes a small omission in the testing instructions.
=> Add test-gui step to testing instructions

modules/search/class.jetpack-search.php
Adds ability to make authenticated API requests from the JP site (via filtering jetpack_search_es_query_args) to support querying 'private' data (unpublished content for example)
* Add a filter on `jetpack_search_es_query_args` to set `authenticated_request` => `true`:
```
add-filter( 'jetpack_search_es_query_args', function( $args ) {
$args['authenticated_request'] = true;
return $args;
});
```
With the Search module active, perform some regular searches - requests should then go through `Jetpack_Client::wpcom_json_api_request_as_blog` class instead of `wp_remote_post()` and work normally.
=> Search: Add ability to make authenticated API requests

gulpfile.js, modules/shortcodes/css/gutenpack.css, modules/shortcodes/js/blocks/blocks.js, modules/shortcodes/js/blocks/index.js, modules/shortcodes/js/blocks/vr-block.js, modules/shortcodes/js/blocks/vr-block.jsx, modules/shortcodes/vr.php
Add a block for the VR shortcode
=> Add gutenblock for VR shortcode

modules/shortcodes/css/gutenpack.css, modules/shortcodes/js/blocks/blocks.js, modules/shortcodes/js/blocks/giphy-block.js, modules/shortcodes/js/blocks/giphy-block.jsx
=> Gutenblock: Giphy

modules/shortcodes/css/recipes.css, modules/shortcodes/js/blocks/blocks.js, modules/shortcodes/js/blocks/recipe-block.jsx, modules/shortcodes/recipe.php
=> Jetpack Recipe as Gutenberg Block

.github/CODEOWNERS
* Docs: add myself as code maintainer for the docs.
=> Docs: add myself as code maintainer for the docs.

class.jetpack-network.php, class.jetpack.php
Fixes a crash that could occur when building the connect URL.
=> Fix crash on registration

class.jetpack-options.php, class.jetpack-user-agent.php
=> improve condition

json-endpoints/class.wpcom-json-api-update-term-endpoint.php
This change synchronizes r137908-wpcom, r147008-wpcom.
=> Synchronized changes in term update endpoints.

modules/theme-tools/content-options/blog-display.php, modules/theme-tools/content-options/featured-images.php, modules/theme-tools/content-options/post-details.php
* Fix “Continue reading” translation issue with non-latin characters
* Make sure a PayPal product Featured Image cannot be hidden via the
options
* Clearer ifs statements
=> Content Options: Keep Content Options up to date with wpcom

_inc/client/traffic/index.jsx
Partially reverts #7829 for now.
cc @beaulebens
=> Lightweight disabling of search module UI

jetpack.php, readme.txt
Reverts #7715 in an attempt to help our plugin SEO
discussed in p1HpG7-4aQ-p2
=> revert plugin description changes

_inc/client/components/welcome-new-plan/index.jsx, _inc/client/components/welcome-new-plan/personal.jsx, _inc/client/components/welcome-new-plan/premium.jsx, _inc/client/components/welcome-new-plan/professional.jsx
Adds tracks events for the warm welcome merged in #7837
=> Warm Welcome (plans): add tracking 

class.jetpack.php
Fixes #7792
In the above issue, it was reported that we were hitting the database multiple times per page load. After looking at the reporter's logs, it was apparent that the issue was happening during the IDC validation logic, which is how we determine whether to put a site into staging mode if the site is in IDC.
To address this, I suggest two things:
- In `Jetpack:: validate_sync_error_idc_option()` we only call `Jetpack::get_sync_error_idc_option()` if there is a sync error. If there's not a sync error, then there's nothing to validate.
- In `Jetpack::get_sync_error_idc_option()` add a 1 minute transient. Transients will allow us to add a small caching layer around this IDC logic and minimize hitting the DB multiple times per page request.
To test:
- Add some debug to …
=> IDC: Minimize database hits in validation logic

jetpack.php, package.json, yarn.lock
Minor housekeeping: bumped version to 5.5-alpha and ran `yarn upgrade` to update dependencies.
=> Update master version to 5.5-alpha.

LICENSE.txt
Added header to clarify that license is GPL 2+, not GPL 2
Fixes #
*
*
=> Clarify GPLv2 or later

modules/sharedaddy/sharing-sources.php, modules/shortcodes/googleplus.php
=> Google scripts: edit minified javascript

.travis.yml
* Adds me to the mail address list
=> Adds Osk to email list of Travis tests results on master

yarn.lock
Fixes #6878 
* Updates dops-components to include a change made by @sirreal in dops-components.
=> Ran yarn upgrade to include a new version of dops-components.

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php, sync/class.jetpack-sync-functions.php
* Remove data from the update object to be more consistant with the .com side
* Remove action_links if they are not present
- Note that the plugin has an update. 
- When you activate the plugin via the developer console you should see the data the same way as when you request the data from the .com side of things.
=> Update/plugin v1.2 update

class.jetpack-jitm.php
This allows the client to be smart enough to dismiss things properly.
* Adds client-side dismissal logic
* See D7936-code
=> Fix jitm dismissals

_inc/lib/class.core-rest-api-endpoints.php
Fixes #6987
We were looping through a lot of setting keys and trying to load them as general WordPress Options. Most of them didn't exist at all there because the parent module treats them in an special way (For example, as a Jetpack option, or an array inside a Jetpack option, or as a comma separated list of strings).
Should reduce queries to the DB by ~40% when hitting the settings REST endpoint, the REST modules endpoint, the individual module REST endpoint, similar .com endpoints, or visiting the admin pages.
* Moves some code to the default case of the switch statement so we don't attempt to load options with `get_option()` and which we actually don't store as regular WordPress options. This default case handles all of the non-special options
* Explicitly loads sharing options that …
=> Settings: Only call get_option() for  modules that don't treat their options in an special way

class.jetpack.php
Adds a transient based lock with a short (10s) timeout to prevent
multiple processes from triggering the upgrade routine at the same time.
Only a single process after a version change should be responsible for
running the upgrade, to prevent excessive DB queries or other repeated
upgrade-related actions.
On many sites this is a non-issue, but on high traffic sites with many
concurrent requests, it can be a problem.
Fixes #8064
=> Prevent multiple concurrent instances of the plugin upgrade routine

sync/class.jetpack-sync-wp-replicastore.php
Add some extra hardening code to a function that isn't actually called anywhere, but best practices and such.
Props @gravityrail for the wpcom change
=> Add some extra hardening to an unused function.

readme.txt
=> 5.5 Changelog: tweaks and additions during the Beta period

jetpack.php, package.json, yarn.lock
And run `yarn upgrade` to resolve new dependency versions.
=> Bump version to 5.6-alpha.

modules/custom-css/csstidy/data-wp.inc.php
Sourced list from https://developer.mozilla.org/en-US/docs/Web/CSS/font following a request from a user.
cc: @brezocordero
=> Adding some font properties to whitelist for css.

modules/protect.php
In merging #8108 yesterday, a logic block was shifted, and now i'm shifting it back.
@lezama , @enejb - does it look ok?
=> Protect: adjust logic that was disrupted by a merge conflict

sync/class.jetpack-sync-module-callables.php, tests/php/sync/test_class.jetpack-sync-callables.php
Does not fix https://github.com/Automattic/jetpack/issues/8164
But hopes to. 
* Confirm the fatal with a test. 
* Does it pass the tests?
=> Sync: add broken test

json-endpoints/jetpack/json-api-jetpack-endpoints.php
Fix the upload api endpoint. 
* Change how the new plugins endpoints are defined.
* Re test all the plugin api endpoints.
=> Plugin API: The load order messes things up

_inc/client/components/welcome-new-plan/personal.jsx, _inc/client/components/welcome-new-plan/premium.jsx, _inc/client/components/welcome-new-plan/professional.jsx
=> Warm Welcome: change wording to place Jetpack before plan name.

fusion/sync-this.php
=> Discard this PR.

modules/wordads/php/params.php, modules/wordads/wordads.php
Some backend updates to how we call the ad tags.
**To Test**
1. Turn on ads module.
2. Do you see ads?
=> Ads: Update to new __ATA_PP ad tag

class.jetpack-debugger.php
USE wp_safe_redirect instead of wp_redirect
=> use wp_safe_redirect instead of wp_redirect

_inc/client/at-a-glance/index.jsx
In preparation for the inclusion of the Activity Log card that will have a switch to be enabled from wpcom, this refactor lays the foundation for an easy addition of this and future cards without having the update the markup to insert it in a specific place.
=> At a Glance: refactor code for dashboard cards

class.jetpack-debugger.php
Happiness is unifying the tagging for ticket- and livechat-based interactions; this aligns with our live chat tracking.
=> Jetpack Debugger: Split options for backing up or restoring problems

sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-settings.php
=> sync : Apply filter jetpack_sync_comment_meta_whitelist

sync/class.jetpack-sync-defaults.php
Requested in https://github.com/Automattic/jetpack/pull/8285#pullrequestreview-83000704
=> Add Jetpack version to inline docs for comment meta filter

modules/contact-form/admin.php
Sequel to r166560-wpcom / D8630-code
* Adds additional checks for permissions.
=> Contact Form: Add some additional conditionals to admin-ajax handlers

_inc/client/README.md
=> Docs: remove VP references

json-endpoints/class.wpcom-json-api-comment-endpoint.php
Syncing code with latest changes introduced in D8703-code.
=> Comments: sync comment endpoint with dotcom

3rd-party/3rd-party.php, 3rd-party/vaultpress.php, class.jetpack.php
I may (probably will) need to revisit where in the `$features` array I'm checking to see if Rewind is enabled.
WIP.
=> First pass -- VaultPress deactivation if Rewind is running.

modules/google-analytics/classes/wp-google-analytics-legacy.php
*  clean up code and consolidate string rendering with `printf` instead of adding a placeholder and replacing it with `str_replace`
* it should render properly just like before
=> Google Analytics: clean up code and consolidate string rendering

package.json
See also:
• https://spdx.org/news/news/2018/01/license-list-30-released
• https://spdx.org/licenses/
• WordPress Ticket [#43032](https://core.trac.wordpress.org/ticket/43032)
Fixes #
n/a
n/a
n/a
"Update SPDX License in `package.json` to adhere to SPDX v3.0 specification"
=> Update SPDX License in `package.json` to adhere to SPDX v3.0 specification

docs/development-environment.md
* Updates `development-environment.md` doc to recommend latest yarn.
* Check the [rendered version](https://github.com/Automattic/jetpack/blob/update/yarn-docs/docs/development-environment.md) of this doc.
* Confirm that the instructions around `yarn` installation makes sense.
=> Docs: Update yarn docs references and installation instructions

class.jetpack-signature.php, class.jetpack.php
See D9099-code for testing instructions.
=> REST API: Add support for GET onboarding requests

docs/git-workflow.md
The command is mising the remote name.
* Adds the origin name to the command
=> Docs: Fix fetch command in docs about how to rebase

_inc/client/components/notice/style.scss
- Improve development notices with bullet points
=> Improve development notices UI

_inc/lib/markdown/README.md
Fixes #
n/a
* fix a typo and broken URL
Test the URL in this PR
> "docs: fix typo and broken URL"
=> docs: fix typo and broken URL

_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-builder.php, require-lib.php
Just a couple PHPDoc issues I noticed and fixed.
=> Some PHPDoc fixes

changelog.txt, readme.txt
=> Added changelog for 5.7.1.

readme.md
* Adds the Travis build status badge to the README 
* Docs: Add Travis CI build badge
=> Add Travis build badge

modules/search/css/search-widget-filters-admin-ui.css
I accidentally failed to commit this to #8574
=> Add extra padding to bottom of search help link

modules/search/class.jetpack-search-widget-filters.php
Fixes possible error when parsing search sort value.
=> Guard against undefined offset in sorting search query

_inc/client/plans/plan-body.jsx
One-click threat resolution is only available to a11ns
=> Remove mentions of one-click threat resolution

sync/class.jetpack-sync-module-plugins.php
Fixes #
Sync plugin update failures via Jetpack
Tests forthcoming
=> Sync plugin update failures via Jetpack

readme.txt
* add #8568 to the changelog
* we've added support for changing the site language and timezone in Calypso
* see https://github.com/Automattic/wp-calypso/pull/21482 for further details
=> Changelog: add #8568

_inc/lib/class.jetpack-search-performance-logger.php, class.jetpack.php, modules/search/class.jetpack-search.php
Tracks builtin and ES search performance
=> Track search performance

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-widget-filters.php, modules/search/css/search-widget-filters-admin-ui.css, modules/search/js/search-widget-filters-admin.js, tests/php/modules/search/test_class.jetpack-search-helpers.php
Addresses many issues in #8635
This PR is still in progress. Feel free to take over and finish the last two issues though:
=> Search: Update UX of widget

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-widget.php, modules/search/js/search-widget-admin.js, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8666
Translates "Updated" in widget admin.
=> Search: Ensure that widget date filter placeholders are translated

.circleci/config.yml
* Now test artifacts would be added to CI report, which will help debug UI tests 
* Make sure that build step contains reports artifacts, and screenshots artifacts if build step was failed.
=> Collect CircleCI test artifacts in build step

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-template-tags.php, modules/search/class.jetpack-search-widget.php, modules/search/class.jetpack-search.php
This is a second attempt at adding PHPDoc and code cleanup to all of the search code.
Previously: #8603
=> Search: PHPDoc and code cleanup

_inc/client/components/upgrade-notice-content/index.jsx
=> Previous link was incorrect

_inc/client/components/welcome-new-plan/personal.jsx, _inc/client/components/welcome-new-plan/premium.jsx, _inc/client/components/welcome-new-plan/professional.jsx
Update plans welcome screen to include new features plus fix incorrect numbers of themes available.
=> Update plan welcomes to correct features

json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
Introduced in https://github.com/Automattic/jetpack/pull/8654
=> API: Fix a typo

_inc/client/plans/plan-body.jsx, _inc/client/plans/plan-header.jsx
Corrects text as to what different plans contain.
=> Copy updates to plan pages

modules/publicize/publicize.php
Fixes #6379:
* Doc block for save_meta() is revised to indicate if a function exist on a remote codebase.
*
=> Publicize: Updated doc for save_meta()

modules/custom-post-types/portfolios.php, modules/custom-post-types/testimonial.php
In #2815, we added support to show either the full content or the excerpt, but this CPT doesn't support a custom excerpt.
918124-zen
=> CPTs: Add support for excerpts in portfolios/testimonials

_inc/client/scss/variables/_colors.scss, scss/organisms/_banners.scss
This PR updates our Jetpack primary green color to the correct value.
ref: P6TEKc-L7
=> Update Jetpack primary green color hex value.

readme.txt, yarn.lock
Housekeeping as usual after a release.
=> Updated yarn.lock and bumped stable tag.

.github/PULL_REQUEST_TEMPLATE.md
We want to encourage detailed testing instructions, and make contributors aware of the testing list.
=> PR template: add instructions for testing instructions.

_inc/client/traffic/search.jsx
Fixes #8733
Updates the search module card to better match Calypso.
**Before:**
**After:**
=> Admin: Update search module card to better match Calypso

modules/holiday-snow/snowstorm.js
Attributes aria-hidden="true" and role="presentation" added to the SnowFlake (#8309)
=> Improve accessibility of Holiday Snow

modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php
Fixes #8893
jQuery selector was incorrect for attaching a click event to "Update Cart" button.
* Add a product to the cart
* View the cart
* Open Network tab
* Decrease the quantity to zero on the product
* Click "Update cart"
* See a request `t.gif` appear in the Network tab
cc @greenafrican
=> Analytics: jquery selector for Update button

docs/development-environment.md
=> Docs: add instructions to work-around pre-commit issues on Windows

changelog.txt, readme.txt, to-test.md
* Updates changelog.txt to include 5.8's changelog
* Updates readme.txt with boilerplate for 5.8's changelog.
* ~Updates Stable tag to 5.8~. It was already done by another PR. (please update if there happens to exist a 5.8.1 release)
=> Changelog 5.9: running changelog

readme.txt
Fixes #8908
* Fix markdown bullet rendering by having a space above each list of bullets
=> Fix markdown bullets in readme.txt

jetpack.php, package.json, yarn.lock
* Bumps version in `jetpack.php` to `6.0-alpha`
* Bumps version in `package.json` to `6.0.0-alpha`
=> General: Start the 6.0 release cycle

class.jetpack.php, modules/holiday-snow.php
Fixes some left over issues from #9016
* Deprecate actions and filters from holiday snow module
* Add deprecated module stub in `modules/holiday-snow.php`
=> Add stub holiday snow module and deprecated hooks

fusion/whitelist.json
* After the Options class has been synced, it's time to add it to the whitelist.
=> Added the Jetpack Options file to the Whitelist.

modules/videopress/class.jetpack-videopress.php
Fixes #9001
* Removes method that isn't used anywhere.
TODO: Write a fix for #7073.
=> Remove unused VideoPress method

modules/tiled-gallery/tiled-gallery/tiled-gallery-rectangular.php
Fixes #9018
* Removes unused variable
=> Remove unused Jetpack_User_Agent_Info variable

class.jetpack-admin.php
Fixes #9069 
Ran into this while checking out my logs, appears to be pretty straightforward.
cc: @beaulebens
=> Admin Page: Verify index exists before using it

docker/README.md
- Add links to Ngrok alternatives
- Add section about `wp shell` and its quirks
- Add chapter about Ngrok and Jetpack Rewind
Closes #9073
=> Docker: Improve documentation

tests/php/modules/lazy-images/test_class.lazy-images.php
In #9047, a user reported an issue where an image was lazy processed even though it has the `skip-lazy` class added. The user reported using a custom `gallery` shortcode which still used the `gallery_shortcode()` function just like the core `gallery` shortcode.
This PR adds a test to verify that images are lazily processed as expected when the `skip-lazy` class is added. We should follow up with the user to see if he can help us create a test where this breaks.
To test:
- `phpunit --testsuite=lazy-images`
=> Lazy Images: Add test to check #9047

modules/subscriptions.php
* Be more specific about selected keys cc @westi
=> Cherry pick keys from `$_SERVER` array

_inc/jetpack-jitm.js, scss/jetpack-admin-jitm.scss
Fixes #8948
* Adds the ability to display and parse a list array from wpcom
* Get an annual plan that expires in less than 30 days (may need SA assistance to change expiration date)
* Go to the dashboard
* See this jitm
* If your plan will expire soon, we'll give you a heads up on your dashboard
=> JITMS: Add the ability to parse lists

changelog.txt, readme.txt, to-test.md
* Updates changelog.txt to include 5.9's changelog
* Updates readme.txt with boilerplate for 6.0's changelog.
* Updates Stable tag to 5.9 (please update if there happens to exist a 5.9.1 release)
=> Changelog 6.0: running changelog

modules/widgets/social-media-icons.php
=> Social Icons Widget: add deprecation notice to old file.

jetpack.php, package.json, readme.txt, yarn.lock
Also run `yarn upgrade` to update dependencies.
=> Bump version to 6.1-alpha.

docker/README.md
Some simple instructions for running Xdebug on your Docker image through the PhpStorm IDE.
=> Docker: Adds instructions for Xdebug in PhpStorm

docker/README.md, docker/bin/install.sh, docker/bin/multisite-convert.sh, docker/bin/run.sh, docker/bin/uninstall.sh, package.json
Add uninstall script and improve instructions in other helper scripts.
```
yarn docker:up
```
```
yarn docker:install
```
```
yarn docker:multisite-convert
```
```
yarn docker:uninstall
```
:tada:
=> Docker: add uninstall script

fusion/whitelist.json
These files are all in sync now.
=> Add files to fusion whitelist 

class.jetpack.php, jetpack.php, modules/shortcodes.php, modules/shortcodes/slideshow.php, tests/php/test_class.jetpack.php
See D11913-code for explanation.
=> Reverts changes made in 9324

readme.txt
for all his work on the EU Cookie Widget.
=> Readme: add @clickysteve to list of contributors.

json-endpoints/class.wpcom-json-api-render-embed-endpoint.php
* Localization of error messages (not error codes).
=> Merge WP.com changes to Embed Render Endpoint

changelog.txt, readme.txt, to-test.md
* Updates changelog.txt to include 6.0's changelog
* Updates readme.txt with boilerplate for 6.1's changelog.
=> Changelog 6.1: running changelog

readme.txt
Corrected a few typos I noticed in the changelog. 👌 🤓
=> Readme: fix typos

modules/custom-post-types/testimonial.php
Part of #7590
Removes Omnisearch from testimonial CPT
=> Testimonial: remove omnisearch

modules/theme-tools/responsive-videos.php
Fixes errors in the prior sync of this file #9409, correcting whitespace and indentation.
=> Code sync: responsive videos

modules/custom-css/csstidy/class.csstidy.php, modules/custom-css/csstidy/class.csstidy_optimise.php, modules/custom-css/csstidy/class.csstidy_print.php
Merge css-tidy changes from wpcom. 
Looks like some php 5.x compatibility?
=> CSS tidy: merge changes from Jetpack 

class.json-api-endpoints.php
Sync changes from WP.com.
See D12284.
=> Merge Changes to class.json-api-endpoints.php from WordPress.com

jetpack.php, package.json
* Bumps version in `jetpack.php` to `6.2-alpha`
* Bumps version in `package.json` to `6.2.0-alpha`
=> General: Start the 6.2 release cycle

modules/publicize/enhanced-open-graph.php
WPCOM revisions in this PR:
- r141471-wpcom
- r140604-wpcom
- r135835-wpcom
- r135827-wpcom
- r135821-wpcom
- r135774-wpcom
=> Fusion: merge WPCOM changes to enhanced-open-graph.php

fusion/whitelist.json
=> Fusion: add comment endpoint to whitelist

json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Merges commits:
- r160864-wpcom
- r161684-wpcom
- r165508-wpcom
- r165562-wpcom
=> WPCOM merge: update post endpoints

fusion/whitelist.json
=> Fusion: add list-post-type-taxonomies to whitelist

fusion/whitelist.json
=> Fusion: add update-post endpoints to whitelist

json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php
Commit history came out a bit noisy, but it looks like this is just r170736-wpcom
See also D12422-code
=> WPCOM merge: list post types endpoint

readme.txt
=> Readme: fix typo

json-endpoints/class.wpcom-json-api-bulk-delete-post-endpoint.php
=> WPcom Merge: Sync bulk delete endpoint

json-endpoints/class.wpcom-json-api-get-site-endpoint.php
Merges commits:
* r163142-wpcom
* r163585-wpcom
* r164091-wpcom
* r164771-wpcom
* r165439-wpcom
* r168907-wpcom
* r169677-wpcom
* r172358-wpcom
=> WPcom Merge: get site endpoint

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
cc @oskosk - can we get https://github.com/Automattic/jetpack/pull/9464 and this follow-up PR into v6.1.1 later this month?
=> REST API: Change new settings filter from v6.2.0 to v6.1.1

changelog.txt, readme.txt, to-test.md
* Updates changelog.txt to include changelog for 6.1
* Updates readme.txt to include changelog for 6.1.1
* Bumps stable tag to `6.1`
Note to my future self: This PR updates Stable tag, because 6.1.1 is a point release. Do not do update stable tag on PRs for major releases.
=> Add changelog 6.1.1

readme.txt
* Updates caption for screenshots on `readme.txt`
The following are the new screenshots and will be committed to svn directly
Themes: Choose from hundreds of customizable, professional themes.
Performance: Free high-speed content delivery network for your images.
Apps: Update your site from any device with the free WordPress apps.
Analytics: Simple and concise site stats and traffic insights.
Sharing: Connect your site to social networks for automated social sharing.
Revenue: Sell products & take payments with simple payment buttons.
Downtime Monitoring: Get notified if and when your site goes down.
Security: Protection against brute force attacks, spam, and malware. On-demand backups and restores.
=> Update screenshot captions

json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
`net_neutrality` was added in r166747-wpcom by @ockham
=> File sync: Site settings endpoint v3 & 4

json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
This comment is only meant to be displayed in wpcom
=> Remove wpcom-only comment

modules/custom-post-types/portfolios.php
This is a partial merge of Portfolio changes from wpcom, which includes: 
- stats bumping, but only on wpcom 
- a fix for Infinite Scroll behavior with the `click` setting. See r144617-wpcom (@mendezcode)
=> File sync: Portfolio CPT (partial)

_inc/client/components/module-settings/index.jsx, _inc/client/traffic/related-posts.jsx, _inc/lib/class.core-rest-api-endpoints.php, modules/related-posts/class.related-posts-customize.php, modules/related-posts/jetpack-related-posts.php
Added suggested text for Jetpack UI and Customizer UI. Please let me know if you'd like additional changes or documentation.
=> Related Posts: Make label for thumbnails clearer (#9568)

modules/shortcodes/polldaddy.php
* Load polldaddy scripts asynchronously to improve load time.
* To check polldaddy scripts are loading asynchronously.
=> load polldaddy scripts asynchronously

modules/lazy-images.php
=> Lazy Images: Make it a part of Jumpstart #9567

readme.txt
* Moves an item out of bug fixes into improved compatibility
* Adds #9669 to changelog
None needed.
=> Update changelog for 6.2 with latest changes from the Beta period 

jetpack.php, package.json
* Bumps version in `jetpack.php` to `6.3-alpha`
* Bumps version in `package.json` to `6.3.0-alpha`
=> General: Start the 6.3 release cycle

changelog.txt, readme.txt
* Updates changelog.txt to include changelog for 6.2
* Updates readme.txt to include changelog for 6.2.1
* Bumps stable tag to `6.2`
=> Add changelog 6.2.1

dangerfile.js
* Add rule to validate that at least 1 `[Status]` is set.
* Add rule to validate that `Testing instructions` section is present.
Review warning for this PR
=> Danger: Add [Status] label & Test instructions rules

_inc/client/at-a-glance/backups.jsx, _inc/client/at-a-glance/scan.jsx
Fixes #9565 
* Add contextual links to Security/Backup cards
Before:
After:
* Manually on Chrome
* yarn test-client  and yarn test-gui
=> Add contextual links to Security/Backup cards

readme.txt
Made behavior en_US base, can be switched to behaviour in en_CA, en_GB, en_AU, etc
=> Localization fix

jetpack.php, package.json
* Bumps version in `jetpack.php` to `6.4-alpha`
* Bumps version in `package.json` to `6.4.0-alpha`
=> General: Start the 6.4 release cycle

changelog.txt, readme.txt
* Updates changelog.txt to include changelog for 6.3
* Updates readme.txt to include changelog for 6.3.2
* Bumps stable tag to 6.3
=> Add 6.3.2 changelog

bin/pre-commit-hook.js, composer.json, docs/development-environment.md
* Add PHPCS pre-commit hook for changed files
* check out this branch
* change any PHP file (ideally add some PHP 5.2 issue)
* try to commit these files
* make sure that JS linting is still working as expected
=> Add PHP 5.2 Compatibility linting pre-commit hook

jetpack.php, package.json, readme.txt
* Bumps version in `jetpack.php` to `6.5-alpha`
* Bumps version in `package.json` to `6.5.0-alpha`
* Fixes typo in readme.txt . This fix is to be added by hand on SVN before publishing 6.4
None needed
=> General: Start the 6.5 release cycle

tests/php/modules/shortcodes/test_class.hulu.php
The Hulu shortcode makes a request to Hulu's oEmbed endpoint to lookup `eid`s (Hulu's internal video ID) from `id`s (human readable video ID).
These tests fail intermittently in CI: presumably because we get throttled by Hulu for making too many requsets.
Bypasse the HTTP requests by injecting a value into the shortcode's eid lookup cache.
Add a single HTTP-based test to the `external-http` group (which is not run by default).
This is another attempt to address the issue from #10019.
1. `phpunit --filter=WP_Test_Jetpack_Shortcodes_Hulu`
2. `phpunit --filter=WP_Test_Jetpack_Shortcodes_Hulu --group external-http`
OR:  Let TravisCI do its thing :)
=> Tests: Shortcodes: Hulu - Bypass HTTP Lookup

tests/php/modules/shortcodes/test_class.getty.php
The Getty shortcode makes a request to Getty's oEmbed endpoint to determine what HTML should be output for the given shortcode.
These tests fail intermittently in CI: presumably because we get throttled by Getty/Travis for making too many requsets.
Bypass the HTTP requests by "manually" returning early from `WP_oEmbed::get_html()` via the `pre_oembed_result` filter.
Add a single HTTP-based test to the `external-http` group (which is not run by default).
1. `phpunit --filter=WP_Test_Jetpack_Shortcodes_Getty`
2. `phpunit --filter=WP_Test_Jetpack_Shortcodes_Getty --group external-http`
OR: Let TravisCI do its thing.
Make Getty shortcode tests more robust.
=> Tests: Shortcodes: Getty - Bypass HTTP Request

docker/README.md
=> Docker: remove extra `+` from docs

class.jetpack.php
Removes stray `<<<<<<< HEAD` from a comment
=> Remove stray diff comment

modules/contact-form/grunion-contact-form.php
Currently, the Personal Data Eraser can skip some feedbacks:
1. Request first page's worth of feedbacks (feedbacks 1-250).
2. Delete them all (1-250).
3. Request second page's worth of feedbacks (feedbacks 251-500).
4. Since we deleted feedbacks 1-250 in step 2, these feedbacks we're looking at now are those that were originally the *third* page's worth of feedbacks (501-750). When we delete them, then, we've skipped past what was originally feedbacks 251-500.
See comments at https://github.com/Automattic/jetpack/pull/9638#pullrequestreview-139859128
We can also end up in an infinite loop if the `grunion_contact_form_delete_feedback_post` filter skips enough feedbacks.
To prevent these skips and these infinite loops, keep state tracking the last feedback ID we've processed. On the next …
=> Contact Forms: Ensure Personal Data Eraser Looks at Each Feedback

_inc/lib/class.media-summary.php
Brings the media summary class code in sync with WordPress.com, no major logic changes here except for the `break` replacement with `continue`.
=> Synchronized the media summary class code.

jetpack.php, package.json
* Bumps version in `jetpack.php` to `6.6-alpha`
* Bumps version in `package.json` to `6.6.0-alpha`
None needed
=> General: Start the 6.6 release cycle

modules/sharedaddy/sharing-service.php
I ran PHPCBF (PHPCS 3.3.0) with the WordPress-VIP ruleset.
=> PHPCBF spacing fixes

sync/class.jetpack-sync-module-themes.php
Set the default variable so that .com side works as expected.
Do the tests pass?
=> Jetpack Sync: Make the tests pass on the .com side

tests/php/modules/shortcodes/test_class.gist.php
Related: #10053
Add some basic unit tests to check Gist shortcodes.
Make sure that all tests pass. 
Shortcodes: add basic unit tests for Gist shortcodes.
=> Shortcodes: add basic unit tests for Gist shortcodes.

readme.md
=> Update list of HEs to reflect recent team changes

modules/widgets/authors.php, modules/widgets/blog-stats.php, modules/widgets/contact-info.php, modules/widgets/eu-cookie-law.php, modules/widgets/facebook-likebox.php, modules/widgets/flickr.php, modules/widgets/follow-button.php, modules/widgets/gallery.php, modules/widgets/goodreads.php, modules/widgets/google-translate.php, modules/widgets/googleplus-badge.php, modules/widgets/gravatar-profile.php, modules/widgets/image-widget.php, modules/widgets/internet-defense-league.php, modules/widgets/mailchimp.php, modules/widgets/my-community.php, modules/widgets/rsslinks-widget.php, modules/widgets/search.php, modules/widgets/simple-payments.php, modules/widgets/social-icons.php, modules/widgets/social-media-icons.php, modules/widgets/top-posts.php, modules/widgets/twitter-timeline.php, modules/widgets/upcoming-events.php, modules/widgets/wordpress-post-widget.php
@see #10168
* automated PHPCS fixes for all Widget PHP files.
=> Widgets: automated PHPCS fixes.

modules/carousel/jetpack-carousel.php
=> Carousel: automated PHPCS fixes.

modules/widget-visibility/widget-conditions.php, modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php, modules/woocommerce-analytics/wp-woocommerce-analytics.php
See #10168
* PHPCBF fixed for woo analytics and widget visibility 
* Confirm style only changed
n/a
=> PHPCS: Updating woo anayltics and widget vis phpcbf

modules/after-the-deadline/config-options.php, modules/after-the-deadline/config-unignore.php, modules/after-the-deadline/proxy.php
=> AtD: automated PHPCS fixes.

modules/wordads/php/admin.php, modules/wordads/php/api.php, modules/wordads/php/params.php, modules/wordads/php/widgets.php, modules/wordads/wordads.php
See #10168
* phpcbf fixable wpsc issues in WordAds
* Verify only styling changes
n/a
=> WordAds + WPCS: Fix style issues via phpcbf

modules/theme-tools/compat/twentyfourteen.php, modules/theme-tools/compat/twentysixteen.php, modules/theme-tools/content-options.php, modules/theme-tools/content-options/author-bio.php, modules/theme-tools/content-options/blog-display.php, modules/theme-tools/content-options/customizer.php, modules/theme-tools/content-options/featured-images-fallback.php, modules/theme-tools/content-options/featured-images.php, modules/theme-tools/content-options/post-details.php, modules/theme-tools/featured-content.php, modules/theme-tools/infinite-scroll.php, modules/theme-tools/random-redirect.php, modules/theme-tools/responsive-videos.php, modules/theme-tools/site-breadcrumbs.php, modules/theme-tools/site-logo.php, modules/theme-tools/site-logo/inc/class-site-logo-control.php, modules/theme-tools/site-logo/inc/class-site-logo.php, modules/theme-tools/site-logo/inc/compat.php, modules/theme-tools/site-logo/inc/functions.php, modules/theme-tools/social-links.php, modules/theme-tools/social-menu.php, modules/theme-tools/social-menu/icon-functions.php
See #10168
* Styling updates per phpcbf
* Style changes only.
* n/a
=> Theme Tools + WPCS: Fix style issues via phpcbf

tests/php/_inc/lib/test_class.rest-api-authentication.php
Jetpack can receive signed `multipart/form-data` requests, but the signature is always based on the "equivalent" `application/x-www-form-urlencoded` request; Essentially, Jetpack signs PHP's `$_POST`.
(The above is accurate if not terribly precise: there is more going on to make sure PHP's `$_FILES`, for example, is also signed.)
In the `multipart/form-data` REST API Authentication test, let's make sure we're testing with inputs that look like what Jetpack actually processes and signs.
1. `yarn docker:phpunit --filter=WP_Test_Jetpack_REST_API_Authentication`
None - part of https://github.com/Automattic/jetpack/pull/10188.
=> REST API Auth Tests: Accurately reflect normal behavior

class.jetpack.php
To be in accordance with the actual code, see https://github.com/Automattic/jetpack/blob/b1b0f7e50e296172ab4e7b1a7ec893065ac9cfd8/class.jetpack.php#L7324-L7327
=> Gutenberg: Update path names in PHPDoc

_inc/client/traffic/style.scss, _inc/client/traffic/verification-services/google.jsx
Fixes #10230
* Change Google Site Verification Button Style and Text to better render at narrow widths
The cutoff for these buttons is around 320px widths, but that is both much better than before and the width of an iPhone SE, one of the most narrow modern phones available.
**BEFORE**
narrow
wider
wide
**AFTER**
narrow
wider
wide
* Navigate to Jetpack -> Settings -> Traffic -> Site Verification
* If your site is in the verified mode, clear the meta
* Verify the visual changes above are apparent
* Change Google Site Verification Button Style and Text to better render at narrow widths
=> Make Google Verification Buttons Not Cut Off at Very Narrow Widths

.github/CODEOWNERS
*Title says it all
*Make sure the team exists?
None needed
=> Update catch-all "code owners" team to Jetpack Crew

jetpack.php, package.json
Start a new release cycle by updating the current version in jetpack.php and package.json
None.
None.
=> General: Start the 6.7 release cycle

readme.txt
Changelog: create changelog for 6.6.1
None
None
=> Changelog: create changelog for 6.6.1

modules/sitemaps.php, modules/sitemaps/sitemap-buffer-fallback.php, modules/sitemaps/sitemap-buffer-image-fallback.php, modules/sitemaps/sitemap-buffer-master-fallback.php, modules/sitemaps/sitemap-buffer-news-fallback.php, modules/sitemaps/sitemap-buffer-page-fallback.php, modules/sitemaps/sitemap-buffer-video-fallback.php, modules/sitemaps/sitemap-buffer.php, modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-librarian.php, modules/sitemaps/sitemap-logger.php, modules/sitemaps/sitemap-state.php, modules/sitemaps/sitemaps.php
Pulls into #10275 . Separate PR to make review easier This is not fully inclusive of all PHPCS items noted, but should be all safe. Changes that require testing to be made later.
* PHPCS tweaks to Sitemaps
* Ensure only styling and docblock changes.
=> Sitemaps: PHPCS fixes

tests/e2e/lib/blocks/word-ads.js
* try using `nth-child` css function to locate ad formating 
* Travis tests should be green
* n/a
=> E2E tests: fix flakiness in some tests

tests/setup-travis.sh
We're still running pretty old PHPUnit for everything. Let's try updating it.
* Updating PHPUnit versions.
* n/a
* See Travis.
*
* n/a
=> Unit Tests: Try using PHPUnit 6 and 7

packages/partner/README.md
The code examples on the README.md page where showing two `use` statements but the body is not using any code from those namespaces thus they can be removed.
* No actual code changes, just code examples in README.md.
* Update partner package code examples.
=> Update README.md on partner package

modules/publicize.php
Follow-up to #15527
* The module name makes the hook categorized properly on the Codex site.
* N/A
=> Publicize: add module name to new filter

extensions/blocks/podcast-player/style.scss
Replay #15573 against `master`.
See #15573 
* N/A
=> Podcast Player: Fix cropped description text & title wrapping

.github/workflows/required-review.yml
See p1588082321042300-slack-jetpack-crew
* Is a review required?
* N/A
=> Actions: try to rename job name to test theory about failed tests

class.json-api.php
Allows html content type.
Reviewers: jonsurrell, simison, ramonopoly, noahtallen, vindl
Reviewed By: jonsurrell
Differential Revision: D40475-code
This commit syncs r204594-wpcom.
=> JSON API: Sync with WP.com

modules/sharedaddy/sharing-sources.php
These are present on WP.com but we should have them too.
* Add translator comments.
* n/a
* n/a
* n/a
=> Sharing: Add translator comments

_inc/lib/admin-pages/class.jetpack-react-page.php
* Update docblock to proper version format to the parser connects it with other 8.5 filters.
* n/a
* n/a
*
* n/a
=> React Dash: Correct hook version

modules/sharedaddy/sharing.php
* Adds a translator comment already present on WP.com.
* n/a
* n/a
* n/a
=> Sharing: Add translator comment

jetpack.php, package.json, yarn.lock
* Update version numbers and `yarn.lock` to start new release cycle.
* Not much to test here
* N/A
=> 8.6 Release: start cycle

tests/e2e/jest-puppeteer.config.js, tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/pages/wp-admin/in-place-authorize.js, tests/e2e/lib/pages/wp-admin/in-place-plans.js, tests/e2e/lib/setup-env.js, tests/e2e/specs/connection.test.js
* Adds a new test for an in-place connection flow 
* Make sure that Travis is happy
* n/a
=> E2E tests: Add in-place connection flow

extensions/blocks/image-compare/view.js
Fixes #15743 
Adds a check for element before trying to access a property. An issue was reported in #15743 that I have not been able to duplicate, this adds a bit of defensive programming to avoid an error. 
* Create new post
* Add Image Compare block, check JavaScript console for errors
=> Image Compare: defend against undefined element and JS error

extensions/blocks/button/index.js
Add support for left and right alignment on the button block.
This has been tested with the Revue block, and the updated Contact Form block. Works correctly in the editor and on the front end.
* Add a Revue block
* Change the alignment of the button block and confirm it works in the editor and front end when published.
* None needed.
=> Button Block: Add left/right alignment support

extensions/blocks/instagram-gallery/edit.js, extensions/blocks/instagram-gallery/editor.scss, extensions/blocks/instagram-gallery/use-connect-instagram.js, extensions/blocks/instagram-gallery/view.scss
* Add a confirmation notice when disconnecting an Instagram account.
* Add a description text under the disconnect button to clarify what it does.
Apologies for the big diff: while adding some editor CSS, I've also "swapped" the `editor.scss` and `view.scss` files, in order to avoid loading editor styles in the front end.
* Insert a Latest Instagram Posts block, and connect it to an Instagram account.
* Open the block sidebar.
* Make sure there is a description text under the "Disconnect your account" link.
* Click on the link.
* Make sure there's a confirmation notice interrupting the disconnection.
* N/A
=> Latest Instagram Posts Block: Add a confirmation notice when disconnecting an Instagram account

dangerfile.js
* This PR adds a link to the relevant E2E results in the allure dashboard
* Check danger output. it should have a URL to the dashboard page
*
* n/a
=> Danger: Mention E2E dashboard in danger output

_inc/client/setup-wizard/feature-toggle/map-feature-to-props.js
Fixes https://github.com/Automattic/jetpack/pull/15914#discussion_r429862138
* This PR fixes the copy for the title of the Testimonial feature
* No
No
1. Verify that the copy is appropriately updated.
* None needed
=> Jetpack Setup Wizard: Fix testimonial title copy

_inc/client/setup-wizard/intro-page/index.jsx, class-jetpack-wizard-banner.php
* This PR fixes some copy by adding a period.
* No
* Verify that the copy is changed appropriately.
* None needed
=> Jetpack Setup Wizard: Add period to intro header

3rd-party/vaultpress.php, _inc/client/components/notice/style.scss
Fixes 1169345694087188-as-1177090507902885.
* This updates the copy and link for the notice displayed when attempting to activate VaultPress 
* Part of this: pbtFFM-hc-p2.
* No.
* On a site with Jetpack Backups purchased and the VaultPress plugin installed, activate VaultPress.
* None needed?
=> Updates wording and link on VaultPress notice

bin/phpcs-whitelist.js
* let's keep that list ordered alphabetically
* No
* N/A
=> Whitelist: let's keep it ordered alphabetically

readme.txt, to-test.md
* Changelog for the upcoming version of Jetpack.
* N/A
=> 8.6: changelog

jetpack.php
WordPress core supports these headers now, this plugin should add these headers.
Fixes #
*
* Go to '..'
*
*
=> Add required headers in plugin

readme.txt
* Bring back a changelog entry from the release branch to `master`.
* No
* This is the changelog.
=> Changelog: add #16005

extensions/blocks/recurring-payments/edit.jsx
Fixes #42591
Ensures a Recurring Payment price is updated to reflect the currency's minimum requirement if the previous price isn't valid for the new currency.
Before | After
--- | ---
Updates the Recurring Payments block which is already an existing part of Jetpack.
No.
Jetpack
* Set up Recurring Payments on a JP site using the testing store and using this branch (a JN site works). More info in PCYsg-lW4-p2 #testing-with-jetpack.
* Add a Recurring Payments block to a page or post.
* Add a new plan.
* Note the defaults for currency and price - USD and $0.50.
* Change the currency to something else, like NOK or JPY.
* Make sure the price is updated to the minimum price for the selected currency.
* Make sure the price is not updated if you previously entered a price which is still above the …
=> Recurring Payments: Update price after currency changes

jetpack.php, package.json
* Update version number to start release cycle
* No
* No
* Not much to test here
* No
=> General: start 8.7 release cycle

readme.txt
Brings in readme.txt changes from Jetpack 8.6.1
=> Changelog: 8.6.1 updates

readme.txt
* Updated lazy load description text in readme.txt
* 
no
no
Make sure there are no typos
*
no
=> Update Lazy Load description in readme.txt

extensions/blocks/image-compare/edit.js
* I ran into those 2 unused dependencies when investigating unrelated linting issues.
* No
* N/A
=> Image Compare: remove unused dependencies

_inc/client/at-a-glance/style.scss, _inc/client/components/chart/bar.jsx, _inc/client/components/chart/style.scss
Fixes #12910
This PR improves the accessibility of the dashboard stats component:
* Focus is now clearly indicated for filters and when tabbing through the chart
* Using the enter key on the stats graph now works
* Stats are clearly spoken to a screen reader
Improves the stats module.
Focus styles:
No. 
We might expect to see a slight increase in use of the Calypso stats breakdown view.
* Go to Dashboard > At a Glance
* Use the tab key to cycle through the site stats section
* Make sure your focus is clearly indicated across the stats section
* Listen to spoken labels in screen reader
* Use the enter key to navigate to the stats you wish to view
* Improve accessibility of site stats
=> Improve dashboard stats a11y

modules/module-headings.php, modules/shortlinks.php
Fixes #15937
* None, this is a copy change
N/A
N/A
In the settings for WP.me Shortlinks - under Jetpack -> Settings -> Traffic tab - the tool tip text indicates:
> Generates shorter links so you can have more space to write on social media sites. Learn more
With this PR in place it should now read: 
> Generates shorter links using the wp.me domain
props @csonnek 
N/A
=> Update copy for shortlinks module

json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
Summary: This patch addresses the issue that in non-English we are not showing differenciated error messages when the upload cannot happen because of the file size (too big, over quota etc.) The client-side fix for this is https://github.com/Automattic/wp-calypso/pull/42921
Test Plan: Test along with https://github.com/Automattic/wp-calypso/pull/42921, for a full media library there should be the right error message when the upload fails because of lack of space.
Reviewers: yslavchev, zinigor
Reviewed By: yslavchev
Subscribers: yslavchev
Differential Revision: D44299-code
This commit syncs r208397-wpcom.
=> REST File upload: Add custom error codes

.github/workflows/build-beta.yml, bin/pre-commit-hook.js
* Add new GH action. that builds jetpack and notifies beta builder that the build is ready to download
* re-trigger the GH action.
* find `try_gh-action-beta-build` entry in https://betadownload.jetpack.me/jetpack-branches.json
* make sure that `update_date` refers to the latest run
* n/a
=> HACK: Add beta build github action

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php, tests/php/core-api/wpcom-endpoints/test_class-wpcom-rest-api-v2-endpoint-external-media.php
Extends permission check for uploading media and helps unit tests with cleaning up after themselves.
* More detailed permission check for image upload.
* Clean up manipulation filters in unit tests to not interfere with other tests.
No
* In the Editor, insert an Image block
* Select an image from an external library and insert it into the block
* Make sure images can be inserted without error messages.
* None needed.
=> External Media: Improve upload permission check

packages/status/src/class-status.php, packages/status/tests/php/test-status.php, packages/status/tests/php/test_Status.php
* Add a new known provider using staging sites, newspack.
* no
* On a Newspack staging site, you should now get the staging mode banner at the top of the Jetpack dashboard.
* N/A
=> Staging Sites: add newspack staging to the list of known providers

.github/workflows/build-beta.yml
* Update zip artifact to incapsulate bundle contents in `jetpack-dev` folder as required by Jetpack Beta plugin. 
n/a
* Using Jetpack Beta plugin try to switch to this PR
* n/a
=> Github Actions: fix build-beta artifact

modules/sitemaps.php
See https://core.trac.wordpress.org/changeset/48094
=> Sitemaps: Update filter

modules/shortcodes/crowdsignal.php, modules/shortcodes/mailchimp.php, modules/shortcodes/tweet.php, modules/theme-tools/devicepx.php
Follow-up to #16193
All the modules, except for WordAds which has a bit to do.
* PHPCS
n/a
No.
* n/a
*
* n/a
=> PHPCS: Modules

_inc/client/components/foldable-card/index.jsx, _inc/client/components/form-input-validation/index.jsx, _inc/client/components/global-notices/docs/example.jsx, _inc/client/components/popover/index.jsx, _inc/client/components/setting-toggle/index.jsx, _inc/client/components/spinner/docs/example.jsx, _inc/client/plans-prompt/index.jsx, _inc/client/traffic/verification-services/google.jsx, extensions/blocks/image-compare/index.js, extensions/blocks/tiled-gallery/deprecated/v1/layout/mosaic/ratios.js, extensions/blocks/tiled-gallery/layout/mosaic/ratios.js, extensions/shared/blocks/cover/cover-media-placeholder.js, extensions/shared/blocks/cover/index.js, extensions/shared/blocks/cover/utils.js, extensions/shared/components/upgrade-nudge/index.jsx
This is simply automatically-reformatted files from running `yarn reformat-files`.
Fixing these now means people won't have to include these unrelated changes in other PRs.
=> Reformat files

extensions/blocks/publicize/editor.scss
* in case that text wraps in two or more lines, height should be auto, line-height initial
* also top/bottom padding should be added in order to match the expected height 
the above changes ultimately resolve #16226
No
* Setup local jetpack env with ngrok tunneling as per [instructions](https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md) 
* Go to /wp-admin/admin.php?page=jetpack#/sharing and setup a linkedin connection
* Revoke permission from linkedin https://www.linkedin.com/psettings/permitted-services
* Go to /wp-admin/post-new.php
* Click the jetpack icon
**Before**
**After**
* Publicize: Properly formats text in broken connections list (facebook, linkedin etc)
=> Publicize: Properly formats text in broken connections list

.github/test-case-reminder.json
* Adds initial configuration for [test-case reminder bot](https://github.com/apps/test-case-reminder) 
https://wp.me/p9dueE-1wX
No
* Nothing really to test here. Once this merged, I'll prep a PR with actual content, so it would be "testable"  
* n/a
=> Add test case reminder bot configuration

docs/testing/regression-checklist/README.md, docs/testing/regression-checklist/mapping.json, docs/testing/regression-checklist/regression-checklist.md, docs/testing/regression-checklist/test-suites/extenstions/all.md, docs/testing/regression-checklist/test-suites/extenstions/blocks/contact-form.md, docs/testing/regression-checklist/test-suites/modules/publicize.md, docs/testing/regression-checklist/test-suites/modules/stats.md, docs/testing/regression-checklist/test-suites/packages/connection.md, docs/testing/regression-checklist/test-suites/packages/sync.md
This PR adds some initial setup for the regression checklist. Also, it adds a mapping.json that would be used for [test-case-reminder](https://github.com/apps/test-case-reminder) bot
https://wp.me/p9dueE-1wX
No
* Unfortunately, it is not possible to test the bot integration because it looks for configuration in master, not in a PR branch.
* Look through test-suites. Are they look good?
Once this merged, for new PRs that touches files in `mapping.json` test-case reminder bot will post a comment that will look like this:
* n/a
=> Add regression checklist

modules/calypsoify/class.jetpack-calypsoify.php, modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php
Reverts Automattic/jetpack#15644 due to a change of plan with how to manage deprecation of the calypso editor
=> Editor:  Revert Update switch to classic editor link

docs/testing/regression-checklist/test-suites/extensions/blocks/contact-form.md
* More test cases for the Form block
* No 
* Not much to test here
* N/A
=> Form Block: add more test cases

packages/config/src/class-config.php
---------------
The namespace of the JITM class was changed in v1.6 of the `jetpack-jitm` package. The namespace of the JITM class was also updated in v1.2 of the `jetpack-config` package. The table below shows the JITM class namespaces for the `jetpack-jitm` and `jetpack-config` packages:
| Package.          | Version | JITM class namespace                 |
|---------------|---------|----------------------------------|
| jetpack-jitm     | v1.6       | Automattic\Jetpack\JITMS\JITM  |
| jetpack-jitm    | <v1.6     |  Automattic\Jetpack\JITM             |
| jetpack-config | v1.2       |  Automattic\Jetpack\JITMS\JITM |
| jetpack-config | <v1.2     | Automattic\Jetpack\JITM              |
This means that the v1.2 `jetpack-config` package is not compatible with the <v1.6 `jetpack-jitm` …
=> Config: check for both JITM namespaces

changelog.txt, readme.txt, to-test.md
* Add the changelog entries for this release.
N/A
No 
* Not much to test here. Check for typos.
* This is the changelog.
=> Jetpack 8.7: a changelog

packages/connection/composer.json
The WorDBless mock is now an actual Packagist package.
* No longer points to the direct VCS repo for the package.
n/a
n/a
* cd packages/connection && composer install
* n/a
=> Tests: Update WorDBless location

jetpack.php, package.json, readme.txt
* update version numbers to start 8.8 release cycle
* N/A 
* N/A 
* Not much to test here
* N/A
=> General: update version numbers to start 8.8 release cycle

packages/debug-helper/modules/class-rest-api-tester.php, packages/debug-helper/modules/inc/css/rest-api-tester.css, packages/debug-helper/modules/inc/js/rest-api-tester.js, packages/debug-helper/plugin.php
This is the testing/debugging tool for Jetpack REST API.
* The tool.
No.
_This is an internal tool, no testing necessary._
1. Go to "Jetpack -> Debug Tools" and enable "REST API Tester".
2. Go to "Jetpack -> REST API Tester".
3. Enter `plans` into "REST Route", click "Send.
4. You should see the response under the form.
N/a.
=> Debug Tools: REST API Tester.

tests/php/sync/class.silent-upgrader-skin.php, tests/php/sync/test_class.jetpack-sync-themes.php
Core just introduced https://core.trac.wordpress.org/changeset/48390 , which broke our tests relying on our own fake Upgrader Skin class.
* N/A
* N/A
* N/A
=> Tests: Update our test Upgrader Skin class to match changes in Core

.github/actions/repo-gardening/src/tasks/assign-issues/index.js, .github/workflows/build-artifacts.yml, .github/workflows/gardening.yml, .github/workflows/required-review.yml, .github/workflows/update-package.yml, packages/compat/functions.php
Fixes #16446 
* Let's avoid triggering actions when not necessary.
* N/A
* N/A
* Let's make sure the actions still work for this PR
- See #16446 to see that the labels are added like they should
- I'll be making changes in commits on this branch to trigger other actions (I'll revert them afterwards)
* I'll create another PR, but from my forked version of this repo, and we can see how the actions behave there. See #16448. 
* N/A
=> Actions: limit actions so they do not run on PRs from forks

class.jetpack.php
* It hasn't been used since Jetpack 7.2 (see #11603)
* N/A
* N/A
* Does everything still work? Try loading both the Jetpack dashboard and Jetpack blocks on a site with French language for example.
* N/A
=> i18n: remove unused function

modules/widgets/twitter-timeline-admin.js, modules/widgets/twitter-timeline.php
Fixes #6290 
Fixes #13789
taking into account the recommendations [in this PR](https://github.com/Automattic/jetpack/pull/13853) as well.
1. Add a new option in the Twitter Widget form, c which can be either `fixed` or `dynamic`. 
By choosing `dynamic`:
- the `Height` input is displayed, 
- the `Number of tweets in the timeline` is hidden and 
- the corresponding `scrollbar` related option is enabled. 
By choosing `fixed`:
- the `Number of tweets in the timeline` input is displayed,  
- the `Height` input is hidden and 
- the corresponding `scrollbar` related option is disabled. 
2. Move the `Twitter username` input to the top of the form
4. Use sentence case on all labels: Twitter username, Maximum width, Link color`, etc.
5. Get rid of the weird ( ? ) link and replace it for something …
=> Twitter Widget: Enhance functionality and UX

changelog.txt, readme.txt
8.7.1 Release: Changelog
* N/A 
* N/A 
* N/A
=> 8.7.1 Release: Changelog

package.json, yarn.lock
* Updating this will allow us to start using things like `createInterpolateElement` in the React dashboard (see #13527).
* N/A
* N/A
* The build should complete with no errors, and you should notice no differences in the Jetpack dashboard.
* N/A
=> Build: update to latest stable of @wordpress/element

_inc/lib/core-api/load-wpcom-endpoints.php
See https://wordpress.org/support/topic/fatal-errors-67/
See #3056
* N/A
* N/A
* On a site running this branch, go to `https://mysite.ninja/wp-content/plugins/jetpack/_inc/lib/core-api/load-wpcom-endpoints.php`
* You should not see any errors.
* N/A
=> General: disable direct access to file

extensions/blocks/mailchimp/view.js, extensions/blocks/mailchimp/view.scss
Fixes #11846
* trigger `emailValidator.validate( email )` while user is typing (1000ms debounce) so that they get instant feedback on the email validity. The same check also runs in form submission
* trigger the html5 browser validation so that the email error message is shown 
* add `outline-color: var( --color-error );` to the `input` in case of error
1. Add a Subscription block [instructions](https://github.com/Automattic/wp-calypso/pull/30275)
2. Publish
3. View the block
4. Enter invalid email
* Mailchimp Block: show error message on validation error
=> Mailchimp Block: show error message on validation error

packages/debug-helper/README.md
Adds a README to the Debug helper package/plugin
* Proof read
=> adds a REAME to the debug helper package

tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/page-helper.js, tests/e2e/specs/connection.test.js, tests/e2e/specs/free-blocks.test.js
* fixes few issues with the e2e tests
n/a
n/a
* check E2E build in Travis
*
* n/a
=> Fix e2e tests

_inc/client/README.md
* Update the documentation now we've updated the way the React dashboard handles translations.
Primary issue: #16481 
* N/A
* N/A
* N/A
=> Admin Page: update i18n documentation

_inc/client/components/auth-iframe/index.jsx, _inc/client/performance/search.jsx, _inc/client/plans/utility.js
* Left-overs after PRs updating the codebase (see #16481)
I forgot those when updating the codebase.
* N/A
* N/A
* N/A
=> Admin Page: stop using i18n-calypso for translations

tests/e2e/lib/blocks/eventbrite.js, tests/e2e/lib/blocks/mailchimp.js, tests/e2e/lib/blocks/pinterest.js, tests/e2e/lib/blocks/simple-payments.js, tests/e2e/lib/blocks/word-ads.js, tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/logger.js, tests/e2e/lib/page-helper.js, tests/e2e/lib/pages/jetpack-connect/site-topic.js, tests/e2e/lib/pages/page.js, tests/e2e/lib/pages/postFrontend.js, tests/e2e/lib/pages/wpcom/checkout.js, tests/e2e/lib/pages/wpcom/pick-a-plan.js, tests/e2e/lib/plan-helper.js, tests/e2e/lib/setup-env.js, tests/e2e/lib/utils-helper.js, tests/e2e/specs/free-blocks.test.js
* Update e2e tests with Prettier (follow-up from #16534) and update a few jsdoc to avoid linting errors.
This is needed for #16455. 
* N/A
* N/A
* N/A
=> e2e tests: update with Prettier

packages/debug-helper/modules/class-broken-token.php
Adds a method to randomize the Primary user ID and move its user token along to the same random ID.
This simulates a state where a user was deleted but the site still has an invalid `master_user` options and a user token pointing to the deleted user ID.
* Activate debug helper plugin and activate  Broken token module
* Setup a healthy connection with an authorized user
* Go to Jetpack > Broken token
* Click "Store these options" to store your current valid options
* Click on "Randomize Primary User ID and move the user token together"
* Check the stored options on the top of the page and verify that:
* The Primary User has changed
* The User tokens array has a key matching the Primary User
* The last part of the token, after the last dot, matches the Primary User ID
*
=> Add new method to break the master user

bin/phpcs-requirelist.js, class.photon.php, tests/php/test_class.jetpack_photon.php
Closes #14253
*
n/a
n/a
* Unit testing (Photon suite).
* Connect Jetpack + enable image CDN.
* Try different content -- adding images, adding galleries in the classic editor. Confirm Photon images.
* Activate no intermediate images mode ( `add_filter( 'jetpack_photon_noresize_mode', '__return_true' );` and confirm no intermediate images are added to the file system when uploading new files.
* If any, PHPCS: Bring additional code up to current WordPress Coding Standards.
=> Photon: PHPCS class.photon.php

_inc/client/at-a-glance/connections.jsx
See https://github.com/Automattic/jetpack/pull/16338#pullrequestreview-456156048
* N/A
* N/A
* Spin up a new JN
* In Settings > Jetpack Constants, enable dev mode
* go to Jetpack > Dashboard
* Scroll down and ensure the string is now correct.
* N/A
=> Admin Page: fix remaining mention of Development mode

changelog.txt, readme.txt, to-test.md
* Changelog
* N/A 
* N/A 
* N/A
=> 8.8 Release: Changelog

_inc/client/lib/analytics/README.md
Adds reference for the dops:anayltics (wp-admin) tracks logging command.
Fixes no reference to logging events in wp-admin
Adds reference to logging events in wp-admin.
N/a
No
Read it!
Typos? 
N/a
=> Update analytics readme

extensions/shared/register-jetpack-block.js
Fixes https://github.com/Automattic/jetpack/issues/16631
* Removes `paid` wording from premium blocks
* Apply these changes in your sandbox
* Test in a Simple site with a Free Plan
* Check that the following blocks do not have the `paid` wording
* Removes `paid` wording from premium blocks
=> Paid blocks: remove paid wording

docs/testing/regression-checklist/mapping.json, extensions/blocks/checklist.md
* This should add a checklist when changes are made inside the /blocks directory
An alternative approach to https://github.com/Automattic/jetpack/pull/16617.
No
* Not sure
* Add a regression checklist for blocks
=> Add a regression checklist for all blocks

package.json, yarn.lock
Closes #16644
* use yarn resolutions to update vulnerable packages in npm dependency tree.
n/a
n/a
* Before applying this patch run `yarn audit`
* See a bunch of `High` severity issues
* Apply patch and run `yarn audit` once again
* See only 1 `High` issue left
*n/a
=> Janitorial: Update vulnerable NPM packages

jetpack.php, package.json
* Update versions to start 8.9 Release cycle
* N/A
* N/A
* N/A
=> Update versions to start 8.9 Release cycle

.travis.yml
* Allow E2E CI job to fail the builds
n/a
n/a
* Make sure E2E jobs in CI are green
* Check that "E2E tests" job not in "Allowed Failures" 
* n/a
=> E2E tests: fail E2E CI job

changelog.txt, readme.txt
* Changelog for this release.
* N/A
* N/A
* This is it.
=> 8.8.1: a changelog

docker/README.md, docker/docker-compose.yml
Alternative approach to #16761
* Adds phpmyadmin to the docker build.
n/a
n/a
* yarn docker:up
* Visit localhost:8181
* n/a
=> Docker: Add phpmyadmin to the docker-composer.yml

_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php, extensions/shared/external-media/editor.scss, extensions/shared/external-media/sources/google-photos/google-photos-account.js, extensions/shared/external-media/sources/google-photos/google-photos-disconnect.js, extensions/shared/external-media/sources/google-photos/google-photos-media.js, extensions/shared/external-media/sources/with-media.js
Fixes #16560
* Adds an `account` property to media state
* Expands the modal header with account information and an account disconnect button for Google Photos
* Adds an endpoint to the external media API that deletes a connection (limited to Google Photos).
Yes, tracks the service that is being disconnected.
* Apply D47813-code to your sandbox
* Sandbox public-api
* In the Editor, insert an image block and select Google Photos
* Connect to your Google Photos account.
* The account information should appear at the top right corner.
* Click on the disconnect button.
* After successful removal of the connection you should be redirected to the authentication screen.
* External Media: Added a way to disconnect Google Photos accounts from within the media modal.
Mobile:
Dektop:
=> External Media: Add account disconnect button

_inc/lib/class.core-rest-api-endpoints.php
Depends on #16820, built on top of #16713.
* Trigger new action when activating a plugin via the plugins endpoint too.
* This is a bit annoying because I had to add a new optional request parameter to the endpoints so we can pass the source of the request. That makes us diverge from the Core implementation, so it would make deprecating our endpoints once WP 5.5 is the minimum required version a bit more difficult. I could not think of a better alternative though.
* Internal reference: pbtFPC-H5-p2
* No
* Nothing should change here, not much to test. Once all PRs are merged, this should give us results similar to #16820. 
* N/A
=> Plugins: add hook triggered when a plugin is successfully installed.

extensions/blocks/donations/common.scss, extensions/blocks/donations/donations.php, extensions/blocks/donations/editor.scss, extensions/blocks/donations/save.js, extensions/blocks/donations/tab.js, extensions/blocks/donations/view.js, extensions/blocks/donations/view.scss, extensions/blocks/recurring-payments/view.js, extensions/blocks/recurring-payments/view.scss, extensions/shared/memberships.js, extensions/shared/memberships.scss
Fixes https://github.com/Automattic/wp-calypso/issues/44108
Connect the donations block with the existing memberships functionality, so once a visitor chooses a donation amount and click on the donate button we display the subscribe dialog to process the payment.
pbMlHh-dW-p2
No.
* [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=update/donations-show-payment-dialog). 
* Activate `JETPACK_BETA_BLOCKS`. 
* Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address (make sure you enter the short URL e.g. mysandbox.wordpress.com to avoid issues with the SSL certificate).
* Sandbox the API, the store and `subscribe.wordpress.com` (see PCYsg-lW4-p2 #sandbox-method for …
=> Donations: Process payment after choosing an amount

package.json
* Add yarn resolution for `serialize-javascript`
n/a
n/a
* Nothing to test actually
* run `yarn audit` and make sure there is no `high` vulnerability
* n/a
=> Security: Add resolution for `serialize-javascript`

_inc/lib/core-api/wpcom-endpoints/memberships.php, extensions/blocks/donations/controls.js, extensions/blocks/donations/edit.js, extensions/blocks/donations/tabs.js
* This pull request fixes behavior in the donation block wherein the selected plan was not being updated when the user changed the currency in the edit view.
N/A
No
* Create a JN site running this branch.
* Activate `JETPACK_BETA_BLOCKS`.
* Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address (make sure you enter the short URL e.g. `mysandbox.wordpress.com` to avoid issues with the SSL certificate).
* Sandbox the API, the store and subscribe.wordpress.com (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Go to Posts > New and insert a new Donations block.
* Set up the Stripe connection (you will be able to see a link above …
=> Donations: Update plans when currency changes

3rd-party/creative-mail.php
* Let's change it from uppercase lowercase.
* Internal reference: pbtFPC-H5-p2
* No
* N/A
=> Creative Mail: update option to lowercase

extensions/index.json
Moves-p2 the Donations block from the beta build to the production build.
All blockers reported in the internal CfT (p58i-9k2-p2) have been solved, although we still work on a few minor issues that we'd like to fix before 8.9 is out.
p58i-9k2-p2
No.
* [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=update/donations-stripe-redirect-editor). 
* Go to Posts > New.
* Make sure the Donations block shows up in the block inserter.
Add a new Donations block for collecting one-time, monthly, or annually recurring donations.
=> Move Donations block to production build

extensions/blocks/contact-form/edit.js
* add a missing textdomain that slipped through somehow.
* N/A
* N/A
* N/A
=> Form Block: add missing textdomain

extensions/blocks/contact-form/components/jetpack-newsletter-integration-settings.js
https://github.com/Automattic/jetpack/pull/16713/files
N/A (only using the new API's)
* adopt the new management API
N/A
No
* Search for ‘Newsletter Sign-up’.
* Select the form block in the Gutenberg editor.
* collapse the "Newsletter Integration" on the right side
* Click install plugin
* click open creative mail, this should open the creative mail plugin in a new tab.
* make sure that the Creative Mail plugin is *installed but deactivated*
* Search for ‘Newsletter Sign-up’.
* Select the form block in the Gutenberg editor.
* collapse the "Newsletter Integration" on the right side
* click active plugin
* click open creative mail, this should open the creative mail plugin in a new tab.
* make sure that you break your WP instance, (no write …
=> Contact From: Use the new plugin management api for the newsletter

changelog.txt, readme.txt, to-test.md
* Changelog for the 8.9 release
* N/A
* N/A
* This is it.
=> Changelog: initial change for 8.9 release

extensions/README.md
This PR updates the Jetpack extensions documentation to include information on the fallback pattern used for extensions which are gated by plan but which need to provide a fallback experience (eg: an upgrade nudge).
This is as per the Social Previews extension and was requested by @jeherve in p1596637160315500-slack-CJS75TX3R.
Fixes https://github.com/Automattic/jetpack/issues/16728
* Documentation upgrade.
No.
* Read updates to README.
* Check for grammatical and spelling errors.
* Check for comprehension - can you understand the concepts the new documentation refers to?
* Update the Jetpack extensions documentation to include information on the fallback pattern used for extensions which are gated by plan but which need to provide a fallback experience (eg: an upgrade nudge).
=> Document the fallback pattern for Jetpack sidebar extensions

jetpack.php, package.json, readme.txt
* Update version numbers to start 9.9 cycle
* N/A
* N/A
* N/A
=> Update version numbers to start 9.9 cycle

tools/jetpack-live-branches/jetpack-live-branches.user.js
As we work towards full compatibility between the 2 plugins, it would be nice to be able to launch test sites with AMP installed out of the box.
* N/A
* N/A
* Replace your version of the Userscript with this one.
* See the new entry in the plugin list.
* N/A
=> Live Branches Tool: add AMP plugin

packages/blocks/.gitattributes, packages/blocks/.gitignore, packages/blocks/README.md, packages/blocks/composer.json, packages/blocks/phpunit.xml.dist, packages/blocks/src/class-blocks.php
See #17099
* This PR introduces the scaffolding for a new package, that both the Jetpack plugin and standalone blocks could rely on from now on.
* p9dueE-1BH-p2
* No
* Not much to test yet since the package is not used for anything just yet.
* N/A
=> Blocks: introduce new package for block management

.github/codeclimate-base.yml
* We haven't updated our CodeClimate configuration in a while. It's now time to refresh things a bit, mostly by making sure we do not use any deprecated config flags, and that we use the currently supported version of the configuration tool.
* Related: p9dueE-1R7-p2
* No
* Check the CodeClimate tests below this PR; it shouldn't return any errors.
* N/A
=> CodeClimate: update rules with newer version

_inc/client/components/settings-card/index.jsx, _inc/client/my-plan/my-plan-body.jsx, _inc/client/performance/media.jsx, _inc/client/state/site/reducer.js, _inc/client/traffic/seo.jsx, class.jetpack-plan.php, modules/google-analytics.php, modules/search.php, modules/seo-tools.php, modules/vaultpress.php, modules/videopress.php, modules/wordads.php, tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/pages/postFrontend.js, tests/e2e/lib/pages/wp-admin/jetpack.js, tests/e2e/lib/pages/wpcom/checkout.js, tests/e2e/lib/pages/wpcom/pick-a-plan.js, tests/e2e/lib/plan-helper.js, tests/e2e/specs/pro-blocks.test.js
With new plans we need to update E2E tests to support them
n/a
n/a
* CI should be green
*
* n/a
=> E2E Tests: Update to support new plans

readme.txt
* Changelog for the 8.9.1 release.
* N/A
* N/A
* This is it.
=> 8.9.1: add changelog

.travis.yml
This needs to be done following the change in #14274, so the version used in the CodeClimate test matches the version expected for the build.
* N/A
* No
* Can the CodeClimate Code Coverage run (check https://travis-ci.com/github/Automattic/jetpack/jobs/385128426 )
* N/A
=> CodeClimate test: update node version

packages/a8c-mc-stats/.gitattributes
Removes the testing files from the distribution.
* Removes the testing files from the distribution.
* n/a
* In another project that uses this plugin, run `composer update --no-dev --prefer-dist` and ensure the tests folder is not included.
* n/a
=> a8c-mc-stats: Do not distribute test files

package.json, yarn.lock
* add yarn resolutions to vulnerable dependencies
n/a
n/a
* Not needed. No major version updates for production dependencies
* n/a
=> Build: Update vulnerable dependencies

yarn.lock
Some yarn.lock changes got lost and weren't committed. This PR updates that.
n/a
n/a
* Run `yarn` on master. see new changes in `yarn.lock
* Apply this patch. run `yarn`, note that there is not outstanding changes anymore.
* n/a
=> Build: Update yarn.lock

packages/connection/.gitattributes, packages/terms-of-service/.gitattributes, packages/tracking/.gitattributes
* Do not ship test files in Tracking and Terms of Service packages
* Do not ship docs in Connection packages.
This may help us unblock D49766-code
* N/A
* N/A
* Not much should change, since we don't need those things in production.
* N/A
=> Packages: update list of files distributed in production packages

docs/testing/regression-checklist/test-suites/packages/connection.md
* When testing changes to the connection package, we should verify that the changes are compatible with the consumer plugins.
* n/a
* no
* n/a - This is a documentation change.
* n/a
=> Connection Regression Checklist: add plugins

changelog.txt, readme.txt, to-test.md
* Changelog for Jetpack 9.0
* N/A
* N/A
* N/A
=> Add initial changelog for Jetpack 9.0

_inc/client/security/antispam.jsx
* use "Anti-spam" instead of "Antispam"
* Reported in p8oabR-y3-p2#comment-4574
* See p1HpG7-7Ro-p2
* No
* Not much to test here, it's just a string change.
* N/A
=> Admin Page: use "Anti-spam" instead of "Antispam"

_inc/client/at-a-glance/monitor.jsx, _inc/client/security/monitor.jsx, _inc/client/security/protect.jsx, _inc/client/traffic/site-stats.jsx, modules/module-headings.php, modules/monitor.php
* See p8oabR-y3-p2#comment-4570
* N/A
* No
* Not much to check here, it's just a string change.
* N/A
=> Admin Page: remove unneeded commas

.github/workflows/required-review.yml
As part of p9dueE-1T9-p2, we are updating the GitHub team for the reuired review to the "Jetpack Approvers" team.
* Update team from Crew to Approvers
p9dueE-1T9-p2
n/a
* I'm not sure we can test it in PR form or if it has to be merged. Basically, ensure that any of us can still approve a PR.
* n/a
=> Required Review: Update team to Approvers

composer.lock
This will allow us to ship less unnecessary files in the stable version of Jetpack.
See https://github.com/nojimage/twitter-text-php/pull/35
* N/A
* N/A
* Nothing should change with existing features, but you can check Publicize to Threads to be sure.
* N/A
=> Publicize: update Twitter Text dependency

.github/workflows/codeql-analysis.yml
GitHub now offers a CodeQL Code Scanning Analysis action:
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning
This allows you to automatically scan your code (only JavaScript in this commit so far) for vulnerabilities.
This commit creates an action that will be triggered for new commits to `master` and `master-built` only, and notify us of any issues it may find.
This new file was generated using GitHub's guide. I only modified on what branches and when the action would run.
* N/A 
* N/A 
* Not much to test so far, this will only run on `master` so we cannot test it in this PR.
* N/A
=> Actions: add code scanning analysis

.travis.yml, package.json
As directed by @fgiannar in https://github.com/Automattic/jetpack/pull/17234#issuecomment-700567794, this PR adds the Jetpack Instant Search test suite `yarn test-search` to the CI build in `yarn test-dangerci-and-adminpage-and-extensions`.
No.
Check that the build tests pass on this PR, and that `yarn test-search` is included.
Not required.
=> Instant Search: add test suite to CI

_inc/client/my-plan/my-plan-body.jsx
This is a bad link and also no longer relevant for the new plans.
N/A
Remove simple upgrade card on My Plan section
Part of the offer reset
No
* Pull down this PR
* Visit the My Plan page and ensure card is no longer visible
* N/A
=> Remove free plan upgrade on My Plan page 

SECURITY.md
[GitHub will highlight](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) a SECURITY.md file when new issues are created to help notify folks of where to report security issues.
This initial form was borrowed and modified from WordPress' SECURITY.md file. Since our policy is on HackerOne, generally, the policy will direct folks to there to avoid having duplicative information in multiple locations.
* Adds a security policy.
n/a
No.
None.
* None needed.
=> General: Add a security policy

modules/latex.php
Fixes #17347
* Adds a cache buster to the LaTeX URL and modernizes the string creation.
Syncs r214588-wpcom to Jetpack
n/a
* Enable Beautiful Math
* Add LaTeX to a post. Does it render?
* Beautiful Math: resolves edge caching issue where the cache may have saved some faulty rendered images.
=> Beautiful Math: Add cachebuster to LaTeX rendering

readme.txt
* Updated plugin description
* pbNhbs-eE-p2
* No
* Please check for any spelling, grammar, or technical errors. 
* Double check the formatting is correct and presents correctly in context in the plugin and on WP.org.
* N/A
=> General: update readme.txt

changelog.txt, readme.txt
* Changelog updates
* N/A
* No
* This is it.
=> Changelog: updates to cover changes made during the Beta period

jetpack.php, package.json
* Update version numbers to start release cycle
* N/A
* N/A
* N/A
* N/A
=> 9.1 Release: start release cycle with updated version numbers

changelog.txt, readme.txt
* Bring 9.0.1 changelog to `master`
**Note**: this has already been cherry-picked to the `branch-9.0` branch.
* N/A
* N/A
* This is it.
=> Jetpack 9.0.1: add changelog

json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
Fixes #17412
* Since `get_upload_space_available` is not available in non multisites run space check only in multisites (eg simple sites)
We should test two cases, Atomic & Simple Sites
**Before Applying this patch**
* Launch an ephemeral site
* Connect jetpack to wpcom
* Go to `https://wordpress.com/media/`
* Try adding an image via URL
* You should get an error
**After Applying this patch to your ephemeral site via ssh**
* Go to `https://wordpress.com/media/`
* Try adding an image via URL
* Media should be uploaded as expected
**On wpcom simple sites**
* Apply D50839-code
* Go to `https://wordpress.com/media/` of a simple site
* Try adding an image via URL
* Media should be uploaded as expected
* Uploading media from URL fix
=> Fix external media url uploads on atomic

tests/php/json-api/test-class.json-api-jetpack-endpoints-accessibility.php, tests/php/json-api/test-class.json-api-jetpack-endpoints.php
Reorganize json-api unit tests
* Not much, just re-organizing existing unit tests
no
n/a
Changelog not needed as we are only reorganizing json-api related unit tests
=> REST API tests: Reorganize json-api unit tests

readme.txt
* Changelog for the next point release.
* N/A 
* N/A 
* This is it.
=> 9.0.2: Changelog

.travis.yml
Disable sending slack notifications for failed builds for PRs 
n/a
n/a
* Nothing to test here, unfortunately 
*n/a
=> Travis: Slack notifications only for master builds

class.jetpack-heartbeat.php, class.json-api-endpoints.php, modules/custom-css/csstidy/class.csstidy_optimise.php, modules/custom-css/custom-css/preprocessors/lessc.inc.php, modules/shortcodes/presentations.php, modules/widgets/simple-payments.php, packages/sync/src/class-functions.php, packages/sync/src/class-queue.php
See #17432
* Replaced floatval() with type cast (float) as part of issue #17432.
* Go to '..'
*
* Replaced floatval() with type cast (float) as part of issue #17432.
=> Replaced floatval() with type cast (float) as part of issue #17432.

class.json-api-endpoints.php, modules/contact-form/grunion-contact-form.php, modules/protect.php, packages/connection/src/class-manager.php, packages/sync/src/class-functions.php, tests/php/modules/contact-form/test-class.grunion-contact-form.php
See #17432
* Replaced strval() with type casting (string) as part of issue #17432.
* Go to '..'
*
* Replaced strval() with type casting (string) as part of issue #17432.
=> Replaced strval() with type casting (string) as part of issue #17432.

modules/protect/shared-functions.php, phpunit.xml.dist, tests/php/modules/protect/test-shared-functions.php
Fixes #17566
* Correctly remove the ports from input IPs, instead of trying to misuse `parse_url`.
* Validate that the cleaned IP is valid.
* Add tests.
#17566
It might correct tracking when IPv6 addresses are involved. It doesn't add anything new.
Based on https://wordpress.org/support/topic/truncated-log-of-ipv6-login-error/:
* Attempt a failed login via IPv6.
* Check that the log correctly includes the IPv6 address.
Another possibility:
* Configure Protect with some dummy header as the trusted IP header.
* Make requests that Protect will log with said dummy header set to `[2001:DB8::3]:80`
* Check that the logged IP is `2001:DB8::3`.
* "Protect: Fix handling of IPv6 addresses."
=> Protect: Fix IPv6 handling in `jetpack_clean_ip`

modules/infinite-scroll/infinity.php, tests/php/modules/infinite-scroll/test_class.infinite-scroll.php, tests/php/test_class.jetpack_photon.php
p3btAN-1io-p2
p3btAN-1io-p2
No
p3btAN-1io-p2
* n/a :: Minor enhancement in Infinite Scroll module
=> Infinite Scroll: Update posts_per_page setting

modules/widgets/class-jetpack-instagram-widget.php
This syncs changes from WPCOM back to Jetpack so that we can add the files to Fusion
There should be no functional changes.
=> Instagram Widget: Fix linting issues from WPCOM

changelog.txt, readme.txt, to-test.md
* Changelog for the next release.
* N/A
* N/A
* This is it.
=> Changelog: 9.1 changelog

3rd-party/class.jetpack-amp-support.php, class.jetpack-twitter-cards.php, class.photon.php, tests/php/_inc/lib/test-class.jetpack-tweetstorm-helper.php, tests/php/general/test-class.jetpack-network.php, tests/php/test_class.jetpack_photon.php
After #17406, updated the "requiredlist" files to match new PHPCS rules for packages and the debugger.
* PHPCS
n/a
n/a
n/a
* n/a
=> Updated PHPCS: AMP, Tests, etc

_inc/client/components/support-card/index.jsx
Fixes #17194
Clarifies the language regarding support.
* Updates AAG card language since free support is handled via the forums.
This does not change the URL. Since we're using the Redirect system, we can conditionally route that on the WP.com side.
n/a
n/a
* Go to Jetpack->Dashboard->scroll down to the support card near the bottom.
*
* Admin Page: improve language.
=> Admin Page: Improve language for unpaid sites re Support offering

yarn.lock
Follow-up from #17707
* N/A
* No
* Does it build?
* N/A
=> Build: update lock file

modules/widget-visibility/widget-conditions.php
* Those spaces are stopping us from committing the changes to WordPress.com in D50845-code (pre-commit hook issues).
* N/A
* No
* Not much to test here. 
* N/A
=> Widget conditions: fix indentation issues introduced in #17434

modules/sitemaps/sitemap-builder.php
Fixes #17722
* Includes a trailing slash on the home url in the sitemaps
No.
* Apply PR
* Regenerate Sitemaps
* Verify home url is slashed.
Untested.
* Ensure that the home url is slashed when on a subdirectory site.
=> Sitemaps: Include a trailing slash on the home url.

changelog.txt, readme.txt
* update with latest changes
* N/A
* N/A
* This is it.
=> Changelog: update with latest changes

docs/coding-guidelines.md
* Fix the sanitize link in the coding standards document.
* n/a
* no
* Verify that the new URL is correct.
* n/a
=> Docs: Fix the sanitize link in the coding standards document.

jetpack.php, package.json
* Let's get 9.2 started!
* N/A
* No 
* N/A
=> Update version numbers to start 9.2 release cycle

changelog.txt, modules/contact-form/admin.php, modules/contact-form/js/grunion-admin.js, readme.txt
**Note**: these changes are already part of 9.1
* Contact Form: add check for Feedback spam process request
Add additional checks before checking submitted forms for spam.
Internal references:
- D51216-code
- p3btAN-1iA-p2
* No
* See D51216-code
* Already in changelog
=> Contact Form: bring changes from release branch to master

packages/status/tests/php/test-status.php
Fielded a question about what the regex would catch or not, so added a couple instances to the array for us to catch it in the future.
* Adds a couple of test cases.
* Removes a redundant test.
n/a
n/a
* `yarn docker:phpunit:package status`
* Ensure everything passes.
* n/a
=> Status: Add a couple of test cases for staging site detection

.github/codeclimate-base.yml, .github/files/phpcompatibility-dev-phpcs.xml, .github/matchers/phpcs-problem-matcher.json, .github/workflows/phpcompatibility-dev.yml, .phpcs.config.xml, .phpcs.xml.dist, _inc/lib/class.core-rest-api-endpoints.php, _inc/lib/class.media.php, _inc/lib/debugger/class-jetpack-cxn-test-base.php, class.jetpack-gutenberg.php, class.jetpack-modules-list-table.php, class.jetpack-post-images.php, class.json-api-endpoints.php, composer.json, dangerfile.js, modules/contact-form/grunion-contact-form.php, modules/widgets/rsslinks-widget.php, packages/device-detection/src/class-device-detection.php, tests/php/general/test_class.jetpack-xmlrpc-server.php, tests/php/general/test_class.jetpack.php, tests/php/lib/class-wp-test-jetpack-rest-testcase.php, tests/php/modules/sso/test_class.jetpack-sso-helpers.php, tests/php/sync/test_class.jetpack-sync-callables.php, tests/php/sync/test_class.jetpack-sync-integration.php
Fix PHP 8 issues detected by the development version of [PHPCompatibility](https://packagist.org/packages/phpcompatibility/php-compatibility), then add a (temporary) Github Action to run it against future pull requests.
This also refactors the phpcs config to separate out the specification of paths and the specification of rules (because the PHPCompatibility run needs the former but not the latter), and adjusts the `composer php:compatibility` script to also make use of the separated specification of paths rather than using its own exclude list. And then it fixes compatibility in some files that had been falling through the cracks, and 1000 (hyperbole) other failures that phpcs then whines about since the files are being touched.
See #17166.
No.
* See that the new Github Action runs and …
=> Improve PHP 8 compatibility

tests/php/test_class.jetpack_photon.php
* Fixes a typo in the @/covers docblock for a test.
n/a
n/a
* n/a
* n/a
=> Unit Tests: Fix typo in docblock

docs/coding-guidelines.md
Updates some docs.
I'll leave it up to someone else to decide just how much detail we want
to go into about those "some additions", and whether we want to document
them here or in packages/codesniffer/README.md or the like.
p7H4VZ-2Ml-p2#comment-8992
No.
* Proofread the doc.
* Developer only, none needed.
=> Docs: Update coding-guidelines.md to point to the Jetpack PHPCS standard

modules/masterbar/masterbar/masterbar.php
See #17781.
* Removes class include.
* Enable the masterbar module and make sure nothing crashes.
* None needed.
=> Masterbar: Remove Admin Bar include

bin/pre-commit-hook.js
* Add `tests/e2e` to the list of files to lint
* Update some docs
n/a
n/a
* Make any change in a E2E files that would raise a lint error. For example add an unused import 
* run `node ./bin/pre-commit-hook.js`
* Confirm that the error is raised
* n/a
=> Pre-commit: Lint E2E tests files

tests/e2e/lib/pages/wpcom/pick-a-plan.js
* Update free button plan locator
* (Manually) set up Mailchimp connection for the test user
n/a 
n/a 
* Check E2E Actions, make sure they all green
* Run connection test locally `yarn test-e2e tests/e2e/specs/connection.test.js` (make sure to setup env first)
* n/a
=> E2E Tests: Fix tests

.github/PULL_REQUEST_TEMPLATE.md, docs/writing-a-good-changelog-entry.md
Our PR template has a section for "suggested changelog entry", but gives
no guidance on what that entry should look like. Let's fix that.
None.
No.
* I guess create a PR based on this PR, and see if it picks up the changed template? Or does this have to actually be merged first?
* Developer only, none needed.
=> Docs: Document "suggested changelog entry"

tools/deploy-to-svn.sh
Multiple passes are needed because removing an empty directory may make
its parent empty. So keep trying until a pass doesn't find anything to
remove.
p1606214416135800-slack-CBG1CP4EN
No.
* Run the script.
* See if any empty directories are included in `/tmp/jetpack/trunk`.
* None needed.
=> Tools: Fix empty dir removal in tools/deploy-to-svn.sh

bin/phpcs-requirelist.js, json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
I've experienced some issues when trying to commit some changes to that file in #17820.
This should avoid any further issues.
* N/A
No
* Try to fetch and update site settings via the API, for example using https://developer.wordpress.com/api/console
* N/A
=> fix (wpcom api): fix linting errors in Settings endpoint

packages/connection/docs/error-handling.md
Fix typos in the docs and adds a small new section
N/a
no
* Read it :) 
* not needed
=> fix typos and add section to error handling docs

tests/e2e/README.md, tests/e2e/lib/flows/jetpack-connect.js, tests/e2e/lib/pages/wp-admin/block-editor.js, tests/e2e/lib/pages/wp-admin/dashboard.js, tests/e2e/lib/plan-helper.js, tests/e2e/lib/utils-helper.js, tests/e2e/specs/plugin-updater.test.js
* Clean up E2E docs 
* rename `getNgrokSiteUrl` method
n/a
n/a
* Check the code
* Check the docs
* n/a
=> E2E Tests: Remove Ngrok references

jetpack.php, package.json
* Start the 9.3 release cycle.
* N/A
* No
* N/A
=> General: update version numbers to start 9.3 release cycle

docs/git-workflow.md
Updates the documentation regarding branch naming conventions to match our current practices, specifically adding `branch-` and `feature/`.
* Updates docs to match current practices.
n/a
n/a
* n/a
* n/a
=> Docs: Include reserved branches in naming convention

packages/abtest/.gitattributes
The .gitignore file for the abtest package is being shipped with the dist variant via Packagist.
* Adds .gitignore to .gitattributes for export-ignore.
n/a
n/a
* Not sure really how to do it pre-merge.
* n/a
=> AB Test: Add .gitignore to export-ignore

.github/workflows/js-tests.yml
/usr/bin/composer is not writable.
If we really need to use the latest version of composer, we'll need to
download the phar. For now, though, let's just use the installed version
(2.0.7 at the moment, but Github may well update soon).
p1607028809021000-slack-CBG1CP4EN
No.
* See if the JS Tests workflow passes on this patch.
* None needed.
=> JS Tests: Don't try to self-update /usr/bin/composer

composer.json
Passes `-s` to phpcs-changed when run from composer.json.
We generally want the codes.
None.
No.
* Introduce a PHPCS error in a file. Don't commit.
* Run `composer phpcs-changed {file}`. See if codes are included in the output.
* None needed.
=> Composer: Pass -s to phpcs-changed

.github/workflows/code-coverage.yml, codecov.yml, packages/abtest/phpunit.xml.dist, tests/process-coverage.sh, tests/run-travis.sh
* Add codecov coverage
* exclude `wordpress` folder from coverage report
n/a
n/a
* Go to https://codecov.io/gh/Automattic/jetpack/pull/17960
* click around :) 
* n/a
=> Tests:  Try CodeCov coverage app

packages/autoloader/README.md
Fixes #
* Removed unwanted dot
* Updated readme file
=> Removed unwanted dot

.github/workflows/dangerci.yml, .github/workflows/js-tests.yml, package.json
DangerJS [doesn't recommend it](https://github.com/danger/danger-js/issues/1060), but since we're only checking the PR metadata it may work for us.
Even if it doesn't wind up working, we can still win by not having DangerJS failures block a merge from forked repos.
p1607360394119300-slack-CBG1CP4EN
No.
* Note this PR won't have DangerJS run at all.
* See if DangerJS runs correctly in #18002.
* None needed.
=> CI: Use pull_request_target for DangerJS

sal/class.json-api-site-base.php
Quick PR to add docblock into #18007, but doing as a separate PR for the sake of Fusion since 18007 is a Fusion PR itself.
=> SAL: Add P2 organization identifier

.github/workflows/code-coverage.yml, .github/workflows/js-tests.yml, .github/workflows/phpunit.yml
* Trigger some builds on push to master
* Skip actions if relevant files haven't changed
n/a
n/a
* Not much to test here, unfortunately.
* Once merged, it should trigger coverage, js and PHP tests on master branch
* n/a
=> GH Actions: Updates event triggers for some of the actions

.github/workflows/php-linting.yml
While phpcs-changed sort-of works on a shallow clone with only the two
endpoint revs fetched, it doesn't work correctly.
What it needs is to work correctly is every commit between the two
endpoints, i.e. such that `git merge-base` works. So let's fetch commits
until it does.
p1607440318171700-slack-CBG1CP4EN
No.
* Base a PR like #18007 on this, and see that the phpcs-changed job reports only the expected changes.
* None needed.
=> CI: Fix phpcs-changed

sal/class.json-api-site-base.php
=> SAL: One more PHPCS update

codecov.yml
* Add coverage threshold, which would fail CodeCov check if coverage decreased > 3%
* ignore `tests` folder
n/a
n/a
* 🤷 
* n/a
=> Coverage: Add coverage threshold

bin/phpcs-excludelist.txt, tests/php/modules/contact-form/test-class.grunion-contact-form.php
* There are so many PHPCS issues in this file that the maximum number of errors is reached before the end of the file. Let's clean up the PHPCS issues so we can see new PHPCS issues in our IDEs when we add new tests to the end of the file.
* n/a
* no
* Verify that the unit tests have passed.
* n/a
=> Contact Form Tests: fix phpcs issues

codecov.yml
* Disable github annotations
* decrease threshold down to 3%
p1607505343211700-slack-CBG1CP4EN
n/a
* Since annotations would appear only for a PRs that adds new code, there is no easy way to test this.
* Maybe check the docs, and see if I missed something: https://docs.codecov.io/docs/github-checks-beta
* n/a
=> CodeCov: Disable GitHub annotations

tests/e2e/jest-puppeteer.config.js
Fixes #17870
* Add check for a Mac OS and Chrome when running tests locally
n/a
n/a
* Test on MacOS without Chrome 😬 
* Make sure code make sense
* n/a
=> E2E Tests: Check if Chrome installed locally

composer.lock, docker/config/wp-tests-config.php, docker/mu-plugins/avoid-plugin-deletion.php, modules/publicize.php, packages/analyzer/data/example-external.php, packages/codesniffer/composer.json, packages/codesniffer/tests/php/bootstrap.php, packages/device-detection/src/class-user-agent-info.php
They've released v34 with PHP 8 support, plus dev-master now has breaking changes.
None.
No.
* See that tests still pass. Particularly the package's `composer phpunit` under PHP 8.
* None needed.
=> Codesniffer: Update mediawiki/mediawiki-codesniffer dependency

.gitignore
Updates .gitignore to ignore a few more things:
* PHPUnit 9 leaves .phpunit.result.cache behind.
* The E2E test runner creates an /allure-results/ folder.
None
No
* See that `git status` ignores these things, and doesn't ignore anything it's not supposed to.
* None needed.
=> Gitignore: Add some test runner leftovers

changelog.txt, readme.txt
* Changelog for the upcoming release
* N/A
* No
* This is it.
=> Changelog: add 9.2.1 changelog

extensions/blocks/anchor-fm/editor.js
This PR set the post title when users come from anchor.fm to wp.com in the creating a new post flow.
* Anchor.fm set post title for new blog post with track title
no
* Apply these changes. If you'd like to test in dotcom:
- apply the patch
- get sandboxed 
* Create a new post passing the anchor data in the query string. You can use this in your local env.
```
http://localhost/wp-admin/post-new.php?action=edit&anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spotify_show_url=https%3A%2F%2Fopen.spotify.com%2Fshow%2F6HTZdaDHjqXKDE4acYffoD%3Fsi%3DEVfDYETjQCu7pasVG5D73Q
```
* You should get the post title from the podcast track
* * Anchor.fm set post title for new blog post with track title
=> Anchor.fm set post title for new blog post with track title

.github/workflows/dangerci.yml
GitHub doesn't like us checking out the current branch for running
DangerCI.
Note that will make it difficult to test changes to the DangerCI setup,
as it'll run the old version rather than the new. That's probably ok.
p1607701056340500-slack-CBG1CP4EN
No.
* None.
* None needed.
=> CI: Fix DangerCI workflow

modules/masterbar/admin-menu/admin-menu.css
This is a follow-up to @cpapazoglou's comment here:
> I suggest merging it and iterating more on:
>
> * Mobile menu open / close
> * Site Switcher menu item missing
—https://github.com/Automattic/jetpack/pull/17629#pullrequestreview-529090182
* Sync CSS changes from wpcom proptype
No
* Go to '..'
*
* None needed.
=> Admin Menu: Sync styles from prototype

.gitignore
* Clean up from the initial move re the paths in gitignore for the docker files.
n/a
n/a
* n/a
* n/a
=> Reorg: Fix .gitignore docker.

.github/workflows/code-coverage.yml, packages/a8c-mc-stats/phpunit.xml.dist, packages/abtest/phpunit.xml.dist, phpunit.xml.dist, tests/php.multisite.xml
* Update coverage excludes to include more affected files in the report 
n/a
n/a
* Go to https://codecov.io/gh/Automattic/jetpack/pull/18052 and compare that more files are included
* Go through the files, and see if some files are missing
* n/a
=> Coverage Update whitelist for backend tests

.github/actions/deepen-to-merge-base/action.yml, .github/workflows/js-tests.yml, .github/workflows/php-linting.yml
We're now using it in two places. So let's move the code to an action and reference it that way instead.
None.
No.
* Is CI still running successfully? Check the relevant jobs' logs.
* None needed.
=> CI: Make a GitHub Action for the "deepen to merge base" step

packages/autoloader/src/class-path-processor.php, packages/autoloader/tests/php/tests/integration/test-autoloader-scenarios.php, packages/autoloader/tests/php/tests/unit/test-path-processor.php
When working on updating the autoloader in WooCommerce I experienced infinite recursion on autoloader initialization. My investigation revealed that the problem is caused by `Plugin_Locator::find_current_plugin()` returning a different path than the one stored in the `active_plugins` option when using symbolic links. This is a result of us (unavoidably) using the `__DIR__` constant to identify the absolute path to the currently initializing plugin. 
Since this constant contains resolved symbolic links we need to ensure that _all_ paths in the autoloader resolve those same links. To that end this PR modifies the `Path_Processor` so that all outgoing paths are appropriately resolved. It's worth noting that this harms our tokenization attempts in cases where multiple servers share a cache …
=> Autoloader: Resolve symbolic links for plugin paths

.github/workflows/js-tests.yml
We're running the "JS Tests" workflow on both pull request and on push
to master. #18126 changed the lint job to only work right on PR, so only
run that on PR.
I note we don't run any of the other linting jobs on push to master, so
that seems reasonable.
None.
No.
* Does it run correctly here?
* Post-merge, does it correctly not try to run the job when running against the master push?
* None needed.
=> CI: Fix JS lint on push

.github/workflows/php-linting.yml, .github/workflows/phpunit.yml
These tests now pass and are required, so don't flag them as "experimental" anymore.
None.
No.
* Does CI still pass?
* None needed.
=> GH: PHP 8.0 is no longer experimental

extensions/blocks/dialogue/dialogue.php
_This PR is part of the [follow-up tasks](https://github.com/Automattic/jetpack/issues/18123) after merging `conversation`/`dialogue` blocks._
Fixes #
* Dialogue: allow line-breaks in front-end
* Create a dialogue block
* Add text. Create a line-break (CMD + ENTER in Mac)
* Save
* Confirm that the line-break is rendered properly in the front-end
before  | after
------|------
* Dialogue: allow line-breaks in front-end
=> Dialogue: allow line-breaks in front-end

.github/CODEOWNERS
Tooling.  Remove me from codeowners.  I'm totes pingable, but shouldn't be the default reviewer any longer.
=> Remove @georgestephanis from codeowners file.

readme.txt, to-test.md
* Changelog and testing list for the upcoming version of Jetpack.
* **As you update the changelog here, you can update the Project thread linked below.**
* p1HpG7-aG4-p2 
* No
* This is it.
=> 9.3 Release: changelog

composer.lock
* composer.lock needed to be updated following #18209, to avoid test failures.
* N/A
* N/A
* N/A
=> Composer: update following #18209

package.json, yarn.lock
I noticed that `yarn install` seemed to really like making this
nonsensical change to yarn.lock:
```diff
-minimist@0.0.8, minimist@^0.2.1:
+minimist@0.0.8, minimist@^0.2.1, minimist@^1.2.5:
version "0.2.1"
-minimist@^1.1.1, minimist@^1.1.3, minimist@^1.2.0, minimist@^1.2.5:
+minimist@^1.1.1, minimist@^1.1.3, minimist@^1.2.0:
version "1.2.5"
```
This turns out to be due to an override of "**/mkdirp/minimist" to
^0.2.1 in our package.json, which was happily overriding all the cases
where newer versions of mkdirp depend on minimist ^1.2.5.
It turns out that everything we have that's depending on mkdirp already
has a dependency that is compatible with said newer versions of mkdirp,
but yarn.lock had some of them still locked to an older mkdirp version.
Sigh.
So I ran `npx yarn-deduplicate …
=> yarn: Remove broken mkdirp/minimist override

.github/workflows/code-coverage.yml, .github/workflows/dangerci.yml, .github/workflows/e2e-tests.yml, .github/workflows/gardening.yml, .github/workflows/js-tests.yml, .github/workflows/linting.yml
It seems shivammathur/setup-php has started prepending `/usr/local/bin/`
to PATH. This broke our E2E tests, because GitHub's action runners seem
to have a `node` binary in `/usr/local/bin/` so this prepending overrode
the path entry added by actions/setup-node.
We can work around this by running actions/setup-node after
shivammathur/setup-php.
Also switch to actions/setup-node from @v1 to @v2, which claims to have
better caching behavior.
None.
No.
* Do the E2E tests run correctly now? If they fail, do they at least fail with the usual flakiness?
* None needed.
=> CI: Fix E2E tests

.github/workflows/code-coverage.yml
The codecov.io uploader reports
```
->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0
```
So increase the fetch depth to 2.
None.
No.
* Check the output of the "Process coverage results" step in the "Code coverage" job.
* None needed.
=> Codecov action: Increase fetch depth to 2

bin/pre-commit-hook.js
The missing `checkFailed()` call caused it to not indicate failure.
None.
No.
* Introduce an error or warning in a non-excluded file.
* Attempt to commit. It should stop you.
* None needed.
=> Pre-commit: Actually fail pre-commit if eslint fails

modules/masterbar/admin-menu/class-admin-menu.php, tests/php/modules/masterbar/test-class-admin-menu.php
Fixes #18235.
* Removes default header and background submenu items.
* Maintains toplevel menu item ID as JS/CSS selector.
* Escapes removal URLs so they match the registered URLs.
* Sets the correct parent file, so menu expands when submenu items are active.
No.
This is not easy to test because it requires a bit of a setup. 
* With nav-unification enabled, install & activate [the Singl theme](https://wordpress.org/themes/singl/). Easiest way is probably to go though the theme installer in wp-admin for that
* Navigate to `/wp-admin/themes.php` and make sure that there is only one instance of Header or Background menu items.
On wp.com:
* Apply D55017-code and D55018-code to your sandbox.
* With nav-unification enabled, activate the Singl theme on your test site.
* Navigate to …
=> Masterbar: Remove unwanted Appearance submenu items

jetpack.php, package.json
* Update version number to start the 9.4 cycle.
* N/A
* No
* N/A
=> General: update version numbers to start new release cycle

.github/files/check-excludelist-diff.js
The failure case in question is probably due to errors in maintaining proper sorting in the file, particularly if a PR first removes an entry then adds it back. Tell them that in the error.
I'd like to keep CI enforcing a consistent sort order on the file, as that will help to keep the file clean for future PRs.
Also, it seems [we can use `%0A` to provide multi-line output](https://github.com/actions/toolkit/issues/193#issuecomment-605394935), so do that too.
None.
No.
* Does CI pass?
* None needed.
=> CI: Provide better feedback for excludelist check failures

.svnignore
* Ensure that those files are not shipped with the production version of Jetpack.
* N/A
* No
* N/A
=> Build Script: update svnignore with recent additions

tests/php/general/test-class.jetpack-gutenberg.php
PHP fixed their [bug 77423](https://bugs.php.net/bug.php?id=77423) recently, which changed the behavior of
`parse_url()` when passed a URL with an invalid userinfo part. One of
our tests was relying on the old behavior.
The simplest fix seems to be to expect either the old or new behavior
here, as the URL in question is invalid anyway.
p1610553431468900-slack-CDLH4C1UZ
No.
* Do tests pass?
* None needed.
=> CI: Fix test broken by a PHP bugfix

projects/plugins/jetpack/package.json, projects/plugins/jetpack/yarn.lock
* Resolves a package.json change that was missed during a final merge from `master` before merging in the repo reorg work.
p1610661764139300-slack-CBG1CP4E
N
* `yarn lint-file projects/plugins/jetpack/_inc/client/components/auth-iframe `
* n/a
=> ESlint: Fix i18n relates issue

projects/packages/a8c-mc-stats/.gitattributes, projects/packages/abtest/.gitattributes, projects/packages/analyzer/.gitattributes, projects/packages/assets/.gitattributes, projects/packages/autoloader/.gitattributes, projects/packages/backup/.gitattributes, projects/packages/blocks/.gitattributes, projects/packages/codesniffer/.gitattributes, projects/packages/compat/.gitattributes, projects/packages/config/.gitattributes, projects/packages/connection/.gitattributes, projects/packages/constants/.gitattributes, projects/packages/device-detection/.gitattributes, projects/packages/error/.gitattributes, projects/packages/heartbeat/.gitattributes, projects/packages/jitm/.gitattributes, projects/packages/lazy-images/.gitattributes, projects/packages/licensing/.gitattributes, projects/packages/logo/.gitattributes, projects/packages/options/.gitattributes, projects/packages/partner/.gitattributes, projects/packages/redirect/.gitattributes, projects/packages/roles/.gitattributes, projects/packages/status/.gitattributes, projects/packages/sync/.gitattributes, projects/packages/terms-of-service/.gitattributes, projects/packages/tracking/.gitattributes
We added a mirrored .github file to the mirror repos. Since all files, unless excluded, are included in the dist version offered by Packagist, we would be serving the .github folder in any future versions of packages.
This PR updates the .gitattributes of all packages to ignore the .github folder and .gitignore if present and not already excluded.
* Exclude .github from dist.
None.
No
* Post-merge, you can confirm it isn't present when running `composer install --no-dev --prefer-dist` in a consuming project that is set to use the @dev version.
* n/a
=> Packages: Do not include .github in dist

projects/plugins/jetpack/changelog.txt, projects/plugins/jetpack/readme.txt
- Add entries for fixes
- Copy 9.3 to changelog.txt (I had forgotten to do it for that release).
- Update stable tag in readme.txt
* N/A
* No
* Do you notice any typos?
* This is it.
=> Changelog: add initial changelog for 9.3.1

.github/workflows/build.yml
Script needs to be run from within the monorepo.
p1610733202202900/1610723715.188300-slack-CBG1CP4EN
No.
* Merge it, then see if the mirroring works.
* None needed
=> Mirroring: Fix after #18355

.github/files/push-all-projects.sh, .github/workflows/build.yml
Attempted simplification in #18355 broke it. That `.netrc` file had
incorrect credentials but was being overridden by passing different auth
info in the URL itself.
p1610735022203800/1610723715.188300-slack-CBG1CP4EN
No.
* Merge and see if it works.
* None needed.
=> Mirroring: Fix auth

.github/workflows/build.yml
The variable is API_TOKEN_GITHUB, not API_GITHUB_TOKEN.
p1610738641216100/1610723715.188300-slack-CBG1CP4EN
No.
* I really wish there were a better way than "merge and see if it works"...
* None needed.
=> Mirroring: Fix auth, attempt 2

tools/docker/README.md
* Update relative link locations after #18257 reorganized folders.
* NA
* NA
* Verify that links direct to correct pages rather than 404
* NA
=> Docs: Update relative link locations in Docker readme

docs/development-environment.md
* Update the path to the Code Sniffer ruleset in the development environment doc.
* n/a
* no
* n/a. Just verify that the documentation update is clear and correct.
* n/a
=> Docs: update path to the Code Sniffer ruleset

.github/files/check-composer-locks.sh
The way to fix it is probably to run `composer update --root-reqs`. So
say that in the CI message to save people having to remember that
themselves.
None.
No.
* Make a PR updating one of the package composer.json files, without updating the Jetpack composer.lock.
* See what the CI message says.
* None needed.
=> CI: Give advice in the composer lockfile check

.phpcs.config.xml
PHPCS: Don't lint photon-cdn/jetpack-manifest.php
It's a built file since #18313 / #18257.
None.
No.
* Do something like `composer phpcs:lint projects/plugins/jetpack/modules/photon-cdn/jetpack-manifest.php`. It should not output any warnings because the file is excluded.
* None needed.
=> PHPCS: Don't lint photon-cdn/jetpack-manifest.php

projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php, projects/plugins/jetpack/modules/sharedaddy/sharing.js
Pointed out in #17864 and postponed to this PR.
* Fix several issues pointed out in #17864
None.
No.
Smoke-test sharing functionality, if possible:
- Add a "More button" to your test site.
- Verify that it works correctly on hover and click, particularly in IE 11.
- Fixed a few issues with sharing buttons, particularly in older browsers.
=> Bugfixes to sharing code

projects/plugins/jetpack/readme.txt
**Changes proposed in this Pull Request:**
The current Changelog URL is giving 404, fixed the typo
**Does this pull request change what data or activity we track or use?**
No
**Testing instructions:**
Not needed
**Proposed changelog entry for your changes:**
None needed
=> Update Changelog URL

.gitattributes, projects/plugins/jetpack/.gitattributes
postcss.config.js got moved into Jetpack in #18377, but no exclude entry
was added at the time.
Also, I noticed that deploy-to-svn.sh removes the .gitkeep files and the
directories they're keeping. So there's no point to pushing them to the
production mirrors.
None.
No.
* See if the files are now excluded from the build. Check the artifacts in the Build job.
* None needed.
=> Mirroring: Flag some more files with production-exclude

.github/files/build-all-projects.sh, projects/packages/lazy-images/composer.json, projects/packages/lazy-images/package.json, projects/plugins/jetpack/composer.json, projects/plugins/jetpack/composer.lock
Instead of requiring yarn for building, require composer which we
already require anyway.
Composer can easily enough call yarn or whatever.
None I can recall to link to.
No.
* Does the Build job still work?
* None needed.
=> Mirroring: Move build command into composer

tools/git-hooks/post-merge-checkout-hook.sh
It needed some attention after the repo reorg.
None.
No.
* Switch between branches with modifications to various composer.lock, yarn.lock, and packages files. See if appropriate messages are output.
* None needed.
=> Git hooks: Update post-merge-checkout-hook.sh

projects/plugins/jetpack/extensions/shared/components/audio-player/style.scss
Fixes #18471
* Swaps the player jump button svg icons out for ones with the number of seconds, to make it clear how many seconds each button jumps ahead or backwards.
#18471 
N/A
* Add a podcast player block to a post or visit /wp-admin/post-new.php?anchor_episode=547d02ae-abde-462d-92af-3de55ed5bcd2&anchor_podcast=22b6608
* Check that the icons have changed:
Before | After
------- | -----
No entry needed, part of Anchor work.
=> Podcast player block: Add number of seconds to skip forward/back buttons

projects/plugins/jetpack/extensions/blocks/conversation/components/participants-controls.js, projects/plugins/jetpack/extensions/blocks/dialogue/components/participants-control.js, projects/plugins/jetpack/extensions/blocks/dialogue/edit.js
Another updates round according to UX design feedback:
* Dialogue Block: Checkmark icon needs to be updated
* 
before | after
-----|------
* Dialogue Block: Hide Toolbar Player Controls When Missing Audio Source
before | after
-----|------
* Conversation Block: Remove 'Microphone' icon from the toolbar
before | after
-----|------
Fixes #
* Conversation/Dialogue: UX updates
No
* Test visually all changes described above
n/a
=> Conversation/Dialogue: UX updates

docs/development-environment-cli-support.md, tools/check-copied-files.sh, tools/check-development-environment.sh, tools/cleanup-excludelists.sh, tools/create-release-branch.sh, tools/deploy-to-svn.sh, tools/includes/chalk-lite.sh, tools/includes/check-osx-bash-version.sh, tools/includes/plugin-functions.sh, tools/includes/proceed_p.sh, tools/plugin-version.sh, tools/revert-release.sh, tools/version-packages.sh
* Add color to tool output!
* Update check-development-environment.sh with checks for jq and modern bash.
* Make tools/revert-release.sh generic.
None.
No.
* Do things work?
* None needed.
=> Tools: Cleanup and update other bash tools

tools/cli/commands/build.js, tools/cli/commands/install.js, tools/cli/helpers/tasks/installProjectTask.js
Converts the stream of the build to a prettier set of indicators.
https://user-images.githubusercontent.com/88897/105559526-0d8cfe00-5cd7-11eb-8ee4-bf819ec4a47e.mov
* See above.
n/a
n/a
* `yarn install` from the monorepo to install the CLI initially.
* `jetpack build plugins/jetpack`
* n/a
=> CLI: Prettify build step

projects/plugins/jetpack/tests/e2e/lib/blocks/mailchimp.js, projects/plugins/jetpack/tests/e2e/lib/page-helper.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/block-editor.js, projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/in-place-authorize.js, projects/plugins/jetpack/tests/e2e/lib/pages/wpcom/connections.js, projects/plugins/jetpack/tests/e2e/lib/tunnel-manager.js
* update how Mailchimp test switching between tabs
* increase timeout for post publish
* increase timeout for in-place connection flow
* Add timeout to localtunnel tunnel creation
1199714989172614-as-1199606265177796
n/a
* Re-run tests few times. Make sure they are green 
* n/a
=> E2E Tests: improve stability

tools/check-development-environment.sh
Missed one when renaming things during #18482 development.
No.
No.
* Run `tools/check-development-environment.sh`, see that it doesn't have an error "tools/check-development-environment.sh: line 88: modern_version_of_bash: command not found" in the "Tools used by scripts" section.
* None needed.
=> Tools: Fix check in check-development-environment.sh

projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php
The Spotify URL is provided via the query string. The expected name was `spotify_show_url`. This PR changes the name to `spotify_url`
Fixes #
* anchor-fm: rename Spotify var name
No
* Create a new podcast Episode, using a URL like the following;
```
http://localhost/wp-admin/post-new.php?action=edit&anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spotify_url=https%3A%2F%2Fopen.spotify.com%2Fshow%2F6HTZdaDHjqXKDE4acYffoD%3Fsi%3DEVfDYETjQCu7pasVG5D73Q
```
* Confirm the badge is properly rendered in the post content
* Check the URL assigned to the badge is correct
* Open the Spotify page by clicking on the link
*
=> anchor-fm: rename Spotify var name

projects/plugins/jetpack/extensions/index.json
**Let's hold on until the feature is tested internally.**
This PR moves the `Conversation` and `Dialogue` blocks to the experimental state.
Fixes #
* Extensions: move conversation and dialogue to experimental
No
* Go to '..'
*
N/A
=> Extensions: move conversation and dialogue to experimental

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/plugin_debug-helper.md, .github/ISSUE_TEMPLATE/plugin_jetpack-beta.md
* Add new issue template for beta plugin
* Add new issue template for debug tools plugin
* Update bug report issue template
* Add `[Type] Bug` label. 
* Update feature request issue template
* Add `[Type] Feature` label. 
* N/A
* No.
* Once merged, try creating a [`New Issue`](https://github.com/Automattic/jetpack/issues/new/choose).
* Review the `Plugin - Jetpack Beta Tester` and `Plugin - Jetpack Debug Tools` issue templates for readability, typos, and correctness.
* N/A
=> Issue Templates: Add new issue templates for Beta Tester and Debug Tools plugins

projects/plugins/jetpack/changelog.txt, projects/plugins/jetpack/readme.txt, to-test.md
* Changelog and testing list for the upcoming version of Jetpack.
* **As you update the changelog here, you can update the Project thread linked below.**
* p1HpG7-aVb-p2
* No
* This is it.
=> 9.4 Release: changelog 

projects/plugins/debug-helper/class-admin.php, projects/plugins/debug-helper/modules/class-broken-token.php, projects/plugins/debug-helper/modules/class-jetpack-sync-debug-helper.php, projects/plugins/debug-helper/modules/class-mocker.php, projects/plugins/debug-helper/modules/class-rest-api-tester.php, projects/plugins/debug-helper/modules/inc/class-broken-token-xmlrpc.php, projects/plugins/debug-helper/modules/inc/mockers/class-nonces-runner.php, projects/plugins/debug-helper/modules/inc/mockers/class-options-runner.php, projects/plugins/debug-helper/modules/inc/mockers/class-tools.php, projects/plugins/debug-helper/modules/inc/mockers/interface-runner.php, projects/plugins/debug-helper/plugin.php
Update package name to automattic/jetpack-debug-helper
* n/a
n/a
n/a
* n/a
*
* n/a
=> Debug Helper: Noramlize package names

projects/plugins/beta/admin/main.php, projects/plugins/beta/class-jetpack-beta-admin.php, projects/plugins/beta/class-jetpack-beta-autoupdate-self.php, projects/plugins/beta/class-jetpack-beta.php, projects/plugins/beta/class-jetpackbetaclicommand.php, projects/plugins/beta/jetpack-beta.php
* Updates all @ package tags to 'automattic/jetpack-beta' to noramlize it.
n/a
n/a
* n/a
*
* n/a
=> Beta: Noramlize package name in docblocks

.eslintignore, .github/actions/required-review/.gitignore, .github/actions/required-review/README.md, .github/actions/required-review/action.yml, .github/actions/required-review/package.json, .github/actions/required-review/src/main.js, .github/actions/required-review/src/paths.js, .github/actions/required-review/src/reporter.js, .github/actions/required-review/src/requirement.js, .github/actions/required-review/src/reviewers.js, .github/actions/required-review/src/team-members.js, .github/actions/required-review/test.sh, .github/files/required-review.yaml, .github/workflows/required-review.yml
As we start pulling more different things into the monorepo, the old
"Must have a Crew Review" check isn't going to work for us.
So rewrite the check to allow for different team requirements by paths
touched in the change.
1199714989172614-as-1199714989172714
No.
Things you might try:
* Look at the logs for the job when it runs after making a comment on this PR. [This link](https://github.com/Automattic/jetpack/actions?query=workflow%3A%22Check+required+reviews%22+branch%3Aupdate%2Frequired-review-check) might help.
* See that the "Required review" status looks like it's coming from the new code.
* Make a PR based on this PR and see if the logs indicate proper behavior.
* Use the included `test.sh` to run it against various other PRs and see if it seems to be trying to do the right thing. …
=> GH: Rewrite required-review action to add path-based requirements

.github/files/build-all-projects.sh, .github/workflows/build.yml, projects/plugins/jetpack/package.json
* Use a constant build directory in the action because the path winds up
in vendor/composer/installed.json for all the included monorepo packages.
* Set COMPOSER_ROOT_VERSION in build-production-php
Without this (or .version or .extra.branch-version in composer.json),
composer pulls the git commit sha for a 'reference' field in
vendor/composer/InstalledVersions.php. And unlike when it does so for
monorepo packages, it doesn't even check for the most recent commit that
actually touched projects/plugins/jetpack/.
None.
No.
* Make a PR depending on this one that doesn't touch anything in projects. The build artifacts from this PR and that PR should be the same, no differences inside Jetpack's vendor directory.
* None needed.
=> Build: Fix more always-changing stuff

projects/packages/options/legacy/class-jetpack-options.php, projects/plugins/jetpack/_inc/client/recommendations/index.jsx, projects/plugins/jetpack/_inc/client/state/recommendations/reducer.js, projects/plugins/jetpack/_inc/lib/class-jetpack-recommendations.php
This updates the behavior for deciding whether the Recommendations show based on a conversation with @jessefriedman about the banner not being in this release.
Now:
1. The recommendations tab will show to all users. This was done because the tab alone is not intrusive.
2. The previous logic to hide the recommendations has been left so that it can be used to hide the recommendations banner in the future. This is because the banner is intrusive.
No
1. On a new site, verify that the Recommendations tab shows on the dashboard.
2. On a site that had a completed setup wizard and upgraded, verify that the Recommendations tab shows on the dashboard.
N/A
=> Jetpack Recommendations: Show Recommendations tab for all users

projects/plugins/jetpack/modules/plugin-search.php, tools/phpcs-excludelist.json
PHPCS
Changes proposed in this Pull Request:
* PHPCS PSH
n/a
n/a
* n/a
*
* n/a
=> Plugin Search: PHPCS

.github/files/build-all-projects.sh, .github/files/filter-mirrors-for-release-branch.sh, .github/workflows/build.yml, docs/monorepo.md, projects/github-actions/push-to-mirrors/README.md, projects/github-actions/push-to-mirrors/action.yml, projects/github-actions/push-to-mirrors/composer.json, projects/github-actions/push-to-mirrors/push-to-mirrors.sh, tools/cli/helpers/projectHelpers.js, tools/cli/tests/helpers/projectHelpers.test.js
* Clean up the script of a few a8c-isms.
* Fix newlines in the commit messages.
* Allow for overriding the commit message and release branch infix.
* Create projects/github-actions/ as a place for published actions to live, and put it there.
None I can think of to link to.
No.
* Run the mirroring script manually, see if things work.
* Merge and see if it mirrors to master correctly.
* None needed.
=> Actions: Prepare to publish our push-to-mirrors action

.github/workflows/build.yml
Follow-up to #18575
It looks like the path isn't right, so trying to set it from the workspace.
* Updating the path of the action for the local run.
n/a
n/a
* Merge and check the log.
* n/a
=> Push to Mirrors: Update path

tools/docker/docker-compose.yml
MailDev, the tool we use within Docker to display mail attempted to be sent, has moved to a new location awhile ago.
djfarrelly/maildev is now maildev/maildev. See https://hub.docker.com/r/djfarrelly/maildev
Also updates the URL in the comments.
* See above.
n/a
n/a
* `yarn docker:up`
* After it loads, visit http://localhost:1080 and confirm MailDev 1.1.0 is the version reported near the bottom.
Note: In the Docker text on the screen, it tells me the MailDev app is available via 0:0:0:0:80 both before and after this PR. That's a separate fish to fry; our docs are correct.
* n/a
=> Docker: Upgrade maildev image

.github/workflows/build.yml
Forgot that the monorepo checkout is in a subdir.
???
No.
* Merge and see if the mirroring works again.
* None needed
=> Mirroring: Fix paths after #18575

projects/github-actions/push-to-mirrors/action.yml
=> Push-to-mirrors: Fix action.yml

projects/plugins/jetpack/_inc/lib/class-jetpack-recommendations.php
Atomic sites already get onboarded in Calypso.
* p8oabR-BT-p2#comment-4955
* No
* On an Atomic site, visit Jetpack > Dashboard
* You should not see the Recommendations tab.
* N/A
=> Recommendations: do not show for Atomic sites.

.github/workflows/build.yml
Didn't completely remove it when changing direction in #18575.
p1612201161476800/1612199331.464600-slack-CBG1CP4EN
No.
* None needed.
=> Build action: Remove unused input

readme.md
* Added new members of crew, removed members of Crew who were also listed under other, updated Happiness.
n/a
n/a
* n/a
* n/a
=> Readme: Various staff updates

projects/packages/autoloader/src/CustomAutoloaderPlugin.php
Currently when a package includes the autoloader it will be executed transitively in every package that requires that one. This becomes a problem in WooCommerce when developers add our package as a dev dependency to access intellisense. Since Composer executes plugins from transitive dependencies this results in them generating an autoloader that they don't use and in the worst case receiving an error because of `vendor-dir` customization.
This PR adds a check to prevent autoloader generation when it isn't included in the root package. If a developer wants to depend on a package that has the autoloader and use it themselves they can still add it to their own `require` section and it will work as expected.
N/A
No.
In the `projects/packages/autoloader` directory create two new directories …
=> Autoloader: prevent transitive plugin execution

projects/plugins/jetpack/class.json-api-endpoints.php
Required for Automattic/wp-calypso#49500
* Adds the file size to the Media endpoint 
See Automattic/wp-calypso#49492
I don't think so, but this data isn't accessible in Calypso currently.
* Go to the Media Library in Calypso and open up a file
* Inspect the call to `media?http_envelope=1&number=20`
* Verify the response includes the file's size
* Probably not needed since this is a change in Calypso
=> API: Add File Size to Media Endpoint
