Automattic/jetpack

_inc/client/at-a-glance/index.jsx, _inc/client/components/jetpack-notices/index.jsx, _inc/client/components/masthead/index.jsx, _inc/client/components/navigation-settings/index.jsx, _inc/client/components/navigation-settings/test/component.js, _inc/client/components/non-admin-view/index.jsx, _inc/client/components/settings-card/index.jsx, _inc/client/components/settings-card/test/component.js, _inc/client/components/settings-group/index.jsx, _inc/client/components/settings-group/test/component.js, _inc/client/state/initial-state/reducer.js, _inc/client/writing/composing.jsx, _inc/client/writing/index.jsx, _inc/client/writing/post-by-email.jsx, _inc/lib/admin-pages/class.jetpack-react-page.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes #6475
* allow non admin to use After the Deadline, Post by Email, and, if Publicize is active, display the Sharing tab. This tab is not visible when only Sharing is active because it gives non admins the ability to change the appearance of the site and that's only something admins should do.
* extend GUI tests to verify that a non admin can access After the Deadline settings group, the Post by Email settings card. If Publicize is active, display the Sharing tab.
* if  user is unlinked, hide Sharing tab and block PbE settings card
* don't show main toggles when user can't manage modules
* the `/settings` endpoint was updated. There was an issue where it wasn't allowing non-admins to set AtD options or regenerate PbE address.
* if user is subscriber, don't show the notice "You are …
=> Settings  UI: allow non admins to use AtD, PbE and Publicize

_inc/client/writing/media.jsx, modules/module-headings.php, modules/videopress.php
Adds a settings card in /writing in the media section to allow toggling of VideoPress.  
Will only show if on premium or business plan.  Otherwise, you should see a banner CTA.
=> Settings UI: Add VideoPress settings card

_inc/client/admin.js, _inc/client/main.jsx
Fixes #6610
This ensures that if any route is navigated that is not registered, we will show them the AAG Dashboard rather than a blank page.  This is increasingly important as we're about to change/remove a lot of the routes.  
To test: 
- Navigate the UI as you normally would, click around a couple times
- manually change the route to something like `/wp-admin/admin.php?page=jetpack#/whatever`
- observe that you're taken to the /dashboard route
- observe that the URL changed
- observe that the `back` button takes you to the route you were at before.
=> Settings UI: Routes that aren't defined will take you to the /dashboard

_inc/client/components/navigation-settings/index.jsx, _inc/client/components/navigation-settings/test/component.js, _inc/client/state/connection/reducer.js
Fixes #6660
* introduce new reducer `isSiteConnected` that returns only a boolean
* fixes issue with JS warning regarding a mixed type value passed to `NavigationSettings` component
* updated GUI tests
* make sure Sharing is working properly in connected and Dev Mode
=> Settings UI: solve JS warning due to a mixed value

_inc/client/components/masthead/index.jsx, _inc/client/main.jsx
Fixes #6461 
* Removes the navigation button group from static loading placeholders.
* Removes the navigation button group from disconnected sites that are not in dev mode.
* Adds a page reload on site disconnection to refresh the sidebar navigation.
* Reload the admin page, observe the Masthead element. There should be no button group in loading state.
* Disconnect the site from the dashboard, you should observe a page being reloaded and scrolled back to top. Settings link shouldn't be there in the left sidebar.
* In disconnected mode observe that there are no buttons in the Masthead.
* Turn development mode on, observe the button group in the Masthead.
=> Remove Settings links and buttons from disconnected views.

_inc/client/state/modules/actions.js
Fixes #6652
You should no longer see status notices when activating/deactivating modules from the dashboard.  Also cut the duration time in half, 6 seconds is too long.
=> Remove transition status notices for activating modules on the dashboard

_inc/client/components/settings-card/index.jsx
Fixes #6449 
* Made banners only appear when the site data is not being fetched.
* Used new styles for banners: one liners with call to action buttons.
* Added a condition to hide settings card children for cases when the plan doesn't allow configuration.
* Properly attached banner plan props to each feature's required plans.
* Make sure correct banners appear for correct plans.
* Make sure call to action is 'Activate' when it's not yet in the plan, and 'Upgrade' when it's in the plan but a higher tier is needed.
* Make sure the links have the right query parameters, like `settings-video-premium` for VideoPress on free and personal, and `settings-video-pro` on VideoPress for Premium.
=> Updates banner styles and behaviour.

_inc/client/discussion/subscriptions.jsx, _inc/client/security/backups-scan.jsx, _inc/client/traffic/ads.jsx, _inc/client/traffic/google-analytics.jsx, _inc/client/traffic/seo.jsx
Fixes #6651
Uses clickable compact cards for external links for some settings cards.  Also removed some `p` tags to remove some crazy padding.  
Some of the cards won't show if the module isn't active, like ads and subscriptions.
=> Settings UI: Replace some settings external links with clickable cards 

modules/infinite-scroll/infinity.php
Fixes #6568 
* Change "Older Posts" button text, when we are on taxonomy page.
* If a taxonomy is attached to more that one post type, leave the text "Older Posts", without confusing the users.
* Enable Portfolio post type
* Change posts per page to 1 ( Settings -> Reading )
* Create at least two projects
* Create sample Project type ( Portfolio -> Project Types -> Add New )
* Assign the projects to that type
* Open that Project type archive
* Make sure that the button text is "Older Projects"
=> Infinite Scroll: Change button text on taxonomy page

_inc/client/components/settings-card/style.scss
Fixes clickable card font size and various text bits that hadn't been reset.
=> Fix settings font size issues

_inc/client/at-a-glance/protect.jsx, _inc/client/security/protect.jsx, modules/module-headings.php, modules/protect.php
=> Remove "login" from Jetpack

_inc/client/components/dash-item/style.scss, _inc/client/components/foldable-card/style.scss, _inc/client/components/forms/styles.scss, _inc/client/components/module-settings/style.scss, _inc/client/components/settings-card/style.scss, _inc/client/components/settings-group/style.scss, _inc/client/security/protect.jsx, _inc/client/writing/media.jsx, modules/module-headings.php, modules/protect.php
fixes #6554
* **align learn more icons, mobile and desktop**
* **evenly space toggle explanation**
Before
After
* **vertically align text with toggle**
Before
After
* **align toggles and notice in dash items, also solves bad positioning issue for notice in dash item on mobile**
* **indent explanation for Photon toggle**
* **update texts for Protect settings card, "Brute force login blocking" for header and "Block suspicious-looking login activity" for toggle description**
=> Settings UI: align and space elements

modules/widgets/social-media-icons.php
Instagram now uses www. in all its URLs.
* Social Media Icons Widget: update Instagram base URL to use `www`.
=> Social Media Icons Widget: update Instagram base URL.

_inc/client/components/admin-notices/index.jsx, _inc/client/components/jetpack-notices/index.jsx, _inc/client/main.jsx
[`aria-live`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) is used to tell screen readers that the content in a section will be changed without a page reload. There are two levels of "politeness", polite and assertive.
This PR turns on aria-live=assertive for the Main component, which will interrupt the user when the page content changes (like for a navigation change, or reading out the content of an opened card).
The notices are set as "polite", so they're only read when the user pauses (this _sounds_ like it's not what we want, but it actually works very smoothly in testing).
Fixes #6534
**To test**
1. Turn on a screen reader — VoiceOver (mac), Narrator (windows), ChromeVox (chrome extension), or JAWS (windows).
2. Navigate through the dashboard, …
=> Add aria-live attributes to dashboard containers for Main and notices

_inc/client/components/forms/styles.scss, _inc/client/writing/theme-enhancements.jsx
Fixes #6218
* convert Infinite Scroll toggles into radio options updating its labels so it's more clear to end user
* make sure all options work. The first option will deactivate the module. The other two activate it and the second one sets `infinite_scroll` option to false while the third sets it to true.
cc @tyxla since you were going to implement this in Calypso.
=> Settings UI: convert Infinite scroll options to radio buttons

_inc/client/at-a-glance/backups.jsx, _inc/client/at-a-glance/scan.jsx, _inc/client/at-a-glance/style.scss, _inc/client/components/settings-card/index.jsx, _inc/client/pro-status/index.jsx, _inc/client/security/backups-scan.jsx
Fixes #6405 
* if site has a free plan, prompt to upgrade. This is done only in dashboard item
* if there are threats, prompt to fix them
* if site is secure, display a success badge
* action text is not uppercased in mobile size
* test switching plans
* the threats badge can be tested by, standing on this branch in your local Git, cherry picking the commit from #6688 `git cherry-pick bd607587539c3c05c62476003a4f41d8fa822bb0`
=> Settings UI: introduce actions for scan settings card

sync/class.jetpack-sync-functions.php
Adds `vip-go` to the list of known hosting providers in Jetpack Sync.
=> Add vip-go to hosting provider detection

_inc/client/engagement/index.jsx, _inc/client/plans/plan-body.jsx
After introducing the new Traffic tab in WordPress.com, `/settings/seo/:site_id` and `/settings/analytics/:site_id` are no longer valid, and we use `/settings/traffic/:site_id` instead.
https://github.com/Automattic/wp-calypso/pull/12309 introduces redirects, but this PR updates these URLs in Jetpack as well, so we can avoid the extra redirect.
=> General: Update WordPress.com SEO and Analytics URLs

_inc/lib/admin-pages/class.jetpack-react-page.php, _inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-xmlrpc-consumer-endpoint.php
* whitelist the 'wordpress_api_key' option: an alphanumerical string that can be saved as the Akismet key
* returns data for Holiday Snow and Akismet on Initial_State. This fixes the Akismet checkbox that until now wasn't ticked.
* adds a key `akismet` to list of settings returned by `/settings` endpoint. Value is `true` if Akismet plugin is active, otherwise is `false`.
Fixes #6695
Related #6206
=> Endpoints: allow to save Akismet key

modules/subscriptions.php
Fixes #3110
* Show the correct notification, when the email is already subscribed.
* Activate "Subscription" module.
* Add "Blog Subscription" widget to any sidebar.
* Subscribe to the blog.
* Refresh the page and make sure that `$_GET` params are removed from URL ( ?subscribe= )
* Subscribe again.
* You should see the following message:
"You have already subscribed to this site. Please check your inbox."
=> Subscriptions - Fix already subscribed email notification

modules/theme-tools/featured-content.php
Fixes #6670
@kathrynwp I implemented the changes you suggested; I liked both of your suggestions. :) If I had to make one more change, I'd add "too" at the end of "Display tagged posts outside the Featured Content area", but I don't know if that would read well.
What do you think? 
* Featured Content: Reword checkboxes for clarity
=> Featured Content: Reword checkboxes for clarity

_inc/client/at-a-glance/stats/dash-stats-bottom.jsx
Stats Verbiage: Removing "old stats”. Changing to “detailed stats” -
using the term “old” may signify “outdated” stats, which doesn’t make
sense.
*Before*
*After*
=> Stats Verbiage: Removing "old" stats

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes a bug where saving either of these options would not actually work: 
It's not clear to me why we were checking for the `enabled` string for the value.  Maybe we were passing this before through the request?  Anyway, saving should work now and to test you should toggle these settings and make sure they're working properly.
=> Remove unused rule for saving mobile theme options

_inc/client/components/settings-card/index.jsx, _inc/client/traffic/ads.jsx
Adds an upgrade banner and replaces the settings content when the site is on a free plan.
=> Settings UI: Add banner for WordAds feature

_inc/client/components/support-card/index.jsx, _inc/client/components/support-card/style.scss, _inc/client/scss/variables/_colors.scss, _inc/lib/admin-pages/class.jetpack-react-page.php
* in addition to the UI changes, the info for HEs gravatars now includes the names since they're used below the image.
=> Settings UI: update support block

_inc/client/state/modules/actions.js, _inc/client/state/settings/actions.js, _inc/client/writing/index.jsx, _inc/client/writing/masterbar.jsx, modules/masterbar/masterbar.php
Adds the WordPress.com Masterbar module to the settings page, in the /writing tab.  
Currently using the copy from the module Header.  
It also adds a new function that will reload the page after activation/deactivation in the `updateSettings` function, since we're no longer using `activateModule` and `deactivateModule`.  
**Connected/linked Admin View**
**Unlinked admin view:**
Since the toolbar only works when the user is linked, I figured we should have something there to promote it.  The toggle will be disabled when the user is not linked.  
**Unlinked non-admin role (editor, for example)**
Do we need anything here?  Do we want to add a blurb to push them to link their account?  There are three scenarios here for non-admins: 
- Module is inactive: We don't show anything
- Module is …
=> Settings UI: Add masterbar card

modules/masterbar/masterbar.php, modules/masterbar/overrides.css
Fixes https://github.com/Automattic/jetpack/issues/6709
* Changes hooks on which Masterbar styles and scripts are loaded in order to avoid unstyled flash of data while they are loading.
* This caused some visual regressions in popup menus, which required new CSS overrides to be introduced.
1. Activate WordPress.com Toolbar module on your test Jetpack site.
2. Navigate to `wp-admin/index.php` and verify that data flash is no longer occurring.
3. Verify that there are no visual regressions introduced to Masterbar.
=> Masterbar: Fix unstyled flash bug in WP Admin

_inc/client/traffic/verification-services.jsx
This is my attempt at allowing people to turn on the feature if it is for whatever reason disabled.  
Currently when it's disabled we still show the links to non-existent sitemap URLs. 
**This PR hides the links when the module is inactive.**  
Active Feature: 
Inactive:
=> Settings UI: Adds a toggle for sitemaps feature

_inc/client/components/support-card/index.jsx
* avoid re-rendering the support block unnecessarily
* don't render the support block until we have the plan data so we know which text to display: the one for priority support or the regular one
* once it's rendered, don't re-render when switching tabs if we already have plan information available.
* make sure there are no multiple calls for HE avatars
* make sure the support block is rendered once
=> Settings UI: fix support block triple render

_inc/client/main.jsx
Jumpstart was broken in the Settings UI. 
To Test: 
- Disconnect the site
- Either `Reset options` in the Jetpack footer or reset just the jumpstart option with 
`wp jetpack options update jumpstart new_connection`
- Connect the site, choose any plan or free plan
- When you land back in jetpack admin you should see Jumpstart
=> Settings UI: Fix Jumpstart

modules/contact-form/grunion-contact-form.php
* When a Contact Form is placed in a text widget, submissions generate PHP notices, e.g.:
```
[08-Mar-2017 15:00:41 UTC] PHP Notice:  Undefined index: before_widget in /path/to/wp-includes/widgets/class-wp-widget-text.php on line 75
[08-Mar-2017 15:00:41 UTC] PHP Notice:  Undefined index: before_title in /path/to/wp-includes/widgets/class-wp-widget-text.php on line 77
[08-Mar-2017 15:00:41 UTC] PHP Notice:  Undefined index: after_title in /path/to/wp-includes/widgets/class-wp-widget-text.php on line 77
[08-Mar-2017 15:00:41 UTC] PHP Notice:  Undefined index: after_widget in /path/to/wp-includes/widgets/class-wp-widget-text.php on line 81
```
This PR pre-populates the widget callback's `$args` array with dummy items that prevent these PHP notices.
Before:
* Place a Contact Form in a text …
=> Contact Form: Prevent PHP notices when processing contact form in widget

_inc/client/components/settings-card/index.jsx
Fixes #6735 
* Changes buttons that are currently "Activate" but should be "Upgrade"
* Check to make sure you don't see any "Activate" buttons which try to upsell you.
NOTE: The VideoPress button is fixed in #6740
=> Fix upgrade labels

_inc/client/state/initial-state/reducer.js, _inc/client/traffic/index.jsx, _inc/client/traffic/verification-services.jsx, _inc/lib/admin-pages/class.jetpack-react-page.php
Fixes #6736
* instead of the sitemap URLs, a message will be displayed
* in Settings > Reading, set `Discourage search engines from indexing this site` to true 
* view Jetpack admin > Traffic > Sitemaps and it should display a message when the feature is active
=> Settings UI: don't show Sitemaps settings if site discourages search engines indexing

_inc/lib/admin-pages/class.jetpack-react-page.php, _inc/lib/admin-pages/class.jetpack-settings-page.php
Currently when a developer loads up Jetpack but never ran yarn build they see an error message. 
This PR tries to be a bit more helpful and provide a useful error message.
* Update error message.
* Remove the Build folder. 
See the new message.
=> General: Improved Error Message when static.html is not build

sync/class.jetpack-sync-defaults.php
Adds 2 post types that are generated by auto post plugins. (rssap-feed and wp_automatic)
https://codecanyon.net/item/wordpress-automatic-plugin/1904470
and 
https://codecanyon.net/item/rss-autopilot-unique-content-extractor/12041946
Stop syncing more post types by blacklisting them
=> Sync: Add rssap-feedand wp_automatic to the post type black list

json-endpoints/jetpack/json-api-jetpack-endpoints.php
Missing settings in the api sync_time_limit, enqueue_wait_time
* Add sync_time_limit, enqueue_wait_time to the api so that they can be updated via the api.
* Are you able to update the new settings via the jetpack debugger?
=> Sync: Update the sync api endpoint to support the missing options. 

.eslintrc
We're getting a lot of issues regarding accessibility from DOPS components that are preventing us from building. For now, let's revert to the previous eslint and when the issues in DOPS are addressed, let's enable this again.
* restore previous
* try to build or watch, it should work without errors
cc @ryelle
=> Build: suppress for now the a11y errors since DOPS needs a few fixes.

_inc/client/components/jetpack-disconnect-dialog/index.jsx
* don't initiate a new site data query since there's already one started by AtAGlance component where disconnection dialog lives. This solves the issue of feature text replaced after the site data is received
* verify that when disconnection dialog opens, the text about features is not quickly replaced
=> Settings UI: fix disconnection dialog latency

_inc/client/pro-status/index.jsx
This component because pretty convoluted.  
It also fixes inconsistencies with the Akismet card in the dashboard.  Now we are showing the same `upgrade` notice that we use for scans instead of the button.  It also links the `invalid key` notice to an actual URL.  Before it wasn't.  
To test: 
- Make sure there are no regressions in the pro status cards, especially in the AAG dashboard.  
- Make sure you still see `set up` in the scan card within /security when it's not set up on a paid plan.
=> Settings UI: Refactor ProStatus component to be more DRY and readable

_inc/client/components/settings-card/index.jsx, _inc/client/components/settings-group/style.scss, _inc/client/traffic/index.jsx, _inc/client/traffic/sitemaps.jsx, _inc/client/traffic/verification-services.jsx
* Sitemaps now has its own card 
* card is above Site Verification as per p1HpG7-3Sm-jetpackp2
* setting explanation is indented below toggle
* render and assert that Sitemaps is in a new card above Site Verification
=> Settings UI: new card for Sitemaps

_inc/client/components/settings-card/style.scss, _inc/client/traffic/site-stats.jsx
* add Stats banner when it's inactive
* test in Dev Mode and connected
=> Settings UI: add Stats banner in Traffic tab

_inc/lib/admin-pages/class.jetpack-react-page.php
Fixes #6545
* Always display the Gravatar on Jetpack's Connection settings page, even when avatars are deactivated under Settings > Discussion.
1. Visit wp-admin > Settings > Discussion
2. Disable the Show Avatars setting
3. Connect Jetpack
4. Visit Jetpack > Settings > Connection Settings
cc @alexjgustafson @danjjohnson 
Make sure the Gravatar is properly displayed.
* Admin Page: Make sure Gravatar is always displayed in Settings.
=> Admin Page: Make sure Gravatar is always displayed in Settings.

class.photon.php
Proposed new filter is called: `jetpack_photon_admin_allow_image_downsize`.
This will allow Photon's `image_downsize` callback to run when viewing the Dashboard. For environments where all intermediate images are dynamically generated (e.g. WordPress.com, VIP Go), this can come in handy as we can re-use the same imagerresizing logic on both front-end and dashboard. Currently Photon just [bails early](https://github.com/Automattic/jetpack/blob/master/class.photon.php#L406-L408) when in an `is_admin()` context.
Usage:
```
add_filter( 'jetpack_photon_admin_allow_image_downsize', '__return_true' );
```
/cc @kraftbj
=> New filter to allow running Photon in wp-admin

modules/widgets/mailchimp.php
Fixes #5942 
Adds the MailChimp Subscribe Popup widget. It basically uses the `mailchimp_subscriber_popup` shortcode to add the script and I've tried to match the WordPress.com widget as much as possible.
* Go to Widgets
* Find "MailChimp Subscriber Popup" and add the widget to any sidebar
* Add the following embedcode in "Code" field:
```
<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us11.list-manage.com","uuid":"1ca7856462585a934b8674c71","lid":"2d24f1898b"}) })</script>
```
* Open the front-end and you should see the popup
* If the popup doesn't appear for …
=> Add MailChimp Widget

_inc/client/components/jetpack-banner/index.jsx, _inc/client/components/settings-card/index.jsx, _inc/client/components/support-card/index.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php
Fixes #4537 
* introduces a new filter `jetpack_show_promotions` that when set to `false`, hides all banners from settings UI
* introduces a new component `JetpackBanner` that acts as a hub for the banners and displays them based on the result of the `jetpack_show_promotions` filter
* add `add_filter( 'jetpack_show_promotions', '__return_false' );` in the `functions.php` of a theme or in a plugin. All banners should now be hidden.
=> Settings UI: add filter 'jetpack_show_promotions' to disable banners when false

_inc/client/components/settings-card/index.jsx
Sometimes VP will already be installed/active even without a plan.  Don't show the upgrade banner for those instances.  
Fixes #6763
=> Don't show upgrade banners for scan/backups if feature is already active

_inc/client/sharing/share-buttons.jsx
Point them directly to wordpress.com/sharing/buttons/siteurl.com -- We will be handling the cases where sharing is inactive over in Calypso so that this is not a broken link.
=> Fix path to sharing buttons config to wp.com

class.jetpack-debugger.php
- Include that link only if user has access to the list.
- Create new section, separated by an horizontal line and including a heading, so the link is easier to locate on the page.
Before:
After:
If you have any feedback on wording or anything, please let me know! I think the wording could be improved, but I'm not really sure how to phrase this.
=> Debugger: add link to the old modules list.

modules/contact-form/grunion-contact-form.php
This avoid's SpamAssassin's `MIME_HTML_ONLY` rule.
See #6114
1. From `master`, fill out a `[contact-form]` and copy the email source to http://spamcheck.postmarkapp.com/
1. Note the triggered `MIME_HTML_ONLY` rule
1. Check out this branch, and re-run the test. The rule should no longer be triggered.
=> Contact Form: Add a plain-text alternative to outbound messages

_inc/client/at-a-glance/stats/dash-stats-bottom.jsx, _inc/client/at-a-glance/stats/index.jsx
Fixes #5145
* if user with permission to see stats is unlinked, the buttons to view more stats and stats on WordPress.com will be replaced by a clickable card that prompts them to link their account
* test Jetpack admin with an unlinked user that can view stats
=> Settings UI: if user is not linked, display clickable card to link account under Stats

sync/class.jetpack-sync-module-wp-super-cache.php, sync/class.jetpack-sync-modules.php
Woo and WP Super Cache modules set filters at the constructor.
`set_defaults` for callables and constants depends on those filters being set.
This PR instantiates the modules first so the filters are registerd, and calls `set_defaults` on a second step.
=> Sync: Update sync modules instantiation and set defaults

class.jetpack.php
This addresses an issue on large sites which have multiple web servers accessing a single database.  In that scenario, if updates are applied as a roll out rather than simultaneously, it will cause excessive database load as the versions "fight" over this option.
=> Retain hashes for current AND current-1 versions

_inc/client/at-a-glance/stats/index.jsx
* pass property to solve issue where DashStatsBottom was always rendered as if the user was unlinked
* link user that can view Stats
* make sure the Stats in Dashboard show the blue button to see more stats in WordPress.com and that the clickable card is not displayed
=> Settings UI: pass property to solve issue with DashStatsBottom

modules/widgets/milestone/milestone.php
Site owners should be able to allow links to open in a new window when adding custom links in the Milestone widget.
WordPress itself allows the `target` attribute in kses, so I think it's safe to allow it here as well.
Reported here:
https://wordpress.org/support/topic/html-anchors-in-milestone/
* Widgets: allow links to open in a new window when adding custom links in the Milestone widget.
=> Milestone Widget: allow target attribute in custom links.

modules/custom-css/custom-css.php, modules/infinite-scroll.php, modules/infinite-scroll/infinity.php, modules/theme-tools/infinite-scroll.php
Reported here:
https://wordpress.org/support/topic/deprecated-code-found-4/
Both `get_theme` & `get_current_theme` were deprecated in WP 3.4.
* General: remove deprecated functions, get_theme & get_current_theme
=> General: remove deprecated functions, get_theme & get_current_theme

modules/masterbar/masterbar.php
Previously, Portfolio item was shown in My Sites menu irregardless of Custom Content Types module or Portfolio content type state. These changes prevent showing Portfolio menu item when above settings are not enabled, and adds Testimonials item with similar constraints.
Fixes https://github.com/Automattic/jetpack/issues/6761
* Don't display Portfolio menu item if Custom Content Types module is not enabled, or if Portfolio content type is not enabled.
* Add Testimonials menu item with similar display constraints as for Portfolio.
1. Disable Custom Content Types and verify that Portfolio and Testimonials are not shown in My Sites menu.
2. Enable Custom Content Types, and check `Enable Portfolio Projects for this site` option.
3. Refresh page and verify that Portfolio item is displayed in My …
=> WordPress.com Toolbar: Fix custom post types related menu items display conditions

class.jetpack-debugger.php
It allows users to specify why they're contacting us. The form was modified on WordPress.com to support the new field. See more information in p7pQDF-1gx-p2
1. Go to Jetpack > Debug in your dashboard.
2. Click on the link to contact the Jetpack support team.
3. Pick a reason why you're contacting the Jetpack support team.
4. Submit the form.
5. A prefix should be added to your support email's subject line to indicate the ticket category. No prefix will be added if you picked "Something Else" as reason to contact the support team.
* Debug: include more information in the built-in contact form to help prioritizing your requests for support.
=> Jetpack Debug: add category dropdown to contact form.

modules/masterbar/masterbar.php
Previously, `Switch Site` option was shown even to users that have only one site, along with the plural in My Sites menu title. With these changes, users that have only one site will see Add New WordPress and My Site title instead.
Fixes https://github.com/Automattic/jetpack/issues/6726
* Test on Jetpack site with WordPress.com Toolbar module enabled.
* For test user account that has multiple sites, verify that `Switch Site` option and `My Sites` title are being shown.
* For test user account that has only one site, verify that `Add New WordPress` option and `My Site` title are being shown.
=> WordPress.com Toolbar: Fix menus when user has only one site

_inc/client/state/initial-state/reducer.js, _inc/client/writing/theme-enhancements.jsx, _inc/lib/admin-pages/class.jetpack-react-page.php
Fixes #5824
* introduces a notice and hides the controls if Infinite Scroll is disabled
* "Learn more" link goes to `https://jetpack.com/support/infinite-scroll#theme`
* since there are no settings to save, the Save settings button is hidden
1. use a theme that is not one of the Twenty*, for example Ryu.
`wp theme install ryu --activate`
2. go to Jetpack admin and verify that the controls are shown. This is ok, Ryu supports InfScr.
3. edit the file `/wp-content/themes/ryu/inc/jetpack.php`
4. comment or delete the line
`add_action( 'after_setup_theme', 'ryu_infinite_scroll_setup' );`
5. load Jetpack admin again. Controls should not be displayed this time.
Settings UI: if theme doesn't support Infinite Scroll, its controls will be hidden and a notice will be displayed.
=> Settings UI: add notice and hide Infinite Scroll controls if theme doesn't support it

modules/masterbar/masterbar.php
_**Note:** this PR is targeted against `fix/add-people-link` branch (https://github.com/Automattic/jetpack/pull/6779)_
This bug occurred in sub-folder installed Jetpack sites because `esc_url` was returning empty string when it encountered a site slug that contains `::`. This resulted in empty `href` field being passed to `add_menu` method, which caused the required `a` tag to be omitted from site section, breaking the layout and functionality.
Fixes https://github.com/Automattic/jetpack/issues/6727, https://github.com/Automattic/jetpack/issues/6724
* Converts sub-folder installed site slug to correct URL to be used for site section.
* On a test Jetpack site installed in sub-folder, verify that site icon is aligned properly, and that all elements of site section are clickable. This …
=> WordPress.com Toolbar: Fix unclickable site section and misaligned site icon

modules/masterbar/masterbar.php
Fixes https://github.com/Automattic/jetpack/issues/6786
Removes duplicate keys from arrays that are used to build `Me` submenu.
1. Verify that `Get Apps`, `Next Steps`, and `Help` in `Me` submenu are rendered correctly.
=> WordPress.com Toolbar: remove duplicate keys

modules/masterbar/masterbar.php
For sites with sub-folder install, links to WP Admin were broken because of `::` that was present in generated URLs, instead of slashes.
Fixes https://github.com/Automattic/jetpack/issues/6725
* Replaces `::` with `/` in generated site URL in order to correct link to WP Admin pages.
* Using a test Jetpack site that is installed in sub-folder, verify that `Add` People button works correctly.
* Verify that button works as expected on regular Jetpack sites.
=> WordPress.com Toolbar: Fix broken links to WP Admin on sites with sub-folder install

modules/masterbar/masterbar.php
Since changes to WordPress.com Toolbar related styles and scripts will now affect Jetpack sites too, we need a way to test those changes from sandboxes, before they are deployed.
=> WordPress.com Toolbar: enable testing of remotely enqueued scripts and styles

_inc/lib/icalendar-reader.php, modules/widgets/facebook-likebox.php, modules/widgets/gallery.php, modules/widgets/social-media-icons.php, modules/widgets/twitter-timeline.php, modules/widgets/upcoming-events.php
This handles the sync of wpcom changes to Jetpack, but explicitly omits the `wordpress-post-widget` because of the huge overhaul merged in #3207
=> WPCOM Widgets Merge -- 22march2017

_inc/lib/admin-pages/class.jetpack-react-page.php
cc @richardmtl
All other links in the WordPress admin menu list are relative links.
While absolute links do not usually cause any issues, it can cause notices on systems with `open_basedir` restrictions.
* Here is `$submenu` right now:
https://gist.github.com/jeherve/aa3789294b597ed29e6fc8083e1ec592
* Here it is after this PR:
https://gist.github.com/jeherve/e10ec43d74f6a5247d7257bd14e8a8ca
* Apply this PR, and make sure all Jetpack menu items link to the right page.
* Admin Page: always use relative links for submenu items to account for servers with specific restrictions.
=> Admin Page: always use relative links for submenu items.

json-endpoints/jetpack/class.wpcom-json-api-get-option-endpoint.php
Fixes an issue where we are not able to get and update whitelisted options.
=> API: Allow options api endpoint to update and retrieve whitelisted sync whitelisted options

_inc/client/at-a-glance/scan.jsx, _inc/client/engagement/index.jsx, _inc/client/plans/plan-body.jsx, _inc/client/plans/plan-header.jsx, _inc/client/pro-status/index.jsx, _inc/client/search/index.jsx, _inc/client/writing/index.jsx, _inc/lib/admin-pages/class.jetpack-admin-page.php, class.jetpack.php, modules/videopress/class.videopress-options.php
This is meant to only be merged into `branch-4.7`.  
The easiest way to test this is to manually update the state to use these slugs.  I was doing so by adding this 
`action.siteData.plan.product_slug = 'business-bundle';`
Right before the assign in this reducer [here](https://github.com/Automattic/jetpack/blob/branch-4.7/_inc/client/state/site/reducer.js#L20). 
Make sure that you're not shown any upgrade links/CTAs when on the correct plan.  Check the /apps and /plans pages as well, since the content there depends on the current plan.  
New slugs added: 
- BUSINESS = 'business-bundle';
- PREMIUM = 'value_bundle';
- PERSONAL = 'personal-bundle';
- FREE = 'free_plan';
=> Update UI to account for AT plan slugs

modules/infinite-scroll/infinity.php
When the query is manipulated, it may be necessary to filter the check that there are more posts to display, in addition to the query and query arguments.
* Adds a new filter to short-circuit the `is_last_batch()` method
=> Filter Infinite Scroll's check for more posts to display

functions.opengraph.php
In #6297, we added transients to cache some of the fallback images in jetpack_og_get_image().
However, transients can only be 45 chars maximum.
To work around that limitation, we now create a 44-char string using md5, based on the image URL.
Also added back changes to Site Icon brought in #6303, and accidentally reverted in #6297.
Fixes 144-gh-jpop-issues
* Open Graph: make sure transients are used to save image IDs.
* Open Graph: make sure Site Icons are used as fallback Open Graph Image tags.
=> Open Graph: make sure transients are used to save image IDs.

_inc/client/components/navigation-settings/index.jsx, _inc/client/components/navigation-settings/test/component.js, _inc/client/discussion/comments.jsx, _inc/client/discussion/index.jsx, _inc/client/security/index.jsx, _inc/client/sharing/index.jsx, _inc/client/state/search/reducer.js, _inc/client/traffic/index.jsx, _inc/client/writing/composing.jsx, _inc/client/writing/index.jsx, _inc/client/writing/media.jsx, _inc/client/writing/theme-enhancements.jsx
Hide settings for all modules that are disabled through the `jetpack_get_available_modules` filter.
Fixes #5212
- update reducer to initialize once, resolve ambiguity for searchTerm, optimize string matching, fail asap and return
- hide settings for disabled modules. Consolidate calls to avoid running isModuleFound twice since it's expensive.
* add code to disable modules and check that it's reflected in settings
```
add_filter( 'jetpack_get_available_modules', function( $modules ) {
unset( $modules['masterbar'] );
unset( $modules['after-the-deadline'] );
unset( $modules['carousel'] );
return $modules;
} );
```
=> Settings UI: hide settings for unavailable modules

modules/widget-visibility/widget-conditions.php
Fixes #6698
Scope the WP_User query to only include those with publishing abilities.  Some sites were breaking since we were trying to get all subscribers as well.  This will only get the users with minimum user level of 2, which grants the ability to publish posts.  
https://codex.wordpress.org/User_Levels
To test: 
- Make sure the `authors` rule only lists those who can publish posts.
=> Scope wp_user query to specific user level

sync/class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-listener.php
The actor data helps up determine who and how the action was triggered. 
Currently when we sync data we only store the current_user_id. 
* Add user_email and display name. 
* Add IP address
* Add different environment flag. is_wp_admin, is_wpcom_api, is_cron etc.
* Do the test pass? 
Add actor to sync.
=> Sync: Add actor to sync 

_inc/client/components/jetpack-disconnect-dialog/index.jsx
Fixes #6771
* fix subdirectory install URLs displayed in disconnection dialog
This is basically reverting the replacement that `Jetpack::build_raw_urls` does to slashes.
* use a site located in a subdirectory and verify it doesn't display `::` but `/`.
=> Settings UI: fix subdirectory install URLs displayed in disconnection dialog

_inc/client/components/support-card/index.jsx
Fixes #6764
* update wording in Support card for free plans
* use a free plan and verify the words are correct
=> Settings UI: update wording in Support card for free plans

_inc/client/traffic/index.jsx
Based on task from post p1HpG7-3St-jetpackp2 by @rickybanister 
> Reorder the cards to be Stats, Ads, Related Posts, SEO, Google Analytics, XML Sitemaps, Site verification
* reorders the cards to match the desired order
* make sure the cards are in the proper order
=> Settings UI: reorder cards

class.jetpack-tracks.php
Fixes a bug in Tracks for the following events: 
`jetpack_wpa_module_deactivated`
`jetpack_wpa_module_activated`
The problem with hooking onto the `pre_` version of this, is it doesn't prevent tracking if the module is already active.  
To reproduce the bug, put this `error_log( print_r( $event_obj, 1 ) );` [here](https://github.com/Automattic/jetpack/blob/master/_inc/lib/tracks/client.php#L124), and deactivate a module (`wp jetpack module activate notes` works).  
- Without the patch, you'll see that you can trigger the event multiple times if you run that command multiple times. 
- With this patch, you should only see it once, if the module was active before.  
- Same goes for the activate events.
=> Tracks: use correct hooks for activate/deactivate modules to avoid duplicate events

modules/sharedaddy/sharedaddy.php
Avoid syntax errors due to unexpected characters in the `from` name by
base64encoding the from name if any blacklisted characters are used
or it's non-ASCII.
=> Sharedaddy: Protect against malformed `from` names.

modules/related-posts/jetpack-related-posts.php
Fixes #6706 
* change the list of term queries into a single terms query that is an array of all of the post_ids to exclude
* make a related post request with over 1024 excluded post_ids and verify that the related post query returns a list of related posts
=> ES - updated related posts for excluding terms to use terms instead of term

_inc/lib/admin-pages/class.jetpack-react-page.php
* fix the issue by calling Jetpack::glob_php() passing only the path and letting it resolve the files
* `wp theme activate twentyseventeen`
Before this PR, it would show the notice as if theme wasn't supported.
With this PR, it shows the radio buttons since the theme support is provided by Jetpack.
=> Initial State: fix issue detecting Infinite Scroll for default themes

modules/videopress/class.jetpack-videopress.php, modules/videopress/class.videopress-xmlrpc.php, modules/videopress/utility-functions.php
This PR removes the use of locally downloaded (sideloaded) video files from the user's server and instead uses an attachment URL that points to the processed file for any video headers.
Fixes #6588
1) Upload a video
2) Test that it can be embedded in a post
3) Verify that it can be added as the Video header for the 2017 theme.
=> Remove videopress local files

class.jetpack.php
* Apple now offers the option to embed Keynotes via oEmbed. Let's support this in Jetpack until it makes it to WordPress core.
* See the related discussion here for some examples: p47NkD-BU-p2
* oEmbed: add Apple/iCloud Keynote provider.
=> oEmbed: add Apple/iCloud Keynote provider.

.eslintrc, yarn.lock
Now that https://github.com/Automattic/dops-components/pull/106 is merged, `yarn build` ends correctly so this PR restores the a11y checkings in Jetpack.
* enable a11y check for eslint
* update `yarn.lock`
* `gulp eslint` should end with only warnings, no errors
* `yarn build` should end correctly
=> Dev Tools: enable a11y check for eslint

gulpfile.js
Before it would have problems when there are special characters, or if there is a translator comment with a placeholder. Now it only looks for gettext calls and replaces tab characters with spaces.
Fixes the problem with `yarn build-languages`.
* Make sure `yarn build-languages` works without returning an error.
=> Fixed the way i18n exporter handles client strings.

_inc/client/components/support-card/index.jsx
Fixes #6808
- update support block wording for paid plans
- don't render the support block on each panel or tab switch.
* check that the wording is correct
=> Settings UI: update support block wording and when it should be rendered

3rd-party/bbpress.php, class.photon.php
https://wordpress.org/support/topic/photon-does-not-work/
1. Install bbPress on your site.
2. Make sure Photon is active.
3. Create a new topic and insert an image into that topic.
4. Post a reply to that topic, also including an image.
All images should then be served by Photon.
* Photon: use Photon for all images in bbPress topics and replies.
=> Photon: use Photon for all images in bbPress topics and replies.

_inc/lib/admin-pages/class.jetpack-react-page.php, tools/export-translations.php
Fixes the problem with languages where the locale is specified as a combination of two, like `fr_BE` or `de_CH`.
* Using the whole locale slug instead of just a prefix.
* Properly recognizing locale slugs like `formal` or `informal` for various languages that support them.
* To see the difference in the client side you need to run `yarn build-languages`, and to successfully do it you first need to have #6800 merged. Just run the script and see that your client side translations work for languages like `Deutsch (Schweiz, Du)` or `Français de Belgique`. To make sure they do you can check the state tree, the variable `jetpack.initialState.locale` should have locale data in it, even if it's mostly `null` values.
* Fixed administrator area translations for several languages.
* Added proper …
=> Use the whole locale slug instead of just a prefix.

_inc/client/plans/plan-body.jsx
This fixes an issue in sites in free plans: the Compare plans button in Plans tab leads user to jetpack.com and it's not redirected, as it should, to WordPress.com.
* fix plan slug comparison to render the correct link
* test with site in free plan. Go to Dashboard > Plans. The button Compare plans should redirect to `https://wordpress.com/plans/%YOUR-SITE%`
=> Settings UI - Plans: fix comparison to render the correct link

_inc/client/components/data/query-site/index.jsx
Fixes issue where `/jetpack/v4/site` is queried on every tab switch.
* check that we already have site data, in which case we won't fetch it again
* declare prop types and defaults
* convert to ES6 class syntax
* fix minor ESLint issues
* load Jetpack admin. Everything should work normally as before
* there should be only one query to `/jetpack/v4/site` regardless of the panel or tab that is first loaded when you start the app
=> Settings UI: make the QuerySite component fetch data only once

_inc/client/security/backups-scan.jsx, modules/module-info.php
The previous link lead to a page advertizing plans, although the info link is only displayed when you already have a plan.
`http://vaultpress.com/jetpack-ms/`, on the other hand, doesn't exist anymore.
=> Admin Page: update VaultPress info link.

modules/masterbar/masterbar.php
Fixes https://github.com/Automattic/jetpack/issues/6818
* Restores WP Admin link in WordPress.com Toolbar's My sites menu.
1. Enable WordPress.com Toolbar module on your test Jetpack site.
2. Verify that WP Admin link is displayed as last item in My Sites menu.
=> WordPress.com Toolbar: bring back WP Admin link

_inc/lib/admin-pages/class.jetpack-react-page.php
Fixes a bug introduced by #6815. It broke sites that would use a locale with an underscore like `ru_RU`. Using a dash instead of an underscore fixes it.
=> Fixed the locale string to work properly with toLocaleString.

_inc/client/state/at-a-glance/reducer.js
This patch is pretty self-explanatory, but before we were acting as if none of these actions were fetching if only one of them succeeded or failed.  This was probably breaking some behavior of some query components, and any other checks that depended on the `fetchingWhatever` state of these features.
=> Separate the action types for declaring fetching state for various actions. 

modules/masterbar/masterbar.php
Part 2 of #6823
1. Use `admin_url()` to always return the right admin URL.
- On some sites, the admin URL may be filtered.
- On others, WordPress may live in a subdirectory.
2. Only display WP Admin link when not in the dashboard. The menu item isn't useful when you're already in the dashboard.
P.S.: I'm wondering if "WP Admin" is actually very user friendly. It won't mean much to new WordPress users imo. How about just "Dashboard", like in the default WP admin bar?
=> Masterbar: fix admin URL and make sure the WP admin link is only displayed when necessary

class.jetpack-connection-banner.php
Photon can only be used with images.
=> Connection banner: remove mention of files from Photon description

modules/masterbar/masterbar.php, sync/class.jetpack-sync-module-users.php
Previously, `Sign Out` action in `Me` menu was just signing out users from their current Jetpack site, and it should be signing them out of WP.com too.
Test with: ~D4938-code~ (deployed)
Fixes https://github.com/Automattic/jetpack/issues/6490
1. In `Me` sub-menu of WordPress.com Toolbar, click on `Sign Out` button.
2. Verify that you have been logged out of you Jetpack test site.
3. Verify that you have been logged out from WordPress.com.
=> WordPress.com Toolbar: Make Sign Out action logout of WordPress.com

_inc/client/sharing/publicize.jsx
Fixes the broken link in the Publicize card in development mode. It doesn't make sense to point it anywhere in `wp-admin` because there are no Publicize settings there. So this PR just removes it:
Note: the `siteAdminUrl` property is no longer needed in the card, but it's still passed down from the `index.js` file. I find this to be a good tradeoff between keeping the code DRY and doing "the right thing".
* Removed the connect link from Publicize in dev mode.
* Make sure the link exists only in connected state, and it's working fine for both linked and unlinked users.
=> Removed the connect link from Publicize in dev mode.

modules/masterbar/masterbar.php
I don't think "WP Admin" is actually very user friendly. It won't mean much to new WordPress users imo. I think "Dashboard", like in the default WP admin bar, would be a lot clearer.
Before:
After:
=> Masterbar: use "Dashboard" instead of "WP Admin" as menu item.

_inc/client/at-a-glance/index.jsx, _inc/client/components/navigation/index.jsx, _inc/client/components/navigation/test/component.js, _inc/client/components/non-admin-view/index.jsx, _inc/lib/admin-pages/class.jetpack-react-page.php
Fixes #6842
This ensures that all users will have access to the dashboard, regardless of which modules are active, so that they can disconnect from wpcom if they so choose.  
This patch also fixes the security header showing for non-admins, even if protect wasn't active.
To Test: 
- Follow steps in the issue linked to reproduce
- Log in as non-admin 
- Make sure you have access to the dashboard
- Make sure the security header doesn't show when protect isn't active
- make sure it does show when active.  
Looks like this
=> Settings UI: Don't hide the dashboard for non-admins

_inc/client/components/settings-card/index.jsx, _inc/client/pro-status/index.jsx, _inc/client/security/backups-scan.jsx, _inc/client/security/index.jsx
* only show card content after data is ready. Fixes #6810 
* Update wording when VP is inactive and site has personal or premium/business plans, and also when it's in dev mode.
* only hide Backups/Scan settings card content in free plans since sites in personal plans have backups
* Update ProStatus so it displays the Set Up blue button when VP is inactive and site has personal plan.
* display content when VP data and site are being fetch
* make sure the card doesn't display one content when it's loading and then another
* if site is in personal/premium/business plan, if VP is inactive, it should display the Set Up button.
* the card content when site has a personal plan and VP inactive, mentions only backups, while it mentions backups and scans when site has a premium/business plan
* if …
=> Settings UI: update Backups/Scan settings card

_inc/client/components/jetpack-notices/index.jsx, _inc/client/components/jetpack-notices/style.scss
Fixes #6847
Fixes the awkward/broken list of reasons for being in dev mode.  This style of listing the reasons provides a readable format for when there could be multiple reasons for dev mode.  For example:
=> Fix the display of listing reasons for being in dev mode

_inc/client/traffic/sitemaps.jsx, modules/sitemaps.php, modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-constants.php, modules/sitemaps/sitemap-librarian.php, modules/sitemaps/sitemap-logger.php, modules/sitemaps/sitemaps.php
Fixes #6819
- fix wrong data type, add default parameter, wrong constant
- generate master sitemap on activation
- add a way to disable logged messages since otherwise it looks like activation fails since the response is corrupted by the logged messages
- add meaningful error when /sitemaps.xml has no content and end with WP die sending a 404 response.
- when sitemap is being generated
- disable toggle
- displaymessage about generation.
* activate the module. Verify that the message is displayed and that the module is correctly activated
* go to the sitemaps, verify that they work fine
* to delete the sitemap, go to your DB > `wp_posts` and look for posts of `post_type` equal to `jp_sitemap_master`
=> Sitemaps: generate on activation to solve 404 issue. Add message in settings UI.

tests/php/modules/shortcodes/test_class.hulu.php
This PR aims to dismiss an assertion when Hulu didn't return a proper response and instead returned an unknown error
```
```
* don't test assertion about Hulu URL if it returns an unknown error instead of the content because it could simply be timing out and it's causing Travis to fail
* Travis should pass
=> Unit tests: don't test Hulu URL if it returns an unknown error

modules/sitemaps/sitemap-constants.php
* lower the maximum byte size to be strictly less than 1Mb
=> Sitemaps: lower the max bytes to less than 1Mb

tools/deploy-to-master-stable-branch.sh
The testing list from `master-stable` is used in the Beta plugin to display a list under Jetpack > Beta.
`to-test.md` should consequently be kept up to date in `master-stable` as well.
I'm not sure how to test this, though, so I would really appreciate a good look from a someone who knows a bit more about bash scripting than me. :)
=> Deploy script: make sure changes to the testing list are committed.

_inc/client/traffic/sitemaps.jsx, modules/sitemaps.php, modules/sitemaps/sitemap-builder.php
Fixes #6854
* when module is activated, don't generate immediately. Instead, defer it to a cron job to be run once.
* removes message about sitemap being generated
* make sure the sitemap is generated asap. It won't be generated immediately. Make sure the UI doesn't hang.
=> Sitemaps: when module is activated, schedule generation once

_inc/client/state/modules/actions.js, _inc/client/state/settings/actions.js
Fixes https://github.com/Automattic/jetpack/issues/6836
* We need to reload page when Portfolio or Testimonials are activated in order for changes to take effect in the Toolbar.
1. Navigate to `Writing` pages of your Jetpack settings.
2. Verify that page is reloaded after switching the enabled state for: Masterbar, Portfolio, and Testimonials. 
3. Verify that correct message is displayed when these settings are saved.
4. Verify that we are not reloading when saving other settings.
=> WordPress.com Toolbar: add Portfolio and Testimonials when activated

modules/related-posts/jetpack-related-posts.php
We've had several reports of 500 errors on PHP 7.1 environments where
opcache was enabled.  This was distilled down to the following gist:
https://gist.github.com/georgestephanis/7a0c81593581842d36e2383ae22c0a77
If that file is loaded in a 7.1/opcache environment it will segfault.
By changing the static to a class static instead, this is avoided and it
works fine.
=> Resolve an esoteric opcache conflict in PHP 7.1

_inc/client/plans/plan-body.jsx
Fixes #6865
You should not see a CTA for the free nor personal plan for VideoPress on the `/plans` tab.  
Premium and Pro should show correct text.
=> Plans page: show videopress CTA for correct plan

_inc/client/state/modules/actions.js, _inc/client/state/settings/actions.js
Fixes #6869
* restore blue notices after toggling a feature or saving a setting
* these are restored in At a Glance and Settings
* toggle something in At a Glance. Make sure the blue notice shows up
* toggle some module and save some setting. The blue notice should show up
* regenerate PbE address. Its blue notice with custom text should show up
=> Settings UI: restore blue notices that indicate progress

_inc/client/at-a-glance/index.jsx
To reproduce the bug: 
- Deactivate protect
- Look on the AAG Dashboard
- You'll see the security header disappears
To test the fix:
- Deactivate protect
- Make sure the security header is still there for admins 
- Make sure it's not there for non-admins
=> Settings UI AAG: don't ever hide security dash header for admins

_inc/client/components/navigation-settings/index.jsx
Fixes #6858 
* Adds a call to `decodeURIComponent` to fix the escaping of search terms.
* Try search for things that have spaces in them like "post type".
* Ensure that you can find what you are looking for.
=> Added URI decoding to fix escaping search term characters.

_inc/client/sharing/publicize.jsx, _inc/client/sharing/share-buttons.jsx
Add toggles to Share Buttons and Publicize Features: 
Make sure the link card at the bottom doesn't show when it's inactive.
=> Sharing: add toggles to sharing and publicize features

_inc/client/components/jetpack-disconnect-dialog/index.jsx
Fixes #6864
* remove reference to WordPress support
**Before**
**After**
* check the disconnect dialog
=> Settings UI: update wording in disconnection dialog

modules/module-headings.php, modules/tiled-gallery.php
Currently, if the site was jumpstarted, in order to activate TG a user would have to toggle this OFF and then ON again, which activates both Photon and Tiled Galleries.  
This happens because Photon is a Jumpstart module, and Tiled Gallery is not.  
If we make sure to activate both at the same time, even in Jumpstart, then there will be no disconnect between the two modules.  
To Test **In this order**:
- Reset options link in footer
- Connect the site
- Navigate back to the dashboard, you should see Jumpstart
- Click 'learn more' to view new box for TG
- Activate features
- make sure TG is active
=> Add Tiled Gallery to Jumpstart

sync/class.jetpack-sync-module-comments.php, tests/php/sync/test_class.jetpack-sync-comments.php
This PR adds sync listeners for the `comment_approved_to_unapproved` and `comment_unapproved_to_approved` actions to the Comments Sync Module for the purpose of reporting these events to the Activity Log.
* adds sync listeners for the `comment_approved_to_unapproved` and `comment_unapproved_to_approved` actions to the Comments Sync Module
* run `phpunit --filter comment`
=> Add listeners for comment approval and unapproval actions

_inc/client/components/support-card/index.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php, functions.global.php, modules/masterbar/masterbar.php
Fixes #6874
* update support links based on whether the site is an Automated Transfer site or a standalone site
* Initial State: add information about whether the site is an Automated Transfer site or not, and reducer to obtain the info.
* extract code from method 'is_automated_transfer_site' and create a new function visible from everywhere. Preserve the method and call the function in it.
* make sure support links are correct in standalone sites and in AT site
* make sure Masterbar continues working normally
=> Settings UI: update support links for AT sites

_inc/client/at-a-glance/style.scss
Updates Disconnect dialog styles to match Calypso’s more closely.
Before:
After:
Fixes #6866
=> Admin Page: Disconnect dialog: update styles

modules/sitemaps/sitemap-finder.php, modules/sitemaps/sitemaps.php
Fixes #6901
* restore function `jetpack_sitemap_uri` This solves an issue with WP Rocket since this plugin was calling it and couldn't find it.
Sitemaps: fix issue with WP Rocket where this plugin was calling a function that wasn't available.
=> Sitemaps: restore function jetpack_sitemap_uri

modules/sitemaps/sitemap-state.php, phpunit.xml.dist, tests/php/test_php-lint.php
Fixes #6918 
* Fixes array dereference in the sitemaps code.
* Adds a unit test to run linting on all PHP files in the plugin, huge props co @cfinke for the suggestion and the code.
* Make sure Sitemaps work as they did before.
* See if Travis runs OK for all PHP versions.
* Made changes to the code to make it compatible with PHP versions older than 5.4.
=> Fixes sitemaps PHP compatibility issue.

_inc/client/pro-status/index.jsx
Fixes #6911
On a plan that supports Akismet, deactivate/delete the Akismet plugin.  It should show the `Set Up` button instead of an `invalid key` notice.  
I've also brought in the isFetchingAkismetData() selector, because I noticed we were rendering the `invalid key` notice before it was done fetching.
=> Pro Status: Display correct status for Akismet when plugin is inactive.

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
We current don't have a good way to track when the post is marked as
trashed.
The jetpack_post_trashed follows the same pattern as the published post event.
* Adding the jetpack_post_trashed event will let us know when we have
post is marked as trashed.
* Do we get the expected results on the .com side. Do we hear about the event as expected?
=> Sync: Add Jetpack Post Trashed event

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes #6932
props @cfinke for finding, explaining and suggesting a patch.
* add checking to ensure that the parameter is an array before checking the existence of an item
* make sure modules can be activated/deactivated in PHP 5.2, 5.3, 5.4 and later.
Endpoints: fixed an issue that could prevent module activation in PHP versions lower than 5.4
=> Endpoints: ensure that parameter is an array before checking an item exists

modules/sitemaps/sitemaps.php
* Removes a call to `http_response_code`
* Make sure your sitemap returns a 404 properly if it's not yet generated.
=> Removed an unneeded function call that caused a fatal in PHP 5.2.

sync/class.jetpack-sync-module-attachments.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/test_class.jetpack-sync-posts.php
Current we can't tell if an user added or updated an attachment. 
This PR tries so solve this by adding the current filter to the action being synced. 
* Notice when you add an attachment that the add_attachment action is being send to .com and that the edit_attachment action is being send to .com when you update the attachment info.
=> Sync: Adda a way to distinguish between an added and an updated attachment

sync/class.jetpack-sync-module-comments.php, tests/php/sync/test_class.jetpack-sync-comments.php
Adds non-sync listener for comment update data, and fires action sync listener is listening for if the comment contents is modified
* Adds non-sync listener for comment update data, and fires action sync listener is listening for if the comment contents is modified
* phpunit --filter comment (added test_modify_comment_contents())
=> Add mechanism to report comment content modifications via sync

sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-options.php, tests/php/sync/test_class.jetpack-sync-themes.php
This PR lets us sync changes as they happen to the sidebar.
Currently we don't have enough info that will let us see what is happening to the sidebar.
* Add actions that get fired when the widgets get added, removed and reorder a sidebar.
* Also lets us know when we move a widget to the in active widgets as well as when we 
* Do the test pass? 
* Does it make do the actions get synced on the .com side as expected?
=> Sync: Sidebar changes

_inc/lib/class.core-rest-api-endpoints.php, class.jetpack.php, modules/monitor.php
Fixes #6943
* check if class really doesn't exist first.
* convert `Jetpack_Monitor:: user_receives_notifications()` method to static to call it without instancing the class since it's not needed
Settings: fixed issue that in certain servers caused a gray screen when trying to load the Jetpack admin screen.
=> Endpoints: don't always load the module if it's inactive.

_inc/client/state/connection/actions.js, _inc/client/state/dev-version/actions.js, _inc/client/state/jumpstart/actions.js, _inc/client/state/modules/actions.js
* dismiss notice shown after a process ends successfully like other success notices are dismissed:
- Jumpstart
- Reset options
- Unlink user
* solve minor ESLint notices
**Jumpstart**
- Reset options link in footer
- Connect the site
- Navigate back to the dashboard, you should see Jumpstart
- Click 'Activate recommended features'
- Once it ends, you should see a green success notice that should be automattically hidden after 2 seconds
**Reset options**
- click the link `Reset Options (dev only)`
- the green notice should be auto-dismissed
**Unlink user**
- link a secondary user
- unlink it. The green notice should be auto-dismissed
=> Settings UI: auto-dismiss Jumpstart and other success notices

uninstall.php
Fixes #6938 
* Do not load any modules and listeners when initialising the sender. 
* Load branch. Delete plugin notice that there are no fatal error.
=> Uninstall: Fix fatal due to sync listeners being added for the delete_plugin action

class.jetpack-client.php, class.jetpack-signature.php
This has two parts:
Previously, `Jetpack_Client::wpcom_json_api_request_as_blog()` only
supported `GET` and `POST` verbs, but this allows supporting any method
such as `PUT` or `DELETE`.
HTTP requests made by functions like `Jetpack_Client::remote_request()`
generate signed body hashes for the request content. If the data is sent
via the `PUT` method, however, it was ignored, causing a hash comparison
failure on the server. This change allows `PUT` data to be validated as
well.
Just like the `POST` data, the `PUT` data is taken from the raw
url-encoded input (I don't understand why), but if IS_WPCOM, we assume
the data is JSON-encoded and use the decoded version.
=> Allow HTTP `PUT` requests sent from Jetpack to WPCOM

modules/protect.php
Fixes #6890 
If a `do_action( 'wp_login' )` call is made without the second argument, let's figure out what the user object should be. This defensively codes against an warning we've seen crop up a couple of times.
=> Protect: Backup to ensure the user object is populated

sync/class.jetpack-sync-module-plugins.php, tests/php/sync/test_class.jetpack-sync-plugins.php
Adds plugin name and version to plugin sync events for Activity Log.
Adds plugin name and version to plugin sync events for Activity Log.
phpunit/no tests changed
=> Adds plugin name and version to plugin sync events

modules/subscriptions.php
Fixes #6101 
* Adds array initialization to fix a notice in PHP 7.1.
* Use a WordPress installation running on PHP 7.1.
* Add some code that outputs a default subscriptions widget without any settings, like this:
```
add_action( 'wp_footer', function() {
do_shortcode( '[jetpack_subscription_form]' );
} );
```
* Observe the notice in the error log.
* Update to this PR.
* Observe no notice and verify that the shortcode works as it should.
* Fixed a notice in the subscription widget in PHP 7.1
=> Added array initialization to fix PHP 7.1 notices.

_inc/client/components/admin-notices/index.jsx, _inc/client/components/admin-notices/style.scss
Fixes #6960
Manually remove the link to the VaultPress, so there's not two links anymore. 
No more action notices. 
Added an icon. 
Before:
After:
=> Jetpack Notices: fix ugly VaultPress notice

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Add theme name and version to theme switch sync data
Add theme name and version to theme switch sync data
phpunit
=> Jetpack Sync: Add theme name and version to theme switch sync data

sync/class.jetpack-sync-module-users.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/test_class.jetpack-sync-users.php
This will help us know what event took place on the .com side. Instead of just updating the 
* Separate the 3 events into separate actions. Add, Register and Update user.
Do the Multi Site tests pass? 
`phpunit -c tests/php.multisite.xml --filter=user`
Seperate the Sync user events. Into more meaningful events.
=> Sync: Separate User Events: Add, Register and Update user events should be different

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Adds a Jetpack Sync action for theme installation
Adds a Jetpack Sync action for theme installation via the addition of jetpack_installed_theme action
phpunit to run new test for theme install sync
jetpack_installed_theme action added upon theme installation
=> Add a Jetpack Sync action for theme installation

tests/php/bootstrap.php, tests/php/modules/shortcodes/test_class.flickr.php, tests/php/modules/shortcodes/test_class.slideshare.php, tests/php/modules/shortcodes/test_class.slideshow.php, tests/php/modules/shortcodes/test_class.soundcloud.php, tests/php/modules/shortcodes/test_class.twitter-timeline.php, tests/php/modules/shortcodes/test_class.vimeo.php
This brings some of our unit tests back into sync with the copies that had been synced to wpcom by @enejb some time ago, in r106815-wpcom
Some will need to be tidied or changed before merging back in to Jetpack (some of the wpcom change to blog stuff, for example)
=> Sync some unit tests up with WPCOM versions.

json-endpoints/class.wpcom-json-api-list-users-endpoint.php
Because an associative array can be converted to an object, ensure that we only return the array values and not keys.
Merges r135464-wpcom.
=> Ensure that roles array for /sites/$site/users endpoint return an array

modules/subscriptions.php, tests/php/sync/test_class.jetpack-sync-posts.php
for post types other then Post
* 
* Do the tests pass? Do Posts still are being sent out to subscriptions.
=> Subscriptions: Add a check that we don't send the subscription email flag

json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
Using the bulk upgrade which puts the site into maintenance mode during
updates.
* Use the bulk_update function to update plugins via the api. 
This puts site into the maintenance mode and prevents errors during updates.
* Use the api to update a plugin.
=> API: Update Plugin use the bulk_upgrade

class.jetpack-autoupdate.php
Since we are fireing the autoupdated events from .com. Lets only do autoupdates from there. 
This has a number of benefits. 
- We can stop autoupdates from happening if we know that a site will brake due to an autoupdated. 
- Have better events when the autoupdate does happen.
* Test that the autoupdate doesn't happen for plugins again more.
=> Autoupdates: Remove plugin autoupdates from the Jetpack side of things

json-endpoints/class.wpcom-json-api-list-media-v1-1-endpoint.php
Because an associative array can be converted to an object, ensure that we only return the array values and not keys.
Merges r135464-wpcom.
=> Sync the list media endpoint.

.github/CONTRIBUTING.md, docs/testing/beta-testing.md, docs/testing/testing-tips.md, tools/build-jetpack.sh, tools/deploy-to-master-stable-branch.sh
This info should guide new contributors and help them get started with Beta testing. We'll also pull some of this data directly from the Beta plugin.
=> Docs: add information about beta testing.

_inc/client/writing/index.jsx
Fixes #6971 
* add VideoPress to list of modules that can be found
* build and search for `video` for example, it should display videopress
Settings UI: fix issue where VideoPress wasn't in the results when searching for video
=> Settings UI: allow to search for and find VideoPress

.travis.yml
WordPress has now removed HHVM it's Travis CI job matrix:
See https://core.trac.wordpress.org/ticket/40548 https://core.trac.wordpress.org/changeset/40546
https://make.wordpress.org/core/2017/04/23/recent-updates-to-the-unit-testing-infrastructure/
=> Unit Tests: Remove HHVM from Travis CI job matrix

class.jetpack-network-sites-list-table.php
By default, `get_sites()` only displays up to 100 sites by default.
Fixes 170-gh-jpop-issues
Before we ship this, it'd be great to test it on large networks. cc @iandunn 
* Multisite: display all sites available in network, even on large multisite installations.
=> Network: display all sites available in network.

modules/custom-post-types/portfolios.php
With Ads enabled and using the Portfolio shortcode, ads are injected with each portfolio entry. Let's remove this.
This seeks to surgically remove the ads from this instance only purposely set on a non-default priority so we can add/remove the function with a reduced chance of interfering with other plugins or code modifying the ad run.
To test, use a shortcode like `[portfolio display_types="false" include_types="contributing"]`.
=> Portfolio Shortcode: Remove WordAds

_inc/client/settings/style.scss
Fixes #6917
Before
After
Make sure the viewport size is < 480px and check that the icon is correctly positioned.
=> Settings UI: fix positioning of search icon on mobile screen size

modules/related-posts/jetpack-related-posts.php
Some requests for related posts are using a malformed URL where the
`relatedposts_exclude` parameter is of type array, not of type string, causing
`explode()` to fatal.
This change checks the type of the `relatedpost_exclude` parameter, and will
perform the original `explode()` if it is a string; or extract the values if
it's an array. We sanitize the values to ensure they are valid ints for use as
`$excludes`.
Props @jmdodd
Fixes #N/A
* Sanitize values and handle both comma delimited values as well as url arrays
* Check that the URL param `relatedposts_exclude[]=X` and `relatedposts_exclude=X` both exclude post_id X.
=> Related Posts: Fix fatal when the exclusion parameter is not a string

modules/contact-form/grunion-contact-form.php, tests/php/modules/contact-form/test_class.grunion-contact-form.php
This avoids SpamAssassin's `TO_NO_BRKTS_HTML_ONLY` rule.
See #6114
* From `master`, fill out a `[contact-form]` and copy the email source to http://spamcheck.postmarkapp.com/
* Note the triggered `TO_NO_BRKTS_HTML_ONLY` rule
* Check out this branch, and re-run the test. The rule should no longer be triggered.
=> Contact Form: Add display names to addresses in the `To` header

class.jetpack.php, gulpfile.js, modules/widgets/flickr.php, modules/widgets/flickr/form.php, modules/widgets/flickr/style.css, modules/widgets/flickr/widget.php
This is my second PR in the effort of filling the gaps between Jetpack and WP.com, to smooth the AT process out.
* Adds the Flickr widget as already available on WP.com.
* Add the widget to a sidebar and check if the widget shows up.
* Check if the photos are retrieved from the correct RSS feed.
=> Widgets: Porting of WP.com's Flickr Widget

class.jetpack-debugger.php
Follow-up of #6770
Until now, the link to the full module list was only appearing when your site was connected to a WordPress.com account. That's not ideal when you're working with Jetpack locally.
https://wordpress.org/support/topic/give-access-to-modules-list-on-the-dashboard/
=> Debugger: diplay the module list in Dev mode as well.

modules/seo-tools/jetpack-seo-titles.php
Previously, only arrays were considered as valid title formats, and
in case of deletion we needed to provide empty array. Now, we are also
allowing empty string to be passed in that case instead. This is needed
to resolve the bug that prevented title deletion in Calypso.
Fixes https://github.com/Automattic/wp-calypso/issues/10003
1. Test with https://github.com/Automattic/wp-calypso/pull/13327.
2. On your test Jetpack site with a Professional plan, navigate to `settings/traffic`.
3. Verify that custom title formats can now be deleted.
=> SEO Tools: Allow empty string to be passed as title format

modules/contact-form/grunion-contact-form.php
Some plugins override `wp_mail()` and replace PHPMailer with other libraries, like Zend Mail. Previously, we were relying on PHPMailer to correctly set the content type, but that never happens when other libraries are used. Because of that, the message can be sent out with a `text/plain` type, but contain HTML, making it difficult for users to read.
All plugins should respect the value of `wp_mail_content_type`, though, so this is a much more reliable method of setting the type to `text/html`.
Props georgestephanis, jeherve
Fixes #7003
1. Install the Postman SMTP or Gmail SMTP plugins from the w.org repo
1. Checkout `master`, and submit a contact form. You'll see the raw HTML because the content-type is `text/plain`
1. Checkout this branch and repeat the test. It should display in HTML …
=> Contact Form: Set message content type to restore compat with plugins

_inc/client/rest-api/index.js
Fixes #5217 
* Refactored the REST API component to make it more DRY.
* Adds a cache busting mechanism to address the problem of requests being cached.
* I had a really hard time reproducing the problem on my own server, but it could be reproduced on SiteGround shared hosting. If you enable the browser console and allow browser caching in the settings, you will see that some requests come back with `304 Not Modified`. My guess is that it's because the server sends back the `Last-Modified` header with the zero epoch time every time. If you can't reproduce it, try adding the header to API responses manually with this:
```
add_filter( 'rest_post_dispatch', function( $response, $server, $request ) {
$response->set_headers(
array_merge(
$response->get_headers(),
array(
'Last-Modified' => date( …
```
=> Add REST API cache busting mechanism.

modules/widgets/internet-defense-league.php
This is part of 185-gh-customization
This adds a wpcom widget to Jetpack. This is copied mostly verbatim from wpcom, with some small modifications for stats and the registration of the module.
* In your test sandbox, navigate to your Jetpack plugin and checkout this branch
* Navigate to the customizer /wp-admin/customize.php
* Click on widgets
* Then select a widget area
* Click add a widget
* With a connected Jetpack site, you should be able to search for Internet Defense League
* Add it to your sidebar
* The widget options should work, (different img types/visibility)
* Publish your page
* We should see that the Jetpack site now has an option of `widget_internet_defense_league_widget` which might have a shape like
=> Widgets: add missing internet-defense-league widget

_inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
* make sure AtD file is loaded before AtD_get_options is used
* include files once and don't suppress warnings
To test:
1. disable AtD
2. go to Jetpack > Admin and run this in JS Console
```js
jQuery.ajax( {
url: 'https://thesite.tld/wp-json/jetpack/v4/settings',
method: 'POST',
beforeSend: function ( xhr ) {
xhr.setRequestHeader( 'X-WP-Nonce', Initial_State.WP_API_nonce );
},
data: JSON.stringify( {
'onpublish': true
} ),
contentType: "application/json",
dataType: "json"
} ).done( function ( response ) {
console.log( response );
} ).error( function ( error ) {
console.log( error.responseText );
} );
```
It should succeed and not crash with an error like
```
br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function AtD_get_options() in …
```
=> Endpoints: make sure AtD file is loaded before AtD_get_options is used

class.jetpack-options.php, class.jetpack-xmlrpc-server.php
Since Jetpack 4.4, the Manage Module is now activated by default. We no longer need an XMLRPC method for it.
To test:
Add this PR to one of you Jetpack sites.
Test the various Jetpack Connect flows, and ensure there are no regressions.
Removing an no longer necessary XMLRPC method.
=> XMLRPC: remove activateManage method

sync/class.jetpack-sync-module-plugins.php, tests/php/sync/test_class.jetpack-sync-plugins.php
Jetpack Sync: Adding sync event for plugin edit
Jetpack Sync: Adding sync event for plugin edit
phpunit runs new test for this sync action
Add new action jetpack_edited_plugin when plugin is saved via editor
=> Jetpack Sync: Adding sync event for plugin edit

sync/class.jetpack-sync-module-woocommerce.php
This PR moves the extension of the whitelists to the constructor.
When we initialise all the modules, we first instantiate all sync modules and then we initialise the listeners: https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-modules.php#L73
Somehow Fixes #6887
=> Sync: Woo: Add filters before initialising listeners

sync/class.jetpack-sync-module-themes.php
Fixes issue when activating certain themes
```
Notice: Undefined index: some_sidebar_1 in /jetpack/sync/class.jetpack-sync-module-themes.php on line 200
Warning: array_diff(): Argument #1 is not an array in /jetpack/sync/class.jetpack-sync-module-themes.php on line 135
Warning: array_diff(): Argument #2 is not an array in /jetpack/sync/class.jetpack-sync-module-themes.php on line 114
Warning: array_diff(): Argument #2 is not an array in /jetpack/sync/class.jetpack-sync-module-themes.php on line 164
Warning: array_diff(): Argument #1 is not an array in /jetpack/sync/class.jetpack-sync-module-themes.php on line 168
```
Issue introduced in https://github.com/Automattic/jetpack/pull/6909/files#diff-37af365e9198e952a002bbf543cdcdcfR154
* make sure the sidebar index exists before fetching old …
=> Sync: make sure the sidebar index exists before fetching old widgets

.travis.yml, tests/run-travis.sh
Apparently the problem with foreign pull requests was that we couldn't install yarn by pulling a bash script directly from an URL. So we use `yarn` by installing it from `npm` instead. Hopefully one day Travis will allow using several languages for the same build: https://github.com/travis-ci/travis-ci/issues/4090
* Installing `yarn` using `npm`.
=> Fixes Travis builds for foreign pull requests.

package.json
Calypso requires `6.10.2` -> https://github.com/Automattic/wp-calypso/blob/master/package.json#L141
=> Update NodeJS required version to `6.10.2`

modules/masterbar/masterbar.php
Removed in https://github.com/Automattic/wp-calypso/pull/13342
This will bring a consistent state to both. The Customizer is now the preferred way to manage Menus.
=> Masterbar: Remove the Menus item to match WP.com

modules/widgets/flickr/form.php
It avoids issues when managing widgets in the customizer; you want to
be able to keep managing your widgets without losing your changes.
=> Flickr Widget: make sure external link opens in a new window.

modules/widgets/flickr.php
Instead, we will display a warning message to site admins to let them know
their widget doesn't work properly.
Try entering a Flickr Feed URL where all images are marked as private ([example](https://href.li/?https://api.flickr.com/services/feeds/photos_public.gne?id=154104018@N06&lang=en-us&format=rss_200)).
Here is how it currently looks:
(the link redirects to Flickr but no images are displayed there)
Here is how it looks for admins with this PR:
Reported here:
p8oabR-2x-p2
=> Flickr Widget: do not display widget table when there are no images

modules/widgets/eu-cookie-law/style.css
* Adds a `min-height` (equals to the sum of the button's height and the banner's paddings and borders) to the banner in order to keep the button inside, even when there's not enough content in the banner.
| --- | --- |
| <img width="733" alt="screen shot 2017-04-28 at 14 02 34" src="https://cloud.githubusercontent.com/assets/2070010/25529995/6af23e92-2c1c-11e7-9d9c-a15dddb5f429.png"> | <img width="734" alt="screen shot 2017-04-28 at 14 04 45" src="https://cloud.githubusercontent.com/assets/2070010/25530001/71ef8542-2c1c-11e7-9baf-0386a07cd6c5.png"> |
* Add the EU Cookie Law widget and set all radios to "Custom" and all fields to 1 character long strings.
* Check that the banner height is now big enough that the button is _inside_ the banner.
Reported here: p8oabR-2x-p2
=> EU Cookie Law Widget: Fix minimum height when content is a single line.

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
@yoavf can you please take a look at what I did to run it both on Jetpack and WordPress.com side. Should we do something like that for the `locale_variant` property as well?
=> Synchronizes the site settings endpoint.

class.jetpack.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
* Adds a mechanism that checks the existing token and generates a registration URL if it doesn't work.
* Disconnect your Jetpack, make sure it appears as disconnected both in wp-admin and in Calypso.
* Click the connect link.
* In the approval screen just leave it without clicking "Approve".
* Intentionally garble your token to simulate a non-functional Jetpack connection on the client side, you can do it by running this code as a filter once:
```
add_action( 'noop_wp_loaded', function() {
$token = Jetpack_Options::get_option( 'blog_token' ) . 'garbage';
Jetpack_Options::update_option( 'blog_token', $token );
} );
```
* You shouldn't be able to connect from wp-admin at all. Broken tokens result in different errors, most notorious of which is the following:
```
Invalid request, please go …
```
=> Added a mechanism to check the existing token.

modules/widgets/flickr.php
Building the feed ourselves avoids issues when a user enters the wrong RSS format, or URL format.
With that PR, one can now use the following feed formats, that will all be converted into a compatible Flickr RSS feed:
- https://www.flickr.com/services/feeds/photos_public.gne?id=34430197@N04&lang=en-us&format=rss
- https://api.flickr.com/services/feeds/groups_pool.gne?id=417611@N24&format=rss2
- https://api.flickr.com/services/feeds/groups_pool.gne?id=417611@N24&format=rss_200_enc
- https://api.flickr.com/services/feeds/groups_pool.gne?id=417611@N24
- https://api.flickr.com/services/feeds/groups_pool.gne?id=417611@N24&format=atom
- https://api.flickr.com/services/feeds/groups_pool.gne?id=417611@N24&format=rdf
- https://api.flickr.com/services/feeds/photos_public.gne?id=11023327@N08&lang=fr- …
=> Flickr Widget: build Feed URLs manually based on user or group ID

class.jetpack-cli.php
In testing the sync CLI commands, I noticed that the list of modules wasn't being printed correctly. This is because the array of modules is contained in the keys of the array, and not the values of the array.
So, we simply needed to get the array keys from the array for this to print correctly.
To test:
In a Jetpack site, run `wp jetpack sync start --modules=callables` and ensure that you get output like this:
`Initialized a new full sync with modules: callables`
=> CLI: Properly print list of modules when full syncing

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
This PR adds a Jetpack sync event for theme deletion, primarily for use by the Activity log.
Addition of  'jetpack_deleted_theme' action, which triggers sync action upon theme deletion.
phpunit tests new functionality
Addition of  'jetpack_deleted_theme' action
=> Jetpack Sync: Add sync event for theme deletion

class.json-api-endpoints.php
When calling endpoints with force=secure enforce the endpoint to relieve the request body by making a secure request to wpcom. 
By doing a secondary call to WordPress.com over https to get the post body. 
* 
*
=> API: Force secure endpoints

json-endpoints/jetpack/class.jetpack-json-api-user-connect-endpoint.php, json-endpoints/jetpack/json-api-jetpack-endpoints.php
This will allows us to connect a user after the user accepts an invitation from wpcom. 
* Create an api endpoint that will allow set a user 
Test the api endpoint. 
Does it produce the expected result?
=> API: Add connect user endpoint

.travis.yml, tests/run-travis.sh
Whilst testing #7065 and merging changes from #7074 I noticed this:
> https://travis-ci.org/Automattic/jetpack/jobs/226607567#L227
> _"npm WARN deprecated yarn@0.22.0: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install"_
So, per the above instructions is this PR using apt to install yarn
It also installs "stable main" so isn't locked to the yarn version `0.22.0` that was being used with npm previously, not sure what the reason was to pin to yarn 0.22.0?
=> Install yarn using apt

_inc/client/writing/custom-content-types.jsx
Just adding a dot there so that description for portofolios matches the description for testimonials. :-)
=> Settings: Add trailing period

sync/class.jetpack-sync-module-terms.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/test_class.jetpack-sync-terms.php
This change indicates whether the term save was a creation or an edit/update.
This change indicates whether the term save was a creation or an edit/update.
phpunit
=> Jetpack Sync: Sync term update action type

gulpfile.js
Follow up to #4067
* remove unexistent stylesheet from minification
=> CSS minification: remove unexistent stylesheet

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php
Fixes #7127
* Convert encoding of action link markup to UTF-8. This prevents from encoding issues occurring with non-latin characters. See #7127 for details.
* Change the language of your site to Bulgarian.
* Connect your site to WordPress.com.
* Go to `/plugins/jetpack/$site` in WordPress.com.
* Verify the plugins endpoint retrieves the non-latin copy properly:
* Verify the action link texts now appear properly:
=> JSON API: Fix encoding of action links

modules/widgets/eu-cookie-law/eu-cookie-law.js, modules/widgets/eu-cookie-law/style.css
Fixes 172-gh-customization (comment 299542578) reported by @designsimply 
Some themes applies specific CSS rules over widgets size and positioning.
In these cases it's possible that the EU Cookie Law Banner isn't sized or positioned as expected (which is: as large as the screen, and fixed to the bottom).
* Add a `width: auto` to the widget.
This is needed to prevent themes to apply a width to the banner.
* Add a `position: relative` to the widget internal wrapper.
This is needed to keep the "Close" button (which is absolutely positioned) to stay in its correct position, even when the widget positioning is overridden by the theme style.
* Enable the EU Cookie Law Banner widget.
* Activate a theme with specific widget positioning, such as Twenty Thirteen or Rebalance.
* Check that the …
=> EU Cookie Law Widget: Fix style on themes with specific widgets positioning

sync/class.jetpack-sync-module-updates.php, tests/php/sync/test_class.jetpack-sync-updates.php
The new action lets us know when core gets updated to a specific
version and it was autoupdated and if it was reinstalled.
* Send specific events that would allow us know when a site has autoupdated, updated or reinstalled core.
* Go to the wp-admin/update-core.php and click on the update core button. 
.com should get the `jetpack_sync_update_core_successfull` action with 4 arguments. 
* Update the core verions to help trigger the core update links. 
Do the same. And notice that we get jetpack_sync_update_core_successfull again but with different arguments. 
Let autoupdate update core and notice the same action. 
To the phpunit tests pass?
=> Sync: Add sync actions when core updates

json-endpoints/class.wpcom-json-api-post-endpoint.php
@vindl  please take a look at this one, because I have changed the way we check the meta key here. When using the object notation I would get `trying to get a property of non-object`.
=> Syncs post endpoint v1.0

json-endpoints/class.wpcom-json-api-list-media-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-update-site-homepage-endpoint.php, json-endpoints/class.wpcom-json-api-update-site-logo-endpoint.php
The sync process has been missing some of the files, this PR adds them and syncs one file that was present.
Pinging authors to make sure we're not adding anything that we're not expecting:
@retrofox @dbtlr @artpi @mjuhasz @sirbrillig 
TODO here: make sure `locale_variant` is nulled properly for Jetpack sites.
=> Synchronizing endpoints that were missing.

modules/videopress/class.jetpack-videopress.php
VideoPress attachments are currently added in as a mime-type of `video/videopress`. This is primarily so that we can delineate the difference between these, virtual entries, and the other types of video files that might be present.
Currently, we do not declare this mime-type as a video file to WordPress so when pulling up the media library for videos projects like the new [Core Media Widgets](https://github.com/xwp/wp-core-media-widgets/issues/160) are having problems seeing and uploading videos when VideoPress is enabled.
This PR adds in the mime type `video/videopress` to the `upload_mimes` and `wp_video_extensions` filters, which fixes this gap.
**Note: This is a blocker for getting the [Core Media Widgets](https://github.com/xwp/wp-core-media-widgets) feature plugin working. Can we …
=> The VideoPress mime-type is missing

class.photon.php
* Corrects logic error that defeated all uses of the `jetpack_photon_image_is_local` filter
* Hook `jetpack_photon_image_is_local` with and without this patch. Without the patch, the image wiill be Photon'd regardless of the filter's value.
Correct logic error that defeated the `jetpack_photon_image_is_local` filter.
=> Correct logic error that rendered `jetpack_photon_image_is_local` inoperable

class.jetpack.php
Plugins/site admins would logically assume `add_filter( 'jetpack_just_in_time_msgs', '__return_false' ); ` would disable JITM, but it may not work depending on load order. We should either update this to 9 so the above works or only activate JITM differently.
Example: https://meta.trac.wordpress.org/changeset/5323
See: https://meta.trac.wordpress.org/ticket/2811
cc: @iandunn @ocean90
=> JITM: Change activation to priority 9

sync/class.jetpack-sync-module-updates.php, tests/php/sync/test_class.jetpack-sync-updates.php
When the WP Mu Network updates it sets the wp db version is udpated in the DB.
This PR added an event that gets called when this happends.
* Sync when a mu site updates core across the whole network.
* Do the test pass? 
* update the value of wp_db_version in wp-includes/version.php 
* Go to the Network tab and update all the sites.
=> Add:  Core Update Network sync action

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Jetpack Sync: Add sync action for network/multisite enable and disable themes
Add sync action for network/multisite enable and disable themes
phpunit runs new tests when on multisite
Addition of jetpack_network_disabled_themes and jetpack_network_enabled_themes hooks
=> Jetpack Sync: Add sync action for network site enable and disable themes

class.photon.php
Pass default values to account for others applying the filter without passing all four args.
Every place we use these variables are already checked to ensure they are set, so there should be no harm in `null`ing them.
Fixes #7075 
* Use the Fludia theme at https://wordpress.org/themes/fluida/
* Without patch, see PHP Warnings in the error log
* With patch, no errors.
* Verify other image content (on that theme or any other) is still applying Photon values
=> Photon: Defensive coding on filtered function

_inc/lib/icalendar-reader.php
Fixes #7162
WordPress defines a few specific time constants:
https://github.com/WordPress/WordPress/blob/4.7.4/wp-includes/default-constants.php#L120-L125
`HOUR_IN_MINUTES` is not one of them and is only defined on WordPress.com. Let's not use it.
* Upcoming Events: use correct time constant to define an hour.
=> iCalendar: use WP time constant instead of non-existing constant.

_inc/client/components/apps-card/index.jsx, _inc/client/main.jsx
Reported in p6TEKc-1dr-p2
This removes the apps card from Jumpstart view shown here: 
It should still show on all other pages. 
To test: 
- Delete the `dismiss_dash_app_card` option `delete_option( 'dismiss_dash_app_card' )` , or start a new site.  
- Click "reset options" in the footer of Jetpack.  Or connect a new site.  
- Make sure there's no card on Jumpstart
- Make sure the card shows on all other pages after jump-starting.
=> Remove Apps card from Jumpstart view

_inc/client/components/settings-card/style.scss, _inc/client/searchable-modules/README.md, _inc/client/searchable-modules/index.jsx, _inc/client/settings/index.jsx
Implements @MichaelArestad "one-way activation" suggestion in #6788 
This PR adds a new component, `<SearchableModules />`, which has a hard-coded list of modules available for search.  It's hard-coded, because search already inherits the cards from existing tabs, and has specific settings configs.  These features will all be surfaced with the same card style for each, in order to simplify this code.  
The card is populated with the Name/descriptions from the module headers themselves.  We can change the copy of them, if so desired. 
If the module is not active, it will show a banner like this: 
If the module is active, we'll continue to show the card with the learn more link:
Please test the following (hard-coded) modules that will now appear in search: 
- 'contact-form',
- 'custom-css', …
=> Surface all modules on search and allow "one-way" activation.  

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Add sync action for widget edit
Add sync action for widget edit
phpunit runs the new test
Adds new do_action for 'jetpack_widget_edited'
=> Jetpack Sync: Add sync action for widget edit

class.json-api-endpoints.php, class.json-api.php
This allows to distinguish between WordPress.com and Jetpack usage in one place.
@singerb tagging you for a review because you have worked on removing the method before.
=> Brings back get_avatar_url method.

.travis.yml
Fixes #7124 
* Using directories instead of cache aliases for Travis caching.
=> Using directories instead of cache aliases for Travis caching.

_inc/client/at-a-glance/photon.jsx
* update wording in Photon dash item to remove the Photon word
Note: if you toggle this dash item, you might notice the message "Activating Photon". The Photon word (and the notice itself) will be updated by https://github.com/Automattic/jetpack/pull/7188 and the Photon word removed.
=> Settings UI: update wording in Photon dash item

modules/shortcodes/js/jmpress.js
props georgestephanis, related GitHub issue and related PR/merge: https://github.com/jmpressjs/jmpress.js/issues/185
This commit syncs r134654-wpcom.
=> jspress Javascript lib: fixing bad jQuery selector.

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
Adds the export event. Which gets fired when we export data. 
*
* Export content and see the event show up.
=> Sync: Add export event

modules/wordads/wordads.php
WordAds will inject the inline JS into `the_content` and `the_excerpt`. This won't work very well since it's XML and none of the header or scripts hooks are firing :)
The PR will bail early if being ran while `is_feed()` is true.
Real like failure (from https://micro.blog/bjk , powered via RSS feed from kraft.blog):
XML before patch:
XML after patch:
=> WordAds: Do not try to inject ad when in a feed

json-endpoints.php, json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
This pulls the change from r155891-wpcom (which allows setting posts_per_page from the settings endpoint) downstream
=> Sync API settings posts_per_page

class.jetpack-cli.php
When running the `jetpack status` command, it's useful to know who the primary connection owner is.
* Adds an additional line of output to the `jetpack status` command to include the email of the primary connection owner.
* When connected, run `wp jetpack status` and `wp jetpack status full`. Verify that the correct connection owner information is displayed.
* When disconnected, verify that this information is not displayed.
=> cli: Add info about the primary account owner

modules/stats.php
Fixes #204
In some broken cases, `$count_roles` can be an empty string (which I can only think is due to an object cache issues or something is blocking it from setting options since `stats_get_option` calls `stats_get_options`, which runs `stats_upgrade_options` to set the options), so we can check it the var is an array before we use it as such.
Before this, a warning would be thrown and `NULL` returned from `array_intersect`, so the same logic should still happen without the warning.
=> Stats: Confirm value is an array before treating it as one

modules/widgets/contact-info.php
Fixes an issue where email address doesn't show up in contact widget.
To reproduce:
- add a contact widget to your site
- in the email field, add an email address that has a trailing space
- note that the email address does not get rendered
To test:
- apply this PR to your site, and note that the issue is fixed
Props @BenjaminHilton for reporting issue.
=> Widgets: trim white space from email before validating

class.json-api-endpoints.php
Change wp_get_attachment_url for get_attached_file to avoid breaking API responses on VIP sites.
Fixes #
*
*
=> Sync from wpcom r156638

bin/partner-cancel.sh, bin/partner-provision.sh, class.jetpack-cli.php
Fixes some issues with the new return signature of the generate_secrets method, and adds a new parameter that selected partners can use to assign a specific WPCOM user to be the master user for a site.
Also makes the plan parameter optional.
=> JPS: New params and compatibility fixes

modules/comments/comments.php
In Safari, if the site is http and the iframe loads https, it throws a warning about submitting a secure form to an insecure site.
This is because of the following path:
* http site loading an https iframe (no problem)
* https iframe submitting a form (no problem)
* the iframe takes the submission from the https form to the wp-comments-post.php of the http site (this is the problem)
While we should SSL all the things, we may need to rethink this in light of confusion of scary security warnings. 
As reported in 3216198-t
=> Comments: Revert "Always use https for jetpack.wordpress.com"

modules/shortcodes/recipe.php, sal/class.json-api-date.php
This PR is set to be merged into `update/recipe-shortcode-wpcom-merge`, as it relies on the changes proposed in #7125. I'll update the base branch if #7125 gets merged.
We previously displayed the total recipe time as the user provided it in the shortcode.
While that works on the site, that format isn't compatible with Schema.org.
Search engines relying on Schema.org to display recipe previews expect the recipe time to use ISO 8601 formatted duration interval.
This PR does 2 things:
- It adds a new shared function allowing you to convert any user-inputted duration into ISO 8601 formatted duration.
- It uses the shared function to output a new `time` tag in the recipe output, where that formatted duration is added as a
datetime attribute.
Reported here: …
=> Shortcodes: fix recipe time display to be compatible with Schema.org

json-endpoints/class.wpcom-json-api-list-roles-endpoint.php
I think the it's stats card is trying to poll roles. 
Anyway, this method that's used now has been deprecated since WP 4.7.  
To reproduce the error: 
```
[03-May-2017 18:44:02 UTC] PHP Stack trace:
[03-May-2017 18:44:02 UTC] PHP   1. {main}() /home/dereksma/public_html/xmlrpc.php:0
[03-May-2017 18:44:02 UTC] PHP   2. wp_xmlrpc_server->serve_request() /home/dereksma/public_html/xmlrpc.php:84
[03-May-2017 18:44:02 UTC] PHP   3. IXR_Server->IXR_Server() /home/dereksma/public_html/wp-includes/class-wp-xmlrpc-server.php:197
[03-May-2017 18:44:02 UTC] PHP   4. IXR_Server->__construct() /home/dereksma/public_html/wp-includes/IXR/class-IXR-server.php:35
[03-May-2017 18:44:02 UTC] PHP   5. IXR_Server->serve() /home/dereksma/public_html/wp-includes/IXR/class-IXR-server.php:27
[03-May-2017 18:44:02 …
```
=> JSON API: replace deprecated method

sync/class.jetpack-sync-module-options.php, tests/php/sync/test_class.jetpack-sync-full.php
Fixes #7199, lets not sync full sync the options that do not exist.
Currently we send the key to with the null value to when options do not exits. Which is not ideal. It would be much better if we just not sent the key at all. This PR fixed #7199.
* Remove non-existent options during full sync.
* Do the unit test pass? 
@nabsul Can you test this to make sure this works for you as expected?
=> Sync: Full sync options fix

modules/publicize/publicize-jetpack.php, modules/publicize/publicize.php, modules/theme-tools/social-links.php
PHP 7.1 returns a Fatal Error if get_services() is invoked without any argument.
Providing an argument should fix that.
Reported here:
https://wordpress.org/support/topic/publicize-and-wordpress-customizer/
- Related: 3bbf0603784f5eab435316e49cb7d2fb64f88abe where the change was introduced.
- Master issue: #6106
1. On a server running PHP 7.1, enable a theme using Social Links, like [Ryu](https://wordpress.org/themes/ryu/).
2. Go to Appearance > Customize.
3. Make sure you can set up Social Links without creating any errors.
* Social Links: avoid Fatal Errors on sites running PHP 7.1.
=> Social Links: pass an argument to get_services() to avoid errors.

_inc/client/security/antispam.jsx, _inc/client/security/backups-scan.jsx, _inc/client/security/index.jsx, _inc/client/security/protect.jsx, _inc/client/security/sso.jsx
Applies the `class` react-codemod and Calypso-tuned prettier to use ES6 classes and Calypso styleguides.
```sh
npm i -g jscodeshift
git clone https://github.com/reactjs/react-codemod ~/react-codemod
cd jetpack
npm i "git+https://github.com/Automattic/calypso-prettier.git#calypso-1.1"
jscodeshift -t ~/react-codemod/transforms/class.js  _inc/client/security/*jsx
node_modules/.bin/prettier --write _inc/client/security/* 
git commit -a -m 'Es6ify and run prettier on security components'
```
1. With a Professional plan active on the site, check that the security tab components render properly and work as expected
=> Admin Page: Es6ify and use prettier on security components

json-endpoints.php, json-endpoints/class.wpcom-json-api-list-posts-v1-2-endpoint.php
This introduces a new parameter to the "list posts" endpoint (it creates a new version of that endpoint). That param is `exclude_private_types` and can only be used in conjunction with `type=any`, as noted in new docs. This is useful for cases where we want to show the user only posts that their visitors can access (eg. include posts, pages, portfolio, but don't include feedback and other private types).
See Phabricator Diff 4766 for more info
API change required for https://github.com/Automattic/wp-calypso/pull/11887
This commit syncs r156614-wpcom.
*
* Same as in the original diff
=> API: Add new endpoint version for listing posts

modules/videopress/editor-media-view.php
`[18-May-2017 03:45:18 America/New_York] PHP Notice:  Trying to get property of non-object in
wp-content/plugins/jetpack/modules/videopress/editor-media-view.php on line 104`
* VideoPress: fix notice when get_current_screen() is null.
=> VideoPress: fix notice when get_current_screen() is null.

sync/class.jetpack-sync-module-plugins.php
Fixes the Fatal error reported [here](https://wordpress.org/support/topic/php-fatal-error-every-few-minutes/):
```
[17-May-2017 17:05:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_plugins() in /wp-content/plugins/jetpack/sync/class.jetpack-sync-module-plugins.php:114
Stack trace:
#0 /wp-includes/class-wp-hook.php(300): Jetpack_Sync_Module_Plugins->expand_plugin_data(Array)
#1 /wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /wp-content/plugins/jetpack/sync/class.jetpack-sync-sender.php(145): apply_filters('jetpack_sync_be...', Array, 1)
#3 /wp-content/plugins/jetpack/sync/class.jetpack-sync-sender.php(193): Jetpack_Sync_Sender->get_items_to_send(Object(Jetpack_Sync_Queue_Buffer), true)
#4 …
```
=> Sync: make sure get_plugins exists before to use it.

modules/publicize/publicize-jetpack.php
`[18-May-2017 06:07:11 America/New_York] PHP Notice:  Trying to get property of non-object in
wp-content/plugins/jetpack/modules/publicize/publicize-jetpack.php on line 515`
* Publicize: fix potential PHP notice
=> Publicize: fix notice when $pages is set to false.

_inc/client/pro-status/index.jsx, _inc/client/security/backups-scan.jsx, modules/omnisearch/omnisearch-rtl.css
Fixes #6995
The dev tools won't work in testing, because the dev tools only changes the plan class, and it's possible to have these features active without a Jetpack plan.  
This fixes an issue when we were showing the wrong text on personal plan.  It also re-writes the logic to show the content to make it more readable.
It also fixes an issue where we were not showing the `set up` button on professional plans if scan was not enabled for some reason.
To test: You should see the following statuses
**Free plan, no features active**
**Backups only enabled, (personal plan)**
**Backups and scan enabled (premium/business)**
**Personal plan, not enabled yet**
**Premium/business plan, but not enabled yet**
=> Backups/scan card: Fix broken status for personal plan.

json-endpoints/class.wpcom-json-api-update-comment-endpoint.php
The logic in the /sites/s/comments POST endpoint was returning early 672-gh-io
This commit syncs r156341-wpcom.
=> WPCOM REST API: Do Not Return Early From /comments POST

modules/contact-form/admin.php, modules/contact-form/grunion-contact-form.php
Fixes #7179
Send all outbound Grunion messages through a wrapper that ensures they are correctly rendered as HTML.
1. Add the mu-plugin below to your installation
1. Checkout `master`
1. Send an email. It will be flagged as spam because of the filter.
1. Browse to `Feedback > Spam`
1. Click `Not Spam`
1. View the email. It will have a `text/plain` content type, and show raw HTML in the body
1. Checkout this branch and repeat the steps above. It should have a `text/html` content type and show rendered HTML in the body.
1. Disable the filter and test messages that aren't flagged as spam. They should also have the `text/html` content-type and show rendered HTML.
```php
add_filter( 'jetpack_contact_form_is_spam', function( $is_spam, $akismet_values ) {
return true;
}, 10, 2 );
```
=> Contact Form: Send all emails through wrapper to ensure consistency

modules/videopress/class.jetpack-videopress.php, modules/videopress/js/media-video-widget-extensions.js, modules/videopress/shortcode.php
The new Media Widgets are going to be released in WordPress 4.8, and currently VideoPress does not work seamlessly with the new Video Media Widget.  The issue arises when uploading a new video from within the media modal launched by the Video Widget, and the subsequent `url` from the attachment is returned as the attachment page - not the CDN VideoPress file or oembed url.
This PR seeks to fix that problem by extending a few methods on the Video Media Widget, and adding logic to the `wp_video_shortcode` override so VideoPress oembed url's get rendered like they do within the editor for example.
Further details and discussion:
https://core.trac.wordpress.org/ticket/40808
https://github.com/xwp/wp-core-media-widgets/issues/160
* You must be running trunk, or a nightly build, ~and manually …
=> Add support for VideoPress in core Media Video Widget.

_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-builder.php, _inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-parser.php, class.jetpack-modules-list-table.php, modules/module-headings.php, modules/search.php, modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php
Adds the Search module, which offloads site search to WordPress.com, powered by Elasticsearch.
Includes Aggregation (Facets) support and corresponding Widget.
Is currently ‘headless’ - no admin UI exists so the module must be enabled manually.
=> Search: Add Search module

modules/widgets/flickr.php, modules/widgets/flickr/form.php
Fixes #7085
* Add new "Large" size.
* Rename "Small" with "Medium" to be consistent with WordPress media sizes.
* Replace `<select>` with `<input type="radio>`.
* Changes the logic of the image `src` retrieval from the RSS feed.
| --- | --- |
| <img width="336" alt="screen shot 2017-04-28 at 18 46 40" src="https://cloud.githubusercontent.com/assets/2070010/25540486/229c71ea-2c43-11e7-83f7-a614d1eedf06.png"> | <img width="339" alt="screen shot 2017-04-28 at 18 46 19" src="https://cloud.githubusercontent.com/assets/2070010/25540478/1b72248c-2c43-11e7-9177-baf9104568ef.png"> |
* Activate the Flickr widget.
* Check that all three sizes output images as expected.
=> Flickr Widget: Add new large size

_inc/client/components/dash-item/index.jsx
* when site is in Dev Mode, link the Updates needed warning button to the WP Admin > Updates screen since wordpress.com won't work for this site in Dev Mode
* put site in Dev Mode, make sure you have outdated plugins. Click the Updates needed yellow button and make sure it goes to WP Admin > Updates.
Settings UI: in Dev Mode
=> Settings UI: when site is in Dev Mode, link Updates needed to its WP Admin screen

class.jetpack-options.php, class.photon.php, modules/widgets.php, modules/widgets/image-widget.php, modules/widgets/migrate-to-core/image-widget.php
There's a proposal for a new core image widget in the works, which the core customizer folks want to see merged in WP 4.8. See [the the merge proposal](https://make.wordpress.org/core/2017/04/12/image-widget-merge-proposal/) & https://github.com/xwp/wp-core-media-widgets/issues/43 for more info.
The proposed core widget is a much nicer experience for adding an image, so we should migrate our users' widgets to the new widget (if available), and not register the Jetpack image widget. This PR adds a function that will run once in wp-admin to switch over any Jetpack image widgets to the core image widget.
Additionally this PR adds support for Photon in the widget ⚡️ 
cc @obenland (since the majority of the code came from your comment …
=> Widgets: Migrate Image Widget instances to proposed core widget

modules/seo-tools.php, modules/seo-tools/jetpack-seo-utils.php
When SEO plugins like Yoast SEO or All in one SEO are installed on
Jetpack site, SEO Tools should stop modifying the meta tags.
Related PR: https://github.com/Automattic/wp-calypso/pull/14526
1. Use test Jetpack site with Professional plan and SEO Tools module enabled.
2. In Calypso, navigate to `settings/traffic` and adjust some of the SEO settings.
3. Verify that changes have taken effect on you test site's front end (inspect meta fields).
4. Install Yoast SEO or All in one SEO pack.
5. Verify that changes from step 3 are no longer present.
=> SEO Tools: Suppress output if conflicting SEO plugin is active

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
Jetpack Sync sending whether is_auto_save with wp_insert_post sync_action
Addition of is_auto_save in wp_insert_post payload
* Run phpunit
=> Jetpack Sync: Sending $_SERVER['REQUEST_URI'] with wp_insert_post action

modules/shortcodes/recipe.php, sal/class.json-api-date.php
* Bring changes from WordPress.com over to Jetpack to sync the Recipe shortcode.
* Insert a recipe in a new post, by following the instructions [here](https://en.support.wordpress.com/recipes/)
* Publish your post.
* Run your post through [Google's Rich Snippets testing tool](https://search.google.com/structured-data/testing-tool/u/0/) and make sure no errors are returned. You will see some warnings but those are okay for now.
* Shortcodes: update schema.org markup for the Recipe shortcode.
=> Shortcodes: update Recipe shortcode from WordPress.com

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Previously we were no passing in the widget name and the sidebar name. but instead were just passing in the ids. Which are not enough to build a user friendly Activity log. 
We are adding the names the way we are so that they are backwards compatible if someone else is using the do_actions already. 
* In this pr we are adding the names of the sidebar and the widget whenever possible 
* Do the test pass? Do it pass when testing things manually
=> Sync: Update widgets so that we pass in the Widget name and Sidebar name when ever possible

_inc/client/writing/custom-content-types.jsx
The Portfolio shortcode is `portfolio`, not `portfolios`.
Reported here:
https://wordpress.org/support/topic/mistakenly-written-shortcode/
* Admin Page: update shortcode name in portfolio card.
=> Admin Page: update shortcode name in portfolio card.

modules/masterbar/overrides.css
Previously, WordPress.com Toolbar sub-menus were appearing instantly. This restores the slide in animation in order to make it consistent with WP.com side.
Fixes https://github.com/Automattic/jetpack/issues/6966
1. Use your test Jetpack site with WordPress.com Toolbar module enabled.
2. Navigate to your site's front end or `wp-admin`. 
3. Try opening masterbar's sub-menus (e.g. My Sites, Reader, Me, or Notifications). 
4. Verify that slide in animation is now present.
=> WordPress.com Toolbar: add slide in animation for submenus

class.photon.php
Fixes warning
```
Deprecated: Non-static method Jetpack_Photon::filter_the_image_widget() should not be called statically in /wp-includes/class-wp-hook.php on line 
```
* declare `filter_the_image_widget` as static so it can be called statically
* make sure you don't get that warning
No changelog required since this is a patch for the image widget migration included in this same version
=> Photon: the new filter_the_image_widget must be static

class.jetpack-cli.php
While testing D5777 with the following:
```
bash partner-provision.sh --partner_id=.... --partner_secret=.... --user_id=... --plan=premium
```
I got the following warning:
```
Notice: Undefined property: stdClass::$message in .....public/wordpress/wp-content/plugins/jetpack/class.jetpack-cli.php on line 847
```
This PR ensures that `$token->message` is set before we try and use it, and if it's not set, we use empty string.
To test, you could follow instructions on D5777, or ping @gravityrail or myself.
=> CLI: Fix potential undefined property issue when provisioning partner key

class.jetpack.php, modules/seo-tools/jetpack-seo.php
Since we are already setting the `<title>` tags correctly, we no longer need to use the `<meta name="title" ...>` tag.
Fixes #7190
1. Use Jetpack test site with a professional plan. 
2. In Calypso, navigate to `settings/traffic/{siteSlug}`.
3. Set custom title formats for that site.
4. Verify that those custom title formats are no longer included in `<meta name="title" ...>` tags.
=> SEO Tools: remove obsolete meta title tag

class.jetpack-cli.php
While testing D5777 some more, I hit an undefined index notice:
```
Notice: Undefined index: force_register in ....wordpress/wp-content/plugins/jetpack/class.jetpack-cli.php on line 875
```
To test this PR, you can follow the instructions in D5777 to setup the WPCOM side or you can ping @gravityrail or myself for assistance with testing steps.
You'll then use something like this to test on the Jetpack side:
```
bash partner-provision.sh --partner_id=.... --partner_secret=.... --user_id=... --plan=premium
```
=> CLI: Fixes undefined warning when provisioning a partner plan

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
Adds an do_action that gets synced after an import happends.
* Start listening to jetpack_sync_import_end that happends after an import has finished.
* Test different importers:
- WP importer
- Blogger Importer
- Tumblr Importer
- Live journal (I wasn't able to get this one to work )
- RSS
- woo tax importer
Do you see the events as expected? 
Do the test pass?
=> Sync: Add import finished event

modules/sitemaps/sitemap-builder.php
Fixes #6822
This borrows from the same approaches used by Core to prepare content for RSS feeds, which would pass XML validation.
=> Sitemaps: Use proper encoding

class.jetpack-client.php
Requests made by `wpcom_json_api_request_as_blog()` do not, by default,
send their data as JSON (despite the name of the function) because there
is no `content-type: application/json` header. This can cause issues in
certain endpoints that expect data as JSON.
This change allows sending additional headers in the `$args` array to
`wpcom_json_api_request_as_blog()`, so that it can be used to specify
`content-type` if necessary.
Related to #6813 as they are both needed to communicate properly with v2 endpoints.
=> Allow passing headers to `Jetpack_Client::wpcom_json_api_request_as_blog`

class.jetpack-jitm.php
In order to avoid https://core.trac.wordpress.org/ticket/15058, we should hash the transient key. 
* Verify the data is stored in the transient with a hashed key
=> JITMs: hash the jitm path

class.jetpack-cli.php, class.jetpack-client-server.php
In some cases, we want to immediately connect Jetpack Start master users to a specific user on WordPress.com. 
This PR patches the partner-provision process so that if a user can be immediately authorized, the token is returned and inserted into the DB, and appropriate modules are enabled exactly as if they'd gone through the authorize API itself.
This change also adds a new filter, `jetpack_start_enable_sso`, which can be used to prevent auto-enabling SSO for partners who don't want that.
It also increases timeouts as sometimes provisioning can take a while.
=> Store user tokens if returned by Jetpack Start

class.jetpack.php
1. When redirecting from an admin register link, the redirect parameter was ignored. It's now passed in to `build_connect_url()`.
2. When building a register connect URL, the `redirect` query arg wasn't being added, and now it is.
1. Use `Jetpack::init()->build_connect_url` **with a custom redirect parameter** to add a button with the connect URL
2. If the site has not yet been registered, `build_connect_url` returns an admin URL with the query `action=register`, but the redirect param is not passed in
3. After registration, `build_connect_url` is used again, but the redirect parameter is not passed in
This PR makes sure the redirect parameter is used in both places.
1. Install Jetpack on your site (from `master`)
2. Install and activate …
=> Register connect URL: use 'redirect' query parameter when building connect URL

scss/organisms/_banners.scss
Adjusting full screen connection banner to avoid visual clash with the akismet banner. Text from the akismet banner sits above the full screen connection banner within jetpack.
Fixes: https://github.com/Automattic/jetpack/issues/7173
**Before:**
**After:**
To Test:
1. Install the Akismet plugin on your site. Do not configure it. You'll see this banner in the Plugins page:
2. Install and activate the Jetpack plugin.
3. Some of the text from the Akismet banner appears in Jetpack's full connection banner.
=> fix / Full Screen Connection clash with akismet banner

class.jetpack-cli.php
Removes some debugging output from Jetpack Start's partner-provision command.
=> Remove spurious output from JPS

class.jetpack-jitm.php
Removes a misc `force=wpcom` from the jitm api call
* none
Remove misc entry from wpcom api call
=> JITMS: Remove force=wpcom

bin/partner-cancel.sh, bin/partner-provision.sh
Allows passing --url to the partner provision and cancel scripts, which helps with provisioning in a multisite environment.
=> Add support for --url for multisite

json-endpoints/jetpack/class.jetpack-json-api-get-comment-backup-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-get-option-backup-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-get-post-backup-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-get-term-backup-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-get-user-backup-endpoint.php, json-endpoints/jetpack/json-api-jetpack-endpoints.php
* Add API endpoints for fetching backups of: 
* Users
* Comments
* Options
* Terms
* Term taxonomies
* Using site auth token, GET the following REST paths: 
* `/sites/$site_id/comments/$comment_id/backup`
* `/sites/$site_id/options/backup?name=siteurl`
* `/sites/$site_id/terms/$term_id/backup`
* `/sites/$site_id/term-taxonomies/backup?name=category`
* `/sites/$site_id/users/$user_id/backup`
This PR replaces #6758 since I mucked up a merge and muddied it all up. :)
=> New API endpoints for backups

modules/videopress/editor-media-view.php
Issue introduced in #7229
Reported in p8oabR-3s-p2
=> VideoPress: avoid Fatal when get_current_screen() isn't defined

_inc/jetpack-jitm.js
Supersedes #7268 
Instead of being flexible and handling the possibility of more than one jitm, let's be real. Just replace the wrapper with the first jitm and call it a day.
@jeffgolenski, I don't know if you had anything else that needs to go into this?
1. view a jitm
2. notice no styling issues
=> Replace jitm wrapper div with jitm div

scss/jetpack-admin-jitm.scss
Had to make a classname change after @withinboredom [refactor](https://github.com/Automattic/jetpack/pull/7289) to make some styles from [this former PR](https://github.com/Automattic/jetpack/pull/7268) work again. This PR ensures a proper margin is applied to the JITM
:shakes fist: applies label: `cleanup-after-rob` haha
After: 
Everything appears as it should as seen [in this PR](https://github.com/Automattic/jetpack/pull/7268)
=> JITM classname change

class.jetpack-jitm.php, class.jetpack-options.php, class.jetpack.php, sync/class.jetpack-sync-actions.php
See p1496182959940456-slack-jpop-growth for some background. We basically want to not bust the cache too often and cause a degraded experience for users, or use up all their db queries if they have a quota.
This reverts an earlier commit (that made caching super-passive aggressive) and makes the caching logic much more aggressive (only bust the cache if a plugin activation changes). It also uses transients to avoid hitting the database at all, when the site has a caching layer.
The fact that any of these keys may be evicted at any time doesn't really affect much. Also, the values are going to be fairly small, so they'd be in smaller slabs than most options, which makes them less likely to be evicted. (In theory...) But like I said, won't affect much if they are evicted.
The easiest way to …
=> Sync: avoid busting cache too often

sync/class.jetpack-sync-defaults.php
Currently we don't track how much memory sites have available. 
This will allow us to 
* Sync WP_MAX_MEMORY_LIMIT and WP_MEMORY_LIMIT so that we know how much memory sites have available to them since low memory limits can sometimes be an indicator of a issues. 
* Do the test pass? Update the memory limit does the newly defined memory limit get updated on the .com side?
=> Sync: Sync WordPress defined memory limit constants

class.json-api.php
If the filtered key is an object rather than an array, the request will
fatal because this tries to assign the value using `[ $key ]` rather
than `->$key` notation.
* Ensure that the correct assignment syntax is used for a filtered request result.
=> REST API: Fix object/array assignment issue in request filtering.

modules/shortcodes/class.filter-embedded-html-objects.php
When a server lacks `libxml` or `SimpleXML`, we hard fatal. We can be a bit more defensive for a better user experience.
This is coming up since, at least, Ubuntu's de factor PHP 7 package doesn't include all the libraries the PHP5 package did. Core added a similar check in https://core.trac.wordpress.org/changeset/38883
=> Shortcodes: Trigger error when required PHP libraries not included

json-endpoints/class.wpcom-json-api-get-site-endpoint.php, sal/class.json-api-site-base.php
Differential Revision: D5942-code
This commit syncs r157602-wpcom.
Adds the blog_public option to the options returned from the wpcom /me/sites endpoint.  Centralizes the option retrieval to class.json-api-site-base.php for consistency.
Confirm that the option is properly returned with the list of sites in the /me/sites endpoint.
=> REST API: Includes blog_public to the list of returned options from /me/sites

bin/partner-cancel.sh, bin/partner-provision.sh, class.jetpack-cli.php
Previously we used the proprietary `--user-id` flag. This patch uses --user instead, which allows email, login or ID.
In addition, it tries to use the master user for provisioning plans, if available. This makes provisioning plans MUCH easier and more reliable if the Jetpack site is already connected.
Finally, this patch tries to skip non-Jetpack plugins when booting wp-cli. This improves security and reliability.
=> Use standard --user wp-cli argument, and small fixes

sync/class.jetpack-sync-module-updates.php
Received a report from @richardmtl that a site running Jetpack 5.0 got this error:
```
Warning: Invalid
argument supplied for foreach() in
/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-updates.php on line
203
```
If applied, this patch will check for correct properties before expanding themes. If the properties are not found, the themes will not be expanded.
To test:
phpunit
=> Sync: check for properties before expanding themes

json-endpoints.php
r157700-wpcom allowed the site endpoint to pre-emptively ignore fields and options passed. This teaches the API to pass along the options value if it is supplied. Fields are special, and specified on the root endpoint class.
This commit syncs r157706-wpcom.
=> Sites: Add options to the query arguments to pick them when limiting

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-site-endpoint.php
Summary: Currently meta expansion can see and use the query args passed to the main request. This doesn't really make sense, especially for things like `fields` and `options`, which can't apply to both the main request and the meta requests equally. Instead, remove the query args when processing meta requests and replace them after.
Reviewers: bluefuton
Differential Revision: D5926-code
This commit syncs r157700-wpcom.
This commit syncs r157706-wpcom.
=> REST: Disable query args for meta expansion

.travis.yml
Since WordPress 4.8 came out, we're no longer testing against WordPress 4.6, so it's safe to move PHP 7.1 to the regular matrix and catch failures there.
=> Moved PHP 7.1 to regular Travis matrix not allowing it to fail anymore.

modules/videopress/class.jetpack-videopress.php
* Removes some jitm code that was hiding outside of the original jitm class
* The original warning is replaced by D5960-code
* No PHP warning appears on `/wp-admin/media-new.php`
=> JITM: Remove obsolete videopress warning

modules/masterbar/masterbar.php, modules/masterbar/overrides.css
Previously, Masterbar was removing the dashboard menu item that was used
to enable access to wp-admin menu items on smaller screen sizes. Now that
menu item is restored, with some additional styling fixes that are needed to
resolve incorrect positioning on screens larger than 480px.
Fixes https://github.com/Automattic/jetpack/issues/6914
1. On a Jetpack site, enable the WordPress.com toolbar.
2. Navigate to `wp-admin` and view it in smaller screen size (<780px).
3. Verify that you see the icon to toggle the `wp-admin` menu items.
=> WordPress.com Toolbar: restore access to wp-admin menu items on mobile

class.photon.php
Fixes #7302 
Uses `wp_attachment_url` instead of our custom job to account for images uploaded before WordPress 2.7.
Test via looking at the srcset array for a post with an image uploaded before 2.7. Previously, it had the full server path to the image in the URL. After this URL, have the correct URL.
@westonruter - Would you be game to give this a test on your site?
=> Photon: Use wp_get_attachment_url to support very old images

bin/partner-provision.sh, class.jetpack-cli.php
Partners sometimes want an enhanced onboarding flow that can increase customer success.
This PR provides the foundation for instructing Jetpack Start to direct the user into an onboarding flow during the Jetpack Connect process.
Testing:
- run partner-provision.sh with `--onboarding=1` argument
- when WPCOM redirects you to the Jetpack Connect flow, check that the `onboarding=1` option was passed in the GET params.
=> Add Jetpack Onboarding option for partners

modules/masterbar/masterbar.php
We should guard against possible malicious translations or plugins that might filter them in Masterbar's menu items. Related discussion: https://github.com/Automattic/jetpack/pull/7369#pullrequestreview-45579459
* Change occurrences of `__()` and `_x()`, into `esc_html__()` and `esc_html_x()` respectively.
* Run your Jetpack test site with WordPress.com Toolbar module enabled, and verify that all menu items are still displayed correctly.
=> WordPress.com Toolbar: sanitize translations

modules/masterbar/masterbar.php
Syncing the Masterbar with the Calypso version that now has View Site (for Jetpack sites) item bellow Blog info.
Fixes https://github.com/Automattic/jetpack/issues/6877
Depends on: D6074-code
WP.com side (needed for styles):
* Apply D6074-code to your sandbox.
* Sandbox `s0.wp.com`, `s1.wp.com`, and `s2.wp.com`.
Jetpack side: 
* Open up `wp-admin` of your test Jetpack site and verify that Site Preview item is present in My Sites menu.
* View the same menu on site's front end and verify that Site Preview is not present.
Before:
After: 
Masterbar: added a View Site item to My Sites menu that launches the front end of the current site.
=> WordPress.com Toolbar: Add View Site item to My Sites menu

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes #6970
To reproduce: 
- Free plan
- With VaultPress active
- Force this to return `false` https://github.com/Automattic/jetpack/pull/7286/files#diff-2ccec9069213650359171727de9a2471R1331
You'll see that the API returns nothing, which our UI can't handle and chokes.  We should be returning something here that the API can handle.
=> VaultPress: fix errors when $vaultpress->contact_service() returned false 

modules/widgets/eu-cookie-law.php, modules/widgets/eu-cookie-law/eu-cookie-law.js, modules/widgets/eu-cookie-law/style.css, modules/widgets/eu-cookie-law/widget.php
Fixes #7285 
* Move all the checks pertaining to the EU Cookie Law Banner cookie to JavaScript.
* Remove the PHP fallbacks for users without JavaScript.
* As the widget is now always loaded in PHP, it starts with `display: none`, and then `fadeIn()` if needed, otherwise it's removed from the DOM.
* Enable the EU Cookie Law Banner widget.
* Visit a page where the widget is enabled and hit the "Close and accept" button.
* Reload the page and make sure the widget doesn't show up.
Prevent the caching of the EU Cookie Law Banner cookie.
=> Widgets: Prevent the caching of the EU Cookie Law Banner cookie

sync/class.jetpack-sync-module-themes.php
Fixes #7380
* Sync: avoid php warning by making sure that new widgets to sync are an array
0. make sure you have `WP_DEBUG` set to `true`
1. in Calypso, activate Dyad 2
2. in WP Admin, add a widget that hasn't been added before
3. in Calypso, activate Lodestar
There should be no PHP warnings.
Sync: fixed a PHP warning after switching themes in Calypso, when new theme had different widgets placed (or none) in its sidebar than old theme.
=> Sync: avoid php warning after switching themes in Calypso or WP Admin

class.jetpack.php, sync/class.jetpack-sync-users.php
Fixes https://github.com/Automattic/wp-calypso/issues/14490
To test:
- apply this patch to your test site
- in addition to a master user, have an other user who is connected
- logged in as the master user, update the other connected user's role
- log into wordpress.com as the other user, and ensure your new capabilities are reflected
=> XMLRPC: jetpack.updateRole

modules/widgets/flickr.php, modules/widgets/flickr/style.css, modules/widgets/flickr/widget.php
Fixes #7089 
* Rewrite the front-end of the Flickr widget replacing unnecessary `<table>`s with a flexbox powered `<div>`.
* Center-align the thumbnails, as this was the original intended behaviour (see: `<td align="center">`).
* Activate the Flickr widget.
* Select size "thumbnail" and check that the photos are displayed in a grid (provided there's enough horizontal space).
* Select size "small" and check that the photos are displayed vertically.
=> Flickr Widget: Refactor the look and feel to allow for a thumbnail grid

class.jetpack-client.php, class.jetpack-jitm.php
Previously the function was hard-coded to hit the v1 REST API endpoints,
even though there's a `$version` argument, because the v2 endpoints (at
least the most recent ones) are under a different base path (`/wpcom` or `/wp`
instead of `/rest`). This change adds an additional argument that allows
changing that path.
=> Add `$base_api_path` arg to `Jetpack_Client::wpcom_json_api_request_as_blog`

class.jetpack.php
* when the `jetpack_active_plan` option is fetch, set an empty array as the default to be returned, instead of a boolean false
* if there's no plan stored or if it's Jetpack Free, add a 'class' item set to 'free' to the array to be returned.
This solves an undefined string in `admin.php?page=jetpack-debugger` screen when Jetpack site is in Free plan.
Before:
After:
* make sure a site with Jetpack Free plan doesn't show undefined as shown in the image above.
=> Plans: if there's no plan known or if it's Jetpack Free, add 'free' class item

class.jetpack.php, modules/sharedaddy/sharedaddy.php, modules/sharedaddy/sharing-service.php
Defers #448 until a longer-term solution can be determined.
This feature has been a bit of a thorn in our side with multiple hosts over time disabling Sharing completely or at least the e-mail service due to spam abuse. While we should fix this, disabling this feature by default and requiring a technically-savvy admin to enable it.
Alternatively, we can disable it for sites that do not have Akismet and rely on Akismet to catch spam.
Opening the PR to continue the discussion.
cc: @csonnek
=> Sharedaddy: Disable e-mail sharing by default

modules/widgets/flickr/form.php
Update the Flickr widget description with a workaround to get the RSS URL after the recent Flickr changes.
The copy has already been vetted by the editorial team (hence the couple of unrelated changes in the string).
See: https://www.flickr.com/help/forum/en-us/72157681711158094/page13/#reply72157682795746441
=> Flickr Widget: Update description with RSS URL workaround

modules/masterbar/overrides.css
These override are being moved to WP.com in order to fix the Dashboard icon positioning issue that is also present there. Depends on D6125-code that introduces these changes on WP.com side.
* When D6125-code is deployed, verify that Dashborad icon is displayed correctly on tablet screen sizes.
=> WordPress.com Toolbar: remove obsolete CSS overrides

.travis.yml
https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches only mentions the ability to use regex, not plain asterisks. In my testing in my own repository, this does seem to be the case.
=> Fix what branches Travis CI runs against

modules/protect/math-fallback.php
I've been seeing the occasional HTTP 500 status code in my web server
log for a long time in response to requests such as 'POST
/wp-login.php'. I finally took the time to track it down to a bug in the
math-fallback.php module. The problem is that the invocation of
`wp_die()` is incorrect. This change fixes that bug. I now see the
expected 401 status in my logs.
=> Protect: Correct HTTP status from math failure

modules/masterbar/overrides.css
This style was updated on WP.com side in D5792-code, so we no longer need to override it in Jetpack.
* On your test Jetpack site with WordPress.com toolbar module enabled, verify that there are no artifacts displayed before the `Add` button in Plugins section of My Sites menu.
=> WordPress.com Toolbar: remove obsolete CSS override

sal/class.json-api-site-jetpack-base.php, sal/class.json-api-site-jetpack.php
Exposes the `WP_MEMORY_LIMIT` and `WP_MAX_MEMORY_LIMIT` constants in the `options` list of the `/sites/$site/` JSON API endpoint.
Background: The intended use is for the mobile apps to be able to detect if a Jetpack site's memory limit is too low to support a media item the user is attempting to upload (and prevent it with an error message).
Verify that `options.wp_memory_limit` and `options.wp_max_memory_limit` exist and reflect the correct values when calling the `/sites/$site/` endpoint.
=> REST API: Add memory limit constants to /sites/$site/ options

class.jetpack-jitm.php
Fixes a bug introduced by #6813
* #6813 added a base path parameter, but it requires setting the `body` in the parameter before it.
* Verify you can see jitms
=> Fix broken jitms

modules/widgets/migrate-to-core/image-widget.php
Improves the migration routine proposed in #7103 to include Widget Visibility conditions.
* Add widget visibility conditions to the migrated widget.
* Fixes a case where an uninitialized sidebar is not an array.
* Downgrade to Jetpack 4.9, or forcefully add the old widget class by commenting [a line](https://github.com/Automattic/jetpack/blob/master/modules/widgets/image-widget.php#L15) in the image widget file.
* Delete the flag option by doing `Jetpack_Options::delete_option( 'image_widget_migration' );`
* Create a Jetpack image widget with widget visibility rules, also create one without rules.
* Undo the changes you made to the image widget file, or upgrade to 5.0 depending on what you did in step 1.
* Make sure the widget visibility rules get migrated properly to the newly created …
=> Added widget visibility conditions saving to image widget migration script.

_inc/jetpack-jitm.js
With nexgen gallery, it will call an invalid url which results in a 402 error page response sent back. So, `response.length` is greater than 0, since it's a string. It then continues as though there's a jitm and it breaks because it's not a jitm, it's a string.
I could check the response code, but that seems like I'd still have to check the content and make sure it's sane. So, I basically just decided to do the simplest and make sure if the length is greater than 0, check that the content is not falsy.
- Force your webserver to return a string for this api route (you can modify the code to return a string on [this line](https://github.com/Automattic/jetpack/blob/768b0f76d4c17f8dcafd26965ebf398e4d238b56/class.jetpack-jitm.php#L219-L219))
- Verify there's no error in the console.
=> Fix broken jitms when string is returned

modules/widgets/migrate-to-core/image-widget.php
* Adds saving changes to image widget migration script - old settings get saved to a custom post type for possible later retrieval.
* Fixes image size problems when migrating.
* Basically follow whatever instructions say in #7366 but pay attention to image sizes - they should work.
=> Added backups to image migration script.

modules/masterbar/masterbar.php
Fixes #7412 #7411
Styles loaded from dotcom were missing a cache buster which resulted in new CSS overrides not being loaded in some cases.
=> WordPress.com Toolbar: add cache buster to enqueued styles

class.jetpack-network.php
Fixes multisite subsite automated connection.
* Fixes secrets handling in the connection method, changes are pretty self-explanatory.
* Install Jetpack on a multisite installation.
* Connect a subsite to WordPress.com
* Go to `/wp-admin/network/admin.php?page=jetpack`
* Disconnect a site using the link in the list.
* Try to connect it back, see that it fails.
* Apply this PR.
* Try connecting again, see that it succeeds.
* Fixed automated subsite connection for multisite installations.
=> Fixed secret handling in subsite connection.

modules/sitemaps/sitemaps.php
Identify sitemaps as a "sitemap" feed for the purposes of caching or further analysis of an output buffer.
Caching plugins use output buffering to capture the page so even though the sitemap function dies immediately after the content is pushed out, the content is still captured. However, in my testing the Content-Type header was not captured (even when using `apache_get_header_list` or `headers_list`) in the output buffer callback. With this change the caching plugin can identify a sitemap and then use the right caching and/or content type. [This](https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L1050) is how WP Super Cache does that.
See https://github.com/Automattic/wp-super-cache/issues/237 for further
discussion.
=> Set is_feed/feed so sitemap can be identified later in shutdown

_inc/client/components/masthead/style.scss, modules/masterbar/masterbar.php
Fixes #7417
This PR addresses an overlapping issue on the Jetpack side. Note that styles for hamburger icon positioning must be solved in wpcom side.
Fix works for both `admin.php?page=jetpack` and `admin.php?page=jetpack_modules`.
* add a CSS class `jetpack-masterbar` to admin `body` tag to identify when it's active
* when Masterbar is active, move Jetpack logo to avoid overlapping
* adjust media query so masthead margin kicks in at 782 instead of 720, [fixes this](https://github.com/Automattic/jetpack/issues/7417#issuecomment-312410841).
* activate Masterbar and shrink the viewport until mobile size
* test in mobile device if possible
=> Settings UI: solve Masterbar hamburger overlap with logo

json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
This fixes the image upload issue in Calypso by removing WPCOM only code from Jetpack
Fixes #7339
* Adds in WPCOM exlcusions
* Verify that images can be uploaded from Calypso
=> Remove the call to Jetpack Media Sync

modules/masterbar/masterbar.php
Refactor cache buster values for Masterbar's WP.com styles so we don't have to update them manually.
=> WordPress.com Toolbar: refactor cache buster

sync/class.jetpack-sync-module-posts.php
Fixes #7372
* Index should never be undefined, but appears to be for one user possibly as a result of a combination of plugins he is running
*
=> Jetpack Sync: Setting default value to address undefined index issue

sync/class.jetpack-sync-module-terms.php
* Don't send two actions when saving a term.
Previous to this change we were syncing two actions: `jetpack_sync_add_term` and `jetpack_sync_save_term`
* Add a new term
* Check that only `jetpack_sync_add_term` gets sent.
=> Sync: Fix `jetpack_sync_add_term` and `jetpack_sync_save_term` being sent together

jetpack.php, readme.md, readme.txt
Since `jetpack.com` and all other URLs we're referencing have `https` versions.
No functional changes here
=> Readme: Update links to `https`

sync/class.jetpack-sync-module-posts.php
Jetpack Sync: Adding whether post was just published to wp_insert_post sync action arguments
Fixes #
*
*
=> Jetpack Sync: Adding whether post was just published to wp_insert_post sync action arguments

tests/php/modules/contact-form/test_class.grunion-contact-form.php
Fixes #7471 
Updates the test to account for the new core behavior. The test's intent is to ensure we aren't mishandling stuff, so it makes sense to update it along with core's new way of handling shortcode args.
=> Updates unit test to account for new core behavior

jetpack.php
Removes a pre-WP 4.7 hack needed to handle a core bug with the REST API on sites using a particular permalink structure.
=> Remove shiv for REST API

modules/protect.php
On beta plugin installs, the path of the plugin is `jetpack-dev/jetpack.php` which currently displays a warning to network activate whether or not it is active. Adding it here to better mimic production.
=> Protect: Stop showing multisite network activation warning on beta installs

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
Fixes #7451 
Adding name of importer to sync details for activity log
Adding name of importer to sync details for activity log
phpunit
=> Jetpack Sync: Adding name of importer to sync details for activity log

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
See 69-gh-wp-calypso
The REST API settings endpoint includes a property `jetpack_relatedposts_enabled`, which is true if the Related Posts plugin will display related posts. The value from this endpoint is incorrect, however, when a site has not modified their settings. This is because the `Jetpack_RelatedPosts` plugin defaults the setting to be enabled if it is not set.
This change modifies the endpoint to use the same logic: if the setting is not set, it will default to reporting `jetpack_relatedposts_enabled` as true.
Some sites (VIP and Jetpack) default this setting to `false` instead, but the way this is accomplished is that when the plugin is loaded by `wp-content/mu-plugins/related-posts.php`, it actively changes the option to `false`. Since that loader should still be used by the …
=> REST API: Settings: fix `jetpack_relatedposts_enabled`

.travis.yml
Via [#WP41292](https://core.trac.wordpress.org/ticket/41292)
Travis CI have announced they are switching to Trusty as the default distro come July 18th 2017
> https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
----
The current availability of PHP 5.2 & 5.3 in the Travis CI build environment is the following:
1. ✅ `dist: precise` with `sudo: false` 
2.  ❌  `dist: trusty` with `sudo: false`
3.  ❌  `dist: precise` with `sudo: false`
4.  ❌  `dist: precise` with `sudo: required`
Jetpack's current Travis CI config uses option `1` above
Travis CI will override this configuration with option `2` come July 18th 2017
Workaround to use PHP 5.2 & 5.3 until September 2017 using option `3` for the PHP 5.2 & 5.3 Travis CI job
Come September 2017 Travis CI will overwrite option `3` …
=> Switch Travis CI environment to Trusty - PHP 5.2 to be no longer available Sept 2017

sync/class.jetpack-sync-module-themes.php
Sync move widget to inactive
Sync move widget to inactive
phpunit
=> Jetpack Sync: Sync move widget to inactive

changelog.txt
Fixes #7498 
*changes "Mutli" to "Multi" on line 277 in changelog.txt
=> correct typo in changelog.txt <#7498>

_inc/client/traffic/google-analytics.jsx
Fixes #7491 
* Adds a wrapping paragraph to make inline items behave properly.
* Open the Traffic tab, switch to the Pro plan and make sure that the link in the Google Analytics card is properly spaced.
=> Fixed a spacing issue in Google Analytics card.

class.jetpack.php, modules/comment-likes.php, modules/likes.php, modules/likes/style.css
Aren't needed and the double-quote isn't getting picked up by the concatenation build.
Fixes #7435
=> CSS: Enqueue Open Sans if we're going to use it.

functions.global.php, modules/widgets/migrate-to-core/image-widget.php
Fixes #7438
* this avoids issues down the line like with map_meta_cap()
1. `wp jetpack options update image_widget_migration true`
2. add a new post, set the title, save as Draft
You should not get any notices.
Widgets: solve PHP warnings when Image widget wasn't migrated.
=> Widgets: register post type before inserting one

webpack.config.js
* don't overwrite process.env, only process.env.NODE_ENV
This follows the best practice pointed by Webpack here
https://webpack.js.org/plugins/define-plugin/#feature-flags 
* verify that NODE_ENV is set as before and things are working like before. A quick one is to check file size of final built files, it should be the same.
=> Webpack: don't overwrite the entire process.env

modules/shortcodes.php
Provide indicator that the filter fires before themes are loaded.
Helps to prevent developer grief as seen in #7449. I'm open if there are better ways to indicate this that would get parsed into developer.jetpack.com.
@dereksmart any thoughts?
=> Shortcodes: Update inline docs

json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php
This adds the password and status fields to the list of fields that should always render for post objects. These are needed because downstream code looks at the password and status fields to determine if a post should be shown or not. When a request is made and these fields were not included, those checks would always fail and posts would not be returned.
This commit syncs r159288-wpcom.
* Always render the password and post status so that API handlers downstream can use them.
* Make sure posts still render as before and passwords don't appear when specifying `fields=ID,site_ID`
=> API: Add password and status to list of keys to always render before filtering

modules/theme-tools/content-options.php, modules/theme-tools/content-options/customizer.php, modules/theme-tools/content-options/featured-images-fallback.php, modules/theme-tools/content-options/featured-images.php
Similar to Post, Page, and Archives, a new option can be added to the
themes using the Portfolio CPT.
This update also adds a link to learn more about featured images for
users unsure about what it is.
Finally, a small tweak is added to Featured Images fallback to make
sure only Posts can get the “fake” `has-post-thumbnail` class
=> Content Options: Add a Portfolio option to the Featured Images + fixes

class.jetpack-jitm.php
This change simply updates the params sent over via the JITM CTA URL.
Providing the user ID will allow us to better customize the experience
from there for the particular individual.
To test:
1) Trigger any JITM in your wp-admin.
2) Click on the CTA and make sure that the user ID param is correctly included in the destination URL.
=> JITM: Include the user ID in the URL of the CTA so that we can better customize the experience.

.travis.yml, gulpfile.js, modules/contact-form.php, modules/contact-form/css/editor-inline-editing-style.css, modules/contact-form/css/editor-style.css, modules/contact-form/css/editor-ui.css, modules/contact-form/grunion-editor-view.php, modules/contact-form/js/editor-view.js, modules/contact-form/js/tinymce-plugin-form-button.js
Closes #6685
Fixes #7063
Fixes #1849
Fixes #1055
Fixes #642
Fixes #604
Fixes #254
This is a redo of #6685 because I seem to have made that ugly by rebasing it. :\
The diff to implement this on wpcom is at D6457
This is currently just adding the overrides -- I'm intentionally not removing the old legacy code yet, to ease the transition on any users that prefer the old method.  They can just disable the new include line, and the old way will be back again.
Props @MichaelArestad @azaozz and @georgestephanis for building this at the 2016 a8c GM.
* Add a visual interface for Contact Forms.
* Add a contact form to a post.
* Edit an existing contact form in a post.
* Switch to the html editor.  Back again!
* Add a second or third contact form to a post.
* Open multiple forms to editing mode at …
=> Add Grunion Editor View.

modules/comment-likes.php, modules/comment-likes/admin-style.css, modules/comment-likes/comment-like-count.js
Refactoring parts of the module code in order to comply with coding standards and address new feedback from https://github.com/Automattic/jetpack/pull/7175. 
1. Run `yarn build` in your Jetpack folder.
2. Navigate to `Discussion` tab in Jetpack settings, and enable Comment likes module.
3. Test liking and un-liking comments. 
4. Visit `wp-admin/edit-comments.php` and verify that comment like counts are displayed correctly.
5. Make sure that post likes still work as expected.
=> Comment likes: refactor code

3rd-party/3rd-party.php, 3rd-party/domain-mapping.php, class.jetpack-xmlrpc-server.php, class.jetpack.php, phpunit.xml.dist, sync/class.jetpack-sync-actions.php, sync/class.jetpack-sync-functions.php, sync/class.jetpack-sync-module-callables.php, tests/php/3rd-party/test_class.jetpack-domain-mapping.php, tests/php/sync/test_class.jetpack-sync-callables.php, tests/php/test_class.jetpack.php
For sites that use domain mapping and multi language, it can be quite hard to sync uniform URLs back to WP.com, which can cause the site to be put in IDC.
To address this, I'd like to start syncing the unfiltered values for `home` and `siteurl`. This will introduced some jankiness where we sync the non-mapped domain for domain mapped sites. But, we can then address that by adding support for the top multi language and domain mapping plugins.
I've added support for Donncha's and WPMU Dev's domain mapping plugins. But, it's untested at the moment.
To test:
- Create network and point domains to network
- Install and configure one of the domain mapping plugins
- Ensure that the mapped domain gets sent to WPCOM
- You can comment out [this …
=> Sync: IDC: Add get_raw_url method to Jetpack_Sync_Functions

_inc/client/plans/index.jsx, _inc/client/plans/plan-body.jsx
With D6428-code in place, you should be seeing this CTA in /plans 
However, currently it's looking for the `premium-themes` Object, when it's actually an array item.
=> Plans page: Fix missing premium theme CTA on Pro plan

class.jetpack-debugger.php
After merging #5852, it'd be handy to have some extra debug information around what URLs a site is using as well as if the site is currently in an IDC.
To test:
- Go to `$site.com/wp-admin/admin.php?page=jetpack-debugger`
- Ensure options are there and there are no errors
=> Debugger: Add some sync IDC URLs to the debugger

bin/partner-provision.sh, class.jetpack-cli.php
If a Jetpack site is restored to a pre-connected state and we want to re-provision, then we also want to ignore (and if necessary regenerate) existing credentials on WordPress.com.
This patch allows passing the `force_connect` parameter to accomplish this.
=> Jetpack Start: Allow force_connect to ignore existing token on WPCOM

_inc/client/main.jsx
This solves an issue that happens in Dev Mode and Dev Version: if you click Reset Options in the footer, Jumpstart is shown after reset, even though the route correctly points to `/dashboard`.
* make sure site is connected before showing Jumpstart
* in Dev Mode with a Dev Version, click Reset Options at the bottom. You should see the Dashboard, not Jumpstart.
=> Jumpstart: only display jumpstart if site is connected

.github/CODEOWNERS
To help keep pulse on things being added that would impact what support sees/knows what to do with.
=> codeowners: Add kraftbj to the debugger file

modules/simple-payments/paypal-express-checkout.js, modules/simple-payments/simple-payments.php
Before:
Now:
Perform a purchase of some product in Simple Payments. Does the success message text shows in white color?
=> Simple payments: fix success message styling

class.json-api-endpoints.php, json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
There were some issues with the videopress_guid not return for some Jetpack requests. This attempts to normalize how media items are accessed and add a couple of failure exceptions to help recover if they are encountered.
This commit syncs r159298-wpcom.
=> Sync VideoPress API fixes

bin/partner-cancel.sh, bin/partner-provision.sh
Follow up of #7294, check it for details.
This simply updates the syntax of the command to the traditional one for `wp`.
I checked up with @mjangda and confirmed that syntax didn't make much difference. Let's use this for consistency since it's the most commonly found.
=> Ensure wp-cli will run even if provisioning is called by root

modules/contact-form/css/editor-ui.css, modules/contact-form/grunion-editor-view.php, modules/contact-form/js/editor-view.js
The prior PR #7490 once merged added the button to create forms to the QuickTags and TinyMCE toolbars as a regular button, but a lot of users may not notice the new location and be confused.
Tentatively re-add the prior button back in as well.
=> Reintroduce button above editor to add contact forms to posts.

modules/contact-form/css/editor-inline-editing-style.css, modules/contact-form/grunion-editor-view.php, modules/contact-form/js/editor-view.js
* moved submit and cancel buttons over
* renamed buttons container from .buttons to .grunion-controls
* updated section header font weight
* renamed section headers
=> Grunion: updated styles of the editor

_inc/client/plans/plan-body.jsx
Fixes #7494
* in Jetpack > Dashboard > Plans tab, add card for social scheduling on Premium and Pro plans
* check the site with a Premium and/or Pro plan
=> Plans: add card for social scheduling on Premium and PRO plans

_inc/client/scss/shared/_main.scss
Taken from #7516
* add underline to links inside notice texts, following Calypso and DOPS
=> Settings UI: add underline to links in notices

modules/contact-form/js/editor-view.js
We were writing the contents too quickly after adding the empty iframe
to the dom -- so when load ran, the contents got wiped out.
Instead let's do our stuff on the load event.
The downside is that there's a brief flash of unstyled content, will
look at addressing seperately -- as that's gloss, not functionality.
Props @petitphp for the find!
https://twitter.com/petitphp/status/889968381994160128
=> Fix edit view render for Firefox.

modules/contact-form/css/editor-style.css, modules/contact-form/js/editor-view.js
This can be caused by theme editor styles -- in this case, it was caused
by twentyseventeen here:
https://github.com/WordPress/WordPress/blob/be94fa5483dd98667d1fd911d6390ad34387804d/wp-content/themes/twentyseventeen/assets/css/editor-style.css#L343
and looks like this, before the change:
=> Resolve an unnecessary gap at the bottom.

_inc/client/at-a-glance/index.jsx
Fixes #7462
* pass props so getOptionValue() method is available for usage in the component
* test as Adam points here https://github.com/Automattic/jetpack/issues/7462#issue-242747877
An issue that resulted in a blank dashboard for non admins when they had access to Stats has been fixed.
=> Settings UI: fix blank dashboard when non-admin had Stats access

modules/comment-likes.php
Fixes issue reported by @keoshi 
* set the correct path to resolve URL for assets
* make sure Comment likes work on the front end
=> Comment likes: set the right URL to look for assets

_inc/client/components/settings-group/index.jsx, _inc/client/discussion/comments.jsx, _inc/client/traffic/sitemaps.jsx, _inc/client/traffic/verification-services.jsx
* open inline Learn More links in a new tab to be consistent with info popover links
* comply with ESlint best practices react/jsx-no-target-blank
* make sure Learn More links in Discussion tab open in a new browser tab.
=> Settings UI: open inline learn more links in new tab

_inc/client/components/forms/styles.scss, _inc/client/components/tags-input/style.scss
This PR refines the styling on AtD settings (spelling, style, grammar):
- Increases spacing between subsections.
- Cleans up input inside an input on “Ignored Phrases”
Visit Writing settings, and expand “Check your spelling, style, and grammar” — `wp-admin/admin.php?page=jetpack#/writing`
Fixes #6868
=> Settings UI: Refine AtD options styling

modules/sharedaddy/sharing-service.php
A change introduced in #6355 started merging the regular options array with the global options. This has been largely unnoticed, but sometimes resulted in weird errors like this:
```
PHP Catchable fatal error:  Argument 2 passed to Share_Twitter::__construct() must be of the type array, null given, called in /home/asotestjetpack/main/wp-content/plugins/jetpack-dev/modules/sharedaddy/sharing-service.php on line 227 and defined in /home/asotestjetpack/main/wp-content/plugins/jetpack-dev/modules/sharedaddy/sharing-sources.php on line 562
PHP Warning:  array_merge(): Argument #1 is not an array in /home/asotestjetpack/main/wp-content/plugins/jetpack-dev/modules/sharedaddy/sharing-service.php on line 227
PHP Notice:  Undefined index: global in …
```
=> Fixes default global options array merging.

_inc/client/components/admin-notices/index.jsx, _inc/client/components/admin-notices/style.scss
Fixes issue reported by @keoshi: WooCommerce notices aren't properly stylized and they're cropped on mobile sizes.
The style they had before was due to the `is-basic` modifier. However, Filipe pointed that there are no notices with that style, and indeed there's none in https://wpcalypso.wordpress.com/devdocs/design so I've removed it so they're stylized as any regular notice.
* ensure notices aren't cropped in mobile
* update their styling to match the basic notice styling
Note: Skip setup has that color because it's slightly faded in WC so I set it in our `$gray` color var.
* edit this WooCommerce file `woocommerce/includes/admin/class-wc-admin-notices.php` and in method `add_notices()` replace the line
```php
$notices = self::get_notices();
```
with
```php
$notices = array(
'install', …
```
=> Settings UI: update styling of WooCommerce notices shown here

sync/class.jetpack-sync-module-themes.php
Fixes #7570 
In #7487, we tried to improve syncing of widgets for activity log, but manage to break instances where new widgets were added.
Team Poseidon will work on a better method for improving widget syncing.
To test:
Checkout this branch, and ensure you can add a new widget and save it's settings.
=> Fix widget saving

class.jetpack.php
addresses #7568
The actual fix for this would require a change in the epoch plugin as well as Jetpack.  For now, we're adding it to the incompatible list for comment-likes module.
=> Add Epoch plugin to incompatible plugin list for comment-likes module

class.jetpack.php, sync/class.jetpack-sync-listener.php
Currently the current user is not set to during the wp_login action.
This PR fixes this by updating the setting the actor.
* Set the actor information as expected. 
* E2E test that when you login you see the activity log as expected.
=> Sync: Add actor to wp_login sync action

class.json-api.php
This is part of https://github.com/Automattic/wp-calypso/pull/16638
Differential Revision: D6588
This commit syncs r160556-wpcom.
Fixes #
*
*
=> Add email field to error on social account create

modules/contact-form/grunion-editor-view.php
Relevant for #7598 and #7617
* use current_screen hook to delegate actions for other screens
* make sure editor actions are only added to post editing screen
=> Contact Forms: use current_screen hook to specify when to add actions

modules/contact-form/grunion-editor-view.php
This should remedy any issues hitting JS errors due to the tinymce extensions being loaded on pages where the rest of the cforms code isn't.
Fixes #7598
=> Contact Form: Ensure dependencies are set correctly

3rd-party/3rd-party.php, 3rd-party/qtranslate-x.php
Fixes #7589
* hook into a qTranslate X filter to check the URL. If it's a call to Jetpack REST endpoints, return false so it's not redirected and the settings page can work properly
1. install qTranslate X without checking this branch
`wp plugin install qtranslate-x --activate`
2. go to Settings > Languages and set a secondary language as default
3. go to Jetpack dashboard, verify it doesn't work and that REST url calls are prefixed with the language you set as default
4. switch to this PR and verify it's working fine and Jetpack endpoint calls aren't prefixed
prevent qTranslate X from redirecting REST API calls to Jetpack endpoints so Jetpack dashboard works properly.
=> Settings UI: prevent qTranslate X from redirecting REST API calls

modules/shortcodes/class.filter-embedded-html-objects.php
Fixes #7629 
To test:
* Activate the shortcodes module
* Install and activate this plugin: https://gist.github.com/marcinbot/14c7fb17c59181f39ebd58fdf2a117c1
* Load any admin page with an array passed in GET params (`arrName[]=e1&arrName[]=e2`)
* Verify no warnings appear
=> Fixed warnings appearing when kses is called on an array

_inc/client/at-a-glance/monitor.jsx, _inc/client/at-a-glance/photon.jsx, _inc/client/at-a-glance/protect.jsx, _inc/client/at-a-glance/stats/index.jsx, _inc/client/components/settings-card/style.scss, _inc/client/traffic/verification-services.jsx, yarn.lock
Fixes #7021
When Site Verification feature is inactive, show a one-way activation banner.  
This uses the title/long description of the module from the module header and can be manually changed if we want.  
To Test: 
- Disable site verification module
- Navigate to /traffic and view the banner
- Make sure activation works properly
Looks like this:
=> Site Verification: Show one-way activation banner when feature is inactive

modules/widgets/social-media-icons/style.css
Fixes #7452
* add specificity to CSS rule
* use TwentySeventeen
* add Social Media Icons widget
* verify there's no border like in the issue #7452
Remove unwanted border around social media icons with TwentySeventeen theme
=> Widgets: fix border around icons in TwentySeventeen

modules/masterbar/masterbar.php
Rename "Pages" to "Site Pages" and move above "Blog Posts"
Keeping in sync with Calypso: https://github.com/Automattic/wp-calypso/pull/17016
=> Masterbar: Rename and reorder Pages menu

class.json-api-endpoints.php
Add the author IP address to the response of [`GET /sites/$site/comments/$comment_ID`](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/%24comment_ID/).
Like the email address, IP address is limited behind a check on the request context (must be set as `edit`) and the requester capabilities (must have `edit_comment`).
Try the `GET /sites/$site/comments/$comment_ID` endpoint on a Jetpack site here: https://developer.wordpress.com/docs/api/console/
The response's author object must contain an `ip_address` field.
Its value must be `false` if the request `context` parameter is not `edit`. Otherwise it should be an IP address.
This is a blocker for the [Comment Management development](https://github.com/Automattic/wp-calypso/projects/32) going on in Calypso.
=> Comments: Add author IP address to the response

modules/widgets/migrate-to-core/image-widget.php
Fixes #7595 
* if the widget_media_image wasn't updated, maybe it already exists. If so, delete legacy option and set our flag so this code isn't always run
* delete `image_widget_migration` and test migrating an image widget from a previous WP version
* delete `image_widget_migration`
In both cases, the code should run once instead of every time WP Admin loads as is now
Widgets: prevent code that migrated legacy Jetpack image widget to WordPress' new image widget from running on every WP Admin load.
=> Widgets: if widget_media_image exists, flag migration as done

class.jetpack.php, sync/class.jetpack-sync-module-users.php, tests/php/sync/server/class.jetpack-sync-server-eventstore.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/server/class.jetpack-sync-test-replicastore.php, tests/php/sync/test_class.jetpack-sync-users.php
Update user sync for activity log
This PR modifies the Jetpack User Sync Module to ensure that user related sync actions are sent with the data necessary to populate the Activity Log, and that duplicate/extraneous sync actions are not sent.
phpunit
=> Jetpack Sync: Update user sync for activity log

class.jetpack.php, tests/php/test_class.jetpack.php
Fixes dns_prefetch to output a self-closing tag
`Jetpack::dns_prefetch` is updated to output a self closing tag in order to be used in a blog that strives for XHTML compliance.
=> XHTML compliance

json-endpoints/class.wpcom-json-api-update-comment-endpoint.php, sal/class.json-api-site-base.php
Replicates the changes introduced in D6713-code and D6726-code
* Add the `moderate_comments` capability to those returned from the sites endpoint.
* Allow comments to posts with closed comments if the author has the `moderate_comments` capability.
Part 1
* Login as an Author.
* Go to `https://wpcalypso.wordpress.com/comments/`, and make sure to be redirected to the Stats page.
Part 2
* Login as an Admin.
* Create a new post, add a comment to this post, and disable the comments for this post.
* Go to `https://wpcalypso.wordpress.com/comments/`, select the site, locate the new comment and reply to it.
* The reply should be approved. Wait for a couple of seconds and make sure that the reply pops up in the comments list and no error notice is displayed.
=> Comments: Add checks on the `moderate_comments` capabilities

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-comments-tree-endpoint.php
Introducing the Comments tree endpoint in Jetpack. This endpoint is already available on WordPress.com side, and the changes presented here are a verbatim copy of D6862-code.
1. Apply D6862-code on your sandbox.
2. Sandbox the WP.com API.
3. Send `GET` request to `https://public-api.wordpress.com/rest/v1/sites/{$blog_id}/comments-tree/?status=all`, where `$blog_id` is the `id` of your test Jetpack site.
4. Results should be similar to the one that you can obtain by performing a `GET` request for: `https://public-api.wordpress.com/wpcom/v2/sites/{$blog_id}/comments-tree?status=all`
=> Comments management: add Comments tree endpoint from WP.com

_inc/jetpack-connection-banner.js, class.jetpack-connection-banner.php, class.jetpack-options.php, class.jetpack.php, scss/organisms/_banners.scss
Fixes #7567 and #7447
This PR adds the connection banner to the wp-admin dashboard as well as the plugins screen.  It replaces the connection widget that was there before, so you should not see that widget unless the site is connected.  It uses some custom JS to sit below the welcome message: 
This PR also changes the behavior of the dismiss, which now sets an option via AJAX and does NOT dismiss the plugin.  This option is cleared on the next plugin_initialize, so that we make sure to show the banner if they deactivate/enable Jetpack again for whatever reason.  
To Test: 
- Visit your wp-admin dashboard `/wp-admin/index.php?welcome=true` and see the connection banner
- Dismiss should remove the banner persistently
- Deactivating/reactivating the plugin should show …
=> Add connection banner to Dashboard

modules/widgets/eu-cookie-law/style.css
Fixes 832-jpop-issues
On some themes `.widget` containers might have borders.
The EU Cookie Law banner logic on close and accept simply removes the _content_ and not the entire `.widget`, therefore the `.widget` border remains visible no matter what.
Particularly odd is the case with the Twenty Sixteen theme, where the `.widget`s have a black upper border.
On large screens, there is a "black frame" that effectively hides the EU Cookie Law banner's border.
On small screens, though, the frame disappears and the border is visible.
Large screen, banner active. Notice the black border.
Large screen, banner closed. Notice the black frame of the theme. The closed banner border is actually there, but not visible.
Small screen, banner closed. No more black frame, and the widget border is visible …
=> EU Cookie Law Widget: Remove unnecessary widget border

modules/comments/comments.php
In some cases, http is stored in the comment meta for the hc_avatar coming in from Facebook/Twitter. Since FB/Twitter support https, we can force that and avoid mixed content warnings. With Photon on, Twitter likely already worked since Photon uses https, but Facebook would still fail since we skip graph.facebook.com URLs via Photon.
Originally reported in 606687-zen
Fixes https://github.com/Automattic/jetpack/issues/7548
=> Comments: Force https on Facebook/Twitter avatars

modules/widget-visibility/widget-conditions.php
Fixes #5221
I had originally added this filter in this PR: https://github.com/Automattic/jetpack/pull/5222 but it was later erased when this module was refactored here: https://github.com/Automattic/jetpack/commit/0c510aaa0c8fb362657ec8ca6f0195506e214fe2#diff-deea61a2ffe944e4c0f7e2bc0d534be2L157
This pull request re-adds the filter again.
Add a an arg with the following:
```php
add_filter( 'jetpack_widget_visibility_tax_args', function( $args ) {
$args['public'] = true;
return $args;
} );
```
=> adding back the tax filter for the widget visibility module

modules/videopress/shortcode.php
Fixes #7303 
Testing:
Add an autoplay arg to a VideoPress shortcode. It should autoplay but not loop.
cc: @dbtlr
=> VideoPress: Only loop if specifically indicated

modules/module-headings.php
After running `yarn build` today against the latest master, I noticed that `modules/module-headings.php` had changed. Since this file is already tracked, we can't `.gitignore` it. So, I'm creating this PR to separately update that file.
My guess is that this happened because we removed omnisearch in #7590.
=> General: Update module headings file

modules/sso/class.jetpack-sso-helpers.php, tests/php/modules/sso/test_class.jetpack-sso-helpers.php
When I initially added this logic, I only wanted to allow the change for sites that were in some form of non-production mode. But, this also has the effect of breaking the auto-authorize redirect for a production site if the the site has defined `JETPACK__API_BASE` to something other than the default.
This change should only affect SSO redirects, and as such, adding the extra URL parsing to requests should not be a performance burden.
To test:
- Connect site
- With a user other than the the master user, disconnect, then login via SSO
- After clicking "Log In" on WPCOM, you should end up the auto-authorize flow of JPC
- Try the previous two steps after setting `JETPACK__API_BASE` to your WPCOM sandbox
cc @gravityrail for review.
=> SSO: Allow redirecting to JETPACK__API_BASE in production

json-endpoints/class.wpcom-json-api-comment-endpoint.php
Add the raw content to [`GET /sites/$site/comments/$comment_ID`], in order to enable edit of comments without re-requesting the content.
Try the `GET /sites/$site/comments/$comment_ID` endpoint on a Jetpack site here: https://developer.wordpress.com/docs/api/console/
The response should contain a new `raw_content` property, with the unformatted content of the comment.
p7jreA-Gv-p2
D6987-code
=> Comments: adds a raw content response to the sites comment endpoint.

json-endpoints/class.wpcom-json-api-comment-endpoint.php
Continuation of https://github.com/Automattic/jetpack/pull/7637
Add the author IP address to the response of [`GET /sites/$site/comments/$comment_ID`](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/%24comment_ID/), removing the `display` context limitation. Requester must have `edit_comment` capabilities.
Try the `GET /sites/$site/comments/$comment_ID` endpoint on a Jetpack site here: https://developer.wordpress.com/docs/api/console/
The response's author object must contain both `email` and `ip_address` fields for `display` and `edit` request contexts. Other contexts should return `false` for both fields.
https://github.com/Automattic/wp-calypso/pull/17251#issuecomment-322849896
p7jreA-Gv-p2
D6984-code
=> Comments: adds author email and IP Address to the site's comments endpoint

_inc/client/components/admin-notices/index.jsx
Before, the success notice that comes from VaultPress after plugin setup has the wrong style and icon, making it look not so "successful"
This PR fixes the notice, and now looks like this for success:
To Test: 
- Add this snippet into a functionality plugin
```
add_action( 'admin_notices', 'show_vp_notice' );
function show_vp_notice() {
$message = sprintf(
__( 'VaultPress has been registered and is currently backing up your site. <a href="%1$s">View Backup Status</a>', 'vaultpress' ),
admin_url( 'admin.php?page=vaultpress' )
);
$vp = new VaultPress();
$vp->ui_message( $message, 'registered',  __( 'VaultPress has been activated!', 'vaultpress' ) );
}
```
- View the Jetpack admin dashboard, it should look good.
- Change the `registered` value in the snippet to anything else.  It should …
=> Fix VaultPress success notice design

class.jetpack.php, json-endpoints/class.wpcom-json-api-get-site-endpoint.php, json-endpoints/class.wpcom-json-api-post-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-user-endpoint.php, modules/shortcodes/instagram.php
Very very minor change - noticed that VS Code was getting confused by bracketed `@param` types and highlighting everything below them as a comment.
=> Fix syntax highlight errors in VSCode

_inc/client/main.jsx
Fixes an issue where the dashboard nav item was not selected after jumpstart.  
To test: 
- Connect Jeptack
- Click "reset options" in the footer
- when you see jumpstart, make sure to refresh the page to clear css rules
- Click jumpstart or skip 
- The dashboard nav item should be underlined
=> Show correct nav item selected after jumpstart

class.jetpack.php
The most common error during connect authorization is that the secrets have timed out.
The default timeout is 10 minutes, but it's easy to imagine someone going to make a coffee and coming back and clicking "Accept" more than 10 minutes later.
2 hours feels like a more comfortable number, and it seems that the security implications are probably fairly minor. Interested in feedback on this idea though.
Unfortunately we have not been able to capture the median expiry interval (how long after the timeout is the endpoint getting hit?), so conceivably we could return that with the error and log it to get a better sense of what number to set here.
That said, if no-one has any complaints, I'd rather ship this and then see how it affects the error rate.
=> Allow 2 hours for authorize secrets rather than 10 minutes

json-endpoints.php
This PR will allow a comment author's data (name, email, and website/URL) to be edited through the REST API, just as a user can edit the same information in `wp-admin` now.
See: https://github.com/Automattic/wp-calypso/issues/17164
D7046-code
=> WP.com API: Allow comment author data to be edited through the `Update_Comment` endpoint.

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-comments-tree-endpoint.php
Only regular comments are currently included in the comments tree endpoint; by removing the check on the `comments_type` column, we allow pingbacks and trackbacks to be included in the endpoint response also.
* Make this PR active on a Jetpack site with pingbacks and/or trackbacks. This can be done with the Jetpack Beta plugin too, by selecting `add/comments-tree-endpoint-pingbacks-trackbacks` from Jetpack > Jetpack Beta > Search for a Jetpack feature Branch.
* Hit the WP.com API `comments-tree` endpoint for that site, and verify that any pingbacks and trackbacks are included. This can be done in the [WordPress.com API dev console](https://developer.wordpress.com/docs/api/console/), at `GET
v1/sites/(JP site URL)/comments-tree`.
* If using the dev console, be sure to sandbox the API, and …
=> Add pingbacks and trackbacks to the response of the comments tree endpoint.

class.jetpack.php
Provided that this option is turned on, this will point all front end post edit URLs to Calypso, instead of WP-Admin.
1. Use a Jetpack connected test site.
2. Since the option does not exist yet, change [this line](https://github.com/Automattic/jetpack/compare/add/edit-post-calypso-redirect?expand=1#diff-9ba9fa5bb52bd6cf36c6c0bdd5ed4830R617) to:
`if ( get_option( 'jetpack_edit_links_calypso_redirect', true ) && ! is_admin() ) {`
3. Open a post or page from your site's front end and verify that edit links redirect correctly to Calypso.
4. Test with supported Custom Post Types too (Portfolios and Testimonials).
=> Point edit post URLs to Calypso

bin/partner-provision.sh
We need to add the params to the parsing block otherwise they are not recognized as valid params and the command bails with usage instructions.
* Without patch, call the script with either the `--force_connect=1` or `--force_register=1` flag, or both:
```
$ ./bin/partner-provision.sh --partner_id=1 --partner_secret=2 --wpcom_user_id=1 --force_register=1
Usage: partner-provision.sh --partner_id=partner_id --partner_secret=partner_secret [--user=wp_user_id] [--plan=plan_name] [--onboarding=1] [--wpcom_user_id=1234] [--url=http://example.com] [--force_connect=1] [--force_register=1]
``` 
This will output the Usage instructions.
* Apply patch and run again and verify that the script actually executes (it may still fail unless you provide valid data)
```
$ ./bin/partner-provision.sh …
```
=> Fix `force_*` params for partner provision script

_inc/client/state/jumpstart/actions.js, _inc/client/state/settings/reducer.js, modules/comments.php, modules/likes.php, modules/module-headings.php, modules/monitor.php
Suggested by @beaulebens in p2JiWH-29g-p2:
> I think we should include Monitor, Likes and Comments into the Jumpstart Features.
I just copied the descriptions from what was already there, but could use a review.  
This also fixes a bug where Photon and the other Jumpstart modules did not display as active in the UI.  it just needed a state update to the `settings` branch of the tree.  
**To Test:**
- Connect Jetpack
- Click "reset options (dev)" in the footer
- Jumpstart your site
- Verify the modules were activated.
=> Jumpstart: Adding Comments, Likes, and Monitor to Jumpstart features

json-endpoints/jetpack/class.jetpack-json-api-cron-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php, sync/class.jetpack-sync-actions.php, sync/class.jetpack-sync-sender.php
Fixes #
Getting sync status when not using the `full_sync` module.
* request GET /sites/%s/sync/status where the sync module is disable
```
add_filter( 'jetpack_sync_modules', array( __CLASS__, 'custom_jetpack_sync_modules' ) );
/**
* Define what Jetpack sync modules to enable
* @param  array $modules
* @return array
*/
public static function custom_jetpack_sync_modules( $modules ) {
return array(
//'Jetpack_Sync_Module_Constants',
//'Jetpack_Sync_Module_Callables',
//'Jetpack_Sync_Module_Options',
//'Jetpack_Sync_Module_Network_Options',
//'Jetpack_Sync_Module_Terms',
//'Jetpack_Sync_Module_Themes',
//'Jetpack_Sync_Module_Menus',
//'Jetpack_Sync_Module_Users',
'Jetpack_Sync_Module_Posts',
//'Jetpack_Sync_Module_Comments',
//'Jetpack_Sync_Module_Updates', …
```
=> Sync: Update Sync Status Endpoint

modules/masterbar/masterbar.php
Add Comments to My Sites menu in order to sync it with WP.com masterbar.
Resolves https://github.com/Automattic/jetpack/issues/7651
1. Use a Jetpack test site with WordPress.com Toolbar module enabled.
2. Visit site's front end and open up My Sites menu.
3. You should see a `Comments` field in `Manage` section.
**_Note:_** In case the icon is not showing up for you, you can try to manually bust the cache [here](https://github.com/Automattic/jetpack/blob/master/modules/masterbar/masterbar.php#L112) for testing purposes. This will happen automatically once the Jetpack version is bumped.
=> WordPress.com Toolbar: add Comments to My Sites menu

modules/comments.php
After the conversation in #7682, we've decided to omit the Comments feature from Jumpstart, as there is concern that we need to be more defensive.  There are too many plugins/themes out there that customize WP comments and we'd like to minimize the possibility of unintentional conflicts with them.
=> Remove comments from Jumpstart

class.jetpack-client-server.php, class.jetpack-debugger.php, class.jetpack-network.php, class.jetpack.php, modules/custom-css/custom-css-4.7.php, modules/monitor.php, modules/protect.php, modules/widgets/migrate-to-core/image-widget.php
@gravityrail was auditing the connection flow today, and found that a missing exit after a redirect was causing stats to be double counted in cases. 
This sparked an audit by @georgestephanis of the Jetpack code base for `wp_redirect()` without an exit and I followed up with an audit of `wp_safe_redirect()` without an exit.
This PR fixes cases of `wp_redirect` and `wp_safe_redirect` without an exit or die afterwards.
Test steps TBD.
=> General: Exit after redirecting

class.jetpack-client-server.php
After stepping through some connection code today, @beaulebens pointed out a potential issue where it seems like we were firing the `jetpack_client_authorized` inappropriately. Before this patch, it seems like we fire the `jetpack_client_authorized` action on both successful and errored authorizations.
It looks like this hook was added in #4347 to handle kicking off a full sync after connecting a site to WordPress.com.
I don't imagine this is causing much of an issue in production since it's only hooked in `class.jetpack-sync-actions.php` to start a full sync, and even then, the method that kicks off the full sync short-circuits if sync is not allowed. But, we should fix it all the same.
=> Connection: Fire jetpack_client_authorized action if no error

functions.global.php, sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
Fixes pNEWy-9C9-themedevp2
Fixes #7348
* perform Jetpack theme updates using credentials
* if theme upgrade fails, don't try to sync because there's nothing to work with and it fatals
* add a free and premium Jetpack themes, downgrade them manually editing the `style.css` and then try updating them in `update-core.php` page and in themes, using inline upgrade.
Perform Jetpack theme updates using credentials.
=> Update themes using credentials

_inc/client/components/connect-button/index.jsx, _inc/client/components/connect-button/test/component.js, _inc/client/components/jetpack-connect/index.jsx, _inc/client/components/jetpack-connect/style.scss, class.jetpack-client-server.php, class.jetpack-connection-banner.php, class.jetpack-xmlrpc-server.php, class.jetpack.php, functions.global.php, modules/publicize/publicize-jetpack.php, scss/organisms/_banners.scss, views/admin/must-connect-main-blog.php
Right now it's hard to improve quality across the board because of inconsistent identifiers between WPCOM and Jetpack.
This PR aims to include a number of changes to address that.
- ensure informed consent info is present on all connect buttons
- send tracks user_id and type (either anon or wpcom ID) with register and authorize requests
- add a number of new events
Register:
- `jetpack_jpc_register_begin`
- `jetpack_jpc_verify_register_begin`
- `jetpack_jpc_verify_register_success/fail`
- `jetpack_jpc_register_success/fail`
Authorize:
- `jetpack_jpc_remote_authorize_begin`
- `jetpack_jpc_verify_authorize_begin`
- `jetpack_jpc_verify_authorize_success/fail`
- `jetpack_jpc_remote_authorize_success/fail`
=> Add more consistent instrumentation

_inc/client/components/jetpack-banner/index.jsx
Fixes #7235
This makes sure to hide all `JetpackBanners` that are being used to promote paid plans from users that are not able to purchase them.  
I'm doing this by blocking the banner if there is a `plan` prop passed and user is not admin, as the `plan` prop is required for upgrade banners, I figure it's a good indication of whether or not it's being used as such.  
To Test: 
- Make sure you're not seeing any upgrade to purchase a plan as a non-admin. 
- Make sure the non-upgrade JetpackBanners are being rendered
- Make sure you see them correctly as an admin.
=> Hide Upgrade banners from non-admins

_inc/client/at-a-glance/index.jsx
Neither the cog nor the "manage security" text should show to non-admins, as they're unable to manage it in Calypso anyway.  
To Test: 
- Make sure those links don't show for a non-admin 
- Make sure they do show for an admin
=> Hide the 'manage security' link on the dashboard from non-admins

sync/class.jetpack-sync-actions.php
* Connecting from a fresh MU installation fails due to lacking the sync modules class, this requires it in the sync actions class, since it's used here and any file could pull it in.
* Create MU site, connect from network admin
=> Fix Multi-Site Connections

_inc/client/components/settings-card/index.jsx, _inc/client/components/themes-promo-card/index.jsx
For the purposes of optimized internal tracking, we need to send `type:
upgrade` as a property to any click event attached to a ‘upgrade’ CTA.
Currently, upgrade CTAs on any of the ‘Settings’ cards, as well as the
‘Plans’ tab, lack this property. This PR fixes that.
=> Update tracking props being sent with any upgrade CTA click events.

class.jetpack-network.php
In #7697 we added instrumentation for register() requests, but we didn't add it to the subsite register request.
This PR adds that.
=> Add tracks identity for subsite register requests

modules/tiled-gallery/tiled-gallery/tiled-gallery.js
* allow `post-load` custom event to pass a parameter so that when it's `resize`, the galleries are resized. When it's not passed or is different from `resize`, it will perform the usual task: find and setup new galleries.
* setup a tiled gallery and execute this in JS console:
`jQuery( 'body' ).trigger( 'post-load', ['resize'] );`
you can verify that it worked by altering first the inline dimensions like these and checking that the image is ok after running the code in console
or you can add a `console.log` [here](https://github.com/Automattic/jetpack/pull/7652/files#diff-4f9b83c204105157a58e1d538ab4925fR147).
Tiled Gallery: allow to resize galleries already loaded by passing 'resize' to the 'post-load' custom event.
=> Tiled Gallery: resize galleries passing a parameter to a custom event

modules/contact-form/grunion-contact-form.php, tests/php/modules/contact-form/test_class.grunion-contact-form.php
This PR takes a different approach from #7367 to avoid the need for any escaping.
Currently in the To: field we use:
`"foo.bar@example.com" <foo.bar@example.com>`
To avoid any need to escape the @ char in the display name part, instead use:
`"foo.bar" <foo.bar@example.com>`
Fixes #7276 
**To Test**
* Use testing instructions in #7276
=> Contact Form: Fix problem sending mail from SiteGround

class.jetpack-options.php, class.jetpack.php
Instead of using a separate site option for Calypso redirect switch, let's utilize existing Jetpack options functionality. This was suggested by @beaulebens in https://github.com/Automattic/jetpack/pull/7702.
1. Use a Jetpack connected test site.
2. Since the option will not be set, change [this line](https://github.com/Automattic/jetpack/compare/update/move-calypso-edit-option?expand=1#diff-9ba9fa5bb52bd6cf36c6c0bdd5ed4830R618) to:
`if ( Jetpack::get_option( 'edit_links_calypso_redirect', true ) && ! is_admin() ) {`
3. Open a post or page from your site's front end and verify that edit links redirect correctly to Calypso.
Test with supported Custom Post Types too (Portfolios and Testimonials).
=> Move Calypso redirect option to Jetpack options

modules/masterbar/masterbar.php
Fixes https://github.com/Automattic/jetpack/issues/6993
I wasn't able to reproduce this bug, but the detailed steps are outlined in https://github.com/Automattic/jetpack/issues/6993. My guess is that for some reason `jquery` is not required on those sites, and it results in an error since the `masterbar-overrides.js` script from WP.com requires it to work.
=> WordPress.com Toolbar: add jQuery as a dependency for dotcom script

modules/sitemaps/sitemap-buffer.php, tests/php/modules/sitemaps/test_class.sitemap-buffer.php
If a site has no posts in a while a news sitemap can be empty. Previously it didn't contain a root element in this case, now it does. This fixes a yellow screen of death (at least on Firefox).
* Always generate a root element no matter if the sitemap has not had any items added.
* Get a site with no recent posts to test or modify the code to [empty the recent posts array](https://github.com/Automattic/jetpack/blob/master/modules/sitemaps/sitemap-builder.php#L943).
* You may want to tweak the conditional to disregard [existing cache entries](https://github.com/Automattic/jetpack/blob/master/modules/sitemaps/sitemap-builder.php#L918), it will be easier to test this way.
* Open the news sitemap.
* Observe the XML element without a root element, which should give you an error.
* Use this PR, …
=> Fixed empty sitemap YSOD.

.travis.yml, readme.txt
Travis tests for PHP 5.2 have stopped working again due to a missing download file.
We might as well take this opportunity to stop testing on PHP 5.2 and recommend that people upgrade since this version of PHP is insecure and extremely outdated.
This also sets the minimum PHP version in readme.txt as per the [WordPress Plugin guidelines](https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/).
=> Remove PHP 5.2 support

modules/masterbar/masterbar.php
See https://github.com/Automattic/wp-calypso/issues/16812.
This PR adds a few hooks to the `modules/masterbar/masterbar.php` that make it possible to hook in and add new links to each menu section.
Our proposed usage for this is to add a `Store` link to the menu when applicable, so we can match the menu in Calypso/WordPress.com
* Go to the front end of your site and open the "My Sites" menu and make sure everything looks correct.
* You can add a test snippet to test adding entries to the menu:
```
add_action( 'jetpack_masterbar', function() {
global $wp_admin_bar;
$wp_admin_bar->add_menu( array(
'parent' => 'blog',
'id'     => 'store',
'title'  => esc_html__( 'Store', 'jetpack' ),
'href'   => 'https://wordpress.com/store',
'meta'   => array(
'class' => 'mb-icon-spacer',
)
) );
} );
```
=> Add hooks to the masterbar my sites menu

_inc/lib/class.core-rest-api-endpoints.php
If sites have XMLRPC blocked for security reasons, Jetpack will fail to connect.
This PR adds REST versions of the two most critical XMLRPC methods so that we can still connect, even though other things will also fail. This at least allows us to get users started with Jetpack so that we can help them make their site compatible.
To test:
- Block XMLRPC on your server like this (nginx example):
```
location = /xmlrpc.php {
deny all;
access_log off;
log_not_found off;
}
```
- Attempt to connect
- You should be able to connect! But things like auto-installing VaultPress/Akismet will fail later.
Here's a screenshot of ngrok logged requets during Jetpack Connect.
=> Jetpack Connect: Add REST fallback for connect endpoints

class.jetpack-tracks.php, class.jetpack-xmlrpc-server.php
Fixes an issue where we weren't properly identifying events triggered during authorization. This PR uses the `state` passed with authorize and verify events to look up the user who is connecting the site.
cc @withinboredom
=> Look up user for verify and authorize method instrumentation

modules/subscriptions.php, modules/subscriptions/block.css, modules/subscriptions/block.js, modules/subscriptions/block.jsx, modules/subscriptions/subscriptions.css
Initial once through for creating a Gutenberg Block based on the Jetpack Subscription Form.
The js should probably get yanked to its own file and done in es6, but this works for now and saves an additional file to sync and transpile.
CheckboxControl doesn't seem to update.  I may be missing something there.
Apart from that, seems to work.
=> Gutenblock: Jetpack Subscription Form

class.jetpack-xmlrpc-server.php
Our remote_authorize errors weren't adding up, and I realised that we had verify errors not being captured before being returned.
=> Track remote authorize IXR errors

class.jetpack-client-server.php
Fixes an issue where instrumentation was losing events because WPCOM didn't have a Jetpack anon ID for token requests.
This PR also moves the client authorize success event to the end of the authorization response to allow for other failures.
=> Instrument token request

class.jetpack-network.php, class.jetpack.php, tests/php/bootstrap.php, tests/php/test_class.jetpack.php
In order to understand how our users are discovering and activating Jetpack, this change parses the referer or WP_CLI environment and extracts out useful stuff to know, then includes it with the register and authorize URLs.
The plugin activation source is split into two parts: the source name, and any keywords associated with it (or null).
Currently detected activation sources:
- wp-cli
- list
- featured
- popular
- recommended
- favorites
- search-term (plus query)
- search-author (plus query)
- search-tag (plus query)
=> Record discovery terms

modules/stats.php
Fixes #7141
* switch from `esc_html_e()` to `wp_kses( __() )` to allow `<strong>` tag output without escaping.
* remove unnecessary whitespace (removed automatically on save in Atom IDE)
* Visit the "Configure Site Stats" page (`/wp-admin/admin.php?page=jetpack&configure=stats#/`). The description for the Smiley field checkbox contains an escaped `<strong>` tag in the description.
* With this patch, the text should be bolded rather than display the `<strong>` tag.
=> Fix escaped html in option description on "Configure Site Stats" page

docs/development-environment.md, tests/php/bootstrap.php
The unit testing instructions were pretty dated, including a reference to the unmaintained standalone WP unit tests repo.
This PR updates them to be more explicit, and adds auto-detection of a standard VVV environment so that tests "just work" even if installed inside an alternative WP version for VVV hosting purposes.
=> Update development instructions for unit testing

class.jetpack-cli.php
When Jetpack Protect is first installed, the option
`jetpack_protect_whitelist` does not exist, which means the whitelist
command tries to iterate over FALSE, so you get warnings:
```
PHP Warning:  Invalid argument supplied for foreach() in
/path/to/wp-content/plugins/jetpack/class.jetpack-cli.php on line 381
Warning: Invalid argument supplied for foreach() in
/path/to/wp-content/plugins/jetpack/class.jetpack-cli.php on line 381
Success: 4.2.2.2 has been whitelisted.
```
Squelch these messages to tidy things up for novice users.
* Silence PHP warnings when whitelist option is empty.
* On clean installation, `wp jetpack protect whitelist list` should emit no warnings.
Note that `whitelist clear` does not erase the whitelist option, so no warnings there.
=> Squelch warning in wp-cli protect whitelist on new install

class.jetpack-client-server.php, class.jetpack.php
Today, while testing Jetpack Onboarding, with latest `master` for Jetpack, I cleared out the connection on my site with:
- `wp option delete jetpack_options`
- `wp option delete jetpack_private_options`
Then, when I tried to reconnect, I got an `ERR_TOO_MANY_REDIRECTS` error in Chrome. Upon debugging, it looks like `build_connect_url` got into some loop where it kept trying to register. Here's some debug.
```
[04-Sep-2017 21:04:54 UTC] do_action('load-toplevel_page_jetpack'), WP_Hook->do_action, WP_Hook->apply_filters, Jetpack_Admin_Page->admin_page_load, Jetpack->admin_page_load, Jetpack->build_
connect_url
[04-Sep-2017 21:04:54 UTC] {"register":true,"token":"*****************","site_id":14310116}
[04-Sep-2017 21:04:54 UTC] do_action('load-toplevel_page_jetpack'), WP_Hook->do_action, …
```
=> General: Connection: Only force register on build_connect_url max one time

modules/contact-form/grunion-editor-view.php
Fixes #7608 
`plugins_url()` is being filtered by [`maybe_min_asset()`](https://github.com/Automattic/jetpack/blob/f4cd94c378cd49349625f768849240e7ab237605/class.jetpack.php#L5961) to use a minified file path if a minified file exists.
This causes an issue when passed to `add_editor_style()`, which according to the [codex](https://developer.wordpress.org/reference/functions/add_editor_style/) "automatically adds another stylesheet with -rtl prefix, e.g. editor-style-rtl.css."
This results in a url pattern like editor-style.min-rtl.css, where the `-rtl` string is appended to the min extension, rather than the root filename.
* Switch from `plugins_url()`, which is filtered, to `plugin_dir_url()`, which is unfiltered
* You can see the stylesheets passed to TinyMCE by adding `var_dump( …
=> Remove incorrect RTL filepath in Contact Form module's editor css

readme.txt
We're not quite ready to "officially" set this requirement.  Let's remove it until we have a more solid plan going forward.
=> Remove required PHP version from readme

_inc/client/admin.js
* Adds the Redux `store.dispatch` method to `window` if `process.env.NODE_ENV === 'development'`. 
* Adds the Redux action types  to `window.actionTypes` if `process.env.NODE_ENV === 'development'`. 
1. Run `yarn build` to build the development version of Jetpack's UI.
1. Confirm that you can dispatch actions from the browser's console. Like `dispatch()`.
1. Confirm that `window.actionTypes` is defined and it holds all of the action types defined in `_inc/client/state/action-types.js`.
1. Run `yarn build-production` to build the development version of Jetpack's UI.
1. Confirm that neither `window.dispatch` or `window.actionTypes` is defined.
Added utility functions to the browser's console allowing easier debugging of the Redux state while in development mode.
=> Add dispatch and actionTypes properties to the global window object so we can use it from the browser console when developing

_inc/lib/class.core-rest-api-endpoints.php, class.jetpack-jitm.php, class.jetpack.php, tests/php/test_class.jetpack-jitm.php
JITMs are initialized as soon as the JITM file is loaded, which is before `init` and before `Jetpack::init()`, which makes it hard to intercept; separately, we call Jetpack_JITM::init() in our APIs, which when invoked directly doesn't respect the `jetpack_just_in_time_msgs` filter.
This also adds cache control, related to the issue mentioned in the conversation: p1506030617000439-slack-jpop-jedi-council
This PR fixes both those issues and adds the beginning of JITM tests.
cc @withinboredom
=> Initialize JITMs later; add tests

class.jetpack-jitm.php
Fixes #7849
* Don't show Just in Time Messages in development mode
* With a fresh, free plan site
* And Jetpack in dev mode, while connected
* Visit comments screen, should see no jitms
* Turn off dev mode and go back to comments screen
* should see jitms
* Don't show Just In Time Messages while in dev mode
=> Fixes #7849: don't show jitms in development mode

modules/simple-payments/paypal-express-checkout.js, modules/simple-payments/simple-payments.php
Implementing @iamtakashi 's idea to add icons of accepted credit cards under the PayPal "Pay with" button:
Create a Simple Payments button. See if the CC icons show up.
=> Simple Payments: add CCs icons to Pay with btn

class.jetpack-jitm.php, class.jetpack.php
In reviewing #7833, I realized that the docblocks were incorrect for a couple of JITM filters. While the default state for JITMs is to be on, that is only because we filter in the `Jetpack` class and return true on a priority of 9. The filters for JITMs are provided a false value which means if we didn't hook on in the `Jetpack` class they would return false.
The docblocks now reflect the default args correctly.
=> JITM: Fix docblock for default argument value

modules/widgets/contact-info.php
This should help with SEO, as Google uses this to more easily discover
metadata about businesses.
More info on the schema from Google: https://developers.google.com/search/docs/data-types/local-businesses
This patch is based on `D7261-code` by @scruffian - I'm just porting it to Jetpack.
* Adding `LocalBusiness` Schema Markup markup to the Contact Info widget.
* Use Google's testing tool, https://search.google.com/structured-data/testing-tool/u/0/, to verify that the fields have been properly discovered.
This is how it looks like using the default values of the contact info widget:
It seems that due to the limitations of the contact info widget (the address is just one big textarea), we can't precisely define/declare all the parts of a postal address - so it's not properly found.
The …
=> Widgets: Add schema.org markup to the contact info widget

modules/comments/comments.php
Lets fix the comment expention, by only trying to do it after the dom has loaded also wrap evenything in a self-executing anaonomous function so we don't pulte the global name space.
Fixes #
* Only start listening to the changes after the whole page has loaded.
* Does it fix the bug on http://single.lamdayap.com/blog/another-notification/ 
* Does it still work as expected across all the browsers?
=> Try fixing the comment expansion

json-endpoints/class.wpcom-json-api-get-site-endpoint.php
When we check that user is a member of blog, let's use current_blog_id() rather than remote blog id.
For more information and context
See corresponding JPOP issue.
And: 686842-zen
=> JSON API: GET site endpoint

class.jetpack-network.php, class.jetpack.php
When users connect Jetpack, the very first step is registration.
A couple of hundred sites a day fail registration because of timeouts, and of these the vast majority are sending us a timeout of 15 seconds or less (the timeout sent by Jetpack is 50% of the `max_execution_time`, to allow for multiple connection attempts). 
This is because in order to register the site, WPCOM must make a couple of requests, and some Jetpack sites are pretty slow.
Some sites appear to have execution timeouts as short as 10 seconds, which is not anywhere near enough to register a lot of the time.
This change tells PHP to increase the local `max_execution_time` for the duration of the register() step so that WPCOM has more time to register the site. If the request timeout is already longer than 60 seconds, it …
=> Try to set longer timeouts for Register() in connect

_inc/client/components/support-card/index.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php, functions.global.php, modules/masterbar/masterbar.php
Force the display of WordPress.com Toolbar on Atomic sites regardless of value of `show_admin_bar` user setting. This is done in order to make the experience similar to WP.com where this option has been discontinued.
Fixes https://github.com/Automattic/jetpack/issues/7667
1. Use a test Jetpack site with WordPress.com toolbar module enabled.
2. Navigate to `/wp-admin/profile.php` of your test site and disable the `Show Toolbar when viewing site` option.
3. Visit the site's front end and verify that the WordPress.com Toolbar is no longer present.
4. In order to simulate the Atomic site environment, mock the `jetpack_is_atomic_site()` function to always return `true`.
5. Visit the site's front end and verify that WordPress.com Toolbar is now visible.
6. Verify that all usages of old …
=> WordPress.com Toolbar: override user setting for hiding the toolbar

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
Currently we might not have the complete author info when we publish a post don't have a good way to display the author info.
This PR adds the author infor we care about to the publish sync action so that we can use it in the activty log.
Part 1 in fixing the activity log. 
* Adds author information to the activity log publish post action.
=> Sync: Add author to the published post sync action

modules/likes.php
Adds a stub for this method, since there are some themes that were calling this method directly.
=> Likes: Add stub for is_likes_visible in Jetpack_Likes class

modules/infinite-scroll/themes/twentyeleven.php, modules/infinite-scroll/themes/twentyfifteen.php, modules/infinite-scroll/themes/twentyfourteen.php, modules/infinite-scroll/themes/twentyseventeen.php, modules/infinite-scroll/themes/twentysixteen.php, modules/infinite-scroll/themes/twentyten.php, modules/infinite-scroll/themes/twentythirteen.php, modules/infinite-scroll/themes/twentytwelve.php
Yesterday @dereksmart requested me to namespace all functions here: #5940. 
He has agreed that since we are going to namespace the functions in twentyseventeen.php file, we should definitely namespace the functions in other theme files too ( twentyten.php, twentytwelve.php etc ). Meanwhile I found few more issues that I think will be nice to be addressed too.
* Added `jetpack_` prefix to all Infinite Scroll theme functions.
* Changed the function names, so they will be consistent with the themes. For example:
* twenty_ten -> twentyten
* twenty_eleven -> twentyeleven
* Removed usage of `infinite_scroll_has_footer_widgets `, and change it to use `footer_widgets` setting instead.
* Changed several comments, so they will be consistent in all files.
* Added new line at the end of the files, …
=> Infinite scroll: Namespace and refactor theme function

sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-users.php, tests/php/sync/test_class.jetpack-sync-callables.php
In order to allow invitations for custom roles we need to sync the list of roles to WPCOM.
See: https://github.com/Automattic/jetpack/issues/7812
=> Sync: Sync `get_editable_roles`

.circleci/config.yml
* Adds a config to run the [e2e tests](https://github.com/Automattic/wp-e2e-tests) against a dynamically created / activated Jetpack site.
* Uses a webhook to CircleCI to run the tests
1) You merge a change into Jetpack master, and a CircleCI webhook fires (it actually fires on every branch, but the Circle config restricts it to only run against master or branches with “e2e” in the name)
2) On the CircleCI container it does a git clone of the latest wp-e2e-tests master. I debated making it a submodule, but I didn’t want to add any unnecessary dependencies to the repo.
3) A new WP site is built via the ServerPilot API on a DigitalOcean droplet
4) It SSHes in and installs the latest Jetpack master on the site. (I have a clone of the repo already on the server, and it just copies it into the …
=> Add config to run e2e tests against master branch

_inc/client/components/settings-group/style.scss
Fixes #7134
* Update the display property to resolve IE11 display issues, and switch from margin to padding to retain the spacing intended in the [original commit](https://github.com/Automattic/jetpack/commit/134a1f0dd586c60ae4989cc33328a5a39bc0fd3f#diff-25fe11b65ebc031d13de1c4b6d5b9d56R48).
* Using browserstack to emulate IE11, visit the module settings page of a jetpack site (`/wp-admin/admin.php?page=jetpack#/settings`). Without this patch, all card content should be pushed to the left (as seen in #7134).
=> updating card spacing method for ie11 compatibility

modules/contact-form/css/grunion.css, modules/contact-form/css/jquery-ui-datepicker.css, modules/contact-form/grunion-contact-form.php, modules/contact-form/grunion-editor-view.php, modules/contact-form/js/grunion-frontend.js
Date field support was started in https://github.com/Automattic/jetpack/commit/40e7bbe8de7f42a528ed2854bd49e738dcb2b4d0. This PR aims to complete the feature and address some of the issues raised in #269 and #3578.
* Detect [browser support](https://caniuse.com/#search=input%20date) for `<input type="date">` elements, and conditionally setup jQuery datepicker only if native date field browser support is not available. This solves the issue reported in #269 where both the jQuery datepicker and native browser datepicker appear simultaneously.
* Add styles for jQuery datepicker (none existed previously). These were borrowed from @JJJ's [open source style library](https://github.com/stuttter/wp-datepicker-styling/blob/master/datepicker.css)  🎉, and are meant to be minimal.
* Add date field as …
=> Add full support for Contact Form Date Field

modules/widgets/milestone/admin.js, modules/widgets/milestone/milestone.js, modules/widgets/milestone/milestone.php, modules/widgets/milestone/style-admin.css
This PR adds a new _Time Unit_ setting and enables counting up to a milestone in addition to counting down.
The options are:
* Automatic (default)
* Months
* Days
* Hours
The _Time Unit_ setting implements the following logic on the front-end:
_Automatic (how it currently works)_
* More than 2 years - show in years to one decimal point
* Fewer than 2 years - show in months
* Fewer than 3 months - show in days
* Less than 1 day - show in hours
* Less than 1 hour - show in minutes
* Less than 1 minute - show in seconds
_Months_
* More than 1 month - show in months
* Less than 1 month - show in days
* Less than 1 day - show in hours
* Less than 1 hour - show in minutes
* Less than 1 minute - show in seconds
_Days_
* More than 1 day - show in days
* Less than 1 day - show in hours
* Less than …
=> Milestone Widget - Add "Time Unit" setting and ability to count up to a milestone

class.json-api-endpoints.php
`wp-admin` allows a user to edit a comment author's name, email, and URL. This can be done for both logged-out and logged-in users.
If a comment author is logged-in when commenting, the stored comment will also have the comment author's user ID. The presence of this ID will fail [this check](https://github.com/Automattic/jetpack/blob/b44640a3572b2579e73d6e47c0f7ecb1251f0d30/class.json-api-endpoints.php#L1064) in `get_author()`, and the author object returned by an API call will reflect the user based on that ID; any edited name, email, or URL in the comments table will be bypassed.
This PR seems like the simplest way to get at the edited data: if the "author" passed in is a comment row (as determined by the presence of `comment_author_email`, which is required when commenting), return …
=> REST API: Fix the comment author object for comments whose author info has been edited.

modules/widgets/top-posts.php
Fixes #7402
When you want to see the default title in the widget, let's display it.
* Add a Top Posts Widget to your sidebar.
* Set a custom title for that widget, ensure it gets saved and displayed on the site and in the widget setting screen.
* Now change that title to "Top Posts & Pages"
* When saving your changes, make sure the title doesn't disappear from the widget settings.
* Top Posts Widgets: display the default title when it is set to false.
=> Top Posts: display the default title when it is set to false.

sync/class.jetpack-sync-defaults.php
Customizer changesets can be used to store for a week pending changes via the Customizer. There is no work done on our site regarding this data and is not useful at this time.
If we're using this data for anything, we can close this PR, but I'm not aware of anything.
Additionally, orders the list of post types.
cc: @david-binda
=> Sync: Stop syncing Customizer changesets

docs/rest-api.md
Updates `docs/rest-api.md` to be up to date to latest endpoints behavior.
* Improves `/settings` endpoint documentation
* Clarifies that the modules endpoint are not super useful anymore.
* Check how the document in this branch looks like: [rest-api.md](https://github.com/Automattic/jetpack/blob/update/improve-api-docs-again/docs/rest-api.md)
Improved documentation for Jetpack REST API endpoints.
=> Jetpack REST API: Update endpoint docs

tests/php/modules/shortcodes/test_class.tweet.php
It looks like wp_oembed_get that is used in the shortcode returns a shortened version of the Twitter URL, which breaks the test. The simplest way out here seems not to test for that URL, just for the existence of some Twitter card-like markup.
Fixes current Travis CI breakage.
=> Removed testing for the URL from the tweet unit test.

class.jetpack-signature.php
Fixes a typo in an unused aspect of the code :P
* Changes `sheme` for `scheme` in an error code.
* Couldn't find any references in .com code, Jetpack code, or anywhere else. So regular check with your own eyes is fine.
=> Jetpack Signature: Fix spelling of 'invalid_scheme' in class.jetpack.signature.php

json-endpoints.php, json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php
This commit syncs r162791-wpcom.
Fixes #
Related: https://github.com/Automattic/jetpack/pull/7817
* This changeset rolls the /site/siteID/settings GET and POST endpoints to v1.3 and adds anonymize_ip, ec_track_purchases and ec_track_add_to_cart flags to the wga (Google Analytics) setting.
* Install this branch on a site and then:
```
Fire up postman
Set your headers to
Content-Type: application/json
Authorization: BEARER (steal a token from a developer REST API console request)
Origin: https://developer.wordpress.com
(you'll need to use Postman Interceptor to pull that off)
Direct a v1.3 GET request at /site/{siteID}/settings ( e.g. /sites/#######/settings )
( i.e. public-api.wordpress.com/rest/v1.3/sites/########/settings )
Ensure you get a wga key in the response and that it has the …
```
=> Google Analytics: Add support for new settings to endpoints (Differential Revision: D7273-code)

modules/google-analytics/wp-google-analytics.php
Fixes #7777 #7778 
Related: https://github.com/Automattic/jetpack/pull/7869
WORK IN PROGRESS
* The present Google Analytics module in Jetpack only looks for the tracking code (the UA code) in settings.
* We are adding three other fields to the jetpack_wga option  (and, as a separate PR, to the endpoint that sets that option)
* The three other fields are
1. anonymize_ip - allows IP anonymization. It defaults to off.
2. ec_track_purchases - syncs WooCommerce order amounts and items to Google Analytics as orders are received. Defaults to off.
3. ec_track_add_to_cart - notifies Google Analytics (as an event) when customers add items to their carts. Defaults to off.
* In addition to the endpoint, there will be a wp-calypso PR to allow the user to control these new settings.  For now, for …
=> Google Analytics: Add support for IP anonymization and basic ecommerce tracking

modules/masterbar/masterbar.php
As part of our Plugins Page Enhancements project we updated the sidebar plugins nav item in Calypso. For Jetpack and Business sites we replaced the "Add" option with a "Manage" option.
This updates the the Master bar to reflect these changes
**Testing**
- Visit the frontend of a Jetpack site
- Open the the sidebar menu from the master bar
- The plugins nav item should display "Manage" and link to https://wordpress.com/plugins/manage/site-slug
=> Master Bar: update Plugins sidebar nav

class.jetpack.php
Fixes this issue
```
Undefined variable: widget_title in /wp-content/plugins/jetpack/class.jetpack.php on line 6745
```
* dismiss variable assignment so avoid an undefined variable when Jetpack is not connected but jetpack_dashboard_widget has an action
* check dashboard with a disconnected site with and without this PR. WP_DEBUG must be set to true
=> General: solve undefined variable in Dashboard widget when site is disconnected

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, class.jetpack-options.php, class.jetpack.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
While this token is now a created a network Jetpack option and will be valid for all sites in the network, it doesn't pose a threat because the `user_email` must match a user added to the site and the new checking introduced will ensure this and also the WP REST API endpoints will provide the proper validation for that. The onboarding token is just one part of the validation to ensure that the request comes from a trusted site but the new checking and the REST validation will check that the user has the permissions to execute the desired operation.
* create Jetpack_Option `onboarding` as a `network` option so it can be read from a child site in a multisite
* introduces one new test for onboarding option
* fixes issue after connection when saving anything to `jetpack/v4/settings` like …
=> Onboarding: create the token as a network option.

class.jetpack.php, modules/module-extras.php
This is required because with some recent changes in the code SEO tool class constants are required by the code even when Jetpack is not active, for example in multisite environment.
Fixes #7898.
=> SEO tools suite loading even if the site is not active and not in development mode.

modules/contact-form/css/grunion.css, modules/contact-form/css/jquery-ui-datepicker.css, modules/contact-form/grunion-contact-form.php, modules/contact-form/grunion-editor-view.php, modules/contact-form/js/grunion-frontend.js
There's some issues popping up in review (#7885, #7887, #7888, #7889) that appear to step from spotty cross-browser support for the HTML5 date input field.
Some information about this can be found here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Handling_browser_support
jQuery datepicker is already being used for fallback support in legacy browsers (added in #7819). This PR converts the default display from HTML5 date input to use a text input + jQuery datepicker always.
* Switch contact form HTML5 date input to a text input with `date` class.
* Remove conditional logic so that jQuery datepicker is always used for text inputs with class `date` (instead of only as a fallback for browsers that don't support the date input type).
* Fixes the duplicate year issue …
=> Contact Form: Convert HTML5 date input to text input + jQuery Datepicker

tools/builder/frontend-css.js
Changes in #7767 led to the `gulp frontendcss` task building to a file `jetpack.rtl.css`, where we need `jetpack-rtl.css`.  This will fix it! 
to test: 
- run `gulp frontendcss` task 
- make sure the correct files get updated.
=> Fix -rtl suffix for gulp task

class.json-api-endpoints.php
A previous change in #7707 could lead to incorrect avatars being displayed on Highlander comments made through Facebook. This fix restores the `get_avatar_url()` param to its previous `$author` value.
WPCom: D7075 (which is #7707 plus this correction)
=> REST API: Correct Highlander comment avatars.

class.jetpack-options.php, tests/php/test_class.jetpack-options.php
In some cases it might be better if we bypassed that option to get the raw info.
* Allows other devs to define constants and filters that lets them define which options should be allows to be set directly. 
=> jetpack raw option: Add a way to bypass it

sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-functions.php, tests/php/modules/shortcodes/test_class.kickstarter.php, tests/php/sync/test_class.jetpack-sync-callables.php
See #7907
* `get_editable_roles` is undefined on non admin pages
* it is also specific to the user so it could change depending on the user loading the admin
*How to test*
* Run this branch
* Check that you don't get any warnings on the frontend or backend
=> Sync: Fix warning caused by get_editable_roles

modules/google-analytics/wp-google-analytics.php
Fixes #7913
**Found in 5.4-beta3 - This is a fix for 5.4**
* Tests for WooCommerce before attempting to use it.
* Force ecommerce tracking on, e.g.
```
function allendav_force_wga_settings() {
update_option( 'jetpack_wga', array(
'code' => 'UA-13130172-7', // UA-13130172-7
'anonymize_ip' => 1,
'ec_track_purchases' => 1,
'ec_track_add_to_cart' => 1
) );
}
add_action( 'init', 'allendav_force_wga_settings' );
```
* Disable WooCommerce
* Go to any front side page
* Ensure no errors appear
* Enable WooCommerce
* Visit a product page
* Ensure tracking code like this appears in the page source
```
jQuery( function( $ ) {
$( '.single_add_to_cart_button' ).click( function() {
_gaq.push(['_trackEvent', 'Products', 'Add to Cart', '#709']);
} );
} );
```
* Complete ordering the product
* On the …
=> Google Analytics: Fatal Error: Test for WooCommerce before attempting to use it

_inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
* allow to delete the onboarding token
1. in your wpcom sandbox, apply D7342
2. locally, build and run https://github.com/Automattic/wp-calypso/pull/18413
3. use this branch `update/network-onboarding` in your sandboxorg
4. in your sandboxorg, do `wp eval "Jetpack::create_onboarding_token();"` to generate the token that will validate unauthorized requests performed during onboarding
5. test that you have an onboarding token
`wp jetpack options get onboarding`
5. ensure your sandboxorg will use your local Calypso development environment by editing `class.jetpack.php` and uncomment `//$url = add_query_arg( 'calypso_env', 'development', $url );`
6. go to the WP Admin of your sandboxorg, to the Jetpack settings, connect it and you should be sent to the `/start/jetpack-onboarding` flow.
7. go …
=> JPO: allow to delete the onboarding token

class.jetpack-client-server.php, modules/sitemaps.php
Generating sitemaps can take quite a while. Currently we generate them immediately when we connect Jetpack, which can cause the requests to time out, right when we need responses to be most reliable.
This change triggers the sitemap build one minute after connect.
=> Don't generate sitemap on activate, wait a minute

sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-module-users.php, tests/php/sync/test_class.jetpack-sync-users.php
This makes sure that we are returning a whitelist of capabilities that the user has.
* Whitelist the capabilities so that we only sync the ones we care about and also pass them thought the filter. Since plugins have the ability to change capabilities.
=> Sync: Pass capabilities though a filter.

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php, sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-functions.php, sync/class.jetpack-sync-module-callables.php, tests/php/sync/test_class.jetpack-sync-callables.php
We want to display plugins from the .com side api endpoint. 
And we are missing info regarding the plugin action links. This PR starts syncing the new action links. 
* 
* test the get plugin api endpiong /sites/SITE_ID/plugin 
Do you see the actions links for jetpack ?
* Activate a plugin like Woo do you see the action links being synced on the .com side?
=> Sync: Start syncing Plugin Actions

3rd-party/wpml.php
Fixes #7931
`wpml_get_language_information` can return either an array of language infomation about a specific post ID,
or a `WP_Error` if no ID is provided or if no post exists with the provided ID.
The `wpml_jetpack_widget_get_top_posts` now accounts for that second possibility,
and will not attempt to remove a post if WPML cannot find info about it.
* Avoid Fatal Errors when the Top Posts Widget is used on a site using WPML, and when a popular post cannot be found by WPML.
=> WPML / Top Posts Widget: avoid Fatal Error when post doesn't exist

_inc/lib/tracks/class.tracks-client.php
I was seeing lots of `SetCookie`s in API response headers (many identical) because we were setting the anon ID cookie multiple times in the scope of a single request.
This patch just doesn't set the cookie for clients that clearly don't care about them.
=> Don't set cookie on API requests, it's useless

class.jetpack-modules-list-table.php, class.jetpack.php, modules/search/class.jetpack-search.php
A bunch of free plans appear to have enabled the search module somehow. It won't work for them, since the API checks plan status, but it would help to also check plan support for search when initializing the plugin.
=> Fix search plan support

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php, sync/class.jetpack-sync-functions.php, sync/class.jetpack-sync-module-callables.php, tests/php/sync/test_class.jetpack-sync-callables.php
Make sure that the admin_init action gets called at least ones. So that we get the right plugin_action hooks.
Make sure that the plugins did `jetpack_plugin_api_action_links` gets called in the right conntext.
I am not sure if this is the best way to go but it fixes the issue. 
* Make sure to send the data.
=> Sync: make sure that the admin_init hook gets called before getting the links

tests/php/modules/shortcodes/test_class.getty.php
Sounds like Getty may be making some changes to their oembed endpoints?  Until we figure it out, let's skip it to unblock failing PRs
see r-163677-wpcom
=> Getty: Mark test as skipped to unblock failing PRs

_inc/lib/admin-pages/class.jetpack-react-page.php
Addresses #7952.
* Replaces usage of `rest_do_request` for a call to `Jetpack_Core_API_Module_List_Endpoint:get_modules()`.
1. Load the admin page.
1. Expect the admin page to load properly If this PR introduced any problem, the Admin Page wouldn't load
=> Admin Page: Replace call to own REST API with internal call for getting module list

_inc/client/components/jetpack-notices/feedback-dash-request.jsx, _inc/client/components/jetpack-notices/index.jsx, _inc/client/components/support-card/index.jsx, _inc/client/constants.js
Introduces `JETPACK_CONTACT_SUPPORT` and `JETPACK_CONTACT_BETA_SUPPORT` in `_inc/client/constants`;
* Updates files using that URL to use the constants instead.
* Visit the dashboard, check that the *Ask a question* button's URL takes to `https://jetpack.com/contact-support`
=> Admin Page: Introduce constants for support URLs

_inc/lib/admin-pages/class.jetpack-admin-page.php, _inc/lib/class.core-rest-api-endpoints.php
Fixes #7952.
* Introduces `Jetpack_Core_Json_Api_Endpoints::site_data()` which fetches the site data from wpcom
* Refactors `Jetpack_Core_Json_Api_Endpoints::get_site_data()` to use `self::site_data()`
* Replaces usage of `rest_do_request` for a call to `Jetpack_Core_Json_Api_Endpoints::site_data()` in `class.jetpack-admin-page.php`.
1. Load the admin page.
1. Expect the admin page to load properly If this PR introduced any problem, the Admin Page wouldn't load
=> Admin Page: Replace call to own REST API with internal call for getting site data

json-endpoints/class.wpcom-json-api-get-comments-tree-endpoint.php
This PR will allow hitting the `comments-tree` endpoint with a `status` parameter of `unapproved`, for the same results as `pending` currently returns. Allowing both may avoid confusion for users of the older `comments` endpoint, that has always used `unapproved`.
eg. `https://public-api.wordpress.com/rest/v1/sites/:site/comments-tree?status=unapproved`
See: https://github.com/Automattic/jetpack/pull/7933#discussion_r143689263
**Testing**
* Apply this PR and hit a site with unapproved comments using the format above.
* Make sure the results are the same for `?status=pending`.
=> REST API: Allow `unapproved` as a `status` parameter for the comments tree endpoint.

modules/seo-tools/jetpack-seo.php
Fixes #7962
* Follow the steps in the original issue; make sure no duplicate meta description tag is added.
- SEO Tools: do not output any custom meta tags if another SEO plugin is already active.
=> SEO Tools: don't output any tags when another SEO plugin is active.

json-endpoints/class.wpcom-json-api-update-comment-endpoint.php
Allow post authors to moderate their own comments, as they can in wp-admin.
Currrently, the API requires the `moderate_comments` cap to, uh, moderate comments, and [this cap is only possessed by admins and editors](https://codex.wordpress.org/Roles_and_Capabilities), not authors nor contributors (meaning authors and contributors cannot moderate comments on their own posts with the API). However, this is not what's used by wp-admin; the meta cap of `edit_comment` ("can the current user edit this particular comment") [is used instead](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/class-wp-comments-list-table.php#L501) to display the actions that allow moderation. This PR brings the API inline with wp-admin.
See: https://github.com/Automattic/wp-calypso/issues/17687 …
=> REST API: Allow post authors to moderate their own comments.

tools/builder/admin-css.js
Fixes #7464
1. Activate VideoPress
2. Go to Users > My profile and switch your interface language to Hebrew.
3. Go to Posts > Add New
4. Make sure the visual editor is active. 
5. You should not see the following error in your editor anymore:
```
Failed to load content css: .../wp-content/plugins/jetpack/modules/videopress/css/videopress-editor-style-rtl.css
```
You should also see the RTL file when looking at your network tab.
**Note: this requires rebuilding the plugin to create the files.**
* VideoPress: avoid missing file warning in the editor when using an RTL language.
=> VideoPress: build an RTL version of the editor CSS files

modules/subscriptions.php
This will allow other plugins to track whenever a user has subscribed to new comments on the post via a comment form.
* Added a new hook called `jetpack_subscriptions_comment_form_submission`
* Add a testing hook event to your WordPress installation, like this:
```
add_action( 'jetpack_subscriptions_comment_form_submission', function( $result, $post_ids ) {
error_log( $result );
error_log( print_r( $post_ids, true ) );
}, 10, 2 );
```
* When you subscribe to comments to a post make sure you see nothing output by the first statement, and the array containing the post ID by the second statement.
* When you also tick the subscribe to blog checkbox, you should see a zero entry in the array
* Added a filter to track comment subscription activations.
=> Added a hook on comment subscription.

sync/class.jetpack-sync-module-protect.php
This file was removed in #7974.
However, in some situations (cache, ...), the file can still be called, or not deleted properly.
This should help.
Related:
- 8c3790d8cb1463a687a250b6b3d687c03a0365ca
- e9cb5f0e468abba56a00ed706606dadb6b7a8cf2
=> Sync: add in an empty file to replace deprecated file.

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php, modules/publicize.php, sync/class.jetpack-sync-module-callables.php
Reported here:
https://wordpress.org/support/topic/problems-with-the-plugin-9/
Avoids errors like this one:
```
PHP Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ‘;’ in Entity, line: 1 in /wp-content/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php on line 214
```
We also do it here already:
https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/class.filter-embedded-html-objects.php#L251-L255
=> DOMDocument: suppress errors with libxml

tests/php/sync/test_class.jetpack-sync-themes.php
[Core changed the label](https://core.trac.wordpress.org/changeset/41868/trunk) `Custom Menu` for `Navigation Menu`. Tests are failing
* Expect string to be `Navigation Menu` instead in `test_widgets_changes_get_synced` test.
* Confirm that test are not failing for this PR.
* Updated test to handle new naming of Navigation Menu in Core
=> Sync: Expect Navigation Menu instead on widget changes test

_inc/lib/tracks/tracks-ajax.js, class.jetpack-tracks.php, class.jetpack.php, modules/masterbar/masterbar.php, modules/masterbar/tracks-events.js
Fixes #7738
~~Depends on D7169-code~~
~~Enqueues tracks scripts when the WordPress.com masterbar is loaded, to make them available to the javascript overrides.~~
Makes the Masterbar and the Notifications Panel interactions trackable by making the record event function global on `tracks-ajax.js` and adding event handling to the Masterbar plugin.
* ~~Sandbox `s0.wp.com`.~~
* ~~Apply D7169-code on your sandbox.~~
* ~~Using a http debugger, click on any menu item (this does not work on top level items). An entry for the corresponding event with the domain `pixel.wp.com` should appear.~~
* Run a WordPress instance with this branch
* Enable WordPress.com Masterbar
* Using an http debugger, any activity on the masterbar, or opening a site, post or comment on the notifications panel should …
=> Masterbar: add Tracks instrumentation

modules/verification-tools/verification-tools-utils.php, phpunit.xml.dist, tests/php/modules/verification-tools/test_functions.verification-tools-utils.php
In [this forum thread](https://wordpress.org/support/topic/error-when-saving-multisite-site-settings/), the user reported the following error:
```
Warning: Invalid argument supplied for foreach() in ../wp-content/plugins/jetpack/modules/verification-tools/verification-tools-utils.php on line 9
Warning: Cannot modify header information – headers already sent by (output started at ../wp-content/plugins/jetpack/modules/verification-tools/verification-tools-utils.php:9) in ../wp-includes/pluggable.php on line 1210
```
> I have multisite install and when I try to save site settings in the network admin I get this error message
* Verification Tools: avoid notices when saving changes on a Multisite network admin page.
=> Verification Tools: avoid errors in PHP 5.3+

class.jetpack-cli.php, class.jetpack-options.php, class.jetpack.php, sync/class.jetpack-sync-module-full-sync.php, sync/class.jetpack-sync-module-updates.php, sync/class.jetpack-sync-sender.php, uninstall.php
After talking to @annezazu, I realized that the uninstall script doesn't do a great job of cleanup.
It looks like the file was created in November 2011, and since then was only updated for sync stuff. But we've done other things since then, such as adding `jetpack_private_options` and keeping more non-compact options that are not in non-compact options. 
This PR should get us closer to a comprehensive uninstall, and can perhaps be used in abstracting out a reset button to completely reset Jetpack without deleting/reinstalling.
To test:
- Checkout PR
- Start fresh by connecting to Jetpack
- Deactivate and Uninstall Jetpack
- Check that all `jetpack_` options are deleted, except for some sync options perhaps. We can clean those up in a follow-up PR
=> General: Update uninstall script to delete many more options

class.json-api-endpoints.php
Fixes https://github.com/Automattic/wp-calypso/issues/18811
Replication of D7664-code
Comments to detached media attachment pages fail to load in the Calypso Comment Management section and in the API.
Requesting via API the comment to an _attached_ media, works fine: they are the comments that actually appear in the Calypso Comments section.
You can tell them apart in WP Admin because they have an original post, and can be detached:
On the other hand, requesting a comment to a _detached_ media fails with the { error: "unauthorized", message: "User cannot view post" } error.
In Calypso they’re stuck in a placeholder state, and in WP Admin they are reported as "(Unattached)" and can be attached:
---
Posts with `post_type: 'attachment'` can be attached to, or detached from, a parent post. …
=> Comments: Allow comments to detached attachment pages to load for users with enough capabilities

_inc/lib/icalendar-reader.php
`if ( $timezone_offset_interval )` produces an Undefined variable when it is not set prior.
Fixes #7993
* See description of #7993
=> Upcoming events Widget: Fix for #7993 Undefined variable: timezone_offset_interval

json-endpoints/class.wpcom-json-api-comment-endpoint.php, json-endpoints/class.wpcom-json-api-list-comments-endpoint.php
In wp-admin, contributors and authors can see others' unapproved comments, as `edit-comments.php` just [does a check](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/edit-comments.php#L11) for the `edit_posts` cap (which [both contributors and authors possess](https://codex.wordpress.org/Roles_and_Capabilities#Capabilities)). By using `moderate_comments` in our API (which wp-admin doesn't use at all), we're blocking authors and contributors from seeing the same info they can see in wp-admin. This PR brings the API inline with wp-admin. Some spelling errors ("coment") were also corrected.
Note that while they can see others' comments, they cannot see the comment author's email nor IP address; these will be `false` in the API response.
See: …
=> REST API: Match permissions for viewing comments to those of wp-admin.

modules/sitemaps/sitemap-constants.php
This reduction will make sure that Sitemaps do not consume too much memory on generation.
Fixes a problem where the cron script would run out of memory trying to load 1000 posts.
* Fixed memory consumption problem during Sitemaps generation.
* Get a site with more than 1000 posts with a significant amount of content.
* Optionally lower PHP memory limits.
* Try to rebuild the sitemaps by adding the following code to your functions file:
```
add_action( 'wp_loaded', function() {
$sitemap_builder = new Jetpack_Sitemap_Builder();
$sitemap_builder->update_sitemap();
} );
```
* See that the process runs out of memory.
* Roll this PR on, see that it runs OK.
=> Reduced the sitemaps generator batch size.

sync/class.jetpack-sync-functions.php, tests/php/sync/test_class.jetpack-sync-callables.php
There's been an uptick in support tickets where connections are breaking after the site switches to https. This seems to have started with 5.2 or 5.3, likely when we deployed this PR:
#5852
In that PR, we began syncing the raw home/siteurl values from the DB or from the `WP_HOME` and `WP_SITEURL` constants. As part of that work, since we were no longer calling functions like `get_home_url()` which will set the protocol to `https` when `is_ssl()` is true, the `https` change wasn't getting picked up.
This PR should fix that by adding the `is_ssl()` check and setting the protocol to `https` if so.
To test:
- Run tests
=> Sync: Add protocol to raw urls

modules/widgets/mailchimp.php
**Important: this PR is set to be merged into the `fix/mailchimp-shortcode-7945` branch, since the widget is broken right now and this PR couldn't be tested without the changes included in #7989**
Fixes #7960
Fixes #7990
- The widget now calls the shortcode file even when the shortcodes are not active, so you do not need to activate the shortcode module for this to work.
- On save, the widget uses the reversal function provided in the shortcode to save a valid shortcode.
- That shortcode is then displayed in the widget, as before.
1. Start activating both the widget and the shortcode module.
2. Add “MailChimp Subscriber Popup (Jetpack)” widget in a widget area.
3. Copy code from mail chimp into the code area, as explained in the documentation:
https://en.support.wordpress.com/mailchimp/ …
=> Mailchimp: save a shortcode when pasting a form code in the widget

modules/contact-form/grunion-editor-view.php
Fixes 1130-gh-jpop-issues
1. Activate the Contact form module.
2. Go to Posts > Add New with the Network tab opened in your browser's dev tools.
3. Make sure you're looking at the visual post editor.
4. The `modules/contact-form//css/editor-style.css` resource should load without an extra `/`.
- Contact Form: avoid duplicate slash when loading editor style.
=> Contact Form: avoid duplicate / when loading editor style.

modules/contact-form/css/jquery-ui-datepicker.css
I noticed that the min-width on the jquery datepicker was causing some display issues. This PR removes the min-width, fixing the problem. Test cross-browser, and appears to fix the problem across the board.
Before:
After:
=> Contact Form: remove min-width on jquery datepicker styles

modules/contact-form/css/grunion.css, modules/contact-form/grunion-contact-form.php, modules/contact-form/grunion-editor-view.php, modules/contact-form/js/editor-view.js
Fixes #7062 
* Setup a condition for fields marked `url` type to use HTML5 URL fields (which include native validation).
* Update field styles to apply to url fields also.
* Enable the Contact Form module and create a form containing a Website field.
* On the front end, add a non-url in the Website field (such as `xfbdgbd`), and try submitting the form.
* The url field should display a validation message requiring you to enter a valid url.
* I considered adding additional validation in the [`validate()` function](https://github.com/rclations/jetpack/blob/68df77386ba152b279c2cc0c6fc8050ad461da64/modules/contact-form/grunion-contact-form.php#L2498-L2504) using [FILTER_VALIDATE_URL](http://php.net/manual/en/filter.filters.validate.php), but saw that it only validates ASCII URLs, and that …
=> Update Contact Form website field to use HTML5 url field

modules/shortcodes/mailchimp.php, modules/widgets/mailchimp.php, tests/php/modules/shortcodes/test_class.mailchimp.php
Fixes #7945
To test, create a Maichimp form as explained here:
https://en.support.wordpress.com/mailchimp/
Then try to embed it into one of your posts or pages, when logged in as an editor. You should see the form transform into a shortcode on save. Make sure
the form is displayed properly on the site.
* Maichimp: make sure subscription forms can still be embedded in posts and pages.
=> Shortcodes: remove aws domain from Mailchimp shortcode.

bin/partner-cancel.sh, bin/partner-provision.sh
To provide flexibility in implementation, let's not assume where we need to change directory to.
This came up in my testing of JPS v2 where I had symlinked my Jetpack directory to another copy of Jetpack in another WordPress installation. I was able to get around this by going one directory up and running the partner provision script.
By removing the `cd` command going one directory above `jetapck` to `wp-content/plugins` I was able to get the script to successfully run.
To test:
- Check out branch
- Run `sh jetpack/bin/partner-provision.sh --partner_id={$id} --partner_secret={$secret} --plan={$plan} --url={$url} --user=1` with proper variables. See @gravityrail or @ebinnion for details
- Ensure `next_url` returned in response is a proper authorization URL
=> CLI: Do not change directory within partner scripts

json-endpoints/jetpack/class.jetpack-json-api-plugins-install-endpoint.php
Recently we added some bug fixes. This introduced a bug where we would always be returning an error when we install an plugin.
This PR fixes this by making sure that $error is being checked for the empty case.
*
Run this PR Go to calypso and install a plugin. Notice that this doesn't error.
=> Plugin API: Installing plugins always returns an error.

class.jetpack-jitm.php
We were sending user roles via a jitm request. We shouldn't do this. This PR removes it.
* Don't send user roles in a JITM request
* Verify you still see JITMs as an admin on a free Jetpack site and you do not see them as any other user level.
=> JITMs: Remove the need for sending user roles

modules/infinite-scroll.php
This parameter [has been present since 4.2](https://github.com/WordPress/WordPress/commit/fa86f3ef9cdc01954269fea4870e334bef6b5fcd) and by applying the filter here, we are currently breaking all callbacks that expect the $instance as third param.
Fixes #7939
* Makes the application of the `post_gallery` filter include a third parameter to not make PHP throw when calling callbacks that expect it.
=> Infinite Scroll: Apply post_gallery action with integer as third parameter

sync/class.jetpack-sync-functions.php, tests/php/sync/test_class.jetpack-sync-callables.php
Fixes #7997
In #7997, @enejb reported an issue where his multisite was syncing an incorrect URL, the base URL for the site. This was caused by #5852 when we/I started syncing the raw URLs.
While I did test multisites, I apparently didn't test multisites with the constant set. Or, I would've noticed the wrong URL was being synced.
I was able to narrow this down to these lines in core WordPress:
```php
// WP_HOME and WP_SITEURL should not have any effect in MS
remove_filter( 'option_siteurl', '_config_wp_siteurl' );
remove_filter( 'option_home',    '_config_wp_home'    );
```
The `_config_wp_siteurl` and `_config_wp_home` filters check if the `WP_HOME` or `WP_SITEURL` constants are set, and if so, uses those constants. **BUT** ... the filters that call those functions are removed for …
=> Sync: Fix issue with syncing raw URLs for multisites

bin/partner-cancel.sh, bin/partner-provision.sh
This PR does a few things:
- Fixes a regression I introduced in #8009 where I started quoting `$ADDITIONAL_ARGS`. I did this because `shellcheck` recommended that we quote the variable, which I ran last after doing my functional testing. But, quoting the variable caused the arguments to be counted as one string. We need them to be evaluated as separate words. I have now added a comment above these instances so that we don't change it in the future.
- Moves global arguments to just after the `wp` part of the WP-CLI command. WP-CLI has a special environment variable that removes ambiguity by evaluating all arguments just after `wp` as global arguments and arguments after the command or subcommand as local arguments [#](https://make.wordpress.org/cli/handbook/config/#environment-variables). …
=> CLI: Update script so that global args are directly after wp

modules/shortcodes.php
This is needed since #7991 has landed in Jetpack. There is a particular edge case that illustrates the problem. After #7991 the widget would check if a shortcode is present, and would load it if it wasn't. If then the shortcode would try to include that file again, it would fatal. This could happen when you have the widgets module enabled, and shortcode modules disabled. The fatal would appear in the request when you're trying to enable the shortcodes module.
* Changes `include` to `include_once` for shortcode files.
* Disable shortcodes module.
* Enable widgets module.
* Try enabling the shortcodes module again using the legacy modules page.
* Observe the fatal error.
* Try to do the same thing again with this PR, observe no fatal.
=> Changes include to include_once in shortcode files.

modules/gravatar-hovercards.php
Fixes `PHP Notice:  Trying to get property of non-object in ...jetpack/modules/gravatar-hovercards.php on line 238`
Ensure that the $user object is not false before using and return out early if we don't have a hash.
cc: @donnchawp
=> Grav Hover: Ensure user object is present before using

modules/tiled-gallery/tiled-gallery.php
Fixes #7830
Thank you @westonruter for [this patch](https://core.trac.wordpress.org/ticket/42285), which, once merged, allows us to seamlessly integrate TG functionality into the new Core widget.  
To Test: 
- Activate Tiled Galleries
- On a site running WP trunk, add a core media gallery widget
- Choose a `type` of gallery
- Make sure it saves the value correctly and displays the right type on the front end
- Make sure there is no conflicts when not running trunk
=> Add filter to allow Tiled Galleries on the new Core media gallery widget

json-endpoints/class.wpcom-json-api-update-comment-endpoint.php
This will let us attribute comments to authors on the site running Jetpack if a user has successfully connected their account to the actount on WordPress.com.
* Adds code that fetches a user based on the external ID stored on WordPress.com
* Get a site with a user that is not the connection owner.
* Better if you have two users, one of them should be connected to WordPress.com, while the other shouldn't.
* Use the `/sites/%s/posts/%d/replies/new` API endpoint to add comments with both of them.
* Notice how the author is set to a user with 0 ID.
* Apply the PR.
* Notice how in case of a connected user the author field gets properly attributed to the local user.
Tagging @georgestephanis because you worked on the SSO module.
* Added user matching when adding comments via JSON API.
=> Added user matching when adding comments via JSON API.

class.jetpack-twitter-cards.php
=> Twitter Cards: Use site title if no post title exists

class.jetpack-jitm.php
We aren't currently tracking when a user attempts to dismiss a jitm. This allows us to track that.
* Dismiss a jitm and see it in Tracks.
=> Add tracking of jitm dismissals

class.json-api-endpoints.php, json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php
Does it look like what you expect? Does the output make sense?
Related discussion: p9c7Jx-8V-p2
Related .com changes: D7853-code
@koke, @oguzkocer 
* Are these the requested change?
Update your wp-config.php to have this set
```
define( 'DISALLOW_FILE_MODS', true );
define( 'AUTOMATIC_UPDATER_DISABLED', false );
define( 'WP_AUTO_UPDATE_CORE', false );
```
Reconnect your site to force a resync ( unless you want to wait an hour? )
- Activate a plugin. 
- Does the result look like what you expected?
=> API: Tweeks to the plugins api.

json-endpoints.php, json-endpoints/class.wpcom-json-api-bulk-restore-post-endpoint.php
Summary:
This diff introduces a new bulk post restoration endpoint. The endpoint will be used in the future to enable bulk restoration of posts via Calypso. The endpoint follows the behavior of the current single-post restoration endpoint.
This PR is similar to #7926 except for restoration as opposed to deletion.
Differential Revision: D7573-code
This commit syncs r163624-wpcom.
This commit syncs r163625-wpcom.
* Checkout branch.
* Use the developer console on developer.wordpress.com to make requests against your Jetpack site.
* Verify that the bulk restore endpoint at `/sites/$site/posts/restore` works the same as the single post restore endpoint at `/sites/$site/posts/$post_id/restore`, except that it takes an comma-separated list of `post_ids` as a request parameter as opposed the …
=> API: Introduce a bulk post restoration endpoint

modules/seo-tools.php, modules/seo-tools/jetpack-seo.php
In case when 3rd party SEO plugin is active on the site we should prevent SEO tools from outputting duplicate meta tags.
Fixes https://github.com/Automattic/jetpack/issues/7962
This is another take at https://github.com/Automattic/jetpack/pull/7976 and reverts changes that were introduced there. The reason behind this is that the code in it was causing issues on Dotcom when synced.
* Follow the steps in the original issue; make sure no duplicate meta description tag is added.
- SEO Tools: do not output any meta tags if another SEO plugin is already active.
=> SEO Tools: remove duplicate meta tags when another SEO plugin is active

class.jetpack-cli.php, class.jetpack-client-server.php
When going through JPS v2, @MichaelArestad pointed out that Jumpstart was not showing, even on a new site. 
After much debugging, I narrowed it down to [this line](https://github.com/Automattic/jetpack/commit/7c6349c132b6d138df9841d4b4d4ab0846597fde#diff-eae3f6a880e55a097f18a5d96c4567b6R137) where we were activating SSO by calling `Jetpack::activate_module( 'sso', false, false );` after the site had been created, provisioned by Jetpack Start, and the user had authorized.
In `Jetpack::activate_module()` there is a condition that will set the Jumpstart option to `jetpack_action_taken` which keeps us from showing the Jumpstart page.
To fix this, I made a change that starts to pass in `sso` in to `Jetpack::activate_default_modules()`, which will activate SSO in the same case, but without …
=> JPS: Fix issue where Jumpstart did not show for new JPS sites

modules/masterbar/masterbar.php
This ensures it gets enqueued in the correct order.
* Makes the masterbar dependent on jquery
* Make sure it works :p
* `$wp_scripts->registered['a8c_wpcom_masterbar_tracks_events']->deps` should have `'jquery'` in the array
=> Make masterbar tracks js dependent upon jquery

_inc/lib/icalendar-reader.php, modules/widgets/social-media-icons.php
Xgettext expects it to be lowercase
This commit syncs r164390-wpcom.
* None, this only affects the PO file generation.
* None needed.
=> i18n: Update translator comment prefix

sync/class.jetpack-sync-defaults.php
Update blacklisted post types.
These post types aren't useful to the end user or happen too often and could break sync. Saving resources :)
=> Sync: Update blacklisted post types

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-comments-tree-endpoint.php, json-endpoints/class.wpcom-json-api-get-comments-tree-v1-1-endpoint.php
This PR seeks to remove much of the duplication in the comments tree endpoint response to make it as light as possible (greatly benefitting sites with thousands of comments, such as `en.blog.wordpress.com` and `wptavern.com`). Because we're changing the shape of the response, we're versioning these changes to v1.1.
Rather than the current flat list duplicating post IDs and parent IDs of `0`, each post ID is now its own key, with an array of parent-less (top-level) comment IDs (at `[0]`) and an array of comments with parent IDs. eg. `[ comment_id, comment_parent_id ]`, at `[1]`). Because pingbacks and trackbacks never have comment parents, they simply have the one array of comment IDs on a comment post ID key. The shape now looks like this:
```
{
comments_count: 1234,
comments_tree: { …
```
=> REST API: Reduce duplication in the comments tree endpoint response.

_inc/client/components/connect-button/index.jsx, _inc/client/components/connect-button/test/component.js, _inc/client/components/jetpack-connect/index.jsx, _inc/client/components/jetpack-notices/index.jsx, _inc/client/state/connection/actions.js, _inc/client/state/connection/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php
Makes the components that use the connection URL, get the data from the initial state instead of attempting to fetch. 
Problem here is that any given output or error that any other plugin putos on the php output will make the user not be able to connect. This is a general problem, but it's critical for us to at least allow the user to connect.
Fixes #7979
* Makes the `connection` reducer react to `JETPACK_SET_INITIAL_STATE` by loading the `state.jetpack.connectUrl` with the data coming from the server via `wp_localize_script`.
* Removes every usage of `<QueryJetpackConnect />` because there's no more need for it.
* Makes the promise chain in the `disconnectSite()` action also call `fetchConnectUrl()` after disconnection is successful. 
* Start with a disconnected site and user.
* Visit …
=> Admin Page: Get the connection URL from initial state instead of fetching it

json-endpoints/class.wpcom-json-api-update-media-endpoint.php
Without this change POST requests to a v1.1 endpoint would get served by a v1 endpoint.
This syncs r162000-wpcom.
* Make sure the /sites/%site%/media endpoint returns the results that the v1.1 media endpoint should return.
* Fixed JSON API endpoint that handles media updating.
=> Explicitly setting max version for a deprecated endpoint.

modules/carousel/jetpack-carousel.php
Props @westi for the suggestion.
wip
=> Carousel optimizations

.circleci/config.yml
We pushed a change to the wp-e2e-tests repo that uses the new Chrome --headless option, which requires an updated version of Chrome.
=> Updated wp-e2e-tests Docker image to 0.0.7

class.jetpack-cli.php
Currently, if a site is active and a hosting partner then runs the `bin/partner-provision.sh` script, we return an SSO login URL as the next step, regardless if the site has SSO enabled or not.
This PR will check if the site is connected, and if so, if SSO is active, before setting the redirect_uri to an SSO login URL.
To test:
- Connect Jetpack site
- Run `bin/partner-provision.sh` with whitelisted client ID and secret
- Ensure you get a longer authorization URL 
- urldecode that and visit the URL to finish the process
- Run `bin/partner-cancel.sh` to cancel the plan out
- Run `bin/partner-provision.sh` again to ensure you get a next_url that is to your admin dashboard this time
=> CLI: JPS: If site is active, do not SSO as redirect_uri

class.jetpack-cli.php
The current implementation of the wp jetpack partner-cancel command relies on `Jetpack_Options::get_option( 'id' )` being set, but in the case where the user had already disconnected their site before churning from the host, this value would be falsey.
In that case, we should fall back to using the site slug as an identifier.
This patch requires D7924 on the WPCOM side.
To test:
- Checkout D7924 on WPCOM (if not merged already)
- Sandbox API on your host
- Run `bin/partner-provision.sh` with required client ID and secret
- Disconnect site with `wp jetpack disconnect blog && wp option delete jetpack_options`
- Verify that plan exists for site still
- Run `bin/partner-cancel.sh` and verify plan is cancelled
=> CLI: JPS: Allow site slug fallback when cancelling a plan

class.jetpack-cli.php
When running the partner CLI scripts, the `wp partner_provision` command returns something like:
```
{ "success": true, "next_url" : {$URL} }
```
But, the `wp partner_cancel` command returned something like:
```
{"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
```
To assist partners in integrating, these responses should be the same.
To test:
- You'll need to run the `bin/partner-provision.sh` script and the `bin/partner-cancel.sh` script with a whitelisted client ID and secret. See @gravityrail or @ebinnion about that.
- For both requests, you should get back a JSON object with a key of `success`.
=> CLI: JPS: Return request body for partner cancel CLI command

_inc/client/state/connection/reducer.js
This helps the code not break static pages building as the initial state is mocked there.
Fixes generation of static files
* Access the action props safely with `get` when reducing the `JETPACK_SET_INITIAL_STATE` action. 
* checkout this branch
* clean you current build with `yarn distclean && yarn clean-client`
* Confirm that running `yarn build` builds everything correctly
=> Admin Page: Return state in connection reducer if the initial state is not loaded fully

sync/class.jetpack-sync-module-themes.php
During some server-side work, @gititon and I discovered that there
was a more performant way to detect theme-switch events.
We've already deployed this patch server side, and now we are updating
the client to remain in sync.
To test:
- Apply this PR to a connected Jetpack site, that is on a paid plan
- Add, re-order, and remove some widgets on your site, and ensure that entries appear in AL
- Switch themes, and ensure that only a theme-switch event appears in AL
=> Sync: theme module

modules/masterbar/masterbar.php, modules/masterbar/tracks-events.js
Updates the event props sent to Tracks for user activity on the Masterbar to keep them in sync with D7919-code, including:
* Events firing twice for a menu element with a secondary action.
* Click event not firing on the user name links on the my account menu.
* Events not firing for primary and secondary actions on Testimonials and Portfolio links on My Sites.
* Notifications Panel `source` event prop renamed to `clicked` for consistency.
* Run a WordPress instance with this branch
* Enable WordPress.com Masterbar
* Using an http debugger, any activity on the masterbar, or opening a site, post or comment on the notifications panel should trigger an `admin-ajax.php` request with the `jetpack_tracks` action, and at least the `clicked` event prop corresponding to the clicked element.
=> Masterbar: updates event props to keep them in sync with WordPress.com

class.jetpack.php
Better than using a a single option b/c we can bypass DB writes with
memcache dropins, and we don’t have tons of UPDATE queries all changing
this option for different versions of JP during an upgrade.
Fixes #8055
=> Switch to separate transients for caching JP file data

modules/shortlinks.php
Simple commit. Use HTTPS for wp.me links regardless of the HTTPS? status of the request being rendered for.
=> wp.me links should always be HTTPS links

modules/contact-form/grunion-contact-form.php
Fixes #8059
To test, add a contact form shortcode to a text widget in your sidebar, and make sure it is properly rendered, whether you are running WordPress 4.8.2 or 4.9 Beta.
* Contact Form: do not process shortcodes in widgets when WordPress itself does, starting in 4.9
=> Contact Form: do not process shortcodes in widgets when Core does

_inc/client/rest-api/index.js, _inc/client/state/settings/actions.js
Fixes #
* Updates message to be shown when JSON cannot be parsed from a REST API response.
* Checkout this branch and build. Or test it using Jetpack Beta for this PR.
* Play with manually generated errors by using this snippet in line `331` of `_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php`
```
echo '/';
//http_response_code(404);
//header('Location: /');
//header('Location: /nonexistantpath');
exit;
```
* By uncommenting the first one, you'll get a JsonParseError. (Resembling something broken in the user's WP installation but unrelated to Jetpack
* By uncommenting the second one, you'll get a JsonApi404Error. (Resembling something weird in WP's config that doesn't let us reach the REST api.
* By uncommenting the third one, you'll get a redirection to the home. So the …
=> Admin Page: Show better error messages when we can't parse JSON from API responses

json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
If applied this patch will add an autosave parameter to the post update endpoint,
and if present, the endpoint will truthify the DOING_AUTOSAVE constant.
=> Post update endpoint: autosave parameter

modules/widgets/google-translate.php, modules/widgets/google-translate/google-translate.js
Fixes #5962
This PR includes 2 changes:
1. Change the default layout of the widget displayed by Google. Until now the widget used the "Dropdown Only" mode. It now uses
the "Vertical" mode. This layout is more compatible with mobile devices.
2. Create a new filter, `jetpack_google_translate_widget_layout`, allowing one to switch between layouts if needed:
```php
/**
* Change the Google Translate Widget layout.
*/
function jeherve_dropdown_only_translate_layout() {
return 'google.translate.TranslateElement.InlineLayout.SIMPLE';
}
add_filter( 'jetpack_google_translate_widget_layout', 'jeherve_dropdown_only_translate_layout' );
```
Before:
After:
1. Make sure the widget is displayed properly on desktop and mobile devices. I'd recommend using an incognito window when switching to the branch to …
=> Translate Widget: update layout to be responsive.

class.jetpack.php
Somehow `$wp_object_cache` (used by `wp_cache_get()`) is not defined by the time we reach
`Jetpack::__destruct`. Looks like using cache from the `shutdown` callback is fine though.
* Removes the `__destruct` method as currently only is pushing stats.
* Adds a `push_stats()` method that will check if any stats are pending and send the to .com
* Hooks `push_stats()` to `shutdown` in the class constructor.
*
* [PHP Fatal Error in cache.php on line 123 $wp_object_cache is non-object](https://wordpress.stackexchange.com/questions/283085/php-fatal-error-in-cache-php-on-line-123-wp-object-cache-is-non-object).
=> Call do_stats() on shutdown instead of on __destruct

modules/sharedaddy/sharing.css
Fixes #6573
* Aligns sharing icons for custom sharing services in wp-admin:
* Go to Settings > Sharing in your dashboard.
* Click "Add a new service" and add a new sharing service
* Select the "Icon + Text" button style.
* The icon for the custom service should now be aligned with the text in the Live Preview
=> Fixes Issue #6573: sharing icons are not aligned in wp-admin

_inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-widgets-endpoints.php, modules/widgets/milestone/milestone.js, modules/widgets/milestone/milestone.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
Fixes #7940, replaces #7942.
* Adds a new unit test for the widget data getter.
* Moves i18n out of client side code to fully utilize gettext powers.
* Moves calculation out of the client side code, making server side data the only source of truth.
* Relies on REST API refreshes to show messages.
* Test various widget configurations: time units, until and since modes.
* Make sure unit tests pass.
* Fixed the Milestone widget in different translations.
=> Moved the Milestone widget i18n and calculation out of client side code.

json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-v1-2-endpoint.php
In WP 4.9 Core is introducing new capabilities for managing plugins 
See https://make.wordpress.org/core/2017/10/15/improvements-for-roles-and-capabilities-in-4-9/
The current API endpoints should respect them. 
This PR adds checks for the new capabilities if the site is running the latest beta of WP 4.9.
* Check that if the user is running WP 4.9 or greater they are not able to activate plugins. 
* Make sure that everything still works as expected in older version of WP. 
* Add the following plugin
```
<?php
/*
Plugin Name: Plugin De/Activation Check
Author: Enej
*/
add_filter( 'map_meta_cap', 'eb_disable_dolly_activation', 10, 4 );
function eb_disable_dolly_activation( $caps, $cap, $user_id, $args ) {
$plugin_file = isset( $args[0] ) ? $args[0] : '';
if ( $cap == 'deactivate_plugin' && …
```
=> Api/update plugins filter for 4.9

class.jetpack-post-images.php, tests/php/_inc/lib/test_class.jetpack-media-extractor.php, tests/php/test_class.jetpack-post-images.php
Fixes #2284
When using `jetpack_og_get_image`, we specify a minimum width and height (200px).
Those 2 values are then used by `Jetpack_PostImages::get_images()`. `get_images` looks for images following different methods, and we
applied the minimum width and height to most of them, thus excluding images that were too small. However, we did not apply the values for
the last fallback used to look for images in a post: `from_html`.
This commit implements the 2 width and height requirements to `from_html`. To do so, I switched from a regex match to using `DOMDocument`
to fetch the different image tags and their width and height values.
1. Enable Sharing or Publicize on your Jetpack site.
2. Insert multiple small images (less than 200x200px) in a new post.
3. Publish post.
4. View post.
5. View …
=> Open Graph: do not return images smaller than required size.

class.jetpack-options.php, modules/widgets.php, modules/widgets/gallery.php, modules/widgets/migrate-to-core/gallery-widget.php, tests/php/modules/widgets/migrate-to-core/test_migrate-to-core-gallery-widget.php
Allows active Jetpack Gallery Widgets to be upgraded to Core's Media Gallery widgets, maintaining type, random and visibility options for each widget.
Will try to keep the same id for every widget, unles this collides with an already existing Core Media Gallery Widget id. ~This is just an edge case that can come up if the user upgrades their WordPress with Jetpack inactive, creates a Media Gallery widget and then decides to activate and connect Jetpack. If existing Jetpack Gallery widgets are there with ids similar to the new ones created by the user, the imported widgets will try to have a non-colliding id~.
* Creates an importer that hooks on `widgets_init` for transforming Jetpack Gallery Widgets into Media Gallery widgets introduced in WordPress 4.9
* Makes the Gallery widget don't be …
=> Widgets: Migrate Gallery Widget instances to core 4.9 Media Gallery widgets

_inc/client/security/backups-scan.jsx
Fixes #7483
If threats are found, the messaging was not clear.  See the screenshot in the linked issue.  
This PR updates the description to [what we have](https://github.com/Automattic/jetpack/blob/branch-5.4/_inc/client/at-a-glance/scan.jsx#L58-L72) in the dashboard.  It includes number of threats and links to VP dashboard and support.  I think we should not worry too much about design here.  
To test: 
- Hack the `getVaultPressScanThreatCount()` selector to return a number.  it's [here](https://github.com/Automattic/jetpack/blob/branch-5.4/_inc/client/state/at-a-glance/reducer.js#L281).
- View the scan card in the `/security` tab.  
- Make sure the links work. 
- Make sure it looks fine with no threats.
=> Fix Scan card description if there are threats found.

modules/carousel/jetpack-carousel.php
Fixes an issue where `<img>` tags without a `wp-image-N` class would cause an undefined index notice and load all WordPress attachments into RAM (!)
To reproduce:
1. Add a regular image tag, like `<img src="https://www.blog.google/static/blog/images/google-200x200.7714256da16f.png" />`
2. Render the page
3. Observe errors like:
```
Notice: Undefined offset: 568 in /srv/www/wordpress-default/public_html/wp-content/plugins/jetpack/modules/carousel/jetpack-carousel.php on line 374
```
=> Fix undefined index on bare image tags

modules/widgets/gallery.php
#8062 introduced a filter `jetpack_force_enable_gallery_widget` for forcing the enabling of the Gallery Widget for WordPress versions that include the Media Gallery Widget introduced by WordPress 4.9
The logic for making this filter be useful was wrong.
* Changes the boolean comparison made in `modules/widgets/gallery.php` for forcing the enabling of the Gallery Widget
* On a test site with WordPress 4.9
* Hook into the filter with `add_filter( 'jetpack_force_enable_gallery_widget', '__return_true' );`
* Visit Appearance -> Widgets and confirm that you get to see `Gallery (Jetpack)` among the available widgets list.
=> Gallery Wdiget: Fix logic for force-enabling Jetpack Gallery widget if filter returns true

.svnignore, _inc/lib/admin-pages/class.jetpack-settings-page.php, class.jetpack-connection-banner.php, class.jetpack-idc.php, class.jetpack-jitm.php, class.jetpack-modules-list-table.php, class.jetpack.php, functions.gallery.php, gulpfile.babel.js, modules/comment-likes.php, modules/likes.php, modules/masterbar/masterbar.php, package.json, yarn.lock
Minifies all the JS files in _inc into _inc/build, with sourcemaps, and modifies existing code to point to those files.
This is factored out of our larger experimental #7963 branch.
=> Minify more JS

_inc/client/writing/post-by-email.jsx
Fixes #8099
* Checks if the value returned by the API is `noop` and shows `''` instead.
* Start with a fresh site that is connected.
* Build this branch (or try this PR out on Jetpack Beta plugin)
* Vist the Jetpack Admin settings page
* Confirm that the input for Post By Email Address is blank instead of showing the text `noop`.
Fixes bug that showed wrong content in the Post By Email Address setting if it hadn't been configured before.
=> Admin Page: Transform a noop string value into empty string if post by email address is not set yet

_inc/client/sharing/index.jsx, _inc/client/sharing/publicize.jsx
Fixes #8098 
* Hides the publicize activation toggle if user cannot manage modules
* Check this branch and build the admin page
* Log in as an user with an editor role
* Get to the Admin Page settings, and confirm that you get the publicize activation toggle disabled for the user.
**Before**
**After**
=> Admin Page: Don't show publicize activation toggle for users that cannot manage modules

modules/videopress/class.videopress-player.php
Currently, we version lock VideoPress for videos that are directly embedded in a page. This does not affect 90% of videos, as they exist inside of an iframe, so always receive the newest version of VideoPress. However, for directly embedded videos, we never update the version of VideoPress, even when valid fixes are applied.
Case in point, back in early October I released a fix for Safari which had broken VideoPress, thanks to the no autoplay feature they added. During this fix, I accidentally broke some versions of Internet Explorer. While I found and fixed the issue within days, it seems during those days Jetpack 5.4 was released and now that broken version of VideoPress is feature locked for Jetpack 5.4 users... bummer.
While I can appreciate the likely reasoning behind this feature …
=> Remove the Jetpack version lock for directly embedded VideoPress

modules/sharedaddy/sharedaddy.php, modules/sharedaddy/sharing-service.php, modules/sharedaddy/sharing-sources.php
Jetpack uses the bookmarklet usage which is now removed from Press This, starting in WP 4.9+.
Fixes #8097
Updated to work with 4.9 Press This.
=> Sharing: Press This + 4.9

_inc/client/writing/composing.jsx
Fixes issue reported by @ebinnion in p8oabR-6W-p2 where after entering a new phrase, it was unnatural to not be able to save the settings right away
* Adds and explanation below Ignored Phrased input in Admin Page composing settings prompting the user to press enter after they've entered a new phrase. Reads: `Confirm each new phrase you add by pressing enter afterwards.`
* Build the admin page
* Visit the Jetpack Settings page.
* Expand the `Check your spelling, style, and grammar` card.
* Confirm that the explanation below the Ignored Phrases input is fine.
**Before**
**After**
=> Admin Page: Add explanation below Ignored Phrases input under composing settings

_inc/client/writing/post-by-email.jsx, _inc/lib/class.core-rest-api-endpoints.php
Also fixes #8099 but with a more comprehensive approach.
Turned out that the setting `post_by_email_address` has a valid value of `null` if it's not set and evaluating with `isset()` does not favor this case against the ones that have no `current_value`. This problem was introduced by #8053 and is a problem only for this particular setting. No other setting has a valid value of `null`.
* Uses `array_key_exists()` instead of `isset` for checking the absence of the `current_value` key when iterating through passed options.
* Reverts changed introduced by #8107 which are not needed anymore as the problem is handled at a lower level. 
* With a user that has never linked to .com or generated a post-by-email address, check the Jetpack Admin Page settings tab.
* Confirm …
=> REST API: Take in account desirable null values when preparing options before assigning default_value to current_value

modules/carousel/jetpack-carousel.php
Without it the query would return an empty result set trying to get results using only IDs because attachment images have status set to `inherit` and type set to `attachment`.
Fixes #8103 
* Tweaks the query introduced in #7943 to include attachments.
* Enable Carousel.
* Create a post with an image that should link to the attachment page.
* Observe that the carousel overlay doesn't open, instead you go to the attachment page.
* Roll this PR on.
* Observe the carousel overlay.
=> Carousel: Added post type and status specification to the query.

functions.gallery.php, modules/tiled-gallery/tiled-gallery.php
This allows to also save the types when Tiled Galleries module is inactive, and also when the Slideshow shortcode is disabled too. We can still store visibility options now even when those modules are inactive.
Fixes #8113
* Moves the filter hooking from the gallery module to the Gallery settings where types are filtered. 
* Get to Appearance -> Widgets
* Add a new Gallery core Widget. Set one of the types like 'Slideshow' and save.
* Refresh the Widgets page and check that the type setting is maintained.
* Repeat under these conditions
* Tiled Gallery module inactive.
* Shortcodes module inactive.
* Tiled Gallery and Shortcode modules inactive. Here you can save visibility options and verify they're stored.
* Confirm that options are persisted in every case
_Should …
=> Widgets: Hook into Media Gallery Widget from a more general place in the code.

modules/widgets/migrate-to-core/gallery-widget.php, tests/php/modules/widgets/migrate-to-core/test_migrate-to-core-gallery-widget.php
This PR proposes to store references in the `wp_inactive_widgets` sidebar for the old Gallery Widgets that have been successfully migrated to new Core Media Gallery widgets.
After migrating Gallery Widgets successfully to the new Media Gallery widgets, the user ends up with this:
1. **New Widget** (Reads _Gallery_, instead of _Gallery (Jetpack)_
2. **No longer has access to the Gallery (Jetpack) widget type** for creating them and adding to sidebars (We don't load the code for Gallery widgets anymore, instead we hook on core's).
If then, the user decides to use the filter
```
add_filter( 'jetpack_force_enable_gallery_widget', '__return_true' );
```
Before removing the old widgets from the original sidebar, adds them to the `wp_inactive_widgets` sidebar.
1. By using the filter, the user …
=> Gallery Widget Migration: Move migrated gallery widgets to inactive sidebar

sync/class.jetpack-sync-module-callables.php
Jetpack Fatals on servers without `mbstring`
big props for @zinigor for catching this 👍
=> Bug: Fix undefined `mb_convert_encoding` error

_inc/client/components/settings-card/index.jsx
This was showing a warning due to the React 15 upgrade.
* Removes passing down of unnecesary `isSubmitting` prop.
* Check and build this branch (not production build)
* Get to Jetpack's Admin Page settings.
* Confirm that you don't see a warning about `isSubmitting` being invalid prop.
=> Admin Page: Remove passing down of unnecessary prop isSubmitting in settings headings button

sync/class.jetpack-sync-functions.php
Fixes #8137
Use empty() to check if it is available.
=> Sync: check schema is available or not

modules/related-posts/jetpack-related-posts.php
fix #8030
The excluded_post_ids array is getting reset each time in the foreach loop, so it is good to define excluded_post_ids  array before foreach loop then we overcome the issue.
Thanks
=> Related Posts: Define array before foreach loop

yarn.lock
Updates yarn.lock to include latest commit on Automattic/dops-component (coming from Automattic/dops-components/pull/117 )which removed some passed-down properties to HTML components. That was triggering a warning in React's development mode 
* Updates yarn.lock file after `yarn upgrade` was run.
* Run `yarn distclean && yarn clean-client && yarn cache clean && yarn build`
* Confirm the admin page has been properly built.
=> Admin Page: Update yarn.lock to take in account dops-components PR #117

class.jetpack-cli.php
This will help in testing and will allow users at least a low level way to rebuild the sitemap.
* Added a CLI command to rebuild the sitemap.
*  Added a CLI command to rebuild the sitemap.
=> Added a WP CLI command to rebuild the sitemap.

json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
Adds an `autosave` parameter to the posts/new endpoint which if true, will define `DOING_AUTOSAVE` to true.
This cleans noise from the Activity Log and allows us to be more
correct / accurate with the definition of DOING_AUTOSAVE.
Changes already deployed server side: 165562-r
See: p7rcWF-FO-p2
=> JSON API: add `autosave` param to posts/new endpoint

class.photon.php, tests/php/test_class.jetpack_photon.php
Fixes #8191
Until now, when filtering content, Photon has removed width and height attributes from img tags. This makes sense in certain cases since we optimize and resize the image on WordPress.com. If we resize the image, but left the width and height attributes the same, it could cause distortion.
But, it also causes issues, which are described in #8191. 
To address the issue, I am proposing that instead of always removing the width and height attributes, that we update the width and height instead.
To test:
- Run tests
- Place various images in posts/pages. Observe that when there are height/width attributes for the image, that we don't strip the height/width tags. Ensure that you're "viewing source" as oppose to using dev tools.
=> Photon: Do not remove width and height attributes when known

functions.opengraph.php
I added `esc_url` in #7246, but it seems to be causing encoding issues
with images including special characters and being passed through Photon.
Fixes 1305-gh-jpop-issues
Fixes 1306-gh-jpop-issues
=> Open Graph: do not pass image URL through esc_url

json-endpoints/class.wpcom-json-api-bulk-delete-post-endpoint.php, json-endpoints/class.wpcom-json-api-bulk-restore-post-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-check-capabilities-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-themes-active-endpoint.php
Updates the signature for the `callback()` method overriden by these classes.
Fixes #8186
Modifies the following endpoints to have the same signature as the update endpoint for their `calback()` method.
* Bulk Restore Endpoint
* Bulk Delete Endpoint
* Active Theme endpoint
* Check compatibility endpoint
1. Start with a site running on PHP 7.2RC and Jetpack connected...
1. Get to calypso and try to run a full sync from [Settings/General/Manage Connection](https://wordpress.com/settings/manage-connection).
1. Verify you get an error.
1. Repeat after checking out this PR (Can be done easily by using the [Jetpack Beta Tester Plugin](github.com/Automattic/jetpack-beta))
1. Confirm that triggering he full sync works and you get no errors.
=> WPCOM API: Fix incompatible method signature in json endpoints inheriting from the update endpoint

sync/class.jetpack-sync-module-users.php, tests/php/sync/test_class.jetpack-sync-users.php
Lets not send the user on logout if the user is empty.
Fixes #8175 
* For some reason some sites try to send us an empy value when the user logs out. It could be that the user is already logged out. 
This prevents the event from being sent.
=> Sync: Don't sync user if the user is null.

modules/sharedaddy/sharing-sources.php, modules/shortcodes/googleplus.php
plusone.min.js and platform.min.js are currently broken, gapi.plusone is undefined. The documentation at https://developers.google.com/+/web/+1button/ uses platform.js, which is working fine.
=> Use platform.js for Google+ sharing functionality

modules/theme-tools/responsive-videos.php
Fixes #8215 for Jetpack sites running WordPress 4.9 and with a theme that supports the `jetpack-responsive-video` features.
Sequel to r165801-wpcom.
WordPress 4.9 already provides responsiveness for video embeds and widgets, so this PR makes Jetpack not attempt to achieve responsiveness for them too.
* Start with a connected Jetpack site running on WordPress 4.9.
* Activate theme Twenty Sixteen or any other that support `jetpack-responsive-videos` on the site.
* Add a Video Widget with a Vimeo video.
* Add a Video Widget with a Youtube video.
* On the customizer add this CSS:
```
.site-inner {
max-width: 5000px ;
}
```
* With Chrome Dev Tools, try to emulate a device with resolution like `4500x1800`.
* Confirm that both videos play well without going into …
=> Responsive Videos: Don't add Jetpack video wrapper for video embeds if WordPress core supports responsiveness for them already

modules/publicize/ui.php
Fixes #8134
1. Starting in Posts > Add New.
2. If you use Publicize on your site, you will see the following box:
Since Twitter now supports more characters, we need to expand the limit accordingly (280 characters minus 23 characters for the link, and a space):
https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html
* Publicize: update message length to match Twitter's new 280 character limit.
=> Publicize: update message length to match Twitter's new limit.

modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-logger.php
Makes the report method `Jetpack_Sitemap_Logger ::report()` only log success messages if `JETPACK_DEV_DEBUG` is defined.
Error logs in several sites I'm using are filled with this piece of information which is not actually useful, specially when `WP_DEBUG` is turned on to observe possible errors happening. Message are like:
```
jp-sitemap-fDyFX: -- Building sitemap-1.xml
jp-sitemap-WTjbS: 0.123 seconds elapsed.
jp-sitemap-fDyFX: -- Cleaning Up jp_sitemap
jp-sitemap-fDyFX: -- Cleaning Up jp_sitemap_index
```
* Updates the check for `WP_DEBUG` to be a check for both `WP_DEBUG` and `JETPACK_DEV_DEBUG` instead for success messages and just a check for `WP_DEBUG` for error messages.
* Activate sitemaps
* Define  `WP_DEBUG` to `true`.
* Rebuild the sitemaps (`wp jetpack sitemaps rebuild`).
* …
=> Sitemaps: Make the reporter log success messages only if JETPACK_DEV_DEBUG is defined 

_inc/client/at-a-glance/activity.jsx, _inc/client/at-a-glance/index.jsx, _inc/client/components/dash-item/index.jsx, package.json, yarn.lock
Fixes #8132
* introduces a new card Activity to point user to Activity Log
* test this with a Professional plan and without it
=> At a glance: add Activity Log card

docs/development-environment.md
* Fixes some minor typos in `docs/development-environment.md`
---
*I was just digging in a bit and thought I'd fix these while I was reading it myself.*
=> fix: Minor typos in docs/development-environment.md

modules/sharedaddy/sharing-sources.php
This JS was previously removed in #6339, but then added back (I think during a rebase) in #6332.
* Sharing: remove inline JavaScript used in the email sharing form.
Related: 774824-zen
=> Sharing: remove inline JS used in the hidden email sharing form.

modules/search/class.jetpack-search.php
Elasticsearch doesn’t guarantee the order of returned Aggregations will
match the input order, which leads to unexpected behavior when
rendering the Aggregations in the Widget.
Adds code to re-order the Aggregation results to match the ordering as
passed to `Jetpack_Search::set_filters()`.
Fixes #8096
=> Search: Fix aggregation ordering in search results

modules/masterbar/masterbar.php, modules/masterbar/overrides.css
Previously the user was redirected to `wp-admin/undefined` and would not be signed out properly.
Fixes #8142
1. Use test Jetpack site with WordPress.com toolbar module enabled.
2. Open the profile submenu and click on `Sign Out` button.
3. You should signed out and redirected to login page.
Note: this worked properly before, but some unrelated changes in the meantime, which I didn't track down yet, caused it to break. For reference check #6791 where we tested this behavior both for Jetpack site and WP.com side.
=> WordPress.com Toolbar: fix sign out redirect

class.jetpack-cli.php, modules/sitemaps/sitemap-librarian.php
Fixes a problem where after a complete regeneration of the sitemap old index files would still be included into the sitemap.
* Fixed sitemap custom post type query.
* Added a `--purge` switch to the CLI rebuild command to be able to rebuild sitemaps from scratch.
* Rebuild sitemaps using `wp jetpack sitemap rebuild --purge`.
* Make sure index sitemaps do not have duplicate entries.
* Fixed the sitemap generation mechanism.
=> Fixed the sitemap query to disregard trashed posts.

modules/likes/jetpack-likes-master-iframe.php
We need to pull down new translations for comment likes.
Fixes #7958
From the backend [when cache is busted]:
* New comment like strings with better context for translators.
* Denesting of some `if`s in `likes-rest.js`.
* Apply D8423-code
* Point widgets.wp.com to your SB.
* Clone this to your test site.
* Use a language that has translations for the new comment like strings.
Fixed comment likes localization bugs.
=> Likes: Bust iframe cache to facilitate string fix

_inc/lib/admin-pages/class.jetpack-settings-page.php, class.jetpack-connection-banner.php, class.jetpack-idc.php, class.jetpack-jitm.php, class.jetpack-modules-list-table.php, class.jetpack.php, functions.gallery.php, modules/comment-likes.php, modules/likes.php, modules/masterbar/masterbar.php
After a [comment](https://github.com/Automattic/jetpack/pull/8076#issuecomment-344840965) from @enejb, we made some changes to how we enqueue minified/non-minified JS in #8153.
Because of that, we now need to update how the JS in `_inc` is enqueued to be sure that we enqueue minified or non-minified JS files correctly.
To test:
- Checkout PR
- `yarn build`
- Test various parts of Jetpack
- Test IDC by triggering an IDC and ensuring the notice shows
- Trigger connection banner by deactivating and then reactivating Jetpack
- Visit `$site.com/wp-admin/admin.php?page=jetpack_modules` to trigger the modules js files
- Embed a Facebook post
- etc.
- Set `define( 'SCRIPT_DEBUG', true );` in your `wp-config.php` and ensure that non-minified JS files are enqueued when you run the above again
=> Build: Enqueue non-minified _inc JS when SCRIPT_DEBUG true

modules/lazy-images/lazy-images.php, tests/php/modules/lazy-images/test_class.lazy-images.php
The only thing I am 100% certain about is that we can never 100% predict where and how users will implement our products. Because of this, I am suggesting that we add a `jetpack_lazy_images_new_attributes` filter so that plugins and theme could hook in and provide better integration with lazy images in the case that there are some compatibility issues.
One potential case where this might come in handy is with themes that set `height: auto`. On themes that set `height: auto`, the `height` attribute on the image tag will be ignored. This has the effect of not reserving space in the page for the image, which causes reflow when we do actually load the image.
Themes could attempt to provide better support by hooking in and manually setting the height values via the `style` attribute:
```php …
```
=> Lazy Images: Add filter for modifying lazy image attributes

modules/masterbar.php, modules/masterbar/masterbar.php
Do not perform dns prefetching for logged out users since they won't be able to see the masterbar anyway.
We are relying on the fact that the masterbar is an extension of the default admin bar, which is only loading for logged in users. Further more, the `dns_prefetch` call is placed after the bail that checks if current user is WP.com connected one, so this will be executed only for users that will actually see the masterbar.
Fixes #8089
1. Use a test Jetpack site with WordPress.com Toolbar module activated.
2. When viewing the homepage while logged in you should be able to see the following lines in HTML source:
```
<link rel='dns-prefetch' href='//s0.wp.com'/>
<link rel='dns-prefetch' href='//s1.wp.com'/>
<link rel='dns-prefetch' href='//s2.wp.com'/>
<link rel='dns-prefetch' …
```
=> WordPress.com Toolbar: prevent dns prefetching for logged out users

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-comment-history-endpoint.php
Depends on D8410-code.
Add endpoint that will return comment history for given comment id.
This functionality relies on Akismet plugin.
1. Use your test Jetpack site with Akismet plugin activated. 
2. Point Jetpack to your permanent sandbox using `define( ‘JETPACK__API_BASE’, ‘https://hostname.wordpress.com/jetpack.’ )`;
3. Pick a comment and make some changes to it (approve, unapprove, spam etc).
4. Set GET request to `https://public-api.wordpress.com/rest/v1/sites/{site_slug}/comment-history/{comment_id}`
5. Verify that the comment history is correct.
6. Verify that correct error message is returned if Akismet plugin is not active.
=> Comments: add comment history endpoint

json-endpoints.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
This commit syncs r165593-wpcom.
Related issue: #8181
Module change forthcoming in a separate PR: #8182 
* Adds a 1.4 version of the site settings endpoint that allows new fields in the google analytics setting
Fire up postman
Set your headers to
Content-Type: application/json
Authorization: X-WPCOOKIE (steal a token from a developer REST API console request)
Origin: https://developer.wordpress.com
(you'll need to use Postman Interceptor to pull that off)
First, let's double check the 1.3 endpoint for regression
Direct a v1.3 GET request at /site/{siteID}/settings ( e.g. /sites/87832313/settings )
( i.e. public-api.wordpress.com/rest/v1.3/sites/87832313/settings )
Ensure you get a wga key in the response and that it has the following sub-keys
code, anonymize_ip, ec_track_purchases, and …
=> WPCOM API: Site Settings: Additional fields for Google Analytics D8279

modules/google-analytics/classes/wp-google-analytics-legacy.php, modules/google-analytics/classes/wp-google-analytics-options.php, modules/google-analytics/classes/wp-google-analytics-universal.php, modules/google-analytics/classes/wp-google-analytics-utils.php, modules/google-analytics/wp-google-analytics.php
Ready to test.
Fixes #8181 
* The Jetpack Google Analytics module currently only supports "legacy" (ga.js) analytics
* This PR refactors the  module in Jetpack to add support for "universal" (analytics.js) analytics and the ecommerce plugin while maintaining support for legacy analytics.
* Which is used is driven by a new field in the jetpack_wga option: `enh_ec_tracking`
* Both "modes" support IP anonymization, tracking new orders and tracking when products are added to the cart (on single or loop pages)
* A follow-on PR will expand on this PR further by adding support for these additional enhanced analytics behaviors:
enh_ec_track_remove_from_cart
enh_ec_track_prod_impression
enh_ec_track_prod_click
enh_ec_track_prod_detail_view
enh_ec_track_checkout_started
* Note: The original …
=> Google Analytics: Add support for universal analytics for eCommerce

modules/likes/queuehandler.js
Follow up to https://github.com/Automattic/jetpack/pull/8228
More info: https://github.com/Automattic/jetpack/pull/8228#issuecomment-346507519
With new translations some parts of the comment likes widget text were cropped due to fixed widget width. 
Update the widget width to assume the one of parent container in order to resolve this.
1. Use test Jetpack sites with Comment Likes module enabled.
2. Like one comment with two separate WP.com accounts in order to obtain `Liked by you and one other person` message.
3. Verify that all of the widget text is visible.
=> Comment likes: fix width of comment likes iframe

_inc/lib/admin-pages/class.jetpack-react-page.php
* Updates the check to see whether we need to load `w.js` to also check if the site is connected.
* On a disconnected Jetpack with the changes proposed here.
* Get to the Jetpack's Admin Page. View the source code. 
* Verify `w.js` is not loaded.
=> Admin Page: Don't load w.js until it's necessary

modules/stats.php
Fixes #8010
* Replaces a function created with `create_function` for passing as callback to `preg_replace_callback`. A new  function called `stats_convert_chart_urls_preg_replace_callback` which does the same is introduced.
* Start with a site running on PHP 7.2 with `WP_DEBUG` (and maybe `WP_DEBUG_LOG` too) (`/specialops`, can help)
* Check this branch and visit Jetpack's admin page dashboard
* Expect to see not logged message about `create_function` being deprecated.
=> Stats: Remove usage of create_function() in stats_convert_image_urls()

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-comment-counts-endpoint.php
Depends on D8370-code.
Closes: https://github.com/Automattic/wp-calypso/issues/19477
Add endpoint that will return comment counts for each available status on a given site. Optionally, these results are filterable by post_id parameter.
1. Apply D8370-code on your sandbox.
2. Point Jetpack to your sandbox using `define( ‘JETPACK__API_BASE’, ‘https://hostname.wordpress.com/jetpack.’ )`.
3. Set GET request to https://public-api.wordpress.com/rest/v1/sites/{site_slug}/comment-counts
4. Verify that the comment counts are correct.
5. Try passing in `post_id` parameter with the request and verify that the results are filtered by post.
=> Comments: add comment counts endpoint

package.json
This would make the Admin Page build process a little bit more reliable for folks not developing the admin page for a long time, or onboarding.
* Introduces an npm-script `install-if-deps-outdated` which runs `yarn check` and `yarn install --check-files` if needed.
* Runs `install-if-deps-outdated` before the `yarn watch` and `yarn build` are run.
* Remove one of the modules already present in your env (`rm -rf node_modules/react`).
* Run `yarn build` and expect nothing to fail. (This means the missing dependency will be installed)
* Remove another module.
* Run `yarn watch` and expect nothing to tail.
=> Admin Page: Add check for dependencies before attempting to build

class.json-api-endpoints.php
In r165506-wpcom I added a new flag to `class.json-api-endpoints.php` to allow access to selected endpoints (specifically `/read/site/:site`) if the site has been deleted.
In Reader, we use that functionality to return a `410 Gone` response when a site has been deleted rather than a 403.
Add the `allowed_if_deleted` configuration flag for an API endpoint. This defaults to false.
Set the flag to `true` in an endpoint definition. For example:
```
new WPCOM_JSON_API_Read_Site_Endpoint( array(
'description' => 'Get information about a site',
'allowed_if_flagged' => true,
'allowed_if_deleted' => true,
...
```
Ensure that you can access a deleted site using the endpoint.
=> Add flag to allow access to an endpoint if the site is deleted

_inc/client/at-a-glance/index.jsx
Removes the display of the new Dashboard card added in #8199 
Reverts the card from displaying on the dashboard, as it's not quite ready yet.  Left the guts of the card in the repo to make for a smaller changeset later. 
Now it should look like this again 
cc @eliorivero @samhotchkiss
=> Reverts the display of Dashboard card for AL

json-endpoints.php, json-endpoints/class.wpcom-json-api-get-comments-tree-v1-2-endpoint.php
Copy of D8318-code
Extend the `comments-tree` endpoint to accept an optional `post_ID` parameter to allow filtering the results for posts too, to cut the size of the tree requests for larger sites.
I thought the difference would have been minimal, but in fact the hard data contradicts me:
Fetching **all** comments on a large site:
- 127402 comments and pings
- 146KB of response size
- 420KB of content size
Fetching the **most commented post** on the same site:
- 825 comments and pings
- 2.5KB of response size
- 6KB of content size
I opted to extend the current endpoint instead of creating a whole new endpoint because I don't think this use case requires its own endpoint.
* Bump the `comments-tree` endpoint version to 1.2.
* Add a new `post_id` query parameter to only obtain the comments …
=> Comments: Add new Comments Tree v1.2 endpoint

_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-parser.php
Currently the code assumes that one (1) single quote in the query means that the user has forgotten the second one and wanted to quote a string.
For example searching for `can't login` would have the query rewritten to `can "t login"` (because it assumed you wanted to write `can't login'`, thus quoting `t login`) and this doesn't make a lot of sense for English.
By changing the regular expression to look at word boundaries we can make sure that such a single quote is only considered as "missing a partner" if no text is adjacent on both sides. See p1510734114000357-slack-mgs-next
This commit syncs r165510-wpcom.
=> Fix queries containing single quotes as apostrophes in words

modules/sharedaddy/sharing.js
Fix email sharing submit validation error when two instance of the widget are present in the same post.
Fixes #8154
There was a problem with jQuery selectors for source and target email inputs when the email sharing button is rendered more than one time in the same page.
The .val() method was always returning empty, causing an unexpected validation error.
The approach to fix the problem here is to use a selector relative to the current form element.
=> Sharing: Fix email sharing submit validation error.

sync/class.jetpack-sync-module-users.php
If we pass an error here into user_can, it'll fatal due to core not being defensive here.
As discussed in Slack with an issue with AT.
=> Sync: Defensive coding for user_can

class.jetpack-cli.php
Users running a multisite or scripting tools to run multiple single instances might be running Jetpack CLI commands across multiple sites at once. The lack of any information about what site the command is running on diminishes the usefulness of the output.
This change ensures the site URL is printed along with the output so that it's clear which site the command is running against.
I also moved some of the echo statements to use `WP_CLI::line()`.
* Apply the patch
* Run altered CLI commands and check output
=> CLI: Output site URL with some commands.

modules/google-analytics/classes/wp-google-analytics-universal.php
Fixes #8258 
* Don't attempt to use `wc_enqueue_js` when WooCommerce plugin is deactivated/not present
* WP_DEBUG true
* Use https://github.com/automattic/jetpack-google-analytics-helper to enable everything, especially enhanced eCommerce. Don't forget to give a tracking ID too.
* Deactivate the WooCommerce plugin
* Visit a front side page
* Ensure no error is logged to the PHP error log
=> Google Analytics: Test for WooCommerce before using wc_enqueue_js

bin/partner-provision.sh, class.jetpack-cli.php
With one of our hosting partners, we're noticing an issue that I believe is related to how they set the URL. They set the URL via the `WP_HOME` and `WP_SITEURL` constants, which seems to work well for web traffic. But, from the CLI, it appears that we're incorrectly getting the `home/siteurl` values from the `wp_options` table.
In this specific case, the option in the db is a development URL that is no longer accessible. So, when the partner runs the script, the register step fails because we can not reach the site.
To address this, I suggest we expose `--home_url` and `--site_url` arguments to allow the host to override the home/siteurl values when provisioning a plan. This will allow hosting partners who run into similar issues with CLI to set the URL as it should be.
Backstory in …
=> JPS: CLI: Allow hosts to override home and siteurl via partner provision script

_inc/client/components/themes-promo-card/index.jsx
Before this PR, we were mentioning a 50% discount for Jetpack Professional, which we plan to no longer offer.
This PR removes that link.
To test:
- Ensure site does not have a plan
- Ensure site is connected
- Click plans tab
- Ensure you see the promo above about Jetpack professional, without mention of a 50% discount
=> Promo Card: Remove 50% off link

modules/protect/blocked-login-page.php
500, 403 headers produce custom errror messages on pressable.
Making sure that we went 200 fixes the issue and show the message as expeceted.
Fixes issue were we were returning a 500 error on pressable and any other host that implemenets custom error messages.
* update the response code from the default 500 to 200.
* Do you see the 500 error message on pressable?
=> Protect: Fix Pressable

modules/search/class.jetpack-search.php
Fixes the following:
- `Illegal Offset` warnings when displaying WP Query tax searches that include a relation entry, e.g. 'AND'
- Missing active buckets due to typo in array check
- Allow min_doc_count on aggregations so that we can compress long month/year timescales and not run out of buckets
- Fixes https://github.com/Automattic/jetpack/issues/7946 by outputting query info as HTML comment in footer
- Add a filter which allows plugins to select when a WP_Query is to be handled by ES
=> Fix miscellaneous Jetpack Search issues

modules/search/class.jetpack-search.php
Adds a docblock for the newly added `failed_jetpack_search_query` action, corrects `@since` to be a full version number, and adds `@module search` to a few docblocks.
No functional changes.
Follow-up to #8276
=> Search: Various docblock fixes

json-endpoints/jetpack/class.jetpack-json-api-get-user-backup-endpoint.php
Fixes User backup endpoint
* Use `to_array` instead of array casting to convert WP_User object to an array. It's the correct method, and produces more predictable results.
* Call the `/user/x/backup` endpoint using a site token.
=> Use to_array to convert a user to an array; don't just cast it

modules/masterbar/tracks-events.js
Fixes #8272 
* Updates the Masterbar Tracks script to target the correct address when clicking on the blog infor elements.
* Enable the WP.com toolbar (masterbar)
* Go to any page in wp-admin
* Click "My Sites" in the top-left
* Click the Site Icon or label of the site at the top of the menu to visit the site
You should navigate away to the site url. There should be no regressions on other links.
=> Masterbar: fixes Site link from wp-admin is undefined bug

_inc/client/components/footer/index.jsx
Makes the version number more explicit on what it is, rather than just showing a random number.  
Before: 
After: 
cc @rickybanister
=> Update footer text for version to make more verbose

_inc/client/at-a-glance/index.jsx
This checks the `/features` endpoint response to see if `rewind` is active for the given site.  If so, it will add a card to the dashboard, the details of which are explained in #8199
more testing instructions when it's ready.
=> Conditionally add Activity Log card to dashboard if is an active feature

sync/class.jetpack-sync-module-posts.php
Closes #8302
Fixes an issue where sync was sending the old order status, not new order status.
See this bug: https://github.com/woocommerce/woocommerce/issues/18007
* Reload shop_order post type when processing `wp_insert_post` event
* Update order status on a Woo site
* Check that order status is properly synced on WPCOM
Properly synchronize post_status for Woocommerce orders
=> Reload post when saving shop_order to sync correct status

class.jetpack.php
@nickdaugherty recently created D8621 to fix an issue where the Jetpack search module wasn't showing for VIP clients. After looking into this, I think the ideal solution is to add `vip` to the business plans array.
We broke search for VIP clients in #7950, when we tried to fix an issue where we were trying to make sure that free users didn't see the Jetpack Search module when they couldn't use it since the API would return an error.
=> Plans: Add VIP as a product slug

modules/manage/confirm-admin.php, modules/masterbar/masterbar.php
See https://github.com/Automattic/wp-calypso/issues/20416 and https://github.com/Automattic/wp-calypso/issues/20617
* Change `/design` to `/themes` for Calypso Theme Showcase URLs.
* Load the branch, check your site's "masterbar" navigation: click "Themes" under Personalize to go to the correct URL.
Fix WP.com Theme Showcase URLs in toolbar navigation.
=> Update Calypso theme showcase URLs to /themes

modules/search/class.jetpack-search.php
When filtering by month+year, such as "December 2017", the remove URL for that filter cleared the month and day, not the month and year.
Fixes #8328.
1. Enable search beta.
2. Enable Jetpack search filter widget.
3. Enable a month filter using code described here: https://jetpack.com/support/search/customize-search/#basic-facets
4. Search for something on your test site.
5. Click on one of the month filters in the widget.
6. Click the remove filter link for that month.
7. Verify that the year has been removed from the URL.
=> Search: Fix the remove month+year filter link

modules/sharedaddy/sharing-sources.php
Fixes #8325
Bump character limit to 280 when sharing a post via Twitter.
=> Sharing: Bump character limit to 280 in Twitter sharing source

modules/lazy-images/lazy-images.php, tests/php/modules/lazy-images/test_class.lazy-images.php
Fixes #8320
In #8320, @galbaras reported that Lazy Images wasn't working on archive pages in Genesis. He further determined that this is because Genesis uses the `wp_get_attachment_image` function to display images on the archive page. Because of this, we weren't hooking in to lazily load those images.
This PR fixes that by refactoring Lazy Images so that there is a static method to modify an array of image attributes. This method is now called by `Jetpack_Lazy_Images::process_image()`, but it can also be used to handle lazy loading images generated via `wp_get_attachment_image`, since that function sends an array of attributes via the `wp_get_attachment_image_attributes` filter.
To test:
- Test that lazy images continue to load properly on a test site
- `phpunit …
=> Lazy Images: Add callback for processing image attributes array

modules/search/class.jetpack-search-widget-filters.php
This PR refactors the search filters widget so that other plugins/themes can hook in and change its output.
To test:
- You'll need a Jetpack site with a professional plan
- You'll need content with various dates, categories, and tags that has been synced to WordPress.com
- You'll need to manually add a filter(s), which you can find here: https://jetpack.com/support/search/customize-search/
- Go to wp-admin, or the customizer, of your site, and add the Search Filters widget to the sidebar
- Perform a search
- Ensure filters show up
=> Search: Refactors the search module so filters widget can be overridden

json-endpoints/class.wpcom-json-api-get-comment-counts-endpoint.php
Add integer typecasting to the returned values of `comment-counts`.
_Before_
_After_
Dotcom: D8722-code, r166736-wpcom
=> Comments: Ensure all values from the `comment-counts` endpoint are returned as integers.

class.jetpack.php
This PR introduces an `onboard` action to the admin page. For a user that's logged in and has enough capabilities to manage site options it:
* Generates an onboarding token (if not generated already).
* Is accessible at `/wp-admin/admin.php?page=jetpack&action=onboard`.
* Redirects to Calypso (through the Jetpack Server) with various parameters we'll use for the Jetpack Onboarding flow.
* Allows to specify the Calypso environment by adding a `calypso_env=ENV` parameter.
To test:
Follow the instructions in https://github.com/Automattic/wp-calypso/pull/20821
=> Admin: Introduce onboard action

modules/widget-visibility/widget-conditions/widget-conditions.js
Fixes #8338
* Trigger Change event when a Visibility Condition is deleted
* Create a Widget with 3 visibility conditions and Save
* On created Widget click visibility
* Click "delete" link for 1 of the visibility conditions
* Verify the "Save" button becomes enabled.
* Click "Save"
* Verify the condition was removed from the widget.
=> Widget Visibility - Save button enabled on removal of conditional

.eslintignore, modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php, modules/search/css/search-widget-filters-admin-ui.css, modules/search/js/search-widget-filters-admin.js
This is a rough first pass at adding UI to the search filters widget so that users can add filters without having to write code.
At this point, the UI is mostly functional for post types and taxonomies. You should be able to add one of those. Then, if you save and refresh, your choice should show again.
Known issues:
- Customizer preview is not great. User has to refresh page to get widget filters added to search
To test:
- Setup a Jetpack site with a professional plan
- Turn on the search module
- Go to the widget administration page
- Add the Jetpack search filters widget
- Tinker with UI 
- Set different filters and ensure the filters are applied on the frontend after performing a search
=> Search: First pass at adding working admin UI for filters widget

modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php, modules/search/css/search-widget-filters-admin-ui.css, modules/search/js/search-widget-filters-admin.js
Fixes #8374
In #8358, I broke the filters widget for users that had manually been setting the filters via `Jetpack_Search::set_filters()`, with the understanding that I would fix it in a follow-up PR. That is this PR.
This PR adds a checkbox that turns on the filter admin UI in the widget. If there are no active widgets that have that checkbox checked, the widget will default to displaying global filters.
If any widget has that checkbox checked, the widgets will only display their own filters.
To test:
- Checkout branch on a site with a professional plan
- Ensure that you have some filters manually set: https://jetpack.com/support/search/customize-search/
- Ensure that your filters show on the front-end when searching
- Check the "Add filters" checkbox and set a filter
- Refresh search …
=> Search: Provides backwards-compat for the filters widget

_inc/client/at-a-glance/index.jsx
In preparation for updating the cards for Security Scan and Backups to display content based on Rewind availability, this PR feeds the prop that contains the state of Rewind for a certain site into the components for Security Scan and Backups.
It also removes a couple of redundancies.
Elements in dashboard should work in the same way, there was no update in their behavior.
=> At a glance: add Rewind state prop to Security Scan and Backups

_inc/client/plans/index.jsx, _inc/client/plans/plan-body.jsx
Fixes #8263
To Test: 
- For a site with Rewind "active", you should see the card above in /plans **regardless of which plan you are on**
- If a site does not have Rewind active, the card should look and behave exactly as it did before.
=> Update "/plans" Backup card to reflect an active Rewind site

_inc/client/at-a-glance/backups.jsx, _inc/client/components/dash-item/index.jsx, _inc/client/state/site/plugins/reducer.js
Related #8266
* the Backups card in dashboard will be updated based on VP or Rewind availability
* fix issue where during load and without VP plugin deactivated, the "Loading..." text wasn't shown and instead the text to install VP plugin was shown
* refactored to clean up code and make things more reusable
* updated DashItem so the Set Up button or the toggle are hidden when it's a Rewind feature
* test with a Rewind-enabled site and another without it
=> At a glance: update Backups dashboard card based on Rewind availability

_inc/client/at-a-glance/scan.jsx
Related #8266
* update Security Scan card in dashboard to show content based in VP or Rewind availability
* Refactor card
* move method that can be static as a const outside of component
* test in a site with Rewind and another without Rewind
=> At a glance: update Security Scanning card to show content based on Rewind

_inc/client/components/settings-card/style.scss, _inc/client/pro-status/index.jsx, _inc/client/security/backups-scan.jsx, _inc/client/security/index.jsx, _inc/client/settings/index.jsx
For #8264
- For a site that has Rewind active, the scan/backups card in /security should reflect rewind.  
- If a site does not have rewind active, then it will continue to show the VaultPress card.
=> Update Security Settings card to reflect Rewind

modules/search/class.jetpack-search-widget-filters.php
If a site had disabled search filters via the `jetpack_search_disable_widget_filters` filter, then when a widget was saved, it caused an undefined index notice:
```
PHP Notice:  Undefined index: filter_type in .../jetpack/modules/search/class.jetpack-search-widget-filters.php on line 152
```
I didn't catch this before because I was testing on widgets where I had previously configured a filter.
To fix this, I added a condition to not check `$new_instance['filter_type']` if widget wasn't supposed to use filters.
To test:
- On a site with a professional plan
- Checkout Jetpack master
- Set `add_filter( 'jetpack_search_disable_widget_filters', '__return_true' );`
- Add a new Jetpack search filters widget
- Check error log for undefined index notice
- Checkout this branch
- Add a new Jetpack …
=> Search: Fixes an undefined index when filters were disabled via filter

modules/theme-tools/featured-content.php, modules/theme-tools/social-links.php
* I see many file customize_register() use esc_html__() instead of __(). So it is fine to use esc_html__() maintain consistency. 
*
=> theme-option: Use esc_html__() in customize_register function. 

class.jetpack-cli.php
Related #8266
This doesn't do anything, just displays a message in command line.
=> WP CLI: remove VP reference

_inc/lib/markdown/gfm.php
This ensures that nested blocks are replaced first (e.g. code inside shortcodes).
Fixes #7535.
* Replace hashes in (roughly) the same order they were added.
* Follow example from #7535.
* Markdown: Fixed bug where code inside shortcodes isn't correctly restored from the hash.
=> Markdown: Reverse text hashes before restoration

_inc/jetpack-jitm.js
On a page where two JITMs exist, but the first has been dismissed, the response back from the API [here](https://github.com/Automattic/jetpack/blob/master/_inc/jetpack-jitm.js#L71) will be an object with a key of `1`:
```javascript
{ 1: [...] }
```
...instead of the zero-indexed array expected in [the code handling the response](https://github.com/Automattic/jetpack/blob/master/_inc/jetpack-jitm.js#L73-L78), giving an uncaught type error (and no JITM displayed).
This PR hacks Humpty back together again, but I'm not sure how better to handle it. It seems we should be leaving the response coming from the API alone, to keep open the possibility of handling multiple JITMs on the client [in the future](https://github.com/Automattic/jetpack/blob/master/_inc/jetpack-jitm.js#L77). This PR also …
=> JITM: Fix JITM display when the first result has been dismissed.

modules/widgets/goodreads.php
See 7920-wpcom patch ready for commit on WP.com side.
* Update WP.com support link to support HTTPS
* Update Goodreads URLs to support HTTPS
* Add the widget to a sidebar, test with an author ID like `68367616` [Author page](https://www.goodreads.com/author/show/8071273.Joanna_Kafarowskil)
* Test also with a normal, non-author user like `16499599` [Lance](https://www.goodreads.com/user/show/16499599-lance-willettl)
Widgets: update Goodreads URL for HTTPS support
=> Update Goodreads URL for HTTPS support

_inc/client/at-a-glance/index.jsx, _inc/client/plans/plan-body.jsx, _inc/client/security/index.jsx
If Rewind is not active, but available for some reason, hide all mentions of VaultPress.
Test: 
- If a site is unavailable for Rewind, everything should behave as normal 
- If a site has rewind active, continue to show mentions/cards for rewind
- If a site is not either of those, i.e. "available", then you should not see any cards for VaultPress in neither /plans, nor /settings/, nor /dashboard.
=> Hide all mentions of VaultPress if rewind is available but not active

modules/related-posts/class.related-posts-customize.php
* Comment is not write on "jetpack_related_posts_customize_options filter" in class.ralated-posts-customize.php file so I add comment. 
*
=> Related Posts: add docblock to existing filter

modules/custom-post-types/portfolios.php
* enables revisions for `jetpack-portfolio` post type
* ensures feature parity with r120738-wpcom which is in place for 2 years already
* make a new post with post type `jetpack-revisions`
* save the draft few times
* confirm you can see revisions in the sidebar, just as you would see for posts or pages
Added ability to create revisions of Portfolio Projects.
=> Add revisions to Portfolios

_inc/client/components/footer/index.jsx, _inc/client/state/initial-state/reducer.js
* fixes an issue where the Jetpack version at the footer was shown as `undefined` since data wasn't still available. This will now show Jetpack when the version is unavailable and the complete Jetpack version xx when it's available.
* throttle or use a slow network and load the admin and verify it doesn't show undefined for the version on the footer
=> Dashboard: fix undefined version number on footer

tools/build-release-branch.sh
While creating a built branch I realized that some git-ignored files from the release branch (the not-built one) were still added to git tracking by the `tools/build-release-branch.sh` script because they were there from a previous unrelated build run in `master`. As the files were .gitignored I didn't notice them until they were commited to the built branch (consequence of an `git add .` from the same scripts.
* Adds a line before installing dependencies  running `yarn clean-client`.
* Don't test it. Just review the code
=> Release Branch Build: Run yarn clean-client before building the Admin Page

_inc/client/writing/index.jsx, _inc/client/writing/masterbar.jsx
Users of Atomic sites are currently seeing this toggle and being able to interact with it. This results in a weird experience when they try to deactivate the Masterbar as the toggle ends up moving, the page refreshing and the masterbar stays active.
* Checks if the site is an atomic site and skips rendering the Masterbar settings card if it's the case.
* On an atomic site, with Jetpack Beta, check this PR
* Confirm that the card is not shown under the Writing tab. 
Hide the Master bar settings card for Atomic Sites.
=> Admin Page: Hide Masterbar toggle for Atomic Sites
