Automattic/jetpack

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Fixes #8399
* Adds a check with `is_readable` in case PHP can see the `akismet/akismet.php` file exists but can't read its contents.
* On a connected Jetpack site with Akismet present.
* Remove reading permissions from the `akismet/akismet.php` file
* Visit the Jetpack admin dashboard
* Expect to see no fatal errors (e.g. in debug.log)
* Fixes a fatal error caused when hittin an endpoint api and akismet files are present but not readable.
=> REST API: Check if Akismet plugin file is readable in REST API endpoints code

modules/comments/comments.php
Fixes #7357 
A proof of concept to investigate whether we could be less aggressive with the `comment_form_after` hook and get the same effect.
Testing:
Add a plugin that hooks in after the comment form, such as Webmentions ( https://wordpress.org/plugins/webmention/ ).
Before: JP comments override and does not display the Webmentions form.
After: Webmentions form displayed, nothing else changed.
=> Comments: Allow comment_form_action actions

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This updates the JPO onboarding request to insert a contact form to automatically enable the contact form module if not enabled already. Previously, it would just bail if the module was disabled.
To test:
Follow the instructions in https://github.com/Automattic/wp-calypso/pull/21065
=> REST API: JPO - enable contact form module when inserting form

class.jetpack.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
As found independently by @ockham and @oskosk and discussed in p1513787687000060-slack-jetpack-onboarding and p1513970123000089-slack-luna, if a user has an onboarding token, this would cause the connection links to contain the `onboarding=TOKEN` parameter, which would then lead users to a broken JPC flow (because JPO in Calypso is not yet in production).
* Checkout the latest Jetpack master on your **unconnected** Jetpack sandbox.
* While logged in as an admin, load `/wp-admin/admin.php?page=jetpack&action=onboard`
* Go to `/wp-admin/admin.php?page=jetpack#/`
* Inspect the connect button link - it contains the `onboarding=TOKEN` parameter.
* Attempt to connect - you will be dropped at an empty page in WP.com.
Seems like this is caused by some code from the previous JPOalypso attempt, …
=> Isolate Jetpack Onboarding from Jetpack Connect

modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php
Moves us closer to #8372 design for JP Search
- added search box
- restyling of headers and added some css classes
- adjust defaults for number of items
- adjust name and description since this is now a generic search widget
- reorder the dates so earliest first
I tested in a bunch of popular themes:
- 2010, 2011, 2012, 2013 (has no sidebar), 2014, 2015, 2016, 2017
- Storefront
- Astra
- Shapely
- ColorMag
Took these from https://wordpress.org/themes/browse/popular/ and went for themes with more than 50k active installs.
Mostly all look ok. A few minor spacing issues (Shapely in particular for the search box). I don't love that I resorted to breaks. :/ Not sure if there is a better way.
Would like to get this into 5.7.
=> Search: widget styling and design improvements

modules/wordads/php/widgets.php, modules/wordads/wordads.php
A handful of back-end updates to provide a bit of extra space for "Report This Ad" link we're rolling out.
**Note**
The `Report This Ad` link itself is something we enable from the ad server, so don't fret if it doesn't appear during testing. You can see it live on https://derekspringer.wpsandbox.me/
**To Test**
1. Enable Jetpack Ads module
1. Enable `Display second ad below post`
1. Check to see that 2nd unit appears below post
1. Enable options under `Enable below post ads on`
1. Check below post ads do/don't display under appropriate type of page
1. Enable AdBlock Plus extension (😭)
1. Check `Allow some non-intrusive advertising` in `Adblock Plus Options`
1. Check that some non-obtrusive ads are in the regular spots.
=> Ads: Updates for "Report this ad" link

_inc/client/plans/plan-body.jsx, _inc/client/traffic/index.jsx, _inc/client/traffic/search.jsx
- Adds a toggle for turning on search to the JP settings->traffic page
- Adds a toggle for turning on search to the JP Plans page - and a link to the widgets admin when it is already enabled
This should complete cleaning up the purchase flow from buying a Pro plan to enabling and configuring search.
=> Search: add to plans and settings dashboards

sync/class.jetpack-sync-defaults.php, sync/class.jetpack-sync-functions.php, tests/php/modules/publicize/test_class.publicize.php, tests/php/sync/test_class.jetpack-sync-callables.php
- Add a whitelist to what we sync.
- Add a way to convert the synced data back to what we expect
- Add tests to show that things work as expected.
Fixes p4IuY0-TS-p2
* Only sync sanitized post type data.
* Do we get expected values on the .com side? 
* Do subscription emails, publicize and other things work as expected?
=> Sync: Better Post type syncing

class.jetpack.php
Needs https://github.com/Automattic/wp-calypso/pull/20777.
Just as we've added the ability to redirect front-end post and page edit links to Calypso in #7732 , this PR gives the same treatment to front-end comment edit links. The same Jetpack option is used for activating (`edit_links_calypso_redirect`).
When this option is enabled, comment edit links will be filtered with an `href` pointing to Calypso, in the format `/comments/all/:site?commentId=:comment-id&action=edit`.
See https://github.com/Automattic/wp-calypso/issues/17221.
**Testing**
* Switch to this branch.
* Ensure the option returns as enabled. One way is to edit `class.jetpack.php` L619 and replace the first check `Jetpack::get_option( 'edit_links_calypso_redirect' )` with just `true`.
* Verify that a front-end Edit link for …
=> Comments: Redirect front-end comment edit links to Calypso.

docs/git-workflow.md
This PRs add some shell snippets on how to rebase a PR that comes from a forked repo.
Sometimes we need to ask folks to rebase their PRs and this flow may not be so familiar to them.
* Adds some text to `docs/git-workflow.md`
*  Check the [rendered version of the new section on this PR](https://github.com/Automattic/jetpack/blob/add/rebasing-instructions-on-devdocs/docs/git-workflow.md#keeping-your-pr-up-to-date-as-an-external-contributor) and confirm commands make sense
=> Development Docs: Add instructions on how to rebase against master for external contributors

modules/search/class.jetpack-search-widget-filters.php
- Clarify when filters get shown so the user knows they need to search for them to be displayed
- Clarify that the number is a maximum
- Make the casing consistent
- Based on some user testing feedback for 5.7 release
=> Search: Update Widget Text

tests/php/_inc/lib/test_class.rest-api-authentication.php
Fixes failing unit test that expects status code `403`. This was introduced in latest core master here: https://github.com/WordPress/WordPress/commit/a7870062981b3200802b3059b6d65bf5d6ee5369
Updates the test `WP_Test_Jetpack_REST_API_Authentication::test_jetpack_rest_api_authentication_fail_no_token_or_signature` to expect `401` instead of `403`.
* Run the tests and expect them to pass. (Which is the same as seeing this PR passing the tests).
=> REST API Tests: Expect proper http status code instead of previously hardcoded 403 with WordPress >= 5.0-alpha

.svnignore
@oskosk reported an issue to me where we weren't shipping the non-minified JS files in the `_inc/js` directory. This is because we added `_inc/*.js` to the `.svnignore` file.
We did this because, originally, we decided to only ship minified files along with map files. But, for the last release, we found that shipping the non-minified files was actually bit lighter than shipping maps, so we changed that.
Unfortunately, as part of that change, we didn't update the `.svnignore`. And, since the files are only purged when releasing a master-stable build or a build for release, via scripts in the `tools` directory, we didn't notice the issue.
To test:
- Modify the `tools/deploy-to-master-stable-branch.sh` so that the "echo "Finally, Committing and Pushing" until the end of the file are …
=> Build: Fixes issue where non-minified files in _inc/js were not shipped

tests/php/sync/test_class.jetpack-sync-callables.php
The `var_dump()` that was added in https://github.com/Automattic/jetpack/commit/0aabd5172a6615492d3453d14ae14803273ccbcc is polluting the unit test results. Example:
https://travis-ci.org/Automattic/jetpack/jobs/324279199#L653-L801
=> Remove var_dump() from unit test

bin/partner-provision.sh, class.jetpack-cli.php
Overrides the email sent to WPCOM for the "Partner Provision" request. 
For partners that are auto-connecting, this allows them to re-provision with an email that matches an existing account, in case the user didn't want to create a new account or connect to the one that matches their WP user email.
=> Add wp-cli argument to override user_email for partner-provision

docs/development-environment.md
No need to run `npm install` since running `yarn` will do the same thing but much better, and `yarn watch` runs our `install-if-deps-outdated` script which in turn will install as needed.
=> Remove npm install suggestion, yarn does it

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, class.jetpack-options.php
This updates the JPO onboarding request to save the site type in the onboarding request. Previously, the site type was not taken into consideration. Option name is consistent with the original JPO plugin (see https://github.com/Automattic/jetpack-onboarding/blob/master/class.jetpack-onboarding-end-points.php#L7).
To test:
Follow the instructions in https://github.com/Automattic/wp-calypso/pull/21154
=> REST API: JPO - save site type

class.jetpack.php
As @oskosk correctly identified and explained in https://github.com/Automattic/jetpack/pull/8414#issuecomment-354473595, with a fresh JP site we're unable to initiate the onboarding process. This is because in the initial JPC registration step, we didn't support the onboarding parameter when isolating JPO logic in #8414.
To test:
* Go through steps in https://github.com/Automattic/jetpack/pull/8414#issuecomment-354473595
* Verify you're able to arrive to the onboardng page in all cases.
* Verify you're still able to connect and reconnect a JP site properly.
=> JPC: Support onboarding in register step

gulpfile.babel.js
Fixes issue when building languages and for example, `msgfmt` is not installed in the system.
* In gulpfile.babel.js, calls `callback()` with an error as parameter if `export-translations.php` exited with non zero code.
*  check this branch
* Edit `export-translations.php` adding `exit 1` on the first line of the file. Save and exit the editor.
* Run `yarn build-languages`.
* Expect the command to fail and stop execution of the other language-related gulp tasks.
=> Build: Make the languages task fail if the export-translations.php tool exits with code different than zero.

class.jetpack.php
Currently, if dev mode is disabled and you're not connected, you're not able to enable modules that don't require connection. We'll need to be able to do it for JPO - this is what this PR suggests.
To test:
* Disable dev mode.
* Pick a fresh unconnected, site that doesn't have an onboarding token yet.
* Try enabling contact form module (`wp jetpack module activate contact-form`)
* Verify module is not activated.
* Generate an onboarding token (`/wp-admin/admin.php?page=jetpack&action=onboard` can do it for you)
* Try enabling contact form module (`wp jetpack module activate contact-form`).
* Verify module is activated.
* Try activating a module that requires connection (like photon). Verify it doesn't activate, even if you have an onboarding token.
=> Allow enabling connection-free modules when onboarding

modules/search/class.jetpack-search-widget-filters.php, modules/search/js/search-widget-filters-admin.js
In #8372, @gibrown suggested setting the default number of everything to 5. This PR sets the default number of buckets to return for each filter to 5.
We set the number as the `DEFAULT_FILTER_COUNT` constant on the `Jetpack_Search_Widget_Filters` widget. We then use that constant throughout the widget code and we also pass it to JS so it uses that value as well.
To test:
- Checkout branch on a site with a professional plan
- Add the Jetpack search widget to a sidebar
- Add a filter
- Ensure the number of filters is set to 5 by default
=> Search: Set default filter count to 5 for all filters

class.jetpack-modules-list-table.php
Fixes #8423
We previously removed the activate/deactivate links for the Search module on the old settings page in #7950 because users that didn't have a professional plan were activating the module.
With the launch of Jetpack Search coming next month, and with other plan checking in place, we can show these options again.
=> Search: Show activate/deactivate controls on old settings page

modules/search/class.jetpack-search-widget-filters.php
Fixes #8435
Before this PR, a user could enter a negative number of filters or a number that was too high.
After this PR, the values are limited to integers between 1 and 50 inclusive. Any value below 1 will become 1 and any value above 50 will become 50.
To test:
- Checkout branch on a site with Jetpack professional
- Add widget
- Add a filter
- Check different number values and ensure that after saving, the value updates to some integer between 1-50
After screenshot:
=> Search: Add filter count validation to filters widget

modules/search/js/search-widget-filters-admin.js
I noticed that when I added a new filter by clicking the "add" link at the bottom of an existing filter, that I got a JQMIGRATE warning in the console:
```
jQuery.fn.attr('selected') might use property instead of attribute
```
The issue is that while we do set the selected value in HTML by adding a `selected` attribute, that corresponds to the `defaultSelected` prop and not to a `selected` prop, and it should only be used to set the initial value. That is per the jQuery documentation, under the Attributes vs. Properties heading, here: http://api.jquery.com/prop/
To fix this, we simply needed to swap out the usage of `attr` with `prop`.
To test:
- Checkout branch on a site with a professional plan
- Add Jetpack search widget to a sidebar
- Ensure that you create at least two filters
- …
=> Search: Fix jqmigrate warning due to using attr instead of prop

_inc/lib/class.jetpack-automatic-install-skin.php, _inc/lib/plugins.php, json-endpoints/jetpack/class.jetpack-json-api-plugins-install-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-plugins-new-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-themes-install-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-themes-new-endpoint.php
Some prep work for ~#8450~ #8482. De-duplicate all the things!
Move:
* the `Jetpack_Automatic_Install_Skin` helper class to `_inc/lib/class.jetpack-automatic-install-skin.php`
* some static helper methods from `Jetpack_JSON_API_Plugins_Install_Endpoint` to `Jetpack_Plugins` in `_inc/lib/plugins.php`.
To test: Make sure all affected endpoints still work. Note that `Jetpack_Automatic_Install_Skin` is used by a few other endpoints (grep to verify!):
* Plugin installation (from WP.org): `POST` to `/sites/%s/plugins/%s/install` (try `woocommerce`)
* Theme installation (from WP.org): `POST` to `/sites/%s/themes/%s/install` (try `twentyseventeen`) -- *see note at bottom*
* Plugin installation (via upload): `POST` to `/sites/%s/plugins/%s/new` -- use Calypso to test …
=> Move code from plugins install endpoint to new Plugins Library

modules/search/class.jetpack-search.php
We output debug data that comes from a remote source and even though that remote source is us, this makes it unsafe to be trusted. As a result, this data should be escaped for safety. For example if the result contained `-->`, it could be used to output arbitrary HTML.
=> Search: Escape remotely supplied data just to be safe

_inc/client/main.jsx
Avoid an unnecessary query to .com if the site is not yet connected when visisting the Jetpack Admin Page.
* Checks if site is connected before rendering the `QueryRewindStatus` component.
* Check this PR on a disconnected site.
* Build the admin page
* Visit the Jetpack Dashboard
* Expect to see no failed request (404 status if the site is brand new. 400 if the site has been connected before being disconnected now) to get rewind status on the network panel.
=> Admin Page: Only query Rewind status from Jetpack Dashboard if the site is connected 

sync/class.jetpack-sync-module-updates.php
Use the pre_update_site option filter to hook into the event. This way we would always get the evernt not just when the is really neccessery.
Fixes issue reported that said that the event wasn't showing up as expected.
* Listen for when the filter gets fired. Since that filter always gets fired before the update to the option.
* Go to the network admin click update.
=> Sync: Sync the network update event everytime

.github/CONTRIBUTING.md
We do not use the Community milestone anymore. Instead we use a label.
=> Docs: update link to community issues in contributing guide.

class.jetpack-post-images.php, modules/widgets/top-posts.php
1. Insert an image in a post. It should be a big image. It can be hosted somewhere else.
2. Publish the post.
3. Visit that post a few times while logged out.
4. Add the Top Posts widget to your site and configure it to show images list.
5. The post should use the image from the post, and not a fallback image.
* Post Images: allow passing size when searching for images in HTML.
=> Post Images: allow passing size when searching for images in HTML.

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, _inc/lib/plugins.php
Add `install_and_activate_plugins()` to the Plugins Helper class, and use that to install WooCommerce from the JP Onboarding endpoint.
Counterpart to Automattic/wp-calypso#21237 -- find testing instructions there.
=> REST API: JPO: Enable WooCommerce installation

modules/sharedaddy/sharing-sources.php
Fixes #
Instead of using whatsapp deeplink, use the official api to support whats on web, and will trigger whatspp app when installed on mobile
https://faq.whatsapp.com/en/general/26000030
*
*
=> use whatsapp api click to chat

modules/shortcodes/brightcove.php
Fixes error being shown when used under PHP 7.2.
Part of #8156.
* Updates `shortcodes/brightcove.php` to check attributes with `is_array()` before assuming we can use `count()` on the argument passed to `normalize_attributes()`.
* Run `phpunit --testsuite infinite-scroll` under PHP 7.1, PHP 7.0 or PHP 5.6
* Expect test to pass.
* Updated Brightcove shortcodes to be compatible with PHP 7.2.
=> Shortcodes: Check if Brightcove shortcode attributes are an array before assuming they can be counted

sync/class.jetpack-sync-module-users.php, tests/php/sync/test_class.jetpack-sync-users.php
Add state of the jetpack_sync_save_user event so that we know a bit more information as to why it was triggered in the first place. This will make it easier to provide info to the user as to what was changed.
- Did the role change? Did the capabilities change. Did we also change the password? Did all those things change at once? 
Fixes issue where we didn't record that we a password was changed. 
* Add a state to the jetpack_save_user sync event that provides more info as to why the event happened. 
* Does everything still work as before? 
* Test changing password, Role, and user data at once. 
* Test adding a new user. Do we get the right info? 
* Test Removing a user? 
* Does multisite still work as expected?
=> Sync: Add user password syncing as an event

_inc/client/components/settings-card/index.jsx, _inc/client/lib/plans/constants.js, _inc/client/traffic/search.jsx, modules/search.php, modules/search/class.jetpack-search-widget-filters.php
Fixes #8468 
Adds a prompt for non-Professional sites to upgrade to get Jetpack Search.
=> Add upgrade prompt for Jetpack Search

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, class.jetpack-options.php
This PR updates the JPO contact form saving to store the ID of the contact page in an option. We'll need that in order to provide consistent experience to the user; also for knowing whether the user has already completed the contact form step.
We'll use this option when retrieving onboarding data for the GET onboarding endpoint.
To test:
* Use https://github.com/Automattic/wp-calypso/pull/21003 for step by step instructions.
* Verify the `jpo_contact_page` option is set (you can use `wp jetpack options get jpo_contact_page`)
=> REST API: Store JPO contact form page ID in an option

tests/php/sync/server/class.jetpack-sync-test-replicastore.php
Part of #8156.
* Replaces usage of `create_function` in `class.jetpack-sync-test-replicastore.php` for regular foreach loops and a set of new class methods that serve as callback to `array_map`.
* Run tests on PHP 7.0, PHP 7.1 or PHP 5.6 and confirm they pass. 
Updated code to be compatible with PHP 7.2
=> Remove usage of create_function so PHP 7.2 does not complain

.svnignore
We were shipping this file when bundling. 
* Adds `webpack.config.js` to .svnignore.
=> Build: Add webpack.config.js to svnignore

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, class.jetpack-options.php
This PR updates the JPO homepage saving to store the format of the homepage in an option. We'll need that in order to provide consistent experience to the user; also for knowing whether the user has already completed the homepage format step.
We'll use this option when retrieving onboarding data for the GET onboarding endpoint.
To test:
* Use https://github.com/Automattic/wp-calypso/pull/21003 for step by step instructions.
* Verify the `jpo_homepage_format` option is set (you can use `wp option get jpo_homepage_format`)
=> REST API: Store JPO homepage format in an option

class.jetpack.php
Seems like in #8449 we introduced `sanitize_key` over the registration URL onboarding token. This was a mistake, because it caused (only) fresh Jetpack sites onboarding tokens to be passed to Calypso as lowercase instead of uppercase 🤦‍♂️ And then, when comparing the lowercase tokens to the original ones, comparison failed and signature was different, thus we received the "The request is not signed correctly." error.
So, we don't need the `sanitize_key` and we can remove it safely.
To test:
* Start a new JN site with the latest JP master (to do that, start the site from here https://jurassic.ninja/create/?shortlived&nojetpack and use ssh to install Jetpack master)
* Go to https://YourJetpackSandbox.com/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=development where …
=> JPO: Remove sanitize key on registration URL

sync/class.jetpack-sync-module-users.php, tests/php/sync/test_class.jetpack-sync-users.php
This PR removes duplicate synced actions.
To test:
With this diff applied try
adding a new user
editing a user
adding / editing via API
editing your profile
add existing user to multi-site
invite user -> user accepts invite
user registers via registration form
delete user
Ensure stuff is syncing properly upstream.
=> Sync: Update User Sync Module

sync/class.jetpack-sync-module-posts.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/test_class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-posts.php, tests/php/sync/test_class.jetpack-sync-sender.php
Sync previous state with in the wp_insert_post
Currently we don't have a good way to tell what the previous state was previous state with we sync posts.
Creating a new action would help keep things backwards compatible. 
*
* With the .com patch do you does you site still publicize and send subscription emails? 
* Does the data save and are you able to get the post to show up in related posts?
=> Sync: Sync previous state when sycing post saves. 

modules/carousel/jetpack-carousel.php
Fixes an issue in Jetpack Carousel that printed an Array to string conversion notice on the screen.
Reported in https://wordpress.org/support/topic/php-notice-array-to-string-conversion-in-jetpack-carousel/ and 892311-zen.
To reproduce the issue:
- add meta to an image, where that meta is an array
- add that image to a gallery
- output that gallery as a Jetpack carousel
- you will see a notice like "Notice: Array to string conversion in 
`/home/user/public_html/wp-content/plugins/jetpack/modules/carousel/jetpack-carousel.php 
on line 444`
This PR removes non-scalar values from the array before applying strval.
=> Fix array->string conversion notice in carousel

modules/protect/math-fallback.php
Before they were called as static methods and they fatalled on multisites because setter and getter methods require self object calls inside them.
Fixes #8507.
* Try to log into a multisite installation with Protect unavailable (mangle the API URL).
* Observe a fatal.
* Try to do it with this PR.
* Observe a math fallback instead.
* Fixed the math problem fallback for logging into Multisite installations.
=> Modified transient setter and getter calls to be object method calls.

_inc/lib/tracks/tracks-ajax.js
Fixes #8517
* Prevents window.opener from being set with new tabs opened via tracks lib
* Open a jitm link, `window.opener` should be null
=> Prevent linked pages from using window.opener

_inc/client/security/backups-scan.jsx
Reported by @Viper007Bond in Slack, the `/security` tab was repeatedly requesting endpoints.  This was introduced in #8382 where we were rendering a loading card if we were fetching data, and when the data was fetched it was calling a sub-component `ProStatus` which would request again, etc... 
To Test: 
- Activate VP plugin
- Make sure there are no multiple requests being made in /security tab.
=> Rely on data rather than fetching state to determine loading

_inc/jetpack-jitm.js
* Makes the button link in JITM open a new window without sharing control of the current window to the destination site.
* Adds attribute `rel="noopener noreferrer"` to JITM button link in `_inc/jetpack-jitm.js`.
* Confirm that the JITM setup link contains the `rel` attribute.
=> JITM: Add noopener noreferrer to jitm button link

_inc/client/lib/decode-entities/index.js, _inc/client/writing/index.jsx, _inc/client/writing/media.jsx, _inc/client/writing/speed-up-site.jsx, modules/lazy-images.php, modules/module-headings.php, modules/module-info.php, modules/photon.php
Closes #8193
When we launched lazy images in 5.7, we did not ship any react admin UI. This was partly because we wanted to do a soft launch and also because we would be releasing a new feature just before the holidays.
Now that we're past the holidays and have had some time to test the feature, let's get it out there!
Following the advice of @rickybanister, @michelleweber, and others in #8193, this PR creates a new section within the "Writing" tab called "Speed up your site". This PR, then moves the photon setting into this section and adds the lazy images setting as well. Further, this PR updates the descriptions for the Photon module to match what was suggested in #8193.
To test:
- Do a fresh `yarn build` to rebuild module translations
- Go to "Writing" tab of Jetpack …
=> Lazy Images: Add react admin UI

modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php
Closes #8139 and Closes #8371
This PR adds the ability to select which custom post types to search for a given Jetpack search widget.
We accomplish that by getting the search form code and appending a hidden input with the post types that have been selected for the widget. This will allow us to support multiple search widgets across the site.
Once I added this support, I noticed that even when I set `post_type` to some value in the query args, it doesn't have any effect. 🤔 
After a bit of looking, I found this article: https://codex.wordpress.org/Plugin_API/Action_Reference/pre_get_posts#Exclude_Pages_from_Search_Results
Which suggests that we need to manually set the post type for search. So, I also did that, which fixes #8371.
To test:
- Checkout branch on a Jetpack site with a …
=> Search: Improves post type support

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search.php, phpunit.xml.dist, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8532
In #8532, I noticed an issue where we were building URLs for filters that sometimes resulted in 404s. The root cause of this is that we were simply adding/removing query args to the current URL which included the page of the search results.
So, if the user was on, say, page 4 of search results, and then selected a filter that reduced results to a single page, then the user would end up getting a 404.
To fix this, I created a class named `Jetpack_Search_Helpers` with some functions that add the query args to the result of `home_url()`. 
As a note, this PR also adds some boilerplate for unit testing the search module. 👍 
To test:
- Search for term with many results
- Go past page 1 of results
- Select a filter, and ensure that …
=> Search: Begin using helper for adding and removing query args

modules/search/js/search-widget-filters-admin.js
Fixes #8475
In #8475, @Viper007Bond pointed out that removing filters didn't always allow the customizer to save the filter removal. After testing, I found that the customizer would not allow a save if ONLY a filter had been removed. If any other form field had changed, the customizer would allow saving.
It appears the the root issue is that we're dynamically inserting/removing content to our widget and the customizer wasn't receiving change events when we added or removed those values.
The fix here was to fire some change events when we added or removed a filter.
To test:
- Add Jetpack Search widget
- Add filter
- Ensure that customizer button changes to "Save & Publish"
- Click that "Save & Publish" button
- Ensure that button text …
=> Search: Ensure adding or removing filters allows customizer to save

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This PR introduces an `onboarding` option in the GET settings endpoint, in order to allow us to retrieve the state of onboarding of a site. 
To test:
* Go to https://YourJetpackSandbox.com/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=wpcalypso where `YourJetpackSandbox.com` is the domain of your Jetpack sandbox.
* In the JPO flow, fill all the steps in a certain way until you reach the Summary step.
* Hit the `GET` `/jetpack/v4/settings` endpoint and verify the `onboarding` option returns data as expected.
Note: storing business address is currently in progress, so it's not expected to work in this PR - it'll always return an empty array right now.
=> REST API: Introduce onboarding option in GET settings endpoint

modules/search/class.jetpack-search-widget-filters.php
When all post types are selected, we don't send `&post_type=` with all search queries. This caused an undefined index notice:
```
PHP Notice:  Undefined index: post_type[...]
```
This PR fixes that.
I didn't catch this before, because I didn't have ALL post types selected.
To test:
- Ensure `WP_DEBUG` is defined and true
- Add a Jetpack Search widget to a sidebar
- Ensure all post types are selected
- Search for something on the frontend of your site
- Ensure there are no notices
=> Search: Fix undefined index when all searchable post types selected

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search.php, tests/php/modules/search/test_class.jetpack-search-helpers.php
This factors some logic from the `Jetpack_Search` class into the `Jetpack_Search_Helpers` and adds tests. 
This will help keep things DRY as I continue to work on customizer preview in #8552. There shouldn't be any functionality changes here. The existing functionality that we're factoring out is in the `set_filters_from_widgets()` method in `Jetpack_Search`.
To test:
- Setup search widget with several filters and with post types
- Ensure search widget works
=> Search: Refactor logic into Jetpack_Search_Helpers and add tests

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, _inc/lib/widgets.php, class.jetpack-options.php
An alternative approach to #8480  and #8426. 
* adds functions required to inject a Business Address widget or update an existing one,
* saves Business Address data in an option,
* enables widget module if inactive ( throws an error on failure ).
* Follow the instructions https://github.com/Automattic/jetpack/pull/8426 tested on a site with a Business Plan ( or temporarily set `isBusiness` to `true` in main.jsx). 
* To test that it works for the initially inactive `widgets` module: 
use `wp jetpack module deactivate` to deactivate the module and follow the previous instructions. After, verify that the module is listed as active in `wp jetpack module list` and that the widget has been set correctly. 
* Verify that the `jpo_business_address` option is set i.e. using `wp option get …
=> REST API: add functionality for saving Business Address widget in JPO (alternative)

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This PR updates the settings endpoint to contain the business address within the onboarding setting. 
Requires #8523 to have landed first - it takes care of saving the business address in the option that we're using here.
To test right now:
* Checkout #8523 and follow its instructions.
* After you've saved the business address, make a GET request to the `/jetpack/v4/settings` endpoint.
* Verify the business address is returned in the response.
* Delete the option (`wp option delete jpo_business_address` using WP CLI)
* Hit the endpoint again and verify that the business address returned is `false`.
=> REST API: Include business address in the JPO GET endpoint

sync/class.jetpack-sync-sender.php, tests/php/sync/test_class.jetpack-sync-callables.php
This PR prevents the actorless Plugin Updated activity log entry. 
Previously, certain wpcom api requests to Jetpack sites resulted in the syncing of callables without a user set. This code ensures that the user is determined from the token and sent along in the Jetpack sync action.
Update a plugin via Calypso and ensure that you don't have an actorless Plugin Update activity in your activity log.
=> Prevent actorless Plugin Updated activity log entry

tests/php/sync/test_class.jetpack-sync-base.php, tests/php/sync/test_class.jetpack-sync-modules-stats.php, tests/php/sync/test_class.jetpack-sync-sender.php, tests/php/test_class.jetpack-heartbeat.php
Improvements on execution time for the following tests:
test_sends_stats_data_on_heartbeat
test_dont_send_expensive_data_on_heartbeat
test_delays_next_send_if_exceeded_sync_wait_threshold
test_cron_exec
* adds a prefilter to `wp_remote_request` 
phpunit --filter=<your favorite test name>
* Do the test pass. Are they faster than currently?
Thanks for your help @zinigor :)
=> Tests: Try to gain speed on tests execution time

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php, modules/search/css/search-widget-filters-admin-ui.css, modules/search/js/search-widget-filters-admin.js, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8535, Fixes #8536, Fixes #8466
Previously, managing the Jetpack Search filters widget was pretty frustrating via the customizer since the preview didn't work very well. 😞 
The main issue was that when filters were added, we didn't update and redo the query to WPCOM to get update buckets back.
This PR also addresses #8536, which was to start using a comma separated string of post types in the URL instead of using `&post_type[]=post&post_type[]=page`. Normally, I would've addressed this in a separate, smaller PR. But, I noticed that the customizer doesn't play nicely when multiple values are passed like this `&post_type[]=post&post_type[]=page`.
Lastly, this PR also addresses #8466 by not rendering a header for the title when the title is empty.
The only known issue with preview is …
=> Search: After updating the widget, rerun search to get lastest filters

phpunit.xml.dist
The logic behind this is that we check the syntax only on PHP versions that are older than 5.4 to avoid unnecessarily spent time on these tests. It's the same code, so the lowest versions will serve as the lowest common denominator of sorts.
=> Lint PHP files only for older PHP versions.

phpunit.xml.dist, tests/php/bootstrap.php
Now when running phpunit you should see the following enriched output:
```
You should really fix these slow tests (>150ms)...
1. 17859ms to run WP_Test_Jetpack_PHP_Lint:test_php_lint
2. 15209ms to run WP_Test_Jetpack_Heartbeat:test_cron_exec
3. 15177ms to run WP_Test_Jetpack_Sync_Module_Stats:test_dont_send_expensive_data_on_heartbeat
4. 15003ms to run WP_Test_Jetpack_Sync_Module_Stats:test_sends_stats_data_on_heartbeat
5. 9366ms to run WP_Test_Jetpack_Sync_Themes:test_install_edit_delete_theme_sync
6. 8812ms to run WP_Test_Jetpack_Sync_Plugins:test_installing_and_removing_plugin_is_synced
7. 6037ms to run WP_Test_Jetpack_Sync_Sender:test_rate_limit_how_often_sync_runs_with_option
8. 6023ms to run WP_Test_Jetpack_Sync_Sender:test_limits_execution_time_of_do_sync
9. 6006ms to run …
```
=> Tests: Add info about slow tests.

modules/search/css/search-widget-filters-admin-ui.css
Addresses a UI issue raised by @jeffgolenski in https://github.com/Automattic/jetpack/pull/8542
Indents the checkbox for enabling sort controls since it is dependent on the search box being enabled.
=> Indent 'show sort controls' checkbox

_inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Provide API support for users to manage site / blog language from their WordPress.com Site Settings page.
See: https://github.com/Automattic/wp-calypso/issues/11316
* Declare support for `lang_id`
* Prevent modification & return an error code if the client cannot change the setting
* Download language packs if needed & available
* Broker access to the `WPLANG` option
* Run this branch on your connected Jetpack site
* Run the Calypso branch in https://github.com/Automattic/wp-calypso/pull/21482 & follow testing instructions there
Added support for changing site language via WordPress.com
=> Site Settings: Add support for the language setting to the API

modules/search/class.jetpack-search.php
Fixes #8114
We were searching by tag before, but tag is an object with a `tag.name.*` property (in the global index) so we weren't matching any records.
This fixes the issue, when combined with r168666-wpcom
To test:
- tag some content with a unique tag that doesn't match any text, e.g. `customtag1234`
- search by that tag alone
- results should match the tagged posts
- do the same for a category
=> Use tag.name/category.name instead of tag/category for search field

class.jetpack.php
This PR modifies the `is_rewind_enabled` method to only return `true` if rewind is ACTIVE, rather than AVAILABLE as it was for the Pressable release, since all of the migration paths require user intervention/confirmation before migration.  This affects the behavior of "auto-deactivating" VP which was added in #8378. 
p9rlnk-3T-p2
=> Deactivate VP only if Rewind is active

_inc/client/plans/plan-body.jsx
* Show correct information about the updated Premium plan matrix. See https://github.com/Automattic/wp-calypso/pull/21730
* After purchasing a Premium plan in a flow that starts from the plugin, (or visiting `wp-admin/admin.php?page=jetpack#/plans`), verify that it reflects Unlimited video storage and doesn't try to upgrade you for SEO Tools, which it already has.
=> Update Premium plan feature matrix

modules/search/class.jetpack-search-widget-filters.php
Makes the "Why aren't my filters appearing?" link at the bottom of the search filters widget open in a new tab so that you don't navigate away from the customizer in the process. Changes likely wouldn't be lost due to auto-save but this improves the user experience since presumably the user isn't finished with the customizer yet.
Also a minor string change to avoid having to escape a single quote.
=> Search: Open filters help link in filters widget in a new tab to avoid leaving customizer

modules/widgets/gallery.php
jetpack\modules\widgets\gallery.php file use  $widget_tiled_gallery::default_scripts_and_styles(); instead of 
$widget_tiled_gallery->default_scripts_and_styles();
Beacause default_scripts_and_styles() is static.
=> Gallery : use scope operator when we call static function

modules/search/class.jetpack-search-widget-filters.php
Fixes #8597
Some plugins define taxonomies with common names, like "Tag" (I'm looking at you, WooCommerce ;) ). In order to disambiguate these taxonomies in the Jetpack Search widget taxonomy drop-down, we add the taxonomy name (i.e. slug) in parentheses, since this is required to be unique.
Before:
After:
=> Display taxonomy name in parentheses if we detect a duplicate taxonomy label

.github/CODEOWNERS
* Adds @Automattic/jetpack-search team as reviewers to any changes to the Search module.
* Adds @gibrown to any changes to the ES Query Builder library.
Also swaps out `*` for `/` so that files in subdirectories get included too. See https://help.github.com/articles/about-codeowners/#codeowners-syntax
=> Update CODEOWNERS for search

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-widget-filters.php, modules/search/class.jetpack-search.php, modules/search/js/search-widget-filters-admin.js, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8571
This PR adds analytics to the Jetpack Search feature. At the moment, specifically in the widget UI.
I'd still like to figure out a way to track when a widget is added or updated that way we can understand how many widgets are being added to each site, which filters are most used, etc.
To test:
- Checkout branch on a site with a Jetpack Professional plan
- Add a Jetpack Search widget
- Make changes to widget
- Delete widget
- Check and ensure events were logged in tracks
=> Search: Add tracks events

_inc/client/components/connect-button/index.jsx, _inc/client/components/connect-button/style.scss, _inc/client/scss/variables/_colors.scss, class.jetpack-connection-banner.php, scss/organisms/_banners.scss
* This PR updates the looks of the connect buttons to make them jetpack-green.
* It also adds a parameter to the connection URL in the banner buttons, since we are already telling the user that by clicking those button they agree with our ToS, so we don't need to ask again wpcom-side
* Disconnect any of your jetpack sites, and then navigate anywhere where the banner up there is showing. The buttons should be green, and the url they link to should contain "already_approved=true"
ping @joanrho and @MichaelArestad  for design review
=> Update connect buttons in banner

_inc/lib/widgets.php
Fixes: redundant error thrown when updating the Business Address widget.
Currently we update the widget 's content and option containing the Business Address details even if no changes were introduced to the form. `update_option` returns `false` at attempts to update unchanged content resulting in throwing a WP error as an indication of an unsuccessful update. We want to keep an error on unsuccessful update, but do not need to throw it in this scenario.
* adds a check to the updating function of whether the widget's content has changed, prior to updating its instance and option with any new data.
* Follow the instructions on https://github.com/Automattic/jetpack/pull/8426 with a Business site ( or temporarily set `isBusiness` to `true`/remove from the definition of steps in …
=> JPO: skip Business Address widget instance and option update if the content has not changed.

modules/search/class.jetpack-search-widget-filters.php
Fixes #8607
To test:
- Add Jetpack Search Widget
- Try the different variations of Date Histogram filters
- Ensure that all settings save and show on widget after the widget re-renders
Note: Test in the legacy widget UI. The customizer doesn't seem to show the bug unless you do a full refresh.
=> Search: Fix date filter saves in widget

modules/search/class.jetpack-search-helpers.php, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8554
Previously, if the filter wasn't given a name, then we would use the key that had been sent to the API. This key was auto-generated though and looked like `post_type_0`, which isn't too pretty on the front-end.
This PR begins to use some sane default names when users do not supply a name for a given filter.
Note: Currently, the date filters don't seem to be saving properly. I'm tracking this in #8608
To test:
- `phpunit --testsuite=search`
- Checkout on a site with Jetpack Professional
- Add a widget and various filters, and ensure that a default name is set when the filter has no name
=> Search: Add default filter names if widget did not set a name

modules/search/class.jetpack-search-widget-filters.php
As suggested by @Viper007Bond, labels in the taxonomy selector may need to be adapted to each language, so we need to use a translated string and sprintf values into it.
=> Added i18n to search widget admin UI taxonomy selector.

class.jetpack.php, modules/search/class.jetpack-search-widget-filters.php, modules/search/css/search-widget-frontend.css, tools/builder/frontend-css.js
Fixes #8553
Previously, since we were hard-coding in an `h4` and not changing styles, our sub-heading could look out-of-place. This was definitely the case in the TwentySeventeen theme. See #8553 for an example.
To test:
- `yarn build` to build the `jetpack.css`
- Add search widget
- Add various filters
- Try with sorting controls on/off
- Try selecting a filter to see current filters
- test with/without `define( 'SCRIPT_DEBUG', true );` in `wp-config.php`
Some notes:
- I moved the JavaScript we were outputting to the end of the widget
- I also replaced the label for the sort control with an `h4` to match the other sections in the widget
Here are some current screenshots of the TwentySeventeen theme after this PR:
On TwentySixteen:
On …
=> Search: Style sub-heading on front-end of search widget

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-widget-filters.php, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8604 
Alternative to #8605
Testing instructions:
1. In the search filters widget configuration in the customizer, exclude one or more post types.
2. Search for something.
3. Limit results to a particular post type.
4. Limit results by something else so that "Remove All Filters" shows up.
5. Verify that "Remove All Filters" link only contains the search term and the limited post types.
=> Search: Fix remove all filters link when multiple filters selected

modules/sharedaddy/sharedaddy.php
Fixes #8165
* add wp_sharing_email_send_post_subject  for allow modifying the email share Subject Line
*
=> Sharing : Add wp_sharing_email_send_post_subject filter

modules/search/class.jetpack-search-widget-filters.php, modules/search/css/search-widget-filters-admin-ui.css, modules/search/js/search-widget-filters-admin.js
Fixes #8537 
Previously we used a multiple select to allow an admin to restrict a search widget to certain post types. We were given some feedback that a list of checkboxes would be better. This Pr does that.
To test:
- Add Jetpack search widget
- Ensure when "Show search box" is not checked that the list of post type checkboxes does not show
- Ensure when the "Show search box" is checked that the post type checkboxes appear and you are able to select and save post types
- Once selecting post type, perform a search on the frontend and ensure that something like `&post_type=post,page` is added to the URL after entering a value in the widget
- Ensure that tracks events are triggered and are properly recorded
Screenshots:
=> Search: Use checkboxes instead of select for post type selection

modules/shortcodes/mailchimp.php, tests/php/modules/shortcodes/test_class.mailchimp.php
Fixes #8546
* Set window.define.amd to undefined after window.define is set by MailChimp script
* Create a mailchimp popup window widget, and open any page where it should work kick in. It should work, and both window.define and window.require should be null.
* Ideally we would set `window.require` and `window.define` to undefined after using them in MailChimp shortcode, but MailChimp script needs `require` and `define` functions to remain in the global scope. Scripts like jquery will not use `define` if `window.define.amd` is undefined so we can at least do that.
=> Mailchimp Widget: avoid conflicts with jQuery UI

3rd-party/3rd-party.php, 3rd-party/beaverbuilder.php
Fixes #8594 
* Add filter provided by BeaverBuilder which forces a page refresh on save.
* Install BeaverBuilder from https://wordpress.org/plugins/beaver-builder-lite-version/
* Make sure WordPress.com toolbar (masterbar) module is active.
* Edit a page with BeaverBuilder, add a module to the page anything you like.
* Click 'Done', then 'Publish'.
* The 'My Sites' link will now be unclickable.
=> Masterbar: Fix compatibility with BeaverBuilder plugin.

_inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-builder.php, _inc/lib/jetpack-wpes-query-builder/jetpack-wpes-query-parser.php, modules/search/class.jetpack-search.php
Fixes #8590 
- Adjusts what fields we boost on when running our queries (now I really want an all_content field)
- Adds separate groups of fields for boosting on. All of the boosting is very ad-hoc. Needs more data and testing rather than this hand tuned mess
- Fixes a bug where the default search query was not working if the site had a VIP index (requires adding `define( 'JETPACK_SEARCH_VIP_INDEX', true )` as proposed in #8560 )
- Added a filter for adjusting the recency scoring as discussed in #7975 cc @jeherve 
- I looked at adding other filters, but feels like the other parts of the alg are likely to change too much.
- Cleaned up some code, and made some vars and functions protected
@mdbitz @nickdaugherty the VIP index bug was pretty big here. Also, I think we had broken any cases …
=> Search: adjust query boosting, add recency filter, and minor refactoring

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search-widget-filters.php, modules/search/css/search-widget-frontend.css, tests/php/modules/search/test_class.jetpack-search-helpers.php
Alternative to #8540 
This PR begins to use checkboxes for the filters in the hopes that it's a bit clearer to the user which filters are applied and which are not.
As part of this, the active buckets are now displayed in line with other buckets for a given filter. Because of this, the "Current Filters" section is now gone. 👋 🚶 
To test:
- Add a Jetpack search widget with multiple filters
- Ensure all post types are selected
- Select/deselect filter on the frontend and ensure they act as expected
- Go back to widget admin and make sure at least one post type is NOT selected
- Select/deselect filters on the frontend and ensure:
- When you remove a post type filter, or when you click "Remove all filters", that you end up on a URL 
- On …
=> Search: Use checkboxes for frontend filters

modules/search/class.jetpack-search-widget-filters.php
Make 'add another' filter label clearer - it was just "Add" before and I wasn't sure if it meant "add this one" or "add another one of these"
=> Tweak "add" label for search filters

sync/class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-listener.php
If applied this PR will:
- only send IP address to the server during login related events
- allow site administrators to completely opt out of sending IP address
- use `jetpack_protect_get_ip` instead of relying on $_SERVER global
To test:
- try logging in, logging out, and a failed login attempt and ensure IP is sent upstream
- try filtering `jetpack_sync_actor_ip_address` to `false` and ensure IP is not sent upstream
- any other event, writing a post for example, should not send IP upstream regardless of filter
=> Jetpack Sync Actor: only include IP address after running checks

.eslintignore, 3rd-party/3rd-party.php, 3rd-party/debug-bar.php, 3rd-party/debug-bar/class.jetpack-search-debug-bar.php, 3rd-party/debug-bar/debug-bar.css, 3rd-party/debug-bar/debug-bar.js, modules/search/class.jetpack-search.php
Addresses part of #8564
In Progress
This PR is a first pass at adding debug bar support for Jetpack Search.
To test:
- Add a search widget to your sidebar and add filters
- Ensure Debug Bar plugin is not activated
- Run a search on the frontend and ensure that no errors occur in the error log
- Install and activate the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin
- Install and activate [Query Monitor](https://wordpress.org/plugins/query-monitor/)
- Run a query on the front end and ensure you get debug bar output
- Force an error and ensure error information shows up in debug bar. One way I found was to add the following in an integration plugin:
```php
function jp_search_setup_filters() {
if ( class_exists( …
```
=> Search: First pass at debug bar support

modules/search/class.jetpack-search-widget-filters.php, modules/search/js/search-widget-filters-admin.js
Fixes #8616 
A user can not deselect all post types, or else what would we search? But, the way we handled this previously was to validate on the backend and just select all of the posts.
This PR updates the label to to mention that at least one post type is required and then doesn't allow deselecting all post types via JavaScript. As a note, we can't just disabled that last checkbox, because disabled checkboxes don't get sent in the request to save the widget. TIL.
To test:
- Add search widget
- Ensure "Show search box" is toggled on
- Try deselecting all post types
Screenshot:
=> Search: Force at least one post type to be selected

modules/search/class.jetpack-search-widget-filters.php
After walking through Jetpack Search, @kellychoffman pointed out that there were some awkward taxonomies that admins could choose to filter on. For example
- Navigation menus
- Link categories
- Format
The issue is that were calling `get_taxonomies( false, 'objects' )` without an array of args for the first argument. This meant we were getting all taxonomies and not just public ones. 🤦‍♂️ 
After making this change, link categories and navigation menus no longer show up by default. Format does, which makes sense since post formats are public.
To test:
- Add Jetpack Search Widget
- Ensure that non-public taxonomies are not listed
=> Search: Only allow adding filters for public taxonomies

_inc/client/components/jetpack-connect/index.jsx
* Content changes to disconnected landing page
* Should look like this:
=> Bring disconnected landing page in line with new site content

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
This Diff updates the site settings endpoints to allow `posts_per_rss` and `rss_use_excerpt` to be updated and read from the API.
See p3Ex-32f-p2.
Differential Revision: D9173-code
This commit syncs r168133-wpcom.
* Apply this PR to a Jetpack site managed in Calypso
* In Calypso, visit Site-Settings for this site and select "Writing" (https://wordpress.com/settings/writing/)
* A section for "Feed Settings" should appear (it wouldn't have appeared prior to applying this PR).
* Any changes made to feed settings should persist to your site.
=> API: Allow posts_per_rss and rss_use_excerpt to be updated/read from API

_inc/client/components/admin-notices/index.jsx, _inc/jetpack-jitm.js, class.jetpack-jitm.php, class.jetpack.php
This will allow JITM's to load on the Jetpack settings/dashboard page.  It modifies the jitm script to add the JITM to a div within the Jetpack UI, so that it's not rendered ugly above.  
To Test: 
- Test with D9355-code
- Change `JETPACK__WPCOM_JSON_API_HOST` to point to your sandbox
- If the site is connected by an a11n, you should see this notice on the Jetpack admin page. 
- You should also be seeing it in your wp-admin dashboard page.  If you're not seeing it in either places, something else is wrong.
=> Allow rendering of JITM's on Jetpack admin page

package.json
Add `yarn` version to `engines` in `package.json`
---
**Before https://github.com/Automattic/jetpack/pull/8630#issuecomment-361237331 Issue description was:**
Warn about Node or Yarn versions we don't guarantee to work on build/watch. Gives smoother developer experience when Node/Yarn updates happen.
Calypso [uses the same module](https://github.com/Automattic/wp-calypso/blob/c9a6a98cf90a7d0bfea600a2e5663183a9038c65/package.json#L215), although over there it's a bit more important because Node/NPM versions are [locked down precisely](https://github.com/Automattic/wp-calypso/blob/c28274a4214a1eaec3131ddfefbc0cc491303e0c/package.json#L164-L167).
Instead of just warning, this could also exit on failure.
- Add Yarn to `engines` in `package.json` (version from …
=> Build: warn about incompatible yarn version

modules/search/class.jetpack-search-helpers.php, modules/search/class.jetpack-search.php, tests/php/modules/search/test_class.jetpack-search-helpers.php
Fixes #8560
We've changed the maximum values for `size` and `from` in the API, so now we need to apply those changes here.
To test:
- Run `phpunit --testsuite=search`
- Test that search continues to work as expected
=> Search: Update max offset and max posts per page

modules/search/js/search-widget-filters-admin.js
Fixes #8649
In #8649, @gibrown reported an issue where the filter order wasn't updated after changing the order of filters. After looking into it, this seems to be because we weren't firing a change event which the customizer picks up on.
This PR ensures that we fire a change event after moving a filter.
To test:
- Go to customizer
- Add a widget if you don't already have one, with multiple filters, and save
- Reload customizer
- Change the order of the filters
- Publish
- Ensure order changes on the frontend
- Do the same above, this time testing the legacy widgets admin at `$site.com/wp-admin/widgets.php`
=> Search: Emit change event after sorting filters

_inc/lib/class.jetpack-search-performance-logger.php
Fixes an issue recording boom.gif stats - the JSON parser on the other end is pretty finicky so we have to hand-roll our own JSON encoding.
=> Fix stats encoding/decoding for search performance

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Currently we insert a Contact Us form every time the `Add a contact form` tile is clicked in the JPO flow. 
Fixes: adding multiple Contact Us forms.
* Adds a check to not set the form when one already exists.
* Checkout this branch on your JP sandbox,
* Follow the instructions on #8426,
* Skip to the contact form step and select `Add a Contact Form`,
* Check that the contact us page was inserted,
`yourJPsandbox.com/wp-admin/edit.php?post_type=page`
* Go back and add click the tile again
* Confirm that there is only one contact form on your sandbox.
=> JPO: do not add a Contact Us form when one exists already.

_inc/lib/class.core-rest-api-endpoints.php, modules/wordads/php/params.php, modules/wordads/php/widgets.php, modules/wordads/wordads.php
A handful of small updates to bring Jetpack Ads on par w/ .com.
Notably:
1. Default header unit to on.
2. Increment widget unit section ids so they’re unique.
3. Ensure belowpost unit(s) only gets displayed once per page.
**To Test**
1. Enable Jetpack Ads module on a fresh install
1. Check that header unit is defaulted on
1. Enable `Display second ad below post`
1. Check to see that 2nd unit appears below post.
1. Check to see that below post units only appear once in front page.
1. Add two Ads widgets under `Appearance -> Widgets`, check both load.
=> Ads: January Ads Tweaks

modules/stats.php
XHTML compliance requires that attributes not be minimized and this fix was in an earlier version but appears to have been removed or edited for some reason this pull request simply adds back the necessary tags. 
Fixes #8415
=> XHTML Compliance For Stats Script

_inc/client/components/chart/index.jsx, _inc/client/components/chart/x-axis.jsx
Part of #8405
The component code is already removing listeners and cancelling throttled functions on unmounting.
* Removes unnecessary usage of ismounted in the components `chart` and `chart/x-axis`.
* Updates requires for PropTypes to use `prop-types` module in these two components.
* Checkout this branch. 
* Build the admin page
* Visit the Jetpack Dashboard 
* Expect to see the stats charts.
* Expect to see no errors in the dev console.
* Switch to the Settings page and expect to see no errors in the dev console.
=> Admin Page: Remove all usages of this.isMounted

class.jetpack-admin.php
Tested : 
Fix minor changes in class-jetpack-admin.php get_modules().
=> Admin Page : Update static function in get_modules() with use :: operator.

_inc/client/traffic/index.jsx
`commonProps` is passed on to `GoogleAnalytics` component which [expects to have `siteRawUrl`](https://github.com/Automattic/jetpack/blob/537309fd4a530257e4aa6ab5fa104e6496cda995/_inc/client/traffic/google-analytics.jsx#L33-L39).
Without it a link in the component will render with "undefined":
`https://wordpress.com/stats/day/undefined`
Add `siteRawUrl` to `commonProps` object in the Traffic class.
- To see the copy you need **Professional plan**.
- Go to `/wordpress/wp-admin/admin.php?page=jetpack#/traffic`
- Scroll to **Google Analytics**
**Before:** "built-in stats"-link renders with `undefined`.
**After:** link renders with site URL. 👌
=> Traffic: add missing siteRawUrl to props

modules/shortcodes/getty.php, tests/php/modules/shortcodes/test_class.getty.php
This is a merge of changes from WordPress.com related to the new format of markup returned by GettyImages oembed endpoints. D9498-wpcom is the mirror change.
Fixes #8569 
Make sure Getty Images shortcode works as expected in both ways:
* You should be able to insert an embed code from Getty Images;
* You should be able to use a shortcode like this: `[getty src="82278805" width="462" height="370"]`
Both ways should result in an embedded image.
* Updated the Getty Images shortcode to match changes made on their end.
=> Merges changes to the GettyImages shortcode from WordPress.com.

class.jetpack.php
This PR allows active modules to be loaded while onboarding. We need to handle this special case because we might be in a state where we're not connected and not in development mode in the same time, but we still need to load the active modules.
Fixes https://github.com/Automattic/wp-calypso/issues/21930
To test:
1. Create a fresh Jurassic Ninja site.
1. Install JP beta, switch on bleeding edge.
1. SSH into the JN site and apply this branch manually.
1. Go to https://JNsite.com/wp-admin/admin.php?page=jetpack&action=onboard where `JNsite.com` is a fresh Jurassic Ninja site.
1. On the site type step, select Business.
1. On the Business address step, input your business address and submit the step.
1. Go to wp-admin and verify that the contact info widget is active and is properly inserted …
=> Load active modules when onboarding

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This PR fixes https://github.com/Automattic/wp-calypso/issues/21923
To test:
1. Go to https://YourJetpackSandbox.com/wp-admin/admin.php?page=jetpack&action=onboard where `YourJetpackSandbox.com` is the domain of your Jetpack sandbox.
1. For site title and description, use some HTML entities, like single quote or ampersand.
1. During the JPO flow, when asked whether you want a personal or business site, select business.
1. Skip to the Business Address step.
1. For each business address field, use some HTML entities, like single quote or ampersand.
1. Re-run the onboarding flow (step 3).
1. Go through the site title step and the business address step and verify that the special characters appear properly and are not encoded.
=> REST API: Decode special chars in onboarding data

_inc/client/at-a-glance/index.jsx, _inc/client/security/index.jsx
**New! Use the `dev tools` link to mock rewind state for testing!**
Compliments #8581 nicely.  
This PR updates the logic that decides whether or not to hide the backup & scan cards.  The new logic is to NOT hide them if rewind is `available`.  Instead, we show these cards, including the new `<DashActivity />` card: 
To Test: 
- You should see no changes to the UI in any state unless the /rewind endpoint is returning an `active` state. 
- With rewind `active`, you should see the cards in the state shown in the screenshot for ANY level of paid plan.
- With rewind `active`, you should see this as the backup/scan card in `/security` tab:
=> No longer hide backup & scan cards if Rewind is available

class.jetpack.php
The "edit" link on a site's frontend no longer redirects the user to the comments management interface with a predefined action
Fixes https://github.com/Automattic/wp-calypso/issues/21931 for Jetpack
* 
* Force `edit_links_calypso_redirect` option to `true`.
* Logged in as Admin or Editor, navigate to a site's frontend.
* View a post with comments
* click the _Edit_ link.
The link should redirect the user to Calypso's comment management single comment view without a preselected action.
=> Comments: edit link without predefined action

modules/search/js/search-widget-filters-admin.js
In #8637, we changed the `.on` listener for adding a filter here:
https://github.com/Automattic/jetpack/pull/8637/files#diff-937926921eb40702b21d1b8e21d7f3cdL143
But, we didn't remove the `.off` call for that.
To test:
- Add Jetpack Search widget
- Ensure that you can manipulate filters without JS errors
=> Search: Remove unnecessary .off in widget JS after changing classes

class.jetpack.php
This change introduces a filter (`jetpack_active_modules`) that allows theme and plugin developers to modify the list of active Jetpack modules.
For some projects, there will be multiple copies of a site in different environments (e.g. development, QA, staging as well as production) and maintaining consistency across environments is important for quality assurance. Manually enabling/disabling modules across multiple environments is time consuming, inefficient and susceptible to human error. This change allows active modules to be defined in code, under version control, helping to ensure consistency across environments.
=> Modules: Allow filtering of active modules.

modules/search/class.jetpack-search-widget-filters.php, modules/search/js/search-widget-filters-admin.js
Fixes #8667 as well as an issue where filters didn't properly save.
The root issue behind #8667 was that we had removed a `.change()` event which had previously told the legacy widget UI that it was in a "dirty" state. To fix that, we now fire a change event on form fields within the new widget that was added.
There was also an issue where filters were not always properly saving. After looking into this, it was because the filters had an incorrect name. I described some about that here: https://github.com/Automattic/jetpack/pull/8637#issuecomment-361421715
@gravityrail and I paired to nail that down. The root issue was that I had multiple instance of the widget on the page. For example, some were inactive. To fix this, we simply needed to find the template for our specific widget. So, I …
=> Search: Fixes issue where filters did not always properly save

scss/templates/_settings.scss
Removed styles targeting a .vaultpress selector, as per Issue #8266
Fixes #
* Removed styles targeting a .vaultpress selector, as per Issue #8266
*
=> Removed styles targeting a .vaultpress selector

modules/search/class.jetpack-search-widget-filters.php, modules/search/css/search-widget-filters-admin-ui.css
This PR makes a few simple UI tweaks:
- Surrounds the "Add a filter" button with a `<p`> tag to give it some vertical space
- Changes the "Where are my filters?" link to use a `<p>` to give it some vertical space
- Adds a notice to tell users that adding filters requires JS support
- Removes the left padding for the widget notices
Screenshots after:
Screenshots before:
=> Search: Widget minor UI/UX tweaks

_inc/client/at-a-glance/plugins.jsx, _inc/client/components/dash-item/index.jsx, _inc/client/components/dash-item/test/component.js, modules/manage/confirm-admin.php
Fixes #8669
This updates the relevant links to manage your plugins to the correct path.  
To Test: 
- Trigger some plugin update notices by updating the plugin's version manually 
- See the notices in the dashboard card as shown in the linked issue
- Clicking them should take you to the correct path described in the linked issue
=> Update links to point to correct "manage plugin" path

class.jetpack.php, json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php, json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-v1-2-endpoint.php, sync/class.jetpack-sync-module-plugins.php, tests/php/sync/test_class.jetpack-sync-callables.php, tests/php/sync/test_class.jetpack-sync-plugins-updates.php, tests/php/sync/test_class.jetpack-sync-plugins.php
This PR adds test for plugin updates and plugin update failures.
- Fix API for plugin updates so that it returns an error as expected. 
- Adds 
- syncing of plugin updates on success fully plugin update and failure.
- updates the ....wait for it....
* make it so that plugin updates fail ( use a plugin like something below) 
```
<?php
/*
* Plugin Name: Break Plugin Updates
*/
add_filter( 'upgrader_package_options', 'eb_break_plugin_updated' );
function eb_break_plugin_updated( $options ) {
$options['package'] = 'http://example.com';
return $options;
}
```
- try updating a plugin via the api (in calyspo) Do you notice an error? 
- try updating the plugin via the wp-admin interface, plugin.php and core-updates.php UI.
- try updating the plugin via the wp cli interface. …
=> Add: Sync  Plugin Updated event.

modules/search/class.jetpack-search-template-tags.php
After #8655, I noticed that there were some PHP warnings:
```
[30-Jan-2018 21:41:37 UTC] PHP Warning:  array_filter() expects parameter 2 to be a valid callback, class 'Jetpack_Search_Helpers' does not have a method 'is_not_post_type_filter' in wp-content/plugins/jetpack/modules/search/class.jetpack-search-template-tags.php on line 38
[30-Jan-2018 21:41:37 UTC] PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/jetpack/modules/search/class.jetpack-search-helpers.php on line 365
```
The issue was that `is_not_post_type_filter` is a static method on the `Jetpack_Search_Template_Tags` class and not `Jetpack_Search_Helpers`.
To test:
- Add a search widget 
- Do a search
- Ensure there are no PHP warnings
=> Search: Fix PHP warnings introduced in #8655

3rd-party/debug-bar/class.jetpack-search-debug-bar.php
Fixes #8673
I wasn't able to reproduce #8673, so I've decided to be a bit more defensive in how we use `Jetpack_Search`.
1) Only get an instance of `Jetpack_Search` when we're about to render
2) Bail if `Jetpack_Search` does not exist
=> Search: Be more defensive in usage of Jetpack_Search for the debug bar

changelog.txt, readme.txt, to-test.md
* Updates changelog.txt to include 5.7's changelog
* Updates readme.txt with boilerplate for 5.8's changelog.
* Updates Stable tag to 5.7 (please update if there happens to exist a 5.7.1 release)
=> Changelog 5.8: running changelog

.svnignore, Gruntfile.js, composer.json, composer.lock, gulpfile.babel.js, phpcs.xml
This adds PHP_CodeSniffer to Composer along with some initial rules:
* [Rules for core WordPress](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards)
* @sirbrillig's [VariableAnalysis rules](https://github.com/sirbrillig/phpcs-variable-analysis)
* [Rules for ensuring PHP 5.2+ compatibility](https://github.com/wimg/PHPCompatibility)
**These rules are not actually being enforced anywhere**, such as in CI tests, rather this is an attempt to standardize coding rules for the project and to allow for easily enabling of linting in IDEs such as PHPStorm.
TL;DR: This should help us write better code.
=> Add PHP_CodeSniffer to Composer along with some initial rules

modules/search/class.jetpack-search-widget.php, modules/search/js/search-widget-admin.js
Fixes #8676
This change basically uses the same template to render an underscore template (in a script tag) and a PHP template. It passes the $is_template tag to the rendering function, which then renders using `<%= value %>` placeholders instead of `<?php echo esc_attr( $value ); ?>`.
Since we only do two kinds of client-side interpolation in the template (selecting drop-downs and injecting a couple of attr values) this turns out to be the smallest amount of code changed in order to fix this problem.
=> Use same template for rendering server side and client side filters

_inc/lib/tracks/class.tracks-client.php
Blocks sending a tracks event (if Jetpack is not connected) late enough to catch all instances of sending an event.
=> Better checks for active Jetpack in Tracks

3rd-party/debug-bar/class.jetpack-search-debug-bar.php
Fixes a minor issue where the Jetpack Search debug bar styles weren't including in wp-admin. This led to some weird styling like this in wp-admin:
This PR ensures that we enqueue the debug bar styles in wp-admin as well, which makes things look like this:
To test:
- Ensure debug bar or query monitor are installed
- Load wp-admin
- Check that the Jetpack Search debug bar panel looks more like the second screenshot than the first
Note: styles are a tad different with the query monitor plugin. So, the screenshots will not be exact. The big thing to look out for is that the header is not floated and that the "none" is displayed below the header.
Another note: we don't currently use Jetpack Search in the backend. So another approach might …
=> Search: Enqueue debug bar styles in admin

modules/search/class.jetpack-search-widget.php
While testing the beta, I realized that if I attempted a search without a query that the sort selector didn't work.
For example, if you go to `$site.com?s=&orderby=relevance&order=DESC&post_type=post%2Cpage%2Cjetpack-testimonial` with the current master, the sort select won't work.
The issue was that we were short-circuiting the sort selector functionality if there was not a current search query. I can't think of a reason to leave that in, so I went ahead and pulled it out.
I considered not showing the sort selector when there's no query, but decided to leave it in since it's possible for a user to sort oldest to newest in order to see older posts.
To test:
- Ensure Jetpack Search is on and a widget is added to your sidebar with the …
=> Search: Enable the sort selector even if no query

sync/class.jetpack-sync-module-plugins.php
It currentrly isn't even possible to reach this part of the code beacuse a failed intall event never calls the `upgrader_process_complete` do action.
Removing this event is find becasue we only included it very recently in https://github.com/Automattic/jetpack/pull/8654 and it never made it into a Jetpack version except master.
=> Sync: Remove newly added plugin install failed event

_inc/client/components/text-input/index.jsx
ClipboardButtonInput was forwarding non-standar attributes to the input element (like `isError`, `isValid`, etc).
* Updates clipboard-button-input to not forward own props.
1. Check this branch
2. Build the admin page
3. Visit the Settings page and confirm you don't see a warning like:
```
Warning: Unknown props `selectOnFocus`, `isError`, `isValid` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```
=> Admin Page: Remove invalid props forwarded from ClipboardButtonInput to input element

_inc/client/components/modal/index.jsx
* Removes `onRequestClose` prop from the list of attributes forward to the div created by the `Modal` component
* check this branch
* build the admin page
* Visit the Jetpack dashboard
* Click the "Manage site connection" link
* Expect to see a modal/popup and no warnings like the following in the console:
```
Warning: Unknown prop `onRequestClose` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```
=> Admin Page: Omit onRequestClose prop from attributes forwarded to div element in modal component

_inc/client/components/gridicon/index.jsx, _inc/client/components/jetpack-dialogue/index.jsx, _inc/client/components/jetpack-dialogue/style.scss
Fixes #7904
* Clicking the background or pressing the ESC key should close full screen dialogs
* Move close button into the dialog body.
* Trigger a full-screen dialog. This code snippet in a micro-plugin will do the trick for forcing an upgrade prompt on any of the Jetpack dash/settings pages:
```php
Jetpack::state( 'message', 'modules_activated' );
});
```
* Click the background, the dialog should be closed
* Click the foreground (main part of dialog or picture above it) - the dialog should NOT be closed
* Re-open the dialog (e.g. by re-loading). Hit the ESC key. The dialog should be closed.
This also moves the close button into the top-right corner of the dialog, and includes an updated gridicons file which includes the circular close icon. …
=> Enable ESC and clicking background to close full screen dialog

_inc/client/components/jetpack-dialogue/style.scss, _inc/client/components/upgrade-notice-content/index.jsx
A suggestion from @beaulebens, it's handy for users to be able to enable a new feature when we add a UI for it. 
So I added the module toggle right into the upgrade notice.
* Upgrade Jetpack, or force showing the upgrade prompt by using the following micro-plugin:
```php
Jetpack::state( 'message', 'modules_activated' );
});
```
* Use the toggle in the screen to enable Lazy Images
* Close the prompt and confirm that Lazy Images is enabled in the Jetpack settings and that images on the front-end are being lazy loaded (i.e. they have the `data-lazy-loaded="1"` attribute)
Allow enabling new features from upgrade screen
=> Allow enabling lazy images from the upgrade screen

_inc/client/components/button/style.scss
Fixes #8688
* Remove :visited rule from .dops-button which sets inner text to gray
* In Chrome debugger, set state of a dops-button to :visited. Text should stay white.
=> Remove :visited rule from dops-button

modules/search/class.jetpack-search-widget.php
@rachelmcr reported a bug with how the sort controls checkbox is disabled or not:
@gibrown asks:
> The sort selection dropdown checkbox should be disabled when “show search box” is unchecked. Was that not the case?
@rachelmcr responds:
> Nope, that wasn’t the case for me. I tried again, watching more closely, and I see now what’s happening:
>
> When I first add the widget, the sort selection checkbox is disabled when “show search box” is unchecked.
>
>After I save the widget settings (either under Appearance > Widgets or in the customizer) even if “show search box” is unchecked the sort selection checkbox is enabled.
>
>If I check and then uncheck “show search box,” the sort selection checkbox is disabled again.
At first I was not able to reproduce with my existing widget. But, once I …
=>  Search: Disable widget sorting control if search box not checked

modules/search/class.jetpack-search-widget.php, modules/search/css/search-widget-frontend.css
While working on #8689, we realized that there was another issue where the search query wasn't set in the search input for some themes. This would result in the query not being set when changing the sort.
For example, in the ColorMag theme, the search input looks a bit like this:
```html
<input name="s" placeholder="Search" />
```
But, since it doesn't have the `value=""` attribute, it'll never persist the search query for subsequent searches.
To fix this, I decided to always set the search query in the input with JavaScript. One alternative approach was to run a regex over the HTML for the search form, but I'd rather not go that route for the moment. 
The biggest issue I could think of with this JavaScript approach is that there could be flash of the placeholder text until the document …
=>  Search: Ensure that the search query is set in the widget search box

_inc/client/components/jetpack-banner/index.jsx
So we don't get warnings about a boolean value for a string prop-type… a boolean value for a string prop-type
Fixes #8725
* Updates the default value of `plan` to be `''` instead of `false` in JetpackBanner component.
* Visit the Traffic tab
* Use the DevTools at the bottom of the page to emulate a **secondary admin**, that is **unlinked**:
* Expect to see no error in the console mentioning an invalid boolean value
=> Admin Page: Jetpack Banner - Make plan default to empty string instead of false

modules/search/css/search-widget-frontend.css
Fixes a visual issue on the Hemingway theme which would affect others that set height on input controls.
Before:
After:
=> Fix Hemingway checkbox height in search filters

modules/search/class.jetpack-search-widget.php
Fixes #8724
* Add a wrapper div with a unique ID, so that our JS which updates the search form works with themes that don't output the widget ID into the before_widget HTML.
* Install and activate the Hemingway theme
* Add a widget to any widget area with a search box and sorting controls 
* Do a search
* Changing the sort dropdown value should reload the search results with the new sort order
=> Add wrapper div for more reliable targeting of search form

_inc/client/traffic/index.jsx
Currently when you type "Search" into the search UI of the Jetpack Settings, the actual "Search" _module_ is way down the list, below modules of dubious relevance like SItemaps.
Given the simplistic nature of our feature search (just lists matching modules in their current UI order), this change hacks Search into the top spot by moving it closer to the top of the Traffic tab, right below stats.
* Search for "Search" in Jetpack Settings
* Should be at top of list.
New Search results:
Reordered UI in Traffic tab:
=> Move 'Search' to top of a Search for Search

_inc/client/writing/post-by-email.jsx
Fixes a warning being shown in the console for development builds of the admin page, due to a `null` value forward as an attribute of an `input` tag when everything is enabled, but the user hasn't generated an address yet.
* Updates the `PostByEmail` component `address()` method to return `''` if there's a value of `null` currently.
* Start with a fresh site.
* Build the admin page.
* Activate recommended features.
* Visit the Settings page
* Confirm there's now warning about an `<input>` receiving a value of `null`.
=> Admin Page: Post By Email Address - Handle null value properly

modules/lazy-images.php, modules/module-headings.php
For the Jetpack 5.8 release, our marketing is going to be using the phrase "Lazy load images".
See: p9mQOq-hy-ps
This PR updates the module description to match what marketing is using.
@ballio2000 said these changes are important, so I've added the blocker label.
Screenshot:
=> Lazy Images: Update module description to match marketing

modules/search/class.jetpack-search-widget.php, modules/search/css/search-widget-frontend.css
Fixes #8690 
We currently put the label for the sort control in a `<h4>` right above it, similar to the headings for filter sections.
As per @gibrown 's suggestion, this PR turns it into a less obtrusive inline label.
(theme pictured is Hemingway)
By adopting this HTML structure, I also feel like it's a little closer to how forms are typically rendered (including the form elements in our widget admin area)
=> Inline label with search widget sort control

_inc/client/state/settings/actions.js
Helps debugging issues when users see vague messages like: 
`Error updating settings. (Error)`
We're currently handling some errors that come from rogue web server setups (404 status, or 404 after a redirection) and also problems with JSON parsing (In case the REST API is redirected or turned off for the site). 
But we have a bunch of custom messages (already translated) that come from the API related to possible problems around Jetpack innerworkings. This PR adds more support for them.
* Tries to show `error.message` or `error.code` (provided by the WP REST API response when creafted based on an `WP_Error`) before falling back to `error.code` or `error` (which are custom JS errors we implement to detect network errors..
* build the admin page
* Add this minor change …
=> Admin page: Better error message in notice when the error is a WP_Error coming from the API

_inc/client/components/settings-group/style.scss, _inc/client/traffic/search.jsx
Fixes #8712
Use correct widget name in settings panel.
Also adds an underline to link styles in the "settings explanation" panels, since it was hard to distinguish links from non-linked text.
=> Use correct widget name in Search setting explanation

modules/lazy-images/lazy-images.php, tests/php/modules/lazy-images/test_class.lazy-images.php
Fixes #8490
In #8490, @StefMattana reported an issue where featured images weren't working for a theme. After looking into it, the issue was that our "lazy" attributes were being filtered out by `wp_kses_post()`. 😱 
This meant that the src was getting swapped to the transparent GIF, but then we had no record in the HTML of what the src should be. Further, the JS didn't even know which images were lazy loaded since they didn't have the `data-lazy-src` attribute that the JavaScript looks for.
This PR ensures that our lazy attributes are allowed for images.
To test:
- Check out branch
- Ensure lazy images is enabled
- Run tests `phpunit --testsuite=lazy-images`
- Note that there's a test there without any assertions... Let's fix that in a follow-up PR
- Install the Apostrophe 2 theme and …
=> Lazy Images: Ensure lazy image attributes are not filtered out

modules/search/css/search-widget-frontend.css
Fixes themes that set a width to inputs, such as Zerif Lite.
**Before:**
**After:**
See #8742
=> Search: Force checkboxes in the search width to have normal width.

modules/search/css/search-widget-frontend.css
Twenty Ten hides labels in the search widget: https://core.trac.wordpress.org/browser/tags/4.9.2/src/wp-content/themes/twentyten/style.css#L1154
This forces them to be shown within our search widget.
**Before:**
**After:**
See #8742.
=> Search: Force labels to be shown in widget. Fixes Twenty Ten.

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This PR updates the settings save endpoint to allow onboarding requests to contain an empty site description. It seems that right now we were specifically allowing only non-empty site descriptions, and empty descriptions are also a valid case.
Fixes part of https://github.com/Automattic/wp-calypso/issues/21868
To test:
* Make sure the site already has a tagline.
* Start the onboarding flow
* Empty the site description field.
* Click the save button.
* Verify the site description is properly updated to an empty string in the remote site.
=> REST API: Allow empty site description in onboarding requests

_inc/client/components/settings-card/index.jsx
The work started in #8584 did not address the upsells/setting links in the SEO Tools and Google Analytics cards for Premium Plans.
Load Jetpack's settings page in wp-admin for a site with a Premium plan, go to the **Traffic** section. Without this branch, you will see:
With this branch, you should see:
=> Don't show upsells for SEO and Google Analytics for Premium Plans

_inc/client/at-a-glance/index.jsx
Avoids a warning being thrown when visiting the Jetpack dashboard as an Editor or Subscriber
* Updates the check for ability to manage modules that results in a boolean attribute passed if user can't manage modules.
* check this branch
* build the admin page
* Visit the Jetpack dashboard.
* Using the Dev Tools at the bottom of the page, switch roles to `Editor`.
* Expect to see no warning being thrown in the console about `Invalid prop `settingsPath` of type `boolean` supplied to `DashSectionHeader`
=> Admin Page: Fix settingsPath prop passed to DashSectionHeader from Main component

_inc/jetpack-jitm.js, class.jetpack-jitm.php
This PR introduces a `redirect` parameter in the URL of a JITM pointed to the current screen URL where the JITM was displayed.
This is handled in D9909-code to apply it to Rewind JITMs and sent to Calypso as `rewind-redirect`. This query param triggers the flow to activate Rewind.
- use this PR with D9909-code and https://github.com/Automattic/wp-calypso/pull/22141
- check the WP Admin of a site that doesn't have Rewind active (but available). It should show a JITM. When clicked, it should go to Calypso and display the Rewind activation flow
=> Rewind: when displaying a JITM for Rewind, add a redirect parameter

.travis.yml, tests/php/sync/test_class.jetpack-sync-plugins-updates.php, tests/php/test_class.jetpack-client-server.php
With more and more people moving to 7.2 we need to introduce automated testing.
=> Adding PHP 7.2 testing with Travis.

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
Support for setting the site's language was added in #8568.
`wp_download_language_pack` & supporting functionality were previously defined in the context of the Site Settings API call.
That changed in [core](https://core.trac.wordpress.org/changeset/42606/trunk/src/wp-includes/capabilities.php) ([see also](https://core.trac.wordpress.org/ticket/42697
)) and now calls to change the language setting cause fatal errors.
This sources the files needed to continue calling `wp_download_language_pack`
* Source required files in `wp-admin/includes` if `wp_download_language_pack` & `request_filesystem_credentials` are not defined.
* Apply this branch to your **connected** test site
* Run calypso at the version just prior to the language setting getting disabled:
* `git checkout 1a0bad3550`
* Visit …
=> Site Settings: Source supporting files for changing the language setting

_inc/client/writing/speed-up-site.jsx
This allows the setting UI to hide Lazy Images individually when they are filtered out, plus properly display search results.
Fixes #8778. 
* Fixed Lazy Images setting display in Settings for search results and special cases like filter usage.
* Try to filter out lazy images as a module using this snippet:
```
add_filter( 'jetpack_get_available_modules', function( $active ) {
return array_diff_key( $active, array( 'lazy-images' => 'Does not matter' ) );
} );
```
* Make sure you don't see the module at all when you open the Writing tab, or search for something like `lazy`.
=> Properly handle display of Lazy Images setting.

tests/php/modules/lazy-images/test_class.lazy-images.php
Previously, there was a test that was being marked as risky because it didn't perform an assertion. Ooops.
This PR fixes that by updating the the test so it makes an assertion as well as updating the expected HTML value.
To test:
- Run tests: `phpunit --testsuite=lazy-images`
=> Lazy Images: Fixes test that had no assertion

docs/partners/plan-provisioning.md
We currently send the following documentation to hosting partners when to explain the technical bits of provisioning plans via a PDF. This works, but has a few issues:
- We have to manually send this file
- If we update the documentation, we then have to send the file again
- If we have update, even if we send the updated documentation, the host may continue to use the outdated documentation
Putting this documentation into the Jetpack repository itself allows partners to easily find the documentation and to view the most up-to-date version of the documentation.
=> Docs: Partners: Add JPS provisioning/cancelling doc

docs/partners/managing-modules.md
Our partners have occasionally requested the ability to manage modules. We currently support this functionality via a couple of filters, but it's not widely known. Creating this document in the `docs/partners` directory will make the information more discoverable for partners.
As a note, while creating this documentation, it became apparent that while we support forcing a module on/off, we do not properly handle this in the UI. I've created #8800 to address this.
We intend on adding more partner documentation into this `docs/partners` directory in the future. This will allow partners to easily access the documentation as well as view updates without us having to manually export a PDF and send it to the partners.
cc @gravityrail @jessefriedman @griersongithub @nicoleckohler
=> Docs: Add partner docs directory; Add module management doc

.circleci/config.yml
Relies on https://github.com/Automattic/wp-e2e-tests/pull/911
* Use Jurassic.ninja as platform for e2e tests
* Get rid of `destroy` step which was dependant on `test` step and was not always successful
* re-run CircleCI job: https://circleci.com/gh/Automattic/workflows/jetpack/tree/master
=> Switch e2e tests to Jurassic.Ninja infrastructure

sync/class.jetpack-sync-defaults.php
* Don't sync sitemap post types. They are huge, transient, and computed from other information.
=> Add sitemap post types to sync blacklist

modules/lazy-images/lazy-images.php, tests/php/modules/lazy-images/test_class.lazy-images.php
Closes #8785
Closes #8641 
In #8641, a user requests the ability to skip processing images with a given class.
In #8745, a user reports a compatibility issue with another plugin where we shouldn't be processing an image so that it's lazy. After looking at the plugin's code, I don't see any specific classes that we can hook on. 
These two issues go pretty well together. :smile:
This PR will begin skipping images where the `skip-lazy` class is applied. Further, a user can filter `jetpack_lazy_images_blacklisted_classes` to add or remove classes to the list of classes that we'll skip.
I've also added a filter that will allow skipping an image via its attributes. The `jetpack_lazy_images_skip_image_with_atttributes` receives an array of the current image's attributes as its second argument. …
=> Lazy Images: Allow filtering out images via class and attributes

bin/partner-cancel.sh, bin/partner-provision.sh, class.jetpack-cli.php
While debugging plan provisions and cancellations, I've noticed that users will often create various clones of sites and will move a domain name around those sites.
This sometimes results in the plan for a given site being cancelled when it probably shouldn't.
We have logs in place on WordPress.com to track when a partner provisions or cancels a plan, but it sure would be nice if we could tell exactly which site the partner intended on provisioning or cancelling the plan for. After this PR, hosts will be allowed to pass in a `--host_tracking_id` argument which will help in debugging.
To test:
For instructions on setting up a partner ID and secret, see: PCYsg-eDL-p2
- Use the following command, replacing partner the arguments :
- `sh jetpack/bin/partner-provision.sh …
=> Jetpack Start: Allow hosts to pass a tracking ID when provisioning or cancelling a plan

class.jetpack-cli.php, docs/partners/plan-provisioning.md
After sending the plan provisioning documentation to one of our hosting partners, there was some confusion over the `--user-id` parameter. Our partner thought that this might be the ID of the WordPress.com user, which then led them down the path of looking into oAuth and querying us for support.
Since we didn't clarify which user ID we were looking for, this was a very understandable interpretation. 
To minimize frustration on our hosting partners and to ease the integration process in the future, I've made a few changes that should help clarify which ID we want as well as provide an example for how to get the ID if the host only has an email address.
=> Docs: Clarify that user ID for partner plan provisioning is from remote install

sync/class.jetpack-sync-module-posts.php
Fixes #8137
Fixes #7156
*  In this file directly call $post->post_type so it given error. If We update the code so we overcome the problem.
*
=> Sync: Fix Trying to get property of non-object in sync/class.jetpack-sync-module-posts.php

.circleci/config.yml
* Using encrypted config file instead of bare NODE_CONFIG env variable for E2E tests
Make sure that CircleCI build is passing:
https://circleci.com/gh/Automattic/jetpack/tree/try%2Fuse-e2e-encrypted-config
=> Use encrypted config for E2E tests

_inc/lib/class.core-rest-api-endpoints.php
* This adds a local endpoint to get the current plans available. Works with D10122-code
* Apply D10122-code
* hit `/jetpack/v4/plans` from the api explorer while logged in (using the plugin found at https://wordpress.org/plugins/rest-api-console/)
You will get back an api response that contains a localized list of plans in the correct currency for your location.
=> Plans In Plugin: Add plans endpoint

modules/wordads/php/widgets.php
Part of #8156.
Fixes https://wordpress.org/support/topic/deprecated-function-create_function-2/
* Introduces function `jetpack_wordads_widgets_init_callback `.
* Replaces usage of `create_function` for `jetpack_wordads_widgets_init_callback` as `widgets_init` callback.
*
=> WordAds: Avoid usage of create_function

json-endpoints/class.wpcom-json-api-list-comments-endpoint.php
Trying to treat a string like an array results in a fatal error in PHP 7.2
Fixes #
* Fix a fatal error under PHP 7.2
* Calling sites/X/posts/Y/replies triggers a fatal error condition under PHP 7.2.
Make sure that $output is an array before treating it as an array.  Trying to treat a string like an array results in a fatal error in PHP 7.2.
=> Make sure that $output is an array before treating it as an array

3rd-party/beaverbuilder.php
Fixes #8851 
Simply changing classname.
=> Rename class to fix a theme clash.

_inc/client/traffic/search.jsx
Make the "Add Jetpack Search Widget" link in the Search module settings card open the widgets section of the customizer.
Go to Jetpack → Settings → Traffic and enable the Search module. Click on "Add Jetpack Search Widget" and verify that the widgets section of the Customizer opens once it fully loads (it'll take a moment).
=> Settings: Auto-focus the widgets panel in the Customizer for Search module

sync/class.jetpack-sync-listener.php
Fixes #
* I'd like to add an action hook to `enqueue_action` when anything on the whitelist gets sent to the queue to sync.
* Hook onto it via `add_action`.
=> Sync: Add action hook to enqueue_action

Gruntfile.js, gulpfile.babel.js, package.json, webpack.config.js
Follow up for #8861 since we now [require](https://github.com/Automattic/jetpack/blob/master/package.json#L150) Node.js 8, this should be safe.
1. Fix with eslint:
```
npx eslint *.js -c .eslintrc --fix
```
2. Manually fixing these warnings:
```
Gruntfile.js
4:6  error    'path' is assigned a value but never used        no-unused-vars
4:6  warning  'path' is never reassigned. Use 'const' instead  prefer-const
5:3  warning  'cfg' is never reassigned. Use 'const' instead   prefer-const
webpack.config.js
5:7  error  'fs' is assigned a value but never used             no-unused-vars
9:7  error  'IS_HOT_UPDATE' is assigned a value but never used  no-unused-vars
78:2  error  Mixed spaces and tabs                               no-mixed-spaces-and-tabs
79:2  error  Mixed spaces and tabs …
```
=> Build: eslint --fix build files

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This PR adds support for enabling stats through JPO - preparatory work for https://github.com/Automattic/wp-calypso/issues/22532. 
The PR introduces:
* A new boolean `stats` parameter for JPO saving POST endpoint - when enabled, will try to enable the stats module. Requires connection.
* A new boolean `stats` field to return in the GET endpoint, which will return `true` if the stats module is enabled and the site is connected; false in all other cases.
To test: 
* Load local Calypso.
* Checkout this branch on a fresh Jetpack site.
* Start the onboarding flow (`/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=development`)
* In your console, enter `dispatch( { type: 'JETPACK_ONBOARDING_SETTINGS_REQUEST', siteId: 12345678 } )`, where `12345678` is the ID of your site.
* Verify …
=> REST API: Add support for stats module in JPO endpoints

_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
This PR introduces a `country` field to the business address step of the Jetpack Onboarding flow. See https://github.com/Automattic/wp-calypso/issues/22530 for context.
To test:
Use the test instructions of https://github.com/Automattic/wp-calypso/pull/22580.
=> REST API: Add Country field to Business Address onboarding step

class.jetpack-connection-banner.php, class.jetpack.php
`already_authorized` is a connection URL param that lets a connecting customer know they've already connected the site.
`auth_approved` is a connection URL param that let's a connecting customer skip
the screen that shows the terms-of-service-acceptance button.
In #8544 we meant to use `auth_approved`
Fixes #8783 
To reproduce:
On an unconnected jetpack site, try connecting from the banner on the plugins page. Not that you get an odd "Already connected..." error when you land on wordpress.com
Then apply this patch to your jetpack site, and try again from the banner on the plugins page. You will not see the error, and you should skip the terms-of-service-acceptence and be auto authorized.
=> Jetpack Connect URL: use correct URL to auto-approve

modules/protect.php, sync/class.jetpack-sync-module-protect.php, tests/php/sync/test_class.jetpack-sync-module-protect.php
An activity for failed login attempt should look like:
>[user_login] had a failed login attempt from IP Address: 123.123.123.123
But it currently looks like :
This adds user login we can then show in Calypso.
- Send `user_login` (_username_ or _email_) used in a failed login attempt.
- Removes IP from `args` since it's [already being sent](https://github.com/Automattic/jetpack/blob/dd45834afcac620eb9048960b2676499f1a00602/sync/class.jetpack-sync-listener.php#L264-L268) in `author` object.
Should I be worrying about backwards compatibility for `jpp_log_failed_attempt `action?
In the new version, it'll send an array containing `login_user` instead of a string containing IP.
Before:
https://github.com/Automattic/jetpack/blob/1db8bc30853208b57c988d726f45fd4f2cb926c2/modules/protect.php#L272-L2 …
=> Activity log: add user-login to failed login attempts

modules/masterbar/masterbar.php
This is a proposal so it can be tested with the Jetpack Beta Plugin when the PR finishes being unit-tested by Travis.
Context: p1HpG7-4Fe-p2
* Adds a filter `jetpack_masterbar_should_logout_from_wpcom` defaulting to `false`. 
* Make the value be filtered to true for AT sites.
* Start by being signed in to WordPress.com (non-proxied).
* Then, on a connected Jetpack site...
* Install the [Jetpack Beta Tester Plugin](https://github.com/Automattic/jetpack-beta)
* Select this PR ( #8243 ).
* Enable the Masterbar from the Jetpack Settings Page..
* Sign out from the Masterbar.
* Go back to WordPress.com.
* Expect to be logged in.
Repeat steps on an AT site but expect to be logged out from WordPress.com in the end.
* Start by being signed in to WordPress.com (non-proxied).
* Then, on an AT …
=> Masterbar: Proposal - Do not sign out by default from wpcom when clicking the Sign out link

docs/partners/plan-provisioning-direct-api.md
JPS v1 required hosting partners perform a lot of integration work setting up oAuth and then integrating in our APIs. We tried to simplify this as much as possible in JPS v2 by shipping two shell scripts that handle provisioning and cancellation of plans.
But, there are cases where a host may actually want to call the API instead of running a CLI command. For example, what if the site is already gone by the time the CLI command can be run?
It's currently pretty straightforward to cancel a plan by making calls directly to the API. A hosting partner simply needs to get an access token then call the cancellation endpoint, passing the domain and access token. That process is what is documented in this PR.
Provisioning a plan via calls directly to the API is much less straightforward. …
=> Docs: Partner: First pass at documenting endpoints

_inc/client/components/banner/index.jsx
Removes unnecessary statements that wrapped the default export with a call to `connect()`.
* exports the component without using the `connect()` HoC.
* Check this branch.
* Confirm the admin  page builds `yarn build`.
=> Admin Page: Remove unnecessary wrapping with connect from Banner component

tests/install-php-phpunit.sh, tests/php/sync/anonymous_function_test_for_register_post_types_callback_error.php, tests/php/sync/test_class.jetpack-sync-callables.php
Fixes #8458
The PHP 5.2 job was failing due to static analysis of this test file even when the test was marked as skipped for PHP >= 5.4.
* Replaces a current test code for one that includes a file that will define an anonymouns function for testing when PHP >= 5.4.
* Updates the way we install the yaml dependency for phpunit.
* Checking that the tests run by Travis in this PR pass is a good way to test. Otherwise setting all of the environments locally is complicated.
* Particularly, confirm that the job for PHP 5.2 (The last one in the list and currently allowed to fail) passes the tests.
=> Sync: Refactor test so it's able to pass on PHP 5.2

.travis.yml
Depends on #8790.
* Removes PHP 5.2 runner from Travis allowed failures in `.travis.yml`.
* Either set up a php 5.2 installation, have wordpress source code at hand, configure the testing db, install phpunit and run all the test confirming that they pass or...
* ...check if Travis says this PR is good to go as it runs the PHP 5.2 job blocking this PR from getting merged if tests don't pass.
=> Unit tests: Remove PHP 5.2 from travis allowed failures

modules/module-extras.php, modules/module-info.php, modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php, modules/woocommerce-analytics/classes/wp-woocommerce-analytics-utils.php, modules/woocommerce-analytics/wp-woocommerce-analytics.php
New module with WooCommerce analytics ported from the recent Google Analytics enhancements. 
* support for add-to-cart events
* support for product detail views
* support for remove from cart events
* support checkout events
* support for order-received events
* Use a test site which is connected with Jetpack and has WooCommerce active
* As a logged out user, notice a request to  `https://stats.wp.com/s-20180821.js` on public facing pages. The `20180821` is dynamic and will change based on date
* Notice `https://stats.wp.com/s-20180821.js` is not requested on `wp-admin` pages because this code should not run on admin facing pages. The same for logged in admin users.
* Back to user facing pages, open the console and see `_wca` global exists and is an ~array~ object. 
* Go to a product page …
=> New module for WooCommerce analytics

modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php
Fixes #8898 
* Brings the `s.js` cache busting inline with `e.js` to reduce http requests for the analytics library
* Open Network, reload a product page and you should see a `s.js` file with a YW format like `s-201808.js`
=> change from daily cache busting to weekly - inline with e.js

package.json
Doesn't look like we need to build the client before linting and this renders the `yarn lint` command useless if wanting to use it locally for fast linting.
* Removes the command `yarn build` from the npm script `yarn lint`
* run `yarn lint` and check that you get `eslint` run.
* If an error happens, you may have to run `yarn` before to install dependencies
=> Scripts: remove `yarn build` command from lint script

sync/class.jetpack-sync-module-woocommerce.php
Background: p7rcWF-IV-p2
Currently there seem to be some 3rd party Woo integrations of the drop-ship variety that perform massive product/inventory updates on JP-connected sites, which result in thousands of objects being synced.
I have searched both the wpcom and calypso codebases and currently it doesn't look like we are using the `_stock` and `_stock_status` meta on the shadow site at all, so this PR removes both items from the `$wc_post_meta_whitelist`.
I opted to comment out with "skip" akin to other values in this file to show that we acknowledge the meta exists, but are purposely choosing to not have it trigger a sync.
/cc @nabsul just to verify that you aren't using these values in any of your queries
=> Sync: Remove Woo _stock* meta from whitelist

modules/lazy-images/js/lazy-images.js
Fixes #8821
When we first worked on Lazy Images, we were using the W3TC IntersectionObserver polyfill, but near the end, we moved to another polyfill because the W3TC version had conflicting licenses. Specifically, in one case they were using an Apache 2.0 license which isn't GPL compatible. You can see more discussion about that in #8093.
As of https://github.com/w3c/IntersectionObserver/commit/4a9a908f88f6d38be068b9dd523f86d281c5398b and https://github.com/w3c/IntersectionObserver/commit/b025731ab0f4bdbd444ad1b0917b8d5991774548, they have updated their licenses to "W3C SOFTWARE AND DOCUMENT NOTICE AND LICENSE", which is GPL compatible!
Since this is the one being worked on by W3C, I imagine that it's the most up-to-date and well tested. Using this polyfill fixes the Twitter embed issue …
=> Lazy Images: Use W3C IntersectionObserver polyfill

docs/partners/README.md, docs/partners/managing-modules.md, docs/partners/plan-provisioning-direct-api.md, docs/partners/plan-provisioning.md
In #8801 and #8804 I'm proposing that we add partner documentation directly to the Jetpack repo. With our documentation going public, it seems like a waster opportunity if we don't try to reach out to interested hosts.
Creating this `README.md` file means that any time someone is browsing the Jetpack repo and they visit the `/docs/partners` directory, that they will see this file below the list of of other partner documentation.
As I added the READM.me file, it seemed like that was the best place to add mine and Dan's contact information. So, I put it there and referenced the README.md in other files.
=> Docs: Add README.md for docs/partners directory

_inc/lib/class.jetpack-search-performance-logger.php
Fixes #8926
* Only log mysql and ES query times that are less than 60 seconds. There are some outliers that mess up our stats.
* Open the browser's debugger tools
* Disable Search
* Run search queries, ?s=foo
* Check that your network requests include a request like `https://pixel.wp.com/boom.gif?(stuff)jetpack.search.mysql(stuff)`
* Do the same with Search enabled, and check that it logs with `jetpack.search.es` instead of `jetpack.search.mysql`
If you want to see if logging happens over the query limit, you might need to throttle your connection to public-api.wordpress.com and your local MySQL server. Instructions on how to do so are system-specific, so up to the tester.
=> Remove outliers for mysql and ES query times

class.jetpack-client-server.php
This PR suggests that we delete the JPO token after a successful connection.
Part of the solution for https://github.com/Automattic/wp-calypso/issues/21680. You can use in conjunction with https://github.com/Automattic/wp-calypso/pull/22763 if you want
To test:
* Start a fresh JN site with this branch on it (you can do that by loading https://jurassic.ninja/create?jetpack-beta&branch=update/delete-jpo-token-after-connecting)
* Make sure you are logged into WP.com and the Jetpack site.
* Start the onboarding flow by going to `/wp-admin/admin.php?page=jetpack&action=onboard` and get redirected to the site title step in Calypso
* Open a ssh session for the Jetpack site and verify a `wp option get jetpack_onboarding` returns the token.
* Go to https://wordpress.com/jetpack/connect/ and …
=> JPO: Delete onboarding token after connecting the site

_inc/lib/class.core-rest-api-endpoints.php
Follows on from #8834 
* use the correct `$_SERVER` var from the client so that the wpcom plans endpoint can guess the client's locale and localize the currencty
* correctly bypass caching when the `jetpack_cache_plans` filter returns false
=> Plans in Plugin: correctly forward the client IP for currency localization

class.jetpack-debugger.php
Updates the category options on the in-plugin debugger. A matching change has already been committed to a8c/jetpackme-new theme on wp.com (r11470).
=> Debugger: Update debug contact form category options

modules/search/class.jetpack-search.php
Fixes #8929
Due to #8822, having the search widget active will enable the search module. This makes it impossible to disable the module while the widget is in use.
This change moves any active search widgets to the inactive list if you disable the search module.
1. Add the Jetpack Search widget to your sidebar. Ideally give it a custom title so you can more easily track it.
2. Disable the search module.
3. Refresh the page and verify that the search module is still disabled.
4. Visit the widgets configuration page and make sure that the widget you added in step one is now listed at the top of the inactive widgets list.
=> Search: When disabling the search module, move any active search widgets to the inactive list.

class.jetpack.php
Allows us to respect the `from` and `redirect` parameters when coming from JPC.
Testing instructions: see https://github.com/Automattic/wp-calypso/pull/22668.
=> Jetpack Connect: Respect from and redirect parameters for Calypso

_inc/lib/markdown/extra.php
Part of #8156.
Alternative to #8869.
Fixes https://wordpress.org/support/topic/deprecated-function-create_function-2/
* Introduces function `jetpack_utf8_strlen`.
* Replaces usage of `create_function` for `jetpack_utf8_strlen` in `markdown/extra.php`.
~**Note:** `mb_strlen` has been available since PHP 4. Should we drop this conditional usage instead ? This alternative is implemented in #8869.~ Apparently there's still a chance that a php installation lacks the `mbstring` extension.
*
=> Markdown: Avoid usage of create_function

json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php
Currently we assume that that dates being passed to date range queries with /sites/:site/posts are in the same TZ as the site. That's pretty fragile assumption and can easily break depending on client preference. This patch changes how we build the query to always use UTC dates and post_date_gmt when querying, which allows clients to use any TZ they like in the query.
Differential Revision: D9104-code
This commit syncs r167670-wpcom.
=> REST: Change /sites/:site/posts date range queries to use post_date_gmt

class.jetpack-twitter-cards.php
Twitter cards: add new `jetpack_twitter_image_default` filter to allow themes and plugins to customize twitter:image when no suitable image is found automatically. It matches the existing `jetpack_open_graph_image_default` filter.
(Thanks for considering this!)
To test, add this to your theme's `functions.php`:
```php
function my_twitter_image_default ($url) {
return 'http://asdf.com/89asdf.gif';
}
add_filter( 'jetpack_twitter_cards_image_default', 'my_twitter_image_default' );
```
Fetch your site's home page, and a post page that wouldn't otherwise have a Twitter image set. Verify that they both now include `<meta name="twitter:image" content="http://asdf.com/89asdf.gif" />`.
Proposed changelog entry:
> Twitter cards: add new `jetpack_twitter_image_default` filter to allow themes and …
=> Twitter cards: add new jetpack_twitter_image_default filter

_inc/client/components/apps-card/index.jsx
Fixes #7299 in a way.
* Makes the dismissal link only be shown for users that can manage options.
Another option would be replacing  `update_option` for something per user.
2. Build the admin page
3. Connect Jetpack if it's not. Create an editor user if there's not one on the site.
4. Login in incognito with that editor
4. Visit the Jetpack Dashboard, scroll to the bottom until you see the Apps card.
5. Confirm that you don't see the dismissal link
**Before**
**After**
*
=> Admin Page: Show app dismissal button only for admin users in Dashboard

_inc/lib/tracks/class.tracks-client.php, class.jetpack-options.php, class.jetpack-tracks.php, class.jetpack.php
This adds a Jetpack option `tos_agreed` as well as a method `Jetpack::jetpack_tos_agreed` for checking whether or not the TOS has been agreed upon.  
#8685 introduced a regression, blocking some of the Tracks events sending during the connection flow, since the tokens were not yet created, `is_active()` was not a suitable check for blocking the events from sending. 
To Test: 
- Start with a fresh site 
- Either add some error logging in `Jetpack_Tracks_Client::record_event()`, or look at the live tracks feed in mc for your username.
- Click on any of the connection buttons.  The option should have been set.  You can check with `Jetpack_Options::get_option( 'tos_agreed' );`
- You're looking for the events `jetpack_jpc_register_begin`, `jetpack_jpc_register_success` events specifically.  
- …
=> Add flag/option for whether TOS has been agreed upon

class.jetpack-cli.php
It's currently possible to provision/cancel a plan to a site that is in safe mode. This can cause interesting issues such as a cloned site cancelling the production site's plan.
For more details, see: p7kMJG-4mB-p2
Testing instructions:
- Put site in safe mode
- I tend to do this by ensuring a site is accessible by two domains
- Connect on the first domain `idc.jetpack.com` for example
- Update home and siteurl values to other domain. 
- `wp update option home http://idcclone.jetpack.com`
- `wp update option siteurl http://idcclone.jetpack.com`
- Login to site at new domain
- This fires off a sync event that usually will put the site in safe mode
- Ensure safe mode notice shows
- Ensure you have a partner ID and secret
- Follow instructions here if you don't: PCYsg-emq-p2
- Run JPS …
=> CLI: Do not allow managing partner plans while in safe mode

modules/seo-tools.php
Fixes #8693
* Don't recommend SEO tools in Jumpstart screen
* Don't activate SEO tools by default
* On any connected Jetpack site
* Run `wp jetpack reset` (warning, this discards all your settings)
* Go to `/wp-admin/admin.php?page=jetpack#/dashboard`
* Observe Jumpstart screen should not include SEO tools
* Click to activate Jumpstart
* Observe that SEO tools should not be enabled
Remove SEO Tools from Jumpstart
=> Remove Jumpstart reference from SEO Tools

modules/sharedaddy/sharing.js
LinkedIn has deprecated sharing counts in their share plugin:
https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter
@see 1564-gh-jpop-issues
1. After setting up this branch, enable the sharing feature on your site.
2. Go to Settings > Sharing and enable the LinkedIn button as well as the Pinterest and Facebook.
3. Pick a non-official sharing style.
4. Save your changes.
5. Make sure the 3 sharing buttons work, and that sharing counts can still appear for Facebook and Pinterest.
* Sharing: remove LinkedIn sharing count functions as [LinkedIn has deprecated sharing counts](https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter).
=> Sharing: remove LinkedIn sharing counts.

class.jetpack-post-images.php, json-endpoints/class.wpcom-json-api-list-media-endpoint.php, json-endpoints/class.wpcom-json-api-post-endpoint.php, json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php, modules/carousel/jetpack-carousel.php, modules/minileven/theme/pub/minileven/functions.php, modules/minileven/theme/pub/minileven/image.php, modules/shortcodes/slideshow.php, modules/stats.php, modules/theme-tools/featured-content.php, modules/tiled-gallery/tiled-gallery.php, modules/widgets/migrate-to-core/image-widget.php, sal/class.json-api-site-base.php
Fixes #8624
* Pass suppress_filters to all public facing calls to get_posts / get_children
* This is hard to test. There should be no noticeable difference it it works. 
Added suppress_filters param to get_posts / get_children function calls.
=> Added suppress_filters param to get_posts / get_children function calls.

modules/widget-visibility/widget-conditions.php, modules/widget-visibility/widget-conditions/widget-conditions.js
The option items of the minor conditions dropdown in the widget visibility settings are being correctly handled with esc_attr in the backend. However, some of the category names may contain entities (e.g. ampersands), so those option items must be decoded in the frontend to make the text human-readable in these cases.
* Adding a decodeEntities function in widget-conditions.js to handle entity decoding for the minor conditions dropdown.
* Check the minor conditions dropdown with a category name that contains an entity (e.g. ampersand) in the widget visibility settings with and without this patch. Don't forget to bump the version number of the javascript file while it is enqueued.
=> Widget Visibility: fix widget minor conditions dropdown entities

.circleci/config.yml
* This depends on https://github.com/Automattic/wp-e2e-tests/pull/982
* That PR moves the e2e tests from a custom Docker container to use one provided by CircleCI instead.  Details can be found on that PR. 
* It's unfortunately not possible to trigger a CircleCI Workflow build via API, so the only way to test this ahead of time is to set the `E2E_BRANCH` envvar to `try/generic-circleci-container` (the branch from the wp-e2e-tests PR above) in the CircleCI UI and trigger a rebuild of the last workflow.
Note that this PR runs Chrome Headless rather than using xvfb as we were previously.  The last time we turned that feature on there were a lot of unexplained timeout failures, but as best I can tell at the moment that's no longer an issue.  But it's something to watch out for when this is …
=> Update e2e CircleCI config to use generic container

modules/search/class.jetpack-search.php
I have no idea how we missed this but we were having WordPress re-sort the search results instead of relying on Elasticsearch's ordering.
This means that we were getting the most relevant search results per page (as intended) but the individual posts weren't sorted by relevance too. 🤦‍♂️ 
1. Install the plugin [Query Monitor](https://wordpress.org/plugins/query-monitor/) or Debug Bar.
2. Search for something.
3. Verify that the posts displayed are in the same order as they appear in the ES response (you can find that in the debug panel in your admin bar). To easily find the IDs of the displayed posts, I tend to use the edit post links (the ID is in there).
4. You can also look at the query section and make sure `ORDER BY FIELD` is in the query.
=> Search: Keep the posts in the order that ES returns them to us in.

_inc/client/plans/plan-grid.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php
When viewing the plans page, it is possible to be logged out of wpcom, this makes sure they go to the right flow depending on whether they're logged in or not by using the jetpack redirector.
Due to https://github.com/Automattic/wp-calypso/issues/22857, we need to control the final destination of these links without requiring a jetpack release.
* Adds the wp-admin user id to the redux state tree
* Adds a reducer to retrieve the wp-admin user id
* Sends the wp-admin user id to the destination (so tracks aliasing works correctly)
* Links go to the jetpack redirector where it makes sense so they go to the right place
* View plans page with a free plan
* Open links in new tab to various plans while logged into wpcom, see items auto-added to cart
* Open links in new incognito window to various …
=> Fix where if a user isn't logged into wpcom, go to blank screen

_inc/client/plans/plan-body.jsx, modules/module-headings.php
Fixes #6111
* Default to grid view when linking to upload videos
* Activate Pro plan
* Activate VaultPress
* Go to plans description page from dashboard
* Click "Upload Videos" link
* Link should be `/wp-admin/upload.php?mode=grid`, and displayed in grid mode
=> Default to grid view when uploading videos

modules/likes/jetpack-likes-settings.php, modules/sharedaddy/sharedaddy.php
Fixes #8924
Update Like & Sharing metaboxes:
* Use `side` context.
* Use `default` priority.
* Enable **Sharing → Sharing Buttons**
* Confirm metabox shows on right side when adding a new Post.
* Enable **Sharing → Like Buttons**
* Confirm metabox shows on right side when adding a new Post.
* Also test when one or the other is disabled.
* Likes/Sharing: Move metabox in post editor to the right side for a better fit.
=> Move like/share metaboxes to right side

modules/contact-form/css/editor-inline-editing-style.css, modules/contact-form/css/editor-style.css
Fixes #8923
In Contact Form module:
* Add styles for `input[type="url"]`
* Create a new Post.
* Click 'Add Contact Form'
* Confirm 'Website' field is styled like other text fields.
* Preview the new post, confirm 'Website' field is styled like other text fields.
* Contact Form: Fix style/width of `input[type="url"]` for Website address.
=> Fix contact form styling for `input[type="url"]`

_inc/client/components/jetpack-disconnect-dialog/index.jsx
Fixes #8912
In the Jetpack Disconnect Dialog:
* Use `/::/g` to replace all occurrences with `/`
* Clear your browser cache.
* Checkout this branch and run `npm run build`.
* Connect a site that's at least two subdirectories deep; e.g., `example.com/wp/personal`
* Then, from the Jetpack Dashboard, click 'Manage site connection' to disconnect it.
* Observe; instead of `::` you should see the correct `/` separators in the URL.
* Dashboard: Fix `::` separators (should be `/`) when disconnecting a site in a subdirectory.
=> Fix display of site URL on disconnect

modules/lazy-images.php
Fixes #8888 
In #8888 an a11n reported that the `lazyload_is_enabled` filter wasn't working as expecting. He expected it to work like this:
```php
/**
* Disable Lazy Loading on non-singular views
*
* @filter lazyload_is_enabled
* @return bool
*/
add_filter( 'lazyload_is_enabled', 'turn_off_lazyload_on_hfeed' );
function turn_off_lazyload_on_hfeed( $enabled ) {
if ( ! is_singular() ) {
$enabled = false;
}
return $enabled;
}
```
The root issue here is that we run that filter as the plugin is loaded which is way before conditional tags are available. My first thought was to load lazy images on `init`, but that wouldn't work either since conditional tags aren't available until the `wp` action. See the docs on conditional tags here:
https://codex.wordpress.org/Conditional_Tags
To test:
- Add …
=> Lazy Images: Initialize lazy images on wp hook

modules/module-headings.php
Upon running `npm run build` from the master branch, the `modules/module-headings.php` file keeps showing up as a changed file, even though I didn't change anything in this file.
The Jumpstart description was removed a few days ago in #8938 but the built file was not committed with it at that time.
I ran `npm run build` to generate the new `modules/module-headings.php` file.
=> Commit change to module-headings.php

_inc/client/traffic/index.jsx
Fixes #8704
Update links to avoid unnecessary redirects. The following links redirect to these locations anyway, so this PR is simply linking directly to the ultimate destination.
* https://wordpress.com/settings/seo/yoursite → https://wordpress.com/settings/traffic/yoursite
* https://wordpress.com/settings/analytics/yoursite → https://wordpress.com/settings/traffic/yoursite
* Checkout this branch and run `npm run build`
* Visit **Jetpack → Settings → Traffic → Search engine optimization**
* Confirm "Configure your SEO settings" points to: https://wordpress.com/settings/traffic/yoursite
* Visit **Jetpack → Settings → Traffic → Search engine optimization**
* Confirm "Configure your Google Analytics settings" points to: https://wordpress.com/settings/traffic/yoursite
* Settings: Update …
=> Update SEO/analytics links to avoid redirects

_inc/lib/admin-pages/class.jetpack-admin-page.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php, class.jetpack-admin.php, class.jetpack-cli.php, class.jetpack-modules-list-table.php, class.jetpack.php, modules/google-analytics.php, modules/module-headings.php, modules/search.php, modules/seo-tools.php, modules/videopress.php, modules/wordads.php
Fixes #7867
Some plans support different modules. This change declares plan support in the module header, and checks for that support when rendering the "active plan" information.
This allows us to easily render inactive rows in the `jetpack_modules` page and elsewhere, so that users know which modules are truly available.
This change also adds some basic checking in WP-cli and elsewhere for whether plan activation was successful.
* Declare modules with a `Plan: business, premium, personal` (default is `free`) attribute
* Render full list of supported modules and plugins (in the case of vaultpress/akismet) in the `Jetpack::get_active_plan()` response
* Render rows as inactive in the `jetpack_modules` list if they are not supported by the current plan
The goal is NOT to prevent users from …
=> Prevent module activation when plan doesn't support them

_inc/client/components/jetpack-dialogue/index.jsx, _inc/client/components/jumpstart/index.jsx, _inc/client/components/jumpstart/style.scss, modules/module-headings.php
Fixes #7666 and #8744
* Move close button into Jumpstart dialog, as per #8697, by reusing the same Jetpack Dialogue component
* Fix some existing bugs with missing CSS on dialogue background.
Because this page now reuses the Jetpack Dialogue component that powers other modals, it doesn't have the gap between the top two cards. 
This could be implemented by making the Dialogue component transparent, and requiring wrapped components to implement cards where they want translucency. I didn't do this because I wasn't sure if anyone cared either way. Let me know if you need this refinement.
* On a Jetpack site that is already connected
* Open `wp shell` and run `Jetpack_Options::update_option( 'jumpstart', 'new_connection' )`
* Open `/wp-admin/admin.php?page=jetpack#/jumpstart`
* Dialog should …
=> Position Jumpstart dialog close button same as upgrade dialog close button

readme.txt
Fixes #8906
* Change strapline to focus more on popular features: 
> The ideal plugin for stats, related posts, SEO, social sharing, backups, security, and themes.
Should now look like this on the plugins pages:
=> Focusing strapline on more broadly-applicable keywords and features

_inc/client/at-a-glance/backups.jsx
Fixes #8487 
* Update the "install and activate" link in the _Backups_ card to be a functional link matching the "Set up" button.
* Get a new Jetpack site with this branch (JN with `?shortlived&jetpack-beta&branch=fix/8487-backup-install-link`)
* Set up the site with a paid plan
* After checkout but before allowing set up to run, return to the site dashboard.
* You will see the link on "install and activate" now points to the same URL as the "Set up" button.
* Click the link and verify that the _Backups_ set up is performed correctly.
=> Backups: Update "install and activate" link

readme.md
Updates the Waffle.io link in the readme to https://waffle.io/Automattic/jetpack/metrics/throughput
The old link didn't link to the metrics like it said it did.
=> Update Waffle.io link in readme.md

functions.opengraph.php
Fixes #6061
This addresses @mjangda's feedback about how `wp_get_attachment_image_src()` will never work for Blavatar's hosted elsewhere than wpcom, since they will be external URL's.
**Note: this code I am removing was never actually merged to wpcom until today, where it broke as explained and was reverted immediately.**
You should see no change in Jetpack's behavior.  This simply reverts the blavatar checks to what we currently have on wpcom.
=> Open Graph: stop trying to query for a Blavatar post ID 

modules/publicize/ui.php
Fixes #8919
* Add sharing icon in publish metabox
* Refactor form rendering to make code easier to understand
* Change "Show Details" and "Show" links to "Edit"
* Renamed "Publicize" to "Social Sharing" (ooh - controversial!)
* Change 'Hide' links to 'OK' buttons
* Enable Publicize, ensure no connected accounts
* Start a new post
* Ensure styling looks consistent with other elements of the Publish metabox
* Click "Edit" next to Social Sharing section
* Add one or more accounts
* Start a new post again
* Ensure styling looks consistent with other elements of the Publish metabox
Not connected, closed:
Not connected, open:
Connected, closed:
Connected, open:
Make styling of Publicize more consistent with wp-admin.
=> Add icon and font parity with other Publish items

package.json, yarn.lock
An error in the dependency was breaking static files generation on the latest step of the build, leading to the 'static.html file missing' error. You should be able to use this branch in the Beta plugin.
Fixes #9020
=> Upgraded i18n-calypso to 1.9.1 to fix the Beta Builder.

.eslintrc, _inc/client/components/form/input-checkbox-multiple.jsx, _inc/client/components/form/input-radio.jsx, _inc/client/components/global-notices/index.jsx, _inc/client/components/jetpack-notices/dismissable.jsx, _inc/client/components/navigation-settings/index.jsx, _inc/client/components/navigation/index.jsx, _inc/client/components/popover/docs/example.jsx, _inc/client/components/section-nav/docs/example.jsx, _inc/client/components/select-dropdown/docs/example.jsx, _inc/client/components/settings-card/index.jsx, _inc/client/discussion/subscriptions.jsx, _inc/client/plans/plan-body.jsx, _inc/client/pro-status/index.jsx, _inc/client/searchable-modules/index.jsx, _inc/client/security/sso.jsx, _inc/client/traffic/ads.jsx, _inc/client/traffic/related-posts.jsx, _inc/client/traffic/site-stats.jsx, _inc/client/writing/composing.jsx, _inc/client/writing/custom-content-types.jsx, _inc/client/writing/media.jsx, _inc/client/writing/theme-enhancements.jsx
Fixes all eslint warnings about the react/jsx-no-bind rule.
* Upgrades the `react/jsx-no-bind rule` to an error.
* Refactors several components to drop `.bind()` and `onEvent={ () => {} }` patterns among jsx code.
* Run `npm run lint` and expect to see no linting warnings.
* Build the admin page and confirm it does it properly (`yarn build`).
=> Admin Page Fix all eslint warnings about the react/jsx-no-bind rule

.circleci/config.yml
Woraround for https://github.com/oskosk/jurassic.ninja/issues/103
* disable parallelism in CircleCI E2E tests
Make sure that CI job(`test` part) is running in a single container: https://circleci.com/gh/Automattic/workflows/jetpack/tree/try%2Fe2e-use-single-container
=> Use single container in E2E tests

modules/seo-tools.php
Fixes #9033
* Ensure that `Jetpack::active_plan_supports( 'seo-tools' )` returns `true` for people with the Premium plan.
* Upgrade to Jetpack Premium
* Activate SEO tools via Calypso or WP Admin
* SEO tools should be activated without error
=> Add SEO tools to the premium plan in module meta

modules/protect.php
Currently math fallback doesn't do anything for xml rpc requests. Lets hard block xmlprc requests when they get marked as blocked. This would help prevent more of the requests coming though. 
This PR blocks xmlrpc requests for would regularly show the math test just gets bypassed and allows more valid xml rpc requests though.
use the following code. composer.json 
```
{
"name": "xmlrpc-tester",
"type": "test",
"require": {
"hieu-le/wordpress-xmlrpc-client": "~2.0"
},
"license": "GPL2",
"authors": [
{
"name": "Enej",
"email": ""
}
]
}
```
index.php 
```
require __DIR__ . '/vendor/autoload.php';
$endpoint = "https://enej.wpsandbox.me/aaa/xmlrpc.php";
$wpClient = new \HieuLe\WordpressXmlrpcClient\WordpressClient();
$wpClient->onError(function($error, $event) {
print_r( $error );
});
$do = …
```
=> XML RPC request should get hard blocker quicker

_inc/jetpack-jitm.js
Fixes #8769
* Allows specifying that a jitm can be opened in a new window, or the same window.
* Check out this branch and build
* Check out D10673-code
* Get a personal plan
* View the rewind jitm on the dashboard (alternatively update one of the other jitms to use this new rule)
* Clicking the button should open in same window instead of a new window
=> JITMs: Allow opening in the same window

modules/masterbar/tracks-events.js
Follow up of D10762-code
With the Grammarly extension enabled on Chrome macOS, the following error occurs when navigating to a site with the WordPress.com Masterbar module active, logged in as a WordPress.com user:
```
Uncaught TypeError: Cannot read property 'origin' of undefined
at masterbar-tracks.js?m=1520506909h&ver=20171026:130
at dispatch (jquery.js?m=1466523978h&ver=1.12.4:3)
at r.handle (jquery.js?m=1466523978h&ver=1.12.4:3)
```
Also the code is wrong. There's no `event` variable.
Navigate to a Jetpack site with the Masterbar module active and there should be no regressions, all _Tracks_ events should fire.
=> Masterbar: fixes "origin" undefined error.

_inc/client/components/tags-input/style.scss
Fixes #8702
* Remove `height:` property in CSS giving the container an ability to resize based on the number of ignored phrases it contains.
* Checkout this branch and `npm run build`.
* Open Jetpack **Settings → Writing → Composing → Check your spelling, style, and grammar**.
* Fill in lots of ignored phrases. Enough to consume three or more lines.
* Observe; the bordered container grows with the number of ignored phrases.
Before, this was overflowing/overlapping:
* Settings: Fix overflow/overlap when there are many ignored phrases in spelling options.
=> Fix ignored phrase overflow/overlap

modules/wordads/wordads.php
Adding blog/site id to IPW metadata in head.
**To Test**
1. Enable Jetpack Ads module
1. Go to any page with ads, view source, and check that `siteid` with site's blog_id is added in `__ATA_PP` object.
e.g.
=> Ads: Adding site id to head meta

webpack.config.js
It looks like maybe this used to work, but it sure makes debugging easier during development.
=> Use JS sourcemaps during development

_inc/lib/admin-pages/class.jetpack-admin-page.php, class.jetpack-admin.php
fixes https://github.com/Automattic/jetpack/issues/8723
Right now, if you navigate to WordPress.com from the Jetpack dashboard and then come back via back button, you are getting the previous state of the app because of browser's cache. This PR add no-store cache policy to jetpack admin pages so you don't get a cached version of the dashboard when you click 'back' from wpcom
How to test
=========
1. Activate Jetpack (or if it's already active and you don't want to deactivate, run `wp option update show_welcome_for_new_plan true` with wp-cli)
2. You should get the Warm Welcome modal (if you used wp-cli, you may need to navigate to the jetpack dashboard or reload the page)
3. Click on the "view more stats in WordPress.com" button. 
4. Once you get to wp.com, click on the browser's back …
=> no-store cache policy for admin pages

3rd-party/vaultpress.php
Fixes #8691
This PR fixes issues with VaultPress deactivation driven by Jetpack when Rewind is active:
The Jetpack menu was previously still showing the VaultPress submenu and clicking it lead to a blank page. This is now fixed here.
The notice saying "VaultPress needs your attention!" was still shown before, but it's now hidden. It was complex to remove it since it wasn't possible to remove the actions hooked to `user_admin_notices` and `admin_notices`. To overcome this, a `<style>` tag was added with a rule to hide the notice.
Updated PHPDocs.
1. test with a site with Rewind active
2. activate the VaultPress plugin. It will be automatically deactivated and a notice will show.
3. ensure that:
- there's not a **VaultPress** submenu entry under the **Jetpack** menu
- the notice …
=> VaultPress: if Rewind is enabled, remove its entry in sidebar and hide its notice

package.json
Adding `private:true` to `package.json` will suppress yarn warnings about invalid license field.
https://docs.npmjs.com/files/package.json#private
It'll also prevent accidental publication using `npm publish`.
Previously running `yarn` commands would show:
> warning package.json: License should be a valid SPDX license expression
Adding `private:true` to `package.json` will make warnings dissapear.
Noting that we do have a valid SPDX license expression but `GPL-2.0-or-later` is so new format that Yarn v1.3 just didn't recognise it.
=> Build: add `private:true` to package.json

modules/likes.php, modules/module-headings.php
Remove Likes from Jump start - usage patterns suggest it's better as an opt-in.
=> Remove likes from jumpstart

gulpfile.babel.js
Fixes `yarn build` and `gulp php:unit` when having Rewind temporary files .
* Ignores `docker/**` in check:DIR gulp task.
* Ignores `docker/**` in php:lint gulp task.
* Start with a dir structure that has wordpress and temporary rewind files on it `jetpack-temp`.
* Run `yarn build` and expect nothing to fail.
* Run `node_modules/.bin/gulp php:lint` and expect nothing to fail.
=> Build: Ignore docker directory in gulp tasks that glob with **/*.php

modules/google-analytics/classes/wp-google-analytics-universal.php, modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php
"PHP Warning: str_replace() expects at least 3 parameters, 2 given"
Adding the last parameter should help.
Reported here:
https://wordpress.org/support/topic/php-warning-156/
* WooCommerce Analytics: fix PHP warning.
=> WooCommerce Analytics: fix PHP warning.

docker/README.md
Because [Ngrok inspector](https://ngrok.com/docs#inspect) is pretty awesome for Jetpack development, it'd be good to have it in docs so that everyone knows about it.
=> Docker: mention Ngrok inspector in docs

scss/organisms/_banners.scss
Fixes #8677
- View on a wider screen
Set to width 1250px as suggested by @joanrho 
Looks like this now
=> Widen the connection banner content

scss/jetpack-admin-jitm.scss
Based on @kellychoffman's suggestion, this removes the all caps from the button text.
Before:
After:
cc @jeffgolenski as the original designer for a 👍
=> JITM: Do not use all caps for button text

modules/widgets/wordpress-post-widget.php
* Adds `rel="noopener"` to post links shown by the WordPress Posts widget if the `Open links in new window/tab:` setting is active.
* Check this branch.
* Add a  **Display WordPress Posts** widgets to the sidebar (listed as `DisplayWordPress Posts (Jetpack)`).
* Add a WordPress site as **Blog URL**.
* Check the box **Open links in new window/tab** and save the widget.
* Visit a page on your site that will show the widget.
* Inspect the links and confirm that the links to the other site posts include the attribute `rel="noopener"`.
Tested in MacOs with:
* Firefox
* Opera
* Safari
* Chrome 
* Adds rel=noopener attribute to links in the Display WordPress Posts widget if set to open in a new window.
=> Widgets: WordPress Posts - Add rel=noopener attribute to links in WordPress posts widget if set to open in new window

modules/masterbar/masterbar.php
Fixes p1HpG7-4X1-p2
Fixes #9044.
* Sets the `jetpack_masterbar_should_logout_from_wpcom` to be `true` by default.
* Activate masterbar
* Sign out from the site
* Expect to be signed out from WordPress.com too.
* Made the Sign Out link in the Master always log you out from WordPress.com
=> Masterbar: Always sign out from WordPress.com

Gruntfile.js, gulpfile.babel.js, phpcs.xml
Follow up for https://github.com/Automattic/jetpack/pull/9087
- Use the same list of paths to exclude in different tasks
- Add Docker folder to excluded list in Gruntfile.js
- Move ignored paths to the end from the beginning of glob array in Gulp. Having ignored paths at the end of the glob array reads better to me because I see relevant files first. It should not have any impact on the current setup because:
> A glob that begins with `!` excludes matching files from the glob results **up to that point**.
([via](https://github.com/gulpjs/gulp/blob/v3.9.1/docs/API.md#globs))
- Add `__DIR__` to some php-file in `./docker` directory and observe `node_modules/.bin/gulp check:DIR` not fail.
- Add `*-block.jsx` file file under in `./docker` directory and observe it not get cloned to `.js` file. …
=> Build: exclude more folders

_inc/client/components/admin-notices/index.jsx, _inc/client/components/global-notices/style.scss, _inc/client/components/notice/index.jsx, _inc/client/components/notice/style.scss, _inc/client/pro-status/index.jsx, _inc/client/scss/calypso-colors.scss
Fixes #8920 
**To test:** 
Notices should look like this now: 
- Regular notices
- Global notices: 
- Compact
=> Update notice styles to match Calypso

_inc/client/components/jumpstart/index.jsx
Fixes warning reading `Warning: validateDOMNesting(...): <h2> cannot appear as a descendant of <p>. See JumpStart > p > ... > h2` due to an `h2` element being child of `p`.
* Updates a `<p>` tag for `<div>` so it's valid markup
* On a fresh site, unconnected.
* When you're shown to the Jumpstart dialog, open the javascript console. Don't close the Jumpstart dialog.
* Check the preserve log setting. 
* Clear the log.
* Refresh the page.
* Confirm that you don't see any message reading `Warning: validateDOMNesting(...): <h2> cannot appear as a descendant of <p>. See JumpStart > p > ... > h2.`
=> Admin Page: Replace p for div in jumpstart component

_inc/client/pro-status/index.jsx
Fixes #8525 
Fixes #9113
* Makes the Set Up show only for paid features related to plugins.
* Go to wp-admin > Jetpack > Settings,
*  Search for the "Widget Visibility" . Expect to see no setup button.
**Searchable module active Before**
When Akismet is active: 
When Akismet is deactivated:
Note that the ACTIVE label is intended for paid features depending on plugin configuration
**Searchable module active After**
=> Admin Page: Hide pro set up button for searchable modules

modules/comments/comments.php
Fixes #9118
Add title to iframe rendering the comment form. This allows VoiceOver users to navigate to the iFrame and leave a comment.
To test
Does the iframe display the title attribute.
Use Mac's VoiceOver to navigate to the form.
=> Comments: Add title attibute to comment form iframe

_inc/client/plans/plan-grid.jsx, _inc/client/plans/style.scss
* don't hide the plans table on small screens
View the Plans tab on a screen smaller than 600px wide. Before this PR, the table will be hidden. After, it shows.
It does look bad on very small screens, and we should plan to bring over the plans cards view from Calypso in the next release.
=> Plans: don't hide on small screens

_inc/client/at-a-glance/stats/index.jsx, _inc/client/at-a-glance/stats/test/component.js
This PR hides the date range tabs shown in the Stats in the dasboard when the dialog explaining about the time needed to collect data is shown and it hasn't been yet dismissed.
Fixes #7899
* when empty Stats dialog hasn't been dismissed, hide the date range tabs
* use a new site and connect
* verify that you see the dialog "Hello there! Your stats have been activated." and that the date range tabs aren't shown
*
Hide the date range tabs when the initial dialog is shown
=> Stats: don't display the date range tabs when the initial dialog is shown

modules/shortcodes/tweet.php
Fixes #8816
* Loads Twitters widget.js via https instead of http connection
=> Load Twitter widget using secure connection

modules/likes/jetpack-likes-settings.php
Fixes #2044
* Makes the single post edit metabox not have likes forcedly unchecked when Likes are enabled for all posts.
* Replace a `xor` comparsion for a regular `or` when deciding whether to show the Likes button or not based on the metadata of the post and the global setting for Likes
1. Likes module enabled, Settings->Sharing set to likes on a per post basis
2. On a post, check the box to enable likes for that post, save.
3. Confirm likes are visible.
4. Change the setting on Settings->Sharing to enable likes for all posts.
5. View the previously likeable post.
6. Confirm you see the Likes button.
7. Edit the post and see the checkbox remains checked.
Made manually enabled likes to still be likeable if Likes are enabled for all posts
=> Likes: Make posts with manually enabled likes still be likeable if Likes are enabled for all posts

modules/google-analytics/classes/wp-google-analytics-legacy.php
```
PHP Notice: Undefined index: s in /wp-content/plugins/jetpack/modules/google-analytics/classes/wp-google-analytics-legacy.php on line 82
```
Reported in 1034382-zen
I could not reproduce the error on my end, unfortunately.
* Google Analytics: fix PHP notice on search
=> Google Analytics: fix PHP notice on search reported by some users.

_inc/client/components/welcome-new-plan/professional.jsx
Fixes #8694.
https://github.com/Automattic/jetpack/issues/8694#issuecomment-368961905
1. Comment out this `return` to get the dialog to show up: https://github.com/Automattic/jetpack/blob/master/_inc/client/components/welcome-new-plan/index.jsx#L50
2. Run `yarn build` to build a fresh set of the JavaScript app.
3. Visit the Jetpack dashboard in `wp-admin` on a site that has the Professional plan. Check out the updated dialog box.
4. Verify that the new link at the bottom takes you to the Customizer's widget section.
5. Verify that the Tracks event triggers when you click on that new link.
=> Add search to the Professional plan warm welcome

_inc/client/admin.js, _inc/client/components/footer/index.jsx, _inc/client/components/navigation-settings/index.jsx, _inc/client/components/navigation/index.jsx, _inc/client/main.jsx, _inc/client/privacy/index.jsx, _inc/client/settings/index.jsx, _inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/class.jetpack-core-api-module-endpoints.php
~~Must be merged after #9003 is merged.~~ It's merged
This PR introduces a new page accessible through the Privacy link at the bottom of the Jetpack dashboard.
The page features links to the Automattic privacy policy and to the upcoming privacy.blog. The support link goes through what data does Jetpack sync.
The page also introduces a toggle so users can opt-out of information tracking that Automattic collects for its own purpose.
=> Add new settings route and page for Privacy settings

class.jetpack-client.php
This adds a new utility method: `Jetpack_Client::wpcom_json_api_request_as_user()`
- Depends on D11180-code, which has already been merged (now live).
```php
$response = Jetpack_Client::wpcom_json_api_request_as_user( '/jetpack-user-tracking' );
if ( ! is_wp_error( $response ) ) {
$settings = json_decode( wp_remote_retrieve_body( $response ) );
}
// var_dump( $settings->tracks_opt_out ); // (bool)
```
```php
$response = Jetpack_Client::wpcom_json_api_request_as_user(
'/jetpack-user-tracking',
'v2',
array( 'method' => 'PUT' ),
array( 'tracks_opt_out' => true )
);
if ( ! is_wp_error( $response ) ) {
$settings = json_decode( wp_remote_retrieve_body( $response ) );
}
// var_dump( $settings->tracks_opt_out ); // (bool)
```
=> Add utility for WPCOM API requests as user

views/admin/network-admin-footer.php
Just some small cleanup.
In Jetpack settings page for WP network:
- http → https links in the footer
- Add `rel="noopener noreferrer"` to links with `target="_blank"` as a security measure
- Move HTML code out from survey button translation string
1. create WP network site
2. Go to `/wp-admin/network/admin.php?page=jetpack-settings` 
3. Check footer links and survey button
=> Network Settings: secure footer links

_inc/client/components/popover/index.jsx
Fixes positioning of popovers when the window is resized
Mirrors https://github.com/Automattic/wp-calypso/pull/19992
Props to @AnnaMag and @eliorivero 
* Defers setting the new position on the popover until next tick.
* On a connected Jetpack site, Checkout this branch
* Build the admin page
* Get the Jetpack Settings.
* Click the InfoPopover links and expect to see the popover properly positioned.
* Narrow the window , close and reopen the Popovers and expect them to be well positioned.
* Fixed the positioning of popovers in Jetpack Settings page.
=> Admin Page Fix popover positioning

_inc/client/components/settings-group/index.jsx, _inc/client/components/settings-group/test/component.js, _inc/client/discussion/comments.jsx, _inc/client/discussion/subscriptions.jsx, _inc/client/security/antispam.jsx, _inc/client/security/backups-scan.jsx, _inc/client/security/protect.jsx, _inc/client/security/sso.jsx, _inc/client/sharing/likes.jsx, _inc/client/sharing/publicize.jsx, _inc/client/sharing/share-buttons.jsx, _inc/client/traffic/ads.jsx, _inc/client/traffic/google-analytics.jsx, _inc/client/traffic/related-posts.jsx, _inc/client/traffic/search.jsx, _inc/client/traffic/seo.jsx, _inc/client/traffic/site-stats.jsx, _inc/client/traffic/sitemaps.jsx, _inc/client/traffic/verification-services.jsx, _inc/client/writing/composing.jsx, _inc/client/writing/custom-content-types.jsx, _inc/client/writing/masterbar.jsx, _inc/client/writing/media.jsx, _inc/client/writing/post-by-email.jsx, _inc/client/writing/speed-up-site.jsx, _inc/client/writing/theme-enhancements.jsx
Fixes #8922
* allow to display a short text and a link in the info popover. The `support` property of `SettingsGroup` component is no longer a string and no longer receives a URL. It receives and object with `text` and `link` properties, that are the text blurb and the link to the support doc respectively.
* add support text & link to all settings group in Writing tab. Introduce new settings group for portfolios in custom content types. Refactor theme enhancements to remove unnecessary code
* add support text & link to all settings group in the Sharing, Discussion, Traffic, and Security tabs.
* align popover towards left to follow Calypso's style
Popovers now look like this with the text and link
* verify that on each settings card the text corresponds to [the one provided …
=> Settings: update learn more info

_inc/client/traffic/ads.jsx
Fixes wrong state for the toggles perceived as soon as the Ads module is enabled. Feature states is left in the opposite of current expected state. So toggling a setting to off, ends up enabling the setting on the site.
Fixes 1568-gh-jpop-issues
* Removes unnecessary handling of internal state from the Ads component
1. On a site with Professional Plan, check out this branch and build the admin page (Or use the [Jetpack Beta Tester](github.com/Automattic/jetpack-beta) plugin to test this PR out)
1. Reset ads settings to their defaults:
```sh
wp jetpack module deactivate wordads
wp option delete wordads_display_archive
wp option delete wordads_display_post
wp option delete wordads_display_front_page
wp option delete wordads_display_page
```
1. Go to Jetpack > Settings > Traffic > Ads 
1. …
=> Admin Page: Ads Settings - Fix settings toggling

_inc/client/components/jetpack-notices/index.jsx, _inc/client/main.jsx, _inc/client/state/initial-state/reducer.js
Fixes #8066.
This PR adds a check to the connection view condition. Before we would not show anything to the user if they could not manage modules. Now we add the connect privilege check here as well, so the same thing happens if a user does not have the 'jetpack_connect' cap.
* Adds the connect capability to initial state reducer.
* Adds a check for this capability when determining whether to show the connection view or not.
* Disconnect Jetpack.
* Remove connect capability for every user in the client by adding something like `false &&` here: https://github.com/Automattic/jetpack/blob/master/_inc/lib/admin-pages/class.jetpack-react-page.php#L397
* View the dashboard, check that no connection prompts appear.
* Fixed the dashboard view for non-admin users on disconnected sites.
=> Not showing connection view if the user cannot connect.

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
When syncing content to WordPress.com for display or syndication, it is helpful to know if a post has an AMP URL. This PR detects the `amp_get_permalink()` function and uses it to sync the AMP URL alongside the permalink and shortlink.
* Detect and sync AMP permalink for a post object.
* Install this Jetpack branch on a site which is set up to sync via a WPCOM sandbox, and which has the [AMP plugin](https://github.com/Automattic/amp-wp) installed, and Jetpack connected.
* Subscribe to posts from the site in your reader
* Confirm that the post has an "amphtml" meta in the page `<head>` section
* Run this Calypso PR: https://github.com/Automattic/wp-calypso/pull/23603
* Reload the Reader until the new post appears
* The post should be displayed as AMP content, rather …
=> Sync AMP permalink URL

_inc/client/privacy/index.jsx
`SettingsGroup` expects an object with `text` and `link` properties, but a string is being passed. We don't need this since the card already has the pertinent information. Bug introduced in #8993
Load `master` before this and click the Privacy link in the Footer. See this error in your console:
```
Failed prop type: Invalid prop `support` of type `string` supplied to `SettingsGroup`, expected `object`
```
After this, the error is gone because the prop is no longer being passed.
=> Privacy Settings: Fix PropTypes error

modules/module-extras.php, modules/search/class.jetpack-search.php, modules/widgets.php, modules/widgets/search.php
Fixes #9041
~~Not 100% sure this is the best way to always load a widget or not. Suggestions welcome for alternate code choices.~~
~~Always load the Search widget, even if the Extra Sidebar Widgets module is disabled. It's already loaded even if the Search module isn't loaded.~~
Force the Search widget to be loaded via the Search module so that even if Extra Sidebar Widgets is disabled, the widget is still available for use.
If both the Search module and the Extra Sidebar Widgets module are disabled, then the widget will not be loaded.
0. Make sure your test site has a Professional plan.
1. Visit `/wp-admin/admin.php?page=jetpack_modules` and disable both the Extra Sidebar Widgets module and Search module.
2. Visit Appearance -> Widgets and make sure that "Search (Jetpack)" is **not** …
=> Load the Search widget even if Extra Sidebar Widgets is disabled

sal/class.json-api-site-base.php
This will remove the skyword-tracking shortcode, which is used on our main WordPress.com blog and Jetpack.com from posts that are returned via the API. Before this patch, the shortcode was being output unrendered. Even rendered, it would be a script tag which I'm not sure makes sense in content returned via the API.
This commit syncs r172151-wpcom.
=> API: SAL: Remove skyword-tracking shortcode when querying for post via SAL

_inc/client/at-a-glance/akismet.jsx, _inc/client/at-a-glance/plugins.jsx, _inc/client/at-a-glance/style.scss
Fixes #4549
Adds a clickable card so users can go and manage plugins in Calypso when plugin autoupdates are enabled. This card will be persistent and always displayed.
And this is how it looks when autoupdates aren't turned on:
The clickable card is not shown in Dev Mode
This card also got a clickable card to go to comment moderation at 
https://wordpress.com/comments/all/SITESLUG
As with plugins card, the clickable card is not shown in dev mode.
* turn on auto-updates
* make sure the link is there
Dashboard - Plugins: new link allows to go to WordPress.com to manage plugins even when auto-updates are enabled.
=> Dashboard: add link to manage plugins and moderate comments in Calypso

_inc/lib/class.core-rest-api-endpoints.php, class.jetpack.php
* Adds a  new endpoint proxy for D11180-code (to get/set `tracks_opt_out`). Note that D11180-code has been merged already and is now live.
* Uses a new utility added by this PR: `Jetpack::current_user_ip()`
* Merge https://github.com/Automattic/jetpack/pull/9122  first.
* Merge this branch.
* Install [REST API Console](https://wordpress.org/plugins/rest-api-console/) plugin.
* From the console, test `/jetpack/v4/tracking-settings` (GET & POST methods).
* Confirm `tracks_opt_out` changes when POSTing an update.
=> Add user tracking endpoint proxy for `tracks_opt_out`

class.jetpack-modules-list-table.php
We intended to hide this from the legacy settings page, but it has not been working.  
To Test: 
- Make sure you do not see Manage in the module list at `/wp-admin/admin.php?page=jetpack_modules`
- Deactivate manage with CLI.  You should see it in the list again.
=> Remove Manage from the legacy settings page if active

functions.global.php
Follow-up to #9053.
Since some tracking begins upon any attempted connection, we need to clarify the statement provided alongside our connection (“Set up Jetpack”) button so that it is apparent to folks connecting to
WordPress.com. 
As mentioned by  @eliorivero in https://github.com/Automattic/jetpack/pull/9053#issuecomment-374216586 this banner may need an update too
* Updates text from `By connecting your site you agree to our fascinating `, to `By clicking the Set up Button, you agree to our fascinating...`.
1. On a disconnected site, visit the plugins page (for example) and confirm the text before the button reads `By clicking the Set up Jetpack button, you agree to our fascinating...`.
**Before**
**After**
Updated connection banner to clarify when tracking of events begins.
=> Connection: Update connection banner text to clarify ToS acceptance on click

_inc/client/at-a-glance/monitor.jsx, _inc/client/at-a-glance/photon.jsx, _inc/client/at-a-glance/plugins.jsx, _inc/client/at-a-glance/protect.jsx, _inc/client/at-a-glance/stats/index.jsx, _inc/client/at-a-glance/stats/test/component.js, _inc/client/state/modules/reducer.js
This PR introduces a new selector `isModuleAvailable( state, 'module-slug' )` to consolidate in a single place a bunch of duplicated code scattered around components used in At a Glance.
Fixes #9111 
* introduce `isModuleAvailable( state, 'module-slug' )`
* remove duplicated code
* remove unused class `.jp-dash-item__interior`. It's added in components but doesn't have any rule applied to it. Furthermore, it wasn't in Monitor card for example.
* test that everything is working like before
=> Settings: introduce new selector to check module availability

modules/subscriptions.php
This PR modifies the message that appears when a user that is already subscribed to a blog attempts to resubscribe to the blog as per https://github.com/Automattic/jetpack/issues/5812. It adds a link to the subscription management to the message.
Before:
After:
=> Jetpack: Add subscription management link to already subscribed error

3rd-party/vaultpress.php
Follow up #9056
* Remove WP core notice that says that the plugin was activated
1. test with a site with Rewind active
2. activate the VaultPress plugin. It will be automatically deactivated and a notice will show.
3. make sure there's not a `Plugin activated.` notice
=> VaultPress: remove WP core notice that says that the plugin was activated

_inc/client/at-a-glance/akismet.jsx
Fixes a bug introduced in #9078 where we were passing an object instead of a string.  Turns out we need to expect either of them, since the state sets a string by default :(
=> Dashboard: fix undefined prop type

modules/widgets/social-icons.php, modules/widgets/social-icons/social-icons-admin.css, modules/widgets/social-icons/social-icons-admin.js, modules/widgets/social-icons/social-icons.css, modules/widgets/social-media-icons.php
Fixes #3776
Fixes #7433
Fixes #7601 
Closing previous PR/branch (#7454) and opening a new one due to an issue with a rebase.
To keep in line with WPCOM, I’d like to add the new Social Icons
widget. You can add this widget to any site and you should have a new
widget as seen on its documentation page
(https://en.support.wordpress.com/widgets/social-media-icons-widget/).
The old widget should become unavailable to sites not using it. If they
do then we add a “(Deprecated)” to the label.
In `social-icons.php`, L72, we use the same `social-menu.svg` file as
the one used for the Social Menu.
=> Add new Social Icons widget and deprecate old Social Media Icons widget

3rd-party/bbpress.php
Fixes #8952 . Docblock for 6.0 since we're past 5.9 code freeze.
* Add markdown support for bbPress CPTs
* Enable bbPress, Jetpack, Jetpack's Markdown feature
* While editing a topic/forum/reply, use Markdown (e.g. underscores wrapping a word).
Expected: Content is transformed (e.g. the text becomes italics).
Enhancement: Markdown support added for bbPress CPTs.
=> Add markdown support for bbpress CPTs

_inc/client/lib/analytics/index.js, _inc/client/privacy/index.jsx, _inc/lib/tracks/class.tracks-client.php
Depends on https://github.com/Automattic/jetpack/pull/9142 and https://github.com/Automattic/jetpack/pull/9154 
---
This PR is a fork of (and alternative to) https://github.com/Automattic/jetpack/pull/9155 (props @mattwiebe) that brings it together with the work I did previously in https://github.com/Automattic/jetpack/pull/9085 to implement `window._tkq.push( [ 'setOptOut', true|false ] )` 
- Implement the `setOptOut` command; i.e., whenever the new privacy option is changed, this PR will set or unset the opt-out cookie using `window._tkq.push( [ 'setOptOut', true|false ] )`
- Make `Jetpack_Tracks_Client` in PHP aware of the `setOptOut` cookie too. If the opt-out cookie exists, do not record server-side events either.
- First merge https://github.com/Automattic/jetpack/pull/9142 and …
=> Update/centralize user privacy + cookie (PR combo)

3rd-party/woocommerce.php, modules/infinite-scroll/infinity.js, modules/infinite-scroll/infinity.php
Adds basic WooCommerce support in the 3rd party scripts directory for WooCommerce.
This branch was branched from https://github.com/Automattic/jetpack/pull/9112 which will need reviewing and merging first.
The following changes are all related to WooCommerce and other plugin compatibility and are hence grouped into this single PR.
---
**Posts per page changes**
The current system is quite odd; it uses a fixed number of 7 or the 'posts per page' setting in WP Admin. This isn't suitable for custom post types where they have their own posts_per_page setting or preference. WC is a perfect example whereby posts_per_page is set to match our products grid.
To make this more robust we pass through the posts per page setting from the original query and use this instead.
If the theme defines a …
=> Infinite Scroll: Improved rendering callbacks w/ WooCommerce support

modules/infinite-scroll/infinity.js, modules/infinite-scroll/infinity.php
I believe this fixes #1135 but we have slightly different reproduction steps in that we're simply running this on a custom post type archive. I found issues in the way pagination works which I'll do my best to explain below.
There are 2 main issues this PR aims to resolve;
1. Page "1" being loaded when you're already viewing page 1.
2. Queries from other plugins failing because the Infinite scroll query is not the "main query".
**Globals**
This PR adjusts the order in which the globals `wp_the_query` and `wp_query`  are set so that `is_main_query` is accurate when ran on the `pre_get_posts` hook.
Looking at the code where it set `wp_the_query` and `wp_query` it looks like the intention here was to be the 'main query' but because the query is RAN before these globals are set, any functions …
=> Infinite Scroll: Prevent first page duplication, and fix main query detection

modules/shortcodes/pinterest.php
Fixes #7968.
For URLs other than pinterest.com that are embedded, the embed doesn't pick them up. This change modifies the regular expression to include any domain that has pinterest. followed with TLDs. This allows for false positives for garbage links and sites not affiliated with pinterest ( like http://pinterest.example.com/something )  to also work with this embed, but it shouldn't be a problem.
* Updated the Pinterest embed regular expression.
* Try to embed an URL from pinterest.co.uk like https://www.pinterest.co.uk/stayandroam/blue-and-white/
* See that it doesn't work
* Use this PR
* See that the embed does work and doesn't break existing .com embeds.
* Fixed embeds from Pinterest when using .co.uk, .pt or other TLDs.
=> Fixed Pinterest embeds for URLs other than .com.

modules/widgets/customizer-utils.js, modules/widgets/eu-cookie-law.php, modules/widgets/eu-cookie-law/form.php
Fixes #8998
* fix issue where custom URL choice wasn't preserved in Customizer
* fix issue where widget didn't selectively refresh in Customizer. While the widget declared support, it didn't reinitialized itself after it was selectively refreshed.
* add a EU Cookie Law Banner widget and make sure you can choose a Custom URL for the policy
* make sure selective refresh works fine
=> Widgets - EU Cookie Law: fix issue with custom URL choice and selective refresh

_inc/client/at-a-glance/stats/index.jsx, _inc/client/state/at-a-glance/actions.js, _inc/client/state/at-a-glance/reducer.js
Fixes wrong handling of a first request for a site that has no stats collected yet.
With current default, the state is left in this form:
* Updates the default state for the stats reducer from `'N/A'`. to `{}`. (from string N/A to empty object).
1. Launch a new site
3. Quickly when you're dropped into Jetpack's Dashboard, attempt to Jumpstart.
4. Expect to see no errors.
*
=> Admin Page Update default state value for stats reducer

class.jetpack-jitm.php
* This fixes an issue where if one of the jitms in the response is a woo jitm from a hook, it would return a completely empty response instead of any other matching jitms. @Davidlenehan discovered today while building a new jitm.
Please cherry pick into release.
=> Fix where jitms may return an empty response where it shouldn't

json-endpoints/jetpack/class.jetpack-json-api-core-modify-endpoint.php
The `update` method is called without parameters within the endpoint, causing fatals on newer PHP versions.
cc @kraftbj
@dereksmart can we merge this into 6.0?
=> REST API: Core Update, fix fatal on PHP 7.1

modules/search/class.jetpack-search-helpers.php
Fixes #9101.
Strip slashes from `$_GET` when constructing the search URL.
1. Search for "_something_" with `something` being a term that'll result in search results.
2. Click on one of the filters.
3. Make sure the search term doesn't change, namely not to having the quotes escaped.
Fixes for searching for terms containing quotes.
=> Search: Strip slashes from search terms

_inc/client/at-a-glance/monitor.jsx, _inc/client/components/dash-item/index.jsx, _inc/client/components/dash-item/test/component.js, _inc/client/components/jetpack-disconnect-dialog/index.jsx, _inc/client/searchable-modules/index.jsx, _inc/client/security/index.jsx, _inc/client/security/monitor.jsx, modules/monitor.php
Closes #7484
Resolves partly https://github.com/Automattic/jetpack/issues/9086
- **Settings** → **Security**: add **Monitor** module toggle
- **Dashboard**: change button to a toggle
- Unify language used about the module:
- We've been using terms "Jetpack Monitor", "Uptime Monitor", "Downtime Monitor".  This unifies everything to be "Downtime Monitor". 
"Downtime Monitor" term is already used all over [Jetpack plans page](https://jetpack.com/pricing/) and [feature intro page](https://jetpack.com/features/security/downtime-monitoring/).
"Read more" link brings users to [Monitor's support page](https://jetpack.com/support/monitor/) which still needs updating. 
Similar change in Calypso: https://github.com/Automattic/wp-calypso/pull/23729
- Adds word "email" to where we speak about …
=> Security: add Monitor toggles to Jetpack and unify copy

docker/config/apache_default, docker/docker-compose.yml
Fixes error during Apache startup:
> Could not reliably determine the server's fully qualified domain name, using 172.22.0.5. Set the 'ServerName' directive globally to suppress this message
- Rebuild: `yarn docker:build`
- Up: `yarn docker:up`
- No error during installation and test accessing via localhost and proxied URL
=> Docker: set ServerName directive for Apache

_inc/client/components/settings-group/README.md, _inc/client/components/settings-group/index.jsx, _inc/client/searchable-modules/index.jsx
This PR:
- fixes issue with search where modules didn't display the help popover with the support link.
- fixes a warning in JS console since these searchable modules were passing a string instead of an object.
- updates the readme file for `SettingsGroup`
=> Settings: update searchable modules to accept the new object format

_inc/client/privacy/index.jsx, _inc/client/searchable-modules/index.jsx
Fixes a current issue where the new Privacy card surfaces on all search results, even if none are found.  
This adds a hard-coded list of search terms that will surface the card. Any ideas for more? 
To Test: 
- Make sure this card only surfaces when searching for the terms listed in the changeset.
=> Add custom search terms for the Privacy card

_inc/client/rest-api/index.js, _inc/client/state/at-a-glance/actions.js
#9165  only handled error-y API responses from a request for `general`  data. This PR handles error reponses for `month` and `week` data. 
* Updates the `getStats` redux action to not handle errors when requesting stats data.
* Moves error handling behaviour to the rest-api client.
* On a connected site with stats.
* Visit the dashboard
* Expect to see the general stats
* Switch to month and week view
* Expect to see the stats for the period
=> Admin Page: Stats - Fix default value for week and month stats query

_inc/lib/class.jetpack-search-performance-logger.php
The alt value is now set to a smiley, just like the main stats pixel (see r134484-wpcom).
This solves any HTML Validation errors reported on search pages.
Reported here:
https://wordpress.org/support/topic/html-validation-error-11/
=> Search: add alt attribute to stats pixel.

gulpfile.babel.js, package.json, yarn.lock
Previously we were ignoring gettext calls with context and calls with plural strings. This has caused many strings to not be available. This change overhauls the way we export strings from po files into JSON for client side usage and fixes the problem.
Huge kudos for @johnHackworth and @oskosk for bringing this to my attention!
* Instead of parsing jetpack-strings, modify it slightly and require it as JS, capturing gettext method calls.
* Run `yarn build-languages`.
* Use Jetpack settings with any language that we have close to 100% translations, you should see no untranslated strings where strings have been added some time ago, like in navigation, module descriptions and miscellaneous texts.
* Fixed translation handling to fully use community provided strings in the Settings area.
=> Fixes context usage in i18n in client side code.

_inc/client/privacy/index.jsx
Unless something happens quickly in p4H3ND-E6-p2, it looks like this URL won't be ready by Tuesday's release.  Prepping this to merge in case.
=> Remove references to privacy.blog

_inc/client/at-a-glance/stats/index.jsx, _inc/client/at-a-glance/stats/test/component.js
Alternate to #9190
This will show a spinner as we're retrieving data, rather than the "empty stats card", which is meant to be shown for empty stats, and for it to be dismissible. 
You should see this when the page is loading regardless if it has views or not: 
For a site with no views recorded, you should see the "empty stats card" as expected.
=> Dashboard Stats: render spinner/empty stats card correctly

.circleci/config.yml
Some of the node dependencies are missing in an old cache. This PR switching to a new cache file.
See CircleCI build is able to run tests. `env: ./node_modules/.bin/magellan: Permission denied` Error is not present in `test` job.
fix broken E2E tests CI cache
=> E2E tests: Get rid of old, invalid cache

_inc/class.jetpack-provision.php, class.jetpack-xmlrpc-server.php, tests/php/test_class.jetpack-xmlrpc-server.php
Previously, partners had to provision plans via CLI commands. The documentation for that can be found here:
https://github.com/Automattic/jetpack/blob/master/docs/partners/plan-provisioning.md
This works fine, but can be a bit awkward for some hosts to implement. This PR refactors so that hosts will be able to call to the WordPress.com API in order to provision a plan. Things get a bit interesting since the there is a bit of back-and-forth between the Jetpack site and WordPress.com, but we do that so that we don't require sending bearer tokens to and from the Jetpack site.
The testing instructions are "fun" and can be found on D11321, which this PR relies on. So please see that patch for the instructions.
At this point, I believe this PR is in a pretty good place. I'd like to follow-up …
=> CLI: Partner: Updates partner provisioning to allow REST API

docs/partners/plan-provisioning-direct-api.md
Previously, it was not practical for a partner to provision a plan by calling directly to the WordPress.com API. The issue was that the site needed to have registered with WordPress.com first.
As of #9178, there is a new endpoint that allows hosts to call directly to the WordPress.com API to provision a plan. This PR documents that endpoint.
=> Docs: Partners: Add documentation for provisioning plan directly

modules/google-analytics.php
Fixes https://github.com/Automattic/wp-calypso/issues/23936
* Allow Premium customers to activate Google Analytics
* Add Premium to a test site
* Try to activate GA
* Apply patch.
* Try again.
Resolve conflict preventing Google Analytics from activating for Premium subscribers.
=> GA: This feature is also available for Premium plans

class.jetpack-autoupdate.php
In PHP we use . instead of + when concatenating stings.
=> Jetpack Autoupdates: Removed php warning

_inc/client/state/modules/reducer.js, _inc/client/state/modules/test/selectors.js
Builds on the work introduced with #9168.
* Adds the selector `isModuleForcedInactive` which returns `true` if the module is forced to be active by a filter ad `false` otherwise.
* Adds the selector `isModuleForcedActive` which returns `true` if the module is forced to be inactive by a filter and `false` otherwise.
* Checkout to  this branch.
* Run `yarn test-client`.
* Expect the tests to pass.
=> Admin Page: Add isModuleForcedInactive and isModuleForcedActive convenience selectors

3rd-party/class.jetpack-modules-overrides.php, tests/php/3rd-party/test_class.jetpack-modules-overrides.php
After talking to @oskosk today, I realized that we weren't taking into account the `jetpack_active_modules` filters when calculating the modules that were forced active or inactive. This PR handles that.
To test:
- `phpunit --filter=WP_Test_Jetpack_Modules_Overrides`
=> 3rd Party: Add override support for jetpack_active_modules filter

tools/jetpack-live-branches/jetpack-live-branches.user.js
* The WP Rollback plugin allows one to test any old version of Jetpack (Any plugin actually).
* The WP Downgrade plugin allows on to test any old version of WordPress.
In combination they're super useful for double-checking user reports about something happening on old versions, and also for quickly confirming regressions and figuring out at which version the regressions was introduced.
* Adds the ability to launch a Live Branch site with the Gutenberg, WP Rollback and WP Downgrade plugins
* Click https://github.com/Automattic/jetpack/raw/add/some-features-to-tampermonkey-script/tools/jetpack-live-branches/jetpack-live-branches.user.js to get the new script version installed. 
* Visit a PR on this repo
* Expect to see three new checkboxes for Gutenberg, WP Downgrade and WP Rollback
=> Tools: Add Gutenberg, WP Rollback and WP Downgrade checkboxes to Live Branches Script

modules/sso.php
Fixes #9025 
Ensure that we are setting secure cookies when `is_ssl()` is true. 
To test:
- Checkout branch on site that is http
- Clear cookies
- Log in via SSO
- Log out
- Ensure that `jetpack_sso_*` cookies are set and are not secure
- Repeat the above, ensuring the cookie are secure
- Attempt to connect [Google Docs](https://chrome.google.com/webstore/detail/wordpresscom-for-google-d/baibkfjlahbcogbckhjljjenalhamjbp?hl=en) to one of your sites, logging in via SSO
=> SSO: Ensure cookie is secure if is_ssl() is true

docker/README.md
This PR updates the documentation to specify the right directory in the step that instructs the user to copy the `default.env` file to an `.env` file to modify it, since the one mentioned previously, `defaults.env` doesn't exist, but [default.env does exist](https://github.com/Automattic/jetpack/blob/master/docker/default.env).
=> Docker: update step when creating .env

docker/README.md, docker/bin/tail.sh, package.json
Creates the log file before attempting to `tail` it, preventing confusing errors.
Run:
```bash
rm -f ./docker/wordpress/wp-content/debug.log
yarn docker:tail
```
→ 💥 
> tail: cannot open '/var/www/html/wp-content/debug.log' for reading: No such file or directory
> tail: no files remaining
→  🕊 ✌️
=> Docker: create log file before tail

docker/config/wp-tests-config.php
Fixes database env vars to correct ones in wp-config used by phpunit.
Change that broke these was introduced with `.env` file in https://github.com/Automattic/jetpack/pull/9149
Note that `phpunit` uses `docker/wordpress-develop/wp-tests-config.php` — file I'm modifying is used as a template to create that file.
Run:
```
yarn docker:phpunit
```
Previously phpunit would fail. With the fix all good again!
```
yarn docker:phpunit
yarn run v1.3.2
$ yarn docker:compose exec wordpress phpunit --configuration=/var/www/html/wp-content/plugins/jetpack/phpunit.xml.dist
$ docker-compose -f docker/docker-compose.yml exec wordpress phpunit --configuration=/var/www/html/wp-content/plugins/jetpack/phpunit.xml.dist
Using test root /tmp/wordpress-develop/tests/phpunit
To run Jetpack woocommerce tests, …
```
=> Docker: fix env variables in phpunit setup

_inc/client/components/settings-card/index.jsx
The upgrade nudges for the SEO Tools and Google Analytics features show the plan icon for the professional plan, which is incorrect since those features require the premium plan. This PR fixes that.
Expand the code below each diff below and note that the conditional looks like this:
```php
if ( 'is-business-plan' === planClass || 'is-premium-plan' === planClass )
```
This logic is checking for whether we have a premium or professional. In other words, whether we have _at least_ a premium plan.
To test:
- On a site with the latest master and no plan, go to the `Traffic` tab of the settings page.
- Ensure that you see something like this:
- Checkout this branch on a site with no plan, then go to the `Traffic` tab of the settings page
- Ensure that you see something like this:
=> Admin Page: Correct plan icon in upgade nudges

docs/partners/plan-provisioning-direct-api.md
This PR adds some clarification around fetching a bearer token, specifically that we are interested in the `access_token` key returned form the `/oauth2/token` endpoint. This PR addresses that by mentioning it as well as updating the examples to fetch the `access_token` key.
Further, this PR also addresses some markdown lint warning that were coming up. 
The first commit contains the changes that mention `access_token` while the second commit contains the markdown lint changes.
=> Docs: Partners: Ensure that oauth2/token examples specify access_token

json-endpoints/class.wpcom-json-api-autosave-post-v1-1-endpoint.php
Merges r172745-wpcom.
Summary:
When editing a published custom post type like portfolios the preview would break on autosave. This was due to the wrong preview URL being sent to the front end which this change resolves.
Without the appropriate theme functions, the custom post types (& their redirects) do not get registered.
Further details: https://github.com/Automattic/wp-calypso/issues/22645
Test Plan was:
1. Starting at URL: https://wordpress.com/types/jetpack-portfolio
2. Select a site with Portfolios enabled (or enable them in the Writing settings on your site).
3. If you don't have any portfolio projects yet, create and publish one.
4. In the list of portfolio projects, select one to open it in the editor.
5. Before making any changes, select "Preview" to preview the project.
6. …
=> Code Sync: Autosave Post v1.1 endpoint - was wpcom-ahead

json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
Duplicates work of #9177.
* Syncs the `json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php` file from wpcom to Jetpack.
=> Code Sync:  Upload Media v1.1 endpoint - was wpcom-ahead

sal/class.json-api-post-base.php
Merges r172268-wpcom.
* Brings the latest changes from wpcom to Jetpack from the `sal/class.json-api-post-base.php` file
None needed
None needed
=> Code Sync: sal/class.json-api-post-base.php - was wpcom-ahead

sal/class.json-api-site-base.php, sal/class.json-api-site-jetpack-base.php
Brings these two files in sync with wpcom.  
Is a blocker for #9177 to merge
Pretty much just adds new methods, but a sanity check is appreciated. 
The wpcom-side changes have been merged in 
r172582-wpcom
r172580-wpcom #
=> Code sync: bring divergent SAL files in sync

sync/class.jetpack-sync-defaults.php, tests/php/sync/test_class.jetpack-sync-options.php
Adds a set of basic options to whitelist that are safe to sync:
- no filters
- simple enough content
These would all be used for capturing events for the Activity Log.
Change these settings in your WP admin interface and observe them get synced.
- 'start_of_week' → In general
- 'blacklist_keys'  → In discussion
- 'posts_per_page'  → In reading
- 'posts_per_rss'  → In reading
- 'show_on_front'  → In reading (radio button)
- 'ping_sites'  → In writing ("Update services")
- 'uploads_use_yearmonth_folders'  → In media
- 'date_format' → In general
- 'time_format' → In general
Tests pass:
```
phpunit --filter=WP_Test_Jetpack_Sync_Options
```
=> Options: add basic options to sync whitelist

modules/masterbar/masterbar.php
Firest removed in Calypso in https://github.com/Automattic/wp-calypso/pull/23952
Then removed on .com in D11711-code
This PR brings things in line.
Before:
After:
load jetpack with the mastebar
Notive that the section Next Steps is gone.
*
=> Masterbar: Remove the Next Steps link

class.jetpack-xmlrpc-server.php
Currently, the `jetpack.remoteProvision` XML-RPC method is guarded by a nonce that is verified by calling back to WordPress.com. This PR seeks to add an extra layer of security by forcing the XML-RPC request to be authenticated when this site is connected to WordPress.com. 
This patch requires D11321
To test:
- Follow testing instructions on D11780 and D11321
=> JPS: XML-RPC: Require authentication of jetpack.remoteProvision when site connected

modules/protect.php
Since a lot of third party services relied on this be able to connect and were blocked as a result of failed login attempts we decided to revert the PR. The services will still eventually get blocked but not as quickly as they were before.
If someone want to harden their XMLRPC login they can use the following code instead.
```
add_filter( 'jpp_use_captcha_when_blocked', 'jetpack_no_captia_on_xmlrpc_requests' );
function jetpack_no_captia_on_xmlrpc_requests($allow_math_fallback) {
if( Jetpack_Constants::is_true( 'XMLRPC_REQUEST' ) ) {
return false;
}
return $allow_math_fallback;
}
```
More Context: p1HpG7-51K-p2
Reverts https://github.com/Automattic/jetpack/pull/8855
=> Protect: Revert XML RPC request should get hard blocker quicke

sync/class.jetpack-sync-sender.php, tests/php/sync/server/class.jetpack-sync-server-eventstore.php, tests/php/sync/test_class.jetpack-sync-sender.php
Currently if there is nothing to send and only things to skip we would be clearing the info from sometimes on the successful syncs. but if we were only dealing with skiped items the sync queue would get stuck and would not clear anything.
This PR make sure that we clear skipped items when there is nothing to send. 
And also not try to talk to .com if there  is nothing to send. 
cc: @lezama
=> Sync: Bug fix empty the queue if there is nothing to send and only skip

_inc/client/at-a-glance/plugins.jsx, _inc/client/components/dash-item/style.scss, _inc/client/scss/variables/_colors.scss
Fixes #9196
Screenshot:
* Add more consistent layout and neat border to dash numbers
* Build Jetpack
* Go to dashboard
* Should look like screenshots in #9196
=> Add border and new layout to dashboard numbers

class.jetpack.php, jetpack.php, modules/shortcodes.php, modules/shortcodes/slideshow.php, tests/php/test_class.jetpack.php
This introduces a filter that can be used to override Jetpack trying to load minified assets. It also introduces a constant that replaces the path used to enqueue assets for shortcodes. This is the proposed approach to handle other assets as well.
=> Changes the way Jetpack handles asset paths based on environment.

tools/jetpack-live-branches/jetpack-live-branches.user.js
* The [Code Snippets](https://en-gb.wordpress.org/plugins/code-snippets/) plugin allows us to add custom code to test PRs that would require small snippets of filtering or hooking to review a PR.
* Adds the ability to launch a Live Branch site with the [Code Snippets plugin](https://en-gb.wordpress.org/plugins/code-snippets/).
* Click https://github.com/Automattic/jetpack/raw/add/code-snippets-feature-to-tampermonkey-script/tools/jetpack-live-branches/jetpack-live-branches.user.js to get the new script version installed. 
* Visit a PR on this repo
* Expect to see a checkbox for Code Snippets.
=> Tools: Add Code Snippets checkbox to Live Branches Script

_inc/lib/markdown/extra.php
This regex does not work properly. 
Reported by @mdawaffe  in D11859-code
> Inside the create_function() call, there needs to be an extra level of slashes. That level was not removed when the function was pulled out of the create_function() call.
To Test: 
```
php > var_dump( preg_match_all( "/[\\\\x00-\\\\xBF]|[\\\\xC0-\\\\xFF][\\\\x80-\\\\xBF]*/", 'hello', $m ) );
int(0)
php > var_dump( preg_match_all( "/[\\x00-\\xBF]|[\\xC0-\\xFF][\\x80-\\xBF]*/", 'hello', $m ) );
int(5)
```
or 
```
<?php
function jetpack_utf8_strlen( $text ) {
return preg_match_all( "/[\\\\x00-\\\\xBF]|[\\\\xC0-\\\\xFF][\\\\x80-\\\\xBF]*/", $text, $m );
}
var_dump( jetpack_utf8_strlen( "Hello" ) ); // should be 5
```
=> Markdown: fix jetpack_utf8_strlen regex

sync/class.jetpack-sync-defaults.php, tests/php/sync/test_class.jetpack-sync-options.php
Adds `new_admin_email` and  `admin_email` options to sync whitelist.
These are for the "admin email address" field in `/wp-admin/options-general.php`
Not for user email of the WP account.
`new_admin_email` is used temporarily when changing email:
Changing emails can sync out events like these:
```
'added_option'
(
[0] => new_admin_email
[1] => ipsum@example.com
)
'updated_option'
(
[0] => new_admin_email
[1] => ipsum@example.com
[2] => ipsum2@example.com
)
'updated_option'
(
[0] => admin_email
[1] => lorem@example.com
[2] => ipsum@example.com
)
'deleted_option'
(
[0] => new_admin_email
)
```
- Change site admin email from `/wp-admin/options-general.php` and confirm it.
- Observe events sync
- Tests should pass: `phpunit --filter=WP_Test_Jetpack_Sync_Options`
=> Sync: add admin email options to sync whitelist

modules/wordads/wordads.php
* Remove dns prefetch for scripts that are no longer used on the ad server.
=> WordAds: remove dns prefetch for scripts that are no longer used

class.jetpack.php
After https://github.com/Automattic/jetpack/commit/d2fc8b97de7c082e6c512455b6a0412b37dfa25c , some sites were seeing warnings:
```
Warning: in_array() expects parameter 2 to be array, null given in 
/home/public_html/wp-content/plugins/jetpack/class.jetpack.php on 
line 1518
``` 
It appears we should be setting a default `array('free')` if there are no headers present, so I am not sure _where_ this failure is coming from. This would prevent the warning.
cc: @gravityrail
=> Modules: Confirm array is present

modules/shortcodes/mixcloud.php
WP.com previously switched from iframe embed to oEmbed, which also switches over to https support.
Fixes #9006 
Update: Mixcloud shortcode now uses oEmbed.
=> Shortcodes: Sync Mixcloud with WP.com

_inc/client/components/module-settings/module-settings-form.jsx
Fixes where we send some props with `-` in them, where it's required they be snake_case. I'm not sure this is the *best* approach, but I didn't want to change a bunch of things to expect snake_case. This seems like the *best low-impact* change and the performance hit is negligible.
Please cherry pick into a release if possible. Currently, this event is being rejected in some cases: see p4qSXL-2De-p2 comment-7252 for more information.
* Do not send `-` in a prop.
* Ensure when toggling the Infinite Scroll setting, that it sends an event with snake_case.
N/A
=> Replace -'s with _'s

modules/sitemaps/sitemap-builder.php, modules/sitemaps/sitemap-librarian.php, modules/sitemaps/sitemaps.php
Sorry to lump what is three different changes into a single PR. I can break these apart if that's preferable. However, for the sake of clarity I wanted to first show how this syncs with upcoming changes in D11614-code. See References below.
- D11614-code (diff pending review)
- D11616-code (depends on these changes)
- p9f5aF-ud-p2 (requested here)
- For video sitemaps, pull all attachments with a MIME type that begins
with `video/`, instead of specific MIME types. We were currently missing
`video/mp4` and `video/quicktime`, so this fixes that by including
all `video/*` MIME types.
- ☝️ The same for `image/*` MIME types.
- Fixes: https://github.com/Automattic/jetpack/issues/9254 by returning `true` when finished, instead of `die()`ing.
- Adds a new filter: `jetpack_page_sitemap_other_urls` …
=> Bring Jetpack Sitemaps in sync w/ upcoming dotcom changes

class.jetpack-idc.php
Since VaultPress and Jetpack both rely on the URL and key being correct, and since we're already clearing out an IDC situation when the site cycles the connection, let's go ahead and cleanup the VaultPress connection options as well.
`Jetpack_IDC::clear_all_idc_options()` is currently called whenever the site connects or disconnects, so it seems like a good place to put the VaultPress options check. But, for a Jetpack IDC, to delete the IDC options, we don't care if the site is in a current IDC. If the connection is updated, we just flush. 
So, to keep from clearing out the VaultPress connection every time the Jetpack connection is cycled, this PR also adds a check to make sure the site is in an IDC before clearing out the VaultPress connection options.
To test:
- Check this PR out on a …
=> IDC: Clear VaultPress options when in IDC and Jetpack connection cycled

json-endpoints/class.wpcom-json-api-list-media-endpoint.php, json-endpoints/class.wpcom-json-api-post-endpoint.php, json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php, json-endpoints/class.wpcom-json-api-render-endpoint.php, sal/class.json-api-site-base.php
=> Revert suppress filters for json-api

_inc/class.jetpack-provision.php, class.jetpack-xmlrpc-server.php
Since these strings are returned in an API response, and not echoed to the browser, it's not necessary that they be escaped. Escaping these strings also results in this output in the API:
> The required &quot;siteurl&quot; argument is missing.
This PR chooses to replace `esc_html__()` with `__()` for partner provisioning of plans since those strings will be returning via the API or by WP-CLI.
To test:
- Checkout PR
- Follow the docs [here](https://github.com/Automattic/jetpack/tree/master/docs/partners) to make a request to the API, ensuring that you leave off the siteurl or local_username args
- Ensure that response comes back with `"` instead of the escaped `&quot;` equivalent
=> JPS: Do not escape translated strings since they are not echoed

sync/class.jetpack-sync-defaults.php, tests/php/sync/test_class.jetpack-sync-options.php
Adds `default_email_category`, `page_for_posts` and `default_role` to whitelisted options to sync.
Changes will be shown at the Activity Log.
- Modify **New User Default Role** from `/wp-admin/options-general.php`
- Modify **Default Mail Category** from `/wp-admin/options-writing.php`
- Modify **Homepage**  from `/wp-admin/options-reading.php`
→ Observer these get synced.
→ Tests pass: `yarn docker:phpunit --filter=WP_Test_Jetpack_Sync_Options`
=> Sync: add more options to the whitelist

modules/widgets/top-posts.php
Brings in latest changes from .com version
* Makes the URL be either jetpack.com or wordpress.com based depending on the `IS_WPCOM` constant
Nothing to test. confirm the change is straightforward.
=> Code Sync: Top Posts Widget - was divergent

_inc/lib/class.core-rest-api-endpoints.php
Fixes https://github.com/Automattic/jetpack/issues/9279
This PR adds a locale param to the plans info request. At the moment we are not passing any locale info, so the plans tab is always being rendered in English, no matter the language of the user
0. Change the language of your site to any other than English
1. Clean the transients (`wp-cli transient delete-all`)
2. Go to your Jetpack dashboard and click on the plans tab. The plans information should be in the same language you selected in 0.
=> Fixes the internationalization of the plans tab

json-endpoints/class.wpcom-json-api-get-comment-counts-endpoint.php
The response is a "bare" object - no nesting.
This also brings the code inline with the code running on WordPress.com.
Example response:
```
{
"all": 0,
"approved": 0,
"pending": 0,
"trash": 0,
"spam": 0,
"post_trashed": 4,
"total_comments": 0
}
```
1. `curl --dump-header /dev/stderr -H "Authorization: Bearer $YOUR_BEARER_TOKEN" "https://public-api.wordpress.com/rest/v1/sites/$YOUR_SITE_ID/comment-counts?pretty=1"`
2. Verify the output doesn't change between patched and unpatched :)
Because of how the `response_format` is used in Jetpack code, there should be no change in behavior.
=> Comments: Fix counts endpoint's response format

class.jetpack-post-images.php
Sync a commit to this file from wpcom that does the following: 
Warnings/Post Images: Don't try and carry on extracting images from a slideshow we failed to parse.
- Fixes a `Invalid argument supplied for foreach()` warning.
=> Slideshow: fix warnings (wpcom merge)

3rd-party/woocommerce.php
This PR removes the sharing and like display functionality from CART, CHECKOUT, and ACCOUNT pages which are pretty much useless in these contexts.
Based on code in the 2016 theme file within Jetpack, and with the woocommerce compatibility file.
Requested here: https://github.com/woocommerce/woocommerce/issues/19687
To test:
1. Enable sharing and/or like buttons on a site running WooCommerce.
2. Go to a regular page. Confirm sharing is displayed.
3. Add something to cart. Go to cart. Confirm sharing is NOT displayed.
4. Proceed to checkout, again sharing should be hidden.
=> jetpack_woocommerce_remove_share function to remove sharing display on cart pages.

modules/sharedaddy/sharing-sources.php
The Sharing module includes handy functions for determining the 'via' and 'related' Twitter accounts. By making these functions static, we can allow other plugins to utilize these functions.
Example: https://github.com/automattic/co-authors-plus-social-pack filters both the via and related values. Twitter will only show two related accounts after submitting a tweet via the Sharing module, which if the `via` and the first value of `related` are the same account will then show the same account twice.
The most straightforward way to avoid this is to check what is being used as the "via" and to be sure to exclude that from the "related" set, which would be great to do via the same functionality Jetpack is using.
Additionally, accept a post ID in addition to a post object.
=> Sharing: Make via/related functions static for outside use

modules/gravatar-hovercards.php, modules/widgets/gravatar-profile.php
Fixes 1820-gh-jpop-issues
It's not useful to conditionally load those over HTTP anymore. It only creates issues from time to time, for sites with a redirection from HTTP to HTTPS but not actually using HTTPS in the site settings.
* Add a Gravatar Profile widget to your site's sidebar.
* Make sure it works.
* Check comments on a page where that widget is not there.
* Make sure Gravatar Hovercards are triggered and work.
* Gravatar Hovercards: always load script via HTTPS.
=> Gravatar: always use HTTPS to query images

modules/publicize/assets/publicize.css, modules/publicize/assets/rtl/publicize-rtl.css, modules/publicize/ui.php
The publicize disconnect buttons on the Sharing page currently have a cursor css property with a value auto applied, which probably wasn't intended. When properly implemented by the browser vendor (like in a release version of Firefox or Chrome 63+), cursor: auto on a text link must display the so called text selection cursor according to the CSS specification.
Additional reading (incl. comments by some browser vendors): https://github.com/w3c/csswg-drafts/issues/1598
Official CSS test: https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-auto-002/format/html5/
* Remove the cursor css property for the publicize disconnect buttons in the publicize.css and publicize-rtl.css files.
* Compare the cursor when hovering a publicize disconnect button in Firefox or Chrome 63+ and any …
=> Publicize: remove cursor css property from publicize disconnect button

modules/publicize/publicize-jetpack.php
Fixes https://github.com/Automattic/msm-sitemap/issues/118
When a post transitions to `publish`, Jetpack adds Publicize post meta to all posts, whether or not it is a publicize-able post type.
Testing:
* Setup Jetpack + Publicize
* Add a new CPT that is not able to be Publicized (e.g. lacking `post_type_support('publicize')`).
* Publish a post.
* Inspect the post meta and see `_publicize_pending` with value of 1.
* Apply patch and repeat. No `_publicize_pending` present.
=> Publicize: Return out early for non-Publicize CPTs

modules/likes/jetpack-likes-master-iframe.php
The style.css loaded from the widgets.wp.com Likes iframe was cached with an outdated version, resulting in a duplication of the "Like" star (see screenshot).
The issue is already resolved on widgets.wp.com, but Jetpack keeps loading an older version.
Testing Plan:
* Load a post with Likes on, observe the double-star.
* Apply patch.
* Reload and confirm no double-stars.
h/t Cody in 1096146-z for the report.
=> Likes: Bust the likes iframe cache

_inc/lib/class.media-summary.php
Fixes #8420
Fixes #9209
Complement of #8510
Supports #8156
In PHP 7.2, warnings are thrown, in the end, because we are attempting to apply `get_the_excerpt` filters without being within the Loop. While Core makes it seem like this should work, it doesn't. (see #8510 for PR that would require Core changes to work as I think it should). 
In this PR, we override the `$post` global and setup the post data so the excerpt and underlying functions work as intended.
We're overriding the `$post` since this function does not presume to operate within the Loop, so we need to fully mock the Loop.
* Jetpack + Sharing (or any module that outputs OG tags) on PHP 7.2
* Open a post without an explicitly set excerpt.
* Observe PHP warnings are reported in #8420.
* Apply patch.
* Confirm excerpt is set in …
=> Media Summary: Setup postdata for obtaining the excerpt

modules/widgets/social-icons/social-icons.css
Modern themes must include this snippet nowadays:
https://make.wordpress.org/themes/2015/01/26/supporting-screen-reader-text/
Jetpack must remain compatible with non-modern themes, so let's include the snippet
with the Social Icons widget, since it relies on this CSS class.
Reported here:
https://twitter.com/RebaBaskett/status/981211671111913472
https://twitter.com/davezatz/status/981310446522249216
* Social Icons Widget: bundle support for screen reader text for themes that do not provide support out of the box.
=> Social Icons: bundle screen reader text CSS class.

modules/widgets/gravatar-profile.php
Fixes A small syntax thing that was introduced in #8976. 
* Removes trailing comman from line 355 of `modules/widgets/gravatar-profile.php`.
* A site with current master and should be WSODing right now.
* Confirm that this fix brings it back.
=> Widgets: Gravatar Profile - Remove trailing comma from last function call parameter in Gravatar Profile Widget

functions.global.php, sync/class.jetpack-sync-json-deflate-array-codec.php, sync/class.jetpack-sync-module.php, tests/php/sync/test_class.jetpack-sync-callables.php
Lets add recusion proteccion to our get_checksum call.
Fixes #7501
* We removed most of the calls functions that return in whole objects ( get_post_types ) so this shouldn't in theory be needed. 
Do the tests pass?
=> Jetpack Sync: remove recursion from checksum call

sync/class.jetpack-sync-module-updates.php
Fixes #7297
Throws an error as and adds some simple checks to make sure that we are dealing with arrays as expected before iterating over them. 
Do the test pass?
=> Sync: Add Array checks in the updates modules

modules/contact-form/grunion-contact-form.php, sync/class.jetpack-sync-module-posts.php, sync/class.jetpack-sync-wp-replicastore.php, sync/interface.jetpack-sync-replicastore.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/server/class.jetpack-sync-test-replicastore.php, tests/php/sync/test_class.jetpack-sync-meta.php
Performance optimization: Instead of sending 100s of delete post meta events we send only 1. That tells us to bulk delete the post_meta for the array of post_id supplied. 
* Stop sending individual post meta events. 
* send 1 bulk post meta event.
- Do the tests pass?
- Trigger a daily cron event via a cron plugin. 
- Do you see any errors? 
- The .com side still needs to be implemented for this.
=> Sync: Do bulk delete of post meta on daily akismet cleanup

class.jetpack.php, tests/php/test_class.jetpack.php
As reported in p73hgi-JQ-p2 , if a non-bool falsely response is returned from `is_development_mode`, Calypso will output it.
When writing `is_development_mode` the expectation was a bool response, so let's force that to prevent unintended usage of the constant/filter.
=> Dev Mode: Force bool on is_development_mode

_inc/client/privacy/index.jsx
This change reflects some minor copy updates.
Details:
* Add “the” in front of “Automatic Privacy Policy”.
* Note that the “What Data Does Jetpack Sync” is a support document.
* Move the “?” character into the linked area, since it’s part of the
document’s title.
Testing:
* Go to the Privacy section in the dashboard of any Jetpack site.
* Confirm that the updated copy appears and that both links work as
before.
=> Privacy Settings: Update the accompanying copy.

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
This PR adds support for the new Google My Business integration soon to be available on WordPress.com.
Technically, it defines 2 new site settings, `google_my_business_keyring_id` and `google_my_business_location_id`, which allows a site to be linked to a Google My Business location.
- `google_my_business_keyring_id` is the id of the Keyring entry on wpcom which gives us access to the GMB api.
- `google_my_business_location_id` is the id of the location on the Google My Business API side.
- Requires WPCOM patch D11870 and `public-api.wordpress.com` sandboxed
- Requires a jetpack site connected to WordPress.com for which you are admin (`manage_options` privilege)
- Requires this jetpack site to have this patch applied
- Requires a Google account with at least 1 Google My Business location …
=> Update site settings enpdoints to support Google My Business integration

modules/shortcodes/class.filter-embedded-html-objects.php
A little bit more defensive coding to avoid a hard fatal when the class is not present. Seen in support ticket 1037952-zen .
Not a blocker for 6.0 release.
=> Shortcode: Specifically check for DOMDocument

modules/wordads/wordads.php
Removing Acceptable Ads from Criteo since we are not using those any more.
For now we will not be showing any ads to browsers with adblockers.
* Remove Acceptable Ads from Jetpack Ads.
* Visit any page loading Jetpack ads with adblocker turned on. Before it would try to show ads from Criteo's Acceptable Ads, but it might show empty ad units.  After the change it shouldn't display any ads at all.
=> WordAds: Remove Acceptable Ads

_inc/client/traffic/ads.jsx
The purpose of this PR is to make sure Jetpack ads module users know they can place additional ads via the Ads widget.
* Adds help text below the `Additional ad placements` header alerting them that the Ads widget is an available option. This will only display when the Ads module is turned on - otherwise the Ads widget is not available, and users clicking the CTA would result in a poor ux.
* Using a Jetpack site with premium or pro plan, enable the Ads module and make sure the Ad widget message displays. A sample of what this should look like is shown below.
=> WordAds: promote Ad widget within WordAds settings card

modules/widgets/social-icons.php
Fixes: #9234
It seems that we're not scoping js in this way on other widgets.
* Removes the check to see if we're on the customizer or the widgets page before enqueuing the admin form for the Social Icons Widget
* Starting with a connected Jetpack site
* With a plugin like [Page Builder](https://wordpress.org/plugins/siteorigin-panels/) that allows to add widgets from a page different than the customizer or the widgets one.
* Attempt to add the Social Icons widget on a page.
* Confirm that you can add and remove icons (JS-powered behaviour).
=> Widgets: Social Icons - Load admin form supporting javascript without scoping it to the customizer or the widgets page

modules/carousel/jetpack-carousel.php
If we set data-* attributes from a different ID we end up setting them with random incorrect data, and break new post notifications.
Test Plan: Make sure we still get the data- when we expect it
Reviewers: georgestephanis, dereksmart
Reviewed By: dereksmart
Differential Revision: D11942-code
This commit syncs r174008-wpcom.
=> Don't set data-* attributes if the ID in the HTML isn't for an attachment on this site.

modules/stats.php
Replay of #3798, as it got rather stale.  
This adds a filter `jetpack_honor_dnt_header_for_stats`, which if enabled would not track stats for visitors with DNT enabled.  
This is different from 3798 in that it does NOT provide a UI for enabling this.  We may revisit adding one in the future, but for now this will suffice.  It also namespaces the function. 
props @perillamint for their initial PR
=> Add filter for honoring DNT support for Stats

modules/theme-tools/content-options/featured-images.php
Fixes #8835.
* Added a function that checks if WooCommerce Shop page is being displayed. It's a copy of a function we include in our WooCommerce compatible themes.
1. Activate a theme that supports Content Options, for example Lodestar or Shoreditch.
2. Activate WooCommerce and add a few products.
3. Go to Customizer > Content Options and make sure "Display on blog and archives" under Featured Images is checked.
4. Visit Shop page - the product images should be visible. Visit blog page - the featured images should be visible.
5. Go to Customizer > Content Options and uncheck "Display on blog and archives" under Featured.
6. Visit Shop page - the product images should be visible. Visit blog page - the featured images should not be visible.
7. Deactivate WooCommerce and check if Content …
=> Content Options: Add a check for WooCommerce Shop page in order to exclude it from the is_archive check

_inc/client/components/settings-card/index.jsx, _inc/client/state/site/reducer.js, _inc/lib/admin-pages/class.jetpack-admin-page.php, _inc/lib/admin-pages/class.jetpack-react-page.php, class.jetpack-admin.php, class.jetpack.php
This PR adds a check to see if WordAds are available even on the free plan based on the response we're getting from WordPress.com. Companion diff D11633-code.
* Fixes a small reducer inconsistency in site state.
* Moves the features to be stored inside the plan state, to be consistent with the format they are now returned from WordPress.com.
* Unifies supported feature checks by using `Jetpack::active_plan_supports` where we need feature checks.
* Removes additional plan checking on every admin page load, leaves only existing heartbeat plan refreshing.
* Makes sure the WordAds module is not greyed out in the legacy settings page.
* Adds a Settings UI check for Ads feature.
* Use the `JETPACK__WPCOM_JSON_API_HOST` to point your Jetpack site to your sandbox for API calls.
* Use D11633-code. …
=> Added a check for WordAds feature.

functions.opengraph.php
Fixes #9302 
* Adds a closing HTML comment to help readability of what plugin added what to a page's head.
* Apply patch with Jetpack active and the Sharing module enabled (as one that would enable Jetpack OG tags).
* View Source and confirm both an opening and closing html comment surrounding the OG tags.
=> Open Graph: Add closing comment to OG tags

modules/google-analytics/classes/wp-google-analytics-universal.php, modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php
When filtering the remove cart URL, we don't want to make any changes to the URL itself; we only want to add additional attributes if needed.
Fixes issues when the remove cart link was broken when the Product ID was missing from the cart item and Woo Analytics was adding it.
1. Start with a Woo site with a Jetpack Professional plan.
2. In Calypso > Settings > Traffic, enable Google Analytics and all its options.
3. On your site, add products to your cart.
4. Go to the cart page.
5. Make sure that all remove from cart icons work, and include the product ID attribute.
* WooCommerce Analytics: fix broken remove from cart link.
=> WooCommerce Analytics: always return a properly formatted URL.

modules/custom-post-types/comics.php
Fixes #7590
* Syncs r174050-wpcom by removing Omnisearch from comic custom post type
=> Comic Custom Post Type: remove omnisearch

_inc/lib/class.core-rest-api-endpoints.php, class.jetpack.php
Fixes https://github.com/Automattic/jetpack/issues/9169
This PR changes how we retrieve the plans tab info, so it has the connected WordPress.com user into account when dealing with localization. Up to this point, we were trying to use IP geolocalization and it wasn't working so well.
It also removes the plans info caching: If the user changed their WordPress language, we were still showing the cached plans info in the previous language.
How to test:
=========
1. go to your Jetpack dashboard and click on plans
2. You should get the plans' prices in the same currency your connected wpcom user gets the prices in the wpcom store
3. Change your WordPress language 
4. Go back to your jetpack dashboard and select 'plans' ... you should get the plans info in the new language.
=> Fix user currency

_inc/client/traffic/ads.jsx
Fixes https://github.com/Automattic/jetpack/pull/9310#discussion_r183578279
* Switch tracks event to use underscores instead of hyphens.
Tracks event was added in https://github.com/Automattic/jetpack/pull/9310 (6.1)
=> WordAds: rename tracks event to use underscores over hyphens

modules/wordads/php/api.php, modules/wordads/wordads.php
* On Jetpack Ads sites, automatically build an ads.txt file using content from the API.
* Apply the patch in D12055-code to your sandbox and sandbox the api
* Before applying this patch
* visit `/ads.txt`. You should see a 404.
* After applying this patch
* Turn on the Jetpack Ads module
* Visit `/ads.txt`. You should now see a text file.
* Adds ads.txt support to the Ads module.
=> WordAds: Add ads.txt support

_inc/client/writing/custom-content-types.jsx
Fixes PropTypes  warning: ` Invalid prop `support` of type `string` supplied to `SettingsGroup`, expected `object`.`
* Reverts a consequence of merging #8934 which stepped over changes introduced by #9137
* Build admin page
* Visit Settings.
* Confirm no red warning is shown.
=> Admin Page: pass object instead of string to SettingsGroup component for custom content-types settings

class.jetpack.php
Fixes error on fresh sites when plan data is not loaded yet on the site
* Adds the keys `feature` and `[feature][active]` to the boilerplate array returned by `Jetpack::get_active_plan()`
* Start with a fresh site and before connecting Jetpack:
* Enable `WP_DEBUG` and `WP_DEBUG_LOG` so you can make sure you see errors being logged if any.
* Connect Jetpack and get a paid plan
* When getting back to the wp-admin of your site, check the `debug.log` file and confirm you don't see an error coming from line `1552` of `class.jetpack.php`
=> General: Fix error when jetpack_active_plan is empty

_inc/client/components/dash-item/style.scss
@rickybanister this is about the best I can do here. If we want this to look good on all screen sizes, we'll need to stack the number like before. With this rendition the label is capped at 60% width and will wrap when the number is too big. It's not ideal, but I'm not sure what else to do. This might look not great on tiny screens. Let me know what you think.
=> DashItem - fixes count to wrap when numbers are too long or on smaller screen sizes

modules/theme-tools/compat/twentysixteen-rtl.css, modules/theme-tools/compat/twentysixteen.css
Adds social icons widget support from r157421-wpcom and r157430-wpcom.
Test Plan:
Visually verify that Twenty Sixteen theme's Social Icons widget support matches WPCOM version.
=> Fusion: Twenty-Sixteen Social Icons Widget support

_inc/client/security/monitor.jsx
This is a follow-up to work already merged in https://github.com/Automattic/jetpack/pull/9199. This adds the missing support info icon for Downtime Monitoring -- reported in p8oabR-c9-p2
* Adds missing support info icon for Downtime Monitoring.
* Check for the existence of this icon for Downtime Monitoring.
* Screenshot below.
=> Add missing support info icon for Downtime Monitoring

sal/class.json-api-site-jetpack.php
* Update the SAL to return the current WordAds module status (instead of returning false).
=> WordAds: Return WordAds module status through SAL

modules/shortcodes/wordads.php, modules/wordads/wordads.php
This PR updates the Jetpack Ads shortcode name from `[wordad]` to `[wordads]`.
=> Update WordAds shortcode name

json-endpoints/class.wpcom-json-api-list-post-type-taxonomies-endpoint.php
r146417-wpcom - has tests on .com side.
=> WPCOM merge: list post type taxonomies endpoint

modules/wordads/wordads.php
If a site owner uses widgets or shortcodes to add more than 6 ads per page, we automatically shut off rendering after the 6th ad.
The header ad renders after any ads in the post body added via shortcodes. This PR updates the ad limit to 5, allowing for the header ad to be included as the 6th ad.
* Update the limit to 5 ads + a header ad.
On a site that was approved for WordAds > 24hrs ago, add 12 wordads shortcodes to the body, and make sure that header ads are turned on in Jetpack > Settings > Traffic.
Without the patch, the header ad will be missing.
With the patch, the header ad will display.
=> WordAds: prioritize header ad display when hitting 6-ad limit

modules/wordads/php/widgets.php, modules/wordads/wordads.php
Fixes issue with ads not rendering because the `sectionId` param is required by the ad server.
* Reinstate the previously used `sectionId` parameter.
* Using a site that was approved for wordads > 24hrs ago, test ad rendering on the front end.
* without the patch, all ad slots will be blank
* with the patch, ad slots will be present :)
Sites approved for wordads <= 24hrs ago will show house ads by default, so testing with these types of sites will result in a false positive.
=> WordAds: reinstate sectionId param needed for ads rendering

modules/lazy-images/js/lazy-images.js, modules/theme-tools/compat/twentysixteen.php
In #8879 it was reported that outdented images were broken in cases where the CSS class was applied after the initial page loading. In TwentySixteen, this seems to be because when the initial `1x1` image loads, it wasn't meeting the condition that it be below the entry meta content.
The first part of a fix here is to fire an event when we lazy load an image, which will allow themes and plugins to better integrate with Lazy Images.
I wasn't able to reproduce the multiple network requests that @PatTheMav reported in that issue. Based on his testing though, it seems possible that the issue was because we were calling `image.setAttribute()` on the image in the dom. What I've tried to do in this PR is to clone the original image, update the attributes, and THEN replace the original image with …
=> Lazy Images: Add jetpack-lazy-loaded-image event

_inc/client/main.jsx
Fixes issue with Some settings tab being disallowed for users that can manage modules but cannot connect site. 
Context: p9zhOE-8J-p2
* Moves the check for connection permissions right before we attempt to show the connect card
* Either check on VIP Go sandbox or update [class.jetpack-react-page.php#L398](https://github.com/Automattic/jetpack/blob/master/_inc/lib/admin-pages/class.jetpack-react-page.php#L398) by hand to set `connect` to `false`.
* With an admin user  attempt to visit the "Discussion", "Security", or "Traffic" tabs. Confirm that you're able to do it .
* Visit Jetpack's dashboard an confirm you can't see the "Manage site connection" link on the Connection Card. Should look like:
=> Admin Page: Check for connect permissions a bit later for hiding connection Banner

class.jetpack.php
Previously the stored plan could have been restored improperly from cache, or did not have an expected property because it was retrieved before WordPress.com changes took effect.
This PR introduces defaults for every plan, not just free, plus fixes a problem when the global plan cache was incorrectly populated.
* Properly checks the global variable where the plan cache was stored.
* Introduces defaults for every plan, not just free plan.
* Sandbox your site, make sure you're receiving the old plan without the features array. To do that you can comment out the line in the `get_plan` method of the `trait.json-api-site-wpcom.php` file.
* Observe warnings.
* Roll this PR on, see no more warnings.
* Make sure the site works properly with paid plans - i.e. all promoted features should be …
=> Fixed missing expected plan properties.

modules/wordads/wordads.php
The ads.txt file introduced in 6.1 is currently not using any sort of caching.
This PR puts the ads.txt contents into a transient expiring daily.
This will result in only 1 api call to the server for the ads.txt contents per day.
* Set a transient `jetpack_ads_txt` containing the ads.txt contents - expires daily.
On a jetpack site with wordads enabled:
* run the following wp-cli command: `wp transient get jetpack_ads_txt`. You should see a warning that the transient is not set.
* visit `/ads.txt` on the site. You should see ads.txt contents displayed.
* re-run the following wp-cli command: `wp transient get jetpack_ads_txt`. You should now see the same ads.txt contents echo'd in the console.
* and for good measure, once again visit `/ads.txt` on the site. You should see ads.txt contents …
=> WordAds: update ads.txt to pull from daily transient, falling back to api call

modules/markdown/easy-markdown.php
This reverts commit dc18c8453d744548efb42682bc1fc606e2e9780f.
This last minute revert fixes error in console (`tinymce is not defined` )
coming from the changes introduced in #9366 with  https://github.com/Automattic/jetpack/pull/9366/files#diff-c8a16334ab363043643dab428095f818R453
=> Revert "Code Sync: sync easy-markdown.php - was divergent (#9366)"

modules/carousel/jetpack-carousel.js
=> Resolve divergence in file: whitespace 

modules/custom-css/custom-css.php
This syncs the change in r169244-wpcom : fixes a fatal error in PHP 7.2
=> Modules: resolve divergent custom css change

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
This is pretty straightforward after sorting through diffs and changes, it's wpcom-specific code and the `net_neutrality` setting (also wpcom-specific).
The `net_neutrality` stuff doesn't strictly have to go into Jetpack, since it's WP.com-only.  One way to split this out better would be to use the new filter on the site settings endpoint (see #9464).  If this is something that's desired, I'd propose that we do it separately, bringing the file in sync first via this PR and #9464.
=> WPCOM merge: site settings endpoint

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
This change is part of the work to sync the site settings endpoint (see also #9465), but it's worth surfacing on its own.
On the WP.com side we're using this new filter parameter to be able to hook in and add "extra" settings that can be updated using the API.  (There is already a filter that works for reading settings: `site_settings_endpoint_get`).
See D12286-code for details and an example usage.
=> REST API: Allow filters to update site settings

modules/masterbar/masterbar.php
This brings the Masterbar My Site(s) navigation (the frontend version of the Calypso Sidebar) in line with https://github.com/Automattic/wp-calypso/pull/24587.
* Swap the order of the arguments passed to `A8C_WPCOM_Masterbar->create_menu_item_pair` such that the `Customizer` array is first & the `Themes` array is second
Before:
After:
* Run this branch (the Jetpack Beta Plugin can help with this!)
* Activate the "WordPress.com Toolbar" in the Jetpack "Writing" Settings
* Click `My Sites` (or `My Site` if your test user only has one)
* You should see `Customize` as the main menu item under the `Personalize` section and `Themes` in the smaller inline button
* Clicking `Customize` should take you to the Customizer for the site
* It should also trigger an appropriate Tracks event
* Clicking …
=> Masterbar: Invert Order of Customize and Themes buttons

.travis.yml
Successful builds are not important enough to email.
=> Update Travis success email notifications stop emailing success notices

jetpack.php, modules/sharedaddy/sharing.php
This syncs changes introduced in r174775-wpcom that synchronised Sharing code. This is the first place where we use the new filter instead of directly checking for SCRIPT_DEBUG constant.
* Adds a filter to switch minified assets on or off in places in code that currently support it.
=> Adds a filter that switches minified assets on or off.

fusion/whitelist.json
=> Fusion: Add update-comment endpoint to whitelist

modules/widgets/eu-cookie-law.php, modules/widgets/eu-cookie-law/eu-cookie-law-admin.js, modules/widgets/eu-cookie-law/form.php
* GDPR: A new warning is displayed while configuring an instance of the EU Cookie Law widget: "_Caution: The default policy URL only covers cookies set by Jetpack. If you're running other plugins, custom cookies, or third-party tracking technologies, you should create and link to your own cookie statement._"
* Be sure 'Extra Sidebar Widgets' are enabled in Jetpack.  
See: `/wp-admin/admin.php?page=jetpack_modules` to review.
* Add the EU Cookie Law Banner widget.
* It should be using our cookies statement as a default setting, which will generate this notice.
* Using a custom URL should automatically disable the notice.
* Save the widget, try with multiple EU widget instances in a single sidebar, and try multiple instances across multiple sidebars; i.e., do your best to break it and …
=> Add warning about privacy policy in EU cookie widget

modules/likes/jetpack-likes-master-iframe.php
We've had a few recent issues regarding stale caching of the likes iframe assets. Instead of busting the cache when we realize something is broken and having to wait for the next release, what about switching to weekly automatically like the stats js?
If there is bad code, we can fix it and, worst case, tell folks that it'll be fixed for them the following Monday?
See issue #9377 which was fixed by #9475 and #9347 which busted the cache based on a support request reporting bad styling.
=> Likes: Automatically bust the likes iframe cache weekly

json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php, json-endpoints/jetpack/json-api-jetpack-endpoints.php
In 6.1 we introduced the simple codec. This will allow us to extract sync items that are not configured as expected. 
* 
Apply this patch to the PR. 
Notice that you are able to retrieve the sync object via the manager when the site doesn't support the correct default codec.
=> Sync: Add codec to the sync objects endpoint

modules/contact-form/grunion-contact-form.php, tests/php/modules/contact-form/test_class.grunion-contact-form.php
Closes https://github.com/Automattic/jetpack/issues/8799
Uses upcoming changes in core:
- https://core.trac.wordpress.org/ticket/43546
- https://core.trac.wordpress.org/ticket/43438
- https://core.trac.wordpress.org/ticket/43440
* Registers and implements a core data exporter.
* Registers and implements a core data eraser.
* Adds unit tests for the exporter and eraser.
Not yet, but it attaches through filters, so in current versions of WordPress it's simply not enabled, because the filters do not exist yet. To clarify further, this works with [upcoming tools in core](https://core.trac.wordpress.org/ticket/43546) that allow site owners to export personal data and/or remove personal data by email address.
* I suggest testing with [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) using …
=> Register personal data exporter & eraser for feedback (i.e., contact form submissions)

modules/wordads/wordads.php
This fixes an incompatibility issue with the publicize module.
The `Jetpack_Media_Summary` class used by the Publicize module applies filters for [get_the_excerpt](https://github.com/Automattic/jetpack/blob/master/_inc/lib/class.media-summary.php#L331
), which the WordAds module uses to insert ads.
Combined with the [5-6 ad limit](https://github.com/Automattic/jetpack/blob/master/modules/wordads/wordads.php#L439) we introduced in 6.1, this had led to lots of issues.
Ads are being placed in the Publicize filter calls, which is using up to 4 of the available 5-6 ad slots.
This means that Jetpack sites that once had 5 ads on their posts may now only have 1.
* When filtering the content & excerpts, only proceed if `is_main_query()` and `is_the_loop()` are both true - otherwise bail for …
=> WordAds: Don't insert ads unless this is the main query within the loop.

sync/class.jetpack-sync-module-import.php, sync/class.jetpack-sync-module-posts.php, sync/class.jetpack-sync-modules.php, tests/php/sync/test_class.jetpack-sync-import.php, tests/php/sync/test_class.jetpack-sync-posts.php
* Extact the import and export sync events into its own module
This will make the curreny sync module easier to understand.
Do the tests pass? 
- Create an export, 
- Create an import 
do the events show up as expected on the .com side?
=> Sync: Extract Import sync events into its own module.

modules/stats.php
By far, the number one most visited Jetpack page is the stats page.  There is nothing there that even mentions Jetpack.  This PR adds the same Jetpack admin header and footer. The actual stats content is styled the same, except for a narrower width to match Jetpack's admin. **This PR is not meant to style anything within the stats content itself. Just a quick win.** 
Test: 
- Make sure all the links work properly
Now: 
Before:
=> Stats page: Brand it Jetpack

modules/stats.php
#9517 added headers and footers, this just updates the container background to match Jetpack admin.
=> Stats page: update background to match Jetpack

docker/README.md
Adds note about `yarn` version in Docker-readme since there have been already two cases where v0.x versions were causing issues.
p7rcWF-MA-p2
=> Docker: add note about yarn version in readme.md

modules/contact-form/js/editor-view.js
Fixes #9258
The problem seems to be only in Firefox.  Increasing the timeout to check for height seems to fix the issue.
To test: 
*In Firefox*
- Insert this shortcode in the html editor
```
[contact-form][contact-field label="Name" type="name" required="1"][contact-field label="Email" type="email" required="1"][contact-field label="Website" type="url"][contact-field label="Message" type="textarea"][contact-field label="date" type="date"][contact-field label="multiple" type="checkbox-multiple" options="hi,one,two"][contact-field label="whatever" type="textarea"][contact-field label="Keep going..." type="text"][contact-field label="check" type="checkbox"][contact-field label="drop" type="select" options="whatever,yo,ma"][contact-field label="" type="text"][contact-field label="" …
```
=> Contact Form: Fix scrolling/height for very large contact forms

tests/php/sync/test_class.jetpack-sync-themes.php
Make the test not skippable 
Make sure that the data that is returned is what is expected.
Fixes #7691
* Update one test so that it passes again and is not skipped.
*
=> Jetpack: Sync fix theme update test

json-endpoints/class.wpcom-json-api-list-roles-endpoint.php, sal/class.json-api-site-jetpack.php
Summary: Ads a 1.2 endpoint that returns roles from shadow data
Test Plan:
Check that we don't break anything.
Do the test pass?
test the api endpoint for .com sites v1, v1.1 and v1.2
test the api endpoint for a jetpack sites v1, v1.1 and v1.2
Does it return the values as expected
Do not connected sites not return data as expected.
Reviewers: migueluy
Reviewed By: migueluy
Differential Revision: https://[private link]
https://[private link]
Merges r164573-wpcom.
=> wpcom merge: REST API: Roles endpoint update for JP sites

sync/class.jetpack-sync-defaults.php, tests/php/sync/test_class.jetpack-sync-options.php
Adds new `wp_page_for_privacy_policy` option to the sync options white-list.
`wp_page_for_privacy_policy` is a new option introduced in WordPress 4.9.6 ([in RC1](https://make.wordpress.org/core/2018/05/10/wordpress-4-9-6-release-candidate/) as of 11 May 2018):
- https://core.trac.wordpress.org/ticket/43491
- https://github.com/WordPress/WordPress/commit/f1e065b13bdf21cf246302216e15ac8e4efdbe45#diff-edf10fb2833dc3fa63e4d9879ce60bfdR346
and:
- https://core.trac.wordpress.org/ticket/43435
- https://github.com/WordPress/WordPress/commit/9af2f7cd35c05a6e0a7e1ae0938236efcdbf571a
The official 4.9.6 release is scheduled for Thursday, May 17th.
wpcom side: D13136-code
1) Use WP 4.9.6 beta:
- https://wordpress.org/wordpress-4.9.6-RC1.zip
- https://make.wordpress.org/core/handbook/testing/beta/
2) …
=> Add option `wp_page_for_privacy_policy` to sync

modules/shortcodes/wordads.php
The wrapping div shouldn't be inside the translatable string - it serves no purpose there.
=> i18n: remove wrapping div outside of translatable string. 

modules/related-posts/jetpack-related-posts.php
Fixes #9494
Attempting to grab Related Posts for an unpublished post doesn't really make sense for our use case as we could cache the result for a post that changes drastically before publishing.
=> Related Posts: Only attempt to grab related posts for Published posts.

modules/infinite-scroll/infinity.php
This PR includes changes from:
- r168073-wpcom - Infinite Scroll: Provide feature info via the Site Settings REST API endpoint
- r168325-wpcom - Infinite Scroll: Leave a pointer in wp-admin to the new setting
Test Plan:
Test and compare infinite-scroll feature on WPCOM and Jetpack site.
=> Fusion: r168073-wpcom, r168325-wpcom

modules/widgets/eu-cookie-law.php
This change proposes an update to the title and description of the EU
Cookie Law Widget. As it will soon be updated to also handle consent
(as required by the GDPR) on sites using WordAds (9373) — and we may
very well update it in the future to handle more privacy-related things
— it makes sense to expand the title/description accordingly.
To test, simply apply this change and make sure that the widget’s title
and description are updated accordingly. Also confirm that there are no issues with adding/configuring/removing the widget. It should behave
exactly as before.
=> EU Cookie Law Widget: Update the title and description

modules/widgets/google-translate.php
This PR brings over changes introduced in r166780-wpcom / props @thomasguillot 
> Fix admin bar position on small screens + update translate bar position depending on screen size
To Test: 
- Make sure translate widget looks ok in smaller screens 
This PR + D13122-code will put this file in sync.
=> Google Translate Widget: Override admin-bar styles

modules/sharedaddy/recaptcha.php
Merges changes from .com that added more support for Recatpcha v2. 
This specific changes makes sure that the requests are actually coming from the site they're filling out the recatpcha on. It shouldn't affect behavior, but it allows people to set domain wildcards like *.wordpress.com 
Read more here https://developers.google.com/recaptcha/docs/domain_validation
To Test: 
- Make sure recaptcha still works as expected
=> Sharing Recaptcha: manual Domain/Package validation 

sal/class.json-api-site-jetpack-base.php
Brings `sal/json-api-site-jetpack-base.php` up to date.
Updates sal/json-api-site-jetpack-base.php
Not needed
=> Code Sync: Bring changes to json-api-site-jetpack-base present in wpcom - was divergent

docs/partners/plan-provisioning.md
A partner reported that the `partner-provision.sh` and `partner-cancel.sh` scripts were no longer executable, which means that our sample commands that treated the scripts as executable would not work.
When I tested the last two version of Jetpack, `wp plugin install jetpack --version=6.0` and `wp plugin install jetpack --version=5.9`, the scripts weren't executable in those versions either. My guess is that the scripts were previously executable as a byproduct of how Jetpack had been installed.
For example, when I `git clone git@github.com:Automattic/jetpack.git` down to my local machine and then run `ls -lah`, I get the following:
```
-rwxr-xr-x   1 user  group   1.8K May 10 16:39 partner-cancel.sh
-rwxr-xr-x   1 user  group   5.7K May 10 16:39 partner-provision.sh
-rw-r--r--   1 user …
```
=> Docs: Partners: Add sh to sample commands in case scripts are not executable

modules/widgets/eu-cookie-law.php, modules/widgets/eu-cookie-law/widget.php
Updates the default contents (text, link) of the EU Cookie Law widget's banner.
Requested in p4H3ND-Hx-p2
* Make sure the new default text for the widget matches the changes here.
=> EU Cookie Law Widget: Update cookie banner text.

modules/widget-visibility/widget-conditions/widget-conditions.css
The layout for the delete and add action icons was broken in Edge. Each button was shifted down by 100% of their height.
The root cause is unknown :) But this fixes the issue and causes no problems in IE, Chrome, Firefox, Safari, or Safari iOS.
1. In MS Edge, open wp-admin/widgets.php and look at a widget's Visibility settings.
2. In MS Edge, open wp-admin/widgets.php, click "Manage with Live Preview" to open the Customizer, and look at a widget's Visibility settings.
Tested in Microsoft Edge 42.17134.1.0
Before in wp-admin/:
Before in Customizer:
After in wp-admin/:
After in Customizer:
Fix Widget Visibility styling in MS Edge.
=> Fix Widget Visibility Condition Actions for Edge

modules/lazy-images/js/lazy-images.js
The `data-lazy-src` attribute was being set to `1` when an image was lazy
loaded causing the script to trigger again as the viewport was scrolled.
This appears to have been a typo in a recent change and was meant to set
`data-lazy-loaded` to `1`.
Fixes #9527
* Lazy Images: Fix bug where images would disappear when scrolling
1. Install Jetpack 6.1
2. Enable Lazy Images
3. View a page with many images that go past the viewport height
4. Scroll up and down repeatedly
5. See that images that have been lazy loaded disappear
6. Check inspector to see that `src` has been set to `1`
7. When scrolling see that `data-lazy-src` is set to `1` when image is lazy loaded
* Lazy Images: Fix bug where images would disappear when scrolling
=> Lazy Images: Fix bug where images would disappear when scrolling

_inc/client/privacy/index.jsx
This change updates the copy and content of the Privacy settings area within the Jetpack settings UI. This will now be in sync with the same setting on WordPress.com.
Specifically:
* Add additional copy that better explains what folks are opting out of.
* Add reference/link to the Automatic cookie policy (note that this will not be live until May 21).
* Add reference/link to the Jetpack Privacy Center.
Test Plan:
* Visit the Privacy settings page of your Jetpack site (wp-admin).
* Confirm that the content/copy has been updated, according to the changes in this PR.
* Confirm that all links work as expected and that the setting still toggles correctly.
=> Privacy Settings: Content and Copy Updates

modules/woocommerce-analytics/wp-woocommerce-analytics.php
Fixes #9545 
* Use `Jetpack::get_active_plugins()` instead of pulling straight from the db. The prevents issues of a non-array being returned as well as catching multisite network-activated plugins.
=> WooCommerce Anayltics: Use `Jetpack::get_active_plugins`

class.jetpack-cli.php
This PR seeks to add a `wp jetpack call_api` command which is a wrapper for simplifying authenticated (with the blog token) requests to the WordPress.com API. One use case of this is to query the WordPress.com API for stats. We can make that query with the following:
```
wp jetpack call_api --endpoint='/sites/%d/stats'
```
This functional is currently available with `wp eval`, but the results are pretty rough since there is no error handling and it's quite hard to grok:
```
wp eval "echo json_encode( Jetpack_Client::wpcom_json_api_request_as_blog( sprintf( '/sites/%d/stats?force=wpcom', preg_replace( '/^Success:\s+/', '', '$(wp jetpack options get id)' ) ), '1.1' )['body'] );"
```
To test:
- Test multiple API calls with the `call_api` command:
- `wp jetpack call_api …
=> CLI: Adds an api_call command that acts as wrapper for making authed API calls

class.jetpack.php
More context in p1HpG7-570-p2.
* Updates Jetpack::is_akismet_active() to also check for a valid Akismet key.
* Start with a Jetpack-connected site.
* Go to wp-admin > Jetpack > Settings > Sharing > Sharing buttons and make sure sharing buttons are enabled.
* Go to wp-admin > Plugins and make sure Akismet is activated but do not connect Akismet via Jetpack or with an API key.
* Check this branch.
* With the Akismet plugin activated but not connected, expect to not be able to add the email sharing button.
Sharing: Added check for validating akismet key before allowing sharing by email.
=> Sharing: Refactor Jetpack::is_akismet_active() to also check for a valid key

modules/contact-form/grunion-contact-form.php
**Fixes a bug reported in p8oabR-cR-p2**
> An error occurred while attempting to find and erase personal data.
This PR updates the array keys returned by the eraser so they match those found in WP core's latest [comment data eraser](https://github.com/WordPress/WordPress/blob/fc800115a76c461cd3c5527a1fd1289bd8498795/wp-includes/comment.php#L3499-L3500); i.e., I'm simply removing the `num_` prefixes.
- Enable Jetpack Contact Forms.
- Create a page and add a Jetpack Contact Form.
- Submit the form a couple of times with a test email address.
- Test both of these upcoming tools in core.
- **Dashboard -> Tools -> Export Personal Data**
- **Dashboard -> Tools -> Erase Personal Data**
Expect to find that exporting personal data includes a “Feedback” group containing the personal data that you …
=> Fix personal data eraser so it works with latest core

modules/widgets/eu-cookie-law.php
Fixes the following `E_NOTICE` by checking if each `isset()` during validation.
> Undefined index: hide in wp-content/plugins/jetpack/modules/widgets/eu-cookie-law.php on line 199
@oskosk I took a slightly different approach than what I suggested in chat because merging with defaults would have altered the way other things work in this function, based on later assumptions.
* Check this branch and enable WP_DEBUG_LOG
* Remove any EU Cookie law widget present.
* Add a Cookies & Consent Banner Widget.
* Expect to see no warning logged.
=> Fix EU cookie banner `E_NOTICE` on missing array index

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
This reverts PR #9322.
Google My Business integration with Jetpack sites has taken a new approach (See https://github.com/Automattic/wp-calypso/pull/24815 and D13317) which makes #9322 useless now.
=> Revert "Update site settings enpoints to support Google My Business integration (#9322)"

.svnignore
The fusion directory is no longer present so it can be removed from svnignore.
* Removes the line reading `fusion` from `.svnignore`.
None needed
=> General: Remove fusion directory from .svnignore

class.json-api-endpoints.php
This commit adds a site keyrings endpoint
to manage site<->keyring relationship.
Currently that being used only for Google My Business
Differential revision: D13317
Merges r175707-wpcom.
* adds a site keyrings case
* Check that r175707-wpcom matches this diff
=> Code Sync: Bring wpcom changes to class json endpoints: Add Site keyrings endpoint

json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-get-media-v1-2-endpoint.php
These changes bring the files in line with wpcom. 
to test: 
- Make sure the API endpoints are working properly, and that you're still able to get and edit media files from Calypso. 
- Make sure all the functions/methods are being defined properly.  
@retrofox I had to do some custom mapping of `Jetpack_Media` for these to sync properly, since we have a different className defined in wpcom in the `class.media` library.
=> File sync: Media endpoints

json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php
@allendav, I think this is correct.  I don't see `wga_defaults` called or used anywhere else, and when I tried to sync this change back to wpcom in D13790-code (since it's the most recently changed here), it broke all the API tests because this method wasn't defined.
=> File sync: site-settings-v3-endpoint

class.jetpack-cli.php, modules/publicize/publicize-jetpack.php, tests/php/modules/publicize/test_class.publicize.php
This pull request seeks to add some CLI commands for managing Publicize. Specifically for listing connections and disconnecting connections.
This is currently useful for a partner that is integrating deeply with Jetpack, but it can be used by any Jetpack user that uses Publicize.
To test:
- Connect several accounts
- Run commands from the examples section (replacing the ID with your own connection IDs) and ensure the commands work
- When specifying `all` or a service for disconnection you should be asked to confirm the action and progress bar should be displayed
- When specifying a specific connection to disconnect, no prompt should be displayed
=> CLI: Publicize: Adds publicize command for listing connections

sync/class.jetpack-sync-json-deflate-array-codec.php
Fixes #9477 
* use the previous version of the function if the current once doesn't exits.
*
Downgrade Jetpack to 6.0 use the cli command to update to the this version of Jetpack
=> Sync: Check that jetpack_json_wrap exists

json-endpoints/class.wpcom-json-api-list-media-v1-2-endpoint.php
I'm not sure how/if this is used, but if it was it definitely wasn't working because `Media` is not defined in Jetpack.
=> Media endpoint: Rename class - Media not defined in Jetpack

class.jetpack-cli.php
This PR updates the `wp jetpack module list` command so that is used the `format_items` functionality of WP-CLI so that users can format the output however they'd like. For example, a hosting partner requested the ability to list modules by JSON. That is now possible with `wp jetpack module list --format=json`.
As part of these changes, I've updated the documentation for the command so that we get some built-in validation which will allow us to simplify some logic in the command. 
To test:
- Checkout branch and try the example commands in the documentation.
=> CLI: Allow formatting the output when listing modules

docker/mu-plugins/avoid-plugin-deletion.php
- Disables notices for Jetpack plugin in Docker environment.
- Disables plugin deletions
Deleting or updating the plugin would cause your complete development folder being erased. _Not cool._
Previous version of the plugin was already removing the delete link but this disables the actual deletion.
Probably the easiest way to test is to download older version of Gutenberg: https://downloads.wordpress.org/plugin/gutenberg.2.7.0.zip
...and add it to the list at `docker/mu-plugins/avoid-plugin-deletion.php`:
```php
$jetpack_docker_avoided_plugins = array(
'jetpack/jetpack.php',
'gutenberg/gutenberg.php',
);
```
Just ensure your gutenberg folder is `gutenberg`,  not `gutenberg-2.7.0`
Confirm that:
- Update notice dissapears from wp-admin and the Activity log:
- Bring back plugin deletion link …
=> Docker: disable Jetpack update notices

modules/stats.php
After #9458, the pixel was not printed to the front-end.
This restores a `print` that was removed during the refactoring.
=> Stats: Print stats pixel again

3rd-party/class.jetpack-amp-support.php
Most AMP sites are currently configured to use the `/amp/` suffix as the canonical path to AMP content.
In Jetpack's AMP support code, we need to hook earlier than `parse_query` in order to properly intercept and modify Jetpack's output, however this means we can't use the standard means to detect `/amp/` from WP_Query and must roll out own solution that assumes that `/amp/` is truly the AMP path for the site.
The downside is that if the site has changed it to something else, e.g. `/mobile/` or `/lite/`, we won't detect it. The upside is that 99% of sites just go with the default, so this provides a workable solution for them.
cc @westonruter
=> Detect /amp/ suffix when determining AMP request

tests/php/sync/test_class.jetpack-sync-callables.php
Fixes the test so that the test is less fragile and doesn't break when we run the test locally and the user has some other plugins installed.
=> Jetpack Sync: Fix fragile php action links test

modules/contact-form/admin.php
Hi  @georgestephanis ,
Could you use this PR which fixes #8796 ?
* Return` $views` instead of `$actions`, taking as an example` grunion_admin_bulk_actions()`
* Use `$meta` which is defined and contains akismet data, instead of `$akismet_values` which does not, taking as an example `grunion_ajax_spam()` and `grunion_handle_bulk_spam()`
I'm not sure if the variable name should be renamed as `$akismet_values` instead of meta, which may not fit well. Thanks, any feedback is gladly appreciated
=> Contact form: Fix undefined variables.

modules/tiled-gallery/tiled-gallery/tiled-gallery-item.php
Fixes #9202
If Photon is active and a Tiled Gallery links to media file, then use Photon for the link
=> Tiled Galleries: Use Photon for linked media file

sync/class.jetpack-sync-module-plugins.php
Currently when we update a plugin we end up with a missing plugin name if the plugin fails to update and is deleted.
Perform a plugin update. 
Plugin install
Plugin deletion
Editing a plugin
Do they all show the right info.
=> Sync: populate the plugins list before doing the update

modules/theme-tools/content-options/blog-display.php
* Make sure we exclude CPTs like Portfolio and Testimonial when we toggle content/excerpt via the Blog Display option -- It should only affect Posts
* Check a CPT archive page and check if you have the option to switch between content and excerpt (you shouldn't be able to)
* Check a Post archive page and check if you have the option to switch between content and excerpt (you should be able to)
=> Content Options: Exclude Jetpack CPT from the archives blog display

modules/markdown/easy-markdown.php
Previous attempt in #9366 went wrong because the `<script>` was being executed before `window.tinymce` was declared. So it was reverted in #9366.
Now, for syncing the file, this PR will do it, but also will leave the file jp-ahead because of this wrapping.
* Wraps the initialization code for hooking into tinymce be wrapped on a jQuery.ready call.
* check this PR with a connected Jetpack
* VIsit WordPress's Dashboard and confirm you get not Javascript warnings in the console
* Visit an edit post screen and confirm you're able to write markdown in the "Visual" mode of the classic editor.
=> Code Sync: sync easy-markdown.php - was wpcom-ahead - will be jetpack-ahead

modules/widgets/eu-cookie-law/style.css
Fixes #9632
* Adds a specific bottom margin to the cookie widget
* Install and activate Storefront theme
* Enable the cookie widget
* Verify the margins are consistent within the widget
=> Reset bottom margin for eu cookie law form in case theme changed it

modules/likes.php, modules/likes/jetpack-likes-settings.php
This adds back a stubbed version of `Jetpack_Likes::is_post_likeable()`. It's called directly on the class in wpcom.
Also moves `sharing_meta_box_content` where it can be reached in wpcom by [this](https://github.com/Automattic/jetpack/blob/23eb01b21f22d9bc25482a8dc4557b56333aff4e/modules/likes.php#L78)
**Testing**
These changes only affect wpcom
=> Likes: sync changes needed for WordPress.com

modules/widgets/eu-cookie-law/style.css
Fixes #8166
Removes `.widget` class from selector in EU Cookie Law Widget styles, since `.widget` is not used in every theme.
* Apply one of the themes mentioned in #8166 (Graphene or Kahuna) to a test site
* Add the EU Cookie Law Widget to the footer widget area
* View the site from the front-end. Rather than being fixed to the bottom of the screen, the widget message will be at the very bottom of the site:
* Apply PR to the test site
* View the site from the front-end. The widget message should now be fixed to the bottom of the screen, and stay with you when you scroll:
(Unfortunately this issue doesn't screenshot very meaningfully).
This may not fix all individual clashes between theme styles and the EU Widget, but should help those described in the ticket!
=> Remove .widget class from selector used in EU Cookie Law Widget styles

modules/sharedaddy/sharing-sources.php
Used the esc_url() function to escape the space. Tested this in my local machine:
`<a` rel="nofollow" data-shared="" class="share-jetpack-whatsapp sd-button share-icon" href="https://api.whatsapp.com/send?text=Testing%20http%3A%2F%2Flocalhost%2Fwordpress%2F2018%2F05%2F23%2Ftesting%2F" target="_blank" title="Click to share on `WhatsApp"><span>WhatsApp</span></a>`
This addresses the reported issue (#9591)
=> WhatsApp sharing button has invalid space (#9591)

class.json-api-endpoints.php
This diff adds a new property `feed_url` to responses for the API endpoints to list terms and get a single term.
The new property uses the [`get_term_feed_link`](https://developer.wordpress.org/reference/functions/get_term_feed_link/) function from WP core, which has different behavior depending on the current permalink setting and is filterable various ways by plugins, so we shouldn't make any assumptions about the format of feed URLs.
This commit was generated from D13871-code.
Still left to do:
=> REST API: Add term feed URL to terms API endpoints

_inc/lib/class.core-rest-api-endpoints.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
Part of fix for https://github.com/Automattic/wp-calypso/issues/16021. A new API is needed to change the connection owner.
* Adds a new API endpoint `/connection/owner` to set a new master user with `owner={new owner id}`
* Only current owner has permission to call
* Supplied `owner` must be a currently admin
* Contains unit test for new API
* Also can be tested from js console with:
```
jQuery.ajax( {
url: '/wp-json/jetpack/v4/connection/owner/',
method: 'post',
beforeSend: function ( xhr ) {
xhr.setRequestHeader( 'X-WP-Nonce', Initial_State.WP_API_nonce );
},
data: JSON.stringify( {
'owner': **** new owner id ****
} ),
contentType: "application/json",
dataType: "json"
} ).done( function ( response ) {
console.log( response );
} ).error( function ( error ) {
console.log( …
```
=> Add REST API endpoint to allow changing the connection owner

modules/widgets/customizer-utils.js, modules/widgets/eu-cookie-law.php, modules/widgets/eu-cookie-law/eu-cookie-law.js, modules/widgets/eu-cookie-law/form.php, modules/widgets/eu-cookie-law/style.css
Fixes #9634
* Adds a "top" option for the cookie widget position. The existing bottom of the screen position is the default.
* Test both the top and bottom for existing and new instances of the widget. Test with and without the admin bar present. 
* To test in development mode, you'll need to force the widgets module active, e.g. using https://github.com/allendav/jetpack-force-widgets-active
* Adds a "top" option for the cookie widget position. The existing bottom of the screen position is the default.
=> Add option for top of page position for the cookie widget

_inc/client/components/dash-item/style.scss
Fixes #9547
Test: 
- All sizes
- All browsers 
Before: 
After:
=> Dash Cards: Fix icon overlap

class.jetpack-cli.php, class.jetpack-debugger.php
The `status` check provides a possibly-incorrect response in terms of if the connection with WordPress.com is functional.
This integrates the testing suite done when visiting the in-plugin debugger with the cli status command.
A future todo would be to align this suite (and which is what is used with jetpack.com/support/debug/) and the test-connection REST API endpoint. At this time, I suggest we use the test suite here since it matches what Happiness uses and contains the most accurate source of information.
Testing:
1. On a Jetpack site that is functional, check https://jetpack.com/support/debug/ and confirm the same result (everything is working) with `jetpack status full`).
2. On a Jetpack site, create some type of breakage that would impact communication only - for example, add …
=> CLI: Add testing suite to cli status command

modules/widgets/twitter-timeline.php
Context: p58i-715-p2, p58i-72F-p2
[Twitter will deprecate](https://twittercommunity.com/t/deprecating-widget-settings/102295) `widget-id` on 25/05/2018 and will cease support altogether on 27/07/2018:
> On May 25, 2018, the widget settings page will no longer allow embedded timeline widgets to be created or edited. From that date, the only (and best) way to create timeline widgets will be to head to publish.twitter.com. All existing timeline widgets that rely on these settings (e.g. the ones that have data-widget-id in the markup) will continue to function until July 27.
Our Twitter Timeline widget can be used to pull tweets either from a `profile` (by feeding it a Twitter username), or from a `widget-id`.
The latter case will stop working on July 27: all Twitter Timeline widgets of type …
=> Twitter Timeline Widget: Deprecate type `widget-id`

json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php
We fixed this on the .com side. but lets fix this on the Jetpack side as well.
Related PR for .com D13118-code
*
Makre sure that the api works as expected for the plugins endpoint. 
- No empty action links arrays.
=> Plugins API: Do not send empy array when the activity links are empty

sync/class.jetpack-sync-module-protect.php, sync/class.jetpack-sync-modules.php, tests/php/sync/test_class.jetpack-sync-module-protect.php
Reverts Automattic/jetpack#9514
We need to only remove the failed login attempts that should happen via xml-rpc but leave the other ones as is. 
the idea is that we would only show the ones that are done by real humans. 
cc: @lezama
=> Revert "Sync: Remove jetpack_valid_failed_login_attempt sync event"

sync/class.jetpack-sync-module-protect.php, tests/php/sync/test_class.jetpack-sync-module-protect.php
We get too many of failed login attems and this will make the Activity log more meaningful for the user by only showing the ones that are not done via xml-rpc. 
* prevents the logging of the failed login attempts when done via xmlrpc requests. 
* Make a login request to the xmlrpc make sure that it doesn't appear in the activity log.
=> Sync: Do not sync failed login attempts that happen via xml-rpc.

sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-themes.php
When updating a theme via the new update theme UI in the activity log.
We should show the new theme updated activity.
This fixes an regression introduced in https://github.com/Automattic/jetpack/pull/9519
cc: @eliorivero 
* Check that we show just one activity as expected.
Set a theme so that it needs an update. 
Update it via the activity log. 
Do you notice that the activity show up as excepted?
=> Sync: Fix single theme update

tests/php/bootstrap.php, tests/php/modules/shortcodes/test_class.ted.php, tests/php/test_class.json-api-jetpack-endpoints.php
Follow-up to https://github.com/Automattic/jetpack/pull/9635:
> Add Jetpack automated tests, ideally with a couple of different permalink settings because the feed URLs can look very different based on this. (WP.com automated tests are in place but they can't cover this case.)
=> REST API: Add tests for term feed URL

class.jetpack.php
Alternative to #9667
in #9585 we updated `Jetpack::is_akismet_active` to always check if the plugin is active and with a valid key. This had implications for:
1. When we were deciding whether to render or not the Share by Email Button in Settings -> Sharing. So users without a valid Akismet key can't configure the Share by Email Button.
2. Everytime `Jetpack::get_all_services` is called, because there we decide whether to show the Share by Email button in the **frontend**. 
* Caches the result of verifying the Akismet for ten minutes so we don't request it a lot of times in the frontend.
* **Start with Akismet being active but without a key set**
* Connect Jetpack and activate recommended features
* Visit Sharing -> Settings
* Confirm that you don’t see the Share by Email button
* **Enter …
=> Sharing: Cache the result of verification of the akismet key in a transient

_inc/client/components/jetpack-dialogue/style.scss, _inc/client/scss/layout.scss
Issue: The `body` is not growing along with the component, so we get issues like this: 
To Test: 
- Activate jumpstart manually: `wp jetpack options update jumpstart new_connection`
- Hover over a menu item towards the bottom
- It should hover in the correct place
=> JP dialogue component: add height to account for the rest of wp 

_inc/lib/admin-pages/class.jetpack-react-page.php, functions.global.php
Fixes fatal when using the Gutenberg editor in the Frontend introduced by #9560.
* Moves the function `jetpack_get_user_locale()` from `_inc/lib/admin-pages/class.jetpack-react-page.php` to `functions.global.php`
* Install and activate the Frontenberg Editor:
```
wp theme install https://github.com/tomjn/Frontenberg/archive/master.zip --activate
```
* Visit the site's home and expect it to not throw a fatal error
* Visit Jetpack's admin page and expect the same.
Shortcodes: Fixed a fatal coming form the VR shortcode when using the Gutenberg editor in the frontend
=> General: Move jetpack_get_user_locale to functions.global.php so it's more widely available

class.jetpack-twitter-cards.php
Yesterday, this deployment r176550-wpcom
caused a regression in the way we generate open graph Twitter tags.
This diff attempts to fix it by using the correct twitter setting based on `IS_WPCOM`
Jetpack and WPCOM sites use different options for twitter site tag.
Test Plan:
On site running this branch, update your twitter handle.
Ensure that twitter sharing buttons continue to use your chosen Twitter handle.
=> Jetpack Twitter Cards: fix open graph tags

modules/custom-post-types/nova.php, modules/custom-post-types/testimonial.php
In front end editing situations, `get_current_screen` may not be available. If it isn't, return the title without modification.
Fixes #7955
* Using the Front End Editor feature plugin, confirm no fatals when the testimonial CPT is active.
Compatibility fix when using Testimonials and a front-end editing plugin
=> Testimonial CPT: Confirm get_current_screen exists

_inc/client/components/apps-card/index.jsx, _inc/client/components/themes-promo-card/index.jsx
The var `imagePath` already includes the trailing slash `images/` so let's clean up the image URLs to use just the image name and extension to avoid double forward slash `//`.
`https://sitename.com/wp-content/plugins/jetpack-dev/images//themes.svg`
`https://sitename.com/wp-content/plugins/jetpack-dev/images/themes.svg`
- Have Jetpack site on a free plan.
- Go to your site > `/wp-admin/admin.php?page=jetpack#/plans`.
- Make sure the images on the Themes and Apps promo cards have the correct URL path.
=> Promo cards: fix images URLs

3rd-party/class.jetpack-amp-support.php
Fixes #9716
* Render stats pixel for legacy, non-paired, non-canonical AMP pages
* Enable AMP plugin 0.7 or higher
* Ensure stats module is enabled
* Go to any post with `?amp` suffix
* Search page source for `<amp-pixel>` - there should be a stats pixel rendered in the footer
=> Render stats footer on non-canonical AMP pages

_inc/client/components/dash-item/index.jsx, _inc/client/components/settings-group/index.jsx, _inc/client/components/support-info/README.md, _inc/client/components/support-info/index.jsx, _inc/client/searchable-modules/index.jsx, _inc/client/writing/masterbar.jsx
Allow info bubbles have no text if needed and not to default on module description texts when text is missing.
- Previously `support-info` component would default to `module.long_description` when `text` is empty and to `module.learn_more_button` when `link` is empty. Moved these features out since the feature doesn't seem to be used anywhere.
It's simpler to have clarity for components: no surprise texts when no text isn't defined. If info bubble should show module description, it should explicitly be passed to it.
I found that [`searchable-modules`](https://github.com/Automattic/jetpack/blob/aa233aa9683cb4f923688a02898939dd7fc3a858/_inc/client/searchable-modules/index.jsx#L115) component is missing `text` but I didn't notice any differences in info-bubble texts when searching for …
=> Allow empty texts for support info bubbles

modules/widgets/customizer-utils.js
Replace #9668
Required by #9577
The Simple Payments module works basically like this: whenever the Simple Payments button is rendered, it calls a JS script that in turns renders a PayPal button.
This doesn't happen with the Simple Payments widget, when the Customizer _selectively refreshes_ it.
* Add the Simple Payments widget to the widgets that support Selective Refresh.
* Upon widget change or move, trigger a new PayPal button render on the updated widget button.
* `git checkout fix/simple-payment-widget-customizer-reload-script`: it's the branch of #9668, and it contains exactly the same changes as this PR, but it's branched off #9577 which introduces the Simple Payments widget, so it's easier to test.
* Pick a Premium/Business site with one or more Simple Payments button already …
=> Widgets: Make the Simple Payments button compatible with Selective Refresh

docker/README.md
In the [`Working with containers | Quick install WordPress` section](https://github.com/Automattic/jetpack/tree/1e60685fc6a3c60b1f0b91a11cdeaeaa86691c9f/docker#quick-install-wordpress), fix a minor typo.
* Correct `You can to just quickly...` to `You can just quickly...`
Ensure it reads appropriately.
=> Docker README: Fix minor typo

_inc/client/components/support-info/index.jsx
"Privacy info" links to support pages (e.g. https://jetpack.com/support/monitor/#privacy).
Chatted with @benhuberman earlier about this:
> sentence case looks like the way to go.
> on the linked page, Privacy Information is an actual title, and so capitalizing makes sense. otherwise, these are generically used terms here.
This was left out from https://github.com/Automattic/jetpack/pull/9715
=> Support info component: use sentence case in links

modules/stats.php
Fixes #9700 
* widen max width
=> Classic Stats - widen width a bit to match Calypso stats

json-endpoints/class.wpcom-json-api-taxonomy-endpoint.php
Summary: In rWP176103 we added `feed_url` to the response. This Diff documents that addition to the response.
Test Plan:
* Sandbox `[private link]`
* Apply Diff
* Verify that `feed_url` is documented [here](https://[private link].1/get/sites/%24site/categories/slug:%24category/#apidoc-response)
Differential Revision: D14406-code
This commit syncs r176710-wpcom.
=> REST-API: Categories: Document `feed_url` in category documentation

_inc/client/writing/media.jsx
Resolves #9689
- Remove un-used `carousel` const
- Update labels and descriptions for media settings
- Add section titles for Video and Image settings
See that Media settings in `/wp-admin/admin.php?page=jetpack#/writing` continue working.
=> Media Settings: Verbiage Adjustments

_inc/client/components/module-settings/index.jsx, _inc/client/traffic/related-posts.jsx, _inc/lib/class.core-rest-api-endpoints.php, modules/related-posts/jetpack-related-posts.php
Move _"try it out!"_ link in Related posts settings to card's footer.
The config link was quite unnoticeable and not in line with other sections.
Fixes #8736
Before:
After:
- Go to `/wp-admin/admin.php?page=jetpack#/traffic`
- Enable feature
- Test link works
- Test closing customizer and ensure you come back to where you left
=> Related posts settings: move configure link to card's footer

docker/config/wp-tests-config.php
Enables PHP error logging for the Jetpack test suite. You can now add error_log() or l() statements to unit tests for debugging purposes and see them in wp-content/debug.log
=> Enables PHP error logging for the Jetpack test suite

_inc/client/components/dash-item/style.scss, _inc/client/components/section-header/index.jsx
This PR removes the paid labels from all cards in the Dashboard.
Details as described in #9299 :
> As part of Jetpack dashboard improvement initiative (p6TEKc-1WA-p2), we decided to remove the "PAID" labels from Jetpack dashboard cards. We are going to improve the upgrade badge (now it looks like alert) and removing the PAID label is the first step.
Fixes #9299
=> Dashboard cards: remove paid labels

modules/tiled-gallery/tiled-gallery/tiled-gallery-item.php
https://github.com/Automattic/jetpack/pull/9454 implemented a fix to always link to the photonized image in a tiled gallery if Photon is active.
The code works well. This PR just makes it easier to keep Jetpack's code in sync with the code running on WordPress.com.
* Filter the link URL through the `jetpack_photon_url` filter. This filter only photonizes the URL if Photon is active:
https://github.com/Automattic/jetpack/blob/e89efa8fe67e506071ca9e1ffca61ab587041a4f/jetpack.php#L113-L120
* Document the choice in using the filter in one place and the function in the other.
* Leave `$this->orig_file` alone in case something else depends on it being the unmodified value.
1. Create a new post.
2. Add a gallery
3. In the gallery options, select "Link To: Media File" and "Type: Tiled Columns". …
=> Tiled Galleries: Sync tiled-gallery-item.php with WordPress.com

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
Currently, we save the value of `rss_use_excerpt` as a boolean which stores false-values as an empty string.
Bug's result is visible in the wp-admin:
WP core expects this option value to be integer (`0` or `1`).
This PR fixes it.
* Always save `rss_use_excerpt` as an integer via the settings API.
- Update your sandbox with this PR. 
- Make sure to set Feed settings from `/wp-admin/options-reading.php` to "full"
- Go to Calypso _Settings > Reading > Feed Settings_ and press "save" without touching anything
- The new setting is reflected as expected on the wp-admin dashboard
Related D14755-code
=> Fix saving rss_use_expert as an integer.

modules/widgets/customizer-utils.js
From @dereksmart:
"`gulp js:hint` runs on all of the .js files which aren't compiled, so can't use es6 directly in those"
=> Widgets: using `const` causes build to fail

sync/class.jetpack-sync-module-posts.php, sync/class.jetpack-sync-module-themes.php, tests/php/sync/test_class.jetpack-sync-posts.php
Customizer makes ajax requests as you change widget titles in order to preview them. They trigger sync actions which can result in many activities for the same title change. What's more, these changes aren't actually saved until you hit Publish in Customizer, which makes the activities invalid.
This change paired with a change on wpcom will ensure that Widget Modified activities are only added to the Activity Log once the changes are published in Customizer.
=> Fix Activity Log Customizer Widget Title Edit Activities

sync/class.jetpack-sync-queue.php, tests/php/sync/test_class.jetpack-sync-queue.php
Previously, the `test_queue_lag()` method relied on sleeping for 3 seconds after each call to the queue's `add()` method.  After sleeping for 6 seconds, it would then call `lag()` and assert that the `intval()` of the return value was 6.  This would randomly fail on Travis builds when for whatever reason the lag actually exceeded 7 seconds.
That may have been due to a slow database read or write.  The Jetpack sync engine finds relevant options by doing a LIKE query on option_name, which could have highly variable performance depending upon the number of options in the table, other queries running at that time, etc.  So, the lag goes above 6 seconds and the old test approach fails, which is very frustrating.
Beyond that, the old approach required at least 6 seconds to complete the test …
=> Fix reliability and speed of sync queue lag test

package.json
We were missing this...
*  Makes the `yarn lint` script run  `gulp jshint` before eslint
* Run `yarn lint`. Confirm that two types of linting are run on JavaScript. One based on jshint (with rules related to core's style). Another one based on eslint (with rules similar to Calypso's).
=> General: Add gulp jshint to the yarn lint script

_inc/client/writing/speed-up-site.jsx
Resolves #9709
Test "Performance & speed" section works at `/wp-admin/admin.php?page=jetpack#/settings`
=> Performance Settings: Verbiage adjustments

modules/sitemaps/sitemap-builder.php
The video sitemap is not filtering the last modified datetime using the `jp_sitemap_datetime`, resulting in an invalid datetime being printed to the xmlsite map.
To test:
1. Have a site with a video that would generate a video sitemap.
2. Review sitemap.xml and see the video last mod time in the format of `2018-06-08 14:51:39`.
3. Apply patch.
4. Review sitemap.xml and see the correct format of `2018-06-08T14:51:39Z`
=> Sitemap: Format last modified datetime for vid sitemap

class.jetpack-options.php
Currently, we use the `update_option` when ensuring that an option is set.
With `update_option` we get a sync event:
```js
[ 
option_name
old_value // which in the case of non-existing option would always be null
new_value
] 
```
With `add_option` we would get more truthy sync event (there never was any "old value" after all):
```js
[ 
option_name
new_value
] 
```
In the activity log API better able to distinguish how an option gets set, which is important for detecting if we should discard an event or not.
https://github.com/Automattic/jetpack/blob/6c20cae769e9c5741789d5c3841160b70a18f276/class.jetpack-options.php#L175-L202
In `get_option_and_ensure_autoload()` we first check does the option exist in the DB.
If it doesn’t exist _and_ default value is not `false` → store option in the db. …
=> Fix: update ensure autoloading to use add option

modules/carousel/jetpack-carousel.php
Remove double-domain in: `__( string, 'jetpack', 'jetpack' )`
https://codex.wordpress.org/Function_Reference/_2#Parameters
Nothing much to test:
"Background colour" drop-down in `/wp-admin/options-media.php` translates well with or without the change — no warnings in PHP log neither.
=> Fix: double-domain in translation function

modules/markdown/easy-markdown.php
It looks like recently WordPress has changed the way TinyMCE is loading on various pages. We can no longer rely on tinymce object being present, and we can check to see if it is before registering event handlers. This lets us avoid fatal errors while remaining backwards compatible.
Fixes #9761 
* Adds a TinyMCE check to avoid fatal errors.
* Try to load WordPress admin dashboard with Jetpack Markdown enabled. See the fatal error and not loading Stats Widget.
* Roll this PR on.
* Try step 1, see that the widget loads OK.
* Try creating posts and pages in TinyMCE using markdown, see that it works fine as usual.
* Fixed a compatibility problem between WordPress TinyMCE and Jetpack Markdown.
=> Added a check to see if tinymce is defined.

class.jetpack-data.php
This check is redundant and also doesn't work on some hosts due to differences in local address and external address, particularly for newly-created sites.
This was attempted previously in #7319, which includes a pure-PHP DNS client so we could verify DNS externally, but after some criticism @kraftbj said:
> I think removing the check outright (and relying on WordPress.com to verify it can reach the site) is better than trying to make this check do hoops to verify the site is externally accessible.
So this PR just removes the check. We do the same check (more reliably) from WPCOM during registration anyway.
Side note: This fixes connection issues for developers using VVV with ngrok.io (i.e. me)
=> Remove local DNS check

modules/comments/comments.php
If the core's "Save my name, email, and website in this browser for the next time I comment." checkbox is enabled on a WP 4.9.6+ site, tell Jetpack's comment form iframe about the checkbox and its checked state.
With this change:
* When a commenter opts-in (checks the checkbox), we recover the original behavior (and core's current behavior for opt-inners): the commenter sees their newly submitted comment in the comments list flagged as awaiting moderation.
* When a commenter does not opt-in (leaves the checkbox unchecked), we still have the bad UX (and core's current behavior for non-opt-inners): the commenter does not receive any feedback that their comment was successfully submitted.
Fixes #9808 
This PR can only be tested in combination with WP.com's D15393-code. See testing …
=> Comments: Tell Comment Form Iframe about Cookie Consent Status

.jshintignore, docs/development-environment.md, gulpfile.babel.js, package.json, tests/runner.js
Allows executing unit tests for Javascript code within modules. All javascript unit tests inside any of Jetpack modules will be run after calling the command 'yarn test-modules` in the terminal.
This PR is a suggestion from @ehg, and the code is based on the work done by @c-shultz in the PR #9144 (thanks!)
* Added a new script entry to `package.json` to run modules Javascript unit tests.
* Just execute `yarn test-modules` in Jetpack base folder.
* The command shouldn't fail (command exit status should be 0).
* The output should be:
```  0 passing (1ms)```
since there aren't any Javascript unit tests inside any modules yet.
* You can also add a dummy test to a folder within the modules folder and after running `yarn test-modules` again the test should be executed.
=> Allows to run tests for modules Javascript code

.svnignore
Adds `dangerfile.js` to `.svnignore`.
* Adds a line mentioning `dangerfile.js` to .svnignore. We don't need the file published in the plugin directory.
None needed
=> General: SVN ignore dangerfile.js

class.jetpack-post-images.php
We have recently introduced a minimum 200x200 image size when extracting images from HTML markup. Unfortunately, sometimes the image has one of the dimensions slightly less than the minimum, but otherwise it fits the featured image perfectly. Or some sites do not use dimension properties at all, even though images are perfectly fine size wise. This change lets users customize size properties parsing. Related to 8081-wpcom.
* Added a filter to allow for custom image dimension treatment.
The filter is currently not used anywhere in Jetpack. You can use it manually by adding a custom check and calling `Jetpack_PostImages::from_html` with an arbitrary HTML, like this:
```
$html = '<img src="https://example.com/example.jpg" />';
error_log( 'Without …
```
=> Added a filter to allow for custom image dimension logic.

dangerfile.js
* update `Test instructions` => `"Testing instructions"`
* Skip Danger checks if `no ci`/`no danger`/`skip ci`/`skip danger` is present in commit message
=> Danger: Update message wording & add `danger skip` check

.travis.yml
Reverting failed attempt on skipping Travis builds to not to be triggered by changes in doc files 
* Revert #9677 
* Revert #9844
* Make sure Travis doesn't have a `before_install` hook anymore
=> Revert: Travis not run on docs (#9677 & #9844)

tests/php/modules/shortcodes/test_class.hulu.php
Fixes failing test runs for all PRs and `master`.
Currently the response of `curl https://www.hulu.com/api/oembed.json?url=http://hulu.com/watch/771496` is being strongly cached and messing with our unit tests.
* Updates a bunch of unit tests related to the Hulu shortcode to be skipped until we get a permanent solution.
* Confirm tests pass for this PR
=> Shortcodes: Update hulu tests to be skipped

functions.global.php
Updates the agreement text on the new Connection Splash screen to be consistent with the text present in the Jetpack connection screen (Jetpack dashboard) and on the Jetpack banner present in the WordPress Dashboard.
1. Checkout this PR.
3. Deactivate Jetpack and reactivate
4. Expect to be shown the following text: 
By clicking the <strong>Set up Jetpack</strong> button, you agree to our fascinating <a href="%s" target="_blank">Terms of Service</a> and to <a href="%s" target="_blank">share details</a> with WordPress.com
**Before**
**After**
**Jetpack connection card:**
**WordPress Dashboard banner for Jetpack**
=> Connection Splash Screen: Update agreement text to specify that consent is granted by clicking the Set up Jetpack button

bin/partner-provision.sh
Fixes an issue where specifying `JETPACK_START_API_HOST` on the command line (useful for development) didn't work.
Trying this:
```
JETPACK_START_API_HOST=mysandbox.wordpress.com sh bin/partner-provision.sh --partner_id=12345 --partner_secret=abcd1234
```
Would result in a 404 since the script wasn't specifying the 'host' header, meaning that a WPCOM sandbox would not recognise the incoming request as being to the `public-api.wordpress.com` virtualhost.
In addition, we weren't using the `JETPACK_START_API_HOST` var in the access token request, which meant that this wouldn't go to your sandbox.
What this added up to is that the JETPACK_START_API_HOST env var was broken, and the only way to develop against your sandbox is to modify the /etc/hosts file, which is not possible in all the …
=> Respect JETPACK_START_API_HOST env var in partner-provision.sh

docs/partners/upgrade-redirection.md
Now that we have deployed upgrade redirection logic for partner hosted sites in r177942-wpcom, we should add documentation for that feature.
This PR adds an overview of the functionality as well as a prompt for how hosts can get started.
=> Docs: Partners: Add doc for partners that describes upgrade redirecting

sync/class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-listener.php
This change indicates whether the current action was triggered via the WordPress command line interface
=> Jetpack: Add wp_cli indictator to sync action actor

modules/lazy-images/lazy-images.php
To support browsers without JavaScript enabled, we made a change to hide lazily loaded images by default and then add a class with JavaScript which would show the lazy loaded image. This was done in #9780.
When released, at least two users reported issues with their images no longer being centered. This is because we were setting the display to `inline-block` when we decided to show the image. This PR changes that behavior so that we set display to `block` instead.
~Ideally, we would hide the lazily loaded images by appending a class to the HTML element when the post is rendered. Then, we could just remove the class with JavaScript. That being said, I am not aware of a great way to do this in WordPress.~ I just pushed a second commit to do just that. Essentially, I use a `not` selector on …
=> Lazy Images: Do not change image display for no JS support

modules/widgets/simple-payments.php, modules/widgets/simple-payments/form.php
Follow-up to #9859 
- fix syntax error `$errors.add( 'illegal_params' );`
- add missing message parameter in `->add`
- add missing `jetpack` translation domain
- replace undefined functions `require_lib` and `tracks_record_event`
Test with PHP 5.2 and ensure the widget works normally.
PHP 5.2 Compatibility for Simple Payments Widget
=> Widgets - Simple Payments: fix a few issues

docs/partners/determining-connection-status.md
This PR adds documentation about determining connection status of a Jetpack site for hosting partners. This topic has come up a few times, from different hosts, so having this documentation should simplify things.
* Manually test the suggested connection status checks for connected and non-connected sites
=> Docs: Partners: Add document for determining connection status

class.jetpack-connection-banner.php
> Change “Chat with Us” to “Get in touch with us” since we don’t have embedded chat on the support site yet.
Reported in p6TEKc-2c8-p2
- Spin up a new site; jurassic.ninja is your friend.
- Confirm that the contact us (secondary) button on the connection splash shows the updated label.
=> Connection splash: update copy on contact us button

_inc/jetpack-connection-banner.js
Make sure we don't scroll users to top when clicking “Start quick tour” or “Next feature” on the quick tour banner.
Reported in p6TEKc-2c8-p2
- Spin up a new site; jurassic.ninja is your friend.
- Make sure the “next step” links on the quick tour banner don't scroll the browser window to the top.
=> Quick tour: don't scroll to top

composer.json, docs/development-environment.md, package.json, phpcs.xml
We had the PHP Codesniffer standard `PHPCompatibility` already be installed by composer but not declared in the `phpcs.xml' file. 
* Updates `phpcs.xml` to use `PHPCompatibility` as a rule.
* Introduces two `composer` scripts:
* `composer php:5.2-compatibility`.
* `composer php:lint`.
* Updates `development-environment.md` to mention these commands.
* Introduces three `yarn`/`npm` scripts:
* `yarn php:5.2-compatibility`. Wrapper for `composer php:5.2-compatibility`. 
* `yarn php:lint`. Wrapper for `composer php:lint`.
* `test-adminpage`. Wrapper for `yarn test-client && yarn test-gui`.
* Run `yarn php:5.2-compatibility` and expect to see a lot of errors only related to the Jetpack PHP code being not fully compatible with PHP 5.x versions.
* Run `yarn php:lint` and …
=> General: Update PHP Codesniffer configuration to include the PHPCompatibility standard

sync/class.jetpack-sync-module-updates.php, tests/php/sync/test_class.jetpack-sync-updates.php
This Pr makes sure that we do not mark updating core via calypso as a autoupdate in the Activity log.
* Check that the constant REST_API_REQUEST is not defined or set to false. 
Set your site to need an update. By changing $wp_version in wp-include/version.php
use the core/update api endpoint to update the site to the latest version. 
Notice in the activity log we say who updated the core in the activity log as expected.
=> Fix: When we update core in using calypso we wouldn't send the event as a core autoupdate

sync/class.jetpack-sync-module-users.php, tests/php/sync/test_class.jetpack-sync-users.php
Indicate via Jetpack sync when user confirms email address change for display in the Activity Log.
Testing instructions: 
Change your super admin email address and confirm via email. Confirm sync payload indicates email changed.
=> Indicate when user email changes via Jetpack sync

tests/php/modules/shortcodes/test_class.hulu.php
Reverts Automattic/jetpack#9850
It appears that the Hulu json endpoint started worked again.
Confirm unit tests pass on this PR.
=> Shortcodes: Revert "Shortcodes: Update hulu tests to be skipped"

tools/jetpack-live-branches/jetpack-live-branches.user.js
Updates the Jetpack Live Branches Tampermonkey script to have Gutenberg checked by default.
* Updates the `jetpack-live-branches.user.js` Tampermonkey script to have Gutenberg checked by default.
* Install ths `1.5` version of the script by [clicking here](https://github.com/Automattic/jetpack/raw/update/jetpack-live-branches-gutenberg-checked-by-default/tools/jetpack-live-branches/jetpack-live-branches.user.js).
* visit a Pull Request.
* Expect Gutenberg to be checked by default
=> Make Gutenberg be checked by default in Jetpack Live branches

3rd-party/woocommerce.php
Fixes #9914
In testing, I noticed that the images returned from the AJAX request are not processed by the lazy images module. You can see this yourself by adding a `console.log( data );` around this line: https://github.com/woocommerce/woocommerce/blob/387093cd27f097c71b2fcb4bfd73362d058c3ed9/assets/js/frontend/cart-fragments.js#L42
Note, you'll also need to set `define( 'SCRIPT_DEBUG', true);` in `wp-config.php` to load the non-minified file.
This makes me think that the initial lazy loaded image, that is set when the page initially loads, is being stored somewhere in the Woo script. We should probably find that. Perhaps @coderkevin or @mikejolley can help explain why that is happening and or correct me if I'm wrong.
That being said, this PR does fix the reported issue.
* Add a listener …
=> Lazy Images: WooCommerce: Adds compat for lazy images when updating cart quantity

modules/shortcodes/flatio.php
Adds oEmbed endpoint for flat.io.
To test:
1. Start a new post and paste `https://flat.io/score/5a5268ed41396318cbd7772c-string-quartet-for-rainy-days` on a new line.
2. Publish the post and see the embed.
More details about the oEmbed: https://flat.io/developers/docs/embed/oembed.html
Requested via 1253763-zen and Twitter https://twitter.com/CJRPhD/status/1013205598106800128
=> Shortcodes: Add flat.io oEmbed

docs/partners/determining-provisioning-status.md
Now that I've provisioned a status endpoint for partners in D16141, we should add a support document for hosts.
* Add support doc
- Ensure description and examples make sense
- Possibly try it out live by provisioning getting a partner key and secret and making queries
- For instructions on setting up a partner ID and secret, see: PCYsg-eDL-p2
Note: The link in the document does work. To test it:
- Go to the specific commit hash for this PR
- Click browse files 
- Navigate to this doc in `/docs/partners`
- Click link
=> Docs: Partners: Add doc for retrieving provision status of a site

class.jetpack.php, modules/seo-tools.php
* Registers The SEO Framework as:
* An SEO plugin
* A verification plugin
* A sitemap plugin
* Removes The SEO Framework as:
* A conflicting Open Graph plugin, it's now superseded.
The outcome should be no different from when other SEO plugins are present. Little to no testing is needed.
* Improved compatibility with The SEO Framework plugin.
=> Improves The SEO Framework compatibility.

_inc/lib/class.core-rest-api-endpoints.php, tests/php/_inc/lib/test_class.rest-api-endpoints.php
Currently, when we change the connection owner of a Jetpack site in Calypso (AKA "Site Owner" in the Calypso UI), this only changes the master user, but doesn't actually change the site ownership. As consulted earlier with @kraftbj and @dereksmart, master user and site ownership must be the same.
* Update the `/connection/owner` REST API endpoint to change the blog owner when the connection owner is changed.
* Update tests to skip the XML-RPC request as it's beyond our testing capabilities.
* Checkout this branch on your Jetpack site.
* Make sure you're admin in the site, you're connected and you're the connection/site owner.
* Make sure you're proxied, as the feature is available only in Calypso staging.
* Make sure there is at least 1 more connected admin user in your Jetpack site.
* Go …
=> REST API: Change blog owner when changing the connection owner

class.jetpack-connection-banner.php
Fixes p8oabR-fb-p2 #comment-1839
* Replaces mention of `OSX` for `macOS`. 
This was observed during the Jetpack 6.3 call for testing, but will be punted to 6.4 as the translations are already done including `OSX`.
=> Connection Splash Screen: Replace OSX for macOS in connection banner

modules/publicize/publicize-jetpack.php, modules/publicize/publicize.php
This change removed the ability for users to select personal pages from the facebook selection. 
Before:
After:
if the user has 1 page to select
If the user has no pages to select.
Another minor fix:
This gets display to the user after they connect Facebook but haven't selected the account just yet to which they want to publish to. Before it used to show the users name. 
Connect your facebook account. 
Does the dialog make sense?
=> Publicize: Remove the ability to select personal facebook page from the overlay

modules/theme-tools/site-logo/inc/class-site-logo.php
> WordPress has changed that section to Site Identity since 4.3 so you shouldn't mess with it anymore as the new name is more inclusive. At least you shouldn't do this for 4.3 or newer.
This PR removes the custom name for the "Site Identity" section in the Customizer. The custom name is unnecessary, given core's updating of the section name in 4.3.
Fixes #3082. Props stalebot ;)
----
- Visit the Customizer with this patch applied.
- The section containing Site Title, Tagline, and Logo should be named "Site Identity"
=> Site Logo: remove custom name for "Site Identity" section

modules/publicize/publicize-jetpack.php, modules/publicize/publicize.php, modules/publicize/ui.php
* Some Code clean up. 
* Removed the error showing when the we are in the middle of the connection process. 
* Made sure that the user doesn't show up when we are in the middle of the connection process.
* Try connecting a facebook group notice that the error in the background is not there any more. 
* Connect a tumbler account it still works as expected. 
* Start the connection process and notice that post wrote screen is working as expected. 
Before:
After:
=> Publicize: Fix warning showing in the backhground when connecting facebook to publicize

functions.global.php
I noticed someone left the "Set up Jetpack" button untranslated in the description, although the actual button itself was translated. 
To avoid discrepancies between the button text and the description above it, I made the button text a placeholder and added a translator's comment.
=> Fix: Make the button text in a sentence a placeholder

changelog.txt, readme.txt
This adds changelogs entries for #9938, #9927, #9926, and #9925.
* Updates changelog.txt to include changelog for 6.3.2
* Updates readme.txt to include changelog for 6.3.3
* Bumps stable tag to `6.3.2`
=> Add changelog for 6.3.3.

modules/shortcodes/youtube.php
Fixes # black letterboxing bars above and below normal 16:9 ratio-ed Youtube embeds, see https://github.com/Automattic/jetpack/issues/9800
Remove addition height "+ 30" from responsive ratio-ed height calculation.
=> Remove extra 30px from responsive height

modules/comments/comments.php
When `amp` theme support is present and the Comments module is active, attempting to submit a comment through the iframed form results in `sandbox` security errors. To get around these, adding the explicitly-required sandbox permissions is needed.
For more, see https://www.ampproject.org/docs/reference/components/amp-iframe#sandbox
This change also removes a `script`, since it is disallowed by AMP. Maybe there is another/better way to achieve `allowTransparency` and `scrolling=no`?
How to reproduce the issue:
1. Install [AMP v1.0-beta1](https://github.com/Automattic/amp-wp/releases/tag/1.0-beta1).
2. In the admin, go to AMP > General settings and enable Native template mode.
3. Activate the comments module in Jetpack.
4. Navigate to a post and attempt to leave a comment.
Upon clicking the …
=> Improve AMP compatibility for Comments iframe

modules/widgets/top-posts.php
* A `jetpack_top_posts_widget_layout` filter has been added that allows you to create a custom display layout for the <b>Top posts</b> widget
* Everything should work as before
=> Widgets: Add jetpack_top_posts_widget_layout filter

modules/contact-form/grunion-contact-form.php
The aim of this PR is to add a bit of flexibility to the data exporter and eraser so they can be tailored to the needs of different privacy and data retention policies. For example, on WordCamp.org, we want to retain our contact form submissions for 3 years, so any Feedback posts that are newer than that shouldn't be erased.
To this end, I'm proposing the following changes, which I will add as commits to this PR:
* Use associative strings when registering the exporter and eraser callbacks
* Allow individual items to be skipped during erasure via a filter, similar to how Core's comments eraser works
* ~Perhaps add filters to modify which individual Feedback fields get exported and erased~
Follow the testing steps in #9395 to get set up and confirm that data export/erasure are working. …
=> Contact Form: Updates to data exporter/eraser

modules/contact-form/grunion-contact-form.php
Fixes #2734
* Only optimize tables upon specific intent. 
As described in 2734, Core restricts this type of activities behind a repair flag. All in all, either way, this is relatively safe since it runs on the daily cron and, even then, very randomly.
If we want to assist with optimization items like this, we should do it more intentionally than just within the contact form module.
=> Contact Form: Only optimize tables via a filter

docs/partners/plan-provisioning-direct-api.md
After D16780 is merged, we'll need some documentation to explain to hosts how we deal with issues where DNS does not resolve.
* Adds doc to describe fallback for when DNS does not resolve for a given URL.
* Read doc and ensure it makes sense and there are no typos.
* Alternatively, manually provision a plan for a URL that will not resolve following instructions on  PCYsg-eDL-p2
- Updates partner documentation to describe fallback for when DNS not resolve for a given URL.
=> Docs: Partners: Add doc to describe fallback when DNS does not resolve

sal/class.json-api-site-base.php
This PR adds a filter which allows setting the `is_automated_transfer` site option.
The SAL method `is_automated_transfer()` is called by the `/rest/v1.2/sites$site` endpoint.
The filter will be used later, so the testing instructions simply reduce to check that everything is ok.
=> Added a filter for the AT is_automated_transfer state flag.

docs/partners/plan-provisioning-direct-api.md, docs/partners/plan-provisioning.md
Previously, we allowed hosts to use the Jetpack Start API to provision a site without a plan, called a Jetpack Free plan from here on out. This worked by leaving off the `plan` argument. Now, the API has been changed to allow sending `free` as a plan so we should update our docs to reflect that.
* Expand the allowed plans mentioned in the partner provisioning docs to include free.
* Ensure that changes make sense
Updated partner documentation to mention free plan as a provision option.
=> Docs: Partners: Mention the ability to use free plan

sal/class.json-api-site-base.php
Before that we were using an environment check and using a getter method that required PHP namespace syntax. This didn't work in PHP 5.2, so we are changing it to a filter call.
Fixes #9943.
Related: D16395-code
=> Added a filter for the AT pending state flag.

class.jetpack.php, modules/publicize/publicize.php, modules/publicize/ui.php, modules/sharedaddy/sharing.php, readme.txt
* Reverts #9951
* Removes changelog entry.
Changes introduced in #9951 are not behaving as expected and expectations are not clear enough for testing. We need to revert.
=> Revert "Sharing: Update sharing links to redirect to calypso"

modules/sharedaddy/sharing-sources.php
_Fixes an issue introduced in https://github.com/Automattic/jetpack/pull/9644 where Google would crawl sharing links, because a duplicate rel tag meant the first rel="nofollow" was ignored. After this fix, the additional rel tags are combined with the first._
* move noopener and noreferrer tags into existing rel tag
* Install Jetpack and enable sharing.
* Inspect the sharing links, there should only be one rel tag. 
[Status] Needs Review
See https://github.com/Automattic/jetpack/pull/9644#issuecomment-411115258
=> Fix rel issue - move noopener and noreferrer tags into existing rel tag

tests/prepare-wordpress.sh
Prevents further errors after cloning WordPress and failing.
* Maxie the `tests/prepare-wordpress.sh` fail immediately if there was a problem attempting to clone WordPress.
1. Check the Travis runs and see how it currently fails earlier than attempting to copy Jetpack over the cloned WordPress source codel.
=> Unit Tests: Fail immediately if we cannot clone WordPress

modules/comments/comments.php
Fixes #10000 
Changes introduced in #9681 were bringing issues with comments on non AMP environments. 
* Updates the `sandbox` attribute to read `allow-same-origin allow-top-navigation` and thus allowing the functions needed by the remote JS file loaded for comments
* Check this branch with a theme that has styles for threaded comments. like Storefront .
* Reply to a comment on a post, in the front-end.
* Open the dev console. Expect no erros coming from the browser blocking requests or actions
* Expect to see the comment threaded
* Comments: We fixed an error that broke functionality of nested comments.
=> Comments: Fix values used on sandbox attribute for comments iframe

readme.txt
This adds a changelog entry for #10001.
* Updates readme.txt to include changelog for 6.4.1
* Bumps stable tag to `6.4`
none needed
=> Add changelog for 6.4.1

class.jetpack.php, modules/lazy-images/lazy-images.php, tests/php/modules/lazy-images/test_class.lazy-images.php
Fixes an issue that a user pointed out in this comment:
https://github.com/Automattic/jetpack/pull/8787#issuecomment-411196808
* Fix a typo in `jetpack_lazy_images_skip_image_with_atttributes` so that the filter is `jetpack_lazy_images_skip_image_with_attributes`.
* Deprecates `jetpack_lazy_images_skip_image_with_atttributes` filter
* `phpunit --filter=WP_Test_Lazy_Images` to ensure that both filters work
Deprecates `jetpack_lazy_images_skip_image_with_atttributes` filter in favor of `jetpack_lazy_images_skip_image_with_attributes` to address typo.
=> Lazy Images: Fix typo in attributes filter name

modules/comments/comments.php
Fixes #10005
See #9681
* Add `allow-popups` to `sandbox` attribute. The social login buttons depend on it.
1. Click each of the social login buttons. Do they work? :)
2. Leave a comment using each method:
* Logged out completely
* Logged in to WordPress.com
* Using each of the Social Login options
* Logged in to the local Jetpack site
Fix an error that broke social login buttons when commenting.
=> Comments: Add `allow-popups` to iframe so that social logins work.

readme.txt
This adds a changelog entry for #10006.
* Updates readme.txt to include changelog for 6.4.2
* Bumps stable tag to `6.4.1`
none needed
=> Add changelog for 6.4.2

3rd-party/debug-bar/class.jetpack-search-debug-bar.php
During testing today, I noticed that a CSS and JS file from Jetpack for Debug Bar integration were being loaded on all visits to my personal site, even when I was logged out. This didn't happen when I only used Debug Bar, but when I was using Query Monitor, which support Debug Bar panels, the CSS and JS files were loaded unnecessarily.
We shouldn't load those files unless necessary.
* Do not load CSS and JS file for Debug Bar integration unless Query Monitor or Debug Bar CSS has already been enqueued.
- Purchase Jetpack Professional plan
- Ensure Search module is on
- Install and activate Debug Bar
- While logged in, perform a search on frontend of site and ensure Jetpack Search debug panel shows
- Ensure that you can prettify JSON output in panel
- In an incognito, or …
=> Debug: Do not enqueue Jetpack Search debug bar scripts unless necessary

modules/widgets/twitter-timeline.php
Twitter stopped supporting the `widget-id` parameter on 2018-07-27. Ahead
of time, we hardcoded a cutoff date near then as part of a warning to
folks.
That date is in the past, so we no longer need the check.
See https://github.com/Automattic/jetpack/pull/9575
* Remove cutoff date check that is no longer necessary.
1. Agree that `time() > 1532563200` :)
=> Widgets: Twitter Timeline - Remove Cutoff Date that has now passed

modules/shortcodes/wufoo.php
Summary:
This removes the ssl argument of shortcode and replaces everything to work over https. SSL used to be a paid feature over at Wufoo but that changed 5 years ago https://www.wufoo.com/blog/making-wufoo-more-secure-https/
It also turns the old embed codes into their new async version and makes sure only a single `form.js` would be loaded even for multiple forms.
Testing instructions: Test with various wufoo embed shortcodes, all should work over https, regardless whether they set https argument (to true/false) or not at all.
Reviewers: paulbunkham
Reviewed By: paulbunkham
Subscribers: mdawaffe, paulbunkham, jblz
Differential Revision: D16996-code
This commit syncs r179447-wpcom.
Updated Wufoo Shortcode to always load over https and use async form embed.
=> Make Wufoo safe for https usage and async

_inc/client/at-a-glance/backups.jsx, _inc/client/at-a-glance/scan.jsx, _inc/client/components/jetpack-connect/index.jsx, _inc/client/components/themes-promo-card/index.jsx, _inc/client/plans/plan-body.jsx, _inc/client/plans/plan-grid.jsx, _inc/client/plans/plan-header.jsx, _inc/client/security/backups-scan.jsx, _inc/client/state/initial-state/reducer.js, _inc/lib/admin-pages/class.jetpack-react-page.php, class.jetpack-connection-banner.php, class.jetpack.php
Currently, our module overrides functionality does not allow disabling UI relating to VaultPress or Backups. This is an issue for some of our partnerships where hosting partners need the ability to disable that UI.
* Add ability to disable backups related UI.
- In an integration plugin, add `add_filter( 'jetpack_show_backups', '__return_false' );`
- Load Jetpack admin page
- Ensure that backups and scanning are not mentioned in UI
- Install and activate VaultPress
- Ensure that backups and scanning are mentioned
- Adds ability to disable backups UI by filter when VaultPress is not activated.
**After**
**Before**
=> Module Overrides: Add support to disable backups UI

_inc/lib/class.media-summary.php
Starting in PHP 7.3 (currently in Beta 2), PHP will throw a warning when using `continue` within a `switch` to confirm intent. In PHP, within `switch`, `break` and `continue` do the same thing while in other languages `continue` would behave like PHP's `continue 2`.
This would preserve the same behavior and avoid the warning. See https://github.com/php/php-src/blob/php-7.3.0beta2/UPGRADING
Based on the current timeline, this would need to land no later than our December release (6.8 based on our monthly clip). PHP 7.3 is expected to go into GA on December 13th. Since this is a backwards compatible change, no reason to wait though.
1. Before patch, run something via PHP 7.3. See warning.
2. Apply patch, repeat, see no error.
* Improves compatibility with the upcoming PHP 7.3
=> PHP 7.3: Use break instead of continue within a switch case

modules/subscriptions.php
Fixes #
* Moves the subscription checkboxes from after the submit button to before the submit button
* When viewing the subscription options underneath the comments box on a site, the checkboxes should be over the Post Comment button.
Moves the subscription checkboxes from after the submit comment button to before the submit button.
=> Put the checkboxes to subscribe to comments above post comment button.

_inc/client/components/module-settings/connect-module-options.jsx, _inc/client/components/module-settings/module-settings-form.jsx, _inc/client/traffic/verification-services.jsx, _inc/lib/class.core-rest-api-endpoints.php, modules/verification-tools/blog-verification-tools.php, modules/verification-tools/verification-tools-utils.php, tests/php/modules/verification-tools/test_functions.verification-tools-utils.php
The validation for meta tags entered in the Jetpack Settings page for site verification is overly strict. In fact, even the same meta tags we offer in our alternative UI (under "tools" in the wp-admin menu) don't work! (because they aren't self-closing tags, lack a space before the `>`, and use single instead of double quotes).
This PR updates the input validation we have for meta tags used for website verification services. We just want a meta tag that is valid enough so we can extract the value of the content property from it. HTML parser on browsers are quite flexible so we need to allow all kinds of valid meta tags.
For instance this change makes it so those are valid:
- `<meta name="google-site-verification" content="1234"/>` (no space before `/>`)
- `<meta …
=> Make check for meta tag to verify site more permissive

_inc/class.jetpack-provision.php, _inc/jetpack-server-sandbox.php, class.jetpack-cli.php, class.jetpack-client.php, class.jetpack-signature.php, jetpack.php
Currently, Jetpack provides a number of configurable constants that define various domains and endpoints (public-api.wordpress.com, dashboard.wordpress.com, etc.). These constants serve two purposes in Jetpack:
1. So we don't have to keep typing the same domains over and over again (typo prone), and
2. So we can change them to point various requests at Automattic sandboxes.
These two purposes get muddled. When we want to point public-api.wordpress.com requests to a sandbox, for example, we set the `JETPACK__WPCOM_JSON_API_HOST` constant. This:
* [changes the URL](https://github.com/Automattic/jetpack/blob/d7a1fadb4163d62d388c1b636c05f261fbab31fd/class.jetpack-client.php#L338) to use the sandbox domain,
* tells `Jetpack_Client` to set a [`Host` …
=> Improve Sandboxing for Automattic Developers

modules/sitemaps/sitemaps.php
We've been running into issues with custom post types not showing up in sitemaps. These custom post types are leveraging the `jetpack_sitemap_post_types` filter. Testing locally, it appeared that custom post types _do_ appear in sitemaps after running `wp jetpack sitemap rebuild  --url=URL`; however, custom post types would _not_ appear after running `wp cron event run --all --url=URL`.
Testing locally, it seemed that, for cron, the `Jetpack_Sitemap_Builder` instance was getting created too early for the theme's `jetpack_sitemap_post_types` filter to be registered. As such, the `jetpack_sitemap_post_types` WP option value, updated in the constructor method of `Jetpack_Sitemap_Builder`, is reset to the default value of `array( 'post', 'page' )`.
This PR attempts to patch this issue by …
=> Fix: sitemap cron with custom post types

modules/geo-location/class.jetpack-geo-location.php
Before the geolocation tool would add the namespace attribute that was not separated by anything in the beginning of the string. This caused issues like #9885, where a plugin would add their own namespacing and cause a validation error because Jetpack would add a namespace right next to it without any spacing.
This PR, however, does not fix the problem of duplicate namespace attributes, which would also cause validation errors. In case of duplicate namespaces we need to disable Jetpack's functionality one plugin at a time by adding them to conflicts.
Fixes #9885 
* Adds `PHP_EOL` to both ends of the namespace string.
* Add a plugin that uses the `rss2_ns` hook, or better yet, create one yourself: https://gist.github.com/zinigor/8c2fb946536be33b2cb141d5808d57b4
* Feed your feed into [the …
=> Added line breaks to namespace attribute.

modules/wordads/php/api.php, modules/wordads/php/params.php, modules/wordads/wordads.php
* Prevents ads from showing on sites marked as unsafe (fetched daily via api)
Follow the testing instructions in D17303-code, using the new corresponding api work.
Proposing no changelog entry.
=> WordAds: don't show ads on unsafe sites

_inc/client/traffic/ads.jsx, _inc/lib/class.core-rest-api-endpoints.php, modules/wordads/php/params.php, modules/wordads/wordads.php, sync/class.jetpack-sync-defaults.php, tests/php/sync/test_class.jetpack-sync-options.php
There are is a small subset of advanced users that run multiple ad networks in addition to the Jetpack ads module that overrides our custom ads.txt. Since our ads.txt is frequently updated and custom tailored to the site we need a way to allow users to include custom entries.
Additionally, changes to the ads.txt should show up in Jetpack Sync (separate commit):
* Custom ads.txt textarea w/ explanation & instructions in ads module.
* Restored `Save Settings` button to accommodate textarea entries.
* New filter to insert custom entries into latest ads.txt pulled from API.
**Admin update**
**ads.txt update w/ `#Jetpack - User Custom Entries`**
1. Enable Jetpack ads module.
1. View `<site>/ads.txt` and verify `#Jetpack - User Custom Entries` is not present.
1. Add custom entries to `Custom …
=> Add interface for custom ads.txt entries

.editorconfig
Original work by @abidhahmed .
The commit here was cherry-picked from #9980 and removed from that PR.
* Update line-endings config in `.editorconfig` for `.txt` files from CRLF to LF.
1. Check this branch
1. Open readme.txt in an editor that support `.editorconfig` files and confirm all is good.
=> General: Update .editorconfig for txt files from CRLF to LF

modules/lazy-images/lazy-images.php
Use a base64 encoded transparent to reduce a network request.
- Ensure that site has Lazy Images turned on
- Create a post/page with some images in it
- Load the post/page
- Ensure that images loads properly
- If you view the source when the page first loads, you should see the base64 encoded image
Update lazy images to use a base64 encoded transparent to reduce a network request.
=> Lazy Images: Use base64 encoded transparent gif

class.jetpack-xmlrpc-server.php, class.jetpack.php, modules/contact-form.php, tests/php/test_class.jetpack-xmlrpc-server.php
We are currently working on improving flows for our users that connect via hosting partners. Part of this will be auto-connecting sites/users where the user connecting does NOT have an existing WordPress.com account. In this case, we'll create a new WP.com account for the user and then auto-connect the site. See D16948 for the required WPCOM patch.
* Add `jetpack.remoteConnect` method for automatically connecting a disconnected site, given a local user ID and a token.
- `phpunit --filter=WP_Test_Jetpack_XMLRPC_Server`
- Checkout `D16948` on WordPress.com
- Manually test flow
- Ensure email address of user on does not have existing WP.com account
- Ensure that you're sandboxing WordPress.com:
- Use the following command, replacing partner the arguments :
- `sh …
=> XML-RPC: Partners: Add jetpack.remoteconenct method for auto-connect a site

class.jetpack-cli.php
While testing for #10072, I noticed that `wp jetpack publicize --help` wasn't returning the correct output. Specifically, it wasn't returning examples or options for the command.
* Fix documentation for `wp jetpack publicize` command so that the `wp jetpack publicize --help` works properly.
* Bring documentation closer in line to WP-CLI documentation standards
- Against `master`, run `wp jetpack publicize --help` and observe output like this:
```
NAME
wp jetpack publicize
SYNOPSIS
wp jetpack publicize
GLOBAL PARAMETERS
--path=<path>
Path to the WordPress files.
--url=<url>
Pretend request came from given URL. In multisite, this argument is how the target site is specified.
--ssh=[<scheme>:][<user>@]<host|container>[:<port>][<path>]
Perform operation against a remote server over SSH (or a …
```
=> CLI: Fix issue where help for publicize command did not show long description

class.jetpack-cli.php
JN sites set the `WP_HOME` and `WP_SITEURL` constants by doing the following:
```
define('SP_REQUEST_URL', ($_SERVER['HTTPS'] ? 'https://' : 'http://') . $_SERVER['HTTP_HOST']);
define('WP_SITEURL', SP_REQUEST_URL);
define('WP_HOME', SP_REQUEST_URL);
```
In CLI, `$_SERVER['HTTP_HOST']` is either empty or isn't set, which causes the url to be `https://` or `http://`.
This causes the site to be in development mode due to this line:
https://github.com/Automattic/jetpack/blob/09794f658cca9ef3a5d3ae41bce02b04235c0b66/class.jetpack.php#L1599
Add a a development mode check to the `wp jetpack publicize` command so that we bail when the `Publicize` class does not exist.
- On a JN site, SSH in
- Run `wp jetpack publicize list`
- Ensure there is an error like this:
```
Fatal error: Uncaught Error: …
```
=> CLI: Publicize: Fix issue where publicize command would error for JN site

_inc/client/traffic/search.jsx
Fixes the word search composed in all lowercase.
=> Search: capitalize Search

tools/builder/frontend-css.js
This PR fixes the path to the file to be minified. Since it was incorrect, it wasn't being minified but it was in the styles enqueued, and thus removed from being included on its own. This resulted in missing styles and wrong layout in the front end.
Verify that the new path leads to the right file, it's this
https://github.com/Automattic/jetpack/blob/master/modules/widgets/search/css/search-widget-frontend.css
You can also build this branch and verify that styles are correct now.
=> Search: fix path to CSS file to be minified

class.jetpack-cli.php
In #10075, we fixed an issue where the `wp jetpack publicize` command would error due to the publicize module not being loaded because the site was in development mode. What I didn't consider at the time was that the same error would occur if the module had been deactivated and the `wp jetpack publicize` command was called.
This PR fixes that by adding a check to see if the Publicize module has been loaded.
On a connected site:
- In `wp-config.php`, add `define( 'JETPACK_DEV_DEBUG', true );`
- Run `wp jetpack publicize list`
- Ensure you get an error message like:
> Error: Jetpack is currently in development mode.
- Ensure that you do not see any errors
- Remove `JETPACK_DEV_DEBUG` define
- Run `wp jetpack module deactivate publicize`
- Run `wp jetpack publicize list`
- Ensure that you …
=> CLI: Publicize: Fixes an issue where an error could occur when publicize not active

modules/lazy-images/lazy-images.php
In #10054, I introduced a bug that can occur when an image is processed multiple times. The condition that we had in `process_image()` to keep us from double processing an image was... messed up. 😞 
First, it was checking in the processed attributes, instead of the attributes for the image that we are about to process.
Second, the logic was backwards. We wanted to bail if we detected the presence of a class, but that condition was bailing if we did not detect the presence of the class.
This became apparent to me when testing against a site with the Storefront theme and WooCommerce. Specifically, blank space was showing where images should be on the shop page.
So, if possible, I would test the following against a WooCommerce site with Storefront:
- Create products with images and load the …
=> Lazy Images: Fix issue introduced in #10054 where some images were double processed

modules/contact-form/grunion-contact-form.php, tests/php/modules/contact-form/test_class.grunion-contact-form.php
Fixes #10076 
Instead of doing a "normal" WP_Query search, we refine the search with a more complicated query. To do that, we extract the email address from the normal query, and use it to build the more complicated query.
We were not taking into account the fact that string representing the email address can change when used in the query: in particular, because we LIKE (and SQL) escapee the data, the strings representing email addresses with underscores in them change.
When we build the more complicated query, we do another round of LIKE (and SQL) escaping, which is one round too many :)
For an address like `under_score@example.com`, we end up actually searching for `under\\_score`.
Instead of relying on passing the email address around in the query itself, let's just hold on to it in an …
=> Contact Form: Improve Email Address Handling Personal Data Eraser

class.jetpack-heartbeat.php
Fixes #10070
Props to @kraftbj for finding the source of the issue.
> The XML-RPC server sets a default param of `array()` via https://github.com/WordPress/WordPress/blob/4.9.8/wp-includes/IXR/class-IXR-message.php#L17
and it passes that to the method via https://github.com/WordPress/WordPress/blob/4.9.8/wp-includes/IXR/class-IXR-server.php#L65
_The proposal here is based on a personal opinion that using `generate_stats_array` was being overloaded in usage as both a direct xmlrpc method handler and a statically callable method for other purposes._
* Adds a new static method `Jetpack_Heartbeat:: xmlrpc_data_response` method as handler for the XML RPC request `jetpack.getHeartbeatData`.
* Start with a connected Jetpack site, and `WP_DEBUG` `WP_DEBUG_LOG` constants set to true.
* Pass your …
=> Heartbeat: Improve xmlrpc request argument handling 

_inc/client/at-a-glance/activity.jsx, _inc/client/plans/plan-body.jsx, _inc/client/security/backups-scan.jsx
We are changing the URL from 'wordpress.com/stats/activity/' to 'wordpress.com/activity-log/'
See: https://github.com/Automattic/wp-calypso/pull/26941
This PR will update links in the dashboard to point to the activity log's new URL:
**In the at-a-glance section:**
**In the plans section:**
**In the settings -> security section:**
=> Activity Log: update remote url

json-endpoints/class.wpcom-json-api-site-settings-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php, json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
Differential Revision: D17676-code
This commit syncs r180015-wpcom and brings these three files in sync. It has already been merged to wpcom. 
Summary:
- indicator of if jp search supported
- enable/disable flag
Test Plan:
- TeamCity Tests (done)
- Apply the patch and ensure that `/sites/%site/settings` is returning the correct value for the given site. And no errors. 
- Either none or... "API: add flags to determine if Jetpack Search is enabled and supported."
=> Site Settings API: add jetpack search controls

modules/masterbar/masterbar.php
In https://github.com/Automattic/wp-calypso/pull/26941 we are adding the activity log to the sidebar.
This PR adds the activity log to the master bar.
This is the complimentary .com pr D17682-code 
* Add the activity link to the master bar
* Activate the Master bar to your site. 
* Manual testing: Does the activity log link work as expected? 
Add the activity link to the master bar
=> Masterbar: Add the activity link to the master bar

sync/class.jetpack-sync-module-users.php
This PR fixes a PHP notice found in my error log>
In cases where get_user_by doesn't return a valid user object this PR supressed the followind php Notice.
```
[04-Sep-2018 20:23:06 UTC] PHP Notice:  Trying to get property of non-object in /var/www/html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-users.php on line 299
[04-Sep-2018 20:23:06 UTC] PHP Stack trace:
[04-Sep-2018 20:23:06 UTC] PHP   1. {main}() /var/www/html/wp-admin/themes.php:0
[04-Sep-2018 20:23:06 UTC] PHP   2. switch_theme($stylesheet = *uninitialized*) /var/www/html/wp-admin/themes.php:33
[04-Sep-2018 20:23:06 UTC] PHP   3. do_action($tag = *uninitialized*, $arg = *uninitialized*, *uninitialized*, *uninitialized*) /var/www/html/wp-includes/theme.php:753
[04-Sep-2018 20:23:06 UTC] PHP   4. …
```
=> Fix: PHP Notice

jetpack.php, phpcs.xml, readme.txt
This is consistent with the current support that we announce.
We support current WordPress version and previous one.
* Updates `JETPACK__MINIMUM_WP_VERSION` to `4.8`
* Start with a site with no Jetpack. 
* Install WP Downgrade to go back to WordPress 4.7
* Download ...
*
General: We updated the minimum WordPress version to 4.8
=> General: Update minimum required WordPress version to 4.8

sync/class.jetpack-sync-module-attachments.php, tests/php/sync/server/class.jetpack-sync-server-replicator.php, tests/php/sync/test_class.jetpack-sync-posts.php
This PR changes attachment update syncing to be triggered by `attachment_updated`, and syncs a specific action when the update changes the post_parent from 0 to non-zero, which is indicative of an attachment being attached to a post.
Testing Instructions:
Attach an existing post from your media library to a post by clicking `Add Media` in the post. You should see the `jetpack_sync_save_update_attachment` sync action come through on your wpcom sandbox.
phpunit tests were added to test this functionality as well
=> Jetpack: Sync when an attachment is added to a post for the first time

modules/protect/math-fallback.php
This PR seeks to solve a layout issue that was originally found in japanese. Note how the translation of the string "Prove your humanity" is long and causes the math question to be splitted in two lines.
After a discussion with @naokomc where she stated that this could cause issues in other languages and pointed to 
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/nl/default?filters%5Bterm%5D=Prove+your+humanity%3A&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/ru/default?filters%5Bterm%5D=Prove+your+humanity%3A&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sor …
=> Protect: fix layout of "Prove your humanity" label

modules/widgets/search.php
* Extract default name into constructor.
* Extract search activation into methods. (Making it easy for WordPress.com
to implement its own methods.)
* Fix some typos.
1. Create a site with Jetpack Professional plan
2. Go to https://wordpress.com/settings/traffic/{your site}
3. Make sure Jetpack Search (bottom of page) is disabled
4. Go to wp-admin/widgets.php
5. Add the "Search (Jetpack)" widget.
6. Go back to https://wordpress.com/settings/traffic/{your site} (reload the page)
7. (Wait a second or two)
8. See that Jetpack Search is enabled.
Minor Changes to Jetpack Search Widget
=> Widgets: Search: Unify Jetpack and WP.com Code

modules/infinite-scroll/infinity.php
Fixes #9435 
WP bundled themes now have a privacy policy link in their footer, which
is helpful for complying with GDPR rules, but users who enable the infinite
footer lose that link. This adds a similar link to the infinity footer $credits.
* Add a privacy policy link to `$credits` to mimic the new WP bundled theme link
* Publish the privacy policy page on test site
* Enable infinite scroll with this patch applied
* Scroll down to display the infinite footer
* Confirm that it now includes a link to the privacy policy page
(Edit: Added extra step for testing.)
=> Infinite Scroll: Add privacy policy link

_inc/lib/admin-pages/class.jetpack-react-page.php, class.jetpack.php, functions.global.php, modules/after-the-deadline/proxy.php, modules/infinite-scroll/infinity.php, sync/class.jetpack-sync-module-users.php, sync/class.jetpack-sync-wp-replicastore.php, tests/php/sync/test_class.jetpack-sync-full.php
Updates #10099 
* Remove functionality needed prior to WordPress 4.8
* Verify that Infinite Scroll does not cause issues when previewing via the Customizer.
* Ensure Admin Pages are still properly translated when a user's language is not English.
=> Remove code no longer needed since WP minimum is 4.8+

_inc/lib/tonesque.php
Fixes #10124
The color function accepts a type parameter that can be one of the following strings: hex, rgb, or hsv.
Not much to test here. You can check the `get_color` function downer in the same file, to see what types can be used.
Tonesque: fix typo in function's comment.
=> Tonesque: fix typo in function's comment.

functions.opengraph.php
While researching a tangential issue, I realized there's an arg that's never used in `jetpack_og_get_image`. In looking at the history, it was never used in Jetpack ever. The parent command from the WP.com side once used it, but was removed prior to Jetpack gaining OG.
* Deprecates argument for `jetpack_og_get_image`
* Ensure a deprecated arg warning is thrown when WP_DEBUG is true.
None.
=> Open Graph: Remove unused arg

modules/geo-location/class.jetpack-geo-location.php
Fixes #10089
Only enqueue the dashicons when we need them, when the icon must be displayed on the page, and only once.
1. Check out this branch.
2. Go to https://wordpress.com
3. Pick your site, and start writing a new post. Add a location to your post thanks to the option in the sidebar.
4. In your theme or in a functionality plugin, add the following:
```php
function jeherve_enable_geo(){
add_theme_support( 'jetpack-geo-location' );
}
add_action( 'after_setup_theme', 'jeherve_enable_geo' );
```
5. Make sure the little location icon appears alongside the post location when you view that post you just wrote.
6. Make sure the dashicons.css file is not loaded on your home page or on any other page, when logged out of your admin account.
7. Make sure there are no errors in your logs.
* Geo …
=> Geolocation: only enqueue dashicons when necessary.

modules/videopress/class.videopress-player.php
Fixes #9999
Remove duplicate `rel` attributes added in #9644
Check #9644 for any links including a duplicate set of `rel` attributes.
VideoPress: avoid duplicate rel attributes in links.
=> VideoPress: avoid duplicate rel attributes.

sync/class.jetpack-sync-listener.php, tests/php/sync/test_class.jetpack-sync-listener.php
This PR adds the url the request was made on/from to the sync actor to assist in troubleshooting issues where the actor and or payload data does not seem correct.
Please see the detailed instructions I've added for how to observe Jetpack Sync data that is sent from Jetpack to a WPCOM sandbox: PCYsg-hnH-p2
Please follow the above instructions, make a post on your Jetpack site, and confirm that the sync payload (array) that appears in your terminal has a `from_url` field.
=> Jetpack: Add url request was made on/from to actor

sync/class.jetpack-sync-module-posts.php, tests/php/sync/test_class.jetpack-sync-posts.php
This PR, specifically will detect if a post is being saved via Gutenberg's 2-request-post-saving mechanism, which sends 1 request to save the post, and one request to save stuff related to meta boxes.
The aim is to prevent from double-syncing stuff upstream, causing an issue where 2 events appear in the activity log.
To test:
- Apply this PR to a test site
- Publish and Update posts using the gutenberg editor, and with the classic editor
- Observe the sync data flowing up-stream
- Does `is_gutenberg_meta_box_update` appear as expected?
Before merging:
- Test and merge up-stream equivalent: D18168-code
=> Sync: send gutenberg info when syncing posts

_inc/lib/class.core-rest-api-endpoints.php, _inc/lib/core-api/load-wpcom-endpoints.php, _inc/lib/core-api/wpcom-endpoints/hello.php, _inc/lib/core-api/wpcom-endpoints/sites-posts-featured-media-url.php
This PR adds a folder that is designed to share WP REST API (v2 API) code between WP.com and Jetpack and keep them in sync.
This is useful now that you can access Jetpack sites via the WP REST API and public-api.wordpress.com.  The **namespaces** of new endpoints in this folder should be `wpcom/v2` so that they will also work on WP.com.
The endpoints here are just tests, one shows how you can extend the built-in `wp/v2` endpoints and another adds a new route.
To try it, apply D16735-code and this PR, and visit API URLs like the following:
- https://public-api.wordpress.com/wp/v2/sites/nylen.io::jp/posts (note communication with the Jetpack site and `jetpack_featured_media_url` property added to each post object)
- https://public-api.wordpress.com/wp/v2/sites/jnylen0.wordpress.com/posts …
=> WP REST API: Add endpoints synced from WP.com

jetpack.php
Fixes #10136
The `JETPACK__SANDBOX_DOMAIN` constant is set to an empty string by default,
so the existing check wasn't useful enough; the sandbox file was required
even if you had not defined a custom sandbox domain on your end.
1. Add some debugging code to `_inc/jetpack-server-sandbox.php`
2. Do not set the `JETPACK__SANDBOX_DOMAIN` constant. 
3. Your debugging code should not run at all when this branch is active.
Sandboxing: only require sandbox file if the constant isn't empty
=> Sandboxing: only require sandbox file if the constant isn't empty

modules/theme-tools/responsive-videos.php
Fixes #3048
Avoid PHP notice when param is not given.
This was already fixed in #3243, but got reverted by mistake in ab7f2e0d3619bfc483723727bb427656e1581898
1. Add the following to your theme's functions.php file or to a functionality plugin:
```php
function jeherve_enable_resp() {
add_theme_support( 'jetpack-responsive-videos' );
}
add_action( 'after_setup_theme', 'jeherve_enable_resp' );
```
2. Add a few videos from YouTube or Vimeo to your posts. 
3. View your site on a mobile device.
4. Make sure you do not see any PHP notices. 
Responsive Videos: avoid PHP notice.
=> Responsive Videos: avoid notice when param is not given.

jetpack.php
Just because it's Friday... :/
This reverts commit 7adde9eb88fc29dd50f33c098f7851e1a0a84da1 (see #10140)
After further tests, this additional check does not appear to be necessary. The file is only included when necessary.
=> Revert #10140

modules/infinite-scroll/infinity.js
When scrolling, Infinite Scroll periodically looks to see what DOM
elements are no longer in the viewport, caches them, and removes them from
the DOM.
On Android (and others?), switching to/from fullscreen triggers the
`scroll` event, which, in turn, triggers this DOM manipulation. The switch
to fullscreen mode also confuses Infinite Scroll's understanding of what
is visible in the viewport.
Playing a VideoPress video (or fullscreening a Vimeo or other video) on
Android can therefore remove the video from the DOM, which obviously
breaks everything :)
This patch uses the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)
to determine if the browser has switched to or from fullscreen in between
throttled scroll events. If it has, Infinite Scroll will not do …
=> Infinite Scroll: Prevent DOM Caching when Switching to/from Fullscreen

.gitignore, docker/README.md, docker/bin/run.sh, docker/default.env, docker/docker-compose.yml
Use environment variables (`PORT_WORDPRESS`, `PORT_MYSQL`, ...) to configure the host ports of the docker containers.
A second attempt at #10048, now with a much simpler implemenation.
Updates `docker/docker-compose.yml` to look for `PORT_WORDPRESS`, etc. environment variables when assigning host ports to the various docker containers.
Uses Docker Compose's [Variable Substitution](https://docs.docker.com/compose/compose-file/#variable-substitution). You can also add these environment variables to `.env` (different than `docker/.env`), and they will get picked up by `yarn docker:compose`.
The WordPress container runs on host port 80, which I'm already using on my machine. This results in the following error:
```
nukta:jetpack mdawaffe$ yarn docker:up
yarn run v1.9.4
$ yarn docker:compose …
```
=> Docker: Configurable Host Ports

modules/sharedaddy/sharing-service.php, modules/sharedaddy/sharing.js
Fixes #9678
When the Stats module is disabled, do not use any tracking pixel on pages using sharing buttons.
1. Enable Sharing and Stats.
2. Add a Facebook button to your posts.
3. Load a post and check requests in the network tab; you will see 2 requests to `pixel.wp.com`; one for regular stats and one for sharing.
4. Disable the Stats module (under the old Module settings screen)
5. Reload the post's page; you should see no `pixel.wp.com` request.
- Sharing: do not record stats if the stats module is disabled.
=> Sharing: do not record stats if the stats module is disabled.

.codeclimate.yml, .eslintrc.js, .svnignore, docs/development-environment.md, package.json, tools/build-release-branch.sh
.eslintrc without extension is deprecated (https://eslint.org/docs/user-guide/configuring#configuration-file-formats).
The changes should not conflict with current development, only make it future-proof in case linters remove support for .eslintrc without extension.
* Add .js extension to .eslintrc
* Change .eslintrc content to be a js module export, given that comments are not allowed in JSON
* Change references in other files to new file name
* No change in current testing structure
=> Development: Add extension to .eslintrc

_inc/client/components/footer/index.jsx, _inc/lib/admin-pages/class.jetpack-react-page.php, class.jetpack-network.php, class.jetpack.php, modules/publicize/ui.php
Remove translations for `Jetpack` and `WordPress.com` as we never translate them anyway.
This came up at https://github.com/Automattic/wp-calypso/pull/27190#discussion_r218363254
See https://translate.wordpress.com/translation-style-guide/ for reference.
- Check that Jetpack wp-admin menu works in single and multi installs
- Check that Publicize UI works
=> Remove translations for "Jetpack" and "WordPress.com"

class.jetpack.php
- Adds `view` files to Gutenberg tester
- Renames editor files from `jetpack-editor.*` to `editor.*`
- Add support for RTL CSS files
- Switch to `try/stylish-hello-dolly` branch in Calypso (https://github.com/Automattic/wp-calypso/pull/27241)
- From calypso folder, generate files — note to change `output-dir` to correct place:
```bash
npm run sdk -- gutenberg \
--editor-script=client/gutenberg/extensions/presets/jetpack/editor.js \
--view-script=client/gutenberg/extensions/presets/jetpack/view.js \
--output-editor-file=editor \
--output-view-file=view \
--output-dir=/absolute_path_to_your_jetpack/_inc/blocks
```
- Add these filters to your Jetpack setup, e.g. to a file in `mu-plugins` folder:
```php
add_filter( 'jetpack_gutenberg', '__return_true' );
```
These will: enable loading these …
=> Gutenberg: add view files to Gutenberg tester

modules/google-analytics/classes/wp-google-analytics-universal.php, modules/google-analytics/wp-google-analytics.php
👋from a HE. My first PR. Thanks for the feedback in advance :) 
Fixes #10091
Currently, Jetpack does not output the GA tracking code in a specific case, which can be replicated as you see on #10091 : 
* `Enable Enhanced eCommerce` option is active
* But WooCommerce is not active
1. Activate WooCommerce on a Premium or Pro site.
2. In https://wordpress.com/settings/traffic/my-site.com, activate Enable Enhanced eCommerce.
3. Deactivate WooCommerce
4. Visit the site without login as an admin. 
5. Check the HTML output and find the GA code by searching `Jetpack Google Analytics`.
Fix Bug - Do not output the Google Analytics code when `Enable Enhanced eCommerce` option is active but WooCommerce is not active
=> Fix - No GA code when `Enable Enhanced eCommerce` option is active but WooCommerce is not active

composer.json, composer.lock
* Bumps WPCS to 1.1.0
* Updated composer.json with `composer update`
* Verify composer-based dependencies are working (phpcs, etc)
* None yet.
=> Bump WPCS to 1.1.0 and update composer.lock to latest

modules/comments/admin.php, modules/comments/base.php, modules/comments/comments.php
@see #10168
Since comments also rely on checking for `wordpress`, I added exceptions to the rules.
=> Comments: PHPCS Fixes.

modules/widgets/gravatar-profile.php
#10170 introduced this issue when we automatically fixed that instance of the "WordPress" string.
Coding style fixes.
=> Gravatar Widget: do not autocapitalize this instance of WordPress.

modules/contact-form/admin.php, modules/contact-form/grunion-contact-form.php, modules/contact-form/grunion-editor-view.php, modules/contact-form/grunion-form-view.php
Automated PHPCS fixes.
@see #10168
Coding standards fixes only.
=> Contact Form: automated PHPCS fixes.

tools/builder/admin-css.js
Up until now, no rtl files or min files were generated when running `yarn build`.
This caused issues on RTL sites, but also in other places where we look for the file,
like in the work we are doing in #10102
Apply this branch, run `yarn build`, and check for 2 new minified files and an RTL file under `modules/shortcodes/css/`.
You can also check that the slideshows look good on a site using an RTL language.
Shortcodes: ensure we build minified and RTL stylesheets for slideshows.
=> Shortcodes: ensure that we generate RTL & min files for slideshows

modules/wordads/wordads.php
Discovered during the great PHPCBF hunt. Two `!`s are functionally the same as a `(bool)` and should be a tad bit faster.
* Use type casting instead of a `!!`
* None
n/a
=> WordAds: Cast a bool instead of using two not operators

modules/shortcodes/mailchimp.php, tests/php/modules/shortcodes/test_class.mailchimp.php, to-test.md
Fixes #10104
Mailchimp updated their newsletter embed code, and the old one does not work anymore.
This change matches the new format, and updates our test accordingly.
Note that this also reverts the changes introduced in #8547, since they do not appear necessary anymore. Mailchimp fixed that issue on their end.
Try adding Maichimp shortcodes to your site in different ways:
- As an admin, add the new embed code to a new post. 
- As a contributor, add the new embed code to a new post and save your draft. Watch the code convert into a shortcode. 
- Make sure the newsletter pop up appears on your site when you view the post. 
- Make sure no JavaScript errors appear in your browser console.
Here is an example embed code you can add to your post:
```html
<script type="text/javascript" …
```
=> Shortcodes: update MailChimp shortcode to match new format.

json-endpoints.php, json-endpoints/class.wpcom-json-api-bulk-update-comments-endpoint.php
Contributes to fixing https://github.com/Automattic/wp-calypso/issues/20299
WPCOM diff: D13678-code
I'm not exactly sure how to do this from a Fusion standpoint.
I've (accidentally) created the WPCOM diff first, which has been thoroughly reviewed and approved, and then realized that it contains: 1 file already synced, and 1 completely new file.
What would be the best practice here?
This diff proposes the introduction of several new bulk endpoints:
`POST /sites/{site}/comments/status`: update multiple comments statuses (also useful because currently we do this with a frontend loop).
`POST /sites/{site}/comments/delete`: delete multiple comments or, in alternative, all spam or trash comments.
Most of the logic here is inspired by how Core handles all of this: …
=> Comments: Add Bulk Update/Delete Endpoint

class.jetpack.php
From pafL3P-1X-p2
> [When] Jetpack is disconnected […], blocks will not show up or work […] previously added blocks will behave as if Jetpack was deactivated.
Do not register Gutenberg blocks when Jetpack is disconnected. This is the same behavior as it Jetpack were deactivated.
Should we enable the blocks in Dev Mode?
- Connect a new Jetpack site with this branch, Gutenberg, and the Gutenberg Jetpack blocks
- Open the Gutenberg editor and confirm you can add an existing block `/markdown`. Create the block and save the draft.
- Return the the draft. You should now see a Classic Editor block instead of the Jetpack block.
=> Gutenberg: Disable Jetpack blocks when disconnected

class.jetpack.php
Add additional dependencies for Jetpack Gutenberg blocks.
Adding these early on to avoid needs for switching away from a stable version of Jetpack when testing blocks in future. None of the currently shipped versions of blocks (Markdown or Tiled Gallery) use these dependencies yet but we have other blocks in the works.
- `lodash`: many of [our blocks](https://github.com/Automattic/wp-calypso/tree/e29640763f230188febbacbbde61c7c13c2b35b8/client/gutenberg/extensions) are already depending on Lodash. So far this has worked because other dependencies depend on it as well, but it's good to be explicit about these.
- `wp-hooks`: gives access to block filters and actions. Likely going to be needed with Tiled Gallery block https://github.com/Automattic/wp-calypso/pull/27369
- `wp-api-fetch`: used …
=> Gutenberg: update editor script deps

modules/theme-tools/featured-content.php
Add array_unique for the post_types list.
array_merge appends arrays, and since post is set as the default, it means that for many post will be listed twice.
For example in Canard (an Automattic theme) where post_type is set to post and page the post_type will become array( 'post', 'post', 'page' )
https://github.com/Automattic/themes/blob/b8444897830573b47505a19623e1f3459a45aac4/canard/inc/jetpack.php#L22
By filtering the list we prevent the register_taxonomy_for_object_type from being called multiple times for the same post type, and we ensure the post_types are listed once when we later call get_posts.
To be honest I don't imagine it will make a huge amount of difference to anything but I was debugging a featured content issue in my theme and saw this and it confused me. This …
=> Clean up duplicate post types in featured content

class.jetpack.php
Fixes #10009
Do not load the authors and Social Icons widgets' stylesheets separately, whether the widget is on the page or not; instead, load it as part of the `jetpack.css` file.
0. Make sure `SCRIPT_DEBUG` is not set to true on your site. 
1. Load your site and make sure the `modules/widgets/social-icons/social-icons.css` and `modules/widgets/authors/style.css` files are not loaded. 
2. Add the 2 widgets to your site, and make sure they are styled properly.
CSS Concatenation: add Authors and Social Icons widgets to concatenated styles.
=> CSS Concat: add authors and Social Icons widgets to concat styles.

modules/sharedaddy/sharedaddy.php
Fixes #10150
Until now, we only saved post meta when saving a post, not when saving an attachment.
This problem does not exist with Likes as we already hook into `edit_attachment` there.
1) Go to WP-Admin > Media > Open an image
2) Hit `edit more details` option
3) Disable sharing buttons from the right sidebar
4) Save settings
5) Make sure your settings are saved properly.
Sharing: allow saving sharing button options on media edit page as well.
=> Sharing: save post meta on the media edit screen as well.

class.jetpack.php, tests/php/_inc/lib/test_class.rest-api-authentication.php
WordPress.com's D18560-code allows arbitrary `Content-Type`s and removes the need to base64-encode files before forwarding them to Jetpack.
Related to #9965
* Remove Jetpack's Content-Type restrictions when handling a forwarded REST API request.
Testing from the WordPress.com side at D18560-code.
For Jetpack, `yarn docker:phpunit --filter=WP_Test_Jetpack_REST_API_Authentication`
=> REST API: Remove Content-Type Constraints

modules/sitemaps/sitemap-builder.php
Fixes #8138
* Before adding an image to the image sitemap, check the post status. When an attachment is checked for status, the following is returned:
1. If the image is private, it will be returned as private. Not included in the sitemap.
2. If the image is unattached, it is assumed published. Included in the sitemap.
3. Otherwise, it will assume the parent status. Any status other than "publish" is not included in the sitemap.
* Create a new draft post
* Upload a new image to that post. Do not reuse an existing image.
* Save as draft.
* Let the sitemap regenerate. Check the image sitemap.
* Notice the image is included and the link is the parent's permalink (?p=123).
* This page will 404 if not logged in, as a draft.
* Apply patch.
* Try again. Image not included.
* No longer add images …
=> Sitemaps: Do not include images not published

_inc/client/components/forms/styles.scss, _inc/client/state/site-verify/actions.js, _inc/client/state/site-verify/reducer.js, _inc/client/traffic/style.scss, _inc/client/traffic/verification-services.jsx, _inc/client/traffic/verification-services/google.jsx
Fixes #10141
Requires server patch D18402-code
* Do not verify the site on page load, even if the user already has a google site verification token, wait for the user to click on the "Auto verify with Google" button
* Display an error notice on request error
* Revamp of the google site verification UI, props to @jeffgolenski for his design proposal!
- Go to `/wp-admin/admin.php?page=jetpack#/traffic` (Jetpack > Settings > Traffic) and scroll down to Site Verification
- Try clicking on "Auto verify with Google", authenticate with Google and make sure your site is verified, go to https://www.google.com/webmasters/verification/home?hl=en&authuser=2 and make sure your site is in the list. Go to https://search.google.com/search-console and make sure your site is there as well
- You should see …
=> Improve Google Verification Service integration

_inc/client/traffic/verification-services/google.jsx
**DO NOT MERGE**
Includes changes from #10143 and should be rebased and merged after
Adds a disclaimer to the Google Site Verification that warns users that connecting to Google Search Console will cause emails to be sent to them.
**Before**
**After**
* Load up a Jurassic.Ninja Live Branch [here](https://jurassic.ninja/create?jetpack-beta&branch=update/google-site-verification-ui&shortlived&wp-debug-log)
* Connect to WordPress.com
* Navigate to https://[my-site].jurassic.ninja/wp-admin/admin.php?page=jetpack#/traffic
* Scroll to the "Site verification" pane
* Connect your site to Google via the "Auto-verify with Google" button
* Verify that the screen now is nearly identical with the "After" image above
=> Update Google Site Verification UI

json-endpoints/class.wpcom-json-api-bulk-update-comments-endpoint.php
A late commit to #9990 changed the behaviour of the Bulk Update Comment Status endpoint when the request is missing the `status` parameter.
https://github.com/Automattic/jetpack/pull/9990/commits/e046d50d222239e921fcc153833cec2e37ff5f69#diff-e0f9cad9828665a0ca86b565495efe3fR93
The expected response would be a `WP_Error` complaining about the empty status.
But, by adding that `isset`, we effectively skipped the callback (where the `WP_Error` would have been thrown), and returned a generic empty response, which, even if not strictly incorrect, it doesn't give the consumer of the API any useful information.
* Replaces an `else if` with an `else` so that the Bulk Update Comment Status endpoint callback is always executed.
* Make sure that the `$input['status']` param is only used if `isset`, …
=> Comments: Fix missing status param error

_inc/client/traffic/verification-services/google.jsx
Slight change to the wording of the Search console option description
New wording
Old wording
=> Refine wording of search console integration

sync/class.jetpack-sync-actions.php, tests/php/sync/test_class.jetpack-sync-integration.php
This PR removes the invocation of Jetpack_Sync_Actions::do_initial_sync() when Jetpack is updated. This will prevent resources from being overwhelmed when a new version of Jetpack is deployed to many sites concurrently.
Follow the instructions at PCYsg-hnH-p2 to observe what is synced in real time. Ensure there is no full sync when you update Jetpack.
=> Jetpack Sync: Prevent full sync when Jetpack is updated

modules/shortcodes/gist.php, tests/php/modules/shortcodes/test_class.gist.php
* Return `amp-gist` from a `gist` shortcode or oEmbed when in an AMP response.
1. Install the [AMP plugin](https://github.com/Automattic/amp-wp).
2. Add a `gist` shortcode or gist oEmbed URL to a post. Then view that post in AMP.
3. View the AMP version of the post.
Example content:
```html
oEmbed: Full gist:
https://gist.github.com/sebastianbenz/1d449dee039202d8b7464f1131eae449
oEmbed: Linking to a file via in a Gist:
https://gist.github.com/sebastianbenz/1d449dee039202d8b7464f1131eae449#file-sw-html
oEmbed: Linking to file without username in URL.
https://gist.github.com/1d449dee039202d8b7464f1131eae449#file-sw-html
Example from WordPress.com docs:
[gist https://gist.github.com/2314628 /]
Second example from WordPress.com docs:
[gist]2314628[/gist]
```
Originally proposed in …
=> AMP: Render amp-gist from gist shortcode/oEmbed during AMP requests

_inc/client/traffic/verification-services/google.jsx
Follow up for https://github.com/Automattic/jetpack/pull/10143
We already have the following events triggered on the `Jetpack > Settings > Traffic` page:
- `jetpack_site_verification_google_auto_verify_click` upon clicking on the "Auto-verify with Google" button
- `jetpack_site_verification_google_manual_verify_click` upon clicking on the "Manually verify with Google" button
- `jetpack_site_verification_google_manual_verify_save` upon clicking on the "Save" button
This PR adds the following ones:
- `jetpack_site_verification_google_verify_success` upon receiving a successful verification response from the server
- `jetpack_site_verification_google_verify_error` upon receiving a failed verification response from the server
- `jetpack_site_verification_google_authenticate` upon opening the …
=> Add tracks events for google site verification result

modules/shortcodes/youtube.php, tests/php/modules/shortcodes/test_class.youtube.php, tests/php/sync/test_class.jetpack-sync-posts.php
See #10201 
`set_url_scheme` would have prevented issues for the most part with attempting to load a http variant on a https site, but there's no reason not to just use https always for YouTube.
* Use https urls for YouTube.
* n/a
n/a
=> YouTube: HTTPS everywhere

_inc/client/rest-api/index.js, _inc/client/state/site-verify/actions.js, _inc/client/state/site-verify/reducer.js, _inc/client/traffic/verification-services/google.jsx, _inc/lib/class.core-rest-api-endpoints.php
Fixes #10217 
Fixes #10218
Requires D18820-code
* Never use existing Google Site Verification tokens when verifying a site, always request external access
**Setup**
* Apply D18820-code
* Point Jetpack to Sandbox
* Set `public-api.wordpress.com` to your sandbox IP
**Testing**
1. Go to Jetpack -> Settings -> Traffic
2. Click "Verify with Google"
3. You will be prompted to authorize the connection in a popup
4. The UI should change to tell you that your site was verified
5. Click the "Edit" button, clear the field, and click "Save"
6. Click the link to the Google Search Console and Un-verify the site  
7. Return to Jetpack -> Settings -> Traffic
8. Click "Verify with Google" again
9. Confirm that the same popup from top 3 appears, and that you can chose a different Google Account
=> Always Chose Google Account When Verifying

_inc/client/components/forms/styles.scss, _inc/client/traffic/style.scss, _inc/client/traffic/verification-services/google.jsx
Fixes #10219
* Improve styles for Site Verification on small devices
Thanks to @jeffgolenski for helping on this!
- Visit `Jetpack > Settings > Site Verification` on a device with a screen less than 660px wide (or emulate it with chrome).
- Check that the design looks good
- Improve style of the site verification section for mobile devices
=> Improve style of site verification section for mobile devices

class.jetpack-debugger.php
Removed Fatal error when a plugin removed the full sync module on the jetpack debug page.
```
Fatal error: Uncaught Error: Call to a member function get_status() on boolean in /var/www/html/wp-content/plugins/jetpack/class.jetpack-debugger.php on line 120
```
The plugin that removes the module looks like 
```
/*
* Plugin Name: Remove Jetpack's Full Sync Module
* Author: Automattic
* Version: 1.0
* License: GPL2+
*/
add_filter('jetpack_sync_modules', 'jetpack_stop_remove_full_sync_module' );
function jetpack_stop_remove_full_sync_module( $modules ) {
return array_diff( (array) $modules, array( 'Jetpack_Sync_Module_Full_Sync' ) );
}
```
* Make the debugger less prone to fatal errors. By checking that the full sync module is available. 
1. Add the plugin and activate it by coping and pasting …
=> Jetpack Debuger: Remoeves fatal error when jetpack full sync is disabled

tools/deploy-to-svn.sh
Fixes #10208
* Update to the SVN script to reflect proper location within the svn dir.
* from `branch-6.6` in the JP root, run `./tools/deploy-to-svn.sh HEAD` (it won't actually deploy, so safe to test as such).
* none
=> SVN Deploy Script: Use correct path

modules/masterbar/tracks-events.js
Adds click tracking to the new Activity link found in the masterbar.
* 
1. Activate the masterbar. 
2. Click the new Activity Log link in the master bar. 
Do we send the new track click event?
@dereksmart  and suggestions how to see the events show up in tracks?
=> Masterbar: Add activity tracking

modules/contact-form/grunion-contact-form.php, sync/class.jetpack-sync-defaults.php, tests/php/modules/contact-form/test_class.grunion-contact-form.php, tests/php/sync/test_class.jetpack-sync-posts.php
This PR syncs structured data submitted to feedback forms so that it can be used downstream by the Activity Log.
Please follow the instructions here so that you can view live sync data: PCYsg-hnH-p2
and ensure that the data for all of the fields you add to a feedback/contact form are synced via the `added_post_meta` action with the `_feedback_add_fields` key.
New phpunit tests ensure that this meta is added when a feedback form is submitted and that the data is synced when it is added.
=> Jetpack Sync: Sync feedback keys and values

_inc/client/traffic/verification-services/google.jsx
Fixes #10227
* Automatically unset google verification token on page load when server failed to unverify site.
We want unverify the site when user has remove the property from their search console
- Verify your site with googl using the auto-verify feature
- Go to https://search.google.com/search-console/welcome select your site on the left panel, go to settings and remove property
- Refresh the page, you should see your settings updated (the token is being removed) and your site being unverified
- Check that your site is unverified by visiting those 2 links
- https://search.google.com/search-console/welcome
- https://www.google.com/webmasters/verification/home
- Automatically unverify site if user removed it from google search console
=> Unset google meta tag on unverify error

_inc/client/traffic/verification-services.jsx
Fixes #10245
* This PR fixes a bug related to the token fields showing undesired value changes on save.
- Go to `Jetpack > Settings > Traffic > Site Verification`
- Enter verification token values for several services
- Save settings
- Edit one value and make sur the other values remain unchanged
- Fix inconsistent save button behaviour for Site Verify
=> Make sure fields for other services don't change when we edit and save a verification token
